### ISSUE TITLE
Naive Question of Using. Recursive Loop

### ISSUE THREAD

**Issue by EmmaHansson** [mobxjs/mobx#1004]
I use react + aspnet core + mobx + axios (to make REST).

I am planning to make a progress bar showing while REST query is executing.
I created an AppState:
```
import { observable, computed, action } from 'mobx';

export default class AppState {

    @observable inProgress: boolean = false;

    public progressOn() {
        this.inProgress = true;
    }

    public progressOff() {
        this.inProgress = false;
    }

    @computed
    get inProgressString(): string {
        return this.inProgress.toString();
    }
}
```

In my router I initialized everything I need:
1. created AppState object
2. In Axios intercepters I tried to make an action call:
```

        axios.interceptors.request.use(
            (request) => {
                appState.progressOn();
                console.log('app state: ' + appState.inProgress.toString());
                console.log('request');
                return request;
            },
            (error) => {
                return Promise.reject(error);
            }
        );

        axios.interceptors.response.use(
            (response) => {
                console.log('response');
                appState.progressOff();
                console.log('app state: ' + appState.inProgress.toString());
                return response;
            },
            (error) => {
                const originalRequest = error.config;
                if (error.response.status === 401 || error.response.status === 403) {
                    browserHistory.push("/"); // auth page
                } else {
                    browserHistory.push("/error");
                }
            }
        );
```
So for each request I will change a state ON and when I will have a response I will change it OFF. Seems logically good as idea.

In my Layout.tsx I try to render
```

export interface IProps {
    body: any,
    appState: AppState
}

@observer
export class Layout extends React.Component<IProps, void> {
    constructor(props: IProps) {
        super(props);
    }

....
```

and in render() I use renderBody() to determine to show or not body:
```

renderBody() {
        if (!this.props.appState.inProgress) {
            return <div>
                {this.props.body}
            </div>;
        }
    }

```

Sure instead of hiding a body I can make progress bar showing in future.
But, I have a magic issue: I have infinite REST GET request after a child component call a axios REST GET.

**Comment by urugator** [comment]
> I have infinite REST GET

Can you be more specific? Is it being send over and over? Or the request is not send at all? Are the interceptors called?

Post the child component, which calls the request and how it's being used.

Unrelated: Put @action on methods modifing the state (progressOn/Off).

Only problem I can currently imagine: component mounting -> GET -> state modified -> re-rendering -> component mounting -> GET -> ....

**Comment by EmmaHansson** [comment]
Child Component is rather big and calls a axios REST GET. And it causes calling axios interseptors for request I described above.

Seems it's logical problem. And not pleasure.
