### ISSUE TITLE
Observables not working

### ISSUE THREAD

**Issue by gate3** [mobxjs/mobx#1005]
Hi, wonderful library here. I am using mobx without decorators, but the observables are not working in my observer classes. Here is what i did

extendObservable(this, {
  isDataLoaded:false,
functionA:action(this.funcA)
})

funcA(){
//perform promise action
this.isDataLoaded = true
}

And then in the view i am watching the isDataLoaded for changes in order to display or hide my loading bar. I can see the data from the promise return in the console but the observable does not change. Please help

**Comment by vstlouis** [comment]
Did you wrap your React component in observer ?

**Comment by gate3** [comment]
Yes i did. Like this

const componentName = observer(
   class componentName extends Component{

**Comment by vstlouis** [comment]
the context of what "this" is in your funcA function is more than likely not what you think it is, meaning that `this.isDataLoaded` isn't actually actually pointing to your mobx observable but something else. Could you put your whole class in a jsbin or here? =]

**Comment by gate3** [comment]
i will put it here.. when i don't use this, it doesn't recognize the observable variable. Also i don't have any other variable by that name if that's what you are implying

**Comment by gate3** [comment]
What i also noticed is this. Anytime i assign value to an observable, the script stops running and it doesn't show any errors.

**Comment by gate3** [comment]
```
import { action, extendObservable } from 'mobx';
import { genericAction } from './genericAction';
import EmitterStore from './EmitterStore';

class searchStore extends genericAction {
    constructor() {
        super(null);
        this.emitter = EmitterStore.getEmitterObject();
        this.p = this.ParseObjectFactory();

        extendObservable(this, {
            isDataLoaded:false,
            doctorData:[],
            get getisDataLoaded(){
                return this.isDataLoaded
            },
            fetchDoctorBySpecialization:action((spec)=>{
                var DoctorInfo = this.p.Object.extend("DoctorInfo");
                var query = new this.p.Query(DoctorInfo);
                query.equalTo("specialization", spec);
                this.getFindPromise(query).then(
                    (s)=>{
                        //this.isDataLoaded = true
                        //console.log(s);
                        this.doctorData = s;
                        this.emitter.emit('searchResults:new',{status:true,obj:s}); 
                    },
                    (e)=>{
                        //console.log(e)
                        this.emitter.emit('searchResults:new',{status:false,obj:e}); 
                    }
                )
            })
        });
    }

    /*fetchDoctorBySpecialization(spec){
        var DoctorInfo = this.p.Object.extend("DoctorInfo");
        var query = new this.p.Query(DoctorInfo);
        query.equalTo("specialization", spec);
        this.getFindPromise(query).then(
            (s)=>{
                //this.isDataLoaded = true
                //console.log(s);
                this.emitter.emit('searchResults:new',{status:true,obj:s}); 
            },
            (e)=>{
                //console.log(e)
                this.emitter.emit('searchResults:new',{status:false,obj:e}); 
            }
        )
    }*/
}

var store = new searchStore();
export default store;
```

**Comment by gate3** [comment]
Funny thing is that the observable is actually seen as an observable, but it doesnt update the UI and assigning a value to it just makes everything that comes after it stop running.
![image](https://cloud.githubusercontent.com/assets/3597437/26273303/51616cc2-3d25-11e7-8eb0-06347686ec1e.png)

**Comment by vstlouis** [comment]
Your example should work..
https://jsbin.com/kahojoximi/edit?js,console,output

Also whats the error in your console?

**Comment by gate3** [comment]
No errors

**Comment by gate3** [comment]
I can see in your example you used decorators, i am using create-react-app and it doesn't allow decorators and i do not wish to eject

**Comment by vstlouis** [comment]
In the screenshot you sent there was an error there (might be unrelated of course). anyway you should add out mobxDevtools to your app

**Comment by vstlouis** [comment]
You can use create-react-app with decorators.. See: https://github.com/kitze/custom-react-scripts/tree/master/packages/react-scripts

Also I'm using extendObservable in the store and not decorators there. Just showing you that it works.

**Comment by gate3** [comment]
ok thanks for the link. Can you show me how to use it with an existing project?

**Comment by vstlouis** [comment]
Not 100% sure how to do this as I have not ported an existing application. but it should take ~5 minutes.

simply `create-react-app my-app --scripts-version custom-react-scripts`
move all your files to that directory
npm install any dependencies you use
modify the `.env` and turn on decorators
run your app

**Comment by vstlouis** [comment]
Hope you resolve your issue, sorry I couldn't be of more help =]

**Comment by gate3** [comment]
hi, thanks a bunch. Turns out I needed to use 

> runInAction 

since the data is coming from a promise.
