### ISSUE TITLE
[Question] Is any way to spy particular observable ?

### ISSUE THREAD

**Issue by IIIristraM** [mobxjs/mobx#1007]
Hello,

I want to track the scope where observable object was changed. I want to be insured that my store is changed only inside particular functions, avoiding unexpected changes that violate architecture.

Somthing like

```
// middleware
function transaction() {
  let isInTransaction = false;

  if (DEV_ENV) {
    spy((event) => {
      if (!event.type) return;

      if (event.type.match(/(update|add|delete)/) && !isInTransaction) {
        console.error('STORE CHANGED OUT OF TRANSACTION', event);
      }
    });
  }

  return (cb, store) => {
    isInTransaction = true;
    runInAction(() => {
      cb(store);
    });
    isInTransaction = false;
  };
}
```

The problem is the store is not the only observable in application, and I need some way to detect whether the change was in store or not.

**Comment by urugator** [comment]
You can filter the spy events with `event.object === storeToSpy`, obviously it won't work for nested observables - you would have to do the matching against the whole object graph.

**Comment by IIIristraM** [comment]
It probably wouldn't work for "delete" event as far as deleted object is no longer the part of the graph
