### ISSUE TITLE
Suggestion: Add IReadOnlyObservableValue

### ISSUE THREAD

**Issue by hepiyellow** [mobxjs/mobx#1012]
Hi,

It seems to me that a basic readonly observable is missing from mobx.
Maybe this exists and I didn't find it.
I was looking at IComputedValue, but it has a setter.
I am looking for something like:
```
interface IReadOnlyObservableValue<T> {
    get(): T;
    observe(listener: (newValue: T, oldValue: T) => void, fireImmediately?: boolean): Lambda;
}
```

This of course is just a TypeScript interface, it doesn't really make the observable immutable. But it would be a useful interface.

I saw this discussion: https://github.com/mobxjs/mobx/issues/925
but what I am talking about it much more simple.

**Comment by mweststrate** [comment]
Is your goal to make it 

1. readonly: Then use a computed without a setter. Or just an observable value, and `intercept` the any modification but just throwing
2. or: immutable: Then just don't make it observable. Immutable observables are a contradiction :)

**Comment by hepiyellow** [comment]
My goal is (1) to make it a read-only observable.
Something similar to JAVAFX Observables, which have for example an `ReadOnlyIntegerWrapper` which is an observable, on which you can call `wrapper.getReadOnlyProperty()` which will return an observable which can be read (by `get()`) and can be listened on (`addListener()`). 
So you can modify the wrapper, and the listeners of the read-only property will get notified.

I agree in Javascript such a wrapper should intercept any modification (since you can't really block it at compile time). And I think a proper interface would be useful instead of the IComputedValue interface which is not appropriate for this case.

So first step would be having the proper interface that users can use to semantically state their intentions.
2nd step would be writing this wrapper, which would be nice if it is a part of Mobx, so I wouldn't have to use my own.

**Comment by mweststrate** [comment]
There is a good pattern to achieve that in general:

```javascript
class Test {
   private @observable _temperature = 10
   get temperature() {
       return this._temperature
   }
}
```

Should do the trick. I don't think there is reason to expand the api for that, especially since the moment of 'when is the thing not read only so that it can be modified?' would be tricky
