### ISSUE TITLE
Is there any concept called Global variables used across the application?

### ISSUE THREAD

**Issue by kamarajuPrathi** [mobxjs/mobx#1014]
So that i need not inject store everyPlace ..?Is there a way i can defined global variable

**Comment by mattruby** [comment]
That's not really a mobx issue.  Just reference your singleton directly if
you don't want to use provide and inject. Or pass it on down via props, but
that's the same as provide in your case. Testing will be more challenging
if you directly import.

**Comment by mweststrate** [comment]
If you create an observable and put it into a global variable that will just work. As pointed out by @mattruby , might bite you during testing though, as holds for any global variable.
