### ISSUE TITLE
ContainerComponent vs Provider?

### ISSUE THREAD

**Issue by sheam** [mobxjs/mobx#1015]
I have a newb question. Let me know if there is a better place to post than her in your issues.

I have a common need to load a specific object from DB often. But what I do with is different, editing, viewing, approving, deleting, etc. 

I have a DocService class that handles all DocumentCrud. It is a pure class with no React or Mobx present.

For all the various actions, the document is loaded the exact same way. I am wondering what is the best way to reuse that? Either a container component that loads and renders the appropriate action, or just wrap the action component in a  provider?

Here is the Container method I came up with with example View/Edit pages.

    class DocumentService
    {
        public get(id: number): Promise<MyDocumentType>
        {
            //fetch
            return new Promise((resolve) =>
            {
                setTimeout(() =>
                {
                    resolve(new MyDocumentType());
                }, 1000);
            });
        }
    }
    
    class MyDocumentType
    {
        title: string;
    }
    
    export interface IDocLoaderContainerProps
    {
        docService: DocumentService;
        documentId: number;
        action: string;
    }
    
    @observer
    export class DocLoaderContainer extends React.Component<IDocLoaderContainerProps, undefined>
    {
    
        @observable
        private _isLoading: boolean;
    
        @observable
        private _document: MyDocumentType;
    
        public constructor(props: IDocLoaderContainerProps, state: any)
        {
            super(props, state);
            this._isLoading = false;
            this._document = null;
        }
    
        @action
        private startLoading(): void
        {
            this._isLoading = true;
        }
    
        @action
        private loadingComplete(d: MyDocumentType): void
        {
            this._isLoading = false;
            this._document = d;
        }
    
        @action
        private loadingFailed(e: any): void
        {
            this._isLoading = false;
            this._document = null;
            console.log(e);
        }
    
        public componentDidMount(): void
        {
            this.startLoading();
            this.props
                .docService
                .get(this.props.documentId)
                .then((d) => this.loadingComplete(d))
                .catch((e) => this.loadingFailed(e));
        }
    
        public render(): JSX.Element
        {
            if(this._isLoading)
            {
                return (<span className="loading-message">loading...</span>);
            }
    
            if(this.props.action == 'edit')
            {
                return <DocumentEditor document={this._document} />
            }
            return <DocumentView document={this._document} />
        }
    }
    
    export class DocViewPageWithContainer extends React.Component<undefined, undefined>
    {
        private _docService = new DocumentService();
    
        public render(): JSX.Element
        {
            const docIdFromRoute = 5;
            return (
                <div>
                    <h1>Viewing Document</h1>
                    <DocLoaderContainer docService={this._docService} documentId={5} action='view'/>
                </div>
            );
        }
    }
    
    export class DocEditPageWithContainer extends React.Component<undefined, undefined>
    {
        private _docService = new DocumentService();
    
        public render(): JSX.Element
        {
            const docIdFromRoute = 5;
            return (
                <div>
                    <h1>Editing Document</h1>
                    <DocLoaderContainer docService={this._docService} documentId={5} action='edit'/>
                </div>
            );
        }
    }

Switching on the 'action' parameter seems weird. I would think there is a better way to do this.

Here is an attempt to solve this issue using a provider:

    export class DocumentStore
    {
        @observable
        public isLoading: boolean;
    
        @observable
        public document: MyDocumentType;
    
        private _docService: DocumentService;
    
        public constructor()
        {
            this._docService = new DocumentService();
            this.load();
        }
    
        @action
        private docLoadComplete(d: MyDocumentType): void
        {
            this.isLoading = false;
            this.document = d;
        }
    
        private load(): void
        {
            const idToLoad = 5; //???? How do I get this?
            this._docService
                .get(idToLoad)
                .then((d) => this.docLoadComplete(d))
                .catch((e) => { throw e });
        }
    }
    
    export class DocViewPageWithProvider extends React.Component<undefined, undefined>
    {
        private _docStore = new DocumentStore();
    
        public render(): JSX.Element
        {
            const docIdFromRoute = 5;
            return (
                <Provider documentStore={this._docStore}>
                    <h1>Viewing Document</h1>
                    <DocumentView />
                </Provider>
            );
        }
    }
    
    export class DocEditPageWithProvider extends React.Component<undefined, undefined>
    {
        private _docStore = new DocumentStore();
    
        public render(): JSX.Element
        {
            const docIdFromRoute = 5;
            return (
                <Provider documentStore={this._docStore} documentId={5}>
                    <h1>Editing Document</h1>
                    <DocumentEdit />
                </Provider>
            );
        }
    }

The provider version seems cleaner, but I also feel like maybe there is still a better way to do this?

(Bonus points for answers in TypeScript.)

**Comment by urugator** [comment]
Static - HOC solution:
```javascript
function Wrap(Component) {
  return DocLoaderContainer extends React.Component<IDocLoaderContainerProps, undefined>
  {
    @observable
    private _isLoading: boolean;

    @observable
    private _document: MyDocumentType;

    public constructor(props: IDocLoaderContainerProps, state: any)
    {
        super(props, state);
        this._isLoading = false;
        this._document = null;
    }

    @action
    private startLoading(): void
    {
        this._isLoading = true;
    }

    @action
    private loadingComplete(d: MyDocumentType): void
    {
        this._isLoading = false;
        this._document = d;
    }

    @action
    private loadingFailed(e: any): void
    {
        this._isLoading = false;
        this._document = null;
        console.log(e);
    }

    public componentDidMount(): void
    {
        this.startLoading();
        this.props
            .docService
            .get(this.props.documentId)
            .then((d) => this.loadingComplete(d))
            .catch((e) => this.loadingFailed(e));
    }

    public render(): JSX.Element
    {
        if(this._isLoading)
        {
            return (<span className="loading-message">loading...</span>);
        }        
        return <Component document={this._document} />        
    }
  } 
}

// Usage:
const WrappedDocumentEditor = Wrap(DocumentEditor);
const WrappedDocumentView = Wrap(DocumentView);
```

Dynamic - props solution
```javascript
@observer
export class DocLoaderContainer extends React.Component<IDocLoaderContainerProps, undefined>
{

    @observable
    private _isLoading: boolean;

    @observable
    private _document: MyDocumentType;

    public constructor(props: IDocLoaderContainerProps, state: any)
    {
        super(props, state);
        this._isLoading = false;
        this._document = null;
    }

    @action
    private startLoading(): void
    {
        this._isLoading = true;
    }

    @action
    private loadingComplete(d: MyDocumentType): void
    {
        this._isLoading = false;
        this._document = d;
    }

    @action
    private loadingFailed(e: any): void
    {
        this._isLoading = false;
        this._document = null;
        console.log(e);
    }

    public componentDidMount(): void
    {
        this.startLoading();
        this.props
            .docService
            .get(this.props.documentId)
            .then((d) => this.loadingComplete(d))
            .catch((e) => this.loadingFailed(e));
    }

    public render(): JSX.Element
    {
        if(this._isLoading)
        {
            return (<span className="loading-message">loading...</span>);
        }
        return this.props.render({ document: this._document })         
    }
}

// --- Usage ---
const renderView = props => <DocumentView {...props}>;
<DocLoaderContainer render={renderView}>

const renderEditor = props => <DocumentEditor {...props}>;
<DocLoaderContainer render={renderEditor}>
```

**Comment by sheam** [comment]
Thank you for this. I tried both, and tended to like it better. I appreciate the multiple options.

No for some reading up on dealing with forms and saving.

Cheers.
