### ISSUE TITLE
autorun dependencies

### ISSUE THREAD

**Issue by fehergeri13** [mobxjs/mobx#1016]
Hello!

I have an issue about autorun, that it triggered, but it should not. This causes a `bundle.js:35937 Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[Autorun@7]` 

Is it possible to define the dependencies of autorun? Is it possible to catch the causer of autorun? for example the changed value?

**Comment by fehergeri13** [comment]
Here is a very simple example, which I have

```
import React, {Component} from 'react';
import {observer} from 'mobx-react';

import {computed, observable, toJS, autorun, runInAction} from 'mobx';

@observer
class Tester extends Component {

    @observable data = observable.map();

    constructor() {
        super();

        autorun(() => {
            console.log('autorun');

            const {props = {}} = this;
            const {
                onChange = () => {
                }
            } = props;

            onChange(toJS(this.data))
        });
    }

    componentDidMount() {
        console.log('componentDidMount');
        runInAction(()=>{
            this.data.set('data', observable.array());
            this.data.get('data').replace(this.props.data);
        });
    }

    componentWillReceiveProps(nextProps) {
        console.log('componentWillReceiveProps');

        if (JSON.stringify(this.props.data) !== JSON.stringify(nextProps.data)) {
            console.log('componentWillReceiveProps inner');

            this.data.replace(nextProps.data);
        }
    }

    render() {
        console.log('render tester');
        return <h1>Hello Mobx</h1>
    }
}

@observer
export default class RenderThisWillCauseStackOverflow extends Component {

    data = observable.map();

    @computed get computedData() {
        console.log('computed data calc');
        return this.data.get('data');
    }

    onChange(data) {
        console.log('onChange');
        this.data.set('data',data);
    }

    render() {
        console.log('render tester2');
        return(
            <div>
              tester2
                <Tester
                    data={toJS(this.computedData)}
                    onChange={data => this.onChange(data)}
                />
            </div>
        )
    }
}
```

The problem is, that the autorun is called, however nothing is changed inside the Tester component, only received new props, but they are deep equal.

**Comment by urugator** [comment]
> Is it possible to catch the causer of autorun? 

`extras.getDependencyTree(autorunDisposer)`

**Comment by mweststrate** [comment]
Not sure if related, but note that you pass a fresh onChange function to the component each time the parent changes. Not sure if `onChange` is intended to be changed over time, but using a local function instead of an inline arrow function *and* picking onChange from the props outside the autorun might improve things.

**Comment by fehergeri13** [comment]
Thanks. By the way why is it running into an endless recursive loop?

**Comment by mweststrate** [comment]
@fehergeri13 your constructor of `Tester` calls `onChange` immediately, causing the RenderThisWillCauseStackOverflow to update it's data, to render and pass new data to Tester, which will fire `onChange` again.... etc.
