### ISSUE TITLE
 'Mobx' reaction bug in StackNavigatior of 'react-navigation' 

### ISSUE THREAD

**Issue by AlphaDu** [mobxjs/mobx#1021]
I'm using StackNavigator,and There are two page A and B。

In page B,there is a  function which is passed to 'mobx reaction' just like 'reaction(()=> var1,()=>{ FunctionA()})'.  Then I navigate to page B and goBack page A many times repetition .Finally I navigate to B to execute action to make  var1 change 。
Then The bug occured：the FunctionA will execute many times .The count Function A excuted time is the cyclic action time which I navigate to B and goBack。

Sorry My English is bad  : (，I hope this conveys my thoughts with clarity.

**Comment by mweststrate** [comment]
Make sure you dispose any reaction you create in a component, when unmounting. `reaction` will return a function that allows you to do that

**Comment by AlphaDu** [comment]
@mweststrate thank you for your help !I solve it by invoking disposer function when component will unmount.I will close this issue  : )
