### ISSUE TITLE
add a "module" entry point to package.json

### ISSUE THREAD

**Issue by nikitaMe1nikov** [mobxjs/mobx#1026]
Why there is no build for es6 target? It allows to reduce the bundle size.

**Comment by capaj** [comment]
@nikitaMe1nikov we've just switched to rollup for doing mobx builds, so there is an es6 build target on the horizon. I may take a stab at it this weekend if no one else grabs it sooner.

**Comment by capaj** [comment]
this will be fixed by #1027

**Comment by mweststrate** [comment]
Released as 1.1.13
