### ISSUE TITLE
Intercept that filters numbers seems to be letting '.' onto a React form input

### ISSUE THREAD

**Issue by mattruby** [mobxjs/mobx#1029]
I have a:
2. [X ] Issue:
  * [X ] Provide a **minimal** sample reproduction. **create a reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)** 

Here's my sample code: https://codesandbox.io/s/G5v71oDA8

I have an intercept that will only allow numbers to be added to `model.age`.  I'm not sure how, but I'm able to add a . onto the input.  It will not hit the model, but it will show in the input.  If I type another . the first will be removed.

**Comment by urugator** [comment]
https://github.com/facebook/react/pull/9584

**Comment by mattruby** [comment]
Wow! I searched for this, but no way I was going to find it. Thanks @urugator!
