### ISSUE TITLE
Better warnings when not setting store props accordingly

### ISSUE THREAD

**Issue by rodryquintero** [mobxjs/mobx#103]
I noticed that when you mistype a state prop, rendering it undefined, all hell breaks loose. This happend to me when I introduced a typo on one of the store and the entire app crashed. 

I was also getting errors from a component that I wasn't even using/importing on any module component. This was very difficult to troubleshoot.

Something along the lines of  `store prop is undefined` would be helpfull.

**Comment by mweststrate** [comment]
Hi Rodry,

That's quite a general statement. Could you elaborate a bit with a small example where you made an error and in which kind of exception it resulted? If you assigned a value to the wrong property somewhere, not that random field assignments can simple not be detected in JS (until proxies are standardized). The best way to prevent such mistakes is by using a static typechecker like flow or typescript (which I really recommend)
