### ISSUE TITLE
Getting "Initializers are not allowed in ambient contexts." in 3.1.11

### ISSUE THREAD

**Issue by davidstelter** [mobxjs/mobx#1030]
After an `npm update`, when I run an `npm start` in my project, which triggers a webpack build with TypeScript I get the following:

```
ERROR in [default] ./node_modules/mobx/lib/utils/iterable.d.ts:1:41
Initializers are not allowed in ambient contexts.
```

It doesn't do this in mobx <= 3.1.10 but does in 3.1.11. I can see that there's no change to the source file in question, `lib/utils/iterable.d.ts` between 3.1.10 and 3.1.11 so it must be something in the build process.

Line one of the built iterable.d.ts is:

```
export declare const IS_ITERATING_MARKER = "__$$iterating";
```

...which is indeed an initialization.

It seems like the only relevant change from 3.1.10 to 3.1.11 is moving to rollup for bundling - I'm guessing this is causing the declaration to be exposed differently. Looks like newer versions of TypeScript >= 2.1 support this, but we're using 2.0.8 due to requirements of some other older packages.

It looks like the symbol `IS_ITERATING_MARKER` is only used within iterable.ts, so this really doesn't need to be exported this way as far as I can tell, in fact it could just be replaced with two string literals in iterable.ts or a const within the function body of `arrayAsIterator()` which is the only place in mobx I see it referenced.

**Comment by mweststrate** [comment]
Feel free to open a PR, but note that keeping definitions backward with older TS versions is tricky in general, but if this is the only issue, it should be solvable indeed, as this is just an internal concern indeed
