### ISSUE TITLE
Uncaught TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by mattoni** [mobxjs/mobx#1034]
Hi there,

I'm on latest version (3.1.11) and I'm getting an issue when setting an observable property in some cases.

![image](https://user-images.githubusercontent.com/5110855/26848567-c6a8e59e-4ab5-11e7-98cc-393b597e99d1.png)

The issue is being caused by this line: 

```
export class SignupForm {
    public readonly formState = new MultiStageFormState();
    @observable private readonly state: SignupFormState;

    constructor(state?: SignupFormState) {
        if (state) {
            this.state = state;
            return;
        }

        this.state = { // Error is happening here
            email: "",
            name: { first: "", last: "" },
            password: "",
        };
    }
...
```
I'm having trouble isolating the issue, but no matter where I initialize the state object, it throws this error ( even if i declare on the same line).

The weird part is it works on a very very similar spot earlier in the code with no problem, making me think it may be some sort of weird import issue happening from transforming the code.

Any input would be great, just want to start looking for a solution in the right place.

Thanks!

**Comment by mattoni** [comment]
It appears the error is only caused with this function added into the class:
```
    @action public set firstName(v: string) {
        this.state.name.first = v;
    }
```

It appears that having a setter marked as an action (when I don't have a compute getter) causes this to fail...

**Comment by mattoni** [comment]
Error reproduced here: https://codesandbox.io/s/ElQx9KyJg

**Comment by urugator** [comment]
[Using the @action decorator with ES 5.1 setters (i.e. @action set propertyName) is not supported](https://mobx.js.org/refguide/action.html)

**Comment by mattoni** [comment]
Ah, looks like I missed that line. Might be good to provide a better error upfront (if possible), but I appreciate it!
