### ISSUE TITLE
Add brackets to `if` statement with single console.warn inside

### ISSUE THREAD

**Issue by O4epegb** [mobxjs/mobx#1035]
I have a strange request (probably).
Can we add brackets to [this](https://github.com/mobxjs/mobx/blob/master/src/api/expr.ts#L20) `if` statement?

I am using [webpack strip loader](https://github.com/yahoo/strip-loader), and it chokes on this part, because when it strips console.warn the code becomes non valid.

If you are ok with this change i will make PR.

**Comment by mweststrate** [comment]
I'm not against accepting a PR that adds the curly braces. 

But  you might want to look for a more permanent solution as well; as this does like a classic example of a footgun:

1. when mobx will be using prettier (in the foreseeable future), you will still be screwed.
2. This sounds to me like a fundamental issue with that loader. You would be better of if you replaced the console calls with `noop()` calls rather then by nothing, which breaks the syntactic structure of the program
3. that console message (and many others) are there for a reason. This makes it basically impossible to debug, as you will be missing any hints this library (and others) are giving you. So stripping out console sounds like an extremely dangerous solution to me? I hope you have a better reason than saving a few bytes.. ;-)

**Comment by O4epegb** [comment]
1. I think prettier actually adds brackets :)
2. Yes, this is definitely better solution, but there is no loader or standard way for that. Maybe i should make one..)
3. You might actually be right on that, i just used to have clean console on production and but leave all the debugging and other console.logs in the code.

I'm closing this one, since you convinced me that removing console is not the best idea ever!
