### ISSUE TITLE
Can all stores have access to all stores aka. rootStore parameter?

### ISSUE THREAD

**Issue by thupi** [mobxjs/mobx#1037]
Hey, i am looking for a help to make all of my mobx store have access to all other stores.
The ability to modify other stores from a given store makes the state management way easier in our application. 

Mayby by passing rootStore to all constructors? :-)

Any ideas or solutions for this for this? :-)

**Comment by janhoeck** [comment]
You just can import a store in another store :) This works fine for me.

**Comment by thupi** [comment]
Okay, that seams like a solution i can use for now but that might not work with server side rendering right :-) ?

**Comment by thupi** [comment]
Currently this is athe soultion by @timothyallan i went for :-)
```
const ui = new Ui();
const auth = new Auth(ui);
const notification = new Notification(auth, ui);

const stores = {
  ui,
  auth,
  notification,
};
```

**Comment by janhoeck** [comment]
I never tested my solution via server side rendering :P Sorry

**Comment by thupi** [comment]
@janhoeck Hehe, all right. I do not use server side rendering :-) However, i would like to have at way to solve this problem which also would fit in a server side rendered app :-) Thanks for the very simple and clean solution though :-)
