### ISSUE TITLE
extendsObservable doesnt trigger re-render

### ISSUE THREAD

**Issue by janhoeck** [mobxjs/mobx#1038]
Hello everybody,

I known there are a lot of closed tickets with the same topic.
(See: https://github.com/mobxjs/mobx/issues/194)

All tickets got closed with the answer: **Use observable.map!**

But why? The documentation says for "Observable Objects":
> When passing objects through observable, only the properties that exist at the time of making the object observable will be observable. Properties that are added to the object at a later time won't become observable, unless extendObservable is used.
(https://mobx.js.org/refguide/object.html)

Sure I could use observable.map but there I dont have the nice dot notation for accessing properties in javascript. And this is what I want, because this is my code convention.

My question now is: Do the documentation tells wrong information or is there a way to get extendsObservable work?

**Comment by mweststrate** [comment]
ExtendsObservable can add observable properties just fine. But the addition of these properties itself is not an observable fact, so if you need to react to the fact that a property is added itself, then you need to use maps indeed:

```javascript
const a = observable({ 
   x: 1 
})

autorun(() => {
   console.log(a.x, a.y) // won't react to a.y initially, as it is not an observable property
})

extendObservable(a, { y: 2 }) // won't trigger autorun, the creation of a new observable property is not something tracked by the autorun

a.x = 2 // this will trigger the autorun as usual
a.y = 3 // but this as well! in the last run a.y was a defined observable propery, so mobx started tracking it
```

Maps don't suffer from that problem, as they have explicit support of tracking not-yet existing fields. 

Note that the above could also be fixed by simply:


```javascript
const a = observable({ 
   x: 1,
   y: undefined
})
```

**Comment by janhoeck** [comment]
Is it possible that a new added property via extendOberservable will be overserved?
Maybe a developer can define that by a new property?

extendObservable(a, {y: 2}, true) ?

Maybe that could be implemented in a new version :)
Benefits:
- I can use the dot notation again
- A new developer in the company doesnt get confused when he see that we are using maps at some points and at some other points we are dont using map. You understand what I mean? ;)

**Comment by urugator** [comment]
No, it's technical limitation. MobX uses getters and setters to perform subscription/notification. MobX doesn't know if that not yet defined property was accessed in some reaction/autorun, because the MobX getter was not invoked, therefore it can't notify that reaction/autorun to re-run.    
If you have an access to proxies a handler like this could do the trick (not tested):
```javascript
const handler = {
  get(target, key, proxy) {
    if (!isObservable(target, key)) {
      extendObservable(target, { [key]: undefined });  
    }        
    return target[key];
  }
}
```
However be aware of possible perfromance problems, not with proxy, but with `extendObservable`. MobX Map and Array are optimized for modifications and won't suffer from that problem.

**Comment by mweststrate** [comment]
See #652

**Comment by DeDuckProject** [comment]
@mweststrate I'm wondering if there's some kind of hack to trigger a force render after `extendObservable`.

**Comment by mweststrate** [comment]
Yeah, change one of the already existing properties :-P. But no, really,
either use maps, or declare your properties upfront.

Op wo 23 aug. 2017 om 11:08 schreef Iftach Yakar <notifications@github.com>:

**Comment by pstanton** [comment]
of course, re-reading the docs "after" reading this issue - it makes much more sense (i can close my stackoverflow question now). i think [this page](https://mobx.js.org/refguide/object.html) needs a little more regarding "late-add" of properties. I don't mind declaring them upfront, i think that is a win.. it's just not clearly defined in the docs (or i missed it)

**Comment by mweststrate** [comment]
Feel free to PR doc improvement!

Op wo 24 jan. 2018 14:39 schreef Paul Stanton <notifications@github.com>:

**Comment by mnpenner** [comment]
> MobX doesn't know if that not yet defined property was accessed in some reaction/autorun, because the MobX getter was not invoked, therefore it can't notify that reaction/autorun to re-run.

So, I understand why we can't detect direct access to a yet-to-be-defined property, but is there no way to have `extendObservable` trigger re-renders when `JSON.stringify`, `Object.keys`, `Object.values`, `Object.entries`, or `for(... in ...)` is used? i.e., `extendObservable` should trigger a re-render when a method that accesses *all* properties is invoked?

**Comment by mweststrate** [comment]
`toJSON` might conflict with a user defined `toJSON`, MobX doesn't add anything automatically to observable objects (unless mobx-state-tree which has indeed `toJSON` implemetned on all is objects)

> to make the other methods work
The other methods are built in browser methods (or even language construct), which would require built in method patches, something one shouldn't do. It sounds like an easy way out of many complex problems, but one day it will cause the next smooshgate.
