### ISSUE TITLE
"export 'default' (imported as 'mobx') was not found in 'mobx'

### ISSUE THREAD

**Issue by themre** [mobxjs/mobx#1043]
Installed version 3.1.14 and I get:
`"export 'default' (imported as 'mobx') was not found in 'mobx'`
whereas with 3.1.10 everything works fine.

I'm using https://github.com/timarney/react-app-rewired

**Comment by rossipedia** [comment]
how are you consuming mobx? are 

* `import * as mobx from 'mobx';`
* `import mobx from 'mobx';`?

**Comment by rossipedia** [comment]
mobx's module build (which it seems CRA uses by default) does not have a default export. There's some hacky code in there (that should probably be removed at this point - thoughts @mweststrate?) to mimic a default export, but that's more for CommonJS code that's expecting a `default` property on the module.

For ES2015 modules (default in Webpack 2 and CRA) you should import what you need from mobx specifically:

```js
import { observable, extendObservable } from mobx;
```

or import everything and give it an alias:

```js
import * as mobx from 'mobx';

// use mobx.observable, mobx.extendObservable, etc...
```

**Comment by mweststrate** [comment]
I think we should now mimic the hack, until it is removed in 4.0? This
keeps the commonjs and module version as close as possible to each other?
Did you actually run into this, or were you testing?

Op za 10 jun. 2017 om 21:31 schreef Bryan J. Ross <notifications@github.com

**Comment by rossipedia** [comment]
The trick is that ES2015 modules need to be static, and problem here is we don't have a `export default` in the module build. That's going to prevent module consumers from using a default import with it. To support _both_ scenarios, we'd need to have both:

```js
export {
  extras,
  Reaction,
  untracked,
  IDerivationState,
  Atom,
  BaseAtom,
  useStrict,
  isStrictModeEnabled,
  spy,
  asReference,
  asFlat,
  asStructure,
  asMap,
  isModifierDescriptor,
  isObservableObject,
  isObservableValue as isBoxedObservable,
  isObservableArray,
  ObservableMap,
  isObservableMap,
  map,
  transaction,
  observable,
  IObservableFactories,
  computed,
  isObservable,
  isComputed,
  extendObservable,
  extendShallowObservable,
  observe,
  intercept,
  autorun,
  autorunAsync,
  when,
  reaction,
  action,
  isAction,
  runInAction,
  expr,
  toJS,
  createTransformer,
  whyRun,
  isArrayLike
};
```

_and_

```js
export default {
  extras,
  Reaction,
  untracked,
  IDerivationState,
  Atom,
  BaseAtom,
  useStrict,
  isStrictModeEnabled,
  spy,
  asReference,
  asFlat,
  asStructure,
  asMap,
  isModifierDescriptor,
  isObservableObject,
  isObservableValue as isBoxedObservable,
  isObservableArray,
  ObservableMap,
  isObservableMap,
  map,
  transaction,
  observable,
  IObservableFactories,
  computed,
  isObservable,
  isComputed,
  extendObservable,
  extendShallowObservable,
  observe,
  intercept,
  autorun,
  autorunAsync,
  when,
  reaction,
  action,
  isAction,
  runInAction,
  expr,
  toJS,
  createTransformer,
  whyRun,
  isArrayLike
};
```

That's in theory, actually. I haven't tried this yet and I'm not sure whether or not this would cause things to blow up on the consuming side (can't imagine it would, but you never know).

**Comment by rossipedia** [comment]
We can leave the hack in, but as it stands right now ES2015 consumers (meaning users of Webpack 2, etc) won't be able to use `import mobx from 'mobx';`

**Comment by themre** [comment]
`import mobx from 'mobx'`. so instead I should use  `import * as mobx from 'mobx'`?

**Comment by rossipedia** [comment]
Yes. I believe with version 4 and on mobx will no longer have a default export at all, so going forward `import * as mobx` or individual imports will be the officially supported methods

**Comment by andykog** [comment]
It seems that the hack doesn't work with webpack 2, you can try it in https://github.com/mobxjs/mobx-react-todomvc
(see also https://github.com/mobxjs/mobx-react-devtools/issues/64 )

**Comment by andykog** [comment]
mobx-react-devtools is broken as well due to using the default export here: https://github.com/mobxjs/mobx-react-devtools/blob/092fb0e7/src/globalStore.js#L112

**Comment by mweststrate** [comment]
Line 1 should read: import * as mobx from 'mobx';

Op ma 12 jun. 2017 om 10:11 schreef Andy Kogut <notifications@github.com>:

**Comment by mweststrate** [comment]
@andykog did you try the above? Did that fix it?

**Comment by themre** [comment]
i use it and it works with this new syntax. thanks!

**Comment by andykog** [comment]
@mweststrate, I'm sure it will work, I just thought, breaking compatibility in the minor update wasn't the intention. Maybe we should use something more robust, like `export default { extras, action, reaction ... }` until v4? (Though, I think, that would eliminate the tree shaking effect)

**Comment by mweststrate** [comment]
Yeah I am fine with that, but we added that already? Or am I confusing
things? But yeah breaking it was definitely not the intention. Surprising
though that hardly anyone ran into it, so most people already did it right

Op do 15 jun. 2017 om 10:41 schreef Andy Kogut <notifications@github.com>:

**Comment by andykog** [comment]
Nope, we added this thing https://github.com/mobxjs/mobx/blob/7f8dbf8/src/mobx.ts#L111-L117 and it doesn't seem to work with webpack 2

**Comment by rossipedia** [comment]
It _technically_ works with webpack2, as long as you aren't using es2015 modules (ie: using `require('mobx')` instead of `import mobx from 'mobx'`.

Regardless, it's brittle af and really only exists to support mobx-react (from what I know)

**Comment by andykog** [comment]
Made a pr: #1050

**Comment by AoDev** [comment]
Hi, I have ran into this issue in multiple projects.

> so going forward import * as mobx or individual imports will be the officially supported methods. Ideally

Could you explain why you don't want to provide a default export anymore?

**Comment by rossipedia** [comment]
Mobx is a rather large library that provides many methods that work together, as opposed to being a single function or class with a single purpose. While one _could_ make the case that `observable` is really the focus of the library, there isn't really a single item that `mobx` exports that can be called "mobx". This is the same reason that React doesn't have a default export, nor does [redux](https://github.com/reactjs/redux/blob/master/src/index.js#L28-L34).

This is precisely the scenario that named exports are _for_, and maintaining both named and default exports for a library of mobx's size is cumbersome (as demonstrated by @andykog's PR above). It also removes the need for deciding "how do I want to import mobx today?", as there will be only one way to do it. The trade-off cost of `import * as mobx from 'mobx';` vs `import mobx from 'mobx';` is minimal (4 characters to be precise).

**Comment by mweststrate** [comment]
Released @andykog's PR as 3.1.16

**Comment by ozluy** [comment]
add this to your WebPack configuration.

```
 ignoreWarnings: [
    {
      // Goodbye to annoying mobx warning for ages 🎉🎉🎉
      message: /export\ \'getDependencyTree\'\ \(imported as \'getDependencyTree\'\)\ was\ not\ found\ in\ \'mobx\'/, 
    },
    
  ],

```

**Comment by kubk** [comment]
This version of Mobx not supported anymore. I am the locking conversation. If you experience this issue with a up-to-date Mobx version please create a separate issue.
