### ISSUE TITLE
A provider for a handful of routes

### ISSUE THREAD

**Issue by sheam** [mobxjs/mobx#1048]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ X] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

What is the best way to provide a store to a handful of routes? I have the following routes: 
```
const stores = {
  users: userStore,
  routing: routingStore
};

<Provider {...stores}>
<Switch>
  <Route exact path='/' component={HomePage} />
  <Route exact path='/cats' component={CatsPage} />
  <Route exact path='/rats' component={RatsPage} />
  <Route exact path='/birds' component={BirdsPage} />
  <Route exact path='/dogs' component={DogListPage} />
  <Route exact path='/dogs/:id/edit' component={DogEditPage} />
  <Route exact path='/dogs/:id/history' component={DogHistoryPage} />
</Switch>
</Provider>
```

I have a DogStore which loads from remote sources. I would like this store available to the last three pages in my router. I don't want my store to load up all my dogs unless someone actually acesses that route.

Am I best to just add the store to the surrounding Provider, and only call 'load' on the didMount() of the Dog* pages? Or is there a way to wrap just those pages in their own provider?

**Comment by sheam** [comment]
I have something that works now, just not sure if it is the ideal way to do things with MobX:

```
const stores = {
  users: userStore,
  routing: routingStore
};

<Provider {...stores}>
<Switch>
  <Route exact path='/' component={HomePage} />
  <Route exact path='/cats' component={CatsPage} />
  <Route exact path='/rats' component={RatsPage} />
  <Route exact path='/birds' component={BirdsPage} />
  <DogSection />
</Switch>
</Provider>

export class DogSection extends React.Component<undefined, undefined>
{
    private _dogStore: TestStore;

    public constructor()
    {
        this._testStore = new DogStore();
    }

    public render(): JSX.Element
    {
        return (
            <Provider dogStore={this._dogStore}>
              <div>
               <Route exact path='/dogs' component={DogListPage} />
               <Route exact path='/dogs/:id/edit' component={DogEditPage} />
               <Route exact path='/dogs/:id/history' component={DogHistoryPage} />
             </div>
            </Provider>
        );
    }
}
```

This only constructs and loads the DogStore when one of the three pages is rendered.

**Comment by mweststrate** [comment]
LGTM

**Comment by sheam** [comment]
Thx for the feedback, appreciated.
