### ISSUE TITLE
Emit spy events when reactions get disposed

### ISSUE THREAD

**Issue by hediet** [mobxjs/mobx#1049]
I am trying to implement a mobx dependency visualizer using the `spy` function. For that, I need to know when reactions are no longer used so I can remove them from the visualization.
My current workaround is to check regulary for the `isDisposed` property of reactions. However, it would be nice to have a less hacky way.
I face a similar problem for mobx atoms.

**Comment by mweststrate** [comment]
I don't think it is a good idea. Taking that road into extreme basically every method in the mobx api would be need to be instrumented, depending on what somebody wants to spy. Dispose is something that happens from userland code mainly, so you can annotate over there as well. Or monkey-patching the Reaction object might also work if you really want it to be generic.

For atom's, see also https://github.com/mobxjs/mobx/issues/992. It is now supported for custom atoms, but these events will be made available for all atoms in the future
