### ISSUE TITLE
Observable mongoose models?

### ISSUE THREAD

**Issue by alexmipego** [mobxjs/mobx#1059]
I started a project using mobx-starter and made it possible to import the mongoose models on the client side (http://mongoosejs.com/docs/browser.html).

To create a document on the client side (it's different from server-side) I use `new mongoose.Document({}, MySchema)` but after passing it to a component I'm at a loss on how to properly set it up. 

Wrapping the document with `observable(myDocument)` makes my input show "ObservableValue@15" when I bind it's properties to a form input.

Is there a special step required to wrap complex objects and make them observable?

**Comment by mweststrate** [comment]
Please check the docs. Mobx will never deep convert objects, to avoid accidentally messing up the internal semantics of a class instance. You can use `extendObservable` to replace properties with observable properties in an existing object, but at your own risk :)
