### ISSUE TITLE
Consider using Prettier

### ISSUE THREAD

**Issue by roperzh** [mobxjs/mobx#1060]
**What problem would it solve for you?**

In some places (especially tests files) the code is a bit hard to read because of formatting issues like bad indentation. [Prettier](https://prettier.github.io/prettier) is an opinionated code formatter, and can help us here.

Also, @mweststrate mentioned in https://github.com/mobxjs/mobx/issues/1035#issuecomment-307141578 the will to implement Prettier in the near future.

**Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?**

Yes, but it will not make a difference in the core package.

**Are you willing to (attempt) a PR yourself?**

Yes, but I'm not sure if I'm the appropriate person.

**Comment by mweststrate** [comment]
Prettier is a welcome addition :). Can you make sure the same settings as in mobx-state-tree are used?

**Comment by realityforge** [comment]
The pull request #1103 was raised to satisfy this issue.

**Comment by realityforge** [comment]
This can be closed now that #1103 has been merged
