### ISSUE TITLE
Should @action be used on any class function that updates it's observable?

### ISSUE THREAD

**Issue by IljaDaderko** [mobxjs/mobx#1062]
I am trying to figure out `@action` and `@computed` decorators, not sure what the difference is and why these decorators are needed at all as all my functions to update observables of their class worked fine without these decorators.

So to start with, should I use `@action` decorator on any class function that updates it's observable?

**Comment by urugator** [comment]
To understand what actions do, [this snippet](https://github.com/mobxjs/mobx/issues/1010#issuecomment-303804877) could help.
While actions are used for writes, the computeds are used to create derived state - state which depends on (computes from) another state (another observable) and should be updated (re-computed) any time these observable dependencies change. However, the observers of the computed are updated only if the value returned from computed really changed.
An analogy to computed value is a React element, which is a computation of React component state. When componen state is modified, the computation (render) is invoked again and produces new element. If the produced element differs from the previous one, the DOM is updated.
