### ISSUE TITLE
Observable Initialize on itself vs on constructor

### ISSUE THREAD

**Issue by dsslimshaddy** [mobxjs/mobx#1063]
Is there a Difference between the two ?
If yes, which one to use when ? Which is more performance efficient ?

Also given im not passing anything into the constructor.
I have seen in lots of codes some use method 1 and some use method 2 .

```
class A{
  @observable someVariable = 100; 
}
```
```
class A{
   @observable someVariable; //not @observable someVariable = 100;
    constructor(){
     this.someVariable = 100;
   }
}
    
```

**Comment by urugator** [comment]
Method 1:
1. value is assigned to property
2. property is made observable

Method 2: 
1. value is assigned to property
2. property is made observable
3. value is assigned to property (setter function is invoked)

When assigning values to observables in constructor be aware that constructor does not run inside the the action. So 
```javascript
@observable prop;
constructor() {
  autorun(() => console.log(this.prop);
  this.prop = 5; // autorun is immediately invoked, strict mode is violated (throws)
  
  // POSSIBLE SOLUTION 1  
  this.prop = 5; // no observers yet, modifications are fine
  autorun(() => console.log(this.prop); // not invoked
  
  // POSSIBLE SOLUTION 2
  autorun(() => console.log(this.prop);
  runInAction(() => this.prop = 5); // no strict mode errors, autorun is invoked when action ends
}
```

**Comment by dsslimshaddy** [comment]
@urugator  it seemed a typo while writing but in method 2 value is not assigned to property

**Comment by urugator** [comment]
Most probably the property initializer is transpiled to:
```javascript
Object.defineProperty(this, "prop", {
  value: undefined, // or 100 
})
```
so it really shouldn't matter if there is a value or not, the prop must be somehow added to object first, then the decorators are invoked
