### ISSUE TITLE
A suggestion for mobx npm package

### ISSUE THREAD

**Issue by sheweichun** [mobxjs/mobx#1064]
Sorry for my pool english.I wish you can known me.
When i use mobx npm package,I found you package all the code in a one javascript file
Can you Additional  provide compiled source codes，why?
Because Developer can use the code we need by developing a babel plugin,for Example
`import {observable} from 'mobx'`,by babel,I can transform to 
`import {observable} from 'mobx/api/observable'`,In fact,there are lot code I don't need in production,Besides,like message is also not needed
Compare to redux,mobx is more suitable for little or medium project,especially in mobile,litter code is more important~~~So I hope you can think about my suggestion

**Comment by mweststrate** [comment]
MobX provides an ES6 module which supports tree shaking, which will do this automatically for you if your build setup supports tree shaking.
