### ISSUE TITLE
How to test with autorun in mocha?

### ISSUE THREAD

**Issue by ckwong90** [mobxjs/mobx#1065]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **create a reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)** 
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?
 
Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by mweststrate** [comment]
The above issue template is there for a reason.
