### ISSUE TITLE
Can I listen to the beginning and end of function execution?

### ISSUE THREAD

**Issue by FishOrBear** [mobxjs/mobx#1067]
Mobx is a very library project,

I think it should be able to implement this feature, trigger a message before the function is executed, and trigger a message at the end of the function.

**Comment by mattruby** [comment]
Does intercept meet your needs?

**Comment by FishOrBear** [comment]
I think it does not meet my needs, but I found a library, it can intercept the beginning and end of the function.
https://github.com/cujojs/meld

**Comment by mweststrate** [comment]
The [spy](https://mobx.js.org/refguide/spy.html) method allows you to both intercept action start and end
