### ISSUE TITLE
Discrepancy between re-computation between `render` and `computed`

### ISSUE THREAD

**Issue by iEchoic** [mobxjs/mobx#1075]
(discussion/question)

Hi there,

I've been using MobX in production on a large-scale app (120k+ lines of React), and I love it so far. However, there's one persistent blemish/ugly spot that continues to cause pain.

Imagine this setup:

```
@observer class SomeContainerComponent extends React.Component {
  store = new SomeStore();

  render() {
    // store.someProperty is an observable
    return <SomeChildComponent someProperty={this.store.someProperty}/>
  }
}
```

```
@observer class SomeChildComponent extends React.Component {
  render() {
    const someComputedValue = this.props.someProperty + 123;

    return <div>{someComputedValue}</div>;
  }
}
```

Okay, cool, works great. When `someProperty` changes in the store, then my component updates, because `render` is called when props change.

Now, the computation becomes more complex, so I move `someComputedValue` to a `computed`:

```
@observer class SomeChildComponent extends React.Component {
  @computed get somePropertyTransformed() { 
    // this value is specific to `SomeChildComponent`, so it's computed here
    return this.props.someProperty + 123 / 2;
  }

  render() {
    return <div>{this.somePropertyTransformed}</div>;
  }
}
```

Now, my app is broken because my component will no longer re-render because an observable is not being de-referenced in `SomeChildComponent`. I know that this is expected behavior, but it's (in my evaluation) quite unfortunate that what should be a valid internal refactoring of a component is not valid. And worse, all of the solutions that I've found are bad, and most of them require substantial refactoring.

Here are some solutions, and why they are bad:

1. **Pass the store down to `SomeChildComponent`.** this couples `SomeChildComponent` to the structure of the store passed into `SomeChildComponent`, which should be able to provide an interface that has no knowledge of what a "store" is or how it is structured.

2. **Compute the value in `SomeContainerComponent` and pass it down**: this is bad because the value being computed contains information that is not `SomeContainerComponent`'s concern. This also requires that every component that ever render `SomeChildComponent` repeat this computation.

3. **Keep it in `render`**: this is bad because MobX is no longer able to solve the problem of having to re-compute the same thing on every render. I also can't use this logic as part of other computed props of the component.

Is there a simple solution to this that I'm missing? If not, I can propose some solutions, but I want to get thoughts first.

**Comment by mattruby** [comment]
Would expr help you?
https://mobx.js.org/refguide/expr.html

**Comment by iEchoic** [comment]
@mattruby possibly.... If I use the example as intended, then I believe it's basically the same as #3 in my list above, so it doesn't really solve anything. It does bring up the point that I could do this, though:

```
render() {
}
```

**Comment by iEchoic** [comment]
I think the solution I'm looking for would be something like:

```
@computed.withProps get somePropertyTransformed() {
}
```

**Comment by mweststrate** [comment]
@iEchoic what version of Mobx-react are you using? Since 4.0 props are an observable as well, which should fix this problem. If not, could you create a fiddle demonstrating the problem

**Comment by iEchoic** [comment]
@mweststrate I'm still on 3.5.5. I've been avoiding updating MobX until there are changes that I felt were necessary to pick up, and I've also only been looking at MobX's changelog and didn't even think about mobx-react's changelog, so I missed this.

This is an awesome fix, and it looks like it'll resolve the only thing that's really bothered me about MobX, so I'll try updating this week. You can feel free to close this, thank you!
