### ISSUE TITLE
Expand createTransformer to support multiple arbitrary arguments in the transformer

### ISSUE THREAD

**Issue by SamPruden** [mobxjs/mobx#1087]
Currently, `createTransformer` has some major limitations, such as:

- It only allows a single argument
- That argument must be either a string, number, or object - null, undefined, boolean, etc throw errors
- It doesn't respect `this`, so works poorly to transform class methods
- The documentation lacks details about these limitations

I think it would be beneficial to expand the functionality to remove these limitations, such that any arbitrary function could be transformed and memoized.

## Feature wishlist for `createTransformer`:

- Allow any arbitrary type to be used as arguments in the transformer
- Allow any number (zero or more) arguments to be used in the transformer
- Allow the value of `this` to pass through, such that a method can be a transformer and still have access to its class members
- Allow constructors to become transformers, such that using `new` respects memoization
- Provide a decorator to make methods transformers - either `@transformer` or maybe `@computed` on methods
- MAYBE provide some shortcut for memoizing constructors - a class decorator or a `transformer.makeFactory(Klass)` approach perhaps, but there are some design and technical challenges surrounding this point

I currently have a WIP PR for this at #1088. I've been having fun putting this stuff in and I think the quality of the work is pretty good for now, but it could use some stress testing (perhaps in the form of more unit tests) by a more experienced javascript developer as I'm cautious about claiming it supports all types (there's one acknowledged limit to that already in frozen objects) and doesn't break some backwards compatibility somewhere.

**Comment by TheOtherSamP** [comment]
I've edited this issue to tidy it up a lot, taken out some fluff and made things clearer.

**Comment by mweststrate** [comment]
`createTransformer` will move to the `mobx-utils` package from Mobx 4 and upward. Closing the issue here
