### ISSUE TITLE
Stateless Functional components optimations when using observer

### ISSUE THREAD

**Issue by shkrishms** [mobxjs/mobx#1094]
Welcome to MobX. Please provide as much relevant information as possible!

If at all possible, provide a **minimal** sample reproduction. **Create a minimal reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)**

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)** 
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

**Comment by shkrishms** [comment]
Hi, I would like to know if using a stateless component has any optimizations when used with observer? Mobx is managing state. So , if I use stateless component with observer, it still tracks state in some form right? So what is better
@Observer export class SomeComponent extends React.Component<{ value: string }, {}> 
{ 
public render() 
{ 
   return (this.props.value} ); 
} 
}

OR
export const SomeComponent = observer(({ labelValue: string }) =>
    <p className="ms-fontSize-s ms-fontWeight-semibold">{}</p>
);
--

**Comment by urugator** [comment]
Because `@observer` has to hook into lifecycle methods, the functional component is actually converted into component class... so no optimizations here.

Not sure if intention, but notice that the change of `this.props.value` can't be observed, so `@observer` would have no effect in this case...

**Comment by shkrishms** [comment]
so because string is immutable, that it cannot be observed? Thanks. Makes so much sense now.
This component merely displays a computed value( i.e say total count from an observable list). Making this a separate component to make it reusable. Are there any best practices for such components?

**Comment by shkrishms** [comment]
what is the string is defined as @observable in the parent?

**Comment by urugator** [comment]
Accessing the observable prop in parent render method like `this.observableProp`, will cause the parent to re-render when `this.observableProp` is modified. However if you pass the value alone to the child the observability is lost because value alone can't be observed, you have to pass an observable object. [See the code snippet](https://github.com/mobxjs/mobx/issues/1000#issuecomment-302200137)

**Comment by urugator** [comment]
also check https://mobx.js.org/best/react.html

**Comment by shkrishms** [comment]
Just to make sure I got this right: Below will pass the string as an observable object to the child component right? So in this case we can use @observer in the child component.

class ParentComponent extends React.Component<> {
   @observable name:string;
    public render() {
        return (
            <ChildComponent props ={this.name}
            </ChildComponent>
        );
    }
}

@observer
class ChildComponent extends React.Component<name:string> {

    public render() {
        return (
            <div {this.props.name}
            </div>
        );
    }
}

**Comment by urugator** [comment]
No you're passing `this.name`, which evaluates to something like "myName", only the parent will observe the change and will get re-rendered (which consequently re-renders it's child as well, which would happen even without @observer on child)

**Comment by urugator** [comment]
```javascript
isObservable(this.name); // false
// <=>
isObservable("myName"); //false
// so inside the child:
isObservable(this.props.name); //false
// however (in parent)
isObservable(this); // true
// and
isObservable(this, "name"); // true
```

**Comment by shkrishms** [comment]
Understood. Thanks so much. This is very useful information for our team. We are starting to code in react and there seems to be a lot of misconceptions.
