### ISSUE TITLE
@computed does not work as expected with prototypical inheritance

### ISSUE THREAD

**Issue by phiresky** [mobxjs/mobx#1100]
When overriding a value in a subclass, a computed getter depending on that value does not correctly use the value of the object itself, but rather that of the prototype where the computed getter was defined.

I didn't find a relevant existing issue, though I didn't really know what to search for.

Minimal example:
https://codesandbox.io/s/kRYPM7Rr

```
class Parent {
    @observable items = [1, 2, 3, 4];
    @computed get largeItems() {
        return this.items.filter(x => x > 2);
    }
}
const parent = new Parent();
const child = Object.create(parent, {
    items: {
        get: () => [...parent.items, 5, 6]
    }
});
console.log(parent.largeItems);
console.log(child.largeItems);
```

When I remove `@computed` from Parent.largeItems, it works as expected.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/issues/600
https://github.com/mobxjs/mobx/issues/527

**Comment by mweststrate** [comment]
This might be a bug indeed, not entirely sure, as this code itself smell's. Redefining instance fields is a practice that should strictly be avoided imho in any OOP system. I would rather make sure that you _reassign_ items, instead of _redefining_ items. In your example for example it is pretty unclear what a statement like `child.items = [2,3,4]` would mean, neither with or without mobx.

**Comment by phiresky** [comment]
I agree the code isn't really great, but the example in the OP is of course just a simplified example. In my actual code, `items` is a (non-writable) getter that returns `this.itemMap.values()` and `itemMap` is a observable map from id to objects (which can be modified).

In the context of the child class, the whole instance is only ever used in a readonly context (itemMap is not accessible), it's basically a modified immutable view of the original "object store" that in addition to the items in the original object adds a constant set of other items.

**Comment by mweststrate** [comment]
Still sounds to me like abusing inheritance for delegation. You could consider using viewmodels from mobx-utils maybe? Anyway, a won't fix. Too much of an edge case, which might very well become unmaintainable if the decorators spec is finalized

**Comment by mweststrate** [comment]
Personally I would approach it by using inheritance properly otherwise, like:

```
class Parent {
    @observable _items = [1, 2, 3, 4];
    protected getItems() { return this._items}
    get items() { return this.getItems() }
}

class Child {
   getItems() { return [...super.getItems(), 4,5,6] }
}
```

This doesn't raise any questions on what the semantics will be, and works probably neatly with mobx as well
