### ISSUE TITLE
observable map of object with 'watch' key break on FF

### ISSUE THREAD

**Issue by nirnatan** [mobxjs/mobx#1108]
Bug description:
When trying to create an observableMap with an object that one of his keys is **watch** (i.e. `observable.map({watch: 'failed'})`) in FireFox mobx breaks. (because of the Object.prototype.watch that exist in FF)
You can see an example in [codepen](https://codepen.io/nirnatan/pen/jLNozb). Uncomment the commented line that removes the watch property from the Object.prototype fix the problem.

* CallStack: 
"[1]</</ObservableMap</ObservableMap.prototype.set@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1216:27
[1]</</ObservableMap</ObservableMap.prototype.merge/</<@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1293:68
[1]</</ObservableMap</ObservableMap.prototype.merge/<@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1293:17
transaction@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:781:15
[1]</</ObservableMap</ObservableMap.prototype.merge@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1289:9
ObservableMap@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1193:13
map@https://npmcdn.com/mobx@2.0.0/lib/mobx.umd.js:1340:12
@pen.js:29:16
"
* a **minimal** sample reproduction. **[codepen](https://codepen.io/nirnatan/pen/jLNozb)** 
* **Firefox only** with mobx version 2.0.0

**Comment by urugator** [comment]
I believe that was fixed by #903, but was not merged to 2.X . [Fix is quite trivial](https://github.com/mobxjs/mobx/pull/903/files)
