### ISSUE TITLE
toJS return empty object for some observableObject

### ISSUE THREAD

**Issue by cdlterry** [mobxjs/mobx#1117]
1. toJS is validable to this kind of observableObject. It can return correct result;
![image](https://user-images.githubusercontent.com/15389663/28699622-66bc247a-737d-11e7-89fd-60566686982c.png)

2.but when the observableObject is like this below. toJS just return empty object such as {}
![image](https://user-images.githubusercontent.com/15389663/28699672-adf1aedc-737d-11e7-84a5-e1841f6fb3b2.png)

I'm confused: 
1. I don't know why there are two kinds observableObject above. The #mobx props appear in different positions. But  I just simply do some Assignment actions.
2. How can I deal the issue to use toJS to renturn correct result for the second kind of observableObject?

Thanks very much!

**Comment by mweststrate** [comment]
Please show how the objects where created

Op vr 28 jul. 2017 04:41 schreef cdlterry <notifications@github.com>:

**Comment by cdlterry** [comment]
the definition and the assignment are as below:

![image](https://user-images.githubusercontent.com/15389663/28708476-f9adee54-73ae-11e7-95a6-8d0f251a9b30.png)
![image](https://user-images.githubusercontent.com/15389663/28708535-34273a40-73af-11e7-81b1-a64a3ecafbb7.png)

**Comment by cdlterry** [comment]
@mweststrate 
the definition and the assignment are as below:

![image](https://user-images.githubusercontent.com/15389663/28760991-fd173808-75dd-11e7-871c-a25e7db165ec.png)

**Comment by mweststrate** [comment]
@cdlterry looks okay so far. Can you set up a reproduction, e.g. by using jsfiddle, to demonstrate the problem? (there are some in the readme or new issue template you can directly fork from). (and on a side note: *never* use `catch (error) {}` ).

**Comment by cdlterry** [comment]
@mweststrate 
![image](https://user-images.githubusercontent.com/15389663/28856812-aaebbfb8-7777-11e7-9717-1c48c170e233.png)
![image](https://user-images.githubusercontent.com/15389663/28856814-afbdd4b8-7777-11e7-929e-2cff6b7d67ff.png)

It looks that when the object in the array of 'events' has getter and setter function(as screenshot below) , the observable var of 'gameEvents'  will be toJS an empty obj.
![image](https://user-images.githubusercontent.com/15389663/28856922-510c0218-7778-11e7-83ee-453983afb478.png)

**Comment by urugator** [comment]
The chrome console [prints non-enumerable props with "lighter/slightly transparent" color](https://jsfiddle.net/0gbkotnn/6/). If you would consult the [docs](https://mobx.js.org/refguide/tojson.html), you would learn that:
> Computed values and other non-enumerable properties won't be part of the result.

So the question is, why the `msg` and `editorName` is enumerable in one case and non-enumerable in another.

**Comment by cdlterry** [comment]
@urugator 
Thanks! 
That is, in some cases, I use fs.readJson() in render process to get json objects, but the value is changed by electron.remote. to non-enumerable.

**Comment by Uneetpatel7** [comment]
@urugator @mweststrate I still have the same problem. Also, I have posted[ a question](https://stackoverflow.com/questions/56561924/why-does-tojs-return-an-empty-object-when-applied-on-observable-object) about the same topic on SF as it not good to reopen/open an issue. Can please have a look?

**Comment by urugator** [comment]
@Uneetpatel7 Can't reproduce: https://codesandbox.io/s/mobx-objectassign-tojs-7yst1

**Comment by Uneetpatel7** [comment]
@urugator It seems that the error is being reproduced when an object is assigned in an async manner. Find reproduced error here.
 [![Edit mobx Object.assign + toJS](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mobx-objectassign-tojs-gccwt?fontsize=14)

**Comment by FredyC** [comment]
@Uneetpatel7 Async is another beast :) You are accessing the computed property before it gets assigned. It won't be accessed again later unless you read it. Computeds are not a tool for driving async code ;) Try to use eg. `reaction` and console log based on that.

![image](https://user-images.githubusercontent.com/1096340/59366629-e1f41480-8d3a-11e9-994b-900996ff3fa3.png)

**Comment by urugator** [comment]
@Uneetpatel7 This should make it obvious:
https://codesandbox.io/s/mobx-objectassign-tojs-bc2ox

**Comment by Uneetpatel7** [comment]
@urugator  @FredyC  I understood it well. But I have one question. Why is the log of mobx observable object same both the time. i.e before and after in your code

**Comment by FredyC** [comment]
@Uneetpatel7 Care to elaborate? I don't follow what you mean. There is no modification of observable.

**Comment by Uneetpatel7** [comment]
@FredyC. Yeah. As seen in The log of an observable object it remains same both the time precisely speaking when it is called before the API call when toJS() gives empty object and after the API call when toJS() gives the non-empty object. Concluding the question only the output of toJS() changes while the observable object remains the same both the time [https://codesandbox.io/embed/mobx-objectassign-tojs-gccwt?fontsize=14](https://codesandbox.io/embed/mobx-objectassign-tojs-gccwt?fontsize=14)

**Comment by samiede** [comment]
I have the same problem for arrays that are the result of a @computed. While the array itself is there, the result of the toJS is an array of empty objects. Is there something one can do about that?

**Comment by mweststrate** [comment]
This issue was closed 2 years ago. Please open new issues instead of commenting on old ones nobody sees, except participants that were in this issue earlier.
