### ISSUE TITLE
await runInAction()

### ISSUE THREAD

**Issue by fehergeri13** [mobxjs/mobx#1123]
I couldn't  find in the documentation any answer, so I ask here.

I would like to create an action which do multiple async work, and it should act as a single action. so it can called from other actions:

    @observable isLoaded = false;
    @observable isLoading = false;
    @observable.ref data = {};
    @observable number = 0;

    @action
    async loadAjaxDoc() {
        this.isLoading = true;
        const doc = await fetch("http://example.com/resource");

        await runInAction(async () => {
            this.data = doc;

            const additional = await fetch("http://example.com/additional");

            runInAction(() => {
                this.data.additional = additional;
                this.isLoaded = true;
                this.isLoading = false;
            });
        });
    }

    @action
    async other() {
        await this.loadAjaxDoc();
        runInAction(() => {
            this.number += 1;
        });
    }

Is it possible? Thanks!

**Comment by mweststrate** [comment]
Yeah that is in principle no problem, might be small problems in the above, didn't run it. 
See the docs on async actions: https://mobx.js.org/best/actions.html

Tip: https://github.com/mobxjs/mobx-utils#asyncaction.
