### ISSUE TITLE
@observable in components updates all components from same type.  

### ISSUE THREAD

**Issue by macmonkey** [mobxjs/mobx#1129]
Hi!

I just started to use mobx. I want to get rid off async setState functions. I have done some Tests and came to the situations that mobx updates all Components from same type, or I just doing some mistake? 

For Example: 
my Child Comp

```

import React from 'react';
import {observable} from 'mobx';
import {observer} from 'mobx-react';

@observer
class Test extends React.Component
{
    @observable active = true;

    onClick = () => {
        this.active = !this.active;

    };

    render()
    {
        return (
            <div>
                <p>active: {this.active.toString()}</p>
                <button onClick={this.onClick}>Toggle Comp</button>
            </div>
        );
    }
}

export default Test;

```

my Parent Comp
```
[...]
class PageChildTest extends React.Component
{
    render()
    {
        return (
            <div className="page">
                <Test/>
                <Test/>
            </div>
        );
    }
}
[...]

```

When clicking the toggle button in one Component both components are changing. Is there are way to get around this behavior? 

Thank you for any advice.

**Comment by mweststrate** [comment]
Your code looks correct to me, could you reproduce it in a fiddle? (there are some fiddles you could easily fork in the readme or in the new issue template)

**Comment by macmonkey** [comment]
Oh interesting - it's working fine in fiddle.
[https://jsfiddle.net/amc9wfek/2/](https://jsfiddle.net/amc9wfek/2/)

It seams to be some issue with my project. I recognized it stop working in my Project when I put the Test Class in a separate File. 

Could it be some babel trouble?

**Comment by mweststrate** [comment]
The usual suspect is HMR. Can you check if you are using the latest beta
version that understands decorators? (Or disable it for testing purposes)

Op ma 14 aug. 2017 om 11:11 schreef monkey <notifications@github.com>:

**Comment by mweststrate** [comment]
Assuming this one was solved by using a later version of React hot loader. If not, let us know
