### ISSUE TITLE
How to use mobx observer without the class in react

### ISSUE THREAD

**Issue by Benjamin5050** [mobxjs/mobx#1130]
I am using axios and mobx in my react native project. One of the component (`Home`) on mount calls for a method (`getBirds()`) from a different file where all the API methods are organized.

store.js:

```
class BirdStore {
    @observable birdList = [];

    @action setBirdList = (birds) => {
        this.birdList = birds;
    };
}
```

Home.js:

```
@observer @inject("BirdStore")
export default class Home extends React.Component {    
    componentDidMount() {
        api.getBirds()
        ...
    }
}
```

api.js:

```
@inject('BirdStore') @observer
const api = {    
    getBirds() {
        const url = website + '/api/birds/';
        return axios.get(url)
            .then((response) => {
                // call the setBirdList(response.data) method 
            })
            .catch((error) => {
                console.log(error);
            })
    },
};
```

But this gives me an error:

> Leading decorator must be attached to a class declaration

I can use the data from the server returned by the `getBirds()` into the `Home` component, and then call the `setBirdList()` action, but I wanted to keep API related stuff separately. Is there any way to use mobx without the class so that I can handle all the API related stuff other than the class component itself?

**Comment by mweststrate** [comment]
@Benjamin5050 what should ...

```
@inject('BirdStore') @observer
const api = { ...
```

achieve according to you?

**Comment by Benjamin5050** [comment]
I was hoping I could use the `@action`'s directly from the api.

**Comment by urugator** [comment]
`@inject` uses [React's Context](https://facebook.github.io/react/docs/context.html) to pass dependencies (`BirdStore` instance or whatever) to components. Therefore it can only be applied to React's components.
If you want to use dependencies outside of component tree, you will need a different mechanism.

**Comment by mweststrate** [comment]
... for example, just pass in the store from the component to the api
methods

Op di 15 aug. 2017 om 13:07 schreef urugator <notifications@github.com>:

**Comment by Benjamin5050** [comment]
Yes, I am calling the api from the store. Thanks.
