### ISSUE TITLE
Required observable inside jest 'it' function doesn't track changes

### ISSUE THREAD

**Issue by Niryo** [mobxjs/mobx#1133]
When using jest, trying to require a store that has some observable values in it, causing 'multiple mobx instances active' warning and we loose all observability. 

in store.js:
`export const testObservable = mobx.observable({
    name: 'someRequiredName'
});`

in store.test.js:

```
    it('should trigger change', () => {
        const store = require('./store');
        let requiredCount = 0;
        mobx.autorun(() => {
            requiredCount += 1;
            console.log('required observable changed!,', store.testObservable.name)
        });
        store.testObservable.name = 'changed!';
        expect(requiredCount).toEqual(2); //fail: received 1.
    });
```

here is a demo: 
https://github.com/Niryo/mobx-playground

you can clone and run: npm  install && npm test

**Comment by mweststrate** [comment]
Sorry for the late response. 

Using ` "resetModules": false,` (the default) helps, otherwise new instances of the mobx module will be loaded into memory over and over again.
