### ISSUE TITLE
the function always work if i don't use @action 

### ISSUE THREAD

**Issue by iEricOuyang** [mobxjs/mobx#1134]
hello! when i defined a function which i used to modify the state, i didn't use @action, otherwise ,the function still work, but why?

**Comment by urugator** [comment]
`@action` does 3 things:
Batches state modification, [see this](https://github.com/mobxjs/mobx/issues/1010#issuecomment-303804877)
Wraps code in `untracked` to prevent unintentional subscriptions.
Prevents throwing an exception when [strict mode is on](https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#usestrict)

**Comment by iEricOuyang** [comment]
@urugator also, i fonund using @action without bound,_this_ still quote current observables object, what's the meaning please?

**Comment by urugator** [comment]
It will additionally bind the method to `this`, like: `this.method = this.method.bind(this);`. As a result you can pass `this.method` somewhere as a callback, like `onClick={store.method}`). (`this` would be normally undefined in this case)
