### ISSUE TITLE
Changing the data provided by reaction() causes infinite reaction loop

### ISSUE THREAD

**Issue by all-iver** [mobxjs/mobx#1135]
This might be by design, but I had an infinite loop in a reaction that took me a while to find.  Something like this:

```
extendObservable(this, {
    test: 5,
    disposer: reaction(
        () => { return { test: this.test } }, 
        data => { data.something = 'something'; this.test = 5; }, 
        { compareStructural: true }
    )
})
```

seems to cause an infinite reaction loop even though the observable data hasn't changed.  Mobx is supposed to only call my handler if the data has really changed, so I'm wondering if it is using the same data object to check for changes as it passes as input to my function.

I got into this situation because I was using the data dict as params for an API call, and the code doing the API call added another param or two first.

**Comment by mweststrate** [comment]
You are modifying `data`, which is used for the next comparison in the
future, so you will be comparing in the next run `{ test: 5 }`  with `{
something: 'something', test: 5 }`. Which is indeed a structural change. I
cannot imagine any good reason to modify the result of the watching
function. Is it a mistake and did you intend "this.something = 'something'"
?

Op di 15 aug. 2017 om 20:43 schreef Oliver Smith <notifications@github.com>:

**Comment by all-iver** [comment]
Well, I just didn't know I wasn't supposed to do it.  I did something like this:

```
reactionHandler = data => {
    someAPI(data).then(result => this.updateFromServer(result));
}

someAPI = params => {
    params.userId = loggedInUser.id;
    // call the server and get the changed object json
}
```

It's not really clear who "owns" the handler data so I didn't think it was a problem to modify it.  Maybe there should be a note in the docs?

**Comment by mweststrate** [comment]
Well, depending on what you return in the first function, it could actually
be OK to modify it (you could for example be returning a User instance and
invoke methods on it). The problem was not realizing that modifying it
would make it structurally different from what you would return in the next
run from the expression function, when using strucutral comparison.

Op di 15 aug. 2017 om 21:55 schreef Oliver Smith <notifications@github.com>:

**Comment by all-iver** [comment]
I see, that makes sense.  Okay, thanks for the clarification. :)
