### ISSUE TITLE
How do I trigger compute for Store B when the change is in Store A

### ISSUE THREAD

**Issue by ethanyanjiali** [mobxjs/mobx#1138]
Welcome to MobX. Please provide as much relevant information as possible!

If at all possible, provide a **minimal** sample reproduction. **Create a minimal reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)**

It's more like a pattern question. So for example, I have observable A from store A and observable B from store B. In the meantime, I have a compute property in store A that merging observable A and observable B from store B. When observable A changes, this compute method will be triggered, and return a merged object. However, then observable B changes, the compute method won't be triggered.

In Redux, we use selector to achieve this, but looks like @compute will only be called when the in-store field change? So do we have to get these two objects in an observer component and merge them there?

store A
- B - store B.B
- @observable A
- @compute () => ({ ...A, ...B })
- @action updateA

store B
- @observable B
- @action updateB

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)** 
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?
 
Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by urugator** [comment]
> @compute will only be called when the in-store field change?

No, `@computed` is recomputed if any accessed observable is changed, no matter where ti comes from. But note that a *changed observbale* object must be accessed not just a (possibly copied) plain value. Please refer to [this](https://mobx.js.org/best/react.html)
The idea is to pass observable objects around and not the values alone. So instead of 
`this.b = b.b` you should do `this.b = b` and call `this.b.b` in computed. Or if you don't want A to have a reference to B, introduce third observable object C, shared by both (C doesn't have to be class, but anything observable, for example a boxed value).
Anytime you pass plain value somehwere you duplicate the state, avoid that.
You can also do it like this:
```javascript
class A {
  @observable a = 5;
  @observable b; // the @observable here is for this.b = ..., not for this.b.b = ...
  constructor(b) {
    this.b = b; // note that b is not a value but an observable object
  }
  @computed get merged() {
    this.a + this.b.get(); // note how the B is used    
  }

}
class B {
  @observable b = 5; // no need for shared observable C
}
const b = new B();
const a = new A(Mobx.computed(() => b.b)); // not passing a value, but observable
```

**Comment by ethanyanjiali** [comment]
@urugator Thanks for you explanation.

I actually found where my problem is: I'm observing an object but the actually change is not that object but one level deeper

Here is the first store
```
import { observable, computed, action, autorun } from 'mobx';
import * as CampaignApi from './CampaignApi';
import statsStore from '../stats/StatsStore';

class CampaignStore {

  @observable campaigns = [];

  @computed get campaignsLadenStats() {
    const campaignStats = statsStore.campaignStats;
    const campaignsLadenStats = this.campaigns.map(campaign => {
      const stats = campaignStats[campaign.name] || {};
      return {
        ...campaign,
        ...stats,
      }
    });
    return campaignsLadenStats;
  }

  @action
  addNewCampaign(campaign) {
    this.campaigns.push(campaign);
  }

  createCampaign(campaign) {
    return CampaignApi.createCampaign(campaign).then(campaign => {
      this.addNewCampaign(campaign);
      return campaign;
    });
  }
}

export default new CampaignStore();
```

Here is another store
```
import { observable, computed, action } from 'mobx';
import * as StatsApi from './StatsApi';

class StatsStore {

  @observable campaignStats = {};

  @action
  updateCampaignStats(campaignName, stats) {
    this.campaignStats[campaignName] = stats;
  }

  getStatsForCampaign(campaignName) {
    StatsApi.getStatsForCampaign(campaignName).then(stats => {
      this.updateCampaignStats(campaignName, stats);
    });
  }
}

export default new StatsStore();
```

So I'm using `campaignStats` from `StatsStore` in the `CampaignStore`, but `updateCampaignStats` action would only modify the property of `campaignStats`, which make `campaignsLadenStats` fail to observe the change and compute once `campaignStats` change.

Does that mean I need to use immutable data for object, array ?

**Comment by urugator** [comment]
> but updateCampaignStats action would only modify the property of campaignStats

The problem isn't that you modify the `campaignStats`'s property, but that the property is added dynamically via `this.campaignStats[campaignName] = stats;`.
Due to a technical limitations MobX can't make the "campaignName" property observable like this.
To create dynamic key-value structure, use ObservableMap instead of plain object:
`@observable campaignStats = new Map();`
Note there  is a significant difference between replacing the whole `stats` object or just updating it's properties. If you always replace the stats object with a new one:
`this.campaignStats.set(campaignName, stats)` , it won't notify observers subscribed for the existing `stats.someProp`.

**Comment by ethanyanjiali** [comment]
That works after I replaced
```
@observable campaignStats = {};
```
with
```
@observable campaignStats = new Map();
```
and changed to use getter and setter for map. Thank you so much!

So is it a good practice is to use Map for observable, and plain object for values only? Not quite sure whether it's easy to maintain for a large project.

Anyway, thanks again and I think we could close this issue now.

**Comment by urugator** [comment]
> So is it a good practice is to use Map for observable, and plain object for values only?

Whenever you need to add/remove keys (props) dynamically you have to use Map.
Otherwise you can use object:
```javascript
@observable o = { // observable
  p1: "", // observable
  p2: [], // observable
}
// but
o.p3 = ""; // p3 is not an observable prop, nothing happens
// to add observable prop, you have to 
extendObservable(this.o, {
  p3: null, // now the o.p3 is observable
})
// however such change is not visible for any observer ... there was nothing to observe until now ... therefore you need map...
```
