### ISSUE TITLE
Atomic design, mobx configurable inject

### ISSUE THREAD

**Issue by nadzic** [mobxjs/mobx#1144]
I have a:

question, how in mobx can I create components, which are observable and also reusable (It can depend on different store).

Currently we are passing down store as props and observing.. but for example if I have one component which can use two stores, and methods regarding that two stores, how can I inject dynamically different store with ("inject") or smth like that?

In one case I want... inject("store1").. component ... -> store1.callthisMethod()
in second case I want... inject("store2").. component ... -> store2.callthisMethod()

But actually the component is the same component

**Comment by urugator** [comment]
The generic solution without the `@inject` would most likely involve something like:
```javascript
class Store {
  @computed get store() {
    if (this.somethingObservable) {
      return this.store1;
    } else {
      return this.store2;
    }
  }
}

// Then you would have some HOC which accepts this store and renders the component: 
return <Component store={store.store}>

// which is in principle the same as @inject, only the reactive function is placed elsewhere and props are used to pass deps instead of context 
```

**Comment by mweststrate** [comment]
Closing as an answer has been provided
