### ISSUE TITLE
Cannot call actions from stores in other stores with server side rendering

### ISSUE THREAD

**Issue by stelro** [mobxjs/mobx#1146]
after I make my React Application server-side rendered, I have some troubles with MobX Stores.

```
export default class Store {
  constructor(data = {}) {

    const {
      network,
      commonStore,
      userStore,

      ...rest
    } = data;

    this.network = new Network(network);
    this.commonStore = new CommonStore(commonStore);
    this.userStore = new UserStore(userStore, this.commonStore);

    extendObservable(this, rest);

  }
}
```

```
export default class UserStore {

  constructor(data = {}, commonStore) {
    extendObservable(this, data);
    this.commonStore = commonStore;
  }
}
```
I have this structure, and I hydrate and rehydrate the stores to be able to pass data between server and client. But my problem is that I cannot call any functions from other stores ( like in this example I cannot call any function from commonStore inside the userStore..)

anyone can help me with this issue ?

**Comment by mweststrate** [comment]
Depending on what is in data, `extendObservable` will create different things on the target object (see [docs](https://mobx.js.org/refguide/extend-observable.html)). For example argumentless functions will be turned into computed properties.`extendObservable` is designed to create observables (either (shallow) observable properties or computed properties). For a generic extension that literally copies properties to the target, use `Object.assign`

**Comment by stelro** [comment]
For example I have a store called HomeStore, and the store is structured like this :

```
export default HomeStore {
  constructor(data = {}, commonStore} {
     this.commonStore = commonStore;
     extendObservable(this, data);
  }

     @observable homeRegistry = observable.map();
     @observable isLoading = false;

    @action
     createHome(home) {
        return this.Homes.create(home)
          .then((home) => {
             this.homeRegistry.set(home.body.data.id, home);
             return home;
      });
  }
}
```

When the home is successfully created, i got this error : 
```
HomeStore.js:115 Uncaught (in promise) TypeError: _this2.homeRegistry.set is not a function
    at HomeStore.js:115
    at <anonymous>
```

Or If i want to call any other method or action from commonStore, I got the same error, that the _func_ is not a function.

**Comment by mweststrate** [comment]
Can you setup a reproduction in a fiddle? Does `data` redefine `homeRegistery` ?

**Comment by stelro** [comment]
here you go http://plnkr.co/edit/htuWJEZrpVgc9zIOJ2Fg?p=info

**Comment by mweststrate** [comment]
Please do boil it down to a minimal bug reproduction.

Op di 22 aug. 2017 om 15:40 schreef Stelmach Ro <notifications@github.com>:
