### ISSUE TITLE
Quest: A new name for Mobservable

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#115]
After half a year I still think Mobservable is a silly name :). So let's find a catchy one for once and for all. 

Some suggestions so far:
* Smurf (smurfs your stuff together. Smurf: Manage Ur Reactive Functions)
* Microwave
* TRP
* Bricklin (spreadsheet inventor)
* Deduce (everything from the state)
* Dedux (from deduce. Although it sounds a bit too much like redux :-P)
* Gumshoe (the detective that finds all relations in your data)

Which one sounds most catchy / appealing?

... and feel free to add more suggestions :) But please check npm first, as most nouns and vowels are already taken.

**Comment by mattruby** [comment]
+1 for gumshoe

**Comment by mweststrate** [comment]
uh oh didn't do my homework well: https://www.npmjs.com/package/gumshoe

**Comment by mattruby** [comment]
O man...  Foiled again!  This is like picking a band name!
How about overhear?


On Wed, Feb 17, 2016 at 1:33 PM, Michel Weststrate <notifications@github.com
> wrote:

> uh oh didn't do my homework well: https://www.npmjs.com/package/gumshoe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mweststrate/mobservable/issues/115#issuecomment-185368043>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by mweststrate** [comment]
Hmm... overhear has a negative connotation (at least in Dutch). I think i'll go for either Microwave "instant/easy reactivity" or Smurf (which is a really funny but not too serious name)

**Comment by Kosta-Github** [comment]
what about `microbs` as a merger of `micro` and `obs(erver)`?

**Comment by mweststrate** [comment]
Sounds like a disease :-P. `miniobs` would be saver then (and sounds like `minions` which are funny). Naming... i prefer fixing bugs :)

**Comment by xuoe** [comment]
I like the sound of `probe`, but that's already taken. Maybe `probs` or `probes`?

**Comment by jeffgran** [comment]
I like the name. "Mob" has 2 meanings that come to mind -- (1) a mob of people, meaning a very large amount of people, and (2) "the mob" meaning an organized crime syndicate, which has a sort of "above the law, better than you" feeling, and at least in american pop culture is a (albeit twisted) positive connotation, not negative.

**Comment by blaflamme** [comment]
like @jeffgran I like `mob`, it sounds cool

**Comment by mattruby** [comment]
While I agree that mob would be cool, the name is already taken on npm.
https://www.npmjs.com/search?q=Mob

**Comment by mweststrate** [comment]
`mobster` is free. Or `deryve`?

**Comment by mattruby** [comment]
mobster is pretty cool!

**Comment by blaflamme** [comment]
:+1: `mobster`

**Comment by mweststrate** [comment]
reserved `mobster` for now. Although it's a bit of a paradox to call a state management library mobster :wink:. Simply `mobx` is also available. I think the name should ideally have an `x`, `reactive` or `derive` somewhere to give a clue about the reactivity.

**Comment by mattruby** [comment]
mobx is nice as well.  Reminds me of the old modx days...  I'll all for
short names.

On Fri, Feb 19, 2016 at 8:42 AM, Michel Weststrate <notifications@github.com
> wrote:

> reserved mobster for now. Although it's a bit of a paradox to call a
> state management library mobster [image: :wink:]. Simply mobx is also
> available. I think the name should ideally have an x, reactive or derive
> somewhere to give a clue about the reactivity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mweststrate/mobservable/issues/115#issuecomment-186240974>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by blaflamme** [comment]
:+1: `mobx` it gets `mob` and reactive reference

**Comment by luisherranz** [comment]
+1 on mobx. My favorite so far.

**Comment by vikrammirla** [comment]
How about "notice".
"mobx" also sounds good

**Comment by blaflamme** [comment]
@vikrammirla close to it but with the reactive need, `notix`

**Comment by mweststrate** [comment]
@blaflamme @vikrammirla tnx! `notix` is not bad but I like `mobx` better, it's funnier and it's nice that it is close to `mobservable`.

**Comment by mweststrate** [comment]
Hi all, 

Thanks for all the input so far! I think I'll stick with `mobx` as the new name for `mobservable` for now. But feel free to add more suggestions if you find something cool, since it will take a while to design a fresh logo (input welcome), update docs, blogs etc. anyway.

Tag line ideas are also welcome by the way! Currently it is (which is still ok-ish I think):
* Observable data. Reactive functions. Simple code.

But some other ideas:
1. The Transparent Reactive Programming Library
2. State management made easy
3. State done differently.
4. Keeps your derivations in line

I think ideally the tag line should imho express the value (simple, efficient, unobtrusive, ..), is a subtle reference to the maffia, and makes it clear that it is based on (transparent) reactive programming.

^ @kmalakoff @capaj @tetsuo @dschalk @dslmeinte @cydmax @ikido @chauthai @kenneth_chau ^

**Comment by capaj** [comment]
@mweststrate great pick. mobx is certainly better than mobservable. It's a mouthful, glad we can get it shorter.

When do you get to releasing mobx 2.0.0? Or will you release it as a new project with 1.0.0 version?

I would like a tagline something like:
Observable data + Reactive functions = State management made easy

**Comment by kmalakoff** [comment]
How do you pronounce mobx? Could someone write one of those [phonetic pronunciation bracketed things](http://www.oxfordlearnersdictionaries.com/about/pronunciation_english)? moʊ-bex ?

**Comment by mweststrate** [comment]
@kmalakoff hmm good question, I just assumed mob-X, (since, well, the mob) but on the other hand mÓbex is funnier / easier to pronounce and the natural thing to do for native English speakers I guess?

**Comment by kmalakoff** [comment]
Thinking about it...I'm not even sure about how mobservable is pronounced. I always say em-observable but it could be mob-servable!

I guess my point is that mobx might be a bit hard to know how to pronounce in English. mobex is easier but it is missing the 's'. Not sure and I do not have a real recommendation, but I'm just thinking the name should be easy to know how to pronounce. 

Not sure if anyone else had this thought or if it is important...just a mobservation

**Comment by ikido** [comment]
I like your idea of using reference to mob as mafia — it is something easy to remember. The mob always react on changes, the mob keeps an eye on your data

**Comment by dslmeinte** [comment]
"Nice reactive app you've got there - be a shame if something happened to
it..." ;)

On Sat, Feb 20, 2016 at 6:32 AM, Alex Ponomarev <notifications@github.com>
wrote:

> I like your idea of using reference to mob as mafia — it is something easy
> to remember. The mob always react on changes, the mob keeps an eye on your
> data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mweststrate/mobservable/issues/115#issuecomment-186514869>
> .
>



-- 
With kind regards,


Meinte Boersma (drs./M.Sc.)

Independent consultant and expert in
domain modeling and model-driven software development (MDSD).
Web site: http://www.dslconsultancy.com/
Blog: http://dslmeinte.wordpress.com/
Twitter: http://twitter.com/meinte37

**Comment by ikido** [comment]
@dslmeinte You ask me to manage you state, but you don't ask with respect =)

**Comment by xuoe** [comment]
[keek](https://en.wiktionary.org/wiki/keek)
[obelix](https://en.wikipedia.org/wiki/Obelix)
oberlay

**Comment by nightwolfz** [comment]
Something opposite to redux, **Oxide** ?

**Comment by kenotron** [comment]
I humbly suggest Mobius. It is a shape with one surface. Look at this article:

https://en.m.wikipedia.org/wiki/Möbius_strip

The physical shape reminds me of the infinity symbol as well. That could be a good tie in for your new logo.

**Comment by tetsuo** [comment]
@dslmeinte 
> "Nice reactive app you've got there - be a shame if something happened to
it..." ;)

Haha

**Comment by tetsuo** [comment]
I can only come up with words related to _voyeurism_, _peeping_ and such :smirk:

I don't know, `perv` maybe? :bowtie:

`mobius` sounds cool btw, how about [`moebius`](http://butdoesitfloat.com/filter/jean-giraud)?

**Comment by tetsuo** [comment]
Well, while we're at it, any ideas for the logo? that also needs to be taken into consideration.

**Comment by jeffgran** [comment]
OK, I had a couple of more ideas last night:

* AutoData -- that's kinda what it is. It automatically manages your data so you don't have to imperatively update things. also I thought that a big **A.D.** for the logo would look cool and be reminiscent of A.D. as opposed to B.C. -- like we're entering the new age of auto data.

* Auto-Deriver -- along the same lines but it's automatically deriving things. Not in love with this but I also think that "Deriver" could be a source of some fun word-play -- "Limo Deriver"? "Taxi Deriver"? "Screw Deriver"? :P

* rivlets -- I think this is my favorite. came up with this while picturing the data flow in my app. There are various stores (water sources) and using chains of observable filters I can subdivide them into specific sets of data, and then they recombine at the component level. It's a network of interconnected nodes,  but it's a /directed/ graph, with the data flowing from top to bottom, but splitting and recombining as necessary, like a network of interconnected rivers. so "rivlets". Google image search turned up this as an example: [rivlets](https://www.flickr.com/photos/46357117@N00/457723256).

Plus I like how it follows with the "R" theme of all the React-related stuff. "Yeah, I'm using react/rivlets for this new project I'm working on". 

( huh, just looked up the word and apparently "rivulets" is the correct term. But I kinda like "rivlets" better and it not being "correct" might make it more easily searchable...)

**Comment by mweststrate** [comment]
Thanks guys, a lot of cool suggestions!

`oxide` sounds cool, is taken on npm but `oxyde` is still available

`mobius` is also cool, especially for the logo and mathematical background. Sadly, already taken as well and seems to be too young to exchange the name.

`rivlet(s)` is really awesome @jeffgran! Its a nice conceptual match, starts with an 'r', rememberable and fit for a nice logo. And still available on npm (well, not anymore ;-)). I think the plural form is the best isn't it? I think I like it even more than `mobx`, although it is less funny.

@tetsuo: yeah the lib definitely needs a fresh logo, but well that depends on the name first. But feel free to design one ;-)

**Comment by mweststrate** [comment]
another possibility which I forgot to write down [`sela(h)`](https://en.wikipedia.org/wiki/Selah), ancient musical term which roughly translates to "stop and listen". Available on npm

**Comment by chauthai** [comment]
Inspired by `rivlet(s)` I would suggest:
`re-obs` the short form for reactive objects. It is still available on npm!

**Comment by tetsuo** [comment]
I liked rivlet too!

**Comment by jeffgran** [comment]
@mweststrate glad you liked it :) Yeah, I agree plural makes more sense, since the idea is that there's multiple streams of data diverging and converging.

idea for tagline: "Easy reactive data-flow"

**Comment by tcrognon** [comment]
Big +1 for rivlets!

**Comment by blaflamme** [comment]
@jeffgran rivlets sounds great but too close from an already project named [rivets](https://www.npmjs.com/package/rivets) :(

**Comment by mweststrate** [comment]
Also, this ain't helping for rivlets: http://nl.urbandictionary.com/define.php?term=Rivlets, but not sure whether that is a really common interpretation of the word.

**Comment by tetsuo** [comment]
@mweststrate Haha, now that's truly a vivid interpretation.

**Comment by mweststrate** [comment]
Ok, the final verdict!

![screenshot from 2016-02-24 20-32-13](https://cloud.githubusercontent.com/assets/1820292/13298149/e571c13a-db35-11e5-867b-5584ae0ec92c.png)

The library name will be: `MobX`. Technical name (for packages, namespaces and such): `mobx`.

Tag-line (probably): `Simple, scalable state management`.

Logo submissions are welcome if somebody feels for it.

**Comment by dalcib** [comment]
+1 to mobx

**Comment by chauthai** [comment]
mobx, is that the new rap mastermind? :-)
:+1:

**Comment by mweststrate** [comment]
It has it's own conference already :) http://2016.mobxcon.com/

**Comment by luisherranz** [comment]
I prefer mobx as well.

Just curious, will you create a github org for it or it will remain under your personal account? [Mobx](https://github.com/mobx) is taken but [mobxjs](https://github.com/mobxjs) is not.

**Comment by tetsuo** [comment]
ah good old `js` appendix :+1:

**Comment by mweststrate** [comment]
ah an org is a pretty good idea, tnx!

**Comment by mweststrate** [comment]
Created the org. Just let me know if you want to join!

**Comment by capaj** [comment]
@mweststrate I would love to join!

**Comment by blaflamme** [comment]
Would like to join too, I'm excited by this project :)

**Comment by evoyy** [comment]
Unfortunately this has broken all the links which point to https://mweststrate.github.io/mobservable/

**Comment by mweststrate** [comment]
Yep, I noticed that as well. Still migrating stuff. But sadly github
correctly forwards the old urls to the new ones for the repo's, but not for
the github-pages :(

Op vr 26 feb. 2016 om 03:58 schreef evoyy <notifications@github.com>:

**Comment by luisherranz** [comment]
Can't you create that github page again and add a JS redirection?

**Comment by mweststrate** [comment]
Not sure, then I need a repo called `mobservable` with a `gh-pages` branch,
but creating a new `mobservable` repo on my account will probably kill the
automated repo forward that was created after transferring the repo to
`mobxjs`

Op vr 26 feb. 2016 om 09:37 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
Uhm... you are right. Then it's a github thing:
https://github.com/dear-github/dear-github/issues/135

**Comment by mweststrate** [comment]
MobX has been released! `mobx@2.0.0`, `mobx-react@3.0.0`, `mobx-react-devtools@4.0.0`. 

Boilerplate projects, fiddles, logo, some doc updates will follow.

**Comment by mweststrate** [comment]
Closing the issue. Thanks for all the input!

**Comment by srobinson** [comment]
Really enjoyed following your path to mobxjs. I would have chosen Frank. He's got all the moves.

> Frank:
open, honest, and direct in speech or writing, especially when dealing with unpalatable matters.

**Comment by olee** [comment]
As I got interested in this just an OT question on this old one:
What does the "mob" in "mobx" (and previously mobservable as I just found out") actually stand for? :D

**Comment by capaj** [comment]
@olee I always thought M was for Michael. Observable is the name of the pattern. I might be wrong though.

**Comment by dslmeinte** [comment]
> @olee I always thought M was for Michael. Observable is the name of the pattern. I might be wrong though.

Originally, MobX was call MObservable, with M standing for Mendix predominantly, and partially Michel (you know, for @mweststrate ). I know this for a fact, as Michel and I were on the same team, project, and even the same desk, at a company called Mendix, in those days.
This became MobX after shortening (and “fancyfying”) the name. The “mob” connotation is sort of a happy coincidence, I guess.
