### ISSUE TITLE
Why jsfiddle in mobx3.0 docs use mobx2.0?

### ISSUE THREAD

**Issue by NE-SmallTown** [mobxjs/mobx#1154]
[The mobx website](https://mobx.js.org/intro/overview.html)(which is 3.0) offer an online jsfiddle [sample](http://jsfiddle.net/mweststrate/wgbe4guu/) but the mobx file of External Resources use mobx-2.0.0, and I try to remove it and import 3.0.0 file, it will throw error

```
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at mobx-react@4.2.2:8
    at React__default (mobx-react@4.2.2:4)
    at mobx-react@4.2.2:5

Inline JSX script:21 Uncaught TypeError: observer is not a function
    at <anonymous>:21:17
    at run (JSXTransformer.js:184)
    at check (JSXTransformer.js:238)
    at loadScripts (JSXTransformer.js:291)
    at runScripts (JSXTransformer.js:320)
```

Note: I don't change mobx-react in the External Resources, I just change mobx-2.0 to 3.0 of the External Resources. (i.e. just change `https://npmcdn.com/mobx@2.7.0/lib/mobx.umd.js` to `https://npmcdn.com/mobx/lib/mobx.umd.js`)

**Comment by urugator** [comment]
Btw 
>**Create a minimal reproduction based on this [codesandbox](https://codesandbox.io/s/2vmzpM0wK)**

works no longer as well, seemingly decorators stopped working...

**Comment by mweststrate** [comment]
@urugator the codesandbox samples are broken due to babel misconfiguration, see https://github.com/CompuIves/codesandbox-client/issues/151

**Comment by mweststrate** [comment]
@NE-SmallTown thanks for reporting, this one should work properly: https://jsfiddle.net/mweststrate/f0dptdau/2/

The other setup was still based on in browser JSX transformers of react 0.13

**Comment by mweststrate** [comment]
Updated the links in readme and issue template for now

**Comment by mweststrate** [comment]
N.b. note that the sandbox issue has been fixed in the mean time
