### ISSUE TITLE
Appropriate components do not remount when I swap items in an observable array

### ISSUE THREAD

**Issue by gevgeny** [mobxjs/mobx#1159]
I need to render non-static list of components of different type. When i swap 2 items in an observable array in one transaction: 
```js
store.list = [store.list[1], store.list[0]];
```
Neither the first items nor the second call `componentDidMount`/`componentWillUnmount` methods (Although they re-render correctly).
And they do when item is removed and then added to a new position in the array: 
```js
const component = store.list[0];
store.list = [store.list[1]];
store.list.push(component);
```
Here is a simple live example https://jsfiddle.net/99yeozkj/4/. (console.log is not called when click the first button)

Is it correct behavior ?

**Comment by mweststrate** [comment]
Your second implementation notifies React twice about a change, so it will render twice, first the one-item list (unmounting the second component), then a list with two items (re-mounting the component). 

The proper way to  solve this is to use `action`. In that case React is notified only once, regardless your implementation, see https://jsfiddle.net/mweststrate/99yeozkj/5/

(Also note, that React would have rendered both your implementations only once if you would have been using proper onClick handlers from react, as React will then batch it's updates until the end of that event handler)

**Comment by gevgeny** [comment]
> The proper way to solve this is to use action. In that case React is notified only once, regardless your implementation, see https://jsfiddle.net/mweststrate/99yeozkj/5/

Sure. but the problem is that I need `componentDidMount` to be called. And I am wondering how 2 components can be swapped and non of them called componentDidMount/componentWillUnmount ?

**Comment by mweststrate** [comment]
> Sure. but the problem is that I need componentDidMount to be called

That sounds pretty weird to my, that is actually what React really hard
tries to avoid in the first. Why would you want such a thing?

The simplest way to achieve it is passing `key={Math.random()}` in ;-)

Op di 5 sep. 2017 om 16:44 schreef Eugene Gluhotorenko <
notifications@github.com>:

**Comment by gevgeny** [comment]
> Why would you want such a thing?

Probably my case is a bit tricky: I attach `ResizeSensor` from [css-element-queries](http://marcj.github.io/css-element-queries/) on `componentDidMount ` and detach it on `componentWillUnmout` to track size changes of my components. But the problem is that it stop working when i move a component into another position. And re-mounting used to solve this problem before i implemented the move operation into one `@action`

>The simplest way to achieve it is passing `key={Math.random()}` in ;-)

Yea, but it also renders the component on every parent render. 

Anyway you helped me to understand that the issue is not about mobx and it is just a natural react behavior for components with the `key` prop. I should try to use another lifecycle methods. 
Thank you very much.

**Comment by mweststrate** [comment]
hmm, componentDidRender might help you out in that case? It is triggered
every time, but you probably could verify index on dom level. Or you could
pass the index explicitly in as prop and check it in
componentWillReceiveProps?

Op wo 6 sep. 2017 om 08:31 schreef Eugene Gluhotorenko <
notifications@github.com>:

**Comment by gevgeny** [comment]
>Or you could
pass the index explicitly in as prop and check it in
componentWillReceiveProps?

Yea, that is exactly I am going to start with ;)
