### ISSUE TITLE
AutoRoundNumbers for simulated fixed point numeric processing

### ISSUE THREAD

**Issue by jason-henriksen** [mobxjs/mobx#1161]
3. [ X ] Idea:
  * [ X ] What problem would it solve for you?

Most web sites have to deal in money.  JavaScript is terrible at handling money.   The ability of mobx to clean up questionable data is an appealing way to force JavaScript to handle numbers more reliably. 
 A new flag could cause mobx to automatically scrap away rounding errors.

  * [ X ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?  
I could see this in either the core or in a utils package.  I think any website that has to do arithmetic on monetary values would benefit.

  * [ X ] Are you willing to (attempt) a PR yourself? 
Yes

---------------------------
I am considering writing a new feature pull request, but I want to get feedback before I start writing it. 

I have a C# rest service that returns many fixed point decimal numbers representing dollars and cents in a deeply nested JSON tree.  They come down to javascript, get treated like the floating point numbers and you quickly run into the old ( 0.1 + 0.2 != 0.3 ) problems.

These are the standard ways of dealing with that problem and why I'm unenthusiastic about them:
1) **treat everything as a long count of pennies**:  I don't have to do that in C# land because I have a decimal type that can handle arithmetic correctly.  There is too much legacy code and data to convert everything to pennies.  Plus, you forget one conversion somewhere and suddenly the data is a mess.
2) **use something like decimal.js**:  When if receive the JSON from the service, I just drop it into mobx and it brilliantly makes everything observable all the way down through the tree.  Doing a recursive tree search to find all the numbers and turn them into a decimal library object might work with mobx, but I'm not completely convinced.   Also, decimal.js objects can't use standard +-/* operators so the code gets very ugly.  I also have to worry about serialization back up to C# and it's just yucky dealing with non-numeric values when serializing.  Using an api like that would be a lot of messy work that I'm not certain would work in the end.

My proposed solution:  Javascript can do the right thing if you don't mind rounding a lot.  
You can round 2 digits deep and keep the variable numeric by using:
     numVar = Math.round(num + "e+2")  + "e-2"

I am proposing to add a flag to mobx named:  AutoRoundNumeric.  When true, this value would cause the method observablevalue.set() to check if the input value is numeric and automatically apply the rounding before calling prepareNewValue().   If ES6 is available, we could use the isFinite() and isSafeInteger() methods to avoid rounding that we don't need.  

I considered trying to use an interceptor, however my observables aren't part of a well defined store.  adding an interceptor to hundreds of recursively discovered variables seems possible, but heavier than adding a global flag for a desired global behavior.   

Setting the AutoRoundNumeric flag would absolutely have a small negative impact on performance.  However, if you told me that MobX would run at half the current speed but do this:
```
   @observable val=0.1;
   @action testAction(){ val = val + 0.2; }
   render(){ console.log(val); // writes 0.3 }
```
I would set that flag in a heartbeat.  I would probably have started using MobX just to get that feature alone.  Certainly, it will not solve all of my floating point issues, but it would make my life much, much easier.

Adding a flag like this would be pretty straight forward.  I'd be happy to have a go at writing the pull request for it.  I am a professional developer, so I know that I'd be adding unit tests and documentation changes as well.  Since it's a purely additive change it should not affect any existing users.

So what do you think?  If I write something like that, would you consider it?

**Comment by jamiewinder** [comment]
I don't think this is a MobX concern, but is it something it may help to solve:

```
@observable a = 0.1;
@observable b = 0.2;

@computed get sum() {
    return this.a + this.b;
}

@computed get roundedSum() {
     return Number(Math.round(this.sum + "e+2") + "e-2");
}

// sum = 0.30000000000000004
// roundedSum = 0.3
```

Adding some workarounds to common floating point errors in a state management library seems odd.

**Comment by urugator** [comment]
As @jamiewinder said it doesn't fit to MobX.
I also don't like the idea of making this behavior global, ability to provide own "modifier" would seem more appropriate.

I think it should be quite easy to traverse your JSONs and replace each float with a getter and setter which does the rounding. Then pass this fixed object to `observable` as usual and everything should be alright.

**Comment by mattruby** [comment]
I agree with Jamie. I don't think this belongs in mobx.

**Comment by jason-henriksen** [comment]
I totally understand the "what's that doing here?" concern.  

I'll leave the issue open for the rest of the day to see if anyone else has any comments and then close it if no one jumps in to support the idea.

@jamiewinder I know I could do it like that, but it will be literally hundreds of methods that I would have to write and maintain.  I'm certain that people will accidentally choose the wrong one and mess things up.  That's why it would have been nice to have it all handled "behind the scenes".

@urugator It's possible.  But I take that object and serialize it to send back to the REST service.  The decimal libraries I've been looking at  don't always serialize correctly.  (On of the serialized the numbers to base 88!?!  Like, what other program is going to correctly interpret that?!!)   Still, I'm certain I can keep hunting around until I find one that does the right thing and then recursively cram it every where it needs to go.   I was just hoping for a more "fix it all in one place" solution.

**Comment by urugator** [comment]
@jason-henriksen I don't usggest using any library, use your rounding function in that setter

**Comment by jason-henriksen** [comment]
Closing due to lack of community interest.  Thanks for the discussion.
