### ISSUE TITLE
MobX sometimes stops working completely

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx#1165]
Hello,

I have a very weird issue with one of the React-MobX apps I'm working on at work where sometimes, unpredictably, MobX stops working completely (no derivation or reaction is computed any more). 

That can happen on almost any page of the application. It can be triggered by a state change, or simply by hitting F5 to reload the app.

Actions are run, state is updated, but nothing happens. To make things worse, nothing is logged on the console. If I use `whyRun` at the end of a derivation that is run initially, it correctly lists all the observables it depends on, then promptly refuses to update when one of those changes.

Again, this seemingly happens at random, so if you get lucky it can all work fine.

I'm totally unable to give a code sample to reproduce this, because I have no idea where it comes from and the code isn't open.

I'm pretty sure that the root of the problem comes from something I do somewhere in the app, but I can't find it. I'm hoping that someone here have some clues about what could cause such an issue to give me hints about where to look at.

Thanks a lot.

**Comment by spion** [comment]
Can you use [spy](https://mobx.js.org/refguide/spy.html) to try and track the last successful derivations and reactions? The info collected might be enough to build a reproduction case after..

**Comment by JabX** [comment]
I found the first action that didn't launch its appropriate reactions, traced it to a component that is used on all the pages that could make MobX break, and removed it to see that I didn't have the problem anymore. So I know where the problem is now, thanks for the tip! I was using `spy` already to assess what was happening but didn't think of looking into it to find the last successful operations.

I'll update this issue if I find something worth reporting on.

**Comment by JabX** [comment]
I found the culprit:

(this is part of a React Component)
```ts
private readonly panels = observable.map<PanelDescriptor>();

@computed.struct
private get sortedPanels() {
    return /* lodash */sortBy(this.panels.entries(), (([_, {node}]) => this.getOffsetTop(node)));
}

private getOffsetTop(node: HTMLElement) {
    let distance = 0;

    if (node.offsetParent) {
        do {
            distance += node.offsetTop;
            node = node.offsetParent as HTMLElement;
        } while (node);
    }
    return (distance < 0 ? 0 : distance) - (this.props.scrollToOffset || 150);
}
```

You might think that the bug comes from the `do...while` loop, but actually it's the use of `this.props.scrollToOffset` (which is undefined here) that was responsible for breaking MobX in the application. This definitely looks like an odd bug, and I wrapped the `getOffsetTop` method in `untracked` to avoid it, since I'm not interested in its potential changes.

Maybe the issue is only related to `mobx-react` since it comes from observable props, and I sadly don't have the time to build a standalone exemple to reproduce the issue. 

I'm leaving this here if anyone has the time to look into it.

**Comment by mweststrate** [comment]
@JabX not sure what a PanelDescriptor is, but I could image a `observable.shallowMap` would be more appropiate here?

If `scrollToOffset` is undefined, I would assume than at least some error shows up in the console?

**Comment by mweststrate** [comment]
Closing as answer has been provided
