### ISSUE TITLE
Use Proxy if available in dev mode to detect access non-exists properties of observables

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#1166]
There was a great suggestion from @caesarsol, originally from https://github.com/mobxjs/mobx/issues/1076#issuecomment-327263792:

>  what about using Proxy only in development, to check for uncorrectly used keys or unexistant ones?

This sounds as very good improvement of mobx developer experience. From my point of view, one of the frequent mistake done by developer is accessing to non-existing keys. It comes as hard to debug error, which looks like "my view is not updated, but it should!". This is already noted in docs as common [pitfall:](https://mobx.js.org/best/pitfalls.html)

> object.someNewProp = value is not picked up

Complete suggestion would be like this:

1. If environment support native Proxy, then:
2. Wrap all created observables in it, and
3. Detect all access to non-existing keys of original observable, if detected:
4. Warn (or even error) developer in console about it.

**Comment by urugator** [comment]
Both (get/set) operations are meant by *accessing*?

Maybe someone adds non-observable fiels on purpose? (warns on "valid" usage?)  

How does it relate to `extendObservable`? For example:
```javascript
const o1 = Mobx.observable({});
Mobx.extendObservable(o1, { a: "a" }); // extends proxy
o1.b; // warns?
// BUT:
const o2 = {};
Mobx.extendObservable(o2, { a: "a" }); // extends plain
o1.b; // does not warn? 
```

**Comment by caesarsol** [comment]
Hi, glad you found the time to pick up my idea! :)

**Comment by Strate** [comment]
@urugator

> Both (get/set) operations are meant by accessing?

I think yes, it could just keep things simple.

> Maybe someone adds non-observable fields on purpose? (warns on "valid" usage?)

From my point of view it is strange, to keep non-observable fields. But, if it became a pain, we can handle _get_ operations only inside tracking function, and _set_ operation only inside transactions when strict mode is on, and always when strict mode is off.

Or we can even do not handle _exists_, but _not observable_ fields, and just track only _non-exists_ fields.

> How does it relate to extendObservable? For example:

We can keep `WeakMap` of created proxy objects, where store `Proxy` -> `observable instance`, to get original observable inside `extendObservable` method:

```
function extendObservable(observable, extraFields) {
  if (observable instanceof Proxy && globalProxifiedObservables.has(observable)) {
    observable = globalProxifiedObservables.get(observable)
  }
}
```

**Comment by Strate** [comment]
@urugator, oh, yes, I can see that case, because `extendObservable` do not create new observable, but changes exists plain to observable, it seems to be impossible to handle that case :(

**Comment by caesarsol** [comment]
Well, after ESnext class properties there would be no problem, right?

As for `extendObservable`, we could simply require it's called on an observable. It would be breaking but an easy fix... (My suggestion was made in the scope of a threads of proposals for the new major)

**Comment by urugator** [comment]
> it is strange

It's definitely not common, but introducing warnings to working code or perhaps killing some valid usages would be unfortunate...
From the top of my head I think there were some edge cases where people used non-observable fields to store side effects of computed.

> handle get operations only inside tracking function, and set operation only inside transactions when strict mode is on

The tracking/strict would probably be the reasons why the field was not intentionally made observable, so limiting the warning to tracking/tx doesn't solve the problem.
(You know, without tracking/tx it doesn't really matter whether you make fields observable or not, so if there is an intention, it somehow relates to tracking...)

The intention is good, but I am just afraid whether it won't be a source of another confusion/problems.

**Comment by Strate** [comment]
@urugator what do you think about to warn developer of access _non-exist_ fields only inside track/action methods?

And, of course, it should be completely opt-in feature.

**Comment by urugator** [comment]
> warn developer of access non-exist fields only inside track/action

I don't see how limiting the warning scope to track/action should help? I mean, how is it better/different then warning everywhere? 

> opt-in

globally I suppose?

**Comment by Strate** [comment]
> I don't see how limiting the warning scope to track/action should help? I mean, how is it better/different than warning everywhere?

I misread this https://github.com/mobxjs/mobx/issues/1166#issuecomment-329807930 sorry.
I think we can warn everywhere, but only about non-existing fields.

What about Proxy of initially plain value: we can replace prototype of object, it will helps us to catch access to non-existing properties:

```js
const proxyHandler = {
    get(target, name, receiver) {
        console.log("get", target, name, receiver)
    }
}

function makeAProxy(target) {
    const proto = new Proxy(Object.getPrototypeOf(target), proxyHandler)
    Object.setPrototypeOf(target, proto)
}

const target = {}
makeAProxy(target);
target.blabla // logs get {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …} blabla {}
```

**Comment by mweststrate** [comment]
I think this could add some value, but only for conversion done through `observable(object)`. As that will (deep) clone `object` anyway (so it can safely be proxied). For extendObservable, that is often used as ES5 alternative to declaring `@observable` fields and supposed to leave other fields non-observable. 

I agree that abusing `extendObservable` to create 'maps'  is a common mistake, but I think from our side of things indistinguishable from proper usages. But:

```javascript
const x = observable({ b: 3 })
x.c = 4
```

is most probably an mistake indeed, so proxies warning on these cases could help people out. If people want to mix observable and non-observable fields on the same object, they would probably be  using classes / constructor functions (leveraging `extendObservable`) anyway.

**Comment by caesarsol** [comment]
@mweststrate It makes sense, `extendObservable` should only be useful in ES5 environments, and those does not support `Proxy`!

**Comment by urugator** [comment]
Not ES5, but **non-ESNext** (decorators are stage2, fields stage3 + some time until they land in node/browsers).
@caesarsol Availability of proxy is absolutely unrelated to the need for `extendObservable` in this case. If proxy would be available and required in general (no just opt-in devel feature), then this issue would not even exist.

**Comment by caesarsol** [comment]
No, I'm talking about real ES6 environment, since Proxy is non-polyfillable, and any other feature you mention is transpilable.

Approximately, if you need extendObservable you don't have Proxy...

**Comment by mweststrate** [comment]
Closing this issue for now, to not further complicate the observable construction mechanisms, and rather solve it in the general proxy support story.
