### ISSUE TITLE
Multiple Mobx instances in a single app

### ISSUE THREAD

**Issue by Raathigesh** [mobxjs/mobx#1173]
I want to have multiple mobx instances in an app. The app would have one and then each plugin would have their own. But I still want the component from the app to react to the changes of the observables in the plugin.

Is this achievable without needing to have mobx as a peer dependency?

**Comment by mweststrate** [comment]
`@observer`  will only react to observables created by the same `mobx` it is depending itself. In other words; you should have only one.

Peer dependencies are the proper way to do this. See also https://github.com/mobxjs/mobx-react/issues/319#issuecomment-330174910 and links in that comment fur further reading. This works the same as how you would use `React` in component libraries. 

Closing as duplicate now, until there is a very clear reason why you can't use peer dependencies.

**Comment by Raathigesh** [comment]
Thank you for the quick reply and the reference.
