### ISSUE TITLE
Store can be modified without action in strict mode (RN)

### ISSUE THREAD

**Issue by ethanyanjiali** [mobxjs/mobx#1175]
Welcome to MobX. Please provide as much relevant information as possible!

If at all possible, provide a **minimal** sample reproduction. **Create a minimal reproduction based on this [jsfiddle](https://jsfiddle.net/mweststrate/f0dptdau/2/)**

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [x] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [jsfiddle](https://jsfiddle.net/mweststrate/f0dptdau/2/)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

```
console.log(mobx.isStrictModeEnabled()); // true
console.log(Store.value); // Object {…}
Store.value= {}; // no error
console.log(Store.value); // Object {$mobx: ObservableObjectAdministration}
```

I'm using mobx in React Native with mobx-remotedev, could that be related?

**Comment by mweststrate** [comment]
See also the docs, strict mode only protects observables that are being observed. So as soon as you would use `Store.value` in autorun or an observer component, the assignment would throw.

**Comment by ethanyanjiali** [comment]
Thanks for explanation. So non-visual states are vulnerable.

**Comment by mweststrate** [comment]
No, they are safe to modify as mobx won't doing anything in response.
`useStrict` is not a security mechanism, but a mechanism that helps you to
make sure that mobx doesn't have any work to do (distributing data changes)
at unintended points.

Op do 21 sep. 2017 om 11:29 schreef Ethan Yanjia Li <
notifications@github.com>:
