### ISSUE TITLE
observable.map() changing key order

### ISSUE THREAD

**Issue by DeDuckProject** [mobxjs/mobx#1188]
Got a question over here:
I'm using observable.map and the order of the keys matters to me.
The problem is, that as far as I've seen the best solution here would be to delete some of the map items and re-add them in the correct order. This is not very nice though.

Is there anything I'm missing in the API that would let me change the order of the keys in the observable map?

Thanks 🦆

**Comment by mweststrate** [comment]
Nope, it is not possible to control the order of keys in a map, to stay
close the the semantics of the standard ES 6 maps
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Map

Op ma 2 okt. 2017 om 12:15 schreef Iftach Yakar <notifications@github.com>:

**Comment by DeDuckProject** [comment]
I see.
Thanks @mweststrate
