### ISSUE TITLE
Observer stops working in production in Electron app

### ISSUE THREAD

**Issue by elan** [mobxjs/mobx#1189]
MobX is mostly working great, but there's one component in particular which doesn't re-render when the store changes, but _only_ in production (which is super confusing). I'm posting the component here in case it's obvious what I'm doing wrong (as opposed to it being a bug somewhere).

```js
import React from 'react';
import { observer } from 'mobx-react';
import PropTypes from 'prop-types';
import store from '../store/store';
import styles from './ProgressBar.css';

@observer
export default class ProgressBar extends React.Component {
  static propTypes = {
    display: PropTypes.bool.isRequired
  };

  render() {
    return (
      <div>
        <div
          className={styles.progressTrack}
          style={{
            width: store.app.windowSize,
            position: 'absolute',
            top: this.props.display ? store.app.windowSize : 0,
            transition: '0s top ease-out'
          }}
        >
          <div
            style={{
              width: `${store.player.progress}%`,
              transition: '.1s width ease-out',
            }}
            className={styles.progressBar}
          />
          </div>
      </div>
    );
  }
}
```

There are two stores referenced in this component:

```js
export default class RootStore {
  app: AppStore;
  player: PlayerStore;

  constructor() {
    this.app = new AppStore(this);
    this.player = new PlayerStore(this);
 }
}
```

And the property which is being referenced which doesn't trigger the re-render is a computed one.

```js
  @observable time: ?number;

  @computed get progress(): number {
    const track = this.currentTrack;
    if (track.metadata && track.metadata.duration && this.time) {
      return parseInt((this.time / track.metadata.duration) * 100, 10);
    }

    return 0;
  }
```

**Comment by mweststrate** [comment]
Quick check: does removing `propTypes` from the componenents make a
difference? (Reveal the problem in dev as well)

Op do 5 okt. 2017 om 00:56 schreef Elan Feingold <notifications@github.com>:

**Comment by elan** [comment]
@mweststrate ~ thanks for the quick reply (and also for mobX!)

I tried removing `propTypes` from `ProgressBar` and that didn't make a difference in debug (still worked) or production (still doesn't work). Not sure if you meant just from the problematic component or all components up the tree (only did the first).

If you have any other suggestions or ways I can debug, please let me know.

**Comment by elan** [comment]
Did a bit of spying, and this is what I see in debug:

```
action: processTimeline
compute: progress
action: processTimeline
compute: progress
reaction: Reaction[FlippingPoster#0.render()]
reaction: Reaction[ProgressBar#0.render()]
```

And this is production:

```
action: processTimeline
compute: progress
action: processTimeline
compute: progress
reaction: Reaction[FlippingPoster#0.render()]
```

`FlippingPoster` is a sibling component which (a) has `propTypes`, `defaultProps`, and passes `store.player.progress` down via prop to a child component.

I tried making a bogus child component to pass down the `progress` value to see if that make a difference, and it did not:

```js
class Bogus extends React.Component {
  render() {
    return <div style={{width: this.props.progress}} />;
  }
}

...
render() {
    return (
        ...
          <Bogus progress={store.player.progress} />
        ...
```

**Comment by elan** [comment]
I've tracked this down, and I have to apologize, it was no fault of MobX, but rather of my WebPack configuration, which (silently?!) broke decorators, needed this change:

```diff
--- a/webpack.config.base.js
+++ b/webpack.config.base.js
@@ -16,7 +16,8 @@ export default {
       use: {
         loader: 'babel-loader',
         options: {
-          cacheDirectory: true
+          cacheDirectory: true,
+          plugins: ['transform-decorators-legacy', 'transform-class-properties']
         }
```
