### ISSUE TITLE
Provider and inject leave class variables behind

### ISSUE THREAD

**Issue by Yutenko** [mobxjs/mobx#1191]
Mobx doesn't reflect changes any longer. If iam using the provide-inject-pattern, the store is avaiable in the component, but only the bounded functions (action.bound) are visible. Any observeable value is not visible. Therefore the component cannot rerender on change.

Store.js
```
export default class Store{ 
  @observeable loginname = ""
  @observeable password = ""
  @observeable users = []

  @action.bound setPassword (password) {
   this.password = password
 }

 @action.bound setLoginname (loginname) {
   this.loginname = loginname
 }
}
```

HoC
```
export function withProvider (WrappedComponent) {
  @observer
  class ProviderClass extends React.Component {
    render () {
     const store = new Store()

      return (
        <Provider store={this.store}>
         <WrappedComponent {...this.props} />
        </Provider>
      )
    }
  }
  return ProviderClass
 }
```

Component
```
@inject('store') @observer
class Login extends React.Component {
  render () {
    const store = this.props.store
    return ( 
    <input value={store.loginname}  onChange={e => store.setLoginname(e.target.value)}/>
   )
 }
}
```

At this point, if store.loginname ist changed by an input field, the variable doesn't reflect the change. So the value keeps empty.

I've done it the same before in other projects, first time with this versions of react/mobx

.babelrc
```
{
 "presets": ["es2015","react","stage-0"],
 "plugins": ["transform-class-properties","transform-decorators-legacy"]
}
```

package.json
```
{
  "name": "ktool",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "node server.js",
    "start": "NODE_ENV=production node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.18.2",
    "cookie-parser": "^1.4.3",
    "express": "^4.15.4",
    "isomorphic-unfetch": "^2.0.0",
    "json-stringify-safe": "^5.0.1",
    "jsonwebtoken": "^8.0.1",
    "material-ui": "^1.0.0-alpha.21",
    "mobx": "^3.3.0",
    "mobx-react": "^4.3.3",
    "moment": "^2.18.1",
    "mysql": "^2.14.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router-dom": "^4.2.2",
    "serve-favicon": "^2.4.4",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-import": "^1.5.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.28.7",
    "file-loader": "^0.11.2",
    "json-loader": "^0.5.7",
    "script-loader": "^0.7.1",
    "style-loader": "^0.18.2",
    "webpack": "^3.6.0"
  }
}
```

Even if i create a singleton Store in the storefile instead of export default class
```
const store = new Store()
export default store
```

and importing it to the component without Provider/inject
```
import store from '../stores/store'

render () {
 store.loginname // doesn't exist
}
```

**Comment by mweststrate** [comment]
@Yutenko would you mind tidying up your question a bit? It's hard to make sense of the question now

**Comment by Yutenko** [comment]
@mweststrate 
UPDATE: Made it more readable didn't know how the github editor was supposed to format code

**Comment by mayorovp** [comment]
What is the `@observeable` decorator?

**Comment by mweststrate** [comment]
@Yutenko It is unclear to me in your code how / where either `withProvider` or `LoginComponent` are used. Anyway, in the `render()` method you are created a new Store everytime it rerenders, so this soon will result in a plethorea of stores and only one will be rendered by the `Login`. So it seems you need to restructure  your app a bit. For example by storing one store instance in / near the root component of your app.

Also why is `withProvider` are HoC? You should provide the store only once in your app, so it has hardly any use to make it a HoC.

**Comment by mweststrate** [comment]
@mayorovp https://mobx.js.org/refguide/observable-decorator.html. (Plz take the effort to read docs first before asking questions that are clearly answered by them)

**Comment by mayorovp** [comment]
@mweststrate `@observEable`

**Comment by Yutenko** [comment]
@mweststrate 
Many thanks for your help. You are right, thats my problem. I've created a HoC and exported it like so
``
export default withProvider(LoginComponent)
``

This should be on the root file i guess as first component in the JSX Tree.
But this creates a new Store every time. What got me wondering was the fact, that a singleton store, that is exported right from the Store.js-File is also not reflecting my changes. 

I will close the thread and edit my last answer, if iam going to find my missing piece.
