### ISSUE TITLE
computed functions don't recalculate when observable arrays change

### ISSUE THREAD

**Issue by michelmattos** [mobxjs/mobx#1193]
Have a look at this small example (https://codesandbox.io/s/vvwlz914ml). There is a `store` which has a `todos` (observable array) and `computedTodos` (which returns the `todos` without changing it). Also, there is two "enhanced" component: `InjectTodoList` (which uses `inject` to inject the `computedTodos`) and `ObserverTodoList` (which uses 'observer').

The problem is: when I click "Add todo" button only the `ObserverTodoList` gets updated. Is this a problem with `inject` HOC or am I doing something really stupid, lol?

**Comment by michelmattos** [comment]
Also, if you change `return this.todos` to `return this.todos.slice()` on `computedTodos` then the `InjectTodoList` gets updated but the `ObserverTodoList` stop working.

**Comment by mweststrate** [comment]
@michelmattos `inject` doesn't imply `observer`, so you have to apply both (and in the right order).

**Comment by michelmattos** [comment]
Ah, cool. I thought that the `inject` already did that with its mapper function. But now we arrived where I want to go :P
In this version of the latter example (https://codesandbox.io/s/qkw9x3nypq) I changed the `computedTodos` to return `this.todos.slice()` instead of just `this.todos`. Also, I combined both `InjectTodoList` and `ObserverTodoList` into `ConnectedTodoList` (yeah, I know, it's not a good name, lol).
If you activate the "visualize component re-render" on the DevTools and click on "Add todo", you will see the `ConnectedTodoList` being rendered twice. Putting a `console.log` inside the `TodoList`'s render will show that the "dumb" component only render once. Any idea what's going on here?

**Comment by mweststrate** [comment]
Didn't look into that, but not that `this.todos.slice()` marks the todos
collection as in use, starting mobx to track it (after all, if you slice
is, it means the values of the array are used in the component), while
merely passing on `this.todos` will not mark it as in use, as it is just a
pointer being passed, and the will not change by adding items to it. So it
doesnt need to be observed

Op ma 9 okt. 2017 om 21:33 schreef Michel Mattos <notifications@github.com>:
