### ISSUE TITLE
[RFC] Shorthand for computed with getter/setter pattern

### ISSUE THREAD

**Issue by maxdeviant** [mobxjs/mobx#1196]
A pattern that I find myself using quite often is something like this:

```ts
class Todo {
  @observable private _name = '';

  @computed
  get name() {
    return this._name;
  }

  set name(value) {
    this._name = value;
  }
}
```

Now, this is a lot of boilerplate for something that could be as simple as:

```ts
class Todo {
  // Open to suggestions for what we would call this :)
  @autoComputed name = '';
}
```

I find that this pattern is useful when working with domain objects (in strict mode), since I can tweak the properties anywhere without needing to introduce an `action` everytime I wish to do so.

@mweststrate What are your thoughts on adding something like this? Or have I invented a solution for a problem that I created myself (like perhaps using strict mode where it isn't actually useful/needed)? :smile:

**Comment by urugator** [comment]
Discussed in #839, also check https://github.com/farwayer/mobx-decorators#setter

**Comment by mweststrate** [comment]
Closing for duplicate
