### ISSUE TITLE
How can I use seamless-immutable when upgrde to version 3.3.1

### ISSUE THREAD

**Issue by kingller** [mobxjs/mobx#1201]
I format the data to seamless-immutable, then fill it to an observable value (this.data), but when I get it from this.data, the item of it is not immutable again, and the immutable data's property lost (the function as asMutable, merge, replace, etc...).  It works well in version 2.4.4, but not in 3.3.1

Can you help me please?

My code is bellow,
```js
import Immutable from 'seamless-immutable';

@observable data = [];
setTableData = (data) => {
        if (data && data.length > 0) {
            let data2 = data.map((item) => {
                item = Immutable(item);
                return item;
            });
            //The issue happens here. It is OK in data2, but not in this.data
            this.data = data2;
        } else {
            this.data = [];
        }
}
```

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#observableplainobject-will-no-longer-enhance-objects-but-clone-instead

**Comment by urugator** [comment]
I think `@observable.shallow data = [];` should fix the problem in this case.

**Comment by kingller** [comment]
@urugator I change it as you said, but it sill doesn't work.

`
@observable.shallow data = [];
`

**Comment by urugator** [comment]
What exactly? The objects inside `this.data` should be intact (still imutable) after `this.data = data2` assigment. If it's not the case please provide reproduction.

**Comment by kingller** [comment]
@urugator Sorry, it's OK now when I use `@observable.shallow data = [];`.  I only changed the code in base class, and missed the inherited place. Thank you very much.
