### ISSUE TITLE
computed observableMap property

### ISSUE THREAD

**Issue by prabirshrestha** [mobxjs/mobx#1203]
Is it possible to do something like this where the `observableMap({})`and not `observable({})` contains `computed` value?

```javascript
var person = observable({ fname: 'Prabir', lname: 'Shrestha' });
var map = observable.map({});
map.setComputed('fullName',() => {
    return `${person.fname} ${person.lname}`;
);

var fullName = map.get('fullName');
```

**Comment by urugator** [comment]
No, but you can store boxed computed:
```javascript
map.set('fullName', computed(() => {
    return `${person.fname} ${person.lname}`;
}));
```
and access it with `get`
```javascript
var fullName = map.get('fullName').get();
```

**Comment by prabirshrestha** [comment]
That works. Another similar question.

```javascript
const map = observable.map({});
map.set('time', computed(() => {
  return new Date();
}))
```

My react component then listens to the computed time from map. Is there a way to detect if anyone is subscribing to computed? If someone is subscribing to computed I want to start an interval so I can update the time. If no one is subscribing I want to disable the timer.

**Comment by urugator** [comment]
> detect if anyone is subscribing to computed

Currently not, [should be possible in future](https://github.com/mobxjs/mobx/issues/992).
However you can detect that with custom Atom.
So as a workaround you can create a wrapper, which synchronizes useage of Atom with the useage of computed - [exactly like here.](https://github.com/mobxjs/mobx-utils/issues/51#issuecomment-301452664)

**Comment by prabirshrestha** [comment]
@urugator Thanks again. It works. That is exactly what I have been looking for.

Closing the issue for now since there are other open issues tracking this.
