### ISSUE TITLE
Is it possible to batch updates from different stores?

### ISSUE THREAD

**Issue by alexandernanberg** [mobxjs/mobx#1206]
I'm curious if there is any way to batch/group updates in different stores. 

I've a ProfileStore that is dependent on a MessageStore and NotificationStore 

```js
// ProfileStore.js
import { computed, action } from 'mobx';

class ProfileStore {
  constructor(rootStore) {
    this.rootStore = rootStore;
  }

  @computed get unreadCount() {
    return this.rootStore.notificationStore.unreadCount || this.rootStore.messageStore.unreadCount;
  }

  @action fetchUnreadCount() {
    this.rootStore.notificationStore.fetchUnreadCount();
    this.rootStore.messageStore.fetchUnreadCount();
  }
}
```

The other stores basically just fetches data an assigns it to an observable. 
```js
// NotificationStore.js
import { observable, action } from 'mobx';
import axios from 'axios';

class MessageStore {
  @observable unreadCount = 0

  @action fetchUnreadCount() {
    axios(ENDPOINTS.notificationCount)
      .then(({ data }) => {
        this.unreadCount = data.count;
      });
  }
}
```

So the reason I'd like to batch or group the updates is because my observer renders twice. Once when it receives the notification count and once more when the message count resolves. I still want both actions to be separate because there still will be cases when I just need to fetch either messages or notifications.

Is it somehow possible to get functionality like `Promise.all()` but for my actions? Maybe something similar to this

```js
@action fetchUnreadCount() {
  batchUpdates([
    this.rootStore.notificationStore.fetchUnreadCount(),
    this.rootStore.messageStore.fetchUnreadCount(),
  ]);
}
```

**Comment by mweststrate** [comment]
Actions batch *per tick* (more accurately; per outer action). So note that your `then` clauses should be actions as well (they are not part of the outer `actions`!). (To avoid making mistakes with that you can enable strict mode)

If you want batch updates for multiple asynchronous processes, best safe the updates before applying them, or, indeed, join the promises and update all at once. @urugator just wrote down a nice example of that: https://github.com/mobxjs/mobx/issues/1205#issuecomment-337188426

**Comment by alexandernanberg** [comment]
Oh I've completely missed that the `then` clauses need to be `actions` as well. Nice, will be using strict mode from now on.

Okay, his example does't really do the exact same thing I'm trying to accomplish. The biggest difference is that I need to update values in different stores. But I'll look into something similar.

Thanks for you reply and great work on this library. I'm closing this issue now 😄

**Comment by urugator** [comment]
It's not ideal, but maybe you could do something like this:
```javascript
// ProfileStore.js
import { computed, action, untracked } from 'mobx';

class ProfileStore {
  @observable _unreadCount = null;
  @observable fetching = false;
  
  constructor(rootStore) {
    this.rootStore = rootStore;    
  }

  @computed fetching() {
    return this.rootStore.notificationStore.fetching && this.rootStore.messageStore.fetching
  }
  @computed get unreadCount() {    
    if (this.fetching && this._unreadCount !== null) {
      // During fetch use local unreadCount
      return this._unreadCount;
    } else {    
      // Otherwise compute dynamically  
      return this.rootStore.notificationStore.unreadCount || this.rootStore.messageStore.unreadCount;
    }    
  }

  @action
  fetchUnreadCount() {   
    this.fetching = true; 
    Promise.all([
      this.rootStore.notificationStore.fetchUnreadCount() // return Promise from fetch
      this.rootStore.messageStore.fetchUnreadCount() // return Promise from fetch
    ])
    .then(action(() => { 
      this.fetching = false;
      this._unreadCount = this.rootStore.notificationStore.unreadCount || this.rootStore.messageStore.unreadCount;
    }));    
  }
}
```

**Comment by alexandernanberg** [comment]
@urugator Yes exactly, was something similar I was thinking about. But I feel like I'm adding unnecessarily complicated code for what's really a non issue. My render method is relatively cheap so I'll maybe have to live with having one unwanted rerender. 

Thank you for your reply anyway 👍
