### ISSUE TITLE
Non-value passed to custom computed equality check

### ISSUE THREAD

**Issue by chrisdoble** [mobxjs/mobx#1208]
The documentation for `computed`'s `equals` option states

> This acts as a comparison function for comparing the previous value with the next value. If this function considers the previous and next values to be equal, then observers will not be re-evaluated.

I interpreted this to mean that custom equality functions will only ever be passed values that were returned from the derivation function. Is that correct? I believe I've found a situation where this isn't the case.

A snippet that reproduces the behaviour:

```ts
const mobx = require('mobx');
const observable = mobx.observable(0);
const computed = mobx.computed(() => observable.get() + 1, {
  equals: (old, new_) => {
    console.log(`old=${old}, new_=${new_}`);
    return old === new_;
  },
});

// Logs nothing
const dispose = mobx.autorun(() => computed.get());
// Logs "old=1, new_=2"
observable.set(1);
dispose();
// Logs "old=undefined, new_=2"
mobx.autorun(() => computed.get());
```

`undefined` was never returned from the derivation function `() => observable.get() + 1`, so I didn't expect it to be passed to the equality function. After disposing the observer and establishing a new one, I either expected the equality function not to be called, or to be called with 2 and 2.

I think this is happening because `ComputedValue::value` is assigned `undefined` when it becomes unobserved ([code](https://github.com/mobxjs/mobx/blob/ea6c823a5e6871e4f5352ed3db216003887c60b3/src/core/computedvalue.ts#L113)) and this is then passed to `equals` when it becomes observed again ([code](https://github.com/mobxjs/mobx/blob/ea6c823a5e6871e4f5352ed3db216003887c60b3/src/core/computedvalue.ts#L174-L180)). Perhaps it should be assigned `new CaughtException(null)` as it is in the constructor ([code](https://github.com/mobxjs/mobx/blob/ea6c823a5e6871e4f5352ed3db216003887c60b3/src/core/computedvalue.ts#L78)) which would bypass the equality check ([code](https://github.com/mobxjs/mobx/blob/ea6c823a5e6871e4f5352ed3db216003887c60b3/src/core/computedvalue.ts#L177))?

**Comment by urugator** [comment]
Seems like bug indeed. Summoning @jamiewinder @mweststrate
Btw the relevant behavior is discussed [here](https://github.com/mobxjs/mobx/pull/951#issuecomment-294313667) (scroll down for more)

**Comment by jamiewinder** [comment]
I think you're right about the cause and solution to this problem. I'll add a PR to sort this in the next few days if I manage to claw some free time (unless someone beats me to it!).

**Comment by mweststrate** [comment]
@chrisdoble sorry for the late response! Was kinda drown in github notifications :) Anyway thanks for the thorough analysis, I am pretty sure you are right and the correct behavior imho should be that the comparer indeed shouldn't be called in these cases. Will review asap
