### ISSUE TITLE
Cannot read property 'value' of undefined on observable object?

### ISSUE THREAD

**Issue by Kielan** [mobxjs/mobx#1209]
Why would Uncaught TypeError: Cannot read property 'value' of undefined, why is `this` undefined? Using underscore to try to check if observable value is empty

@action loadInitState() {
console.log('load from store strange behavior')
if (_.isEmpty(this.value)) {
this.value = someValue;
}

**Comment by alex-deas** [comment]
Without being able to see more than just this function any suggestions would just be conjecture. Could you post a more complete example of the class you're trying to implement?

**Comment by Kielan** [comment]
@action.bound, I had never considered the scope of mobx stores
