### ISSUE TITLE
Observable Array is being converted to Object in Android

### ISSUE THREAD

**Issue by luco** [mobxjs/mobx#1214]
I have figured out that `@observable` arrays in Android are being converted to object, in that way I can't push any data.

 This is the error that i'm getting:

```
 I/ReactNativeJS: { [TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === 'function' ? Symbol.iterator : '@@iterator']()')]
                                                             line: 97965,
                                                             column: 203,
                                                             sourceURL: 'http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }

```

This only happens when I try to push any data only to observable arrays. Non-observable arrays gets the push properly.

I'm declaring this way:

```
class MyClass {
  @observable myArray = [];
...
```

Also, when I try to use peek:

```
 @action pushIn() {
  var test = this.myArray.peek();
  test.push({valid: true});
  console.log(this.pictures.replace(teste));
}
```

It returns this:

```
ReactNativeJS: { [Error: [mobx] Modification exception: the internal structure of an observable array was changed. Did you use peek() to change it?]
                                                             line: 80472,
                                                             column: 190,
                                                             sourceURL: 'http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
```

-----
Running this packages:

```
"mobx-react": "^4.3.3",
"mobx": "^3.2.2",
"react-native": "0.47.2",
"react": "16.0.0-alpha.12",

```
This is only happening on Android, while on iOS it works as expected.
Any thoughts on this?

Thanks

**Comment by luco** [comment]
This is not related to mobx but to react. Thanks.

**Comment by urugator** [comment]
> I have figured out that @observable arrays in Android are being converted to object

What do you mean by that? Arrays are alway converted to array-like objects (faux-array).

The `peek` error is expected.

As for `iterator` error:
 > [Android's JS runtime defines Symbol, however does not define Symbol.iterator](https://github.com/facebook/immutable-js/issues/1305)

**Comment by luco** [comment]
@urugator 

On iOS, taking this action:
```
 var tg = _.get(this, target);
tg.push(data);
```

The data gets pushed into array. On Android, I can't push. It returns as a object.
