### ISSUE TITLE
npm page doesn't have a Readme.md

### ISSUE THREAD

**Issue by adrianolaru** [mobxjs/mobx#122]
The npm page is empty. :(

<img width="1211" alt="screenshot 2016-02-26 09 50 06" src="https://cloud.githubusercontent.com/assets/31248/13346378/7ca73272-dc6e-11e5-9dd8-34fd5ef57c77.png">

**Comment by mweststrate** [comment]
Hi @adrianolaru that is correct, we are currently migrating the repo. But note that the package is still available as `mobservable`, `mobservable-react` etc..

**Comment by adrianolaru** [comment]
Thanks, closing this.

**Comment by mweststrate** [comment]
The packages have been released
