### ISSUE TITLE
Props of observer sometimes undefined, until refreshing

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [mobxjs/mobx#1222]
As title said. I'm using mobx with a react web project created with `create-react-app` .

This is the store:

```
import { observable, action, computed } from 'mobx';

class User {
  @observable data;
  @observable token;
  // Base64:
  @observable avatar;

  @action
  setUser(user: Object) {
    this.data = user;
  }

  @action
  clearUser() {
    this.data = null;
  }

  @computed
  get user(): Object {
    return this.data;
  }

  setAvatar(avt) {
    this.avatar = avt;
  }

  clearAvatar() {
    this.avatar = null;
  }
}

export default new User();
```

And the component class:

```
@inject('user')
@observer
export default class AccountDetails extends Component {
  render() {
    const { history, user } = this.props;
    console.log(user);
    const {
      full_name,
      avatar,
      joined_at,
      active_rewards,
    } = user.data;

  return <blah-but-using-user-props-here />
  }
}

```

I have an:

[x] Issue: The data field is sometimes `undefined` until page refreshing. I have researched, but no luck still.

**Comment by mweststrate** [comment]
Your issue confuses me a bit, why is it *not* `undefined` after a page refresh? Doesn't page refresh reset your state? Best create code sandbox to demonstrate your issue. codesandbox.io supports the CRA setup out of the box: https://codesandbox.io/s/2vmzpM0wK

**Comment by Doko-Demo-Doa** [comment]
Yeah sorry for the confusion. The scenario is pretty simple: Updating user data and save the new user object (returned from server) into store. `setUser` is, in this case, considered somehow as `setState` function. And while `setState` is not synchronous function, `user` props is not updated immediately => undefined.

Just my guess, but before that, `user` object in the store is not `null` or `undefined`. It should stay like that for a while before getting updates. That's how I see with Redux, but really hard with mobx.

**Comment by mweststrate** [comment]
Sorry, I can't reason about code I can't see and which is described in a
few sentences ;-). Please provide a reproduction

Op di 24 okt. 2017 om 19:02 schreef Phạm Văn Quân <notifications@github.com

**Comment by movingStars** [comment]
You can try this method:@observer(['user'])
Maybe you did not pass props over

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction

**Comment by ajmalfaiz** [comment]
getting the same issue..

**Comment by mweststrate** [comment]
@ajmalfaiz this issue was closed in 2017. No reason to ping everyone here, rather file your own issue by following the issue template.
