### ISSUE TITLE
Question: Import lib into a legacy VS2015 project

### ISSUE THREAD

**Issue by faberyx** [mobxjs/mobx#1224]
Hi all,

I am trying to use mobs in a legacy VS2015 project. With other libraries like react we managed to just add the js and the .d.ts file and use it in the existing namespace structure without problems. Trying to import the mobs.d.ts i the project however breaks the existing namespace when importing because of the imports in the module.

Is there a solution to this or we need to abandon the idea to use the library?

Thank you!

**Comment by mweststrate** [comment]
MobX ships with typings out of the box in the package configuration, so
there is no need to import any .d.ts files in your code explicitly. `import
{ observable } from "mobx"` should work out of the box

Op di 24 okt. 2017 om 21:09 schreef Fabrizio Catitti <
notifications@github.com>:
