### ISSUE TITLE
Improve Flow Typed Support

### ISSUE THREAD

**Issue by Kriegslustig** [mobxjs/mobx#1232]
Flow has this `.js.flow` file pattern. If utilized correctly, a consumer won't have to change anything in their `.flowconfig` in order to get the flow typings for `mobx`.

We'd have to remove the wrapping `module` block from the `.js.flow` file and add `export` to all declared variables that are exported. I've already done this locally to test it, so I could immediately open a PR.

Projects using MobX with flow typings would have to remove the `[libs]` line from their config when they upgrade.

**Comment by mweststrate** [comment]
The PR has been merged, however if I understand it correctly it does not solve the issue described above? (Properly exposing the types). Would you be interested in submitting a PR for that as well?

**Comment by Kriegslustig** [comment]
Correct. Sure thing! I'll submit a PR.

**Comment by mweststrate** [comment]
Released as 3.4.0
