### ISSUE TITLE
FlatList of react-native not re-render when the data changed

### ISSUE THREAD

**Issue by Symous** [mobxjs/mobx#1235]
Hi, I am using React-Native(0.45) FlatList component with mobx 3.2.2 , I have found that the flatlist will not update(re-render) when the data changed. here is the sample code:
```js

@observer
export default class TaskPage extends Component {
@observable
    pageState = {
        taskList: [{id:1,value:'1'},{id:2,value:'2'},{...}],
    };

....
 render(){
   <FlatList data={this.pageState.taskList} 
   ....
   />
}
}
```
when I call code 
```js
this.pageState.taskList[0].value = '0'
```
it will not re-render as expected, I also use data={this.pageState.taskList.slice()},still not working.
so wired. any idea about that ? thanks a lot!

**Comment by mweststrate** [comment]
The update property seems not relevant for the flat list (it is used
nowhere) so that seems to behave as expected

**Comment by Symous** [comment]
@mweststrate hi,thanks for your reply. I have updated the issue description.
the problem is that I set <FlatList data={this.pageState.taskList} /> and when the taskList value changed, the flatlist will not re-render. :D

**Comment by urugator** [comment]
```javascript
<FlatList data={Mobx.toJS(this.pageState.taskList)} 
   ....
   />
```

**Comment by mweststrate** [comment]
Closed for inactivity after answer has been provided

**Comment by SourceCipher** [comment]
> ```js
> <FlatList data={Mobx.toJS(this.pageState.taskList)} 
>    ....
>    />
> ```

Its so weird.. toJS is actually making an observable object to a non-observable.. But it seems like converting my observable object to toJS made my FlatList  to re-render again... React black magic..

**Comment by mweststrate** [comment]
See https://mobx.js.org/best/react.html section:  "MobX only tracks data accessed for observer components if they are directly accessed by render"

Two things to keep in mind
1. Don't pass observables to components that are not observer, they can't _react_ to them
2. If the component you are passing observables to uses HoC / render callback to render it's content, taht callback needs to use `observer` / `Observer` to be able to respond to the changes.

**Comment by SourceCipher** [comment]
@mweststrate But that doesnt explain to me why its working when passing with toJS? Is it because the toJS is inside the render and any changes to the object which gets converted with toJS is triggering the render again?

**Comment by mweststrate** [comment]
Yes

Op ma 17 dec. 2018 om 09:33 schreef Gvidas M. <notifications@github.com>:

**Comment by quantumpotato** [comment]
My component *is* an observer, I still get this error
https://stackoverflow.com/questions/55522718/flatlist-mobx-reactnative-missing-option-for-computed-get
