### ISSUE TITLE
Static Properties are not inherited to child from parent when decorating class with @observable

### ISSUE THREAD

**Issue by saravanan10393** [mobxjs/mobx#1237]
I am in need of having parent child model, where all util behaviour is defined in parent, child will make a use of it.

```javascript
class BaseModel{
      static classes = {}
      static initialize(){
         this.classes[this.name] = this;
      }
      constructor(value){
       this.value = value;
      }
      getValue(){
       return this.value;
     }
}

@observable
class Model extends BaseModel {
}
Model.initialize()
```

I get `initialize` is not function 

If i remove the `@observable` decorator its works as expected

**Comment by mweststrate** [comment]
Observable is a decorator that should be used on properties or plain
objects, not on class definitions. See the docs for proper usage.

P.S. Also not that `this` has no meaning in a static context, so
`this.classes[this.name] = this` does not mean what you think it means and
should read 'BaseModel.classes[this.name] = this' (which is still weird, as
now your classes will be filled with instances, not classes ;-) )).
Probably you want to use something like `BaseModel.classes.Model = class
Model extends BaseModel { /* etc */ }`. Relying on your constructor name
might not be safe as it might be optimized away when using uglifier for
example.

Op zo 12 nov. 2017 om 16:54 schreef Saravanan Ramu <notifications@github.com

**Comment by saravanan10393** [comment]
@mweststrate  I read this statement in docs after that only i had a thought of using it on class definition, here is the statement from docs page of [https://mobx.js.org/refguide/observable.html](observable) 4th point, object with prototype. 

> 
If value is an object with a prototype, a JavaScript primitive or function, a Boxed Observable will be returned. MobX will not make objects with a prototype automatically observable; as that is the responsibility of its constructor function. Use extendObservable in the constructor, or **@observable in its class definition instead.**

If not is there any way to dynamically add observable property,

P.S : `this` inside the static method points to classs definition itself. Not an instance.

**Comment by urugator** [comment]
> If not is there any way to dynamically add observable property,

"**Use extendObservable** in the constructor, or `@observable` in its class definition instead."

Consider using

**Comment by urugator** [comment]
Sry closed and issues instead of canceling comment...

Use `extendObservable` to define observable props on existing object.
In case of dynamic key-value data structures consider using observable map.

**Comment by mweststrate** [comment]
Closing. `@observable` is only for properties, `extendObservable` or `observable.map` should be used instead depending on the semantics
