### ISSUE TITLE
Dev mode which doesn't catch exceptions

### ISSUE THREAD

**Issue by NaridaL** [mobxjs/mobx#1241]
I've read https://github.com/mobxjs/mobx/issues/731, but the resolution isn't very satisfying. The current behavior makes debugging unnecessarily difficult. `extras.onReactionError(e =>{ throw e; });` makes things slightly better but doesn't fix the main issue that the debugger will not stop at the location of the actual error, but rather on the rethrow, which makes it impossible the inspect the values of the problematic stack frames.

Halting on every exception will have one stepping through a bunch of caught exceptions in other frameworks which isn't helpful either.

3. [X] Idea:
  * [X] What problem would it solve for you? ^^
  * [X] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)? Yes, this would help everyone debugging.
  * [X] Are you willing to (attempt) a PR yourself? If necessary.

**Comment by mweststrate** [comment]
@NaridaL I see why the idea is relevant :). With the limatations of exception handling in JS it is really hard to find a behavior that works optimal for all causes. Feel free to attempt a pr, for example by introducing `extras.disableErrorBoundaries()` (which prints a clear warning that this is a dev / debug only feature)

**Comment by mweststrate** [comment]
Will be implemented in Mobx4. Thanks!
