### ISSUE TITLE
Error: MobX injector: Store 'StoreName' is not available! Make sure it is provided by some Provider

### ISSUE THREAD

**Issue by ariona** [mobxjs/mobx#1242]
I am relatively new to MobX and trying to migrate from Redux to MobX in my React-Native development.

My code work on my debug app, but got error on release build. Here is the logcat:
```
Error: MobX injector: Store 'PlayerStore' is not available! Make sure it is provided by some Provider
This error is located at:
     in inject-t-with-PlayerStore
     in n
     in RCTView
     in RCTView
     in t
```

**My Store**
```js
import { observable, action } from 'mobx'

class PlayerStore {
	@observable isPlaying = false
	...
}
export default PlayerStore

...
// Store index
const stores = {
	PlayerStore: new PlayerStore()
}

export default {
	...stores
}
```

Since i am using `react-native-navigation` from wix i can't use built in Provider component, so i use the provider from this [gist](https://gist.github.com/megahertz/3aad3adafa0f7d212b81f5e371863637)

And here is how i use the inject on my Screen Component:
```js
...
import {observer, inject} from 'mobx-react/native'

@inject("PlayerStore")
@observer 
export default class HomeScreen extends Component {
    ...
}
```

The error only happen on release build and causing the app not running at all.

Thanks.

**Comment by mweststrate** [comment]
What does this do? ` Navigation.registerComponent('myapp.HomeScreen', () => HomeScreen, store, Provider);`

**Comment by ariona** [comment]
@mweststrate already did that
```js
export function registerScreens(store: {} , Provider: {}) {
	Navigation.registerComponent('asaticloud.HomeScreen', () => HomeScreen, store, Provider);
}
```

**Comment by ariona** [comment]
starting from scratch based on https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate working perfectly. It's weird what caused the issue though
