### ISSUE TITLE
Usage of mobx state in React

### ISSUE THREAD

**Issue by giorgim** [mobxjs/mobx#1244]
Often in the docs I see that the observable data is moved to a separate class and then the instance of that class is passed as props to react component. My question is, is the following usage of observable fields alright?

```
import React from 'react';
import ReactDOM from 'react-dom';
import {observer} from 'mobx-react';
import {observable} from "mobx";

@observer
class Timer extends React.Component {
     @observable time = 0;

    constructor(props) {
        super(props);
        
    }

    tick() {
        this.time+=1;
    }

    componentDidMount() {
        this.interval = setInterval(() => this.tick(), 1000);
    }
  
    render() {
        return (
            <div>
                Seconds: {this.time}
            </div>
        );
    }
}


ReactDOM.render(<Timer/>, document.getElementById('root'));

```

The code works by the way.

**Comment by urugator** [comment]
It's alright. I personaly prefer keeping state and logic outside of react component for these reasons:
- you can't simply instantiate a react component to test it
- react components are composed in a hierarchy representing DOM, which sometimes doesn't match how the domain models are composed  
- rendering logic is more prone to change than models, therefore keeping component as simple as possible makes also it's modifications easier
- it's easier to share the same state and logic (model) by multiple components      
- when you introduce observable prop on component you can't pass it further down as MobX state without wrapping it into boxed/computed/object (which is basically an introduction of seperate "model") 

To avoid some maintenance overhead, when component/model abstraction is not necessary, I actually do it other way around - I introduce a render method on domain model:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import {observer} from 'mobx-react';
import {observable} from "mobx";


const TimerComponent = Observer(({ timer }) => <div>Seconds: {timer.time}</div>)

class Timer extends {
     @observable time = 0;

    constructor() {      
        this.interval = setInterval(() => this.tick(), 1000);
    }

    tick() {
        this.time+=1;
    }  
  
    render() {
      return React.createElement(TimerComponent, { timer: this })
    }
}

const timer = new Timer();
ReactDOM.render(timer.render(), document.getElementById('root'));

**Comment by giorgim** [comment]
@urugator Thanks.

> when you introduce observable prop on component you can't pass it further down as MobX state without wrapping it into boxed/computed/object (which is basically an introduction of seperate "model")

I experienced this, basically you mean if I want to pass `time `down to some child element of Timer as a props, then the child element can't modify `time`, unless I put it inside a JS object and pass the JS object to this child element as props instead?

**Comment by urugator** [comment]
Modifications are not an issue, you can pass a callback together with time, the problem is that the descendant component(s) can't benefit from being an observer if you pass "unwrapped non-observable value"

**Comment by giorgim** [comment]
@urugator modifications are an issue IMHO if I just passed `time `directly as props to child component, and from within child component I would do: this.props.time=123 (I get error props is readonly).

**Comment by urugator** [comment]
>  this.props.time=123

Even if it would be possible, you would only modify the props of the component, not the original observable prop. Note that you should wrap state modifications into action.
You can still modify time from children like this:
```javascript
<Child time={this.time} setTime={value => this.setTime(value)}></Child>
// in child:
this.props.setTime(value)
```

> not sure I understood what you mean with descendant components not benefit from being an observer..

It's well explained [here](https://mobx.js.org/best/react.html)

**Comment by giorgim** [comment]
@urugator ok, thanks.

**Comment by giorgim** [comment]
@urugator since you seem experienced with mobx can you please give your opinion on this:
https://github.com/mobxjs/mobx-react/issues/362
?
And whether the situation I encountered there is something you were referring to in this post using:

> 
> "when you introduce observable prop on component you can't pass it further down as MobX state without wrapping it into boxed/computed/object (which is basically an introduction of seperate "model")
> "
> 

thank you.
