### ISSUE TITLE
autorun and reaction don't work on Safari versions<=8.0

### ISSUE THREAD

**Issue by helloncanella** [mobxjs/mobx#1245]
```javascript
function MyStore() {
  extendObservable(this, {
    hello: 2
  })

  this.changeHello = action(a => {
    this.hello = a
  })

  autorun(() => console.log(this.hello))
}

window.myStore = new MyStore()
```

The snippet above raises the exception

> Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[Autorun@23]

exclusively on safari **versions<=8.0**.

When the `autorun`'s line is commented, the exception disappears. 

The same occurs when `reaction` is used.

**Comment by mweststrate** [comment]
This issue is safari 8 specific? That sounds like a browser bug that has
probably been fixed in the last 3 years...

Op do 16 nov. 2017 om 12:42 schreef Hellon Canella <notifications@github.com

**Comment by mweststrate** [comment]
Closing this for the lack of a clear reproduction & motivitation why this is a Mobx bug, rather than a Safari bug. If someone is interested in diving deeping and finding a work around, PR's for such fixes are welcome.
