### ISSUE TITLE
array remove by predicate should be implemented

### ISSUE THREAD

**Issue by fehergeri13** [mobxjs/mobx#1248]
I use this pattern so often:

`myObservableArray.replace(myObservableArray.filter(item => item.bad !== true));`

so I think it should be implemented by default.

`myObservableArray.removeAll(item => item.bad === true)`

**Comment by mweststrate** [comment]
Ehh.. it exists already?

Op ma 20 nov. 2017 om 15:14 schreef Gergely Fehérvári <
notifications@github.com>:

**Comment by fehergeri13** [comment]
Meh, not really. because currently only item match is existing but this is kinda different, since i want to use a predicate

**Comment by mweststrate** [comment]
Feel free to submit a PR :) `removeAll` sounds like a sane name

**Comment by mweststrate** [comment]
Closed, see: https://github.com/mobxjs/mobx/pull/1384#issuecomment-372024393
