### ISSUE TITLE
Dispose autorun from within callback

### ISSUE THREAD

**Issue by scisci** [mobxjs/mobx#1250]
Maybe I'm using autorun incorrectly, but I've found the need to dispose the autorun call from within the callback. This is impossible since you can't get a reference to the disposer until after autorun returns, which is after it has been called for the first time. Any suggestions for how one would do this:

```
const dispose = autorun(() => {
  if (this.ready) {
    dispose();
  } else {
    ...
  }
});
```

I can think of a long winded way, but its ugly.
```
let shouldDispose = false;
const dispose = autorun(() => {
  if (this.ready) {
    shouldDispose = true;
    if (dispose) dispose();
  } else {
    ...
  }
});
if (shouldDispose) dispose();
```

**Comment by scisci** [comment]
I was able to get around this by rearranging the surrounding code, which involved promises.

**Comment by nighca** [comment]
@scisci I think you don't have to dispose it when `this.ready` being true. Just leave it there and dispose it when you don't need this task:

```javascript
const dispose = autorun(() => {
  if (!this.ready) {
    // ...
  }
})

// dispose in some other place such as React Component's componentWillUnmount
dispose()
```

If `this.ready` keeps true, this `autorun` task won't do anything and costs little. So don't worry.

**Comment by scisci** [comment]
That may be true, just wanted it to be as clean as possible. However, I found there is `autorunAsync` and that seems to solve the problem of having dispose defined before the callback.

**Comment by urugator** [comment]
Actually the Reaction object is passed to the autorun as a first param, so you can call reaction's dispose method:
```javascript
Mobx.autorun(reaction => {
  reaction.dispose();
})
```
