### ISSUE TITLE
Understanding reaction

### ISSUE THREAD

**Issue by giorgim** [mobxjs/mobx#1256]
Hi guys, I thought in the following case (mobx/react)

```
export default class MatchingGame extends React.Component {

    @observable board = [];

    componentDidMount() {
        let rands = this.generateUniqueRandNumbers(5).concat(this.generateUniqueRandNumbers(5));
        this.board = rands.map((item) => {
            return {
                itemID: item,
                isOpen: false
            }
        })
 
    }
    ...
```

mobx **shouldn't** react to`  this.board = rands.map((item) =>..` because I made `this.board` refer to something else, instead of going and modifying the contents of array to which `this.board` referred to.
Am I right in understanding?
But like I said this code which I posted, caused a react render to be called. Why?

this is copy from mobx docs due to which I thought mobx should not have reacted to above

> 
> Incorrect: changing a non-observable reference
> 
> autorun(() => {
>     console.log(message.title)
> })
> message = observable({ title: "Bar" })
> This will not react. message was changed, but message is not an observable, just a variable which refers to an observable, but the variable (reference) itself is not observable.

**Comment by mweststrate** [comment]
Question has been closed after ignoring earlier remarks that I don't want to be contacted through personal channels to be urged to answer questions. MobX can be used for free, but it doesn't come with a SLA that permits contacting me *personally* to answer questions within hours.
