### ISSUE TITLE
Observable map cannot be replace with another observable map

### ISSUE THREAD

**Issue by nikolovp** [mobxjs/mobx#1258]
Since MobX v3.3.2 an observable map cannot be replaced with another observable map. I believe the only supported types are plain object, plain array and ES6 Map.

**Error: [mobx] Invariant failed: Cannot get keys from ObservableMap@**

Most probably related to:
Issue: https://github.com/mobxjs/mobx/issues/1243
MR: https://github.com/mobxjs/mobx/pull/1247

The _getMapLikeKeys_ util function in https://github.com/mobxjs/mobx/pull/1247 does not take into account MobX maps. I think the _isES6Map_ check must be replaced with _isMapLike_ check which matches both ES6 Maps and MobX maps.

2. [x] Issue

  * [x] **Provide error messages including stacktrace**
Uncaught (in promise) Error: [mobx] Invariant failed: Cannot get keys from ObservableMap@71[{  }]
    at invariant (webpack-internal:///43:2372)
    at fail (webpack-internal:///43:2367)
    at getMapLikeKeys (webpack-internal:///43:2570)
    at eval (webpack-internal:///43:2287)
    at transaction (webpack-internal:///43:2068)
    at ObservableMap.replace (webpack-internal:///43:2283)

  * [x] Provide a **minimal** sample reproduction.
```
const items = mobx.observable.map();
items.replace(mobx.observable.map())
```
  * [x] Did you check this issue wasn't filed before?
I couldn't find a similar issue

  * [x] Elaborate on your issue. What behavior did you expect?
MobX observable maps should be also supported for replacement (was working before v3.3.2)

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
The issue is reproducible with MobX v3.3.2 only

  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
This scenario was working before v3.3.2 so...

  * [x] Are you willing to (attempt) a PR yourself?
I don't have a setup to build/test MobX but I would be glad to try

**Comment by mweststrate** [comment]
Ai, this seems to be an oversight indeed. Would you be interested to create
a PR? Thanks!

Op ma 27 nov. 2017 om 12:04 schreef Petar Petrov <notifications@github.com>:

**Comment by nikolovp** [comment]
Sure :)

**Comment by mweststrate** [comment]
Fix released as 3.3.3. Thanks!

**Comment by nikolovp** [comment]
Thanks for the fix and sorry for the delay! It was a busy week and I did not have time to prepare the PR. Maybe next time :)

**Comment by mweststrate** [comment]
Cool! Looking forward :)

Op di 5 dec. 2017 om 07:50 schreef Petar Petrov <notifications@github.com>:
