### ISSUE TITLE
Redundant computed calculations.

### ISSUE THREAD

**Issue by alexanderzubarev** [mobxjs/mobx#1259]
Hello.

Sample reproduction: https://jsfiddle.net/wv3yopo0/1783/

As you can see "RECALC ITEMS COMPUTED BY ID" printed twice, but state.items has no changes. Is this expected behavior? I have an issue with it, the map recalculates much more often than it should.

**Comment by mweststrate** [comment]
I think you linked the wrong fiddle. Note that computed values only cache
if they are _observed_ (by observer, autorun or reaction)

Op di 28 nov. 2017 om 08:52 schreef Alexander Zubarev <
notifications@github.com>:

**Comment by alexanderzubarev** [comment]
I updated the link, but seems like "computed values only cache if they are _observed_" is the answer.

Btw, is there any way to manually enable caching for computed value? in my case it seems strange to create meaningless autoruns like this:

```
autorun(() => {
	state.byId;
});
```

**Comment by mweststrate** [comment]
Yes, see mobxUtils.keepAlive.

Op di 28 nov. 2017 om 09:17 schreef Alexander Zubarev <
notifications@github.com>:

**Comment by alexanderzubarev** [comment]
Thank you very much for the help!
