### ISSUE TITLE
Event action problem

### ISSUE THREAD

**Issue by mostafa6765** [mobxjs/mobx#1261]
First result with computed
![pb1](https://user-images.githubusercontent.com/17185462/33526484-8ee3eac4-d86c-11e7-97fe-844e8ad70e65.PNG)

*result computed with onChange/action (or onClick same issue)

![pb2](https://user-images.githubusercontent.com/17185462/33526494-9d4c1c4e-d86c-11e7-9fef-52057af09432.PNG)

```js
import {observable,action,computed} from 'mobx'
class MyComponent{
    @observable project = "mobx project"
    @observable title = "kamal the boss"
    @observable price1 = 20
    @observable vat1 = 15
    @observable totalPrice

    @computed get total() {
      return (
        this.totalPrice = this.price1 + this.vat1
      )
    }

    @action todos(value) {
    return  this.price1 =  value
    }
    @action todos2(value) {
    return  this.vat1 =  value
    }
    @action todoKamal() {
      this.project = `Awesome project`
    }
}

export default window.__STATE = new MyComponent(window.__STATE)
```

```js
import React, { Component } from 'react'
import {inject, observer } from 'mobx-react'

@inject("store")
@observer
class Home extends Component {
  constructor(props) {
    super(props);
    this.storeMobx = this.props.store
    this.state = {
      valueMe : '',
      valueMe2 : ''
    };
  }
  render() {
    // const store = this.storeMobx
    const {store} = this.props
    return (

      <div className="columns">
        <div className="column is-8 is-offset-2">
      <section className="hero is-danger component-part">
        <div className="hero-body">
          <div className="container">
            <h1 className="title">
                {store.project}
            </h1>
           <h2 className="subtitle">
             <div className="columns">
               <div className="column is-8">
               <h1 className="title">
                  price is  {store.price1} , vat is {store.vat1}
               </h1>
               <h1 className="title">
                   total price {store.total}
               </h1>
                  <input className="input is-dark" value={store.price1} onChange={(e) => store.todos(e.target.value)} type="text" placeholder="Text input"/>
                  <input className="input is-dark" value={store.vat1} onChange={(e) => store.todos2(e.target.value)} type="text" placeholder="Text input"/>
                  <button className="button is-info" onClick={(e) => store.todoKamal()}>Click</button>
               </div>
             </div>
           </h2>
          </div>
        </div>
      </section>
    </div>
    </div>
    );
  }
}
export default Home
```
* How to solve this ? Any tips .

**Comment by mweststrate** [comment]
@computed get total() {
      return (
        this.totalPrice = this.price1 + this.vat1
      )
    }



Should read


 @computed get total() {
     return this.price1 + this.vat1
 }


Op zo 3 dec. 2017 om 16:03 schreef Mostafa Kamal <notifications@github.com>:

**Comment by mostafa6765** [comment]
```js
@computed get total() {
      return (
        this.totalPrice = this.price1 + this.vat1
      )
    }
```

same issue . you input as like 30 and 40 result total will be 70 but output 3040 . which behave as string . 
@mweststrate

**Comment by mostafa6765** [comment]
@mweststrate  you can check my project [github project here](https://github.com/code4mk/react-redux-boss/blob/40ccc080e9775df9050c02b04ff354d24497bb36/src/store/mobx/Index.js#L11)

**Comment by mweststrate** [comment]
This means you convert / store one of these values as string somewhere.
Mobx itself does not do any type conversion on primitives, so it is highly
unlikely this is an mobx issue. Do you convert your inputs to numbers when
reading them in your event handlers? (Your project is too big for an issue
report so I didn't check it out)

Op ma 4 dec. 2017 om 12:46 schreef Mostafa Kamal <notifications@github.com>:

**Comment by mweststrate** [comment]
Ideally, it is bettre to sanitize your inputs on the input side of things,
not on the output side (when setting this.price etc from your inputs)

Op ma 4 dec. 2017 om 15:31 schreef Mostafa Kamal <notifications@github.com>:
