### ISSUE TITLE
observe won't response to Map computed property change?

### ISSUE THREAD

**Issue by freshsun** [mobxjs/mobx#1264]
For example:

a = mobx.observable.map()

a.set('b', mobx.computed(function(){return a.get('a')*2; }))

mobx.observe(a ,function(change){console.log(change)})      

mobx.observe(a, 'b', function(change){console.log(change)})  

a.set('a', 2)  // only change object for property 'a' is logged out

What if i want to have a listener when property 'b' is changed? 

Thanks.

**Comment by mweststrate** [comment]
Pick the computed from the map and observe it:

`mobx.observe(a.get('b'), listener)`

**Comment by freshsun** [comment]
@mweststrate thanks, this works!

one more question, is computed observable? or it is observable because it is a modifiers? I don't quite understand them in the documents, for example:

**Observabe definations**
Observable values can be JS primitives, references, plain objects, class instances, arrays and maps. The following conversion rules are applied, but can be fine-tuned by using modifiers. See below.

**observe params** 
target: the observable to observe
propertyName: optional parameter to specify a specific property to observe. Note that observe(user.name, listener) is fundamentally different from observe(user, "name", listener). The first observes the current value inside user.name (which might not be an observable at all), the latter observes the name property of user.

* Note that object update events won't fire for updated computated values (as those aren't mutations). But it is possible to observe them by explicitly subscribing to the specific property using observe(object, 'computedPropertyName', listener).

**Comment by mweststrate** [comment]
All computeds are observable as well. (more precisely: any property
declared with @computed and the `.get()` call to a computed box like you
are creating)

Op wo 6 dec. 2017 om 03:01 schreef freshsun <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing as original question is answered
