### ISSUE TITLE
The Decorators is error in React-native project

### ISSUE THREAD

**Issue by Hancoson** [mobxjs/mobx#1265]
```
"mobx": "^3.3.1",
"mobx-react": "^4.3.4",
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-blur": "^3.2.2"
```
In the IOS simulator has the error unexpected token, and my code is :
![image](https://user-images.githubusercontent.com/5474666/33656077-f4fb7134-daaf-11e7-8e23-ea8947f10ef2.png)

the error is（homeStore.js）:
![image](https://user-images.githubusercontent.com/5474666/33656191-3ffbf8e8-dab0-11e7-9850-648ee729ed70.png)

**Comment by mweststrate** [comment]
You will need to enable decorators in your setup. Which is probably doing something like:

`npm install babel-plugin-transform-decorators-legacy --save-dev`

Create a `.babelrc` in your project directory with these options:

```
{
 "presets": ["react-native"],
 "plugins": ["transform-decorators-legacy"]
}
```

If you already have some plugins, it is important that the decorators plugin comes first

**Comment by vonovak** [comment]
@Hancoson you should close the issue if the comment helped. The decorators certainly work with RN with the babel plugin.
