### ISSUE TITLE
mobx 3.4.0 breaks yarn outdated command

### ISSUE THREAD

**Issue by vitbokisch** [mobxjs/mobx#1266]
Hello, I found out, an issue:

**I get en error message:**
Couldn't find any versions for "mobx" that matches "^3.4.0"

**How to reproduce:**
mkdir repo
cd repo
npm init
yarn add mobx (automatically installs v3.4.0)
yarn outdated

This error breaks _yarn outdated_ command. When using npm outdated, everything works perfectly.
node: 9.2.0
Npm version: 5.5.1
Yarn version: 1.3.2

**Comment by mweststrate** [comment]
Something seems off in the npm / yarn cache. 3.4.0 does exist when trying
to publish, but not all services can find it. Published literally the same
version as 3.4.1 as well, hope that helps

Op do 7 dec. 2017 om 10:42 schreef Vit Bokisch <notifications@github.com>:

**Comment by vitbokisch** [comment]
Updated to v3.4.1 and everything works as expected. Thank you very much for solving this issue sooo quickly! Great job! Closing this issue.
