### ISSUE TITLE
Source order around autorun

### ISSUE THREAD

**Issue by mixtur** [mobxjs/mobx#1269]
I have a:

1. [x] Question or maybe issue. Not sure)

Documentation [claims](https://mobx.js.org/refguide/autorun-async.html) that autorun does first run synchronously which is technically true, but looks like you still cannot rely on source order on first run.

This code works fine.
```js
console.log('before');
autorun(() => console.log('run'));
console.log('after');
```

But this one is not
```js
console.log('before outer');
autorun(() => {
    console.log('before inner');
    autorun(() => console.log('inner'));
    console.log('after inner');
});
console.log('after outer');
```

It is even worse if autorun created in response to some change. It seems to be run after all other reactions are done their work.

So. Can it be fixed? Or is there some workaround? I really want to rely on source order on first run.

**Comment by mweststrate** [comment]
The need for such dependency order signals that there is apparently some dependency in your code / state that is not made explicit in your code. A setup like the above is as smelly as having a pattern like the next and hoping `funcA` will execute before `funcB` 

```
setTimeout(funcA, 100)
setTimeout(funcB, 101)
```


If one autorun needs the output value of another one, that strongly suggests that you need, for example, to express a value as computed value (which does provide ordering guarantees). Autorun's can be seen as side effects actors, which run independently and which effects should not be visible or relevant to the application itself or each other.

At least, if there is a dependency, you should make that explicit by having some observable that captures (the state of) the relationship. 

A solution to your problem might be to just have one actor (autorun) that takes care of all the processes that needs to be taken care in one run, if order is so important.

Also note that creating autoruns in autoruns (and not disposing them) is probably just creating one big memory leak. 

Can you elaborate a bit on your actual use case. What you are trying to achieve and why you did structure it this way?

**Comment by mixtur** [comment]
I am working on react-like wrapper for three.js.
So we have components that have children and some lifecycle methods.
On the user side it looks like declaring portion of scene graph depending on some observables. Updates and initial mounting of components are implemented via autorun. Wrapper takes care of unsubscribing when necessary, so no memory leaks here.

Ok. Now the problem.
Say we have component A that have child component B.
Both creation of A and creation of B wrapped in its own autorun. So we have nested autoruns.
Say we need a ref to instance of B component. I expect it to be available in didMount of component A. Which is not the case because there are other updates queued after creation of A. So there is a gap between creation of A and creation of B.

We could wrap ref in Promise, and it would work, but it seems silly because code is actually synchronous (in bad (for us) order though), but wrapping it in Promise would make code truly asynchronous and messy.

We could also run first update ourselves bypassing mobx. But then we would lose subscriptions. So it is not a solution.

Real solution is to do work that depends on that ref in callback that actually receives ref. And it works of course. And it is not even so messy.

So there is no strong "need" to have match between source order and execution order. But I would prefer it to be. It just seems more intuitive.

**Comment by urugator** [comment]
It's really unintuitive, but allowing autorun to run inside another autorun would basically violate transactional behavior...
When you declare autorun or reaction, you're basically saying "when all state mutations are done (state is consistent), call this function".
But that function itself is allowed to modify state, so it runs inside transaction, which guarantees that no `autorun/reaction` will run until that function is finished.
```javascript
autorun(() => {
  // We are at TX know, which guarantees that no `autorun/reaction` runs until it finishes   
  console.log('before inner');
  autorun(() => console.log('inner')); // autorun must not run before TX finished, otherwise it would consume potentially inconsistent state (note it may be nested TX) 
  console.log('after inner');
  observable.something = "modified"; // the nested autorun must see this state modification before it runs
});
```
I always suggest to consider autorun/reaction being asynchronous.

**Comment by mweststrate** [comment]
as usual, well explained @urugator! (forgot already about that part of the equation)

@mixtur so basically you need a depth first trigger of all did mounts right? I think I would approach it with an array holding a list of pending didmounts to fire, and schedule that to run on next tick so that you can run them all once. 

You can even do it in the same tick by keeping a counter, and have each autorun check if that already dropped to zero and then execute this pending didmount list.

**Comment by mixtur** [comment]
@urugator thank you for explanations.
Though changing observables in reactions doesn't sound like a good idea in the first place. Maybe there could be something like `autorunStrict` that would throw an error if someone tries that? Is there any other obstacles?

@mweststrate Yep. I wanted to do something like that sooner or later anyway)

**Comment by urugator** [comment]
> doesn't sound like a good idea in the first place 

I agree, and notice if there are no state mutations, then execution order doesn't matter, because one autorun can't influence the result of another.

> Is there any other obstacles?

Consider this:
```javascript
autorun(() => {
  system2.action(system1.observable);  
})
```
The action above may be asynchronous, but it may still synchronously modify some internal observable owned by `system2` (eg. some `actionCalled` flag), there is no reason to throw.
Also note that you may not even know whether `system2` uses MobX or not.

The question is whether autorun should run inside TX by default ... if it wouldn't, the current strict mode would throw unless you explicitely call `action/runInAction`, which seems fine to me, but I am not sure about other consequences/implications.

**Comment by malj** [comment]
Sorry to necro an old issue, but perhaps my experience will be useful to someone reading this in the future, as I've also been shot in the foot by this seemingly unintuitive behavior. This is not a question, just dumping a few keywords for search engines to pick up.

I'm building a MobX based base class for web components. The custom HTML elements use `autorun` to reactively render their content, and I've run into the same issue as described above with the initial render order in nested components.

I've put together a short [fiddle](https://jsfiddle.net/2p3e4zb8/) to demonstrate the issue, but this is the gist of the problem:

```html
<script>
    class MobXElement extends HTMLElement {
        connectedCallback() {
            this.dispose = autorun(() => this.render())
        }
        disconnectedCallback() {
            this.dispose()
        }
    }

    class Child extends MobXElement {
        connectedCallback() {
            super.connectedCallback()
            // Not yet rendered because nested autorun has been delayed
            this.querySelector("div") // null
        }
        render() {
            this.innerHTML = "<div></div>"
        }
    }

    customElements.define("child-element", Child)

    class Parent extends MobXElement {
        connectedCallback() {
            super.connectedCallback()
            // Rendered as expected because it's a top level autorun
            this.querySelector("child-element") // HTMLElement
        }
        render() {
            this.innerHTML = "<child-element></child-element>"
        }
    }

    customElements.define("parent-element", Parent)
</script>

<parent-element></parent-element>
```

The solution I've come up with is to wrap the callback in a promise which is resolved when `autorun` fires, although introducing asynchronous code to force the correct execution order seems inelegant and complicates the API:

```js
connectedCallback() {
    return new Promise(resolve => {
        this.dispose = autorun(() => {
            this.render()
            resolve()
        })
    })
}
```

**Comment by urugator** [comment]
@malj I did not think much about it, but to ensure currect order, you will probably need to do something similar to React - that is flagging element as dirty by `autorun/reaction` and then traverse elements from root, re-rendering the dirty ones.

**Comment by malj** [comment]
Thanks for the suggestion @urugator. I wanted to keep this as simple as possible because reactions are local to each component once it's added to the DOM, and they run independently from one another afterwards. The problem is just in the initial order.

After analyzing the `autorun` source code, I managed to achieve the correct order by creating a custom reaction which bypasses internal scheduling ([updated fiddle](https://jsfiddle.net/hax32gcs/)):

```js
function customAutorun(view) {
    const reaction = new Reaction("...", () => reaction.track(view))
    reaction.track(view)
    return () => reaction.dispose()
}
```

I haven't considered all potential implications, but in this case it seems to work fine because the `view` function is just used to render DOM elements based on state changes, it never triggers any state updates during its execution. Does that seem safe at a glance?

**Comment by urugator** [comment]
> it never triggers any state updates during its execution

If it means that components can't communicate with one another during render (like setting props of child by parent), then it's probably fine. Otherwise the rendered result would depend on invocation order of reactions, which isn't clearly specified (but depends on invalidation order).
