### ISSUE TITLE
Observable annotation fails for TypeScript parameter properties

### ISSUE THREAD

**Issue by devuxer** [mobxjs/mobx#1272]
It appears that it is currently not possible to use `@observable` with a TypeScript parameter property (see [this TypeScript docs page](https://www.typescriptlang.org/docs/handbook/classes.html) for general info on parameter properties).

Example:

```
export class ParameterPropertyExample {
    constructor(
        public foo: string
    ) { }
}

export class ObservableParameterPropertyExample {
    constructor(
        @observable public foo: string // error!
    ) { }
}
```

For the second class, I get a red squiggle under `@observable` with this error:

>  Type 'number' has no properties in common with type 'PropertyDescriptor'

Am I doing something wrong or is this just not possible? And if it's not possible, would it be feasible to make this a feature request?

**Comment by mweststrate** [comment]
This is indeed not possible, so use the following instead:

```
export class ObservableParameterPropertyExample {
    @observable foo: string
    constructor(
        foo: string // error!
    ) { 
        this.foo
    }
}
```

It won't be implemented in MobX until decorator proposal has finalized to make sure we don't deviate to far from the final spec
