### ISSUE TITLE
Can't make @observable parameter properties

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mobxjs/mobx#1273]
I have an:

2. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction.
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

MobX version: 3.3.1
TypeScript version: 2.7.0-dev.20171126

```typescript
import { observable } from "mobx";

type Model = { };

export class ViewModel {
    public constructor(
        // Argument of type 'number' is not assignable to parameter of type 'PropertyDescriptor | undefined'.
        @observable
        public readonly model: Model,
    ) { }
}
```

On the other hand, works:

```typescript
export class ViewModel {
    @observable
    public readonly model: Model;

    public constructor(model: Model) {
        this.model = model;
    }
}
```

**Comment by JoshuaKGoldberg** [comment]
Not sure if https://github.com/Microsoft/TypeScript/issues/10777 is relevant here.

**Comment by mweststrate** [comment]
We might implement this ones decorators are standardized. For now blocked until then as there is an easy workaround.

**Comment by mweststrate** [comment]
Closing for now, will be reopened once #1928 happens.
