### ISSUE TITLE
Question: Is observable(object) supposed to box primitive properties?

### ISSUE THREAD

**Issue by vista-dy** [mobxjs/mobx#1274]
I read this in the [docs](https://mobx.js.org/refguide/observable.html) regarding how the observable function handles primitive and non-plain objects:

> If value is an object with a prototype, a JavaScript primitive or function, a Boxed Observable will be returned.

I also read this in the [Observable Objects](https://mobx.js.org/refguide/object.html) page

> If a plain JavaScript object is passed to observable all properties inside will be copied into a clone and made observable

So based on this, I would expect that a primitive value within a plain object would be turned into a Boxed Observable. This doesn't appear to be the case though. See example here: https://jsfiddle.net/90tkho07/1/

Am I misunderstanding this?

**Comment by urugator** [comment]
MobX tries to create 1 to 1 copy of the original non-observable object, but observable.
However thats possible only with plain object, array and map (with a limitation that array isn't actual Array and map isn't actual Map, but behave the same way).
Why? Mobx needs to put it's observing logic somewhere:
In case of object and array it can put this logic into object property accessors `get prop();set prop(value)` (it's a bit complicated with array, but same in principle).
In case of map, the logic is hidden in `get(key);set(key, value)` methods.
In case of primitive value, there is no place to put this logic ... so mobx creates an observable "box" with `get();set(value)` methods.
In other words object/array/map are already natural "boxes" for primitive values, so it's unnecessary to wrap them into another artifical "box".   
Non-observable non-plain objects are handled the same way as primitives - if alone, they're boxed, if already part of object/array/map, no need to box them.
Already observable things are simply returned.
If you don't want or can't rely on `observable()`'s best effort behavior, there are specific factory functions, like `observable.box()` 

Note:
```javascript
isObservable(objectWithPrimitive.value))
// evaluates as:
isObservable(1) // obviously false
// if you want to check whether specific prop is observable use
isObservable(objectWithPrimitive, "value") // true
```

**Comment by vista-dy** [comment]
Alright that makes sense now, thanks,

Documentation is a bit confusing around this area, e.g. in [deep observability](https://mobx.js.org/refguide/modifiers.html):

> When MobX creates an observable object, (using observable, observable.object, or extendObservable), it introduces observable properties which by default use the deep modifier. The deep modifier basically recursively **calls observable(newValue) for any newly assigned value**. Which in turns uses the deep modifier... you get the idea.

Reading this I would think that a primitive would be boxed because observable(primitive) would be called but that is not the case

**Comment by urugator** [comment]
Yea, it's not entirely right, if you think it can be formulated better there is "EDIT THIS PAGE" button :)
For a reference here is the [actual implementation](https://github.com/mobxjs/mobx/blob/master/src/types/modifiers.ts#L27):
```javascript
// it is an observable already, done
if (isObservable(v)) return v

// something that can be converted and mutated?
if (Array.isArray(v)) return observable.array(v, name)
if (isPlainObject(v)) return observable.object(v, name)
if (isES6Map(v)) return observable.map(v, name)

return v
```
