### ISSUE TITLE
createTransformer with non-extensible object

### ISSUE THREAD

**Issue by scisci** [mobxjs/mobx#1275]
I'm getting the error: `Cannot define property $transformId, object is not extensible`

It looks like createTransformer tries to add a property and maybe my object is frozen. Is there any workaround?

**Comment by mweststrate** [comment]
In that case the transformer should rely on weak maps. However, since those are not by default available in ES5 environments we cannot use that in the current version. You could however run your own createTransformer implementation, it is pretty straight forward

**Comment by mweststrate** [comment]
Suggestion: in next version use weakmaps *and* move it to mobx-utils

**Comment by mweststrate** [comment]
`createTransformer` has been moved to mobx-utils. The issue could be added there if still needed.
