### ISSUE TITLE
[docs] Headlines in the docs site dose not have anchors  

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx#1278]
See
https://mobx.js.org/intro/concepts.html#illustration
Expected behaviour: page should scroll to the `illustration` section  
Actual:
It dose not

Fix would be in add 
https://www.npmjs.com/package/gitbook-plugin-anchors

**Comment by mweststrate** [comment]
Fixed, thanks for the suggestion!

**Comment by Obiwarn** [comment]
When I enter via https://mobx.js.org/refguide

![image](https://user-images.githubusercontent.com/9539797/48550481-2584be00-e8d3-11e8-88a8-65f8e4f11c34.png)


and then click a link in the navmenu on the left the menu gets cluttered up like this:

![image](https://user-images.githubusercontent.com/9539797/48550422-02f2a500-e8d3-11e8-9199-1037b1452ae5.png)
