### ISSUE TITLE
[Question] how to avoid circular structure in server-side-render 

### ISSUE THREAD

**Issue by Godsleeper** [mobxjs/mobx#1279]
In official docs 7.2 section part of Combining multiple stores, docs suggest that building a rootStore and new child-store in constructor.But in some scene which uses server-side-render,i must provide a json to window like 'window.rawData = JSON.stringify(store)' to make react components have no difference between node and browser. That cause a problem that the rootStore has childStore, the childStore has rootStore.This is a circular structure which will error in JSON.stringify,so how can i avoid this problem?Sorry for my poor english.
![image](https://user-images.githubusercontent.com/16974903/34076397-dd1f9422-e320-11e7-9397-7a4d60566f7d.png)

**Comment by urugator** [comment]
Implement `toJSON` to customize `JSON.stringify` behavior.
Check [serializr](https://github.com/mobxjs/serializr)
Check [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree)

**Comment by Bnaya** [comment]
I have different architecture, that avoids circular deps and scale very well
It looks like:
```ts
class SharedRootStore {
    @observable todos = [];
    @observable userData = {
        name: "Bnaya",
        lastName: "Peretz",
        id: "bnaya.peretz"
    };
}

class RootStore {
    constructor() {
        const sharedRootStore = new SharedRootStore();
        this.userStore = new UserStore(sharedRootStore)
        this.todoStore = new TodoStore(sharedRootStore)
    }
}

class UserStore {
    constructor(sharedStore) {
        this.sharedStore = sharedStore
    }

    getTodos(user) {
        return this.sharedStore.todos.filter(todo => todo.author === user)
    }
}

class TodoStore {
    constructor(sharedStore) {
        this.sharedStore = sharedStore
    }

    @computed get todos() {
        this.sharedStore.todos;
    }

    @computed get todosOfCurrentUser() {
        this.sharedStore.todos.filter(todo => todo.author === this.sharedStore.userData.id)
    }
}
```

**Comment by mweststrate** [comment]
Closing as several solutions has been suggested
