### ISSUE TITLE
Small documentation improvement

### ISSUE THREAD

**Issue by Bloomca** [mobxjs/mobx#128]
Could you please add link to [gh-pages](http://mobxjs.github.io/mobx/) in the top line? I think it's the general practice.

And add please some link/short mention which environments and browsers (this is crucial for some people) support it.

Thanks.

**Comment by adrianolaru** [comment]
Talking about documentation, I think it's a bit confusing now, especially the code examples.  

Do you think is a good idea to show in which programming language the examples are coded? Like [TS] [ES6]  or [ES5]? 

I don't know TypeScript for example and I see this example, which I believe is TypeScript:

```
class Todo {
    id = Math.random();
    @observable title = "";
    @observable finished = false;
}
```

and it's a bit confusing to me. Then there's the `@computed`  decorator. How can I use it in ES6? My guess is that all I need in ES6 to make an object or a class observable are `extendObservable` and `observable` decorator/function. Right? Thank you. And sorry @Bloomca if I hijacked this issue.

**Comment by kolis** [comment]
:+1:  on linking to https://github.com/mobxjs/

**Comment by mweststrate** [comment]
@adrianolaru `@observable` is ES7 syntax, works with Babel as well. See http://mobxjs.github.io/mobx/best/syntax.html for syntax differences between ES5, ES7, TypeScript

Thanks for the feedback, I'll make sure these items will be easier to find!
