### ISSUE TITLE
[v3.4.1] MobX's toJS isn't properly serializing nested observable arrays.

### ISSUE THREAD

**Issue by sadasant** [mobxjs/mobx#1280]
Hello, MobX team!

I found a bug on `toJS`. It's not properly serializing nested observable arrays. Here's a minimal reproduction of the bug using _jsbin_: https://jsbin.com/bijohi/edit?html,js,console

It happens on MobX v3.4.1. If I try the same with MobX 2.3.3, the issue doesn't happen: https://jsbin.com/sumere/edit?html,js,console

I couldn't find any other relevant issue, but I could be wrong.

Let me know if I can help with any other detail! Thank you for the time 🤗

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#260

**Comment by sadasant** [comment]
@urugator hey! thank you :) so maybe we should close this? 🤔 

At least, we should make this clear in the docs: https://mobx.js.org/refguide/tojson.html

**Comment by urugator** [comment]
If you feel like the docs aren't clear enough, there is **EDIT THIS PAGE** btn...

**Comment by sadasant** [comment]
I guess I'll do that if I find a bit of time tomorrow. Thanks!
