### ISSUE TITLE
Flow Typecheck Error

### ISSUE THREAD

**Issue by wadeanthony0100** [mobxjs/mobx#1282]
Hey, all!

There looks to be a small error in our flow typings definitions.

Having the following code
```js
  import { observable } from 'mobx';
```
and running flow typechecking yeilds the following:

```
node_modules/mobx/lib/mobx.js.flow:273
273:     <T>(IModifierDescriptor<T>): T,
                                ^ Unexpected token <
```

Looking at the source in this repo, I think its just a simple syntax error that _should_ look like this:

```js
<T>(value: IModifierDescriptor<T>): T,
```

That being said, I'm a Flow noob, so I could be missing some big picture details or something. I can open a PR with this one liner change if you guys want.

Thanks!

**Comment by wadeanthony0100** [comment]
Somewhat related: fixing this problem reveals the following:

```
node_modules/mobx/lib/mobx.js.flow:239
239:     oldValue: T | typeof undefined
                              ^^^^^^^^^ typeof-annotation `undefined`. Could not resolve name
```

After fixing this, my project is successfully type checked! I can add this to the PR

**Comment by mweststrate** [comment]
Thanks for the PR! Will ship with the next release.
