### ISSUE TITLE
React Component Not Updating When Observable Array Prop is Mutated...?

### ISSUE THREAD

**Issue by wadeanthony0100** [mobxjs/mobx#1286]
Hey, all! I posted this in gitter yesterday, but haven't gotten any responses (yeah I asked for help on Christmas and people were busy, imagine that 😆). I'm having a weird maybe-a-noob- problem.

I'm trying to make a drag and drop interface, where I have models with observable arrays of objects, and when the user drags elements from one area to another, I remove the object representation from one observable array and into another. The problem is, when I remove the object, the observable array shows that it's gone, but the react rendering still shows it (it gets rendered in both places until I drag another element in the source area, then it disappears). Clearly I'm doing something wrong such that mutations aren't triggering re-renders, but I have no idea what. ~Oddly, insertion does render just fine, which is why I'm so confused~ Insertion sometimes works, sometimes doesn't, either way, Im still confused lol

If anyone can help, the code is in this [repo](https://github.com/wadeanthony0100/Plan-Your-Courses-React), on the WIP-drag-n-drop branch
[Here](https://github.com/wadeanthony0100/Plan-Your-Courses-React/blob/WIP-drag-n-drop/src/stores/models/PlanModel.js#L68) is where I'm mutating the observable arrays
[Here](https://github.com/wadeanthony0100/Plan-Your-Courses-React/blob/WIP-drag-n-drop/src/components/Term.jsx) is the react component that renders that observable array

For reference, I'm trying to recreate [this site](https://planyourcourses.com/) (click browse > click a course > click load to see the view I'm trying to recreate).

Any help is greatly appreciated, thanks!

**Comment by urugator** [comment]
Note that observables used in the "render callback" passed to Droppable are NOT observed, because they are not accessed inside `observer` - they are accessed inside Droppable  (during it's render), which is not an observer.
You may try:
```javascript
(provided, snapshot) => <Observer>{() => <div></div>}</Observer>
```

**Comment by wadeanthony0100** [comment]
Wow, that totally fixed it, thanks for the prompt and accurate response, @urugator!

**Comment by prfcto2** [comment]
that was just awesome! thanks @urugator!
