### ISSUE TITLE
Use with Reason?

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx#1288]
Quick Google didn’t yield anything. 

Any thoughts on working on reactive state management with Reason? Some of the pattern matching, type checking and functional helpers make it an exciting possibility, but I’ve already grown so fond of reactivity I’d want to bring mobx along for the ride. Just wanted to open a discussion of the feasibility/desirability of doing so.

**Comment by mweststrate** [comment]
I have no clue :) Like usual, any community initiative is welcome
