### ISSUE TITLE
Create template for mobx stores

### ISSUE THREAD

**Issue by amaurymartiny** [mobxjs/mobx#1290]
I have a:

3. [x] Idea:

  * [x] What problem would it solve for you?

I have 10+ stores which have 90% of code in common:

```javascript
// Store to get the latest price of something
class PriceStore {
  @observable price;
  @observable error;

  constructor() {
    someSocket.on('price', this.setPrice);
    someSocket.on('price_error', this.setError)
  }

  static instance = null; // To enforce a singleton

  static get() {
    if (!PriceStore.instance) {
      PriceStore.instance = new PriceStore();
    }
    return PriceStore.instance;
  }

  @action setPrice = price => this.price = price;

  @action setError = error => this.error = error;
}
```

```javascript
// Store to get the latest signed up user
class LatestUserStore {
  @observable latestUser;
  @observable error;

  constructor() {
    someSocket.on('latestUser', this.setLatestUser);
    someSocket.on('latestUser_error', this.setError)
  }

  static instance = null; // To enforce a singleton

  static get() {
    if (!LatestUserStore.instance) {
      LatestUserStore.instance = new LatestUserStore();
    }
    return LatestUserStore.instance;
  }

  @action setLatestUser = latestUser => this.latestUser = latestUser;

  @action setError = error => this.error = error;

  @computed get fullname() { ... }; // This store has an additional computed value.
}
```

My problem is: how can I factorize this 90% of code?

Ideally, I would like to write myself a `createMobxStore` function, so that I could use it the following way:

```javascript
const PriceStore = createMobxStore('price');
// Now I'll be able to use PriceStore as if it was defined like above.

const BaseLatestUserStore = createMobxStore('latestUser');
class LatestUserStore extends BaseLatestUserStore {
  @computed get fullname() { ... };
}
// Now I'll be able to use LatestUserStore as if it was defined like above.
```

I would like some help to write this `createMobxStore` function, if possible at all.

  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?

No, it's quite specific to my app. Though other people might also have this pattern.

  * [x] Are you willing to (attempt) a PR yourself?

I don't think a PR would be needed, but if yes, sure.

**Comment by mweststrate** [comment]
I think this question is best asked on StackOverflow, as it isn't really Mobx related, but more a question about reuse in general. Which depends on many architectural decisions... (singletons, type safety required, etc etc|). You could use inheritance, or utility functions that do the common stuff, or create a factory function that creates a new classes etc.. etc..

**Comment by amaurymartiny** [comment]
Yes, makes sense. For anyone interested: https://stackoverflow.com/questions/48007362/create-a-template-for-classes
