### ISSUE TITLE
Make document easier to read please (screenshot inside)

### ISSUE THREAD

**Issue by 1c7** [mobxjs/mobx#1295]
https://mobx.js.org/getting-started.html
![image](https://user-images.githubusercontent.com/1804755/34511406-513f2a5c-f096-11e7-9cdc-b7cc05c5b097.png)

# Please make these font "normal", there are no need to fancy here 
(and "updates" should be horizontal not this weird 102 degree or something)

### I can read these, but I just hate the font, it take longer time to recognize&not beautiful.
of course, it just personal opinion, I have no right ask you guys to do anything, it just advice
I am learning MobX & Redux.

You can close this issue whenever you want 
😄

**Comment by mattruby** [comment]
Fair point.  Feel free to put a PR in.  I do this this page is due for an overhaul with MobX 4.
