### ISSUE TITLE
computed(expression) runs infinite when async data fetching in it.

### ISSUE THREAD

**Issue by kapilpipaliya** [mobxjs/mobx#1297]
1. I am using computed(expression) as function and doing async actions in it.
2. Issue:
     https://jsfiddle.net/kapilp/97xu8xs7/
 when i uncomment line 31 where i am using computed function. it loops infinite. It should run only once.

**Comment by Means88** [comment]
1. `value` changed 
2. `autorun` 
3. create a new `computed`(1) 
4. create a new promise(1)

Now the autorun reaction has 2 dependencies computed(1) and promise(1), then

1. promise(n) resolved 
2. `autorun` 
3. create a new `computed`(n+1) 
4. create a new promise(n+1)

**Comment by mweststrate** [comment]
Closing as an answer has been provided
