### ISSUE TITLE
Diagrams explaining Mobx

### ISSUE THREAD

**Issue by rodryquintero** [mobxjs/mobx#130]
Hey guys, glad to see this project gaining traction in the React community. Please consider the following suggestions that I think the project needs.

**A diagram explaining the flow of things**
This diagram would be analogous to the Flux diagram we are used to seeing.

<img width="1116" alt="flux-diagram-white-background" src="https://cloud.githubusercontent.com/assets/1271370/13376018/b703b390-dd7d-11e5-8182-b955b4f20cfa.png">

This will help people used to Flux understand how to reason about apps when using Mobx.

**More sample code**
Just more examples of common problems and how to solve them using Mobx. Not just the typical "todo" list example. I would like to see more examples for:

* Handling asyncronous request
* Integration with a Router
* Authentication

Just my two cents.

**Comment by mweststrate** [comment]
A diagram like this one, or does it look to simple ;) (see [concepts & principles](http://mobxjs.github.io/mobx/intro/concepts.html)).
![action-state-view](https://cloud.githubusercontent.com/assets/1820292/13377945/f865bd78-ddf1-11e5-8a32-7513471cb0ca.png)

Good point, I'll extend it a bit to address the same concepts

**Comment by rodryquintero** [comment]
Hahhaha... yeah, something like that :). I guess what I am looking for are conventions on how to do things and structure projects with Mobx.

* Multiples stores or single state atom
* "Connect" every component and subcomponent to the stores or simply or do store handling on a container component.

This will help people transition from Redux/Flux to Mobx.

**Comment by mweststrate** [comment]
Would this help, or should it be more fine grained? The latter would be a bit tricky as everything below this point are architectural decisions up to the developer :)
![architecture](https://cloud.githubusercontent.com/assets/1820292/14343074/cbdf4cda-fc9e-11e5-9129-708ec44ace0c.png)

**Comment by rodryquintero** [comment]
Yes. This makes a good starting point for people used to regular flux libs
and helps to make a mental model of how to structure an application.

Thanks Michel.

**Comment by vinej** [comment]
If you really want something like the first diagram, look here; https://github.com/vinej/react-portal.
For me, the advantage of Mobx is really to be able to use mutable data.

Michel, would be possible to add my example to the list of example to your repository to give an example to the community about a flux pattern ?

Thanks
