### ISSUE TITLE
Creating new objects inside computed value handler

### ISSUE THREAD

**Issue by bedeho** [mobxjs/mobx#1300]
Consider the to classic TODO list case. Lets say I have some part of my UI where I want to provide some alternative UI representation of the `TodoItem` objects, e.g. like a little thumbnail thing with some shortcuts.  I dont want to stuff all the new UI state and action handling into the old `TodoItem` class, because that really does not scale well as I add more parts of my UI that correspond to a todo item, so Id like to create a new UI store type, call it the `TodoItemThumbnail`, and create one such object for each object of the `TodoItem`.

How do I keep the set of `TodoItemThumbnail` objects in synch with the set of `TodoItem` objects?

My first thought was to do something like 

```js
// In some new UI store `TodoItemThumbnailView` which has the `TodoStore` as a dependency, referenced through `this.todoStore`

@computed get
todoItemThumbnails() {
 this.todoStore.todoItems.map((todoItem) => {
  return new TodoItemThumbnail(todoItem)
})
}
```

but this seems a bit wasteful? Whenever a single `TodoItem` is added or removed, I keep recreating all `TodoItemThumbnail`?

**Comment by urugator** [comment]
>  I dont want to stuff all the new UI state

**new UI state**

Note what happens if you put some new state into `TodoItemThumbnail` and then `todoItems` array is modified - the state is lost, because `TodoItemThumbnail` is re-created.
Generally any new state introduced inside `@computed` is temporal - until the `@computed` is recomputed, because some dependency changed. Sometimes this is desirable, sometimes not.

When working with dynamic data you may rather pass them to actions as argument:
```javascript
// in  TodoItemThumbnailView
@action setThumbnailWidth({ todoItem, width }) {  
  todo.thumbnail.width = width;
}
// or use ids
@action setThumbnailWidth({ todoId, width }) {
  const todo = this.todoStore.get(todoId);
  todo.thumbnail.width = width;  
}
```
Storing view relevant data elsewhere than inside todo would be troublesome.

**Comment by bedeho** [comment]
Oh yes, that is a great point, can't believe I missed that problem.

Not sure I am really understanding your alternative here, you suggesting that we keep the set of `TodoItemThumbnailView` objects in synch wiht the set of `TodoItem`s as I suggested, but rather to have all state in the `TodoItem`. If so, then what did we really gain? why not just keep everything in the `TodoItem`? Either way we have not solved my original problem, no?

**Comment by urugator** [comment]
> If so, then what did we really gain?

Ability to introduce view specific state and logic without the need to modify `TodoItem` class.
`TodoItem` provides a generic way to retrieve view specific data, but doesn't have to know how the actual data are shaped or how to manipulate them.

**Comment by spion** [comment]
I tend to use a WeakMap based store

```
class DerivedStore {
  cache = new WeakMap()
  constructor(factory) { this.factory = factory; }
  get(item) { 
    let derivedItem = this.cache.get(item); 
    if (derivedItem == null) {
      derivedItem = this.factory(item);
      this.cache.set(item, derivedItem);
    }
    return derivedItem
  }
}

let todoItemThumbnails = new DerivedStore(todo => new TodoItemThumbnail(todo))

todoItemThumbnails.get(todoItem).computedProperty
```

Not 100% sure if its the right approach

**Comment by urugator** [comment]
I would only suggest to wrap `get(item)` into `action` or `untracked`, because it will most likely run during derivation and we don't want to subscribe for observables accessed inside factory...

**Comment by spion** [comment]
Forgot that this won't work too well if a small subset of items needs to be cached in a derived store at any time, but a large set of original items needs to be kept in memory.

For example, a 1000 item todo list is not expensive, but 1000 image thumbnails might be costly when all you need is to show 5 of them at any given time. In that case you can swap the WeakMap with a LRU map: https://github.com/rsms/js-lru

**Comment by mweststrate** [comment]
Question seems answered. Feel free to reopen if it isn't
