### ISSUE TITLE
Should be able to specify reaction onError at initialization

### ISSUE THREAD

**Issue by adamabeshouse** [mobxjs/mobx#1301]
It's not possible to add a custom error handler to an autorun in a way that handles if the error is thrown on initialization and first run.

https://jsfiddle.net/akz7rz1p/1/

A fix would be to be able to specify the error handler at initialization of the reaction.

**Comment by adamabeshouse** [comment]
awesome, thanks!

**Comment by mweststrate** [comment]
Closing as this will be added to mobx4
