### ISSUE TITLE
Q: Inject navigation parameters from react-navigation?

### ISSUE THREAD

**Issue by hardcodet** [mobxjs/mobx#1303]
Question / Idea:

MobX' injects make my life so much better! In contrast, this basically makes eyes bleed (second property in `Props` and the last line):

```
export class Props {
    //life is good here:
    someStore: SomeStore;

    //I need to manually set that property in a sub component to get to the parameter
    navigation: any;
}


@inject("someStore")
@observer
export class MyComponent extends React.Component<Props> {
    @observable navParameterObject: Foo;

    componentWillMount() {
        //extract the parameter from navigation
        this.navParameterObject = this.props.navigation.state.params.navParameterName;
    }
}
```

It would be super awesome if MobX could handle navigation parameters just the same and optionally provides them a properties that are injectable as below. I'm aware that this is not really MobX' responsibility, but: would that be feasible?

```
@inject("someStore")
@inject("navParameterName"); //yay!
@observer
export class MyComponent extends React.Component<Props> {
}
```

**Comment by urugator** [comment]
I am not familiar with react-navigation, but copying props to component observable fields or state usually is not a good idea in the first place.... it causes state ("source of truth") duplication ... you know the  `this.props.navigation.state` won't be synchronized with `this.navParamObject` ... is this intended?

**Comment by mweststrate** [comment]
Tip: `@computed get navParameterObject() { return
this.props.navigation.state.params.navParameterName }` is probably what you
are looking forward if you insist on having a short-hand accessor to the
thing

Op do 18 jan. 2018 om 04:14 schreef urugator <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing as the proper solution has been proposed
