### ISSUE TITLE
isObservable returns false on WeakMap defined as decorator @observable

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx#1312]
mobx@3.4.1

```js
import { observable, isObservable, isObservableMap } from "mobx";

class Test {
  map = observable(new Map());
  @observable decMap = new Map();


  weakMap = observable(new WeakMap());
  @observable decWeakMap = new WeakMap();
}

const t = new Test();

console.log('isObservable(map):', isObservable(t.map)); // true
console.log('isObservable(decMap):', isObservable(t.decMap)); // true
console.log('isObservable(weakMap):', isObservable(t.weakMap)); // true
console.log('isObservable(decWeakMap):', isObservable(t.decWeakMap)); // false
```

Repro: https://codesandbox.io/s/98p5m22qxo

As you can see only `isObservable` call for `@observable decWeakMap = new WeakMap()` returns `false` out of all the cases above. If it's defined as `weakMap = observable(new WeakMap())` then `isObservable` returns true which makes it inconsistent and dependent on the way it is declared.

**Comment by spion** [comment]
Thats because the WeakMap is not actually observable, and the `Map()`s are being converted to mobx-style maps https://mobx.js.org/refguide/map.html

**Comment by le0nik** [comment]
I understand that WeakMap's values won't become observable but I still find it weird that `observable` and `@observable` make `isObservable` behave differently in this case. You can reasonably expect `WeakMap` to be at least shallow observable as a value(meaning that subscribers would be notified if we replaced it with another value), but it's not the case. Even if I change `@observable decWeakMap` to `@observable.ref decWeakMap` `isObservable` still returns `false`.

**Comment by mweststrate** [comment]
Provably you are using isObservable wrong. You shouldn't be asking whether
the map is observable, but instead whether the property that contains it is
observable. So isObservable(This, "myprop") instead of
isObservable(This.myprop)

Op zo 21 jan. 2018 16:12 schreef Leonid Nikiforenko <
notifications@github.com>:
