### ISSUE TITLE
memory leak for reaction

### ISSUE THREAD

**Issue by k9982874** [mobxjs/mobx#1314]
when you redirect a page which has a reaction to another page then memory was leaked.
the reaction does not destroy totally.

when you redirect back you have two same reaction, reaction will be execute twice.

pseudocode
```
class A {
    componentDidMount() {
        if (!this.props.action.isDone) {
            this.props.routing.push('/b');
        }
    }

    doneReaction = reaction(
        () => this.props.action.isDone,
        state => {
            console.log(this.props.startupAction.isDone)
        },
    );
}
```

```
class B {
    componentDidMount() {
        this.props.action.isDone = true;
        this.props.routing.push('/a');
    }
}
```

if you access `A -> B -> A`, because the first `A` not release we have two `A` instances.
the memory leaked, `doneReaction` will execute twice.

**Comment by mweststrate** [comment]
You should clean up the `doneReaction` (by calling it) in your
`componentWillUnmount`

Op ma 22 jan. 2018 om 10:28 schreef k9982874 <notifications@github.com>:

**Comment by k9982874** [comment]
@mweststrate thanks for your quick reply.
i tried `doneReaction = null` not work.
i google how to release reaction no useful answer.

so would you like tell me how to cleanup the reaction?

**Comment by k9982874** [comment]
@mweststrate i found the method in official docs, just call the reaction for release.
