### ISSUE TITLE
store property as autorunAsync

### ISSUE THREAD

**Issue by janat08** [mobxjs/mobx#1317]
Welcome to MobX. Please provide as much relevant information as possible!

3. [x] Idea:
I have a slider that modifies state immediately to reflect on UI yet that triggers expensive computations on which a lot of other computations depend on, so that if the computation is put into autorunAsync that store initialization breaks, yet the computation depends on store itself and so can't just run as a function on some field for initialization. I only care for the debounced computed property.
  * [x] What problem would it solve for you?
Expensives computations or those that trigger a lot deeply interwoven with store making it difficult to use autorunAsync.
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
I don't know how this could be implemented, but if it's a getter modifier then yes.
  * [x] Are you willing to (attempt) a PR yourself?
No.

**Please be sure to close your issues promptly.**

**Comment by mweststrate** [comment]
computeds will not be debounced, as that breaks the promise of MobX that
computed values will always be consistent with the state. Why don't you
debounce the state updates? Probably using a temporarily, separate
observable for the slider itself?

Op di 23 jan. 2018 om 09:17 schreef zhan ishzhanov <notifications@github.com

**Comment by janat08** [comment]
somehow trying to bridge temporary and actual states failed for no reason
within autorun with it not executing at all.

On Tue, Jan 23, 2018 at 3:27 PM, Michel Weststrate <notifications@github.com

**Comment by janat08** [comment]
I only was asking for the option.

**Comment by mweststrate** [comment]
No problem. The alternative I suggested should work out great I think. If it doesn't best set up a fiddle demonstrating the problem.
