### ISSUE TITLE
@computed not work without autorun

### ISSUE THREAD

**Issue by elppac** [mobxjs/mobx#1320]
```js
import { observable, computed, autorun, toJS} from 'mobx';

class O {
  @observable
  x = observable.map({
    a: 1
  });
  y = observable.map({ 
    a: 2
  });
  @computed
  get X() {
    console.log('X computed')
    return JSON.stringify(toJS(this.x));
  }
  @computed
  get Y() {
    console.log('Y computed')
    return JSON.stringify(toJS(this.y));
  }
}
const o = new O();
autorun(() => {
  console.log('print:', o.X);
});
console.log(o.X)
console.log(o.X)

console.log(o.Y)
console.log(o.Y)
```
=>

```
X computed
 total: {"a":1}
 {"a":1}
 {"a":1}
Y computed
 {"a":2}
Y computed
 {"a":2}
```

**Comment by urugator** [comment]
https://mobx.js.org/refguide/computed-decorator.html

>Nor will a computed property re-run if is not in use by some other computed property or reaction. In such cases it will be suspended.
>
>This automatic suspension is very convenient. If a computed value is no longer observed, for example the UI in which it was used no longer exists, MobX can automatically garbage collect it. This differs from autorun's values where you must dispose of them yourself. It sometimes confuses people new to MobX, that if you create a computed property but don't use it anywhere in a reaction, it will not cache its value and recompute more often than seems necessary.*
