### ISSUE TITLE
Reaction doesn't converge to a stable state after 100 iterations - Nashorn - React 16

### ISSUE THREAD

**Issue by lincolncooper** [mobxjs/mobx#1325]
I have a problem creating any type of reaction when using React 16 and Nashorn. The same code works without any problem with React 15.6.2.

To demonstrate the problem I have created a simple example that creates a component which is a DIV being passed a store. In the component I try and create a reaction. If the reaction is created in **componentDidMount** it works but if it is created anywhere else, i.e. in **componentWillMount**, then the there is the "Reaction doesn't converge to a stable state after 100 iterations" error. As said above the reaction works in **componentWillMount** with React 15.6.2.

To test I have used webpack to create a single Javascript file which exposes a method for Nashorn to call. Attached are the relevant files used.

Is there a legitimate reason why the reaction only works in **componentDidMount** or is there an issue with either mobx or react code?

index.js
```
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import Greeting from './greeting';
import { observable } from 'mobx';

export default function() {
  const store = observable({
    name: 'harry'
  });

  return ReactDOMServer.renderToString(<Greeting store={store }/>);
}
```

greeting.js
```
import React from 'react';
import { observer } from 'mobx-react';
import { reaction } from 'mobx';

export default observer(class Simple extends React.Component {
  componentWillMount() {
    reaction(() => this.props.store.name, data => console.log('data:', data));
  }

  componentDidMount() {
  }

  render() {
    const name = this.props.store.name;
    return (
      <div>hello {name}</div>
    );
  }
});
```

polyfill.js
`import 'babel-polyfill';`

package.json
```
{
  "name": "simple",
  "version": "1.0.0",
  "description": "simple",
  "main": "index.js",
  "author": "fred",
  "license": "MIT",
  "dependencies": {
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "mobx": "^3.4.1",
    "mobx-react": "^4.3.5",
    "react": "16.2.0",
    "react-dom": "16.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "expose-loader": "^0.7.4",
    "webpack": "3.10.0"
  }
}
```

webpack.config.js
```
const path = require('path');
const addModuleExportsPlugin = require('babel-plugin-add-module-exports');
const dynamicImportBabelNode = require('babel-plugin-dynamic-import-node').default;
const reactConstantElements = require('babel-plugin-transform-react-constant-elements');
const plugins = [dynamicImportBabelNode, addModuleExportsPlugin, reactConstantElements];
const webpack = require('webpack');

const GLOBAL_DEPENDENCIES = { React: 'react' };

module.exports = {
  target: 'web',
  entry: { ssr: ['./src/polyfills.js', 'expose-loader?renderServer!./src/index.js'] },
  // entry: { ssr: ['./src/polyfills.js', './src/index.js'] },
  output: {
    filename: 'simple.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              'react',
              'es2015'
              // ['env', { targets: { browsers: ['last 2 versions', 'IE >= 9'] }, useBuiltIns: true }]
            ],
            plugins
          }
        }
      }
    ]
  },
  plugins: [new webpack.ProvidePlugin(GLOBAL_DEPENDENCIES)],
  node: {
    fs: 'empty',
  }
};
```

**Comment by mweststrate** [comment]
Maybe stupid question, but what is Nashorn?

**Comment by lincolncooper** [comment]
Nashorn is the Java Javascript engine for doing Server Side Rendering (if Node is not an option!). It basically executes Javascript code and creates a String result that can then be returned to the client. Very useful when used with React as when the client version of the same code executes it reconciles only the differences in the DOM so you get the speed of the Server and flexibility of the client. Here is some info about Nashorn (it's predecessor was Rhino):

http://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/

**Comment by lincolncooper** [comment]
Looks like someone else had a similar issue:

https://github.com/mobxjs/mobx-state-tree/issues/12

**Comment by mweststrate** [comment]
Sounds like a bug in Nashorn then (Safari had also some bugs around object.defineProperty in the past). Not sure what to do with it here. I think your best chance is to file a bug at Nashorn, or work around it with cDM. 

Chanches are that something more low level in Mobx / React doesn't work on Nashorn. If you happen  to find precisely where Nashorn behaves differently and there is a straightforward workaround for it, a PR is welcome so that future users might benefit form it as well until the underlying issue is fixed.

**Comment by mweststrate** [comment]
But wait; despite all that, you should not be creating reactions in your react components when using server side rendering at all. It is pointless as there is only one render pass anyway. The reason that cDM is probably because that hook isn't called at all server side

**Comment by lincolncooper** [comment]
You are right that reactions are not needed server side - at least the execution when a value changes. If the code is shared between server and client (as the idea of SSR is to usually do this) then the creation of the reaction is executed during the first pass. This is course could be avoided by putting all of the creations behind a flag which specifies where the code is being executed although this is not ideal.

The strange thing is that everything is working fine with React 15.6.2 and is broken with React 16 (any version). I have also tried the latest version of Nashorn but still it doesn't work.

I agree that it is probably something at a low level as all of the code works fine with React 16 in the browser - I was hoping that you could shed some light on the problem - failing that I will try either isolating the creation of the reactions or move all of the reactions to the componentDidMount.

If I find out any more then I will share the knowledge. Thanks for the time being.
