### ISSUE TITLE
Improve '@observable items = []' handling/understanding

### ISSUE THREAD

**Issue by KnisterPeter** [mobxjs/mobx#1326]
3. [X] Idea:
The `@observable` decorator should create a getter/setter pair instead of replacing the value (maybe it already does. (Related to #1316)
This would allow to replace the array content instead of creating a new array.

Example in pseudo code below.

  * [X] What problem would it solve for you?
Right now creating an obserable array by a decorator and replacing the array later on will create a new obserable array, right?
This breaks the reference in certain places if the reference is resolved to early (e.g. destructuring).
    
  * [X] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
Yes, I think this will easy the use of observable arrays and meet the expectations.
    
  * [X] Are you willing to (attempt) a PR yourself?
    Sure

### Example
```js
class Store {
  @observalbe items = [];
  update() {
    this.items = fetchFromApi();
  }
}
```
Instead of replacing `this.items` in the update method, I think it would be better to have the decorator replace the content of the entier array and not replace the reference.

**Comment by urugator** [comment]
I am rather against the idea, simply because it introduces exceptional behavior and doesn't solve the whole "problem". There are many situations where user has to be aware that things are passed by reference and not by value:
```javascript
// object
@observable item = {};
update() {
  this.item = fetchFromApi();
  // VS
  Object.assign(this.item, fetchFromApi());
}

// nested objects/arrays
@observable item = { nested: {} }; // or [[], []]
update() {
  this.item = fetchFromApi();  
  // VS
  _.merge(this.item, fetchFromApi())  
}

// array of items with identity
@observable items = [{ id: 0 }, { id: 1 }];
update() {
  this.items = fetchFromApi();  
  // VS  
  const items = fetchFromApi().map(item => {
    const existing = this.items.find(i => i.id === item.id);
    return existing 
      ? Object.assign(item, existing)
      : item;       
  })  
  this.items.replace(items);  
}
```
I also think it could cause some problems or confusion at some scenarios (moving observable array), however these would be quite rare I quess. Mostly I don't like the fact that it deviatates from standard behavior and it could paradoxically create additional mental overhead.

**Comment by mweststrate** [comment]
Closing this discussion in favor of #1316
