### ISSUE TITLE
autorun not triggered

### ISSUE THREAD

**Issue by richdyang** [mobxjs/mobx#1327]
**Example**
[![Edit Codesandbox Boilerplate](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/38211jn455)
```javascript
import 
{
  observable, action, 
  autorun, extendObservable,
  isObservable
} from 'mobx'

class Component {
  @observable editing = false

  constructor() {
    // extendObservable(this, {editing: false})
  }

  toggleEditing() {
    const prev = this.editing
    this.editing = !this.editing
    const current = this.editing
    console.log(prev + " -> " + current)
  }

  render(scope) {
    // it should access here!!! 
    console.log(scope['editing'])
    console.log('rendering')
  }
}

const component = new Component()

const scope = Object.create(component, {})


document.getElementById('button').onclick = () => {
  component.toggleEditing()
}

autorun(() => component.render(scope))
```

The render() cannot be trigger after the first time. I changed to `extendObservable`, it works.

**Comment by mweststrate** [comment]
`render` doesn't use any observable data, so it will never rerun because
`toggleEditing` won't cause a change in the rendering.

Op di 30 jan. 2018 om 04:45 schreef Chao Yang <notifications@github.com>:

**Comment by richdyang** [comment]
@mweststrate why? console.log(scope['editing']), I access ‘editing’ by scope’s prototype

**Comment by mweststrate** [comment]
Your updated examples modifies `component`, but not `scope`. (Just add `console.log(scope.editing)` to `toggleEditing to see that). Btw, also note that your object setup is highly confusing, as you use an _instance_ of an class as the _prototype_ for a new object (which you further don't use in the example, except for the rendering). 

Please make sure you have read [What does MobX react to](https://mobx.js.org/best/react.html), and if you still have questions after that use clear, coherent example.

**Comment by richdyang** [comment]
I found the problem is the lazy initialisation of property. The first when i access the property `editing`, the property will be defined on `scope` object, not the `component` object declaring this observable.

So how can I enable eagerly defining observable property?

**Comment by mweststrate** [comment]
It depends a bit on whether you are using babel or typescript, as they have
subtle different semantics in this area when transpiling decorators.
extendObservable might then be the best option indeed, as it makes very
explicit *when* the property will be made observable, and always creates
the property on the target object, and not in the prototype

Op di 30 jan. 2018 om 13:22 schreef Chao Yang <notifications@github.com>:
