### ISSUE TITLE
Can't use `observableMap.values()` outside of action

### ISSUE THREAD

**Issue by pstanton** [mobxjs/mobx#1329]
I've created a "store" object:

```
import { extendObservable, action } from "mobx";
import { clone } from "../Util.js";

export default class InstallationStore {
	constructor() {
		extendObservable(this, {
			jobs: []
		});
	}

	updateState = action.bound(function(cloudJobs) {
		let tmpJobs = new Map(cloudJobs);
		tmpJobs.forEach((value, key, map) => {
			map[key] = this.toUiJob(clone(value));
		});
		console.log("map values", tmpJobs.values());
		this.jobs = tmpJobs;
		console.log("jobs is", this.jobs);
		console.log("obs.map values", this.jobs.values());
	});

	toUiJob(job) {
		return job;
	}
}

```
When run, the logs show:

> map values > MapIterator {{…}, {…}}
> jobs is > ObservableMap {enhancer: ƒ, name: "InstallationStore@1.jobs", $mobx: {…}, _data: {…}, _hasMap: {…}, …}
> obs.map values > (2) [{…}, {…}, __$$iterating: true, next: ƒ]

However when I use the value in my component.render I get the error:

> TypeError: store.jobs.values is not a function

If I comment out the line that causes the error, and just log the jobs object I get:

> jobs is > ObservableMap {enhancer: ƒ, name: "InstallationStore@1.jobs", $mobx: {…}, _data: {…}, _hasMap: {…}, …}

**Comment by whphhg** [comment]
You are setting `this.jobs` as an `Array` in `extendObservable` and later overwriting it in an action to be a `Map`. Try setting `this.jobs` to `new Map()` in `extendObservable` and instead of overwriting the whole map in `updateState`, update or set the items in `this.jobs`.

**Comment by pstanton** [comment]
yes, initialising as `new Map()` instead of `[]` did the trick, thanks! the other advise is good too but i'm just trying to get off the ground for now, optimisation later.
