### ISSUE TITLE
Create babel preset for all the things typically used with MobX

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#1331]
See this conversation for background: https://twitter.com/kentcdodds/status/958801650348539904

Things typically used in MobX projects
* [ ] decorators-legacy
* [ ] classes
* [ ] field initializers
* [ ] generators
* [ ] async / await

**Comment by mweststrate** [comment]
Should address for example #1328 (and many others)

**Comment by rossipedia** [comment]
I'll give it a shot

**Comment by rossipedia** [comment]
Well, that was fairly easy. Finishing up the README and I'll publish it in a few here

**Comment by rossipedia** [comment]
Looks like somebody already has a `bable-preset-mobx`, so I submitted a PR there instead :)

**Comment by mweststrate** [comment]
Does it even work?
https://github.com/zwhitchcox/babel-preset-mobx/blob/master/src/index.js#L3
looks
like a syntax error to me

Op wo 31 jan. 2018 om 23:14 schreef Bryan J. Ross <notifications@github.com

**Comment by rossipedia** [comment]
yeah, looks like that one is broken as it stands. While I'd like to use the `babel-preset-mobx` package name, if we don't get any movement on the PR from @zwhitchcox I'll go ahead and publish it under `babel-preset-mobx-common`. But I want to give it a little bit before doing that as it might be confusing down the line:

"Add `babel-preset-mobx-common`"
"ok" (adds `npm i -D babel-preset-mobx`)
..."nothing's working"

and so on

**Comment by zwhitchcox** [comment]
Much appreciation for the PR, pulled and published!

**Comment by mweststrate** [comment]
Awesome!  Could you add a PR to the gh-pages @rossipedia ? 

I'm also wondering, could React Native be served by the same package somehow? There is stuff like `react-native-stage-0/decorator-support` needed. Or is that no longer the case with `babel-preset-mobx`? (sry, babel is endlessly confusing for a TypeScript fanatic ;-))

**Comment by rossipedia** [comment]
Yeah I'll pop something in the `gh-pages` branch when I get a few minutes later today (unless somebody beats me to it)

**Comment by grayflow** [comment]
maybe give scoped packages a try?

**Comment by mweststrate** [comment]
Updated the docs. Tnx for the preset @rossipedia / @zwhitchcox !

**Comment by tiann** [comment]
@mweststrate Yes, it works great with react-native.

In fact, [babel-preset-mobx](https://www.npmjs.com/package/babel-preset-mobx) use four plugins:

1. transform-decorators-legacy
2. transform-class-properties
3. transform-es2015-classes
4. transform-regenerator

`transform-class-properties`, `transform-es2015-classes`, `transform-regenerator` is included in [babel-preset-react-native](https://github.com/facebook/react-native/blob/master/babel-preset/plugins.js) already.

So, using `babel-preset-mobx` with react-native is the same with using `transform-decorators-legacy` with react-native. But it is much more easier :)

Great job 👍 

I thin you can add it to document, too :)
