### ISSUE TITLE
Is it possible to keep a computed "alive" without recomputing it?

### ISSUE THREAD

**Issue by spion** [mobxjs/mobx#1332]
1. [ x ] Question

I have a computed that changes a lot and depends on many other computed values, making it expensive to recompute (e.g. serialization). However, I don't need its value all the time, only at certain actions (e.g. for undo and redo).

If I call the computation on every change (e.g. add a dummy autorun), even the cheap version with many pre-computed values can get expensive (for example, movement events could trigger a change on every pixel) 

If I only call the computation when I need the value, it goes away (gets disposed) immediately together with its dependencies, since there are no dependants that need it.

The question is, is it possible to tell mobx to keep a computed value and its dependencies alive without recomputing it? It could stay dirty until its invoked.

If not, would it be possible to add an API to do this? e.g. `mobx.keepAlive(obj, 'computedName')`

**Comment by mweststrate** [comment]
It might be possible to achieve something like this by creating a custom Reaction that uses your computed value, and that basically doesn't track until you want it to; in mobx-react the observer component also separates the step of being notified is has become dirty, and computing the next value.

**Comment by spion** [comment]
Hmm, I wasn't able to figure out how to do this by looking at the sources. It seems that once you run startTracking(), all computations will happen.

I guess I would need to

```typescript
class DirtyReaction extends Reaction {
  onBecomeStale() { } // do nothing
}
```

Then I can create the reaction and `.schedule()` it once, rescheduling it after every change of the tree?

**Comment by urugator** [comment]
Not sure if that's what you're after, but I was solving something similar and solved it by creating the reaction lazily on the first "get". Something like:
```javascript 
get foo() {
  if (!this._dispose) { // or use some flag if you don't want to always keep alive
    this._dispose = keepAlive(this, "_foo"); 
  }
  return this._foo;
}
@computed _foo() {
  return this.a + this.b;
}
// disposer    
dispose() {
  if (this._dispose) {
    this._dispose();
    this._dispose = false;
  }
}
```
Obviously such solution requires wrapping the original computed and using this "wrapper" instead...

**Comment by spion** [comment]
@mweststrate Great, that appears to be working! Interesting.

Here is the final code:

```ts
function keepAlive<T>(expression: () => T) {
  let dirty = false;
  let updateHandler = (): void => void 0; // fn
  let latestValue: T;
  const r = new Reaction('doc-json', function onInvalidate() {
    dirty = true;

    updateHandler = () => {
      r.track(() => {
        latestValue = expression();
      });
      dirty = false;
    };
  });
  r.runReaction();
  return {
    dispose: r.dispose,
    updateNow() {
      updateHandler();
    },
    isDirty() {
      return dirty;
    },
    getValue() {
      return latestValue;
    },
  };
}
```

I think I understand now. Track ensures that all dependant computeds are kept alive. However until the expression is invoked again, the dirty computeds are not "pulled" from. Powerful!

**Comment by mixtur** [comment]
Could this be in the core library? In form of decorator maybe?
It seems to be needed by some people judging by number of duplicate issues.

**Comment by mixtur** [comment]
Will it work if `reference.some.other.computed` is also using livingComputed?

**Comment by mweststrate** [comment]
This issue was closed half a year ago, to avoid everybody needing to read the discussion again to get the context of your question, please open a new one. It also makes sure that people who didn't take part of this discussion, can also see your question.
