### ISSUE TITLE
how to serialize computed properties?

### ISSUE THREAD

**Issue by princewck** [mobxjs/mobx#1334]
I have an object to store auth info, but when I try to access the computed value which values as the user token, I found that I can't strictly serialize it. Who can tell me I to solve this.
below is example code:
```javascript
// test codes
const self = observable({
  manager: false,
  user: {
    token: 't',
    id: 'id'
  }
});
const INIT_TOKEN = observable({
  command: 'invest:token',
  manager: computed(() => self.manager),
  data: computed(() => self.user.token),
  user: computed(() => self.user.id),
})
/** 
 * {command: "invest:token"} it says it just have one property `command`
 *  all other properties gone, I need them to pass to another system for auth
 */
console.log(JSON.parse(JSON.stringify((INIT_TOKEN)))); 
```

**Comment by urugator** [comment]
```javascript
INIT_TOKEN.toJSON = () => Object.assign({
  manager: INIT_TOKEN.manager,
  data: INIT_TOKEN.data,
  user: INIT_TOKEN.user,
}, INIT_TOKEN);
```
Usually you don't need to serialize computeds because they would be "redundat" ... they can be always computed from other serializable values.  
Or in other words how would you deserialize computed values? You would have to de-compute them...

**Comment by mweststrate** [comment]
Closing question as answer have been provided. Deviating from the build-in JSON serialization is up to userland code, as MobX isn't a serialization library (like serializr ;-))

**Comment by urugator** [comment]
@mweststrate
> Deviating from the build-in JSON serialization is up to userland code

The Mobx kinda deviates here, because it makes computed non-enumerable, which is not the case for standard getter:
```javascript
const o1 = {
  get comp() {
    return 5;
  }
}
const o2 = Mobx.observable({
  get comp() {
    return 5;
  }
})
console.log(JSON.stringify(o1)); // { comp: 5 }
console.log(JSON.stringify(o2)); // {}
```
But as I said, I think this is preferred behavior ...

**Comment by saysmaster** [comment]
There are cases where the computed's value is based on observable values outside of the object itself. For instance, when using closures. Then, at some point you may want to deserialize the whole object along with its computed values to send it in a 3rd party component that doesn't know about observability and the rules to recompute the value.

In my case, I have a data grid component that creates column properties from an array of columns and an array of column options. The array of columns is provided as an observable array, and the 'visible' property of each column is a getter that depends on a context value (the logged-in user in the global app store).

I have a computed property in my grid component (which is an observer also),  which returns the calculated column properties array. When I was testing and changing the logged in user, I realized it did not affect the grid view. After debugging I realized the toJS method did not return the 'visible' property of each column (making every column permanently visible).

The grid view is not mobx-aware so I do all the calculations and computeds in a top level component that sends the plain js data to the underlying grid view.

**Comment by urugator** [comment]
I think that mentioned use case doesn't relate to serialization - as already mentioned, serialization is bidirectional process, how do you deserialize computed value?
The `toJS` is intended to be called on simple data structures, for anything a bit smarter you will have to come up with own "serialization/mapping" strategy.
However, I see your point when it comes to passing data to 3rd party libs. Perhaps `toJS` and `toJSON` should treat computed's differently.

**Comment by mweststrate** [comment]
Maybe a customizer function like in JSON.stringify would be useful, for
userland customization of serialization. See
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter.
PR welcome!
