### ISSUE TITLE
help needed with noob question on observable behavior 

### ISSUE THREAD

**Issue by sukeshlaghate** [mobxjs/mobx#1335]
I have a:
1. [X] Question: I am new to react and Mobx, while trying to implement observables and observers(react) I came across this seemingly (at least to me) strange behavior. Lets say I am creating a tags list where user selects some topic from drop down and that gets added as tag. To implement this I am using reactjs, semantic-ui-react and Mobx. The code is available at  https://codesandbox.io/s/13ork5lzkq. 
When you run the code you will see some preloaded tags.
Expected behavior is:  I should be able to add tags by clicking on 'add Tag' button/dropdown and selecting items. Selected items appear as colored tags above and should get removed from the dropdown list. I am able to achieve this. 
Next when I click on x icon in tag it should get "deleted" i.e. get removed from tags list and added back to drop down list. now here is the **strange behavior**: For the preloaded  tags  i am able to "delete" them off however, when I am adding the tags from dropdown and then trying to delete them they never get deleted for e.g add less and MSSQL 2016 now try to delete them they wont get deleted. instead In console you will see action of adding the tag being triggered repeatedly.

2. [X] Provide a **minimal** sample reproduction. you can find the sample at: https://codesandbox.io/s/13ork5lzkq

How can I achieve the expected behaviour of removing the tags and adding them back to dropdownlist. 
Thanking you in advance for any pointers/help in getting this resolved at earliest.

**Comment by urugator** [comment]
The problem is here: `renderLabel={this.onTagSelection}` 
Render function must be without side effects (you can't modify state/observables during render).
What happens is that you delete the item, the component is notified to re-render, dropdown is rendering label using your provided  `onTagSelection` function, which adds the `tag` again to list , resulting in:
> proxyConsole.js:68 Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

**Comment by sukeshlaghate** [comment]
Thank you @urugator for explaining and pointing out the problem. closing the question.
