### ISSUE TITLE
don't throw exception  when assign a primitive value to @observable.shallow?

### ISSUE THREAD

**Issue by grayflow** [mobxjs/mobx#1336]
or make @observale shallow by default?

**Comment by jamiewinder** [comment]
It doesn't make sense to use `@observable.shallow` with anything that isn't a collection, so throwing if you try to seems sensible?

**Comment by urugator** [comment]
@jamiewinder you may not know the type of the value during definition ... the `@observable.deep` also doesn't throw on primitives, even though it also doesn't make sense...

**Comment by grayflow** [comment]
the requirement is exactly as @jamiewinder pointed out!

**Comment by grayflow** [comment]
maybe not to make assumption in api can lead to better api? just provide reasonable defaults and leave room for customization.

**Comment by mweststrate** [comment]
Closing in favor of the discussion in #1316, which basically makes the same point :)
