### ISSUE TITLE
Mobx decorators not working correctly when using webpack with ts-loader and babel-loader

### ISSUE THREAD

**Issue by AndrewMorsillo** [mobxjs/mobx#1339]
I have the following simple code

```
import {  observable, isObservable } from "mobx"

class TestStore{
    @observable data = new Data()
}

class Data{
    @observable _id: string
    @observable name: string
}

let test = new TestStore()
console.log("Test is observable ", test.data, isObservable(test.data))
```

This outputs `Test is observable Data{} false`. I would expect `isObservable(test.data)` to return true. 

Edit: more detail

My app has a similar structure. I have a class User with a lot of `@observable` properties on it. This gets stored in an `@observable` field on my store class but `isObservable(mystore.user)` is false. I don't initialize any of the properties on my user right away, I set them later when data is received from the server by `extendObservable(mystore.user, {...userDataFromServer})`. I noticed in the example above that `isObservable(test.data)` is true if I initialize one of the properties on `data`. Shouldn't a class instance be observable even if none of its properties have values yet? 

It seems like it may have to do with the way I have typescript/webpack/babel configured in my project. Here is a minimal reproduction.

https://github.com/AndrewMorsillo/mobxdecoratorbug

**Comment by mweststrate** [comment]
what does `isObservable(test, "data")` yield?

Op ma 5 feb. 2018 om 01:02 schreef amorsillo <notifications@github.com>:

**Comment by mweststrate** [comment]
Is this still an issue @AndrewMorsillo ? Otherwise please close the issue
