### ISSUE TITLE
toJS doesn't convert observable objects nested within non-observable primitives.

### ISSUE THREAD

**Issue by spion-h4** [mobxjs/mobx#1341]
Example: https://jsfiddle.net/j93d0ab8/

If thats intended, what should we use to do this kind of "clear all observables" conversion?

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#260

**Comment by spion** [comment]
Ok. Would be nice to have a "clear all observables" conversion that works on all plain records, maps and built in arrays, as well as mobx records, maps, and arrays (but not classes).

**Comment by mweststrate** [comment]
The conceptual problem with that is that it would require mobx to form an
opionion about all data types outside mobx, stuff that is much better
handled by general purpose libraries like lodash and such. For this
specific issue you could try combining lodash deepclone with toJS for the
observable data parts. But in general I think  storing observables in
non-observables becomes confusing quickly and I would make the array
observable for good order as well :)

Op di 6 feb. 2018 om 16:20 schreef Gorgi Kosev <notifications@github.com>:

**Comment by spion** [comment]
Yeah, it turned out the original problem was caused by an accidental lodash deepClone anyway, which then a toJS could not correct. The solution was not to deepClone.
