### ISSUE TITLE
please

### ISSUE THREAD

**Issue by Varavarforvar** [mobxjs/mobx#1356]
webpack

options: {
                  cacheDirectory: true,
                  plugins: ["transform-object-rest-spread","transform-runtime",'add-module-exports',"transform-decorators-legacy"],
                  presets: ["env", "react","stage-1"]
                }

——————————————————————————————————————————————
babelrc

{
  "presets": ["env", "react", "stage-1"],
  "plugins": ["transform-decorators-legacy"]
}

_______________________________________________________________________________________________________________

why throw

ERROR in ./src/store/AppStore.js
Module parse failed: C:\Users\yuye\Documents\GitHub\project_order\src\store\AppStore.js Unexpected character '@' (8:4)
You may need an appropriate loader to handle this file type.
|
| class AppStore {
|     @observable todos = []; //todos
| }
|
 @ ./src/app/main.js 11:16-47

**Comment by mweststrate** [comment]
in your webpack config, but transform-decorators-legacy *first*

Op wo 28 feb. 2018 om 11:12 schreef 翟予也 <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing as an answer has been provided. Please be so kind next time to either close the issue, or elaborate on what wasn't fixed @Varavarforvar
