### ISSUE TITLE
Tracking whether an observable/computed is being observed?

### ISSUE THREAD

**Issue by dualscyther** [mobxjs/mobx#1363]
I have a:
1. [x] Question

Is it possible to track the tracked status of an observable/computed value? My particular use case is:

I am making a front end for live messaging. For each conversation, I have two observable arrays that both store messages as objects. One of these arrays stores the pending messages sent from the client (ones that have not yet been confirmed by the server), and the other array reflects the state of the server - i.e. the entire message history. I then have a computed value which simply returns the set union of the two arrays.

My problem is that my particular application has hundreds of separate conversations going on at the same time - but I only want to be polling the server (once every x seconds) for one particular conversation at a time (i.e. the one that the user is currently viewing). There are many ways to approach this problem, but I was wondering if it was possible to have an `autorun` track the tracked status of the `computed` value. It could then call `setInterval` (for polling the server) when the `computed` was tracked, and dispose of the timer when it became untracked.

I understand that this is similar to the example usage of `Atom` - but `Atom` also doesn't make sense because I'm trying to track the tracked status of a `computed` which is also based on other observables.

**Comment by urugator** [comment]
[Maybe this is what you seek?](https://github.com/mobxjs/mobx/issues/992#issuecomment-368169493)

**Comment by mweststrate** [comment]
@dualscyther you don't really need anything fancy for that, you can set that up with reactions. Note that every computed value is an observable in itself. For example:

```
let handler

reaction(
   () => viewStore.currentlyViewingMessage, 
   newSelection => {
       if (handler) clearInterval(handler)
       handler = setInterval(() => fetchDataForMessage(newSelection), 1000
   }
)
```

**Comment by dualscyther** [comment]
@mweststrate you're totally right actually, I think I was overthinking it a little bit - your answer works for my use case but I can definitely foresee the need for `onBecomeObserved` too (when it comes out) - thanks @urugator

**Comment by mweststrate** [comment]
@dualscyther please close issues when they are answered
