### ISSUE TITLE
Plea for help: Mobx in component.  Works local, does not observe when published through NPM

### ISSUE THREAD

**Issue by jason-henriksen** [mobxjs/mobx#1367]
I say "plea for help" because I recognize that this could be a build issue on my end, but I'm not sure how to fix it or even what is wrong.

I have a project called react-json-grid.  

What works: 
> git https://github.com/jason-henriksen/react-json-grid.git
> npm run storybook
Displays a grid that you can select cells, edit them, move around.  With an interactive API explorer that I'm about 1/3rd done building.

What fails:
> npm run build
> npm publish
> ** switch to some other project **
> npm -i react-json-grid
> ** use the grid in a project **
This displays the grid correctly however none of the observable re-renders happen.  I can see in the console log that clicks/keypresses are updating the state, but the components simply do not re-render.

I've tried putting whyRun() into the render methods but get this:
"whyRun() can only be used if a derivation is active, or by passing an computed value / reaction explicitly. If you invoked whyRun from inside a computation; the computation is currently suspended but re-evaluating because somebody requested it's value."  This makes me think that the decorator has not made the store observable correctly, but I don't know what to do the compiler to make it behave the same through NPM as it does when I'm testing locally. 

You can check out the scaffold program I'm using to test react-json-grid at :
https://github.com/jason-henriksen/rjg-test.git

Thank you for any help.  I've got quite a lot of code riding on MobX and I honestly can't imagine working without it.  You guys have saved me SO much time.  Thank you tremendously for any hints or ideas of avenues to explore.

**Comment by mayorovp** [comment]
mobx, react, react-dom and any other libraries must be dependencies, not devDependencies

**Comment by jason-henriksen** [comment]
tried that.  No luck.  Same behavior.

If you have any other ideas, I'd love to hear them.  Thank you.

**Comment by mweststrate** [comment]
@jason-henriksen / @mayorovp  mobx, react, react-dom, mobx-react should be `peerDependencies` *and* should be marked as external in your webpack config so that they don't get bundled into your component

**Comment by jamiewinder** [comment]
I highly recommend Rollup for bundling libraries rather than Webpack which I'd only use for apps. This kind of thing doesn't happen in Rollup because it automatically excludes external code from the produced bundle (it assumes it'll be bundled with your application, via dependencies, instead)

**Comment by jason-henriksen** [comment]
Honestly, at this point I'd just be happy to have it work and get the fine details of packing resolved later.   The fact that it does not react at all when the mobx store changes, and that whyRun makes it look like the Observer isn't tracking things to observe have be baffled.  If the decorators weren't being called, you'd think there would be some kind of error message.  But nothing at all shows in the logs.

**Comment by jamiewinder** [comment]
It looks a lot like packing might be the problem though; if you've got multiple versions of the same packages involved (i.e. one embedded in your library output, one embedded in the application output) then it can wreak havoc.

I've used the webpack-bundle-analyzer plugin in the past to find out if this is the case. It's happened to me a few times!

**Comment by mweststrate** [comment]
Oh, also, disable hot reloading when in doubt. Usually it doesn't
understand classes & decorators in my experience.

Op di 6 mrt. 2018 om 18:54 schreef Jamie Winder <notifications@github.com>:

**Comment by jason-henriksen** [comment]
SOLVED!  In a nutshell, here was the problem.   Starting from my scaffold project:

PS C:\src\oss\rjg-test> npm ls mobx
rjg-test@0.1.0 C:\src\oss\rjg-test
+-- mobx@3.6.1
`-- react-json-grid@1.0.11
  `-- mobx@2.7.0

It seems that the differing versions were causing shenanigans.  I brought the react-json-grid project up to current and then switched from dependencies to peerDependencies.  After uninstalling react-json-grid from the scaffold project and then re-installing it, everything works as expected.

Thank you guys so much for helping out even though it wasn't really your problem.  To my mind mobx is the best thing in all of javascript.  

Thanks again!
