### ISSUE TITLE
Pass stores by props explicitly

### ISSUE THREAD

**Issue by pmonty** [mobxjs/mobx#1368]
Hi all, wondering what the ideal way to pass a store to a smart component is. Was thinking of using @inject or explicitly passing via props. At the moment we are using react router so passing like so:

```    
const stores = {
    store1: new Store1(),
    store2: new Store2(),
    store3: new Store3(),
};
// mobx-react Provider
<Provider {...stores}>
// ..
````

but after reading @mweststrate [How to decouple state and ui](https://hackernoon.com/how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount-cc90b787aa37) I am considering _director_ package to handle routing. Really like the idea behind the state changing the view components.

Testing is also definitely an objective, there will be a UI store for ui state that multiple components are dependent on. So really wondering would explicitly passing be the ideal way or the @inject decorator.

**Comment by mweststrate** [comment]
Either is fine and provide similar semantics. I usually introduce Provider as soon as I would otherwise need to pass stores to components that don't have to know about the stores (e.g. layout components).
