### ISSUE TITLE
[4.0.0-beta.2] ReferenceError: fail is not defined

### ISSUE THREAD

**Issue by heikkilamarko** [mobxjs/mobx#1376]
I migrated my project to use 4.0.0-beta.2. When using extendObservable, I receive the following error:

```ReferenceError: fail is not defined```

I took a look at the MobX source code and found the possible reason:

In `action.ts` file, and in the following line:

``` arg1[arg2] = createAction(name, arg3.value)```

`name` is not defined. Should this be something like:

``` arg1[arg2] = createAction(arg1.name || "<unnamed action>", arg3.value)```

**Comment by mweststrate** [comment]
Thanks for reporting! Fixed in `mobx@4.0.0-beta.3` (this will probably result in some peer dep errors, but you can ignore these)
