### ISSUE TITLE
Line numbers not available in observer component

### ISSUE THREAD

**Issue by pstanton** [mobxjs/mobx#1389]
I have a:

3. [ X] Idea:
  * [X ] What problem would it solve for you?
easier debugging
  * [X ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
of course

When an error is thrown within an observer component, the line numbers are not available.

eg:
```
...
export default inject("store")(observer(MyComponent));
```

> TypeError: someList.slice is not a function
> 
> This error is located at:
>     in MyComponent (created by inject-MyComponent-with-store)
>     in inject-MyComponent-with-store(at MyContainer.js:54)
>     in RCTView (at View.js:71)

is it at all possible to preserve the line numbers during code instrumentation?

**Comment by mweststrate** [comment]
I'm not sure how this relates to mobx(react) in the sense that we could even influence it. Could you set up a minimal reproduction or code sandbox for investigation?

**Comment by pstanton** [comment]
hi michel,

i was only partially hopeful it can be fixed - i'm not familiar with how your injection instrumentation modifies code - and if line numbers can be preserved through this process.

regarding reproduction, 

```
import React, { Component } from "react";
import { observer, inject } from "mobx-react/native";

import { Text } from "react-native";

class App extends Component {
	constructor(props) {
		super();
	}

	render() {
		return <Text>{undefinedVariable}</Text>;
	}
}

export default inject()(observer(App));


```

**Comment by mweststrate** [comment]
Line numbers depend on the build / source map setup, browser etc, and not on something that this library does. `inject` is "just" a function and it doesn't do any recompilation, parsing of javascript or whatever

**Comment by pstanton** [comment]
can you give me any hints about where to look for a solution? i find this very limiting since it's always the line number you're interested in that is missing...

also, is this also a problem when using the '@' style decoration?
