### ISSUE TITLE
[Feature request] Observable tuple

### ISSUE THREAD

**Issue by nunocastromartins** [mobxjs/mobx#1391]
Hi! First of all, thank you for your work!

I'd be interest in having `observable.tuple` as a new observable structure.
The idea is that an `observable.tuple` would behave in a similar manner to an `observable.object`: meaning that it shouldn't track new elements and that it should convert inner `computed` values into derived properties.

The difference being that the value should be (or at least mimic) an array: giving us access to functions such as `forEach`, or `map`.

Note that an `observable.array` currently does not support derived properties; reason why I'm submitting this feature request. _E.g._ `observable.array(['hi', computed(() => 'bye')])[1]` does **not** return `'bye'`; it returns the `computed` object itself.

Changing the behaviour of `observable.array` is likely an unwanted breaking change; thus my proposal.

Once again, thank you for your work!

**Comment by mweststrate** [comment]
I think you can easily achieve this yourself, without needing to modify MobX. Untested code:

```javascript
function tuple() {
  const res = new Array(arguments.length)
  for(let i = 0; i < arguments.length; i++) 
     extendObservable(res, { [i]: arguments[i] })
  return res
}

const myStuff  = tuple(1, 3)
reaction(() => myStuff[0], val => console.log(val))

myStuff[1] = 17 // should not react
myStuff[0] = 2 // should react
```

**Comment by mweststrate** [comment]
See the above test case, it works :)

**Comment by nunocastromartins** [comment]
Lovely, that does work!

I was under the impression that `extendObservable` could not be called on non-observable objects; I now see that it makes the object observable when it isn't already, which is actually quite useful in my case. Thank you for the tip!
