### ISSUE TITLE
Issue with @computed after update to 4.0.0 on React Native

### ISSUE THREAD

**Issue by psycura** [mobxjs/mobx#1396]
Hello, and thank you for this awesome library.
I`m working on RN project, and after update to the 4.0.0 version, stuck with some strange issue. (when downgrading to 3.6.2 everything work fine).
So i have a rootStore:

`import GuiStore from './GuiStore';
import UserStore from './UserStore';
import SchoolsStore from './SchoolsStore';

class RootStore {
    constructor () {
        this.guiStore    = new GuiStore ( this );
        this.schoolsStore = new SchoolsStore ( this );
        this.userStore   = new UserStore ( this );
    }
}

const appStore = new RootStore ();
export { appStore };`

and relevant inner Stores:

SCHOOL STORE
`import { action, computed, observable, toJS } from 'mobx';
import { find, map } from 'lodash'
import firebase from 'react-native-firebase';

const db = firebase.firestore ();

class SchoolsStore {
    
    @observable _schools        = null;
    @observable fetchInProgress = true;
    @observable _school         = null;
    
    constructor ( root ) {
        this.root = root;
        this.toggleFetchProgress ( true );
        this.fetchSchools ().then ( () => {
            this.toggleFetchProgress ( false );
        } )
    }
    
    @computed get schools () {
        return toJS ( this._schools )
    }
    
    @computed get schoolsList () {
        return map ( this.schools, s => {
            return {
                label: s.name,
                value: s.id
            }
        } )
    }
    
    @computed get school () {
        if ( this._school ) {
            return find ( this.schools, school => school.id === this._school )
        }
    }
    
    @action
    toggleFetchProgress ( status ) {
        this.fetchInProgress = status;
    }
    
    @action
    setCurrentSchool ( id ) {
        this._school = id;
    }
    
    fetchSchools () {
        const schoolsRef = db.collection ( 'schools' ).where ( 'subscription.active', '==', true );
        return schoolsRef.get ().then ( collection => {
            const schools = [];
            collection.forEach ( doc => {
                schools.push ( doc.data () )
            } );
            this._schools = [...schools]
        } )
    }
        
}

export default SchoolsStore;
`

USER STORE
`import { action, computed, observable, toJS } from 'mobx';
import firebase from 'react-native-firebase';

const db  = firebase.firestore ();
const FCM = firebase.messaging ();

class UserStore {
    
    @observable userRef         = null;
    @observable _user           = null;
    @observable token           = null;
    @observable fetchInProgress = true;
    
    constructor ( root ) {
        this.root = root;
        
        this.toggleFetchProgress ( true );
        this.msgInit ().then ( () => {
            if ( this.user.activeSchool ) {
                this.root.schoolsStore.setCurrentSchool ( this.user.activeSchool );
            }
            this.toggleFetchProgress ( false );
        } )
    }
    
    @computed get user () {
        return toJS ( this._user ) || null;
    }
    
    @action
    toggleFetchProgress ( status ) {
        this.fetchInProgress = status;
    }
    
    @action
    updateUserField ( { field, value } ) {
        const currentUser = toJS ( this._user );
        if ( currentUser[field] !== value ) {
            currentUser[field] = value;
            switch ( field ) {
                case 'activeSchool':
                    if ( currentUser.schoolsList.indexOf ( value ) < 0 ) {
                        currentUser.schoolsList.push ( value );
                    }
                    break;
                default:
                    break;
            }
            this._user = { ...currentUser };
            
            this.dbUpdateUser ( currentUser );
        }
    }
    
    
    dbUpdateUser ( user ) {
        this.userRef.set ( user );
    }
    
    @action
    async fetchUser ( token ) {
        const ref = db.collection ( 'appUsers' ).where ( 'token', '==', token );
        return ref.get ().then ( async ( collection ) => {
            if ( collection._docs.length ) {
                collection.forEach ( async ( doc ) => {
                    if ( doc.exists ) {
                        this.userRef = db.collection ( 'appUsers' ).doc ( doc.id );
                        this._user   = doc.data ();
                        doc.data ();
                    } else {
                        await this.createUser ( token )
                    }
                } )
            } else {
                await this.createUser ( token )
            }
            
        } )
    }
    
    async createUser ( token ) {
        const ref    = db.collection ( 'appUsers' ).doc ();
        this.userRef = db.collection ( 'appUsers' ).doc ( ref.id );
        const user   = {
            token,
            activeSchool: '',
            role:         'student',
            schoolsList:  []
        };
        await  ref.set ( user );
        await this.fetchUser ();
    }
    
       
    msgInit () {
        return new Promise ( async ( resolve ) => {
            FCM.requestPermissions ();
            await FCM.getToken ().then ( async ( token ) => {
                this.token = token;
                await this.fetchUser ( token );
            } );
            
            FCM.onMessage ( payload => {
                console.log ( 'message received' );
            } );
            resolve ();
        } );
        
    }
        
}

export default UserStore;
`

The issue is happens here - at Login Screen:

```
import React, { Component } from 'react';
import { ScrollView, Image, Text, Picker, StyleSheet, ImageBackground } from 'react-native';
import { observer, inject } from 'mobx-react'
import { Container } from '../components/generic';
import Images from '@assets/images'
import Head from '../components/Login/Head'
import Footer from '../components/Login/Footer'
import FormWrapper from '../components/Login/FormWrapper'
import { computed, when } from 'mobx'

class LoginScreen extends Component {
    
    constructor ( props ) {
        super ( props );
        this.userStore    = props.appStore.userStore;
        this.schoolsStore = props.appStore.schoolsStore;
    }
    
    @computed get fetchInProgress () {
        const userFetching    = this.userStore.fetchInProgress;
        const schoolsFetching = this.schoolsStore.fetchInProgress;
        return userFetching && schoolsFetching;
    }
    
    componentDidMount () {
        
        const { navigation } = this.props;
        
        when (
            () => !this.fetchInProgress && this.userStore.user,
            () => {
                const user = this.userStore.user;
                if ( user && user.activeSchool ) {
                    navigation.navigate ( 'drawerStack' )
                }
            }
        )
    }
    
    navigateTo = ( route ) => {
        this.props.navigation.navigate ( route )
    };
    
    render () {
        
        const { bgImage } = styles;
        
        return (
            <Container column height='100%' width='100%' justify='space-between' alignItems='center'>
                <ImageBackground style={bgImage} source={Images.loginBg}>
                    <Container height='93%' alignItems='center' column justify='flex-start'>
                        <Head mode='school'/>
                        {
                            !this.fetchInProgress && this.userStore.user && !this.userStore.user.activeSchool
                            &&
                            <FormWrapper navigationHandler={this.navigateTo}/>
                        }
                    </Container>
                    <Footer/>
                </ImageBackground>
            </Container>
        );
    }
}

const styles = StyleSheet.create ( {
    bgImage: {
        height: '100%',
        width:  '100%'
    }
} );

export default inject ( 'appStore' ) ( observer ( LoginScreen ) );

```

on launch i receive an error

>  maximum call stack size exceeded

I found out, that if i comment the ` @computed get fetchInProgress` and a when block, and 
` {
                            !this.fetchInProgress && this.userStore.user && !this.userStore.user.activeSchool
                            &&
                            <FormWrapper navigationHandler={this.navigateTo}/>
                        }
`

no error happen, so i think that issue come from using @computed properties.
Why is this happen?

**Comment by mweststrate** [comment]
That is a lot of code. Could you minimize it?

**Comment by psycura** [comment]
Actually, yes.
I tried very simple component, and this error still happen:


`
import React, { Component } from 'react';
import { ScrollView, Image, Text, Picker, StyleSheet, ImageBackground } from 'react-native';
import { observer, inject } from 'mobx-react'

import { computed, when } from 'mobx'

class LoginScreen extends Component {
    
    @computed get test () {
        return 'test'
    }
    
    render () {
        
        return (
            <Text>
                {this.test}
            </Text>
        );
    }
}

export default observer ( LoginScreen );

`

> 

  | handleException | @ | D:\Sites\work\eton4y…ptionsManager.js:65
-- | -- | -- | --
  | showErrorDialog | @ | D:\Sites\work\eton4y…nderer-dev.js:11170
  | logCapturedError | @ | D:\Sites\work\eton4y…nderer-dev.js:11180
  | captureError | @ | D:\Sites\work\eton4y…nderer-dev.js:12116
  | renderRoot | @ | D:\Sites\work\eton4y…nderer-dev.js:11950
  | performWorkOnRoot | @ | D:\Sites\work\eton4y…nderer-dev.js:12742
  | performWork | @ | D:\Sites\work\eton4y…nderer-dev.js:12660
  | performSyncWork | @ | D:\Sites\work\eton4y…nderer-dev.js:12622
  | requestWork | @ | D:\Sites\work\eton4y…nderer-dev.js:12535
  | scheduleWorkImpl | @ | D:\Sites\work\eton4y…nderer-dev.js:12374
  | scheduleWork | @ | D:\Sites\work\eton4y…nderer-dev.js:12321
  | scheduleRootUpdate | @ | D:\Sites\work\eton4y…nderer-dev.js:13025
  | updateContainerAtExpirationTime | @ | D:\Sites\work\eton4y…nderer-dev.js:13059
  | updateContainer | @ | D:\Sites\work\eton4y…nderer-dev.js:13077
  | render | @ | D:\Sites\work\eton4y…nderer-dev.js:13796
  | renderApplication | @ | D:\Sites\work\eton4y…erApplication.js:58
  | run | @ | D:\Sites\work\eton4y…\AppRegistry.js:103
  | runApplication | @ | D:\Sites\work\eton4y…\AppRegistry.js:196
  | __callFunction | @ | D:\Sites\work\eton4y…MessageQueue.js:353
  | (anonymous) | @ | D:\Sites\work\eton4y…MessageQueue.js:118
  | __guardSafe | @ | D:\Sites\work\eton4y…MessageQueue.js:316
  | callFunctionReturnFlushedQueue | @ | D:\Sites\work\eton4y…MessageQueue.js:117
  | (anonymous) | @ | debuggerWorker.js:72

**Comment by mweststrate** [comment]
Can you create a sandbox or repo from that?

Op wo 14 mrt. 2018 17:56 schreef Eugene Alitz <notifications@github.com>:

**Comment by psycura** [comment]
And this issue is happen only in React Native.

In regular React app everything work just fine

**Comment by seantimm** [comment]
We're seeing the same problem in our React Native project.

**Comment by seantimm** [comment]
Nope... same error.

**Comment by AntonPuko** [comment]
Same here. Fails only with `@computed` decorator version. `decorate(observer(Component), { test: computed})` - works as expected.

**Comment by mweststrate** [comment]
Could it relate to hot reloading? (Dunno if that can be disabled?). Does @computed({}) get .... work better?

**Comment by AntonPuko** [comment]
I have hot-reloading disabled. Same fail with  `@computed({})`

**Comment by AntonPuko** [comment]
not sure if its related and helps somehow, but if I drop @observer from the component. I have another error: 
![111](https://user-images.githubusercontent.com/8849922/37436246-9cbcebaa-27ef-11e8-9027-77acd1b58371.png)

**Comment by mweststrate** [comment]
Just released a beta patch, can one verify whether this solves the issue? `mobx@4.0.2-fix-rn`

**Comment by psycura** [comment]
Yes, it works!!
Thank you

**Comment by mweststrate** [comment]
Released as 4.1!

**Comment by rzcoder** [comment]
This change breaks compatible with mobx 4.0 & 3.0

```js
import { computed, observable } from "mobx";

class A {
  @observable _id;
  constructor() {
    this._id = "A";
  }
  @computed get id() {
    return "A_id: " + this._id;
  }
}

class B extends A {
  constructor() {
    super();
    this._id = "B";
  }
  get id() {
    return "B_id: " +this._id;
  }
}

let a = new A();
let b = new B();

console.log(a.id); // A_id: A
console.log(b.id); // A_id: B
```

in 3.6.2 & 4.0.0
```
A_id: A
B_id: B
``` 

in 4.1.0
```
A_id: A
A_id: B
```

**Comment by mweststrate** [comment]
Please open new issues for new issues

Op di 20 mrt. 2018 18:41 schreef rzcoder <notifications@github.com>:

**Comment by rzcoder** [comment]
ok, #1443

**Comment by N1ghtly** [comment]
I am experiencing this issue as well.

**Comment by mweststrate** [comment]
Please open new issues for new issues
