### ISSUE TITLE
defaulting to `observable` for omitted fields not working

### ISSUE THREAD

**Issue by will-stone** [mobxjs/mobx#1397]
Thanks for the v4 update, loving the decorate syntax for those of us without decorators 😄 

In your migration guide you state that the observable declaration isn't required but I'm finding it is.

Here's without:
https://codesandbox.io/s/mmo5pzw3qp

And with:
https://codesandbox.io/s/18k9rx1p7j

In the second example, the number changes when the button is clicked because `test` is observable.

**Comment by mweststrate** [comment]
Sorry for the confusion! It is optional indeed for `observable.object` and `extendObservable`, but with `decorate` it is required indeed. Would you be interested in clarifying the migration guide where the confusion was caused?

**Comment by will-stone** [comment]
Ok, sure.

This part:

```js
// Maybe you have classes, but no decorator syntax enabled. Don't worry, with MobX 4 you don't have to fall back to
// `extendObservable` in the constructor! Instead, just declare the fields and use `mobx.decorate` to ehance the prototype:
class Todo {
    title = "test"
    promise = somePromise

    get difficulty() {
        return this.title.length
    }
    get expensive() {
        return somethingExpensive()
    }

    setTitle(t) {
        this.title = t
    }
    setTitle2(t) {
        this.title = t
    }
}
decorate(Todo, {
    //////////// `title` is excluded
    ref: observable.ref,
    expensive: computed({ requiresReaction: true }),
    setTitle: action,
    setTitle2: action.bound
})
```

**Comment by mweststrate** [comment]
right, thanks! will fix

**Comment by will-stone** [comment]
Thanks, thought I was going mad 😁
