### ISSUE TITLE
how to create/convert to/from observables?

### ISSUE THREAD

**Issue by rickmed** [mobxjs/mobx#140]
like from/to bacon.js/rxjs

**Comment by mweststrate** [comment]
Like https://github.com/chicoxyzzy/rx-mobservable :) ?

**Comment by chicoxyzzy** [comment]
yep I still had no time to make some improvements but I think I'll try to revisit rx-mobservable soon. @mweststrate, does mObservable and mobx have any differences in their API?

**Comment by mweststrate** [comment]
Hardly, see: https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md. But `Atom`s can be used now, which might make integration cleaner. See: http://mobxjs.github.io/mobx/refguide/extending.html

**Comment by rickmed** [comment]
@mweststrate yes, thanks, I've already seen it but thought it wouldn't work with mobx as opposed to mobservable.

**Comment by mweststrate** [comment]
@rickmed Ah check, didn't think about the rename :) that probably will break stuff.
@chicoxyzzy do you need help with migrating? Otherwise I can submit a PR

**Comment by chicoxyzzy** [comment]
@mweststrate I'll do it in next few days. Also I want to make work with both 4 and 5 versions of RxJS.

**Comment by mweststrate** [comment]
Solved by https://github.com/chicoxyzzy/rx-mobx
