### ISSUE TITLE
Run `when` effect in an action

### ISSUE THREAD

**Issue by marcfallows** [mobxjs/mobx#1402]
I have an:
* [x] Issue:
  * [x] Provide a **minimal** sample reproduction. 
    * https://codesandbox.io/s/qkyj3pk379
  * [x] Did you check this issue wasn't filed before?
    * As best as I could. "when" is a very difficult thing to search for in the issues.
  * [x] Elaborate on your issue. What behavior did you expect?
    * I would expect `when`'s effect to be run in an action, like `reaction`'s effect.
  * [x] Are you willing to (attempt) a PR yourself?
    * Yes, but want to be sure this is not as intended.

**Comment by mweststrate** [comment]
Agreed. Surprising nobody noticed that before :) Or there was a good reason for the current behavior... But I don't think so.

It should be as simple as wrapping `effect` in the `_when` function in an `action` (see `src/api/when.ts`). It means that the the `untrackedStart` / `end` can also be removed.

**Comment by mweststrate** [comment]
Released as 4.1
