### ISSUE TITLE
`Observable.map()` not respecting numbers when `replace` is used

### ISSUE THREAD

**Issue by brandonhall** [mobxjs/mobx#1403]
@mweststrate asked me to open an issue after discussion on Gitter. Using `mobx@4.0.1` the `observable.map().replace()` method is not respecting numbers as keys. The numbers passed to `replace` are transformed into strings. I believe the issue boils down to [this change](https://github.com/mobxjs/mobx/pull/800/files#diff-0705ac810d08eaea8944e253e58cd5caL101) which removed the casting of every key to a string.

Here's a [screenshot](https://cl.ly/q91S) of the problem. A reproduction is fairly simple:

```javascript
const map = observable.map();

map.replace({
  1: { id: 1, name: 'test' }
  2: { id: 2, name: 'test 2' }
  3: { id: 3, name: 'test 3' }
});

Array.from(map.keys());
["1", "2", "3"]
```

**Comment by mweststrate** [comment]
I think the current behavior is correct, when looping to the an object with Object.keys and alike, every key will be reported as _string_, so there is on way for us to determine that the key was originally a number. The only way to fix that is to use an entries array as replacement: `[[1, { id: 1, name: 'test'}], [2, { id: 2, //... etc`

**Comment by brandonhall** [comment]
Thanks @mweststrate. That makes perfect sense.
