### ISSUE TITLE
Invariant failed: Expected one or two arguments

### ISSUE THREAD

**Issue by giladno** [mobxjs/mobx#1408]
I receive the following error message: `Invariant failed: Expected one or two arguments to observable.object. Did you accidentally try to use observable.object as decorator?`

My code looks like this:

```
window.data = observable.object({
    username: '',
    entries: [],
}, {}, {deep: false});
```

I don't want my `entries` array to become observable as well, so I want to disable the deep feature. When using mobx 4, it was working great using `observable.shallow({...})`, but after upgrading to mobx 5 - it doesn't work anymore. I've tried to remove the second argument (empty decorators), but it was always creating me an observable array (options are being ignored).

**Comment by mweststrate** [comment]
I think you mean Mobx 4. MobX 5 isn't there yet. What you need is probably: 

```
window.data = observable.object({
    username: '',
    entries: [],
}, {
    entries: observable.shallow
}
```

**Comment by giladno** [comment]
@mweststrate Yeah, I meant mobx 4 :)

In that case, maybe the docs should be updated to better explain that:

`observable.shallowObject(values) has been removed, instead use observable.object(values, {}, { deep: false })`

I've got this warning in the console, which is why I used the same syntax.

**Comment by mweststrate** [comment]
It's described here: https://github.com/mobxjs/mobx/wiki/Migrating-from-mobx-3-to-mobx-4#modifiers-are-dead-long-live-decorators

**Comment by giladno** [comment]
@mweststrate either the docs are wrong, or there is a bug:

From the docs:

`observable.map(values, {}, { deep: false })   Note the empty object as second argument, which can contain decorators (see above)` (https://github.com/mobxjs/mobx/wiki/Migrating-from-mobx-3-to-mobx-4#the-observable-factories-have-been-cleaned-up)

My code:
```
window.data = observable.map({
    username: '',
    entries: [],
}, {}, {deep: false});
```

Error in the console: `Uncaught Error: [mobx] Expected one or two arguments to observable.map. Did you accidentally try to use observable.map as decorator?`
