### ISSUE TITLE
React Developer Tools `no display name` problem

### ISSUE THREAD

**Issue by deathmood** [mobxjs/mobx#141]
Got the problem with stateless components. As you suggest [here](http://mobxjs.github.io/mobx/refguide/observer-component.html), I've just wrapped component declaration into `observer(..)` function like this:

```js
export const MyButton = observer( ({ param }) => (  
   <div>......</div>
));
```

but that breaks up `displayName` of this component. So I see smth like this (without `observer(...)` `displayName` is displayed properly):

![image](https://cloud.githubusercontent.com/assets/2758540/13423779/a5bc97a8-dfa5-11e5-977c-5edd1ef839a9.png)

for now, first solution that I see is to `export default`

```js
const MyButton = ({ param }) => (  
   <div>......</div>
);

export default observer(MyButton);
```

But then I'm able to export only one thing from module. Other way is to create two variables like `MyButton` and then `export const MyButtonObserver = observer(MyButton)` --- but that is unpleasant complication(((

Is there any other way to fix this? Should this be reflected in docs?

**Comment by mweststrate** [comment]
@deathmood the name is actually injected by the babel compiler based on the variable name. The assignment pattern is no longer recognized due to the wrapping `observer` call by the transpiler. However, there are a few ways you can work around this.

1, split the statement into two:
```javascript
export let MyButton = ({ param }) => { etc }
MyButton = observer(MyButton);
```

The second one is to give your render function a name (that is basically what the transpiler does for you), e.g.:

```javascript
export MyButton = observer(function MyButton ({ param}) { return <div> .. </div> })
```

Hope that helps! I'll add it to the docs as well.

**Comment by deathmood** [comment]
thanks)

**Comment by SenerDemiral** [comment]
also works?
```
MyButton.displayName = "MyButton"
```

**Comment by mweststrate** [comment]
Correct. Also applying `observer` later works, as the transpiler usually picks the name of the target var as component name when compiling a JSX function component afaik.

**Comment by vensa-albertgao** [comment]
Have a problem with the `displayName` any idea why, thanks?

Question:
https://stackoverflow.com/questions/52979655/when-use-mobx-uncaught-typeerror-cannot-read-property-displayname-of-null

Repo:
https://github.com/Albert-Gao/trymobx

**Comment by mweststrate** [comment]
To summarize: these approaches all work to get compoments named

```javascript
let MyComponent1_ = () => "hello1!"; // N.B. 'MyComponent1_' is what shows up in devtools
export const MyComponent1 = observer(MyComponent1_);

export const MyComponent2 = observer(() => "hello2!");
MyComponent2.displayName = "MyComponent2";

export const MyComponent3 = observer(function MyComponent3() {
  return "hello3!"
})
```

Demo: https://codesandbox.io/s/w038r5q68w
