### ISSUE TITLE
autorun delay on leading edge

### ISSUE THREAD

**Issue by kjarnet** [mobxjs/mobx#1411]
I have a:
3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

The `delay` option of `autoRun` is really useful, but it would be great if it supported "leading edge" execution, similar to [lodash's debounce function](https://lodash.com/docs/4.17.5#debounce).

The specific problem this would solve for me: I have a function that fetches data from the server, which sometimes is called once, in which case I want it to trigger the fetch immediately, and sometimes called multiple times in quick sequence, in which case I _don't_ want it to trigger on each call.

I could certainly try and submit a PR for this if it sounds like a good idea.

**Comment by mattruby** [comment]
I think you're looking for autorunasync.

https://mobx.js.org/refguide/autorun-async.html

**Comment by kjarnet** [comment]
Yes, but this was removed in [v4.0](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#400):

> autorun(fn, options?) now accepts the following options:
> delay: number debounce the autorun with the given amount of milliseconds. This replaces the MobX 3 api autorunAsync

**Comment by mattruby** [comment]
Ok, didn't know that 😀

How about using the debounce number option?

**Comment by kjarnet** [comment]
You mean `delay`? That gives the behavior I described above, which is _almost_ what I want, except in the case where the user triggers the function only once - then they have to wait a number of milliseconds before the fetch is triggered. I'd like it to trigger _once immediately_, then after a delay.

**Comment by mweststrate** [comment]
@kjarnet PR is welcome! Probably can be incorporated in the scheduler creation utility you will find in `src/api/autorun.ts`

**Comment by quanganhtran** [comment]
At the moment `autorun` actually behaves like a `throttle` function (it means it fires at most once every `delay` ms). A `debounce` behavior (on a trailing edge) should be that it waits `delay` ms after the last change to fire the view (it means any call in quick succession reset this waiting time)
Since there are 3 more behaviors (leading throttle, trailing debounce, leading debounce) how do you want it to be expressed through the autorun option object? Maybe just providing an explicit scheduler from userland would be enough?
Or MobX could provide a `scheduler` namespace, just like how `comparer` currently is

**Comment by mweststrate** [comment]
from top of my head autorun and reaction already support custom schedulers

Op di 17 apr. 2018 om 20:48 schreef quanganhtran <notifications@github.com>:

**Comment by quanganhtran** [comment]
@kjarnet Throttling on a leading edge ("cooldown" effect) can be done like this with custom scheduler (I think):
```js
let idle = true;
autorun(effect, { scheduler: f => {
  if (idle) {
    idle = false;
    f();
    setTimeout(() => idle = true, 500);
  }
}});
```

**Comment by ItamarShDev** [comment]
`autorun`  supports delay argument.
@mweststrate unless I am missing something, this issue should be closed

**Comment by fi3ework** [comment]
Guess this issue could be closed. The scenario can be implement by using custom scheduler. I write a small demo on codeSandBox: https://codesandbox.io/s/n7vjmj0j3m. And just adding option params to `autorun` still can't meet all the conditions. So maybe leave it to userland will be more sensible. Indeed I think `delay` is not needed cause it could be easily implement by custom scheduler in a few lines.😀

**Comment by unel** [comment]
@fi3ework 
> https://codesandbox.io/s/n7vjmj0j3m. 

it isn't same with debounce-like behaviour. I added clearTimeout to fix this nuance (https://codesandbox.io/s/minimal-mobx-react-project-ins4i), but debounce behaviour still broken... because scheduler does not called if previous callback not called.

**Comment by FredyC** [comment]
Yea, fi3ework said long time ago, let's close it here. Given it has a userland solution, I don't think somebody is interested in implementing it anymore.
