### ISSUE TITLE
Method toJS wrong output in Mobx 4

### ISSUE THREAD

**Issue by tiagowippel** [mobxjs/mobx#1413]
Hi,

suposing we have this code:

```
@observable teste = {
      test1: 1,
      test2: true
};

...

console.log(toJS(this.test));
```

when trying to output pure js object (using toJS) we are getting this:

![image](https://user-images.githubusercontent.com/12776397/37468288-55942f84-2841-11e8-981f-568879125077.png)

`__mobxDidRunLazyInitializers: true` ?

https://codesandbox.io/s/z39xk7x92l

**Comment by mweststrate** [comment]
Please upgrade to 4.0.2, should have been fixed in that version

**Comment by tiagowippel** [comment]
Upgraded and worked, sorry to bother you, and congrats for this great lib.
