### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by giladno** [mobxjs/mobx#1415]
After upgrading to mobx 4, I start receiving this error (on a react-native app). I've narrowed it down to the `@computed` decorator.

Here is a very basic class which reproduces this error:

```
export default class extends React.Component {
    @observable data = [];

    @computed get items(){
        return [];
        return this.data;
    }

    render(){
        let {items} = this;
        return (
            <View></View>
        );
    }
}
```

 Even when I don't reference any observable value (this function returns an empty array immediately) - this exception is thrown. When not using the `@computed` decorator - it works fine.

Any idea how to start and debug this issue? Thanks!

**Comment by mweststrate** [comment]
Upgrade to 4.1 :)

Op do 15 mrt. 2018 om 18:19 schreef Gilad Novik <notifications@github.com>:

**Comment by mweststrate** [comment]
See #1396 from the top of my head

Op do 15 mrt. 2018 om 18:27 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by giladno** [comment]
@mweststrate cheers! upgrading to 4.1 indeed solved the problem :)
