### ISSUE TITLE
Feature request: custom setters for `@observable` properties

### ISSUE THREAD

**Issue by girvo** [mobxjs/mobx#142]
Hey there,

As I mentioned in the Discord chat, one feature I'd love to see (if it fits in with the rest of the architecture) is custom setters for `@observable` properties.

The main use-case for this is to be able to validate data being passed into the property, as well as emulating the "one-way data flow" of Flux somewhat. Basically, in the same way Actions in Flux can verify the data passed to them are correct, it'd be great to have a way (similar to `@computed`) to setup a function that the `@observable` setter calls.

Cheers,
Josh

**Comment by mweststrate** [comment]
Just was thinking about adding this feature, then I realized that we are using this pattern for months already, relying on the fact that MobX will observe through levels of indirection. So you can basically do:

```javascript
class MyModel {
    @observable /*private if using typescript*/ __myValue = 3;
   
    get myValue() {
       return this.__myValue;
    }
    set myValue(newValue) {
        // do validation
        this.__myValue = newValue;
    }
}
```

Would that suffice? In ES5 you can achieve this with a combination of `extendObservable` and `Object.defineProperty` in the constructor.

[ @capaj ]

**Comment by capaj** [comment]
@mweststrate that certainly works, but it would require me to create another abstraction layer on top of mobx objects. Currently utilising `preupdate` events, I can let user work directly with mobx objects. If I wanted to introduce those setters, I would have to hide whole observable from the user. I don't want to do that.

**Comment by GuillaumeLeclerc** [comment]
It would be very good to have it without having to wrap all the elements

**Comment by mweststrate** [comment]
@GuillaumeLeclerc note that `intercept` can now be used as alternative setter
