### ISSUE TITLE
Docs: add a page on configuring?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mobxjs/mobx#1420]
I have an:
3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

I can't find any documentation on the `configure` call. I only know of it because `useStrict` is no longer available and was mentioned in the changelog.

```typescript
import { configure } from "mobx";

configure({
	enforceActions: true,
});
```

I can submit a doc page for this. It should probably be under section 6. Utility Functions?

**Comment by mweststrate** [comment]
@JoshuaKGoldberg A PR would be great! Somehow missed it when updating the docs for MobX 4 :)

**Comment by JoshuaKGoldberg** [comment]
Ah, found it! https://mobx.js.org/refguide/api.html#-configure

**Comment by JoshuaKGoldberg** [comment]
Ehh, looks like it's out of date.

On the page:

* enforceActions
* isolateGlobalState
* disableErrorBoundaries
* computedRequiresReaction

In `configure.d.ts`:

```typescript
export declare function configure(options: {
    enforceActions?: boolean;
    computedRequiresReaction?: boolean;
    isolateGlobalState?: boolean;
    disableErrorBoundaries?: boolean;
    arrayBuffer?: number;
    reactionScheduler?: (f: () => void) => void;
}): void;
```

I'll expand the sections with usage examples & more explanations.

**Comment by mweststrate** [comment]
Closing since docs page is merged. Thanks for the effort! Will publish the new docs soon
