### ISSUE TITLE
Export equality check function and document comparer

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx#1421]
Reading through the docs it's totally unclear what comparer is and how it works, and where to find the code.

Also should export the comparer functions, not sure if they are already but browsing through docs/code didn't seem like it does.

Usage for me is doing a simple setState function for my own use. I'd like to be able to compare equality with Mobx objects.

**Comment by urugator** [comment]
Comparare is a function that takes 2 args and returns whether args are equal or not.
It can be passed as an option to `computed` or `reaction`. Both of these compute some value, if the computed value is the same as previously computed value accordingly to comparator, they won't notify observers(reactions).

[`mobx.comparer`](https://github.com/mobxjs/mobx/blob/master/src/mobx.ts#L52)[`{.identity./default/.structural}`](https://github.com/mobxjs/mobx/blob/master/src/utils/comparer.ts#L20)

**Comment by mweststrate** [comment]
Note that they are mentioned here: https://mobx.js.org/refguide/api.html#computed-values

**Comment by natew** [comment]
Think the docs are just really hard to navigate. I did search a few places
manually for "comparer" and then did a global search and it shows a ton of
sections, but I had no idea "API Overview" was significant superset of the
sub-sections, I thought it was just a title for them.

Not to critique the hard work put in here at all, as I have little time to
help out. But not super impressed with the doc software. Perhaps more
sections would help discoverability. And more fleshed out sections with
cross-links for things (comparer is mentioned in places but not linked to
where its defined).

Thanks for the help finding that!

**Comment by natew** [comment]
Another thing is there is no explanation of the three comparers (requires reading source):

![image](https://user-images.githubusercontent.com/12100/37544228-7d3410d2-2921-11e8-94e5-b1b5390f4882.png)

**Comment by mweststrate** [comment]
@natew yeah we are currently reorganizing the docs, but it will take a bit :)

**Comment by natew** [comment]
Thank you, really appreciate mobx, we've done a ton with it! Hope to open source a bunch of cool stuff in the near future.
