### ISSUE TITLE
Upgrade to the latest version and you cannot find the "useStrict" function.

### ISSUE THREAD

**Issue by jamieYou** [mobxjs/mobx#1422]
```
import { useStrict } from 'mobx'
useStrict(true)
```
but useStrict is not a function.

**Comment by leader22** [comment]
See https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#breaking-changes

> useStrict(boolean) was dropped, use configure({ enforceActions: boolean }) instead

**Comment by mweststrate** [comment]
Closing since question is answered
