### ISSUE TITLE
mobx observable controlled form onchange this.forceUpdate() Maximum update depth exceeded @4.0.1 

### ISSUE THREAD

**Issue by Kielan** [mobxjs/mobx#1425]
Welcome to MobX. Please provide as much relevant information as possible!

I have a: bug/issue

mobx observable controlled form onchange this.forceUpdate() Maximum update depth exceeded,using no this.forceUpdate causes inputs to lock and never update onchange. I have reproduced how I'm doing it in this minimal sample, a bit different from my local app but still doesn't work. 
  https://codesandbox.io/s/v3v0my2370

local package.json
    "mobx": "@4.1.0",
    "mobx-utils": "4.0.0-beta.2",
    "mobx-react": "5.0.0-beta.2",

we may need an updated docs on how to build mobx forms.

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction
