### ISSUE TITLE
Updating @box to MobX 4

### ISSUE THREAD

**Issue by sonaye** [mobxjs/mobx#1427]
I am trying to migrate [mobx-box](https://github.com/sonaye/mobx-box) to the new API. Based on what I understood from the release notes, we can -and sometimes should?- explicitly declare decorators as a third parameter to `extendObservable`. The error message also suggested to use `decorate()`.

```javascript
const box = (obj, prop, descriptor) => {
  const decorated = descriptor.initializer;

  const privateName = `_${prop}`;

  const ref = extendObservable(
    obj,
    {
      [privateName]: decorated ? descriptor.initializer() : descriptor,
      get [prop]() {
        return obj[privateName];
      },
      set [prop](value) {
        obj[privateName] = value;
      }
    },
    { [privateName]: observable } // added in mobx 4
  );

  decorate(obj, { [privateName]: observable }); // also tried to use decorate

  if (decorated) return ref;
};

export default box;

```

However this ends up throwing an error:

```
Error: [mobx] Property 'foo' of '[object Object]' was accessed through the prototype chain. Use 'decorate' instead to declare the prop or access it statically through it's owner
```

Kindly advise o this, thanks.

**Comment by urugator** [comment]
I think your current impl is flawed since `Enable usage without decorators` ... you can't use `extendObservable` to "decorate" `prototype`  ... you should use your original impl for decorator usage and `extendObservable` only for non decorator usage.

**Comment by sonaye** [comment]
I think you are right, I just [pushed](https://github.com/sonaye/mobx-box/blob/master/src/index.js) the changes and it is working know. However, I had no issues with mobx 3, any explanation for that?

**Comment by urugator** [comment]
> However, I had no issues with mobx 3, any explanation for that?

Have you tested it on something else than singletons? I think the prop would be actually shared among instances...

**Comment by sonaye** [comment]
I haven't actually, never had a use case where I needed to.

Your suggestion explains why another library that I worked on `mobx-apollo` didn't break with MobX 4, I removed decorators there because I found out that having
```javascript
class a {
  @decorator b = 123;

  constructor() {
    decorator(this, 'c', 456);
  }
}
```
Together can lead to some major inconsistency issues with GraphQL specifically, we should to stick to one. But never faced them with `@box`.

**Comment by mweststrate** [comment]
In MobX 3 this worked "accidentally" well in some cases, but it had inconsistencies all over the place. In MobX 4 it has been made consistent; `extendObservable` will enhance the 'this' (and throw in most cases if you accidentally used it in a prototype chain). 

`decorate` will always consider where it was defined on, and where it is called upon, and try to push the properties down to the actual instance if applicable. So `decorate` can be used safely on classes, or objects that are used as prototype, `extendObservable` not. 

However, not that if you are trying to decorate inside a constructor (like in the last code snippet), you are already decorating the instance (the correct `this`), so I recommend to use `extendObservable` there.

**Comment by mweststrate** [comment]
Looks pretty neat & minimal at first glance :)

Op wo 28 mrt. 2018 om 20:23 schreef sonaye <notifications@github.com>:
