### ISSUE TITLE
(when trying to decorate actions in mobx 4): [mobx] 'extras' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went.

### ISSUE THREAD

**Issue by tsiq-swyx** [mobxjs/mobx#1428]
hi team!

I have an issue.

Here is my error messages:

```
Error
[mobx] 'extras' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went
▶ 11 stack frames were collapsed.
TodoListClass.onSubmit
/src/todolist.js:9:29
   6 | 
   7 | export class TodoListClass {
   8 |   items = ["get milk"]; // observable array
>  9 |   onSubmit = e => this.items.push(e); // action
     |                             ^
  10 | }
  11 | decorate(TodoListClass, { items: observable, onSubmit: action });
  12 | 
View compiled
▶ 2 stack frames were collapsed.
onSubmit
/src/todolist.js:34:17
  31 | <form
  32 |   onSubmit={e => {
  33 |     e.preventDefault();
> 34 |     list.onSubmit(this.input.value);
     |         ^
  35 |     this.input.value = "";
  36 |   }}
  37 | >
View compiled

```

![image](https://user-images.githubusercontent.com/35976578/37550320-9ad01bd2-2961-11e8-8891-fea85380b2b0.png)

Here is the codesandbox:  https://codesandbox.io/s/20lv7n3kvn just try to submit text in any box to see the error

what i'm trying to do here is to `decorate` my `onSubmit` with an `action` or `action.bound`. i expected 
it to work but got this opaque error. checking the changelog showed nothing.

## State the versions of MobX and relevant libraries. Which browser / node / ... version?

latest chrome, and the deps are in the codesandbox:

![image](https://user-images.githubusercontent.com/35976578/37550340-e5cc5eac-2961-11e8-9056-3079be0424fd.png)

please let me know what I should do. thank you!

**Comment by tsiq-swyx** [comment]
update.. i think this is due to mobx dev tools being incompatible with mobx 4.

**Comment by diaraujo13** [comment]
I'm facing a similiar issue. Any helps from team?


rror: bundling failed: Error: [mobx] 'default' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went (While processing preset: "C:\\Users\\Izaias\\Desktop\\Aplicativos\\GenericRedux\\node_modules\\mobx\\lib\\mobx.js")
    at invariant (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\mobx\lib\mobx.js:2632:15)
    at fail$1 (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\mobx\lib\mobx.js:2627:5)
    at Object.get (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\mobx\lib\mobx.js:4032:17)
    at C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:300:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\Izaias\Desktop\Aplicativos\GenericRedux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by sw-yx** [comment]
oh fyi the devtools has been updated to fix the incompat issue with mobx 4.

it doesnt look like you have the same issue here. please file another issue

**Comment by mweststrate** [comment]
@diaraujo13 your problem is that you are probably that you are importing in the wrong way: `import mobx from "mobx"`. Instead use `import { observable } from "mobx"`. Or if it really needs: `import * as mobx from "mobx"`. But I really recommend explicit imports, because otherwise your code cannot be tree-shaken.

**Comment by roots-ai** [comment]
@sw-yx didn't updating to "mobx-react-devtools": "^5.0.0" didn't work for us

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
