### ISSUE TITLE
[mobx] Deprecated: Invoking observable() on scalar values is deprecated. Use extendObservable or @observable instead.

### ISSUE THREAD

**Issue by rickmed** [mobxjs/mobx#143]
How would you implement the example in docs (below)?

```javascript
var numbers = observable([1,2,3]);
var sum = observable(() => numbers.reduce((a, b) => a + b, 0));

var disposer = autorun(() => console.log(sum()));
// prints '6'
numbers.push(4);
// prints '10'

disposer();
numbers.push(5);
// won't print anything, nor is `sum` re-evaluated
```

**Comment by mweststrate** [comment]
@rickmed:

It would become:
```javascript
var data = observable({
   numbers: [1,2,3],
   sum: () => numbers.reduce((a, b) => a + b, 0)
});

var disposer = autorun(() => console.log(data.sum));
```

I definitely should update the docs, but I'm not 100% sure yet whether to really push for this deprecation. In practice observables are always used in some app context. But for testing, experimenting and doing more abstract stuff as making libraries these stand alone observables are quite convenient. On the other hand, I want to keep the api small :)

**Comment by Kosta-Github** [comment]
IMHO, the `sum` example given by @rickmed above makes sense to support; e.g., I am in the need for something similar with my `react` components using some derived values without explicitly adding them to an `observable` object first...

**Comment by mweststrate** [comment]
@Kosta-Github, note that if using ES6/7 you can just introduce observable instance fields in react components

 ```javascript
@observer MyComponent extends React.Component {
   @observable numbers = [];
   @computed get sum() { return this.numbers.reduce((a, b) => a + b, 0) }
   render() {
       return <div>{this.sum}</div>
   }
}
```

**Comment by Kosta-Github** [comment]
I am using pure render functions without internal state; the state is provided by a mapper; but the mapper is used for several components.

And I want to avoid the usage of decorators, because they haven't been standardized yet and are not supported by `babel 6` (only via a legacy plugin)...

**Comment by mweststrate** [comment]
That is a very fair point :) I'm gonna sleep a night over it, but I think I'm gonna undeprecate this one.

**Comment by rickmed** [comment]
@mweststrate Building up @Kosta-Github comments, I understand why there are specific react bindings and a lot of examples using it, but there is a lot more value using mobx using whatever pattern you would like. My specific need is separating state (observable objects) from actions, which would be similar to the example above (looking for an elmish pattern, not using reactjs at all).

**Comment by mweststrate** [comment]
@rickmed check. Definitely it is strongly recommended to keep state as much as possible outside of components. Don't get me wrong on that :). 

From my humble opinion these are, in order, the best methods to create observable objects:

```javascript
class MyModel {
   @observable myProp = 3;
}
// (or use extendObservable in ES5)
```
This is very explicit and easy to read for everyone.

```javascript
const myModel1 = observable({
   myProp: 3
});
// (or use extendObservable for existing objects)
```
That one is very nice if you like working with plain objects instead of prototypes

```javascript
const myModel1 = {
   myProp: observable(3);
}
```

The latter has a danger; you might accidentally do `myModel1.myProp = 4` instead of `myModel.myProp.set(4)`, so that is why I want to discourage using `observable` for _scalars_ a bit, because it is fine to use them stand alone (in combination with `const`!), but don't put them in objects as you might then accidentally throw them away with a change that would never be observed, as the `myProp` field itself is not observable in the last example.

**Comment by rickmed** [comment]
@mweststrate agree with all -I don't like classes but that's a personal taste. 
From your example I guess I could group all actions (functions) in an observable object observing the state in an another object. That would work in my case.
I also agree that depreciation might be too strong. In that example, why would someone do that instead making the whole object observable?

**Comment by mikekidder** [comment]
@Kosta-Github you can use observer with Stateless Functional Components, no decorators.

**Comment by mweststrate** [comment]
@rickmed thought about RxJs like disposers a few times. The downside of it is that you cannot freely pass the disposer easily around as just a function (for example push it on a list of to-be-executed actions, etc).

**Comment by rickmed** [comment]
@mweststrate got it. Haven't been in that situation yet, but makes sense.
Awesome contribution with mobx :)

**Comment by Kosta-Github** [comment]
@mikekidder I know, I do that a lot; actually all my react components are pure render functions, and many of them are rendering derived data.

@mweststrate but I just noticed that I am using expr() instead of observable(), which you pointed me to, but getting the same deprecation warning now...

**Comment by mweststrate** [comment]
@Kosta-Github oh, that is a incorrect indeed. `expr` isn't deprecated, but uses `observable` internally. `observable(scalar)` isn't going anywhere in the near feature, just want to make sure people don't run in the previously explained assignment mistake. Maybe the best course of action here is to undeprecate it, and mention it somewhere as advanced pattern in the docs.

**Comment by mikekidder** [comment]
@Kosta-Github yeah sorry, re-read your message on that, and not wanting to use @observable initially.

**Comment by mweststrate** [comment]
Undeprecated `observable(scalar)` and released it as version `2.0.1`

**Comment by rickmed** [comment]
@mweststrate awesome! I'll try those asap.

**Comment by rickmed** [comment]
@mweststrate using the example at the beginning I get:
[mobx] Deprecated: Use `computed(expr)` instead of `observable(expr)`

and

 return console.log(sum());
                     ^

TypeError: sum is not a function

**Comment by mweststrate** [comment]
Which example is that? That is the old api :) Should be sum.get() instead.

Op za 5 mrt. 2016 om 19:00 schreef rickmed <notifications@github.com>:

**Comment by rickmed** [comment]
@mweststrate It works! thanks.
Although, I still get this: 


[mobx] Deprecated: Use `computed(expr)` instead of `observable(expr)`

**Comment by mweststrate** [comment]
Fixed the docs. It is correct that you indeed should use `computed(expr)` instead of `observable(expr)`, as this makes the different concepts in MobX more clear.

**Comment by rickmed** [comment]
awesome. thanks! Mobx really needs more docs/examples/etc exposure for more people start using it!
