### ISSUE TITLE
Value of process.env.NODE_ENV for Mobx4 : "production" vs JSON.stringify('production')

### ISSUE THREAD

**Issue by Fred2MTL** [mobxjs/mobx#1431]
Hi all
I try to upgrade my existing applications based on Mobx 3 to 4. They are build with rollup / babel 6 as following and according to [React - Rollup](https://reactjs.org/docs/optimizing-performance.html#rollup).

```javascript
rollupBabel({exclude: 'node_modules/**'}),
rollupNodeResolve(),
rollupReplace({'process.env.NODE_ENV': JSON.stringify('production')}),
rollupCommonJS(...),
rollupUglify()
```

When upgrading to 4.x (including upgrading mobx-react to 5.x), the build generates the following error :
```javascript
SyntaxError: Unexpected token (3987:69) in /.../node_modules/mobx/lib/mobx.module.js
```

The build runs correctly when changing `JSON.stringify('production')}`to `'production'`. But, the application doesn't run : `ReferenceError: production is not defined`.

I think the value of process.env.NODE_ENV must respect the rules set by React, as done for Mobx 3.

**Comment by d4rky-pl** [comment]
The result of `JSON.stringify('production')` is `"production"` not `production` (note the quotes).

**Comment by mweststrate** [comment]
Closing since the question is answered
