### ISSUE TITLE
Mobx doesn't use min.js version in production build.

### ISSUE THREAD

**Issue by genzgd** [mobxjs/mobx#1433]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

2. [x] Issue:
  * [x] Provide a **minimal** sample reproduction. 
See repo at: [mobx-min github repo](https://github.com/genzgd/mobx-min)
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. 
As explained in the README for the above repo, when building with webpack 4.1.1 using "production" mode, I would expect webpack to use the included lib/mobx.min.js library when doing the basic:
`webpack --display-modules --mode production`
  * [x] State the versions of MobX and relevant libraries.
Mobx 4.1.0, Webpack 4.1.1

**Comment by caesarsol** [comment]
Hi @genzgd,
usually when you use webpack you are the one responsible for minification.
I have to check, but I think the mobx.min.js is included for use in the browser.
Is that possible?

**Comment by genzgd** [comment]
That's certainly possible.  I was assuming it would work the same as react based on this:

> To get a production build, use the .min.js version from the CDN, or substitute process.env.NODE_ENV with "production" while bundling. This is exactly the same mechanism as React uses, so if you have a proper React build setup already, this does not require any further effort!

From Michel's post here:  https://medium.com/@mweststrate/mobx-4-better-simpler-faster-smaller-c1fbc08008da.

If the lib/mobx.module.js properly minifies (which it seems like it does), then that's fine, it probably just should be documented a little differently.

**Comment by caesarsol** [comment]
You got a point!

Do you have time to investigate the issue? Are you able to look in detail into the build pipeline?

**Comment by genzgd** [comment]
Alas I don't think I have the Javascript/build expertise to comfortably do that.  It appears that React accomplishes it by having an index.js that exports one library or the other depending on process.env.NODE_ENV, but mobx doesn't appear to use a single default export like index.js, but relies instead on package.json information that handles other types of modules as well.  I don't really know what's intended here or even if just minifying lib/mobx.module.js is really good enough.

**Comment by genzgd** [comment]
As I said above, "if the lib/mobx.module.js minifies correctly (which it seems like it does), then that's fine, it probably should be documented a little differently".  It is not, in fact, "exactly the same mechanism as React", which uses two different library files, one pre-minified.  I did not assume something didn't work, I was confused by your own description and was attempting to find out what was intended.
