### ISSUE TITLE
computed(...).get() inside a computed can lead to redundant evaluation

### ISSUE THREAD

**Issue by kring** [mobxjs/mobx#1439]
I have a case where MobX is re-evaluating a computed observable (seemingly) unnecessarily. Here's a toy example that shows the problem:

```js
import { computed, autorun, observable, trace } from 'mobx';

class Test {
    @observable value = 'initial value';

    @computed get foo() {
        trace();
        console.log('evaluating foo');
        return computed(() => {
            trace();
            console.log('evaluating nested computed');
            return this.value;
        }).get();
    }
}

const t = new Test();

autorun(() => {
    console.log(t.foo);
});

setTimeout(() => {
    t.value = 'new value';
}, 1000);
```

(Also at https://codesandbox.io/s/l40rlyw3qm)

The dependency graph looks like this (arrows mean "depends on"):

`foo -> nested computed -> value`

Now, when I change `value`, the nested computed's getter gets called _twice_, instead of just once as expected. The output looks like this:

```
[mobx.trace] 'Test@1.foo' tracing enabled
evaluating foo
[mobx.trace] 'ComputedValue@6' tracing enabled
evaluating nested computed
initial value
[mobx.trace] 'ComputedValue@6' is invalidated due to a change in: 'Test@1.value'
[mobx.trace] 'Test@1.foo' is invalidated due to a change in: 'ComputedValue@6'
evaluating nested computed
evaluating foo
[mobx.trace] 'ComputedValue@8' tracing enabled
evaluating nested computed
new value
```

So what is happening is that MobX is (correctly) determining that the nested computed depends on `value`, and that `foo` depends on the nested computed, but then it chooses (incorrectly, in my opinion) to evaluate the nested computed first. When it evaluates `foo` second, foo's getter creates a brand new nested computed causing the nested getter function to be invoked a second time.

The same thing happens when using `expr` from `mobx-utils`, of course, since it uses this same pattern.

I'm willing to attempt a fix and PR for this but will need to be pointed in the right direction.

**Comment by urugator** [comment]
> nested getter function to be invoked a second time.

It's not ... as you said it's a new computed ... there is no way for mobx to find out whether the newly created computed somehow relates to the old one. It would have to perform some reconciliaction process like react does, but then you need to somehow identify (id/key+type+position in hierarchy) the nested computeds ... maybe `createTransformer` does something similar not sure...
In this simple example you can return the computed directly, so it's accessed like `t.foo.get()`

**Comment by kring** [comment]
Thanks @urugator. You're right, of course, that MobX is evaluating two different computeds with the same evaluation function, rather than evaluating the same computed twice. I'm coming around to the idea that MobX is doing the right thing here, but the story is a bit more complicated.

Consider this slight modification:
https://codesandbox.io/s/614119jlvz

The only thing I've changed is that I've added another observable named `irrelevant` and "used" it inside `foo`, so now `foo` depends on both `irrelevant` and the nested computed. Then, in the timeout, I modify both `irrelevant` and `value` inside the same transaction. Now, the nested computed's evaluation function is only called once. Specifically, MobX has evaluated `foo` _before_ the nested computed. That causes the _old_ version of the nested computed to no longer be referenced, so it doesn't get re-evaluated. Hurray!

So originally I thought MobX should do the same sort of thing in my original example: it should evaluate `foo` first. But that overlooks the fact that `foo` only needs to be evaluated at all if the nested computed's value changes. And MobX, of course, has no way of knowing whether the nested computed's value changed without evaluating it first. Since this is pretty much exactly the use-case for `expr` (protecting a more expensive outer computed from frequent re-evaluation just because a frequently-changing-but-usually-irrelevant property changes), it's important that MobX work the way it does and not the way I originally thought it should.

And if MobX can't evaluate `foo` first in this scenario, then the only way to prevent the double evaluation would be, as you suggested, to do some sort of reconciliation process. "Creating" the nested computed inside `foo` would have to somehow re-use the old one rather than actually creating a new one.

And that seems like some serious overkill, so I'm closing this issue.

I'll look into modifying the docs for `expr` to make a note of this double evaluation, though. AFAICT, anytime the the result of an `expr` changes, its function will be evaluated a second time when the `expr` gets recreated by the outer computed or reaction.

**Comment by urugator** [comment]
> anytime the the result of an expr changes, its function will be evaluated a second time when the expr gets recreated by the outer computed or reaction.

If it actually gets recreated... note that the expr can be in conditional block:
```javascript
computed(() => {
  if (store.something) {
     return expr(() => 5)
  }
  return 3
})
```
Or the expression logic can change depending on surrounding scope ...

Maybe you should just emphasize `temporal` and perhaps offer an explanation what it means...

**Comment by kring** [comment]
> If it actually gets recreated... note that the expr can be in conditional block:

Assuming that `store.something` in your example is an observable, and it hasn't changed, the expression will be recreated just as it was before (and the "double" evaluation happens).

If the value of `store.something` _has_ changed, then MobX will evaluate this outer computed first anyway (based on my tests, I don't know if it's 100% reliable) and the expression will only be evaluated at most once.

If `store.something` isn't observable, then this computed isn't a pure function of observables and all bets are off. :)

I've tried to capture most of this on my proposed change to the `expr` docs. Take a look at #1442 and see if you think I hit the mark.

**Comment by urugator** [comment]
Let me just offer an alternative explanation, feel free to (not) take any inspiration for your PR: 
 
Temporary means that computed value exists only until the surrounding computed/reaction is re-executed.
As a consequence `expr` can't take the advantage of computed value cache.
Once `expr` returns new value, the surrouding computed/reaction is notified, re-executed, original `expr` is **lost** together with it's cached value and possibly new `expr` is created.
While `expr` can prevent expensive recomputation, it may cause more smaller recomputations, due to an `expr` being recreated. The use of *permanent* `computed` is therefore preferred.
