### ISSUE TITLE
Question: which best practice for new extendObservable

### ISSUE THREAD

**Issue by rzcoder** [mobxjs/mobx#1441]
I have a scenario when I get an models with unknown scheme from network and I can't make observable scheme beforehand.

E.g. 
```js
model.fetch({filter: 1}); // returns {field1: 1, field2: 2}
model.fetch({filter: 2}); // returns {field1: 4, field5: 5}
```

Previously i just did `extendObservable` for all received fields on model to keep model up-to-date, now `extendObservable` doesn't update existing fields. 
So, which is best practice now to keep observable model up-to-date in new behavior?

**Comment by mweststrate** [comment]
The old behavior can be achieved with `mobx.set`

Op di 20 mrt. 2018 om 15:45 schreef rzcoder <notifications@github.com>:

**Comment by rzcoder** [comment]
Thanks, but `'set()' can only be used on observable objects, arrays and maps`, model just an class instance, not instance of `observable.object`

**Comment by mweststrate** [comment]
In general the idea is to have either a class with predefined fields, or a dynamic collections (ideally Maps, but objects can be used as well). I recommend not to combine the two. After all, dynamically changing class instances can accidentally hide examples that live in your class if the names collide etc. So I recommend two separate those concepts clearly.

That being set, you can use `isObservableProp(this, "fieldName")` to check if a property exists and is observable or not. If not, you could `extendObservable` it.
