### ISSUE TITLE
issue: @computed implementation from 4.1.0 breaks compatible with mobx 4.0.0 & 3.x

### ISSUE THREAD

**Issue by rzcoder** [mobxjs/mobx#1443]
Also it very confusing now
```js
import { computed, observable } from "mobx";

class A {
  @observable _id;
  constructor() {
    this._id = "A";
  }
  @computed get id() {
    return "A_id: " + this._id;
  }
}

class B extends A {
  constructor() {
    super();
    this._id = "B";
  }
  get id() {
    return "B_id: " +this._id;
  }
}

let a = new A();
let b = new B();

console.log(a.id); 
console.log(b.id);
```
in 3.6.2 & 4.0.0
```
A_id: A
B_id: B
```
in 4.1.0
```
A_id: A
A_id: B
```

**Comment by mweststrate** [comment]
Redefining `@computed` (or `@observable`) fields was and is not supported, although it kinda worked, there are too many subtle semantic differences between the different decorator implementations (Babel and TS) to give any guarantees on this pattern. Which will remain the case until the new stage 3 decorator proposal is standardized

Instead, use the following pattern to avoid this situation:

```javascript
class A {
  @computed get id() {
    return this.computeId()
  }

  /* protected */ computeId() {
    return "A_id: " + this._id;
  }
}

class B extends A {
   /* protected */ computeId() {
    return "B_id: " + this._id;
  }
}
```

It achieves semantically the same, but works properly through inheritance. Additional benefit: you can also call the super implementation of the the computed value :).
