### ISSUE TITLE
Mobx Actions with RxJS Observable subscription 

### ISSUE THREAD

**Issue by amrfarid140** [mobxjs/mobx#1444]
I have a:

1. [ *] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

**Question**

I have an Api service which uses RxJS observable instead of Promises. It is used in a mobx action for a React component.
Similar to the documentation, I have used a combination of @action.bound and runInAction() but neither of them are triggering the render function.

Here is a some sample code:

**Expected Output**

Async Callbacks Count = 0

Observed Item = Test String

**Received Output**

Async Callbacks Count = 1

Observed Item = Test String
```
import * as React from 'react';
import { observable, action, runInAction } from 'mobx';
import { observer } from "mobx-react";
import { Observable } from "rxjs";

let exampleRxObservable: Observable<string> = Observable.create( rxObserver => {
    setTimeout(() => {
        rxObserver.next("Test String");        
    },         1000);
});

export class TestModel {
    @observable observedItem = "";
    @observable asyncCallbacksCount = 0;

    @action
    fetchDataFromRxObservable() {
        this.asyncCallbacksCount += 1;
        exampleRxObservable.subscribe( 
            result => {

            runInAction(() => {
                this.observedItem = result;
            });

        },  error => {
            runInAction(() => {
                this.observedItem = "Error";
            });
        },  () => {
            // OnCompelete is called after next or error
            runInAction( () => {
                this.asyncCallbacksCount -= 1 ;
            });
        }
     );
    }
}

@observer class TestComponent extends React.Component<{model: TestModel}, {}> {

    componentDidMount() {
        this.props.model.fetchDataFromRxObservable();
    }
    render() {
        return (
            <div>
                <p> Async Callbacks Count = {this.props.model.asyncCallbacksCount} </p>
                <p> Observed Item = {this.props.model.observedItem} </p>
            </div>
        );
    }
}
export default TestComponent;
```

Notice that both runInAction calls are executed but only one of them updates the state of the component.  Am I missing something ?

**Comment by mweststrate** [comment]
Please include your state definitions and rendering. If that is a lot of
code; people will chime in quicker if you make a small sandbox
reproduction.

Op wo 21 mrt. 2018 20:45 schreef Amr Yousef <notifications@github.com>:

**Comment by amrfarid140** [comment]
Good point. I will put a sample code for the issue ASAP.

**Comment by amrfarid140** [comment]
The error was on my end. Specifically where this component was used.
