### ISSUE TITLE
`observable.object` to be more consistent with others

### ISSUE THREAD

**Issue by guiguan** [mobxjs/mobx#1447]
Can we move the second decorator param of `observable.object` function to its last param? so `observable.object(values, options, decorator)`. Then all `observable.*` APIs can share the same function signature for first two params: `values` and `options`

**Comment by mweststrate** [comment]
It is this way, because otherwise it would be inconsistent with `extendObservable(target, values, decorators, options)`, where decorators first is the more logical option. 

Also even if it would be better, it would be a pretty annoying change to swap them around now, as options and decorators cannot with certainty be distinguished :)

**Comment by guiguan** [comment]
I thought the new `set` is preferred over `extendObservable` in mobx 4. Am I wrong? If `observable.object` is the new API, it should be more consistent with its family instead of legacy `extendObservable`. It really took me ages to figure out the problem when I was migrating from mobx 3 because of this inconsistency with other new APIs :(

**Comment by guiguan** [comment]
Or really, the decorator should be part of options if I were designing this :P

**Comment by mweststrate** [comment]
> . It really took me ages to figure out the problem when I was migrating from mobx 3 because of this inconsistency with other new APIs :( 

that could have worked out exactly the same if it was the other way around :) `decorate` also takes decorators as second arguments, so it is consistent with the new api as well. Beyond that I think these kind of reflections, now and then we will miss a line of of documentation and stare at something unnecessarily long. C'est la view
