### ISSUE TITLE
Provide an actionScheduler similar to reactionScheduler?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mobxjs/mobx#1453]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

Suppose you have an `@action` that throws an error:

```javascript
class MyStore {
    @action do() {
        throw new Error("Not implemented.");
    }
}
```

`executeAction` now just directly runs `fn.apply(scope.args);` in a `try`/`finally`. That means there's no way to wrap the function in a `catch`-like construct as a consumer of the library. If there's an error, the only way to catch it is with `window.onerror` / `window.addEventListener('error'`. 

Problem: IE and older versions of Edge don't provide stack traces in certain cross-domain situations ([link](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10868717/)/[link](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/817828/)).

So, in addition to the general benefits of being able to play with reactions, I need this for my own sanity debugging apps on IE. Would love to send a PR if approved!

**Comment by mweststrate** [comment]
I don't think i understand the question, what kind of difference does an scheduler make here? If you want to wrap try catch you can just wrap it in another function that does the try / catch?

Something like `do = action(myCatcher(function do() { throw "stuff" } ))`. Optionally you can create your own decorator that does this for you

**Comment by JoshuaKGoldberg** [comment]
> do = action(myCatcher(function do() { throw "stuff" } )).

I'm trying to add the try/catch logic to _all_ actions as a replacement for the broken `window.onerror`. 

> create your own decorator

That would be the next-best option IMO. It's confusing to newcomers to a project to see some imports coming from `mobx` and some from `@team/our-internal-stuff` / `../../our-internal-stuff`.

**Comment by mweststrate** [comment]
I don't think fixing browser error handling is part of the scope of MobX :) .

**Comment by JoshuaKGoldberg** [comment]
Sorry to keep bugging you @mweststrate 😅 but I think I have a legitimate use case for this that doesn't involve browsers from 2013.

In my (relatively large & complex) web app, it's intended that if an error in the app code occurs, a little in-app popup comes up saying there was an error and that you need to refresh. We can hook up a `reactionScheduler` to handle all exceptions from errors, but what if an `@action` has an error?

Your suggestion of writing our own `@action` decorator that wraps MobX's native one works, but is confusing for new developers _("why aren't we using MobX?")_. It's also less clean hooking up a listener for errors - in our own decorator, we'd need to keep some global observable/listener for error state, which adds a second global observable/listener on top of MobX. Adding an `actionScheduler` in our own stores' initialization seems cleaner.

Does that persuade you?

**Comment by mweststrate** [comment]
If an action has an error you can just use the global error handling system provided by the browser / node in javascript itself. The only reason why reactions have a separate error mechanism is because it cannot let exceptions escape the normal way without potentially causing inconsistencies in the internal state. Actions don't suffer from this, hence there is no need to provide what the browser already provides natively.

**Comment by JoshuaKGoldberg** [comment]
Ok. I don't like it, but I'll deal with it 😇 thanks for the open dialog!

I put a basic implementation of my interpretation of how to deal with this outside of MobX here: https://www.npmjs.com/package/mobx-safe
