### ISSUE TITLE
Map.delete() function only works with string-type keys?

### ISSUE THREAD

**Issue by dargue3** [mobxjs/mobx#1455]
I have a:

[x] Question:

I've recently updated to mobx `v4` that includes changes made to `Map`. I've noticed with this new update that in `Map.delete(key)` function, the parameter `key` has to be a string, regardless of what type the key was instantiated with. This is also the case with `Map.get(key)`. Is this a ✨feature ✨of the new Maps? How come?

For context, if necessary, I'm referring to mobx-state-tree's implementation of Maps specifically.

e.g:
```javascript
const ProductList = t
  .model('Model', {
    map: t.map(Product, {}),
  })
  .actions(self => ({
    add(product) {
      self.map.put({ ...product })
    },
    delete(id) {
      self.map.delete(id);
    },
  }))

ProductList.add({ id: 123 })
ProductList.delete(123) // does nothing
ProductList.delete('123') // works as intended
```

**Comment by mweststrate** [comment]
Best ask MST related questions in the MST repo :). But short answer, MobX
maps support generic keys, but MST maps not, as MST always requires indices
which are serializable *and* suitable to be used as paths.

Op di 27 mrt. 2018 om 04:15 schreef Dan Argue <notifications@github.com>:

**Comment by r3wt** [comment]
@mweststrate i think you closed this in error. i found this issue because i am using numeric keys and calling `get()` returns undefined after i upgraded to mobx 4

**Comment by r3wt** [comment]
```
console.log(id);
const item = this.props.store.favorites.get(id);
console.log(item);
```
output:
```
1
undefined
```

note: the `favorites` Map is serialized to/from localstorage using `mobx-persist`

**Comment by r3wt** [comment]
god, mobx is a pile of shit. what the literal fuck. everything is broken after migrating. 

`set`,`get`,`delete`, et al don't work with numeric keys

**Comment by dargue3** [comment]
Wherever you do `Map.get(id)`, do ```Map.get(`${id}`)```. Kinda sucks but I guess that's the price you have to pay for updating a major patch.

Btw, in case you didn't stumble across this yet, `Map.values()`, `Map.keys()`, `Map.entries()` now return iterators, so you have to do `[...Map.values()]` or `Array.from(Map.values())` to get that code fixed up to the way it was working before mobx v4
