### ISSUE TITLE
onBecomeObserved API documentation is lacking/wrong

### ISSUE THREAD

**Issue by dualscyther** [mobxjs/mobx#1456]
I have a:

1. [x] Question: Feel free to just state your question.

From <https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#onbecomeobserved-and-onbecomeunobserved>

> ### `onBecomeObserved` and `onBecomeUnobserved`
> Usage: `onBecomeObserved(observable, property?, listener: () => void): (() => void)` and
> `onBecomeUnobserved(observable, property?, listener: () => void): (() => void)`
> 
> These functions are hooks into the observability system of MobX and get notified when observables _start_ / _stop_ becoming observed. It can be used to execute some lazy operations or perform network fetches.
> 
> The return value is a _diposer-function_ that will detach the _listener_.
> 
> ```javascript
> 
> export class City {
>     @observable location
>     @observable temperature
>     interval
> 
>     constructor(location) {
>         this.location = location
>         // only start data fetching if temperature is actually used!
>         onBecomeObserved(this, 'temperature', this.resume)
>         onBecomeUnobserved(this, 'temperature', this.suspend)
>     }
> 
>     resume = () => {
>         log(`Resuming ${this.location}`)
>         this.interval = setInterval(() => this.fetchTemperature(), 5000)
>     }
> 
>     suspend = () => {
>         log(`Suspending ${this.location}`)
>         this.temperature = undefined
>         clearInterval(this.interval)
>     }
> 
>     @flow fetchTemperature = function*() {
>         // dat afetching logic
>     }
> }
> ```

I'm just wondering what the purpose of the first two arguments are? Is this just the best way of registering these hooks because the values need to be dereferenced or something? If so, why is `property` optional?

Also if I'm not mistaken, the onBecomeUnobserved line should be changed to `onBecomeUnobserved(this, 'temperature', () => this.suspend())` since `suspend` references `this`. Likewise with the onBecomeObserved.

**Comment by mweststrate** [comment]
@dualscyther 1) correct, it is to obtain the observable _box_,. But if you happen to already have that box in hands, the property is not needed. Also you don't need to specify the prop of an array, because arrays are always observed as a whole.

2) No that is not needed, because these methods are already bound at declaration time (note the arrow syntax)
