### ISSUE TITLE
Mobx not recovering from errors between tests

### ISSUE THREAD

**Issue by luisherranz** [mobxjs/mobx#1457]
I have a:
- [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

----

I'm trying to figure out how to use `onReactionError` to test error on autoruns.

I have a very convenient autorun to throw errors like this:
```js
autorun(() => {
  if (column.hasExtracted('horizontal') && column.rawItems.length > 1)
    throw new Error("Don't add extracted lists with other items in the same column.")
});
```

And I'm trying to test it using `onReactionError` and jest:
```js
test('Throws if horizontal extracted is added in a column with more items', () => {
  const mockCallback = jest.fn();
  onReactionError(mockCallback);
  // [ ... code to create the environment in which it should throw ]
  expect(mockCallback).toBeCalled();
});
```

This test passes and `mockCallback` is called. But after that, I'm still getting the error in the jest screen:
![screen shot 2018-03-27 at 12 54 21](https://user-images.githubusercontent.com/3305402/37963275-13139b32-31be-11e8-9666-8348bf73ba3e.png)

Why does it throw if `onReactionError` should capture the error? What am I doing wrong?

**Comment by mweststrate** [comment]
Eh you are skipping the test it seems? You might want to combine it with: https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#disableerrorboundaries-boolean. From top of my head your mock should be called, but the warning will still be printed (the `onReactionError` is mostly for error trackers and such), not a generic error catcher

**Comment by luisherranz** [comment]
> Eh you are skipping the test it seems?

Ups, copy-paste mistake. My bad! 

> You might want to combine it with: https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#disableerrorboundaries-boolean. From top of my head your mock should be called, but the warning will still be printed (the onReactionError is mostly for error trackers and such), not a generic error catcher

I'll investigate that. Thanks @mweststrate!

**Comment by luisherranz** [comment]
*BTW, I'm actually using MST and that autorun is inside an `afterCreate` but I think this is Mobx related.* 

With `configure({ disableErrorBoundaries: true })` I can create this test:

```js
test('Throws if horizontal extracted is added in a column with more items', () => {
  expect(() => {
    mstModel.create({ columns: [{ normalItem, extractedItem }] }); // expected to throw
  }).toThrow()
});
```
And it works! It looks like it's throwing synchronously now.

But when the throw is a reaction of a separate action, it doesn't work:
```js
test('Throws if horizontal extracted is added in a column with more items', () => {
  const model = mstModel.create({ columns: [{ normalItem }] }); // everything fine
  expect(() => {
    model.addItem({ extractedItem }); // expected to throw
  }).toThrow()
});
```
With `configure({ disableErrorBoundaries: true })` it doesn't work if I use `onReactionError` either.
```js
test('Throws if horizontal extracted is added in a column with more items', () => {
  const mockCallback = jest.fn();
  onReactionError(mockCallback);
  const model = mstModel.create({ columns: [{ normalItem }] });  // everything fine
  model.addItem({ extractedItem }); // expected to throw
  expect(mockCallback).toBeCalled();
});
```
And no error is shown on the Jest interface.

**Comment by luisherranz** [comment]
Ok, so let me know if understood it correctly, `onReactionError` doesn't catch the error, it's just a callback. So I still see the real errors on the screen.

And `configure({ disableErrorBoundaries: true })` should make mobx not catch any errors. For that reason, they don't go through the `onReactionError`.

Then what's happening makes kind of sense. 

So, what's the best approach to test something like this?
```js
autorun(() => {
  if (column.hasExtracted('horizontal') && column.rawItems.length > 1)
    throw new Error("Don't add extracted lists with other items in the same column.")
});
```

**Comment by mweststrate** [comment]
Disable error boundaries and expect / toThrow should do the trick

Op di 27 mrt. 2018 om 17:16 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
Ok, thanks. I think I found the root of the problem. After the first throw, mobx doesn't recover.

I've tried to create a simple scenario:

```js
const mobx = require('mobx');
const { types } = require('mobx-state-tree');
const test = require('tape');

mobx.configure({ disableErrorBoundaries: true });

const Model = types
  .model('Model', {
    val: 1,
  })
  .actions(self => ({
    setVal: val => {
      self.val = val;
    },
    afterCreate: () => {
      mobx.autorun(() => {
        if (self.val === 2) throw new Error('OMG! val is 2!');
      });
    },
  }));

// TEST 1: Works fine
test('Do not throw', t => {
  t.plan(1);
  t.doesNotThrow(() => {
    Model.create({ val: 1 });
  });
});

// TEST 2: Works fine
test('Throw syncronously', t => {
  t.plan(1);
  t.throws(() => {
    Model.create({ val: 2 });
  });
});

// TEST 3: Doesn't work. Only works if TEST 2 doesn't exist.
test('Throw asynchronously', t => {
  t.plan(1);
  const model = Model.create({ val: 1 });
  t.throws(() => {
    model.setVal(2);
  });
});
```

It looks like after `TEST 2` mobx is not recovering from errors: `WARNING: Debug feature only. MobX will NOT recover from errors if this is on.` Therefore `TEST 3` fails.

How can I make mobx recover from errors in this situation?

**Comment by mweststrate** [comment]
There is a resetGlobalState api for that 😊

Op di 27 mrt. 2018 18:03 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
Awesome. Working now with:

```js
const beforeEach = () => {
  mobx._resetGlobalState();
  mobx.configure({ disableErrorBoundaries: true });
};
```

Thanks @mweststrate !!!

**Comment by luisherranz** [comment]
Ups, any way to disable warnings? 😓

![screen shot 2018-03-27 at 18 34 40](https://user-images.githubusercontent.com/3305402/37981355-cd659f56-31ed-11e8-88e2-37bf54eab223.png)

**Comment by mweststrate** [comment]
Oh we can probably warn for that only once. Would you be interested in
making a pr on the docs describing this?

Op di 27 mrt. 2018 18:37 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
Actually, there's no need to call `disableErrorBoundaries` on every test. This works just fine:

```js
mobx.configure({ disableErrorBoundaries: true });

const beforeEach = () => {
  mobx._resetGlobalState();
};
```

and only displays one warning.

But I was already looking at the code:
https://github.com/mobxjs/mobx/blob/1090a2c80c68f459b572fe35cc4a1729cd4f897b/src/api/configure.ts#L25-L26
so if you think a PR would be nice just let me know.

**Comment by mweststrate** [comment]
Yeah would be nice I think😊

Op di 27 mrt. 2018 18:47 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
There you go https://github.com/mobxjs/mobx/pull/1462!
