### ISSUE TITLE
'default' is no longer part of the public MobX api.

### ISSUE THREAD

**Issue by rbx** [mobxjs/mobx#1458]
I have an:
2. [x] Issue:

I am adding `mobx`, `mobx-react` and `babel-preset-mobx` to an existing project that runs react, webpack and react-hot-loader.
After running `yarn add mobx mobx-react` and `yarn add --dev mobx-preset-mobx` I am getting following error when building:
```
ERROR in ./src/index.jsx
Module build failed: Error: [mobx] 'default' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went (While processing preset: "/path/to/project/node_modules/mobx/lib/mobx.js")
    at invariant (/path/to/project/node_modules/mobx/lib/mobx.js:2632:15)
    at fail$1 (/path/to/project/node_modules/mobx/lib/mobx.js:2627:5)
    at Object.get (/path/to/project/node_modules/mobx/lib/mobx.js:4032:17)
    at /path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/path/to/project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/path/to/project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/path/to/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/path/to/project/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/path/to/project/node_modules/babel-loader/lib/index.js:173:20)
 @ multi ./src/index.jsx
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c webpack --mode production
``` 

At this point I did not import mobx in any source files.

Adding `import * as mobx from 'mobx';` in index.jsx doesn't help, neither does `import { action, observable } from 'mobx';` in the actual component that I want to start adding mobx to.

Here is my config: package.json:
```json
...
  "main": "index.jsx",
  "scripts": {
    "build": "webpack --mode production",
    "dev": "webpack-dev-server --mode development --hot --content-base ./dist"
  },
  "dependencies": {
    "filesaver.js": "^1.3.4",
    "github-api": "^3.0.0",
    "mobx": "^4.1.0",
    "mobx-react": "^5.0.0",
    "prop-types": "^15.6.1",
    "react": "~16.2.0",
    "react-bootstrap": "~0.32.1",
    "react-dom": "~16.2.0",
    "react-localstorage": "~1.0.0",
    "react-mixin": "^4.0.0",
    "vkbeautify": "^0.99.3"
  },
  "devDependencies": {
    "babel-core": "6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "7.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.6.1",
    "babel-preset-mobx": "^1.0.2",
    "babel-preset-react": "6.24.1",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.7.0",
    "react-hot-loader": "^4.0.0",
    "webpack": "4.3.0",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "3.1.1"
  }
...
```
.babelrc:
```
{
    "presets": [ "env", "mobx", "react" ],
    "plugins": ["transform-class-properties", "react-hot-loader/babel"]
}
```
webpack.config.js:
```js
module.exports = {
  entry: [
      './src/index.jsx'
  ],
  resolve: {
      extensions: ['.js', '.jsx']
  },
  module: {
    rules: [
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  }
};

```

Previous to mobx addition the project builds fine. Error occurs with both `build` and `dev` scripts.

steps to reproduce:
```bash
git clone https://github.com/rbx/DDS-topology-editor
cd DDS-topology-editor/
yarn add mobx mobx-react
yarn add --dev babel-preset-mobx
yarn install
vim .babelrc #add 'mobx' to presets array
yarn run dev
```
Any help appreciated!

**Comment by rbx** [comment]
It works if I remove `mobx-preset-mobx` and just use `babel-plugin-transform-decorators-legacy` instead. Still, using the preset would be a bit cleaner if it worked.

**Comment by mildrenben** [comment]
I'm also experiencing this and even when I remove all instances where mobx is imported it still throws this error

**Comment by rbx** [comment]
@mildrenben yes, just `transform-decorators-legacy` has to come first.
I have now:
```js
{
    "presets": ["env", "react"],
    "plugins": ["transform-decorators-legacy", "transform-class-properties", "react-hot-loader/babel"]
}
```

**Comment by rbx** [comment]
@mildrenben yes, just `transform-decorators-legacy` has to come first.
Now I have in .babelrc:
```js
{
    "presets": ["env", "react"],
    "plugins": ["transform-decorators-legacy", "transform-class-properties", "react-hot-loader/babel"]
}

```

**Comment by mweststrate** [comment]
I think there are several different issues now being discussed in this thread at the same time, but `4.1.1` will fix an issue that tools that reflection on the `default` export will only cause a warning to be printed, instead of an exception being thrown.

**Comment by slavafomin** [comment]
Hello!

I'm getting the similar error message when trying to build React application after installing mobx preset for decorators support:

`Module build failed: ReferenceError: [BABEL] ./src/index.js: Unknown option: ./node_modules/mobx/lib/mobx.js.IDerivationState. Check out http://babeljs.io/docs/usage/options/ for more information about options.`.

**Comment by mweststrate** [comment]
It means that your import statements are not correct. Please share import
statement and open a fresh issue if this one is closed

Op do 31 mei 2018 om 22:50 schreef Slava Fomin II <notifications@github.com

**Comment by slavafomin** [comment]
@mweststrate I hadn't imported any decorators at that moment.

**Comment by mweststrate** [comment]
"open a fresh issue"

Op vr 1 jun. 2018 om 09:30 schreef Slava Fomin II <notifications@github.com

**Comment by charmer1989** [comment]
I have the same problem:
Module build failed: ReferenceError: [BABEL] ./src/index.js: Unknown option: ./node_modules/mobx/lib/mobx.js.IDerivationState. Check out http://babeljs.io/docs/usage/options/ for more information about options.

**Comment by mweststrate** [comment]
@charmer1989 please open a fresh issue, this one has nothing to do with the original issue as far as I can see. Also provide reproduction repository as this is probably a setup problem

**Comment by darthmooguy** [comment]
@charmer1989 @mweststrate  This seems to be an issue with the preset, see https://github.com/zwhitchcox/babel-preset-mobx/pull/3
