### ISSUE TITLE
Making a rich domain model observable

### ISSUE THREAD

**Issue by vladimir-rovensky** [mobxjs/mobx#146]
I was playing with mobx recently and I'm struggling with the following problem: 

I'd like to have a rich domain model, complete with inheritance, polymorphism and all that, but unaware of mobx or any other special library. I'd like to have just vanilla TypeScript classes in my model. Then, in the store, I figured I would make the model instaces observable with @observable, only introducing mobx at the store level. This didn't work for me though - please look at this [sample](http://codepen.io/anon/pen/dMYwMa?editors=1010).

Here I have a super basic domain model consisting of a few typescript classes. In my store, I try to make them observable:
`@observable animals: Animal[] = [];`

Then I have a couple of components listening to this array. Thing is, if I change a property of one of the Animals, nothing happens, the change is not picked up unless I mark said property as @observable in the model, which is what I'd like to avoid if possible.

The examples suggest that making an array property @observable would make its whole object graph observable, but that does not seem to be the case. Is there some way to acomplish this?

**Comment by mweststrate** [comment]
`@observable` will only automatically recurse into other objects when using it with plain objects or arrays. For class instances this would be to obtrusive / unpredictable. The underlying idea is that classes themselves should be responsible for making their members observable. 

If you want to force observability on members of existing class instances, you can use `extendObservable` for that:

```javascript
extendObservable(myObject, {
   attribute1: myObject.attribute1,
   attribute2: myObject.attribute2
   /// etc
});
```

If you no for sure that all enumerable members of a class can be made observable, just `extendObservable(myObject1, myObject1)` would work as well.

**Comment by vladimir-rovensky** [comment]
Ok, seems simple enough, just one follow up question - you say I should know for sure that all members of the class can be made observable, what things cannot be made observable? I thought that `observable` works on pretty much anything.

**Comment by mweststrate** [comment]
Yep, but it it is for example dangerous to assume that any argumentless function is a computed value, or that there are other members that don't need to be observable (for example an `id` value which will never change).

**Comment by vladimir-rovensky** [comment]
Got it, thank you.

**Comment by Veikedo** [comment]
@mweststrate hello! You sad
> just extendObservable(myObject1, myObject1) would work as well.

>Yep, but it it is for example dangerous to assume that any argumentless function is a computed value

I understand that it's risky, but is there a way to use `extendObservable(myObject1, myObject1)` with get/set properties?
I want to make my `get` props computed alongside making the setters act like an action.

We have a lot of big forms (with computed fields) and we found it's a bit boring to mark all of props with `@observable` attribute. 
It would be nice to just put `@observable` decorator for a whole class.

we prefer using strict mode
