### ISSUE TITLE
How to raise reaction?

### ISSUE THREAD

**Issue by d8corp** [mobxjs/mobx#1464]
```javascript
const x = observable(0)

reaction(() => {
  console.log('start', x.get())
}, () => {})

// I can't control after this place

autorun(() => {
  console.log('autorun', x.get())
})

x.set(1)
```
I need the reaction to be runned first after the setting. or maybe to use some else (not reaction).

**Comment by mweststrate** [comment]
use the fireImmediately option

Op wo 28 mrt. 2018 om 13:18 schreef d8corp <notifications@github.com>:

**Comment by d8corp** [comment]
How? https://jsfiddle.net/qgjps8p0/

**Comment by mweststrate** [comment]
Ah, I only get your question now. You didn't separate the observation and
the effect, instead use:

reaction(() => x.get(), value => {
  console.log('it should be first every time', value)
})


Op wo 28 mrt. 2018 om 14:56 schreef d8corp <notifications@github.com>:

**Comment by d8corp** [comment]
all the same, action is first https://jsfiddle.net/pu9hth05/

**Comment by mweststrate** [comment]
Sorry then I totally don't get what the question is :). Please specify _observed_ and _expected_ behavior, and what you are trying to achieve.

**Comment by mweststrate** [comment]
Closed for inactivity
