### ISSUE TITLE
Render function isn't reactive to changes.

### ISSUE THREAD

**Issue by zheeeng** [mobxjs/mobx#1466]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [x] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

versions:
mobx@3.4.1
mobx-react@4.3.5

description:
Render function isn't reactive to changes.

minimal reproduction:
https://jsfiddle.net/Zheeeng/1um4v6Lw/1/

sample codes:

```js
const {observable, action, autorun } = mobx;
const {observer} = mobxReact;

class Renderer1 extends React.Component {
	render () {
  	return this.props.children()
  }
}

class Renderer2 extends React.Component {
	render () {
  	return this.props.children
  }
}

@observer
class App extends React.Component {
	@observable text = 'hello'

  @action handleClick = () => {
    this.text = this.text + '!'
  }

  renderTest = () => (
    <div>
      <p>{this.text}</p>
      <button onClick={this.handleClick}>change text</button>
    </div>
  )

  render() {
    return (
      <div>
        <Renderer1>{this.renderTest}</Renderer1>
        {/* <Renderer2>{this.renderTest()}</Renderer2> */}
      </div>
    )
  }
}
```

Renderer2 works fine. (Renderer2 + Renderer1) works fine. Renderer1 alone doesn't work.

The real usage is passing render function to React-Router Route Comopnet:

```js
 <Route render={this.renderSometing}>
```

**Comment by zheeeng** [comment]
Found a hack solution:
```js
render () {
    const test = this.renderTest()
    return (
        <div>
                <Renderer1>{() => test}</Renderer1>
        </div>
    )
}
```
It works but bring two problem.
1. Can't prevent useless rendering in render conditions(apart the first trigger for deps collection).
2. Can't pass in injected props to render function. e.g.

```
render () {
    return (
         <Route render={props => this.renderSometing(props)}> // Maye we cloud render this Route before return the JSX element? 
    )
}
```

**Comment by mweststrate** [comment]
This is working as expected, as described in the documentation, `@observer` only applies to the current component that is rendering the value. However, your observable data is rendered by a different component, namely `renderTest` (don't be fooled by the fact that it is a field of your App component; react will treat it as stand alone component). 

So something like  `renderTest = observer(() => ( /* same *))` should fix it. 

But beyond that, this creates a really messy and confusing component setup and I would recommend to just lift the component outside `App`, or use `renderTest` as function you call (and not as component you pass to another component.
