### ISSUE TITLE
mobx and proxies: observable won't trigger update

### ISSUE THREAD

**Issue by misantronic** [mobxjs/mobx#1468]
Recently I've been using [Baqend](baqend.com) as BaaS. 
The api outputs Proxies as result.
I now have the problem that my application won't re-render whenever a change on this Proxy was made although it's observable.

Sample (react):

```js
class Store {
  @observable public item = { customProp: 'test' };

  constructor() {
    this.fetch();
  }

  fetch() {
    this.item = await myFancyBaqendRequest(); // returns a Proxy with the property `customProp`
  }
}

@observer  // from mobx-react
class Component {
  store: Store;

  render() {
    return <div>{this.store.item.customProp}</div>
  }

  // triggered from somewhere
  onChangeItem() {
    this.item.customProp = 'new value';
    // note: this will NOT trigger a re-render
  }
}
```

Any ideas on how to properly handle Proxies?

**Comment by mweststrate** [comment]
That is a question that is not generally answerable. There is nothing special about Proxies, it is all about the behavior of the thing they proxy. If the proxy proxies a plain object, and still supports defining properties etc etc, all should work fine. If the proxy proxies a class, then the class rules apply; being that the class itself is responsible for making it's field observable, etc. 

In other words, proxies are undetectable, and whether it is proxied or not should make no difference at all on how MobX works with these objects, unless the proxy is trapping things it probably shouldn't trap or doesn't trap correctly.

**Comment by mweststrate** [comment]
Closing as question seems answered

**Comment by misantronic** [comment]
@mweststrate might this issue be solved with mobx 5 or won't it change anything with this topic?

**Comment by mweststrate** [comment]
I don't think it changes anything. But then again, I have no clue what your Proxy is doing, so hard to make any general statements. You original example doesn't make really sense, since you are modigying `this.item.customProp` instead of `this.item.store.customProp`. Like the issue template prescribes; include something easily runnable like a code sandbox if you want accurate answers :)
