### ISSUE TITLE
Does onBecomeObserved dispose of itself if the observable is garbage collected?

### ISSUE THREAD

**Issue by dualscyther** [mobxjs/mobx#1469]
I have a:

1. [x] Question: Feel free to just state your question.

Hi, I was wondering whether registering an `onBecomeObserved` listener to an observable will:
- Prevent the observable from becoming garbage collected
  - If so, will the listener also be garbage collected or will I need to do it manually?

My use case is that I have a RootStore which will instantiate new instances of SubStore while losing references to old SubStores simply by doing for example `this.subStore = new SubStore()`. I was wondering whether I need to manually run the disposers?

**Comment by mweststrate** [comment]
Not explicitly disposing should work out, but do make sure you don't keep a reference to the disposer in that case, otherwise that would be exactly the thing keeping it in mem :)

**Comment by dualscyther** [comment]
Not that I am doing this, but I could keep a reference to the disposer within the SubStore instance right (since I would lose the entire SubStore reference as a whole anyway)?
And yeah agreed, but this way I don't need to explicitly run cleanup code in the RootStore instance every time I lose a reference. This means my RootStore code is less coupled to whatever different types of sub stores I have, which means my sub stores are essentially 'pluggable'. That makes sense to me, but maybe I'm using/organising stores wrong?
