### ISSUE TITLE
When I install mobx, something is wrong

### ISSUE THREAD

**Issue by dayatang** [mobxjs/mobx#1474]
When I run 'npm install mobx --save', something is wrong:

> unixlib@0.1.3 preinstall /private/tmp/node_modules/unixlib
> node-waf configure && node-waf build

sh: node-waf: command not found
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! unixlib@0.1.3 preinstall: `node-waf configure && node-waf build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the unixlib@0.1.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2018-04-01T20_35_58_187Z-debug.log

I need help, thanks.

**Comment by mweststrate** [comment]
Unixlib is not a dependency of mobx, so please investigate that package
first. Error seems unrelated to mobx and probably will occur on anything
you try to install

Op zo 1 apr. 2018 22:38 schreef gdyangyu <notifications@github.com>:

**Comment by DanielRuf** [comment]
Try upgrading npm, `node-waf` is called `node-gyp` for some years now.

**Comment by fancyboynet** [comment]
I also get the error when I run `yarn add mbox`
```
yarn add v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/6] ⠄ core-js
[2/6] ⠄ core-js
[3/6] ⠄ ejs
[4/6] ⠄ husky
error D:\work\xxx\node_modules\unixlib: Command failed.
Exit code: 1
Command: node-waf configure && node-waf build
Arguments:
Directory: D:\work\xxx\node_modules\unixlib

```
My env is:
`node`: 12.7.0
`yarn`: 1.17.3
`os`: windows10

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
