### ISSUE TITLE
Nested Namespaces - TypeError caused by @action keyword

### ISSUE THREAD

**Issue by pmonty** [mobxjs/mobx#1475]
**MobX version**
3.5.1

**Error**
`Uncaught TypeError: Cannot read property 'API' of undefined` 
I am using TypeScript, FuseBox, React and MobX

**Code**
```ts
export namespace Project
{
    export namespace Website
    {
        export namespace API
        {
            export namespace Endpoints
            {
                export namespace V1
                {
                   //..
```

```ts
import { Project } from './Client.ts';

// ....

@action
public moveAddress(newAddress: Project.Website.API.Endpoints.V1.Account.Actions.MoveAddress.MoveAddressRequest_Address, serviceCode: string) {
    
```

**More info**

It appears the @action keyword is causing issues. If I remove @action it works fine. If I leave @action but make the newAddress parameter `any` then that works too.

It is strange that it doesn't complain about Website but does so about API.

**Edit - Example**
Here is a [nice example](https://stackblitz.com/edit/typescript-mgn8xa) @kingdaro provided me :)
Looks like it isn't working with nested namespaces.

**Comment by kingdaro** [comment]
Here's a reproduction of the issue, with some comments: https://stackblitz.com/edit/typescript-mgn8xa

Definitely couldn't say exactly what's causing it though. Would have to look at compiled output for more details. Bug in typescript?

**Comment by pmonty** [comment]
The code for that particular action in my bundle is:
```ts
    AccountStore.prototype.moveAddress = function (newAddress, serviceCode) {
        var moveAddressRequest = {
            newAddress: newAddress,
            serviceCode: serviceCode,
        };
        return this.apiClient.V1.Account.Actions.MoveAddress(tslib_1.__assign({}, moveAddressRequest), services_1.TokenManager.getTokenHeader());
    };
```

**Comment by mweststrate** [comment]
as discussed through gitter; in the demo the issue is `emitDecoratorData` being enabled, and a circular dependency (or something alike). This isn't a bug related to mobx but to typescript / the project setup. It would probably happen with *any* decorator you try to apply
