### ISSUE TITLE
Array includes/indexOf and objects

### ISSUE THREAD

**Issue by elado** [mobxjs/mobx#1476]
Are `array.includes`/`indexOf` not supposed to work with objects?

```js
class Store {
  @observable list = [];
}
const store = new Store();
const obj = { p: 1 };
store.list.push(obj);
console.log(store.list.includes(obj)); // => false
```

I understand why it happens (`push` creates a new observable object based on `obj` and adding it to the array instead), but is it fixable?

**Comment by mweststrate** [comment]
convert `obj` to observable eagerly: `const obj = observable({ p: 1 })`, so
that the ref will literlally be stored in the list. (Or, if obj doesn't
have to be an observable, use `@observable.shallow list = []`

Op di 3 apr. 2018 om 09:05 schreef Elad Ossadon <notifications@github.com>:

**Comment by elado** [comment]
Thanks. Curious - are there plans to fix that with mobx 5/proxies?

**Comment by mweststrate** [comment]
No, it isn't related to proxy / non-proxy problems. Converting `obj` to an observable simply produces  a new object, and hence you cannot compare the pointers (unless if you did the conversion yourself first)

**Comment by elado** [comment]
yeah - unless array.includes/indexOf is also taken over by the proxy, and proxies of converted observable objects expose `getOriginal()` or so.
