### ISSUE TITLE
Errors thrown in autoruns are caught by mobx, errors thrown in reactions are not caught

### ISSUE THREAD

**Issue by philipstanislaus** [mobxjs/mobx#1480]
# Expected behavior

Errors thrown from reactions and autoruns are both caught, onReactionError handler is called for both. 

# Actual behavior

Errors thrown from reactions are not caught, onReactionError  handler is not called.

# Reproduction example

https://codesandbox.io/s/xr2nzz41zq

## Steps to reproduce

1. Click on "Throw error in autorun", go to console => error is caught, onReactionError handler logs to console.
2. Click on "Throw error in reaction" => error is not caught, application crashes, onReactionError handler is not called.

# Versions

mobx 4.1.0, mobx-react 5.0.0, react 16.0.0, react-dom 16.0.0

# Template

2. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

**Comment by urugator** [comment]
Note it catches errors thrown in "tracking" part (first arg), but not in "effect" part (second arg). Dunno if it's intention or oversight.

**Comment by mweststrate** [comment]
Released a fix in 4.2.0

**Comment by philipstanislaus** [comment]
Thanks!
