### ISSUE TITLE
Suggestion: Allow the use of `decorate` as a decorator 

### ISSUE THREAD

**Issue by iMoses** [mobxjs/mobx#1485]
This can be simply achieved by currying in case of a single argument, allowing the function to be used as such:

```
@decorate({
  name: observable,
  email: observable,
})
class MyModel {
  id = Math.random();
  name = null;
  email = null;
}
```

I believe it's a more readable way to decorate and I don't see any downside for supporting both options.
I'll gladly create a PR if you are willing to add this feature.

What do you say? :)

**Comment by mweststrate** [comment]
If decorator syntax is enabled anyway, `@observable` is just less verbose.
Although this would work fine, I think we should restrain from even more
ways to define observable properties (there are 4 ways already) and add
more confusion and API surface.

Op za 7 apr. 2018 om 16:38 schreef iMoses <notifications@github.com>:
