### ISSUE TITLE
where is the useStrict function in the latest edition ?

### ISSUE THREAD

**Issue by ZhijianZhang** [mobxjs/mobx#1487]
Hello every mobxer，i am a rookie .

yesterday i install the latest edition mobx which is 4.1.1, When I want to use useStrict mode.

    import {observer, inject, useStrict} from 'mobx-react'

I have a Question:  i have found nothing about useStrict in the mobx.d.ts file .it means the latest edition mobx had moved useStrict ? so how can i use useStrict function in the 4.1.1 edition ?

**Comment by urugator** [comment]
`configure({ enforceActions: true })`

**Comment by ZhijianZhang** [comment]
thank you i get it [Migrating from mobx 3 to mobx 4](https://github.com/mobxjs/mobx/wiki/Migrating-from-mobx-3-to-mobx-4#things-that-just-have-moved)
