### ISSUE TITLE
Observable.map used with decorate:observable - .values() .entries() no longer working

### ISSUE THREAD

**Issue by Shooshte** [mobxjs/mobx#1488]
Using:
```
"mobx": "^4.1.1"
"mobx-react": "^5.0.0"
```

I have a observable map that I am trying to use with Mobx4.

```
class UiStore {
   loaders = observable.map({'test': 'test'})
}

export default decorate(UiStore, {
   loaders: observable
})
```

When I try to use `.keys()` or `.values()` it just outputs the function definition instead of the actual values.

Minimal sample reproduction:
https://codesandbox.io/s/7kzl3x840j

**Comment by mweststrate** [comment]
See the migration guide. keys & values return iterators (so that aligned
with the spec now, although a little more inconvenient). Use Array.from to
convert an iterator to an array

Op zo 8 apr. 2018 om 19:25 schreef Miha Šušteršič <notifications@github.com

**Comment by urugator** [comment]
`[...map.keys()]` should work as well...

**Comment by Shooshte** [comment]
as @mwestrate pointed out `Array.from(map.keys())` works. Thanks for the help.
