### ISSUE TITLE
observable.array({deep: false}) not behaving the same as @observable.shallow

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx#1489]
I have a simple store that has the following structure:

```js
class SearchStore {
    @observable term = 'javascript';
    @observable state = '';
    results = observable.array([], {deep: false});

    @computed
    get isEmpty() {
        return this.results.length === 0;
    }
```

Here the computed property `isEmpty()` is never triggered if I set `results` to a new value. In fact, the second time I set `results`, it turns into a regular array and is no longer observable.

```js
    @action.bound
    async search() {
        /* ... */
       this.results = searchResults;
    }

```

However, if I declare results with a decorator:

```js
@observable.shallow results = []
```

it works!. Is my usage of observable.array() not correct?

**Comment by pavanpodila** [comment]
Just found out that I need to use the `replace()` API of the `observable.array()` to make it work properly.

Looks like `@observable.shallow` is internally using that, I guess?

**Comment by mweststrate** [comment]
@pavanpodila the difference is that the first creates an observable _array_, and the second an _observable_ property, that will converts it value to an observable automatically if possible. 

So `this.results = ` does not change the array itself, and hence it will not be picked up if only the array was made observable. `this.results` modifies `this` instead, so you need the property to be observable to pick this up. 

In general, I recommend to either use:

```javascript
@observable.shallow results = []
// or
readonly results = observable.array([], {deep: false});
```
The readonly modifier (in typescript) will protect you against accidentally modifying the non-observable property, where a change to the obsrevable array was intended.

`@observable.shallow` is not internally using `.replace`; assigning a new value will assign a new array instance to the array property, not recycling the existing one. So purely theoretically speaking `readonly results` is slightly faster and safer then `@observable.shallow`; as the latter has two changing pieces (the object property and the array) and the first only one.

**Comment by capaj** [comment]
@pavanpodila yes

**Comment by pavanpodila** [comment]
Awesome. Thanks Jiri

Regards,

--
Pavan Podila
