### ISSUE TITLE
Is it unnecessary to use transaction now?

### ISSUE THREAD

**Issue by ZhijianZhang** [mobxjs/mobx#1492]
hello guys, i think i encountered a problem: 
as we all know the observer function packaged by the autorun and some magic， so when i write:
```
@observer
class TodoItem extends React.Component {
    ...
    render() {
        //UI logic code ...
        let todo = this.props.todo;
        let title = todo.title;
        let completed = todo.complete;
        return (
            ......
        );
    }
}


class TodoItemModel {
    id;
    @observable title;
    @observable completed;
    ......
    reset() {
         /*
         Set title and completed values separately，
        Will trigger two re-rendering of the todoItem UI component
        */
        this.completed = false;
        this.title= '';
    }
    ......
}

var todoItem = new TodoItemModel();
//Calling reset will trigger two re-rendering of the TodoItem UI component
todoItem.reset();
```
 Set title and completed values separately， Will trigger two re-rendering of the todoItem UI component。

I remember to solve this problem Mobx has provided the `transaction ` function for advanced rendering performance optimization 。

```
        transaction(()=>{
            this.completed = false;
            this.title= '';
        })
```

But In fact, I don't use transaction now and added `console.log('render...')`  in the render function. . . Found that calling two assignment statements that change the state will only render once.

so I don’t understand,Mobx optimized for us?  Do we still need a transaction now?

**Comment by mweststrate** [comment]
Still do use actions, (transaction is not needed, use action instead which applies transaction as well). 
Otherwise react is still scheduled to update twice, but react itself might decide to skip one update (which is why you see only one log statement). 

Also, not using transaction will affect all your other autoruns / reactions
