### ISSUE TITLE
how can i invoke other store in this store?

### ISSUE THREAD

**Issue by WebCaiQingChong** [mobxjs/mobx#1494]
in store(A), such as this:
`export default class A {
  @observable loading = false

  @action
  change (flag) {
    console.log(flag)
    this.loading = flag
    console.log(this.loading)
  }
}`
other store B 
`export default class B extends A{
  // i want to change A.loading
  change () {
  this.change(true)
  }
}`

console is correctly runing,but in ract component ,it does' work.

how can i invoke correctly in a perfect way?
Because i want to extract the common store in my project.
thanks

**Comment by urugator** [comment]
`super.change(true)`, however you should most likely use composition instead of inheritance.

**Comment by WebCaiQingChong** [comment]
@urugator how can i use composition?  i finally find a way ,i create a class it only can new once to resolve this problem.like this:
`export default class Common {
  @observable loading = false

  constructor (props) {
    this.init()
  }
  
  @action
  change (flag) {
    this.loading = flag
  }
  
  init () {
    if (first) {
      return result
    } else {
      first = true
      result = new Common()
      return result
    }
  }
}`
but it has a defect, if user create this in new Common,it will create a new one.

**Comment by urugator** [comment]
These are pretty basic programming concepts unrelated to MobX, please use SO/google
