### ISSUE TITLE
Consider exporting ObservableMap once again

### ISSUE THREAD

**Issue by nathanstitt** [mobxjs/mobx#1496]
It was exported in 3.x and I don't see any discussion on why it's no longer exported. I do appreciate the deprecation message though, since that at least told me it was intentional 😁 

I'm guessing there were good reasons for it's removal, but I thought I'd open this issue in case it was just "we thought no-one used it"

There's at least a few people who found it useful https://github.com/mobxjs/mobx/issues/863

My use-case for it is that I have custom store-like objects that add filtering methods to maps.  

There are multiple alternative ways these could be built, such as a factory that builds custom maps with the methods added, or possibly interceptors in some cases.  I think my method is the clearest though, and I suspect that a they're more easily optimized by JS engines.

Of course we could still get the class by `observable.map().constructor` 😉 .  Therefore I don't think you're gaining anything by not exporting it.

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [x] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

**Comment by mweststrate** [comment]
The reason it was original deprecated was that it might disappear in MobX 5. But it will most probably stay, so will undeprecated it :)

**Comment by nathanstitt** [comment]
ok, I'll make a PR to do so then, it looks fairly straightforward to do so. Thanks @mweststrate !

**Comment by mweststrate** [comment]
Released as 4.2.0

**Comment by mweststrate** [comment]
Sorry, just beat you to it!

Op ma 16 apr. 2018 om 20:06 schreef Nathan Stitt <notifications@github.com>:

**Comment by mweststrate** [comment]
Thanks for the effort though :)

Op ma 16 apr. 2018 om 21:13 schreef Michel Weststrate <mweststrate@gmail.com
