### ISSUE TITLE
How to do X from Rx in Mobx

### ISSUE THREAD

**Issue by gregpardo** [mobxjs/mobx#150]
Would be very nice to have a chart with all the RxJS or other library operators and examples of how to accomplish the same task with Mobx.

**Comment by mweststrate** [comment]
Hi @gregpardo, 

MobX is not a stream library and as such it has not really a concept of stream operators. RxJs is for reactive programming with _events_ and MobX for reactive programming with _values_ See https://www.reddit.com/r/reactjs/comments/49qe1f/ten_minute_interactive_introduction_to_mobx_and/d0v19u8 for an eloborate explanation, and tips for when to use MobX or RxJs and how to combine them

**Comment by gregpardo** [comment]
Thanks for your response. I did figure out Mobx was not a stream library but for simple use cases (that don't involve time as you mentioned) they can accomplish similar tasks. Would it be okay to copy that response to the wiki and add a link for those with questions on how they differ?

**Comment by mweststrate** [comment]
Sure, go ahead!

Op vr 11 mrt. 2016 om 14:30 schreef Greg Pardo <notifications@github.com>:

**Comment by gregpardo** [comment]
Can you read over it and edit/change anything that's incorrect. I introduced some stuff about Hot/Cold observables which might be wrong but just check it out and let me know.

https://github.com/mobxjs/mobx/wiki/Mobx-vs-Reactive-Stream-Libraries-(RxJS,-Bacon,-etc)

**Comment by mweststrate** [comment]
Thanks!

```
This is similar to the concept of Hot vs. Cold observables. MobX would be similar to that of Cold observables. This means that values are lazily evaluated on a subscription basis. They are only computed while an observer or subscriber is listening.
```

I think this paragraph is close but not entirely accurate. MobX has a concept related to "hot" and "cold" and calls those "reactions" and "computed values" (see also the getting started). Computed values in MobX will never re-compute automatically, unless some reaction are using them (indirectly). So observables that have observers might still be inactive (which makes it very efficient). In FP terms: MobX uses lazy evaluation, and evaluations only run when a reaction needs a discrete value. But if an observable is not observed by a reaction (indirectly) it will never receive events. So a `computed` which is not used somewhere in `autorun` is effectively a noop and won't even observe it's own dependencies.

Ok, this might sound fuzzy right now, but I have to go AFK, if it is unclear let me know and I'll try to explain it better.

**Comment by mweststrate** [comment]
Again thanks for writing this down. I think the word `similar` provides enough room to cover subtle differences and the description is fine as it is.
