### ISSUE TITLE
Flow typing of observable.map is not updated for MobX 4

### ISSUE THREAD

**Issue by quanganhtran** [mobxjs/mobx#1500]
I have a:

2. [x] Issue:
  * [x] Did you check this issue wasn't filed before?
  * [x] State the versions of MobX and relevant libraries: MobX 4

Since MobX 4 uses ES6 Map, all typings related to `Map<T>` has been updated to `Map<K, V>` except `observable.map`. This introduces Flow error with Flow 0.69

I have prepared a PR to update the definition.

**Comment by mweststrate** [comment]
Merged! Will release soon
