### ISSUE TITLE
Customize decorators on flowed method with typescript

### ISSUE THREAD

**Issue by DrakeXiang** [mobxjs/mobx#1503]
I'm trying to add a loading decorator for async method to automatically indicate loading status:

```typescript
// Loading.ts
export class Loading {
  @observable loading = false;

  @action.bound
  setLoading(isLoading: boolean) {
    this.loading = isLoading;
  }
}

export function loading(
  target: any,
  name: string,
  descriptor: any
): any {
  const method = descriptor.value;

  descriptor.value = async function(params?: any) {
    this.setLoading(true);
    const r = await method.apply(this, params);
    this.setLoading(false);
    return r;
  };

}
```

```typescript
// UserStore.ts
class UserStore extends Loading {
  rootStore: RootStore;

  constructor(rootStore: RootStore) {
    super();
    this.rootStore = rootStore;
  }

  @observable userInfo: any;

  @loading
  @action.bound
  userLogin = flow(function*(userInfo: any) {
    console.log('login start')
    const result = yield s_userLogin(userInfo);
    console.log('login end', result)

    if (result.success) {
      alert('login success');
    }
  })
}
```

If I use `asyncAction` from `mobx-utils` instead of `flow`, this works well. Since `asynceAction` is deprecated in favor of the `flow` api, I'd like to change it, however typescript always reported `Unable to resolve signature of class decorator when called as an expression`. Then I found that descriptor received in flow function doesn't has a `value` property, but a `get` and `set` function.

Is it possible to achieve the similar function?

**Comment by mweststrate** [comment]
The error `Unable to resolve signature of class decorator when called as an expression` is unrelated to the runtime code, it means this function signature is incorrect:

```
export function loading(
  target: any,
  name: string,
  descriptor: any
): any
```

afaik it should be:

```
function (target: Object, key: string | symbol, baseDescriptor?: PropertyDescriptor): any // decorator
```
