### ISSUE TITLE
Object.values(observableObject) always returns [] in Chrome 66

### ISSUE THREAD

**Issue by vkramskikh** [mobxjs/mobx#1504]
Discovered this after update of Chrome.
<img width="310" alt="screen shot 2018-04-19 at 12 12 04" src="https://user-images.githubusercontent.com/426659/38973665-2b245958-43d1-11e8-8474-f1ea898452cc.png">
It works fine with other browsers and the old Chrome. Mobx 3 & 4 are both affected. Lodash's keys() and values() work fine. 

Any clues about the cause of this ussue - is this Mobx or Chrome issue? Any recommended fix (I've switched to lodash's keys() and values() for now).

**Comment by urugator** [comment]
Not always, it returns empty array only if you run `Object.keys` prior to `Object.values` ... bizarre ...
Here is a reproduction: https://codesandbox.io/s/j7k2kk343v

**Comment by xaviergonz** [comment]
Object.entries is affected as well

**Comment by xaviergonz** [comment]
not sure if related https://bugs.chromium.org/p/chromium/issues/detail?id=804159&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by xaviergonz** [comment]
Actually it is this one:
https://bugs.chromium.org/p/chromium/issues/detail?id=836145

**Comment by xaviergonz** [comment]
I just made this polyfill while they fix it
```

import lodashToPairs = require("lodash/toPairs");

import lodashValues = require("lodash/values");

 

// fix for chrome 66 broken Object.values/entries
function polyfillBrokenObjectValuesEntries() { 
  const object1: any = {};
  Object.defineProperty(object1, 'test', { value: undefined });
  object1.a = object1.b = object1.c = 'value';
  const keys = Object.keys(object1);
  const values = Object.values(object1);

 
  if (keys.length !== values.length) {
    console.info("polyfilling Object.keys and Object.entries for broken implementation")
    Object.values = lodashValues;
    Object.entries = lodashToPairs;
  }
}


polyfillBrokenObjectValuesEntries();

 

 

 


```

**Comment by vkramskikh** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=836145 Seems to be fixed in Chrome 66, closing the issue.
