### ISSUE TITLE
observe() do not catch modifications done with set() method

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#1512]
`observe(object, listener)` do not catch modifications to existing props of object done with `set`. It only catches new property added. See jsfiddle: https://jsfiddle.net/4j6b3srp/

```ts
const a = mobx.extendObservable({}, {}, {}, {deep: false})

mobx.observe(a, console.log)

/*
logs {
  type: "add",
  object: {…},
  name: "prop1",
  newValue: "new prop"
}
as expected
*/
mobx.set(a, "prop1", "new prop") 

/*
expected to log {
  type: "update",
  object: {…},
  oldValue: "new prop",
  name: "prop1",
  newValue: "changed with set()"
}
but log do not happens
*/
mobx.set(a, "prop1", "changed with set()") 

/*
logs {
  type: "update",
  object: {…},
  oldValue: "changed with set()",
  name: "prop1",
  newValue: "changed with setter"
}
as expected
*/
a.prop1 = "changed with setter"
```
I think `intercept` is also affected

**Comment by quanganhtran** [comment]
I took a quick look at https://github.com/mobxjs/mobx/blob/dbe4c935d5fe6413d6727fcae36760fb7d7a47cd/src/api/object-api.ts#L65-L71
The first time when a new property is set, `defineObservableProperty` is called and will notify all listeners bound to `obj`, but subsequent calls to `set` get out the `existingObservable` which is an observable value with its own listeners.

Possible solution might be to set the new value through the parent observable object? In that case notification will go through for both the object and the value.

**Comment by mweststrate** [comment]
MR is merged and will be part of next release. Thanks @quanganhtran
