### ISSUE TITLE
[suggestion] use ES6 map instead of array in mob.toJS() memorizer?

### ISSUE THREAD

**Issue by loatheb** [mobxjs/mobx#1519]
I have a Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

This is a suggestion of refactoring `tojs` method. 

I looked at the code and found that in `tojs` comment stated that it hope to improve the performance of the cache through the ES6 Map. Also, I extract a common function in recursion.

PR is here 👉 [1517](https://github.com/mobxjs/mobx/pull/1517)

Can anyone do a review or give me some suggestion of it?

**Comment by mweststrate** [comment]
Reviewed, will be part of next release, thanks!
