### ISSUE TITLE
Decorator issue

### ISSUE THREAD

**Issue by cannc4** [mobxjs/mobx#1522]
Hey folks,

I've been having this problem with the decorators where it's giving me `Unexpected token` error on `@inject` when I try to clean install the app with `npm i`  on version `5.8.0`

```
   "mobx": "^3.4.1",
   "mobx-react": "^4.3.5" 
```
I am aware that the decorators are still experimental but I find this odd as I can run it on a few machines where it was installed in the early days of the software.  
This is basically a rewrite of a project which was originally developed using Redux. So I am in process of re-writing it using Mobx and I created an `orphan` branch in the same repo. I suspect that I may have broken something there perhaps.. 

If anything I can just not use decorators but I still find this quite odd

Any tips?

**Comment by mweststrate** [comment]
Follow the setup instructions as provided in the docs and enable babel decorator compilation. Being able to use decorators or not is completely unrelated to mobx and depends on your build setup, not these libraries
