### ISSUE TITLE
Potential Bug: observable(new Map) does not add .observe in ES6

### ISSUE THREAD

**Issue by arminrosu** [mobxjs/mobx#1524]
I hope this is just me doing something stupid. I'm trying to access the `.observe` method of an observableMap. The umd version of mobx [does this perfectly](http://jsbin.com/hegage/6/edit?html,js,console). But for some reason, my ES6 build will not:

Sample:

```js
import { observable } from 'mobx'

export default class Store {
  @observable articles = new Map()
}


const store = new Store()

console.log(store.articles.observe) // undefined
```

Can someone please advise?

**Comment by arminrosu** [comment]
Nevermind, I was including an old version of mobx. My bad :(

**Comment by mweststrate** [comment]
Tried the above, but it succeeds fine in the test suite. Please provide a proper reproduction.

**Comment by arminrosu** [comment]
@mweststrate thanks for looking into this. I searched for the root cause of this issue today and found it. 

I am including the [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime/) plugin in `.babelrc`. This in turn imports [core-js](https://github.com/zloirock/core-js) in the bundle. 

MobX correctly identifies the decorator argument as a Map, but `Map !== instanceof window.Map`. Oddly, the [current mobx implementation](https://github.com/mobxjs/mobx/blob/master/src/utils/utils.ts#L152) already checks for the correct instance. I don't think a code change is needed.

Removing `transform-runtime` fixes the above issue.

Hope this helps somebody else.
