### ISSUE TITLE
Ordering of overloaded flow method typings wrong?

### ISSUE THREAD

**Issue by erkieh** [mobxjs/mobx#1527]
Shouldn't the ordering of the overloaded methods start with one argument and increase by one after that? All but my one argument generator functions get resolved to the 8 argument version. An example demonstrating the problem.

[![Edit xl8z7p4m3z](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xl8z7p4m3z)

**Comment by singggum3b** [comment]
Yeah , i'm getting that too

**Comment by mweststrate** [comment]
Will swap them in the next release
