### ISSUE TITLE
Cannot create observable when using TypeScript

### ISSUE THREAD

**Issue by Aminadav** [mobxjs/mobx#1528]
TypeScript compiler does not recognize properties on observable. There is any workaround?

Image:

![image](https://user-images.githubusercontent.com/3584317/39470187-de2680fe-4d44-11e8-943a-255f9b201e09.png)

**Comment by mweststrate** [comment]
@Aminadav I tried the same, but it resolves correctly for me on MobX 4.2 & TS 2.8.1. Please make sure you are using the latest versions.

**Comment by mweststrate** [comment]
Close for the lack of  reproduction
