### ISSUE TITLE
toJS doesn't work with computed input

### ISSUE THREAD

**Issue by hyperknot** [mobxjs/mobx#1532]
I'm trying to use toJS to get rid of the "stickiness" of observables, yet it doesn't work in all cases. 
In particular if I try to add it to a computed property, it doesn't have any effect.

https://codesandbox.io/s/v6227j5q60

```
import centerOfMass from "@turf/center-of-mass";
import { observable, computed, toJS } from "mobx";

class Feature {
  @observable geometry;

  @computed
  get geojsonGeom() {
    return {
      geometry: this.geometry
    };
  }

  getCenter() {
    const centerFeature = centerOfMass(toJS(this.geojsonGeom));
    console.log(centerFeature);
    return centerFeature.geometry.coordinates;
  }
}

const geojson = {
  coordinates: [19.701844453811646, 47.79048638563558],
  type: "Point"
};

const feature = new Feature();
feature.geometry = geojson;
console.log(feature.getCenter());
```

I end up with observable arrays, which I cannot use in vanilla libs, unless I do toJS() again.

**Comment by urugator** [comment]
`toJS` doesn't recurse into non-observables, the same way as `observable` doesn't recurse into already observables
For more info see https://github.com/mobxjs/mobx/issues/1341

**Comment by hyperknot** [comment]
I see. And what do you recommend for solving this use case?

**Comment by hyperknot** [comment]
I see. I'll simply avoid using computed here then.
