### ISSUE TITLE
onBecome(Un)Observed intercept hooks can remove each other

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#1537]
The way `onBecomeObserved` and `onBecomeUnobserved` are implemented means they can inadvertently cancel each other. 

Source of the issue is here:
https://github.com/mobxjs/mobx/blob/master/src/api/become-observed.ts#L44

If you add a hook, the behaviour is 'call the original hook, then the new one'. The disposer function that is returned has the behavior of 'restore the original hook'. 

This means that if a hook is disposed (with the return value), any subsequent hooks added since that was added will also be removed. Example here:
https://codesandbox.io/s/k0y70x7vy7

(You'd expect one of the two callbacks be called, but it isn't because the first was removed).

I started a fix for this, but the solution wasn't as immediately straightforward as I thought and since I don't know when I'll have time to give it another go I wanted to record this for now.

**Comment by mweststrate** [comment]
Hey! Feel free to open a PR, it is probably easier to discuss with some
code at hand :-)

Op ma 1 okt. 2018 om 11:25 schreef Michał Warda <notifications@github.com>:

**Comment by michalwarda** [comment]
@mweststrate Do you have any suggestions on how can we continue this? I have some time currently so I can adjust the PR.

**Comment by mweststrate** [comment]
released in 4.8.0 / 5.8.0
