### ISSUE TITLE
[Question] Implementation details, about reactions 

### ISSUE THREAD

**Issue by zhDmitry** [mobxjs/mobx#1541]
1. [ x] Question: Feel free to just state your question
I have a question about implementation. I was researching  and found mobx source quite useful, but i have one question unanswered after looking throw all code base. So how did you track such computations like below. How can you know that you don't need to track full property 'b'. 
So, what is the algo of resolving computed function, property dependencies ? 
```
import { computed, observable, autorun } from 'mobx';
const data = observable({ a:0, b: { c: 0, d: 0 }  });

const res = computed(()=> {
  console.log('call');
  const temp = data.b;
  return { c:temp.c }
})

autorun(()=>{
  console.log(res);
})


data.a = 1;
data.b.c = 2;
data.b.d = 4;
```

I just want to implement something similar, something like  this.
```
fn = (data) =({  name: data.user.name, data: data.user.pass  })
```
And i looking for inspiration, mobx sources looks promising in solving similar problem but them too complex for me. Maybe you can give some hins where should I look or some info how to solve my problem. Thanks =)

**Comment by zhDmitry** [comment]
But how mobx, knows that it shouldn't track `const temp = data.b; ` , but it knows that it should track when we get return something like this `{ a:  temp.c, temp: temp }` it will track all changes. How it knows the difference ?  I saw that it doesn't track return properties, it only tracks return value.

**Comment by urugator** [comment]
Again it doesn't care what you return, but what you access...
If you access `data.b`, it will react to `data.b = 5`.
If you access `data.b.c` (`temp.c`), it will react to  `b.c = 5`. 
It wil never react to `data.b.d = 5`, unless it's accessed inside computed.

As mentioned the premise is simple: If you don't access something inside computed, it can't change the computation result, therefore it doesn't have to be tracked...

**Comment by zhDmitry** [comment]
but in case when you return this value, it will start track it, https://stackblitz.com/edit/react-wv3gvp
`{ a: temp.c, temp: temp }`. I don't get why this happening.

**Comment by urugator** [comment]
It's not the computed being recomputed, but autorun being re-run, because `console.log` recurses into the object, subscribing for all props... try to put `console.log("computing")` inside `computed`

**Comment by zhDmitry** [comment]
thanks  @urugator
