### ISSUE TITLE
Understanding WHERE to use autorun() (mobx-react-devtools breaks autorun?)

### ISSUE THREAD

**Issue by CharlieIGG** [mobxjs/mobx#1542]
Hello y'all!

I think I'm having issues figuring out where / how to use autorun.

I'm using Mobx with React, where I instantiate a store and then pass it to my components using the `Provider` and `inject` modules from `mobx-react`. My store looks like this:

```javascript
class AppStore {
    @observable exampleData = {
        foo: 1234,
        bar: "baz"
    };
    @computed get fooMultiplier(){
        return this.foo * 2;
    }
    reactToFooChange = autorun(() => console.log(this.exampleData.foo));
}
```

When I do this `exampleData` is successfully observed by my observer components, and `fooMultiplier` works as expected too, however `reactToFooChange` doesn't work.

I've also tried just declaring the `autorun` without naming it without success.

If on the other hand I use `autorun` outside of this class declaration, and inside one of my components (changing `this.exampleData.foo` to `props.exampleData.foo` for instance), `autorun` triggers when the component mounts itself, but not when the observed data changes...

Can anyone help me understand how this should be implemented?

Do you guys think we should add more contextual examples to the README?

Thanks!

**Comment by urugator** [comment]
Seems working to me: https://codesandbox.io/s/94nm892nqr

**Comment by CharlieIGG** [comment]
@urugator  I now realize the problem might be changing the nested values of an observed object (this wasn't properly represented on the snippet above due to over-simplification). How should I proceed to properly call autorun in this scenario? Would autorun/reaction only run if I explicitly pass all the nested object's values inside the function?

**Comment by urugator** [comment]
Firstly consult https://mobx.js.org/best/react.html

For additional background you may also take a look at [this recent post](https://github.com/mobxjs/mobx/issues/1541#issuecomment-388026096)

For edge cases where you need to explicitely subscribe for whole object hierarchy (usually when passing observables to 3rd party libs), take a look at `mobx.toJS(data)`

**Comment by CharlieIGG** [comment]
Thanks @urugator. I did go through the whole post already and I think I'm doing it right. I adapted the codesandbox you made to my specific use case, and it works in there, but for some reason it doesn't work on my project with virtually the same stuff 🤔

**Comment by urugator** [comment]
You may try to move `autorun` to constructor eliminating the possibility, that there is some problem with transpilation (shouldn't matter I quess, but who knows).
In case you're using HMR note it doesn't play well with Mobx

**Comment by CharlieIGG** [comment]
I AM using HMR... however I just tried removing it (i.e. calling `export default App` instead of `export default hot(module)(App)`, with the same resulting behavior. Also tried declaring the `autorun` in my constructor with and without HMR, all to no avail.. 😔

**Comment by urugator** [comment]
You may also try to get decorators out of equation and replace them with 
`extendObservable(this, { isMobile: null, /*...*/ })` prior autorun creation.
To check that something is actually observable use `isObservableProp(this, "isMobile")`
I also noted that sandbox doesn't use latest version so you may try fiddle with that as well...

**Comment by CharlieIGG** [comment]
@urugator just for the sake of testing I did the following:

```javascript
import { autorun, computed, flow, observable, reaction, extendObservable, isObservableProp } from "mobx";

class AppState {

}

// exposes store to the console if not on production

let store;

if (process.env.NODE_ENV !== 'production') {
    store = window.store = new AppState();
} else {
    store = new AppState();
}

extendObservable(store, {
    isMobile: null,
    sidebarOpen: false,
    quote: {
        selectedService: "Diagnóstico General",
        availableServices: [
            (...)
        ],
        errors: {
            (...)
        },
        years: [],
        brands: [],
        models: [],
        motors: [],
        carData: {
            brand: '',
            model: '',
            year: '',
            motor: '',
        },
        (...)
    }
})

const reactToStuff = autorun(() => {
    console.log("New Value: ", store.isMobile);
    console.log(isObservableProp(this, "isMobile"));
});

export default store;
```

Doesn't work, and it says "isMobile" is not an observable prop. 

I then went and tested `isMobile`, `sidebarOpen`, `quote`, `quote.carData`, and `quote.carData.year` using 'isObservableProp()` with the following results:

- object props return `true` (quote, quote.carData)
- anything else returns `false` (isMobile, sidebarOpen, quote.carData.year)

This makes me believe that I'm misunderstanding the way Mobx works, but I'm confused, since the examples show similar things with different outcomes...

**Comment by CharlieIGG** [comment]
**BINGO!** I found the culprit, but not the reason why.
The problem is with this chunk of my state:
```javascript
@observable quote = {
        selectedService: "Diagnóstico General",
        availableServices: [
            "Diagnostico General",
            "Diagnostico Viajero",
            "Cambio de Aceite",
            "Afinación Mayor",
        ],
        errors: {
            cannotConnectToApi: null,
            errorGettingYears: null,
            errorGettingBrands: null,
            errorGettingModels: null,
            errorGettingMotors: null,
        },
        years: [],
        brands: [],
        models: [],
        motors: [],
        carData: {
            brand: '',
            model: '',
            year: 4,
            motor: '',
        },
        loading: false,
        initialLoading: false,
    };
```

if I remove this prop from the state everything starts working as expected (`autorun`, `reaction`, etc):

```javascript
        availableServices: [
            "Diagnostico General",
            "Diagnostico Viajero",
            "Cambio de Aceite",
            "Afinación Mayor",
        ],
```
I tried removing accents and whitespaces in the strings, just for the sake of testing, and it still doesn't work. Removing this attribute altogether is the only way of getting things working again, like so:

```javascript
@observable quote = {
        selectedService: "Diagnóstico General",
        errors: {
            cannotConnectToApi: null,
            errorGettingYears: null,
            errorGettingBrands: null,
            errorGettingModels: null,
            errorGettingMotors: null,
        },
        years: [],
        brands: [],
        models: [],
        motors: [],
        carData: {
            brand: '',
            model: '',
            year: 4,
            motor: '',
        },
        loading: false,
        initialLoading: false,
    };
```

Any idea why this might be so???

**Comment by CharlieIGG** [comment]
1. I completely uninstalled `react-hot-loader` and stopped using the `hot(module)` function on my app and am still getting the same results (This would've been a probable deal-breaker for me anyways).
2. Based on [this post](https://mobx.js.org/best/stateless-HMR.html) I went and changed all my Stateless Components that were being subscribed as observes from arrow functions to named functions. Still same results. I still have some minor components that are declared as arrow functions, but that are not being subscribed as observers, so IDK if it would matter or not to try to change all those to named functions.
3. Removing [mobx-react-devtools](mobx-react-devtools) and using [mobx-devtools](https://github.com/mobxjs/mobx-devtools) instead seems to be doing the trick for me.

I will turn HMR back on and keep on working. If I see anything else breaking then I might come back to this thread and re-open the discussion.

Thanks for all your help @urugator.
