### ISSUE TITLE
Every time I refresh the page with F5 the @observable is lost.

### ISSUE THREAD

**Issue by godimen123456** [mobxjs/mobx#1544]
Hi,

I have a doubt about the annotation @observable. Every time I refresh the page with F5 the state is lost, and the logged user with it. How do you manage this? Do you keep the user data in the localstorage/cookies? I'm looking for the best practive to persist this data and validate with the server later.

My component is like this:

<Route
        {...rest}
        render={props =>
          isLoggedIn
            ? <Component {...props} />
            :<Redirect
                to="/signin"
              />}
      />

The method isLoggedIn checks if the user is logged in or not, by checking the stored user in the Store.

**Comment by vaclav-zeman** [comment]
There's a handy library for that called [mobx-persist ](https://github.com/pinqy520/mobx-persist). You decorate the observables that you want to persist with `@persist` - that way the library knows what to save in localStorage (which is used by default). Then just you hydrate the data at store initiation with the lib's `create` method.

You can also do it by yourself with localStorage/indexedDB. I personally wouldn't store UI state in cookies.

**Comment by urugator** [comment]
If possible I suggest to use cookie based session for user identification and store everything else to DB.
So you re-fetch user data on each page load (or pass them as part of initial state in case of SSR).  
 
There are some security risk related to `localStorage`:
- data can't expire
- data are stored unecrypted 
- data are accessible from JS (XSS)

If you don't mind deleting the data upon closing tab/window you may use `sessionStorage`.

**Comment by jbreckmckye** [comment]
Observables just store / track state in the browser heap, which gets cleared between refreshes. You wouldn't expect a JavaScript variable to persist between refreshes - observables are no different.

If you want to keep them in storage, you'll need a helper library like mobx-persist that can sync your heap observables to local storage. I don't know the internals of that library, but be aware there might be performance implications - writing to localstorage will block on system I/O.

**Comment by mweststrate** [comment]
Closing as question has been answered
