### ISSUE TITLE
Cannot override mobx actions

### ISSUE THREAD

**Issue by ionutmiftode** [mobxjs/mobx#1545]
Hi,
In mobx 3.x I was able to mock actions using jest something like
`myStore.myAction = jest.fn()`

However after the update I receive the following error:
`TypeError: Cannot assign to read only property 'myAction' of object '#<MyStore>'`

it seems that in mobx 4.x actions are `writable: false` while in 3.x were `writable: true`.
I know that I can override them doing something like
`Object.defineProperty(myStore, 'myAction', {value: jest.fn(), writable: true});`
but it will be a pain to change it in all the 100 failing tests :).

I saw that this was fixed in #1407 but it seems that is not working for me with `process.env.NODE_ENV = 'test'`. Any ideas why?

mobx: 4.2.1
node: v8.9.4

**Comment by mweststrate** [comment]
Reproduced, will fix in next release

Op ma 14 mei 2018 om 11:59 schreef Mifi <notifications@github.com>:
