### ISSUE TITLE
(@)computed not updated

### ISSUE THREAD

**Issue by misantronic** [mobxjs/mobx#1546]
mobx@4.2.0

I've had really good experiences with computed-values. Now, I've come to a case where the computed-value is simply not updated. Here the example:

```js
@computed
public get assignedGroups(): Option[] {
    const { $: userJSON } = this.user;
    const { $: allRoles } = this.roles;

    if (userJSON && allRoles.length) {
        const userRoles = allRoles.filter(r => {
            for (const u of r.users || []) {
                if (u.id === userJSON.id) {
                    return true;
                }
            }
            return false;
        });

        return userRoles.map(role => ({
            label: role.name,
            value: role.id
        }));
    }

    return [];
}

@computed
public get hasAssignedGroups(): boolean {
    console.log('hasAssignedGroups', this.assignedGroups);
    return (
        this.assignedGroups.some(group =>
            this.companyRoles.$.some(cRole => cRole.id === group.value)
        ) === false
    );
}
```

what's fine and updating is `assignedGroups`. Whenever the observables referenced inside change, this value is re-calculated and all is good.
now, `hasAssignedGroups` has a dependency on `assignedGroups`, so `hasAssignedGroups` should recalculate when `assignedGroups` changes. But it does not. It just consoles out the first time and then nothing ever changes.

**Comment by mweststrate** [comment]
Please create a sandbox demonstrating the issue

Op wo 16 mei 2018 02:24 schreef David Skx <notifications@github.com>:

**Comment by misantronic** [comment]
I went on creating an example on jsfiddle, there it all worked fine. That got me thinking and the problem was that `r.users` is a `Set` which cannot be observable. So I converted it to an observable array and that solved it.
