### ISSUE TITLE
using componentWillMount silently breaks things

### ISSUE THREAD

**Issue by schumannd** [mobxjs/mobx#1547]
I was debugging an issue where render would simply not register any updates.
But only when I tried to use `trace()` within render, I got the following error:

```
Error: [mobx] Invariant failed: 'trace(break?)' can only be used inside a tracked computed value or a Reaction. Consider passing in the computed value or reaction explicitly
```

Through trial and error I found that removing `componentWillMount()` solved the problem. Even an empty `componentWillMount() {}` method would cause the error.

Using componentDidMount was enough in my case to solve all my issues. Shouldn't this be mentioned somewhere? Or what about throwing a warning if the user uses `componentWillMount`?

**Comment by mweststrate** [comment]
Can you create a reproduction in a sandbox?

Op wo 16 mei 2018 om 10:57 schreef David Schumann <notifications@github.com

**Comment by mweststrate** [comment]
Then I can't really help you at this moment.
