### ISSUE TITLE
Add option to suppress minified build warning 

### ISSUE THREAD

**Issue by jtheisen** [mobxjs/mobx#1548]
MobX doesn't like to be minified while not having the NODE_ENV set to production:

> you are running a minified build, but 'process.env.NODE_ENV' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle

I want both minification and keeping the React logging which won't happen with the suggested setting.

I don't think performance will be an issue for me.

Is there a way to get rid of that warning?

**Comment by mweststrate** [comment]
Afaik MobX follows the exact same pattern as React here. React will give the same error if I am not mistaken?

**Comment by jtheisen** [comment]
I sure used to. I think that's no longer the case.

**Comment by avioli** [comment]
@jtheisen Fork it and remove the offending check?

**Comment by mweststrate** [comment]
Or https://www.npmjs.com/package/patch-package, it's awesome!

**Comment by chase-moskal** [comment]
@mweststrate — i'm also having this issue, but i can't figure out how else to express how productive i want my node env to be:

    NODE_ENV=production browserify source/global.ts --debug -p [ tsify ] -t [ envify --NODE_ENV production ] -t uglifyify | uglifyjs -cm > dist/global.bundle.js

what gives? how can i satisfy the warning and fix my bundle?

**Comment by avioli** [comment]
@chase-moskal That comment is for the browserify project. Not MobX.

**Comment by mweststrate** [comment]
See release notes of 4.8.0 / 5.8.0, it is now possible to override this using a global env variable (make sure to configure it in your build setup)
