### ISSUE TITLE
[Question] Use mobx in a UI Library

### ISSUE THREAD

**Issue by janhoeck** [mobxjs/mobx#1550]
Hello Guys,

I have an question. Maybe it is an issue, that why I create my question here.

I created a UI library to use components in more than one application. The UI Library just use @observable, @observer and @action decorators. The library hasn't defined any stores or providers. When I now try to use these conponents (maybe a button that uses mobx) than it don't work. My Application doesn't listen on any observables. 
The second problem is, when I use npm link, than my main project tells me that there are two mobx instances running. But when I use the library without npm link, than the message disappears.

My question is now: Am I able to use mobx in this way I described?
Is there a example library you can show me, who is using mobx?

Thank you :D

**Comment by urugator** [comment]
Take a look at https://github.com/mobxjs/mobx/issues/1082

**Comment by mweststrate** [comment]
Recommendation: use MobX as peer dependency (it can be a direct dependency as well when used in isolated mode, but that will usually blow up the bundle sizes (of consumers)). This might give issues when using `npm link` indeed, but that is a bug (or fundamental problem) with linking packages; when using link packages appear indeed twice in the dep tree (draw it out to see why). I recommend using yarn workspaces instead when working on multi package solutions.

Beyond that, what @urugator said :)
