### ISSUE TITLE
Mobx do weird things (with code demo)

### ISSUE THREAD

**Issue by janhoeck** [mobxjs/mobx#1551]
Hello,

mobx is doing weird things in my application.
<Header /> will always be rerendered and every <EntityListItem> will be rerendered, when I click on a checkbox. BUT: When I make Header and EntityListItem to an @observer than these components won't be rerendered. Why? Do I make anything false?

Code demo with my current versions:
https://codesandbox.io/s/jnv687o48v

**Comment by mweststrate** [comment]
I couldn't really parse your original question, but yes that could be the answer. Please formulate issues more carefully. I assume you mean `@observer`, not `@Observer`? I didn't get what you mean with 'anything false'  etc. Please state observed and expected behavior clearly when asking a question, and make sure the reproduction is small.

**Comment by janhoeck** [comment]
Sorry github removed my `< />` phrases ... I did not know that.
Lets try it again in a some clearer way :)

The Header component will always be rerendered, even if the props changed or not.
The EntityListItem component has the same issue. The issue is gone, when I add `@observer` to the components. 
I was confused why this happens, because these two components does not have any `@observables`

**Comment by urugator** [comment]
> The `<Header />` component will always be rerendered, even if the props changed or not.

This is standard react behavior - if component is updated (`EntityList`) , all it's children (`Header`, `EntityListItem`) are updated as well, unless the child implements `shouldComponentUpdate`.
Which is what `@observer` does, it provides `shouldComponentUpdate` implementation, working the same way as `React.PureComponent`, therefore the different behavior.

> I was confused why this happens, because these two components does not have any @observables

`@observable` doesn't modify the component behavior, it simply defines observable property on component instance, but it could be defined anywhere else.

For explanation see: https://mobx.js.org/best/react.html
