### ISSUE TITLE
Ability to use decorate non-eager

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx#1552]
Basically behavior of Mobx.decorate for now is "eager" in that it decorates everything.

For my use case would be much nicer to have the option to have it just decorate the properties I specify, and leave the rest alone. For now I can work around, but just noting here.

**Comment by mweststrate** [comment]
Use extendObservable instead

Op wo 23 mei 2018 00:58 schreef Nate Wienert <notifications@github.com>:

**Comment by natew** [comment]
I think actually I was misinterpreting the docs. Seems like Mobx.decorate doesn't auto decorate my properties, at least ones set by class properties so I am ok.

extendObservable has a deprecation warning for me in 4.

Fine for me for now, thank you.
