### ISSUE TITLE
toJS() includes functions in its return value

### ISSUE THREAD

**Issue by nareshbhatia** [mobxjs/mobx#1553]
[x] Issue
  * [x] **Provide error messages including stacktrace**
N/A, just unexpected behavior
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
Could not reproduce in ES6. Only in TypeScript. Hence I created a minimal example in a repo: https://github.com/nareshbhatia/mobx-tojs-issue. Please see the observable object called `Order` and run the test to see that the expected output from `toJS()` does not match the actual output.
  * [x] Did you check this issue wasn't filed before?
Yes. Also asked @mweststrate over Gitter. He asked me to file an issue.
  * [x] Elaborate on your issue. What behavior did you expect?
When toJS() is called on an observable object, it includes functions in the output. I expect only data to be present in the output. Note that functions marked as actions and computed are not included, but other functions are. In my example, I have a function called `serialize` that is included.
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
MobX 4.2.1

**Comment by urugator** [comment]
`toJS` is the opposite process to `observable`, meaning it only converts enumerable props and it preserves inconvertible values (like functions, class instances, etc).
Computed and actions are not enumerable, because ES6 class getters and methods are not enumerable.
For serialization either implement `toJSON` or change your tests to actually compare serialized values (strings), in which case `JSON.stringify(instance)` will most likely produce desired results.

**Comment by nareshbhatia** [comment]
@urugator, thanks for the detailed explanation.

In order to satisfy my use case, I have to run `JSON.stringify()` followed by `JSON.parse()`. This is to make sure that I have a clean JS object that I can use for comparisons in my tests. Here's the modified code. It is kind of ugly, but I can live with it:

```
export class Order {
    constructor(
        readonly id: string,
        public symbol: string,
        public quantity: number,
    ) {}

    serialize(): JsOrder {
        // return toJS(this);
        return JSON.parse(JSON.stringify(this));
    }
}
```

Just out of curiosity, what use case is `toJS()` catering to? Is there a practical example that you can point to?

**Comment by urugator** [comment]
It is mostly used when passing observables to 3rd party libs ... it subscribes for the whole object (inside observer/reaction), removes mobx boilerplate (hidden private fields, redundant getters, etc), reverts quirks (array/set/map not being a native array/set/map) and obviously removes observability, so the returned object actually looks and behaves as plain JS structure...

**Comment by nareshbhatia** [comment]
Thanks @urugator, that makes perfect sense.
