### ISSUE TITLE
ObservableMap should extend Map

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#1556]
Ideally, ObservableMap should extend the built-in Map object. However neither TypeScript nor Babel 6 support this well:

See https://github.com/Microsoft/TypeScript/issues/10853
and https://github.com/babel/babel/pull/7020

Alternatively we could instantiate normal Maps and monkey patch them, but that has probably quite some impact, so for now, leaving this as-is.

**Comment by odahcam** [comment]
Is it possible now to extend Map anyway?

**Comment by mweststrate** [comment]
I think it is possible to extend `ObservableMap`, but `ObservableMap` doesn't extend `Map`. It gave too much issues

**Comment by odahcam** [comment]
All right, thanks!
