### ISSUE TITLE
In row observable array change doesn't cause rerender

### ISSUE THREAD

**Issue by Kiarash-Z** [mobxjs/mobx#1563]
Hi I have noticed a bug (maybe its for performance but in my case It's not good at all) in array observables which if you update  them in row only second change will cause rerender. I have a list of files(songs) and I want to reset them before I replace them with new ones. 
Example:

store.js:
```
class SomeStore {
  songs = [];
  
  updateList() {
    this.resetList();
    // only this will cause rerender and is sent to observer React component
    this.songs = ['new item', 'another new item']
  }
  resetList() {
    // this won't cause rerender because of this.updateList change in this.songs 
    this.songs = [];
  }
   constructor() {
      intercept(this, 'songs', change => {
        console.log(change.newValue); // first [] then ['new item', 'another new item'] which is right 
        return change;
      })
    }
}
```

Component.js:

```
class SomeComponent extends Component {
   render() {
       console.log(this.props.store); // only logs ['path', 'the second path'] and it doesn't log []
       return <SomeJSX>;
   }
}
```

I want to receive empty array in my component as well as second assignment to store.songs . I can even see that It's changing using `intercept` but It's not sent to my component. Any Idea? 🤔

**Comment by mweststrate** [comment]
Please provide a reproduction in code sandbox. The code below is not even
syntactically valid, please put some more effort when filing an issue 😊

Op za 26 mei 2018 19:28 schreef Kiarash Zarinmehr <notifications@github.com

**Comment by Kiarash-Z** [comment]
[code sandbox](https://codesandbox.io/s/04x3m70z3v)

as you can see intercept logs both [] and ['3', '4] but the `console.log` inside component only logs ['3, '4']

**Comment by mattruby** [comment]
Please read about mobx actions. I think that will help you.

**Comment by Kiarash-Z** [comment]
@mattruby Can you explain more specifically please? we have something like `setState` chain in React for such a thing and `setState`'s are async. the code below is working in React and it causes **2** rerenders
```
    this.setState({
      list: []
    }, () => {
      this.setState({
        list: ['3', '4']
      })
    })
```

**Comment by urugator** [comment]
Without action, this:
```javascript
this.songs = [];
this.songs = ["3", "4"];
```  
actually translates to:
```javascript
this.forceUpdate();
this.forceUpdate();
```
which works the same way as: 
```javascript
this.setState({
  songs: [],
})
this.setState({
  songs: ["3", "4"],
})
``` 
The thing is, if you call multiple `setState/forceUpdate` synchronously inside event listener (onClick), the react batches these calls into one (it's not done by Mobx!)

You can use `componentDidUpdate` (which is recommended over the `setState` callback anyway), or you can defer the second call:
```
this.songs = [];
setTimeout(() => {
  this.songs = ["3", "4"];
}, 0);
```
However I wonder why you want to do this...

**Comment by Kiarash-Z** [comment]
@urugator Thanks your solution's working 👍  and `Promises` are much better than `setTimeouts` to send second assignment to _queue_. Actually I'm building a music player [https://github.com/Kiarash-Z/music-player](which you can see here) and I have some classes and animations for each song in the player the problem is when user opens some local files and then wants to reopen some same files, list doesn't get empty and it somehow caches and causes some bugs in my DOM.

**Comment by urugator** [comment]
If you're dealing with CSS animations not being used, then defering the call won't always work, because browser batches DOM mutations as well (when peformed quickly enought). You would have to use this trick:
```javascript
this.songs = [];
window.requestAnimationFrame(() => {
   window.requestAnimationFrame(() => {
      this.songs = ["3", "4"];
   }))
})  
```
Both `requestAnimationFrame` are required to ensure at least one DOM redraw, before the second call is performed.
