### ISSUE TITLE
initial state of an observable

### ISSUE THREAD

**Issue by rickmed** [mobxjs/mobx#157]
I'm trying to keep the initial state of an observable. I tried it like this.

```javascript
const initState = { props }

const state = observable(Object.assign({}, initState)

// later on to get back to initial state
extendObservable(state, initState)
```

the problem is that observable() modifies the initiState props to be observable too.
I looked at createTransformer but seems like an overkill.
Any other way to do that?
 Thanks!

**Comment by mweststrate** [comment]
I tried your example, but it seems to work as expected, so I guess I don't understand the question correctly ;-). Can you verify these outputs?

https://tonicdev.com/56e321978216cb1200681660/56e321978216cb1200681661

**Comment by rickmed** [comment]
So I did a little experimenting, it seems that with an object 1 level deep it works as expected, but not with an object 2 levels deep
https://tonicdev.com/56e3253706dc8215007ba92c/mobxtest

PS: tonicdev.com looks cool

**Comment by mweststrate** [comment]
Ah, yes observability will recurse by default on plain objects. Use modifiers like `asFlat` to change that. Not sure about your case, but shouldn't you just deepclone it? `JSON.parse(JSON.stringify(initialState))` might be a simple fix :)

**Comment by rickmed** [comment]
Thanks! That fixed it. Now I'm trying to get state to go to initState, I tried extendObservable(state, initState) but (obviously?) it won't work bc for the observers to be notified you need to mutate the properties on a property by property basis so I would need to diff the objects and set the new values all the observers get notified...Is there a helper for something like that in mobx?

**Comment by mweststrate** [comment]
extendObservable will update existing properties and thus observers should be notified. Can you elaborate on your case? Maybe you are passing subobjects of your state tree around without doing this from an autorun?

**Comment by rickmed** [comment]
I had an error on my part. I'm using react stateless components (reactive with observer) and passing sub objects around. I'm developing a pattern for 100% reusable components but when composing a higher order component I was using the same object reference of the model's subcomponents. The solution was to JSON.parse(JSON.stringify(composedModel))
Thanks!

**Comment by evoyy** [comment]
The way I do this is to assign the model to a new object. You can't use const for this, you must you let.

````javascript
let state = observable(Object.assign({}, initState)

// reset
state = { };
extendObservable(state, initState);
````

**Comment by rickmed** [comment]
@mweststrate I experimented with mobx.toJSON(obj, false) at it seems to have the same as  JSON.parse(JSON.stringify(obj)), does it seem right?
