### ISSUE TITLE
Create derived (computed) values inside observable objects.

### ISSUE THREAD

**Issue by CharlieIGG** [mobxjs/mobx#1572]
Hi! 

I'm trying to avoid creating `autorun` or `reaction` methods to alter properties that should be observable. I'm however bumping into a problem when I want to derive the value of a nested object, for instance:

```javascript
class Rectangle {
    @observable measurements = {
          width: 2,
          height: 4,
          area: computed(( ) => { return (this.measurements.width.get()*this.measurements.height.get())})
    }
}
```

which throws the following error on runtime: `Passing a 'computed' as initial property value is no longer supported by extendObservable. Use a getter or decorator instead.`.

I cannot find or I do not seem to be able to understand any documentation regarding this use case...

In this example it might make sense to flatten out the properties, but in my real use case that's not an option.

Is this even possible?

if so, how should this use case be correctly implemented?

**Comment by urugator** [comment]
As suggested by error use getter (getters are converted to computed):
```javascript
@observable measurements = {
          width: 2,
          height: 4,
          get area() { return (this.measurements.width.get()*this.measurements.height.get()); }
}
```
If you really want standalone computed object (not a getter, but boxed), then you have to assign that computed later (in constructor).

**Comment by CharlieIGG** [comment]
Thank you @urugator , this works perfectly for me IF the `.get()` is remove from the returned computation. I got the idea of using that from other examples in the documentation... I probably misinterpreted that. Can you confirm it is OK just doing this the following way (Adapting your snippet)?

 ```
@observable measurements = {
          width: 2,
          height: 4,
          get area() { return (this.width*this.height); }
}
```
Also I didn't know getters could be used like this in JS. Apparently this is exclusive to EC6 and up?

Anyway, thanks a lot @urugator you rock!

**Comment by urugator** [comment]
No it's ES5. You adopted it correctly, I copy pasted your snippet and forgot to adjust the return statement, I will fix it for other potential readers.
