### ISSUE TITLE
autorun fails to execute when modifying an observable with extendObservable

### ISSUE THREAD

**Issue by HandEyeProtege** [mobxjs/mobx#158]
Apologies if this is fixed in a recent version; I haven't started using 2.0+ yet.  Here's a simple code fragment that demonstrates the problem:

```
var myObservable = observable({ foo: 1 });
autorun(() => {
    for (var key in myObservable) {
        console.log(key);
    }
});
extendObservable(myObservable, { bar: 2 });
```

I would expect the addition of a property to trigger the autorun to execute again, but it doesn't.  The output is just:

```
foo
```

**Comment by mattruby** [comment]
Try the map feature.

**Comment by rickmed** [comment]
seems to work in the last version

https://tonicdev.com/56e3253706dc8215007ba92c/mobx1

**Comment by mweststrate** [comment]
@mattruby @HandEyeProtege, indeed, for dynamically keyed objects [map](http://mobxjs.github.io/mobx/refguide/map.html) should be used (or you could also maintain your own `keys` collection).

**Comment by HandEyeProtege** [comment]
I do know about ObservableMap, but in this case the use of extendObservable is intentional.  This isn't a dynamically keyed object; what I am looking to do is effectively to lazy initialize some members of my state object.  My state has a number of well-known properties, it's just that in order to have a smaller initial download and faster startup some of them aren't initialized until later.

One reasonable fix would be to initialize all these properties to null so that they'll be picked up when I first make the object observable.  However, it seems like this _should_ work for extendObservable so I thought it was worth opening an issue.

**Comment by evoyy** [comment]
@HandEyeProtege I do the same thing as you with my state object. And I make some properties observable, others not. Initializing all properties to null is how I handle this.

**Comment by mweststrate** [comment]
@HandEyeProtege @evoyy Yep, initializing as `null` (or `undefined`) is they way to go here. But thanks for reporting nonetheless! Currently this behavior cannot be improved due to the limitations of `defineProperty`, once ES6 proxies are general available (not supported on safari yet) this could be changed though.
