### ISSUE TITLE
5.0.0 => 5.0.1 problem

### ISSUE THREAD

**Issue by dooboolab** [mobxjs/mobx#1585]
I recently faced problem upgrading mobx `5.0.0` to `5.0.1`.
<img width="443" alt="screen shot 2018-06-11 at 6 21 07 pm" src="https://user-images.githubusercontent.com/27461460/41223476-de2f06ea-6da4-11e8-8428-73e8b28cfe18.png">

I've added `Observer` component in `ListHeader` component in `FlatList` so that `ListHeader` component will re-render when `mobx` state changes.

However, it no longer works when I updated mobx `5.0.0` to `5.0.1` and I've tried re-installing them several times alternatively to confirm myself. I've seen the changes in `commits` but no idea why this is happening currently.

Above solution was known [solution](https://stackoverflow.com/questions/45681276/react-component-does-not-react-to-mobx-observable-data?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) to update child component in `FlatList`.

any idea?

**Comment by mweststrate** [comment]
Confirmed, the master build has tripped over the latest changes, something
seems to have broken with the bundling

Op ma 11 jun. 2018 om 11:30 schreef Hyo Chan Jang <notifications@github.com

**Comment by mweststrate** [comment]
Version 5.0.2 should fix this
