### ISSUE TITLE
Update property on a class instance.

### ISSUE THREAD

**Issue by marcfallows** [mobxjs/mobx#1586]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

***

Tried the Gitter, but my question was missed I think.

I have a class which has an observer as an instance property, and currently I have a reaction which sets that property. This seems like a job more suited to computed, but doesn't seem possible anymore

Currently:
```
class ReusableStore {
  @mobx.observable.deep items: Item[] = [];

  // ... a bunch of @computeds driven from this.items.
}

const specificStore = new ReusableStore();

mobx.reaction(
  () => {
    // compute items from other observables
    return items;
  },
  items => specificStore.items = items,
);
```

What I'd really like is something like:

```
mobx.extendObservable(specificStore, {
  get items() { // function which computes items },
});
```

But that's no longer possible in mobx because items already exists on `specificStore`.

The computed can't exist on the `ReusableStore` class because I don't want `ReusableStore` to have to gain a dependency on the dependencies of the `computed` as the class is used elsewhere without the items being driven in a similar fashion.

**Comment by mweststrate** [comment]
I think a simple workaround is to introduce a  getter on your superclass, and have that redirect to either the computed or observable prop in a subclass.

(On a side note I think redefining class fields in inheritance is a code smell and often signals a design issue. Redefining often breaks the contract. In this example, in your superclass items is writeable, but in your subclass isn't it, which is not sound type-wise)

**Comment by mayorovp** [comment]
Try this:

```typescript
class ReusableStore {
    @mobx.observable.ref itemsSource : Item[] = mobx.observable.array();

    get items() : Item[] { return this.itemsSource; }
    set items(values : Item[]) { 
        if (mobx.isObservableArray(this.itemsSource))
            this.itemsSource.replace(values);
        else
            this.itemsSource.set(values);
    }

    // ... a bunch of @computeds driven from this.items.
}

// ...

specificStore.itemsSource = mobx.computed(() => {
    // function which computes items
});

```
