### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by dooboolab** [mobxjs/mobx#1587]
Related to [issue](https://github.com/mobxjs/mobx/issues/1582). I am facing this issue again in android. ios is working fine.

![image](https://user-images.githubusercontent.com/27461460/41271074-67d674e2-6e49-11e8-8009-b2b10f09e762.png)

my mobx version is `5.0.2` and mobx-react is `5.2.3`. When I downgraded mobx to @4 it worked again.

**Comment by mweststrate** [comment]
This is mentioned in both the readme and changelog; MobX 5 is not supported by RN Android (unless you upgrade JSCore, links how to do that can be found there as well).

**Comment by MR03web** [comment]
"mobx": "3.6.2",
    "mobx-react": "4.4.3"

available version in my project

**Comment by mweststrate** [comment]
@MR03web great!

**Comment by yjb2020** [comment]
thx，down to mobx 3.6.2 ,It works ok ， @MR03web

**Comment by mweststrate** [comment]
Mobx 4 also doesn't require symbols, no need to go two majors back

Op wo 27 jun. 2018 14:09 schreef yjb2020 <notifications@github.com>:
