### ISSUE TITLE
How to access mobx administration in mobx 5?

### ISSUE THREAD

**Issue by manulitopetito** [mobxjs/mobx#1594]
I have a Question on the newly arrived mobx5:

1. [x] Question:I need to access the former $mobx administration object for being able to iterate over observables of a class.

In mobx 4 i used to be able to do it like this:
```
Object.values(this.$mobx.values)
      .map(observable => observable.value)
```

For mobx5 I got a little workaround, accessing the administration via the mobx administration symbol of the class:
https://codesandbox.io/s/v00q28559l

Unfortunately, it is much less convenient to access the administration this way.

What would be the easiest way to iterate over observables of a class?

**Comment by mweststrate** [comment]
use `getAdminstration()` (also available in 4).

(Your use case looks by the way something you can also achieve by using the
`values` api?)

Op vr 15 jun. 2018 om 14:50 schreef manulitopetito <notifications@github.com

**Comment by mweststrate** [comment]
See https://mobx.js.org/refguide/object-api.html,
`values(someObservableObject)` gives all the values of an observableobject

Op vr 15 jun. 2018 om 15:25 schreef manulitopetito <notifications@github.com

**Comment by mweststrate** [comment]
$mobx should not be needed in normal circumstances (nor getAdministration)

Op vr 15 jun. 2018 om 15:53 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by manulitopetito** [comment]
`entries`, `values` and `keys` is beautiful! 
Thanks, did not know about that :)
