### ISSUE TITLE
Observable array member's property becomes undefined (with Next.js project)

### ISSUE THREAD

**Issue by delgermurun** [mobxjs/mobx#1596]
I have a issue:
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

Hello,

I've face with very weird problem. I don't know whether it is Nextjs's or MobX's problem. I am sorry if it is Nextjs specific problem.

Observable array member's observable property becomes `undefined` on initialization.

Reproduction repo: https://github.com/delgermurun/mobx-next-issue
Similar code ([sandbox](https://codesandbox.io/s/0y13k12750)) with `create-react-app` works fine.

When you run project and go to http://localhost:3000, you don't see team's name on initial render. But it appears after 2 seconds. If you see `console`, team's name is `undefined`.

But team's name has been initialized before adding to observable array. It should be `tt-name` on initial render.

If you comment out [pages/index.js#L25-L26](https://github.com/delgermurun/mobx-next-issue/blob/master/pages/index.js#L25-L26) these lines it works fine.

Code is based on base [sandbox](https://codesandbox.io/s/v3v0my2370). `TimerView` doesn't observe `AppState`'s `timer`. If you comment out [pages/index.js#L6](https://github.com/delgermurun/mobx-next-issue/blob/master/pages/index.js#L6) and add `this.timer = 0;` this to `constructor`, it fixes this problem too.

BTW our project was working fine (with decorators). Problem occurred when I removed decorators.

Thanks a lot for great library, I really enjoyed using it.

**Comment by urugator** [comment]
Managed to isolate the problem
```javascript
const team = new Team({ name: "tt-name", _id: "tt-id" });
console.log("name:", team.name); // tt-name - ok
const teams = observable([team]);
console.log(teams[0] === team); // true - ok
console.log("name:", team.name); // undefined - messed up
```
Since the exact same piece of code works fine everywhere else (tried both mobx 4 and 5), I think it's either HMR (try to run it with NODE_ENV=production) or babel...

**Comment by delgermurun** [comment]
@urugator Thanks for checking out. tried with `NODE_ENV=production` and `next start` (production run command). Both doesn't help.

**Comment by urugator** [comment]
Could you try to set `loose` option to `true` for `class-properties` in `.babelrc`?
```javascript
{
  "presets": [
    ["next/babel", {      
      "class-properties": { loose: true }
    }]
  ],
  "plugins": []
}
```
You could also try to swap `plugin-proposal-class-properties` for `babel-plugin-transform-class-properties` (dunno if possible)

**Comment by delgermurun** [comment]
@urugator Tried above config doesn't work.

> You could also try to swap plugin-proposal-class-properties for babel-plugin-transform-class-properties
Haven't tried it

Thanks

**Comment by mattruby** [comment]
Not an expert on this one, but could your problem be related to how next
serializes your store? I thought they had something in their mobx example
docs related to serializing mobx maps and arrays.

**Comment by urugator** [comment]
@mattruby it seems to break immediately after putting `Team` instance into an observable array during SSR, so I quess that's before any serializaton could even occur? And supposedly it works with decorators and also when commenting out the class field initializers (haven't tried for myself) ...
Checked [the mobx example](https://github.com/zeit/next.js/blob/master/examples/with-mobx/.babelrc) and it uses [transform-class-properties](https://github.com/zeit/next.js/blob/master/examples/with-mobx/.babelrc), but is also uses mobx `2.*` so thats not very useful...

**Comment by delgermurun** [comment]
@mattruby Hi thanks for checking out.

My simple reproduction repo has SSR, but on actual code I am creating `mobx` store on client and server separately. So no serialization happening.

But as @urugator said observable array broken already on server side.

**Comment by ysabynin** [comment]
I'm having the same issue with next.js(8.0.3), mobx(5.13.0), mobx-react(6.1.1). Here is my .babelrc:
`
{
  presets: [["next/babel", {"class-properties": {loose: true}}], '@zeit/next-typescript/babel'],
  plugins: [
    ["@babel/plugin-proposal-decorators", {"legacy": true}]
  ]
}
`

Did anyone faced a problem with similar babel config?

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
