### ISSUE TITLE
mobx and listview in react native issue

### ISSUE THREAD

**Issue by Hypothesis-github** [mobxjs/mobx#1598]
I have a no output from this code 
```
componentWillMount() {
        const ds = new ListView.DataSource({

            rowHasChanged: (r1, r2) => r1 !== r2
        })
        
        this.dataSource = ds.cloneWithRows(this.props.store.data)
        console.log(this.props.store.data.toString() === ["1st" , "2nd" , '3rd' , '4th'].toString())
```
....
```
<ListView dataSource={this.dataSource}
                enableEmptySections={true}
                renderRow={(rowData) => { return <Text>{rowData}</Text> }}
```
where this.props.store.data is `@observable data = ["1st" , "2nd" , '3rd' , '4th']`

However when I replace this.props.store.data with ["1st" , "2nd" , '3rd' , '4th'] in `this.dataSource = ds.cloneWithRows(this.props.store.data)` I get the correct output.

I tested if the this.props.store.data is equal ["1st" , "2nd" , '3rd' , '4th'] and the result is true.

I am using 
"mobx": "^3.6.2",
"mobx-react": "^4.4.3",
"react": "16.3.1",
"react-native": "~0.55.2",

![mobx](https://user-images.githubusercontent.com/20628299/41596888-03ae19f0-73e1-11e8-8c78-e64caa512267.jpg)
the attached file shows the differences in log when the array is copied (bottom part ) and the time it is called from store ( top part ) .

**Comment by mrkhoros** [comment]
I found a way by adding `slice()` to  `this.dataSource = ds.cloneWithRows(this.props.store.data)` but I wonder if slice should also be used in other places too.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/484#issuecomment-391685354

**Comment by mweststrate** [comment]
Closing issue as answered, and also documented here: https://mobx.js.org/best/pitfalls.html#rendering-listviews-in-react-native
