### ISSUE TITLE
react throws key-warning when rendering observable JSX-content

### ISSUE THREAD

**Issue by misantronic** [mobxjs/mobx#1599]
Whenever I try to render observable JSX-content (which results in an observable array), react throws an error:

`Warning: Each child in an array or iterator should have a unique "key" prop.`

here is an example:
https://jsfiddle.net/n5u2wwjg/52218/

the issue is solved by giving all children a key - which might no be an elegant solution.

**Comment by mweststrate** [comment]
Don't use `observable` to store JSX data structures as it will make the JSX
elemetns themselve observable as well. Use observable.ref instead

Op di 19 jun. 2018 om 17:18 schreef David Skx <notifications@github.com>:

**Comment by misantronic** [comment]
works great, thank you!
