### ISSUE TITLE
state is null when api takes too long to respond

### ISSUE THREAD

**Issue by nzpopa** [mobxjs/mobx#1604]
The API I'm requesting is taking +60s to respond and I get the following error regarding to state:

```
@inject('userStore')
@observer
export default class UsersTable extends Component {
	@observable state = {
		column: null,
		data: this.props.userStore.users, // data which has to be fetched from server. Request is pending
		direction: null,
	}

	render() {
		const { column, direction } = this.state; // TypeError: Cannot read property 'column' of null. The error is displayed after 60s. 
...
}
```

Even if `this.state.column` is defined as `null`, I get that error while trying to access the `column` property.

I tried to validate against `this.state === null` and return null inside render(), but then the UI doesn't refresh when the data becomes available.

mobx: v4.2.0

**Comment by urugator** [comment]
You can't use react's `state` prop as observable.

**Comment by nzpopa** [comment]
@urugator thank you, it worked! But why do I get the error in a production environment, while locally I don't(the page renders correctly)?
