### ISSUE TITLE
computed can't invoke super in mobx3

### ISSUE THREAD

**Issue by nestharus** [mobxjs/mobx#1605]
```javascript
		class A {
			@computed get a() {
				return 5;
			}
		}

		class B extends A {
			@computed get a() {
				return super.a + 2;
			}
		}

		expect(new B().a).toBe(7);
```

Error: [mobx] Invariant failed: Cycle detected in computation B@1.a in 'function get() {
					return _get(B.prototype.__proto__ || Object.getPrototypeOf(B.prototype), 'a', this) + 2;
				}'

**Comment by spion** [comment]
Use methods for inheritance. Put the getter in the superclass only.

**Comment by nestharus** [comment]
Methods aren't going to have the same performance benefit as computeds. This is perfectly legal in javascript ; ).

**Comment by mweststrate** [comment]
If you invoke the method from the computed property (and only override the
method in the subclass), you will get exactly the same MobX computed prop
performance benefits

Op di 26 jun. 2018 om 13:51 schreef nestharus <notifications@github.com>:

**Comment by nestharus** [comment]
That was the workaround I was doing. I thought that the entire chain would recompute though whereas computed values would only partially recompute along the chain?

// return new computed
super.a; // return new computed
super.super.a; // return cache

vs

getA() // return new computed
super.getA() // return new computed
super.super.getA() // return new computed

get a() { return this.getA(); } // either recomputes the entire chain or caches the entire chain

**Comment by spion** [comment]
They will not be cached.

If you want partial computations to be cached along the way, you'll need to name them differently.

```javascript
		class A {
			@computed get a() { return this.getA(); }
            getA() { return 5; }
		}

		class B extends A {
            getA() { return this.superBa + 2; }
            @computed private get superBa() { return super.getA(); }
		}
```

**Comment by nestharus** [comment]
Ah true, that is one way to do it.

Why not just fix the mobx3 computed bug instead? : )

**Comment by urugator** [comment]
> Why not just fix the mobx3 computed bug instead

"Just" try to PR and you will find out :)
For start, try to think about what would be the best place to store memoized value of each computed on prototype chain...

> Infinitely more readable and easier to follow ^_^.

Perhaps there is even better solution that doesn't involve inheritance...

**Comment by nestharus** [comment]
Hmmm, urugator, perhaps.

Currently using it for a store that has 1 live set of data and a bunch of cold sets of data that can be swapped in/out. The data is selected by some parent store that contains the child. The parent defines a sort of composite key selection criteria (object) that is used to fetch cold data and swap it with the liva data. When there is no cold data, the endpoint backing that data is fetched instead and thrown into live data. The arguments for fetch are based on an endpointArguments property. This is built by merging the selection criteria down the chain from the parent to the child. The child also has the option of adding additional information that may be required. This store inherits from the base-store, which automatically builds this object. I called super to build the object and then merged my own additional criteria into it and returned it. This is what prompted the invariant from mobx. Please let me know if there is a more natural way of doing this : ).

**Comment by mweststrate** [comment]
Because it was a bug in 3, just giving problems in different areas, and the
behavior cannot be made consistent across transpilers. Conceptually this
way of super doesn't make much sense either as a computed property is more
like a field (otherwise it couldn't cache) then a method on a prototype

Op wo 27 jun. 2018 18:29 schreef nestharus <notifications@github.com>:

**Comment by urugator** [comment]
@nestharus You should send some code ... would something like this be suitable?
```javascript
class BaseCriterion {
  constructor() {}
  get endpointArguments() {
    return {} 
  }
}

class TypeCriterion {
  @observable type;     

  constructor(wrappedCriterion) {
    this.wrappedCriterion = wrappedCriterion;             
  }
  
  @computed get endpointArguments() {
    return {
      ...this.wrappedCriterion.endpointArguments,
      type: this.type,
    }
  } 
}

class CategoryCriterion {
  @observable category;     

  constructor(wrappedCriterion) {
    this.wrappedCriterion = wrappedCriterion;             
  }
  
  @computed get endpointArguments() {
    return {
      ...this.wrappedCriterion.endpointArguments,
      category: this.category,
    }
  } 
}

class Data { // original Parent - manages data based on criterion
  @observable data = {};
  
  constructor(criterion) {
    this.criterion = criterion;    
  }
  refetch() {
    xhr.post(url, this.criterion.endpointArguments);
  }
}

class SpecificStore { // originally subclass
  constructor() {
    // compose criterions nad expose them as required
    const baseCriterion = new BaseCriterion()
    this.typeCriterion = new TypeCriterion(baseCriterion); 
    this.categoryCriterion = new CategoryCriterion(typeCriterion);
    // create data
    this.data = new Data(this.categoryCriterion);    
  }
}

const store = new SpecificStore();
store.typeCriterion.type = "myType"; // use action in actual code  
store.categoryCriterion.category = "myCategory"; // use action in actual code  
```

**Comment by nestharus** [comment]
@urugator great idea, but unfortunately all of the computeds work with immutable objects : (.

**Comment by mweststrate** [comment]
Didn't read the entire discussions, but the answer to the original issue is a "won't fix", at least until the new decorators proposal is standardized and adopted by MobX.

**Comment by vilicvane** [comment]
@mweststrate as the new decorator adopted, can we revisit this issue?
