### ISSUE TITLE
toJS function use ES6 Map on 4.x, can't run on some ES5 browser

### ISSUE THREAD

**Issue by XiaominnHoo** [mobxjs/mobx#1609]
Hi, 
    I came across a problem that I use toJS in my code, and can't run on some browser on Android 4.4.
 I found that ES6 Map is used in toJS function, while I didn't use any Map polyfill in my project. Also Typescript does nothing to Map. So it seems 

> MobX 4 runs on any ES5 browser

is wrong or it is my misunderstanding :)

Add [es6-shim](https://github.com/paulmillr/es6-shim) solved my problem.

**Comment by loatheb** [comment]
I think mobx@4 need ES6 `Map` globally, you can see [CHANGELOG](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md) for much detail.
<img width="957" alt="2018-06-27 5 31 22" src="https://user-images.githubusercontent.com/18140164/41965828-225035b4-7a30-11e8-9939-9f741559480e.png">

**Comment by XiaominnHoo** [comment]
Thanks for your reply.
