### ISSUE TITLE
use toJS  In strict mode error

### ISSUE THREAD

**Issue by zhanshuyou** [mobxjs/mobx#1610]
Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: keys(ObservableObject@6)

**Comment by mweststrate** [comment]
Can you create a minimal reproduction?

Op wo 27 jun. 2018 12:15 schreef Shuyoou <notifications@github.com>:
