### ISSUE TITLE
Variable in mobx store

### ISSUE THREAD

**Issue by markolofsen** [mobxjs/mobx#1614]
How to change value of the variable in mobx store only for client-mode?

1. Install repo https://github.com/markolofsen/nextjs-toolkit
2. Open http://localhost:3000/
3. Check Firebug console

**Code below change store for session of the all customers.**
```
componentDidMount() {
    store.isTest = 'welcome new'
    console.log(store.isTest)
}
```

**Comment by yordis** [comment]
@markolofsen this is unrelated to Mobx itself but, this is a solution you could do.

Probably create some helper function with these functions.

```jsx
const noop = () => undefined

const isSSR = () => {
  // Check this other solution which I am not sure of.
  // return !process.browser
  return (typeof window !== 'undefined' && window.document) ? false : true;
};

const onSSR = (onServerCallback, onClientCallback = noop) => {
  return isSSR() ? onServerCallback() : onClientCallback();
};

componentDidMount() {
  onSSR(()=> {
    store.isTest = 'welcome new'
  });
  console.log(store.isTest)
}
```

**Comment by markolofsen** [comment]
@yordis Thanks!
