### ISSUE TITLE
Idea. Scoped strict mode, aka pure functions

### ISSUE THREAD

**Issue by zubivan** [mobxjs/mobx#1616]
I have an idea:
* What problem would it solve for you?
MobX comes with a built-in `strict mode` that prevents state modification from outside of code blocks explicitly marked as actions. It's a nice feature, but introducing it across the whole codebase of any project of decent size usually requires quite a big refactoring. Thus I'm thinking to introduce a concept of `pure` functions solving several problems:
   - allowing a step by step transition into the strict mode by marking code blocks as pure one at a time
   - making tracing code that modified your state easier, aka "aha, this block is `pure` so probably it's not coming from here.."
   - preventing accidental introduction of side effects in your code
* Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)? I think it can live in a core package side by side with the strict mode.
* Are you willing to (attempt) a PR yourself? Yes

From API perspective I was thinking of something like that:

``` typescript
class Person {
    @observable name = "John"
    @observable surname = "Doe"
    
    @pure
    functionWithSideEffects(value: string) {
        this.name = value;
    }

    @pure
    @computed
    get getterWithoutSideEffects() {
        return `${this.name} ${this.surname}`
    }

    // should throw
    @pure
    @computed
    get getterWithSideEffects() {
        if (!this.surname) {
            this.surname = "Unknown"
        }
        return `${this.name} ${this.surname}`
    }

    @pure
    calculateSomeValue<T>(): T {
            // ...
    }

    // ... etc
}

const person = new Person();

person.changeName("Jim") // should throw
person.getterWithoutSideEffects // should not throw
person getterWithSideEffects  // should throw
```

``` typescript
@pure
function add(left: number, right: number): number {
     return left + right
}
```

Let me know if this is something you guys think worth having in MobX. I'm willing to try a PR if community or @mweststrate is up for it.

**Comment by benmccormick** [comment]
> allowing a step by step transition into the strict mode by marking code blocks as pure one at a time

Can you lay out what you think this would look like, and how a full transition from non-strict mode to strict mode would occur?  What would be the states of the code base on the way from "wild west" to "strict mode"

As an example of what I'm trying to get at, could you explain how this would be better than say a "class-level" strict mode, where you enforce updating through actions for a specific class?


Also things like this might be unexpected:

```javascript
let sums = [];
@pure
function add(left: number, right: number): number {
    let sum =  left + right;
    sums.push(sum);
    return sum;
}
```

IE pure functions only guarantee purity with regards to mobx tracked objects/properties.

**Comment by KnisterPeter** [comment]
I would argue to not name it pure. This is associated with functional programming and means side effect free.

**Comment by urugator** [comment]
The idea behind `strict mode` is to not forget `action`, so that your code accidentaly doesn't run outside of transaction (possibly causing excessive re-rendering).
Introduction of `pure` won't change anything about it, because as opposed to `action`, missing `pure` is undetectable and you still need `action` so that Mobx knows when to flush.
In a way "scoped strict mode" is contradiction in terms, because strict mode is about not forgetting to apply the *scope* (action)...

> preventing accidental introduction of side effects in your code

Unless you accidentally forget to apply `@pure`...

> "aha, this block is pure so probably it's not coming from here.."

Not sure "purity" is actually a strong indicator of anything, because even pure function can modify observables:

```javascript
@pure
@computed get something() {
  const something = new Something();
  observable.observableProp1 = 1;
  observable.observableProp2 = 2;
  return something; 
}
```
Which gets us to another problem, that we can't reliably ensure purity, because we can throw only on observed things similary to strict mode, therefore:
```javascript
const box = observable.box(1);

@pure
@computed get unpure() {
  box.set(2); // doesn't throw unless box is observed by something 
}
```

**Comment by mweststrate** [comment]
Agree with @urugator, I don't `@pure` will add that much to value to justify the added complexity. For migration, I would probably make more sense to
1. only apply strict mode in DEV mode
2. optionally change the error to a warning with (an additional) configuration

**Comment by mweststrate** [comment]
Closing for now, I don't think we need this very badly
