### ISSUE TITLE
Do reactions automatically get cleaned up when an observable is not longer present?

### ISSUE THREAD

**Issue by ManuSevenval** [mobxjs/mobx#1617]
I have a...
* [x] Question
* [x] Did you check this issue wasn't filed before?

Hi!

I am wondering if mobx / GC automatically dispose reactions and observers on observables, that have been dereferenced, or if I have to make sure that their dispose methods get called and thereby release unused memory by myself.

I tried to illustrate the case with the following example:
https://codesandbox.io/s/94zmr52l9w

How could I check, if the reaction is still registered within mobx's tracking cycle?

Thanks!

**Comment by mweststrate** [comment]
Reactions returns a disposer function that can be used to stop the
observation and thus enable GC. Otherwise, the engine can only GC a
reaction if *all* things on which the reaction depends can be GC-ed as
well. Something I wouldn't rely on too much :)

Op vr 29 jun. 2018 om 13:15 schreef ManuSevenval <notifications@github.com>:

**Comment by ManuSevenval** [comment]
thanks for the quick response!
just out of curiosity:

> Otherwise, the engine can only GC a
reaction if *all* things on which the reaction depends can be GC-ed as
well. 

in my particular example the reaction looks like this:

```
reaction(
      () => this.isHungry,
      () => document.getElementById('root').innerHTML = "FEED WALTER!!",
    )
```

would the GC keep the reaction alive because `#root` is still present? Or would it be clever enough to notice, that the class instance was killed and collect the reaction anyways?

**Comment by mweststrate** [comment]
it will be alive as long as `this.isHungry` is alive. In this case it is
easy to oversee the impact, bug in general I recommend to be a good citizen
and clean up any subscriptions you make. Like you would do in Rx for example

Op vr 29 jun. 2018 om 16:40 schreef ManuSevenval <notifications@github.com>:

**Comment by ManuSevenval** [comment]
alright, thanks! :+1: :+1:
