### ISSUE TITLE
[question] How to 'clean' memory usage

### ISSUE THREAD

**Issue by designalchemy** [mobxjs/mobx#1622]
Hello,

I have an application that is turned on 24/7 and shows sporting data, one race at a time, looping over say 70 results

Running into a problem with it consuming too much memory 

here are some screenshots to highlight the issue:

![screen shot 2018-07-02 at 12 32 02](https://user-images.githubusercontent.com/11962756/42162200-b50c6aa8-7df5-11e8-9617-6fbe4595e901.png)

The retained size here is just increasing and increasing on each snapshot

![screen shot 2018-07-02 at 12 47 03](https://user-images.githubusercontent.com/11962756/42162296-0a3cbc9e-7df6-11e8-9add-460a5847e695.png)

This function above is called every say 1-2 minutes to change the currently displayed data on the page

Is there anyway I can force it to remove its old references?

or am i updating my state in the wrong way?

Thanks a lot

**Comment by designalchemy** [comment]
Update:

I found a found 'reactions' i wasn't disposing of, this seems to have helped a lot, will confirm after a few hours

**Comment by mweststrate** [comment]
Yes, always clean up reactions :)

Op ma 2 jul. 2018 om 14:32 schreef Luke <notifications@github.com>:

**Comment by designalchemy** [comment]
Yep thanks my bad !
