### ISSUE TITLE
Inspecting a computed property in spy event will throw an exception.

### ISSUE THREAD

**Issue by AoDev** [mobxjs/mobx#1623]
* mobx version: `mobx@4.3.1`

I am trying to log computed properties value in a spy event.
But this throws an exception.

```
Encountered an uncaught exception that was thrown by a reaction
or observer component, in: 'Reaction[Autorun@3]
RangeError: Maximum call stack size exceeded

Reaction doesn't converge to a stable state after 100 iterations.
Probably there is a cycle in the reactive function: Reaction[Autorun@3]
```

I have created a repo to reproduce the error:
https://github.com/AoDev/mobx-spy-computed-exception

At first glance it seems that an endless loop occurs:
* *reaction* -> *spy event* -> *reaction* -> *spy event* -> ...

**Comment by mweststrate** [comment]
```
that makes sens that it loops, in pseudo code you are doing:
get fullName() {
   emitSpyEvent()
   return computeSomething
}
```
and then attach a handler `onSpy(() => x.fullname)`.
your spy event will compute fullname again, triggering a spy event etc.
maybe a flag should be kept that a spy handler is already running or something like that

**Comment by mweststrate** [comment]
Closing for now, to much of an edge case. But if more people run into this, it could be re-opened and fixed
