### ISSUE TITLE
Interest in removing custom Iterator interface in Flow types?

### ISSUE THREAD

**Issue by adunham-stripe** [mobxjs/mobx#1624]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

MobX currently defines a [custom Iterator interface](https://github.com/mobxjs/mobx/blob/master/flow-typed/mobx.js#L263-L268) that is used for stuff like `ObservableMap.keys()`, etc.  This conflicts with the built-in [Flow `Iterator` interface](https://github.com/facebook/flow/blob/master/lib/core.js#L488-L492), and, in particular, is missing Flow's current `@@iterator` hack to recognize iterators. This essentially means that you can't use `Array.from` or similar methods with MobX types, since Flow doesn't recognize them as iterators.

I've tested just removing the `Iterator` interface from the Flow definitions in MobX, and everything seems to work fine, but I'd like to gauge others' interest before submitting a PR that does this.

**Comment by mweststrate** [comment]
Implemented, will be part of next release
