### ISSUE TITLE
MobX 4.x crashes on Internet Explorer 11 when calling an @action before first react rendering cycle happened.

### ISSUE THREAD

**Issue by RPDeshaies** [mobxjs/mobx#1626]
I have a:

2. [x] Issue: 

When loading an application using React and MobX4 and calling an `@action` before react finishes it's first rendering cycle, internet explorer 11 throw the following exception

```
XMLHttpRequest: Network Error 0x80004004, Operation aborted
```
I've passed 3 days trying to debug this issue, initialy thinking it was related to loading script from a different origin, https/ssl and maybe my code splitting.

I've finally been able to find that it was related to MobX changing the state before React was finished rendering.

Right now, I can fix the issue by doing a `setTimeout(()=>{ this.myActionMethod (), 0}` to fake a first rendering cycle, but you will understand that it's ugly and useless.

This also seems to only hapenned on my production build, which I still don't understand why...

  * [x] **Provide error messages including stacktrace**
```
{code: 0, msg: "", Symbol(isForcingUpdate)_x.5rdccuaah5f: undefined, Symbol(props atom holder)_13.5rdccuaah5: undefined, Symbol(props atom holder)_17.5rdccuaah5: undefined, Symbol(props atom holder)_1b.5rdccuaah5: undefined, Symbol(props atom holder)_1f.5rdccuaah5: undefined, Symbol(props atom holder)_1j.5rdccuaah5
   ```
   }

**Which seems to be coming from [here](https://github.com/mobxjs/mobx-react/pull/436/files#diff-08f3e9ab539253c87ea111cc61c69e29L25)

  * [] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
    **I'll work on it, I just don't want to loose the stack trace**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
    **It NOT should crash on IE11** 
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
     **IE 11,  mobx 4.3.1, mobx react 5.2.3**

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by RPDeshaies** [comment]
I tried to create a sandbox for you guys, but your app for sandbox doesn't support IE 11.

So that doesn't get us very far

**Comment by mweststrate** [comment]
Note that you can just download a sandbox and run it locally, so you could
use that to verify the bug first.

Op vr 6 jul. 2018 om 23:43 schreef RPDeshaies <notifications@github.com>:

**Comment by mweststrate** [comment]
Use the close button 😊

Op za 7 jul. 2018 17:26 schreef RPDeshaies <notifications@github.com>:
