### ISSUE TITLE
After doing a resetGlobalState, the objectCache for the createTransformer() isn't cleared...

### ISSUE THREAD

**Issue by kenotron** [mobxjs/mobx#163]
So in this case, some old objectCache[someReusedId] could be used and it would then make the createTransformer return an old memoized thing even after resetGlobalState.

This is bad for test cases that could potentially throw

**Comment by kenotron** [comment]
I think if you're going create a cache for the createTransform, maybe you should place that inside the "globalState."

**Comment by mweststrate** [comment]
Released as part of 2.1.0 last week.
