### ISSUE TITLE
Suggestion: configure comparer.default

### ISSUE THREAD

**Issue by damonmaria** [mobxjs/mobx#1633]
# Idea

Have the ability to override `comparer.default` that mobx uses internally. 

## What problem would it solve for you?

I often have to deal with `Date`s being returned from computed properties. By default even if the same date value is returned it's a new object and so all observers have to update. As such I'm regularly using this code:

```js
import datesEqual from 'date-fns/is_equal'

decorate(VisitsStore, {
  day: computed({ equals: datesEqual }),
  ...
})
```

I would like to be able to instead not have to remember to add this every time the result of a computed happens to be a `Date`. And instead replace `comparer.default` with my own implementation that treats `Date`s as equal, probably through `configure()`. As `Date`s are technically mutable this shouldn't be the default for everyone.

## Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?

I imagine this would help others as it would also solve issue #1561.

I don't think it can be in mobx-utils, although mobx-utils could contain other 'common' comparers that could be used to replace the default. 

## Are you willing to (attempt) a PR yourself?

Honestly, I probably won't have the time.

**Comment by kuitos** [comment]
I think you could write a wrapped function to do that, but not changing the mobx default behavior
```ts
const dateComputed = computed({ equals: datesEqual })

decorate(VisitsStore, {
  day: dateComputed,
  ...
})

```

**Comment by nunocastromartins** [comment]
This doesn't solve your issue, but just as an FYI, in case you don't know, `comparer.structural` also compares dates properly. Might be relevant for you in case you're comparing complex structures with dates within.

> As Dates are technically mutable this shouldn't be the default for everyone.

I disagree with you in that it shouldn't be the default. Dates are technically objects and, like other objects, they are (and in my opinion should be), **by default**, compared by reference. However, I wouldn't argue against having the default comparator be configurable.

**Comment by mweststrate** [comment]
Closing, as good work arounds are suggested and changing the default behavior is not applicable without making assumptions (it would be _awesome_ if dates were immutable in JS....)
