### ISSUE TITLE
Store should be immutable

### ISSUE THREAD

**Issue by nir2002** [mobxjs/mobx#1639]
I recently encountered a problem by a programming mistake which I believe we can protect others from redoing.

I set up an action in my store which purpose was to set a store value.

Then, after I injected the store to my (React) component i was using the action as an assignment instead of a function: ("store.action = value;" insted of -> "store.action(value)")

That cause the action to change from function to the value and be no longer valid as an action.

I think we can use the configuration object of mobx and set the store to immutable to prevent issues like that from happening.
This can go hand by hand with the "enforceActions" configurations.

**Comment by mweststrate** [comment]
This was originally the case but has been removed as it makes testing /
stubbing hard

Op do 12 jul. 2018 18:33 schreef Nir Parisian <notifications@github.com>:

**Comment by nir2002** [comment]
got it, thanks!
