### ISSUE TITLE
[Need help] Can I use mobx for check dirty form?

### ISSUE THREAD

**Issue by louisnguyen1012** [mobxjs/mobx#164]
First thing, thank you so much for the nice library!

As mentioned on title, is there any way the Mobx can help us detect dirty form?

Thanks,

**Comment by mweststrate** [comment]
Can you elaborate a bit on your question? Do you have an example of what you mean by a dirty form? Input validation?

**Comment by louisnguyen1012** [comment]
Hi,

I have a page with some input controls, use the mobx to observer and update them when onChange event occurs . Also on this page I have Cancel button, when user clicks on it, the system should know and confirm with user when there are some changed.

**Comment by mweststrate** [comment]
Hi,

I think in these cases it is best practice (both with and without MobX) to do not update the state directly while the form is active, but only when the input is confirmed by the user. Dirty checking is then simply comparing your state values with the current values in the form. So you get something like the following example, which modifies the name of a person. (in this example I use observable properties on the component, but you could achieve the same with React's own `getState`):

```javascript

class ChangeNameForm extends React.Component {
  @observable nameInputValue;
  @computed get isDirty() {
    return this.props.person.name !== this.nameInputValue;
  }

  getInitialState() {
    this.nameInputValue = this.props.person.name;
  }

  render() {
    <div>
     <input value={this.nameInputValue} onChange={this.onChangeHandler} />
     <button onClick={this.confirm} enabled={this.isDirty}>Ok</button>
     <button onClick={this.cancel}>Cancel</button>
    <div>
  }

  onChangeHandler = (e) => this.nameInputValue = e.target.value;

  confirm = () => {
    this.person.name = this.nameInputValue;
    this.close();
  }

  cancel = () => {
    if (this.isDirty) {
       // ask confirmation
    } else {
       this.close();
    }
  }
}
```

**Comment by louisnguyen1012** [comment]
Yes, thank you for your answer!

I think this way first, but as source code tells - we code manually to check.
And the second think, take snapshot of store and compare it with current value - but it takes a lot of time for comparing.

**Comment by mweststrate** [comment]
Not sure whether this issue is solved now or not, feel free to re-open it if it isn't :)
