### ISSUE TITLE
observe is not triggered with 'removed' property

### ISSUE THREAD

**Issue by Hypothesis-github** [mobxjs/mobx#1641]
Welcome to MobX. Please provide as much relevant information as possible!
 
using version @ 5. 2. 3

While this code runs fine
```
  @computed
  get _error() {
    observe(this.data, change => {
      console.log(change);
      if (change.added) {
        runInAction(() => {
          this.error = `something is wrong`;
        });
      }
    });
    return this.error;
  }
```
by changing `change.added` to `change.removed` although I splice 2 from the existing data, the if statement fails to run meaning that nothing is detected as removed.
this is my data 
`@observable data = [1, 2, 3, 4];`
and this the splice trigger 
```

  @action
  _timeOut = () => {
    setTimeout(() => {
      this.data = this.data.slice(2);
    }, 1111);
  };

```
the code can be found at [Sandbox](https://codesandbox.io/s/xpwomnqwjw)

I would appreciate if you could also tell me using `computed `with `observe `is all that logical since I couldn't return a constant and had to return the `observable `

**Comment by urugator** [comment]
You're using `slice` not `splice`, so `this.data = this.data.slice(2);` only changes the property value not the observed array, use `.splice` or `.replace`.

> computed with observe is all that logical

No, computed shouldn't contain any side effects and it creates new `observer` anytime the computation runs.

**Comment by Hypothesis-github** [comment]
@urugator I am unable to get a return from `@computed` in the if statement tho, is my syntax wrong ?

**Comment by urugator** [comment]
```javascript
@computed
get _error() {
  observe(this.data, onChange);
  return this.error;
}
```

onChange is a callback, it's return value isn't even known during _error execution, onChange is executed when this.data changes, not during _error
