### ISSUE TITLE
Make trace work anywhere in mobx

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx#1642]
Right now debugging some stuff downstream from a reaction and I always find myself wanting a Mobx stack trace showing the reactions/computations/react render stack trace not the console.trace which doesn't say much.

If Mobx.trace() worked inside sub-function of reactions, etc, and showed a full Mobx stack trace of everything above, that would be the single biggest feature I could see being helpful for our team day-to-day and I'd happily sponsor the change.

**Comment by mweststrate** [comment]
If you pass in 'true' as argument it will pause the debugger and show the
derivation tree, is that what you are looking for?

Op wo 18 jul. 2018 17:06 schreef Nate Wienert <notifications@github.com>:

**Comment by natew** [comment]
I’ll give that a shot. Though having it just print would be useful as well.
It seems the default could do this without breaking anything as it would be
a superset of current functionality.

**Comment by ItamarShDev** [comment]
@mweststrate 
Would be happy to try to contribute this matter.
Is there any possible way to get some guidance?
my main concerns are: 
1. how can i locally test it (npm link?)
2. is there any source to point me out to the basic idea of the change needed (i guess in `trace.ts`)

Hope it's not too much of a request/

thanks!

**Comment by mweststrate** [comment]
Cool @ItamarShDev!

For the unit tests there is no need to link, that should work when just checking out. For a react project, `npm link` should work indeed, although in my experience it doesn't always :-P. But can't remember from top of my head what the issue was. 

No specific pointers, but `trace.ts` is a good place to start indeed :-)

**Comment by ItamarShDev** [comment]
thanks! will dive deep and try to learn the code.
Hope to submit a PR, but no promises yet :)

**Comment by FredyC** [comment]
I think there is no need to keep this open as there is not enough interest in it.
