### ISSUE TITLE
Mobx Observable map

### ISSUE THREAD

**Issue by ertejaspatel** [mobxjs/mobx#1648]
Hi 

Why Array.from(this.map.values()) returns an array like this rather than returning the actual array of objects which were set with the key in the map?

[Proxy]
   0:Proxy
   [[Handler]]:Object
   [[Target]]:Object
   [[IsRevoked]]:false
   length:1

**Comment by urugator** [comment]
https://mobx.js.org/refguide/map.html#-observable-map-values-deep-false

**Comment by mweststrate** [comment]
Answered, closing
