### ISSUE TITLE
Render function does not run on @observable change with computed func

### ISSUE THREAD

**Issue by ertejaspatel** [mobxjs/mobx#1649]
Hi 

I have an observable map with  a computed field

 @observable todoRegistry = new Map();

 @computed
  get todos() {
    return Array.from(this.todoRegistry.values());
  }

todosFromServer.forEach(todo => {
        this.todoRegistry.set(todo.id, todo);
});

this does not trigger computed todos to recalculate and my render function does not re-rendered.

I am using create-react-app with eject and have added decorator support. 

"dependencies": {
    "@coreui/coreui": "^2.0.2",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.2.0",
    "@coreui/icons": "0.2.0",
    "@coreui/react": "^2.0.4",
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "bootstrap": "^4.1.1",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "chart.js": "^2.7.2",
    "classnames": "^2.2.6",
    "core-js": "^2.5.7",
    "css-loader": "0.28.7",
    "custom-react-scripts": "^0.2.2",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "flag-icon-css": "^3.0.0",
    "font-awesome": "^4.7.0",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "mobx": "4.3.1",
    "mobx-react": "^5.2.3",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "prop-types": "^15.6.2",
    "raf": "3.4.0",
    "react": "^16.4.1",
    "react-chartjs-2": "^2.7.2",
    "react-dev-utils": "^5.0.1",
    "react-dom": "^16.4.1",
    "react-loadable": "^5.4.0",
    "react-router-config": "^1.0.0-beta.4",
    "react-router-dom": "^4.3.1",
    "react-test-renderer": "^16.4.1",
    "reactstrap": "^6.1.0",
    "resolve": "1.6.0",
    "simple-line-icons": "^2.4.1",
    "style-loader": "0.19.0",
    "superagent": "^3.8.3",
    "superagent-promise": "^1.1.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "devDependencies": {
    "babel-jest": "^23.0.1",
    "node-sass-chokidar": "^1.3.0",
    "npm-run-all": "^4.1.3"
  },

**Comment by ertejaspatel** [comment]
Found the issue -  the order of observer and inject matters
inject needs to come before observer in react component

**Comment by barbarosso** [comment]
@ertejaspatel perhaps you can close the issue yourself?
