### ISSUE TITLE
issue with reference to observable map

### ISSUE THREAD

**Issue by sivapolisetty** [mobxjs/mobx#1658]
Hi, 
Here is my sample code.
class ProfileDomainStore {
    @observable adminProfileDetails = observable.map();	
	constructor(){
		reaction(
			() => this.adminProfileDetails,
			(newValue) => {
				console.log("reaction in domain store", newValue.get('name'));
			});
    }
    updateAdminProfile(profileDetails)
    {
        this.adminProfileDetails = observable.map(profileDetails);
    }
}
class ProfileUIStore {
    @observable adminProfileDetails;
    constructor(){
        this.adminProfileDetails = ProfileDomainStore.adminProfileDetails;
        reaction(
            () => this.adminProfileDetails,
            (newValue) => {
                console.log("reaction in UI store", toJS(newValue));
            }
        );		
	}
}

I am have implemented logic two store Domain and UI store. React components would always observe UI store. 
Problem is the reaction in domain store working as expected. But adminProfileDetails In UI store  which refers to Domain store variable is not able to get observed.  Please provide insights on this.

**Comment by silversteez** [comment]
I believe its because you're setting the value of this.adminProfileDetails to a new map in updateAdminProfile method so the reference in ProfileUIStore is lost. You'll need to mutate your map instead if you want to keep maintain the reference in both places.

**Comment by mweststrate** [comment]
Closing as the issue is inactive, and answer seems provided
