### ISSUE TITLE
Invalid this reference in getter as observable properties

### ISSUE THREAD

**Issue by alxsavard** [mobxjs/mobx#1661]
I have a:

1. [x] Question

Hi everyone! I'm trying to set up an object which have computed properties. The idea is that I'll have a big 'error' object with complicated computed values in it and I don't want it to recompute completely every time either property change. This is why I was gonna use an observable with getters as properties as seen here: https://alexhisen.gitbooks.io/mobx-recipes/content/computed-properties-without-computed.html

Code looks something like this:
```
class Store {
  @observable email = 'some@email.com';
  @observable name = 'my name';

  @observable errors = {
    get email() { if (this.email === '') {return 'empty email'; } return null; },
    get name() { if (this.name === '') {return 'empty name'; } return null; }
  };
}


// Somewhere else in the code
<p>Errors are: ${store.errors.email}</p>
```

My problem is inside the getter `this.email` is always undefined. I'm thinking this is not referencing correctly but I can't figure out why!

Any ideas would be appreciated! Thanks

**Comment by urugator** [comment]
`this` refers to `errors` object not to `store` instance

**Comment by alxsavard** [comment]
Yeah I know, my question was how can can I fix it and have `this` pointing to what I want?

In the mean time, if I don't find a better solution I did something like that: (which I think is not that bad)
```
class Store {
  @observable email = 'some@email.com';
  @observable name = 'my name';
  @observable errors = new Errors(this);
}

@observer
class Errors {
  this.user = null;

  constructor(user) {
    this.user = user;
  }

  @computed get email() { if (this.email === '') {return 'empty email'; } return null; }
  @computed get name() { if (this.name === '') {return 'empty name'; } return null; }
}
```

**Comment by urugator** [comment]
If your intention was not to save keystrokes of writing `@computed` (as the linked gitbook could somehow suggest), then the solution you came up with is probably the preferable one. However the use of `observer` is wrong, only react components should be decorated with `@observer`.

Alternatively:
```javascript
@observable errors = {
  user: this,
  get email() { if (this.user.email === '') {return 'empty email'; } return null; },  
};
//---  
constructor() {
  const self = this;
  this.errors = {
    get email() { if (self.email === '') {return 'empty email'; } return null; },    
  }
}
```

**Comment by mweststrate** [comment]
Closing as question is answered
