### ISSUE TITLE
[Documentation] Incorrect fact in the Ten Minute Intro.

### ISSUE THREAD

**Issue by prometheansacrifice** [mobxjs/mobx#1664]
I have an:

Issue: The [Ten minute introduction to MobX](https://mobx.js.org/getting-started.html), under the section ***Making React reactive***, incorrectly states that React Components are not Reactive out of the box

> React components are (despite their name) not reactive out of the box.

I think this is factually incorrect. Maybe this needs to be re-worded?

Please try to understand this is with good intentions. The tutorial was a great intro to MobX - quick and to the point. I mean no harm and things like this can be sensitive. I felt it was necessary to report it.

**Comment by mweststrate** [comment]
PR to improve the wording is fine, but how React is reactive is unclear to me, as updating a component is an explicit, imperative command; `setState`?

**Comment by prometheansacrifice** [comment]
Well, yes. And while the docs admit to not making reactivity itself declarative like other FRP libraries, an imperative api like  `setState` is warranted in a language like JS, isn't it?

Since terms like Reactivity can be subjective, can you please explain how MobX's usage brings declarativeness? I'm fairly new to MobX and could be lacking here.

**Comment by hawkeyegold** [comment]
How about this:

> Despite their name, React components are something less than reactive out of the box.

**Comment by prometheansacrifice** [comment]
Appreciate your input. Could you please also help me understand in what way
MobX makes it more reactive?
