### ISSUE TITLE
Test failure in js-framework-benchmark

### ISSUE THREAD

**Issue by krausest** [mobxjs/mobx#1667]
I recently updated mobx to 5.0.3 / mobx-react 5.2.3 in the [js-framework-benchmark](https://github.com/krausest/js-framework-benchmark) and ran into what I think looks like a regression for very large tables.
I've files the bug here https://github.com/krausest/js-framework-benchmark/issues/427, but I'm not sure @mweststrate had a chance to take a look at it, so I decided to file the bug here as well.

How to reproduce:
`git clone https://github.com/krausest/js-framework-benchmark.git`
`cd js-framework-benchmark`
start the local web server on port 8080:
`npm install`
`npm start`
open a new terminal with js-framework-benchmark as current directory, then:
`cd frameworks/keyed/react-mobX/`
`npm install`
`npm run build-dev` 
open [http://localhost:8080/frameworks/keyed/react-mobX](http://localhost:8080/frameworks/keyed/react-mobX)

Now observe the following:
click create 1,000 rows then append 1,000 rows. There'll be 2,000 rows.
click create 10,000 rows then append 1,000 rows. There'll be only 1,000 rows (not 11,000 as expected). 
Similarly click create 1,000 and then click 10 times on 'append 1,000 rows'. As soon as there are more than 10,000 rows, the first 10,000 rows are removed  and only the appended 1,000 rows are rendered.
The same code works when I downgrade to mobx 3.3.1 / mobx-react 4.3.4.

**Comment by mweststrate** [comment]
Reproduced and fixed in 5.0.5
