### ISSUE TITLE
There are no Flow types for `comparer`.

### ISSUE THREAD

**Issue by dapetcu21** [mobxjs/mobx#1668]
I have an issue:
  * [x] Provide a **minimal** sample reproduction. 
    `import { comparer } from 'mobx'` errors out Flow with `there is no "comparer" export`.
  * [X] Did you check this issue wasn't filed before? Yes
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
    * MobX 4.1.0
    * Flow 0.74.0

**Comment by mweststrate** [comment]
PR is welcome.
