### ISSUE TITLE
Once I modify the second item, the first item also have modified,when I use observable.

### ISSUE THREAD

**Issue by linmodev** [mobxjs/mobx#1669]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question:  Once I modify the second item, the first item also have modified,when I use observable.
2. [ ] Issue: I can't describe this problem ,but I have a very simple example to reproduce it.
  * [ ] **https://stackblitz.com/edit/react-ryzsaj**
3. [ ] Idea:Why the twice console log is different?

**Comment by urugator** [comment]
Not exactly sure I understand the problem, but you're pushing the same "newMeta" object reference to the array, there is no cloning, so `this.newMeta === this.test[0] === this.test[1];`
Perhaps this is what you want to do:
```javascript
 testArr() {
    this.newMeta.uid = 0;
    this.test[0] = { ...this.newMeta };
  }
```
Mobx clones the object only when it's converted to observable, however `this.newMeta` is already an observable, therefore no conversion and therefore no cloning happens.

**Comment by linmodev** [comment]
@urugatorI  try this example again. I think you are right. Thank you for solving my problem.

**Comment by mweststrate** [comment]
@linmodev  Please make sure to close issues after accepted answer has been provided
