### ISSUE TITLE
toJS in ObservableArray not defined in IObservableArray

### ISSUE THREAD

**Issue by KimPeeters** [mobxjs/mobx#1670]
Hi,

This error:
`TS2339: Property 'toJS' does not exist on type 'IObservableArray<Car>'.`

is produced by the following code.
```PHP
import {observable} from "mobx";
class Car {
    constructor(public id: number) {}
}
class Garage {
    readonly cars = observable<Car>([])
}
const garage = new Garage();
garage.cars.push(new Car(10));
console.log(garage.cars.toJS());
```
The console log is working though, because toJS, exists on ObservableArray.

I also tried:
```PHP
import {observable} from "mobx";
class Car {
    constructor(public id: number) {}
}
class Garage {
    @observable cars: Car[] = [];
}
const garage = new Garage();
garage.cars.push(new Car(10));
console.log(garage.cars.toJS());
```
I don't prefer this way because garage.cars could be overritten and wouldn't be observable anymore. And this still produces the error `Property 'toJS' does not exist on type 'Car[]'.`

I need the toJS() because the array wil be serialized with mobx/serializr and putting a ObservableArray in serialize doesn't work that well.

Greetings, Kim

**Comment by urugator** [comment]
For the time being, note that `cars.slice()` or `[...cars]` or `Array.from(cars)` works the same way.

**Comment by KimPeeters** [comment]
Thx. Didn't think of that. Going to use that for now.
