### ISSUE TITLE
SyntaxError:  Using the export keyword between a decorator and a class is not allowed.

### ISSUE THREAD

**Issue by TheSixth** [mobxjs/mobx#1671]
I have a Issue.SyntaxError:  Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead
`
@observer

export default class ShopCar extends Component {
...
}
`

**Comment by kuitos** [comment]
check the babel plugin configuration

**Comment by mweststrate** [comment]
Or just move the decorator as suggested. The final syntax is still under
debate at TC 39

Op do 9 aug. 2018 11:32 schreef Kuitos <notifications@github.com>:

**Comment by mweststrate** [comment]
Duplicate of https://github.com/mobxjs/mobx-react/issues/528
