### ISSUE TITLE
Documentation typo for mobx 4

### ISSUE THREAD

**Issue by domehead100** [mobxjs/mobx#1674]
In README.md:

MobX 4 vs MobX 5
...
The difference between MobX 4 and MobX 5 is that the latter uses Proxies to do property tracking. 
...
The most noteable limitations of MobX 4:
  * Adding properties to existing observable objects after creation is automatically picked up. 

That last line should end with "is _not_ automatically picked up."

**Comment by mweststrate** [comment]
Docs have been updated

**Comment by domehead100** [comment]
In cases like this, would you prefer a small PR?

**Comment by mweststrate** [comment]
Definitely :)

Op di 14 aug. 2018 om 17:05 schreef Michael Stephenson <
notifications@github.com>:
