### ISSUE TITLE
Array of non-plain objects don't update the UI

### ISSUE THREAD

**Issue by Syndesi** [mobxjs/mobx#1676]
Hi,

I want to store an array of custom non-plain objects in order to represent a table.
At this moment I can access, draw & update these objects, but the UI isn't updated automatically.
Therefore I created a small [demo](https://codesandbox.io/s/4wn7wq9o27).
(Note that the updated names appear in the console while the UI remains as it is)

Any help or alternative implementations are welcome :)

**Comment by urugator** [comment]
You're missing `@observer` in your `demo.

**Comment by Syndesi** [comment]
I guess you're right. And with `@observe` it's working as it should.
Sometimes it is very hard to catch the most obvious mistake, but thank you very much for helping me :)

**Comment by mweststrate** [comment]
That is normal and stated in the docs,  observer should be applied first

Op vr 10 aug. 2018 14:22 schreef Syndesi <notifications@github.com>:
