### ISSUE TITLE
mobx-connect (release)

### ISSUE THREAD

**Issue by nightwolfz** [mobxjs/mobx#168]
[mobx-connect](https://www.npmjs.com/package/mobx-connect) allows use to access mobx state from any component decorated with `@connect` 
(similar to redux's connect).

This is a generic version of my previous package [ryan](https://www.npmjs.com/package/ryan). 
Hope no one minds if I use the name mobx-connect.

Enjoy !

**Comment by mweststrate** [comment]
Awesome stuff. I definitely don't mind about the name! Btw, if you want to move it to the org I can arrange that.

**Comment by nightwolfz** [comment]
Sure but not yet. Once it's more useful, we can make it "official"

**Comment by mweststrate** [comment]
Thanks for sharing this. I'll close this issue for now, but I'll add it to a 'related projects' as soon as I have time to write it :)
