### ISSUE TITLE
configure enforceActions does not work!

### ISSUE THREAD

**Issue by up209d** [mobxjs/mobx#1680]
I was using `umd mobx 5.0.3` and I couldn't get `configure({ enforceActions: true })` works. It just does nothing. There is no error thrown because of changing observable object outside of an action.

Could anyone take a look into my sample code to see where is my problem here? Otherwise, it might be a bug, isn't it? Thank you.

https://codepen.io/up209d/pen/KBENbz

**Comment by kuitos** [comment]
I guess `enforceActions: 'strict'` was what u want, but not `enforceActions: true`.
check the doc https://mobx.js.org/refguide/api.html#-enforceactions-boolean

**Comment by up209d** [comment]
That's not true as it was stated:

`In sloppy (true) mode, MobX will only throw if an observed observable is modified, in "strict" mode it will even throw for non-observed observables`

If it is not a bug, I guess that feature just doesn't work with `production build` as well as `umd version` cuz it has meaning only in developing phase.

**Comment by mweststrate** [comment]
When filing a bug, please describe expected and observed behavior, as
prescribed by the issue template. Reading this conversation it is still
unclear for me what "doesn't work" means in this conversation. Since I
don't see observed observables in your example, I think you might be
misinterpreting the docs @kuitos quoted.

Op ma 13 aug. 2018 om 15:33 schreef U.P <notifications@github.com>:

**Comment by up209d** [comment]
I did assign `observable` on `githubProjects` and `state` of `Store` class in the `decorate`, and you can see I did fire `fetchProjects` and in the callback of that method, I change `githubProjects` and `state` not in an action, and no `error` was thrown. Am I doing wrong?

```
const { observable, action, configure, computed, decorate } = mobx;

configure({ enforceActions: true })

class Store {
    githubProjects = []
    state = "pending" // "pending" / "done" / "error"
    fetchProjects(cb) {
        this.githubProjects = []
        this.state = "pending"
        fetch('https://api.github.com/users').then(
            projects => {
              projects.json().then((data)=>{
                this.githubProjects = data
                this.state = "done"
                cb(data);
              })
            },
            error => {
                this.state = "error"
            }
        )
    }
    get count() {
      return this.githubProjects.length;
    }
}

decorate(Store,{
  githubProjects: observable,
  state: observable
})

const store = new Store()
console.log(store.state, store.count)

store.fetchProjects(()=>{
  console.log(store.state, store.count)
})



```

**Comment by mweststrate** [comment]
In sloppy (true) mode, MobX will only throw if an observed observable is modified, _in "strict" mode_ it will even throw for _non-observed observables_

Maybe not the most optimal formulation (PR welcome!), but in other words, in `"strict"` mode it will throw on all mutations, of both non-observed and observed observables. While in loose mode (`true` for now, PR for changing that to `"loose"` welcome as well ;-)), non observed observables can be modified outside actions. The reason for that is that observables that are not being observed, cannot cause unexpected side effects, and are from that perspective safe to modify.

**Comment by urugator** [comment]
Not sure if relevant, but some time ago I proposed perhaps a bit more matching/self-explanatory nomenclature:
https://github.com/mobxjs/mobx/issues/1473#issuecomment-383050201

**Comment by mweststrate** [comment]
In MobX 4.4 / 5.1 the config values have changed to `never`, `observed` and `always`
