### ISSUE TITLE
Error: [mobx] Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify: CounterStore@1.isChargesApplied

### ISSUE THREAD

**Issue by badarshahzad** [mobxjs/mobx#1684]
I have the following:

CounterStore:
```
 @observable isChargesApplied = true;

// total price of place order
  @computed
  get totalPriceValue() {

    let totalPrice = this.item.price + this.totalPrice;

    // if the order price is less than 350 then charges will apply
    if(totalPrice <= 350 ){
      totalPrice = totalPrice + this.deliveryCharges;
      this.setChargesApplied(true);
    }else{
      this.setChargesApplied(false);
    }


    return totalPrice;
  }

 //set the state charges applied or not
  @action
  setChargesApplied(value){
    this.isChargesApplied = value;
  }

  //get the chage value 
  @computed
  get getChargesApplied() {
    return this.isChargesApplied;
  }

```

I am using the state like this way:
```

 {/* Delivery Charges Price*/}
                <Text
                  style={[
                    styles.regularTextCss,
                    { marginRight: 8, paddingBottom: 8 }
                  ]}
                >
                  {"Rs. "} 
                  {(this.props.counterStore.getChargesApplied)
                    ? this.props.counterStore.deliveryCharges
                    : "0"}
                </Text>
```

I want to return the state true or false to used in my Text view to show charges are applied or not.

Libraries:
```
 "mobx": "^4.3.1",
 "mobx-react": "^5.2.3",
```

Screen Error:
![whatsapp image 2018-08-15 at 12 21 38 pm](https://user-images.githubusercontent.com/19945367/44136374-fbdb875e-a085-11e8-9726-10cdf8c48c17.jpeg)

**Comment by mweststrate** [comment]
Computed properties should be pure, but yours has a side effect:
setChargesApplied. Probably things will be clearer if you instead introuce
two computed values, one with, and one without charges applied.

Op wo 15 aug. 2018 om 09:29 schreef Badar Khan ツ <notifications@github.com>:

**Comment by urugator** [comment]
```javascript
  @computed
  get price() {
    return this.item.price + this.totalPrice;
  }

  @computed
  get chargesApplied() {
    return this.price <= 350;
  }

  @computed
  get priceWithCharges() {
    if (this.chargesApplied) {
      return this.price + this.deliveryCharges;      
    } else {
      return this.price;
    }    
  }
```

**Comment by badarshahzad** [comment]
@urugator  Thank you! your example works great. Can you recommend me resource where I can these tricks easily.

**Comment by urugator** [comment]
Besides mobx docs and github issues I don't think so, however there is nothing "tricky" here. Just think twice before introducing a new `@observable` field and ask yourself if it can be expressed as computation of other `@observable` field(s).
Always prefer `@computed` to keep the state minimal. Actually I recommend to get familiar with React as quite the same principles applies to mobx. Eg. directly from react documentation:
> If something can be derived from either props or state, it probably shouldn’t be in the state.
