### ISSUE TITLE
Typescript API: Interface `IAutorunOptions` is not exported by `mobx.d.ts`

### ISSUE THREAD

**Issue by akloeber** [mobxjs/mobx#1685]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [x] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version? __mobx 5.0.3__ 
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

Interface `IAutorunOptions` is not exported by `mobx.d.ts`, although it is part of the public API. So in order to use this type it needs to imported with a deep path:
```js
import {IReactionPublic, IReactionOptions, IReactionDisposer, reaction, autorun} from 'mobx';
import {IAutorunOptions} from 'mobx/lib/api/autorun';
```

It should also be exported by `mobx.d.ts` so that it can be imported through module `'mobx'` like
```js
import {IAutorunOptions} from 'mobx';
```

**Comment by mweststrate** [comment]
Fixed in Mobx 4.3.2 / 5.0.4
