### ISSUE TITLE
First-level view binding library option available?

### ISSUE THREAD

**Issue by agquick** [mobxjs/mobx#1687]
I'm aware we can use React or Vue as the view-binding layer for mobx, but is there a view/template library that supports mobx by default (not by an extension)? I've built several production apps with Knockoutjs, but I'm not quite sure what the future of it will be, and mobx seems the most comparable going forward. Migrating to Mobx/React seems the most likely option, but I'm not a huge fan of JSX.

I'm thinking of something almost like marko.js in that it would just provide a very simple component-centric view binding layer on top of mobx.

For the "why not just use vue?" responses, I have grown accustomed to adding observables and computeds to my data models so that I can bind to model changes, not just changes in the Vue component.

**Comment by mweststrate** [comment]
MobX is generic and view library agnostic, but nonetheless quite easily bound to arbitrary view libraries, especially if they are not to complex, see for example: https://github.com/johnlindquist/mobx-yo-yo

There are no mobx-first featuring view libraries afaik

**Comment by agquick** [comment]
Thanks, yes I also found a similar mobx binding to Mithril, which if tied to a templating language (e.g. jade) gets me close to what I'm trying to do. The only issue is proper handling of custom components. I'm trying to avoid writing yet another JS view framework, though...

The observable paradigm simplifies state management a ton, it seems strange that most view libraries rely on a simple "data" or "state" variable to manage all state. In any event, thanks for the response.
