### ISSUE TITLE
The latest mobx version (5) is set in older mobx builds like 4.3.0.

### ISSUE THREAD

**Issue by MauricioAndrades** [mobxjs/mobx#1689]
## Issue:
The latest mobx version (5) is set in older mobx builds like 4.3.0.
I think it happened here: ca734adf3095a717e8a7fe36cb68622dbe0de6a8
https://github.com/mobxjs/mobx/commit/ca734adf3095a717e8a7fe36cb68622dbe0de6a8#diff-b7cd2bd0ae3078ef83015cbfa3499bf6

package.json version is 4.3.0 but mobx internal version `mobx._getGlobalState().version` says 5.

I could be misunderstanding the purpose/what number the version is supposed to be at. Just wanted to point this out.

## Reproduce:
  `git checkout 4.3.0 && npm run build` Look at version set in `src/core/globalstate.ts`
  or `npm install mobx@4.3.0` and load into app then run `mobx._getGlobalState().version`;

## Elaborate on your issue. What behavior did you expect?
  Not a huge deal but this caused a bit of confusion with the team when we were doing module analysis and trying to work out our upgrade schedule.

**Comment by mweststrate** [comment]
Ah, that version number is unrelated to the package version, and can actually be the same across majors as it signals the internal formatting of the globalstore. So you can safely ignore that. That it is 5 is just a confusing coincidence.

**Comment by MauricioAndrades** [comment]
Ah thank you for clearing that up. I'll close this.

-M
