### ISSUE TITLE
ES7 interop

### ISSUE THREAD

**Issue by chicoxyzzy** [mobxjs/mobx#169]
Hi. I just want you to check out https://github.com/cujojs/most/issues/160. I think that it is really useful enhancement.

**Comment by chicoxyzzy** [comment]
I think I can implement this so we will be able to deprecate https://github.com/chicoxyzzy/rx-mobx :)

**Comment by mweststrate** [comment]
Fancy! Feel free to take a shot at it :)

**Comment by chicoxyzzy** [comment]
Wow actually this is way more complicated than I thought =) I am familiar with TypeScript though I need to explore mobx source code a bit to find a place should I add Symbol.observable method

**Comment by mweststrate** [comment]
I think you need to add it to the prototypes of `ObservableValue`, `ComputedValue`, `ObservableArray`, `ObservableMap` and as symbol when extend an object. In all 5 cases you can probably use some identical utility function that wraps around `mobx.observe`.

**Comment by benjamingr** [comment]
I think we can close this now given https://github.com/mobxjs/mobx/issues/677 and blesh's intent to implement
