### ISSUE TITLE
Most efficient way to use onBecome[Un]observed()?

### ISSUE THREAD

**Issue by papercuptech** [mobxjs/mobx#1693]
I'm looking to be notified on a per-object basis, of only when the first property access  "becomesObserved", and then only when the last property access "becomesUnobserved".

Can't seem to locate any api docs on the `onBecome`s either. It appears they return a function that needs to be called at 'right' time for cleanup; not sure when that would be.

Conceptually would like something like this 
```javascript
onObjectObs(obj) {}
onObjectUnobs(obj) {}

@notifyObserved(onObjectObs)
@notifyUnobserved(onObjectUnobs)
class MyThing {
  @observable foo = 0
  @observable bar = 's'
}

//or

const obj = new MyThing()
onBecomeObserved(obj, onObjectObs)
onBecomeUnobserved(obj, onObjectUnobs)

```

But it appears I would have to do something like:

```javascript
onObjectObs(obj) {}
onObjectUnobs(obj) {}

class MyThing {
  _becomeObserved = []
  _becomeUnobserved = []
  _observedCount = 0
  _onPropObserved = () => if(this._observedCount++ === 0) onObjectObs(this)
  _onPropUnobserved = ()  => if(--this._observedCount === 0) onObjectUnobs(this)

  constructor() {
    ['foo', 'bar'].forEach(prop => {
      this._becomeObserved.push(onBecomeObserved(this, prop, this._onPropObserved}
      this._becomeUnobserved.push(onBecomeUnobserved(this, prop, this._onPropUnobserved}
    })
  }

  cleanup() {
    this._becomeObserved.forEach(cb => cb())
    this._becomeUnobserved.forEach(cb => cb())
  }

  @observable foo = 0
  @observable bar = 's'
}
```

uhh.... is this true?

thx

**Comment by urugator** [comment]
Check [this comment](https://github.com/mobxjs/mobx/issues/992#issuecomment-303860444)

Based on the that comment the solution would be to place onBecome(Un)Observed handler one level up - on an observable/computed which provides MyThing instance.

**Comment by papercuptech** [comment]
Thanks for the reply and the reference.

There are some assumptions in the comment I'm not sure apply in my case. Some better (any) docs on `onBecome`'s might help.

>>attach the handlers for a whole object graph and treat it as one

>That is something you cannot reason about if you don't know about the data structure. Two objects referring to each other would kill this approach. You need a _tree_ for that.
 
Not clear what is meant by "if you don't know about the data structure". In my case the data structure is known, in so much as knowing the names and types of properties for a given class, and what other class instances are referenced, qualify as that (i.e. the schema). 

It's known the structure is a graph not a tree; a node can be referenced from several other nodes. This can and likely will happen, but not sure what `objects` in above is referring to; specifically a cycle of Atoms instances, or cycle of something else.

Last comment in issue:
>Those handlers are only called if atoms get observed *while being used in a reactive context*

Which seems to imply a cycle alone won't make all objects within immediately "observed", until at least one actually becomes so in a reactive context.

>However, if you design your data to be a tree, you just need to listen to the root node events, as accessing a deeper node should cause the root node to be accessed and observed as well in a properly design object

Technically, not clear why observing a leaf "should" cause all ancestors to be observed as well, unless the meaning here presumes the tree of the observers itself is observing the observable tree from root to leaf; a "reactive" reflection of that part of the tree.

Not seeing the implied context to understand why a tree structure for the data to be rendered is considered a "properly design object"?

Think of traversing an enormous (millions of nodes) graph "visually" and wanting to manage what parts (typed nodes/edges) of the underlying graph need to be locally present, can be released when "distance" from viewport lengthens, or will soon need fetching. Think of certain properties of the nodes being "real-time" and having to manage the subscribe/unsubscribe lifecycle as they go in and out of view. Imagine some nodes or there parts appearing at several locations. Think of the visual tree needing to be virtualized for optimal memory usage and performance, and reflecting only the "visible/observed" portion of the graph while faking scrollbars. The visualizers of the nodes/edges can participate in determining what's being observed in ways decoupled from the mere x/y location and size of the viewport.

Simply being notified when the first property of a node/edge record is observed, and when the last property is unobserved, would help. Or maybe I'm really confused about something?

**Comment by papercuptech** [comment]
I looked at the code to see exactly how `onBecome`s work. For what I'm looking for, the essential house keeping in original question appears required. I made a decorator that relies on and replaces `@observable`, setting some stuff up on first get/set. It works for now, will see later how well with lots instances. Closing. Thx
