### ISSUE TITLE
How to handle error within SSR (with Express)

### ISSUE THREAD

**Issue by aripekkako** [mobxjs/mobx#1695]
1. [X ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

Hi,

we're using mobx with mobx-state-tree and mobx-react and rendering our React app on the server with `renderToString`  from react-dom.

We're encountering `[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component ...` errors in some cases and would need to return HTTP 500 to the user. 

However, due to to how MobX handles errors, we can't catch these errors.

What I've considered:

1.  **Use global onError handler from mobx-react** (https://github.com/mobxjs/mobx-react#global-error-handler-with-onerror). However I don't think this would work as expected, because all reaction errors end up here and we can have multiple requests concurrently so a single request encoutering an error would lead to all current requests getting an HTTP 500 response.
2. **Using `configure({ disableErrorBoundaries: true });` together with `_resetGlobalState()`**. However, I understood from the comments in the `_resetGlobalState()` code that it will break all currently existing observables. Because of concurrency, this will not work.
3. **Using React error boundaries** (https://reactjs.org/docs/error-boundaries.html). I tried to have a top level `ErrorHandler` -component, but `componentDidCatch` does not get called.

Is there any way I could catch the unhandled errors in the context of the current `renderToString` reliably?

**Comment by aripekkako** [comment]
We do call `useStaticRendering(true);` in the beginning of our server side component, as explained in the docs (https://github.com/mobxjs/mobx-react#server-side-rendering-with-usestaticrendering).

Does this somehow affect error handling? From the docs I understood that it only has to do with component lifecycle & memory.

**Comment by mweststrate** [comment]
It makes observer basically a noop, is your exception thrown from an
observer component (render method) or from a reaction / autorun that is
setup somewhere?


Op vr 24 aug. 2018 om 10:32 schreef aripekkako <notifications@github.com>:

**Comment by aripekkako** [comment]
From the render method:

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@164] TypeError: Cannot read property 'activated_coupons' of null
    at ActivatedCoupons.render (/ui/frontend/src/components/coupon/ActivatedCoupons/index.jsx:19:31)
    at ActivatedCoupons.makeComponentReactive (/ui/frontend/node_modules/mobx-react/index.js:740:56)
    at ActivatedCoupons.target.render (/ui/frontend/node_modules/mobx-react/index.js:962:38)
    at d (/ui/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:211)
    at xa (/ui/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:493)
    at a.render (/ui/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:18)
    at a.read (/ui/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:243)
    at renderToString (/ui/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:6)
    at render (/ui/frontend/server/universal.jsx:99:16)
    at /ui/frontend/server/universal.jsx:186:9
```

**Comment by mweststrate** [comment]
IN that case no reaction should be set up at all (see
https://github.com/mobxjs/mobx-react/blob/375d731f3e2f64c36b2f183e98fb02c472d95fac/src/observer.js#L154).
You might be setting the config to late? (it applies globally). Or you are
accidentally having multiple instances of the mobx-react module? I think
this is a setup issue, please provide minimal reproduction to proceed

Op vr 24 aug. 2018 om 10:38 schreef aripekkako <notifications@github.com>:

**Comment by aripekkako** [comment]
The error was actually indeed thrown inside a component render method that was done inside `autorun` (missed the `Reaction[Autorun@164]` in the previous stack trace). I now added `onError` callbacks for our autoruns and everything seems to work!

Thank you for your time & responses, which helped me to find the culprit!
