### ISSUE TITLE
Idea. multi-disposer + SideEffects react component

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx#1698]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

Sometimes (usually when dealing with react components) I have to use this pattern
```
disposerOfReaction1,2,3,4...

componentWillMount() {
  this.disposerOfReaction1 = reaction(...)
  2, 3, 4...
}

componentWillUnmount() {
  if (this.disposerOfReaction1) { this.disposerOfReaction1(); this.disposerOfReaction1 = undefined}
  2,3,4...
}
```

first thing, how about something like a multi disposer?
```
  multiDisposer: Disposer
  
  componentWillMount() {
    this.multiDisposer = disposer({
      a: reaction(...)
      b, c, d...
    })
  }

  componentWillUmount() {
    this.multiDisposer.disposeAll()
  }
```

that would work for anything that is disposable (autorun, reaction...). methods:
```
disposer({ [k: string]: IDisposer })
keys(): string[]
has(key): boolean
dispose(...key: string[]): void // throws if key not there
disposeAll(): void
isDisposed(key): boolean // true if key is disposed, false if not, throws if key not there
areAllDisposed(): boolean // true if all keys are disposed, false if not
```

That'd be the generic version.

As for react, I think it could be even easier if in mobx-react there was something like
```

render() {
  sideEffects = () => ({
      a: reaction(...)
      b, c, d...
    })

  return (<>
    <SideEffects>{this.sideEffects}</SideEffects>
  </>)
}
```

in this case, the component implementation would be as easy as 
```
class SideEffects extends React.Component {
  componentDidMount() {
    this.multiDisposer = disposer(this.props.children())
  }
  componentWillUnmount() {
    this.multiDisposer.disposeAll()
  }
}
```

plus maybe calling disposeAll and creating a new multiDisposer if childrens change

**Comment by urugator** [comment]
> how about something like a multi disposer?

I would be very hesitant to introduce a new abstraction for something solvable nearly identically with pure JS:
```javascript
// don't use willMount but didMount
componentDidMount() {
  this.disposers = [
    reaction(...),
    reaction(...),
  ]         
}

componentWillUnmount() {
  this.disposers.forEach(dispose => dispose())
}
``` 

> could be even easier

I don't see how, it just increases cognivite load.   

> plus maybe calling disposeAll and creating a new multiDisposer if childrens change

You're creating sideEffect callback at every render therofore children are always changed.

You may want to check:
https://github.com/mobxjs/mobx-react/issues/181#issuecomment-314451287

I do use a similar disposer utility, but in different context - on the server when loading various services - it deals with asynchronicity (serial/parallel disposer), errors etc - nothing I would need in react/mobx.

**Comment by xaviergonz** [comment]
@urugator good points!

I read the comment, based on it, what about something like this then?
```
import {autoDispose, observer} from "mobx-react"

@observer
class Test extends React.Component {
   @autoDispose
   fetchData = reaction(....) // would also work for autorun, when, etc...

   @autoDispose
   allReactions = [ reaction(...), reaction(...), ...]
}
```

that auto disposes on componentWillUnmount

**Comment by urugator** [comment]
I think it's better suited for 3rd party lib and since it simply calls the prop as a function on unmount I would rename it to `@onWillUnmount`

**Comment by mweststrate** [comment]
Agreed, but also, I see the value (it would be very useful to us as well), but I think it should be not part of the mobx package. I

 could live with it in the mobx-react package if it small, it doesn't 100% belong there (just like Provider and inject), but it might be valueable to provide it because it is such a super common pattern, and it helps people to not forget to dispose their reactions. So a pr on mobx-react would be welcome.

**Comment by mweststrate** [comment]
Closing as question is answered, and could be further discussed in mobx-react package
