### ISSUE TITLE
createTransformer appears to contaminate object with $transformId? 

### ISSUE THREAD

**Issue by amsb** [mobxjs/mobx#170]
In attempting to use `createTransformer` in a custom serialization utility, it appears that `$transformId` properties are being added to both the original objects and the output objects. I'm a bit perplexed about how/why this is happening. Can anyone shed light on this and offer a suggestion on how to fix it? THANKS!

From my [JS Bin](https://jsbin.com/cipowaguhu/edit?js,console) example, here's the function I'm working to write which works without `createTransformer`.

```javascript
function serialize(obj) {
  const _serialize = mobx.createTransformer(obj => {
    if (mobx.isObservableMap(obj)) {
       const serializedObj = new Map()
       obj.entries().forEach(([k,v]) => {
         serializedObj.set(k, isObject(v) ? _serialize(v) : v)
       })
       return serializedObj
    } else if (mobx.isObservableArray(obj)) {
      return obj.map(v => isObject(v) ? _serialize(v) : v)
    } else if (mobx.isObservable(obj)) {
      const serializedObj = {}
      Object.keys(obj).forEach(k => {
        const v = obj[k]
        serializedObj[k] = isObject(v) ? _serialize(v) : v
      })
      return serializedObj
    } else if (isPlainObject(obj)) {
      const serializedObj = {}
      Object.keys(obj).forEach(k => {
        const v = obj[k]
        serializedObj[k] = isObject(v) ? _serialize(v) : v
      })
      return serializedObj
    } else {
      return obj
    }
  })
  if (isObject(obj)) {
    return _serialize(obj)
  } else {
    return obj
  }
}

function isObject(value) {
  return typeof value === "object"
}

function isPlainObject(value) {
	return (value !== null
    && typeof value === "object"
    && Object.getPrototypeOf(value) === Object.prototype
  )
}
```

Here's example usage:

```javascript
var A = function () {
  mobx.extendObservable(this,
    {
      m: {}
    }
  )
}

var a = new A()
a.m['key1'] = 'value1'
a.m['key2'] = mobx.observable({
  'subkey1': 'subvalue1'
})

console.log(a.m)
console.log(JSON.stringify(serialize(a), null, 2))
console.log(a.m)
```

which produces the output:

```
[object Object] {
  key1: "value1",
  key2: [object Object] {
    subkey1: "subvalue1"
  }
}

'{
  "m": {
    "key1": "value1",
    "key2": {
      "subkey1": "subvalue1",
      "$transformId": 10
    },
    "$transformId": 8
  },
  "$transformId": 6
}'

[object Object] {
  $transformId: 8,
  key1: "value1",
  key2: [object Object] {
    $transformId: 10,
    subkey1: "subvalue1"
  }
}
```

**Comment by mweststrate** [comment]
`$transformId` is used internally for memoization purposes. But the property should not show up indeed. Fixed in 2.0.4 that the property is no longer enumerable.

**Comment by amsb** [comment]
Perfect. Thank you!

**Comment by mweststrate** [comment]
By the way, your serialize function seems to be generic? Might be worth
sharing :)

Op di 22 mrt. 2016 om 17:48 schreef amsb <notifications@github.com>:

**Comment by amsb** [comment]
It's generic, but simplistic (e.g. no cycles). It also unfortunately fails to work for me in an [example app](https://github.com/amsb/mobx-reactor/blob/master/examples/basic/index.js#L123) but I haven't yet been able to isolate the cause although I observe that isObservableMap returns false when I think it should return true.
