### ISSUE TITLE
What can I do to cache the result of a computed in the same tick it is created?

### ISSUE THREAD

**Issue by thejohnfreeman** [mobxjs/mobx#1701]
```javascript
class Data {
  @computed
  get x() {
    console.log("computing x");
    return 1;
  }
}

const data = new Data();
console.log(data.x);
console.log(data.x);
```

The output is this:

```
// computing x
// 1
// computing x
// 1
```

Further, there will be an additional `computing x` the first time a dependent, reactive expression uses `x`.

I expected this:

```
// computing x
// 1
// 1
```

It seems that `@computed` doesn't cache results and track dependencies until after the tick in which it was created. Is there a way to get what I want?

**Comment by urugator** [comment]
https://mobx.js.org/refguide/computed-decorator.html

> This automatic suspension is very convenient. If a computed value is no longer observed, for example the UI in which it was used no longer exists, MobX can automatically garbage collect it. This differs from autorun's values where you must dispose of them yourself. It sometimes confuses people new to MobX, that if you create a computed property but don't use it anywhere in a reaction, it will not cache its value and recompute more often than seems necessary. However, in real life situations this is by far the best default, and you can always forcefully keep a computed value awake if you need to, by using either observe or keepAlive.
