### ISSUE TITLE
correct way of making a setter for observables 

### ISSUE THREAD

**Issue by panda0603** [mobxjs/mobx#1704]
I've just started using mobx. I have mobx class as follows:

```
class Store{
@observable locationKey = null;
@observable query = '';

@action setLocationKey = key =>{
    this.locationKey = key;
}
@action setQuery = test =>{
    this.query = test;
}
}
```
I have two observable properties, and I have two actions that can alter these properties. As far as I know, I can only change the observable properties through the action, and I cannot directly change, for example, this.props.store.locationKey = 5 in some other component ( Am I right?)

Then if I have like 100 observable properties and I wish to change them, do I have to make each action for each observables? That would be really inefficient. Is there way to make one function so that all observables can share in order to alter the properties?

something along the line of..(i know this code won't work but just the idea)
@action setProp = (obsName, value) =>{
 this[obsName] = value;
}
so that I can use it by for instance, setProp(locationKey, 5)

**Comment by mweststrate** [comment]
That would work, but is not needed. You can just pull actions "up", actions
are not bound to their store (or properties) and can safely be nested as
well. Think about them as transaction boundaries. It doesn't really matter
what they modify.

```
@action userClickedSomething() {
   something.x = 1
   somethingElse.y = 2
}
```

Op do 30 aug. 2018 om 08:17 schreef panda0603 <notifications@github.com>:

**Comment by panda0603** [comment]
@mweststrate  thank you for the answer. I'm not fully understanding what you said. can you give me an example using my code above? so if I wish to alter props locationkey and query, how should I alter them without having to make setter action for each of the props?

**Comment by mweststrate** [comment]
You can write a action setter for each prop of the above, but it misses the point (and optimizations), the idea is rather that you mark all the operations your application has as actions. So, something like:

```
class Store{
@observable locationKey = null;
@observable query = '';

@action loadDataFromServer() {
   // updates a bunch of observables
}


@action onQueryChagne(key, query) {
    this.locationKey = key
    this.query = query
}
}
```

It doesn't matter where the action is defined, so probably you don't want that onQueryChange handler in your store, but as event handler in your react component. Then you move that function just there:

```
@action onQueryInputChange = (evt) {
    this.props.myStore.query = event.target.value
}
```

etc

**Comment by panda0603** [comment]
@mweststrate okay,  so I understand that  I can have actions to change the props in the store in other components. The way I understood is that the event handler you have suggested, 
`@action onQueryInputChange = (evt) {
    this.props.myStore.query = event.target.value
}`
still means that it can only change one prop which is the 'query' prop, and with this same function I cannot alter other props in the store, am I right? So i still need to make anther handler for other props.

`@action onQueryChagne(key, query) {
    this.locationKey = key
    this.query = query
}
}`
for this change handler, this is okay for two props as the example, but what if I have like 100 props, 
then I cannot pass all the parameters like @action onQueryChange(key, query, ..., so on forever). 

Maybe it's just me not understanding :( What I'm expecting is something is the lines of 

`(just the idea)
@action setProp = (obsName, value) =>{
this[obsName] = value;
}`

so that I can alter different props with just this action alone, e.g. setProp(query, "hello") or setProp(locationKey, 7) etc..

**Comment by mweststrate** [comment]
> and with this same function I cannot alter other props in the store

No, you can. What suggested otherwise?

I think you are completely overthinking this thing. Just write your code as if `@action` doesn't exist. Then take the most outer function that is going to cause those hundred updates and mark it with `@action`  (typically an event handler or stream listener or something)

**Comment by wbercx** [comment]
There's nothing wrong with with your `setProp` idea at all. It works as-is, and is perfectly fine. 

Perhaps this will clarify what actions do: https://codesandbox.io/s/34kqw238z1

They're an optimisation.

**Comment by urugator** [comment]
Actions don't care about the observables, they simply switches some global flag. The observables checks this global flag during assigment/modification. 

```javascript
@action method() {
  this.observable1 = 1;
  this.setSomeOtherObservables();  
  this.observable2 = 1;
}
```

roughly =>  

```javascript
method() {
  mobxGlobals.runsInAction = true;
  mobxGlobals.actionNestingCounter++; // allows nesting actions
  // --- 
  this.observable1 = 1; // checks mobxGlobals.runsInAction flag, the flag is true, so it pushes reactions to queue, otherwise it would invoke reactions (observers) immediately 
  this.setSomeOtherObservables(); // doesn't matter if this is action or not, the global flag is already set to true
  this.observable2 = 2;
  // ---
  mobxGlobals.actionNestingCounter--;
  if (mobxGlobals.actionNestingCounter === 0) {
    mobxGlobals.runsInAction = false;
    runScheduledReactions(); // invokes reactions one by one as they were inserted to queue
  }
}
```

As you may have noticed, the key is that everything runs synchronously.

**Comment by panda0603** [comment]
@wbercx wow thank you for the example exact function I was looking for! So so difference between action/ non action function is only in the re-rendering time difference? for changing the value of the observable, both action/non action does the same job am I right? 

@urugator thank you for the answer! took some time for me to understand, but good lesson for me.

**Comment by urugator** [comment]
> re-rendering time difference

Number of re-renderings - each observable mutation would cause individual re-render (it's not entirely true, because react batches certain updates as well, but thats not important here)
Action also wraps the function in `untracked` - to prevent unintentional subscription (when running action from derivation...)
The action is also required when `enforceAction` option is set to `always` or `observed` - it makes sure that you don't forget to apply `action` somehere (as mentioned everything works even without action, but possibly hurts performance).
