### ISSUE TITLE
Observable array, re-render React component

### ISSUE THREAD

**Issue by loeck** [mobxjs/mobx#1709]
Hi  !

I think, I have issue for understand correctly how observable array is working :'D

See this example: https://codesandbox.io/s/oll7y9n845, for re-render my React component I need to slice my array (`index.js` line 10) without that, my props never change (maybe I miss something ô ô)

Thanks for your help !

**Comment by mweststrate** [comment]
Your Items component should be observer as well, then you can skip the
slice.

Op vr 31 aug. 2018 om 10:14 schreef Loëck Vézien <notifications@github.com>:

**Comment by loeck** [comment]
Quite simply...

Thank you!
