### ISSUE TITLE
observable.ref and decorate() function

### ISSUE THREAD

**Issue by davidmz** [mobxjs/mobx#1713]
I am trying to use MobX (5.1) with TypeScript (3.0) but without a decorators syntax. Docs recommends to replace @-directives by `decorate(Class, {})` function. There is sample code:
```typescript
import { decorate, observable } from 'mobx';

class A {
  foo?: object;
}

decorate(A, {
  foo: observable.ref,
});
```
And this code produces the following TS error in my environment:
```
Argument of type '{ foo: IObservableDecorator; }' is not assignable to parameter of type '{ prototype?: MethodDecorator | PropertyDecorator | MethodDecorator[] | PropertyDecorator[] | undefined; }'.
  Object literal may only specify known properties, and 'foo' does not exist in type '{ prototype?: MethodDecorator | PropertyDecorator | MethodDecorator[] | PropertyDecorator[] | undefined; }'.
```
There is obviously something wrong with types but in fact this code works: https://codesandbox.io/s/znyp2x33xx

What am I doing wrong and what is the recommended way to do such things?

**Comment by mweststrate** [comment]
Does the error go away without '?'

Op ma 3 sep. 2018 21:10 schreef Давид Мзареулян <notifications@github.com>:

**Comment by davidmz** [comment]
No, it does not.

I found that the problem is related to the `strictFunctionTypes` flag in tsconfig.json. This flag is _true_ in my environment, if I set it to _false_, the error disappears. I made a small test repository to demonstrate this issue: https://github.com/davidmz/mobx-decorate-test.

**Comment by davidmz** [comment]
Hmm, strictFunctionTypes isn't always working… Looks like TS chooses invalid definition for 'decorate', `decorate<T>(object: T, …` instead of `decorate<T>(clazz: new…`, and requires keys of class function as object (i. e. prototype).

**Comment by makepost** [comment]
Please review pull requests #1711 and #1712, they fix calling decorate with modifiers. This is connected to an older issue, #1448.

**Comment by mweststrate** [comment]
This changes has been released yesterday, closing the issue
