### ISSUE TITLE
Question: Destroy mobx store?

### ISSUE THREAD

**Issue by swarles1337** [mobxjs/mobx#1718]
Hi guys,
I'm relatively fresh to MobX, and I couldn't find any information if it is possible to destroy a MobX store.

I would like to create a store when entering a part of my website and destroy the store, when the user is leaving this part as the data is not needed outside.

Right now I'm creating the store in the construct of the main react component of that part like:
`constructor(props) {
    super(props);
    this.myAwesomeStore = new AwesomeStore();
  }`
In my store I added a spy with some logging in the constructor:
`spy(event => {
        switch (event.type) {
          case 'action':
            console.log('MobX AwesomeStore action: ${event.name}');
            break;
            [...]
        }
      });`

Now if the component gets unmounted and constructed again a new store will be created and I get two times all logs. Is there a way of destroying the old store on componentWillUnmount?

**Comment by mweststrate** [comment]
What do you mean by "destroy"? javascript is a managed language, so as soon as no one uses your store it will be garbage collected, but that is not really related to MobX. If you want to reuse the same store you should not create it inside your component, but outside and use for example Provider / inject to make it available to your component

**Comment by swarles1337** [comment]
/close
I think it was because of the non disposed reactions. The store seems to be picked up by the garbage collector correctly now.
