### ISSUE TITLE
observable string changing to null not triggering refresh in React component.

### ISSUE THREAD

**Issue by actransitorg** [mobxjs/mobx#172]
Say I have this:

`@observable wo = null; // string `  

and in my observer React component, I have this:

`<textarea className="form-control" value={this.props.wo} />`

When I load wo with a value, the textarea is refreshed, but when set to null, it is not.   Is this documented somewhere?  I'll have to change all nulls to empty string to force refreshes.   

This becomes more complicated once the string is embedded within a DTO.

**Comment by mweststrate** [comment]
Hi, 

This should work as expected. I suspect however that you are passing a string value (the current value of  `wo`) as value to your component. Javascript primitives are never observable, the properties are. 

So if you have 

```javascript
class Person {
   @observable wo = null
}
```

Make sure you pass the person object(which has the observable property) to your observer components, and not just the current value of `person.wo`. I hope that helps!

**Comment by andykog** [comment]
@actransitorg, here is an example https://jsfiddle.net/Sl1v3r/f2usr8gw/

**Comment by actransitorg** [comment]
That example proves to me I'm doing something wrong.  Thanks for the tips.
