### ISSUE TITLE
Prettier 1.14 and MobX

### ISSUE THREAD

**Issue by hyperknot** [mobxjs/mobx#1722]
How are people using Prettier with MobX projects? 1.14 started moving every decorator to a new line, which I think totally breaks readability of MobX code. Are you staying on 1.13?

https://github.com/prettier/prettier/issues/5088

**Input:**
```jsx
export class SearchStore {
  @observable searchText = ''
  @observable message = ''
  @observable waiting = false
  @observable selectedId = null
  @observable expanded = false

  results = observable.array()

  @computed
  get selected() {}
}
```

**Output:**
```jsx
export class SearchStore {
  @observable
  searchText = "";
  @observable
  message = "";
  @observable
  waiting = false;
  @observable
  selectedId = null;
  @observable
  expanded = false;

  results = observable.array();

  @computed
  get selected() {}
}

```

**Comment by mweststrate** [comment]
Closing for now, as this is not under our control, but agreed that this is super annoying, and I recommend to stick to 1.13 indeed. This would blow up our code base as well with a few thousand lines
