### ISSUE TITLE
Idea: Generate UUIDs on observable array elements

### ISSUE THREAD

**Issue by msholty-fd** [mobxjs/mobx#1723]
I have a Idea:

When iterating over an observable array of generic objects in react, there is nothing unique on the object so that I can use it as a `key`. Here is a simple example:
```js
const foos = [
  {
     text: '',
  },
  {
     text: '',
  },
];

function Foo() {
    return (
      <div>
        {foos.map((foo, index) => (
          <input key={???} attribute="text" type="text" value={foo.text} />
        ))}
      </div>
    );
}
```
The reason I can't use `foo.text` here is on each keystroke, `foo.text` will update and react will re-render this list. The input will completely re-render because the key changed, and the input will lose focus. 

I can't use `index` as the key here because if I allow the user to `.splice` from the middle of this array, it will change the `index` of elements ahead of that one and cause React to re-render incorrectly.

A lot of libraries that implement some type of collection generate uuid's for elements in a collection, like [`backbone`](http://backbonejs.org/#Model-cid). I think mobx could also implement something like this and it would be extremely useful.
 
  * Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)? **Yes!**
  * Are you willing to (attempt) a PR yourself? Yes, with guidance from the maintainers of this repository.

**Comment by urugator** [comment]
It would mess with original item structure.
The ID field would need bizzare name to avoid collision with user data.
It's easy to do in userland on demand.
Possible performance impact, while IDs may actually not be needed anywhere.

> A lot of libraries that implement some type of collection generate uuid's for elements in a collectio

They generate IDs for their models, not for arbitrary data. You are free to introduce such models and use them instead:

```javascript
const foos = [
  model.extend({
     text: '',
  }),
  model.extend({
     text: '',
  }),
];
```

**Comment by mweststrate** [comment]
Agreed, this, nor React, is a goal of mobx itself. It is trivial to create items with id's yourself:

```
{
    id: uuid.v4(),
    test: ''
}
```

Alternatively, you could even use `getDebugName(object)` from mobx, but that would basically be a hack and doesn't guarantee uniqueness, although in practice it is
