### ISSUE TITLE
monitor  nested observables

### ISSUE THREAD

**Issue by Penggggg** [mobxjs/mobx#1734]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

**Please be sure to close your issues promptly.**

how can i monitor  nested observables

**Comment by urugator** [comment]
Can you be more specific?

Reactions (`reaction`/`autorun`/`observer`) react's to anything, which could influence the outcome of the reaction - that is - any observable accessed inside the reaction - no matter how deep it's placed in object graph.

If you're reffering to `observe`, then it's not possible. You would have to manually subscribe/unsubscribe for individual observables.

**Comment by mweststrate** [comment]
mobx-utils now has a `deepObserve` utility: https://github.com/mobxjs/mobx-utils#deepobserve.

This might answer the question, or maybe not. Closing the question for now, as it lacks relevant information. Can be reopened if more details are provided
