### ISSUE TITLE
Update observable without causing rerender

### ISSUE THREAD

**Issue by elderapo** [mobxjs/mobx#1737]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

Is it possible to update observable without causing rerender? At first it sounds like it might not make any sense but let me explain my usercase.

So I have layout store where I store information about `scrollY` offset. In [react-custom-scrollbars](https://github.com/malte-wessel/react-custom-scrollbars) I use `onScrollStop` callback function to update `scrollY` observable in layout store. I would like this update to not cause rerender and only update `scrollY` because after user stops scrolling layout is exactly in the right state thus it doesn't need to be rerendered. But on the other hand I have page where I need to scroll to `element` knowing it's y offset so from this place I would like to cause rerender by updating `scrollY`. Also when `LayoutComponent` is rendered for the first time it scrolls layout contents to position from `layoutStore.scrollY`.

I managed to achieve what I wanted using following hack but it doesn't feel right...

```ts
class LayoutStore {
  @computed
  public get scrollY() {
    this.scrollYInernalHelper; // <---- hack - DO NOT REMOVE

    return this.scrollYInternal;
  }

  private scrollYInternal: number = 0;

  @observable
  private scrollYInernalHelper: number = 0;

  @action
  public setScrollY(y: number, render: boolean = true) {
    console.log(`setScrollY: ${y} render: ${render}`);
    this.scrollYInternal = y;

    if (render) {
      this.scrollYInernalHelper++;
    }
  }
}
```

So in [react-custom-scrollbars](https://github.com/malte-wessel/react-custom-scrollbars) `onScrollStop` I call `layoutStore.setScrollY(y, false)` and from the other part when I need to scroll to some element I do `layoutStore.setScrollY(y, true)`.

**Comment by urugator** [comment]
> user stops scrolling layout is exactly in the right state thus it doesn't need to be rerendered

Does the extra render causes perfromance/usability issues?

> when I need to scroll to some element I do layoutStore.setScrollY(y, true)

I am not familiar with react-custom-scrollbars, I just quickly checked the API.
It provides `scrollTop(top = 0)` and `getValues()` methods. 
Can't you use these and keep the scrollbars component being a source of truth?    
How exactly do you use your `layoutStore.scrollY` inside `render`?
Perhaps you could use reaction to call `scrollTop(y)` instead of subscribing for `layoutStore.scrollY` inside render?

> is rendered for the first time it scrolls layout contents to position from layoutStore.scrollY

Similary, can't you call `scrollTop(previousY)` on componetDidMount?
Possibly saving previousY on componentWillUnmount...

> Is it possible to update observable without causing rerender?

No, but you can (eg conditionally) read observables without subscribing to them via `untracked`. Not sure if any use in this case.

About your workaround:
You can also use Date.now(), istead of incremented number. 
You can make the intention a little bit more obvious with `void(this.scrollYInernalHelper)`.
You can get rid of the extra prop at the cost of extra wrapper: 
```javascript
@observable.ref _scrollY = { value: 0 } // value is not observable due to .ref modifier

@computed
public get scrollY() {    
  return this._scrollY.value; // subscribed for this._scrollY but not for value
}      

@action
public setScrollY(y: number, render: boolean = true) {
  if (render) {
    this._scrollY = { value: y }
  } else {
    this._scrollY.value = y;
  }    
}
```

**Comment by elderapo** [comment]
>Does the extra render causes perfromance/usability issues?

Not really but it doesn't feel right.

>Can't you use these and keep the scrollbars component being a source of truth?

`LayoutComponent` keeps ref to `react-custom-scrollbars` element so I would still need some way of notifying it that I want it to scroll to some element. Thats why I decided to use `mobx` to hold the state of the scrollbar.

>How exactly do you use your layoutStore.scrollY inside render?

Simplified:
```ts
class LayoutComponent extends React.Component {
    private scrollbarsRef: any;
    private historyUnsubscribe: () => void;

    componentWillMount() {
        // so after route change scrollbar always goes to top
        this.historyUnsubscribe = history.subscribe(() => {
            layoutStore.setScrollY(0);
        });
    }

    componentWillUnmount() {
        if (this.historyUnsubscribe) {
            this.historyUnsubscribe();
        }
    }

    render() {
        // ...


        const {scrollY} = layoutStore;

        if (this.scrollbarsRef) {
            this.scrollbarsRef.scrollTop(scrollY);
        }

        return (
            <Scrollbars
            onScrollStop={e => {
              if (!this.scrollbarsRef) {
                return;
              }

              layoutStore.setScrollY(this.scrollbarsRef.getScrollTop(), false);
            }}
            ref={r => {
              this.scrollbarsRef = r;
              if (this.scrollbarsRef) {
                  this.scrollbarsRef.scrollTop(scrollY);
              }
            }}
          >
            {this.props.children}
          </Scrollbars>
        );
    }
}
```

**Comment by urugator** [comment]
> Not really but it doesn't feel right.

React is build on the premise that rendering and diffing is fast enough. Therefore preventing render is always an optimization. Don't optimize if it makes your code more complicated and doesn't provide actual benefits.  

> Simplified:

The `render` function must not contain any side effect, you shouldn't call `scrollTop(scrollY)` there.

> LayoutComponent keeps ref to react-custom-scrollbars element so I would still need some way of notifying it that I want it to scroll to some element

The idea is to keep the reference in store:
```javascript
class LayoutStore {
  @observable.ref scrollbarsRef = React.createRef();
  
  setScrollY(scrollY) {
    const scrollbars = this.scrollbarsRef.current;
    if (!scrollbars) {
      // TODO throw or ignore call
    }
    return scrollbars.scrollTop(scrollY);
  }  
}
class LayoutComponent extends React.Component {
  componentDidMount() { // note it's changed to DidMount
    this.historyUnsubscribe = history.subscribe(() => {
      layoutStore.setScrollY(0);
      // or use scrollbar directly
      // at this point we are already mounted, therefore the ref is surely available
      layoutStore.scrollbarsRef.current.scrollTop(0);
    });    
  }

  componentWillUnmount() {
    if (this.historyUnsubscribe) {
      this.historyUnsubscribe();
    }
  }

  render() {        
    return React.createElement(Scrollbars, {
      ref: layoutStore.scrollbarsRef,
    },
      this.props.children
    )
  }
}
```
If you want the `scrollY` to survive re-mounting the component, you can save it to store in `componentWillUnmount` and recover it from store in `componentDidMount`:
```javascript
componentDidMount() {
  layoutStore.scrollbarsRef.current.scrollTop(layoutStore.lastKnownScrollY);
}
componentWillUnmount() {
  layoutStore.lastKnownScrollY = scrollbarsRef.current.getValues().scrollY;
}
```
Alternatively you can keep the `scrollbarsRef` synchronized with your observable:
```javascript
class LayoutStore {
  @observable scrollY = 0;
}
class LayoutComponent extends React.Component {
  constructor() {
    this.scrollbarsRef = React.createRef();
  }
  componentDidMount() {
    this.disposeReaction = reaction(
      () => layoutStore.scrollY,
      scrollY => this.scrollbarsRef.current.scrollTop(scrollY),        
      { fireImmediately: true } // immediately init scroll position from observable
    )    
  }
  componentWillUnmount() {
    this.disposeReaction();
  }
  render() {        
    return React.createElement(Scrollbars, {
      ref: this.scrollbarsRef,
      onScroll: event => layoutStore.scrollY = event.scrollY,      
    },
      this.props.children
    )
  }
}
```
You may need to put some equality checks to the reaction/onScrollStop, just to make sure there isn't infinite cycle.

**Comment by mweststrate** [comment]
Closing as question seems answered and inactive
