### ISSUE TITLE
How to update the particular object of observable Array  Mobx + react-native

### ISSUE THREAD

**Issue by tusharmutreja** [mobxjs/mobx#1738]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by tusharmutreja** [comment]
i had created the store:

class profileStrore {
@observable
data= [{id:1,name:tushar},{id:2,name:jack}];

@action
updateElement(index){
const element = this.data[index];
element.name = alex;
}
}


@inject('profilestore')
@observer
class Home extends React.componnet {
render(){
<Flatlist
renderItem = <Component item={item}/>
....../>
}
}

This is the demo structure
I need to update the particular object of Array , it will update but it didnt cause that item re-render.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/issues/1142#issuecomment-323161298

For more info search for `FlatList` in issues.

**Comment by urugator** [comment]
It took you 12 minutes to reply. You're either very fast or very ignorant.
```javascript
renderItem = () => <Observer>{() => /* original renderItem code */}</Observer>

render() {
  return(
    <Flatlist
       data={this.props.feedStore.feedArray.slice()} // note the .slice
       renderItem={this.renderItem}
    />
  )
}
```

**Comment by tusharmutreja** [comment]
@urugator  i am already using the observer in that the component that i am returning from render item, but still it is not updated

**Comment by urugator** [comment]
Provide repro based on https://codesandbox.io/s/v3v0my2370

>parent component not updated if i update the paticular element of observable array in store

That's expected if parrent does not access the element.

**Comment by tusharmutreja** [comment]
thanks @urugator  , now it works , i am closing this issue

**Comment by anujAnujMody** [comment]
how did u solve it please can u let me know

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
