### ISSUE TITLE
MobX converts Array empties to nulls

### ISSUE THREAD

**Issue by bsmith-cycorp** [mobxjs/mobx#1745]
I have a:

2. [X] Issue:
  * [X] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [X] Did you check this issue wasn't filed before?
  * [X] Elaborate on your issue. What behavior did you expect?
  * [X] State the versions of MobX and relevant libraries. Which browser / node / ... version?

This is a fairly obscure issue and might be endemic to what MobX does, but I thought I'd bring it up anyway. 

The following is what happens with a regular array:
```
var arr = new Array(4)
var nonEmptyCount = Object.entries(arr).length
console.log(nonEmptyCount)
// <- 0
```
And this is what happens with a MobX (observable) array:
```
@observable arr = new Array(4)
...
var nonEmptyCount = Object.entries(this.arr).length
console.log(nonEmptyCount)
// <- 4
```
This seems to happen because the observable array becomes `[ null, null, null, null ]` instead of `[empty x 4]`. It can be worked around, but I didn't see it mentioned in the docs and in some obscure edge cases like mine it can cause problems.

Live example:
https://codesandbox.io/s/n31prxmj9j

Interesting note: the sandbox started out on MobX version 4 and the issue didn't happen there.

Google Chrome 69
MobX version 5.1.2

**Comment by mweststrate** [comment]
See also #1822, MobX doesn't support sparse, or out-of-bound index based arrays at the moment. This can be fixed potentially, but using such arrays is a code-smell in general, so I am not sure if it is worth the additional complexity. Closing for now, if this becomes a recurring problem, we can revisit.

**Comment by bsmith-cycorp** [comment]
Could a note be made in the docs at least? I don't have a good argument for why sparse arrays aren't a code-smell, but regardless, this is an unexpected API change like the `Array.sort()` situation, which got this explanation:

> Unlike the built-in implementation of the functions sort and reverse, observableArray.sort and reverse will not change the array in-place, but only will return a sorted / reversed copy. From MobX 5 and higher this will show a warning. It is recommended to use array.slice().sort() instead.

In my case I took something that worked, made it observable, and suddenly it didn't work. I think that warrants documentation.

**Comment by mweststrate** [comment]
Indeed, should be mentioned in docs!

Op vr 30 nov. 2018 om 17:09 schreef bsmith-cycorp <notifications@github.com

**Comment by mweststrate** [comment]
Seems to be accidentally fixed in v6: https://codesandbox.io/s/minimal-mobx-react-project-jnuev?file=/index.js
