### ISSUE TITLE
[Docs] Best practice on observing Date or moment objects

### ISSUE THREAD

**Issue by nareshbhatia** [mobxjs/mobx#1746]
Is it ok to observe Date and moment objects directly?

    @observable d = new Date();
    @observable m = moment();

The docs state that:

> If value is an object with a prototype..., observable will throw.

However code written as above works!

1. Why does this code work when the docs say that it will throw?
2. Would it be better to always store the time in millis instead (e.g. `@observable d = Date.now()`) and convert to Date or moment as needed?

**Comment by urugator** [comment]
> Why does this code work when the docs say that it will throw?

Docs are refering to: `observable(thing)`, not the decorator usage.

> Would it be better to always store the time in millis instead

Timestamp doesn't contain timezone info, so it's not usable as exchange format. String version (ISO/etc) would work in this regard.
You can keep using any arbitrary object, but I suggest to explicitely use `observable.ref` (sometimes it acts as plain objects, so it's converted by Mobx and may or may not work as expected - I have a feeling it's the case of momentjs, not sure), treat it as immutable and never access it directly (so you always access the observable wrapper).

**Comment by nareshbhatia** [comment]
Thanks @urugator, this makes total sense. Based on your comment, shouldn't a date object also be observed using `observable.ref`? We don't want mobx to be messing with its internals.

**Comment by urugator** [comment]
`observable.ref` for anything you wanna be sure it's not converted.
I think the mobx should detect Date properly as non-convertible, but I am never sure until I actually try.
One more thing - you may want to use Date in conjunction with `@computed.struct`, so that observers are notified only when the actual Date value is changed.

**Comment by nareshbhatia** [comment]
I just ran a small experiment. As far as I can tell, MobX does not modify Date or moment objects! I didn't even use `observable.ref`:

```
class Meeting {
    @observable title;
    @observable startTime;
    @observable startMoment

    constructor(title, startTime, startMoment) {
        this.title = title;
        this.startTime = startTime;
        this.startMoment = startMoment;
    }
}

const meeting = new Meeting('Code Review', new Date(), moment());
console.log('Meeting:');
console.log(`title:       ${meeting.title}`);
console.log(`startTime:   ${meeting.startTime.toISOString()}`);
console.log(`startMoment: ${meeting.startMoment.toISOString()}`);
console.log();

console.log('meeting instanceof Meeting:', meeting instanceof Meeting);
console.log('isObservable(meeting):', isObservable(meeting));
console.log('typeof title:', typeof meeting.title);
console.log('isObservable(title):', isObservable(meeting.title));
console.log('startTime instanceof Date:', meeting.startTime instanceof Date);
console.log('isObservable(startTime):', isObservable(meeting.startTime));
console.log('startMoment instanceof moment:', meeting.startMoment instanceof moment);
console.log('isObservable(startMoment):', isObservable(meeting.startMoment));
```

Here's the output:

```
Meeting:
title:       Code Review
startTime:   2018-09-30T04:46:33.046Z
startMoment: 2018-09-30T04:46:33.046Z

meeting instanceof Meeting: true
isObservable(meeting): true
typeof title: string
isObservable(title): false
startTime instanceof Date: true
isObservable(startTime): false
startMoment instanceof moment: true
isObservable(startMoment): false
```

**Comment by nareshbhatia** [comment]
I am reopening this issue because I think docs are not very clear on this. The [following statement](https://mobx.js.org/refguide/observable.html) is contradicting what I have seen above:

> By default, making a data structure observable is infective; that means that observable is applied automatically to any value that is contained by the data structure, or will be contained by the data structure in the future. This behavior can be changed by using modifiers.

(Note that at the top of the page it says that the docs apply to both `observable(value)` and `@observable classProperty = value`)

Based on this, one would think that `startTime` and `startMoment` would be "infected", but as far as I can tell, they are not.

I would be happy to create a PR for the docs, if someone can explain what's going on here.

**Comment by urugator** [comment]
> 3.  If value is an object without prototype or its prototype is Object.prototype, the object will be cloned and all its current properties will be made observable. See Observable Object

Mobx "infects" anything which is "infectible" - plain object, array, map.

My point about the use of `.ref` was, that sometimes checking for object's prototype isn't sufficient indicator of non-plain object.
