### ISSUE TITLE
Problem with infinite loop in `runReactions` function

### ISSUE THREAD

**Issue by PhiLhoSoft** [mobxjs/mobx#175]
I had the error about a cycle in my attempts to use MobX in my AngularJS 1 project, in a code that should not have a cycle (in my noob opinion...)..
When debugging, I found out the following (transpiled) function:
```
var MAX_REACTION_ITERATIONS = 100;
function runReactions() {
    if (globalState.isRunningReactions)
        return;
    globalState.isRunningReactions = true;
    var pr = globalState.pendingReactions;
    var iterations = 0;
    while (pr.length) {
        if (++iterations === MAX_REACTION_ITERATIONS)
            throw new Error("Reaction doesn't converge to a stable state. Probably there is a cycle in the reactive function: " + pr[0].toString());
        var rs = pr.splice(0);
        for (var i = 0, l = rs.length; i < l; i++)
            rs[i].runReaction();
    }
    globalState.isRunningReactions = false;
}
```
OK, what is the intent of the `pr` variable here?

If it is to have a snapshot of the `globalState.pendingReactions` array, to be consumed in the loop via the splice function, it fails, as, in my code, the `globalState.pendingReactions` gets another item pushed in it in the `rs[i].runReaction();` line, so `pr.length` is always 1 in the loop test. Hence the error.

If it is intended to be just a shortcut to this rather lengthy name, OK, I will close this issue (or you do) and I will open a new one with a reproduction of my problem.

**Comment by mweststrate** [comment]
It is intended as just a shortcut indeed. The idea is indeed that the `pr.length` should converge to zero if each time the remaining reactions are pulled from it and executed. I'll introduce clearer var names.

**Comment by mweststrate** [comment]
Feel free to open a new issue with the reproduction indeed, or reopen this one if more clarification is needed.
