### ISSUE TITLE
_mobx.decorate  is not a function

### ISSUE THREAD

**Issue by JxSx** [mobxjs/mobx#1750]
Hi, I met a problem!
![image](https://user-images.githubusercontent.com/12441183/46256436-a2073d00-c4dd-11e8-93c4-456431cd16d2.png)

**Comment by mweststrate** [comment]
Please provide more context. Versions,  reproduction etc.

Op zo 30 sep. 2018 12:23 schreef SmallXin <notifications@github.com>:

**Comment by Tkach7** [comment]
Probably,  You need to update Mobx.

> Hi, I met a problem!
> ![image](https://user-images.githubusercontent.com/12441183/46256436-a2073d00-c4dd-11e8-93c4-456431cd16d2.png)

**Comment by JxSx** [comment]
> Probably, You need to update Mobx.
> 
> > Hi, I met a problem!
> > ![image](https://user-images.githubusercontent.com/12441183/46256436-a2073d00-c4dd-11e8-93c4-456431cd16d2.png)

OK
