### ISSUE TITLE
Suggestion: enforceActions to report only instead of throwing errors

### ISSUE THREAD

**Issue by dannsam** [mobxjs/mobx#1758]
### Idea
The idea is to extend mobx configuration to report state changes outside of an action instead of throwing an error.

### What problem would it solve for you?
While throwing errors in strict mode in development is undeniably useful, I would hate it to affect a real user in production. ATM, I am thinking to disable `strict mode` in prod just to avoid potentially bad user experience. The app would work *almost* perfectly with probably somewhat degraded performance. However, it'd be awesome to know that modifications outside of actions happen and to fix them.

  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?
  I can do a PR once we settle on the approach.

What do you think ?

**Comment by mweststrate** [comment]
The simpler solution is no to use "strict mode" in production, but only set it conditionally in DEV mode.
