### ISSUE TITLE
Syntax error in docs ? 

### ISSUE THREAD

**Issue by fellz** [mobxjs/mobx#176]
Hi
It seems to me that this code has an syntax error

```
class TodoStore {
    @observable todos = todos: [{
        title: 'Find a clean mug',
        completed: true
    }]

    @computed get completedCount() {
        return this.todos.filter((todo) => todo.completed).length;
    }
}
```

``` @observable todos = todos: [{ ```

I cann't find this construct in ES6. Babel repl doesn't convert it so is it a mistake or ... ? 

https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/syntax.md

**Comment by mweststrate** [comment]
You need `babel-transform-decorators-legacy` to be enabled, see also #105 or the docs https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/syntax.md#enabling-decorators-in-your-transpiler (same page ;-))

**Comment by fellz** [comment]
it's not the decorator stuff but 

```
todos = todos: [ ]
```

**Comment by mweststrate** [comment]
Ah sorry misread the issue! Will fix that, should be `@observable todos = [{`

**Comment by andykog** [comment]
Fixed
