### ISSUE TITLE
Question: observer.shallow - don't understand

### ISSUE THREAD

**Issue by amelon** [mobxjs/mobx#1762]
I have a:
1. [x] Question: 

I'm using mobx 4.
Here is some code to explain my question.

````
import { observable, action, computed, autorun } from 'mobx'

class Test {
  @observable.shallow states = {}
  id = 'a'

  constructor() {
    // option A
    ['a'].forEach(v => {
      this.states[v] = { s: 'a' }
    })
    // option B
    // this.states = {
    //   a: {s: 'a'},
    // }
    this.transition('b')
  }

  @computed get currentState() {
    return this.states[this.id]
  }

  @action transition(v) {
    const n = {s: v}
    this.setCurrentState(n)
  }

  @action setCurrentState(state) {
    this.states[this.id] = state
  }
}

const test = new Test()

autorun(() => {
  console.group('autorun')
  console.log(test.currentState, test.id)
  console.groupEnd('autorun')
})

test.transition('c')
````

In constructor there are 2 options (A and B).

With option A, `autorun` does not react to `test.transition('c')`.
With option B, it works.

I looked at doc, and made many search, but it's hard to find references on `shallow`

If you could tell me why I'm wrong with option A, it would be very helpfull.

thanks

**Comment by urugator** [comment]
Mobx4 does not support dynamic object keys (adding/deleting props of object), use ObservableMap instead. Or Mobx5 if that's the option.

**Comment by urugator** [comment]
Shallow means that the prop and it's value are observable, but in case the value is array/map/object, it's entries are not observable.
```javascript
@observable.shallow states = { a: { nested: 'foo' } }
// autorun reacts to
this.states = { a: { nested: 'bar' } };
this.states[a] = { nested: 'bar' };
// autorun doesn't react to
this.states[a].nested = 'bar';
```
