### ISSUE TITLE
Performant undo without spies in MobX 4+

### ISSUE THREAD

**Issue by MLoughry** [mobxjs/mobx#1764]
I'm a contributor to [SatchelJS](https://github.com/Microsoft/satcheljs), which is in the process of upgrading MobX from v2 to v4. However, one of the functions in the current version is [`createUndo`](https://github.com/Microsoft/satcheljs/blob/master/src/legacy/createUndo.ts), which is built upon `spy` per #260. However, the latest MobX optimizes out all spies in production mode.
https://github.com/mobxjs/mobx/blob/be74b5f00a298c8946adebe5f2ffad945ee53fb2/src/core/spy.ts#L29-L31

Short of serializing the entire state tree (which would not be very performant, and would lose any object references), or migrating to `mobx-state-tree` (which is a non-trivial migration), is there any other way to implement an undo method in a performant manner?

**Comment by MLoughry** [comment]
Unfortunately, I don't think we can guarantee that the state is fully cycle-free. :(

**Comment by mweststrate** [comment]
I'm pretty sure it could be made to work with cycles as well,  feel free to
PR. I just didn't  bother in the first implementation as it had more edge
cases.

Op di 16 okt. 2018 19:43 schreef Michael Loughry <notifications@github.com>:
