### ISSUE TITLE
Flow functions are not type checked by FlowType

### ISSUE THREAD

**Issue by thejuan** [mobxjs/mobx#1769]
FlowType sees `this` inside a flow function as any and so no type checking takes place on this calls.
You can get around it by binding the generator function passed to flow.

`flow(function*(){yield 1;}.bind(this))`

It's easy to forget todo this and I haven't found a lint for it.
Are there any other suggestions on how to get type checking?
Is there a reason why flow isn't a decorator? Is it dangerous in some way if i added it locally?

**Comment by mweststrate** [comment]
The primary problem is that arrow functions cannot be combined with generators, so `.bind` seems to be a nice work around. 

`flow` can be used as decorator when using `asyncAction` from mobx-utils (no worries, it is just a wrapper, same implementation): https://github.com/mobxjs/mobx-utils#asyncaction. Bu this works only with TypeScript, as it doesn't work for babel legacy. Babel stage 2 non legacy decorators are under way, so will add it as todo there.

**Comment by cncolder** [comment]
for typescript, you can type `this` by hand:

```ts
class MyStore {
    @observable
    value = ''

    print = flow(function*(this: MyStore) {
        // type checking worked.
        console.log(this.value.toLowerCase())
    })
}
```

**Comment by thejuan** [comment]
You still loose the return type if you have one. We went with a Babel Transform to convert async methods to flow during transpilation.

**Comment by joshua1** [comment]
@mweststrate can We use mobx-task here for async actions then. would that suffice?

**Comment by mweststrate** [comment]
Closing for now, will be reopened once #1928 happens.

**Comment by davidgolden** [comment]
It seems to me that functions inside `flow` are bound to `this` as an arrow function would be:

```
const ctx = this
const args = arguments
const runId = ++generatorId
const gen = action(`${name} - runid: ${runId} - init`, generator).apply(
    ctx,
    (args as any) as Args
)
```
https://github.com/mobxjs/mobx/blob/master/src/api/flow.ts

Am I understanding this wrong?
