### ISSUE TITLE
[Question] How to use @inject using TypeScript?

### ISSUE THREAD

**Issue by warpdesign** [mobxjs/mobx#1778]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

Let's say I have this component:

```
interface Props {
    myProp: string;
}

class MyComponent extends React.Component<Props> {
}
```

That's being used this way:

```
class App extends React.Component {
    render() {
        return(
            <MyComponent myProp = "foo" />
      )
   }
}
```

Now, if I want to inject a store, here is what I would do:

```
interface Props {
    myProp: string;
}

@inject('myStore');
class MyComponent extends React.Component<Props> {
    render() {
      const param = this.props.myStore.param;

       return(
          <div>{param}</div>
      )
    }
}
```

```
class App extends React.Component {
    render() {
        return(
        <Provider myStore={myStore}>
            <MyComponent myProp = "foo" />
       </Provider> 
     )
   }
}
```

The problem is that TypeScript will then complain that myStore isn't defined in the Props interface of MyComponent. If I add it into the Props interface, I then have to add it when using my component, eg.:

```
<MyComponent myProp = "foo" myStore="myStore" />
```

So there's no point in using provider/injection if I have to add into my html again in every of my components.

The only solution I found was to declare the prop types of my component as `any`: this works as expected but then I loose the benefits of having strict type, like intellisense completion, etc...

Is there something I did wrong? Is there a way to use @inject without loosing strict typing?

Note that I am using TypeScript 3.1 and Mobx 3.2.1 Mobx-react 4.4.3.

**Comment by mweststrate** [comment]
See: https://github.com/mobxjs/mobx-react/issues/256
