### ISSUE TITLE
MobX 4.4 when() stops working after react native navigation transition

### ISSUE THREAD

**Issue by creativefctr** [mobxjs/mobx#1781]
Hi,
I am using 4.4 + upgraded JSC +React Navigation.
I put when() in the componentDidMount (or constructor) and it works fine and reacts to changes. But after the user navigates away from the page and then presses back button to return to the same page, when stops observing changes and stops calling the handler after values are changed.

I fixed this issue by calling when again in onDidFocus even for react navigation and it worked ... but ...
Is it the normal way or there is a bug here? Am I missing something?
Thanks

**Comment by urugator** [comment]
Are you aware that `when` is immediately disposed once the effect is invoked (predicate changed to true)?
Check whether the constructor/componentDidMount is actually invoked when navigating (`when` is re-created).
Create a simple reproduction in codebox.

**Comment by creativefctr** [comment]
Wow ... I did not know that about when! 
Many thanks
