### ISSUE TITLE
How do I bind a computed value?

### ISSUE THREAD

**Issue by obiwarn** [mobxjs/mobx#1795]
How do I bind a computed value to my store like with an arrow function action or with @action.bound?

I don't understand the related chapter in the manual (an example could help).

Background:
I write all my actions as arrow functions so I can call them from anywhere.
I would like to do the same for my computed values. Right now they are plain arrow functions (not getters) without a decorator.

**Comment by urugator** [comment]
Computed values are either represented as getter or boxed value (value is exposed via `boxedComputed.get()`).
In case of getter  `this` referes to an object on which the getter is invoked.
In case of boxed `computed(fn)`, `this` referes to whatever the invocation context of `fn` is:
```javascript
class Store {
   @observable observable1;
   @observable observable2;

   @computed get computed() {
       return this.observable1 +this.observable2;
   }
   boxedComputed = computed(() => this.observable1 + this.observable2);
}

const store = new Store();
console.log(this.computed);
console.log(this.boxedComputed.get())
```
You're probably misusing `computed`. Send an example of what you're trying to achieve.

**Comment by obiwarn** [comment]
@urugator Sorry for answering so late. Thank you very much.

I changed it to 
`public isSelected = () => computed(() => this.store.session.current === this).get();`
to avoid the get call in the view.
