### ISSUE TITLE
Data not changed/persisted after upgrade v3.3 to v5.5

### ISSUE THREAD

**Issue by foxhound87** [mobxjs/mobx#1800]
I  updated an app from mobx v3.3 to v5.5 and it seems that actions don't change the state in some cases, and a part of the react UI is not reacting to changes because the state is not persisting (basically it ramain as with the initial state). 

I also tried to remove the strict mode completely but still not working as expected. 

> dependencies (before update)

```
-    "mobx": "3.3.1",
-    "mobx-react": "4.3.3",
-    "mobx-state-tree": "1.4.0",
-    "react": "16.2.0",
-    "react-dom": "16.2.0",
```

> dependencies (now)

```
+    "mobx": "^5.5.2",
+    "mobx-react": "^5.3.6",
+    "mobx-state-tree": "^3.7.1",
+    "mobx-utils": "^5.0.4",
+    "react": "^16.6.0",
+    "react-dom": "^16.6.0",
```

Let me know if you have some suggestions.
Thank you.

**Comment by mweststrate** [comment]
@foxhound87 that is very little information. Can you provide something specific / reproducible? These packages are all out for quite while, so there is nothing obvious known that can be explained from just  looking at version numbers without any code

**Comment by mweststrate** [comment]
Those packages should all be compatible with mobx 4 as well

Op di 6 nov. 2018 om 16:24 schreef Claudio Savino <notifications@github.com

**Comment by foxhound87** [comment]
Which version of mobx-react and MST should I use with mobx 4?
I will provide the code as soon as I'm able to isolate and reproduce the issue outside the project.

**Comment by foxhound87** [comment]
I solved it, The new MST version has new types, and I was creating a model which failed, and because I was not correctly catching the errors, MST didn't show the thrown error.
