### ISSUE TITLE
how to use autorun second params scheduler?

### ISSUE THREAD

**Issue by ShootToThrill** [mobxjs/mobx#1801]
i don't want any  data used in the autorun changed ,the autorun run again 

just like the watch() in Vue  ,i decide watch which data and excute function 

i think maybe this can help 

![image](https://user-images.githubusercontent.com/17040474/48121069-e8a34080-e2ae-11e8-999f-83d7f77084c0.png)

but i did not find how to use scheduler in the doc

**Comment by mweststrate** [comment]
`scheduler` is a function, that receives as argument, and should invoke it whenever it feels appropiate. For example:

```
scheduler: run => {
  setTimeout(run, 1000)
}
```
