### ISSUE TITLE
mbox has no exported member 'configure'

### ISSUE THREAD

**Issue by warpdesign** [mobxjs/mobx#1802]
2. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

When trying to import configure in typescript without the following code:

```ts
import { configure } from 'mobx';
```

I get the following typescript error: `mobx has no exported member 'configure'`.

I am using the following package versions:

 - mobox: 3.6.2
 - typescript 3.1.4

**Comment by urugator** [comment]
`configure` was introduced in v4.0

**Comment by warpdesign** [comment]
That's what I thought but could not find the changelog.

@urugator There's no equivalent in v3?

**Comment by urugator** [comment]
What exactly do you want to configure?

**Comment by urugator** [comment]
Unfortunately, I think that only `useStrict(true)` is available which corresponds to `enforceActions: observed`

**Comment by warpdesign** [comment]
Thanks, I'll see what I can do with that.
