### ISSUE TITLE
trace utility logs invalid info

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#1803]
Hello.

I've found that `trace()` utility is useless in some cases. Check the code (also available as jsfiddle: https://jsfiddle.net/Strate/0wyp6vhk/11/):
```js
const {observable, computed, autorun, trace, runInAction} = mobx;

const a = observable.box(null, {name: "a"});

const b = computed(() => {
  void a.get();
  return 2;
}, {name: "b"})

const c = observable.box(null, {name: "c"});

const final = computed(() => {
  trace();
  c.get();
  b.get();
  return {}
}, {name: "final"})

autorun(() => {
  console.log(final.get());
})

runInAction(() => {
  a.set(1);
  c.set(1);
})

runInAction(() => {
  a.set(2);
  c.set(2);
})
```
Actual log becomes:
```
[mobx.trace] 'final' tracing enabled
{}
[mobx.trace] 'final' is invalidated due to a change in: 'b'
{}
[mobx.trace] 'final' is invalidated due to a change in: 'b'
{}
```

But expected log is:
```
[mobx.trace] 'final' tracing enabled
{}
[mobx.trace] 'final' is invalidated due to a change in: 'c'
{}
[mobx.trace] 'final' is invalidated due to a change in: 'c'
{}
```

Because `final` computed recomputes only when `c` changes, and `b` actually not changed.

**Comment by urugator** [comment]
I have noticed this as well. It seems like `invalidated` means that there is a "possible change" in the deps, not that it will actually "re-run" or "re-calculate".
Try to add `trace()` to autorun and return constant from `final`. Autorun will be `invalidated`, but won't re-run.
I quess it relates to how the change is propagated - the computeds are not immediately recalculated, so you end up with a tree of "possibly dirty" (invalidated) nodes, but their actual state is unknown until their value is actually requested by something (autorun) - which doesn't have to occur immediately during `a.set(1)`, but possibly later, based on scheduler? not exactly sure...

**Comment by FredyC** [comment]
@urugator Do you think we should do something about this or is it an obsolete problem too? Feel free to close.
