### ISSUE TITLE
Cannot build mobx - compilation error

### ISSUE THREAD

**Issue by mayorovp** [mobxjs/mobx#1810]
commit: a120190caeb6338404c742b5268c121d8de4c201
tsc version: 2.9.2

src/api/flow.ts:40:14 - error TS2345: Argument of type '"" | "Flow expects one 1 argument and cannot be used as decorator" | undefined' is not assignable to parameter of type 'string | boolean'.

location: https://github.com/mobxjs/mobx/blob/master/src/api/flow.ts#L40

**Comment by mayorovp** [comment]
After `yarn install` code was compiled.

**Comment by ItamarShDev** [comment]
should it be closed?
@mweststrate @mayorovp

**Comment by mweststrate** [comment]
Yes :)
