### ISSUE TITLE
Is it possible to encapsulate multiple observable changes together?

### ISSUE THREAD

**Issue by Tsury** [mobxjs/mobx#1813]
I have a class which depends on 2 different observables.
I also have a method which changes 2 said observables, one after the other.
This triggers 2 renders of my class.
Is it possible to create something like a transaction, which will only bubble the changes after said transaction is finished? 
Or maybe any other way to prevent the first render?

**Comment by mattruby** [comment]
See action and runInAction.

**Comment by Tsury** [comment]
Thanks!
