### ISSUE TITLE
Raise code quality in Ten minute, interactive MobX + React tutorial

### ISSUE THREAD

**Issue by zigacernigoj** [mobxjs/mobx#1815]
I have a:

1. [x] Question: 
2. [x] Issue:
3. [x] Idea:

I know this is Javascript, but still, can we raise the level of general code / coding style quality? Especially in tutorials, where all the beginners begin and copy the coding style.

If you started with an object oriented code, you should continue in that manner ... Namely, you should use ordinary functions or even setters to set / change the values of `completed`, `task` and `assignee`, not change them directly.

Example of first runnable code in [Ten minute, interactive MobX + React tutorial](https://mobx.js.org/getting-started.html):

```javascript
todoStore.addTodo("read MobX tutorial"); // using function to alter the todoStore object
console.log(todoStore.report());

todoStore.addTodo("try MobX"); // using function to alter the todoStore object
console.log(todoStore.report());

todoStore.todos[0].completed = true; // changing todoStore object property directly
console.log(todoStore.report());

todoStore.todos[1].task = "try MobX in own project"; // changing todoStore object property directly
console.log(todoStore.report());

todoStore.todos[0].task = "grok MobX tutorial"; // changing todoStore object property directly
console.log(todoStore.report());
```

Example of improved code

```javascript
class TodoStore {
  todos = [];

  get completedTodosCount() {
    return this.todos.filter(
      todo => todo.completed === true
    ).length;
  }

  report() {
    if (this.todos.length === 0)
      return "<none>";
    return `Next todo: "${this.todos[0].task}". ` +
      `Progress: ${this.completedTodosCount}/${this.todos.length}`;
  }

  addTodo(task) {
    this.todos.push({
      task: task,
      completed: false,
      assignee: null
    });
  }

  // added function to change the task "name" 
  changeTaskName(index, newName) { 
    this.todos[index].task = newName;
  }

  // added function to mark the task as complete
  markCompleted(index) {
    this.todos[index].completed=true;
  }
}

const todoStore = new TodoStore();
```

```javascript
todoStore.addTodo("read MobX tutorial");
console.log(todoStore.report());

todoStore.addTodo("try MobX");
console.log(todoStore.report());

todoStore.markCompleted(0);
console.log(todoStore.report());

todoStore.changeTaskName(1, "try MobX in own project");
console.log(todoStore.report());

todoStore.changeTaskName(0, "grok MobX tutorial");
console.log(todoStore.report());
```

**Comment by mattruby** [comment]
Thanks for the suggestions.  PRs are always welcome.

**Comment by goldylucks** [comment]
@mweststrate 

> Ideas for improved tutorial are welcome 

Not sure from your comment if you prefer @zigacernigoj style for the docs or not. I can prepare a small PR for one of the steps :)

**Comment by FredyC** [comment]
I want to point out that since this issue the site https://mobx-react.js.org was created. Perhaps it's not needed anymore? Or if you see what's missing and can be covered there, feel free to submit PR there.

**Comment by spion** [comment]
I think its fine to keep this as it is. Adding them to the class might imply that there is some mobx limitation (mobx will only track class methods), the way it works in the demo clearly eliminates that possibility.

Also note that the real title isn't "Ten minute, interactive MobX + React tutorial". Its "Ten minute introduction to MobX and React". Its not a tutorial on how to write apps, and its not meant to prescribe or suggest how to organize your code.

**Comment by goldylucks** [comment]
Material UI has a toggle between JS/TypeScript in their docs, it's pretty cool, tho much more work to maintain.

**Comment by FredyC** [comment]
@goldylucks I don't think they are actually maintaining two versions of codes. Converting TS to JS is merely about stripping types. It should be doable and I was thinking about it, but haven't got the time for it.

There is another more pressing issue to cover class components as well with the ultimate goal to trim down README in mobx-react repo and have a single site with all relevant information. It's not exactly a motivating task for me, because I don't use classes anywhere anymore.

**Comment by goldylucks** [comment]
@FredyC I meant to use the same idea of toggling like TS/JS, but for toggling between class and function syntax

**Comment by FredyC** [comment]
@goldylucks If you have some idea how to achieve that with Docz platform, it would be very appreciated.
