### ISSUE TITLE
Upgrade to TS 3 and improve flow() typing

### ISSUE THREAD

**Issue by ismailhabib** [mobxjs/mobx#1816]
The flow() typing is suboptimal since you we have to choose to either provide the type of the output (and having to manually provide all the argument types), or have the argument types inferred but use `Promise<any>` for the output. Inferring is also not possible due to the typing of Generator (this is a long discussion in TS project but it's a different matter).

Fortunately, with TS 3 there is this new generic rest parameters which not only will improve the typing but also make it much simpler. See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#generic-rest-parameters. I'm willing to create an MR once mobx is upgraded to TS 3.

Thanks!

**Comment by mweststrate** [comment]
Master now uses TS 3, feel free to contribute!

**Comment by ismailhabib** [comment]
https://github.com/mobxjs/mobx/pull/1825

**Comment by mweststrate** [comment]
released in 4.8.0 / 5.8.0

**Comment by mweststrate** [comment]
Thanks for the PR!
