### ISSUE TITLE
Support replace process.env.NODE_ENV using rollup-plugin-replace

### ISSUE THREAD

**Issue by thdk** [mobxjs/mobx#1819]
I have mobx 5.6 and i see the following line in mobx.module.js

```
 if (testCodeMinification.name !== "testCodeMinification" &&
         process.env.NODE_ENV !== "production") {
         console.warn(
         // Template literal(backtick) is used for fix issue with rollup-plugin-commonjs rollup/rollup-plugin-commonjs#344
         "[mobx] you are running a minified build, but 'process.env.NODE_ENV' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle");
     }
```

 The comment regarding the template literal is there, but the line below
 still uses the double quotes instead of backticks.

 Did the fix from issue #1724 got lost somewhere?

Expected:

`[mobx] you are running a minified build, but 'process.env.NODE_ENV' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle`

 Note: The string *process.env.NODE_ENV* is being replaced with
 *'development'* or *'production'* by the plugin [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace).

The code looks like below in my bundle:

```
if (testCodeMinification.name !== "testCodeMinification" &&
	        'development' !== "production") {
	        console.warn(
	        // Template literal(backtick) is used for fix issue with rollup-plugin-commonjs https://github.com/rollup/rollup-plugin-commonjs/issues/344
	        "[mobx] you are running a minified build, but ''development'' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle");
	    }
```

Note the double single quotes around 'development'. It works now but the comment line suggest backtick character instead of the double quote.

**Comment by mweststrate** [comment]
As far as I can see it is still in there in the source: https://github.com/mobxjs/mobx/blob/fa09fa64ee4d0d91801a33f3c22dbbbaa21ce15b/src/mobx.ts, that comment is just to work around a rollup issue. If you are seeing bundled code you are already passed that and the comment is further irrelevant. 

That being said, I am not entirely sure what your question is :).

**Comment by mweststrate** [comment]
Closing for now, as it seems to be a question, not a problem at first sight.

**Comment by mweststrate** [comment]
That's the compiled code, the backticks are there for correct processign by
rollup, not for the end result

Op do 27 dec. 2018 om 14:40 schreef Vadym Borodin <notifications@github.com

**Comment by borodean** [comment]
@mweststrate yes, and when some other Rollup-based project that depends on MobX imports it, the `mobx.module.js` is being imported, and that project's Rollup breaks.

**Comment by borodean** [comment]
(Yet it feels more like `rollup-plugin-replace` and `rollup-plugin-node-resolve` limitation, not the one of MobX.)
