### ISSUE TITLE
Why does MobX 5 array still have the index violation issue?

### ISSUE THREAD

**Issue by vilic** [mobxjs/mobx#1822]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [x] Issue

```
[mobx.array] Index out of bounds, 1 is larger than 0
```

https://runkit.com/embed/56jty1h3u27y

**Comment by mweststrate** [comment]
There are a few reasons
1. Nobody took the effort to remove it :)
2. This keeps feature parity between MobX 4 and 5, so that it is easier to migrate from 5 back to 4, if your browser support for example demands it
3. Imho out-of-bound assignments that result in sparse arrays are a bad practice anyway :).

**Comment by vilic** [comment]
@mweststrate The 2nd reason doesn't look valid to me, because of the 3rd one (as most of the time we don't write out-of-bound assignment). 😂 

I am encountering this because of a third-party library https://github.com/flitbit/diff:

> elements in arrays are now processed in reverse order, which fixes a few nagging bugs but may break some users

Will happy to send a PR for this if you like.

**Comment by mweststrate** [comment]
weird, why would a diff need out of bound assignments? Is .slice() your
array first a simple work around?

Op vr 30 nov. 2018 om 15:20 schreef vilicvane <notifications@github.com>:

**Comment by vilic** [comment]
@mweststrate Ahh, unfortunately not a simple workaround in my case. The object structure is unpredictable (it's like updating/restoring custom objects between versions). Thanks though.
