### ISSUE TITLE
Issue with generic types on action

### ISSUE THREAD

**Issue by tv1ster** [mobxjs/mobx#1829]
I have a:

2. [x] Issue:
  * [x] **Provide error messages including stacktrace**

TypeScript error `Type '{}' is not assignable to type 'number'.`

  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**

Seems like generics for `action` not really working well. In real project I am triggering some simple `action` on rxjs subscription. But I created small **[example](https://www.typescriptlang.org/play/index.html#src=interface%20IActionFactory%20%7B%0D%0A%20%20%20%20%3CA1%2C%20R%2C%20T%20extends%20(a1%3A%20A1)%20%3D%3E%20R%3E(fn%3A%20T)%3A%20T%0D%0A%20%20%20%20%3CT%20extends%20Function%3E(fn%3A%20T)%3A%20T%0D%0A%7D%0D%0A%0D%0Aconst%20action%3A%20IActionFactory%20%3D%20function%20(fn)%20%7B%0D%0A%20%20%20%20return%20fn%3B%0D%0A%7D%0D%0A%0D%0Afunction%20actionOnResolve%3CT%3E(dummy%3A%20T%2C%20fn%3A%20(val%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20return%20new%20Promise%3CT%3E((res%2C%20rej)%20%3D%3E%20res(dummy))%0D%0A%20%20%20%20%20%20%20%20.then((val)%20%3D%3E%20fn(val))%3B%0D%0A%7D%0D%0A%0D%0Alet%20someNumber%20%3D%200%3B%0D%0A%0D%0AactionOnResolve(4%2C%20action((val)%20%3D%3E%20someNumber%20%3D%20val))%3B)** to show you the issue. I tried to duplicate your code for `IActionFactory` so it will be easier to understand the rootcause.

  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?

I expect TS to not throw error, because it have already all info about my types.

3. [x] Idea:
  * [x] What problem would it solve for you?

For real, problem is not so huge, I just need to define some types for `action`, and TS will understand what is going on. But it would be great, if everything would work without strict types declaration.

  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

I found out, that issue will dissappear, if I will move generic types at top, like **[here](https://www.typescriptlang.org/play/index.html#src=interface%20IActionFactory%20%7B%0D%0A%20%20%20%20%3CT%20extends%20Function%3E(fn%3A%20T)%3A%20T%0D%0A%20%20%20%20%3CA1%2C%20R%2C%20T%20extends%20(a1%3A%20A1)%20%3D%3E%20R%3E(fn%3A%20T)%3A%20T%0D%0A%7D%0D%0A%0D%0Aconst%20action%3A%20IActionFactory%20%3D%20function%20(fn)%20%7B%0D%0A%20%20%20%20return%20fn%3B%0D%0A%7D%0D%0A%0D%0Afunction%20actionOnResolve%3CT%3E(dummy%3A%20T%2C%20fn%3A%20(val%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20return%20new%20Promise%3CT%3E((res%2C%20rej)%20%3D%3E%20res(dummy))%0D%0A%20%20%20%20%20%20%20%20.then((val)%20%3D%3E%20fn(val))%3B%0D%0A%7D%0D%0A%0D%0Alet%20someNumber%20%3D%200%3B%0D%0A%0D%0AactionOnResolve(4%2C%20action((val)%20%3D%3E%20someNumber%20%3D%20val))%3B)**, but I'm not sure about full impact of this change, so decided ask you about this issue. Maybe I'm doing something wrong? Because I'm not fully understand, why do we need these types

```
    <A1, R, T extends (a1: A1) => R>(fn: T): T & IAction
    <A1, A2, R, T extends (a1: A1, a2: A2) => R>(fn: T): T & IAction
    <A1, A2, A3, R, T extends (a1: A1, a2: A2, a3: A3) => R>(fn: T): T & IAction
    <A1, A2, A3, A4, R, T extends (a1: A1, a2: A2, a3: A3, a4: A4) => R>(fn: T): T & IAction
    <A1, A2, A3, A4, A5, R, T extends (a1: A1, a2: A2, a3: A3, a4: A4, a5: A5) => R>(fn: T): T &
        IAction
    <A1, A2, A3, A4, A5, A6, R, T extends (a1: A1, a2: A2, a3: A3, a4: A4, a6: A6) => R>(fn: T): T &
        IAction
```

while we can use only

```
<T extends Function>(fn: T): T & IAction
```

**Comment by mweststrate** [comment]
Closing as duplicate
