### ISSUE TITLE
[Docs] Views as Backend Integration

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#183]
In http://mobxjs.github.io/mobx/intro/concepts.html:

> Views are all forms of data that can be derived from the state without any further interaction. Views exist in many forms:
> 
> - The user interface.
> - Derived data, such as the amount of todos left.
> - Backend integrations like sending changes to the server.

Backend integration is a view? I do it using `autorun`?

**Comment by mweststrate** [comment]
Only the submitting part. You can do it manually when you press a save
button for example. But what we did in several projects is introduce a
@computed asJson property on objects (which is just another view on the
data, like the UI), and use autorun(Async) to submit it automatically to
the server when the json representation changes (which will change if
observable properties inside it are changed)

Op wo 13 apr. 2016 om 04:44 schreef Héliton Nordt <notifications@github.com

**Comment by hnordt** [comment]
Awesome, thank you!
