### ISSUE TITLE
ObservableArrayAdministration.dehanceValues does not dehance last value

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx#1839]
Originally found by @tarno0se at mobx-state-tree: issue [#1105](https://github.com/mobxjs/mobx-state-tree/issues/1105)

When array.lenght === 1, ```dehanceValues()``` skips dehancing of last ```shift()/pop()```'ed value.

**Comment by mweststrate** [comment]
released in 4.8.0 / 5.8.0
