### ISSUE TITLE
observable.map.replace doesn't seem to work for [[k,v], [k,v]] form

### ISSUE THREAD

**Issue by sis-dk** [mobxjs/mobx#1842]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:
3. [ ✔️] Issue:
  * [ ] Elaborate on your issue. What behavior did you expect?
         
              `
                  const newMap = [['a', 'hi'], ['b', 'hello']]
         
                  @action setMyMap(myNewMap) {
                      if(this.myMap)
                            this.myMap.replace(myMap) //This is not triggering re-render
                      else
                            this.myMap = observable.map(myNewMap)
                   }

                   this.setMyMap(newMap);
              `
            
               It started working when instead of    `this.myMap.replace(myMap)`, I did a
               `
                    this.myMap.clear()
                    this.myMap.merge(myNewMap)
               `
            
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
      
      MobX - 5.7.0

**Comment by fi3ework** [comment]
```js
    this.myMap.replace(myMap) //This is not triggering re-render
```
you may want to pass `myNewMap`, but you passed `myMap`?

and your second way which works passed into `myNewMap`
```js
this.myMap.clear()
this.myMap.merge(myNewMap)
```

**Comment by ItamarShDev** [comment]
also, is `this.myMap` and observable?

**Comment by mweststrate** [comment]
Closing for the lack of activity

**Comment by CubedEye** [comment]
@mweststrate Can confirm this is still a bug in 5.8.0. We are using replace in a sorting context to reorder a map of models by their ids.

Calling `_setModels `with a reordered array doesn't trigger a reorder:
```
_models = observable.map(new Map(), { deep: false });
_setModels(modelsArray) {
    const newModels = modelsArray.map(model => [model.id, model]);
    this._models.replace(newModels);
}
```

However, this does correctly trigger the rerender:
```
_models = observable.map(new Map(), { deep: false });
_setModels(modelsArray) {
    const newModels = modelsArray.map(model => [model.id, model]);
    this._models.clear();
    this._models.merge(newModels);
}
```
