### ISSUE TITLE
Mobx 5.8.0 build error, downgrade to 5.7.0 fixed my problem

### ISSUE THREAD

**Issue by wqj97** [mobxjs/mobx#1843]
I have an issue:
Mobx 5.8.0 Build Error
```
../../node_modules/mobx/lib/api/flow.d.ts:9:62 - error TS2370: A rest parameter must be of an array type.
export declare function flow<T, U extends any[]>(generator: (...args: U) => FlowIterator<any>): (...args: U) => CancellablePromise<T>;
```
![image](https://user-images.githubusercontent.com/18662395/49924497-74813b80-fef1-11e8-8d17-21823904497b.png)

**Downgrade to 5.7.0 fix my problem.**

Hope to fixed this problem;

**Comment by mweststrate** [comment]
Looks like you are on TypeScript 2, consider upgrading to 3 (in my
experience the impact is very minor).

Op do 13 dec. 2018 om 09:11 schreef 万千钧 <notifications@github.com>:

**Comment by fi3ework** [comment]
Actually in TypeScript 3.2.1. There's still an error when running `yarn run quick-build`. 😅
```
src/api/flow.ts:25:86 - error TS2345: Argument of type 'IArguments' is not assignable to parameter of type 'U'.

25         const gen = action(`${name} - runid: ${runId} - init`, generator).apply(ctx, args)
                                                                                        ~~~~


Found 1 error.

error Command failed with exit code 2.
```
TS: 3.2.1

**Comment by mweststrate** [comment]
@fi3ework fixed and pushed (was introduced by a non-optimal merge order). But note that that issue is completely unrelated to the issue reported in this thread, so for future questions on that one please open a new issue.

**Comment by fi3ework** [comment]
My bad, ack 😅

**Comment by wqj97** [comment]
Thx~

**Comment by nhsiehgit** [comment]
So looks like the solution here is to upgrade TS to 3?

should this change have been a minor version bump then?

**Comment by mweststrate** [comment]
That is a good question, semver doesn't really capture changes in tool or
peer dependencies. So in the MobX repositories for now we followed the most
common best practice used by other TypeScript based projects: a minor
update (there are no breaking api's, semantics or migration guides, but a
peer dependency upgrade (in this case TS) is required, as stated in the
changelog)

Op wo 26 dec. 2018 om 21:41 schreef Nathan Hsieh <notifications@github.com>:
