### ISSUE TITLE
Make console.log show the toJS version directly.

### ISSUE THREAD

**Issue by wahlforss** [mobxjs/mobx#1845]
IDEA: Make console.log of mobx proxy show the js version, not the proxy version. Using toJS is really cumbersome. It would be better if you had to use a function to get the version you get now, instead of the opposite.

**Comment by urugator** [comment]
I don't think that's possible without monkey patching `console.log`

**Comment by ItamarShDev** [comment]
sadly, seems like it :(

**Comment by fi3ework** [comment]
Seems like hard to do that without hack `console.log`.
Maybe it is possible to add a util function which use `toJS` convert Proxy to plain object automatically. But seems like no better than `toJS`.
Or add a switch to control weather to monkey patch `console.log` for debugging?

**Comment by mweststrate** [comment]
For flat de-proxying, one can simply spread the object; `console.log({ ...myObject })`, for deep, use `toJS` as suggested, `console.log(toJS(myObject))`.
