### ISSUE TITLE
how to send multiple request at the same time use flow approach?

### ISSUE THREAD

**Issue by lewayjack** [mobxjs/mobx#1852]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

i'm using **mobx**  with  **flow** approach to send request.i'd like to know how to _**send multiple request at the same time**_ use flow approach.
here is my code
```
 parallelRequest = flow(function *() {
    try {
      const data = yield [
        axios.get(url1),
        axios.get(url2),
      ]
      this.data0 = data[0] // just the Promise Object
      this.data1 = data[1] // not the data i want
      console.log(data) // [ [[Promise]], [[Promise]] ]
    } catch (error) {
      console.error(error)
    }
  })
```

The following code works, but I don't know if this is right to use a nested flow approach?
```
requestA =  flow(function *() {
     const data = yield axios.get(url1)
     this.data0 = data
  })
 requestB =  flow(function *() {
     const data = yield axios.get(url2)
     this.data0 = data
  })
 
 parallelRequest = flow(function *() {
    try {
      const data = yield [
        requestA()
        requestB()
      ]
      console.log(data) // [ [[Promise]], [[Promise]] ]
    } catch (error) {
      console.error(error)
    }
  })
```

or,is there a better way to  parallel request?
by the way ,THX for create mobx , which makes my work much more easier : )

**Comment by mayorovp** [comment]
Use Promise.all before yield...

Nested flow is ok.

**Comment by lewayjack** [comment]
thanks @mayorovp 
i add yield to each request and the code worked
```
      const data = yield [
        yield axios.get(url1),
        yield axios.get(url2)
      ]
      console.log(data)
```

**Comment by mayorovp** [comment]
@lewayjack nope, you code is not working. It is not parallel now. You need to use Promise.all

**Comment by lewayjack** [comment]
@mayorovp  thanks for pointing out the mistake.It is not parallel ,my fault.
would you kindly show me the example code .i tried  following code ,but get a error

_TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))_
```
const data = yield Promise.all(
        axios.get(url1),
        axios.get(url2)
      )
console.log(data) //  error
```

**Comment by mayorovp** [comment]
@lewayjack https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by lewayjack** [comment]
@mayorovp i see,i lost the square brackets 😂. thanks for the kindly help again.
```
const data = yield Promise.all([
        axios.get(url1),
        axios.get(url2)
      ])
console.log(data) 
```
