### ISSUE TITLE
Using `decorate` results in loss of type information in a typescript project

### ISSUE THREAD

**Issue by michalczaplinski** [mobxjs/mobx#1854]
Here's a minimal reproduction repo: https://github.com/michalczaplinski/ts-mobx-reproduction

The project is based on fresh `create-react-app` with only typescript and mobx added.

```
    "mobx": "^5.8.0",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.2",
    "typescript": "^3.2.2"
```

```
// Store.ts

import { observable, decorate } from "mobx";

class TestStore {
  x: number

  constructor() {
    this.x = 1
  }
}

export default decorate(TestStore, {
  x: observable
})
```

When using in a typescript project, a store defined in a separate file and imported into another file, fails with: 

```
Type error: Cannot use 'new' with an expression whose type lacks a call or construct signature.  TS2351

    3 | import Store from './Store';
    4 |
  > 5 | const store = new Store();
      |               ^
    6 |
    7 | class App extends Component {
    8 |   render() {
```

Strangely enough, when defining the Store in the same file as `App.ts` there is no issue. It might be a problem with the default typescript configuration provided by CRA 🤷‍♂️ ...

**Comment by mayorovp** [comment]
decorate now returns void in this case:

    export function decorate<T>(clazz: new (...args: any[]) => T, decorators: { ... }): void

so it can be used this way:

    decorate(TestStore, {
        x: observable
    });
    export default TestStore;

**Comment by michalczaplinski** [comment]
@mayorovp Have you looked at the reproduction repo? The whole issue is about the fact that it cannot be used this way.

**Comment by michalczaplinski** [comment]
ok, thanks @mayorovp 🙂 
I think it would be worth mentioning explicitly in the docs that the decorator mutates the original class and does not return a new object!
