### ISSUE TITLE
MobX documentation impossible to read on iOS mobile

### ISSUE THREAD

**Issue by cmwelsh** [mobxjs/mobx#1855]
Using iPhone SE with Chrome 71.0.3578.89. All I can see is the sidebar and a sliver of content.

https://mobx.js.org/index.html

https://imgur.com/gallery/hxJ6M4j

**Comment by fi3ework** [comment]
Click the drawer button in the top right corner and the catelog will be retracted.

**Comment by cmwelsh** [comment]
Thanks. That worked. That’s really unintuitive.

**Comment by cmwelsh** [comment]
Perhaps it should be hidden by default? I don’t recall seeing any mobile sites that work like this.

**Comment by mweststrate** [comment]
See also #1859, I think we might migrate from gitbook soon. It's UI doesn't feel really up to par anymore
