### ISSUE TITLE
Introduce global error handling override for testing purposes

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#186]
Computed values and autorun's should never throw. If they do, MobX prints warnings. This is annoying during testing expected exceptions. Make it possible to override this:

`mobx.extras.setGlobalErrorHandler(func, preserve=true)`

It should only be possible to register one handler. This handler will be reset on `mobx.extras.resetGlobalState()` (another test utility to reset all numbers, caches etc). Except `preserve` is set to `true`.

**Comment by aksonov** [comment]
i have problem with console.error(“[mobx] unexpected exception …….”)
The problem that React Native outputs red screen with that message and i don’t see real error.
Could you make it configurable - i prefer to see original exception

**Comment by mweststrate** [comment]
`mobx@2.3.3` changed the logging behavior from error to warning to avoid long stack traces in the output and fix RN error screen isssues. If that doesn't suffice feel free to reopen this issue!

**Comment by markflorisson** [comment]
I'm using mobx 3.1.0 and mobx-react 4.1.0, but any exceptions from from render() are not shown in the react native error screen, only the mobx warning "[mobx] Encountered an uncaught exception ...". This makes debugging really difficult.

Any ideas why this this happens? How can I disable the mobx logging entirely?

**Comment by mweststrate** [comment]
I think the latest mobx-react version, `4.1.2` might fix this as well. Can anyone confirm?

**Comment by markflorisson** [comment]
Using `4.1.2`, it logs two things to the output stream (`react-native log-{android,ios}`):

```
'[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: \'Reaction[HomeScreen#0.render()]', { [Error: This is a test!]
line: 110957,
column: 31,
sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
``` 

and 

```
{ [Invariant Violation: HomeScreen.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.]
name: 'Invariant Violation',
framesToPop: 1,
line: 2181,
column: 12,
sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
```

However, the console.error shows only the following:

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[HomeScreen#0.render()]'
```

This useful error is the one captured by the first log output error, as it has captured the actual exception (Error('This is a test!')). However, the line number is not mapped, and you have to dig through the console output to find it, which is quite a hassle.

Maybe the only way to get the right exception to show it to not log it?

**Comment by mweststrate** [comment]
That error should not be thrown anymore with the latest mobx-react, can you double you have the latest version?

**Comment by markflorisson** [comment]
I think it was some weird yarn/npm caching issue. Deleted and reinstalled and now it works fine. Thanks a lot!
