### ISSUE TITLE
mobx documentation layout bug

### ISSUE THREAD

**Issue by billbaincodes** [mobxjs/mobx#1860]
Hello,

When navigating to the docs for the first time, the layout displays normally.
https://i.imgur.com/hMQoB4X.png

But clicking any of the section links shifts everything.
https://i.imgur.com/TvuzaAk.png

I'd appreciate any insight on ways to fix this. Thanks!

**Comment by mweststrate** [comment]
Yeah, gitbook doesn't really cut it anymore at the moment it seems. Well probably migrate anywhere in the near future, see also #1859
