### ISSUE TITLE
Methods with @action.bound cannot be extended

### ISSUE THREAD

**Issue by mciastek** [mobxjs/mobx#1864]
It may be related to https://github.com/mobxjs/mobx/issues/379. With the latest version of MobX I can't extend method with `@action.bound` decorator used. I get `[mobx] @action fields are not reassignable` error from MobX.

Although, action override works with normal `@action`, when you apply a new context by `bind()` function. Consider this example code:

```es6
class Todo {
  constructor() {
    this.update = this.update.bind(this);
  }
  
  @action
  update() {}
  
  @action.bound
  remove() {}
}

class ExtendedTodo extends Todo {
  @action
  update() {
    super.update(); // works
  }

  @action.bound
  remove() {
    super.remove(); // throws "[mobx] @action fields are not reassignable"
  }
}
```

Is it by design?

---
FYI @stosiu

**Comment by mweststrate** [comment]
Don't bind methods in super classes, it doesn't mean in javascript what you
hope it means :-). If you call a method on super, the this should already
be correct, so there is no need to bind. Binding in a super class actually
means that you are potentially overridding your subclass method, as both
the super and subclass method are defined under the same name on the same
instance.

Op ma 7 jan. 2019 om 16:04 schreef Mirosław Ciastek <
notifications@github.com>:

**Comment by mweststrate** [comment]
So note that your update method doesn't work either, as your subclass
implementation is skipped! (just add a console.log to verify)

Op ma 7 jan. 2019 om 17:37 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by mweststrate** [comment]
Closing for now, will be reopened once #1928 happens.

**Comment by sndurkin** [comment]
Just FYI, the `core-decorators` library has implemented support for bound super methods within its `autobind` decorator (https://github.com/jayphelps/core-decorators/issues/20), and it seems to work fine when paired with a MobX `action`.
