### ISSUE TITLE
Create better error for missing decorated getters

### ISSUE THREAD

**Issue by jefffriesen** [mobxjs/mobx#1867]
In the case of using the decorate syntax (in an environment where decorators aren't enabled), there is a really confusing error message.

For example, in the documentation on how to not use decorators, you have this example:
```
class Timer {
  start = Date.now();
  current = Date.now();

  get elapsedTime() {
    return this.current - this.start + "milliseconds";
  }

  tick() {
    this.current = Date.now();
  }
}
decorate(Timer, {
  start: observable,
  current: observable,
  elapsedTime: computed,
  tick: action
});
```

If you delete the `get elapsedTime(){` function, you get this error:
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at Object.propertyCreator (mobx.module.js:596)
    at initializeInstance$$1 (mobx.module.js:373)
    at MobxStore.set [as activeFile] (mobx.module.js:358)
    at new MobxStore (MobxStore.js:33)
```
The problem is that the `elapsedTime: computed` property doesn't get deleted with the function, which is easy to do when they aren't co-located (without decorators). This keeps happening to me and I've memorized the error, but the first couple times where hard to track down. It seems like there is no intentional error checking - it just errors down the stack at instantiation of the class.  

I think it should error (give the dev a chance to clean up cruft) but give them more information why it's throwing an error.

Thank you

**Comment by mweststrate** [comment]
Computed properties should not be deleted, as it only removes the descriptor, but the computed value is still there, potentially leaking memory. (I think as a rule of thumb `delete` should never used in JavaScript, but that is a different point). 

The simple prevention for this is to mark the properties as non-configurable. Downside of that is that stubbing will be harder, but it might fix some other errors.

**Comment by mweststrate** [comment]
Fixed and released in 4.9.0 / 5.9.0

**Comment by mweststrate** [comment]
Oh sorry! I understood it as programmatically deleting :) Reopeneing.

Op di 22 jan. 2019 om 16:06 schreef Jeff Friesen <notifications@github.com>:

**Comment by mweststrate** [comment]
Yes, that is precisely why we keep configurable true in general, but in this specific case it can also lead to quite confusing bugs. Not that both spy and inheritance issues can be worked around by extracting the logic like: 

```
class X {
  @computed getMyFummies() { return this._getMyFummies() } 
  
_getMyFummies() { 
   /* actual logic here */ 
  }
```

That makes it both possible to inherit `_getMyFummies` and spying it.

**Comment by Android3000** [comment]
Oh nice -- if the observed properties involved in the computation are within `this._getMyFummies()`, the computed function will still be recomputed when they change? That's a great workaround - thanks!

**Comment by mweststrate** [comment]
Correct

Op di 22 jan. 2019 17:37 schreef Android3000 <notifications@github.com>:

**Comment by alendit** [comment]
1b0f5ed4b24844498152e90c08c6a3287fe468d5 breaks latest `mobx-state-tree`, see https://github.com/mobxjs/mobx-state-tree/issues/1143 .

**Comment by zetoke** [comment]
>Yes, that is precisely why we keep configurable true in general, but in this specific case it can also lead to quite confusing bugs. Not that both spy and inheritance issues can be worked around by extracting the logic like:

That quite breaks the flow of writing tests that we use in a company with `spyOn` in jest or manually mocking with `Object.defineProperty`.
And this workaround will work but it looks super weird (duplicating a lot of properties/fields) and we also need to rewrite a lot of places in the current projects.
Hmmm, can it be a kind of setting may be?

**Comment by evoyy** [comment]
https://github.com/mobxjs/mobx/commit/1b0f5ed4b24844498152e90c08c6a3287fe468d5 also broke some of my tests as I can no longer stub computed properties with sinon. Exception thrown: ````TypeError: Cannot redefine property````. The suggested workaround works fine for me.

**Comment by mweststrate** [comment]
@zetoke, I don't like settings in at all in generally, but it might actually be a nice idea in this case, to have it a 'test only' setting. Something like `mobx.configure({ enableStubbing: true })` ?

**Comment by r3nya** [comment]
Hey @mweststrate!

> 'test only' setting. Something like `mobx.configure({ enableStubbing: true })` ?

I guess it will work!

**Comment by zetoke** [comment]
@mweststrate Yeah, I think so. It looks perfect!

Agree with you, that usually it's not a good choice to add a new setting in general 😄 But here, I don't see an other way.

**Comment by jpalomar** [comment]
would it be fair to consider this revision: 
https://github.com/mobxjs/mobx/commit/f0473c83c75930406bc91699f6b9013d118b5c1e#diff-147a1f3618d08f1399ce092b72872853R328
a breaking change?  

could we release `5.9.1`\`4.9.3` version that reverts this back?  and release a new feature for `5.10.0`\`4.10.0` that includes the feature to configure Mobx with `mobx.configure({ canStub: true })`

**Comment by asaarnak** [comment]
Any news on this?
We currently use alot Object.defineProperty or jest.spyOn in tests and https://github.com/mobxjs/mobx/commit/1b0f5ed4b24844498152e90c08c6a3287fe468d5 prevents updating mobx.

**Comment by mweststrate** [comment]
PR is welcome :)

**Comment by goldylucks** [comment]
@mweststrate is it a good first task for a new maintainer? If so, I'll take a swing at it with some guidance :)

**Comment by FredyC** [comment]
@goldylucks The label "ready-to-be-implemented-by-volunteer" is exactly for that :)

**Comment by goldylucks** [comment]
challenge accepted!

**Comment by goldylucks** [comment]
@FredyC ,
I started poking around the relevant bits of code, and I see that [it's already configurable](https://github.com/mobxjs/mobx/blob/master/src/api/configure.ts#L12) and [tested](https://github.com/mobxjs/mobx/blob/master/test/base/strict-mode.js#L253).

What am I missing here?

It might be completely obvious, I'm new to the internals of mobx

**Comment by FredyC** [comment]
To be honest, I have no idea either :) I just briefly skimmed through here, apparently, there is some issue when interacting with mobx-state-tree. Perhaps you can start by creating a reproduction in CodeSandbox if that helps to discover the problem. It will allow you to switch between versions easily and see what brakes.

**Comment by goldylucks** [comment]
ok, if someone can provide some guidance I will look into it. I also haven't used MST

**Comment by wlindner** [comment]
I was having test failures after upgrading mobx in my app that uses mobx-state-tree. I couldn't stub getter properties that were mst views after the upgrade. I came across this thread and fixed it by putting this code in my test setup.
```
const mobx = require('mobx');
mobx.configure({ computedConfigurable: true });
```

Then I could stub out getter views this way.
```
sinon.stub(newBlock, 'hash').get(() => '000');
```
Which I got from sinon's docs https://sinonjs.org/releases/latest/stubs/#stubgetgetterfn

**Comment by andreipfeiffer** [comment]
If you get the `property is not declared configurable` error when using `Jest spyOn` on mobx `@computed` properties, you can add this:

```
import { configure } from "mobx";
configure({ computedConfigurable: true });
```

Thanks @wlindner ;)

PS: it's documented here https://mobx.js.org/refguide/api.html

**Comment by guerjon** [comment]
Hi @andreipfeiffer  yes, didn't realize that my setup test is call enzume-setup.ts, that is been set in setupTestFrameworkScriptFile in the jest config file. That works thank you.

**Comment by FredyC** [comment]
PR with a fix has been merged, but not released yet. Closing the issue.
