### ISSUE TITLE
enforceActions: 'always' stops working in conjunction with isolateGlobalState: true

### ISSUE THREAD

**Issue by choruk** [mobxjs/mobx#1869]
Hello! 👋 

I have a:

2. [x] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**

I created a minimal sample reproduction here: https://codesandbox.io/s/v8kkpjq8x7. If you remove `isolateGlobalState: true` from the configuration, then the "strict mode" errors start appearing in the console and the timer is no longer incremented. However, with `isolateGlobalState: true` in the configuration, no "strict mode" errors appear and the timer increments.

  * [x] Did you check this issue wasn't filed before?

I started down this path because we ran into a situation where the "strict mode" errors were only being thrown when two instances of MobX existed on the page (which is only on a subset of pages in our application). Any page that only had one instance of MobX worked just fine (i.e. no "strict mode" errors). I noticed a couple closed issues (https://github.com/mobxjs/mobx/issues/1473 seems like the most relevant), but they all seemed to indicate that the issue was fixed.

We have automated tests covering the code path in our application that was modifying observables outside of an action, but the tests were not failing. I noticed that removing the `isolateGlobalState` configuration option caused the tests to start to fail, so I decided to see if I could reproduce this issue outside of our application...and here we are 😅 

  * [x] Elaborate on your issue. What behavior did you expect?

I expect that if I set `enforceActions: 'always'` then MobX will _always_ enforce that observables must be modified in an action, regardless of whether `isolateGlobalState` is enabled or not.

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

I think you can see this from the code sandbox that I linked. One other data point: if I change the version of MobX in that sandbox to 4.1.0, then everything works as expected. I didn't exhaustively go through all MobX versions to figure out if others work / don't work, but we are using MobX 4.5.0 in our production application where we originally ran into this issue.

**Comment by mweststrate** [comment]
Confirmed the bug. Note that having two mobx instances sounds like a potential setup for trouble :sweat_smile:

**Comment by mweststrate** [comment]
Fixed and released in 4.9.0 / 5.9.0

**Comment by choruk** [comment]
Thanks for the quick fix! 

> Note that having two mobx instances sounds like a potential setup for trouble 😅

Haha yea 🙈
