### ISSUE TITLE
toJS different output from 4.8->4.9

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx#1875]
As discussed on Gitter: 
Given `@observable meta = new Map<string, any>();`

4.8 `toJS` outputs a js object, as it has been for ages.
https://codesandbox.io/s/pwrz28jzx7

4.9 `toJS` outputs an observable map.
https://codesandbox.io/s/jp0j98y0yy

There wasn't supposed to be any changes according to the changelog, so I'm guessing that something is borked.

**Comment by mweststrate** [comment]
Thanks for reporting! Fixed in 4.9.1. This was a regression introduced by a merge indeed! (Note that it depends on the module bundler whether the issue actually manifested)
