### ISSUE TITLE
findIndex for observable arrays are not in typings

### ISSUE THREAD

**Issue by DomiR** [mobxjs/mobx#1879]
In the following definition file findIndex is not available.

https://github.com/mobxjs/mobx/blob/aa1bf2099a1cbe5b593df12acb3d4a5c9957eac2/src/types/observablearray.ts#L32

**Comment by mweststrate** [comment]
`findIndex` is inherited from `Array`: https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

Whether you will having receive typings for it probably depends on your typescript compilation target (es5 or es6)

**Comment by DomiR** [comment]
Arg, thanks 🙏

PS: You are my hero, doing all the web and mobile stuff for a small startup and this wouldn't be possible without mobx. Thank you so much!
