### ISSUE TITLE
[mobx] Dynamic observable objects cannot be frozen]

### ISSUE THREAD

**Issue by jasuno** [mobxjs/mobx#1881]
<img width="1280" alt="screen shot 2019-01-23 at 5 03 21 pm" src="https://user-images.githubusercontent.com/29812661/51641002-105f8780-1f33-11e9-9abb-ef54842c1d2e.png">

**Comment by mweststrate** [comment]
Please follow the issue template.

**Comment by mweststrate** [comment]
Closing for the lack of information

**Comment by andreiTuduce** [comment]
I am having the same issue and it can be recreated as follows: 

The allVehicles variable is an array of objects;
```
    @observable allVehicles;

    @action setAllVehicles(arrayOfVehicles) {
        this.allVehicles = arrayOfVehicles;
    }
}
```

Then here the VehiclesStore.setSelectedObjects sets the selectVehicle to an observable variable inside the VehiclesStore,
```
selectVehicle(vehicleID) {
    let selectVehicle = VehiclesStore.objects.find(vehicle => vehicle.id === vehicleID);
    VehiclesStore.setSelectedObject(selectVehicle);
  }
```

I hope that this is information helps, and maybe if someone can help me or both of us with this issue i'll be grateful for all the help.

Have a nice day!
