### ISSUE TITLE
Repeated When

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx#1886]
I have a Idea. There is common pattern in my reactions: 
`reaction(() => client.online, online => online && ts.sync())`. 
Basically, it's just `when`, which is not autodisposes itself on first run. So, it can be done via `when` option named (e.g.) `repeated`. With it, my code will look as:
`when(() => client.online, () => ts.sync(), {repeated: true})`

  * [X] What problem would it solve for you?
Code readability and complexity.
  * [X] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
Yep, it just additional `when` option, which can be useful for many cases.
  * [X] Are you willing to (attempt) a PR yourself?
Maybe, it shouldn't be difficult.

**Comment by mweststrate** [comment]
I think the syntactical sugar here is so straight-forward that it doesn't
justify expanding the api for it. Rather, it confuses two concepts which
are now clearly deliniated: one time? -> when. Multiple times? -> reaction

Op di 29 jan. 2019 om 14:44 schreef Иван Плесских <notifications@github.com

**Comment by Amareis** [comment]
Hmm. My second approach was `reactionWhen`, which is can be added to mobx-utils.

**Comment by nunocastromartins** [comment]
My two cents: call it `whenever` and just declare it yourself:
```ts
function whenever(whenFn: () => boolean, doFn: () => void): () => void {
  return reaction(whenFn, val => val && doFn());
}
```
Example usage:
```ts
 whenever(() => client.online, () => ts.sync());
```

**Comment by mweststrate** [comment]
Closing, the pattern is hopefully so straight forward I don't see any need to standardize this

**Comment by mweststrate** [comment]
Thanks for sharing the idea nonetheless!
