### ISSUE TITLE
Mobx testing

### ISSUE THREAD

**Issue by mishk0** [mobxjs/mobx#1888]
Since v5.9.0 computed properties became not configurable. That's probably why Sinon.js throws an error, while stubbing a getter: ```TypeError: Cannot redefine property```.

Are there any ways to stub/spy a getter, best practices?

**Comment by mweststrate** [comment]
@mishk0 

```javascript
class X {

   @computed get nonStubable() {
     return this._stubablle()
   }

   /* private */ stubable() {
      // this one is stubable, but the indirection won't loose any of the semantic benefits of `nonStubable` 
   }
}
```

**Comment by ItamarShDev** [comment]
@mishk0 Any updates on this issue?

**Comment by mishk0** [comment]
@mweststrate thanks!
