### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by franciscojfs** [mobxjs/mobx#1889]
Hello!

I saw the issue #1582 and tried to upadate my JSC version to the last as recomended, but that not worked. When I tried to lauch the remote debugging to copy the stack trace the application begin to work. If I stop it the application crashes.

Here is my package.json:

```json
{
  "name": "person",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "jsc-android": "236355.1.1",
    "@expo/vector-icons": "^9.0.0",
    "mobx": "^5.9.0",
    "mobx-react": "^5.4.3",
    "native-base": "^2.10.0",
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-firebase": "^5.2.1",
    "react-native-gesture-handler": "^1.0.15",
    "react-navigation": "^3.0.9",
    "react-timer-mixin": "^0.13.4"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by mweststrate** [comment]
Can you share what the exact version of mobx is you are using, and the error thrown?

**Comment by Bradzer** [comment]
I faced the same issue too. I got rid of it by downgrading my mobx to version 4 and I'm waiting for the bug to be fixed in version 5.

**Comment by franciscojfs** [comment]
@mweststrate

"mobx": "^5.9.0"
"mobx-react": "^5.4.3" 

![screenshot_20190209-110410](https://user-images.githubusercontent.com/30843274/52521201-beb93b80-2c5a-11e9-836a-fb8da7a29f45.png)

**Comment by franciscojfs** [comment]
@Bradzer I will give this a try. Thank you!

**Comment by mweststrate** [comment]
If the error is `Symbol` not defined, that sounds like the JSCore update is not applied / didn't succeed, as it means that a core language feature is still missing. I don't think we can change much about that from our side, beyond maintaining 4.x for a very long time, which was the plan already :).
