### ISSUE TITLE
Creating a "boxed" computed value evaluates the expression immediately

### ISSUE THREAD

**Issue by nunocastromartins** [mobxjs/mobx#1890]
I have a question: creating a "boxed" computed value (`computed(exp)`) evaluates the expression (`exp`) immediately, without `.get()` ever being called. Is this expected behaviour? Example:

```typescript
let count = 0;
const comp = computed(() => count++);
console.log(count); // Logs: 1 (`comp.get()` never called)
```

I expected computed values to always be lazy when evaluating their expressions, is this a wrong assumption? Should I instead use an observable object with a computed property to represent a lazy "boxed" computed value? Example:

```typescript
let count = 0;
const obs = observable({get comp() { return count++; }});
console.log(count); // Logs: 0 (`obs.comp` never accessed)
```

Honestly, the difference in behaviour of these two examples is counter-intuitive to me. If this is indeed expected behaviour, would you explain the reasoning behind it?

Tested in MobX 4.9.2.

**Comment by urugator** [comment]
Can't reproduce:
https://codesandbox.io/s/987xko68rp

**Comment by nunocastromartins** [comment]
Interesting, you're absolutely right. Lack of proper testing on my end.

I was actually testing MobX using Node's REPL and I wasn't assigning the `computed` to a variable. For example, if you copy/paste the following into Node's REPL, it results in a `1` being logged:
```ts
const {computed} = require('mobx');
let count = 0;
computed(() => count++);
console.log(count);
```

Turns out that when the REPL prints the result of `computed(exp)`, it apparently triggers a computation of `exp`. I don't know if this can be classified as a bug in the Node's REPL, but it did throw me off.

Thanks for the input and sorry for the noise!
