### ISSUE TITLE
How to implement observable ref withou decorators?

### ISSUE THREAD

**Issue by franciscojfs** [mobxjs/mobx#1892]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I what to use MobX to manage my React Navigation, but I was not able to find out how to do that without decorators. 

```javascript
class NavigationStore {
  @observable headerTitle = "Index"
  @observable.ref navigationState = {
    index: 0,
    routes: [
      { key: "Index", routeName: "Index" },
    ],
  }

  // NOTE: the second param, is to avoid stacking and reset the nav state
  @action dispatch = (action, stackNavState = true) => {
    const previousNavState = stackNavState ? this.navigationState : null;
    return this.navigationState = AppNavigator
        .router
        .getStateForAction(action, previousNavState);
  }
}
```
I'm trying to acheive that based on [that](https://hackernoon.com/react-navigation-with-mobx-2064fcdaa25b) article

**Comment by ItamarShDev** [comment]
Here you go: https://mobx.js.org/refguide/modifiers.html
use `decorate`
```javascript
decorate(Person, {
    headerTitle: observable,
    navigationState: observable.ref,
})
```

**Comment by ItamarShDev** [comment]
@franciscojfs Please report if this is the solution you need and close this issue\

Thank you

**Comment by franciscojfs** [comment]
Thank you!
