### ISSUE TITLE
What does the value res() of a state property mean ?

### ISSUE THREAD

**Issue by Bradzer** [mobxjs/mobx#1893]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

When I log one of my state property I see the value **res()** while I'm expecting instead a boolean one.
What does the res() value mean ?

**Comment by ItamarShDev** [comment]
Please supply a codesandbox example

**Comment by Bradzer** [comment]
@ItamarShDev 
I'm working with React-native actually

**Comment by ItamarShDev** [comment]
Stiil, can you create the store on codesandbox to reproduce said `res`?

**Comment by Bradzer** [comment]
I still don't know what was that `res()` when I log my value but I found a way to get rid of it.
So I'm closing the issue.
