### ISSUE TITLE
Parameter of action is undefined when logged

### ISSUE THREAD

**Issue by Bradzer** [mobxjs/mobx#1896]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I have an input text component and I use a mobX action to update it's value.
However, when I log the action parameter which is the new value of the the input text I get `undefined`.

Here's my action code:

```
    updateStartingLettersText = action((changedText) => {
        reactotron.logImportant('changed text is : ', changedText) //prints changed text is undefined
        this.startingLettersText= changedText
    })
```

**Comment by ItamarShDev** [comment]
Can you please supply a codesandbox example of your problem?

**Comment by Bradzer** [comment]
@ItamarShDev Here's the link https://codesandbox.io/s/w25q96225l
Like I said in a previous question I'm using React native though.

**Comment by urugator** [comment]
`onChangeText={() => this.onStartingLettersTextChanged()}`
=>
`onChangeText={this.onStartingLettersTextChanged}`

**Comment by Bradzer** [comment]
thank you @urugator 
You're the man ;)
