### ISSUE TITLE
Autorun does not trigger in some cases

### ISSUE THREAD

**Issue by Bradzer** [mobxjs/mobx#1897]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

My achievement is to persist data using autorun.

```
class Settings extends React.Component {

    store = this.props.store

    screenAutorun = autorun(() => {
        reactotron.logImportant('autorun is running')
        Realm.open({})
        .then((realm) => {
            realm.write(() => {
                realm.objects('settingsScreen').filtered('pk = 0').update('updatedIndex', this.store.selectedIndex)    //persistence instruction
            })
        })
        .catch((error) => console.log(error))
    })
//...other stuff
}
```
The code above on triggers once when I enter the component and then not anymore even when `this.store.selectedIndex` has changed.

However, the following autorun is triggered everytime `this.store.selectedIndex` changes as expected.

```
class Settings extends React.Component {

    store = this.props.store

    screenAutorun = autorun(() => {
        reactotron.logImportant('autorun is running')
        reactotron.logImportant(this.store.selectedIndex)
    })
//...other stuff
}
```

Why such behavior in the first case ?

**Comment by urugator** [comment]
In the first case the `this.store.selectedIndex` is accessed inside a closure, which doesn't run inside the `autorun` - it is deffered via `then`. So it's actually accessed outside of tracking context.
I suggest using `reaction` instead as it makes clear what are the depedencies and what is the effect:
```javascript
reaction(
  () => this.store.selectedIndex, // collect dependencies
  index => persist({ index }) // runs only if deps actually changed
})
```
The original can be fixed by accessing observable before the deffered clojure
```javascript
autorun(() => {
        reactotron.logImportant('autorun is running')
        const index = this.store.selectedIndex; // here
        Realm.open({})
        .then((realm) => {
            realm.write(() => {
                realm.objects('settingsScreen').filtered('pk = 0').update('updatedIndex', index)    //persistence instruction
            })
        })
        .catch((error) => console.log(error))
    })
```

**Comment by Bradzer** [comment]
@urugator thank  you very much.
I can close the issue now ;)
