### ISSUE TITLE
Observable Realm Result Instance

### ISSUE THREAD

**Issue by wdhays** [mobxjs/mobx#1898]
I have a question:
I am currently using:
    "react": "16.5.0",
    "react-native": "0.57.1",
    "mobx": "~4.9.2",
    "mobx-react": "~5.4.3",
    "realm": "~2.23.0"

Disclaimer: I am fairly new to MobX.

I have some data stored in a realm that I would like to make observable. In order to attempt this I have created a 'Results' instance of the data stored in the realm. ['Results'](https://realm.io/docs/javascript/latest/#auto-updating-results) instances in Realm and live and auto-updating.
```Javascript
this.allRealmCats = RealmInstance.objects('Cats');
```
Due to the deep-copy nature of creating an observable in MobX(?), changes made the the 'Results' instance are not reflected in the observable and therefore do not update the DOM when changes are made to the realm data. Note: I have also attempted to use observable.ref and observable.shallow without success(I do not yet fully understand their uses, I was just curious if they could help me).

Here is an example of my current work around using a listener attached to the 'Results' instance that updates a MobX observable map(inside CatStore). I like this set up because it allows me to make a single change(to the realm data) and have it automatically update the data in my store(as opposed to updating the store data then also updating the realm data with something like an autorun or observe).

```Javascript
import React from 'react';
import {View, Text, StyleSheet, Button, ScrollView} from 'react-native';
import {observable, computed, action, decorate} from 'mobx';
import {observer} from 'mobx-react';
import Realm from 'realm';

// REALM STUFF
const CatsSchema = {
    name: 'Cats',
    properties: {
        name: 'string',
    },
};
let RealmInstance = new Realm({schema: [CatsSchema]});

// MOBX STUFF
class CatStore {
    constructor() {
        this.allRealmCats = RealmInstance.objects('Cats');
        this.allRealmCats.addListener(() => this.updateObservableCats());
        this.observableCats = new Map();
    }
    get allCats() {
        return this.observableCats;
    }
    updateObservableCats(){
        // I guess this.allRealmCats is not a plain JS object, which might be part of 
        // the problem with observable.ref?
        this.observableCats.replace(JSON.parse(JSON.stringify(this.allRealmCats)));
    }
}
decorate(CatStore, {
    observableCats: observable,
    allCats: computed,
    updateCats: action,
});
let catStore = new CatStore();

// RN STUFF
export default class App extends React.Component {
    catCounter = 0;
    constructor(props) {
        super(props);
        // Bind all the methods that we will be passing as props.
        this.addOnPress = this.addOnPress.bind(this);
        this.clearOnPress = this.clearOnPress.bind(this);
    }

    addOnPress() {
        let name = 'Patches' + this.catCounter;
        this.catCounter++;
        RealmInstance.write(() => {
            RealmInstance.create('Cats', {name: name});
        });
    }

    clearOnPress() {
        let allCats = RealmInstance.objects('Cats');
        RealmInstance.write(() => {
            RealmInstance.delete(allCats);
        });
    }

    render() {
        return (
            <View style={styles.container}>
                <Text>This is a Realm test!</Text>
                <Button title={'Add'} onPress={this.addOnPress}/>
                <Button title={'Clear'} onPress={this.clearOnPress}/>
                <ScrollView style={styles.listView}>
                    <Text>All Cats: {JSON.stringify(catStore.allCats, null, 2)}</Text>
                </ScrollView>
            </View>
        );
    }
}

decorate(App, {
    render: observer,
});

const styles = StyleSheet.create({
    container: {
        flex: 1,
        marginTop: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    listView: {
        width: '80%',
    },
});
```

My Question is this: Is there anyway currently(or planned) to make Realm 'Result' instances directly observable by MobX without having to use the extra Results.addListener() logic? Is there any way to make this work using Observable.ref? See below for an example of how I wanted it to work.

```Javascript
// MOBX STUFF
class CatStore {
    constructor() {
        this.observableCats = RealmInstance.objects('Cats');
    }
    get allCats() {
        return this.observableCats;
    }
}
decorate(CatStore, {
    observableCats: observable.ref,
    allCats: computed,
});
let catStore = new CatStore();
```

**Comment by urugator** [comment]
Mobx can't make non-plain (objects with prototype) data structures observable, because it literally doesn't know how - it can't make any assumptions about their internal structure, what and how should (not) be made observable etc.
Plain structures (prototype-less/array/map/set) are copied for technical and practical reasons (inability to preserve original object referecens, messing with original data, ...).
Dunno how Realm objects are treated (whether they have prototype or not), but in both cases original objects are untouched. 
Observable.ref instructs mobx to make the field itself observable, but never convert the assigned value to observable (in case it's convertible - plain object/array/map/set).
Observable.shallow makes the field itselfs observable and converts the assigned value to "shallow" observable - meaning - if the value is array/object/map/set, it's content won't be converted, but the structure itself will.

**Comment by wdhays** [comment]
Thanks for the explanation!
