### ISSUE TITLE
Question: How to access DOM safely after call an Action which changes observable variable in react? Like $nexttick in Vue

### ISSUE THREAD

**Issue by lake2** [mobxjs/mobx#1903]
Question: How to access DOM safely after call an Action which changes state in react, after rendering is completed, DOM is updated? Like $nexttick in Vue

**Comment by fi3ework** [comment]
use `componentDidUpdate`

**Comment by lake2** [comment]
Is there other ways to do this? Using `componentDidUpdate` seems not graceful, is there any ways like callback in setState?

**Comment by urugator** [comment]
Mobx is absolutely unaware of the DOM existence.
You should use `componentDidUpdate` as suggested.
You can try `Promise.resolve.then(() => { accessDOM() })` at own risk.
Or if you need to wait for an actual repaint:
```javascript
window.requestAnimationFrame(() => {
  // just before next repaint, schedule another repaint
  window.requestAnimationFrame(() => {
     accessDom();
  })
})
```

**Comment by ItamarShDev** [comment]
@lake2  can you supply some codesandbox example of a case and what you want to happen?

**Comment by mweststrate** [comment]
Closing, question has been answered and no clear example is provided about why it isn't a good solution.
