### ISSUE TITLE
[suggest] improove get api for object

### ISSUE THREAD

**Issue by akaguny** [mobxjs/mobx#1904]
maybe add deep get? such as https://lodash.com/docs/4.17.11#get ( it works fine ) to get method
https://github.com/mobxjs/mobx/blob/21f749a0e4116f366b39a50bad92f2d342ee64ea/src/api/object-api.ts#L181

**Comment by fi3ework** [comment]
The deep get of lodash is mainly for get a deep prop safely. You also can use lodash's `get` to get a deep  property of an observable object safely.
