### ISSUE TITLE
Render Not Triggering If Observable Is Read Inside Of Non Observed Render Prop Component 

### ISSUE THREAD

**Issue by dested** [mobxjs/mobx#1905]
Sorry for the verbose title.

2. [X] Issue:
  * [X] Reproduction: https://codesandbox.io/s/w6w4ly2kx7
  * [X] Did you check this issue wasn't filed before?
  * [X] Elaborate on your issue. What behavior did you expect?
             I'm not sure if this is a generally known behavior, but it certainly threw me for a loop for a few hours. 
If an observed value is read in the callback children of a render prop, it does not seem to trigger that it was "read" during the render, and will not update the UI when subsequently updated.
In the example, if you tap the button you will update the store, but only when you force the render does the value change. 
The solution to this, in my case anyway, was to make my render prop component an @observer. This caused the children to update accordingly. Is this stated somewhere in the docs that I missed? Is there a better, more elegant solution to this, especially if I don't own the render prop component to change?
  * [X] State the versions of MobX and relevant libraries:  **Latest** 

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by ghalle** [comment]
> Is there a better, more elegant solution to this, especially if I don't own the render prop component to change?

I would recommend making `renderBody` into its own component. Like this: https://codesandbox.io/s/2op40jxj0n

Notice how I didn't have to change `SomeRenderProp`

Although if `SomeRenderProp` didnt expect a function it would be a bit simpler: https://codesandbox.io/s/nwwq323ryp

**Comment by urugator** [comment]
Take a look at [`Observer`](https://github.com/mobxjs/mobx-react#observer)
