### ISSUE TITLE
Return spy to the prod build

### ISSUE THREAD

**Issue by makarov-roman** [mobxjs/mobx#1906]
Hi, I'm confused a bit with spy removal at 5.x. It's very convenient utility function for me. 
Use cases:
1) my undo/redo implementation was built on top of it (I have to move to explicit action logging)
2) I use it as global observer, which set the flag if there are any unsaved data (to prevent data loss on exit), or to show notification if it's not possible to save (e.g. read only page)

**Comment by mweststrate** [comment]
You might want to try mobx-utils.deepObserve instead. Spy triggers on anything, not just the relevant pieces of your model, so it isn't a scalable solution
