### ISSUE TITLE
[Question] Create React App - MobX without decorators

### ISSUE THREAD

**Issue by jeffersonrt** [mobxjs/mobx#1909]
I have a:

1. [ x ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

Hello guys,
I'm studying MobX,  but I can't move on.
I'm using a create react app with a react router dom. I don't want to eject, so I decided not to use decorators. But when I try to access my store on a component I get an ObservableObjectAdministration and my Actions disappeared. Even if I use toJS  I couldn't see my Actions.

<img width="768" alt="observableobjectadministration" src="https://user-images.githubusercontent.com/5914251/53054314-c2cb3180-3482-11e9-8ad4-44182928d9eb.png">

This is the repo I'm working on it:
 [github.com/jeffersonrt/mobx-learning](github.com/jeffersonrt/mobx-learning)

**Comment by ItamarShDev** [comment]
can you please supply a [code-sandbox](https://codesandbox.io/s/v3v0my2370) with the problem reproducing?
You can use CRA in Code sandbox too.
Thank you

**Comment by jeffersonrt** [comment]
@ItamarShDev  Thanks for try to help me. I don't what did happen, but everything is working now.
