### ISSUE TITLE
How to write actions outside of class

### ISSUE THREAD

**Issue by SaekiRaku** [mobxjs/mobx#1912]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

For example, If I need 100 actions in a class, then It'll very ugly and unmaintainable  if all those actions write in a single js file.

so I want to separate those actions into other js files, I try to use `Object.assign()` to append separated modules/function into Class, but it can't use `decorators` outside class, and without that, all actions is not working. 

I know that use `decorate` function can implemented it. But still I think it's not very elegance, because I have to rewrite all function name again. And `extendObservable` is the same way.

```
import Actions from "./Actions/index.js";

class User { ... }

Object.assign(User.prototype, {
    ...Actions
});
```

**Comment by ItamarShDev** [comment]
maybe https://mobx.js.org/refguide/extend-observable.html ?

**Comment by urugator** [comment]
```javascript
export action(function doSomething() { /**/ })
```

**Comment by SaekiRaku** [comment]
@ItamarShDev @urugator Thank you, my problem is solved. `export action(function doSomething() { /**/ })` this way is much easier in my condition. Thanks.
