### ISSUE TITLE
`replace` for observable object?

### ISSUE THREAD

**Issue by colinmcd94** [mobxjs/mobx#1913]
Is there an equivalent for `IObservableArray.replace` for objects?

Or put another way, what's the canonical way to take an existing observable object, clear all the keys, and re-populate it with new data?

**Comment by urugator** [comment]
Consider using `IObservableMap`.
[Object api](https://mobx.js.org/refguide/object-api.html) could also help a little.
IIRC deleting object props has some performance implications (V8) so `Map` is preferred solution as dynamic key/value storage.

**Comment by colinmcd94** [comment]
I'm confused why the object API says `set` is "not really necessary when using MobX 5" even though there's no other way to actually do this.

Also maps look interesting but raise another question. From the docs: "Observable maps are very useful if you don't want to react just to the change of a specific entry, but also to the addition or removal of entries". So if I have an observable _object_ and I iterate over its keys in an observer function, it won't update if I add an additional value? Just making sure I understand this.

**Comment by urugator** [comment]
Depends on which version of Mobx you use.
Mobx5 uses proxies therefore it's possible to intercept `delete obj.prop` and addition of a new property. (so you can just iterate the object keys and call `delete` on each)
Mobx4 uses setters/getters, therefore only set/get operations of existing props can be intercepted. Object api can be used to overcome this limitation.
