### ISSUE TITLE
Can decorate automatically detect what to decorate?

### ISSUE THREAD

**Issue by andraz** [mobxjs/mobx#1914]
Decorate appears to detect getters (computed) and setters (actions) automatically, but still needs to get fields (observable) defined manually.

example in store.js
https://codesandbox.io/s/6xrz30jz1w

Can it detect everything "automagically"?
Will the way I am using it in the example make computed fields and actions potentially break later in more complex nested configurations?

**Comment by urugator** [comment]
> Decorate appears to detect getters (computed) and setters (actions) automatically

It does NOT. You can check it yourself:

```javascript
const store = new Store()
console.log(isComputedProp(store, 'footer')) // false
console.log(isAction(store.toggleTodo)) // false
``` 
`action` or `computed` are not required for observables to work, but it provides benefits like batching and memoization.
   
About class level decorator: https://github.com/mobxjs/mobx/issues/743

**Comment by andraz** [comment]
Could it be upgraded in such a way to detect those automatically + auto-observe all fields of class without manually specifying their names?

Maybe by using code behind this feature:
https://github.com/farwayer/mobx-decorators#allobservable

**Comment by mweststrate** [comment]
No, MobX won't provide a default way for doing this. (If you need more details I am pretty sure you can find similar issues in this repo). But if one is able to make certain assumptions about their own classes, it is easy to implement in userland.
