### ISSUE TITLE
use mobx  @observer in react didn't re-render

### ISSUE THREAD

**Issue by jockw** [mobxjs/mobx#1915]
i used like this , it is re-render
   const Timer = observer(class Timer extends React.Component {
      componentDidMount() {
       console.log(this.props)
     }
      render() {
        return (<span>Seconds passed: { this.props.timerData.secondsPassed } </span> )
     }
});

but it is didn't re-render     like this:
  @observer class Timer extends React.Component {
  componentDidMount() {
    console.log(this.props)
  }
  render() {
    return (<span>Seconds passed: { this.props.timerData.secondsPassed } </span> )
  }
}

and i use autorun to listen secondsPassed, the value is change

**Comment by ItamarShDev** [comment]
I dont know if it was a typo, but it should be *observer* and not Observer

```javascript
@observer class Timer extends React.Component {
    componentDidMount() {
        console.log(this.props)
    }
    render() {
        return (Seconds passed: { this.props.timerData.secondsPassed } )
    }
}
```

**Comment by jockw** [comment]
no, i write @observer in my code; all code like this 👍 
   import React from 'react';
import ReactDOM from 'react-dom';
import { observable, autorun } from 'mobx';
import {observer} from "mobx-react";

var timerData = observable({
  secondsPassed: 0
});

setInterval(() => {
  timerData.secondsPassed++;
}, 1000);

@observer class Timer extends React.Component {
  render() {
    return (<span>Seconds passed: { this.props.timerData.secondsPassed } </span> )
  }
};

ReactDOM.render(<Timer timerData={timerData} />, document.body);



but it is didn't work ; is it webpack problem?

**Comment by jockw** [comment]
it is "observer" in my code not 'Observer'; i didn't know why it's to show "Observer" on this answer

**Comment by mweststrate** [comment]
Maybe your decorator setup is incorrect. Please share your .babelrc

Op do 28 feb. 2019 10:26 schreef jockw <notifications@github.com>:

**Comment by jockw** [comment]
thank i maybe find it；you are right it‘s in my 
babelrc
