### ISSUE TITLE
License header is removed in minified production build

### ISSUE THREAD

**Issue by quanganhtran** [mobxjs/mobx#1921]
We were doing a compliance check on our code base and realized that MobX license header is stripped off by minifier.

According to webpack-contrib/uglifyjs-webpack-plugin#222, to solve this at least for Webpack + UglifyJs code base we can add `@license`, `@preserve` or `/*!`

This is something I am willing to make PR for, but what I would like to have opinions on is what to put in the license header because as many bytes will be added to the (default) production build.

**Comment by mweststrate** [comment]
PR is welcome! (shouldn't be that many bites right?)

**Comment by runnez** [comment]
@mweststrate I found the cause https://github.com/mobxjs/mobx/pull/1966
