### ISSUE TITLE
How can I realize HMR with mobx-react?

### ISSUE THREAD

**Issue by kwzm** [mobxjs/mobx#1924]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I use react-hot-loader but find when I modify some jsx codes the mobx states are lost.

**Comment by ItamarShDev** [comment]
@kwzm  can you provide more information?
Are you using class based store or object based?
Maybe try to supply a codesandbox of a problematic code

**Comment by mweststrate** [comment]
There are quite a bunch of issues in the mobx-react repo related to HMR. Please check those first. Beyond that, there is not any information to work with in the current question. Closing.
