### ISSUE TITLE
Can I use the mobx on backend as model structure for socket.io ?

### ISSUE THREAD

**Issue by askucher** [mobxjs/mobx#1926]
Hi I use the mobx for react and it is awesome

I want to reuse the same experience on backend where I change the state on backend and it fires automatic io.emit. Do you have example how to make this?

**Comment by mweststrate** [comment]
Yes, autorun or reaction can be used for that, just like anywhere else, like:

```javascript
const state = { x : 1 }

autorun(() => {
  socket.emit(JSON.stringify(state))
})
```
