### ISSUE TITLE
☂ [on hold] Things to fix / investigate once decorators are standardized ☂

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#1928]
Since half of the open issue on the repo are waiting for decorators to be standardized, it is just easier to create an umbrella issue, to investigate them all once we arrive at that glorious moment. 

[All relevant issues](https://github.com/mobxjs/mobx/issues?q=is%3Aissue+label%3Awaiting-for-standardized-decorators)

Linked issues:
* [ ] #1864 
* [ ] #1769, #1767 
* [ ] #1526 
* [ ] #1352 
* [ ] #1273

(On hold) PR 
https://github.com/mobxjs/mobx/pull/1732

**Comment by mweststrate** [comment]
Implementation notes based on the 'static decorator' proposal: https://github.com/tc39/proposal-decorators/issues/267

**Comment by FredyC** [comment]
@mweststrate I wonder if any of this is relevant now with upcoming MobX6?

**Comment by mweststrate** [comment]
Let's close for now until something is actually standardized, which is probably long after V6 :)
