### ISSUE TITLE
es module observable error "could not be converted"

### ISSUE THREAD

**Issue by chase-moskal** [mobxjs/mobx#1932]
hi!

i'm trying to set up a modern build-free app using mobx, [htm](https://github.com/developit/htm), preact, and native es modules

**i get an error when i try to use `observable`**

**esmodule** [*(codepen)*](https://codepen.io/ChaseMoskal/pen/ZPRQbm?editors=0010)
- ```js
  import {observable} from "https://unpkg.com/mobx@5.9.0/lib/mobx.es6.js"
  observable("anything")
  ```

**error**
- ```
  Uncaught Error: [mobx] The provided value could not be converted into an
  observable. If you want just create an observable reference to the object 
  use 'observable.box(value)'

    invariant$$1 @ mobx.es6.js:16
    fail$$1 @ mobx.es6.js:11
    createObservable @ mobx.es6.js:402
    (anonymous) @ pen.js:4
  ```

i don't know what's wrong

----

I have a:

- [x] Issue:
  * [x] **Provide error messages including stacktrace**
    - ```
      Uncaught Error: [mobx] The provided value could not be converted into an
      observable. If you want just create an observable reference to the object 
      use 'observable.box(value)'

        invariant$$1 @ mobx.es6.js:16
        fail$$1 @ mobx.es6.js:11
        createObservable @ mobx.es6.js:402
        (anonymous) @ pen.js:4
      ```
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
    - its only two lines but i have this [codepen](https://codepen.io/ChaseMoskal/pen/ZPRQbm?editors=0010)
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
    - i expected `observable` not to throw an error for primitives like strings or numbers
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version
    - `mobx@5.9.0`, `chrome@71.0`

**Comment by chase-moskal** [comment]
i have found that `mobx@4.9.3` reproduces the same error

```js
import {observable} from "https://unpkg.com/mobx@4.9.3/lib/mobx.module.js"
observable("anything")
```

**Comment by Maaartinus** [comment]
@chase-moskal I'm a beginner here, but isn't this what the [documentation](https://mobx.js.org/refguide/boxed.html) says?

The string `"anything"` is immutable and therefore
- it can't be made observable
- there's nothing to observe as it can't change

A primitive-valued field is a different story.

**Comment by fi3ework** [comment]
@chase-moskal 
The target of `observable` should be an object. If you wanna observe a primitive value, please use `observable.box`, see details [here](https://mobx.js.org/refguide/boxed.html)

**Comment by chase-moskal** [comment]
@Maaartinus, @fi3ework -- thanks for pointing me in the right direction fellas!

[i fixed the codepen example](https://codepen.io/ChaseMoskal/pen/ZPRQbm?editors=0010)

i was simply totally naive about how to use observables without using decorators (coming from typescript-land)

following [this article](https://mobx.js.org/best/decorators.html) in the mobx docs solved my problem :)

all i needed to understand was how to use the `decorate` function to properly apply observable/action/computed/etc (or otherwise that i could use `observable.box` as you folks have mentioned)

hopefully somebody from the future with a similar confusion might find this issue helpful!

good day :)
