### ISSUE TITLE
has anybody begun work on a "mobx-lit"?

### ISSUE THREAD

**Issue by chase-moskal** [mobxjs/mobx#1936]
hello friends,

i've been digging into the new polymer libraries, lit-html and lit-element.. cool stuff!

i wanted to ask here: has anybody already begun work integrating mobx with lit-element?

i want to get started and contribute, though i'll have to spend some time learning how mobx works

i would really appreciate any pointers and insights about implementation designs :)

cheers!

**Comment by mweststrate** [comment]
Capturing the computation of the rendering, and the assignment to the relevant DOM will in general get you quite far. 

Some quite random pointers:
https://t.co/Dqs4VJP942

https://gist.github.com/mweststrate/b4ebb27d7c4dcb7e3a37090b91490da7
