### ISSUE TITLE
Can we force actions to track properties?

### ISSUE THREAD

**Issue by LandonSchropp** [mobxjs/mobx#1938]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Our application uses an `autorun` function to automatically fetch a resource from our API when the current ID property is updated. Here's a simplified example of what we're doing.

```
class BananaStore {
  
  constructor(routerStore) {
    this.routerStore = routerStore;
    autorun(this.loadBanana);
  }

  @action
  async loadBanana() {
    this.loading = true;
    
    let banana = await fetchBanana(this.currentBananaId);

    runInAction(() => {
      this.loading = false;
      this.currentBanana = banana
    });
  }

  @computed
  get currentBananaId() {
    this.routerStore.currentId;
  }
}
```

This doesn't call `loadBanana` when `currentBananaId` is updated. According to the [documentation](https://mobx.js.org/refguide/untracked.html):

> Untracked allows you to run a piece of code without establishing observers. Like transaction, untracked is automatically applied by (@)action, so usually it makes more sense to use actions than to use untracked directly.

So it seems like we're not seeing this fire because the action is marked as untracked. We *could* make this a `reaction`, but that involves having to specify each computed property used by the action. This is a pattern we're repeating in several places in our code. If we forget to specify a property in `reaction`, it's easy to introduce a subtle bug that's difficult to track down later.

My questions:

* Are we thinking about this correctly? Is `autorun` the right thing to use?
* Is `autorun` fundamentally incompatible with `@action`?
* Is there a way to force actions to track properties?
* Are we missing anything else?

Thank you!

**Comment by LandonSchropp** [comment]
One last note: It would be really nice if we could simply use `autorun` as a decorator like this:

```
  @autorun
  @action
  async loadBanana() {
    this.loading = true;
    
    let banana = await fetchBanana(this.currentBananaId);

    runInAction(() => {
      this.loading = false;
      this.currentBanana = banana
    });
  }
```

It looks like there's a closed ticket for this (#181).

**Comment by urugator** [comment]
Firstly `autorun` doesn't work with `async`, check: https://github.com/mobxjs/mobx/issues/1003

`action` also doesn't work with `async`, check https://github.com/mobxjs/mobx-react/issues/505#issuecomment-478221501

Consider using `reaction` it allows you to cleanly seperate the derivation (get banana id) and the effect (fetch banana based on id).

I suggest avoiding `autorun`/`reaction` altogether, some reasoning here:
https://github.com/mobxjs/mobx/issues/1006

**Comment by mweststrate** [comment]
Closing for answered / inactivity. 

Note that reaction and action are each conceptual counterparts, see https://mobx.js.org/intro/concepts.html. Triggering an action from a reaction is possible, but in that case follow the pattern `reaction(() => somethingToReactTo, somethingToReactTo => { callAction() })`
