### ISSUE TITLE
Error: [mobx] missing option for computed: get . Not able to make out what the issue exactly is

### ISSUE THREAD

**Issue by ashukhetan** [mobxjs/mobx#1940]
I have an observable @observable currentConfigObject = {"locales": []};

In one method I am trying to play around with this object and getting error Error: [mobx] missing option for computed: get . I am not able to figure out what is the reason of the error.

customerDetailStore.<anonymous>
C:/sharecare/codebase/UserManagement/src/onboarding/model/CustomerDetailStore.js:108
  105 | 
  106 |        // console.log(this.currentConfigObject.get());
  107 |        // console.log(this.currentConfigObject.locales.get());
> 108 |        this.currentConfigObject.locales.push(localeObject);
  109 |    };
  110 | 
  111 |    @action enableSpanish = () => {
View compiled

The error is coming in the this.currentConfigObject.locales.push(localeObject); where localeObject is an object with some keys which I am trying to push in the "locales" array of currentConfigObject .

Please help..I have been stuck and not able to understand the reason behind this error

**Comment by devuxer** [comment]
I'm getting this too. The stack trace doesn't have any of my code, so it's hard to track down.

**Comment by fi3ework** [comment]
Hi:
You can use `get()` only when it's wrapped by `observable.box`. In your case, you can just use `currentConfigObject` just like you used to. MobX doesn't change the usage of object or array.

**Comment by quantumpotato** [comment]
@devuxer I'm trying to follow along.

I have

```
export default class UserStore extends RootStore {
 @observable user = {name: ""}
...

getUser = (params,callback) => {
 apiFetch(path, (data, error) => {
this.user = data.user
}
}
```

Do I need to wrap the setting in a mobx  decorator?
