### ISSUE TITLE
Flow decorator documentation inaccuracy

### ISSUE THREAD

**Issue by maciejmyslinski** [mobxjs/mobx#1942]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

Hey! I'm relatively new to mobx – excuse me any lack of understanding. I think I might found a documentation inaccuracy and I'm not sure how to fix it.

[This](https://mobx.js.org/best/actions.html) part of documentation states:
> `flow` can be used only as function not as decorator

But in [onBecomeObserved documentation](https://mobx.js.org/refguide/api.html), the example is using `flow` as a decorator. What am I missing?

**Comment by urugator** [comment]
Example is incorrect, it should be: 
```javascript
fetchTemperature = flow(function*() {
   // data fetching logic
})
```
PR welcome.
Before you ask, Babel has problems with decorator+generator.

**Comment by mweststrate** [comment]
Fixed example
