### ISSUE TITLE
Is it possible to use operators on observable values?

### ISSUE THREAD

**Issue by lihaibh** [mobxjs/mobx#1943]
I have the following code:
```
export default class AppState {
  @observable public timer = 0;

  constructor() {
    setInterval(() => {
      this.increaseTime();
    }, 1000);
  }
}

const buffer = observable<number>([]);
const app = new AppState();
computed(() => app.timer, t => buffer.push(t));
```
however the setter function in the computed doesnt work for me, it looks like its not being invoked...
What i want to do is basically is creating a buffer of fixed size length that get the emitted values of observable value like timer.
so what i would like to do is having a list of 5 last emitted values of timer and update it on the fly.
I thought that like RxJS, mobx will have its own operators so like i would do:
```
const app = new AppState();
computed(() => app.timer, t => buffer.push(t));
const buffer = mobxBuffer(()=>app.timer, 5);
// buffer is a list of 5 items maximum
```
I couldnt find a way to do it, can u give me a suggestion?
Thank you for help.

**Comment by fi3ework** [comment]
hi:
I don't quite understand this line

```js
computed(() => app.timer, t => buffer.push(t));
```
Why pass two computed function. What exactly you want computed from app or buffer? IMHO, this is not the right usage of computed.

**Comment by spion** [comment]
Replace 

```js
computed(() => app.timer, t => buffer.push(t));
```

with

```js
autorun(() => buffer.push(app.timer));
```
