### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by alexbigapps23** [mobxjs/mobx#1946]
Hi i try get action and proptypes from my mobx store 
I am inject the store but get Cannot read property of undefined
if i am console.log the store i see the all proptypes  and actions
i thinking react render component before inject store 

why is it happening ?
```javascript
{
	"presets": [
		[
			"@babel/preset-env",
			{
				"targets": {
					"browsers": [
						"last 2 versions"
					]
				},
				"debug": false
			}
		],
		"@babel/preset-react"
	],
	"plugins": [
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties",{"loose":true}],
		"@babel/plugin-transform-async-to-generator",
		"@babel/plugin-syntax-dynamic-import",
		"@babel/plugin-transform-runtime",
		"universal-import"


    ],
	"env": {
		"development": {
			"plugins": [
				"react-hot-loader/babel"
			]
		}
	}
}
```
![1](https://user-images.githubusercontent.com/23071049/56278815-9b55b580-610f-11e9-9753-24d5ea480c6e.jpg)

**Comment by ItamarShDev** [comment]
can you please try your setup on the sandbox and try to reproduce?

**Comment by alexbigapps23** [comment]
> can you please try your setup on the [sandbox](https://codesandbox.io/s/v3v0my2370) and try to reproduce?

how i can clone the project from bitbucket to sandbox ?

**Comment by alexbigapps23** [comment]
sandbox https://codesandbox.io/s/k96npnm52v

**Comment by mweststrate** [comment]
Please isolate your issue in something small, so that others can take a look on it without needing to figure out what your application does.
