### ISSUE TITLE
[Question] Jest + mobx: how to test autorun & reaction?

### ISSUE THREAD

**Issue by kesha-antonov** [mobxjs/mobx#1947]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ x ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

Hey!
Love mobx! Nice lib.

Please advice how to use code that depends on ```autorun``` and/or ```reaction```.

I have caching logic in one store. When I add item to cache it pops item and start processing it. All is async. I want to test it with jest.

Here's my current test
Not very nice solution with setTimeout (or maybe not?). How would you do this test?

```
it.only("should add lesson to caching queue and cache cover, assets, audios", async () => {
    const store = await loadStore()

    const { processingLessonsCache } = store

    expect( processingLessonsCache.queue ).toEqual(
      observable({
        queue_cache: [],
        queue_remove: [],
      })
    )

    let lesson = store.courses.items[0].Lessons[0]
    processingLessonsCache.addItem({
      courseId: lesson.course.Id,
      lessonId: lesson.Id,
    })
    expect( toJS(store.courses.items[0].Lessons[0]._CoverCached.path) ).toBeFalsy()
    expect( processingLessonsCache.queue.queue_cache.length ).toEqual( 1 )

    while( processingLessonsCache.queue.queue_cache.length > 0 ) {
      await new Promise((resolve,reject) => { setTimeout(resolve, 100) })
    }


    expect( processingLessonsCache.queue.queue_cache.length ).toEqual( 0 )
    expect( toJS(store.courses.items[0].Lessons[0]._CoverCached.path) ).toBeTruthy()
  })
```

**Comment by ItamarShDev** [comment]
can you please update a demo code to [sandbox](https://codesandbox.io/s/v3v0my2370) to ease the way and debug?

**Comment by ItamarShDev** [comment]
also, have you look in the test files?
https://github.com/mobxjs/mobx/blob/master/test/base/autorun.js
https://github.com/mobxjs/mobx/blob/master/test/base/reaction.js

**Comment by mweststrate** [comment]
Also, `await when(() => somethinghasHappened)` is a great way to test async stuff

**Comment by kesha-antonov** [comment]
Thanks guys! I'll try that as well
