### ISSUE TITLE
shouldComponentUpdate does not work

### ISSUE THREAD

**Issue by MikhailTatsky** [mobxjs/mobx#1952]
Hi there,
I am sorry for disturbing.
We have very complex app and we faced the problem that `shouldComponentUpdate` in some cases work, in some it does not with the same code.
We read that it is not recommended to use `shouldComponentUpdate` for MobX.
But we use ag-Grid and since it is not written on React, it can not be updated properly and fast for React over changing states. The only way to work fast for ag-Grid with React is using ag-Grid methods.
We need to rerending updating grids container.
Our code definition looks like this.

```
@inject('sheetStore')
@observer
export default class GridContainer extends Component {
...
Many grids rendering
...
//Accidentally it stops to work
shouldComponentUpdate = () => {
    if (sheetStore.stopReRenderingGrids) {
      return false;
    }

    return true;
}
```

 Sorely I can not provide link on sample for this case.
Please, give me advice.

**Comment by urugator** [comment]
Firstly don't use arrow functions `() => {}` for lifecycle methods.
> When using @observer on a component, don't implement shouldComponentUpdate, as it will override the default implementation that MobX provides. When using mobx-react, you should in general not need to write an sCU (in our entire Mendix code base we have none). If you really need to implement sCU, split the component into two, a reactive and non-reactive (with the sCU) part, or use <Observer> sections instead of observer on the entire component.

Also check https://github.com/mobxjs/mobx-react/issues/667#issuecomment-483747386

**Comment by ItamarShDev** [comment]
https://github.com/mobxjs/mobx-react#about-shouldcomponentupdate
this is the docs segment @urugator was referencing.

**Comment by mweststrate** [comment]
Was the question solved?

**Comment by MikhailTatsky** [comment]
@mweststrate 
 Thank you Michel,
We use use usual property without observable and it looks like it works so no need in shouldComponentUpdate for the moment.
