### ISSUE TITLE
Reaction delay throttling instead of debouncing

### ISSUE THREAD

**Issue by Annihil** [mobxjs/mobx#1956]
Hi,

As stated in the documentation for `reaction`

> Options
> `delay`: Number in milliseconds that can be used to debounce the effect function. If zero (the default), no debouncing will happen.

The `delay` option should debounce the reaction, but in fact it throttles it.
Is the documentation incorrect or is it a bug?

**Comment by mweststrate** [comment]
Feel free to update the docs. Note that a custom scheduler can be set to customize the behavior

**Comment by Annihil** [comment]
I'm failing to use scheduler to achieve debouncing
```js
let id;
...
delay: 0,
scheduler: f => {
    clearTimeout(id);
    id = setTimeout(f, 1000);
}
```

It's still throttling and not clearing the timeout if a reaction has been done in those 1000ms timeout

**Comment by mweststrate** [comment]
well, you would have to wrap the reaction function itself as well, and
introduce some state in the closure to take care of the throttling process.

**Comment by Annihil** [comment]
That's what I ended up doing yes.  
I think it'd be great to have a `debounceDelay` option that provides this out of the box :)

**Comment by koffmoff** [comment]
Agree that there is some confusion between throttling/debouncing. This is my take on achieving true debouncing.

```ts
function debounceEffect<T>(effect: (arg: T, r: IReactionPublic) => void, debounceMs: number) {
    let timer: NodeJS.Timeout
    return (arg: T, r: IReactionPublic) => {
        clearTimeout(timer)
        timer = setTimeout(() => effect(arg, r), debounceMs)
    }
}

// Use it like so:
reaction(
    () => this.searchTextField,
    debounceEffect(s => this.searchString = s, 1000)
)
```

**Comment by FredyC** [comment]
Docs fixed in #2337

**Comment by pkhodaveissi** [comment]
> ```ts
> function debounceEffect<T>(effect: (arg: T, r: IReactionPublic) => void, debounceMs: number) {
>     let timer: NodeJS.Timeout
>     return (arg: T, r: IReactionPublic) => {
>         clearTimeout(timer)
>         timer = setTimeout(() => effect(arg, r), debounceMs)
>     }
> }
> ```

@koffmoff I tried to use this function to run a function which returns Promise<void> instead of an assignment inside my reaction, but couldn't use your code, what am I missing?

**Comment by koffmoff** [comment]
@pkhodaveissi should work. Msg your code + error to me if you want.

**Comment by pkhodaveissi** [comment]
> @pkhodaveissi should work. Msg your code + error to me if you want.
There it is:
```ts
const disposePaginationReaction = reaction(
        () => ({
          pageSize: self.pagination.pageSize,
          pageIndex: self.pagination.pageIndex,
        }),
        () => {
          getItems(true, false);
        }
      );```

and the getItems:
```ts
const getItems = flow(function* getQueuesFLow(
      shouldShowLoading: boolean = true,
      shouldResetPagination: boolean = true
    ) {
// some work to yield an API call
});
```
Typescript complains about passing `Promise<void>` instead of `(arg: T, r: IReactionPublic) => void` when I tried to replace `debounceEffect(s => this.searchString = s, 1000)` with something like `debounceEffect(self.getItems(), 1000)`.

Thanks for your time man.
