### ISSUE TITLE
Observable array & debugging experience (0..999 indices created)

### ISSUE THREAD

**Issue by borekb** [mobxjs/mobx#1959]
In VSCode, when I hover over a variable that is an observable array, I get a ton of messages (1,000, to be precise) in the debug console:

```
[mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
mobx.module.js:3246
[mobx.array] Attempt to read an array index (1) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
mobx.module.js:3246
[mobx.array] Attempt to read an array index (2) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
mobx.module.js:3246
[mobx.array] Attempt to read an array index (3) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
...
```

Also, expanding such objects in the **Variables** or **Watch** panels impact usability there.

I couldn't find many mentions about this anywhere and maybe there's nothing to do about it but I though I'd at least ask if there's a way to mitigate this somehow, for example, is there a way to tell MobX to create fewer such indices? In some of my arrays, I know that there will always be 5 or less items in them.

Also, I found this mention in https://github.com/mobxjs/mobx/issues/381#issuecomment-230209228:

> ...this 1000 number could be safely increased a lot...

I don't think this is true as for example setting this to 1,000,000 would make things significantly worse during debugging.

**Comment by mweststrate** [comment]
I assume this report is about MobX 4? I don't think it is a problem with the proxy implementation, as we don't need to use faux arrays there. 

I don't think there is a clear fix for this. If it is too annoying, `.slice()` it in your watch expression

**Comment by borekb** [comment]
Yes, MobX 4. Just plain hovering over a variable does this, before I have a chance to create a watch expression but thanks for the tip anyway.

What do you think about adding some parameter to customize the number of stub array items? 1000 seems like an arbitrary choice – quite a good one but I'd guess that there are people for whom this is too much or too little.

**Comment by mweststrate** [comment]
That is possible already: `mobx.configure({ arrayBuffer: 10 })`

**Comment by borekb** [comment]
Aha! I was looking for something like `observable.array(values, { buffer: 10 })` as this feels more per-array but it's good to know that it's at least globally configurable (I didn't know what to google for so missed this config value; thanks!).

**Comment by D19cannon** [comment]
Hi, 

I ran into a similar problem. However, for some reason whenever I am trying to set an observable array with 10 items, the indices are by default a 1000. The strangest part is that I am doing the exact same thing in another store and it works the way it is expected.

Any ideas, where these 1000 indices are coming from?

**Comment by FredyC** [comment]
@D19cannon We talked about this on gitter. As long as you would refusing to show the actual code, we cannot help you. Try to understand that, please.

I have prepared a very basic CodeSandbox for you. Please expand on that to show what you need to do and why are those indices a problem.

https://codesandbox.io/s/practical-allen-9fr5i
