### ISSUE TITLE
observable array will throw error when use Array.prototype.push.apply in safari (mac && ios)

### ISSUE THREAD

**Issue by luosong** [mobxjs/mobx#196]
I test, it's ok in chrome (mac && android)

**Comment by mweststrate** [comment]
Observable arrays are not normal arrays but objects instead (until ES6 proxies are standardized). This means that standard Array prototype methods might not work on them, see also the docs http://mobxjs.github.io/mobx/refguide/observable.html (section "Arrays"). If needed, the `ObservableArray` prototype can be exposed from the library to make it possible to use it's `push` method from the prototype.
