### ISSUE TITLE
observable structure is totally different between v4 and v5

### ISSUE THREAD

**Issue by chj-damon** [mobxjs/mobx#1961]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [*] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [*] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**
this is the observable structure in V5:
![image](https://user-images.githubusercontent.com/4902684/57439122-ee86d800-7277-11e9-8937-1c73923ff2eb.png)
and this is the observable structure in V4:

![image](https://user-images.githubusercontent.com/4902684/57439914-99e45c80-7279-11e9-9183-5839638a25d2.png)

I don't understand why they are so different.
because reports error if one component need array but it actually got an object. like below:
![image](https://user-images.githubusercontent.com/4902684/57440008-c8623780-7279-11e9-819e-4e5c1b09d729.png)

in V5, it works fine.
my mobx version is v4.9.4.

**Comment by urugator** [comment]
https://mobx.js.org/refguide/array.html

> Array limitations in MobX 4 and below
>
> Due to limitations of native arrays in ES5 observable.array will create a faux-array (array-like object) instead of a real array. In practice, these arrays work just as fine as native arrays and all native methods are supported, including index assignments, up-to and including the length of the array.
> 
> Bear in mind however that Array.isArray(observable([])) will yield false, which some native array manipulation methods require and which some external libraries may also require. E.g. [].concat(observable([])) will not work as expected since the native array concat method expects the test to return true. So whenever you need to pass an observable array to an external library or use the observable array as an argument to native array manipulation methods, you should create a shallow copy by using array.slice(), which will cause Array.isArray(observable([]).slice()) to yield true.

**Comment by chj-damon** [comment]
yes, I know that. But I don't know why it reports error.

**Comment by urugator** [comment]
What exactly isn't clear? As mentioned above observable array in V4 isn't actual array.
Therefore checking for array with `Array.isArray` or `PropTypes.array` reports an error.
The reason is compatibility with IE9 (lack of proxies and inability to extend built-ins).

**Comment by chj-damon** [comment]
Ok, thanks for your help
