### ISSUE TITLE
Proper usage of createTransformer

### ISSUE THREAD

**Issue by guanzo** [mobxjs/mobx#1963]
Hi, I'm trying to derive a map from another map, where the derived map's keys are the original map's values. Whenever the original map sets/deletes a key, or a key's value is updated, I want the derived map to reflect that. `createTransformer` seems like the right API to do this, but I can't quite figure out how to implement it.

Here's an example:

- Original map (name -> language):
bob -> [python, js]
mary -> [js, java]
tom ->[java, python]
jack -> [js, java]

- Derived map (language -> name):
python -> [bob, tom]
js -> [bob, mary, jack]
java -> [mary, tom, jack]

I'm currently creating the derived map with a `@computed` property, which works but is horribly inefficient because I have thousands of elements that are frequently updated. Each recomputation requires a full map iteration and the event loop is being blocked.

```
@observable nameToLanguages = new Map()

@computed get languageToNames () {
    const map = new Map()
    for (const [name, languages] of this.nameToLanguages) {
        for (const lang of languages) {
            if (!map.has(lang)) {
                map.set(lang, [])
            }
            map.get(lang).push(name)
        }
    }
    return map
}
```

What would be the correct mobx way to create this derived map?

**Comment by urugator** [comment]
I presume the reason for the inverted map is lookup optimization.
I don't think you can come up with anything better (simpler and performant) than keeping maps synchronized on writes:
```javascript
@action
addLangToUser(name, lang) { 
  if (!nameToLangMap.has(name)) {
    nameToLangMap.set(name, new Set());
  }
  if (!langToNameMap.has(lang)) {
    langToNameMap.set(lang, new Set());
  }  
  
  nameToLangMap.get(name).add(lang);
  langToNameMap.get(lang).add(name);    
}

@action
removeLangFromUser() {
  nameToLangMap.get(name).delete(lang);
  langToNameMap.get(lang).delete(name);    
}
```

**Comment by ItamarShDev** [comment]
I agree with @urugator 
also, `languageToNames` should not be a computed.
it should be an observable like `nameToLanguages`

I would init it once when I get nameToLanguages (constructor?)
and then add or remove from one when the other changes


(acctually', i would probably use Proxy API for it :P)
