### ISSUE TITLE
Mobx + React Native + Meteor

### ISSUE THREAD

**Issue by odesey** [mobxjs/mobx#1965]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [X] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

  * [X] Are you willing to (attempt) a PR yourself?
 I could, but life as we know might cease to exist? :-) (new developer)

I am starting a project and hope to use Mobx for my state management, my single reactive source of truth. My stack is as follows:

**react-native v0.59.6** 
**mobx v5.9.4**
**mobx-react v5.4.3**
**Wix react-native-navigation v2.18.x**
**meteor JS v1.8.1**

I've gotten Mobx + Meteor to work by subscribing to my Meteor data at the component layer and then pushing that data to my Mobx store like so:

```javascript
import  ...

@inject("userStore")
@observer
class Home extends Component {

  static getDerivedStateFromProps(nextProps, prevState) {
   /*
      push the data to my Mobx store here...
      this.props.userStore.setUserData(nextProps.someData) //may be called a few times
   */
       
  }

render() {
  return (
  //will re-render as Meteor data is updated and when data is pushed to Mobx
  <View>
  <Text>{this.props.userStore.getUserData}</Text>
  <Button onPress={() => this.getData} />
</View>
 )
 }
}

export default withTracker(() => {
  return {
    someData: Meteor.subscribe("moreData"),
    user: Meteor.user(),
    userLoggingIn: Meteor.loggingIn(),
    userId: Meteor.userId()
  };
})(Home);
```
This method is highly inefficient as the component will render multiple times unnecessarily. 

I would like to move all my Meteor code to my Mobx stores so I can avoid the unnecessary re-renders.

Is there anyway I can subscribe to my Meteor data from within my Mobx stores?

I've read #26 and a few other of the Meteor related issues but did not find a clear concise pattern for re-actively subscribing to my Meteor data from within my Mobx stores.

Ive tried the following so far in my store:

```javascript
import { action, observable, computed, autorun, observe } from "mobx";
import Meteor, { withTracker, Tracker } from "@socialize/react-native-meteor";

class UserStore {
  constructor() {
    autorun(() => console.log(Meteor.loggingIn(), "autorun")); //never re-runs even when I log in and out

    Tracker.autorun(() => {
      console.log(Meteor.user(), "<-- TRACKER"); //never re-runs even when I log in and out
    });
  }
   @observable userId = Meteor.userId(); //stays null even when I login and out

  @observable user = Meteor.user();  //stays null even when I login and out

}

const userStore = new UserStore();
export default userStore;
```

Any help, idea's on this would be greatly appreciated!!

One more issue I've run into:

If I manually set my user property and then try to get the value, I get the following:
`{$mobx: ObservableObjectAdministration$$1} {$mobx: ObservableObjectAdministration$$1}`

instead of the object I was expecting:
`{_id: "8M7m9CyBGzzceQpnh", emails: Array(1), profile: {…}, _version: 3}`

Version `4.x` of Mobx returns a `$mobx` object and version `5.x` returns a `proxy`

Why is this?

Thanks.

**Comment by mweststrate** [comment]
It is possible, but at the moment I don't have the luxury of the time to go into in detail. I can give you some quick pointers:
- https://medium.com/@swalta/adventures-with-react-mobx-and-meteor-605a133460b3
- From the meteor Tracker you will need to change _mobx observables_, from the _mobx autorun_ you want to update Meteor state
- To avoid duplicate state between meteor and mobx, one can use `createAtom` so that in the meteor Tracker you can make sure that atom is propagating a change. Than when reading the data, read it from meteor directly, but mark the atom as being read, so that mobx can establish their relationships. 

Sorry, it is very little information, do take a look at the `createAtom` documentation, make sure you deeply understand it, (it is used in several of the mobx-utils utilities like fromResource, which solves a similar problem).

**Comment by odesey** [comment]
Thanks @mweststrate  for taking time out of your busy schedule to respond to my question.

I actually came across the medium article as well but I was not able to get it working in my`react native` project, I was not sure if it was because of an error on my part or because it would only work on `react web`. I will re-read it and try again utilizing the `createAtom` method as well.

If you can think of anything else please let me know.

Thanks again.



I will review the information you provided and update the issue if/when I make progress.

**Comment by FredyC** [comment]
Closing, for now, will reopen if you have more questions.
