### ISSUE TITLE
启用装饰器语法问题

### ISSUE THREAD

**Issue by devYoungyang** [mobxjs/mobx#1971]
"react": "16.3.0",
"react-native": "0.54.4",
"mobx": "^5.9.4",
"mobx-react": "^5.4.3",
启用装饰器，怎么安装插件，如何配置babel

**Comment by urugator** [comment]
https://mobx.js.org/best/decorators.html
Scroll down to *Enabling decorator syntax* part

**Comment by devYoungyang** [comment]
我的react-native版本是0.54.4，根据文档配置还有插件需要添加，运行还是报错

**Comment by ilovedesert001** [comment]
use typescript

**Comment by devYoungyang** [comment]
0.54.4不支持TypeScript，原因是react-native 0.54.4使用babel版本号是6，而mobx4需要babel是7

**Comment by FredyC** [comment]
@devYoungyang Try to explain your issue in English please so someone can actually help you.

**Comment by aretecode** [comment]
[google translate (_"Chinese (Simplified)"_ => _"English"_)](https://translate.google.com/?langpair=en%7Czh-CN#view=home&op=translate&sl=zh-CN&tl=en)

https://github.com/mobxjs/mobx/issues/1971#issue-446024240
> decorators... how to configure babel? how to install plugins?

https://github.com/mobxjs/mobx/issues/1971#issuecomment-494210628
> My react-native version is 0.54.4, depending on the documentation configuration, there are plugins to add, run or report an error.

https://github.com/mobxjs/mobx/issues/1971#issuecomment-494255951
> 0.54.4 does not support TypeScript
> React-native 0.54.4 using babel version number 6
> mobx4 needs babel 7

---

@devYoungyang 

1. https://medium.com/react-native-training/react-native-with-mobx-getting-started-ba7e18d8ff44
2. [google translate ( _"English"_ => _"Chinese (Simplified)"_)](https://translate.google.com/?langpair=en%7Czh-CN#view=home&op=translate&tl=zh-CN)

> '  upgrade your version of "react-native".  '

(_translating that back and forth a couple times still seemed to make sense_)

**Comment by FredyC** [comment]
@aretecode Thanks, I tried to google translate but had a hard time anyway to understand. Well, it's 20 days, I expect he solved it.
