### ISSUE TITLE
[TypeScript] ObservableMap -  clear and replace methods doesn't exists in the _proto_ .

### ISSUE THREAD

**Issue by elcrespito** [mobxjs/mobx#1972]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by elcrespito** [comment]
Use TypeScript.

Create such an object

@observable public items: ObservableMap<string, Item> = observable.map();

this.toasts.clear(key); - clear doesn't exists. Same to replace.

As for observable.array, we have the same issue.

**Comment by elcrespito** [comment]
Use TypeScript.

Create such an object

@observable public items: ObservableMap<string, Item> = observable.map();

this.toasts.clear(key); - clear doesn't exists. Same to replace.

As for observable.array, we have the same issue.

**Comment by ItamarShDev** [comment]
@elcrespito Please follow the issue guidelines to help us get to the issue in the best possible way.
please state your versions and configuration so we could check it out (as stated in the issue template)

thank you

**Comment by elcrespito** [comment]
TypeScript: 3.4.2
"mobx": "^5.9.4",
"mobx-react": "^5.4.3",
"react": "^16.8.6",
"react-dom": "^16.8.6",

**Comment by ItamarShDev** [comment]
thank you!

**Comment by elcrespito** [comment]
You are welcome!
