### ISSUE TITLE
How to fix: 'Object is possible undefined' in react with typescript and mobx

### ISSUE THREAD

**Issue by KakarN** [mobxjs/mobx#1974]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

2. [*] Issue:

I have a mobx store (`AnimalStore`), which has an observable list of animals. And also, I have two components (ParentComponent and ChildComponent).

On the ParentComponent, I am displaying the total animals count, which I am getting from the observable list of mobx injected store (`animalStore.animals`). And on the ChildComponent, I am displaying all the animals, also from the observable list of mobx injected store (`animalStore.animals`).

On the ParentComponent, I am setting the props interface for the store as required. On the ChildComponent, I am setting the props for the store as optional.

But, I am getting a typescript error on the ChildComponent when I am trying to access `this.props.animalStore`:

> Object is possible undefined.

However, if I change the optional store props of ChildComponent as required, the error `Object is possible undefined.` goes away, but, on the ParentComponent I am getting error:

> Property of animalStore is missing in type '{}' but required in type 'Readonly'.

```
// ParentComponent.tsx

interface IProps {
    animalStore: AnimalStore
}

@inject('animalStore')
@observer
export default class ParentComponent extends React.Component<IProps> {
    render() {
        return (
            <View style={styles.container}>
                <Text>Total animals: {this.props.animalStore.animals.length}</Text>
                <SecondComponent/>
            </View>
        )
    }
}


// ChildComponent.tsx 

interface IProps {
    animalStore?: AnimalStore
}

@inject('animalStore')
@observer
export default class ChildComponent extends React.Component<IProps> {
    render() {
        return (
            <ScrollView style={styles.container}>
                {
                    this.props.animalStore.animals.map((el: string) => {
                        return <Text key={el}>{el}</Text>
                    })
                }
            </ScrollView>
        )
    }
}
```

How can I fix this issue of typescript and mobx?

I am working with mobx: 5.9.4, mobx-react: 5.4.4

**Comment by FredyC** [comment]
You might want to consider replacing obsolete `inject` with more robust approach...

https://mobx-react.js.org/recipes-inject

**Comment by mweststrate** [comment]
See https://github.com/mobxjs/mobx-react/issues/256 for the why and a bunch of different solutions. The simplest one is `this.props.animalStore!.something`.
