### ISSUE TITLE
Enable global trace()

### ISSUE THREAD

**Issue by spion** [mobxjs/mobx#1978]
3. [x] Idea:

Can we add a global `trace()` functionality to MobX?

Currently trace is for specific derivations, however, in some cases its unclear which reactions or computations are running at a given moment and why (like for example a RangeError stack blow-out due to too long chain of computeds). 

For these cases it might be helpful to have a global tracing functionality that you can enable or disable.

PR should be relatively easy to do, all we need is another flag in the globalState called globalTracing, and changes in the if condition of all the trace calls.

**Comment by ItamarShDev** [comment]
Isn't spy what you need? https://mobx.js.org/refguide/spy.html
