### ISSUE TITLE
version 4.10 requires polyfill for getOwnPropertySymbols

### ISSUE THREAD

**Issue by weitalu** [mobxjs/mobx#1987]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: 

https://github.com/mobxjs/mobx/blob/4.10.0/src/utils/utils.ts#L174

The method 'Object.getOwnPropertySymbols' breaks my app in IE 11 after I upgraded to 4.10,

Is this a intended work?

**Comment by loklaan** [comment]
No, it's an unintended break, please stay on `4.9.4` until it's resolved

**Comment by mweststrate** [comment]
Fixed in 4.11.0
