### ISSUE TITLE
Request for a more detailed spy: Log reaction

### ISSUE THREAD

**Issue by hediet** [mobxjs/mobx#1990]
I would like to track which specific reaction got triggered, not just the name. It does not seem to be possible at the moment, as only the name is logged [here](https://github.com/mobxjs/mobx/blob/b56ca5fcc86420cfbf8654a1e1837b1d34b2ce56/src/core/reaction.ts#L131).
Are you open for PRs here?

**Comment by FredyC** [comment]
We are looking for maintainers (#1983) so PRs might take longer to get through right now but I suppose PR won't do much harm in this case.

**Comment by mweststrate** [comment]
Added a ready for volunteer and closing, as there is further no need to act on this issue.
