### ISSUE TITLE
Computed properties enumerable depends on property access

### ISSUE THREAD

**Issue by fijiwebdesign** [mobxjs/mobx#1991]
When you set a computed getter to enumerable, it will not become enumerable until you access the property. 

`mobx-4.6.0`
`node v11.14.0`
`jest@23.6.0`

Here is a test case. 

```
import { toJS, computed, observable } from 'mobx'

class MockModel {
  @observable foo = 'foo'
  @computed get bar() {
    return 'bar'
  }
}

describe('mobx', () => {
  it('observable props are enumerable', () => {
    const model = new MockModel()
    expect(toJS(model).foo).toBe(model.foo)
  })
  it('computed props are not enumerable', () => {
    const model = new MockModel()
    expect(toJS(model).bar).toBe(undefined)
  })
  it('computed props can be made enumerable', () => {
    const model = new MockModel()
    Object.defineProperty(model, 'bar', { enumerable: true, configurable: true })
    expect(model.bar).toBe(toJS(model).bar) // success
  })
  it('computed props can be made enumerable without accessing property', () => {
    const model = new MockModel()
    Object.defineProperty(model, 'bar', { enumerable: true, configurable: true })
    expect(toJS(model).bar).toBe(model.bar) // fail
  })
})
```

If this is a bug I can attempt a PR.

**Comment by FredyC** [comment]
If I understand your test case correctly, you are replacing originally computed variable with a completely new variable by calling `defineProperty`? How would expect from MobX too keep track of it when you do something like that?

If there some other problem, can you please provide a working example (ideally CodeSandbox) with a better focus on what you think is wrong?

**Comment by fijiwebdesign** [comment]
Here's a code sandbox: 

https://codesandbox.io/s/amazing-frog-b2vxi

If you comment out line 25 `toJS(model),` it will fail. This is only with with the 4.x versions. 
With 5.x versions the property description is not configurable. 

### Note: 

```
Object.defineProperty(model, "bar", {
      enumerable: true
    });
```

Does not replace the property, it only modified the enumerability, so the property getter is untouched. 

### Notes: 

* It appears mobx will build property descriptors on the object itself when toJS() is called on it. 
* In 4.x the property descripter is `{get: function get(), set: function set(), enumerable: false, configurable: true}`
* In 5.x the property descriptor is `{get: function get(), set: function set(), enumerable: false, configurable: false}`
* In both versions the property descriptors are only attached to the object when `toJS()` is called on it. 

* Defining enumerable on the prototype doesn't seem to make it enumerable: 
```
Object.defineProperty(model.constructor.prototype, "bar", {
      enumerable: true
    });
```
* This is internal API so probably not a bug but the question is how to you make the getters enumerable. 

My use case is that I have models that need to have their properties enumerated for validation before it gets sent to the server to storage.

**Comment by FredyC** [comment]
Well, MobX 5 is building on top of Proxies. Frankly, I haven't used Proxies anywhere yet so I don't know its specifics, but it's highly likely the reason why you cannot change enumerability of such property.

I don't exactly follow why you would want to serialize computed properties. They are derivations of some state value and as such should be always recomputed from those values. Point is that you cannot actually write to computed property, so you cannot really deserialize such state.

However, if you really need to serialize only I think you should be doing it manually by assigning values to a new (non-observable) object.

The whole approach with `decorate` feels so much legacy these days :)

**Comment by urugator** [comment]
Afaik re-configuring observable properties isn't supported.

Legacy property decorators don't have an access to `this`.
So as a workaround Mobx creates `configurable` temporal descriptor first, which lazily reconfigures itself to actual descriptor upon it's first invocation. In your case the property is firstly accessed in `toJS`, so that's when the "final" descriptor is set.

**Comment by fijiwebdesign** [comment]
> So as a workaround Mobx creates configurable temporal descriptor first, which lazily reconfigures itself to actual descriptor upon it's first invocation.

@urugator  Is "Legacy property decorators" the use of `decorate()` or the use of the legacy `@decorator` syntax or both? 
I assumed `@decorate` is syntactic sugar over `decorate()`? 

> Well, MobX 5 is building on top of Proxies.

Makes sense. My specific use case is MobX 4.x - if that's still maintained. 

> I don't exactly follow why you would want to serialize computed properties. They are derivations of some state value and as such should be always recomputed from those values. Point is that you cannot actually write to computed property, so you cannot really deserialize such state.

I may be using computed props for more than intended like: 

* validation
* ensuring a lazy memoized initial value
* doing other work on prop access

```
const uid = () => Math.random()

class Model {
  /**
   * @property {string} Memoized UID
   */
  @computed get uid() {
    return this.getAttribute('uid', () => uid())
  }
  /**
   * @param {string} Memoized UID
   */
  set uid(uid) {
    // superfluous example
    if (!validateSomehow(uid)) throw new TypeError('Invalid uid')
    if (this.getAttribute('uid')) throw new TypeError('Uid already exists')
    this.setAttribute('uid', uid)
    if (this.isCreatedFromRemote()) syncLocalStorageUpdates() 
  }
 
  /** 
   * @return an observable memoized value for the key
   */
  getAttribute(key: string, initialValueFn: function) {}

 /** 
   * set an observable concrete value for the key
   */
  setAttribute(key: string, value: any) {}

  toJSON() {
    // cycle through enumerable props return a serialized JSON structure
  }

  @action from JSON(json) { 
    // cycle through each key/value, validate is enumerable and set prop
  }
}
```

This enables lazy generation of a memoized unique ID for each model. 
This `uid` can be serialized with the model and deserialized to a new model that hasn't generated a uid. 
Doing this with an `observable` would be more messy I think (You'd put the equivalent validations in getUid(), setUid(), validateUid() etc. and invoke from outside scope in non-deterministic manner) - thus this approach requires the computed value to be serializable. 
I believe this is personal preference and would like to know what the best practise here is if I'm going about it upside down.

**Comment by urugator** [comment]
> @urugator Is "Legacy property decorators" 

By "legacy decorators", I mean decorator syntax used by Mobx, which may not be up-to-date with the latest version of the EcmaScript proposal. Therefore the need for:
` ["@babel/plugin-proposal-decorators", { "legacy": true }]` in babel config.

Neither of `@decorator`/`decorate()` is considered legacy or deprecated if that's your question.

**Comment by urugator** [comment]
Few notes:
- `computed` must depend solely on observables
- `computed` must not contain any side effects (state modifications)
- by default `computed` cache isn't persistent, you need `computed({ keepAlive: true })`
- you should treat computed cache as an optimization, not a quarantee
