### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read property 'get' of undefined at extendObservableObjectWithProperties

### ISSUE THREAD

**Issue by RosenTomov** [mobxjs/mobx#1995]
Since ver. 5.10 I'm getting the following error:

`Uncaught TypeError: Cannot read property 'get' of undefined at extendObservableObjectWithProperties`

It looks like descriptor (from `Object.getOwnPropertyDescriptor()`) is null (`descriptor.get`):
```
function extendObservableObjectWithProperties(target, properties, decorators, defaultDecorator) {
    if (false) { var key, i, keys; }
    startBatch();
    try {
        var keys = getPlainObjectKeys(properties);
        for (var i in keys) {
            var key = keys[i];
            var descriptor = Object.getOwnPropertyDescriptor(properties, key);
            if (false) {}
            var decorator = decorators && key in decorators
                ? decorators[key]
                : descriptor.get // <-- descriptor is null
                    ? computedDecorator
                    : defaultDecorator;
            if (false)
                {}
            var resultDescriptor = decorator(target, key, descriptor, true);
            if (resultDescriptor // otherwise, assume already applied, due to `applyToInstance`
            )
                Object.defineProperty(target, key, resultDescriptor);
        }
    }
    finally {
        endBatch();
    }
}
```

https://github.com/mobxjs/mobx/blob/6c1d807a44dfc32567f3e55231eb1464a2155826/src/api/extendobservable.ts#L102

Version 5.9.4 works fine.

Thanks.

**Comment by aretecode** [comment]
https://github.com/mobxjs/mobx/issues/1994
^ as with this issue, both have issues with the `getPlainObjectKeys`

**Comment by recover758126** [comment]
> #1994
> ^ as with this issue, both have issues with the `getPlainObjectKeys`
The parameter `properties` of `getPlainObjectKeys` and `getOwnPropertyDescriptor `  cannot be `null` or `undefined`,  is it necessary to call the`extendObservableObjectWithProperties ` function ?

**Comment by stolenng** [comment]
Getting the same error, any solutions ?

**Comment by ItamarShDev** [comment]
@FredyC do you know the status of this issue?

**Comment by FredyC** [comment]
@ItamarShDev Well, I tagged it that we need reproduction. Otherwise, it's guesswork probably.
