### ISSUE TITLE
Default generics types to unknown or upper bound instead of any 

### ISSUE THREAD

**Issue by quanganhtran** [mobxjs/mobx#1997]
I have a:

3. Idea:

Generics in MobX repositories often default to `any` if not inferable. With TypeScript 3.5, generics are now defaulted to `unknown` instead of `{}`, which I think is the most suitable type for non-inferable generics, instead of the permissive `any` (which will leak to all the code following it). I propose to change MobX TypeScript typings by removing the default `any`

It is just an idea. I haven't investigated whether there is any negative impact introduced by this change.

  * [x] Are you willing to (attempt) a PR yourself? Yes

E.g.
```diff
export interface IObservableFactories {
-   box<T = any>(value?: T, options?: CreateObservableOptions): IObservableValue<T>;
+   box<T>(value?: T, options?: CreateObservableOptions): IObservableValue<T>;
}
```

**Comment by FredyC** [comment]
Wait, if you don't include default type, doesn't it mean it will require one when used? If not that it sounds like an interesting idea for sure.

**Comment by quanganhtran** [comment]
@FredyC now that you mentioned it, I think it goes like this:
- If you specify T in `<T, U>`, then TS will want you to specify U as well.
- If you skip specifying the generics altogether, TS will try to infer the type of the generics, and if not, fallback to top type `unknown`.
- In any case, if we need to provide a default (e.g. when we want to partially skip explicitly specifying a generic parameter), we should use `unknown` instead of `any`.

```ts
function makeMap<K, V>(): Map<K, V> {
    return new Map([]);
}

function makeMapAny<K, V = any>(): Map<K, V> {
    return new Map([]);
}

function makeMapUnknown<K, V = unknown>(): Map<K, V> {
    return new Map([]);
}

const a = makeMap(); // Map<unknown, unknown>
const b = makeMap<string>(); // Error
const c = makeMapAny(); // Map<unknown, any> -> leaking any
const d = makeMapUnknown<string>(); // Map<string, unknown>
```
The TS playground seems to be still in 3.4 so no link to snippets

**Comment by FredyC** [comment]
Ok, that makes sense. Using `unknown` as default instead of `any` should work just fine.

It would also mean that we will be supporting TS 3.0+ only. It's not explicitly stated anywhere and it most likely doesn't warranty for a next major for breaking change. I am not even aware if we are using some other features of TS 3. Perhaps it's time to mention that in docs.

Either way, I suppose you can start by preparing a PR. We should probably backport it to MobX4 as well.
