### ISSUE TITLE
Way to automatically dispose reactions that *aren't* associated with a React component lifecycle?

### ISSUE THREAD

**Issue by bsmith-cycorp** [mobxjs/mobx#2001]
A common pattern with MobX is to define "store" classes whose properties are observables. But if one sets up reactions in that class's constructor, are those automatically memory leaks? Would it be possible to make an equivalent of `disposeOnUnmount()` for regular class instances that cleans up reactions when they go out of scope, or is that impossible in JavaScript because it doesn't have destructors?

**Comment by FredyC** [comment]
You are in the wrong repo ... https://github.com/mobxjs/mobx-react
React hooks makes that much simpler... https://mobx-react.js.org/recipes-effects
And duplicate :) https://github.com/mobxjs/mobx-react/issues/561

**Comment by bsmith-cycorp** [comment]
I think you misread, @FredyC. I'm specifically looking for an analogous solution which *doesn't* require any interaction with React.

**Comment by FredyC** [comment]
Right...Sorry, but that's out of scope and heavily depends on how you keep track of your reactions. No built-in way to handle that, nope.
