### ISSUE TITLE
Consolidate configs across MobX repos

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2002]
With so many repos it's getting hard to keep all config changes in sync. Some time ago I've run into this tool and I am thinking of creating MobX preset. Haven't really tried it yet, but sounds interesting for sure. Opinions?

https://www.npmjs.com/package/mrm#custom-presets

**Comment by goldylucks** [comment]
What presets would you put in there? babel? linting?

**Comment by FredyC** [comment]
I haven't dived much into the detail yet and did not use that tool yet anywhere. Seemed just a like a cool idea :) For example, recently we were configuring CircleCI, that quite a huge config that's pretty much copy pasted. Or a configuration for a Stale bot could be reused as well. Or templates for issues/prs which we are still not using but we definitely should. There is a lot of things that could be shared for sure, not just obvious ones.

**Comment by goldylucks** [comment]
ohhhh haha now I get it, you mean Mobx own repos, not repos of projects which use mobx. Gotcha :)

**Comment by Bnaya** [comment]
Another candidate tool:
https://github.com/neutrinojs/neutrino

**Comment by FredyC** [comment]
@Bnaya Thanks, but I don't it's a good fit. We don't need "zero configuration" but "shared configuration" :)

**Comment by Bnaya** [comment]
Neutrino is ment also for that

**Comment by FredyC** [comment]
I haven't really crawled through their docs that extensively, but can you give an example of how we could share for example CircleCI config? Or the ones for Stale/Lock bots?

**Comment by xaviergonz** [comment]
What about just using tsdx everywhere?

**Comment by FredyC** [comment]
Uhh, how is TSDX related to eg. CircleCI config? :)

**Comment by xaviergonz** [comment]
My bad, for whatever reason I thought it was about consolidating the whole build system :)

**Comment by FredyC** [comment]
Meh, I am not that thrilled about the idea anymore, so let's dump it :)
