### ISSUE TITLE
mobx5 can't call my object

### ISSUE THREAD

**Issue by kirhim** [mobxjs/mobx#2005]
I used to use mobx4 and it worked fine when I called my object but when I upgraded to mob5 it won't work. 

When I run this code:
`console.log(store.memberObject)`
I get data like this:
`Proxy {Symbol(mobx administration): ObservableObjectAdministration} "memberObject"` 

How could I call object in mobx5?

**Comment by urugator** [comment]
It's just how `console.log` works. For everything else it's normal object.
To print it as usual use `console.log(mobx.toJS(store.memberObject))`
For further details check #1653
