### ISSUE TITLE
How to give name to a bound action?

### ISSUE THREAD

**Issue by nagylzs** [mobxjs/mobx#2008]
It is possible to give names to actions:

    @action('actionName')

But I don't see how could I add this to action.bound. I have tried these:

    @action('actionName').bound
    @action.bound('actionName')

**Comment by goldylucks** [comment]
From the [docs](https://mobx.js.org/refguide/action.html#bound-actions):

>  Note that unlike action, (@)action.bound does not take a name parameter, so the name will always be based on the property name to which the action is bound

Are you asking if there's a way to override this default behavior?

**Comment by nagylzs** [comment]
Yes, I would like to specify the name of the action manually. I need this because I have multiple methods with the same name, and I would like to give them different names so I can distinguish between then in MobX developer tools. I cannot rename the methods because they are overriding other methods from base classes. So their TypeScript name must be the same, but I really need to give them different names in MobX. Right now I cannot do this and it makes debugging harder. Possibly I could bind all of them manually but this is something I just don't like.

**Comment by goldylucks** [comment]
Have you tried `mobx-logger`? it logs the name of the class as well as the action:

![image](https://user-images.githubusercontent.com/6963212/60535250-5c95cb80-9d0c-11e9-86ca-85af075219a7.png)

As you can see I have `hydrateState` method in each of my classes, and I can differentiate between them easily.

**Comment by nagylzs** [comment]
I have never used it, but it looks like a solution. Please wait some hours, I'm going to try it.

**Comment by nagylzs** [comment]
I need more time to configure this, but it will solve my problem. Thanks.
