### ISSUE TITLE
mobx array observable not updating on splice

### ISSUE THREAD

**Issue by MarcDAFrame** [mobxjs/mobx#2010]
I have an array that I am observing in a mobx store. when I attempt to reorder it using the array splice method it fails to call the observe function and do some console.logs.

here is a codesandbox I've created for the issue
[https://codesandbox.io/s/cool-bas-gy1cn?fontsize=14](https://codesandbox.io/s/cool-bas-gy1cn?fontsize=14)

all details concerning my setup are in the codesandbox, the only thing missing is that I'm not using mobx-react for this example, but that doesn't affect the behavior

**Comment by urugator** [comment]
`observe` is not deep, try `observe(this.listOne)`
`App` must be `observer`
