### ISSUE TITLE
Setup a stale bot

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2015]
It's not like we would be having hundreds of issues here, but still, might be worth to be auto closing stale issues.

@xaviergonz Can you please do an initial setup?

**Comment by ItamarShDev** [comment]
this? https://probot.github.io/apps/stale/

**Comment by FredyC** [comment]
@ItamarShDev Yea, that one :)

**Comment by ItamarShDev** [comment]
Added to mobx repo

**Comment by FredyC** [comment]
Great, I am not sure if it needs some other configuration. I would be expecting it take care of old issues and mark them as stale. I only saw it in action, never configured that one.

**Comment by ItamarShDev** [comment]
we do, submitting PR
