### ISSUE TITLE
Can I dispose an observe function in its listener like reaction?

### ISSUE THREAD

**Issue by mannok** [mobxjs/mobx#2026]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ v ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

According to the docs, effect function receives a reaction param to let developer dispose the reaction so that the reaction can run only once. May I know that if I can do the same thing in observe function?

**Comment by FredyC** [comment]
Why? What would you gain by that? The observe function should pure and return observable you want to observe. Nothing else.

Either way, the reaction also returns a disposer function which you can call whenever you want, but I really advise you not to do that in observe function. It's certainly not a documented and as such might cause unexpected bugs.

**Comment by mannok** [comment]
If "the observe function should be pure", then what is the use of observe function? As docs just show us an example of logging in observe function. Other than logging, I cannot think of another use case...

**Comment by FredyC** [comment]
Wait, what? Can you show the specific example/link document you are talking about?
