### ISSUE TITLE
"why did you update" warns unnecessary rerenders of observer components

### ISSUE THREAD

**Issue by goldylucks** [mobxjs/mobx#2028]
I have a:
2. [ ] Issue:
  * [x] **Provide error messages including stacktrace**

```js
// not error but warning from [`@welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render)
whyDidYouRender.min.js:1159 {inject-DishType-with-rootStore: ƒ} "Re-rendered because the props object itself changed but it's values are all equal." "This could of been avoided by making the component pure, or by preventing it's father from re-rendering." "more info at http://bit.ly/wdyr02"
```

  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**

https://codesandbox.io/s/minimal-mobx-react-project-28jic

  * [x] Did you check this issue wasn't filed before?

Yes

  * [x] Elaborate on your issue. What behavior did you expect?

I expect to not see the warnings in the console from why did you render package. If I implement `shoudlComponentUpdate` myself then the warning goes away, but a warning from `mobx-react`pops up to not `shoudlComponentUpdate` on observer components.

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

``` bash
$ cat node_modules/mobx/package.json | grep version
  "version": "5.9.4",

$ cat node_modules/mobx-react/package.json | grep version
  "version": "5.4.4",

$ cat node_modules/@welldone-software/why-did-you-render/package.json | grep version
  "version": "3.2.1",
```

I'm willing to try and PR this myself with some guidance - I want to contribute to mobx regardless of this issue :)

**Comment by FredyC** [comment]
Well, I've investigated slightly and the fact is that at the moment you remove `<DevTools />`, the warnings are gone. I haven't personally used devtools much, but I wouldn't be surprised if it would be doing some extra stuff that is not exactly optimal and might causing re-renders more often.

Btw, in mobx-react V6 the use of devtools is no longer possible. Instead, use of React Devtools is recommended. Perhaps it's not worth the hassle trying to figure this one out :)

**Comment by goldylucks** [comment]
Good catch Fredy! 

In my local project I have no dev tools, and this still happens ... Any ideas where should I start to investigate?

**Comment by FredyC** [comment]
Sorry, no ideas, I am not a performance hunter, never used that tool for discovering unnecessary re-renders. Ultimately it's rarely a source of the problem as long as the output of that rendering is the same. In that case, it just creates a bunch of extra objects in memory that will be garbage collected, but DOM won't be changed at all.

Aren't you planning to migrate to V6? Many people are reporting it's actually faster on its own. It might perhaps even solve some extra re-render issues.

**Comment by goldylucks** [comment]
> Premature optimization is root of all evil, keep that in mind :)

hahaha I know that man, we have one screen in the app that's lagging, hence the performance hunt.

> Aren't you planning to migrate to V6?

Where can I find info on that?

(btw, I will leave this open for a few days in hope of someone shedding some light on the issue)

**Comment by FredyC** [comment]
> Where can I find info on that?

Well, there is a changelog :) The only possible problem is that you need the React 16.8. Otherwise, there are no essential breaking changes.

**Comment by mweststrate** [comment]
> Any ideas where should I start to investigate?

Create a reproduction by stripping until you have just that component, it's parent, and still the same issue :) Without such a thing we can't really help you. Note that all the normal React rules still apply. So if you pass for example `<child style={{ color: "red" }}>` it can cause wasted renderings on child as you are passing a new object every time, which is further unrelated to mobx.

**Comment by mayorovp** [comment]
This warning means that WDYR cannot find reason for render because WDYR does not track `forceUpdate` calls.

I think this is a WDYR issue.

**Comment by goldylucks** [comment]
Seems like the warning stopped showing in the console of the sandbox, so I'm closing this for now :)
