### ISSUE TITLE
Is it possible to cache computeds that are not observed at the moment?

### ISSUE THREAD

**Issue by mixtur** [mobxjs/mobx#2030]
Is it possible for computed values to be invalidated, but not recomputed when observables they depend on are changed?

Now we have two options. 
- Do not observe at all. Then computed essensially becomes regular getter.
- Observe. Then computed is cached until observables they depend on are changed, but recomputed even it is not needed.

I have pretty heavy computed, that changes a lot, but it's value needed less often than it changes. Also I rely on it being immutable'ish. (subject to ===). So I would be happy to avoid unnecessary recomputations.

Here is simple example.
```js

class A {
    @observable.ref
    b = 0;

    @computed
    get c() {
        console.log(`compute c, b=${this.b}`);
        return this.b + 1;
    }
}

const a = new A();

Reflect.get(a, 'c');
Reflect.get(a, 'c');
a.b = 1;
Reflect.get(a, 'c');
Reflect.get(a, 'c');

console.log('start observing');
observe(a, 'c', () => {});

a.b = 2;
Reflect.get(a, 'c');
Reflect.get(a, 'c');

a.b = 3;
Reflect.get(a, 'c');
Reflect.get(a, 'c');

a.b = 4;
a.b = 5;
```
In this example I would like to either avoid duplicate messages before 'start observing', or avoid messages about 4 and 5.

**Comment by spion** [comment]
See https://github.com/mobxjs/mobx/issues/1332

**Comment by urugator** [comment]
Use `@computed({ keepAlive: true })`, it shouldn't recompute since #1799

**Comment by mweststrate** [comment]
Closing as answered
