### ISSUE TITLE
Memory leaking of Observable Maps (), because _hasMap keeps links on all once used keys (key could be object) and never delete them

### ISSUE THREAD

**Issue by BanderasPRO** [mobxjs/mobx#2031]
Issue:
I find that observable Maps absolutely always loose a memory. For every key of the map, you create same key in your private map called _hasMap and place there a boolean value. But these keys are kept there even the origin map is empty or already doesn't contain the key. Don't forget that key could be large object or linked with many other objects. So we loose all memory even we don't keep links (have variables) to these key object in our code, because the _hasMap keeps links on all once used keys (key - is the big object, remember ?) and never delete them.

Please see the example:
https://codesandbox.io/s/minimal-mobx-react-project-1uyb0

Of cause we expected that we don't see the our objects in memory heap, after clearing the map.

Idea:
You should use another mechanism to register of using the map methods and of getting values.

**Comment by FredyC** [comment]
I wonder if WeakMap could be helpful here.

**Comment by BanderasPRO** [comment]
@FredyC 
It seems WeakMap can't help. _hasMap keep values which are observable boolean, and I think that something was subscribed on that observable to detect an access to a Map, maybe to register dependency on the Map. So, if it is then the subscription does't allow to free the memory as for key object as for value either.

**Comment by BanderasPRO** [comment]
+++
you also loose a memory when you just use 'has' method of a map. Once you used `has(key),` the key will put into the _hasKey forever

So the `observable.map` with `_hasKey` map is deep hole to loose memory

**Comment by FredyC** [comment]
Yea, I have no idea why is it implemented like that. Hopefully, @mweststrate can stop by and shed some light onto this.

**Comment by mayorovp** [comment]
We can remove unobserved atoms from this map...

**Comment by mweststrate** [comment]
IIRC there is no specific reason for it being implemented this way, than mere legacy. Up to MobX 4 only primitives were supported as map keys, so the problem (barely) existed in that scenario.

A PR that cleans up unobserved entries as suggestd by @mayorovp  in the `hasMap` is welcome!

**Comment by mayorovp** [comment]
@mweststrate what about my PR?

**Comment by mweststrate** [comment]
Apologies, looked over that!

**Comment by mweststrate** [comment]
Released as 4.13.0 / 5.13.0
