### ISSUE TITLE
Can I trigger another reaction in one reaction's sideEffect?

### ISSUE THREAD

**Issue by mannok** [mobxjs/mobx#2036]
I have a: Question

According to doc explanation, observables in reaction's "sideEffect" won't be tracked. That means there is only 1 reaction triggered for 1 observable mutation. 

I found mobx because I used to develop web using vue. Vue's reactive system allow us to chain reaction. For example, I can observe `state.foo` and mutate `state.bar` in the handler. At the moment if I have another observer which is observing `state.bar`, it will be triggered too. Therefore, I can design the system with such "chained reaction".

May I know if I can achieve such design with mobx?

**Comment by mayorovp** [comment]
Have you tried to do this?

**Comment by mannok** [comment]
@mayorovp Sorry, I tried just now and it works. However, what is it meant by 

> Any observables that are accessed while executing the side effect will not be tracked.

in [https://mobx.js.org/refguide/reaction.html](url)

**Comment by mayorovp** [comment]
"tracked" == "observed"
"tracked" != "triggered"

**Comment by mannok** [comment]
Sorry I don't clear what is the mean by "observed". Does it mean that `observe()` of the observable won't be triggered?

**Comment by mayorovp** [comment]
It is your word: *"For example, I can observe state.foo and mutate state.bar in the handler. "*

In some reaction you are observing (tracking) `state.foo` and mutating `state.bar`. You are not observing (tracking) `state.bar` in that reaction, but you can observe (track) it in another reaction.

**Comment by FredyC** [comment]
@mayorovp is right. Nothing is preventing you to execute further mutations in reaction effect. You can observe those changes by another reaction if you want. Just make sure you don't run into loop by mutating state that first reaction is observing :D
