### ISSUE TITLE
docs > Best Practices Performance references PureRenderMixin, now it's PureComponent

### ISSUE THREAD

**Issue by benatkin** [mobxjs/mobx#2037]
On the [Best Practices Performance Page](https://mobx.js.org/best/react-performance.html) it references PureRenderMixin which is a legacy add-on. I think it should reference [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent) and/or [memo for hooks](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-shouldcomponentupdate). Sorry for the lack of PR.

**Comment by FredyC** [comment]
Thanks for the suggestion. We are generally working toward having a dedicated site for React. That particular page on mobx.js.org will be probably removed eventually.

https://mobx-react.js.org
