### ISSUE TITLE
How can I check mobx version in runtime

### ISSUE THREAD

**Issue by Mess1ah** [mobxjs/mobx#2038]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

- [ x ] Question: I wonder how to get mobx version in runtime . I have noticed that It has already export MobXGlobals in globalstate.ts and it has a `version` property. But it writes in annotation:

> this version is unrelated to the package version of MobX, and is only the version of the internal state storage of MobX, and can be the same across many different package versions

I want to check the mobx version in the project to avoid the problem causing by using both mobx 4 and mobx 5.

**Comment by FredyC** [comment]
Probably duplicate of #1957
Please read through that and if you still have a question, elaborate more what you have in mind.

**Comment by Mess1ah** [comment]
Sorry, I don't think my question is duplicate of that one.
> Probably duplicate of #1957
> Please read through that and if you still have a question, elaborate on what you have in mind exactly.

My question is can mobx export the package version in global variable. Just like what React do in the picture below.
![image](https://user-images.githubusercontent.com/11548784/60936361-649ece00-a2ff-11e9-8ecc-8e58409c65de.png)

The situation is when some packages depend on mobx 4 and if user install mobx 5 , there will be 2 different mobx versions in project which will cause some problems. So I need check the mobx version in my package which depends on mobx 4 and throw out errors when I detect the mobx version installing in the project is mobx 5.

At present,  Mobx has already export MobXGlobals in globalstate.ts and it has a version property. But it is not the package version so it can't solve my problems

**Comment by FredyC** [comment]
Alright, that's certainly an interesting idea, but comes with certain overhead who is going to be updating that version number :) Are you willing to investigate how React does that (I doubt it's a manual process).

I am not entirely sure how the release process works here. If a regular `npm version` command is used to set a version or what.

ping @xaviergonz @ItamarShDev

**Comment by Mess1ah** [comment]
I investigated React source and found out React has a file called [ReactVersion](https://github.com/facebook/react/blob/master/packages/shared/ReactVersion.js). It looks like changing manually

**Comment by Mess1ah** [comment]
Maybe we can define a property in export modules and replace by rollup-plugin-replace while building. But I noticed that the project changes version number when running `publish` script, but the `publish` script  will run after `build`

**Comment by FredyC** [comment]
Build definitely runs before publish, we don't publish old version :) Rollup plugin might be not such a good idea because we want to eventually switch over to some build tool like microbundle.

**Comment by Mess1ah** [comment]
Yep, of course we should build before publish. Maybe we can use pre-publish hooks to change version in package.json and build the package?

**Comment by FredyC** [comment]
Man, I cannot give you a straight answer here because I am not doing publishing in this repo. Let's wait for someone responsible to answer that.

Either way, what I wanted to suggest. Isn't actually feature testing better than relying on a specific version? For example, when React Hooks came out, many libraries opted for checking if `React.useState` is available to verify a necessary version. With all those alpha versions it would be hard to check that properly.

I can't tell you what exactly V4 has and what V5 doesn't, but I am sure you can find some difference there and base your decision on that.

**Comment by FredyC** [comment]
Btw, your decision on version number would be also slightly crippled and relying on people to have the latest version from either branches. With feature testing, you can do right now even with the older versions.

**Comment by Mess1ah** [comment]
Yep, your words make sense. I will figure out can I distinguish between V4 and V5 by checking api difference. Thanks for your idea.

**Comment by mweststrate** [comment]
> The situation is when some packages depend on mobx 4 and if user install mobx 5 , there will be 2 different mobx versions in project which will cause some problems. 

This should be picked up and detected automatically by MobX already, and there should be no need for you to check this manually. (That is exactly what that `version` property is for btw). 

If you have an actual problem with it, please provide a reproduction, otherwise this issue can be closed as you are trying to solve an issue that MobX should already take care of for you :)

**Comment by farwayer** [comment]
This can be useful for third-party libraries that peerDepends on MobX.

**Comment by Mess1ah** [comment]
I have checked out the error trace. It is caused by the bellow code:
![image](https://user-images.githubusercontent.com/11548784/61196037-a912db00-a6fe-11e9-8bfa-3e9eef907796.png)
This code is invoked by following code which is simply set a symbol type key in the object. And because of `Object.proxy`, It calls the code showing in the first photo.
![image](https://user-images.githubusercontent.com/11548784/61196259-d4e29080-a6ff-11e9-8b03-219391905502.png)
When running the conditional sentence `!isNaN(name)`(name is a symbol type variable), It causes an error.
So I guess it maybe a bug? Certainly I can avoid it by using Mobx4, so in order to prevent this similar situation from causing errors, maybe checking version by user is essential.

**Comment by mweststrate** [comment]
@Mess1ah it is completely unclear what "the error" refers to, or how this relates to the current issue atm. 

Note btw that matching libraries is not a runtime problem, but a design time problem, and setting `peerDependencies` of your package correctly should result in your package manager giving warnings about this.

**Comment by FredyC** [comment]
> of your package correctly should result in your package manager giving warnings about this.

I don't know how about you, but half of those peer dependencies warnings are false-positive coming from a wrong understanding. I tend to these warnings which isn't right, but the whole concept is wrong and kinda leading to it. All I am saying it's not a golden bullet.

**Comment by Mess1ah** [comment]
Here is the example code:
`const mobx = require('mobx');

let todos = mobx.observable([
    { title: "Spoil tea", completed: true },
    { title: "Make coffee", completed: false }
]);

// set some symbol-type keys on an array for some logics
let a = Symbol('a');

// next line will cause an error in mobx5 but won't in mobx4.
todos[a] = 'test';
`

These code will run good in Mobx 4 and get errors in Mobx 5. The error trace is 

`
/yourProjectName/node_modules/mobx/lib/mobx.js:2943
        if (!isNaN(name)) {
             ^

TypeError: Cannot convert a Symbol value to a number
    at isNaN (<anonymous>)
    at Object.set (/yourProjectName/mobx-error-demo/node_modules/mobx/lib/mobx.js:2943:14)
    at Object.<anonymous> (/yourProjectName/index.js:12:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
`

**Comment by FredyC** [comment]
Hmm, could that be a bug? It should probably recognize a Symbol before falling back to thinking it's a number. However, you shouldn't be accessing elements of **array** with Symbol. If anything, it should an object imo. It's really weird to use case.

**Comment by mweststrate** [comment]
Only numeric keys are supported on observable arrays, so this is not a
supported use case in either versions. If you want to associate additional
information with an observable array, use a weakmap instead.

Op ma 15 jul. 2019 15:52 schreef Daniel K. <notifications@github.com>:

**Comment by FredyC** [comment]
@Mess1ah I wonder. Is this whole issue happening because one user of your lib has run into this particular problem? You should have probably started with that instead of trying to figure version detection :D

**Comment by Mess1ah** [comment]
@FredyC This is not the case, I know exactly how to use mobx ~ I add these keys to tag the variable for some extra logics and these logic is not about value observable.

**Comment by FredyC** [comment]
Yea I suppose it would make sense, in that case, to add a condition when Symbol is used, then just set it on that object. Can you please open a new issue with details and reproduction on this particular case? It's getting fairly convoluted in here.

**Comment by Mess1ah** [comment]
Okay,I have opened a new issues about it [2044](https://github.com/mobxjs/mobx/issues/2044). Thanks for your time~
