### ISSUE TITLE
[Request] asStructure - Better Docs

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#204]
Hello.

I was reading the docs again and again but can't really understand how `asStructure` works.

Can someone write a detailed explanation with a better real world example?

**Comment by mweststrate** [comment]
I updated http://mobxjs.github.io/mobx/refguide/modifiers.html, I hope this clarifies the case! 

In practice, you rarely need it because usually computations yield changed values if upstream values are changed anyways. But it is a possible optimization.

**Comment by hnordt** [comment]
Thank you @mweststrate

**Comment by mweststrate** [comment]
By the way, when using decorators you can use: `@computed({ asStructure: true }) get property() { .. } `, I'll add that as well

**Comment by mattruby** [comment]
Thanks for the ES5 examples!

On Thu, Apr 21, 2016 at 12:36 PM, Michel Weststrate <
notifications@github.com> wrote:

> By the way, when using decorators you can use: @computed({ asStructure:
> true }) get property() { .. }, I'll add that as well
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mobxjs/mobx/issues/204#issuecomment-213030733>
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by smirnovshina** [comment]
@mweststrate it seems there is a mistake in the example:
```js
                this.screenSize.width = window.clientWidth;
                this.screenSize.height = window.clientHeight;
```
As far as I know `window` object does not have those methods, elements have. Maybe `window.innerWidth` or `window.documentElement.clientWidth`?

By the way I also didn't understand what for the `asStructure ` is needed.
