### ISSUE TITLE
Child component not rerendered when array prop changes

### ISSUE THREAD

**Issue by davidgolden** [mobxjs/mobx#2040]
I have a:

 * [x] Issue:
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

Minimal sample reproduction: https://codesandbox.io/s/thirsty-kalam-9q331

Tested in mobx 4 and 5, mobx-react 5 and 6.

When an array (non-observed) is passed as a prop to either a functional component or a class component that has an `observer` decorator or HOC, the child component is not re-rendered when the array prop is changed.

This obviously is not the behavior of React, and I'm guessing it's not the expected behavior of Mobx.

**Comment by FredyC** [comment]
This is the expected behavior. The items of array change, but not the array itself. And as such if MobX sees array reference, it won't see changes to it. You would need to access array items for MobX to worry about it. Among the popular approaches there is `Array.from(this.state.numbers)` or `[...this.state.numbers]`.

**Comment by davidgolden** [comment]
@FredyC Interesting.. perhaps it would be worthwhile to add this to the documentation?

**Comment by FredyC** [comment]
Feel free to submit a PR :) I am almost sure it's mentioned somewhere, but cannot seem to find it, so it's probably not visible enough. Problem is, it's the fairly specific case which you wouldn't realize even if you would read in the docs. It's only after you are working with MobX for a while to realize how it works and what makes sense.

**Comment by davidgolden** [comment]
Okay, I'll hunt around a bit and if I don't find anything plan to submit a PR for this at some point.
