### ISSUE TITLE
Garbage  collection of observed object

### ISSUE THREAD

**Issue by ivandotv** [mobxjs/mobx#2047]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

**Please be sure to close your issues promptly.**
Looking at the code for [intercept and observe](https://mobx.js.org/refguide/observe.html)

```js
const disposer = observe(person, (change) => {
    console.log(change.type, change.name, "from", change.oldValue, "to", change.object[change.name]);
});
```
What happens when I delete the person object (try to completely remove it from the system)
Is it available to be garbage collected or mobx is still holding on to the reference and I need to run the `disposer` function?

**Comment by mweststrate** [comment]
You *should* call disposer. It _could_ be garbage collected, if disposer, and the callback themselves are not reachable anymore, but just be a good citizen, don't take any chances and clean up after yourselves.
