### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by MoonCheung** [mobxjs/mobx#2053]
My project built the application based on `react-app-rewired`, then installed `mobx` again, `mobx-react` dependency package import, error reporting：`Support for the experimental syntax 'decorators-legacy' isn't currently enabled`，When you see an error, install again `@Babel/plugin-proposal-decorators`, `@Babel/plugin-proposal-class-properties`, `@Babel/preset-env`, `Babel-plugin-transform-decorators-legacy` still exists an error after import
```javascript
import CounterView from './CounterView';
  5 |
> 6 | @observer // this decorator is must
    | ^
  7 | class MobxCounter extends React.Component {
  8 |   // 观察者
  9 |   @observable count = 0;
```

.babelrc file:
```javascript
 "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    ["react-app", {
      "absoluteRuntime": false
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    "transform-decorators-legacy"
  ]
```

How to solve this problem, please help me, ok?

**Comment by FredyC** [comment]
Sorry, but this isn't MobX related question, more likely ask in react-app-rewired repo.
