### ISSUE TITLE
mobx@4.x , component not update

### ISSUE THREAD

**Issue by rannuo** [mobxjs/mobx#2056]
Welcome to MobX. Please provide as much relevant information as possible!

I have a: mobx@4.x

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [x] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [stackblitz](https://stackblitz.com/edit/react-px75ml)**
  * [ ] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
click add button, but component not update
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
![image](https://user-images.githubusercontent.com/21377874/61772326-8e3e1600-ae24-11e9-9cd1-6db240d3469c.png)

**Comment by FredyC** [comment]
With MobX4 the object is not observable on new properties. You have to either use the observable.map or have a known keys beforehand.

**Comment by rannuo** [comment]
@FredyC Thank you!
