### ISSUE TITLE
Patterns for @computed, ES6 classes and (de)serialization

### ISSUE THREAD

**Issue by jbrantly** [mobxjs/mobx#206]
This is a question but is long/involved enough that it didn't seem suitable for gitter.

One of the hyped advantages of MobX is that you can use ES6 classes for your models. While I don't particularly care about classes vs objects in general, in the MobX world using classes allows you to easily use the @computed decorator to achieve some nifty code. Let's say that I have a collection of line segments each with a start and end point.

```javascript
class Point {
  @observable x;
  @observable y;
}

class Line {
  @observable p1;
  @observable p2;
  @computed get length() {
    let x = p1.x - p2.x, y = p1.y - p2.y
    return Math.sqrt(x*x+y*y)
  }
}

class Drawing {
  @observable lines = [];
}
```

So far so good. The problem comes in when you start talking about serialization, in particular deserialization. Let's say that I can make an API call to fetch a drawing that returns the following JSON.

```javascript
{
  lines: [{
    p1: { x: 0, y: 1 },
    p2: { x: 1, y: 1 }
  }]
}
```

I now need to somehow hydrate ES6 classes with that JSON. I think the standard solution is to do something like:

```javascript
class Drawing {
  constructor(initialState) {
    if (initialState) {
      this.lines = initialState.lines.map(line => new Line(line))
    }
  }

  @observable lines = [];
}
```

However, for complex models that can get really old really fast. I realize that hydration of ES6 classes from JSON is not a problem specific to MobX, but I'm wondering if there is some pattern that I'm missing that would simplify this concept. **Essentially something that allows both simple hydration of data but also simple use of computed values.**

One thought I had was to set up computed functions inside components instead of models. For example...

```javascript
...
componentWillMount() {
  // this could be extracted into a factory function that sits elsewhere
  this.computedLength = computed(() =>
    let line = this.props.line, p1 = line.p1, p2 = line.p2,
        x = p1.x - p2.x, y = p1.y - p2.y
    return Math.sqrt(x*x+y*y)
  )
}
render() {
  return <div>{this.computedLength.get()}</div>
}
...
```

This seems like a common enough pattern (using ES6 classes but also needing to retrieve nested complex data from the server) that some official guidance would probably be good. Any thoughts would be appreciated.

**Comment by mweststrate** [comment]
Hi @jbrantly,

You are right, it is a kind of generic problem, but also quite opinionated. So on one side my hands are itching to provide something standardized for this, but on the other hand I think it should not be part of MobX. At least not of the core package. It is basically client side ORM.

I think it is not too hard to write a standardized solution, as it is basically about (de)serializing references and objects using the right constructors. But I think libraries like bookshelf.js, persistencejs or [mobx-model](https://github.com/ikido/mobx-model) might be a fine fit in themselves already to do such things.

Note by the way that you shouldn't need to bother about `computed`, they are non-enumerable so they won't (shouldn't) serialize. They don't need to be de-serialized as they will be re-created by your `Line` constructor.

**Comment by mweststrate** [comment]
Closed for inactivity, feel free to re-open if needed.
