### ISSUE TITLE
[Question] How to observe only some properties of a store ?

### ISSUE THREAD

**Issue by CYB3RL1F3** [mobxjs/mobx#2060]
Hello,

I have a store with 8 observable properties, and I'd like to inject it but in one component I'd like to observe only 4 of them to avoid pointless re-rendering.

A clue how to do it ?

I don't find anything clear in the documentation :/ 

Thanks a lot.

**Comment by FredyC** [comment]
I assume React? The `mobx-react` repo would be better place next time...

And why are you changing those observables if it's pointless? :)

Either way, you can use `Observer` component or `useObserver` hook if you can. The `observer` HOC will always watch over a whole render and it's not possible to prevent that.

https://mobx-react.js.org/observer-component

**Comment by CYB3RL1F3** [comment]
It's pointless in the component where I want to filter the observable properties but not in the whole app. In other components it's useful of course ;) 

yes I'm talking about react, all my apologizes.
I'll try with useObserver, thanks.

**Comment by jeremy-coleman** [comment]
It shouldnt rerender anyway , its not like redux where the entire state is a new object after updates. The proxy ref doesnt change, just the properties inside, which is why you must wrap with an observer hoc, to trigger updates on any observable values

**Comment by CYB3RL1F3** [comment]
haa! You mean I have to declare an @observer on each child component ?
Indeed, that make sense, it might fix the performance issue I tried to solve. Didn't thought about this.
Thanks.

**Comment by FredyC** [comment]
Wait, what? You wanted to prevent render for some observables. Adding more observer won't do that :) Unless, you want to split components to smaller ones and use observer only there. Then it makes sense.

**Comment by CYB3RL1F3** [comment]
Alright, it's noted. Maybe I'll remove the @observer hook and use the <Observer> as child. Seems a good idea. Sorry for the stupid questions, that's the first time I've been using mobx on a react project, really happy of this, I was just facing this limitation ^^
