### ISSUE TITLE
Rootstore setup with React Context

### ISSUE THREAD

**Issue by pmonty** [mobxjs/mobx#2063]
```
App = () => {
    AppContext = React.createContext(new RootStore(props))
    const root = React.useContext(AppContext)
    // ....
    return (
        <AppContext.Provider value={root}>
            <Component />
        </AppContext.Provider>
     )
}
```

This is my context setup and RootStore
```
export class RootStore {
    public api: ApiClient
    public checkAddressStore: CheckAddressStore
    public appStore: AppStore

    public constructor(config: any) {
        this.api = new ApiClient(config)
        this.appStore = new AppStore(this)
        this.checkAddressStore = new CheckAddressStore(this)
    }
}
```

It works fine until I worked out when I call something like `this.rootStore.appStore.someAction()` in checkAddressStore for example. It isn't updating the appStore in the context its like a new instance. I can't do useContext() in the store for obvious reasons either. 

I feel I might be against a brick wall now and really have no way around it other than MST (which I don't have the time to do it yet so decided to migrate slowly and use context first).

Am I missing something?

**Comment by FredyC** [comment]
It's hard to guess from these snippets, reproduction would be great. I assume you have read through these? https://mobx-react.js.org/recipes-context

**Comment by pmonty** [comment]
Yep read https://mobx-react.js.org/recipes-context#complex-stores which does suggest MST. But it does also say 

> You can have a single Root store and attach every other store onto it. Or have a multiple contexts, each for own segment of the app.

So I thought instead of going the MST route I would first use context and start converting some stuff to mobx-react-lite observer functional components. So I think the main issue now though is `AppContext = React.createContext(new RootStore(props))` So basically it is creating a new context and passing it to the tree every rerender. Because I need to pass the props to the Rootstore to setup some stuff. Might need to try figuring out a slightly way to set up the context.

**Comment by FredyC** [comment]
Well, if the `App` is not re-rendered, it shouldn't matter, but yea, generally `createContext` should be called globally.

**Comment by pmonty** [comment]
Yeh that is definitely the issue hmmm done a workaround for now

```
export let AppContext = React.createContext<RootStore>(null)
let root: RootStore = null

export const App: React.FunctionComponent<IAppProps> = observer(
  props => {
    if (root === null) {
      AppContext = React.createContext(new RootStore(props))
    }
    root = React.useContext(AppContext)
```

Thanks for the rubber ducking.

**Comment by FredyC** [comment]
Ughhh, what have you done, friend? That's so crazy :) Do you know about [the Provider](https://reactjs.org/docs/context.html#contextprovider)? That's the major way of changing context value. You should be creating a new context because you need a different value :)
