### ISSUE TITLE
[preact][mobx 5.13] TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by zoraneus** [mobxjs/mobx#2064]
Hi,
I've this error and I don't know how to solve it:
`Uncaught TypeError: Cannot read property 'get' of undefined          mobx.module.js.618`

`var computedDecorator = createPropDecorator(false, function (instance, propertyName, descriptor, decoratorTarget, decoratorArgs) {
   HERE -> var get = descriptor.get, set = descriptor.set; // initialValue is the descriptor for get / set props
    // Optimization: faster on decorator target or instance? Assuming target
    // Optimization: find out if declaring on instance isn't just faster. (also makes the property descriptor simpler). But, more memory usage..
    // Forcing instance now, fixes hot reloadig issues on React Native:
    var options = decoratorArgs[0] || {};
    asObservableObject(instance).addComputedProp(instance, propertyName, __assign({ get: get,
        set: set, context: instance }, options));
});`

I'm using preact with mobx/mobx-preact: my package.json: 
`{
  "name": "React-in-WP",
  "version": "1.0.0",
  "license": "MIT",
  "main": "src/index.js",
  "scripts": {
    "dev": "cross-env BABEL_ENV=default webpack --watch",
    "build": "cross-env BABEL_ENV=default NODE_ENV=production webpack -p"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@wordpress/babel-preset-default": "^1.2.0",
    "autoprefixer": "^9.6.1",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "classnames": "^2.2.6",
    "cross-env": "^5.1.5",
    "css-loader": "^3.1.0",
    "eslint": "^4.19.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "mobx": "^5.13.0",
    "mobx-preact": "^3.0.0",
    "node-sass": "^4.9.0",
    "postcss-loader": "^2.1.5",
    "preact-places-autocomplete": "0.0.3",
    "preact-router": "^2.6.1",
    "raw-loader": "^0.5.1",
    "react": "^16.8.6",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.19.1",
    "webpack": "^3.0.0",
    "webpack-cli": "^3.3.6"
  },
  "dependencies": {
    "preact": "^8.4.2",
    "run-script": "^0.1.1"
  }
}
`

and my babel.rc:
`{
	"plugins": [
		["transform-react-jsx", { "pragma": "h" }],
		"transform-class-properties"
	]
}`
thanks

EDIT: sorry for the indent, I don't know why github does not display my indentation.

**Comment by FredyC** [comment]
Can you please provide a reproduction, eg. with CodeSandbox? It's unclear to what that error refers to.

**Comment by zoraneus** [comment]
> Can you please provide a reproduction, eg. with CodeSandbox? It's unclear to what that error refers to.

Ok I'm working for it, just a little time (beause I'm using wp-react-plugin in wordpress, I need to isolate preact components before send it to code sandbox)

**Comment by zoraneus** [comment]
the bug does not occur in codesandbox. But locally yes, try to clone my repo and see console:
codesandbox: [https://codesandbox.io/s/react-in-wp-2crmq](url)
github: [https://github.com/zoraneus/preact-mobx-reproduction-err](url)

**Comment by FredyC** [comment]
Ok well, I think it would be better if you redirect your issue to https://github.com/mobxjs/mobx-preact repo as this is general MobX. So unless proven otherwise, I assume it's a problem in that library. Will reopen in that case.
