### ISSUE TITLE
cannot read property value after modify it with inject

### ISSUE THREAD

**Issue by guidetheorient** [mobxjs/mobx#2065]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

2. [x] Issue:
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  [demo here, https://codesandbox.io/s/modest-newton-8w2e4](https://codesandbox.io/s/modest-newton-8w2e4)
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
     I can read property immediately after it changes
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
    mobx 5.11.0
    mobx-react 6.1.1
    browser: chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by FredyC** [comment]
Some description please considering the sandbox does not yield any errors.

**Comment by urugator** [comment]
See comments:
```javascript
@action setInfo() {
  // Next line replaces "userInfo" on "user" like: "user.userInfo = { a: "v" }"
  // a component update is scheduled
  // but it will NOT replace the "userInfo" on "this.props" like: "this.props.userInfo = { a: "v" }"
  this.props.setUserInfo({ a: "v" }); 
  // Component isn't updated yet at this point
  // "this.props.userInfo" holds a reference to old "userInfo" object  
  console.log(JSON.stringify(this.props.userInfo), 2); // 
  
  setTimeout(() => {
    // At this point the component already recieved new props with updated "userInfo" object
    console.log(JSON.stringify(this.props.userInfo), 3);
  });
}
```
It's similar to:
```javascript
this.setState({ a: "v" })
console.log(this.state); // Not updated yet!
```
Clear? Just inject the whole `user` object and use it for both - reads and writes.

**Comment by guidetheorient** [comment]
thanks for your help, i'll follow your suggestion and inject the whole user object. sorry for the late reply.
