### ISSUE TITLE
Mobx not working ios release build

### ISSUE THREAD

**Issue by mukherjeeraja7** [mobxjs/mobx#2066]
I have built a react native application which is working fine in debug build on android and ios. In **ios release build**, the application is crashing. Steps are below-
   1. I am firing a rest API request from component to mobx store to fetch data. My react 
      component is an observer.
   snippet :- 
   **@inject('attendeeStore')
   @observer
   class Attendees extends Component {
     componentDidMount() {
        this.props.attendeeStore.fetchAttendee();
    }**

  2.  Mobx store is trying to fetch the data from the rest API service layer. Once the rest service layer function resolves the promise, the application is crashing when I am trying to modify observable inside the mobx runInAction(). 
       Snippet:- 
 class AttendeeStore {
    @observable attendees = [];
    @observable isLoading = false;

    constructor(rootStore) {
        this.rootStore = rootStore
    }
    @action
    fetchAttendee() {
        this.attendees = [];
        this.isLoading = true;

        fetchAttendees(this.rootStore.authenticationStore.userDetails.UserEmail,
            this.rootStore.authenticationStore.userDetails.SessionAuthToken).then(
                res => {
                    // code crashing here
                    runInAction(() => {
                        this.attendees = res.data.Attendees;
                        this.isLoading = false;
                    })
                },
                error => {
                    runInAction(() => {
                        this.isLoading = false;
                    })
                }
            )
    }

 3. below is my babel.config.js :- 
     module.exports = {
            'presets': ['module:metro-react-native-babel-preset'],
             'sourceMaps': true,
              'plugins': [
              '@babel/transform-flow-strip-types',
              ["@babel/plugin-proposal-decorators", { "legacy": true }],
              ["@babel/plugin-proposal-class-properties", { "loose": true }],
              '@babel/transform-runtime'
                ],
         };

4.  I am using react-native 0.59.8, mobx 4.13.0 and mobx-react 5.4.4

**Comment by FredyC** [comment]
What is your iOS version? We do support only iOS >= 10

**Comment by mukherjeeraja7** [comment]
@FredyC  ios version is 12.3 and devices are iphone 6 plus and iphone 7

**Comment by FredyC** [comment]
Well then, can you at least show some call stack or error message?

**Comment by mweststrate** [comment]
Please don't ping individual users for general issues 😊

Op za 3 aug. 2019 09:57 schreef Daniel K. <notifications@github.com>:

**Comment by mukherjeeraja7** [comment]
@FredyC  as it is an ios release build, i am not getting any log.  It is showing only the process is getting stopped.

**Comment by FredyC** [comment]
Sorry, but that's rather vague to help you with that. You have to dig deeper on your own. I know from practice that debugging RN prod apps is a real pain.

**Comment by mukherjeeraja7** [comment]
Ok. I am closing this issue. Thanku for ur feedback
