### ISSUE TITLE
Reserved keys `global`, `self` in appx of alipay

### ISSUE THREAD

**Issue by doxiaodong** [mobxjs/mobx#2070]
When I run mobx in appx of alipay，it's thow error caused by `self` in https://github.com/mobxjs/mobx/blob/f944b5413f2f4b9de89e00e7de1ddde2a178e19d/src/utils/iterable.ts#L6
and `global` in https://github.com/mobxjs/mobx/blob/6f095ed0330d5ee2433fc87359ebd44ded630e26/src/core/globalstate.ts#L183 

in Alipay appx, the `global` , `self`  cannot be used and defined.
![image](https://user-images.githubusercontent.com/6927481/62717132-ec2e4880-ba35-11e9-9c85-39bb660357af.png)

It can be fixed simply by
```
function _self() {
  return this;
}
```
and
```
const mockGlobal = {};
function getGlobal() {
  if (ypeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  return mockGlobal;
}
```

finally, it's better to update both v4 and v5

**Comment by FredyC** [comment]
That's some really awkward platform having a problem with something like that :) I suppose it cannot hurt anything, so if you are willing to provide PR for both versions, it will likely be merged.
