### ISSUE TITLE
Observing seems to be lost after overwriting nested values

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2077]
1. [x] Question: 

Simple sandbox: https://codesandbox.io/s/mobx-playground-z64tf

I am definitely missing something fundamental here. Is there some way how to safely merge those values in there without disturbing configured observation? Or do I have to tackle that on my own and set those values one by one?

```js
const state = mobx.observable({
  values: {
    prices: {
      value: 0
    }
  }
})

mobx.observe(state.values.prices, 'value', change => {
  console.log(change)
})

const mergeValues = mobx.action(values => {
  Object.assign(state.values, values)
})

setTimeout(() => {
  // simulates loading data to form
  // commenting out "fixes" the observe
  mergeValues({ prices: { value: 10 } })
}, 100)

setTimeout(() => {
  // represents user changing value later
  state.values.prices.value = 20
}, 200)
```
---

To give some mind-frame here. I want to observe specific values in a nested object because each of them can have some validators attached. I don't want to be executing all validators on each small change. It works nicely until I have to merge those new values there.

---

### Update

So it seems that `mobx.reaction` still works after merging those values in, but only in Sandbox. Doing exactly the same in my app tests and nothing happens. More investigation tomorrow, but some hints would be appreciated.

**Comment by FredyC** [comment]
Ok, I have found the culprit. In the actual app, I need to lookup paths in that object dynamically based on a string, so I have a little function...

```js
function getIn(obj: any, path: string[], def) {
  let p = 0
  while (obj && p < path.length) {
    obj = obj[path[p++]]
  }
  return obj === undefined ? def : obj
}
```

Unfortunately, if I set up a reaction like this...

```js
const parent = getIn(state.values, ['prices'])
mobx.reaction(
  () => parent['value'],
  () => {
    // doesn't trigger after Object.assign
  }
)
```

I have to do `mobx.reaction(() => getIn(state.values, ['prices'])['value'])`. That's not very nice to have to be running that `getIn` loop all the time.

I would be expecting that `Object.assign` doesn't replace the whole internal structure, but only values. I've also tried `mobx.set`, but that's the same result.

So the same question is pending. Is there some better way how to overwrite nested values?

**Comment by mayorovp** [comment]
You can try to build chained computed value:

```javascript
function buildSelector(obj, path, def) {
  const c = path.reduce(
    (parent, prop) => mobx.computed(() => {
      const obj = parent.get();
      return obj && obj[prop]);
    }),
    { get() { return obj } }
  );

  return () => {
    const obj = c.get();
    return obj === undefined ? def : obj
  };
}

mobx.reaction(
  buildSelector(state, ['values', 'prices', 'value']),
  () => {
    // ...
  }
);
```

Or you can try to use runtime code generation:

```javascript
function buildSelector(obj, path, def) {
  const expr = path.map(prop => `obj = obj && obj[prop];`).join('\n');

  return new Function('obj', 'def', expr + '\nreturn obj === undefined ? def : obj').bind(obj, def);
}

mobx.reaction(
  buildSelector(state, ['values', 'prices', 'value']),
  () => {
    // ...
  }
);
```

**Comment by FredyC** [comment]
Oh my, it does work in code sandbox but once again not in the app code.

Even with my solution from the previous comment, all works in tests, but running it in the app the reaction is silent again.

I am already thinking about flattening the whole thing into `Map` and using some sort of dot notation for keys. Not only that would mean a single reaction, but all these shenanigans won't be necessary.

**Comment by mayorovp** [comment]
> I am already thinking about flattening the whole thing into Map and using some sort of dot notation for keys. 

That still will not work if you rewrite entire map instead of modifying the keys.

**Comment by FredyC** [comment]
> That still will not work if you rewrite entire map instead of modifying the keys.

Well, since I would flatten, I would have to crawl through the whole object and set it one by one. But that's basically what `deepmerge` module does and no luck with that either.

It's sick. It works nicely in sandbox and in tests, but I am unable to figure out why app behaves differently. I even tried `mobx-logger` if it helps anything, but nothing except creating those reactions gives a clue why would they stop reacting. No dispose is happening there, just silence. I love MobX, but this a first time when it gives me a real headache.

**Comment by mayorovp** [comment]
> Well, since I would flatten, I would have to crawl through the whole object and set it one by one. 

Why you cannot do it without flatten?

**Comment by FredyC** [comment]
Because it annoys me that I don't know what's wrong :) Somehow it feels if those data would be in flat Map, it would be more transparent.

**Comment by mayorovp** [comment]
The wrong thing is replacement of the root observable object instead of update.

**Comment by FredyC** [comment]
Alright, turns out would really just silly me and there was dispose happening 😅 Its shame that `mobx.spy` doesn't provide a clue about the reaction being disposed, that would have helped a long time ago. Or maybe it does but `mobx-logger` doesn't care? 🤷‍♂ 

Anyway, thanks for the `buildSelector`, I think I will stick with that as it's slightly nicer.

---

I wonder though why `deepmerge` works like in this sandbox

https://codesandbox.io/s/mobx-playground-r22tw

I mean it sees the initial value and then the latest one from a direct update, but the one from the merge is omitted for some reason

**Comment by FredyC** [comment]
> I wonder though why `deepmerge` doesn't work properly.

Oh I know, because it does not mutate source object 😆

Anyway, I have settled with my `getIn` approach after all and using `lodash.merge` which mutates the object so it basically behaves like I would be updating one by one. I can then reliably keep parent observable node in a closure and reuse it because it is stable.

Thanks for the help, now I am understanding a bit more about MobX :)
