### ISSUE TITLE
The mobx can't be passed from iframe?

### ISSUE THREAD

**Issue by luther-nwpu** [mobxjs/mobx#2085]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

[1] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
The mobx can't be passed from iframe? In the Iframe, I take the iframe store to window store。But when you change window store, the iframe store doesn't change.Can you give me a solution? Not window store to iframe Store。

**Comment by FredyC** [comment]
> Welcome to MobX. Please provide as much relevant information as possible!

If you want help, you have to make some effort to do exactly that. We don't have any sort of spyware to see inside your code... 😉

**Comment by luther-nwpu** [comment]
For Example:
window.top have one topStore, Iframe have one iframeStore

In window:
    iframeWindow.loadStore(topStore)
In iFrame:
    We initial one iframeStore.
    window.loadStore = (store) => {
        Object.assign(store, this.iframeStore)
    }


So I hope in window, I operate the topStore to change the iframeStore

**Comment by urugator** [comment]
Related #973, #1644

**Comment by luther-nwpu** [comment]
1

**Comment by luther-nwpu** [comment]
Related #973,  had you merged this Pr,?

**Comment by urugator** [comment]
There wasn't any PR, check the comments...

**Comment by luther-nwpu** [comment]
I know you do it in the one total window。But some state will need it.Because I ask one question to solve the iframe document question, that is that the iframe document is not window's document。
