### ISSUE TITLE
Introduce `firstrun` param for autorun functions

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#209]
See #207 

```
var myData = observable({ some data })

autorun((firstrun) => {
  // start observing..
  var data = serializeStuff(myData)
  // .. but don't apply effects on the first run
  if (!firstrun)
    sendDataToServer(data)
})
```

**Comment by fisch0920** [comment]
wouldn't this be trivial to implement without an extra param to the autorun function?

```
firstrun = true
autorun(() => {
  if (firstrun) {
    // ...
    firstrun = false
  }
  // ...
})

**Comment by mweststrate** [comment]
Yep :)

**Comment by fisch0920** [comment]
Then I would forego this addition.  Keep the official API as simple & small as possible.

**Comment by timeyr** [comment]
A related question: I would like to have an autorun that runs exactly once and then disposes itself. I understand that using the `firstrun` variable as suggested above would be enough to skip any computations after the first one, but wouldn't it make sense to also dispose the autorun in order to save resources?

**Comment by timeyr** [comment]
A related question: can an autorun dispose itself? Like:

```
const dispose = autorun(() => {
  if (relevantEvent) {
    doSomething();
    dispose();
  }
});

**Comment by mweststrate** [comment]
see `when`

Op za 21 mei 2016 10:50 schreef Tim Meyer <notifications@github.com>:

**Comment by mweststrate** [comment]
@timeyr the idiomatic way to do that is `const dispose = when(() => relevantEvent, () => doSomething)`. 

After running `doSomething` when will be automatically disposed. The returned `dispose` method is only need to _cancel_ the thing entirely.

**Comment by timeyr** [comment]
Ah, I should RTFM, thanks for the hint!

**Comment by mweststrate** [comment]
Closing this for now. The feature still makes sense, but `reaction` does this already by default so maybe `reaction` is favorable for these patterns. Let's await how people use that in practice :)
