### ISSUE TITLE
How to handle heavy action operation in react

### ISSUE THREAD

**Issue by anikethsaha** [mobxjs/mobx#2092]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [X] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [] Are you willing to (attempt) a PR yourself?

# Issue

I have a store with simple object observer
```
import { action, computed, observable } from "mobx";

class TaskStore {
    @observable public task = {};

    @action public addNewTaskJson(storageJson: Object[]) {
        return new Promise(resv => {
      this.task = storageJson;
      resv(this.task);
    });
    }

}

const store = new TaskStore();
export default store;
```

AND THE COMPONENT I am having simple like this

```
@inject("TaskStore")
@observer
export default class TaskContainer extends React.Component<ITaskContainerProps, ITaskContainerState> {
    constructor(props: ITaskContainerProps) {
        super(props);
    }
    public componentDidMount() {
        console.log("TaskStore.task", this.props.TaskStore.task);
    }
....
....
...
```
In root component (app.tsx), I am mutating the store like this 
```
this.props.TaskBookStorageStore.addNewTaskBookStorageJson(storageJson).then(taskbookstore =>
				console.log("taskbookstore", taskbookstore)
);

```
**Output I am getting**
For log calls, I am getting like [**this**](https://files.gitter.im/mobxjs/mobx/YQ2X/image.png)
 
or 
![image](https://user-images.githubusercontent.com/26347874/64126371-153ec080-cdcb-11e9-8471-d66d67368fb0.png)

*Here in the above pic, the red color area is my actual data object I am adding but a lot of it. like 30-40*

**Demo**
A similar kind of store is [**here**](https://codesandbox.io/s/g4uu8), but here the data adding is small so it's working fine, but in my project, I have to add JSON object of more than 40-50 entries, and Its giving me the proxy handlers. I am pretty sure I am somewhere messed up with the async thing. 

I have also done it without `promise` but still the same behavior, 

also done like this , but still same 
```
    @action public async  addNewTaskJson(storageJson: Object[]) {
      this.task = await storageJson;
    });

```

**Dep**
```
  "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/polyfill": "^7.4.3",
    "@babel/runtime": "^7.4.4",
    "body-parser": "^1.19.0",
    "mobx": "^5.11.0",
    "mobx-react": "^6.1.1",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-router-dom": "^5.0.0",

```

`.babelrc`

```
{
  "plugins": [
    "@babel/plugin-transform-regenerator",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-syntax-dynamic-import",
    [ "import", { "libraryName": "antd" }]
  ],
  "presets": ["@babel/preset-react", "@babel/preset-env"]
}

```

**Comment by urugator** [comment]
Not sure what the problem is...
Are you confused by these proxies?
They are supposed to be there. And they are present even in the demo you posted - check the chrome console (not the codesandbox output)

**Comment by anikethsaha** [comment]
Yeah I am confused how to handle them! 
Like i know I am lagging somewhere to handle async operation. Need a guide with it. 
The codesandbox output is not resulting in proxy cause it's doing assignment with small data. But the chrome output is doing same operation with huge number of data. 
How can I use this state even with proxies.

**Comment by FredyC** [comment]
@anikethsaha The CodeSandbox does have proxies too, have a look in a real chrome devtools, not their console.

![image](https://user-images.githubusercontent.com/1096340/64147949-49919b80-ce22-11e9-982f-68a3c01d660e.png)

You don't need to worry about proxies at all. It's an internal thing. You are just reading and writing to the properties you want. If you need to convert to a plain object, use `toJS` exported from `mobx`, but be aware it won't be observable anymore. It's for purposes of serialization and similar.
