### ISSUE TITLE
Improvement of contribution flow.

### ISSUE THREAD

**Issue by damianprzygodzki** [mobxjs/mobx#2098]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

3. [x] Idea:
  * [ ] What problem would it solve for you?
I wanted to improve docs because deprecation of passing stores directly should be featured in documentation. You are asking in issue template to instead of that, create a PR. Ok! Great. But where i can find docs? Found some PR about docs, to another branch. Wait what? Docs are other branch with totally different files structure? I wouldn't expect that...
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
Of course, anyone who is beginning a journey with Mobx firstly sees egghead clip where is shown deprecated code.
  * [ ] Are you willing to (attempt) a PR yourself?
If there would be straightforward information how to deal with this weird docs location...

**Comment by FredyC** [comment]
@damianprzygodzki Yea, docs contributing is rather cumbersome and done through gh-pages branch and Gitbook as the underlying tool. There were already attempts to improve that (#1859), but it never went through.

So in case, you would be up to the task, feel free for sure :)
