### ISSUE TITLE
mobx community

### ISSUE THREAD

**Issue by fisch0920** [mobxjs/mobx#210]
I really really like mobx and its simplicity compared with Flux alternatives.

That being said, the main problem I see mobx having is a lack of an official company sponsor like FB & Redux.  Without more resources, the project's relatively weak community of devtools and extensions surrounding mobx will continue to inhibit its growth.

@mweststrate have you given any thought to reaching out to other companies or Facebook itself which may be interested in sponsoring mobx?

**Comment by hellectronic** [comment]
As a start we could collect related projects (mobx-reactor etc.), examples (from #104 ) etc. for the main README ?

**Comment by mweststrate** [comment]
@fisch0920 Good questions. I don't think MobX is big enough yet to awake the interest of the Facebook. Note by the way that my employer (Mendix is a medium sized, well settled software company) has a few core projects running on MobX, so in that sense continuation is guaranteed.

@hellectronic Good point. Feel free to PR :)

**Comment by philcockfield** [comment]
Is there a Slack Channel, or Gitter group where people are talking with each other about MobX?  What's the best place to go and ask questions?

**Comment by AriaFallah** [comment]
@philcockfield 

1. [gitter](https://gitter.im/mobxjs/mobx)
2. There are a fair amount of MobX questions in the issues section so I think you can go there as well.

**Comment by jlhamilton** [comment]
There is a MobX channel on [Reactiflux](https://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html) where @mweststrate answers questions.

**Comment by philcockfield** [comment]
Cheers - thanks guys.  MobX totally lands conceptually where I want it too.  This just makes so much elegant sense.

**Comment by vinej** [comment]
I'm working for CGI at SNC-Lavalin as a software architect and I started to do some marketing about React/Mobx because I really like it. Last week, I sent a link of my repository to all my co-workers to show them that it's possible to build software more easily with this kind of technology. 

Continue your good works,  it's worth it.

Thanks

**Comment by mweststrate** [comment]
Thanks for sharing!

Op zo 29 mei 2016 om 03:00 schreef Jean-Yves Vinet <notifications@github.com

**Comment by mergebandit** [comment]
Looks like the reactiflux mobx is no longer? Is there another community somewhere for us to hang out?

**Comment by mattruby** [comment]
https://gitter.im/mobxjs/mobx
