### ISSUE TITLE
[Question]Is it possible to "manually reevaluate" a computed value? (e.g. when data is from an arraybuffer)

### ISSUE THREAD

**Issue by whzx5byb** [mobxjs/mobx#2109]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [*] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

```typescript
class Foo {
  private _dataSource = new ArrayBuffer(4);
  private _dataView = new DataView(this._dataSource);

  @computed get bar() {
    return this._dataView.getUint32(0);
  }

  @action setBar(value: number) {
    this._dataView.setUint32(0, value);
    forceToUpdateBar(); // <== should reevaluate foo.bar here.
  }
}

var foo = new Foo();
autorun(() => console.log(foo.bar));
foo.setBar(42);
```

I want to make some data observable which is from an arraybuffer.
Since I can't really "observe" the arraybuffer, I have to manually reevaluate the computed value when it changes.
Is there any way to do it?

**Comment by urugator** [comment]
https://mobx.js.org/refguide/extending.html
Create an `atom` representing the array, call `atom.reportObserved()` inside `get bar()`, call `atom.reportChanged()` inside `setBar()`
