### ISSUE TITLE
Unnecessary change in a observable is being required to pops in a snackbar.

### ISSUE THREAD

**Issue by almeida-samuel** [mobxjs/mobx#2110]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

Hello everyone, how's going? I have a question about a flow that I'm implementing. Code bellow.

Reaction
```
    reaction(
      () => this.state,
      () => {
        if (this.state === 'error') {
          Snackbar.error({ title: this.error })
        }
      },
    );
```
Calling setError
```
    Alert.confirmReportRemoval({
      onConfirm: () => {
        this.setError(i18n.t('myReports.removalError'))
      }
    });
```

setError
```
  baseClass.prototype.setError = function(message) {
    this.error = message;
    this.state = 'error'
  };
```

The flow is:
1. A user tries to remove an item from a list
2. A react-native Alert shows asking for confirmation
3. The user confirms the removal
3. A snackbar pops in showing an error

All seems to be working fine, but however the Snackbar doesn't appear no matter what I do. But when I replace the setError function with...

setError(REPLACED)
```
  baseClass.prototype.setError = function(message) {
    this.state = 'foo' // can be anything: bar, undefined or whatever
    this.error = message;
    this.state = 'error'
  };
```

Everything just works, as the Nvidia CEO says haha.

What I'm doing wrong here? Can someone please, enlighten the path?

**Comment by FredyC** [comment]
Probably best if you can reproduce the issue in eg. CodeSandbox. These piece of code looks just fine so there is something you are not telling us (not on purpose).

**Comment by almeida-samuel** [comment]
I'm going to create a way to simulate the issue, give me a few hours.

**Comment by almeida-samuel** [comment]
I haven't been able to create a project on CodeSandBox because `react-native-snackbar` isn't working there. However, I discovered that if a wrap the `Snackbar.error({ title: this.error })` call in a `setTimeOut` with a trigger...let's say 100ms, it works. So, the issue is related to `react-native-snackbar`. Thanks a lot for the support @FredyC.

**Comment by FredyC** [comment]
Let's keep it closed here then and let me know if some MobX related issue pops out :)
