### ISSUE TITLE
Allow normalization of results from computed properties

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx#2111]
I have a:

- [x] Idea:
  * [x] What problem would it solve for you?
    Reduced rendering.
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
    Everyone returning arrays or objects from `@computed` may benefit. It's no utility, just an option for `@computed`.
  * [x] Are you willing to (attempt) a PR yourself?
    Not without getting a lot of help.

A simple property like
```
@computed
get firstTwo() : Array<Entity> {
    return this.entities.slice(0, Math.min(this.entities.length, 2))
}
```
gets recomputed every time any entity change and returns a new array, which is quite often equal to the previous value (this example is a big simplification of what happens in a real project). It'd be nice to have something like `@computed(equals=myEquals)`, which would return the old value in case `myEquals` returns a truthy value.

This normalization is something, I can't do myself, as I have no access to the old value. An alternative could be providing some global `mobx.oldComputedValue` accessible during the execution of the getter body.

**Comment by FredyC** [comment]
Well, you don't have immediate access to the previous value, but I believe something like this should work, right?

```js
class {
  firstTwoMemo = []
  get firstTwo() : Array<Entity> {
    const newValue = this.entities.slice(0, Math.min(this.entities.length, 2))
    if (newValue !== this.firstTwoMemo) {
      this.firstTwoMemo = newValue
    }
    return this.firstTwoMemo
  }  
}


```

**Comment by urugator** [comment]
`@computed({ equals: myEquals })`

https://mobx.js.org/refguide/computed-decorator.html

>Options for computed

>equals: By default comparer.default. This acts as a comparison function for comparing the previous value with the next value. If this function considers the previous and next values to be equal, then observers will not be re-evaluated. This is useful when working with structural data, and types from other libraries. For example, a computed moment instance could use (a, b) => a.isSame(b)
