### ISSUE TITLE
How to alias an @observable on another class? @observable.alias a = other.a; ?

### ISSUE THREAD

**Issue by thepian** [mobxjs/mobx#2114]
3. [x] Idea:
  * [x] What problem would it solve for you? It would allow me to transparently share annotated observables
  * [x] Do you think others will benefit from this change as well and it should in core package   
  * [x] Are you willing to (attempt) a PR yourself?
I have an Idea:

I have two State(store) classes with observable members. Both domains use a common set of data `listHeaders`. It seems to me that the best structure would be a third class with a `listHeader`observable, and a way to define observable aliases on my two State classes.

```
class A {
  @observable listHeaders = [];
}
class B {
  @observable.alias listHeaders = a.listHeaders;
  constructor(private a: A) {}
}
class C {
  @observable.alias listHeaders = a.listHeaders;
  constructor(private a: A) {}
}
```

You'd be able to assign listHeaders anywhere and fire a change everywhere since all three listHeaders are actually the same observable.

I haven't seen a way to do this. Perhaps I missed it.

**Comment by urugator** [comment]
```javascript
class C {  
  constructor(private a: A) {}
  get listHeaders() {
    return this.a.listHeaders;
  }
  set listHeaders(listHeaders) {
    return this.a.listHeaders = listHeaders;
  }
}
```
Why not to expose `a` on `B`/`C`?

**Comment by mweststrate** [comment]
closing as answered
