### ISSUE TITLE
computedFn should support IComputedValueOptions

### ISSUE THREAD

**Issue by hearnden** [mobxjs/mobx#2116]
I have a:

3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

---

`computedFn` is great :tada:

And it would be even greater if it supported `comparer.structural` or a custom `equals()` function, for all the reasons.

Example:
```ts
const xs = mobx.observable([1, 2, 3]);
const xsLessThan = computedFn(n => xs.filter(x => x < n));
mobx.autorun(() => console.log(xsLessThan(3)));  // ==> [1, 2].
xs.push(4);                                      // outputs ==> [1, 2] again :(
```

Proposal:
```ts
const xs = mobx.observable([1, 2, 3], { equals: comparer.structural });
const xsLessThan = computedFn(n => xs.filter(x => x < n));
mobx.autorun(() => console.log(xsLessThan(3)));  // ==> [1, 2].
xs.push(4);                                      // no output :)
```

From the source, it looks like computed options can just be passed through from `computedFn` to the dynamically instantiated `.computed()` boxes.

**Comment by mweststrate** [comment]
Published as part of mobx-utils 5.5.0
