### ISSUE TITLE
Singleton store with static property will throw error in some cases

### ISSUE THREAD

**Issue by Tan90Qian** [mobxjs/mobx#2122]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I want create a singleton store with `static` modifier just like:
```javascript
class Store {
  static instance = new Store()
}
```
But when I create `observable` and `computed` property, it throws an error `Typeerror: Store is not a constructor`.
If I assign value for `instance`outside `class`, just like
```javascript
class Store {
  static instance;

  @observable value = 1

  @computed get doubleValue(){
    return this.value * 2;
  }
}

Store.instance = new Store();
```
It will be ok.
What is happening?

Here is online repo demo
https://codesandbox.io/s/recursing-bassi-wktzw

**Comment by Tan90Qian** [comment]
https://codesandbox.io/s/recursing-bassi-wktzw

**Comment by FredyC** [comment]
That's not related to MobX, it's just a limitation of JavaScript.
