### ISSUE TITLE
Question: strongly typed object => observable (hard case)

### ISSUE THREAD

**Issue by yahorsi** [mobxjs/mobx#2123]
Hi Guys!

Imagine the case when we have strongly typed objects generated by some tool, e.g. model types generated from the swagger spec. And, we would like to use these strongly typed classes in our stores. So, what is the right way to turn them in to the observable object?

Thanks!

**Comment by FredyC** [comment]
Um, I guess it depends on what behavior do you expect. Perhaps you want `mobx-state-tree` which is built on top of strong types and you can declare custom types if needed.

**Comment by yahorsi** [comment]
What we need is to just make it observable :) and work as if it is plain object

**Comment by FredyC** [comment]
So why to mention strong typing? Just do what everyone else :) There is plenty of documentation on observables.
