### ISSUE TITLE
Getting started link in document was not found

### ISSUE THREAD

**Issue by Meeeeow** [mobxjs/mobx#2140]
I have a:
2. [x] Issue:

- The second link in [Getting started](https://mobxjs.github.io/mobx/getting-started.html) return a 404 page
- The "Why MobX" link in footer was also broken, return a 404

It looks like the getting-started.html was replaced by "Why MobX" recently, but links in document was not removed?

**Comment by dimitrisnl** [comment]
I would also like to ask if the '10 minute introduction to MobX and React' is somewhere too because it links to `getting-started` as well.

**Comment by FredyC** [comment]
You can still see "old docs" here

https://github.com/mobxjs/mobx/tree/a40e711d6e17b154a9f88122ae0399820705848c

The link is the same, also leads to `getting-started` so I am not sure what exactly are you looking for :)

**Comment by cloverich** [comment]
@FredyC they are talaking about a stand-alone set of pages that looked like this:

<img width="1100" alt="Screen Shot 2019-10-08 at 9 15 40 PM" src="https://user-images.githubusercontent.com/1010084/66446592-d2e35180-ea10-11e9-85af-8b796425d123.png">

It looks like they were a stand-alone page + static assets. You can find them under the old gh-pages branch. I can probably re-add these files to the website, or remove the links if they are no longer desired. Any additional context?

**Comment by mweststrate** [comment]
Yeah it is a stand alone hosted page, which I missed in the migration. It could just be copied over literally into the `static` section I presume (maybe would get a slightly different link). 

I have honestly no idea how good it still is though? It feels a bit dated, would you folks consider it a useful learning resource, or should we just drop it?

**Comment by dimitrisnl** [comment]
I haven't checked the resource before - was looking for the official docs for the react bindings and it's the second google search result for `react mobx`.

If anything, something should be under the `getting-started` or remove the links altogether since it creates some confusion.

**Comment by FredyC** [comment]
For React there is a dedicated docs website: https://mobx-react.js.org

It's probably still too fresh (and I suck at SEO) so it won't be popping in google that well. I could certainly accept help with that.

That side is still fairly limited and mostly focused around React Hooks. I am mostly waiting for more feedback and general interest before spending more time polishing it. Chances are before that happens, class components might not be that relevant, who knows 🤷‍♂

**Comment by Meeeeow** [comment]
@FredyC I don't need the old doc and more ;) Already getting start by “Why Mobx” section. So please fix dead links on page

**Comment by FredyC** [comment]
@Meeeeow PR is welcome for link fixing ;)

**Comment by mweststrate** [comment]
The pages have been restored. Sorry for the late follow up, it was a bit tricky to get it incorporated in docusaurus at first :)
