### ISSUE TITLE
Deduplicate readme

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2145]
@cloverich We shall also figure out to deal with that README, I did not like that I had to do the change (#2144) twice, even though it was a small thing.

If we were about to copy those files, how do we ensure people will edit the right one?

Is it really that problematic with Docusaurus to reference the one from the root folder? Some sort of aliasing?

**Comment by FredyC** [comment]
@mweststrate What do you think? Looking at immer repo, the readme is not part of docs. I guess because it's so small. Should we trim down readme in here as well and have it in docs only?

**Comment by mweststrate** [comment]
Done as part of the v6 docs cleanup by @faassen
