### ISSUE TITLE
Docs not found

### ISSUE THREAD

**Issue by TotallWAR** [mobxjs/mobx#2146]
A lot of links to docs are not found.

Example: https://mobx.js.org/getting-started.html

**Comment by FredyC** [comment]
Where did you get that link? We have migrated to a different platform.

https://mobx.js.org/README.html#getting-started

**Comment by FredyC** [comment]
Ok, in that case duplicate to #2140

**Comment by mweststrate** [comment]
Should be fixed now. Sorry for the inconvenience!
