### ISSUE TITLE
TS2339 property 'observe' does not exist on type...

### ISSUE THREAD

**Issue by khusamov** [mobxjs/mobx#2147]
Issue

Hello!
While programming in TypeScript, I found this problem. Observable properties are not cast to type IObservable* (different properties have their own interfaces, for example, for iobservablearray arrays).

How to solve it?

```typescript
import {IArrayChange, IArraySplice, observable} from 'mobx';

class Project {
	@observable title: string = '';
}

const project1 = new Project;

// TS2339 property 'observe' does not exist on type 'string'
project1.title.observe((changeData: IArrayChange<any> | IArraySplice<any>) => {
	switch (changeData.type) {
		case 'splice':
			// TODO
			break;
		case 'update':
			// TODO
			break;
	}
	return changeData;
});

```

![image](https://user-images.githubusercontent.com/4146998/66582800-034efb00-eb8b-11e9-820a-3c130ac31cb5.png)

**Comment by FredyC** [comment]
Only type-safe variant I am aware of is `mobx.observe(project1, 'title', (changeData...`. I don't think it's possible your way without typecasting. Decorators are a nasty beast on its own.

Or if you are looking for strong types, the mobx-state-tree is a much better imo.

**Comment by urugator** [comment]
> Observable properties are not cast to type IObservable* (different properties have their own interfaces, for example, for iobservablearray arrays)

Primitives (number/string/bool) are left as they are. You can box them like this:   
```javascript
class Project {
  @observable title: IObservableValue = observable.box('');
}
```
However the suggested `mobx.observe(obj, propName, onChange)` is probably what you want to use.
Note that `observe` ignores transactions and overall should be rarely needed.

**Comment by khusamov** [comment]
Thanks!
