### ISSUE TITLE
Add coercer functionality to Observerable map merge

### ISSUE THREAD

**Issue by nrakochy** [mobxjs/mobx#2148]
[x ] Idea:
  * [x ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x ] Are you willing to (attempt) a PR yourself?
  * What problem would it solve for you? Eliminate hand-rolled implementation of same functionality

I am interested in extending the `merge` capabilities of the observable map. When I receive a data payload that has nested reference data objects, it would be helpful to merge those into a target map without first needing to instantiate the reference.

For example, 
***Model***
```
const User = model({
...
department: types.reference
});
```
***Create action***
```
var data = [{id: "Test", example: "Test", department: {id: "DeptId", name: "Example"}}]
users.merge(data) /* Fails on reference error */
```

What I would like to propose is an [additional function argument to merge](https://github.com/mobxjs/mobx/blob/master/src/types/observablemap.ts#L307), where the function could coerce the given object on each iteration - 

***Proposed API***
```
const coercerFn = ({department, ...user}: IteratedObjectFromThePayload) => { 
     const { id } = department;
    this.departments.put(id, department)
    user.department = id;
    return user;
}

const data = [{id: "Test", example: "Test", department: {id: "DeptId", name: "Example"}}]
users.merge(data, coercerFn)  /* Sweet success */
```
This is related to `mobx-state-tree` but I believe the functionality would live here. Open to other ideas as well. Thanks for the great library.

**Comment by FredyC** [comment]
I wonder, why can't you coerce before you call the merge, eg. `users.merge(coercerFn(data))`. I don't follow why that would need to be in MobX really.

**Comment by nrakochy** [comment]
Introducing the coercer function would allow coercion on one pass. That is, `forEach` is called on the collection inside of `merge`, and each record could be processed once. 

If the coercerFn is outside of merge, then it requires processing 2x. 
```
const coerced = data.map(obj => coercerFn(obj))
users.merge(coerced);
```

**Comment by FredyC** [comment]
@nrakochy That's really a premature optimization trying to save on loops. Unless you are writing something really expensive, it won't matter by a long shot.

Besides, there is no need to split into two lines ... `users.merge(data.map(coercenFn))`. Or what @urugator suggested.

Closing. I think this is unnecessary API bloat.

**Comment by nrakochy** [comment]
Iterating over 1000 records 1x versus 2x is not `"premature optimization"`.  Your code example is still iterating over all the records 2x irrespective of line count.

The issue is very clear in `mobx-state-tree`, in that there is no exposed api for merging nested data-objects-as-references into top-level model data. 

This `"bloat"` would expose that api, but, nevertheless, I will hand-roll the API implementation as I have previously.

**Comment by FredyC** [comment]
Believe me, it is premature. Been at your mindset in the past and it's not worth it. Do you have an actual benchmark showing it's a major slowdown? Sorry, but adding something based on "hunch" is not good enough.

**Comment by urugator** [comment]
1. It's a case specific optimization  - few extra lines of code in userland should be acceptable cost. It's not like there isn't a away to do it, correct?
2. `n`, `2n`, `3n`,... asymptotic time complexity is same ... if it's slow on `2n`, it will be very likely slow on `n` (at some point), so you will have to find a different solution anyway

**Comment by nrakochy** [comment]
While iterating 1x versus 2x makes good sense, it is actually a secondary issue. The primary issue is developer expectation. 

I am trying to get mobx(-state-tree) adopted at my company. A surprise for a new-to-mobx-state-tree dev is that there is no mechanism for intuitively updating the store in bulk. 

One would think that with a well-formed payload with nested data,  `users.merge(data)` should just work. It is a convenience method, after all.

`That's another silly idea, how would the store know where to upsert the nested reference instance?` 

This proposal was to give a supported api for bulk updates into a mobx-state-tree store rather than hand-rolling with lower level apis every time. To update in bulk, inform the framework of the data shape via a coercer, and it will just work. 

Admittedly, this was my first attempt to contribute to a library that I have benefited from. Perhaps a new idea was the wrong approach. It has been a great help. Thanks for the work you invested in it. Cheers.
