### ISSUE TITLE
observe external library string

### ISSUE THREAD

**Issue by tomeraz** [mobxjs/mobx#2162]
hi,

I have an external library that has a string.
How can I use mobx to observe that string?
Thanks!

**Comment by FredyC** [comment]
Please read docs ... `observable.box` is probably what you are looking for.

**Comment by tomeraz** [comment]
I've read the docs and tried observable.box but it doesn't change when the external library string changes

**Comment by FredyC** [comment]
MobX cannot magically inform you when some arbitrary string changes. Does the library expose some sort of event emitter or another way to notify about the change? Then you can use `.set()` method on the boxed value.

If there is no way to get notified about the change, you would probably need some sort of timer that would be checking value, but that's fairly nasty :)

**Comment by FredyC** [comment]
Here is the example I am using to wrap around browser online status.

```js
import { observable } from 'mobx'

const isOnline = observable.box(navigator.onLine)

window.addEventListener('offline', () => isOnline.set(false))
window.addEventListener('online', () => isOnline.set(true))

export const isNetworkOnline = () => isOnline.get()
export const isNetworkOffline = () => !isOnline.get()
```

**Comment by tomeraz** [comment]
Managed to get my code working. Thanks for your help.
