### ISSUE TITLE
Question: React HOC for useObservable hook from mobx is not reacting to changes

### ISSUE THREAD

**Issue by tudordumitriu** [mobxjs/mobx#2170]
Hi
I am trying to create a react HOC for useObservable hook from mobx but it is not reacting to changes.

Working code:

```js
const MobXItemsList = () => {
  const store = useContext(MobxDataStore);
  return useObserver(() => (
    <ItemsList
      customers={store.customers}
      initialized={store.initialized}
      length={store.customers.length}
    />
  ));
};
export default MobXItemsList;
```

Version with HOC which is NOT working (not reacting/observing to any changes):

```js
const withObserverMobx = Component => () => {
  const store = useContext(MobxDataStore);
  return useObserver(() => <Component store={store} />);
};

export default withObserverMobx(({ store }) => {
  return (
    <ItemsList
      customers={store.customers}
      initialized={true}
      length={store.customers.length}
    />
  );
});
```

Much appreciated!

**Comment by FredyC** [comment]
Why are you reinventing the wheel when you have a look at our observer HOC and modify the code for your needs? https://github.com/mobxjs/mobx-react-lite/blob/master/src/observer.ts

It's hard to tell what's wrong here without proper reproduction.

**Comment by urugator** [comment]
`return useObserver(() => <Component store={store} />);`
=> 
`return useObserver(() => Component({ store }));`

**Comment by mweststrate** [comment]
`observer` only listens to changes in _THIS_ component. Since, in your HoC, nothing is used in `THIS` component (since it is just a stable store reference), the HoC won't be tracking anything, while the original component was using customers, initialized etc. For that reason @urugator's solution work, as the component is no longer split into two different components. (Although one could consider calling `Component` as a function instead of as component a confusing pattern)

**Comment by urugator** [comment]
> (Although one could consider calling Component as a function instead of as component a confusing pattern)

[It's what this lib does...](https://github.com/mobxjs/mobx-react-lite/blob/a6bc7c225c7bb495840d9b972f84b9273e2b2879/src/observer.ts#L37)
Since he opted for `useObserver`, I presume he doesn't want to support classes ... so memo/ref/name handling aside, he can do just the same thing as we do...

**Comment by mweststrate** [comment]
I know :) I more meant to say it might be confusing to read for readers of
this code. Although these kind of HoCs are typically utilities stuffed
somewhere away, so I guess it's fine as long as the difference between the
two constructions is clear and intentional.

**Comment by tudordumitriu** [comment]
Thank you @urugator 
Actually I was experimenting but I found it kind of limiting not being able to create the HOC that reacts to changes, but thanks to @mweststrate explanation it does make sense and yes, it's a bit confusing calling the component that why it didn't cross my mind, but it gets the job done.

**Comment by urugator** [comment]
Just in case it's not obvious, you can create the same HOC using `observer`:
```javascript
const withObserverMobx = Component => {
  const ObserverComponent = observer(Component);
  return () => {
    const store = useContext(MobxDataStore);
    return <ObserverComponent store={store} />;
  };
}
```
