### ISSUE TITLE
How do I subscribe to @computed object in mobx?

### ISSUE THREAD

**Issue by khusamov** [mobxjs/mobx#2176]
Question

I want to subscribe to a computed property that returns a simple object.

Codesandbox: https://codesandbox.io/s/epic-noether-g8g0x

I made a simple example of my situation to show exactly what the problem is:

```typescript
const zeroSize = {
    width: 0,
    height: 0
};

class Item {
    @observable size = zeroSize;
}

class Collection {
    @observable childrens: Item[] = [];

    @computed get size() {
        return this.childrens.length > 0 && this.childrens[0] ? this.childrens[0].size : zeroSize;
    }

    constructor() {
        reaction(() => this.size, size => {
            // Expected { width: 0, height: 1000 }
            // Actual { width: 0, height: 0 }
            console.log('-----size=', toJS(size));
        });
    }
}

const item1 = new Item;
const collection1 = new Collection;
collection1.childrens.push(item1);
item1.size.height = 1000;
```

**Comment by FredyC** [comment]
Interesting, I don't exactly know the answer, but if you flip those last two lines it works as expected. I am sure someone else can come up with a better one :)

**Comment by khusamov** [comment]
But I do not want to change these lines in places.

**Comment by khusamov** [comment]
Second example: Here I am trying to subscribe to changes to the item property.size And nothing comes out. How do I do that?



```typescript
class Item {
  @computed get size() {
    return {
      width: this.width,
      height: 0
    };
  }
  width = 0;
}

const item = new Item();

observe(item, 'size', change => {
  // Why isn't this handler called?
  console.log("first observe");
});

item.width = 1000;
```

**Comment by khusamov** [comment]
But reaction recommends the use of mobx. What was it made for, then? )))

**Comment by spion** [comment]
You are returning the size of the first item. The size object itself hasn't actually changed, its still the same object (the size of the first item). Its properties however have changed, but you are not reacting to those, only to the object.

Really, autorun prevents these reasoning puzzles quite nicely.

**Comment by khusamov** [comment]
I removed toJS() and my code worked!

**Comment by spion** [comment]
Keep in mind that if you trigger some window resizing based on this reaction you will *still* have a bug, because it will only react to changes which is the first item, not on the item changing its internal size.

To fix the bug you actually need to *add* to toJS() in the first reaction function. That will force dependency on the first item size.

**Comment by urugator** [comment]
> What was it made for, then? ))

Reaction does't run the effect immediately by default.
Reaction runs the effect only if returned value differs from the one returned previously.
Consider:
```javascript 
reaction(
  () => {
    // runs anytime the size or width or height changes 
    return this.size.width * this.size.height;
  },
  area => { 
    // runs only if area differs 
    console.log(area);
  }
);

autorun(() => { 
  // runs anytime the size or width or height changes
  const area = this.size.width * this.size.height;
  console.log(area); 
});
```

**Comment by 1813927768** [comment]
I don't think it's the problem of the `toJS()` function. 
If you add this line `console.log("-----size=", size.height);`
, you will notice the height is still `0` not `1000`, which means this reaction still can't catch the internal change of `size` object.

**Comment by khusamov** [comment]
I realized that I do not understand how to use mobx!

**Comment by FredyC** [comment]
He said and I am closing 😎

**Comment by khusamov** [comment]
Prompted how to solve this problem
https://stackoverflow.com/questions/58536450/how-do-i-subscribe-to-computed-object-in-mobx/58562815#58562815
