### ISSUE TITLE
Accessing from when calling is not in a reactive context?

### ISSUE THREAD

**Issue by bengry** [mobxjs/mobx#2182]
I'm trying to have an action that performs a call to the network, which might've already been called. Therefore, I'm using `fromPromise()` inside a Store, and accessing that on demand - and use `when()` to verify it has been fulfilled/rejected before continuing execution.

This doesn't work for some reason, and I'm getting duplicate network requests, even  though no dependencies of the `@computed` changed between calls.

Seems like MobX isn't caching the result of the `@computed` when accessed from a `when()`, even though it seems like it should.

I have a minimal reproduction here: https://codesandbox.io/s/blue-cloud-b4vtc

Also notice that if you uncomment line 62 (render the data inside an `@observer` component, everything works as expected, and only 1 network request is being sent).

Please advise, I'm not sure why this doesn't work :/.

P.S.
If you change the code to use a `reaction()` instead, it works fine, but is more verbose, and less readable, and feels unnatural - in the sense that calling `doWork()` just queues a callback basically, which I also can't get back in my `onClick()` handler in case I wanted to follow it up with something (unlike the `when()`, where I just get the `Promise` back and can `.then()` it).

**Comment by urugator** [comment]
You've posted link to a wrong sandbox

**Comment by bengry** [comment]
> You've posted link to a wrong sandbox

Oops, fixed in OP.

**Comment by urugator** [comment]
Computed caches only if there is an observer (otherwise it could leak memory, check `keepAlive` option). `when` is immediately disposed when it finishes, so it flushes the cache.
However I think you're making it more complicated than it needs to be...

**Comment by bengry** [comment]
@urugator
> However I think you're making it more complicated than it needs to be...
How so? What's the suggested alternative? Keep in mind that I don't have want to re-fetch the data (it's an expensive call in the real world use case).

**Comment by urugator** [comment]
```javascript
class Store {
  @observable fetching;
  @observable data;
  
  @action
  doWork() {
    if (this.fetching) {
      return;
    }
    this.fetching = true;
    fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then(action(response => {      
      this.data = response.data;
    }))
    .finally(action(() =>{
       this.fetching = false;
    }))     
  }
}
```

**Comment by urugator** [comment]
Well ... you want to fetch whenever something changes ... which implies that there must be some persistent subscription - a reaction (or computed with keepAlive, which is in principle the same thing...).
You could create this `reaction` in constructor or lazily inside the `doWork`, but it has to live on the class instance, not just temporarily for the duration of the `doWork` function...
`keepAlive` basically creates such reaction lazily first time it's accessed - computed being the reaction's dependency and noop fn being the reaction's effect.
Inside the `doWork`, you have an access to Promise, so you could just await/chain it, no need for `when` I think.

Personally I would suggest to avoid the "reactive" approach altogether and imperatively invoke the fetch whenever something relevant changes, like:
```
@action
setSomethingThatFetchDependsOn(val) {
  if (this.val !== val) {
    return;
  }
  this.val = val;
  this.doWork();
}
```
The reason is explained here: https://github.com/mobxjs/mobx/issues/1006#issuecomment-426027838 (mainly last 3 paragraphs)

**Comment by bengry** [comment]
The data is needed by either going to a specific tab, which is an `@observer` (React component), or by doing the above - from another place (so you may have not visited that tab before clicking the button that needs the data).

> Inside the doWork, you have an access to Promise, so you could just await/chain it, no need for when I think.
In regards to this - I don't have access to the Promise in the real app - this store is injected into another one, so I only see the public members, which means `dataRequest` is not visible to it. Moreover, I don't want to re-trigger the fetch if it's not needed (as mentioned in a previous comment, this is an expensive operation).

`keepAlive` does solve it, though I'm not sure if it caches all previous values of the data, or just the most recent one? i.e. if a dependency of a `@computed({ keepAlive: true})` changes, is the previous value of that getter kept in memory? If so, what about the next time in changes - does the 2 previous values kept (and the same for any N), or just the most recent one?

**Comment by spion** [comment]
Its just the most recent one, however if you have multiple instances of the class there will be multiple instances of the computed, and if the instances go away the computed does NOT go away

**Comment by bengry** [comment]
Got it. Is there a way to clear after that `keepAlive` computed manually? Especially after that class has gone..

**Comment by spion** [comment]
It depends on what work that console.log actually does once the fetch is complete. 

Does it fill up data into variables? If so the best way is to derive the data from the computed all the way to the observer React component that uses it, which in turn will take care that it only lives until its needed.

Does it run another fetch then use the data of that? Have a computed promise that chains the promise.

Does it actually run side-effects that are non-mobx? Use `autorun` to run those sideeffects.

Is it something else entirely? Then it depends on what it is.
