### ISSUE TITLE
intercept: TS2339 property "newValue" does not exist on type "IObjectWillChange"

### ISSUE THREAD

**Issue by inoyakaigor** [mobxjs/mobx#2183]
In this code I have an error
![image](https://user-images.githubusercontent.com/1235286/67871884-25142000-fb42-11e9-8b65-c5d8f130c405.png)

> TS2339 property "newValue" does not exist on type "IObjectWillChange"

This error threw because type `IObjectWillChange` defined as union type. This mean that `newValue` will exclude from end type. https://github.com/mobxjs/mobx/blob/c42c6e54582a290ac5c9142e7c3f58f3f01ed9e3/src/types/observableobject.ts#L63-L74

Based on the source code, I suppose that in this place you meant the XOR type and if I add generic type XOR from that comment https://github.com/Microsoft/TypeScript/issues/14094#issuecomment-373782604 error have disappeared:

```typescript
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never }
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U

export declare type IObjectWillChange = XOR<{
    object: any;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
}, {
    object: any;
    type: "remove";
    name: PropertyKey;
}>;
```

![image](https://user-images.githubusercontent.com/1235286/67873719-fba8c380-fb44-11e9-9ef2-1f9036ac9ecd.png)

**Comment by inoyakaigor** [comment]
@FredyC in my case it is unnecessary condition but yes, it works

**Comment by FredyC** [comment]
> in my case it is unnecessary condition but yes

Care to explain? I mean if you want to access `newValue` for some reason, it should be with a condition.

**Comment by inoyakaigor** [comment]
I have a store with observable properties which have a default value. This props never can be deleted or added. Intercept in my screenshots is for logging changes and reducing unnecessary re-rendering
