### ISSUE TITLE
Mobx calls baseclass computed getter instead of subclass getter with same name

### ISSUE THREAD

**Issue by donharriman** [mobxjs/mobx#2186]
Updating an old project (built with mobx v3.4.1) to v5.14.2 caused the working project to fail. 
Here's a minimal example exhibiting the issue:
```
Base.js
const Mobx = require('mobx')
const { observable, computed, decorate } = Mobx

class Base {
  constructor() {
    this.foo = 'something'
  }
  get bar() { 
    console.log(`Base.bar`) 
  }
}
decorate(Base, {
  foo: observable,
  bar: computed
})
module.exports = Base
```
```
Sub.js
const Base = require('./Base')
class Sub extends Base {
  get bar() { 
    console.log(`Sub.bar`) 
  }
}
module.exports = Sub
```
```
index.js
const Sub = require('./Sub')
new Sub().bar
```
```
>node index.js
Base.bar
```
Remove the decorate block, then
```
>node index.js
Sub.bar
```

**Comment by FredyC** [comment]
Please, create reproduction with eg. CodeSandbox. From these pieces of code, it's not apparent (to me) what's the actual issue.

**Comment by donharriman** [comment]
The actual issue is: the executed getter is not the one that was called. I apologize, but have no experience with CodeSandbox.

**Comment by FredyC** [comment]
This is a good time as any to learn with CodeSandbox then ;) You will find it useful for any sort of testing out advanced stuff.

**Comment by donharriman** [comment]
Fredy - with all respect, your immediate dismissal of this issue is rather disappointing. I tried hard to make the example so it was self-evident. The code is simple and I included the output. What would a CodeSandbox add?

In the larger scheme of things, we're talking about violating some basics of OOP. Subclasses can override baseclass methods to provide specialized behavior. The base class method provides a default implementation, which would be called if the subclass does not provide an override.
This is a basic of polymorphism.

When the subclass provides an implementation, it must be called. The issue is that mobx is not calling the subclass implementation.

**Comment by FredyC** [comment]
CodeSandbox shows the code with an actual error and version of all dependencies used. It can be debugged and analyzed for the behavior. Snippets tend to be incomplete (not on purpose) and don't really serve that well.

Besides, it's Friday, it's expected you won't get an answer sooner than on Monday. I am mostly trying to lead you toward providing the most comprehensive report so when someone who understands the problem does not need to spend extra time reproducing the issue.

Is that sufficient explanation? If you need help with your issue, providing as much information as possible will always increase the chances of fast resolution.

**Comment by donharriman** [comment]
Thanks for the info. I'm sure CodeSandbox is an excellent tool.
My small snippets are sufficient to reproduce this issue (in a minimal node project with mobx installed). 
I took the time to report because this is a subtle bug in a some corner of mobx that appears in a particular circumstances that I narrowed down. It bit me, and I hope by bringing it to light, other might not also be bitten.

**Comment by FredyC** [comment]
Suit yourself. If you are not in a hurry, you can only hope someone would be willing to go the extra mile and try to solve your problem without reproduction.

**Comment by donharriman** [comment]
We are totally mis-communicating here. 
This is NOT my problem.
It is a MOBX problem.
I'm not trying to get someone to solve MY problem.
I am reporting a MOBX issue I have identified to the community.

**Comment by FredyC** [comment]
It is your problem because nobody else seems to be bothered by this use case ;) No software is perfect and if you want to utilize some uncommon pattern, you should try to be as helpful as possible.

This is OSS, nobody here is obliged to help you out, especially if you are not willing to provide relevant information.

**Comment by urugator** [comment]
Known limitation, mentioned in docs:
https://mobx.js.org/refguide/computed-decorator.html

> Note that computed properties are not enumerable. Nor can they be overwritten in an inheritance chain.

As a workaround, you can do something like this:

```javascript
class Parent {
  _overridable() {
     /* whatever*/
  }

  @computed get notOverridable() {
    return this._overridable()
  }
}
```
