### ISSUE TITLE
MobX property tracing issue

### ISSUE THREAD

**Issue by sam-perez** [mobxjs/mobx#2187]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I've just been scanning over the documentation since I've heard about MobX a few times now and it made me curious. I immediately dove into how MobX traces property access, and because I wondered how it handled conditional access. It seems to me that this is just not expected behavior because I didn't really find any callout in the docs and haven't easily found any discussion online. Honestly, I'm not even sure if there is a specific term for the issue so that might be tying me up, but here's a short example:

```
import React, { Component } from "react";
import { observer } from "mobx-react";

@observer
class DataObserver extends Component {
  invocations = 0;

  render() {
    console.log("rerender DataObserver");
    if (this.invocations++ === 1) {
      return <span>nothing to see here</span>;
    } else {
      return <span>{this.props.store.userData}</span>;
    }
  }
}

export default DataObserver;
```
I modified the `src/DataObserver.js` in this [example](https://codesandbox.io/s/mobx-playground-lgyyh).

This is pretty unrealistic but you can easily imagine stuff like this happening in the real world. It seems to me that the basic assumption is that every bit of data that could affect the access pattern of an observable during a tracked function's execution must itself be observable. I think this is a reasonable assumption to make, but shouldn't this be specifically called out as it is a subtle assumption with subtle implications? Because in this case, for the rest of the life of this component, changing `name` or `surname`, which causes the store's computed `userData` to update, will not cause rerenders.

**Comment by urugator** [comment]
React states that render function must depend on `state` or `props`. Depending on anything else may cause staleness and is most likely a programmer error. Mobx just adds `observables` to the list of valid dependencies.
So imo it shouldn't really happen in the real world as long as you use react correctly.

If you feel like this could be covered better [in docs](https://mobx.js.org/best/react.html), feel free to PR.

[These two new config options](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#5140--4140) can help to uncover some of these errors.
