### ISSUE TITLE
Mobx5 not support IE11 

### ISSUE THREAD

**Issue by Joycewu31400** [mobxjs/mobx#2188]
I have a question as below:
Mobx Version: 5.10.1
React Version: 16.8.6
When i run my application on IE11, 
i get a error like this, "MobX 5+ requires Proxy and Symbol objects. If your environment doesn't support Symbol or Proxy objects, please downgrade to MobX 4. For React Native Android, consider upgrading JSCore."
I also install "react-app-polyfill" and import "react-app-polyfill/ie11","react-app-polyfill/stable"  to the first line of index.js
If anyone has a good idea to solve the issus, welcome to share with me

**Comment by FredyC** [comment]
Is it really that hard to scroll down one page in the readme? Please do that now...

**Comment by Joycewu31400** [comment]
> Is it really that hard to scroll down one page in the readme? Please do that now...
> 
> Besides, that error message is pretty clear, why don't you trust it? The proxy cannot be polyfilled.

Anyway, thank you for your replay. I just want to make sure if I miss any new features about mobx.

**Comment by FredyC** [comment]
You won't, MobX 4 is LTS, which means it will be updated to anything that MobX 5 has and can fit in there.

**Comment by czbczb** [comment]
I get a same problem too.please help me

**Comment by FredyC** [comment]
Please, read what I said above or open new issue with more details if it doesn't help you.
