### ISSUE TITLE
Dynamic observable objects cannot be frozen

### ISSUE THREAD

**Issue by stevematdavies** [mobxjs/mobx#2194]
I see there are several issues  raised (and closed) e.g. #1900 #1881  with this problem , but I also see that the solutions are somewhat confusing and obfuscated, at least to me. This is such an issue now that I cant fix, Im on the cusp of using an alternative solution to MobX , I really don't wish to, but I have found no explanation of what this error actually means, why it happens, and how to fix it. Most of the replies here are as confusing as the issue itself. (This is due to me). I would really like to solve this and get on with things!

Without giving up too much detail as the work is for a private client, I have the following situation:

I have a store "LocationStore" and a "RootStore" injected into my HomeScreen, and I have a react-native-maps MapView using observables from these stores. 
 
```
// From LocationStore:
    @observable current = {};
    @action updateCurrent(newCurrent){
          this.current = newCurrent;
    }
```

```
From RootStore:
  @observable isVisible = false;
```

At the time if its uses, current is correctly populated and then:

        const { region } = this.props.LocationStore;
        const { isVisible } = this.props..RootStore;
        return <MapView
            initialRegion={toJs(region)}
            region={Platform.OS === 'ios' ? toJs(region): null}
            customMapStyle={MapStyles}
            showsUserLocation={true}
            followsUserLocation={Platform.OS === 'ios'}
            showsPointsOfInterest={false}
            showsIndoors={false}
            visible={isVisible}
            showsBuildings={false}>
            {markerElements}
        </MapView>

```
Error: [mobx] Dynamic observable objects cannot be frozen
This error is located at:
    in AIRMap (at MapView.js:981)
    in MapView (at HomeScreen.js:38)
    in RCTView (at View.js:45)
    in View (at HomeScreen.js:65)
    in HomeScreen (created by inject-with-RootStore-LocationStore-FavouriteStore(HomeScreen))
    in inject-with-RootStore-LocationStore-FavouriteStore(HomeScreen) (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:910)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:985)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:394)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:384)
    in PanGestureHandler (at StackViewLayout.tsx:377)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:59)
    in RCTView (at View.js:45)
    in View (at App.js:57)
    in MobXProvider (at App.js:56)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
```

It seems to be because of the MapView component, but I cannot see what's happening here. Is it my code or a bug, or the MapView component? Some clarity and help here would truly be appreciated, Im at the end of my wits on this one!

**Comment by FredyC** [comment]
Can you please provide a reproduction? I don't see a problem here (maybe someone else does) so it's hard to guess from these snippets.

**Comment by stevematdavies** [comment]
What do you mean? This is part of a large application for a private client, I cant give a whole copy of the app here

**Comment by FredyC** [comment]
Just use CodeSandbox a try to replicate the issue there. We don't need a whole app, on the contrary, the limited piece code that shows the problem is much better.

**Comment by stevematdavies** [comment]
The code in the issue is exactly where the issue occurs, I really don't know, how to provide any more info short of setting up much of he app code I have written, (all the stores, the constants etc), Its not really possible to provide the wider context without the entire app.

**Comment by FredyC** [comment]
Well, thing is that with those snippets we might be as clueless as you are. The problem might be occurring in some piece of code you are not showing.

If you are unable to use CodeSandbox for some reason, then you will have to wait and hope someone will understand the problem.

**Comment by stevematdavies** [comment]
I think I may have got into the issue, to do with the object being returned from the store, it's not what I thought it to be. I assumed objects are returned as is, but they are a mob-x proxy of some sort, so using toJS seems to work. Its' a bit hacky, but for the lack of an explanation of the causes, this appears to stop the symptoms. Thanks for your time.
