### ISSUE TITLE
IDerivationState.POSSIBLY_STALE + observableRequiresReaction = warning

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx#2195]
<s>I don't have a minimal repro or test case yet</s>

Minimal repro:
```ts
    test("don't warn on reads inside a computed, when reaction updates the observed value", function () {
        try {
            // #916
            mobx.configure({ observableRequiresReaction: true })
            const a = mobx.observable.box(0)
            const b = mobx.observable.box(0)
            const c = mobx.computed(() => a.get() + b.get())
            const values = []

            mobx.autorun(() => {
                values.push(c.get())
                b.set(100)
            })

            const messages = utils.supressConsole(() => {
                a.set(1)
            })

            console.log(messages)

// [warn] [mobx] Observable ComputedValue@4 being read outside a reactive context
            expect(messages.length).toBe(0)
        } finally {
            mobx.configure({ observableRequiresReaction: false })
        }
    })
```

The observableRequiresReaction is triggered  when hitting the following code path:
https://github.com/mobxjs/mobx/blob/master/src/core/derivation.ts#L93-L109 
```ts
        case IDerivationState.POSSIBLY_STALE: {
            const prevUntracked = untrackedStart() // no need for those computeds to be reported, they will be picked up in trackDerivedFunction.
```
Due to the `untrackedStart` call

Related #916

**Possible fix:**
Make untrackedStart/untrackedEnd to have own globalState flag?

**Comment by urugator** [comment]
Wierd ... IIRC `untracked` shouldn't have any effect on `allowStateReads` which is the relevant flag for raising the error (rather than actual presence of derivation - that was the point of the rewrite...)

**Comment by Bnaya** [comment]
Maybe it's something else
I will look again

**Comment by urugator** [comment]
It's not because of `untracked`.
What happens is, that you modify the observable, which notifies the computed, which has to recompute, which accesses the observable - at this point `allowStateReads` is `false`.
`autorun` is or isn't invoked later based on the `computed`'s result.
We have to `allowStateReads` during the recomputation.

**Comment by Bnaya** [comment]
PR up

**Comment by Bnaya** [comment]
published
