### ISSUE TITLE
Option for enabling spy in production

### ISSUE THREAD

**Issue by ItaHeld90** [mobxjs/mobx#2201]
Hey,
I'm working on a large scale project where we're using mobx 3 and would like to upgrade to mobx 4 (we need to support IE).
The issue is we have an undo/redo mechanism that is relying on the spy, and I see that as of mobx 4 it's a **no-op in production mode**.

I'm aware of the fact that you suggested before, in other threads, to use the **MST/deepObserve/custom serialization** for this task, but none of the options are practically possible for us at this stage.

**deepObserve** was our top alternative, except that it stops observation at non-observable objects in the hierarchy, and we want to listen to deep changes in the top stores (even if between the top store and the changed observable there exist non-observable layers).

What I would like to ask is: Is there any way to add an **option** to enable the spy in production mode?
Also are there any breaking changes in the spy's behavior, that would make this upgrade difficult?

I know the spy wasn't built with this task in mind, I would of course appreciate other suggestions.
Thanks.

**Comment by 8balloon** [comment]
@ItaHeld90 I'd try forking the repo and removing all of the `process.env.NODE_ENV` checks in `src/core/spy.ts`

**Comment by khusamov** [comment]
Except the `src/core/spy file.ts` will have many where still correct code. 

For example here https://github.com/mobxjs/mobx/blob/master/src/core/reaction.ts#L129

**Comment by khusamov** [comment]
Is there an alternative to spy ()?

**Comment by codeBelt** [comment]
I am converting a sample project from Redux to Mobx 5 to compare the differences. I was hoping `spy()` would act like a middleware to check all actions for a `Error` object across stores but I see you cannot use it in production.  How could I accomplish this without `spy`?

**Comment by mweststrate** [comment]
@codeBelt establish a global error handler? 

Beyond that, either use a fork or patch-package if you're convinced you really need spy in prod :)

**Comment by Dutzu** [comment]
New idea maybe.

How about using Spy to be able to track all user interactions to determine the session time more accurately for analytics?

**Comment by FredyC** [comment]
To discuss new ideas please use https://github.com/mobxjs/mobx/discussions and elaborate more on details why do you need it, what are pros & cons.
