### ISSUE TITLE
Question: What is the correct way to use the decorate function?

### ISSUE THREAD

**Issue by gjae** [mobxjs/mobx#2206]
Hi good day.
Can someone give me a hand with mobx ?, I am using the utility decorate with a class like Store but when executing an action it indicates that this.counter is read only, does anyone know what to do in this case ?, attached reference images.

![image](https://user-images.githubusercontent.com/28078695/68960456-97256f80-07a6-11ea-8d35-2a1cbe28c45a.png)
![image](https://user-images.githubusercontent.com/28078695/68960474-9e4c7d80-07a6-11ea-8efc-a18b06112fe9.png)

**Comment by FredyC** [comment]
Can you please make a working reproduction with eg. CodeSandbox? From these snippets it does look alright indeed.

**Comment by gjae** [comment]
Solution: i use arrow functions with actions methods and work!!

**Comment by FredyC** [comment]
Ah right, that because you are calling `this.props.addCounter` which means it does not have a reference to original store. By using arrow function you bind them to the class instance.
