### ISSUE TITLE
error TS2304: Cannot find name 'AsyncGenerator'

### ISSUE THREAD

**Issue by vovkasm** [mobxjs/mobx#2210]
I have a:

2. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

After update to mobx 4.15.0 I have this issue (4.14.1 works ok):
```
node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                             ~~~~~~~~~~~~~~


Found 1 error.
```

My environment:
node: 13.1.0
typescript: 3.7.2

tsconfig.json (related parts):
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["es2015", "es2016"],
    "module": "es6",
    "moduleResolution": "node",
    "noEmit": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "preserveSymlinks": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "es6",
    "importHelpers": true,
    "types": ["react", "react-native"]
  },
}
```

Above error because AsyncGenerator defined only in lib.es2018.asyncgenerator.d.ts

So question, does mobx (even 4.x) now requires es2018 to work properly?

**Comment by FredyC** [comment]
@xaviergonz Is this related to your changes?

**Comment by mpotter-modus** [comment]
Yep, AsyncGenerator was introduced here: e988a5220b2f437635eebb10b774853e224c2800

There is no corresponding dependency update in the commit (for npm, at least).

**Comment by xaviergonz** [comment]
Yep, I didn't actually realize AsyncGenerator is part of the es2018 type defs, but those are required to properly type flows that use async generators. There are several ways to fix this:
1) The user can add "es2018.asynciterable" or better (es2018, esnext) etc to the lib section of tsconfig (which are just type definitions, doesn't polyfill or change code generation etc)
2) The user can use `skipLibCheck: true` on tsconfig (which ignore external d.ts errors)
3) To remove AsyncGenerator from mobx, although that yields a bad typing experience when using async generators in flows (not like that's used too often, though it seems mobx supports it)

**Comment by FredyC** [comment]
@xaviergonz I think both 1 and 2 are a better option, but needs to be documented.

**Comment by bengry** [comment]
This shouldn't be stale, it's an issue that needs handling. @xaviergonz?

**Comment by xaviergonz** [comment]
Where in the docs do you think it should be?

**Comment by FredyC** [comment]
Perhaps add it to FAQ? https://mobx.js.org/faq/faq.html

**Comment by xaviergonz** [comment]
PR created
