### ISSUE TITLE
Incorrect type inference of the action callback arguments

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx#2211]
I have an:
[x] Issue:
  * [X] Provide a **minimal** sample reproduction: https://codesandbox.io/s/react-mobx-starter-t8xju
Go to `components/App.tsx`
* [X] **Did you check this issue wasn't filed before?** It looks like there was a fix in 2016, which solved the same issue: https://github.com/mobxjs/mobx/pull/500
* [X] **Elaborate on your issue. What behavior did you expect?**
I am expecting correct type inference for the arguments of `action` callback. All arguments have type 'unknown':
![image](https://user-images.githubusercontent.com/22447849/69094534-9835f580-0a61-11ea-8019-f1ead716889d.png)
Expected type 'number'.
* [X] **State the versions of MobX and relevant libraries. Which browser / node / ... version?** Mobx 5.9.4, TypeScript 3.4.5
* [X] **What problem would it solve for you?** It would allow to use type inference instead of manually specifying each argument type of the action callback.
* [x] **Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?** Yes, because it looks like type inference worked with previous Mobx/TypeScript versions.
* [x] **Are you willing to (attempt) a PR yourself?** I already tried to fix the issue but with no success.

**Comment by FredyC** [comment]
Um, since you obviously have CodeSandbox in that picture, can you please share that as well?

**Comment by kubk** [comment]
@FredyC Sorry, I updated the link and removed unrelated code.

**Comment by FredyC** [comment]
Thanks. Well, I am not so sure `action` can infer that argument properly. And if it would be possible, it would be a lot of hassle for a little gain. Have a look at the current typings for actions.

https://github.com/mobxjs/mobx/blob/db4b3e72096279a7ac07faa7eb44d25a227f191d/src/api/action.ts#L20

It's already crazy overload hell. Expanding that to get the correct argument type might not be worth it. I think this is one of the cases where explicit type casting will be necessary ... `action((arg: number) => ...`.

I will leave this open if someone else wants to chime.

**Comment by kubk** [comment]
@FredyC The interesting detail I noticed is that type inference works with Mobx 4.1: https://codesandbox.io/s/minimal-mobx-react-project-pkzhx
![image](https://user-images.githubusercontent.com/22447849/69131572-a74d8f80-0ac3-11ea-8000-98acf0a9908a.png)
But this example doesn't use TypeScript. I'll investigate it further. Thank you.
