### ISSUE TITLE
Hydrating client store through autorun in webworker?

### ISSUE THREAD

**Issue by IljaDaderko** [mobxjs/mobx#2212]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

I'm attempting this latter today, but I don't see why this won't work. Hence I wanted to ask this question here in case I am missing anything crucial in terms of performance.

I want to create mobx observable store and associated actions within a webworker. In the same worker I will add `autorun` that listens to worker store changes and then posts message to client if there was a change (message will contain whole store, but it is not too big).

On thee client I will create a client store that my react application will observe. Client will then call actions within worker (there are no actions in client) and thus once worker updates its state it will update client one as well from autorun.

Is there anything wrong with this approach?

I guess it could be illustrated like this (perhaps client is not correct here, rather main thread).
![example](https://user-images.githubusercontent.com/3154053/69144299-a886b880-0ad3-11ea-8a4a-f0bf23c06dd0.jpg)

**Comment by FredyC** [comment]
It might be useful if you can explain what did not work about your approach.

**Comment by IljaDaderko** [comment]
I just tested it and everything works, this was more of a question to clear things up i.e. is it ok to pass store around from web worker to main thread this way? etc...

**Comment by FredyC** [comment]
Uhh....if it works for you, it's definitely fine :) I am sure not many people tried that, so chances are you are a pioneer and in that case, we thank you for letting us know it works ;)

**Comment by IljaDaderko** [comment]
Alright :D only caveat is that you can't pass `observable` as is to main thread, I needed to use `toJS` method on it and then just `set(myClientStore, workerStore)` on client. But so far so good, could be powerful way to offload state management of the main thread.

**Comment by FredyC** [comment]
Yea, that's expected, you need to serialize everything going between WW and main. That's kinda one the reason why I did not give it a proper try out. And also of course because I had no use case of heavy computation that would be better done in WW.
