### ISSUE TITLE
I had a problem, "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Shin-JaeHeon** [mobxjs/mobx#2214]
### My environment
I use Chrome and TypeScript.
All dependencies are up to date.

### My problem
![image](https://user-images.githubusercontent.com/21238436/69219497-523e7600-0bb6-11ea-8632-d93691c00ab6.png)

When I used the debugger to find out, the code below is repeated.
![image](https://user-images.githubusercontent.com/21238436/69219559-7437f880-0bb6-11ea-89d1-9639fee2c524.png)

### My code
`serviceSeparator` has `@observable`.
This `serviceSeparator` was initialized in the constructor.
![image](https://user-images.githubusercontent.com/21238436/69218150-73ea2e00-0bb3-11ea-8bcc-dab87a900e58.png)

`Main VM` inherits the `VM`.
`@computed get service()` is return service object.
![image](https://user-images.githubusercontent.com/21238436/69218183-87959480-0bb3-11ea-8ae4-acc77937b343.png)

call `MainVM.init()`

![image](https://user-images.githubusercontent.com/21238436/69218278-bad82380-0bb3-11ea-886f-156429e55c9e.png)

##  I found something interesting.

* If `serviceSeparator` is `@observable`, this error occurs when the value is initialized in the constructor.
*  If `serviceSeparator` is `@observable`, this error occurs when `get service()` in the `MainVM` is `@computed`.
* If the `get service` in the `MainVM` is not `@computed`, initializing `serviceSeparator` from the constructor does not cause an error.

I want to use both `@observable` and `@computed`.

**Comment by FredyC** [comment]
Thank you for the detailed and minimal repro. Someone will surely have a look soon. I tried, but I don't understand MobX internals that well and I don't see anything wrong with your code, so it's most likely a bug.

**Comment by FredyC** [comment]
Oh wait a minute, you have that infinite loop in your code actually...

You are calling `MainVM.service` which calls `VM.getService` and that tries to access `MainVM.service` again. There is no end.

I think you need to throw an error if no service is present or something like that to stop the loop.

```js
return this.serviceSeparator ? this._service : (this._service2 ? this._service2 : this._service);
```

**Comment by HealGaren** [comment]
@FredyC @Shin-JaeHeon 
I have a little simpler example.

https://stackblitz.com/edit/typescript-sfupmj

![image](https://user-images.githubusercontent.com/13010755/69224595-30e28780-0bc0-11ea-9981-f6c4a6dc548f.png)

Same error, I think it's a bug...

**Comment by HealGaren** [comment]
I analyzed javascript code after transfiling.

https://stackblitz.com/edit/typescript-jhwcsr?file=index.ts

I don't know deeply what's happening inside mobx,
but it makes error when i decorate `Derived` before the static value assigned to class, 
and it works fine when decorate before static value assigned.

I hope sharing my attempt could be helpful.

**Comment by mweststrate** [comment]
Thanks for the analysis.

There is very limited support for statics and other fancy patterns until decorators are finally standardized. I think a simple work around for your use case is to initialize that static field *after* the class decoration.

```typescript
class MainVM {
  static instance!: MainVM
}
MainVM.instance = new MainVM()
```

**Comment by urugator** [comment]
It's not because of a static member, but because you're changing prototype (`decorate`) after you create an instance `new Derived()` (of that prototype)
```javascript
// throws as well
const derived = new Derived();
decorate(Derived, {
  service: computed
});
derived.service;
```

**Comment by Shin-JaeHeon** [comment]
Thank you all for your help.
