### ISSUE TITLE
if mutate observable in reaction, reaction order works differently on mobx 4 or 5

### ISSUE THREAD

**Issue by HealGaren** [mobxjs/mobx#2215]
Issue:
  * [x] Provide a **minimal** sample reproduction.
https://codesandbox.io/s/minimal-mobx-react-project-y0s2g?fontsize=14&hidenavigation=1&theme=dark (mobx 4, problem)
https://codesandbox.io/s/minimal-mobx-react-project-poew3?fontsize=14&hidenavigation=1&theme=dark (mobx 5)

```js
import { observable, reaction } from "mobx";

const store = observable({
  a: 0,
  b: 0
});

reaction(
  () => store.a,
  a => {
    console.log("first effect start!");
    store.b++;
    console.log("first effect done!");
  }
);

reaction(
  () => [store.a, store.b],
  ([a, b]) => {
    console.log("second effect!", a, b);
  }
);

store.a++;
```

  * [x] Did you check this issue wasn't filed before?
https://github.com/mobxjs/mobx/issues/1158
As I have read it must be ordered.

  * [x] Elaborate on your issue. What behavior did you expect?
(according to issue 1158)
I expected the effect of second reaction should be called after first reaction.
but mobx 5 works fine, and mobx 4 works strangely.

<Mobx 5 (expected)>
![image](https://user-images.githubusercontent.com/13010755/69240174-42875780-0bdf-11ea-85d3-fe3fe8b9c510.png)

<Mobx 4 (strange)>
![image](https://user-images.githubusercontent.com/13010755/69240264-6fd40580-0bdf-11ea-9d15-8b74714cc525.png)

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
chrome

(+)
You may think of this as a bad example of mobx use. but I think some case makes sense...
https://stackblitz.com/edit/typescript-c4btrz
if observable source is changed, fetch in reaction.
the fetched result is other source of fetch reaction.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#500

> In some cases, the order in which autoruns are fired could have changed due to some internal optimizations (note that MobX never had a guarantee about the order in which autoruns fired!)

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/issues/1916
