### ISSUE TITLE
Make computedDecorator part of the public API, or otherwise document how to make a custom decorators

### ISSUE THREAD

**Issue by nstoertz** [mobxjs/mobx#2216]
I'd like to create a couple decorators for use on computed properties needs to use a custom equals function. For example:

```
const computedMoment = computedDecorator({
  equals: (a: Moment, b: Moment): boolean => a.isSame(b),
});

  @computedMoment
  public get startMoment(): Moment {
    ...
  }
```

`computedDecorator` is already defined here:
https://github.com/mobxjs/mobx/blob/master/src/api/computed.ts#L19

Could you add `computedDecorator` to Flow and Typescript definitions, or if there is a better solution for creating custom decorators, add some documentation to that effect?

https://github.com/mobxjs/mobx/blob/db4b3e72096279a7ac07faa7eb44d25a227f191d/src/mobx.ts#L105

**Comment by spion** [comment]
You shold be able to just use the computed function i.e. 

```typescript
let computedMoment = computed({equals: (a: Moment, b: Moment): boolean => a.isSame(b)});
```

non-decorator-call detection will take care of the rest.

**Comment by nstoertz** [comment]
That works well... thanks!
