### ISSUE TITLE
Issue with observable array after mobx4 --> mobx5 upgrade 

### ISSUE THREAD

**Issue by tif-p-st** [mobxjs/mobx#2220]
I have a:

1. [X] Question: 

Hello, I uses mobx with ArcGIS JavasScript API in my application. The following is a simplified version of my workflow: 

1. I create a jobs `FeatureLayer` for an ArcGIS map
1. I create an `@observable` array of "jobs", 
2. From each job I create a "graphic"
3. Then I use an `applyEdits` function from ArcGIS to draw the graphics

The app works when I was using mobx 4. However, after switching to mobx 5, the `applyEdit` function breaks with this error `DOMException: Failed to execute 'postMessage' on 'MessagePort': [object Object] could not be cloned.`. My guess is this is related to the use of Proxies as documented [here](https://mobx.js.org/README.html#mobx-4-vs-mobx-5). 

I also notice that if I `JSON.parse(JSON.stringify())` my observable array. The code will work again with mobx 5. Can anyone please advice if this is a good approach to "unproxy" the array? 

### Repro steps/demo
1. Open https://codesandbox.io/s/react-arcgis-demo-x97ei?fontsize=14&hidenavigation=1&theme=dark
2. Bring up the browser's dev tool &gt; Console tab (**not** the codesandbox built-in console)
3. See the error
4. Doing one of the following will stop the error: 
    - open utils/map-loader.js, uncomment L65 and comment out L66
    - Switch mobx to 4.15.0

**Comment by FredyC** [comment]
You better use `toJS` exported function to serialize observable, but yes, you need to "unproxy".

**Comment by tif-p-st** [comment]
Thanks for the quick response @FredyC ! I will do the unproxy then. Closing the ticket
