### ISSUE TITLE
Reacting to an observable array, and async responding

### ISSUE THREAD

**Issue by stevematdavies** [mobxjs/mobx#2223]
Im trying to run an async function to set sessionStorage (mobile) everytime an (favourites) array is updated. The session storage reolaces its current value with the updated array.

This is part of a rather involved React Native Expo managed app.

basically

```

@observable favouriteParks = [];
// in constructor
reaction(() => {
                this.favouriteAreas.length;
                return this.favouriteAreas.slice()
            },
            areas =>
                (async () => {
                    if (areas.length > 0) {
                        console.log("setting areas item");
                        await AsyncStorage.setItem(
                            this.storageKeys.FAVOURITE_AREAS,
                            JSON.stringify(toJS(areas))
                        );
                }
                })());
//......
 @action addNewFavourite(id) {  this.favouriteParks.push(id) }
```

I'm still not 100% clear if this is correct, and / or why the console.log or the function is not firing.

_Originally posted by @stevematdavies in https://github.com/mobxjs/mobx/issues/385#issuecomment-560372442_

**Comment by FredyC** [comment]
As Michel already suggested, please create a reproduction with eg. CodeSandbox. It doesn't matter it's a part of RN, these mechanics are exactly the same so use regular React project.

**Comment by mayorovp** [comment]
There are error here: `parks => async () => { ... }`

You return second function from the fisrt one, but nobody invoke it.

**Comment by stevematdavies** [comment]
IN the process of a reproduction, why was it closed??

**Comment by mayorovp** [comment]
This error is not related to mobx

**Comment by mayorovp** [comment]
Reproduction:

```
function foo() {
    return async () => console.log('Why i am never called?');
}

foo();
```

**Comment by stevematdavies** [comment]
@mayorovp this is not the issue I opened, please see my issue and example, but it was reccomended I open a new issue,

**Comment by mayorovp** [comment]
@stevematdavies ok, but please edit your first message

**Comment by stevematdavies** [comment]
What should I have in my first message?

**Comment by stevematdavies** [comment]
What should I have in my first message?

**Comment by mayorovp** [comment]
@stevematdavies that code: https://github.com/mobxjs/mobx/issues/2223#issuecomment-560387603

**Comment by stevematdavies** [comment]
I have updated it to call the async function

**Comment by stevematdavies** [comment]
Ok Im having issues with providing a codeSandbox result, mainly with it not allowing decorators, support but I think I have the gist of what is happeining, ill try and hack through

**Comment by mweststrate** [comment]
Note that you can use the [decorate](https://mobx.js.org/best/decorators.html) api to avoid using decorator syntax

**Comment by stevematdavies** [comment]
Yes, thanks @mweststrate 

I use that in that api in the actual app, however, I'm under a deadline to get this app done, so I am trying to fix things directly in my code for time. Id I have some time and I cant fix it using the sugegstions here, ill reproduce this issue using the api.
