### ISSUE TITLE
Computed property based on a property in another store

### ISSUE THREAD

**Issue by giacomorebonato** [mobxjs/mobx#223]
Is it an expected scenario to have a computed property on a store, based on an observable that is in another store?
In my example I have a QueryStore that contains all params to filter an array which is in another store.
How would you deal with this scenario?
In my case I am importing the store in the other one... and it works.

Thank you.

**Comment by AriaFallah** [comment]
@giacomorebonato It would be helpful if you posted your code or at least something similar.

**Comment by giacomorebonato** [comment]
```js
/* globals */
import mobx, { computed } from 'mobx'
import itemStore from './itemStore'

function SearchStore () {
  let self = this

  mobx.extendObservable(self, {
    categoryId: null,
    page: 0,
    take: 10,
    loading: true
  })

  self.visibleItems = computed(() => {
    let copy = mobx.toJSON(itemStore.items)

    if (self.categoryId) {
      copy = copy.filter((c) => (c.category_id === self.categoryId))
    }

    return copy
  })
}

export default new SearchStore()

```

**Comment by giacomorebonato** [comment]
The code above works... but is it the right approach in your opinion? (the filtering part is not complete..)

**Comment by AriaFallah** [comment]
I think the idea behind it is fine. Though I'm curious why you're using `new` and a function here. Why not just something like.

```js
import { computed, toJSON, observable } from 'mobx'

const itemStore = observable({
  items: [{ category_id: 1 }, { category_id: 2 }, { category_id: 3 }]
})

const p = observable({
  categoryId: null,
  page: 0,
  take: 10,
  loading: true
})

export default {
  ...p,
  visibleItems: computed(() => {
    const copy = toJSON(itemStore.items)
    return p.categoryId ? copy.filter((c) => (c.category_id === p.categoryId)) : copy
  })
})
```

**Comment by giacomorebonato** [comment]
I didn't like the annotation syntax and I lint with [standard](https://github.com/feross/standard).
I have just tried to follow the ES5 examples in the doc, but your example is really nice... I will think about converting my code. Thank you.
