### ISSUE TITLE
MobX errors thrown as strings aren't properly caught and obfuscate the actual error

### ISSUE THREAD

**Issue by clehene** [mobxjs/mobx#2230]
Instead of seeing the error I was getting an error boundary error;

```
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `error` of type `String` supplied to `ErrorBoundaryFallbackComponent`, expected instance of `Error`.
    in ErrorBoundaryFallbackComponent (created by ErrorBoundary)
```

The actual error was 
```
"[mobx] missing option for computed: get" 
```

The problem is this is thrown as `string`

https://github.com/mobxjs/mobx/blob/728ad70feef5856060e1dd30516ca1c6161803dd/src/core/computedvalue.ts#L109

As most code catching errors expects actual Error objects It should be `Error`

I

**Comment by urugator** [comment]
Probably oversight. I think it should be 
`fail("missing option for computed: get")` 
or perhaps
`invariant(options.get, "missing option for computed: get")`
 (not sure whats the reasoning behind `production` check)
PR welcome

**Comment by ramkumarvenkat** [comment]
@FredyC @clehene Let me pick up this issue! I am new to JS, react and mobx and this will be a good first issue for me to get started into the code. 

https://github.com/mobxjs/mobx/pull/2243
