### ISSUE TITLE
Pitfalls should be part of `eslint-mobx`

### ISSUE THREAD

**Issue by clehene** [mobxjs/mobx#2231]
There are a couple of outdated eslint plugins for mobx. 
Arguably these should be part of an `eslint-mobx` package maintained with the main code base in order to keep them in sync with releases.

This could likely decrease the number of issues raised because of common mistakes, reduce traffic on support chats, etc.
For reference see https://github.com/mobxjs/mobx/issues/2230

Good starting points
https://github.com/gakimball/eslint-plugin-mobx
https://gist.github.com/gakimball/334a33796c8c15a4b89b8aabb0b01de8
https://github.com/eranshabi/eslint-mobx
https://www.npmjs.com/package/eslint-plugin-mobx-computed-getters

**Comment by kubk** [comment]
Agreed. React introduced [ESLint rules](https://reactjs.org/docs/hooks-rules.html) for hooks, why not create an official ESLint plugin for Mobx? I created [eslint-plugin-mobx-computed-getters](https://github.com/kubk/eslint-plugin-mobx-computed-getters), this package has up-to-date dependencies and might be used as a starting point for an official Mobx ESLint plugin. I'll be happy to contribute to such a plugin. Also, it looks like name `mobx-eslint` is not reserved in NPM and we may use it for a new package: https://www.npmjs.com/package/mobx-eslint

**Comment by FredyC** [comment]
In my opinion, the `eslint-plugin-mobx` would be better to follow ESLint naming convention which then allows specifying plugin in the configuration as "mobx" only, but that's the detail.

Either way, are you asking for a permission to make a separate MobX package? If you are willing to make it, don't hesitate and go for it. We can definitely host that repo under mobx org.

**Comment by FredyC** [comment]
Closing the issue as out of the scope. Anyone interested in making that plugin - just do it :)
