### ISSUE TITLE
[Suggestion] Create cross-org maintainers chat

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx#2232]
In some cases it's super helpful to directly contact other org members or maintainers, to ask for a quick and short look on something, coordinate releases or even asking who can make a release.

For example, i want to ask now when the next mobx release is expected, and also ask a specific maintainer quick question and i really not sure what is the write way to do so 😅 

I suggest we create a channel in one of the chats/community platforms, with write permissions for org members only.
It will be expected from the members to keep the chats relevant and to keep most of the discussions in issues.
Tagging specific members when relevant will be allowed.

I don't have any specific preference for where this channel gonna be,
But i would personal prefer avoid creating another dedicated slack/discord org.

Would love to hear your opinion!

**Comment by Bnaya** [comment]
tagging some of the relevant people i can think of
@mweststrate @xaviergonz @FredyC @urugator

**Comment by FredyC** [comment]
It sounds like a good idea, but I am not aware of any suitable platform for that. The best that comes to my mind is Gitter for ease of access (no need for another account). I made a separate room, but it cannot be made private.

https://gitter.im/mobxjs/team

**Comment by Bnaya** [comment]
@FredyC made a channel https://gitter.im/mobxjs/team
