### ISSUE TITLE
shallow comparer uses incorrect depth for Map comparison

### ISSUE THREAD

**Issue by hearnden** [mobxjs/mobx#2237]
The shallow comparer was introduced in fc70ee3e7596159ce9ac588f070ee4058aca5b2b.

A shallow comparison of Map objects should presumably compare their keys and values.  However, the current shallow comparer does not do this.  This can be seen by the following test failure:
```js
   expect(sh(new Map([[1, 2]]), new Map([[1, 2]]))).toBe(true)
```
that could be added to the shallow-comparer tests: https://github.com/mobxjs/mobx/blob/3fe3ada1ee2cd319a8f5d21d8f2a569ac054722a/test/base/extras.js#L491

I believe this is because Maps are unwrapped to an Array of entries:
https://github.com/mobxjs/mobx/blob/3fe3ada1ee2cd319a8f5d21d8f2a569ac054722a/src/utils/eq.ts#L138
which introduces an extra level of depth to the data being compared.  However, the `depth` argument to `deepEqual` remains at 1:
https://github.com/mobxjs/mobx/blob/fc70ee3e7596159ce9ac588f070ee4058aca5b2b/src/utils/comparer.ts#L16

This means that a shallow comparison of `Map`s is effectively performing an identity comparison of their `entries()`, which will probably always fail for non-empty maps, and that is unlikely to be useful.

This can potentially be fixed by increasing the depth by 1 whenever `unwrap` encounters a pair of `Map`s.

**Comment by hearnden** [comment]
Proposed fix in PR: https://github.com/mobxjs/mobx/pull/2238

**Comment by mweststrate** [comment]
Released as (4/5).25.2. Thanks again!
