### ISSUE TITLE
structural and shallow comparers have false positives for different collection types

### ISSUE THREAD

**Issue by hearnden** [mobxjs/mobx#2239]
A comparison of different collection types should presumably always fail.  For example, both of these comparisons should presumably fail:
```ts
   comparer.structural(new Set([1, 2]), [[1, 1], [2, 2]])
   comparer.shallow(new Set(), [])
```
However, both pass.

`eq` unwraps ES6 collection types to Arrays before the same-type test, which produces those false equalities:
https://github.com/mobxjs/mobx/blob/3fe3ada1ee2cd319a8f5d21d8f2a569ac054722a/src/utils/eq.ts#L30-L33

This can presumably be fixed by moving the unwrapping to after the same-type test.

**Comment by urugator** [comment]
It seems intentional, but I don't think it's useful - I can't imagine `computed/reaction` altering between produced types, unless the types actually represent different value.

What also seems troubling is treating `Set` as ordered collection...

@mweststrate

**Comment by mweststrate** [comment]
I think the set case is just an oversight, as they have been bolted on later. PRs to fix welcome!

cc @auvipy this is a nicely limited scoped PR if you want to get hands on :)

**Comment by hearnden** [comment]
> PRs to fix welcome!

Sure thing, I raised a PR here (I should have mentioned it in the description):
https://github.com/mobxjs/mobx/pull/2240

**Comment by mweststrate** [comment]
Fixed in (4/5).15.2.
