### ISSUE TITLE
React Components - Clear observables

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#224]
Do I need to clear observables?

Example:

```js
@observer
class MyComponent extends Component {
  @observable hello

  componentDidMount() {
    this.hello = 'world'
  }

  componentWillUnmount() {
    this.hello = null // or delete this.hello ?
  }
}
```

**Comment by AriaFallah** [comment]
What would be the benefit of doing that other than resetting the state of your component?

**Comment by hnordt** [comment]
@AriaFallah just wondering if I need to do any "memory" cleanup

**Comment by mweststrate** [comment]
@hnordt no `@observer` takes care of all cleanup. Observables and computeds themselves never need cleanup. The only thing that needs cleanup are `autorun` and `.observe` listeners.

**Comment by hnordt** [comment]
@mweststrate thank you!

**Comment by AriaFallah** [comment]
@mweststrate is there a way to know when your store is garbage collected so that you can dispose of the `observe`? Or is that something that's not in my control?

I'm using it pretty liberally for mobx-store:
https://github.com/AriaFallah/mobx-store/blob/master/src/index.js#L85
