### ISSUE TITLE
Document better differences between observe/reaction/autorun

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2241]
I think this is a piece of very valuable information here and should be incorporate in docs in some way.

_Originally posted by @urugator in https://github.com/mobxjs/mobx/issues/2222#issuecomment-561233503_
---

Naming is a bit misleading, in short:
`observe` has nothing to do with `autorun/reaction/action` etc.
`onBecomeObserved` only relates to `autorun/reaction`.
The mobx is designed around `autorun/reaction`. The `observe` is just something extra, it uses completely different (very trivial) logic and isn't actually very useful (arguably).
For illustration, this is a setter for simple observable value (`observable.box()`):
https://github.com/mobxjs/mobx/blob/c4131f1f008330ecd1fc3d9c5f1603b52760a82e/src/types/observablevalue.ts#L107-L119
`this.reportChanged()` relates to propagating a change through dependency graph, created by `reaction/autorun`.
`notifyListeners` simply invoke callbacks registered via `observe`.

`onBecomeObserved` is invoked when a node is attached as a child of another node inside a dependency graph.
It doesn't care about listeneres attached with `observe` (internally `registerListener`).

`onBecomeObserved/autorun/reaction/action` works with `IObservable`
`observe`, despite it's name, works with `IListenable`

Ok so, how you're supposed to use `reaction/autorun`:
Do not think about detecting changes/diffs. Think about what you want to do with your model.
Whatever you want to do, it must be wrapped inside "subscription" function - either `autorun` or `reaction` (it's first arg)
The difference is that `reaction` produces some value and calls another function (second arg) with value provided as argument.

Let's say you want to print model to console using reaction. Why following doesn't work:
```javascript
reaction(() => items, () => {
  console.log(items);
});
```
Because printing model means to "stringify it" first and then send it to stdout.
The stringification process determines which parts of the model are actually needed. Therefore it must be part of the "subscription" function.
What you want to "subscribe for" very much depends on "what you want to print". 
Eg if you would change the implementation of `console.log` to only print the first `item` of `items`, then we are not interested in changes of other items. 
So it should be like this:
```javascript
reaction(() => stringify(items), string => console.log(string));
```
The implementation of `stringify` function is non-trivial, so in practice you could workaround it like:
```javascript
reaction(() => toJS(items), copy => console.log(copy));
```
However, it presumes that you need a whole `items` object for `console.log` operation, which is not neccessarily true as noted previously.

Note the difference between `autorun/reaction`
```javascript
// prints anytime items are modified
autorun(() => console.log(items));
// prints only if the string actually changed
reaction(() => stringify(items), string => console.log(string));
```

At this point you may have noticed, that Mobx works with discrete observable units called Atoms.
Eg. an observable array of 10 items is basically a collection of 10 atoms + 1 atom representing size. Similary objects have one atom per property.
You cannot subscribe for (observe) an array/object/map as a whole, you can only subscribe for (observe) these individuals atoms.
Therefore `onBecomeObserved` expects such single atom (or computed).
However you can expose the array via another "atom/computed" and use it instead:
```javascript
const store = observable({
  array: [],  
})
onBecomeObserved(store, "array", () => console.log("array is being consumed by someone"));
// (the object's property is the atom representing the array)
```
Obviously you have to make sure, that you can't get access to the array without accessing(subscribing) the store property (`store.array`) along the way.

**Comment by mweststrate** [comment]
Closing the issue since nobody cared about it enough to pick it up, and docs are now largely refactor in v6
