### ISSUE TITLE
Export is not defined in Codepen/CDN

### ISSUE THREAD

**Issue by lipedeitos** [mobxjs/mobx#2242]
Trying to run a Codepen with **mobx/mobx-react/mobx-react-lite** (**mobx-react-lite** its not even in CDN yet) and its giving me the following error:

Versions:
https://cdnjs.cloudflare.com/ajax/libs/mobx/5.15.0/mobx.min.js
https://cdnjs.cloudflare.com/ajax/libs/mobx-react/5.4.4/index.min.js

Errors:
`mobx.min.js:1 Uncaught ReferenceError: exports is not defined at mobx.min.js:1`
`Uncaught TypeError: Cannot read property '$mobx' of undefined at index.min.js:1`

**Comment by FredyC** [comment]
You need to UMD bundle ... https://github.com/mobxjs/mobx#installation

**Comment by FredyC** [comment]
Alternatively for a better experience use CodeSandbox instead of Codepen. It will allow you to install a package directly without relying on UMD. Ultimately, it's much easier than looking for UMD url.
