### ISSUE TITLE
set function

### ISSUE THREAD

**Issue by roeycohen** [mobxjs/mobx#2245]
Hi, it's more of a thought...

in mobx 4, i understand why i need to use extendObservable when i want to add a new attribute to an object.

but why is it needed when using the "set" function? i'm already calling a "real" function, so why won't it do it for me?

also, from the docs it seems like set accepts an object so that i can change multiple values at once. should i use set if i have multiple values to set? can it replace the "action" decorator in some situations?

**Comment by urugator** [comment]
> why is it needed when using the "set" function

I think it could give user a false impression that "dynamic objects" are actually supported (in a sense that `reactions` accessing the field or iterating over object's properties are invalidated).
Usually whenever you need to call `extendObservable` multiple times on a same object, Map should be used instead.

> can it replace the "action" decorator in some situations?

Sort of. It does batch the updates:
https://github.com/mobxjs/mobx/blob/fd009da98770b76018a284d2f619968e440ec17a/src/api/object-api.ts#L98-L103
However `action` does more then batching (untracked, allows the use of enforceActions and other options)

**Comment by roeycohen** [comment]
@urugator I'm not sure how and why, but the set seems to do register new properties... am I missing something?

**Comment by urugator** [comment]
Seems it does:
https://github.com/mobxjs/mobx/blob/bf43367cd930a453af178ffcd236e0483bf876ee/src/v4/api/object-api.ts#L112
I haven't checked before, I was assuming it throws or something based on your description.
So is there any problem?

**Comment by urugator** [comment]
Ok here is the thing I wasn't aware of ... if you use exclusively object api for iterating over keys (no `for in`/`Object.entries/getOwnPropertyNames` etc), then it should correctly notify on key changes...

**Comment by roeycohen** [comment]
@urugator I'm also not really sure why I've assumed the "set" function does not introduce new properties...
the docs here say it does... https://mobx.js.org/refguide/object-api.html
weird 🤔
