### ISSUE TITLE
How to make class objects's attributes observable in MobX?

### ISSUE THREAD

**Issue by charanjit-singh** [mobxjs/mobx#2246]
I've a class as:

```
class Field{

  constructor(name) {
    this.name= name
    this.otherAttr = null
  }
  
  changeName(newName) {
    this.name = newName
  }
}


const f = new Field("Charanjit")
f.setName("Singh") // It shoukd reflect in observer 

f.name = "Rahul" // It should also reflect in observer


```

How to make `f` object observable such that any changes in `f`'s attributes, update the observer components.

Currently, I'm getting error: https://github.com/mobxjs/mobx/issues/1932 if I use:
```
@observable(f)
>>> It shows Error: https://github.com/mobxjs/mobx/issues/1932
```

**Comment by mweststrate** [comment]
This is well covered in the docs. See `@observable` / `extendObservable` / `decorate` or check out the free egghead tutorials
