### ISSUE TITLE
Feature request: @computed.shallow (or etc.)

### ISSUE THREAD

**Issue by iEchoic** [mobxjs/mobx#2247]
I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [x ] Idea:
  * [x] What problem would it solve for you?

More efficient re-computation of arrays and objects in @computed values.

  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?

Yes

  * [ ] Are you willing to (attempt) a PR yourself?

Yes

---

It'd be great to have a comparer (on the `@computed` decorator) - perhaps `@computed.shallow` - that simply does an equality comparison on the first level of children in an object and/or arrays.

We have a lot of `@computed` values that do some sorting/re-arrangement on arrays, or sometimes transform between arrays and objects. In these cases, default comparer is not ideal because `.sort` (or any other manipulation, really) produces new arrays, so the computed will always be seen as changed, and `@computed.struct` is not ideal because in the case where the order of the array changes, we will then attempt to do a value comparison on individual items, reducing the performance of the comparator.

For these computeds, we'd really only like to signal that the computed value has changed if the first level of items in the return object differs by strict equality.

It'd be something like (not optimized or considering edge cases, just throwing something down here):

```
(obj1, obj2) => Array.isArray(obj1) 
  ? obj1.every((item, idx) => item === obj2[idx]) 
  // just assume it's an object; bad assumption. Also doesn't check obj2 keys not present on obj1
  : Object.entries(obj1).every(([key, value], idx) => obj1[value] === obj2[value]);
```

Is there anything like this now? If not, would this be a welcome addition to mobx-utils and/or mobx core?

**Comment by iEchoic** [comment]
Looking into this I stumbled across some other issues and see that actually has been proposed before, so I'm going to close this. If anyone sees this, just count this as a vote/:plus1: for this feature :)

**Comment by urugator** [comment]
`@computed({ equals: comparer.shallow })`
