### ISSUE TITLE
[Problem]: Undefined is not an object - React-Native + Firebase

### ISSUE THREAD

**Issue by Jub1leu** [mobxjs/mobx#2251]
**When I emulate the following error occurs:**
undefined is not an object (evaluating 'new _reactNative.ListView.DataSource')

**Code:**

class PostsList extends Component {
    constructor(props) {
        super(props);
        this.state = {
            dataSource: new ListView.DataSource({
                rowHasChanged: (row1, row2) => row1 !== row2
            }),
        }
    }

    getDataSource(posts: Array<any>): ListView.DataSource {
        if(!posts) return;
        return this.state.dataSource.cloneWithRows(posts);
    }

    componentDidMount() {
        this.setState({dataSource: this.getDataSource(this.props.posts)});
    }

    componentWillReceiveProps(props) {
        this.setState({dataSource: this.getDataSource(props.posts)});
    }

    renderRow = (post) => {
        return (
            <View>
                <Text>{post.title}</Text>
                <Text>{post.content}</Text>
            </View>
        );
    }

    render() {
        return(
            <ListView
                dataSource={this.state.dataSource}
                renderRow={this.renderRow}
                enableEmptySections={true}
            />
        );
    }
} `

https://riptutorial.com/react-native/example/22000/react-native---listview-with-firebase

**Comment by mweststrate** [comment]
Why is this posted in this repository?

**Comment by FredyC** [comment]
I am closing unless some explanation is provided how is it related to MobX.
