### ISSUE TITLE
Mobx store failing to inject in enzyme for functional component, jest test

### ISSUE THREAD

**Issue by SVaeth** [mobxjs/mobx#2257]
When running our test with shallow, we get the following error:
`Error: Uncaught [TypeError: Cannot read property 'userStore' of undefined]`

This issue started happening when we were refactoring class components to functional components and was cause by the inject statement in our export. Something about inject and enzyme's shallow rendering violated the react hook principles.  Upon further research, we learned that MobX was moving away from inject and making hooks using contexts in functional components, and it worked in the application, but jest tests with enzyme still do not inject from the provider. 

We also read that we are supposed to use wrappedComponent, but this returns 
`TS2339: Property 'wrappedComponent' does not exist on type 'FunctionComponent<Props>'.`

Attached is a code sandbox of a sample project. Any advice moving forward is appreciated
https://codesandbox.io/s/cool-euclid-vonp0

**Comment by FredyC** [comment]
I don't see the error you are talking about, in the tests tab, there is this message only.

![image](https://user-images.githubusercontent.com/1096340/72413758-c63d6a80-3770-11ea-8715-5aa58d6aac66.png)

**Comment by SVaeth** [comment]
The code sandbox is a sample project for illustrating the environment in which the problem occurred. The error persists in IntelliJ on our environment, but we can't share that source code, so this is the best example we could provide.

I have no idea what's wrong with code sandbox's environment, but we're asking about a core issue we are having with mobx

**Comment by mweststrate** [comment]
I don't even see any inject in the code sandbox, please provide a _minimal_ reproduction that just demonstrates the setup issue.

**Comment by SVaeth** [comment]
This is a minimal reproduction. As was stated in the original post,

> upon further research, we learned that MobX was moving away from inject and making hooks using contexts in functional components, and it worked in the application, but jest tests with enzyme still do not inject from the provider.

There is no inject because per the mobx documentation we are migrating away from mobx. The new standard is to use context hooks to inject stores into components, but it is not working in the jest test when doing an enzyme shallow render

https://mobx-react.netlify.com/recipes-migration

**Comment by mweststrate** [comment]
Sorry, if this _not_ about inject, than I am afraid I don't understand what your issue is about :). 

Please provide a stacktrace and code pointers where the error occurs. A project + one liner exception is a bit too vague to dive into I'm afraid. " Something about ..." isn't actionable.

**Comment by FredyC** [comment]
If I am not mistaken, Enzyme does not support React Hooks out of the box, you need to configure the adapter as said in that picture above.

Please, be sure to read through https://stackoverflow.com/help/minimal-reproducible-example because it's apparent you don't know what minimal reproduction is ;)

If you have a problem with failing Enzyme test, provide simple test that runs very simple code and shows the actual error. If you don't want to "bother with that", then you have to help yourself.
