### ISSUE TITLE
autorun destruct handling

### ISSUE THREAD

**Issue by martinheidegger** [mobxjs/mobx#2258]
I have an idea that could solve a code cleanness issue _(and by extend might result in less bugs in userland)_.

What if `autorun` _(or a variant of it)_ would process eventually returned functions in the destruct process and before subsequent runs:

```javascript
const obj = observable({ foo: 'bar' })
const destruct = autorun(() => {
  console.log(`render ${obj.foo}`)
  return () => {
    console.log(`cleanup ${obj.foo}`)
  }
})
// render bar
obj.foo = 'baz'
// cleanup bar
// render baz
destruct()
// cleanup baz
```

As illustrated in the code, the first time `autorun` is called it would just process the code. The return function would be stored and executed _(if possible with the old model state, thought that might be difficult)_.

Right now I need to keep track manually if the method has run before and wrap the destruct mechanism with duplicate code. This makes working with autorun in my world a bit hard. This should be useful in a variety of use-cases as such I think it might be interesting to other users as well.

I am not sure if this can or should be implemented, I am not familiar with the repository but I would be willing to work on a PR with a little guidance.

**Comment by FredyC** [comment]
I don't exactly follow what is your reasoning here. The `autorun` is basically one-off that runs whenever the observable would change. If you would create some resource that needs to be cleaned up during that run, where do you keep it? Also, it would be prone to memory leaks. You never know how many times would reaction execute before you dispose it. Some of those created resources would be left hanging in there.

I don't think this is a job for MobX, I might be wrong though. Not sure if you are using React, but something similar should be possible in any sort of library/framework.

```js
React.useEffect(() => {
  // setup other resources
  const dispose = autorun(() => {
    // observe
  })
  return () => {
    dispose()
    // cleanup other resources
  }
})
```

That way you can be sure there are no memory leaks or weird behavior.

**Comment by mweststrate** [comment]
I think it is pretty easy to create your own abstraction for this with the existing primitives, and there is no reason to add it to the core is it doesn't look very common. So you could establish your own `autoRunOnceCleanup` around the above pattern as utility. Note that for one-off effects `when` is usually used. I'm curious what your actual use case is, as rendering is typically a repeating process?

**Comment by martinheidegger** [comment]
My actual use-case is to reinitialize the connection to the server when the specified (observable) config changes, a little bit like:

```javascript
useEffect(() =>
  autorun(() =>
    listenToChannel(config.channelId, handler) // listenToChannel returns a destructor as well
  )
)
```

in this case the channel listener would be added/removed every time the config of the channel has changes and every time the component is added/removed from the UI. (in other words: no lost listeners). 

> So you could establish your own `autoRunOnceCleanup` around the above pattern as utility.

I actually did that already, though I called it [`safeAutorun`](https://github.com/consento-org/mobile/blob/10981a0d641927c03df19787e737601b27c14080/src/util/safeAutorun.ts#L1-L18). It is in use in my main `mobx-keystone` app that uses a configuration [here](https://github.com/consento-org/mobile/blob/10981a0d641927c03df19787e737601b27c14080/src/model/Consento.ts#L189) to create a new subscription when the server address changes in [the config](https://github.com/consento-org/mobile/blob/10981a0d641927c03df19787e737601b27c14080/src/model/Consento.ts#L193).

My thinking was that this util/pattern might be useful in other cases as well: think UI listening such as [`BackHandler.addEventlistener()`](https://facebook.github.io/react-native/docs/backhandler#addeventlistener) which is why I thought it might have its place in mobx in general.

**Comment by FredyC** [comment]
Yea, I don't think we want to expand API layer for rare cases that can be tackled easily in user-land. I can also imagine it could lead to bad practices and abuse of `autorun` for something it's not meant for.

Your solution looks ok, so let's close it here.

**Comment by mweststrate** [comment]
I think if you set up the deps of useEffect here correctly, there is no
need for auto autorun here at all?

Op zo 19 jan. 2020 11:30 schreef Daniel K. <notifications@github.com>:

**Comment by martinheidegger** [comment]
I am not sure if I was able to make my case properly or not but I thank you anyways for the consideration.

**Comment by FredyC** [comment]
Yea, the "problem" is that it's your single case and over several years I am not aware of anybody asking for something similar. We won't be bloating API because it feels convenient for a single case really. I hope you can understand. If you can gather more people with similar cases then it's something for consideration.
