### ISSUE TITLE
runWithoutReaction function

### ISSUE THREAD

**Issue by sisp** [mobxjs/mobx#2259]
# Idea `runWithoutReaction`

## Background

I frequently need to test "what-if" scenarios, i.e. execute actions on the state, check the result, and undo the changes. In order to avoid changing the actual state that drives UI rendering for these tests, the changes are performed on a copy of the original state. Since creating a new clone for each "what-if" test is too expensive, I'm maintaining a copy of the state and whenever the original state changes, the same changes are applied to the copy.

Everything is fine except when the original state contains reactions that again execute actions on the state. When an action changes the original state which triggers a reaction, both the changes made by the action itself and the changes made by the reaction are applied to the copy, but a reaction is also triggered in the copy after the changes of the first action are applied. Specifically:

1. execute action on original state
1. apply changes made by 1. to copy
1. execute reaction triggered by 1. on original state
1. apply changes made by 3. to copy
1. execute reaction triggered by 2. on copy <-- _this is a problem_

When the reaction is _non-idempotent_, e.g. an action `inc() { this.n++ }`, the reaction is effectively applied twice to the copy which results in the original state and the copy to be out of sync.

The general feature is implemented as the [sandbox utility in `mobx-keystone`](https://mobx-keystone.js.org/sandboxes). For more details, see the [original discussion about this feature](https://github.com/xaviergonz/mobx-keystone/issues/73) and the [discussion about the divergence of the copy](https://github.com/xaviergonz/mobx-keystone/issues/96).

## Suggested solution

In order to keep a copy of the original state and the original state in sync, I believe reactions should _not_ be triggered in the copy while applying changes made in the original state to the copy. The reason is that the changes to the original state made by an action that was executed as part of a reaction are applied to the copy anyway.

I suggest to add a function `runWithoutReaction<R>(fn: () => R): R` which temporarily disables scheduling reactions.

I'd be happy to attempt a PR if there is positive feedback about this idea.

**Comment by urugator** [comment]
Just an idea, haven't tried, use at own risk
```javascript
configure({ 
  reactionScheduler: () => _getGlobalState().pendingReactions.splice(0),
})
```

**Comment by sisp** [comment]
@mweststrate I get your point and don't like using reactions for state updates either. Because of your comment, I gave things a second thought and actually found way to turn a reaction into a derivation.

About the state copy for testing "what-if" scenarios: I see your point that MobX has no concept of copy, but even with a tree-shaped state, how would you test what happens when a certain sequence of actions was executed, e.g. would a certain sequence of actions make some computed property true or false (imagine e.g. `isValid`). Now actions would need to be executed inside a computed property (e.g. in a clone if cloning is not too expensive).

Have you had this kind of problem before?
