### ISSUE TITLE
[5.15.3] Error "process is not defined" in production if `node` is set to `false` in webpack config

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx#2264]
If webpack doesn't mock `process` then it only replaces exact strings defined in `DefinePlugin` or `EnvironmentPlugin` etc, so `process.env.IGNORE_MOBX_MINIFY_WARNING` doesn't get replaced and causes a "process is not defined" error in production. This is the offending line.

https://github.com/mobxjs/mobx/blob/d5488a180a34701ed90c4a25ccecef3619a42ea8/src/v5/mobx.ts#L43

Workarounds on user's side for now are:
- roll back to 5.15.2
- add `IGNORE_MOBX_MINIFY_WARNING` to Define/Environment plugin in webpack config

**Comment by mweststrate** [comment]
should be be prefixed with a `typeof process !== "undefined"` indeed... I
think we should accepting these 'lets change MobX because it doesn't play
nicely with my specific setup' PRs..... :-/

**Comment by le0nik** [comment]
https://github.com/mobxjs/mobx/pull/2265
