### ISSUE TITLE
False warning message starting from version 5.15.3 (`you are running a minified build, but 'process.end.NODE_ENV'...`)

### ISSUE THREAD

**Issue by ranyitz** [mobxjs/mobx#2266]
* [x] Issue:
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

## The Problem

On version `mobx@5.15.3` the bundle `mobx.module.js` throws an error which is a false positive. It says that the bundler was not configured for production which in fact it was.

> [mobx] you are running a minified build, but 'process.end.NODE_ENV' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle

This is a degradation from `mobx@5.15.2` where there was no such message.

## Explanation

Digging into the build process of mobx i've found [this change](https://github.com/mobxjs/mobx/commit/582a51691ebdbb5b8cd628ee286919a6dafc480c#diff-ea1c4abd09127cfb80f898b2bf12b0a4R72) which did the following replacement

```diff
- process.env.NODE_ENV !== "production"
+ "development" !== "production"
``` 

https://github.com/mobxjs/mobx/blob/d5488a180a34701ed90c4a25ccecef3619a42ea8/src/v5/mobx.ts#L42

It makes mobx send this message in case the code passed minification regardless of the `process.env.NODE_ENV` that was used during build time. Sending a false message to the user.

## Possible Solution

While the replacement is good for optimizing production bundles, for development it is not critical. Removing [this line](https://github.com/mobxjs/mobx/commit/582a51691ebdbb5b8cd628ee286919a6dafc480c#diff-ea1c4abd09127cfb80f898b2bf12b0a4R72) should remove this warning. If we would like to optimize the development bundle we can later on see how we can do it without sending the false warning.

**Comment by FredyC** [comment]
Related to #2264

Thanks for the report. Can you please describe your environment?

This has happened mostly by accident when merging a code base (#2248). But the intention is actually good. The `process` should be present in `commonjs` builds at all.

That is true for `mobx.min.js` which a production build with correctly eliminated dead code. However, the `package.json` does not refer to this minified file. The correct fix I see here is to change that so a minified bundle is used by default.

**Comment by mweststrate** [comment]
@FredyC, see also my comment on the PR, using the .min. by default just exposes the opposite problem: getting minified code while devving that lacks the assertions that are especially build for dev I? I think we should stick to the old setup, where you get the 'dev' version by default, unless you configure your bundler to substitute for prod, and make sure nothing dies if there is no substitution at all

**Comment by FredyC** [comment]
Yea, I think we will go the way TSDX does, by exposing `index.js` which looks like this (plus safety checks with `typeof`).

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./mobx.min.js')
} else {
  module.exports = require('./mobx.js')
}
```

This way the correct bundle will be selected depending if you are developing or bundling for a production.

**Comment by ranyitz** [comment]
@FredyC We are using `webpack@4.28.4` for bundling.

The problem is in the [published file `mobx.module.js`](https://github.com/mobxjs/mobx/archive/5.15.3.tar.gz)

When opening its contents, you'll see that there is a `"development" !== "production"` condition which is always `true`. If you'll create two bundles (just like [react](https://github.com/facebook/react/blob/master/packages/react/npm/index.js)) it wont necessarily solve the problem above. I think that the [code that handles the `testCodeMinification` check](https://github.com/le0nik/mobx/blob/de5a3261ea124d5bfe4d2b5ef4a19d5ed6337fa2/src/v4/mobx.ts#L37) should leave the `process.env.NODE_ENV` for the bundler for the check to work properly instead of replacing it.

**Comment by FredyC** [comment]
Ah yes, you are right, module bundle should be left untouched because it is handled by the bundler. That's definitely a mistake I will fix.
