### ISSUE TITLE
add middleware mechanism to mobx actions

### ISSUE THREAD

**Issue by zilberman3k** [mobxjs/mobx#2269]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Documentation improvement. Please don't open an issue but create a PR instead!
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?

Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Please be sure to close your issues promptly.**

**Comment by FredyC** [comment]
Can you elaborate, please? The title is not enough.

**Comment by zilberman3k** [comment]
I would like to use the ability to use middleware while executing actions, so for example I can determine before execution should I execute it or not...
example :

I would like to prevent "@action updateUserData(data)" from running if user is logged out...

**Comment by FredyC** [comment]
Please show some examples, the term middleware can have various meaning so we need to see what exactly you have in mind.

Either way, if you don't want the action to be called, then don't call it :) I don't follow why would require anything special.

**Comment by zilberman3k** [comment]
I dont have specific code example, however, suppose I would like an automatic logout system after some time user perform any action on UserStore, I would like to have the ability to intercept action execution to provide additional logic scope such as clear the logout timer, or redirect to another functionality if time has passed... I saw mobx-state-tree has "addMiddleware" functionality

**Comment by FredyC** [comment]
Sorry, but that does sound like something that doesn't need to be in MobX, it's out of scope. If you want, use MST.

**Comment by mweststrate** [comment]
For a solution that doesn't need some fundamental change in MobX itself, you can create your own decorator that applies `action` and does some other useful stuff as well. In generally writing decorators is not very hard, although it differs a little pending you are using babel or TS

**Comment by zilberman3k** [comment]
Yep tnx!

בתאריך יום ד׳, 29 בינו׳ 2020, 13:35, מאת Michel Weststrate ‏<
notifications@github.com>:
