### ISSUE TITLE
actions a la flux

### ISSUE THREAD

**Issue by maxguzenski** [mobxjs/mobx#228]
Hi
I'm trying to figure out how to perform actions that change many stores. I have a UserModel, a PendingFriendStore, FriendStore and SessionStore and want to do something like that:

```javascript
function acceptFriend(user) {
  user.friend = true 
  pendingFriendStore.remove(user)
  friendStore.add(user)
  sessionStore.currentUser.friendCount++
  api.acceptFriend(user) // call backend
}
```

How can I do this? just have this method out site of any store or is there a better way?

**Comment by mweststrate** [comment]
Yeah a controller class sounds fine for this. 

Or if you like still apply the flux pattern; create a dispatcher and actions, where the dispatchers dispatches each action to all the stores (the [d3 demo project](https://github.com/mobxjs/react-particles-experiment/tree/mobx-flux) does this as well). But in my experience that is a little less flexible when the order of execution is important or when you need return values from store methods.

**Comment by maxguzenski** [comment]
I'm porting a medium size app from redux to mobx, dispatchers is exactly what I dont want ;) ... 
But has some methods in store, others in controller, others in model dosent look very good was well. 

I'll think about it a little more...

**Comment by mweststrate** [comment]
In large projects I usually keep the stores really dumb (just fetching,
submitting and storing) and have separate controllers with all logic, with
receive the relevant stories in their constructor.

Op za 30 apr. 2016 om 11:31 schreef Maximiliano Guzenski <
notifications@github.com>:

**Comment by maxguzenski** [comment]
Now I trying to do something like redux autoBind and redux-ducks, but without dispatcher.

```javascript
class BlockStore extends Page {
  constructor() {
    super('/blocks')
  }

  getItemFromJSON(userId) {
    return userStore.find(userId)
  }
}

export const unblockUser = stores => user => {
  user.blocked = false
  stores.blockStore.removeItem(user)
  return axios.delete(`/blocks/${user.id}`)
}

// on appStore.js

stores  = {blockStore: new BlockStore(), friendStore: new FriendStore()}
actions = {unblockUser: unblockUser(stores), acceptFriend: acceptFriend(stores)}

const appStore = {
  stores,
  ...actions
}
```

I think that this is ok.
