### ISSUE TITLE
Why obfuscating error messages?

### ISSUE THREAD

**Issue by M0ns1gn0r** [mobxjs/mobx#2280]
I don't understand the reason MobX outputs this message in production build:

> An invariant failed, however the error is obfuscated because this is an production build.

1. If this invariant is not a critical problem, just don't check it on production.
1. If this invariant is critical, don't hide the error from the user/developer. How else should one diagnose the problem?

Does an obfuscated error bring any benefit?

**Comment by mweststrate** [comment]
bundle size. it probably means we cannot not throw, as the behavior is
undefined / different than what it would be in Dev. So it means you missed
an important code path in your dev testing. If you load the exception with
the corresponding source maps (most bug tracking tools can do this), it
should still be quite easy to figure out which one you hit by looking at
the stack.

**Comment by FredyC** [comment]
You could essentially decide to use DEV bundle of mobx in production. I doubt it would be too much slower if you don't care about bundle size much. Most decision paths are about verbose dev checks, but it's far from React style where performance can differ vastly.

**Comment by M0ns1gn0r** [comment]
> we cannot not throw, as the behavior is undefined / different than what it would be in Dev
If the bundle size is the main reason for such behavior, maybe at least show an error code to indicate which error has happened?

> You could essentially decide to use DEV bundle of mobx in production. 
The problem is, I will have to re-defined the "global" `process.env.NODE_ENV` for that. This will also influence how other modules are built, including the "react" itself. Or do I miss an option to do that for MobX only?

**Comment by mweststrate** [comment]
> If the bundle size is the main reason for such behavior, maybe at least show an error code to indicate which error has happened?

Ideas / PRs are welcome :)

**Comment by Maaartinus** [comment]
Possibly a stupid idea: Externalize all error texts as if they were subject to i18n.
- in dev mode, do the "translation"
- in production, show the error code (=translation key) and a link to the translation file

**Comment by FredyC** [comment]
@mweststrate The idea from @Maaartinus might be worth including in V6, what do you think? Otherwise, close this if it's not worth the effort for now.

**Comment by mweststrate** [comment]
@FredyC good point, I'll add the same mechanism as in immer, where at least a unique code per error is preserved. Note that some errors will still not occur in production if the checks themselves are expensive at runtime.

**Comment by lachenmayer** [comment]
Hi there, I'd like to add my support for this proposal as well! We are currently being hit hard by this as I am trying to debug React Native crashes that are only happening in production builds, which throw this error and not much else to go by.

An error code would be super useful, so I think that's a great idea.

For what it's worth, we aren't really concerned with bundle sizes as this is a mobile app and still in beta, so some way of running MobX in "dev mode" (without affecting the rest of our build) while we're still trying to smooth out rough edges would also be great - appreciate that that might be a bit more difficult though.

Thanks a lot! :)

**Comment by mweststrate** [comment]
In V6 error codes will be thrown instead, so this is being planned
