### ISSUE TITLE
Getting Started - Cannot run demo code

### ISSUE THREAD

**Issue by berrybell** [mobxjs/mobx#2282]
I have a:
2. [x] Issue: 

Whenever I am trying to run any code on the [https://mobx.js.org/getting-started](Getting Started) page I am greeted by `Code editors not yet loaded` message in the `console.log` section.

I see the following error messages in my console:
```
Failed loading 'https://mobx.js.org/assets/getting-started-assets/javascripts/codemirror/lib/codemirror.js'.
ReferenceError: CodeMirror is not defined
```

**Comment by mweststrate** [comment]
Fix has been published. Thanks for reporting, and @lgordey thanks for the fix!
