### ISSUE TITLE
@observable + class property assignment causes constructor not to get called until access

### ISSUE THREAD

**Issue by bsmith-cycorp** [mobxjs/mobx#2290]
I have a situation like this:
```javascript
class Thing {
  constructor() {
    fetch(...)
  }
}

class Store {
  @observable myThing = new Thing();
}
```

**Intended outcome:**
Each time a Store is constructed, `Thing`'s constructor gets called as part of that process. i.e., the above is equivalent to:
```javascript
class Store {
  @observable myThing;

  constructor() {
    this.myThing = new Thing();
  }
}
```

**Actual outcome:**
`Thing`'s constructor does not get called in the course of `Store`'s constructor. Removing `@observable` prevents the issue, as does moving the assignment into the "real" constructor.

As best I can tell, `Thing`'s constructor gets called the first time `Store.myThing` gets accessed, or something like that. This is weird in such a way that I don't think it would result from the Babel side of things, and anyway, the relevant part of my `.babelrc` matches the Babel docs (https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties):
```json
"plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    ...
]
```

**How to reproduce the issue:**
[see above]

**Versions**
```json
"mobx": "^5.0.3",
"mobx-react": "^5.2.3",
"mobx-utils": "^5.0.3",
"@babel/core": "^7.0.0",
"@babel/plugin-proposal-class-properties": "^7.0.0",
"@babel/plugin-proposal-decorators": "^7.0.0",
```

I did see mention of a similar quirk here, in the MobX docs: https://mobx.js.org/best/decorators.html#disclamer-limitations-of-decorator-syntax

> Decorated properties might not be visible yet on class instances as own property until the first read / write to that property occurred.

I'm not sure precisely what "own property" means, so I'm not sure whether this is the same issue, a different one, or a related one.

**Comment by mweststrate** [comment]
Yes, this is known limitation of the babel decorator implementation (TS doesn't suffer from it). You might be able to work around it by using the `decorate` utility, call `extendObservable` in the constructor, or just move the field initialisation to the constructor. 

In the next major version we will address this, but it most probably will require code changes as well, for some background see #2288

**Comment by bsmith-cycorp** [comment]
> TS doesn't suffer from it

We are using TypeScript, though through the Babel plugin instead of tsc. This may be getting out of scope, but do you know if it's possible to switch over and have TypeScript handle decorators in that context?

**Comment by mweststrate** [comment]
sure, compile with typescript (tsc) first, then pass it through babel :).
Probably depends on your setup how to do that. For example with webpack you
will probably add ts-loader, rather and remove the babel-typescript preset.
But probably moving the assignment in the specific cases where it is an
issue is an less obtrusive solution

**Comment by bsmith-cycorp** [comment]
What I ended up doing in our case was to just remove `@observable` on the `Thing` instances (and add `readonly`, in fact), since the class handles its own inner observables and the instances of it will never get re-instantiated

**Comment by mweststrate** [comment]
readonly > @observable, so that sounds like a neat solution in this
specific case 😊

Op ma 17 feb. 2020 22:36 schreef bsmith-cycorp <notifications@github.com>:

**Comment by mweststrate** [comment]
This will be fixed in v6

Op za 18 apr. 2020 23:18 schreef lock[bot] <notifications@github.com>:
