### ISSUE TITLE
Values with prototypes

### ISSUE THREAD

**Issue by thepian** [mobxjs/mobx#2299]
**Intended outcome:**

```
class State {
@observable dashboard:
@computed get widget() { return dashboard.widget; }
}

state.dashboard = { widget: makeWidget() };

function makeWidget() {
return Object.assign(Object.create({ x: 'default', y: 'default' }), { title: '' });
}
```

I would not expect `dashboard.widget.x` to be "default"

**Actual outcome:**

I would not expect `dashboard.widget.x` to be "default", but it is undefined as the prototype is thrown away.

**How to reproduce the issue:**

https://codesandbox.io/s/nice-khorana-lwnxu

**Comment by FredyC** [comment]
Would this work for you? https://codesandbox.io/s/angry-ptolemy-yiu6e

**Comment by thepian** [comment]
Interesting it seems to work. We must be doing something wrong elsewhere in our codebase.
