### ISSUE TITLE
The right way to pass a store to components tree?

### ISSUE THREAD

**Issue by smirnovshina** [mobxjs/mobx#230]
Is there the right and simple way to pass a store to components tree like with react-redux's `Provider` and `connect`? It seems that the kind of functionality should be in mobx-react but there isn't.

**Comment by mweststrate** [comment]
See mobx-connect or react-tunnel

Op ma 2 mei 2016 om 14:23 schreef Sergey Smirnov <notifications@github.com>:

**Comment by smirnovshina** [comment]
@mweststrate I have tried those. react-tunnel seems to not support stateless functions (I got an error) and the module itself not supported by the author. mobx-connect is similar to react-redux but more verbose.

What method do you use or the right way to pass a store? It seems it is quite common functionality passing a store to components. Do you plan include this functionality to modx-react, for example delegate `connect` functionality to `@observer` and add `Provider` like component?

**Comment by AriaFallah** [comment]
@smirnovshina why don't you just pass the store as a prop? That's how every other library does it behind the scenes anyways unless they're using context, which is the same concept regardless. The only reason that a library like redux needs provider and connect is because it has a very rigid structure that you have to follow.

With MobX you shouldn't need another library to pass down your store...just pass it down. That's what I think anyways.

**Comment by mweststrate** [comment]
I tend to agree with @AriaFallah. But people ask on a regular basis for a connector. So the question is should `mobx-react` maybe provide some standard approach / HoC for working with context? And if so, what should it look like? considering there can be multiple stores in MobX etc.

**Comment by mattruby** [comment]
I'm all about passing it down via props.  However, I do get the argument
for context.  At times, I'll have a "smart" component hotwire the works to
grab a store out of the ether.

On Mon, May 2, 2016 at 10:22 AM, Michel Weststrate <notifications@github.com
> wrote:

> I tend to agree with @AriaFallah <https://github.com/AriaFallah>. But
> people ask on a regular basis for a connector. So the question is should
> mobx-react maybe provide some standard approach / HoC for working with
> context? And if so, what should it look like? considering there can be
> multiple stores in MobX etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mobxjs/mobx/issues/230#issuecomment-216265825>
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by luisherranz** [comment]
What about [recompose](https://github.com/acdlite/recompose) mapProps method?

```javascript
// MyComponent.jsx
import someStore from '../stores/someStore';
import otherStore from '../stores/otherStore';

export const MyComponent = ({someProp, otherProp}) => (
  <div>..{someProp}..{otherProp}..</div>
);

export default mapProps(() => ({ 
  someProp: someStore.someProp,
  otherProp: otherStore.nested.otherProp,
}))(MyComponent);
```

**Comment by AriaFallah** [comment]
@mweststrate for the multiple stores problem I keep all my stores in one central store using [mobx-store](https://github.com/AriaFallah/mobx-store). I haven't built anything large or "real world" yet with it though so I think I still need to see if the store of stores idea holds up.

I think it will though considering redux kind of does the same thing.

**Comment by maxguzenski** [comment]
I made a simple Provider and a very simple connect

my store
```javascript
import {observable, computed} from "mobx"

export default class SessionStore {
  @observable user  = null;
  @observable token = null;
  @observable updatingUser = false;
}

export const actions = {}

actions.setCurrentUserFromServer = stores => json => {
  const user = stores.userStore.createOrUpdate(json)
  stores.sessionStore.user = user
}

actions.updateSessionUser = stores => user => {
  //code
}
```

and on store index.js
```javascript
import UserStore, {actions as userActions} from './userStore'
import SessionStore, {actions as sessionActions} from './sessionStore'

const store = {
  sessionStore: new SessionStore()
  userStore: new UserStore()
}

const actions = {
  ...userAction, ...sessionActions
}

forOwn(actions, (v, k) => ( actions[k] = (...params) => transaction(v(store)(...params)) ))
export {store, actions}
```

a simple Provider: 
```javascript
class Provider extends React.Component {
  static childContextTypes = {
    store: React.PropTypes.object,
    actions: React.PropTypes.object
  };

  getChildContext() {
    return {
      store: this.props.store, actions: this.props.actions
    }
  }

  render() {
    return React.Children.only(this.props.children)
  }
}
```

and a very simple connect
```javascript
const connect = Component => {
  const displayName = `Connect(${getDisplayName(Component)})`
  const ObservedComponent = observer(Component)

  return class WrappedComponent extends React.Component {
    static displayName = displayName;

    static contextTypes = {
      store: PropTypes.object,
      actions: PropTypes.object
    };

    shouldComponentUpdate(nextProps, nextStats) {
      return shallowEqual(nextProps, this.props)
    }

    render() {
      return <ObservedComponent {...this.props} {...this.context} />
    }
  }
}
```

Now I just use "connect" on everyplace and the component receive store (with all stores) and actions (with all actions). Dont need to filter anything.

```javascript
export default connect(MyComponent)
```

**Comment by AriaFallah** [comment]
@maxguzenski I'm curious, what's the benefit of doing it this way over just passing it down with props?

**Comment by maxguzenski** [comment]
@AriaFallah Component can "connect" with stores and actions and use what it want... parent dont need to now everything about its children. If a component want to use something new, just use it, without has to change every component that call this one.

**Comment by maxguzenski** [comment]
@AriaFallah this is like Replay works, just pass down the minimum that components need to know from its parent, and let component find/load/call everything else.

**Comment by luisrudge** [comment]
Sorry if this is a dumb question, but why go through all those hoops?
This is working just fine for me:

```js
//Store.ts
import {observable} from 'mobx';

class Store {
    @observable foo: string;

    setFoo() {
        this.foo = 'test';
    }
}

const store = new Store();
export default store;


//ShowFoo.tsx
import Store from './Store';

@observer
export default class ShowFoo extends React.Component<{}, {}> {
  componentDidMount() {
    Store.setFoo();
  }
  render() {
    return (
      <div>{Store.foo}</div>
    );
  }
}
```

**Comment by maxguzenski** [comment]
@luisrudge Yes, You could do that. 

But if you want Isomorphic javascript (render on server) that will not work, because you Store is a singleton, and server'll use it to all request, from all users.

ps.: My example was a singleton as well, I updated it.

**Comment by luisrudge** [comment]
Good to know, thanks!

**Comment by smirnovshina** [comment]
Thank you all for answers, situation became clearer. "react-connect" do the job well, but maybe there is no need to use it and just pass a store through props. Most likely people just need to revise some "Redux habits". 😉 Nevertheless it would be great if there were more "best practices" written: now to structure the app, how to solve some common cases, etc...

**Comment by jefffriesen** [comment]
For other folks coming to this thread, `Provider` was released with mobx-react: https://github.com/mobxjs/mobx-react#provider-and-inject

**Comment by dcworldwide** [comment]
Is there an example with Provider in use? I'm having some issues getting it working with my use case.

**Comment by mattruby** [comment]
Here's a small example:
https://jsfiddle.net/gh/get/library/pure/mattruby/mobx-examples/tree/master/react-examples/20-provider
