### ISSUE TITLE
Make observable(..) monadic

### ISSUE THREAD

**Issue by dslmeinte** [mobxjs/mobx#2300]
Observing values computed from observables is doable, but a bit tedious since you have to wrap things in `computed`, and use `mobx-utils/createTransformer` to make it work well. It seems `observable(..)` is already quite close to being monadic. 

Would it be an idea to extend the API of observables with `map` and `fmap` methods which allow to perform functions on the underlying observable, returning a computed (and possibly memoised) value that's again observable?

**Comment by spion** [comment]
You can use https://github.com/mobxjs/mobx-utils#tostream

**Comment by dslmeinte** [comment]
Thanks @spion! I think your suggestion fits my use case even better than making Observable monadic :) Nevertheless: might that be something worth considering?

**Comment by dslmeinte** [comment]
Btw @spion: that particular piece of example code doesn't actually work. Maybe RxJS has changed a bit? `Rx.Observable.from` doesn't exist anymore and `Rx.from` seems to do something else.

**Comment by FredyC** [comment]
I guess this goes beyond MobX now, so closing.
