### ISSUE TITLE
ReferenceError:Can't find variable:mobx

### ISSUE THREAD

**Issue by ektasahu027** [mobxjs/mobx#2304]
I am getting error which is Can't find varible :mobx

![Screenshot_2020-03-06-14-19-43](https://user-images.githubusercontent.com/41745899/76067971-513f2200-5fb6-11ea-8ff0-74a86132f1e8.png)

Here is packages version : 

"mobx": "^5.15.4",
    "mobx-react": "^6.1.8",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "pusher-js": "^5.1.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",`

**Comment by FredyC** [comment]
I know that reproducing issues with React Native is a pain, but without some actual code snippets, it's hard to tell where is your problem.

**Comment by ektasahu027** [comment]
@FredyC  You may suggest that how can I find this issues actually I am trying to update Expo project and there are many places where these two module mobx and mobx-react are used.

**Comment by FredyC** [comment]
So you just updated mobx version? What version you have used before in that case?

**Comment by ektasahu027** [comment]
@FredyC Here is the old version:

` "mobx": "^4.3.1",
      "mobx-react": "^5.1.0",
      "moment": "^2.23.0",
      "pusher-js": "^4.3.1",
      "react": "16.5.0",
      "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",`

**Comment by FredyC** [comment]
Try to isolate some small portion of the app, comment out things that are not necessary for the app to start and where mobx is used.

**Comment by mweststrate** [comment]
did you try nuking your node_modules? This sounds like something pretty low
level being wrong with your project.

**Comment by ektasahu027** [comment]
@mweststrate but I am using all updated as well as supported versions.

Here are the packages let me know if you find any low level package which may caused error:

`"@expo/vector-icons": "^10.0.6",
    "@react-native-community/masked-view": "^0.1.5",
    "@react-native-community/netinfo": "4.6.0",
    "autobind-decorator": "^2.4.0",
    "buffer": "^5.4.3",
    "crypto-js": "3.1.9-1",
    "decorate-component-with-props": "^1.1.0",
    "expo": "~36.0.0",
    "expokit": "^36.0.1",
    "gl-react": "^4.0.1",
    "gl-react-expo": "^4.0.1",
    "lodash": "^4.17.15",
    "mobx": "^5.15.4",
    "mobx-react": "^6.1.8",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "pusher-js": "^5.1.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-callkit": "^1.3.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.2.7",
    "react-native-fullwidth-image": "^0.1.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-infinite-scroll": "^1.0.6",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-maps-super-cluster": "^1.6.0",
    "react-native-modal-selector": "^1.1.5",
    "react-native-onesignal": "^3.6.5",
    "react-native-picker-select": "^6.5.1",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-read-more-text": "^1.1.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-svg": "^9.13.3",
    "react-native-swipeable-row": "^0.8.1",
    "react-native-tabs": "^1.0.9",
    "react-native-twilio-programmable-voice": "^3.21.3",
    "react-native-unimodules": "^0.7.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.2.2",
    "react-navigation-drawer": "^2.4.2",
    "react-navigation-stack": "^2.2.3",
    "react-navigation-tabs": "^2.8.2",
    "striptags": "^3.1.1"`

**Comment by FredyC** [comment]
@ektasahu027 Doesn't matter, do try to delete node_modules folder and NPM/Yarn install for fresh.

**Comment by ektasahu027** [comment]
It's working now actually there is one file where modx word randomly typed. 

thank you All.
