### ISSUE TITLE
TypeError:(0,_mobx.useStrict) is not a function

### ISSUE THREAD

**Issue by ektasahu027** [mobxjs/mobx#2305]
![Screenshot_2020-03-06-16-21-58](https://user-images.githubusercontent.com/41745899/76078895-97ea4780-5fc9-11ea-8f19-871d1184d470.png)

I am getting this error when I tried to use mobx module in Expo project

```
 "mobx": "^5.15.4",
"mobx-react": "^6.1.8",
"moment": "^2.24.0",
"prop-types": "^15.7.2",
"pusher-js": "^5.1.1",
"react": "~16.9.0",
"react-dom": "~16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
```

**Comment by mweststrate** [comment]
useStrict was dropped a long time ago:
https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by mweststrate** [comment]
`useStrict` was removed a long time ago. Please read changelogs when bumping majors. https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#breaking-changes-1
