### ISSUE TITLE
Mobx 5+ requires Proxy and Symbol objects.

### ISSUE THREAD

**Issue by dajun1** [mobxjs/mobx#2315]
Does react native version 0.61.2 not support mobx version 5+？
What's the solution, please。

**Comment by FredyC** [comment]
From the readme ...

![image](https://user-images.githubusercontent.com/1096340/77232596-50a3af80-6ba2-11ea-829f-25042eaea95d.png)

Does that answer your question?

**Comment by mweststrate** [comment]
Update: Hermes is currently working on proxy support, so for RN on Android that might be a solution as well :)
