### ISSUE TITLE
have a plain object as the value of a mobx map?

### ISSUE THREAD

**Issue by aitchnyu** [mobxjs/mobx#232]
I did:

```
sf.values.set('meow',{})
sf.values.get('meow')
Object {$mobx: Object}
```
I expected this for last output:

`Object {}`

How do I have a plain object as the value of a mobx map?

Thank you for making the replacement for difficult to understand models and error-prone GUI updates!

**Comment by AriaFallah** [comment]
@aitchnyu it is a plain object, but when you added it to the MobX map it was transformed into an observable value. It'll behave the same as a regular object, but now it's an observable value.

https://github.com/mobxjs/mobx/blob/master/src/types/observablevalue.ts

**Comment by mweststrate** [comment]
Note that if you are in the rare situation that the values you assign to the map should not become observable, you can use [modifiers](http://mobxjs.github.io/mobx/refguide/modifiers.html) to prevent this default behavior. But in normal situations you shouldn't need this.

**Comment by jjvattamattom** [comment]
Thanks for resolving my query! I had a react component which didnt work with an observable object, so I had to convert it to JS. However I will try again since it'll behave the same as a regular object, to quote @AriaFallah.

**Comment by mweststrate** [comment]
closing this issue as it seems resolved. @jjvattamattom if your issue is still there, feel free to open a new one :)
