### ISSUE TITLE
Run MobX 4 on ES5 environment got ReferenceError: identifier 'Set' undefined

### ISSUE THREAD

**Issue by littlesome** [mobxjs/mobx#2323]
Since 4.9.0 https://cdnjs.cloudflare.com/ajax/libs/mobx/4.9.0/mobx.js
there's a `isES6Set` function references ES6's `Set` 
which will cause a ReferenceError: identifier 'Set' undefined

```
function isES6Set$$1(thing) {
    return thing instanceof Set;
}
```

**Comment by FredyC** [comment]
Yes, it needs to be polyfilled, you can use eg. http://polyfill.io/

**Comment by littlesome** [comment]
@FredyC  Ok,  thanks for your quick response :)
