### ISSUE TITLE
Cycle detected in computation with keyword 'super'

### ISSUE THREAD

**Issue by khusamov** [mobxjs/mobx#2328]
How do I fix a bug?

https://codesandbox.io/s/cycle-detected-in-computation-with-keyword-super-nq5tg

```typescript
import {computed} from "mobx";

class Model {
  @computed get asObject() {
    return {
      type: 'Model'
    }
  }
}

class Construction extends Model {
  @computed get asObject() {
    return {
      ...super.asObject,
      type: 'Construction'
    }
  }
}

console.log(new Construction().asObject) // Cycle detected
```

**Comment by mweststrate** [comment]
You can't override a computed property. Factor out the logic to a function,
access that from the computed, and override the function instead.

**Comment by FredyC** [comment]
@khusamov Did that answer your question? Closing and feel free to post a followup.
