### ISSUE TITLE
Proposal: Change type IObjectWillChange to generic

### ISSUE THREAD

**Issue by inoyakaigor** [mobxjs/mobx#2330]
Now the type `IObjectWillChange` is just union type of two type which both contains a field `object`:
```typescript
export declare type IObjectWillChange = {
    object: any;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
} | {
    object: any;
    type: "remove";
    name: PropertyKey;
}
```
If I understand correctly the `object` is just instance of current store:
![image](https://user-images.githubusercontent.com/1235286/79454628-3c619f80-7ff4-11ea-9532-a20f20995d1b.png)

So I propose a small change to this type: make `IObjectWillChange` the generic type:
```typescript
export declare type IObjectWillChange<T = any> = {
    object: T;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
} | {
    object: T;
    type: "remove";
    name: PropertyKey;
}
```
**Pros:**
1️⃣ Stronger default typings
2️⃣ Autocomplete
3️⃣ Backward compatibility
4️⃣ Provide an possibility make stronger typings in other places

**Cons:**
I don't see it

If this change is ok I can make an PR but point me what should be modified also?

**How I see using this:**
```typescript
type UserStoreObservables = {
    firstName: string
    lastName: string
}

type UserStore = UserStoreObservables & {
    getFullname: () => string
}

class UserStore implements UserStore {
    @observable firstName = ''
    @observable lastName = ''
    constructor() {
        intercept(this, (change: IObjectWillChange<UserStoreObservables>) => {
            // … do some stuff
        })
    }

    getFullname = () => this.firstName + '' + this.lastName
}

```

**Comment by FredyC** [comment]
I think it's fairly safe change, so feel free to go ahead with PR.
