### ISSUE TITLE
Actions do not throw error when given same name and different function reference

### ISSUE THREAD

**Issue by Spanoudakhs** [mobxjs/mobx#2331]
I thought that this :
```javascript
action("name", () => 1);
action("name", () => 2);
```
would throw an error , but it doesn't . Why mobX allows that ? I can only see confusion arising from that when debugging or when trying to implement undo/redo functionality .

**Comment by FredyC** [comment]
Well, since the `name` is for debugging only, it's up to you what you type there. Having some dev-only check for uniqueness could be useful. Are you willing to work on the PR?

**Comment by Spanoudakhs** [comment]
I want to be honest with you , I just googled to find out what a pull request is . I really have no clue  how to do that . I will find out on my own and then do it (do not waste your time trying to show to me how to do it) . My issue is that maybe my way of doing it , is not the best . 

Also we have to think of other cases like not providing a name at all . I think that should not be allowed anymore at least for a newer version with breaking changes .

**Comment by FredyC** [comment]
I recommend you going with https://gitpod.io/#https://github.com/mobxjs/mobx. It will start a full code editor with tests and everything running for development and you can create PR from there.

> Also we have to think of other cases like not providing a name at all . I think that should not be allowed anymore at least for a newer version with breaking changes .

Let's not get tool wild. Many people don't like naming actions mainly because it's not possible to compile that away from production. Definitely not a good idea to make it a requirement.

**Comment by mweststrate** [comment]
They get even generated in many cases, so sounds like a bad idea to
generalize to me as well :)

**Comment by Spanoudakhs** [comment]
@FredyC 
> Many people don't like naming actions mainly because it's not possible to compile that away from production.
What issues is this causing ?

**Comment by Spanoudakhs** [comment]
@mweststrate 
>They get even generated in many cases

What do you mean by generated ? You mean those actions that run asynchronously ?

**Comment by FredyC** [comment]
> > Many people don't like naming actions mainly because it's not possible to compile that away from production.
> 
> What issues is this causing ?

Strings cannot be minified so it will increase bundle size with something that's for development only. Sure, it can be minimal, but still, it's a good enough reason for not enforcing it. All development tools should always be optional.

**Comment by mweststrate** [comment]
The string is only a debug utility and we aren't attaching any further semantics on it, if you want to quote hamlet in it, that is fine. The names are by default inferred from the function names, which is a great default but doesn't prevent duplicates. In other cases there are higher level abstractions that create actions behind the scenes (MST is an example of that, but I bet there are many more proprietary ones). So we are not going to impose such radical instructions. If you want to make sure they are unique, you can create your own `action` that wrap mobx's action utility and keep track of the names, or write a lint rule.
