### ISSUE TITLE
decorate(class) with private typescript fields. 

### ISSUE THREAD

**Issue by seivan** [mobxjs/mobx#2339]
This might actually be resolved by `Mobx 6` in which case, feel free to close, though it is an issue for those who will be using older versions, as there is no documented away around this. 

Now I am aware that `private` is just a compile time access modifier, and not runtime (as opposed to the new `#field` syntax introduces in the new ECMA standard.

But how would one decorate the private field in this setup? 

```ts
class TodoStore {
  private _todos: Array<Todo>
  //constructor. 
}

decorate(TodoStore, {
  _todos: observable
})
```

A possible use case is private backed observables, exposed by public computed getters.

**Comment by seivan** [comment]
@FredyC 

One approach is 
```ts
decorate(TodoStore, {
  _todos: observable,
} as any)
```

But I find that too dangerous. 
I wonder if it makes sense to add a second argument to `decorate` for additional `fields` that is untyped?

**Comment by mweststrate** [comment]
This will solved by v6 indeed where this is done from the constructor

**Comment by seivan** [comment]
@mweststrate Actually I am not that sure... 
If you want static typing, you're going to have to define the decorations as 
```ts
[P in keyof T]?: MethodDecorator | PropertyDecorator | Array<MethodDecorator> | Array<PropertyDecorator>;
```

And as far as I know `keyof T` does not expose private fields. 
I have a workaround that might be interesting for `Mobx 6` - assuming I'm correct here about the issue.

**Comment by mweststrate** [comment]
this.x is typed if x is a private, so I expect `keyof typeof this` to be
typed likewise. Didn't test it, but feel free to add a test to the V6 branch

**Comment by seivan** [comment]
@mweststrate 
I just tested this 

```ts
type CollectFields<T> = {[P in keyof T]: T[P]}

class TryToGetThis {
  private first: number
  second: string 

  constructor(){
    this.first = 5
    this.second = "2"
    const onThisDirectly: CollectFields<this> = {first: 2, second: ""}

    let self = this 
    const onTypeOfThis: CollectFields<typeof self> = {first: 2, second: ""}
  }
}
```

Neither approach worked. But maybe I misunderstood what you meant with `keyof typeof this`

**Comment by seivan** [comment]
Anyway my solution for allowing private fields while still retaining as much static typing as I can with `decorate()` outside the class is this 

```ts
type MobxDecoratorTypes = MethodDecorator | PropertyDecorator | Array<MethodDecorator> | Array<PropertyDecorator>
function decorate<T>(clazz: 
  new (...args: any[]) => T, 
  decorators: {
      [P in keyof T]?: MobxDecoratorTypes
  } & {_privateFields?: { [key: string]: MobxDecoratorTypes} }): void {
    
    const {_privateFields, ...rest} = decorators
    console.log(_privateFields)
    console.log({...rest, ..._privateFields})
    mobx_decorate(clazz, {...rest, ..._privateFields} )
  }
```

used: 
```ts
decorate(TodoStore, {
  todos: computed, 
  remaining: computed,
  insert: action,
  remove: action,
  _privateFields: {
    _todos: observable
  }
})
```

Could technically make a second argument, but I quite like this, though it feels like a hack since it shouldn't be needed.

**Comment by mweststrate** [comment]
Yeah doesn't work indeed, bummer. I think for privates in that case I'd
simply recommend to put `// @ts-ignore` above the member, which is more
straightforward than complicating the API and still ending up with
something untyped. Or use protected, they are in practice usually the same
anyway.

https://www.typescriptlang.org/v2/en/play?#code/AQMwrgdgxgLglgewsAtgQwNYFMDyAjAZywCcA3NPAGywB4AVYLADxiwgBMDh8ArLWAHwAKAFDBxwGGmIBzLDABcwOgBoxE9vwTE0MbQSUAFafDSUaAJS3F2NbAE8EIZSuAEYxOBBkCBIgJTAAN7q4sTyYMTIEGCUlMBoXGgQ9gDcIgC+IiJQlIlcdMT2dAgA4vJ0ABZwXCHiAA6e5KygcMTuSjEoeCTqjQissFjswP2KwF09xMAAvMAAzOpEUEjsSu6e3sDZ4isQG2Cw2kL+dRIw1QQAdCBt7rPAAKyhkpdXy6sPAEQATF8v6Gw+CIZAo1CEFxqrjOEgkHw4Si+rHcXzUsNhAHoMcAAAIwAgAWjgMgg2iwbjQ7Eo9gmWGGw1A2lGTV05NuWEonBesNu7XGXwQhBI5CoWFR3IkY0RyJg-1hGX86iyGSAA

**Comment by seivan** [comment]
> . Or use protected, they are in practice usually the same
anyway.

Right, but `protected` isn't exposed as part of `keyof this`, but maybe I am doing it wrong? 

>  I think for privates in that case I'd
simply recommend to put `// @ts-ignore

I disagree, it's not intuitive and  vs having the editor pop up `_privateFields: ` to give you a hint and offer you an exit hatch. 
It's more self descriptive to, and it's one less thing to document not to mention there is a risk you'd end up missing it in the docs. 

>  than complicating the API and still ending up with
something untyped.

Neither approaches (second argument or `_privateFields`) changes the API at all. 

1.  Using `& {_privateFields?: { [key: string]: MobxDecoratorTypes} }` you don't have to actually do anything other than internal change for ` {...rest, ..._privateFields}`

2. Using a second optional argument would not changing any user interfacing API either. 

I tested both for `decorate()` and looking at Mobx 6 PR, I suspect it's the same changes.

**Comment by mweststrate** [comment]
Thanks for the idea, but I prefer to keep things technically simple for now. I am not sure how often this case will occur, and we can easily add it in a later release.

**Comment by seivan** [comment]
@mweststrate No it doesn't. But I am thinking you mean with 
`        // @ts-ignore sadly needed for private fields`? 

`autoObservable will pick up on privates just fine` Are you sure about this? If the library is using `keyof T` still loop to traverse over fields in a class, it will miss out on it, doesn't matter if it's using `this` or not. I think we both tested this and came to the same conclusion, so an escape hatch to offer *specific* private fields instead of all fields manually would be appreciated. 

I am not sure if it's fair to take into account on how "often it happens" when using access modifiers is one of the fundamental features of Typescript to limit exposed methods and fields.

**Comment by mweststrate** [comment]
Typescript nor keyof exist at runtime, the runtime implementation is totally unrelated to what is put in the typings, they are just fancy comments at the end of the day.

**Comment by seivan** [comment]
Just to reiterate. 
> Concerning protected, that works fine, see my previously linked playground snippet.

No it doesn't. Your link just added an `//ts ignore` to it, as opposed to letting the compiler/editor/autocomplete offer a self-documented designated zone to put them in. 

```
Argument of type '{ second: "test"; prot: "test"; }' is not assignable to parameter of type 'Partial<Record<keyof this, string>>'.
  Object literal may only specify known properties, and 'prot' does not exist in type 'Partial<Record<keyof this, string>>'
```

@mweststrate Yes, and no one else said otherwise. What I am saying is how you're writing `Mobx6` using TypeScript and the way `decorate()` works in `Mobx4/5` is that it's using `keyof T` to statically type the fields and that in turn will ignore `private` **_AND_** `protected`.

I looked at your PR, and 
```
export type AnnotationsMap<T> = {
     [K in keyof T]?:
         | Annotation
         | true /* follow the default decorator, usually deep */
         | false /* don't decorate this property */
 }
```

Seem to indicate the same flaws. 

I wrote some suggestions in the [Mobx6 PR](https://github.com/mobxjs/mobx/pull/2327)

**Comment by mweststrate** [comment]
sorry you are right on the protected indeed, the ts-ignore was supposed to ignore the `first` only, but apparently suppresses multiple lines in this case.

That being said, I think this is the first time iirc the lack of support for private in decorate have been reported in ~2 years, so I don't think we urgently need this work-around that is still going to be weakly typed anyway. I'll make sure it gets documented as known limitation

**Comment by seivan** [comment]
> sorry you are right on the protected indeed, the ts-ignore was supposed to ignore the first only, but apparently suppresses multiple lines in this case.


> That being said, I think this is the first time iirc the lack of support for private in decorate have been reported in ~2 years, so I don't think we urgently need this work-around that is still going to be weakly typed anyway. I'll make sure it gets documented as known limitation


There could be a ton of reasons for this, from one of them from developers not caring about cluttering their objects API and namespace surface, to people generally just use Javascript or not using classes to begin with. 

That is really not a good reason to avoid supporting them and making the assumption it will complicate the API, all I am asking is offer an escape hatch similar to 

```ts
{ [P in keyof T]?: MobxDecoratorTypes} 
& 
{_privateFields?: { [key: string]: MobxDecoratorTypes } }
```
Or whatever the successor would look like in `Mobx6` 


You yourself made a mistake now yourself with `ts-ignore` so I don't see how it can be good suggestion as an alternative.

**Comment by mweststrate** [comment]
Ok, I think this is a [better](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-beta&ssl=1&ssc=26&pln=1&pc=42#code/AQMwrgdgxgLglgewsAtgQwNYFMDyAjAZywCcA3NPAGywB4AVYLADxiwgBMDgE8ArLWABpgAaUYs2nYAAViCAA4kYATxFZlwALzAIWUiQB8ACgBQwc8BhpiAcywwAXMDqCzF9gITE0MLwSfS1vBolDQASp7E7DTYygggzsIEMMRwEDYGwAA+wEZizKwcXLr6xMAA-Dp6JMBOEVBe0SJJKWkZAJQGJu1ODADebubE9mDEyBBglJTAaFxoEMoA3CYAviYmUJSzXHTEynQIAOL2dAAWcFwD5vKp5KzAN3B3WABicFiU7E4TKHg12gBGNzyMBUOBQN4fL7AZKpdJaYAAIlYyUR63MDQgsLAsC8RnaVws6Gw+CIZAo1CMMHOBGEhIsFhBYIh70+TmRWFRrgZDIA9LzgAABGAEAC0zEUsHFxDkxEGPPYCE5ADkEDAAKJMC6OJEomBohkrdroomYXCEEjkKi0Xb7I4nGnCRGPZ6Qz6I4zUi50+UMpmUcFu6Ecrm+iz8yw04AXbgYMPXW4+V6s4M8MlW6iI7k88wR4ViiUCGDS2Xx4CKlVqzXa9lUNAGixGtxrFZAA) solution, as it doesn't affect the runtime implementation and thereby all downstream usages of the utility (such as mobx-react hooks). It keeps it a design time problem and it is more explicit as privates need to be defined explicitly, rather than having a more implicit arbitrary set of fields.

(off topic: rules like `@typescript-eslint/ban-ts-ignore` are imho why people hate linters, it doesn't make sense, as they will get preceded by just another `// eslint-disable-next-line`. That rule is just as sensible as having a rule `mobx/ban-decorate-private-fields` icmw your solution: disabling an intentionally designed escape hatch, and in essence just fixing the problems of one escape hatch by creating another escape hatch is just increasing the work for all sides, without actually solving anything tangible)

**Comment by seivan** [comment]
> Ok, I think this is a better solution, as it doesn't affect the runtime implementation and thereby all downstream usages of the utility (such as mobx-react hooks). It keeps it a design time problem and it is more explicit as privates need to be defined explicitly, rather than having a more implicit arbitrary set of fields.

That's a very interesting solution and I actually think very useful for a lot of reasons!
But it expects on implementation. 

You mentioned earlier that `makeAutoObservable` will automatically include private fields since it doesn't rely on TS types to get the fields for proxy. 
So this is just for the `excludes?:` list I assume. 
So for manual, this makes sense.


Just to see if I understood it in terms of the `Mobx6` new API: 

Since (correct me if I am wrong) it it requires a value to indicate the annotation, I wasn't sure exactly what they were but I recall seeing these arguments. 

`Annotation | true | false `

So it would be something like this? 
```ts
makeObservable<TryToGetThis, "privateField">(this, {
        publicField: true,
        privateField: true,
})
```

While the `excludes?` for `auto` would be  something like 
```ts
makeAutoObservable<TryToGetThis, "privateField">(this, {
        privateField: false,
})
```

Correct? 
That works and is better since you don't have to destruct into a new merged list. 

Off topic: Won't it make sense just to have `makeObservable` and make it `auto` if it uses `excludes?:` and make it manual if it uses `includes?:`? 

Or named like Rails `only: ` and `except:`. 

Like  this would be `auto`
```ts
makeObservable<TryToGetThis, "privateField">(this, {
        only: {
            publicField: false
            }
})
```

Like  this would be `manual`
```ts
makeObservable<TryToGetThis, "privateField">(this, {
        except: {
            publicField: true
            }
})
```

Regarding your take on the linters, lets just say we disagree :). You're stating that they're the same. One is a global wide application escape hatch while the other is compensating for `decorate()` not including private fields, not to any faults of its own since `keyof T` doesn't include them, there is an issue open about that.

 So it's to compensate for TS shortcomings. 
But as I understand it Mobx6 no longer uses `keyof T` for `auto` and the only issue was related to `excludes?:` which you just tackled and I am grateful for. 
Thank you!
