### ISSUE TITLE
Is there any costs for calling observable on already observed value?

### ISSUE THREAD

**Issue by Niryo** [mobxjs/mobx#2342]
let obj1 = observable({bla: true});
let obj2 = observable(obj1); 

will it introduce any performance issue or is it safe to do it?
will changes to obj2 trigger only one render?

**Comment by FredyC** [comment]
I believe this answers your question ;)

https://github.com/mobxjs/mobx/blob/326eae873af8c675202c4f47ed7d86b1e6107b4a/src/v5/api/observable.ts#L87

**Comment by Niryo** [comment]
thanks. you are right, didn't thought it will be so straightforward:) Thanks!
