### ISSUE TITLE
Mocking a Mobx store in React Storybook

### ISSUE THREAD

**Issue by casvil** [mobxjs/mobx#2347]
Hi, I am trying to mock a MobX store in Storybook using React. I encountered the following gist https://gist.github.com/kitze/100efcc21597533e8ca8737aa8947dbf but I can't make it work. I tried the simplest way by just wrapping the `<MyComponent />` with a `<Provider />` and passing an observable object as a store that MyComponent needs.

Here's the code:

```javascript
import { Provider } from "mobx-react";
import { observable } from "mobx";

const mobxStore = observable({ myData: true });

storiesOf("My Component", module)
  .addDecorator(withReduxStore)
  .add("Example story", () => (
    <Provider store={mobxStore}>
      <MyComponent />
    </Provider>
  ));
```

```javascript
import { Provider } from "react-redux";

const reduxStore = () => createStore(mockReducer);
const withReduxStore = ({ children, store }) => <Provider store={reduxStore}>{children}</Provider>;

export default withReduxStore;
```

And here the error I encounter:
> **Cannot read property 'myData' of undefined**

Thanks for your help!

**Comment by FredyC** [comment]
Can you show how the `MyComponent` looks like? Make sure you don't have some typo there.

Also what's that `withReduxStore`? This is MobX here :)

**Comment by casvil** [comment]
Well, I can't show the `MyComponent` because of an NDA, but what I can tell is that is just a stateless component wrapped by an `observer` from `mobx-react`. `MyComponent` expects a `store` prop with the MobX store injected by its parent.

I just solved it by passing down the `store` prop to MyComponent like the following:

```javascript
const store = observable({ myData: true });

storiesOf("My Component", module)
  .addDecorator(withReduxStore)
  .add("Example story", () => (
    <Provider store={store}>
      <MyComponent store={store} />
    </Provider>
  ));
```

@FredyC We have different sources of data, one implemented in Redux to manage UI and another one in MobX to manage business logic, so I needed to mock both stores to put `<MyComponent />` in a Storybook. What do you mean by **This is MobX here**? Do you foresee any improvements that can be done?

Thanks!

**Comment by FredyC** [comment]
You need `inject` to get store into the component, the `observer` is not enough. I wonder how it works for you outside of storybook :)

Well, have loads of fun combining MobX and Redux :) Not that it cannot work together, but it sounds like a horrible approach to me.

**Comment by casvil** [comment]
I read in the MobX gitter that "Anythink you inject, can also be passed in as prop explicitly if not provided".

**Comment by FredyC** [comment]
Yes, that works, but you weren't doing that initially. In your previous comment, you have done that and it works so I guess I am closing the issue.
