### ISSUE TITLE
How do I create and use a development build so I can use spy?

### ISSUE THREAD

**Issue by rbabayoff** [mobxjs/mobx#2349]
Hey, would love help getting this to work since I get the following error which I'd like to trace:

```
Uncaught Error: [mobx] An invariant failed, however the error is obfuscated because this is a production build.
```

The app is a browser app that is bundled using browserify.

I tried the following but it didn't get me a dev build (I still get the same message above):

```
git clone ...mbox...
npm install
export NODE_ENV=development
npm run build
```

And then in my project folder:

```
npm install pathToMboxRepo/dist/v5 #I use v5
bundle and run app
```

Thanks in advance!

**Comment by FredyC** [comment]
I don't know how Browserify does, webpack has a plugin that will replace the occurrence of NODE_ENV in the code. You need to find something similar. Ask for help around Browserify community. Closing the issue as it's not related to MobX.
