### ISSUE TITLE
Object with Array values not re-rendering

### ISSUE THREAD

**Issue by odesey** [mobxjs/mobx#2350]
I am working on a `react-native` project and using the [react-native-calendars](https://github.com/wix/react-native-calendars#agenda) package.

As per the documentation, the data structure for the calendar events are as such:
```javascript
{
    '2020-05-22': [{name: 'item 1 - any js object'}],
    '2020-05-23': [{name: 'item 2 - any js object', height: 80}],
    '2020-05-24': [],
    '2020-05-25': [{name: 'item 3 - any js object'}, {name: 'any js object'}]
  }
```
I created a store and have the calendar events stored in an observable like so:
```javascript
class DataStore {
    constructor() {
    this.initialize();
  }

  @action
  //populate the calendar with empty dates as required by the calendar package
  initialize() {
      const startDate = moment()
        .subtract(2, 'month')
        .startOf('month')._d;
      const endDate = moment()
        .add(11, 'month')
        .endOf('month')._d;
      const dates = [];
      let date = startDate;
      const myEvents = {};

      while (date <= endDate) {
        myEvents[moment(date).format('YYYY-MM-DD')] = [];
        dates.push(moment(date).format('YYYY-MM-DD'));
        date = moment(date).add(1, 'days');
      }
      this.emptyEvents = { ...myEvents };
      this.calendarEvents = { ...myEvents };
  }
  @observable calendarEvents = {};

  //this action works as expected and the new event renders to the view
  @action calendarUpdate(calEvent) {
    this.calendarEvents[
      moment(calEvent.start).format('YYYY-MM-DD')
    ].push(calEvent);
  }

  //this does not work, no re-render is done at the component
    @action calendarRemoveEvent(calEvent) {

    const filteredEvents = this.calendarEvents[
      moment(calEvent.start).format('YYYY-MM-DD')
    ].filter(item => calEvent._id !== item._id);

    this.calendarEvents[moment(calEvent.start).format('YYYY-MM-DD')].replace(
      filteredEvents
    );
    
    //this shows the correct information in the array, but still no re-render
    console.log(
      this.calendarEvents[moment(calEvent.start).format('YYYY-MM-DD')]
    );
  }
}
```

This is how my component looks that is actually using the data:

```javascript
@inject('dataStore')
@observer
class Calendar extends Component {

  renderItem = item => (
    <Observer>
      {() => (
        <CalendarItem
          item={item}
          //more props
        />
      )}
    </Observer>
  );

  render() {
    const {
      dataStore: { calendarEvents }
    } = this.props;
    return (
      <View style={{ flex: 1 }}>
        <Agenda
          items={calendarEvents}
          // Initially selected day
          selected={new Date()}
          renderItem={this.renderItem}
          // Specify your item comparison function for increased performance
          rowHasChanged={(r1, r2) => {
            return r1.text !== r2.text;
          }}
          //more props removed for brevity... 
        />
      </View>
    );
  }
}
```

My problem is, when I remove or edit a calendar event from the `calendarEvents` Object Array, the screen does not re-render.

This appears to be the expected behavior based on the documentation, so my question is, how can I get the screen to re-render when I edit or delete an event from the `calendarEvents` Object Arrays?

## Versions:
    "mobx": "^5.15.4",
    "mobx-react": "^6.1.8",
    "react-native": "0.61.5",

Thanks!

**Comment by kubk** [comment]
Hi, destructuring `calendar events` won't work: https://mobx.js.org/best/react.html#mobx-tracks-property-access-not-values

Try this instead:
```js
<Agenda
  items={dataStore.calendarEvents}
```

**Comment by odesey** [comment]
Thanks for your response @kubk , unfortunately your suggestion did not work.

Because the change is taking place in 

`dataStore.calendarEvents['some date']: [{a: 1}, {b: 1}, {c: 1} \\updates happen here]`, 

mobx will not initiate a re-render unless I am directly referring to one of the objects in the array or the array itself inside of my render method. I need to find a way around this...

**Comment by mweststrate** [comment]
check if `CalendarItem` and `Agenda` are `observer` components, since they are the ones actually rendering the data, or, if it isn't and you don't control it, don't pass observables to it, but plain data instead, for example by using `dataStore.calenderEvents.slice()` (or `toJS`). Make sure to study https://mobx.js.org/best/react.html

**Comment by odesey** [comment]
Thanks for your response @mweststrate 

`CalendarItem` I control and it has the `@observer` decorator like so:

```javascript
@observer
class CalendarItem extends Component { // code here }
```
`Agenda` is provided by the `react-native-calendar` package and I do not control it.

I did try your suggestion of the `toJS` method like so:
```javascript
import * as mobx from 'mobx';
//... more code
items={mobx.toJS(calendarEvents)}
```
adding the 'toJS' method did not work however.

The only way I can think of getting mobx to do a re-render is by modifying the `calendarEvents` Object (and forget trying to modify the values), by removing and re-adding the key\value with the affected data. Or possibly cloning the object, updating it and replacing the entire `calendarEvents` object.

Both options seem rather heavy handed and may have performance implications for such a simple  task?

Feedback welcome.

Thanks.

**Comment by mweststrate** [comment]
Both shouldn't be needed. Looking at your code everything seems fine. I am a bit suprised about MobX 5 + React Native though, as RN doesn't support proxies yet afaik?

**Comment by odesey** [comment]
So after more digging, the problem appears to be in the `react-native-calendar` package.
I was only testing if I could update events initially, but it turns out that @mweststrate suggestion above did work for deleting events.

So the `toJS` method solved the problem and now the calendar re-renders. The bug is that updated events are not updated but that is an issue with the calendar package (I can see the updated event being passed to the calendar on re-render).

Thanks for your quick response and help @mweststrate

**Comment by ejabu** [comment]
> check if `CalendarItem` and `Agenda` are `observer` components, since they are the ones actually rendering the data, or, if it isn't and you don't control it, don't pass observables to it, but plain data instead, for example by using `dataStore.calenderEvents.slice()` (or `toJS`). Make sure to study https://mobx.js.org/best/react.html

works for me
