### ISSUE TITLE
MobX 4 actions are hidden

### ISSUE THREAD

**Issue by mbest** [mobxjs/mobx#2352]
I had been developing with MobX 5, but switched to 4 because we need ES5 support. I noticed that actions are now enumerable (not hidden).

The key difference is between these files:

https://github.com/mobxjs/mobx/blob/582a51691ebdbb5b8cd628ee286919a6dafc480c/src/v4/api/action.ts#L45

https://github.com/mobxjs/mobx/blob/582a51691ebdbb5b8cd628ee286919a6dafc480c/src/v5/api/action.ts#L45

**Intended outcome:**

Actions are hidden in 4 like they are in 5.

**Actual outcome:**

Actions are not hidden in 4.

**How to reproduce the issue:**

Use 4 and use the action decorator.

**Versions**

4.15.4

**Comment by FredyC** [comment]
It's probably not worth poking in that now. There is MobX 6 upcoming (#2327) which will make this pain of choosing either V4 or V5 matter of the past, the only single version will exist. And you can already [see there it will be hidden](https://github.com/mobxjs/mobx/pull/2327/files#diff-a2d1fd082197352104fd0428d9369f26R64).

Of course, if this is troublesome for you for some reason, feel free to submit a PR.

**Comment by mbest** [comment]
For now, I've got a workaround by creating my own decorator that wraps MobX's:

```ts
function action(target: any, propertyKey: string, descriptor: PropertyDescriptor): void {
    Object.defineProperty(target, propertyKey, {
        ...descriptor,
        value: mobxAction(propertyKey, descriptor.value),
        enumerable: false,
    });
}
```

**Comment by FredyC** [comment]
Alright, closing then :)

**Comment by mbest** [comment]
@FredyC Can you confirm that MobX 6 will support IE11?

**Comment by FredyC** [comment]
@mbest Better to hear that from @mweststrate. I just know he is working on it, and the merging of V4/V5 is one of the goals meaning it should definitely be compatible with IE11.

**Comment by mweststrate** [comment]
Yes it will support IE 11
