### ISSUE TITLE
Ability to rename an observable when extending

### ISSUE THREAD

**Issue by mbest** [mobxjs/mobx#2353]
I'd like to be able to update an observable's name. `extendObservable` takes a name property, but this only has an effect the first time.

**Comment by FredyC** [comment]
Can you elaborate on what is your use case? Given the name is for debugging purposes only you should be relying any logic on it.

**Comment by mbest** [comment]
I'm using a technique of creating observable objects with `extendObservable` to chain various types of properties to the observable (similar in style to MobX state tree). I'd like to be able to define a base type and then extend to define derived types.

**Comment by FredyC** [comment]
Then maybe have a look at how MST does it. I don't think we will complicate API here just for your edge use case.

**Comment by mbest** [comment]
I did not look at how MST does it, but I was able to make my approach work with MobX by delaying the observable creation until I have all the needed info.

**Comment by mbest** [comment]
On a somewhat related not, the [docs](https://mobx.js.org/refguide/extend-observable.html) say "Note: `extendObservable` can not be used to introduce new properties on observable arrays or objects". However, this is not true, as I have been able to successfully use it to add properties to an observable object.

**Comment by mweststrate** [comment]
I guess that should read arrays, maps or sets
