### ISSUE TITLE
rename mobx to statex

### ISSUE THREAD

**Issue by 7flash** [mobxjs/mobx#2357]
mobx is super cool state management library, but I always wonder about name, what does it mean? In case if there is no special meaning attached, I propose to rename library into statex that clearly defines its purpose

**Comment by FredyC** [comment]
Yeah right, that wasn't even funny. Keep it real, man. MobX has become a brand by now. By changing its name you would only confuse people with a bunch of outdated articles, courses, guides, and whatnot Not really worth it. The original name was Mobservable and there is some explanation behind the name change in past issues, feel free to dig in.

**Comment by FredyC** [comment]
Btw, MobX is not purely a state management library, far from it actually. The underlying concept of observables can be used as a fancier pubsub pattern with some cool optimizations under the hood. Perhaps try to use MobX out of the comfortable chair of React before you draw a conclusion that MobX is some distant cousin to Redux :)

**Comment by 7flash** [comment]
Thanks @FredyC!
