### ISSUE TITLE
Is there a way to globally set strict mode?

### ISSUE THREAD

**Issue by studiojms** [mobxjs/mobx#2358]
I have been using mobx with react in my projects for a long time, and always trying to enforce the behavior of the app following the strict mode recommendation (configure({enforceActions: 'observed'})).

As the application grows, we end up replicating the same configure instruction all over the "stores" of the application (in one of the large apps I have been working, we have almost 300 stores).

When working in a large team, we always need to ensure that the configure clause is declared in all of our store classes, but I would like to know if there is any other way we could set (preferably in one place only, a global configuration) that should enforce that it should be in strict mode for mobx stores for the whole application.

**Comment by kubk** [comment]
This setting is already global. It is enough to put `configure({ enforceActions: 'observed' });` in the entry point of your app.
