### ISSUE TITLE
Cannot access object property 

### ISSUE THREAD

**Issue by ArtjomProzorov** [mobxjs/mobx#2364]
I am trying to access a property of observable object user and when i try to refer to it this.props.auth.user it works but when i try to access user property role  it says undefined.

I tried with mobx.toJS(this.props.auth.user) and it give me the correct JS object , however, once again i cannot access it

![image](https://user-images.githubusercontent.com/43901335/83555962-c966a680-a517-11ea-82d8-30a46c488f5c.png)

```
`export default class AuthStore {

  @observable authenticating = false;

  @observable authenticated = false;

  @observable user;

  @action.bound
  authenticate = async (token) => {
    if (token && token.length > 10) {
      sessionStorage.setItem(STORAGE_AUTH_TOKEN_KEY, token);
      this.authenticating = true;
      loading.start();
      try {
        const {data} = await fetchMe();
        this.user = data;
        this.authenticated = true;
      } catch (e) {
        this.user = null;
        this.authenticated = false;
        console.error(e);
      } finally {
        loading.stop();
        this.authenticating = false;
      }
    }
  };`

```
```
@inject('auth')
class PreferencesSettings

i can do this console.log(mobx.toJS(this.props.auth.user));

user = mobx.toJS(this.props.auth.user
i cannot do this console.log(user.role));
```

**Comment by FredyC** [comment]
Can you set up a reproduction with eg. CodeSandbox? Running `toJS` shouldn't give you a Proxy for sure.

**Comment by ArtjomProzorov** [comment]
@FredyC i dont think i can reproduce the code due to security,   but here is also whats interesting, when i do console.log(console.log(this.user.role); it shows the correct result. Also if i create new observable role  in auth store , i can successfully refer to it in my component 

```
 try {
        const {data} = await fetchMe();
        this.user = data;
         console.log(console.log(this.user.role);
        this.authenticated = true;
```

**Comment by FredyC** [comment]
I don't want access to your project. Just try to reproduce minimalistic steps leading to a problem you are describing. Try to help us here so we can help you.

**Comment by ArtjomProzorov** [comment]
@FredyC  My sincere apologies , after restarting everything completaly i was able to succeed with toJS and refer to role property, you can close this issue. Thank you for your immediate support
