### ISSUE TITLE
Codesandbox example broken

### ISSUE THREAD

**Issue by mateomorris** [mobxjs/mobx#2365]
It looks like the Codesandbox example in the Readme is broken.
![image](https://user-images.githubusercontent.com/39444813/83616355-05d1eb00-a588-11ea-930d-bdcb1eceb684.png)

**Comment by FredyC** [comment]
Then fix it :)

**Comment by mateomorris** [comment]
I don't know anything about MobX, just thought you might want to know so you don't turn off newcomers

**Comment by mweststrate** [comment]
Since it is my sandbox, I'm probably the only one who can fix it. 

Fixed, thanks for notifying @mateomorris!
