### ISSUE TITLE
Call an array inside a component returns Proxy

### ISSUE THREAD

**Issue by stelasido** [mobxjs/mobx#2368]
Hi, I have a store, with an array in it:
store.js:
`class Store {
    @observable locations = [1, 2, 3];
}`

, which I am trying to use inside a component:

SomeComponent.js:
`import { inject, observer } from 'mobx-react';

@inject('store') @observer`

, but when I console log `this.props.store.locations`, I see `Proxy`.
How to get that array ? Can some1 just give me a simple example ? I have an array in the store and I want to use it in a component.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/issues/2005#issuecomment-502108711

**Comment by stelasido** [comment]
Thanks, I did it, will close the case.
