### ISSUE TITLE
Call-stack size exceeded when deleting then getting an observable prop (on a class)

### ISSUE THREAD

**Issue by Venryx** [mobxjs/mobx#2375]
**Intended outcome:**

Deleting then getting/setting an observable class-prop would succeed, without errors.

**Actual outcome:**

Deleting then getting/setting an observable class-prop infinitely calls the mobx `get` function, causing an error:
```
Uncaught RangeError: Maximum call stack size exceeded
    at initializeInstance (app.js:244522)
    at Class1.get [as prop1] (app.js:244511)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
    at Class1.get [as prop1] (app.js:244512)
```

When I step through the code, pressing "step next", it just repeats the two lines marked below (deepening the stack each time):
```
function createPropertyInitializerDescriptor(prop, enumerable) {
    var cache = enumerable ? enumerableDescriptorCache : nonEnumerableDescriptorCache;
    return (cache[prop] ||
        (cache[prop] = {
            configurable: true,
            enumerable: enumerable,
            get: function () {
                initializeInstance(this);	<<
                return this[prop];		<< function calls itself here!
            },
            set: function (value) {
                initializeInstance(this);
                this[prop] = value;
            }
        }));
}
```

**How to reproduce the issue:**

Just run this code:
```
class Class1 {
	@observable prop1 = false;
}
const obj = new Class1();
delete obj.prop1;
obj.prop1; // or: obj.prop1 = true;
```

**Versions**
mobx@5.15.4

**Comment by FredyC** [comment]
Don't delete prop, set them to `undefined` or `null`. Deleting is always problematic.

**Comment by Venryx** [comment]
Is this listed in the readme somewhere?

And could an error perhaps be added to MobX to make this more clear? (perhaps just checking if the infinite loop above gets hit, then logging a warning)

**Comment by FredyC** [comment]
It's kinda common sense that deleting property doesn't give many benefits, most often it causes problems. It's not necessarily related to MobX.

But I guess it could be tackled more gracefully in upcoming MobX V6, what do you think @mweststrate?

**Comment by Venryx** [comment]
The issue is perhaps related to:
https://github.com/mobxjs/mobx/issues/1730
https://github.com/mobxjs/mobx/issues/1796

However, those issues were closed, apparently due to them being fixed. So it may be a regression.
