### ISSUE TITLE
functional store

### ISSUE THREAD

**Issue by negati-ve** [mobxjs/mobx#2376]
Hi, I'm new  to mobx and I see a lot of examples with stores created as classes
but very few where the store is fully functional 

when i try out a class based store using @observable and @action,
I see in react dev  tools that the store has only  the observables and not the actions (which is what i expect it to have) although the  actions  are  accessible from other parts of the app

my  question  is when a store is created functionally.. what  is the right  way to  access and use the store?

would this be correct?

```
import { observable, action } from 'mobx';

export default (initialData = {}) => {

	var userStore = observable({
		name: 'adam'
	})

	const setUserName = action((name) => {
		userStore.name = name
	})

	const getUserName = async () => {
		return userStore.name
	}

	if (typeof window === 'undefined') {
	    // server side
	} else {
            // Client side
	}

        return userStore

}
```

**Comment by FredyC** [comment]
You are not returning anything from your function, return an object with all those variables to access them. Sorry, but that's JavaScript 101.

**Comment by negati-ve** [comment]
thanks for the quick reply @FredyC !

yes,  of course..  sorry, i missed that while copy pasting the code


when I return  userStore, I can access the store data
but I cannot access the store actions 

> this.props.store.UserStore.getUser is not a function

do I need to return the actions as well?

**Comment by negati-ve** [comment]
From the modifiers doc on mobx website, 
I was able to come up with this 

```
export default () => {
    var userStore = observable(
        {
            user: 'name',
            setUser: action((userData) => {
                userStore.user = userData
            }),
        },
        {
            getUser: action,
        })

    return userStore
}
```

So in essence, 
to avoid the @action decorator from the classes 
I need to pass options to observable letting it know that these are the actions

oh boy! I see why @actions decorator is so nice now haha

**Comment by FredyC** [comment]
What about just like this?

```
export default (initialData = {}) => {

	var userStore = observable({
		name: 'adam'
	})

	const setUserName = action((name) => {
		userStore.name = name
	})

	const getUserName = async () => {
		return userStore.name
	}

	if (typeof window === 'undefined') {
	    // server side
	} else {
            // Client side
	}

        return { userStore, getUserName, setUserName }
}
```
