### ISSUE TITLE
concat and observable.array

### ISSUE THREAD

**Issue by logrox** [mobxjs/mobx#2379]
When in the observed array I have few elements and do "concat" below, everything is as expected, but if it will be more data, eg 60,000 elements, then the problem begins.
See for yourself.

[my code](https://jsfiddle.net/logrox/680yq9w5/1)

**Comment by FredyC** [comment]
Thanks for the report. It might be a performance problem related to https://github.com/mobxjs/mobx-react/issues/877.

Note that MobX is not built to be performance winner, there are better tools if you need to handle big amounts of data.

@urugator just FYI since you are rewriting array handling for V6.

**Comment by urugator** [comment]
Can't "debug" it because the fiddle is randomly freezing even without observable array.

**Comment by FredyC** [comment]
https://codesandbox.io/s/affectionate-wildflower-x5kqu?file=/src/index.js

CodeSandbox is at least clever enough to spot a problem and doesn't freeze.

**Comment by mweststrate** [comment]
This might be hitting the maximum function arguments somewhere, given the 60.000 number. https://stackoverflow.com/a/22747272/1983583. If we `...` or `.apply` an array function in our `concat` implementation that could explain.

**Comment by mweststrate** [comment]
as an work around `observableArray.slice().concat(otherObservableArray.slice())` will probably work.

**Comment by urugator** [comment]
Ah I think there was a misunderstanding this isn't about performance...
The problem is `[1,2].concat(observableArray)` results in `[1, 2, undefined, undefined, undefined, ...]`

**Comment by urugator** [comment]
it misbehaves on observbaleArray.length >= const MAX_SPLICE_SIZE = 10000

**Comment by logrox** [comment]
> Ah I think there was a misunderstanding this isn't about performance...
> The problem is `[1,2].concat(hugeObservableArray)` results in `[1, 2, undefined, undefined, undefined, ...]`

You're right, I meant undefined

**Comment by mweststrate** [comment]
...aahh I thought it was about the app hanging (at least for me in chrome).
Urugator are you interested in creating a unit test for this on current
master branch?

**Comment by urugator** [comment]
Current master meaning v6? I could, but note some test are already failing there. I can also add it to #2373 If you want. Btw is this even fixable? It seems to be related to that MAX_SPLICE_SIZE, but notice it's `concat` method of the native array (not our `concat`). I tried `[1,2,...hugeObservableArray]` but that seems to work fine, so I wonder what that native concat really does...?

**Comment by mweststrate** [comment]
Not sure, but having a regression test will already be valuable. Sorry for
being slow in follow up lasts weeks, with  children at home full time I
find it particular hard to find time and focus, so efforts are a bit random
at the moment 😊

Op vr 19 jun. 2020 12:28 schreef urugator <notifications@github.com>:

**Comment by urugator** [comment]
I've added the test to https://github.com/mobxjs/mobx/pull/2373, so feel free to merge it.
The result is different for legacy array because it's `concat(object)` rather than `concat(proxiedArray)`

**Comment by mweststrate** [comment]
awesome, thanks!

**Comment by logrox** [comment]
But when I use the `na.concat(oa.toJS())` everything works as it should.
