### ISSUE TITLE
"Invariant failed" for computed array properties

### ISSUE THREAD

**Issue by gusev-p** [mobxjs/mobx#238]
Hello,

I'm having trouble implementing the following 'ObservablePromise' logic:

```
import {observable, computed, extras, autorun} from "mobx";
export class ObservablePromise<T> {
    constructor(value:T) {
	//extras.allowStateChanges(true, () => { this.value = value; });
	this.value = value;
    }
    @observable
    public value:T;
}

interface IProduct {
	name:string;
}

export class ProductsStore {
	public cachedProducts: IProduct[];

	@computed
	public get products(): ObservablePromise<IProduct[]> {
		if(this.cachedProducts) {
			return new ObservablePromise(this.cachedProducts);
		}
		const result = new ObservablePromise([]);
		this._loadProductsFromServer()
			.then(p => {result.value = <IProduct[]>p});
		return result;
	}

	private _loadProductsFromServer(): any {
		return {
			then(f) {
			}
		}
	}
}

const store = new ProductsStore();
store.cachedProducts = [{name:"orange"}];
autorun(() => {console.log("autorun: " + store.products.value);});
```

This works fine if ObservablePromise's type is string or number or array of 'simple' types, but for arrays of complex types this throws "Error: [mobx] Invariant failed: It is not allowed to change the state when a computed value is being evaluated. Use 'autorun' to create reactive functions with side-effects. Or use 'extras.allowStateChanges(true, block)' to supress this message.". If I uncomment the 'allowStateChanges' line in ObservablePromise constructor as the message suggests, everyting is ok.
Seems strange that the error condition depends on the type of the observable.

**Comment by mweststrate** [comment]
Can you elaborate a bit on what you try to achieve with the ObservablePromise? I see the way you are heading, but I am not sure what your intention is :)

**Comment by gusev-p** [comment]
I want some kind of 'async observable' - give to the consumers of 'products' some 'thing' which will be seen as having default value (empty array for instance) for the time of ajax and will receive real value when ajax completes. And like ordinary @computed property this 'thing' should detect any changes in used observables to pass them as parameters to server call. For example, ProductsStore may have @observable customerId property, assignable from UI:
```
export class ProductsStore {
    public @observable customerId: number;

    @computed
    public get products(): ObservablePromise<IProduct[]> {
        const result = new ObservablePromise([]);
        this._loadProductsFromServer(this.customerId)
            .then(p => {result.value = <IProduct[]>p});
        return result;
    }

    @computed
    public get costlyProducts(): IProduct[] {
	return this.products.filter(x => x.price > 1000);
    }

    private _loadProductsFromServer(): any {
        return {
            then(f) {
            }
        }
    }
}
```
'products' and 'costlyProducts' mapped as list components on the UI.

Am I abusing the concept?

**Comment by gusev-p** [comment]
In other words, I want to abstract away async nature of 'products' for it's derivations to make them simple @computed properties.

**Comment by gusev-p** [comment]
Realized that I can use ordinary observable([]) for this:

```
export class ProductsStore {
    public @observable customerId: number;

    @computed
    public get products(): IProduct[] {
        const result = observable([]);
        this._loadProductsFromServer(this.customerId)
            .then(p => result.replace(p));
        return result;
    }

    @computed
    public get costlyProducts(): IProduct[] {
    return this.products.filter(x => x.price > 1000);
    }

    private _loadProductsFromServer(): any {
        return {
            then(f) {
            }
        }
    }
}
```
ticked can be closed probably.

**Comment by mweststrate** [comment]
I think indeed this might not be the most convenient way to go (but I might be mistaken, feel free to prove me wrong). But observables in themselves are not sync or async, they just are, and at any moment in time they have a value. MobX allows you to implement your own observables through the concept of [atoms](https://mobxjs.github.io/mobx/refguide/extending.html)

`@computed` is used wrong in your example as it triggers effects like making server requests and updating values. So the invariant exception is correct.

I would express your example as follows (assuming you want the products only to be loaded after the fist access)

```javascript
export class ProductsStore {
    public @observable customerId: number;
    private @observable _products = [];
    private productFetcher;  // autorun disposer that fetches the products when needed

    public get products() {
        if (!this.productFetcher) {
            this.productFetcher = autorun(() => {
               this._loadProductsFromServer(this.customerId).then(p => this._products = p)
            })
        }
        return this._products;
    }

    @computed
    public get costlyProducts(): IProduct[] {
    return this.products.value.filter(x => x.price > 1000);
    }
}
```

`autorun` is the proper method to use here, if you want the fetching to happen automatically (otherwise you don't even need it)

**Comment by gusev-p** [comment]
I get you point about side effects in `@computed` props, thanks. It will be really strange for example to set progress indicator flag for the time of ajax (to display that something is going on for the user) in `@computed` prop. But there are more code than I would like for simple server call, I will think about some abstraction to simplify this.

**Comment by ronag** [comment]
@mweststrate: Isn't there a leak here where `autotrun` is never disposed?
