### ISSUE TITLE
Website almost unusable on a 13" retina display

### ISSUE THREAD

**Issue by kswope** [mobxjs/mobx#2383]
The top area and the nav are taking up over a third of the viewable area.  I feel like I'm reading the docs through a mail slot.

<img width="1024" alt="Screen Shot 2020-06-24 at 6 50 58 AM" src="https://user-images.githubusercontent.com/321586/85543215-da22ad80-b5e7-11ea-98ee-f768c51264e8.png">

**Comment by FredyC** [comment]
I am not sure what do you expect from a small resolution screen. Perhaps zoom out?

**Comment by kswope** [comment]
> I am not sure what do you expect from a small resolution screen. Perhaps zoom out?

Well I don't have that problem with the rest of the web, as an example...

<img width="1024" alt="Screen Shot 2020-06-24 at 7 32 41 AM" src="https://user-images.githubusercontent.com/321586/85548549-0e4c9d00-b5ed-11ea-81ff-b7f466065aa7.png">

**Comment by vkrol** [comment]
@kswope you need to zoom out as @FredyC suggested :)

![image](https://user-images.githubusercontent.com/153412/85549636-dcf1c280-b628-11ea-8058-d28834191aa8.png)

**Comment by kswope** [comment]
Ok I see the problem.  The media breakpoint is set a crazy level.  If I go to 110% zoom with a 13" retina it immediately kicks into a mode more suitable for a mobile device.    Basically, at 110% zoom I see exactly whats on my iphone SE.  In fact the docs are easier to read on my iphone than on a 2020 macbook air.

**Comment by FredyC** [comment]
I wonder, do you have the same problem with other Docusaurus based sites, eg. https://docusaurus.io/ itself? We have mostly just default styling, so it's possible that's something that has been fixed in newer versions.

**Comment by kswope** [comment]
> I wonder, do you have the same problem with other Docusaurus based sites, eg. https://docusaurus.io/ itself? We have mostly just default styling, so it's possible that's something that has been fixed in newer versions.

Yep thats it.  There's a media query for screens below 1024px that switches the header area to flex-direction: column.  If you are on a retina 13" and if the browser is anything but edge-to-edge (and not a pixel less), or you go up to zoom 110%, it switches to 'device' mode.

Its not as bad on Docusaurus because their top row is a little crowded and the don't have a menu bar that stretches across the screen.

**Comment by mweststrate** [comment]
Closing, someone can put a PR to fix it, or leave it as is and zoom a bit out.
