### ISSUE TITLE
Should MobX provide something to disable observables?

### ISSUE THREAD

**Issue by timothympace** [mobxjs/mobx#2384]
I am using MobX in a server side rendered app, and I ran into a performance issue with `observable`. My problem occurs when creating a very large `observable`. I assume that this is a bad practice and I will look for a different way to handle this given my use case. However, this got me thinking... If I am using `useStaticRendering` to disable observers on the server, is there any point in creating the observables themselves?

Are there other things that would fail if observables were to be disabled? Would computed properties still be memoized? I don't need computed properties to be re-computed (because there are no state changes when doing a static server render), but my app does assume computed properties are memoized, and that might open up another can of worms if a memo-ized property is getting reevaluated more than I think.

In essence, what kind of things would stop working as expected if observables were no longer observable? I am trying it out as a test right now and everything still seems to be working.

**Comment by mweststrate** [comment]
Nothing should stop working. Your app shouldn't care semantically even if
computeds don't memoize anymore (It might be a perf hit though), but the
outcome should be the same. So yeah it shouldn't matter (famous last words)
if nothing is made observable anymore :)

**Comment by timothympace** [comment]
Thanks for the answer! I'll do some testing to see if my computed function isn't memoizing without observables.

What would be the best way to go about disabling observables in the server environment. Do you think this is something Mobx should provide an API for? Or should I find a way to handle it in my build flow?

**Comment by timothympace** [comment]
Just tested computed property memoization by commenting out all my `observable` decorators and my computed function only had 1 call to it. As a sanity check, I commented out the `computed` decorator, and the getter had 98 calls to it. So it seems the computed property still works as expected with observables disabled 😄

**Comment by urugator** [comment]
Hm, if I am not mistaken, the computeds don't memoize  with `useStaticRendering`, because there are no observers...?

**Comment by timothympace** [comment]
A computed property is still useful without an observer. In my app I have derived data that is used in many places. By using a computed property, the result doesn't need to be recomputed on every call. The difference in static rendering is just that I know none of my data/observables will change, and the computed will never have a reason to recompute.

**Comment by urugator** [comment]
What I am trying to say is that I am suprised by your observations, because afaik the `computed` only caches the value if it's observed by anything (`reaction`) or when it's `keepAlive`. Disposing the last observer (reaction) also disposes the `computed`'s cache to prevent memory leaks. `useStaticRendering` causes `observer` to simply return the original component without creating any reactions ... so no observers -> no caching.
One other situation, when cache works without observers is for the duration of an `action`.

**Comment by timothympace** [comment]
Oh, okay, I see. Yeah I do still have a reaction registered for the `computed` property in question. I'll have to retry my experiment with no reactions now.
