### ISSUE TITLE
Typescript 3.9 breaks getters in extendObservable

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx#2386]
Typescript 3.9 introduced a sneaky breaking change regarding the way getter are emitted by setting `enumerable: false` instead of `enumerable: true` (associated PR [here](https://github.com/microsoft/TypeScript/pull/32264)).

This causes `extendObservable` to ignore properties defined as getters in its second parameter, like that :

```ts
const obs = extendObservable({a: 2, b: 3}, { get c() { return a + b; });
obs.c // undefined (!!)
```

I'm a bit surprised that no one has yet reported this, it literally broke my entire app once I upgraded. 

I'm not sure how this can be mitigated : how can `extendObservable` enumerate the properties to add if they aren't actually enumerable?

**Comment by FredyC** [comment]
Interesting observation. It doesn't seem we can really do much here. I see some complaint in the linked PR so hopefully, that will give it a second thought. I guess you have to stick to the previous TS till then.

**Comment by mweststrate** [comment]
Non enumerable props can be iterated through Object.getOwnPropertyNames w/o
problem. I think in MobX 6 this would actually work already. MobX 4/5 might
need a patch if this is default behaviour in TS

**Comment by JabX** [comment]
This is actually the only behavior that TS supports now, there is no plan to add a flag or something to control it. I ended up reverting to 3.8 for the time being.

They keep mentioning classes though in their justification (and in the existing complaints), but here I'm not using a class at all, just a plain JS object. Is the behavior really supposed to be the same here? 

I forgot to mention, but I am using MobX 4 (latest), so I don't know if it also happens in 5.

If we were to switch to using `Object.getOwnPropertyNames`, isn't it going to break something else? Like weird inheritance-based patterns or something?

**Comment by mweststrate** [comment]
I think there would be little risk in updating that, as the second argument of extendObservable is supposed to be a plain object anyway.

**Comment by mweststrate** [comment]
Anybody interested in making a PR for this one on v5/4? I think the unit tests from 6 could be reused directly: https://github.com/mobxjs/mobx/blob/7c5ed6ce793b262a7aa8ed5ee6243e2bdc70bc73/test/v5/base/make-observable.ts#L338-L357

**Comment by mweststrate** [comment]
Fixed and released as (4/5).14.5
