### ISSUE TITLE
Best practice  for handling cancel edit?

### ISSUE THREAD

**Issue by geohuz** [mobxjs/mobx#2387]
I know there is a snapshot in the mobx-state-tree, now I'm wondering if there is such facility which I can use in the scenario of cancel edit of a form data input, I would like to take a snapshot before edit, and if user choose cancel then I can bring back the original state . Maybe I can use useRef to keep a copy of toJS(...) and then bring them back by create a new instance of the original observable from the copy?

**Comment by kubk** [comment]
Maybe `createViewModel` suits you: https://github.com/mobxjs/mobx-utils#createviewmodel 
It has `reset()` method to abandon modifications.

**Comment by geohuz** [comment]
Hi @kubk,  thanks you so much!

**Comment by FredyC** [comment]
Please, close the issue if's solved for you.
