### ISSUE TITLE
Extending object implementations (example of Linq.ts) to support mobx change detection

### ISSUE THREAD

**Issue by johnhamm** [mobxjs/mobx#2392]
Is there a way to make an object implementation compatible with Mobx's change detection?  I'm using Linq.ts's List type but when I modify the list, Mobx can't detect the changes:

```typescript
import { List } from 'linq.ts';
import { autorun, observable, computed } from 'mobx';

class Test {
  @observable list = new List<number>([1,2,3]);
  @observable a = [1,2,3];

  @computed get list2() { return new List<number>(this.a);}

  constructor() {
    console.clear();

    autorun(() => {
      console.log("Only runs once");
      console.log(this.list);
      console.log(this.list.ToArray());
    });

    this.list.Add(4);

    autorun(() => {
      console.log("Runs three times");
      console.log(this.a);
    })

    autorun(() => {
      console.log("Should also run three times");
      console.log(this.list2);
    })

    this.a.push(4);
    this.a.push(5);    

    console.log(this.list);
  }    
}

var test = new Test();
```
Stackblitz example: https://stackblitz.com/edit/mobx-linqts

I'm not exactly talking about modifying Linq.ts, but if I were to implement my own List, how would I signal outside of it to Mobx that a change has occurred?

My fantasy is to have linq.ts modified to be compatible with Mobx's change detection (assuming the use of Javascript proxy objects would allow this?).

I've cross-posted to  [Linq.ts](https://github.com/kutyel/linq.ts/issues/155) as well.

**Comment by FredyC** [comment]
I don't know anything about Linq.ts, but if it has some sort of events to listen to, you can basically build your own observable through [atoms](https://mobx.js.org/refguide/extending.html).

**Comment by johnhamm** [comment]
I just ended up passing in an observable array to the List constructor to get it to work:

`let list = new List<SomeObject>(observable.array());`

**Comment by FredyC** [comment]
Ok great, closing issue then :)
