### ISSUE TITLE
docs(sitemap): superfluous double slash on URL from sitemap 

### ISSUE THREAD

**Issue by s-pace** [mobxjs/mobx#2394]
**Intended outcome:**

This issue is only related to the documentation website. It follows #2393.

When crawling your website, we have noticed that [the URLs exposed in your sitemap are wrongly build](https://mobx.js.org/sitemap.xml). Please note the superfluous double slash as highlighted on the following screenshot:
![image](https://user-images.githubusercontent.com/32097720/86931002-e5bdba80-c137-11ea-84fb-d208f1debb73.png)

**Actual outcome:**

 For example, this URL should be https://mobx.js.org//best/actions.html -> https://mobx.js.org/best/actions.html
**How to reproduce the issue:**

Go [on the sitemap](https://mobx.js.org/sitemap.xml), open the developper tool from your favorite browse and inspect the sitemap's content

**Comment by mweststrate** [comment]
Thanks for reporting! Should be fixed now
