### ISSUE TITLE
Behavior digression with `observable.box().set()` and `action()`

### ISSUE THREAD

**Issue by montythibault-v2** [mobxjs/mobx#2395]
mobx@5.15.4

Consider this example:

```
const x = observable.box(0);
const y = observable.box(0);

observe(x, () => console.log('reaction x'));
observe(y, () => console.log('reaction y'));

action(() => {

  console.log('changing x');
  x.set(1);

  console.log('changing y')
  y.set(1);

})();
```

Expected output is:

```
changing x
changing y
reaction x
reaction y
```

The bottom two rows could be optionally swapped depending on the order of the observer execution. Actual output is:

```
changing x
reaction x
changing y
reaction y
```

**Comment by mweststrate** [comment]
That is correct. `observe` handling doesn't respect transactions, as
observe listeners notify about the state mutations rather than the state
results. Use autorun or reaction instead. Using observe directly is
generally an anti pattern.

**Comment by montythibault-v2** [comment]
I see, thanks for your clarification. I missed these points in the documentation for observe:


https://mobx.js.org/refguide/observe.html#observe

Note that transaction does not affect the working of the observe method(s). This means that even inside a transaction observe will fire its listeners for each mutation. Hence autorun is usually a more powerful and declarative alternative to observe.

observe reacts to mutations, when they are being made, while reactions like autorun or reaction react to new values when they become available. In many cases the latter is sufficient.
