### ISSUE TITLE
Instantiation order in RootStore example?

### ISSUE THREAD

**Issue by TheRohitSharma** [mobxjs/mobx#2397]
I ran into an issue the other day where I had a RootStore like such:

```
class RootStore {
    constructor() {
        this.AStore = new AStore(this)
        this.BStore = new BStore(this)
    }
}
```
In `AStore`:
```
class AStore {
    constructor(rootStore) {
        this.rootStore = rootStore
        // this.rootStore.BStore does not exist since it was instantiated _after_ AStore
    }
}
```
Should the example here (https://mobx.js.org/best/store.html#combining-multiple-stores) reverse the order of instantiation of the UserStore/TodoStore or am I definitely missing something?

**Comment by FredyC** [comment]
Of course, if you need to access BStore inside AStore within a constructor, then you indeed need to flip the order, but otherwise it doesn't matter because you are storing a reference to rootStore.
