### ISSUE TITLE
transaction suppressing errors

### ISSUE THREAD

**Issue by maxguzenski** [mobxjs/mobx#240]
I believe that transaction is suppressing js errors. I have a lot of nested transaction, and a model was a invalid reference (null) and Chrome console show nothings.

**Comment by mweststrate** [comment]
Hi,

I'm quite sure it doesn't (unless you are using an older version of MobX). The current code base does not contain any `try ... catch` statements, so exceptions should not be eaten. If this is still an issue, could you try narrowing it down / reproduce it?

**Comment by maxguzenski** [comment]
Im trying to reproduce it outside of my app and I cant... I'll try a little more.

**Comment by maxguzenski** [comment]
was axios related.
