### ISSUE TITLE
Make docs easy

### ISSUE THREAD

**Issue by peng** [mobxjs/mobx#2402]
When I finish read docs, I don't how to use it either. Example on docs will be run with error. So I find mobx is too difficult to use. And docs say it is easy to use, that's so funny!

**Comment by mweststrate** [comment]
We are currently revising the docs for v6. Beyond that, since you didn't provide any details this issue is inactionable. Either at least clarify what you mean with "error", (what code, which error, etc), or help out by PR-ing improvements.

**Comment by peng** [comment]
I think i should read your docs more and read your code to help docs improve
