### ISSUE TITLE
Mobx throws error message when changing observable values in the constructor in certain situation

### ISSUE THREAD

**Issue by breck7** [mobxjs/mobx#2409]
**Intended outcome:**

I expect no side effect error when I change an observable value in the constructor.

**Actual outcome:**

`Error: [mobx] Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify...`

**How to reproduce the issue:**

```typescript
import { observable, computed } from "mobx"

class Mall {
    @computed get openStore() {
        return new Store("Open")
    }

    @computed get closedStore() {
        return new Store("Closed")
    }
}

class Store {
    constructor(status: string) {
        this.status = status
        if (this.isOpen && this.shouldClose()) this.status = "Closed"
    }

    shouldClose() {
        return true // Imagine there's some actual logic here
    }

    @observable status: string

    @computed get isOpen() {
        return this.status === "Open"
    }
}

// Works
new Store("Closed")
new Store("Open")
new Mall().closedStore

// Fails
new Mall().openStore
```

**Versions**

 5.13.0.

**Additional Context**

I was hitting an `Error: [mobx] Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify...` and ended up in a lengthy debugging session.

I am not sure if this is a bug or is working as intended, but it was really tricky to debug so I thought I'd post this here in case anyone else runs into a similar situation.

I think my main question is should you *never* create new instances inside of a computed? Or more specifically should you *never* create new instances with observables inside of a computed? I didn't see a rule for that, but it's likely I just missed something. If that's something that you shouldn't do, is there a linting rule?

This bug happens when you:

1. Attempt to change an observable property
2. In the constructor
3. After calling a computed in that constructor that references that observable
4. Only when you are instantiating that object in the computed of another object

All 4 of those conditions have to be met, which is why it was tricky to debug. What is surprising to me is that the behavior of `       new Store("Open")` would be different depending upon whether it was called in the scope of a computed or not.

**Comment by mweststrate** [comment]
It is possible to create observables in computeds, but the good cases are rare, and your above example doesn't look like one of them. The stores in a mall aren't derived values, but stated. So you should rather model that using as `observable` rather than computeds. Instead of burning down all the stores and create new ones every day when you open the mall, you'd be better of if you just swap the signs on the door, something along these lines. Things that are 'addressable identities' are usually not derived values but state. E.g. 'the starbucks in the mall'. Closing that store doesn't make it a different store altogether, it just changes the state the store is in. 


```
class Mall {
   @observable store = new Store()

   openStore() { this.store.status = "open" }

    closeStore() { this.store.status = "closed" }
}

class Store {
   @observable  status = "closed" 

   constructor(status) {
        this.status = status
    }

    @computed shouldClose() {
        return true // Imagine there's some actual logic here
    }

    @computed get isOpen() {
        return this.status === "Open" && !this.shouldClose()
    }
}
```

(shouldClose sounds more like a transition that should happen, rather than a state you can find a store in, in which case you might want to model it is an action instead). For more info check: https://mobx.js.org/intro/concepts.html

**Comment by breck7** [comment]
Thanks @mweststrate ! I guess my contrived test case obscured the issue.

Here's one that more closely mirrors our actual code. In this case:

1. The user can set certain Settings even if they are invalid (we preserve their invalid settings).
2. Dependent code can always derive a valid Settings object from the user's Settings.

```
import { observable, computed } from "mobx"

declare type choice = "apple" | "none"

class UserSettings {
    constructor(itemA: choice, itemB: choice) {
        this.itemA = itemA
        this.itemB = itemB
    }

    get validSettingsWORKS() {
        const clone = new UserSettings(this.itemA, this.itemB)
        if (clone.itemsAreEqual) clone.itemB = "none"
        return clone
    }

    @computed get validSettingsBREAKS() {
        const clone = new UserSettings(this.itemA, this.itemB)
        if (clone.itemsAreEqual) clone.itemB = "none"
        return clone
    }

    @computed get itemsAreEqual() {
        return this.itemA === this.itemB
    }

    @observable itemA: choice
    @observable itemB: choice
}

// Works
new UserSettings("apple", "apple").validSettingsWORKS

// Throws
new UserSettings("apple", "apple").validSettingsBREAKS
```

It seems to me very surprising that the exact same code breaks when in a computed. One way around this would be to have a rule of not creating new observables inside of a computed. The problem is here I'd need 2 near identical classes, one with observables and one without. (Unless there is an easy way to make an instance not observable?)
