### ISSUE TITLE
Mobile Responsiveness issue

### ISSUE THREAD

**Issue by Udit-singh** [mobxjs/mobx#2413]
# Mobx Footer Logo Alignment Fix.

**Description:** - Above the Docs section, the logo should be aligned with other section of the footer

**Screenshot:**

![Screenshot (610)](https://user-images.githubusercontent.com/55452299/88551347-63425f80-d040-11ea-9634-84f793563384.png)

**Environment:**

* OS: Windows
* Browser: Chrome
* View mode - iPhone 6/7/8  IOS
* Version: Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by mweststrate** [comment]
Feel free to take a shot at it (against the mobx6 branch)
