### ISSUE TITLE
mobx-undecorate adds import incorrectly when importing mobx types

### ISSUE THREAD

**Issue by charliematters** [mobxjs/mobx#2415]
**Intended outcome:**

`makeObservable` gets added to the non-type import

**Actual outcome:**
`makeObservable` gets added to the first import even i that is only a type import

**How to reproduce the issue:**

Transforming this file:
```
import type { IReactionDisposer } from "mobx";
import { reaction, observable } from "mobx";

export default class Store {
  @observable counter = 0;

  removeReaction: IReactionDisposer;
  
  constructor() {
    this.removeReaction = reaction(() => this.counter, () => {
      console.log("it changed");
    });
  }

  cleanup() {
    this.removeReaction();
  }
}
```

Becomes this:
```
import type { IReactionDisposer, makeObservable } from "mobx";
import { reaction, observable } from "mobx";

export default class Store {
  counter = 0;

  removeReaction: IReactionDisposer;
  
  constructor() {
    makeObservable(this, {
      counter: observable
    });

    this.removeReaction = reaction(() => this.counter, () => {
      console.log("it changed");
    });
  }

  cleanup() {
    this.removeReaction();
  }
}
```

**Versions**
mobx: 5.15.4
typescript: 3.9.7

**Comment by MoonBall** [comment]
The `makeObservable` doesn't exist in `mobx` code base. I think this problem is related to your transformer of code. 
@charliematters  Would you like to provide more information, such as a repo that can reproduce the bug?

**Comment by charliematters** [comment]
Just to be clear, this relates to the upcoming version 6, and you can find `makeObservable` [here](https://deploy-preview-2327--mobx-docs.netlify.app/refguide/observable.html) and [here](https://github.com/mobxjs/mobx/blob/mobx6/src/mobx.ts#L130). 

I suppose I didn't make the steps to reproduce clear, but if you have a file with the contents mentioned above and then run `npx mobx-undecorate` in that folder you will get the output seen below, which is incorrect.

I would make a PR, but in all honesty, I don't understand how the codemod project works!

**Comment by MoonBall** [comment]
@charliematters I made a PR to fix the issue. Thanks for reporting.

**Comment by MoonBall** [comment]
> I would make a PR, but in all honesty, I don't understand how the codemod project works!

I also don't know how the codemod works. I just search `makeObservable` in the src/undecorate.ts file, and debug those. 
Hope my experience can be useful for you.

**Comment by mweststrate** [comment]
Merged the fix, will release a new beta soon.
