### ISSUE TITLE
Typescript type of `values` from a mobx-state-tree map seems wrong.

### ISSUE THREAD

**Issue by rluiten** [mobxjs/mobx#2422]
**Intended outcome:**
The type returned by `values` function is correct for a model of type map.

**Actual outcome:**
The type returned by `values` is **not** correct for a model of type map.

**How to reproduce the issue:**
I was learning Mobx state tree, built a small app and discovered `values` appeared wrong.
I created a small example on codesandbox.io 
https://codesandbox.io/s/weathered-water-6q3d2?file=/src/App.tsx

This demonstrates 3 different ways to render a Map model, the first way using `values` produces a type error.
You can see the type error show at line 50, as the type of `todoListValues` does not appear to be correct.
Someone on the gitter mobx channel confirmed a likely problem and suggested I post an issue in mobx repository.

The code does appear to run correctly so only type error.

**Versions**
mobx 5.15.4
mobx-state-free 3.17.2

**Comment by mweststrate** [comment]
Confirmed, it looks like the type signature of `values` in mobx should also have overloads for plain `ReadonlySet`,`ReadonlyMap` and `ReadonlyArray` to correct this.

**Comment by MoonBall** [comment]
@mweststrate 
The reason for the current phenomenon is：
1. The type of `store.todos` is [`IMSTMap`](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/map.ts#L67).
2. [The function signature](https://github.com/mobxjs/mobx/blob/master/src/v5/api/object-api.ts#L45) of `values()` would take effect. 

If the IMSTMap can extends ObservableMap, the type of `values()`'s return value would be right. But the code seems to be deliberately bypassing `extends ObservableMap` from [the comment](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/map.ts#L68). 

I don't know how to fix the problem.

**Comment by mweststrate** [comment]
@MoonBall good observation, I _think_ it should be ok to add an `implements Map<string, IT["Type"]>` to the MST map, as the cast utilities can now be used to avoid the typescript errors when assigning with a snapshot rather than an instance. I'm not fully sure if that works correctly though, given the overloaded functions, but could be worth a try.

**Comment by MoonBall** [comment]
@mweststrate I made a pr to fix the type. But I don't know how to add test for ts type.

**Comment by mweststrate** [comment]
Closing here since it is now an open PR on MST

**Comment by jamonholmgren** [comment]
Which PR on MST?

**Comment by thezanke** [comment]
Bump. Seems to still be an issue.

**Comment by longnguyen2508** [comment]
Bumped. Which PR?
