### ISSUE TITLE
`observable.array.reduce` behaviour difference with `Array.reduce` in case `initialValue` not provided

### ISSUE THREAD

**Issue by rexpan** [mobxjs/mobx#2432]
`mobx@5.15.6` `observable.array.reduce` behaviour difference with `Array.reduce` in case `initialValue` not provided.

**Intended outcome:**

`observable.array.reduce(xs)` should operate like `Array.reduce(xs)`

**Actual outcome:**

`observable.array.reduce(xs)` operate like `Array.reduce(xs, undefined)`

**How to reproduce the issue:**

```js
import { observable } from "mobx";

const xs = [1, 2, 3];
console.log("native reduce");
xs.reduce((accumulator, currentValue, index) => console.log({accumulator, currentValue, index}));
// Object {accumulator: 1, currentValue: 2, index: 1}
// Object {accumulator: undefined, currentValue: 3, index: 2}

const ys = observable.array(xs);
console.log("observable array reduce");
ys.reduce((accumulator, currentValue, index) => console.log({accumulator, currentValue, index}));
// {accumulator: undefined, currentValue: 1, index: 0}
// {accumulator: undefined, currentValue: 2, index: 1}
// {accumulator: undefined, currentValue: 3, index: 2}
```

**Versions**

5.15.6 or below.
Note: 6-rc work correctly.

**Comment by FredyC** [comment]
In my opinion, it's always better to be explicit about initial value for reduce. For anyone reading your code, they don't have go through docs for that.

**Comment by urugator** [comment]
Good catch, working on it ... btw v6 is broken as well since yesterday :D
