### ISSUE TITLE
Fix typings, function properties should not be typed as methods

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx#2438]
Hello! In typescript there is distinction between methods (which depends on `this`) and just function properties, which is can be used unbound. Currently typescript doesn't lint it (https://github.com/microsoft/TypeScript/issues/7968), but there is eslint rule, which is really helpful (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md), especially in react codebases. Currently `@computed.struct` is defined as method and not a property, so eslint shout at me for it :) I fix it via custom typings, but I think it should be corrected at sources.

**Intended outcome:**
```ts
export interface IComputed {
    //...
    struct: (target: Object, key: string | symbol, baseDescriptor?: PropertyDescriptor) => void;
}
```

**Actual outcome:**
```ts
export interface IComputed {
    //...
    struct(target: Object, key: string | symbol, baseDescriptor?: PropertyDescriptor): void;
}
```

**How to reproduce the issue:**

**Versions**
Mobx 5 latest

**Comment by mweststrate** [comment]
I'm missing the problem here. Why is ESLint running on MobX code? Beyond that, that is a decorator signature which isn't bound to a `this` as it operates on prototypes, not instances.

**Comment by Amareis** [comment]
ESLint is running on my code. When I use decorator on my getter, eslint go to it's declaration and sees that it's declared as interface method and not as member function, so its decide what it expect proper `this`.
![image](https://user-images.githubusercontent.com/4806617/91306726-627b2580-e7c6-11ea-8bc6-b3dcc0f2b0a3.png)

**Comment by mweststrate** [comment]
Scary magical implicit behavior attached to a merely syntactical change. But feel free top open a PR on the v6 branch since I don't think it will harm anything.

**Comment by Amareis** [comment]
Actually, typescript is actually distinct those two syntaxes: https://stackoverflow.com/a/55992840/5576420
Can I make it PR to master too? Currently I use v5.

**Comment by mweststrate** [comment]
Neat,  never released that. Yeah feel free to open 2.

**Comment by Amareis** [comment]
Not staled

**Comment by Amareis** [comment]
Thanks! When it'll be released?
