### ISSUE TITLE
Find a new logo

### ISSUE THREAD

**Issue by fibric** [mobxjs/mobx#244]
During the [AMA](https://hashnode.com/ama/with-mobx-cinspo7i500vyxs53buh8ebls#cinssey9t00zqo75381sepfbd) on hashnode.com @mweststrate suggested developing ideas for a new logo.

Well, here we are.

Throwing some ideas:
- something related to the mafia
- something with cars
- something about observing
- something with the initials M & X maybe ;-)

**Comment by fibric** [comment]
While trying to get my hands warm, I came up with the idea of a silhouette of a detective. Maybe someone can produce a vector of my hand drawing. Or it's not wanted at all.

![mobx-detective](https://cloud.githubusercontent.com/assets/623932/15198640/f2ba4d3c-17d8-11e6-8d0e-3b8d3c317919.jpg)

**Comment by arahansen** [comment]
I'm actually a fan of the current logo. I think it would be cool to see a redesigned logo that still captures the essence or ideas of the current one.

**Comment by mweststrate** [comment]
@fibric cool :) Yeah I was thinking something along those lines as well indeed. Maybe with an X somewhere. I think referring to Mafia is very suitable for great jokes, as the Mob is kind of anti-state ;-).

cc @tetsuo

**Comment by tetsuo** [comment]
@fibric wow that looks great 👍

**Comment by iamakulov** [comment]
Is there any necessity to actually update the logo? If the current one is already spread, radically changing it will make MobX less recognizable.

I’m up to removing the shadow though:

![mobx](https://cloud.githubusercontent.com/assets/2953267/15207740/9f738fd2-1830-11e6-8458-447109e4dc47.png)

This shouldn’t affect recognizability as the `]x[` part is remaining unchanged.

**Comment by mweststrate** [comment]
btw, original SVG can be found here: https://github.com/mobxjs/mobx/blob/gh-pages/images/mobservable.svg

**Comment by iamakulov** [comment]
Yup, edited it too.

Inkscape source: http://svgur.com/s/5Z.
Plain source: http://svgur.com/s/5S. In this file, I’ve converted the text to path so it can be safely used on any computer and the `]x[` part is always visible.

**Comment by osenvosem** [comment]
May I propose a concept?
![logo-01](https://cloud.githubusercontent.com/assets/6762673/15267031/dbc3a41a-19be-11e6-8ca9-63a2be4dc5e7.png)

**Comment by tetsuo** [comment]
@osenvosem ok this is officially photoshop battle now 😸

![logo](http://i.imgur.com/IUV5ckA.png)

**Comment by osenvosem** [comment]
@tetsuo so cute))

**Comment by osenvosem** [comment]
Or something like this:
![mobx_logo2-02](https://cloud.githubusercontent.com/assets/6762673/15268456/eaa0d0ec-19e7-11e6-9d60-3617dddaf9f9.png)

**Comment by mweststrate** [comment]
@osenvosem I really like the idea :) can you somehow make it a bit more suitable for 1:1 aspect ratio?

**Comment by osenvosem** [comment]
@mweststrate how about this?
![mobx_logo](https://cloud.githubusercontent.com/assets/6762673/15321288/306c6c78-1c3e-11e6-9033-33d7a5382af0.png)
Here are `X` letter and vivid colours to emphasise reactivity.

**Comment by AriaFallah** [comment]
@osenvosem 

This is your best one yet, but it's a little annoying how the X on the tie doesn't align with the X on the hexagon. Not sure if that's just me.

**Comment by osenvosem** [comment]
@AriaFallah I did that intentionally to add a bit dynamics.

**Comment by andykog** [comment]
osenvosem's logo won't play nice in small size. Anyway I didn't get the idea (no offense). +1 for iamakulov's proposal
![logo-heroku](https://cloud.githubusercontent.com/assets/6760207/15321544/d7e63fa0-1c3f-11e6-8fd9-16adea4701f4.png)
.

**Comment by osenvosem** [comment]
@andykog the idea is portray "reactive state manager": tie, colours, `X` outlines. Small elements may be removed or increased in size.

**Comment by osenvosem** [comment]
We also can play with the letters:
![mobx_logo2](https://cloud.githubusercontent.com/assets/6762673/15322587/610a9686-1c46-11e6-995e-f647143dd99e.png)
![mobx_logo](https://cloud.githubusercontent.com/assets/6762673/15322586/610953fc-1c46-11e6-89bf-a7332be50a62.png)

**Comment by hellectronic** [comment]
I would not change the current logo. I am in favour of iamakulov suggestion to just remove the shadows. I like the current one and it is recognizable.

**Comment by mattruby** [comment]
+1 to keeping it the same - shadow

On Fri, May 20, 2016 at 11:01 AM, hellectronic <notifications@github.com>
wrote:

> I would not change the current logo. I am in favour of iamakulov
> suggestion to just remove the shadows. I like the current one and it is
> recognizable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mobxjs/mobx/issues/244#issuecomment-220646943>
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by mweststrate** [comment]
Tinkered it about a bit longer, and indeed the logo doesn't need a radical change. It is very recognizable, and has ascii art support `]v[` which is kinda fun in tweets and such. I leave this tread open until I, or someone else, finds the time to apply some minor tweaks and update the logo everywhere. At least the shadow should be removed, maybe the font should be a bit bolder, and a very subtly 'X' gradient, similar to the gradient in the tie by @osenvosem, might be cool as well.

Thanks for the input and refreshing ideas so far!

**Comment by AriaFallah** [comment]
@mweststrate 

Does `]v[` mean something except looking like an M? I was wondering if `][` has some kind of mathematical significance or something.

**Comment by mweststrate** [comment]
eh nope a cooler story would be nice, but it is just an M 😐

Op ma 23 mei 2016 23:41 schreef Aria Fallah <notifications@github.com>:

**Comment by osenvosem** [comment]
@mweststrate 
![mobx_logo](https://cloud.githubusercontent.com/assets/6762673/15496082/14b232f2-219c-11e6-90b1-7e5e7ba195ac.png)

**Comment by hellectronic** [comment]
@mweststrate @AriaFallah don't you see it? "] [" indicates an open interval an v is a value in an open intervall of changing values :D

**Comment by SenerDemiral** [comment]
Please look http://blog.typekit.com/2013/08/14/understanding-letters/

**Comment by arahansen** [comment]
Ooh I'm a fan of @osenvosem s latest

**Comment by mweststrate** [comment]
me too! one question @osenvosem, was the font change intentional? or just missing? from the top of my head the original font is the Ubuntu font, with the slightly curved V.

**Comment by mweststrate** [comment]
also the new color is really nice!

**Comment by andykog** [comment]
May be something like a real «`M`»? 
![m](https://cloud.githubusercontent.com/assets/6760207/15515890/e60faa3a-21f8-11e6-8e39-affe13b5094c.png)
(ascii representation is ]V[, with capital `V` :-)

**Comment by osenvosem** [comment]
@mweststrate just played with fonts and this one seemed quite pretty. This is Ubuntu, it also looks nice:
![mobx_logo](https://cloud.githubusercontent.com/assets/6762673/15517113/bd92f444-21fe-11e6-8492-719c51d32715.png)

**Comment by PhiLhoSoft** [comment]
Some days ago, I though "Hey, would be nice if MobX had a logo".
Then I went to the repository, and saw the `]v[` again. "Mmm, maybe that's the logo, after all".
But I hardly made the connection between a v between brackets and a "MobX"... Until I winked a lot and saw the M. :pensive: 

So, yes, I am among those thinking that a new logo would be nice... Will give some thoughts about it... :smile: 

I find logos of the React ecosystem nice, in general. Pets are popular too (see SugarCSS' logo, for example). @andykog's proposal has the merit of not going too far of the original one while being more understandable.

**Comment by PhiLhoSoft** [comment]
I just drew a few ideas. Sorry for the low quality, both of drawings and image, but it is just as RFC. I can clean up to SVG if needed...
![mobxlogos](https://cloud.githubusercontent.com/assets/1087902/15576017/07db4c42-2356-11e6-9727-320d30844aaf.jpg)
The first one, I started by drawing a nice big M. Then I thought it looked familiar, I added a semi-cursive X, and stopped here in fear MTV sues me... :smile: 
The second one was based on the idea of "observing", stylizing a binocular into a M, adding the X as a kind of trademark...
The third one is a poor attempt at showing how MobX manages dependencies, trying to get more abstract.
The last one also builds on the binocular idea... :wink:

**Comment by andykog** [comment]
@PhiLhoSoft, are there some kind of bugs inside binoculars? :-D

**Comment by PhiLhoSoft** [comment]
Aha! No bugs in MobX, of course!
Naw, it was supposed to be some kind of shadow / reflect to show these are glasses. Made with a fat marker on a small surface => ugly. :laughing:

**Comment by mweststrate** [comment]
I think @osenvosem logo enhancement (the latest one) is the best option :). Would you mind sharing the SVG / source files? thanks!

**Comment by osenvosem** [comment]
@mweststrate Sure.
[MobX_logo.zip](https://github.com/mobxjs/mobx/files/313634/MobX_logo.zip)
