### ISSUE TITLE
mobx.configure discrepancy: computedConfigurable

### ISSUE THREAD

**Issue by msteitle** [mobxjs/mobx#2443]
**Summary:**
Official documentation for the API Overview lists the configuration option `computedConfigurable`.
https://mobx.js.org/refguide/api.html#computedconfigurable-boolean

However, in the current codebase for v6.x, this option has been removed.
- https://github.com/mobxjs/mobx/blob/5536533ed26d6bd8c7989b49990994daa3831009/docs/faq/migrate-to-6.md#obscure-things-that-dont-work-anymore-but-that-probably-wont-affect-you
- https://github.com/mobxjs/mobx/blob/mobx6/src/api/configure.ts

**Conclusion:**
I was going to create a PR to fix it myself, but I found that it has already been removed. So it appears that the current documentation content just needs to be deployed.

**Comment by mweststrate** [comment]
V6 is not released yet, so the docs describe current master.

**Comment by msteitle** [comment]
That would explain it. Thanks.
