### ISSUE TITLE
autorun callback will be never invoked if Map.Object.Value had been changed

### ISSUE THREAD

**Issue by Aqours** [mobxjs/mobx#2446]
**Intended outcome:**
autorun callback invoke twice

**Actual outcome:**
autorun callback invoke once

**How to reproduce the issue:**
1. Open https://codesandbox.io/s/kind-solomon-hi6ju?fontsize=14&hidenavigation=1&theme=dark
2. Open Console

**Versions**
MobX: 4.15.6 / 5.15.6

**Comment by mweststrate** [comment]
See https://mobx.js.org/best/react.html#common-pitfall-consolelog. Make
sure that the actual values you are interested in are used in the autorun,
or use `toJS` util (to be imported from MobX, not the toJS on Map, that is
deprecated as it works only shallowly)

**Comment by Aqours** [comment]
O, thank you. I don't realize that Observable.toJS is not equal to MobX.toJS
