### ISSUE TITLE
autorun callback invoke sequence is out of order

### ISSUE THREAD

**Issue by Aqours** [mobxjs/mobx#2447]
**Intended outcome:**
first
second

**Actual outcome:**
second
first

**How to reproduce the issue:**
1. Open https://codesandbox.io/s/stoic-butterfly-j07gx?fontsize=14&hidenavigation=1&theme=dark
2. Open Console

**Versions**
MobX: 4.15.6

**Details**
It seems only bug in mobx-4 version.
autorun callback invoke sequence is correct when `this.isOk = false`.

**Comment by FredyC** [comment]
Please, never rely on the order of reaction execution. It's a fragile pattern. Each reaction should be completely isolated and have no expectations.

**Comment by mweststrate** [comment]
See also https://deploy-preview-2327--mobx-docs.netlify.app/refguide/autorun.html#use-reactions-sparingly for some background

**Comment by Aqours** [comment]
Shall we add some documentations?
I view documentation on https://mobx.js.org/README.html, but I'm not find the url which your are posted.

**Comment by FredyC** [comment]
@Aqours That's new documentation coming with the upcoming MobX V6. It contains the most up-to-date information so I recommend reading through it.

**Comment by lillallol** [comment]
So when an `action` changes the state, that means that there is no guarantee that the `reaction`s will execute in creation order. So that begs the following questions:

1. Do `observer`s execute in creation order?
1. What is the reasoning behind executing `reaction`s not in creation order?
