### ISSUE TITLE
isPlainObject() to support objects from another window

### ISSUE THREAD

**Issue by ConneXNL** [mobxjs/mobx#2448]
So I've been running into an issue where I have multiple browser windows, one window holding the state, and the other windows rendering various UI referencing the main window's mobx state.

However, I am running into problems whenever I try to set values with Mobx/MST as the implementation of isPlainObject() in Mobx&MST uses the local window's Object prototype to check if it is an object.

However, when you have multiple windows the Object.prototype of window A !== Object.prototype of window B, thus the below check fails. My setup is really unique but I think apps using Election-like technology might also suffer from this.

Here are the implementation of isPlainObject MobX and MST (found in the utils.ts):
https://github.com/mobxjs/mobx/blob/6ec6499fb8b55a17fe65f42b14d1188fd7fa1ba1/src/utils/utils.ts#L82-L86

https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/utils.ts#L123-L127

So far I have been patching MobX and Mobx-State-Tree to use https://github.com/jonschlinkert/is-plain-object but I figured it might make more sense to see if you are open to change the isPlainObject implementation.

Would you be willing to change isPlainObject() implementation?

**Comment by FredyC** [comment]
Might be worth investigation for the upcoming V6, but I don't we will be backporting since nobody else is interested.

Would you be willing to work on PR?

**Comment by ConneXNL** [comment]
Added a pull request that fixes the issue and doesn't require an external library or much changes.

**Comment by hartum** [comment]
> So I've been running into an issue where I have multiple browser windows, one window holding the state, and the other windows rendering various UI referencing the main window's mobx state.
> 
> However, I am running into problems whenever I try to set values with Mobx/MST as the implementation of isPlainObject() in Mobx&MST uses the local window's Object prototype to check if it is an object.
> 
> However, when you have multiple windows the Object.prototype of window A !== Object.prototype of window B, thus the below check fails. My setup is really unique but I think apps using Election-like technology might also suffer from this.
> 
> Here are the implementation of isPlainObject MobX and MST (found in the utils.ts):
> 
> https://github.com/mobxjs/mobx/blob/6ec6499fb8b55a17fe65f42b14d1188fd7fa1ba1/src/utils/utils.ts#L82-L86
> 
> https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/utils.ts#L123-L127
> 
> So far I have been patching MobX and Mobx-State-Tree to use https://github.com/jonschlinkert/is-plain-object but I figured it might make more sense to see if you are open to change the isPlainObject implementation.
> 
> Would you be willing to change isPlainObject() implementation?

Hi @jrmyio 
I am trying to establish communication between two windows using the same store, but when I modify the store from one the other one does not react, it seems as if they were two different instances of the store. How did you solve this?

**Comment by mweststrate** [comment]
MobX can't track changes across windows, as these are completely different scripting contexts and MobX instances.

**Comment by jrmyio** [comment]
@hartum What I do is I make sure the child windows use the same mobx export from the main window.
I use webpack aliases for the subwindows to grab the mobx functions from the main window.

However, I only using this setup in a 'electron'-like environment, I have not tested it with iframes etc.

This issue was purely done to at least accept snapshot objects that are created in the child window.

**Comment by hartum** [comment]
Finally I solved through localStorage, thanks both
