### ISSUE TITLE
Would MobX play nicely with VueJS?

### ISSUE THREAD

**Issue by makeitrein** [mobxjs/mobx#245]
Just started a new VueJS pet project, does anyone have experience with using MobX for state management rather than the default VueJS implementation? 

Would love to be able to use MobX @computed syntax at the store level, not sure if this is a good idea or not.

Thx!

**Comment by capaj** [comment]
@makeitrein I think some people use MobX with Angular, so it should be possible, but I would probably stick to the state management built in to Vue. I have no idea how they implement it, but everywhere I look I see that vue handles reactivity for you via some "proxyiing". I would be very interested in how they do it.
For example here:
http://blog.evanyou.me/2015/10/25/vuejs-re-introduction/
and
https://vuejs.org/guide/application.html#State-Management

So yes it would. Is it a good idea? Probably not. Unless their implementation of observables and observation is slow.

**Comment by jordan2b1** [comment]
@capaj - thx for the answer, I ended up dropping Vue - React + MobX is the sweet spot I've been finding for front-end JS projects.
