### ISSUE TITLE
change mobx array<object> will not fire computed

### ISSUE THREAD

**Issue by jackple** [mobxjs/mobx#2453]
```ts
  @observable
  list = [
    { id: 0, a: 0, b: true },
    { id: 1, a: 1, b: false }
  ];

  @computed
  get computedList() {
    console.log(this.list);
    return this.list.filter((l) => l.a);
  }

  @action
  updateA = () => {
    const item = this.list.find((l) => l.id === 0);
    item.a = 1;
  };

  @action
  updateB = () => {
    const item = this.list.find((l) => l.id === 0);
    item.b = false;
  };
```

If I do not use `l.b` in `computed`, it will not run?
I think all the changes on `this.list` will fire computed

Here is the demo: https://codesandbox.io/s/wandering-sound-ud6zv?file=/src/store.js:354-772

**Comment by jackple** [comment]
The component had been updated, it's just no log.

**Comment by FredyC** [comment]
> If I do not use `l.b` in `computed`, it will not run?

Exactly. It's a whole difference to change the length of array (push, pop) and change properties on objects within that array. If you do not access that property than MobX has no way knowing you are interested in updates. And that's perfectly fine. Why it should update on change of something you don't care about?
