### ISSUE TITLE
React Navigation with MobX

### ISSUE THREAD

**Issue by chongchungyin** [mobxjs/mobx#2456]
Hi guys,

I am using MobX for my React Native project. I noticed that if i have multiple screens in one stack, if those screens are observing same observable, it will cause all the screens rerender even if screens are in backstack. Is there anyway we can stop screen observing changes?

**Comment by mweststrate** [comment]
make the rendering conditional based on whether you are in the backstack?

**Comment by chongchungyin** [comment]
i tried using `useIsFocused` in react navigation to fix this problem. Overall is working fine but this solution is a bit ugly. Wondering is there any cleaner way to unsubscribe the observable.

**Comment by urugator** [comment]
You can also experiment with conditional `untracked`
```javascript
function Cmp() {
  const render = () => {}
  if (isForeground) { // ger from props or ctx
    return render()
  } else {
    return untracked(render())
  }
}
```
Similary you can conditionally wrap the render in `<Observer>`
Obviously you have to do it for every component.

**Comment by chongchungyin** [comment]
@urugator nice one. for those having same issue can try this.
`
import {untracked} from 'mobx';
import {useIsFocused} from '@react-navigation/native';

export default (component) => {
  const screenVisible = useIsFocused();
  if (screenVisible) {
    return component;
  } else {
    return untracked(() => {
      component;
    });
  }
};`

**Comment by zangornjak** [comment]
@chongchungyin are you satisfied with the solution and can this issue be closed?
