### ISSUE TITLE
[v6] Weird buggy behavior with when

### ISSUE THREAD

**Issue by olee** [mobxjs/mobx#2458]
Mobx `when` does not seem to run in most situations and I wasn't able to identify the cause yet.

[Code Sandbox](https://codesandbox.io/s/concepts-principles-forked-9d3df?file=/src/index.js)
```
import { makeAutoObservable, when, runInAction, observable } from "mobx";

class TestStore {
  data;
  constructor() {
      makeAutoObservable(this);
  }
}

const store1 = new TestStore();

console.log('start');

when(() => Boolean(store1.data), () => console.log('when 1'));

runInAction(() => {
  when(() => Boolean(store1.data), () => console.log('when 2'));
});

runInAction(() => {
  when(() => Boolean(store1.data), () => console.log('when 3'));
  when(() => Boolean(store1.data), () => console.log('when 4'));
  store1.data = observable({});
});

console.log('end');
```

Normally I would expect this to log all the messages (and it did in older mobx versions), but for some reason only `when 3` and `when 4` are logged.

**Comment by olee** [comment]
Also, calling 
```ts
observe(store1, 'data', change => console.log(change));
```
will throw an error `[MobX] no observable property 'data' found on the observable object 'TestStore@1'`

**Comment by olee** [comment]
Ok I found out, that my transpilation did not use define for class fields yet, so uninitialized properties would not be available for mobx to decorate.

Changing `data;` to `data = undefined;` actually fixed the issue.

However, I think that using decorators or explicit makeObservable annotations should still be able to make properties obserable, even if they have not been defined on the target yet.

**Comment by mweststrate** [comment]
`makeObservable(this, { data: observable })` should work. However, you are using `makeAutoObservable`. Since `data;` literally doesn't result in any code after transpilation if you don't enable use-define-for-class-fields, there is no predict that the `data` field is eventually going to exist. So you will either need to enable use-define, or initialize the field with `undefined`, or `useMakeObservable` instead.

**Comment by olee** [comment]
No, it does not work with `makeObservable(this, { data: observable })`: https://codesandbox.io/s/concepts-principles-forked-mujs5?file=/src/index.js

I also thought that this would work, but it tells me `[MobX] Cannot decorate undefined property: 'data'`

**Comment by mweststrate** [comment]
ah yes, that is indeed a hardcoded safety check to catch typos and such. So
I guess either change config, initialize it explicitly, or you could also
grab extendObservable instead which does allow it. Because without
decorators, declaration and annotation are at separate locations in the
code, these checks have been added to catch mistakes early.

**Comment by olee** [comment]
Does `extendObservable` otherwise behave exactly like `makeObservable` in that it reads decorators and can add computeds and actions?

**Comment by mweststrate** [comment]
From top of my head they have the same signatures indeed.

**Comment by olee** [comment]
I think it should still be possible to use `makeObservable` without requiring the fields to be defined beforehand.
There might be various cases where this could be useful.

Anyway, using `extendObservable` like this instead does work (though there seems to be a bug in the signature - see comment):
```ts
class TestStore {
    @observable
    data?: any;
    constructor() {
        // Even though typescript says it requires only one arg, it crashes at runtime if only one arg is passed
        extendObservable(this, {});
    }
}
```

However, this would mean I always have to use `extendObservable` instead of `makeObservable`, which would kinda defeat the purpose of `makeObservable`.
Maybe we could add some kind of `configure` option which could disable the safety check which verifies that a property is defined before making it observable.

**Comment by mweststrate** [comment]
Fixed `extendObservable` not requiring 2 arguments. 

The safety check should normally not bee needed if use define for fields is enabled, which is a requirement (although most things work without as well, it is not officially supported). I think having yet another configuraiton option just adds maintenance burden and confusion. I think trying to make undeclared fields observable is an anti pattern (in a typed environment you typically don't have those fields), and as shown there is already an api that does support it, `extendObservable`. 

So closing this one. Thanks for pointing it out though!

**Comment by olee** [comment]
> in a typed environment you typically don't have those fields

Well you have, if define-for-fields is not enabled - which is what I was experiencing here.
To elaborate a bit - it was working for me in webpack, but broken in jest.

**Comment by mweststrate** [comment]
as said, you _should_ have define-for-fields enabled. So this error signals
a config mistake in your babel or typescript setup. So rather than silently
ignoring that, throwing is the better fail fast behavior.

**Comment by olee** [comment]
That's the question - why **should** it be enabled?
Is there any reason for it, especially when it actually enlarges transpilation size quite a bit?

**Comment by mweststrate** [comment]
It is the spec compliant behavior, the current isn't. So the size problem
will sort itself in time. If you really prefer to old behavior the simplest
solution is to stick to MobX 5 or apply the work arounds suggested here.

Op za 26 sep. 2020 11:47 schreef Björn Zeutzheim <notifications@github.com>:

**Comment by olee** [comment]
Well I'd still like to use latest mobx for the various improvements and size reduction though.
Also right now there might be various build setups that do not allow users to enable define-for-fields transpilation.
But for now I guess I'll have to adjust the jest config to use the same options as webpack (which I should do anyway).
