### ISSUE TITLE
question: what is the best way to make an observable object plain again?

### ISSUE THREAD

**Issue by capaj** [mobxjs/mobx#247]
let's say I have
```javascript
const a = observable({a: 1, b: 2})
```
How can best convert my object back to plain javascript object?
I realize, I could use _.cloneDeep(a) or JSON.parse(JSON.stringify(a)) but I just wonder-wouldn't it be a good idea if MobX provided a utility to do this?
For example I imagine it would be super heplful for arrays-because when you make an array observable using  _.cloneDeep(a) won't get it back to a regular array.
And JSON.parse(JSON.stringify(a))  seems a bit hacky...

**Comment by AriaFallah** [comment]
http://mobxjs.github.io/mobx/refguide/tojson.html

**Comment by capaj** [comment]
@AriaFallah I thought that toJSON() would give me a JSON string. hmm okay, thanks. I guess that is good enough.

**Comment by andykog** [comment]
Yeah, I'd better call it `toJS`, like [Immutable.js](http://facebook.github.io/immutable-js/docs/#/Iterable/toJS) do.

**Comment by capaj** [comment]
@andykog oh please, let's make that happen. This is just plain confusing.

**Comment by andykog** [comment]
@mweststrate, we could introduce `toJS` and keep `toJSON` as an alias, what do you think?

**Comment by mweststrate** [comment]
I agree you guys are right

**Comment by jefffriesen** [comment]
This confused me too and why I built my own function to convert an observable to a non-observable.

**Comment by mweststrate** [comment]
`toJSON` will be renamed to `toJS` in **]v[** 2.2
