### ISSUE TITLE
Upgrading mobx to 6.0.0 and mobx-react 7.0.0 not working

### ISSUE THREAD

**Issue by DavisJaunzems** [mobxjs/mobx#2478]
I was trying to replicate simple mobx-react application using the Todo example. After spending some time I've realized that using `mobx` 6.0.0 together with `mobx-react` 7.0.0 is not working.

**Intended outcome:**

Working Todo example application

**Actual outcome:**

Not working after upgrading to `mobx` 6.0.0 and `mobx-react` 7.0.0

**How to reproduce the issue:**

I've created two sandbox environments where everything is the same only using different `mobx` and `mobx-react` versions:

Working: https://codesandbox.io/s/reverent-booth-ehmz0?file=/src/index.js
Not working: https://codesandbox.io/s/confident-cray-2wl0y?file=/src/index.js

**Versions**

Working: mobx "5.15.7" and mobx-react "5.4.4"
Not working: mobx "6.0.0" and "mobx-react" "7.0.0"

**Comment by mweststrate** [comment]
Please read release announcements or migrations guides first when bumping major versions. We write that stuff for a reason https://mobx.js.org/migrating-from-4-or-5.html / https://michel.codes/blogs/mobx6
