### ISSUE TITLE
React development build warning for getting started tutorial page

### ISSUE THREAD

**Issue by palerdot** [mobxjs/mobx#2479]
https://mobx.js.org/getting-started - This link shows **React development build warning** (*attached screenshot*).

Rest of the site is static and I just noticed this tutorial page is running React's development build. Not sure if this is intentional. If not intentional, it is better to switch to production build (IMHO might not be a good impression for first time MobX users). 

![Screenshot 2020-10-02 at 11 44 40 PM](https://user-images.githubusercontent.com/4299398/94956300-93f3b900-0509-11eb-9525-51d362e2c884.png)

**Comment by mweststrate** [comment]
Yes that is intentional; it is an interactive coding pad

Op vr 2 okt. 2020 19:20 schreef Arun Kumar <notifications@github.com>:

**Comment by palerdot** [comment]
Ok. Let me close this issue then.
