### ISSUE TITLE
about makeAutoObservable

### ISSUE THREAD

**Issue by dpudpu** [mobxjs/mobx#2480]
I'm not sure that is your purpose.

### documentation
makeAutoObservable
Usage:
```
makeAutoObservable(target, overrides?, options?)
```

### code
```typescript
export function makeAutoObservable<T extends Object, AdditionalKeys extends PropertyKey = never>(
    target: T,
    excludes?: AnnotationsMap<T, NoInfer<AdditionalKeys>>,
    options?: CreateObservableOptions
): T {
```

`overrides` in documentation, `excludes` in code

I think overrides and excludes are different. It's confusing.

**Comment by zangornjak** [comment]
If you can, please PR corrections for such minor inconsistencies when you spot them. In my opinion overrides is more suited since you can in fact override, and not just exclude (`false`) when using `makeAutoObservable`.

It was probably meant to get changed, but got overlooked.

**Comment by dpudpu** [comment]
thank you for your answering. I will do PR.
