### ISSUE TITLE
Update documentation for useAsObservableSource hook

### ISSUE THREAD

**Issue by marko-hologram** [mobxjs/mobx#2487]
Hello,

Sorry in advance if this is something that is already planned or in progress, but reading through the React integration part in the docs (https://mobx.js.org/react-integration.html) I noticed few small "problems" with the part of the documentation that mentions `useAsObservableSource` hook (https://mobx.js.org/react-integration.html#computed-props).

1. Link pointing to `useAsObservableSource` doesn't point to the proper place. It points to this https://github.com/mobxjs/mobx-react#useasobservablesource-hook. This section doesn't exist on `mobx-react` github page, but it does exist on `mobx-react-lite` (https://github.com/mobxjs/mobx-react-lite/#useasobservablesourcetsource-t-t-deprecated)
2. `useAsObservableSource` is deprecated as indicated here https://github.com/mobxjs/mobx-react-lite/tree/master#useasobservablesourcetsource-t-t-deprecated and here https://github.com/mobxjs/mobx-react-lite/blob/master/src/useAsObservableSource.ts#L8

I know that having a warning in development is a good way to get notified about this, but maybe adding some info about deprecation in docs directly would just make it more obvious this isn't really a recommended hook to use anymore.

Also, I wasn't sure if I should open this issue in `mobx-react` repo because the topic is this React hook, but it's also about docs and those are located in this main repo here.

I didn't just want to randomly open a PR because I didn't know if this is something you would want addressed and how should it actually be addressed it if you want it to be addressed.

**Comment by mweststrate** [comment]
Hmm that looks like some changes in the docs were list :/. It should be
using useEffect instead to sync the prop into the observable.

**Comment by marko-hologram** [comment]
> Hmm that looks like some changes in the docs were list :/. It should be using useEffect instead to sync the prop into the observable.

You want me to maybe create a PR to update this? I can probably do it today/tomorrow.

If I understand it correctly, it should just use `offset` inside `useLocalObservable` and update it inside a `useEffect`, is that correct? And remove `useAsObservableSource` entirely from that example.

Also then, the link and any reference to `useAsObservableSource` should probably be removed from that part of docs.

**Comment by mweststrate** [comment]
Yes, all correct. PR would be great!

**Comment by mweststrate** [comment]
Thanks for the PR!
