### ISSUE TITLE
Document that makeAutoObservable for generators is not fool-proof

### ISSUE THREAD

**Issue by DeanIfalo** [mobxjs/mobx#2492]
Hi guys, I tested makeAutoObservable automatically infers generators to be flows. (mobx 6.0.1)
The source code is below.
```
import { autorun, flow, makeAutoObservable } from "mobx";

function delay(t: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, t);
  });
}

class Doubler {
  value = 0;

  constructor(value: number) {
    this.value = value;

    makeAutoObservable(this);//!!
  }

  *increment() {
    yield delay(1000);
    return ++this.value;
  }
}

const doubler = new Doubler(10);

autorun(() => {
  console.log("value:", doubler.value);
});

doubler.increment();
```
I only get `value: 10` printed once in the log, and the increment method will not trigger the notification that the value has changed.
when I added the @flow decorator to the increment method, I got the same result.

if I use the same way as the flow + generator function example in this [page](https://mobx.js.org/actions.html#asynchronous-actions) and change the code to `makeAutoObservable(this, { increment: flow });`, I can get the expect result.
```
value: 10
value: 11
```

Is this a bug, or is it necessary to add annotation manually?

**Comment by mweststrate** [comment]
It shouldn't matter, in fact, even when not using flow at all it still
should print twice. Would you mind putting this in a sandbox so that we can
look at running code?

**Comment by DeanIfalo** [comment]
Here, in a sandbox
https://codesandbox.io/s/clever-mendeleev-7rvx1?file=/src/index.ts

**Comment by DeanIfalo** [comment]
@mweststrate 
https://codesandbox.io/s/purple-currying-kmhdz?file=/src/index.tsx
Above with React Typescript template will run correctly. The result seems to depend on the typescript compiler.
The js compiled with babel above runs correctly. By the way, I actually like to use babel to compile typescript.😊

**Comment by mweststrate** [comment]
Yes, there is currently no fool proof way in JavaScript to detect generators. so makeAutoObservable might not always detect them. Annotating manually with `flow` should work in any environment.

**Comment by mweststrate** [comment]
Updated docs

**Comment by DeanIfalo** [comment]
Hi @mweststrate, I found mobxjs/mobx-state-tree#279

Change the codesandbox [project](https://github.com/mobxjs/mobx/issues/2492#issuecomment-704788153) tsconfig.json to below can avoid this issue.
```
"compilerOptions": {
    "strict": true,
    "target": "ES6", //add
    "module": "commonjs",
...
```

Or modify the mobx [source code](https://github.com/mobxjs/mobx/blob/509de1d45c0b6a829652089e6fd8010a0014589b/src/utils/utils.ts#L91)  through this [suggestion](https://github.com/mobxjs/mobx-state-tree/issues/279#issuecomment-319507696).

Regards.
