### ISSUE TITLE
Document makeObservable + private fields

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#2497]
I have protected methods, and I need to make them in to actions however, the typescript complains that they don't exist.
The code looks like this:
```js
    makeObservable(this, {
      play: action,
      stop: action,
      pause: action,
      resume: action,
      // @ts-ignore - protected methods
      disposePlayer: action,
      initPlayer: action
    })
```

_Originally posted by @ivandotv in https://github.com/mobxjs/mobx/discussions/2490_

**Comment by mirbeksm** [comment]
[makeObservable](https://mobx.js.org/observable-state.html#makeobservable) page mentions limitations.

You should be able to use 

~~~
makeObservable<StoreClass, 'myPrivateField1'| 'myPrivateField2'>({
    ...
    myPrivateField1: action
})
~~~

**Comment by ivandotv** [comment]
This has been documented here:
https://mobx.js.org/observable-state.html#limitations
Haven't noticed it before.
Also, I can't find the coresponding document in the repository, and the link to edit the document (from the mobxjs site) is 404.

**Comment by leader22** [comment]
I've submitted PRs to fix these 🙌 

- for TypeScript notes: #2517 
- for EDIT button: #2518

**Comment by a-guerrero** [comment]
A non-class based approach can also be an option, right? this worked for me:
```ts
import { makeAutoObservable, observable } from "mobx";

const WithPrivates = () => {
  const privateObservable = observable({
    counter: 0,
  });

  return makeAutoObservable({
    increase() {
      privateObservable.counter += 1;
    },
    get counter() {
      return privateObservable.counter;
    },
  });
};
```
