### ISSUE TITLE
`makeAutoObservable` doesn't work on uninitialized member

### ISSUE THREAD

**Issue by glacjay** [mobxjs/mobx#2498]
I'm not sure whether it's intentional or not.

[CodeSandbox](https://codesandbox.io/s/minimal-observer-forked-d90d5?file=/src/index.tsx)

This is a fork of the example from [here](https://mobx.js.org/react-integration.html), and I just delete the initial value of line 7.

If a member should have initial value, then there may be a bug in the example of [here](https://mobx.js.org/lazy-observables.html).

**Comment by DeanIfalo** [comment]
Same as the class Message in [here](https://mobx.js.org/understanding-reactivity.html).
Reproduce the problem: https://codesandbox.io/s/serverless-microservice-p6gfm?file=/src/index.js:139-164
Should be changed to
```
constructor(title, author, likes) {
        this.title = title
        this.author = author
        this.likes = likes
        makeAutoObservable(this)
    }
```
There may be more such places in the documentation.

**Comment by kubk** [comment]
Try to add `"useDefineForClassFields": true,` inside `compilerOptions` in your tsconfig.json
It's described in the migration guide: https://mobx.js.org/migrating-from-4-or-5.html#getting-started
