### ISSUE TITLE
mobx-undecorate fails if path contains folders with " " in their name

### ISSUE THREAD

**Issue by akraines** [mobxjs/mobx#2506]
mobx-undecorate fails if path contains folders with " " in their name
eg /test/Folder Name/Test
fails

**Comment by akraines** [comment]
macos / zsh

**Comment by mweststrate** [comment]
Added a unit test, and verified it manually, but spaces in paths are processed fine. So probably it is a local or different issue, so please provide a reproduction.

**Comment by akraines** [comment]
Thank you for taking the time to look into it! I will update you when I get a chance to test it again
