### ISSUE TITLE
The async /await example in the actions section lacks the async keyword

### ISSUE THREAD

**Issue by ilovedesert001** [mobxjs/mobx#2508]
I took a look at the docs folder, it was normal. But the document site displayed abnormally.

![image](https://user-images.githubusercontent.com/15065396/95735661-b0d17e80-0cb7-11eb-836c-3016fd4e8393.png)

chrome:Version 84.0.4147.135 (Official Build) (64-bit)
safari:Version 13.1.2 (15609.3.5.1.3)

**Comment by FredyC** [comment]
Yea, it was fixed recently in #2488, but it's not deployed. It will be there soon. Thanks for the report.
