### ISSUE TITLE
Fix several broken links in docs

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2509]
Just noticed this with the manual build of docs. Is anyone willing to fix those? Help wanted :)

![image](https://user-images.githubusercontent.com/1096340/95748211-eff0d700-0c99-11eb-8963-33ef3a6919ff.png)

**Comment by mweststrate** [comment]
Are you building the right version? The dir structure was flattened 2 weeks
ago.

**Comment by FredyC** [comment]
Ah, you are right, must have been something old, but one warning is there :)

![image](https://user-images.githubusercontent.com/1096340/95788251-78dc3280-0cdb-11eb-9573-eaaa2e7254a4.png)

**Comment by ilovedesert001** [comment]
> Ah, you are right, must have been something old, but one warning is there :)
> 
> ![image](https://user-images.githubusercontent.com/1096340/95788251-78dc3280-0cdb-11eb-9573-eaaa2e7254a4.png)

According to the description in the old document
