### ISSUE TITLE
Updated Observables in Flow after Yield Don't Trigger Reactions

### ISSUE THREAD

**Issue by davidgolden** [mobxjs/mobx#2519]
I'm not completely sure if this is a bug, but it seems like strange behavior to me if it's not. There is already a test for a very similar scenario here https://github.com/mobxjs/mobx/blob/mobx6/test/v5/base/flow.js#L46, except the behavior I'm interested is when `shouldThrow == false` on line 59.

**Intended outcome:**

I would expect that when there are no errors thrown in a flow try block, the function would continue on after the yielded promise is fulfilled, and any observable values updated after that point would trigger reactions. I would expect that after setting `shouldThrow = false`, the expected value of `values` would be `[1, 2, 5, 4]`, but this doesn't happen. However, the value of `v` is 4, which I would expect meaning that `x.a = 4` is executed but does not trigger a reaction.

**Actual outcome:**

The actual outcome is that the resulting value of `values` is `[1, 2, 5]` and this test passes.

**How to reproduce the issue:**

This can be reproduced by simply setting `shouldThrow` to be `false` in the above test.

**Versions**

MobX 6.0.1

**Comment by mweststrate** [comment]
I couldn't fully parse the question. Please create either a PR with test or a sandbox

**Comment by davidgolden** [comment]
Sorry! I think there are a couple things going on. I started using flows in my codebase when I upgraded to v4 a while back and the documentation read 
> However, a nicer approach is to use the built-in concept of flows. They use generators. Which might look scary in the beginning, but it works the same as async / await. Just use function * instead of async and yield instead of await. The advantage of flow is that it is syntactically very close to async / await (with different keywords), and no manually action wrapping is needed for async parts, resulting in very clean code.

Comparing that to the current documentation, it sounds like flows are now unnecessary for async functions with actions past the await, and that they basically function as a drop-in replacement for async actions?

The other confusion is that based on the current documentation, I would expect a flow to function the same as an async action, is this not the case? Here is a sandbox demonstrating the difference I am seeing. https://codesandbox.io/s/lucid-sun-w84zv?file=/src/index.js

**Comment by ilovedesert001** [comment]
> https://codesandbox.io/s/lucid-sun-w84zv?file=/src/index.js

I think this should be the expected behavior , 
Because 
```
  try {
    fo.a = yield delay(100, 2, false); // and this as well!
    fo.a = 3;
  } finally {
    fo.a = 4;
  }

// above is equivalent to

  try {
    const temp = yield delay(100, 2, false); // and this as well!
    fo.a = temp;
    fo.a = 3;
  } finally {
    fo.a = 4;
  }
```

Because of
ao.a = temp;
ao.a = 3;
ao.a = 4;

Synchronous execution, and due to the  mobx's flow function wrapper, this tick will be wrapped into action (same as runInAction) . So there is only one trigger to observer (in this tick)

![image](https://user-images.githubusercontent.com/15065396/96325571-6a837300-105b-11eb-97d6-9318baa7107f.png)



![image](https://user-images.githubusercontent.com/15065396/96325549-46c02d00-105b-11eb-9174-5037ef3aaf3c.png)

**Comment by mweststrate** [comment]
I added the test case and the output is as you expected, 1,2,5,4. Please make sure next time to actually provide a reproduction.
