### ISSUE TITLE
Early Binding

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#252]
The React Performance docs (https://mobxjs.github.io/mobx/best/react-performance.html) say we should bind functions early:

```js
// Bad
render() {
  return <MyComponent onClick={() => console.log('test')} />
}

// Good
handleClick() {
  console.log('test')
}
render() {
  return <MyComponent onClick={this.handleClick} />
}
```

When I need to pass custom params to the function, I do something like this:

```js
handleColorClick(color) {
  console.log(color)
}
render() {
  return <MyComponent onClick={this.handleColorClick.bind(this, 'red')} />
}
```

This is the best approach?

**Comment by mweststrate** [comment]
Binding in the `render` method results in the `MyComponent` always to be re-rendered if the parent component is re-rendered. Often this is not an issue, but when having many or expense `MyComponents` it might.

In your case you are still binding in the render, which should ideally be prevented if performance is a potential issue.

So any of the following approaches will work:

as seperate field: `handleRedColorClick = e => this.handleColorClick(this, 'red')`

or in the constructor: `this.handleRedColorClick = function(e) { this.handleColorClick(this, 'red') }.bind(this)`

**Comment by alexanderchan** [comment]
@hnordt also see the protips in the eslint rule that sub components can also be used: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by mweststrate** [comment]
@alexanderchan I'll add those links to the docs. Thanks!
