### ISSUE TITLE
Mobx 4/5 docs

### ISSUE THREAD

**Issue by olee** [mobxjs/mobx#2520]
Is there any place where we can access the old #mobx documentation? 
I can only find the new documentation for mobx v6 but us and probably many others still have to rely on the older versions and cannot upgrade immediately

**Comment by olee** [comment]
Didn't see I already got a reply elsewhere - sorry.
For everyone else, look here: https://github.com/mobxjs/mobx/tree/mobx4and5/docs

**Comment by FredyC** [comment]
Just for the sake of completeness note that V4/V5 is not that different from V6 so current docs are fairly usable for earlier versions and are composed in a much cleaner fashion. Any V6 breaking changes are nicely summarized in https://michel.codes/blogs/mobx6

**Comment by zero-t4** [comment]
> Just for the sake of completeness note that V4/V5 is not that different from V6
And the official documentation says quite opposite:
> MobX 6 is quite different from MobX 5. This pages covers a migration guide from MobX 4 and 5 to 6, and an extensive list of all the changes.
https://mobx.js.org/migrating-from-4-or-5.html
