### ISSUE TITLE
[mobx6] @action.bound decorator not binding

### ISSUE THREAD

**Issue by anri-asaturov** [mobxjs/mobx#2522]
**Intended outcome:**

Trying to use `@action.bound` in a class with `makeObservable(this)` and reference `@observable property` of the same class. The solution from https://github.com/mobxjs/mobx/issues/2468 does not work.

```typescript
class C {
  @observable x!: number; // if assigned here - works

  @action.bound // but not really
  incX() {
    this.x++;
  }

  constructor() {
    // this.x = 0 // if assigned here - works
    makeObservable(this);
    this.x = 0; // if assigned here - breaks
  }
}
```

**Actual outcome:**

Action is not getting actually bound.
Surprisingly, initializing property makes action bound properly.

**How to reproduce the issue:**

https://codesandbox.io/s/distracted-glade-y30yg?file=/src/index.ts

**Comment by mweststrate** [comment]
Please check existing issues or the mobx migration guide.

**Comment by anri-asaturov** [comment]
@mweststrate I did, if you're referring to tsconfig.json: `"useDefineForClassFields": true` - it is set there in the sandbox.

**Comment by anri-asaturov** [comment]
I raised this issue because you asked to do it here https://github.com/mobxjs/mobx/issues/2467 and it's still reproducing in 6.0.1

**Comment by mweststrate** [comment]
Ah yes, sorry, was reading to quickly apologies.

This is probably an earlier reported babel bug, it has been fixed already, but it might not yet be available in Parcel / Code Sandbox already. See https://github.com/mobxjs/mobx/issues/2486, https://github.com/babel/babel/issues/12146. Best check first if Babel 7.12 or higher is used behind the scenes.

**Comment by anri-asaturov** [comment]
@mweststrate I was just trying to figure out why can't I reproduce it locally, so you're probably right, thank you.

**Comment by mweststrate** [comment]
Added it to the docs, since more people will probably stumble on it as well.
