### ISSUE TITLE
Unable to use {forwardRef: true} option of observer HOC

### ISSUE THREAD

**Issue by leantide** [mobxjs/mobx#2524]
## Intended outcome

I would like to forward a ref to an observed component as per my current understanding of https://mobx-react.js.org/observer-hoc

```
const MyObserverComponent = observer(
  (props, ref) => {
    return <div ref={ref}>My Observer Component</div>;
  },
  { forwardRef: true }
);
```

## Actual outcome

As per codesandbox below, React chokes:

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Warning: Unexpected ref object provided for div. Use either a ref-setter function or React.createRef().

The above error occurred in the <div> component:
    in div (at App.js:29)
    in _c4 (at App.js:18)
    in div (at App.js:16)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

## How to reproduce the issue

https://codesandbox.io/s/inspiring-colden-uettu?file=/src/App.js

## Versions

react: 16.12.0
mobx: 5.15.4
mobx-react: 6.2.2

**Comment by FredyC** [comment]
Even though this issue holds more information, the #2527 is more up to date. Closing this as duplicate.

**Comment by pauldasslier** [comment]
Hello!
I did same issue and it works for me. Try this:
`const MyComponent = compose(inject('profile'), injectIntl)(observer(CommentsCreationField));`
`export default React.forwardRef((props, ref) => <MyComponent {...props} forwardedRef={ref} />);`

This helps me: https://github.com/reduxjs/react-redux/issues/914#issuecomment-377421145
forwardRef should be outside
