### ISSUE TITLE
Clarification on Concurrent Mode Support

### ISSUE THREAD

**Issue by samcooke98** [mobxjs/mobx#2525]
On the docs, specifically this page https://mobx-react.js.org/state-local there is a commen:

>Note that using a local store might conflict with future React features like concurrent rendering.

Is it possible to address _why_ this might conflict? What does conflict mean? 

I've seen some discussion about React's ability to rebase, and Michel Westrate suggesting that mobx shouldn't be used for local component state - https://github.com/facebook/react/issues/15317#issuecomment-481727125 - Is this still a valid claim still? 

--- 

Related issues from around the place,
https://github.com/reduxjs/react-redux/issues/1351#issuecomment-551311008

https://github.com/reduxjs/react-redux/issues/1351#issuecomment-509411957

**Comment by FredyC** [comment]
Since we have deprecated `useLocalStore` & `useAsObservableSource` this is probably outdated issue. Closing for now
