### ISSUE TITLE
Clean timers used for reaction tracking for tests run

### ISSUE THREAD

**Issue by bscaspar** [mobxjs/mobx#2528]
## Intended outcome
Jest runs and finishes when expected.

## Actual outcome
After adding an `<Observer>` to a component and using that component in a test with Jest and react-test-renderer, Jest runs successfully but returns a warning `Jest did not exit one second after the test run has completed.`

## How to reproduce the issue
[Repo](https://github.com/bscaspar/jest-observer-test-demo/tree/master) using expo-init and the basic tabs example
clone, `yarn`, `jest`

**Comment by RoystonS** [comment]
I'll do this within the next few days.

**Comment by RoystonS** [comment]
There's already a `resetCleanupScheduleForTests()` which `mobx-react-lite`'s own tests use to clean the timers up. I'll just expose that as `clearTimers()`.

**Comment by FredyC** [comment]
Fixed in https://github.com/mobxjs/mobx-react-lite/pull/329
