### ISSUE TITLE
🚧 Moving to monorepo

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2530]
We want to move together [mobx-react](https://github.com/mobxjs/mobx-react) & [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite) (more later maybe) into this repo to ease on issue duplication and to provide better idea of where to find help.

* [x] Transfer existing issues and disable issue reporting in those repos.
* [ ] Move API documentation from respective repos to mobx.js.org.
* [x] Sort out pending PRs (merge or close).

----
* [x] Restructure this repo to monorepo.
* [x] Modify changesets tool to work in monorepo.
* [x] Figure out how to set up CI for the monorepo to run tests (help wanted).
* [x] Build [ESM dev/prod bundles](https://github.com/mobxjs/mobx/issues/2564#issuecomment-717683710) for the browser consumption
* [x] Move mobx-react codebase to this repo and archive it.
* [x] Move mobx-react-lite codebase to this repo and archive it.

**Comment by spion** [comment]
Does this include closed issues? I was looking for a past discussion in mobx-react-lite and i was not able to read or find it.

**Comment by FredyC** [comment]
Yea. I suppose it will block access to closed issues as well. Not the best, but what can you do :) I've transferred that issues and converted to discussion for you: https://github.com/mobxjs/mobx/discussions/2531

**Comment by FredyC** [comment]
If anyone is feeling on working on the documentation migration, help is certainly wanted. I will be able to get to this in a week or more.

**Comment by jeremy-coleman** [comment]
I would like to see the 3 versions align if possible. It would make keeping compatible versions a non issue.

**Comment by FredyC** [comment]
> I would like to see the 3 versions align if possible. It would make keeping compatible versions a non issue.

Nah, that doesn't make much sense. These packages are not that tightly coupled. The `mobx` is the main one here and when a major version happens, it might affect others. But not the other way around. Changes to binding packages hardly warrant publishing `mobx` even without changes.

**Comment by Bnaya** [comment]
related proposal: move to yarn2
I've been tracking yarn 2 progress, and when using nodeLinker (and not pnp) it's a drop-in replacement for yarn 1,
And actively maintained, and support additional goodies

**Comment by FredyC** [comment]
@Bnaya Can you elaborate on what would be the benefit of that? I tried to toy with Yarn2 shortly after its release and was a bit confused about it.

**Comment by jeremy-coleman** [comment]
Freddy i know they arent coupled , but what is the downside? The latest versions should always maintain cross compatibility and mobx now supports proxy/no proxy runtimes in the same version, so i only see benefits, but maybe Im missing something?

**Comment by FredyC** [comment]
I already said downside. Making a change to the binding package is not a good reason to publish the other two as well. Especially if the change is compatible and works with previous versions. This pattern makes sense for example to UI libraries where dependencies are harder to track and follow due to many packages. Similarly Babel with numerous plugins it's easier to track compatibility that way.

**Comment by Bnaya** [comment]
> @Bnaya Can you elaborate on what would be the benefit of that? I tried to toy with Yarn2 shortly after its release and was a bit confused about it.

While yarn 1 workspaces could work just fine,
It's, maintenance involvement is minimal, (eg: https://github.com/yarnpkg/yarn/issues/7807)

And since it's release yarn 2 have gained several stability milestones:
babel & jest have are now using it
the node modules linker is fully operational (babel & jest using it)  
It has many new super small features such as:
https://yarnpkg.com/configuration/manifest/#publishConfig

I've opened a PR for that:
https://github.com/mobxjs/mobx/pull/2573

**Comment by FredyC** [comment]
And it's done. It was a rather tough chore, but everything seems to be working now. If I broke something I wasn't aware of, let me know :)

Hopefully, everything will be easier to maintain now when it's in a single spot.

Documentation for mobx-react(-lite) is still in their respective READMEs, but given the simplicity of the API layer, it can wait till someone is in the mood to integrate that with main docs.
