### ISSUE TITLE
Add createTransformer to docs

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2532]
You should be able to use createTransformer for that. I noticed we accidentally dropped the docs for that atm, so best check em here: https://github.com/mobxjs/mobx-utils/blob/extra-docs/README.md#createtransformer

_Originally posted by @mweststrate in https://github.com/mobxjs/mobx/discussions/2500#discussioncomment-101568_

**Comment by mweststrate** [comment]
Addressed in https://github.com/mobxjs/mobx-utils/commit/5c2b956f5fe9c228562fe935a7a3ec57e7ce146f
