### ISSUE TITLE
Error: [MobX] Cannot make property '$submitted' observable, it is not configurable and writable in the target object

### ISSUE THREAD

**Issue by foxhound87** [mobxjs/mobx#2534]
I'm trying to updating my code to mobx6 using `makeObservable(this)` in the constructors and leaving the decorators as they are:

The property where I get the issue is from a subclass and throws this error: 

`Error: [MobX] Cannot make property '$submitted' observable, it is not configurable and writable in the target object`

What this error means and how can be fixed?
Thank you.

**Comment by FredyC** [comment]
Please follow the new issue template.

**Comment by 1111mp** [comment]
@foxhound87 I think you can find a solution [here](https://deploy-preview-2327--mobx-docs.netlify.app/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable)

**Comment by foxhound87** [comment]
@1111mp I have done it.
here's the code of my lib with the changes:
https://github.com/foxhound87/mobx-react-form/tree/mobx6-support
