### ISSUE TITLE
The `deep` option does not work as documented.

### ISSUE THREAD

**Issue by clebert** [mobxjs/mobx#2542]
The `deep` option works only in combination with `defaultDecorator`. In contrast to the documented behavior.

The documentation **"Creating observable state"** states the following about the `deep` option:

> `deep: false` uses `observable.ref` by default, rather than `observable` to create new observable members.

Unfortunately setting the `deep: false` option has no effect in combination with `makeAutoObservable()`.

In the code I have found the following:

https://github.com/mobxjs/mobx/blob/e5d91c4eea7d16f74628d1e00d2937df9c225d97/src/api/makeObservable.ts#L258-L260

If in addition to `deep: false` also `defaultDecorator: observable.ref` is set, **it works.**

Either the documentation should be adapted accordingly, or the behavior is an unwanted bug?

**Versions**

MobX 6

**Comment by FredyC** [comment]
Can you please create a simple reproduction? It's always useful to have a piece of code we can put into tests to avoid regressions.
