### ISSUE TITLE
makeObservable() before property initializers?

### ISSUE THREAD

**Issue by brandon-marginalunit** [mobxjs/mobx#2549]
I've got a use-case where - for maximum declarativeness - I'd really like to set up some reactions within my class-property initializers. I was able to use this pattern in the previous version of MobX, but now that makeObservable has to be called in the constructor (which is executed after property initializers), these reactions don't get hooked up to the observables because they aren't observable yet at that point. I believe this is true whether using decorators or not (please correct me if I'm wrong).

Is there any way to accomplish this pattern or something like it? I'd really very much like to be able to "say" everything relevant to a given property in one singular place, instead of having to jump around and keep multiple things in sync.

**Comment by mweststrate** [comment]
reactions should now be set up in the constructor. Relying on field initialization order was always a bit dangerous at best and indeed not supported anymore in MobX 6
