### ISSUE TITLE
Is there an option to opt out autoaction in mobx6?

### ISSUE THREAD

**Issue by noe132** [mobxjs/mobx#2551]
I have some code before upgrade to mobx6 like this
```js
const item = observable({
  dataA: 1,
  dataB: 2,
  onClose: () => {},
})

const { dataA, ...rest } = item
```

Since functions on observables are made as action while transforming the object, and it'll be non-enumerable, the `rest` would only contain one item `dataB`. Trying access `rest.onClose` will getting undefined value.

It would be nice if there is an option for disable autoaction like `observable(target, decorator, { autoAction: false })` and just make function field like an normal observable field, or making action enumberable, or if there is a better approach to this kindof usage?

**Comment by FredyC** [comment]
Check overrides ... https://mobx.js.org/observable-state.html#observable

**Comment by mweststrate** [comment]
See makeObservable

Op vr 23 okt. 2020 06:31 schreef Daniel K. <notifications@github.com>:

**Comment by linayanse** [comment]
@mweststrate How about recursive object? like this.
```javascript
const item = observable({
  componentName: 'Any',
  props: {
    children: [
      {
         componentName: 'Any',
         props: {
           onClick: () => {},
         }
      }
   ],
    onClose: () => {},
  },
})
```
