### ISSUE TITLE
Attempted import error: 'makeObservable' is not exported from 'mobx'.

### ISSUE THREAD

**Issue by wave-light** [mobxjs/mobx#2557]
**Intended outcome:**

Should be able to wrap a function component export with `observer`, eg `export default observer(MyComponent);`

**Actual outcome:**

got error:

```
Failed to compile
./node_modules/mobx-react-lite/es/utils/assertEnvironment.js
Attempted import error: 'makeObservable' is not exported from 'mobx'.
```

**How to reproduce the issue:**

Create react app: `npx create-react-app MyApp`

Install dependencies: `yarn add mobx mobx-react mobx-state-tree`

Create a function component, and try to wrap the export in observer:

```
import { observer } from 'mobx-react';
import React from 'react';

const MyComponent = () => {
  return (
    <div>
      Hello world
    </div>
  );
};

export default observer(MyComponent);
```

**Versions**

    "mobx": "^6.0.1",
    "mobx-react": "^7.0.0",
    "mobx-state-tree": "^3.17.2",

**Comment by FredyC** [comment]
Please create a reproduction with eg. CodeSandbox. This combination of dependencies should work, so it's likely some mistake on your side.

**Comment by wave-light** [comment]
Apologies, I needed to restart server. With these dependencies I get the error:
`Error: [MobX] Cannot obtain atom from undefined`
But the solution for that error was found here: https://github.com/mobxjs/mobx-state-tree/issues/1588#issuecomment-715044154
