### ISSUE TITLE
[mobx-react] Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by nodegin** [mobxjs/mobx#2568]
**Intended outcome:**

Should be rendering correctly without errors

**Actual outcome:**

Nothing rendered, console print ""

**How to reproduce the issue:**

```
git clone https://github.com/nodegin/mobx-react-bug-reproduce
cd mobx-react-bug-reproduce
npm install
npm start
```

**Versions**

Tried v6 & v7 getting the same error

**Comment by FredyC** [comment]
Uh, you are not doing anything MobX specific except setting up the store and attaching observer but not rendering anything based on it. Figure out your setup first without MobX.

https://github.com/nodegin/mobx-react-bug-reproduce/blob/master/src/renderer/App.js

**Comment by nodegin** [comment]
@FredyC Actually, I can't even get "setting up the store and attaching observer" work...

**Comment by nodegin** [comment]
I am getting this weird error if I add <Provider> and observe

![Screenshot 2020-10-28 at 11 30 51 PM](https://user-images.githubusercontent.com/8536244/97458701-ea6fde00-1975-11eb-8861-f749848374d0.png)


If you change App.js to something like this:
```
import React from "react";

const App = () => {
  return (
    <h1>
      123
    </h1>
  );
};

export default App;
```

Without any mobx-react stuff, it can be rendered normally

**Comment by FredyC** [comment]
Read carefully that error message, most likely you have two different versions of some deps or just delete node_modules and reinstall. This is a problem in your local setup and you have to figure that out on your own, sorry.

**Comment by nodegin** [comment]
@FredyC Have you tried cloning the repo and perform FRESH install? since the version in package.json is same so your guess doesn't make sense imo.

**Comment by FredyC** [comment]
I did not try that, because you are using very little of MobX, but you have a bunch of code for Electron there. This basic thing you did with MobX works 100% for everyone, so this is something in your configuration.

**Comment by she11sh0cked** [comment]
@FredyC I actually have the exact same issue as @nodegin.
My setup is a bit simpler though. Just a basic create-react-app with mobx and functional components.
Basically something like this:

```tsx
import React from 'react' // ^17.0.1
import ReactDOM from 'react-dom' // ^17.0.1
import { makeAutoObservable } from 'mobx' // ^6.0.3
import { observer } from 'mobx-react' // ^7.0.4

class RootStore {
  helloWorld = 'hello world!'

  constructor() {
    makeAutoObservable(this)
  }
}

const rootStore = new RootStore()

const Root: React.FC = observer(() => {
  return <div>{rootStore.helloWorld}</div>
})

ReactDOM.render(<Root />, document.getElementById('root'))
```

What i noticed was that the problem only occurs with react 17!

**Comment by mweststrate** [comment]
1. do check if you have React accidentally installed twice
2. if not, open a new issue, this one is closed

**Comment by she11sh0cked** [comment]
I do have a dependency which has it's own react 16 dependency. Fixed it with a resolution for now. Sorry for bothering!
