### ISSUE TITLE
Upgrade react peer dependency to v17

### ISSUE THREAD

**Issue by Ekristoffe** [mobxjs/mobx#2569]
This issue is about mobx-react and mobx-react-lite.

**Intended outcome:**
Be able to update react to v17.x.x without having a peer dependency warning by npm.

**Actual outcome:**
npm WARN mobx-react@7.0.0 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@3.0.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.

**How to reproduce the issue:**
Install mobx-react or mobx-react-lite with react v17.

**Versions**
mobx-react@7.0.0
mobx-react-lite@3.0.1

**Comment by FredyC** [comment]
Feel free to submit a PR in both repos :)

**Comment by FredyC** [comment]
Fixed in the latest versions.
