### ISSUE TITLE
Warning [mobx-react-lite] 'useLocalStore' is deprecated, use 'useLocalObservable' instead

### ISSUE THREAD

**Issue by rizkyramadhan** [mobxjs/mobx#2574]
When i use latest version of mobx and mobx-react-lite. it shows warning:

`mobx-react-lite] 'useLocalStore' is deprecated, use 'useLocalObservable' instead`

**Comment by FredyC** [comment]
What you don't understand about it? :) Check the #2566 discussion if you like.
