### ISSUE TITLE
React Native not working with mobx 6.

### ISSUE THREAD

**Issue by ranatallal09** [mobxjs/mobx#2578]
I made an expo react native project and installed the mobx 6 and mobx-react 7, however its not working as expected. Iam changing the observable via an action but its not causing any re rendering to my observer. My functional component is wrapped with observer and my store is using decorators of observable and action. After many tries I downgraded to mobx 5 and mobx-react 6 and its working perfect. I think this is an issue with latest version.

**Comment by FredyC** [comment]
Have you followed the migration guide? That's most likely a culprit. Closing unless you can provide more information - ideally reproduction.
