### ISSUE TITLE
mobx-react(-lite) useLocalObservable will wrap a class instance in observable if make(Auto)Observable is not used

### ISSUE THREAD

**Issue by AoDev** [mobxjs/mobx#2579]
### Context
I am migrating my boilerplates 
* from mobx v4/v5 mobx-react v6 
* to mobx v6, mobx-react v7

### Intended outcome

I switched to `mobxReact.useLocalObservable()`.

For some complex components, I have classes for local state. 
So I have adapted the code to have calls like `mobxReact.useLocalObservable(() => new MyState())`

While most of the time, `make(Auto)Observable` will be used, I also had the case where a class "in WIP" was just passing non observable data.

```js
import * as mobx from 'mobx'

export default class AppSettingsVM {
  constructor ({rootStore}) {
    mobx.makeAutoObservable(this) // <- WITHOUT this line, the instance is turned into an observable and the app crashes
    this.settings = rootStore.coreStore.settings
  }
}

```

**Actual outcome:**

From the docs, if useLocalObservable returns a class instance, it should be kept as is, which is not what is happening here and leads to a crash.

**How to reproduce the issue:**

Use `useLocalObservable` where it returns a class instance that is not using mobx make(Auto)Observable.

**Versions**
mobx v6, mobx-react v7

**Comment by mweststrate** [comment]
Would you mind creating a small codesandbox to demonstrate the issue?

**Comment by FredyC** [comment]
Just a note, there is effectively no reason to use `useLocalObservable` for class based stores. Instead you can just do `const [state] = React.useState(() = new MyState())`. That hook does mostly the same, but passes your instances through `observable` which is unnecesssary.

**Comment by AoDev** [comment]
@FredyC  I naively replaced `useLocalStore` by `useLocalObservable` because I had a deprecation warning about useLocalStore. What you say above make total sense, React.useState is enough and I'll use that. 

But the issue does exist. The docs say you can return a class instance and it would be kept as is which seems to not be correct. It seems that userLocalObservable treats a class that has been decorated with makeAutoObservable differently than a class that was not.

Maybe we should clarify that useLocalObservable should be used only with objects?

Here is a sandbox where the issue can be reproduced @mweststrate 
Note that you might need to reload the sandbox browser after edit.

https://codesandbox.io/s/suspicious-lewin-okerp?file=/src/MyStore.js

You can see the difference when I console.log the local store in the component.

<img width="477" alt="Screenshot 2020-11-01 at 18 09 35" src="https://user-images.githubusercontent.com/1526150/97809497-7d0dc700-1c6d-11eb-80a6-66bed999c63e.png">


<img width="474" alt="Screenshot 2020-11-01 at 18 09 05" src="https://user-images.githubusercontent.com/1526150/97809495-7aab6d00-1c6d-11eb-92de-f1668f2b9d0a.png">

**Comment by FredyC** [comment]
I agree with you this is a long time confusion. Class-based stores should not have been used with `useLocalStore`, but it was more tolerant about it. Maybe mobx observable V6 should ignore decorated class instances, is that possible @mweststrate?

**Comment by mweststrate** [comment]
Yeah it is what it should do indeed, Im surprised with this behavior, might
be a bug but didn't check the sandbox yet

Op zo 1 nov. 2020 17:16 schreef Daniel K. <notifications@github.com>:

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/blob/44b64135fdd6cfe98279210f82faab19671a5ed7/packages/mobx/src/api/observable.ts#L96-L108

It always defaults to boxed observable.
