### ISSUE TITLE
MobX map replace method/event?

### ISSUE THREAD

**Issue by AriaFallah** [mobxjs/mobx#258]
So with the [mobx-store](https://github.com/AriaFallah/mobx-store), I recently added the ability to use observable maps in the store. Undo/redo works perfect with both the objects and the arrays now, but there is one caveat.

With arrays there is the `replace` method. So that if I want to remove 5 elements, but have it be only one undo to get all five back, I can do `.replace(arrayWithFiveElementsRemoved)`.

With maps if I want to edit 5 keys, but only do only one undo/redo to revert the changes to all 5 keys at once, it's impossible. This is because according to the `object.observe` spec that you followed, there's nothing like a `splice` event for objects that changes multiple things.

I'd like to know your thoughts on adding a `replace` method and event to observable maps such that you'd be able to do `.replace(newObjectWith5KeysChanged)`. That would emit an event like

```js
{
  type: 'replace',
  oldValue: {}
}
```

With this replace event I'd be able to have a proper undo/redo for object.

Also an interesting thought is that you'd also basically be able to make redux using MobX since constantly replacing and saving that history would be like an immutable store.

What are your thoughts on adding something like this?

**Comment by hellectronic** [comment]
So it will be more like a merge than a replace, something like `Object.assign()`?

**Comment by AriaFallah** [comment]
Looking back...I don't need this at all.
