### ISSUE TITLE
@observable decorator doesn't work in mobx@6

### ISSUE THREAD

**Issue by Yoskutik** [mobxjs/mobx#2580]
**Intended outcome:**

Here's the code:

```javascript
import { action, observable } from 'mobx';
import { observer } from 'mobx-react-lite';
import React from 'react';
import { render } from 'react-dom';

export default class FooterViewModel {
    @observable
    content: number | string = 'asdasdasd';

    @action
    onClick = () => {
        this.content = new Date().getTime();
        console.log(this.content);
    };
}

const viewModel = new FooterViewModel();

const Footer = observer(() => {
    return (
        <footer>
            {viewModel.content}
            <button onClick={viewModel.onClick}>Button</button>
        </footer>
    );
});

render(
    <Footer/>,
    document.getElementById('root'),
);
```

And I expect to change content of the `Footer` by clicking on the button.

**Actual outcome:**

I can see in console, that `content` actually is changing. But the component is not rendering again, so the value in DOM is not changing.

**Versions**

These are the modules I tried to use:
```json
"mobx": "^6.0.1",
"mobx-react-lite": "^3.0.1",
"react": "^17.0.1",
"react-dom": "^17.0.1"
```

---

**Why I suspect that reason of this bug is version and the observable decorator**

If I use this code:

```javascript
import { action, makeAutoObservable } from 'mobx';

export default class FooterViewModel {
    content: number | string = 'asdasdasd';

    constructor() {
        makeAutoObservable(this);
    }

    @action
    onClick = () => {
        this.content = new Date().getTime();
        console.log(this.content);
    };
}
```

Everything works as it should be.

Also, if I switch mobx to version 5 and mobx-react-lite to version 2:

```json
    "mobx": "^5.15.7",
    "mobx-react-lite": "^2.2.2",
```

The code with decorators works also fine.

But both mobx@6 and decorators are not working.

---

__P.S.__

Also I am using Webpack and TypeScript

**Comment by FredyC** [comment]
Did you follow the migration guide? Why is your first example not acting based on it? The second example is correct if you want to use MobX 6.

**Comment by val-o** [comment]
I suspect the problem is that you use ["@babel/plugin-proposal-class-properties", { "loose": **true** }]. Having the same issue with cra@4
