### ISSUE TITLE
Action decorator not working properly when overriding arrow function method

### ISSUE THREAD

**Issue by tahme** [mobxjs/mobx#2593]
We have an existing project that was using decorators and upgraded to Mobx 6.0.3. We now have `makeObservable(this)` in constructors so we can keep using decorators as before.

We have a `BaseClass` and `SubClass` that extends the former. Both have an arrow function method `@action func() => {...}` and a constructor with `makeObservable(this)`. `SubClass` overrides `func` and has no additional observables or actions.

**Intended outcome:**

Calling `func()` for an instance of `SubClass` modifies an observable in an action.

**Actual outcome:**

Calling `func()` for an instance of `SubClass` produces a Mobx warning:
> [MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed.

**How to reproduce the issue:**

See tests in the following CodeSandbox: https://codesandbox.io/s/priceless-goodall-u5cr7?file=/mobx.test.js

Adding a new dummy `@observable` or `@action` to `SubClass` fixes the issue, which led me to believe this might be a bug in how `makeObservable(this)` works.

**Comment by urugator** [comment]
Seems to be a flawed heuristic for checking whether the `makeObservable` happens in superclass constructor (in which case the call should be skipped).
https://github.com/mobxjs/mobx/blob/e19078c9abdb2a3b03f46c4235562da834c44d45/packages/mobx/src/api/decorators.ts#L77-L82

Dunno how it should be fixed, but here is at least a test:
```javascript
test("makeObservable + @action + arrow function + override #2614", () => {
    class Parent {
        constructor() {
            makeObservable(this);
        }

        @action foo = () => {};
      }

    class Child extends Parent {
        constructor() {
          super();
          makeObservable(this);
        }

        @action foo = () => {};
    }

    const parent = new Parent();
    const child = new Child();
    expect(isAction(parent.foo)).toBe(true);
    expect(isAction(child.foo)).toBe(true);
})
```
