### ISSUE TITLE
Proxy target computable is called with wrong context (this should be receiver, not target)

### ISSUE THREAD

**Issue by fijiwebdesign** [mobxjs/mobx#2601]
I'm proxying an instance of a class. 
A computable property of this class should be able to call `this.someProp` where `this` resolves to the Proxied object rather than the Proxy target (the instance). 

With a regular getter, `this` correctly refers to the Proxy receiver. 
With a computed getter, `this` becomes the Proxy target (bypassing the proxy for subsequent `this` references)

```
class MockItem {

  @computed get computedListName() {
    return this.list // this should be the proxy, not the instance of MockItem
  }

}
```

**Intended outcome:**

`this` should refer to the proxy object inside a computable. 

**Actual outcome:**

`this` refers to the Proxy target (the instance itself) rather than the Proxy.

**How to reproduce the issue:**

```
import { computed, observable } from 'mobx'

const mockProps = {
  id: 'mockId',
  title: 'mockTitle'
}

class MockItem {
  @observable id = ''
  @observable title = ''

  constructor(props) {
    Object.assign(this, props)
  }

  get list() {
    throw new Error('The list property should be proxied')
  }

  get listName() {
    return this.list.modelName
  }

  @computed get computedListName() {
    return this.list.modelName
  }

}

class MockList {

  get modelName() {
    return 'MockList'
  }

}

class ListContext {
  list = null
  constructor(list) {
    this.list = list
  }

  createContext(item) {
    const { list } = this
    return new Proxy(item, {
      get: function(target, prop, receiver) {
        if (prop === 'list') {
          return list
        }
        return Reflect.get(target, prop, receiver);
      }
    })
  }
}

it('this.list can be used within Item computed props', () => {
    const list1 = new MockList()
    const item = new MockItem(mockProps)
    const context1 = new ListContext(list1).createContext(item)
    expect(context1.computedListName).toBe(list1.modelName) // error
  });

```
**Versions**

mobx ^5.15.4

any test runner - this example uses jest

**Comment by FredyC** [comment]
Can you please upgrade to MobX 6 if it's fixed there by any chance? We no longer support earlier versions. If it won't work, please provide a runnable reproduction.

**Comment by fijiwebdesign** [comment]
Closing. Fixed in Mobx6.
