### ISSUE TITLE
Wrong global variable name for mobx-react-lite in UMD release

### ISSUE THREAD

**Issue by pvrobays** [mobxjs/mobx#2617]
**Intended outcome:**

Run the UMD mobx-react-lite in development or production mode.

**Actual outcome:**

JS Error: "Cannot read property 'isUsingStaticRendering' of undefined"

mobx-react is unable to find `global.mobxReactLite`

**How to reproduce the issue:**

run mobx-react and mobx-react-lite with the UMD version available on UNPKG:
https://unpkg.com/browse/mobx-react-lite@3.1.5/dist/mobxreactlite.umd.development.js

**Versions**

mobx-react: 7.0.4 (UMD)
mobx-react-lite: 3.1.5 (UMD)

**Extra info**
I believe the issue is situated here https://unpkg.com/browse/mobx-react-lite@3.1.5/dist/mobxreactlite.umd.development.js:
`factory(global.mobxreactlite = {}, ...)`
should be:
`factory(global.mobxReactLite = {}, ...)`

In version 3.1.0 it was still OK: https://unpkg.com/browse/mobx-react-lite@3.1.0/dist/mobxreactlite.umd.development.js

**Comment by pvrobays** [comment]
FYI: I believe the same thing happened in mobx-react:

in 7.0.4 mobx-react is exposed as 'mobxreact': https://unpkg.com/browse/mobx-react@7.0.4/dist/mobxreact.umd.development.js

in 7.0.0 it was still exposed as 'mobxReact': https://unpkg.com/browse/mobx-react@7.0.0/dist/mobxreact.umd.development.js

**Comment by FredyC** [comment]
Thank you for reporting, should be fixed with the latest patch versions of both packages.

**Comment by pvrobays** [comment]
Thanks. I've just tried the new patch releases. They work like charm!
