### ISSUE TITLE
Getting `LegacyObservableArray`s instead of the values from map without Proxies

### ISSUE THREAD

**Issue by abiro** [mobxjs/mobx#2620]
Thanks for all the great work on Mobx! Ran into the problem below when trying to make IE11 compatibility work. Unsure if it's a bug or if I'm missing something. All help is appreciated.

---

**Intended outcome:**

Get values from `Map` with `useProxies: 'never'`.

**Actual outcome:**

Getting `LegacyObservableArray`s instead of the values.

**How to reproduce the issue:**

https://codesandbox.io/s/epic-mendeleev-qsltm?file=/src/index.js

```javascript
import { makeObservable, configure, computed, observable } from "mobx";

const useProxies = "never";
configure({ useProxies });

class Item {
  constructor(values) {
    this.values = values;

    makeObservable(this, {
      values: observable
    });
  }
}

class Store {
  constructor() {
    this.items = [new Item([1]), new Item([2]), new Item([3])];

    makeObservable(this, {
      items: observable,
      values: computed({ keepAlive: true }),
      map: computed({ keepAlive: true })
    });
  }

  get values() {
    return this.items.flatMap((item) => item.values);
  }

  get map() {
    return new Map(this.values.map((el, i) => [i, el]));
  }
}

const store = new Store();

console.log(useProxies);
console.log(Array.from(store.map.values()));
```

With `useProxies: 'always'` the console output is:

```
(3) [1, 2, 3]
```

With `useProxies: 'never'` the console output is:

```
(3) [LegacyObservableArray, LegacyObservableArray, LegacyObservableArray]
```

**Versions**

mobx==6.0.4

**Comment by mweststrate** [comment]
This is a known limitation of the faux arrays used in non proxy environments; those arrays are not real arrays (they don't pass `Array.isArray` checks) and hence not concatenable, so you will have to work around it by doing something like `.flatMap(item => item.values.slice())`
