### ISSUE TITLE
component doesn't re-render

### ISSUE THREAD

**Issue by khvedzeli** [mobxjs/mobx#2622]
A component doesn't re-render after an update in the new version, but it works in the old version.

**Intended outcome:**
A component must be re-render after the update

**Actual outcome:**
A component doesn't re-render after an update

**Versions**

**_New_**: 
react: 17.0.0
mobx: 6.0.4
mobx-react: 7.0.5
https://codesandbox.io/s/jovial-grothendieck-mj5b6?file=/src/App.tsx

_**Old**_:
react: 17.0.0
mobx: 5.15.7
mobx-react: 6.3.1
https://codesandbox.io/s/adoring-wave-1w9kt?file=/src/App.tsx

**Comment by mweststrate** [comment]
R E A D    T H E    M I G R A T I O N    G U I D E

**Comment by FredyC** [comment]
@khvedzeli I am curious. Do you regularly update the major version of packages without looking at the changelog? :) Or what is your reasoning for now following the migration guide?

**Comment by khvedzeli** [comment]
@FredyC My bad. I followed old documentation and didn't check the changelog. 

@mweststrate Thank you.

**Comment by FredyC** [comment]
@khvedzeli Old documentation? Where did you find that? Would be great if you can help us to figure out best approach here because this is a very repeated problem.

**Comment by khvedzeli** [comment]
@FredyC This one https://mobx-react.js.org/recipes-context. Maybe needs to change the warning message. I only thought that docs moved just on mobx website.
