### ISSUE TITLE
Missing "decorate"

### ISSUE THREAD

**Issue by blendsdk** [mobxjs/mobx#2624]
Hi,

I have upgraded to mobx 6.0.4 and I am getting: `/node_modules/mobx/dist/mobx has no exported member 'decorate'`
Looks like the `decorate` is missing in mobx 6.x.  What am I doing wrong?
If i need to use another API to be compatible with 6.x please advise. 

here is my code example:
```
import { action, decorate, observable, runInAction } from "mobx";
....
...
    decorate(clazz, {
        fetching: observable,
        error: observable,
        result: observable,
        fetch: action.bound
    });
    return new clazz();
....
...
```

**Comment by mweststrate** [comment]
Please read the migration guide, and only afterwards post what didn't work.
