### ISSUE TITLE
Overriding computed getter throws 'Cycle detected' error

### ISSUE THREAD

**Issue by pvrobays** [mobxjs/mobx#2625]
**Intended outcome:**

I have an abstract class which implements a computed getter.
I have an implementation of the abstract class, which overrides the abstract class' computed getter.

When executing the computed getter in the implementation class, it should just executed the overridden computed getter.

**Actual outcome:**

Mobx throws `Error: [MobX] Cycle detected in computation`.

**How to reproduce the issue:**

Executing the following code throws the exception:

```typescript
abstract class A {
    @observable
    public value: string;
    
    constructor() {
        this.value = "some value";
    }
    
    @computed
    get hasValue(): boolean {
        console.log("hasValue A");
        return this.value.length > 0;
    }
}

class B extends A {
    
    constructor() {
        super();
        makeObservable(this);
    }
    
    @computed
    get hasValue(): boolean {
        console.log("hasValue B");
        return this.value.length > 0;
    }
}

const obj = new B();
const result = obj.hasValue; //throws 'Cycle detected' error
```

**Versions**

I've encountered this issue while upgrading from mobx 5 to 6.
FYI: This wasn't an issue in mobx 5.

**Comment by mweststrate** [comment]
I think you need a makeObservable call in the super constructor. Otherwise
please put it in a code sandbox so we have some runable code to look at

**Comment by pvrobays** [comment]
I thought so to initially, but that doesn't seem to fix it.

In fact the opposite happens when you don't use decorators.
putting makeObservable in both the super class and the regular class fails: https://codesandbox.io/s/xenodochial-wing-ncwh9?file=/index.js
Once you remove the `makeObservable` call in the super class, and just implement it in the regular class. No error is thrown.

However, I'm 'old fashioned' and still use the decorators + makeObservable(this).
In that case, I never seem to be able to get around the 'Cycle detected' Error.

FYI: This is the typescript compiled Javascript: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=6#code/JYWwDg9gTgLgBAbzgYwuArjApgEwDRwgCGA1lgPIBGAzllAG5GUA2WBENdjLWcAvnABmUNHABEIDgA8xAbgBQ8ptRhQiyeMmZFq1OAEFE8uCbgABDrQZNWx02HQtgyOI2bosALjgqowAHYA5gqmcHYmqP6+6BrQABQAlEahocRkVFbcrHEwABbA1AkhKSZ5BQB0bh5wALzi1Gi8VVhy4fxtbWaoGNg4bYFY8Lk6AGpE7liJ3pQQEKxE-sklKBBRc1jlzBCBcWLD1GMTBmJFbaFQg+hQi2XUleMem1hBeXAAfHAADMUmfPJ-8i0Oj0ACE4FgpNh-Dg9IYEB1QpForEoIkliVqOgwHREj8UmkKJxrDwcvlCni-qFOt0HL1+oM4PtDh4pnAZusFuiUkj1pttrsmQ9eCCTnjzpdrnBbvcJk8Xrl3l8Kf9FEj4BwAFa1OD+LAAdzgINxZ1MgNWKjgF0xzHgdU15UFEwUZrWrD5Oyt6BtRSAA

**Comment by urugator** [comment]
Most likely we won't support overriding computeds, your best bet is:
```javascript
abstract class A {
    @observable
    public value: string;
    
    constructor() {
        this.value = "some value";
    }
    
    get _hasValue(): boolean {
        console.log("hasValue A");
        return this.value.length > 0;
    }

    @computed
    get hasValue(): boolean {
        return this._hasValue;
    }
}

class B extends A {
    
    constructor() {
        super();
        makeObservable(this);
    }
    
    get _hasValue(): boolean {
        console.log("hasValue B");
        return this.value.length > 0;
    }
}
```

**Comment by pvrobays** [comment]
That's fine. The workaround isn't that cumbersome.

Shouldn't this be a small footnote in the [Migration from 4/5](https://mobx.js.org/migrating-from-4-or-5.html) documentation? Overriding computeds did work in mobx 4/5.

Thanks anyway for the awesome library.
For now I'll go ahead and close this issue.

**Comment by urugator** [comment]
I am trying to rework how `makeObservable` acts with subclasses, so if it gets to production I will also try to update docs/migration accordingly. Basically you won't be able to to override/redefine anything but `action` and `flow` on prototype, everything else should end with more or less reasonable error. This is more restrictive, but currently some things work (or don't) more or less by accident.

**Comment by mweststrate** [comment]
IIRC this was a problem in MobX 4/5 as well, I remember having to use the
same pattern as work around in the past. Probably the getter still did its
job, but I'm not sure it was actually still a 'computed' in the end.

**Comment by pvrobays** [comment]
It could definitely have been the case that the actual computed didn't function anymore, even in Mobx 4/5. My code had other observables that were probably also triggered.
So I guess @urugator's proposal to block overriding properties and throwing a more descriptive error is a valid solution.
