### ISSUE TITLE
Cannot decorate undefined property with deep inheritance

### ISSUE THREAD

**Issue by uqee** [mobxjs/mobx#2633]
**Reproducible example:**

Please, have a look at
[CodeSandBox](https://codesandbox.io/s/mobx-cannot-decorate-undefined-property-irf77?file=/src/index.ts).

<details>
  <summary>Copy of the code</summary>

  ```typescript
  import { action, computed, makeObservable, observable } from "mobx";

  class A {
    public constructor() {
      makeObservable(this);
    }

    // @action aAction = () => "aAction";

    // @computed get aGetter() {
    //   return "aGetter";
    // }

    // aMethod() {
    //   return "aMethod";
    // }

    // @observable aObservable = "aObservable";

    // aProperty = "aProperty";
  }

  class B extends A {
    public constructor() {
      super();
      makeObservable(this);
    }

    // UNCOMMENT ME TO BREAK
    // @action bAction = () => "bAction";

    @computed get bGetter() {
      return "bGetter";
    }

    bMethod() {
      return "bMethod";
    }

    // UNCOMMENT ME TO BREAK
    // @observable bObservable = "bObservable";

    bProperty = "bProperty";
  }

  class C extends B {
    public constructor() {
      super();
      makeObservable(this);
    }

    // UNCOMMENT ME TO REPAIR
    // @action cAction = () => "cAction";

    @computed get cGetter() {
      return "cGetter";
    }

    // cMethod() {
    //   return "cMethod";
    // }

    // UNCOMMENT ME TO REPAIR
    // @observable cObservable = "cObservable";

    // cProperty = "cProperty";
  }

  const c: C = new C();
  console.log("OK", c);
```
</details>

---

**How to reproduce the issue:**

1. Uncomment either one from

    ```js
    // UNCOMMENT ME TO BREAK
    ```

    sections to see an error:

    ```bash
    Cannot decorate undefined property: ...
    ```

2. Then comment either one from

    ```js
    // COMMENT ME TO REPAIR
    ```

    sections to remove the error.

**Versions:**

- `mobx@6.0.4`
- `typescript@4.1.2`, `"useDefineForClassFields": true`
- `@babel/plugin-proposal-class-properties@7.12.1`, `"loose": false`

**Comment by urugator** [comment]
You shouldn't call `makeObservable` if there are no decorators/annotation (class A). Otherwise possibly similar issue to #2593. 
Subclassing currently isn't ideal, we are trying to come up with something less fragile.
`cAction = action(() => "cAction")` should be a future-proof solution for arrow functions that needs to be overridable by subclass.

**Comment by uqee** [comment]
If `class A` is not empty it fails anyway, I couldn't find any relation with its content, so commented it for brevity. Also it fails without any overridable properties or even actions.

Seems like the `class C`'s `@computed` causes the trouble and adding any other decorator alongside it is a possible workaround. I would have investigated `@computed` decorators further which seem somehow flawed.

**Comment by urugator** [comment]
> Also it fails without any overridable properties or even actions.

I've uncommented observbales/actions in B/C and commented out `makeObservable` in A and it doesn't throw in sandbox...
If I uncomment everything it also doesn't throw...
Whether everything is correctly converted to observable/computed/action I dunno...

**Comment by mweststrate** [comment]
As a work around, I think in principle it should work fine to not apply `makeObservable`in super classes when using decorators, and apply it in subclasses only. If subclassing is not guaranteed, a condition like `if (this instanceof SuperClass) makeObservable(this)`should work I'd expect

**Comment by uqee** [comment]
Good call, thanks, but didn't work either (tried with the example).

**Comment by jeremy-coleman** [comment]
What do you guys think about something like a mobx specific version of util/inherits designed for extending mobx decorated classes?

**Comment by urugator** [comment]
@jeremy-coleman Have you checked #2641? It restricts overriding only to actions defined on prototype and should throw in all other cases. However it's not entierely BC.
A BC solution is probably possible, but it would have almost the same limitations and no way to enforce them programatically, so user could still mess things up without knowing.

**Comment by jeremy-coleman** [comment]
I did , thank you for directing me there and your work on the pr. I have been thinking about it for a while, but still unsure of any conclusion.

**Comment by ahoisl** [comment]
> As a work around, I think in principle it should work fine to not apply `makeObservable` in super classes when using decorators, and apply it in subclasses only. If subclassing is not guaranteed, a condition like `if (this instanceof SuperClass) makeObservable(this)`should work I'd expect

This worked for my use case, thank you!

Would still be great if #2641 was a remedy, because `makeObservable` should be called as close to the relevant props (in the class constructor) as possible. Right now, it's a bit error prone with a high chance to forget the call in inheriting classes

**Comment by mweststrate** [comment]
MobX 6.1.0 has been released with improved inheritance, which should address this issue.
