### ISSUE TITLE
mobx-react-lite observer(, {forwardRef: true}) has no longer an effect

### ISSUE THREAD

**Issue by alpfactory-alex** [mobxjs/mobx#2636]
In latest mobx-react-lite it seems that the reference pointer is no longer provided to the functional react component eventhough forwardRef: true is set in the options.

Works using regular React.forwardRef (works, ref is a valid reference):

`
React.forwardRef((props, ref) => {  
    console.log('REF', ref)
    return <span />  
})
`

Doesn't work anymore with mobx-react-lite (ref is always null):

`
observer((props, ref) => {  
    console.log('REF', ref)
    return <span />  
}, {forwardRef: true})  
`

**Intended outcome:**

The provided reference should be valid and observer with {forwardRef: true} option should behave equally to using React.forwardRef.

We didn't change our code at all just upgraded mobx to 6x and mobx-react-lite to 3x

**Actual outcome:**

ref is null in observer component

**Versions**

"mobx": "^6.0.4",
"mobx-react-lite": "^3.1.6",

**Comment by FredyC** [comment]
Thanks for the report, but without runnable minimal reproduction it will take a long time for someone to have a look into it. So if you have a capacity for it, can you provide one to expedite it?

**Comment by alpfactory-alex** [comment]
@FredyC Yes sure. Is there a codebox template I could directly use for this? I couldn't find one maybe I didn't look right.

**Comment by FredyC** [comment]
Yes, there was the one in the issue template ... https://codesandbox.io/s/minimal-mobx-react-project-ppgml

**Comment by alpfactory-alex** [comment]
Well fun fact.. I spent the time to rebuild and it seems to work fine:

https://codesandbox.io/s/smoosh-sun-74cne?file=/index.js

Not sure why all of the sudden it then stopped in our code after upgrading while exchanging the same call from observer((props, ref) => void, {forwardRef: true}) to React.forwardRef((props, ref) => void) works...

https://codesandbox.io/s/smoosh-sun-74cne?file=/index.js

**Comment by FredyC** [comment]
You know, that's the usual story. People come in here, report bugs, don't bother with actual reproduction. We asked for it and suddenly "it works" :)

So I guess I am closing unless you can come up with a reproduction that shows the problem.
