### ISSUE TITLE
mobx v6 incorrect work inject decorator in IE11

### ISSUE THREAD

**Issue by MariiaIasakova** [mobxjs/mobx#2638]
When add inject decorator to component, in chrome all works good, but in IE11 get error "Unable to get property 'componentWillReact' of undefined or null reference"

  ``` 
export default hot(inject(stores => ({
        someStore: stores.someStore
    }))(observer(AuthorizationContainer)));
```
without inject all works fine

After investigation I found the problem with symbol "ReactForwardRefSymbol". In Chrome it loads, but in IE11 it has some error (it's shown on screenshot below). Then injector doesn't go to the needed code block and fails.

Versions: 
    "mobx": "^6.0.4",
    "mobx-react": "^7.0.5",
    "react": "^16.13.1"

![image](https://user-images.githubusercontent.com/36912512/100094072-83a4ee00-2e69-11eb-8cba-1ca938ceaaf7.png)

![Untitled1](https://user-images.githubusercontent.com/36912512/100093958-535d4f80-2e69-11eb-8532-ffc7b2a30b21.png)

In IE:
![Untitled1](https://user-images.githubusercontent.com/36912512/100092592-62430280-2e67-11eb-8deb-994ce529a99d.png)

In Chrome:
![image](https://user-images.githubusercontent.com/36912512/100095120-14c89480-2e6b-11eb-83ff-fb7e15286019.png)

**Comment by FredyC** [comment]
You need to polyfill Symbol in IE.

**Comment by MariiaIasakova** [comment]
We use polyfill for it
    "react-app-polyfill": "^1.0.6"

**Comment by FredyC** [comment]
Please setup a minimal reproduction repo so we can have a look at it.

**Comment by MariiaIasakova** [comment]
after deeper investigation I found out that the problem was incorrect build order
I changed the order of the imported files in the webpack entries and it worked

**Comment by Sammiu** [comment]
@MariiaIasakova Can you show the build code you adjusted the order？
