### ISSUE TITLE
Bad section title in the documentation

### ISSUE THREAD

**Issue by mtyaka** [mobxjs/mobx#264]
I think this section was called "Advanced", but now it says "(Ignore below, just links to make gitbook work)".

![screen shot 2016-05-26 at 14 44 43](https://cloud.githubusercontent.com/assets/32585/15574995/da3d0d02-2350-11e6-809a-bf06112fcfbc.png)

**Comment by mweststrate** [comment]
Ah yeah that was me annoyed with gitbook, actually I don't want the section at all, because "API overview" now contains these entries as well, but without link in the ToC gitbook won't compile these files. I'll rename it back to advanced.

Thanks!
