### ISSUE TITLE
MobX 6: makeObservable doesn't work with protected fields

### ISSUE THREAD

**Issue by sorteam** [mobxjs/mobx#2640]
**Intended outcome:**

```typescript
abstract class AStore {
  protected value?: any = undefined;

  constructor () {
    makeObservable(this, { value:observable, setValue : action }); 
  }

  protected setValue(value?: any) {
    this.value = value;
  }
}
```

**Actual outcome:**

**How to reproduce the issue:**

**Versions**
6

**Comment by mweststrate** [comment]
Issue closed for not following the template. And in this case, see the `makeObservable` documentation if my guess about your actual problem is correct.
