### ISSUE TITLE
Link in archived mobx-react repo results in a 404

### ISSUE THREAD

**Issue by Dakkers** [mobxjs/mobx#2646]
**Intended outcome:**
Go to the correct repo

**Actual outcome:**
404 and sadness

**How to reproduce the issue:**
1. go to https://github.com/mobxjs/mobx-react
2. click `mobx`

![image](https://user-images.githubusercontent.com/5009136/100267859-2751d500-2f22-11eb-9ae0-55b5c8beb3d2.png)

3. get 404'd bro

![image](https://user-images.githubusercontent.com/5009136/100267934-45b7d080-2f22-11eb-9cea-578a80d6fde6.png)

**Versions**
N/A

**Comment by FredyC** [comment]
Thanks for reporting, I'll fix in the near future :)

**Comment by meepeek** [comment]
@FredyC I saw the archived repo and confuse of what to do with react integration. The guide in this repo seems to be missing. Could you explain a bit ? I used mobx-react in my project 2 years ago. What should I do for update ? Should I import observer from mobx now ? The guide in this repo and web still use mobx-react and mobx-react-lite

**Comment by mweststrate** [comment]
@meepeek as the message suggests, the github repo's has been **moved**. That doesn't affect your project, as the npm package is still at the same place, unless you're directly building against github source urls.

**Comment by meepeek** [comment]
@FredyC For the new project, I should still use npm install mobx-react and mobx-react-lite even though it has been archived. Is that correct ? What I am worry is about the code in archived repo might no longer get update in the future. If it was moved into mobx main repo then, should I just npm install mobx and import everything from mobx package ?

**Comment by mweststrate** [comment]
@meepeek this is github, not npm. The source code is living at at different place now, that is all. Still maintained by the same team, so really nothing to worry about here, and it doesn't have any impact on your projects. Its just the internal move of an office within the same company

**Comment by bluepeter** [comment]
@mweststrate I am also confused. Where is the new location for `mobx-react`?

**Comment by mweststrate** [comment]
This is a mono repo now.

**Comment by FredyC** [comment]
Fixed links (it was wrong in lite repo as well)
