### ISSUE TITLE
mobx autorun isn't firing

### ISSUE THREAD

**Issue by chase-moskal** [mobxjs/mobx#2647]
hello fine folks of mobx — i've been a long-time happy mobx user, and i've spread the word at every opportunity!

for some reason today, i can't get mobx to work. not sure what's wrong, but my best guess: maybe something to do with the newer esm distribution? or maybe i've simply overlooked something much more mundane?

------

**Intended outcome:**

autorun should respond to changing observables

**Actual outcome:**

autorun is not fired when observables change

**How to reproduce the issue:**

i've created a [demo repo](https://github.com/chase-moskal/mobx-issue-2020-11-25) to narrow down the issue

1. `git clone git@github.com:chase-moskal/mobx-issue-2020-11-25.git`
2. `cd mobx-issue-2020-11-25`
3. `npm i`
4. `npm test -s`
5. see the resulting failure report

see the [mobx-test.js](https://github.com/chase-moskal/mobx-issue-2020-11-25/blob/master/mobx-test.js) test case

**Versions**

- mobx@6.0.4 and also mobx@5.15.7
- using esm
- under node v15.3.0, not browsers

------

thanks fellas, i really appreciate the work you do, and any help i get :)

&nbsp; &nbsp; :wave: chase

**Comment by mattruby** [comment]
I don't think you're calling an observable value the autorun.

**Comment by mattruby** [comment]
`let runs = 0
autorun(() => {
	runs += 1
	console.log(`autorun ${runs}`)
})`
Runs is not observable.

**Comment by chase-moskal** [comment]
@mattruby — aw, sorry about that, my mistake!

https://github.com/chase-moskal/mobx-issue-2020-11-25/commit/a32e7836606495caec5ce49421aa9b309d288c53 fixes my mistake, so you can `git pull` that down and run it again

unfortunately, the bug still reproduces :worried:

**Comment by mattruby** [comment]
I think you need to be using `get` and `set` with your boxed observable.
https://mobx.js.org/api.html#observablebox

**Comment by mattruby** [comment]
Here's a simple example:
```
import { observable, autorun, action } from "mobx"

const numb = observable.box(0)

const increment = action(() => {
	numb.set(numb.get() + 1)
})

autorun(() => {
    console.log(numb.get())
})

increment()
increment()
increment()
increment()
```

**Comment by chase-moskal** [comment]
i think this was confusion about migration to mobx@6

post mortem:

1. at first, i missed the [migration guide's advice](https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable) to add `makeObservable(this)` to my constructors — this is what caused my autoruns to mysteriously stop firing in the first place
2. next, i attemped to narrow down the issue, by eliminating decorators from the equation, while blindly falling back on my outdated knowledge on how i thought observables had worked, which didn't work
3. @mattruby fixed my test-case example by pointing out the necessary `.set()` and `.get()` usage on boxed observables
4. i fixed my app's mobx usage by correctly using `makeObservable(this)`

case closed, thanks @mattruby for helping clear this up

:wave: chase

**Comment by chase-moskal** [comment]
for posterity, in case somebody ends up in the same situation, i created a [fix](https://github.com/chase-moskal/mobx-issue-2020-11-25/blob/fix/mobx-test.js#L8) branch which fixes the demo test case
