### ISSUE TITLE
The property of Object in ObservableArray can not be enumerable in production environment

### ISSUE THREAD

**Issue by tongyuchan** [mobxjs/mobx#2648]
**Versions**
-  mobx 3.4.1
- mobx-react 4.3.5

**Actual outcome:**
when i use `mobx.toJS` to change my data which is array to javascript,  i got empty object in production environment
![image](https://user-images.githubusercontent.com/26242440/100444401-57e26c00-30e6-11eb-9fc5-bcd7ce01ba95.png)

i found it maybe related to `enumerable`
![image](https://user-images.githubusercontent.com/26242440/100444433-64ff5b00-30e6-11eb-95f9-6d96507eab51.png)

 but in local development environment，i can get the object with data,isApply, isOpen properties 
![image](https://user-images.githubusercontent.com/26242440/100445306-d7bd0600-30e7-11eb-99d3-4847f3d26290.png)

![image](https://user-images.githubusercontent.com/26242440/100445324-e0add780-30e7-11eb-8bfd-80e0d7cf316b.png)

the backend  request interface is same in production environment and  local development environment, the code is same, but after webpack build, it has different behavior

**Intended outcome:**
i hope i can get the object with data,isApply, isOpen properties in production environment as it is running in  local development environment

**How to reproduce the issue:**
this is my core code
```
class TagStore {
    @observable
    applyTags = [];

    @action
    setApplyTags = (value) => {
        this.applyTags = value;
    }
}

const store = new TagStore();

@observer
class RegisterAppkey extends Component {
    handleApplyTagChange = (applyTags) => {
        store.setApplyTags(applyTags);
    };

   render() {
      const { applyTags } = store;
      console.log(applyTags);
      console.log(mobx.toJS(applyTags));
       return <Provider tagStore={store}>
          <otherCom   applyTags={mobx.toJS(applyTags)} />
        </Provider>
   }
}

```

**Comment by mweststrate** [comment]
Your MobX version is three majors behind, so I recommend to update MobX first before filing an issue. Or as work around manually construct the object, rather than using `toJS`.

**Comment by mweststrate** [comment]
Closing this issue as it is further inactionable for us. (And for the future: issues should be filed against the latest version and be accompanied with a runnable reproduction)
