### ISSUE TITLE
Mobx observer not refreshing

### ISSUE THREAD

**Issue by yasinkiziltas** [mobxjs/mobx#2659]
Hi everyone,
I just switched to Mobx and I cannot update data instantly. My data is updated only when I renew it, it is not updated instantly.

**Users.js**
import React, { Component } from 'react'
import { View, Button, Text } from 'react-native';
import { observer, inject } from 'mobx-react'

@inject("UserStore")
@observer
export class Users extends Component {
    render() {
        const { UserStore } = this.props;
        return (
            <View>
                <Button
                    title={"fetch users"}
                    onPress={() => UserStore.fetchUsers()}
                />

                <View>
                    {
                        UserStore.users.map((user, key) => (
                            <View key={key}>
                                <Text style={{ textAlign: 'center' }}>{user.name.first}</Text>
                            </View>
                        ))
                    }
                </View>
            </View>
        );
    }
}

**UserStore.js**
import { observable, configure, action, runInAction, decorate } from 'mobx';
import axios from 'axios';

configure({
    enforceActions: "observed"
});

class UserStore {
    @observable users = [];

    @action fetchUsers() {
        axios
            .get('https://randomuser.me/api/?results=10')
            .then(response => response.data.results)
            .then(  
                users => {
                    runInAction(() => {
                        this.users = users;
                    })
                },
            )
            .catch(error => {
                alert('error')
            })
    }

export default new UserStore()

**Comment by mweststrate** [comment]
Follow the issue template and read the migration guide

**Comment by daizhenhong** [comment]
what's your version of mobx? 
If you use version of 6.x,then you should add makeObservable for this.
Like this:
`class UserStore {
  @observable users = [];
  constructor() {
    makeObservable(this)
  }
}`
