### ISSUE TITLE
Mobx toJS not deleting __proto__ field

### ISSUE THREAD

**Issue by saulpalv** [mobxjs/mobx#2669]
Im trying to conver observable to plain js object to save into db, but `__proto__` field wont remove from object or any object nested property

![image](https://user-images.githubusercontent.com/19735362/101292282-b6d17080-37cb-11eb-9895-076a9fe2ed53.png)

![image](https://user-images.githubusercontent.com/19735362/101292390-61e22a00-37cc-11eb-84c3-de14bf16e19d.png)

**Comment by mweststrate** [comment]
@saulpalv please follow the issue template. Note that `__proto__` is a JavaScript build in and can't be modified, this has further nothing to do with MobX. But probably you want to use a utility like `mobx.toJS`
