### ISSUE TITLE
Strict mode error

### ISSUE THREAD

**Issue by osenvosem** [mobxjs/mobx#267]
```javascript
import { observable, action, useStrict } from 'mobx';
useStrict(true);

class Store {
  @observable timer;
}
```
This simple code cause the Error
```
Uncaught Error: [mobx] Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode. Wrap the current method in `action` if this state change is intended
```

Just created simple webpack conf and this one entry point. The state object is not even created.

**Comment by mweststrate** [comment]
Should be fixed now. Sorry, this was an embarrassing one!

**Comment by osenvosem** [comment]
@mweststrate it seems now it works as intended. Thanks.

**Comment by sxcooler** [comment]
There's another thing, in the official docs, I couldn't find an example of useStrict, I don't know how to use it until I see this issue...
