### ISSUE TITLE
Testing actions

### ISSUE THREAD

**Issue by mmazzarolo** [mobxjs/mobx#268]
Hello there! 
First of all thank you for MobX, it's an awesome tool 👍   

After upgrading to 2.2 I started playing with `actions` and I'm trying to grasp the concept behind them because I'm having an issue on testing an async action that with the the `@action` decorator won't work.  
My async action:

```javascript
export default class MuseumsStore {
  @observable museumList = []
  @observable isLoading = false
  @observable error = null

  @action fetchMuseums = async (api = getMuseums, errorHandler = runAlert) => {
    this.error = null
    this.isLoading = true
    const response = await api()
    this.isLoading = false
    if (response.error) {
      errorHandler(response.error)
      this.error = response.error
    } else {
      this.museumList = response.map(this.createMuseum)
    }
  }

...
```

and this is my test:
```javascript
  it('fetches the museums with error', async () => {
    const museumsStore = new MuseumsStore()
    const error = 'testError'
    const api = () => ({ error })
    const errorHandler = () => null
    await museumsStore.fetchMuseums(api, errorHandler)
    expect(museumsStore.isLoading).to.be.false
    expect(museumsStore.error).to.deep.equal(error)
    expect(museumsStore.museumList).to.have.length(0)
  })
```

If I run the test this way the it fails:
```
  1) Museums Store fetches the museums with error:
     AssertionError: expected null to deeply equal 'testError'
```

Removing the `@action` decorator *makes the test pass*.  
Another interesting point is that the other tests of the `fetchMuseum` function (for example checking `museumList` value after a successfull api call) work correctly with and without the `@action` decorator.  

Am I missing something? Should I not consider the `fetchMuseum` as an action or is it simply the test framework that doesn't work correctly with actions/decorators?   

Thank you 💃

**Comment by mweststrate** [comment]
@mmazzarolo which version of MobX are you using? `2.2.0`  had an issue where it used sometimes the wrong `this` inside functions which might be related. Does upgrading to `2.2.1` make a difference. 

If that doesn't help: which transpiler are you using?

Note that you should also use `action` inside the `async`: `async action((api = ...) => {})`, because `@action` applies only to the current stack, and your async will return on a new stack.

**Comment by mmazzarolo** [comment]
@mweststrate Updated to `2.2.2`, now it seems to work correctly 👍
