### ISSUE TITLE
Wrong path to images on documentation website

### ISSUE THREAD

**Issue by alex2sat** [mobxjs/mobx#2685]
Wrong path to images on [main page](https://mobx.js.org/README.html)

![image](https://user-images.githubusercontent.com/1806103/102925384-5406f700-44a4-11eb-9182-b96b4c0cc2f8.png)

![image](https://user-images.githubusercontent.com/1806103/102925430-67b25d80-44a4-11eb-93ab-e363967d2f02.png)

**Comment by FredyC** [comment]
That will be probably my bad. Recently, I noticed the README is outdated in deployed documentation. It's being copied from the root now inside the CI configuration. I am not sure how to solve it yet. Help appreciated.
