### ISSUE TITLE
Regression: onBecomeObserved doesn't fire

### ISSUE THREAD

**Issue by pauldraper** [mobxjs/mobx#2686]
**Intended outcome:**

Simplified example:

```js
const {
  autorun,
  computed,
  observable,
  onBecomeObserved,
  runInAction,
} = require('mobx');

// LIB

// half first element of array
function halfFirst(data) {
  const first = computed(() => {
    console.log('recalculating');
    return Math.round(data.elements[0] / 2) + data.suffix;
  });

  onBecomeObserved(first, () => {
    console.log('observing first');
  });

  return first;
}

// APP

const network = observable({ model: null });

// load
const load = computed(() => {
  // wait to load it
  if (network.model) {
    return halfFirst(network.model);
  };
});

// display
const result = computed(() => load.get() ? load.get().get() : 'loading');
autorun(() => {
  console.log('Current result:', result.get());
});

runInAction(
  () => (network.model = observable({ suffix: '$', elements: [2, 4, 5] })),
);
runInAction(() => (network.model.elements[0] = 3));
runInAction(() => (network.model.elements[0] = 4));
runInAction(() => (network.model.elements[0] = 5));
```

```
Current result: loading
observing first
recalculating
Current result: 1$
recalculating
Current result: 2$
recalculating
recalculating
Current result: 3$
```

**Actual outcome:**

```
Current result: loading
recalculating
Current result: 1$
recalculating
Current result: 2$
recalculating
recalculating
Current result: 3$
```

(Not the absence of "observing first".)

**How to reproduce the issue:**

Version 6.0.4 (bug): https://codesandbox.io/s/divine-hooks-yx4fk?file=/index.js

Version 5.15.7 (no bug): https://codesandbox.io/s/sparkling-worker-kdolx?file=/index.js

**Comment by pauldraper** [comment]
Another example:

```js
const {
  autorun,
  computed,
  configure,
  makeAutoObservable,
  runInAction,
  onBecomeObserved,
} = require('mobx');

configure({
  computedRequiresReaction: true,
  enforceActions: 'always',
  observableRequiresReaction: true,
  reactionRequiresObservable: true,
});

const options = { useColors: false };
makeAutoObservable(options);
const selection = { color: 'red' };
makeAutoObservable(selection);

const blue = computed(() => {
  let val;
  if (options.useColors) {
    const isSelected = computed(() => selection.color === 'blue');
    onBecomeObserved(isSelected, () => console.log('observing'));
    val = isSelected.get();
  }
  return { isSelected: val };
});

autorun(() => console.log(blue.get()));

runInAction(() => {
  options.useColors = true;
  selection.color = 'blue';
});
```

The observing event is never fired:

```
{ isSelected: undefined }
{ isSelected: true }
```

Whereas if the initial value of `options.useColors` is true, the observing event is fired.

**Comment by pauldraper** [comment]
I believe this might also affect atoms.

**Comment by mweststrate** [comment]
Sorry for not looking into it yet! Let us know if it is blocking you

**Comment by RoystonS** [comment]
We're being hit by the same issue: `onBecomeObserved` isn't firing in MobX 6 for `@computed` properties.  If I remove the `@computed` decorator and just allow the code to flow through to the underlying `@observable` it works fine.

**Comment by pauldraper** [comment]
It is -- or rather was -- blocking me.

(I tried to tract the code, but couldn't. So I wound up implementing my own thing, with the subset of features that I needed.)

**Comment by RoystonS** [comment]
Here's a repro for our issue which _may_ help the investigation?  (I'm happy to raise a separate issue if you prefer.)
https://codesandbox.io/s/mobx6-onbecomeobserved-computed-issue-gvfze?file=/src/index.ts
In this case we see a difference in `onBecomeObserved` behaviour depending on whether a property is `@computed` or not. With the `@computed` we don't get the `onBecomeObserved` call.

This is blocking our MobX 6 upgrade: we have utilities that transform arrays of values (like [reselect](https://github.com/reduxjs/reselect) way) that depend upon knowing whether anybody is observing them or not. Our code and unit tests fail with the MobX 6 regression and I've no workaround for this one.

**Comment by mweststrate** [comment]
Looks like a bug, played a little with @RoystonS example, values are properly propagated, but oBO doesn't fire indeed: https://codesandbox.io/s/mobx6-onbecomeobserved-computed-issue-forked-95pkg

**Comment by mweststrate** [comment]
Thanks for the detailed test reports! Did put up a diff that should address the issue
