### ISSUE TITLE
Regression: Objects have enumerable $transformId property on them.

### ISSUE THREAD

**Issue by bradtgmurray** [mobxjs/mobx#2687]
We recently updated our codebase from 5.14.2 to 5.15.7 and we have a codepath that calls `JSON.stringify` on an MobX observable. Starting with the new version, we started getting a new property visible on our objects in some cases.

![image](https://user-images.githubusercontent.com/33967/103020500-7cc7d480-4516-11eb-983f-4e00fef279a8.png)

Sounds like this was reported once before a number of years ago and fixed, #170.

**Intended outcome:**

I believe this property isn't intended to be enumerable

**Actual outcome:**

It's there!

**How to reproduce the issue:**

Let me know if you'd like me to produce a minimal reproduction.

**Versions**

Bisected this down to a commit that updated mobx from 5.14.2 to 5.15.7 with no other package changes.
Using mobx-utils 5.5.0

**Comment by bradtgmurray** [comment]
Doing a bit of digging, this property comes from mobx-utils, not mobx, but we only updated mobx-utils as part of the commit that started causing this behaviour (according to our yarn.lock contents)...

**Comment by FredyC** [comment]
If it's problem in mobx-utils then please move your report to the relevant repo. Ideally, try to contribute fix yourself if it's a big problem for you.

**Comment by bradtgmurray** [comment]
Did a bit more digging and it looks like mobx-utils is correctly adding the property as non-enumerable, but then at some point the property becomes enumerable. Again, this only happened when we upgraded mobx 5.14.2 to 5.15.7 without any change to the mobx-utils package.

**Comment by FredyC** [comment]
Please try to upgrade to MobX 6, we no longer support V5.

**Comment by mweststrate** [comment]
cc @urugator, I think this would fail in current MobX 6 as well?

This might be a nice example of why @urugator's proposed approach to enumerability is better than the current on in MobX 6 (sorry, still reviewing the underlying PR first, kinda hard to scrape the time in a lock-down with homeschooling😅)

**Comment by urugator** [comment]
Can you check if `isObservableProp(object, '$transformId')` when it becomes enumerable?
One way it could suddenly become observable (and therefore enumerable) is if there is an assigment `object['$transformId'] = newId` (changed in the PR for V6 - the value is assigned and fields stays non-observable)
Small repro could help.

**Comment by bradtgmurray** [comment]
Bah, found a call to Lodash's `cloneDeep` in the code path, which is the cause of the '$transformId` becoming enumerable (see https://github.com/lodash/lodash/issues/3043). 

It's still a mystery to me why a MobX upgrade shook this loose, but at this point I'm guessing it's our buggy code.
