### ISSUE TITLE
Broken redirect links in mobxjs/mobx-react

### ISSUE THREAD

**Issue by simon04** [mobxjs/mobx#2692]
The repository `mobxjs/mobx-react` archived, but still shows up as first search result (in DuckDuckGo).

1. The redirect link added in https://github.com/mobxjs/mobx-react/commit/3fcb0d69828acf1018c35bfb23a12d5ef21dbcad does not work (since the branch `mobx6` no longer exists). Can the link be changed to https://github.com/mobxjs/mobx/tree/main/packages/mobx-react?

2. The link in the GitHub about section to https://mobx.js.org/refguide/observer-component.html does not work.

**Comment by FredyC** [comment]
Fixed 1, it was already reported in #2646 but I forgot about it.

Can you be more specific about what "Github about section" you have in mind?

**Comment by simon04** [comment]
![2020-12-30-182037](https://user-images.githubusercontent.com/782446/103369935-b925a280-4acb-11eb-9b88-bbf0c423e522.png)

**Comment by FredyC** [comment]
Thanks, fixed.

**Comment by simon04** [comment]
Thank you for the quick fixes!
