### ISSUE TITLE
Observer not working when I slice/pop observable array. Mobx 5

### ISSUE THREAD

**Issue by MenachemICTBIT** [mobxjs/mobx#2697]
This bug has caused me confusion several times in the past and I want a definite answer as to why this is occurring. 

**Intended outcome:**

I want my observer to see changes in store when pushing or slicing from an observable array.

**Actual outcome:**

The observer does not see the changes unless I clone the array or perform some other major change to the observable array. 

**How to reproduce the issue:**
```
export default class DevicesStore {
	@observable
	hideColumns: string[] = observable([]);

	constructor() {}
}
```

```
const TableSettingsModal = observer(() => {

        const devicesStore = rootStores[DEVICES_STORE];

	const handleSelectionChange = e => {
		if (devicesStore.hideColumns.includes(e.target.innerText)) {
			const indexToRemove = devicesStore.hideColumns.findIndex(item => item === e.target.innerText);
                        devicesStore.hideColumns.splice(indexToRemove, 1);
		} else {
			devicesStore.hideColumns.push(e.target.innerText);
		}
	};
};
```

I am forced to rewrite my code to perform a clone of the observable array as such. 
```
const TableSettingsModal = observer(() => {

        const devicesStore = rootStores[DEVICES_STORE];

	const handleSelectionChange = e => {
		if (devicesStore.hideColumns.includes(e.target.innerText)) {
			const indexToRemove = devicesStore.hideColumns.findIndex(item => item === e.target.innerText);
			devicesStore.hideColumns = [...devicesStore.hideColumns.splice(indexToRemove, 1)];
		} else {
			devicesStore.hideColumns = [...devicesStore.hideColumns, e.target.innerText];
		}
	};
};
```

**Versions**
mobx: ^5.15.4
mobx-react: ^6.1.4
mobx-react-lite: ^1.4.2

Perhaps the reason is that I'm using mobx-react version 6? Is that equal to mobx version 6? (I know there are major changes between 4/5 and 6).

**Comment by FredyC** [comment]
We no longer support MobX V4/V5, please upgrade or check compatibility table: https://github.com/mobxjs/mobx-react#choosing-your-version

**Comment by mweststrate** [comment]
Both approaches should work. Maybe you are passing the `hideColumns` array
to a component that isn't an observer? In that case only the second
approach would work. Please note that we will need a repro to be able to
tell more. The combination of deps looks fine.

**Comment by MenachemICTBIT** [comment]
@mweststrate The code above is the exact code (minus a bunch of other unrelated stuff) that I have with the array being decorated with an observable and the calling component being wrapped with an observer.

 I verified with several engineers on my team that the first approach (pop/slice observable array) does not work, but cloning and replacing it, does. This is also not the first time that we've encountered this issue.

**Comment by FredyC** [comment]
@MenachemICTBIT Please provide a runnable example (eg. with CodeSandbox) that we can investigate. It's not usual that your code snippets are lacking some environmental setup you do not realize and is causing the problem.

**Comment by mweststrate** [comment]
@MenachemICTBIT I imagine it is the same, but it doesn't show how `hideColumns` is _used_. In the first approach you change the _array_, in the second the _property_. If the current (or any other) `observer` component looks only at the _property_, but doesn't read the array itself (for example because it is passed somewhere else), the component (correctly) wouldn't react, as a mutation of the array would be irrelevant to the `observer` wrapped component since it isn't read.
