### ISSUE TITLE
Mobx MVVM example by mobx-roof

### ISSUE THREAD

**Issue by xiamidaxia** [mobxjs/mobx#270]
Mobx-roof is a simple React MVVM framework based on mobx.

[mobx-roof](https://github.com/mobx-roof/mobx-roof)
[mobx-roof-boilerplate](https://github.com/mobx-roof/mobx-roof-boilerplate)

**Comment by mweststrate** [comment]
Nice :) thanks for sharing. Feel free to add it here: https://github.com/mobxjs/mobx#related-projects
