### ISSUE TITLE
Please document crucial change in reaction in upgrading to v6 docs

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx#2707]
I read through the upgrading docs and changelog carefully. Then upgraded to version 6. Next day, I get reports that my offline app is not writing changes to the server any more.

Turns out that reaction has changed it's behavior: The docs for reaction now explicitly say ([link](https://mobx.js.org/reactions.html#reaction)):

> Unlike autorun, the side effect won't run once when initialized, but only after the data expression returns a new value for the first time

Sadly I haven't found the documentation concerning this for the previous version. But from the behavior change in my app it is obvious that this was not the way a reaction behaved before. And as my app is using a reaction to detect changes in queued operations as a basis for communicating with the server ([link](https://github.com/barbalex/vermehrung/blob/master/src/store/index.js#L133-L245)), that completely broke the app.

So please add this info to the changes when upgrading to version 6. To prevent others from running into it.

And thanks for this great tool.

**Comment by barbalex** [comment]
Now I am left with wondering how I can now get my reaction to react when it is initialized. Is there an easy trick to do this?

**Comment by FredyC** [comment]
Wait, reaction never fired initially unless you specify `fireImmediately` option to it: https://mobx.js.org/reactions.html#fireimmediately-_reaction_

**Comment by mweststrate** [comment]
The behavior of autorun and reaction didn't change, so something else is
amiss. (And do look into your test coverage ;-)). If you can find the
difference, feel free setting up two sandboxes demonstrating the
difference. Also note that reaction supports a 'fireImmediately' flag if
you want to run the effect straight away.

**Comment by barbalex** [comment]
I was not using `fireImmediately` in version 5.

After some more testing it seems that what caused the difference was not initial firing (but thanks a lot for that pointer) but the observables the reaction was watching. In my case: ``${self.queuedQueries}/${self.shortTermOnline}``

I had to change this to the following to get it to work in version 6: ``${self.queuedQueries.size}/${self.shortTermOnline}``.

queuedQueries is a map: https://github.com/barbalex/vermehrung/blob/master/src/store/index.js#L111

So maybe the way maps are observed has changed?

**Comment by barbalex** [comment]
And yes, not testing is obviously the reason this accident happened to my app 🙄

**Comment by mweststrate** [comment]
Ah, I suspect your reaction was working quite by accident in MobX 5, where
the `toString()` of a map would print out the full data set (!), thereby
observing it, where toString in 6 works works more like a normal toString,
just printing the type, so the fix look correct and a lot more efficient as
well.

**Comment by barbalex** [comment]
> your reaction was working quite by accident in MobX 5

lol

Well, when creating it, I _did_ try both methods: using size and not. But you're right, using .size must be much more efficient.

Thanks for great help. And most of all: For developing and upkeeping great tools!
