### ISSUE TITLE
not working decorator @observable

### ISSUE THREAD

**Issue by RussianDragon** [mobxjs/mobx#2708]
Hi.
Starting from version 6.0.0, the @observable decorator not working.

registration-store.ts
```
import { observable } from "mobx";

interface FormRegistration {
    name: string;
}

export class RegistrationStore {
    @observable
    public form: FormRegistration;

    constructor() {
        this.form = {
            name: "tt"
        };
    }
}


```
registration.tsx
```
import React from 'react';

import { useObserver } from 'mobx-react-lite';
import { RegistrationStore } from '../stores/registration/registration-store';

const store = new RegistrationStore();

export function RegistrationComponent() {
    return useObserver(() => <div>
        <span>{store.form.name}</span>
        <input type="text" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
            store.form.name = event.target.value;
        }} />

    </div>);
};
```

But working if write this.form = observable({ name: "tt" })

**Comment by mweststrate** [comment]
Follow the issue template. Read the migration guide.

**Comment by RussianDragon** [comment]
> Follow the issue template. Read the migration guide.

Where is migration guide on 6 version?
I don't need "makeAutoObservable(this)" all сlass, I want observe only specific fields.

**Comment by kubk** [comment]
It's documented here: https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable

If you'd like to use decorators you have to call `makeObservable(this)`:

![image](https://user-images.githubusercontent.com/22447849/104283177-346e5780-54c1-11eb-9794-9441273f9b1c.png)

**Comment by RussianDragon** [comment]
> It's documented here: https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable
> 
> If you'd like to use decorators you have to call `makeObservable(this)`:
> 
> ![image](https://user-images.githubusercontent.com/22447849/104283177-346e5780-54c1-11eb-9794-9441273f9b1c.png)

Thank you.
But it's sad...

**Comment by FredyC** [comment]
> But it's sad...

It is but complain about it at TC-39 if you like. You can read about the reasoning behind this at https://michel.codes/blogs/mobx6
