### ISSUE TITLE
No warning about changing an observable outside an action if called from a reaction

### ISSUE THREAD

**Issue by vorou** [mobxjs/mobx#2718]
**Intended outcome:** When changing an observable in the strict mode outside an action there should be a warning `Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed.`

**Actual outcome:** If the invalid change happens as a part of a reaction, no warning is present (it's there if it's an autorun though).

**How to reproduce the issue:** https://codesandbox.io/s/ts-mobx-no-react-1rsgd?file=/src/index.ts

**Versions**
mobx 6.0.4

**Comment by urugator** [comment]
It's "re**action**", the second callback arg is wrapped in `action` implicitly.
`autorun` automatically applies batching, but not an `action` (as it would also applied `untracked` making autorun unable to subscribe for anything)

**Comment by FredyC** [comment]
> It's "re**action**", the second callback arg is wrapped in `action` implicitly.
> `autorun` automatically applies batching, but not an `action` (as it would also apply `untracked` making it unable to subscribe for anything)

I did not know that either. Do have that covered in docs somewhere? No mention of this here: https://mobx.js.org/reactions.html#reaction

**Comment by mweststrate** [comment]
Yep, that should have been mentioned in the first paragraph!

**Comment by vorou** [comment]
I surely trust you guys on this, but from a beginner's point of view it looks kinda inconsistent
I guess I'm wrong in thinking that the main idea of action is that it changes some observables
bc if it's true then it's weird that reaction always wrap it in action, but then the docs make it explicit that generally, you should not update any observables in a reaction
https://mobx.js.org/reactions.html#use-reactions-sparingly

**Comment by urugator** [comment]
You're absolutely right, it's weird and it's the same situation with `autorun`, because you shouldn't mutate state there either, but yet it applies batching.
However people are doing so anyway, either for historical reasons or simply because of different opinions.
So we have to options:
Allow mutations - then we should consider it a valid use case and do our best to keep things working optimally (apply action/batching).
Dissallow mutations - which means to break existing code bases and upset a lot of ppl who would swear on this feature.

**Comment by vorou** [comment]
@urugator got you, thanks for the explanation

**Comment by beilo** [comment]
This is what I do now

```js
React.useEffect(
    () =>
      autorun(() => {
        if (rootStore.count === 10) {
          runInAction(() => {  // key point
            rootStore.add();
          });
        }
      }),
    []
  );

```

**Comment by urugator** [comment]
Please start a new discussion, providing complete (ideally runnable) example. Nobody knows what your intention is, how rootStore looks like etc. Quick suggestion would be:
```javascript
class RootStore {
  setCount(count) { 
    if (this.count === 10) {
      this.add()
    }
  }
}
```
