### ISSUE TITLE
[mobx-undecorate] Lot's of "Cannot read property 'start' of null" errors

### ISSUE THREAD

**Issue by nejsimon** [mobxjs/mobx#2747]
Running the mobx-undecorate utility in a fairly large react + typeascript project created using creat-react-app produces lots of these warnings:

> Users/simonstrandman/work/.../file.ts Transformation error (Cannot read property 'start' of null)
> TypeError: Cannot read property 'start' of null
>     at warn (/Users/simonstrandman/work/.../node_modules/mobx-undecorate/src/undecorate.ts:405:38)
>     at createConstructor (/Users/simonstrandman/work/.../node_modules/mobx-undecorate/src/undecorate.ts:341:17)
>     at NodePath.<anonymous> (/Users/simonstrandman/work/.../node_modules/mobx-undecorate/src/undecorate.ts:195:13)
>     at /Users/simonstrandman/work/.../node_modules/mobx-undecorate/node_modules/jscodeshift/src/Collection.js:75:36
>     at Array.forEach (<anonymous>)
>     at Collection.forEach (/Users/simonstrandman/work/.../node_modules/mobx-undecorate/node_modules/jscodeshift/src/Collection.js:74:18)
>     at transform (/Users/simonstrandman/work/.../node_modules/mobx-undecorate/src/undecorate.ts:168:37)

This happens in `mobx-undecorate/src/undecorate.ts` in the function `warn()`:

```ts
function warn(msg: string, node: Node) {
    if (process.env.NODE_ENV === "test") {
        return
    }
    const line = lines[node.loc!.start.line - 1] // <-- This line is causing the crash
    const shortline = line.replace(/^\s*/, "")
    console.warn(
        `[mobx:undecorate] ${msg} at (${fileInfo.path}:${node.loc!.start.line}:${
            node.loc!.start.column
        }):\n\t${shortline}\n\t${"^".padStart(
            node.loc!.start.column + 1 - line.indexOf(shortline),
            " "
        )}\n`
    )
}
```

Turns out `node.loc` can in fact be null. If I change the above with a null check on `node.loc` before using it, it runs properly and the actual warnings is outputed to the console. In my case the warning was:
> Generated new constructor for class  Foo. But since the class does have a base class, it might be needed to revisit the arguments that are passed to `super()`

**Comment by mweststrate** [comment]
PR welcome :)

**Comment by iChenLei** [comment]
@nejsimon Any minimal reproduction code snippet (link / github repo / snippet comment)? If you have no time to create PR and I can do it , but need reproduction code to check this problem and add unit test. 😄

**Comment by xiluo58** [comment]
One example with error
```
import { useSearch } from "./useSearch";

export function useAlias(): string {
    const parsedSearch = useSearch();
    return (<string>parsedSearch.alias || "").toUpperCase();
}
```

There is no error if type casting is removed
```
import { useSearch } from "./useSearch";

export function useAlias(): string {
    const parsedSearch = useSearch();
    return (parsedSearch.alias || "").toUpperCase();
}
```

In my project jsx code is only in files with tsx extension. There should be an option to let the parser don't parse js/ts files as jsx

**Comment by xiluo58** [comment]
Invalid code:
```
import React from "react";
import { inject, observer } from "mobx-react";
import { computed } from "mobx";

@inject("store")
@observer
export class ActionItems extends React.Component<any, {}> {
    @computed private get name() {
        return "name";
    }

    public render() {
        return <div>{this.name}</div>;
    }
}
```

Valid code: 
```
import React from "react";
import { inject, observer } from "mobx-react";
import { computed } from "mobx";

@inject("store")
@observer
export class ActionItems extends React.Component<any, {}> {
    @computed private get name() {
        return "name";
    }
    
    constructor(props) {
        super(props);
    }

    public render() {
        return <div>{this.name}</div>;
    }
}
```

This error happens if there is no constructor. I pushed the code to https://github.com/xiluo58/mobx-undecorate-reproduce/tree/main/start-null

**Comment by iChenLei** [comment]
@xiluo58 Thanks for your reproducation code, I debug these code and find why we encount issue.
#### Reproduction Code
```js
import React from "react";
import { inject, observer } from "mobx-react";
import { computed } from "mobx";
@inject("store")
@observer
export class ActionItems extends React.Component<any, {}> {
    @computed private get name() {
        return "name";
    }
    public render() {
        return <div>{this.name}</div>;
    }
}
```
#### Why the loc will be `null`
> https://github.com/benjamn/recast/blob/master/lib/util.ts#L180-L183
```js
  } else if (node.declaration && isExportDeclaration(node)) {
    // Nullify .loc information for the child declaration so that we never
    // try to reprint it without also reprinting the export declaration.
    node.declaration.loc = null;
```
👇  Look the AST structure, our `ClassDeclaration`'s loc isn't `null`

![2021-01-30 13 46 21](https://user-images.githubusercontent.com/14012511/106350898-464e5800-6313-11eb-9cf4-df1ee7695b8d.png)


👇  After `recast` modify our AST structure.

![2021-01-30 13 47 24](https://user-images.githubusercontent.com/14012511/106350974-e4422280-6313-11eb-94ad-4e5d0faf0203.png)

#### Summary
`mobx-undecorate` is built on top of `facebook/jscodeshift`, and `jscodeshift` use `recast` as dependencies.
`mobx-undecorate` use `@babel/parser` as the AST parser.
👇  codemod script function call stack chian 

/** ommited  **/
> https://github.com/facebook/jscodeshift/blob/master/src/core.js#L82
```js
return fromAST(recast.parse(source, options));
```
/** ommited  **/
> https://github.com/benjamn/recast/blob/master/lib/util.ts#L152
```js
export function fixFaultyLocations(node: any, lines: any) {
```
/** ommited  **/
```js
node.declaration.loc = null;
```
>btw VScode is very useful for debug js/ts project 😃 

### 100% reproduction code
class comp with export before and class without constructor

### solution
Add null check for `node.loc` and show important warn message enough when loc is null.
