### ISSUE TITLE
Mobx 6.1 breaks spying on actions in unit test

### ISSUE THREAD

**Issue by heath-freenome** [mobxjs/mobx#2752]
**Intended outcome:**

In our unit tests we are using the `jest.spyOn()` function to ensure that certain actions are called under certain conditions (with expected values) in our components.

**Actual outcome:**

With the 6.1 release changes all of our spys are failing in the same manner as below
```
setUsernameSpy = jest.spyOn(authStore, 'setUsername');
```
results in:
```
TypeError: Cannot assign to read only property 'setUsername' of object '[object Object]'
```

**How to reproduce the issue:**
I'm pretty sure it's obvious how to reproduce the issue. My question is HOW can I verify that an action on an observable is called with the proper arguments now that 6.1 is available? Is there an option I can set to turn off making actions read-only for tests?

**Versions**
6.0.4 - working
6.1 - not working

**Comment by urugator** [comment]
>  Is there an option I can set to turn off making actions read-only for tests?

Not yet, but we would like to adress this somehow and we are open to suggestions.
We would like to avoid a global config flag as that could cause some actually broken code to pass the tests.

**Comment by urugator** [comment]
We would like to know if it's only about writability of actions or whether we should also expect demand for configurability of actions or other fields (computed/observable). 
So if anyone reading this has an experienced in testing mobx based codebases, we want to hear from you!
We would like to keep things constrained to keep user in the safe zone, but we also don't want to throw obstacles in the way for legitime use cases.

**Comment by vkrol** [comment]
@urugator 
> We would like to know if it's only about writability of actions or whether we should also expect demand for configurability of actions or other fields (computed/observable).

It might be helpful:
> Jest should be able to mock non-writable but configurable properties.
> Currently jest will throw an error when trying to replace non-writable (but configurable) properties.

https://github.com/facebook/jest/issues/8656

**Comment by heath-freenome** [comment]
Are actions still configurable? If so, then maybe before applying the spy I can make it temporarily writable?

**Comment by urugator** [comment]
Depends if it's plain object or not. All annotated fields of non-plain objects (classes) are non-configurable as well.
We will probably end up with `configure({ safeDescriptors: false })` or something like that. Actually already working on it, but still considering alternatives...

**Comment by heath-freenome** [comment]
I'm using classes, so what can I expect?

**Comment by urugator** [comment]
Non-configurable ... the main reason is that we want to prevent following:
```javascript
class Child extends Parent {   
   // This is like calling defineProperty with new descriptor
   // It breaks all assumptions we made about the field in parent
   // and there is no reasonable way for us to detect this.
   // So we prevent it by making the field non-configurable in parent
   inheritedProp = 5;
   inheritedArrowFunc = () => {};   
}
```

**Comment by josuemontano** [comment]
@urugator I think being able to mock/spy actions is good enough. I cannot think about a use case where mocking an observable or computed is necessary or even good practice.

I've being writing MobX specs in large code bases for over a year and never had the need to mock an observable or computed.

Unfortunately version 6.1 broke many specs so upgrading is not an option for us till this is fixed. Thanks for your work!

> We would like to know if it's only about writability of actions or whether we should also expect demand for configurability of actions or other fields (computed/observable).

**Comment by urugator** [comment]
> broke many specs so upgrading is not an option for us till this is fixed

@josuemontano Is there anything specific you would like to see adressed or behaving differently?

**Comment by heath-freenome** [comment]
> I'm using classes, so what can I expect?

What I meant was, what can I expect from your solution to this issue?

**Comment by mweststrate** [comment]
Check the 6.1.2 release notes on 😊

**Comment by ljani** [comment]
This seems to break [`auto-bind`](https://www.npmjs.com/package/auto-bind) as well. Some observations:

- `autoBind(this); makeObservable(this);` will work with `@action.bound` and seems to work (I guess mobx needs to do the same and thus it is writable)
- `autoBind(this); makeObservable(this);` works once with `@action`, but breaks when the same class is instantiated the second time (bad)
- `makeObservable(this); autobind(this);` with `@action` fails instantly (good)
- - `makeObservable(this); autobind(this);` with `@action.bound` fails instantly (okay, I guess)

As you can guess, I'm worried about the second case. I wonder if there are any solutions to make it at least fail instantly, other than copying React and running everything twice.

**Comment by urugator** [comment]
> autoBind(this); makeObservable(this); works once with @action, but breaks when the same class is instantiated the second time (bad)

Took me a while to understand why this happens and I've learned something new about JS :D
The first time the constructor runs, the prototype method is turned into an action and becomes `writable: false`.
The second time when you try to `this.action = whatever`, it will use **inherited descriptor**, which says that the field is **non-writable** therefore the error ... the only way to create `action` on instance is via `defineProperty` (which we use internally for bound actions therefore no error).
I will take a look if we can keep things on proto writable - that does NOT mean that modifying prototype over time is supported! It's just unlikely to happen...

**Comment by urugator** [comment]
@ljani #2766 should fix this

**Comment by urugator** [comment]
Can we close this or are there any remaining issues?

For future readers, since 6.1.3 there is [a new configuration option `configure({ safeDescriptors: false })`](http://localhost:3000/configuration.html#safedescriptors-boolean)

**Comment by mweststrate** [comment]
Closing issue as to many different symptoms are already being discussed. New issues can be reported in a fresh issue with a repro against 6.1.4
