### ISSUE TITLE
@override not work for arrow function

### ISSUE THREAD

**Issue by zhangchao828** [mobxjs/mobx#2756]
**Intended outcome:**
`@override` work well  on sub classses for arrow function

**Actual outcome:**
error:Cannot redefine property: add

**How to reproduce the issue:**
```js
class SuperStore {
  constructor() {
    makeObservable(this)
  }
  @observable count = 0
  @action add = () => {
    this.count += 1
  }
}
class SubStore extends SuperStore {
  @override add = () => {
    this.count += 2
  }
}
```

**Versions**
mobx: 6.1.0
mobx-react: 7.1.0

**Comment by iChenLei** [comment]
Online codesandbox reproduction link is better 😄 
https://codesandbox.io/s/simple-mobx-todolist-forked-0cb1h
@urugator is the author of #2641 , maybe urugator can answer your question.

**Comment by urugator** [comment]
Works as intended, please see the example in documentation.
https://mobx.js.org/observable-state.html#makeobservable second tab

**Comment by urugator** [comment]
Btw `action.bound` is overridable as well, so you can use it instead. That should be probably mentioned in docs...

**Comment by iChenLei** [comment]
### official doc https://mobx.js.org/observable-state.html#makeobservable _second tab_
####   👇     It works
```js
import React from "react";   // v17.0.1
import { render } from "react-dom";  // v17.0.1
import { makeObservable, observable, action  } from "mobx";  // v6.1.1
import { observer } from "mobx-react-lite"; // v3.2.0

class SuperStore {
  constructor() {
    makeObservable(this)
  }
  @observable count = 0
  add = action(() => {
    this.count += 1
  })
}
class SubStore extends SuperStore {
  add = action(() => {     👈🏻   // override success, but no `override` annotation, it's weird
    this.count += 10
  })
}

const CounterView = observer(({ appState }) => (
  <button onClick={appState.add}>Seconds passed: {appState.count}</button>  👈🏻  // click it show `10`
));

render(
  <div>
    <CounterView appState={new SubStore()} />
  </div>,
  document.getElementById("root")
);

```
![2021-01-29 11 35 40](https://user-images.githubusercontent.com/14012511/106228371-2c831700-6226-11eb-8635-c6611705cb62.png)

####   👇     It's broken
```diff

- import { makeObservable, observable, action  } from "mobx";  // v6.1.1
+ import { makeObservable, observable, action, override  } from "mobx";  // v6.1.1

class SuperStore {
  constructor() {
    makeObservable(this)
  }
  @observable count = 0
- add = action(() => {
+ @action add = () => {
    this.count += 1
-  })
+ }
}
class SubStore extends SuperStore {
-   add = action(() => {
+  @override
 add = () => {
    this.count += 2
-  })
+ }
}
```
![2021-01-29 11 45 42](https://user-images.githubusercontent.com/14012511/106228975-889a6b00-6227-11eb-9319-03f11ef27b79.png)

### official doc example 
>  subclass + makeObservable
```js
import { makeObservable, observable, computed, action } from "mobx"

class Parent {
    constructor(value) {
        makeObservable(this, {
            /*** ommited **/
            arrowAction1: action
        })
    }

    /*** ommited **/

    // not overridable    👈   //  not overridable 💀
    arrowAction1 = () => {}

    // workaround - not annotated - overridable    👈   // offical guide for arrow function override
    overridableArrowAction1 = action(() => {})
}

class Child extends Parent {
   /*** ommited **/

    // workaround - not annotated - overrides     👈   // offical guide for arrow function override
    overridableArrowAction1 = action(() => {})

   /*** ommited **/
}

/**
All annotated fields are non-configurable. All non-observable (stateless) fields (action, flow) are
non-writable.Only action, computed, flow, action.bound defined on prototype can be overriden 
by subclass. Field can't be re-annotated in subclass, except with override.
*/
```

### Summary
Maybe we need mentioned in docs, It's weird for me too 😢 
If needed, I will push the minimal reproduction demo to github.

**Comment by mweststrate** [comment]
I think we should push people in the docs to use `action.bound` instead of arrow functions. It doesn't has this pitfall, and is cleaner anyway :)

**Comment by urugator** [comment]
What exactly isn't clear? The rule is simple:
**You can only override things defined on prototype (methods and getters)**.
`x = y` is defined on instance, doesn't matter whether `y` is function, arrow function, number or whatever.
Everything that wouldn't work throws instead of failing silently.
Everything else behaves like normal JS + being appropriately annotated/decorated.

`override` annotation is **optional**, but it checks that there is something to override. 
Eg if your colleague removes a function from a class that you extend, the override will throw and you will be forced to change `@override` into `@action`. Otherwise your method would suddenly stopped being an action without knowing.
Also it could become mandatory in the future, therefore it's not mentioned in docs.

```javascript
@action add = () => {}
@override add() {}
```
This wouldn't work even without annotations and there is no way for us to detect this.

Still, thanks for the input, I will take a look if we can make some things more pronounced in docs.

**Comment by akphi** [comment]
> Yeah, `action.bound` should be emphasized in the docs over arrow functions.

We're actually doing the exact opposite now 😄

**Comment by urugator** [comment]
The documentation was updated, feedback welcomed.
