### ISSUE TITLE
Mobx codesandbox is outdated

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx#2777]
The link used in GitHub mobx template is outdated:
https://codesandbox.io/s/minimal-mobx-react-project-ppgml

![image](https://user-images.githubusercontent.com/22447849/106613891-c2e36f80-657b-11eb-9e04-72ec062f7e4e.png)

Mobx and React versions should be updated, the code should be updated to Mobx strict actions mode. Is this issue template under Git control, can I change it?

EDIT: Here is up-to-date version: https://codesandbox.io/s/magical-dhawan-jq8t5?file=/index.js

**Comment by FredyC** [comment]
We have MobX workspace on CodeSandbox, I've invited you there. It's the better way than having different versions all over the place.

**Comment by kubk** [comment]
@FredyC Thank you. Codesandbox documentation says that to edit a template I should unfreeze it first, otherwise Codesandbox will create a fork: https://codesandbox.io/docs/templates 

For some reason the "unfreeze" option is not available for me:

![image](https://user-images.githubusercontent.com/22447849/106720889-0f2ebe00-6615-11eb-9dd5-b74b1abd78d5.png)

Codesandbox shows me that I am a member of Mobx docs: https://codesandbox.io/u/kubk

Am I missing some permissions? Anyway, you can copy the code from my fork and update all the dependencies to the latest: https://codesandbox.io/s/magical-dhawan-jq8t5?file=/index.js

**Comment by FredyC** [comment]
That's really strange, you have the same permissions as me (Editor). It's updated now, thanks for noticing it.

![image](https://user-images.githubusercontent.com/1096340/106734696-98dd8c00-6613-11eb-93a8-620c68c86c22.png)
