### ISSUE TITLE
jest.spyOn not working with mobx class methods

### ISSUE THREAD

**Issue by publicJorn** [mobxjs/mobx#2784]
**Intended outcome:**

When using mobx **6.0.5** I was still able to `jest.spyOn` a method of a class

**Actual outcome:**

Since **6.1.0** the spyOn throws an error:

`TypeError: Cannot assign to read only property 'fetch' of object '[object Object]'`

where `fetch` is the name of the method.

**How to reproduce the issue:**

I tried making a working example on codesandbox, but I don't know how to make the test actually run.  
https://codesandbox.io/s/mobx-jest-spyon-u01lr

I used `flow` for the examples, but the error is thrown with a normal method/action as well.

**edit:**

Well... maybe this is a question instead of a bug.. Does `jest.spyOn(store, 'fetch')` count 
as a "direct object manipulation" as described in:  https://github.com/mobxjs/mobx/blob/main/packages/mobx/CHANGELOG.md#610

(fetch is a `flow`, could also be an `action`)

If so, how do I circumvent this?

**Comment by iChenLei** [comment]
Duplicate #2753  (These discussion should help you
> For future readers, since 6.1.2 there is a new configuration option `configure({ safeDescriptors: false })`

**Comment by publicJorn** [comment]
Oh.. really sorry for double-posting.. I should have searched closed issues.

Adding `{safeDescriptiors: false }` didn't work for me. Will read the whole post in more detail, may find a solution yet.

**Comment by iChenLei** [comment]
@publicJorn  https://mobx.js.org/configuration.html#safedescriptors-boolean
And did you upgrade mobx to latest version( >= 6.1.2) ? If you still can't find solution, please @ me.
We will track your issue. 😃

**Comment by publicJorn** [comment]
Thanks @iChenLei!

I've made a test case as simple as I could, but it's still not working. I'm probably doing something wrong.

```js
import { makeAutoObservable, configure } from 'mobx'

let instance

beforeEach(() => {
  configure({ safeDescriptiors: false })

  instance = makeAutoObservable({
    id: 'abc',
    imCalled: (arg) => console.log(arg),
    doStuff: () => this.imCalled('yes'),
  })
})

test('update object', () => {
  const spy = jest.spyOn(instance, 'imCalled')
  instance.doStuff()
  expect(spy).toHaveBeenCalledWith('yes')
})
```

This gives the error: `TypeError: Cannot assign to read only property 'imCalled' of object '[object Object]'`

It doesn't matter where I put `{ safeDescriptors: false }`. In beforeEach/All or even setupTests.js.

Working example repo here. Based on CRA because it was easy to set up: https://github.com/publicJorn/mobx-jest

**Comment by iChenLei** [comment]
@publicJorn  I got it, will spend some time to dig it.

**Comment by urugator** [comment]
You have a typo there: `safeDescript---i---ors: false`

**Comment by urugator** [comment]
Btw `doStuff: () => this.imCalled('yes')` won't work - `this` is not the invoking object if you use arrow function

**Comment by publicJorn** [comment]
🙈  oh boy... almost weekend.

thanks guys for your time. will take a longer break next time!

**Comment by iChenLei** [comment]
Thank you @urugator .
## configure typo
```diff
- configure({ safeDescriptiors: false })
+ configure({ safeDescriptors: false })
```

## `this` error
```js
doStuff: () => this.imCalled('yes')
```
![2021-02-05 18 58 19](https://user-images.githubusercontent.com/14012511/107025253-1f48c800-67e4-11eb-9814-a173014e9291.png)

##  After fix `typo` and `this` 
![2021-02-05 19 00 48](https://user-images.githubusercontent.com/14012511/107025478-78186080-67e4-11eb-8e34-946f5191fd5b.png)

everything works fine.  @publicJorn

**Comment by bovas85** [comment]
I can still see the issue with latest mobx 6.3.0 at the time of posting this.

**Comment by urugator** [comment]
@bovas85 Can you be a little bit more specific?

**Comment by iChenLei** [comment]
@bovas85 Create a new issue for your problem please, thanks!

**Comment by bovas85** [comment]
Thanks, created https://github.com/mobxjs/mobx/issues/2926 @iChenLei
