### ISSUE TITLE
Can't catch thrown 'FLOW_CANCELED' anywhere

### ISSUE THREAD

**Issue by DMS40** [mobxjs/mobx#2790]
**Intended outcome:**

This issue came from [here](https://github.com/mobxjs/mobx/discussions/2789)

When flow function's `cancel()` fired, Can't catch thrown 'FLOW_CANCELED' anywhere

![image](https://user-images.githubusercontent.com/78593468/107032770-abb0b600-67f7-11eb-8ccb-d0f8856dd66d.png)

**Actual outcome:**

Can catch the flow function's `cancel()` fired, for don't want to show throw error message

This also interferes with the integrated test. like for react-testing-library

**How to reproduce the issue:**

https://codesandbox.io/s/magical-hugle-qc0d1?file=/src/App.js

**Versions**
mobx : 6.1.5
mobx-react-lite : 3.2.0
react : 17.0.1
react-dom : 17.0.1
react-scripts : 4.0.0

**Comment by urugator** [comment]
```javascript
useEffect(() => {
    const fetch = flowResult(store.flowAction());
    // ---
    fetch.catch(error => console.log("CATCHED"));
    // ---
    return () => fetch.cancel();
  }, [store]);
```

**Comment by iChenLei** [comment]
`issue` Errors handing for effect callbacks
https://github.com/testing-library/react-hooks-testing-library/issues/308

I think we should add these special case to document, The officical example not work on this case.
https://mobx.js.org/actions.html#flow-wrap

### urugtor's code snippt is great solution.

![2021-02-06 20 33 16](https://user-images.githubusercontent.com/14012511/107118227-8b95fb00-68ba-11eb-82e8-f80c38069917.png)

**Comment by DMS40** [comment]
Oops! It's my mistake not to try that way. Thank you @urugator 

I thought it should be handled inside the flow method! 

I tried it on the actual product and it worked perfectly as I wanted.

@iChenLei 
Should I close this issue? Or will you close it after considering what you were talking about?

**Comment by iChenLei** [comment]
> https://mobx.js.org/actions.html#cancelling-flows-

@DMS40  please keep it until we get a unanimous view for `Do we need mention this case in official doc `, Thanks
Better doc , Better development experience 😄  @mweststrate Any suggestion ?

**Comment by mweststrate** [comment]
@iChenLei yeah it is probably good to mention that the promise returned from the flow will reject and can be catched. You can't catch it inside the flow itself, but as mentioned the finalization block will run so could be used to detect it.
