### ISSUE TITLE
Error: mobx-react-lite@3 requires mobx at least version 6 to be available

### ISSUE THREAD

**Issue by hansiemithun** [mobxjs/mobx#2796]
More details here: https://stackoverflow.com/questions/66152327/error-mobx-react-lite3-requires-mobx-at-least-version-6-to-be-available

**Intended outcome:**

Should compile successfully

**Actual outcome:**

**How to reproduce the issue:**

**Versions**

**Comment by FredyC** [comment]
Please provide runnable reproduction.

**Comment by mweststrate** [comment]
Closing until a repro is available
