### ISSUE TITLE
Unable to inject stores into components in different npm package

### ISSUE THREAD

**Issue by datpham23** [mobxjs/mobx#2805]
I have a typical mobx react application thats injecting the stores using the provider and inject mechanism to inject stores to the components. All the components within my project have no issues injecting the stores. However, I have a component library where i'm trying to inject the stores but the stores object is coming as empty. If i take the same component and put it inside the same project structure it works just fine. To take out other variability with routing or lazy loading I even took those out and just render a bare bone Provider and just the component and the issue still exist. The component also has matching versions of react, mobx, and mobx-react.

```javascript
//Dummy component in my 'my-component-library'
import React, { Component } from 'react';
import { observer, inject } from 'mobx-react';


class Test extends Component {
    render(){
        return <div>hello world</div>
    }
}

export default inject(stores => {
    console.log(stores); //print empty object
    return {}
})(observer(Test))

```

```javascript
//In my application
import Dummy from 'my-component-library';
import { Provider } from 'mobx-react';

<Provider {...{ ...stores }}>
  <Dummy />
</Provider>
```

**Versions**
"react": "16.8.0",
"mobx": "6.1.6",
"mobx-react": "7.1.0",

**Comment by mweststrate** [comment]
Make sure to make mobx and mobx-react *peer* dependencies, not direct
dependencies of your components, as otherwise they will get their own
isolated copies of those packages. Optionally you can add them as
devDependencies add well if you need that for isolated development
