### ISSUE TITLE
Wrapping with action where needed

### ISSUE THREAD

**Issue by giacomorebonato** [mobxjs/mobx#281]
I am refactoring a project where I used to change state around in my components...
So I am creating methods in my stores and wrapping them with actions.
Is there a way to find the point of the code where I am changing the state outside actions?

**Comment by AriaFallah** [comment]
You could do

```js
import { useStrict } from 'mobx'

useStrict(true)
```

and if you change state outside an action, it'll throw an error.

**Comment by giacomorebonato** [comment]
Ok, I was wrapping a lot of function containing state change at the fulfill of a promise.
If I wrap with 'action' only the function with state change and I invoke it at the end of the promise, everything works.
