### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by popec** [mobxjs/mobx#2812]
We're on Angular 11 with mobx-angular and getting JS error with "aot": true and "optimization": true, "buildOptimizer": true
TypeError: t.make_ is not a function

**It works when:**
we set aot: false
or
we set aot: true, optimization: false
or
we set aot: true, optimization: true, buildOptimizer: false (which is our current solution)
Any chances for Angular 11 support?

**Comment by urugator** [comment]
As you've already noticed there is already [an issue in a `mobx-angular` repo](https://github.com/mobxjs/mobx-angular/issues/127)
Is there some bug, that prevents integration with angular?

**Comment by popec** [comment]
It doesn't work when buildOptimizer is true in angular.json, otherwise it works.

**Comment by mweststrate** [comment]
unless there is any reason to assume this is a bug in Mobx itself, lets stick to to the issue in mobx-angular.
