### ISSUE TITLE
mobx-undecorate odd behavior

### ISSUE THREAD

**Issue by jeremy-coleman** [mobxjs/mobx#2813]
mobx-undecorate (v 1.0.7) fails to run when installed with npm - specifically npm. It works with yarn. This is on windows btw, but i think the problem is likely npm v7 via node 15. I don't really have an answer for what would be an easy fix, maybe running it via jscodeshift instead of as a standalone cli?

When running ```bash npx mobx-undecorate``` I get the error "the system cannot find the path specified"
![image](https://user-images.githubusercontent.com/25135855/108263971-eb9b6580-7134-11eb-97c8-bcd56b0b7e65.png)

Note: The error occurs regardless of if mobx-undecorate is installed locally via package.json or globally run with npx when using npm.

However, It SUCEEDS when run with yarn and locally installed. 
But this also has a secondary issue. Because i have to locally install it, i cant cwd into src and run npx mobx-undecorate (like you could with the previous versions). This means im forced to run it in the project root, which transforms node_modules too! I have found doing the following helps a lot, but its still painful because of the ~350 dependencies it brings in. Comment out your devDeps and deps and just add in only mobx-undecorate like this: 
![image](https://user-images.githubusercontent.com/25135855/108263470-513b2200-7134-11eb-9e20-108c64878432.png)

To reiterate, it will run and successfully upgrade your code if you install it locally with yarn and then run it via npx mobx-undecorate . Maybe others can find this helpful if they're having problems in the short term.

3589 files! (actual src/* directory only has ~10 javascript files lol) Not really a big deal, because it works, but it'd be cool to be able to pass in a directory glob to the codemod
![image](https://user-images.githubusercontent.com/25135855/108265475-d0315a00-7136-11eb-8d61-bcae7b72d34b.png)

Thank you all

**Comment by FredyC** [comment]
Can you confirm that running some other CLI tools with npm v7 via node 15 is working correctly? If it works with Yarn then it sounds like a problem of NPM really.

**Comment by jeremy-coleman** [comment]
Npm7 changed peer resolution, so its not a problem per se? Just a f-ing headache. Most popular cli tools work , because they had to work with pnpm . I think they also lowered privileges to global installs also, so maybe that could be the issue. I dont think its worth putting much effort into it if there is not an easy fix, but at least theres a record and explanation of a workaround for people

**Comment by iChenLei** [comment]
Can you write a custom jscodeshift codemod script to test? If you found the same problem, create a issue for [facebook/jscodeshift](https://github.com/facebook/jscodeshift) is better. Thanks
```js
#!/usr/bin/env node
const { spawn } = require("child_process")
const path = require("path")

spawn(
    path.join("node_modules", ".bin", "jscodeshift"),
    [
        "--extensions=js,jsx,ts,tsx",
        ...process.argv.filter(arg => arg.startsWith("--")),
        "-t",
        "src/undecorate.ts",
        process.cwd()
    ],
    {
        cwd: __dirname,
        stdio: "inherit",
        shell: true
    }
)
```
Nothing special, `mobx-undecorate` is only a codemod script based on jscodeshift.

**Comment by mweststrate** [comment]
@jeremy-coleman the error seems to come from your shell itself, not from the JavaScript world, so I think there is just something wrong with your npm / npx installation. What command do you use if you run it from the node modules? I think the following should do the trick to run it in a specific dir:

```
cd src
../node_modules/.bin/mobx-undecorate
```

**Comment by jeremy-coleman** [comment]
i run it with npx, with either the local or global installed version . npm i -> npx mobx-undecorate fails , yarn -> mobx-undecorate works.

I added this console log to make sure the actual mobx-undecorate cli is running, it indeed is. I also checked that all the codependents are co-installed where mobx-undecorate is and they are (jscodeshift , babel , etc)
![image](https://user-images.githubusercontent.com/25135855/108365399-2b119280-71c5-11eb-98ac-7cba9f4c43cc.png)

**Comment by mweststrate** [comment]
might the forward slash on line 12 there be a problem on windows?

**Comment by mweststrate** [comment]
or line 7 needing to start with `path.join(__dirname, etc)`

**Comment by jeremy-coleman** [comment]
I don't think so, because changing the spawn command worked. Forward slashes on windows aren't a problem with node. __dirname was the first thing I tried, and it had no effect.

**Comment by mweststrate** [comment]
Does codeshift itself exist at the given relative path from there? Probably
there is a more idiomatic way to find the binary, maybe using
require.resolve or something

**Comment by jeremy-coleman** [comment]
I think trying to find the bin manually is problematic because there's multiple platform specific files, like in the snippet above^ you have to manually add the extension per platform. My opinion is that if you declare jscodeshift as a dependency, not being able to spawn jscodeshift would be a bug in the package installer.

the spawned jscodeshift exits in the directory the user calls mobx-undecorate from 
![image](https://user-images.githubusercontent.com/25135855/108371090-62833d80-71cb-11eb-8c8f-09ee2401b642.png)

**Comment by mweststrate** [comment]
feel free to put up a PR! (if you have any doc link to show that this is
idiomatic that'd be great as explainer)

**Comment by jeremy-coleman** [comment]
sent! I also added a help message when people use --help that explains how to use jscodeshift manually

**Comment by jeremy-coleman** [comment]
@mweststrate 
unrelated to this PR, but this has been on my mind since hooks came out. What do you think about this use pattern, substituting their observable.get with mobx's get function or something similar? The huge benefit being that you wouldn't need to use observer component wrappers/useRender. 
https://github.com/BeTomorrow/micro-observables/blob/master/src/useObservable.ts

**Comment by mweststrate** [comment]
I think that would be pretty cumbersome as soon as you try to iterate an
object, or try to fetch something deeply in an object?

**Comment by jeremy-coleman** [comment]
Hmm, accessing nested stuff inside the render functions would certainly suck, but its so easy to move everything outside of the component. That ability is really what drives my love for mobx. 

Imagine something like this:

```jsx

let userInfo = {
    name: 'Bob',
    age: 55,
    location: 'Boston',
    //...{ 100 other properties}
}

let AppState = observable({
    userInfo,
    //{...another 100 properties}
})

const PersonCard1 = () => {
    //Is it possible to only call forceUpdate on name age location changes? this would be cool
    const {name, age, location } = useObservable(AppState.userInfo)
    return <div>`Hi my name is ${name}. I'm ${age} years old and live in ${location}`</div>
}

const PersonCard2 = () => {
    //this would definitely suck
    const data = useObservable(AppState)
    return <div>`Hi my name is ${data.name}. I'm ${data.age} years old and live in ${data.location}`</div>
}

const PersonCard3 = observer(() => {
    // normal
    const {name, age, location } = AppState.userInfo;
    return <div>`Hi my name is ${name}. I'm ${age} years old and live in ${location}`</div>
})
```

Is PersonCard1 feasible?

**Comment by jeremy-coleman** [comment]
Btw, I resubmitted the PR here https://github.com/mobxjs/mobx/pull/2818 . Git history got messed up on the first one from editing directly on github then pulling locally for the changeset so just deleted everything and redid it

**Comment by jeremy-coleman** [comment]
@mweststrate I ran across https://github.com/2A5F/Mobz , it has very similar use. Although , in an ideal world I'd try to avoid the use of creating a 'store' and just use a regular observable

**Comment by jeremy-coleman** [comment]
pr fixed
