### ISSUE TITLE
Execute autorun not work when updating storage in the react context

### ISSUE THREAD

**Issue by beilo** [mobxjs/mobx#2816]
**Intended outcome:**
Execute `autorun` when store is updated in `react context`

**Actual outcome:**
not work

**How to reproduce the issue:**
https://codesandbox.io/s/ceshigechongku-v2ypj?file=/src/App.js:1645-1647

**The key code**
```js
--------global store and Context-----
  const store = useLocalObservable(() => new MyState({}));
  React.useEffect(() => {
    store.init();
  }, []);

  return (
    <singleSelectStoreContext.Provider value={store}>
      <Wrap />
    </singleSelectStoreContext.Provider>
  );
```

```js
------ A child component of <Wrap /> -------------
  const rootStore = useSingleSelectStoreContext();
  const state = useLocalObservable(() => ({
    optionArr: [],
    init(val) {
      state.optionArr = val;
    }
  }));
  React.useEffect(
    () =>
      autorun(() =>
       // There's runInAction question here, and not wrapping it with an A would warn me,
      //  It's like  here.      https://github.com/mobxjs/mobx/issues/2718
        runInAction(() => {
          // The reason why I'm doing this is because I don't want to break the data in the global store
          state.init(rootStore.initList);
        })
      ),
    []
  );
```
**Versions**
mobx: 6.1.5
mobx-react: 7.1.0

**Comment by iChenLei** [comment]
### reproduction
Minimal reproduction code example for your case.

> https://jsfiddle.net/ichenlei/t28mrcqp/17/

![2021-02-18 21 49 03](https://user-images.githubusercontent.com/14012511/108366258-21bf0f00-7233-11eb-9adb-533c17683dfa.png)

### summary
It looks like when you nest call `runInAction` in `autorun`, it works not as your expected. I try to debug it and I found that `autorun` tracked zero deps in your case. But maybe it's expected behavior in mobx concepts. Need Mr. `Michel Weststrate` to explain it.

**Comment by mweststrate** [comment]
runInAction won't track anything, if you want to track store.name you have
to access it outside the runInAction. I didn't entirely get what the OP
tried to achieve, but make sure to check
https://mobx.js.org/react-integration.html#useeffect if you want to set up
an effect that listens to observables

**Comment by urugator** [comment]
@mweststrate I think there is a bug - the `autoAction` doesn't switch `allowStateChangesStart` flag

**Comment by mweststrate** [comment]
@urugator IIRC this is working as intended imho; if there is no derivation context, `runAsAction` should be true, so swapping the flag. However, inside a derivation, we don't want to mix tracking and state changes (as that can easily create infinite loops), so if an autoAction is called from e.g. a computed, state changes should indeed warn. If we would allow state changes in an auto actions called from a derivation, simple constructions like `this.field += 1` become really dangerous. So basically autoAction is a utility that chooses between derivation or action based on context, but it still is intended to do only one of those two (deriving or updating). It's not a lenient convenient utility that will help you to suppress all warning :)

**Comment by urugator** [comment]
Ah, that makes sense, I did not realize it depedens on the presence of derivation.

**Comment by beilo** [comment]
@iChenLei @mweststrate 
I'm not in the same situation as your example, because the `component` where the `global context` is located is far away from the `C component`, which would be complicated to pass using `props`.
And I'm not changing the `Global Store `, I'm just initializing the `C Store`.

Or is there a better way to do it?

My current solution is this:
```js
React.useEffect(
    () =>
      autorun(() =>
        runInAction(() => {
          state.init(rootStore.initList);
        })
      ),
    // []  Removed to make 'useEffect' every time it is executed
  );
```
Am I doing this wrong?

**Comment by iChenLei** [comment]
### React Hooks Deps
```js
// []  Removed to make 'useEffect' every time it is executed
```
No, don't do it. https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an

### Fast Chinese Reply
> 我举的例子是想说明为什么你的autorun没有按照你设想的方式去执行，因为是子组件，所以按照`react lifecycle`第一次执行的时候initList是空的，而且runInAction是不会收集依赖的[`runInAction won't track anything`]. 等于说你的autorun没有track到任何可观测的依赖.之后你的rootStore值变更不会响应到autorun。至于你去掉dep数组参数，建议你看看React官方文档，这样等于每次re-render都执行。最后你应该是想在子store里使用Global Store的数据，但是只是初始化，初始化之后子store和Global Store就没有关系了。

### solution for u
I know what you want to do. 
> And I'm not changing the Global Store , I'm just initializing the C Store.

Maybe you forgot the `useRef` in `React hooks` world ?
```diff
+ const localRef = useRef(false);
  const rootStore = useSingleSelectStoreContext();
  const state = useLocalObservable(() => ({
    optionArr: [],
    init(val) {
      state.optionArr = val;
    }
  }));
  React.useEffect(
    () => {
+     if (!localRef.current && rootStore.initList.length > 0) {
+       localRef.current = true;
+       state.init(rootStore.initList);
      }
    },
+   [state, rootStore.initList]
  );
```
It works as expected in your codesandbox example.

**Comment by beilo** [comment]
@iChenLei 
First of all, thank you for providing me with a great idea. This plan is useful for me.

However, my request is that when `global store` changes, the `state` in `C component` should be replaced.

In `mobx useLocalStore` there is a *source* that is able to deliver `props`. But it is now abandoned. I don't know how to replace it now?

And how do you show the added and deleted code in the code block, and I have no effect below

```js
- React.useEffect(
-   () =>
-     autorun(() =>
-       runInAction(() => {
-         state.init(rootStore.initList);
-       })
-     ),
-   []
- );
+  React.useEffect(() => {
+    state.init(rootStore.initList);
+  }, [rootStore.initList]);  // In this way, I can achieve the effect I want

```

**Comment by beilo** [comment]
Actually my problem is the use of useEffect
> MobX has already a way to automatically determine the dependencies of an effect

https://mobx.js.org/react-integration.html#useeffect

```js
 React.useEffect(
   () =>
     autorun(() =>
      xxxxxxxxx
     ),
   []
 );
```
But what I found was that it didn't work out as expected, so I still had to use `autorun` or `useEffect` depending on the situation.
How should I choose?
@mweststrate @iChenLei @urugator

**Comment by iChenLei** [comment]
`runInAction won't track anything`

![2021-02-19 23 16 20](https://user-images.githubusercontent.com/14012511/108523091-7da79780-7308-11eb-97b9-9cecd772cba9.png)

Don't use `runInAction` in `autorun`, it not work as your expected. It's the final conclusion。

**Comment by urugator** [comment]
```javascript
React.useEffect(() => {
  state.init(rootStore.initList);
}, [rootStore.initList]);
```
Won't work correctly unless `initList` is immutable (considering you want to re-run effect when `initList` changes)

> I don't know how to replace it now?

You shouldn't need to synchronize some "local state" with some "global state". It's antipattern. You should just move the local state to the global.
https://github.com/mobxjs/mobx-react-lite/pull/302#issuecomment-678685286
https://github.com/mobxjs/mobx/issues/2710#issuecomment-759354434

**Comment by beilo** [comment]
@iChenLei Thank you for telling me how `runInAction` works
The reason I added `runInAction` is as follows⚠️
How can I change `store` in `autorun` without adding `runInAction`?
```
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. 
Tried to modify: ObservableObject@54.optionArr 
    in Main (created by App)
    in App 
```

**Comment by iChenLei** [comment]
Do you read `urugator`'s comment ? @beilo 
> You shouldn't need to synchronize some "local state" with some "global state". It's anti-pattern. You should just move the local state to the global.

**Comment by beilo** [comment]
@iChenLei 
I'm sorry. I'm just thinking about what the 'urugator' said.
I'm a mixed user of `global` and `local` and have always been used to it. So I spent a lot of time thinking about how I should express it.

@urugator 
Is `mobx 6` recommended to use `global store` for data processing? It's similar to `redux` or `dvajs`.
If you change according to your plan and give up `local state`, I feel that flexibility will be lost and coupling will be increased

The function of switching templates is maintained here, and different templates are initialized differently. If you move the following `local state` to `global`, the coupling is too strong.
ps: The only template associated with `global store` is `curData`. `global store` itself is a parent component
```
global store => {dataList:[],curData:{},xxxxx} 

global  (There's switching between templates and so on. It's a complex component)
    A
    B
    C


A template => curData.map ==> [{...curData, isSelect}] = A loca state
B template => curData.map ==> [{...curData, isClick}] = C loca state
C template => curData.map ==> [{...curData, isxxxx}] = C loca state
```

**Comment by iChenLei** [comment]
use `@computed` annotation
```js
class GlobalStore {
  constructor() {
      makeAutoObservable(this);
   } 

  get isSelectForAComp () {
    return xxxxx;
  }

  get isClickForBComp () {
      return xxxxx;
  }

  /*** omitted **/
}
```

**Comment by urugator** [comment]
> coupling will be increased

It won't, because the coupling already exists, otherwise you wouldn't need to synchronize. You just want to move the coupling to some synchronization layer, but that itself won't remove the coupling. You just make the application more complicated - it's very likely that the "synchronized" component will never be used standalone outside of your application, therefore there is no practical reason to keep it "decoupled" and introduce some additional abstraction to keep it in sync. And even if you would need that, you have hooks - they can be easily moved around and plugged into any component, which allows you to do these refactors easily - eg if you have some complex component logic that depends on state, you don't need to know where the state comes from - whether it's global/local/props - you just pass the state as params to hook.
Forget about mobx and observables and think how you would solve this with react alone - you want to copy state of some parent component into a state of child component -  it's doable with `useLayoutEffect/getDerivedStateFromProps`, but you will be always advised to [lift the state up](https://reactjs.org/docs/lifting-state-up.html) instead.

> give up local state

It's not giving up local state - but you use local state for state that isn't truly local.

Btw if you don't need to keep the local state synchronized, but simply initialize it from global when template switches, then, well I would advise to initialize the template in the action that changes the template, but you can also have a `ATemplate/BTemplate/etc` component that is swapped with template and initializes it's own state on mount (or eventually in layout effect that depends on some template id).

**Comment by beilo** [comment]
@urugator 
Thank you very much for your patient answer.
I'll think a lot about how to reframe my project.


This is the code I had a problem with
**why: https://github.com/mobxjs/mobx/issues/2816#issuecomment-782142333**
```js
  React.useEffect(
    () =>
      autorun(() => {
        runInAction(() => {
          state.init(rootStore.initList);
        });
      }),
    []
  );
```

**Solution 1**
```diff
  React.useEffect(
+    () =>{
-      autorun(() => {
-        runInAction(() => {
          state.init(rootStore.initList);
-        });
-      })
+   },
+  [rootStore.initList]
  );
```

**Solution 2**
```diff
import {
  action,
  autorun,
  makeAutoObservable,
  runInAction,
+  _allowStateChanges
} from "mobx";

  React.useEffect(
    () =>
      autorun(() => {
+        if (rootStore.initList !== state.optionArr) {
+          _allowStateChanges(true, () => {
            state.init(rootStore.initList);
          });
+        }
      }),
    []
  );

```

The above is my summary, I hope to help others.
Thanks again for your patience.
