### ISSUE TITLE
Non numeric keys in an observable array

### ISSUE THREAD

**Issue by MorFix** [mobxjs/mobx#2821]
Hi,
We are working with arrays that contain metadata, like the type of the data in the collection.
The keys for this data are not numbers and they are not added using "push".

When we make those arrays observable, this data is removed.

For example:

```
const myArray = ["apple", "banana"];
myArray["__arrayType"] = "Fruit"; // metadata
const ob = observable(myArray);

console.log(ob.__arrayType) // undefined
```

More specifically, we noticed that when you make an array an observable, it is passed to a `map` function, which returns a new array without the metadata.

In `observablearray.ts`:222 - https://github.com/mobxjs/mobx/blob/5640aa7794420a5fc2f99ac0819de11696d6ba71/packages/mobx/src/types/observablearray.ts
you can see this line.

We believe that the `map` is just a symptom, and the real issue here is bigger - how MobX treats arrays like these? Does MobX consider them?
If my case should work, arrays cannot always be fully treated as arrays, but sometimes as regular objects.

We use MobX 6.

I would appreciate it if we can discuss this problem. 
Thank you!

**Comment by mweststrate** [comment]
We don't support mixing maps / arrays / sets and objects, so non numeric properties on arrays are indeed not supported. I recommend to store the meta data in a separate observable object, which you can then store on the object with a normal object if you want, just make sure to keep that reference stable.
