### ISSUE TITLE
Component with ref forwarding has wrong displayName when it was wrapped via inject multiple times

### ISSUE THREAD

**Issue by lozinsky** [mobxjs/mobx#2829]
**Intended outcome:**

If target component was wrapped via `React.forwardRef`, then every execution of `inject` shouldn't affect the target `displayName`.

```js
import { forwardRef } from "react";
import { inject } from "mobx-react";

const Foo = forwardRef(function Foo() {});

Foo.displayName = "Foo";

console.log(inject()(Foo).displayName); // inject(Foo)
console.log(inject()(Foo).displayName); // inject(Foo)
console.log(Foo.displayName); // Foo
```

**Actual outcome:**

If target component was wrapped via `React.forwardRef`, then every execution of `inject` adds `inject(*)` prefix to the target `displayName`, because `displayName` property descriptor of `Injector` component refers to the target `displayName` due to `copyStaticProperties` implementation.

```js
import { forwardRef } from "react";
import { inject } from "mobx-react";

const Foo = forwardRef(function Foo() {});

Foo.displayName = "Foo";

console.log(inject()(Foo).displayName); // inject(Foo)
console.log(inject()(Foo).displayName); // inject(inject(Foo))
console.log(Foo.displayName); // inject(inject(Foo))
```

**How to reproduce the issue:**

See console output: https://codesandbox.io/s/mobx-react-inject-forward-ref-display-name-qo244?file=/src/index.js:0-254

**Comment by FredyC** [comment]
Why do you wrap in inject multiple times? Either way, we don't recommend using `inject` anymore, it's an obsolete pattern and has been replaced by React Context. See docs: https://mobx.js.org/react-integration.html#using-external-state-in-observer-components

**Comment by lozinsky** [comment]
Thank you for your suggestion! In our codebase we have some reusable components like `Button` and it can be wrapped in `inject` multiple times on a page, but in different places of application, e.g:
```js
const MyAFeatureButton = inject()(Button);

// ...

const MyBFeatureButton = inject()(Button);
```

**Comment by FredyC** [comment]
I think we won't be changing the behavior in this case as it could be a breaking change for some people who expect multiple wrapping (for whatever reason). If it truly pains you, implements your own `inject` variant with `React.useContext(MobXProviderContext)` (exported from package).

**Comment by lozinsky** [comment]
But it is clearly a bug, that wrapping in `inject` will mutate the target component. Wrapping in `inject` should be pure. I don't think that it will be a breaking change. It can be fixed by adding `displayName` key to the `hoistBlackList`. https://github.com/mobxjs/mobx/blob/d921b171e502bd921d829d4763bf8d053e57692f/packages/mobx-react/src/utils/utils.ts#L46-L60

**Comment by vkrol** [comment]
This was also fixed in `hoist-non-react-statics` some time ago https://github.com/mridgway/hoist-non-react-statics/commit/08d47255bc36316613bcd0bc77fe21e058140c6f.

**Comment by mweststrate** [comment]
`inject` is a deprecated mechanism and we don't really invest in it anymore, but if anybody cares enough about it to fix it, feel free to open a PR and we can release it.
