### ISSUE TITLE
IComputedFactory does not get exported from main file

### ISSUE THREAD

**Issue by Neunerlei** [mobxjs/mobx#2839]
**Intended outcome:**

I want to create a list of possible annotations of a prototype, therefore I want to import the annotation interfaces from mobx.
It would be nice if one could do it like this:
```
import {IObservableFactory, IComputedFactory} from 'mobx';

export type BitAnnotations = PlainObject<IComputedFactory | IObservableFactory>;
```

**Actual outcome:**
I can't import the IComputedFactory from mobx directly, but have to reference a child file.
```
import {IObservableFactory} from 'mobx';
import {IComputedFactory} from 'mobx/dist/api/computed';

export type BitAnnotations = PlainObject<IComputedFactory | IObservableFactory>;
```

**Versions**
6.1.8

Thanks in advance :)

**Comment by FredyC** [comment]
Feel free to send in PR :)
