### ISSUE TITLE
Wrapping class component with observers makes original component behave as pure component

### ISSUE THREAD

**Issue by nryumin** [mobxjs/mobx#2841]
https://codesandbox.io/s/nice-ritchie-xfg7x

If i wrap my class component (TodoView) with `observer` original component starts to behave as pure component. 
If i comment out 18th line TodoView's render method called each App render as expected. 

**Steps:**
Click on button

**Expected result:**
Console:
```
render app 
todoview render
```
**Actual result:**
Console:
```
render app 
```

**Comment by FredyC** [comment]
Yes, the `observer` applies `React.memo`. Please read the docs. https://mobx.js.org/react-integration.html#observer-vs-memo

**Comment by nryumin** [comment]
I'm ok that wrapper component behaves like memo. But original components starts to behave as memo too. 
In my example i used original component not observed

**Comment by FredyC** [comment]
Yes, we have to patch the original component `sCU`, there is no other way. If you need separate behavior, use functional component or `<Observer />` component.
