### ISSUE TITLE
@observable no longer working for primitive class fields

### ISSUE THREAD

**Issue by Riba-Kit** [mobxjs/mobx#2848]
in version 5.x I can do loke this:
```
class Example {

    @observable trigger = false;

    @action toggleTrigger() {this.trigger = !this.trigger}
    reaction = reaction(() => this.trigger, (value) => {console.log(value)});
}
```

let instance = new Example();
instance.toggleTrigger(); // should write "true" in console

it was possible because decorator @observable automatically makes seter and geter for primitive fields, which wrapped in box.

But in version 6.x it is not working and I need to replace primitive observable fields in all project to this:

```
class Example {

    triggerBox = observable.box(false);
    get trigger() {return this.triggerBox.get()}
    set trigger(value) {this.triggerBox.set(value)}

    @action toggleTrigger() {this.trigger = !this.trigger}
    reaction = reaction(() => this.trigger, (value) => {console.log(value)});
}
```

Is there a bug or feature?)

**Comment by urugator** [comment]
https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable

**Comment by Riba-Kit** [comment]
> https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable

thanks!
