### ISSUE TITLE
React Native builds fail with mobx-react-lite

### ISSUE THREAD

**Issue by eduardosunrise** [mobxjs/mobx#2861]
**Expected Outcome**
Generate a successful Android React Native build using `./gradlew assembleRelease`

**Current Outcome**
Build fails with the following output:
```
error node_modules\mobx-react-lite\src\utils\reactionCleanupTrackingCommon.ts: Unexpected token: name (_000) in file node_modules\mobx-react-lite\src\utils\reactionCleanupTrackingCommon.ts at 18:48. Run CLI with --verbose flag for more details.
Error: Unexpected token: name (_000) in file node_modules\mobx-react-lite\src\utils\reactionCleanupTrackingCommon.ts at 18:48
    at D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:437:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:75:24)
    at _next (D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:95:9)
    at D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:100:7
    at new Promise (<anonymous>)
    at D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:92:12
    at JsTransformer._minifyCode (D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:444:7)
    at D:\Projects\tsl-mobile\node_modules\metro\src\JSTransformer\worker.js:374:33
```

**How to reproduce the issue:**
1. Install mobx and mobx-react-lite packages into React Native project
2. Run `./gradlew assembleRelease`

**Version**
react-native: 0.63.3
mobx: 6.1.7
mobx-react-lite: 3.2.0

**Solution**
I was able to resolve this issue locally by updating the reactionCleanupTrackingCommon.ts file. There appear to be 2 int constants with underscores that get added to a Date.now() value:

Original:  
export const CLEANUP_LEAKED_REACTIONS_AFTER_MILLIS = 10_000
export const CLEANUP_TIMER_LOOP_MILLIS = 10_000

Fixed:
export const CLEANUP_LEAKED_REACTIONS_AFTER_MILLIS = 10000
export const CLEANUP_TIMER_LOOP_MILLIS = 10000

**Comment by eduardosunrise** [comment]
It has been found that there was wrong import statement for mobx-react-lite that called the src. However it does seem odd to set these constants with an underscore in the `src` whereas the `dist` has them set as ints.

**Comment by mweststrate** [comment]
That is not all strange and happens with most packages, the sources are
written in newer versions of JavaScript (or TypeScript) and compiled down
when creating a distribution to support older versions of JS like the
engine you are using.
