### ISSUE TITLE
Observable values no longer get updated with the latest version of mobx, mobx-react

### ISSUE THREAD

**Issue by SourceCipher** [mobxjs/mobx#2869]
Not sure what happened, but basically using:

"mobx": "^6.1.6"
"mobx-react": "^7.0.5"

observable values no longer get updated at all.

**What's happening?**

I had an app which I worked on for years using mobx all the times and it was working fine. I postponed the development and came back to work on it after half a year or so and after updating all the libraries, configuration and got the app running, realised that nothing is working anymore.

 **What's not working?**

Simple. You have a class. Declare a variable which is observable. Try updating the variable in the input or anywhere else and it will not trigger an update at all (nor from the store or the class itself)

**To replicate**
Here is the codesandbox to replicate with the latest mobx libraries available (broken mobx):
https://codesandbox.io/s/react-native-mobx-forked-gpudx

And here is with the older ones (working mobx):
https://codesandbox.io/s/react-native-mobx-forked-kggqs

**Comment by jheeffer** [comment]
Hey! I think you changed major version, from 5 to 6 and haven't applied the migration guide yet:

https://mobx.js.org/migrating-from-4-or-5.html

It seems adding a constructor to your MainView component makes it work:

```
  constructor(props:any) {
    super(props);
    makeObservable(this)
  }
```

**Comment by SourceCipher** [comment]
Thanks @jheeffer. Seems like a huge hassle to migrate existing code for big projects and a big risk of breaking it.

For anyone looking to continue to use the decorators, read https://mobx.js.org/enabling-decorators.html
