### ISSUE TITLE
The second "Getting Started" demo is malfunctioning

### ISSUE THREAD

**Issue by dschalk** [mobxjs/mobx#287]
The second "Getting Started" interactive demonstration at https://mobxjs.github.io/mobx/getting-started.html prints the first todo five times.

**Comment by mweststrate** [comment]
Good to see you again David! Actually the output is correct (the report always prints the first unfinished task), the example is just confusing. Gonna fix it :) (and will leave this issue open till then)

**Comment by danawoodman** [comment]
To me it seems like they're all broken... Shouldn't the text change when marking TODOs as complete?

![](https://cl.ly/jyDm/Screen%20Recording%202017-04-11%20at%2011.56%20AM.gif)

**Comment by zigacernigoj** [comment]
It returns `this.todos[0]`, so first in array, not first unfinished.
