### ISSUE TITLE
Structural computed + action + non observable variable combination prevents stale derivations from being rerun

### ISSUE THREAD

**Issue by jheeffer** [mobxjs/mobx#2870]
https://jsfiddle.net/jasperh/v6khdc9q/28/

I have a seemingly contrived set up: 
A base state object (`obs.x`)
A structurally compared computed (`obs.y`) which copies the base state object
A non-observable variable which gets set, in the computed, to the result of the computed (`oldObj`)
An action which changes both the base state and the non observable variable
An autorun observing the computed.

Part of why the setup looks contrived is because I simplified it for this issue. I can go into reasons why I ended up with this code, and there may be better ways to do what I was trying to do. Nonetheless this smells like a bug.

**Intended outcome:**

When executing the action, the autorun reruns because it becomes stale through obs.x -> obs.y -> autorun.

**Actual outcome:**

The autorun doesn't run. 

The computed (`obs.y`) does get recalculated but the new (changed) result does not propagate to the autorun. My guess is `obs.y` is incorrectly deemed structurally identical to the previous result, somehow through interaction with the non-observable variable?

The fact the autorun trace is triggered even though it doesn't run can be explained by bug/feature https://github.com/mobxjs/mobx/issues/2859

Weirdly, removing any part of this set up "fixes" the bug:
 - removing the assignment in the computed
 - removing the decorator, making the computed use the default comparer (non-struct)
 - not deleting the property of the non-observable var in the action

**How to reproduce the issue:**

https://jsfiddle.net/jasperh/v6khdc9q/28/

**Versions**

Mobx 5 and 6 (probably 4)

**Comment by urugator** [comment]
It's because `oldObj` is a reference to the same object that is held in `computed`'s cache.
When you `delete oldObj[`foo`]` you're modifying the cache content, so you delete `foo` from both objects that are later being structurally compared - therefore they're structurally equal and autorun isn't notified.
Generally speaking you shouldn't have side effects in computed.

**Comment by jheeffer** [comment]
Aah, that makes sense, thanks @urugator!
Yeah, side effect was because I need the previous value for this computed (removed that part for simplicity). This seems to be one of the ways you recommend doing it, by saving it either in the action or in the computed. But if it's a couple of derivation-steps down, can't do it in the action, so computed seemed the way to go.
