### ISSUE TITLE
5.1 In depth explanation of MobX - broken link

### ISSUE THREAD

**Issue by EmilTholin** [mobxjs/mobx#289]
The link to 5.1: In depth explanation of MobX in the documentation is broken. Should it link [here](https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254#.kctkdiozj)?

**Comment by AriaFallah** [comment]
Yes that's where it should link

**Comment by mweststrate** [comment]
I think it is a bug in gitbook or something, link remains broken..  I'll create a page with a link instead..
