### ISSUE TITLE
React Native and Jest: Cannot find module 'react-dom' from 'mobxreactlite.cjs.development.js'

### ISSUE THREAD

**Issue by IvanSkadorva** [mobxjs/mobx#2910]
Jest asks for react-dom dependency in the React Native app.
I found the same issues here: https://github.com/mobxjs/mobx-react/issues/844, but there is no working solution and the problem has been around for about a year.

**Intended outcome:**
Jest should work as expected

**Actual outcome:**
Unable to test components due to error:

    Cannot find module 'react-dom' from 'node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js'

    Require stack:
      node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js
      node_modules/mobx-react-lite/dist/index.js
      node_modules/mobx-react/dist/mobxreact.cjs.development.js
      node_modules/mobx-react/dist/index.js
      App.tsx
      __tests__/App-test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:10:16)
```

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.979 s
Ran all test suites.
```

**How to reproduce the issue:**
repository:  https://github.com/IvanSkadorva/jest-mobx-testing-issue
npm install
npm test

**Versions**
```
"dependencies": {
    "mobx": "^6.2.0",
    "mobx-react": "^7.1.0",
    "mobx-react-lite": "^3.2.0",
    "react": "17.0.1",
    "react-native": "0.64.0"
  },
```

**Comment by mweststrate** [comment]
@FredyC any idea? I think we have tackled this before IIRC.

**Comment by FredyC** [comment]
Well, since the CJS bundle is used, it's definitely tricky. You would need run from source and use `.native.js` file that works with `react-native`. Another alternative is probably setup an alias in Jest for react-dom to react-native. Not ideal, but I don't think we can do anything here about this.

**Comment by ReeceStevens** [comment]
Hi, I just wanted to add that I am running into this same issue. 

> Not ideal, but I don't think we can do anything here about this.

Just to be clear, does this mean this is something on the user configuration side that we need to change?

For now I have implemented the Jest module aliasing that @FredyC suggested-- thanks for that pointer. The test gets past this import step now, which is good!

```
// jest.config.js
module.exports = {
    preset: 'react-native',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    moduleNameMapper: {
        'react-dom': 'react-native',
    },
};
```

**Comment by IvanSkadorva** [comment]
@ReeceStevens, thank you! It works!
