### ISSUE TITLE
toJS() doens't work well with partial observables (mobx-6)

### ISSUE THREAD

**Issue by ixrock** [mobxjs/mobx#2912]
**Example:**

```ts
class X {
  @observable num = 123;
  @observable list: any[] = [];
  @observable map = new Map<any, any>();
  @observable object: Record<string, any> = {};

  constructor() {
    makeObservable(this);
  }

 // works as expected, but could be easily broken with toJS({...this})
  toJSON() {
    return toJS(this);
  }

  // broken: still contains Proxy()-objects / non-serializible in some envs (e.g. electron.js ipc messaging)
  getState() {
    return toJS({
      num: this.num,
      list: this.list,
      map: this.map,
      object: this.object,
    });
  }
}

const test = new X();
console.log("toJSON():", test.toJSON())
console.log("getState():", test.getState())
```

**Result:**

![image](https://user-images.githubusercontent.com/6377066/115855504-fbd10900-a433-11eb-8ae8-b9bf0cce7b7a.png)

**Versions**

```
"mobx": "^6.2.0",
"webpack": "^4.44.2",
"typescript": "4.0.2",
```

**Comment by urugator** [comment]
This is expected, `toJS` does not recurse into non-observables. You would have to either 
`return toJS(observable({ list: this.list }))` 
or 
`return { list: toJS(this.list) }`

**Comment by ixrock** [comment]
This is not expected regarding to docs:

> To convert a data tree **recursively** to plain objects, the toJS utility can be used. For classes, it is recommend to implement a toJSON() method, as it will be picked up by JSON.stringify.

https://mobx.js.org/observable-state.html#converting-observables-back-to-vanilla-javascript-collections

**Comment by urugator** [comment]
Feel free to improve it.

**Comment by ixrock** [comment]
> This is expected, `toJS` does not recurse into non-observables. You would have to either
> `return toJS(observable({ list: this.list }))` (not very efficient)
> or
> `return { list: toJS(this.list) }`

Would be `JSON.parse(JSON.stringify({list: this.list}))` more performant btw?

**Comment by urugator** [comment]
Dunno, to minimize overhead of creating observable, you may try:
`toJS(extendObservable({ list: this.list }, {}))`

I think it shouldn't be too difficult to write own `toJS` that suits your needs.

@mweststrate any chance of reviving `recurseEverything` option?

**Comment by mweststrate** [comment]
@urugator no, it was an everyending story as it opens a whole can of worms, handle classes, cycles, non-enumerables, getters, dont recurse into React components Buffer and whatnot. Either roll your own or pick any library solution including stringify, some funky lodash utility etc. Proper flexible serialisation is a complex problem and out of the scope of this library beyond data structures that are provided by us.
