### ISSUE TITLE
Decorators don't work by default in V6 with no messages

### ISSUE THREAD

**Issue by ptallett** [mobxjs/mobx#2915]
I notice in closed issue #2869 that decorators alone no longer work requiring a makeObservable call.

Would it be possible to detect this missing call and issue a warning to the console?

I was writing a simple new application and used all the latest versions of everything and MobX didn't work. Spent a couple of hours debugging before reverting to V5 which fixed the issue. I then found #2869 

I do feel a console warning should have been given if its possible to detect this.

Thanks

**Comment by mweststrate** [comment]
We can't really detect this. There is little we can do about people not reading changelogs when they use a different major version of a library or re-checking the assumptions they have by reading docs.

**Comment by idanlevi1** [comment]
> I notice in closed issue #2869 that decorators alone no longer work requiring a makeObservable call.
> 
> Would it be possible to detect this missing call and issue a warning to the console?
> 
> I was writing a simple new application and used all the latest versions of everything and MobX didn't work. Spent a couple of hours debugging before reverting to V5 which fixed the issue. I then found #2869
> 
> I do feel a console warning should have been given if its possible to detect this.
> 
> Thanks

If you want you can use this tutorial for implement mobx without decorators
[https://idanlevi2.medium.com/react-with-mobx-6-with-persist-and-without-decorators-bd7e5a0578d6](https://idanlevi2.medium.com/react-with-mobx-6-with-persist-and-without-decorators-bd7e5a0578d6 )
