### ISSUE TITLE
Can map handle numeric keys?

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#292]
The type definitions tells me that a `map` accepts only string-based keys. Is this actually the case? Can I safely use a number? Can it, like an ES6 map, use an object key?

**Comment by mweststrate** [comment]
I think numbers will work pretty well as they can be coerced to strings, but objects like in ES6 maps won't work. (Upgrading to ES6 maps could technically be done, but are only supported in IE 11 and higher)

**Comment by AriaFallah** [comment]
You can also just do something like `map.set(JSON.stringify(obj), obj)`. Unless you have a bunch of identical objects that each have different properties you don't really need to store the object itself.

**Comment by jamiewinder** [comment]
Thanks both. For now I've taken to manually converting my numbers to strings (e.g. `'' + num`) when using the ObservableMap types. If only just to get around TypeScript warnings.

I don't actually need object keys, but I was just curious since the type otherwise appears to try and emulate an ES6 Map.
