### ISSUE TITLE
toJS ObservableMap behavior difference between v5 and v6

### ISSUE THREAD

**Issue by zhigang1992** [mobxjs/mobx#2924]
**Intended outcome:**

toJS ObservableMap behavior should stay consistent between v5 and v6

**Actual outcome:**

on v5 with 

```
const map = new ObservableMap<string, string>();
map.set("hello", "world");
console.log(toJS({ map }, { recurseEverything: true }));
```

will give you
`{map:{hello:'world'}`

on v6 it will give you `{map: ObservableMap}`

**How to reproduce the issue:**

v5
https://codesandbox.io/s/mobx-tojs-observablemap-6tvoh?file=/src/App.tsx

v6
https://codesandbox.io/s/mobx-tojs-observablemap-v6-09fx1?file=/src/App.tsx

**Versions**

v5 vs v6

**Comment by urugator** [comment]
There is no `recurseEverything` option in V6, see changelog. For explanation see https://github.com/mobxjs/mobx/issues/2912#issuecomment-825890901
