### ISSUE TITLE
Using jest.spyOn with mobx store properties results in error with Mobx >= 6.1.2

### ISSUE THREAD

**Issue by bovas85** [mobxjs/mobx#2926]
**Intended outcome:**
I'd like to be able to spy on mobx properties

**Actual outcome:**
While testing and spying on methods to check when/if they are called I get an error from jest

**How to reproduce the issue:**
Run tests and see the console
`Cannot assign to read only property 'set' of object '#<GreetStore>'`

**Versions**
Go to https://codesandbox.io/s/summer-shadow-jf8vx?file=/src/store.test.js and check the test tab:
Downgrading to version 6.0.4 fixes the issue

**Comment by urugator** [comment]
Provided codesandbox simply fails on:
```javascript
expect(jest.fn()).toHaveBeenCalledWith(...expected)

Expected: "yes"
Received: "hello"

Number of calls: 1

   6 |   const spy = jest.spyOn(instance, 'set')
   7 |   console.log(Object.getOwnPropertyDescriptor(instance, "set"))
   8 |   instance.set('hello')
>  9 |   expect(spy).toHaveBeenCalledWith('yes')
  10 | })
```
Which is expected, because the function is defined on prototype. For cases where it throws please see:
https://mobx.js.org/configuration.html#safedescriptors-boolean

**Comment by bovas85** [comment]
huh that's quite odd, it works now but please don't close as this is a real issue. Will probably need a bigger store to verify this again next week

**Comment by urugator** [comment]
You need eg `makeObservable(this, { set: action.bound })` or use arrow function and `makeObservable(this, { set: action })`

But even then, as already  mentioned multiple times, `configure({ safeDescriptor: false })` should do the trick.

**Comment by bovas85** [comment]
I added that in my app, but it doesn't seem to make the trick as with a simple app like the one I created

**Comment by bovas85** [comment]
ok, that seems to clear some, but what about flow?
if I spy setUsername it says:
`TypeError: Cannot assign to read only property 'setUsername' of object '[object Object]'`
This doesn't happen with version 6.0.4 or lower
```
/**
   * Set username
   * @param {string} username
   */
  setUsername = flow(function* (username) {
    yield AppInitPromise()

    const { inputIsValid, validationErrors } = validationService.formHelper.validator.validate(
      { username },
      'username',
    )

    this.username.value = username
    this.username.valid = inputIsValid

    this.setUsernameTouched(true)

    this.handleInputValidity(inputIsValid, validationErrors)
  })
```

**Comment by urugator** [comment]
Please create runnable repro.

**Comment by bovas85** [comment]
Adding the configure to the single tests works

**Comment by rvicenzo** [comment]
Hi guys. I have had the same problem. Just works when I configured `configure({ safeDescriptors: false });` at store class. There is way to configure only in my tests?

**Comment by urugator** [comment]
> There is way to configure only in my tests?

Call `configure({ safeDescriptors: false });` only in your tests...?

**Comment by kubk** [comment]
@rvicenzo It's not related to Mobx, but you can use the `setupFilesAfterEnv` option in Jest: https://stackoverflow.com/a/50302253

**Comment by rvicenzo** [comment]
> > There is way to configure only in my tests?
> 
> Call `configure({ safeDescriptors: false });` only in your tests...?

I tried it, but didn't work. 
I noticed another behavior: when I changed my class methods, removing arrow functions, tests worked.
