### ISSUE TITLE
Naming autoruns

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#293]
I know you can name an autorun by naming the function parameter:

```javascript
const disposer = autorun(function iAmANamedAutorun() {
    // ...
});
```

Which is great for debugging, but it can be a bit of a pain to fully utilize. For example, if I want to do something like this:

```javascript
const fn = () => {
     // ...
}
fn.name = 'update autorun for item#' + item.id;
const disposer = autorun(fn);
```
It's a little convoluted. It'd be nice if I could do:
```javascript
const disposer = autorun('update autorun for item#' + item.id, () => {
});
```

This'd also align nicely with how an `[@]action` can be named. I'm happy to try adding this if there is any interest?

**Comment by mweststrate** [comment]
Sounds like a very good idea! Feel free to go ahead, I don't think it will introduce overload issues
