### ISSUE TITLE
Intended documentation issue or regression with MobX.toJS?

### ISSUE THREAD

**Issue by seansd** [mobxjs/mobx#2931]
https://www.mobxjs.com/refguide/tojson.html

The current document says that the options argument is supported.  However in looking at the code here: https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/api/tojs.ts#L68  that argument has been removed / deprecated.  

I can update the docs if need be but I'd like an explanation of why that argument was removed.  We rely on it heavily as opting out of cycle detections vastly improves performance.  Is there an alternative method perhaps we could use instead or some other work around?

**Comment by urugator** [comment]
> The current document

Documentation is at https://mobx.js.org/.
`mobxjs.com` isn't ours, I think we tried to contact the author, dunno what's the current status.

> why that argument was removed

https://github.com/mobxjs/mobx/issues/2912#issuecomment-825890901

**Comment by iChenLei** [comment]
@seansd Hi, mobxjs.com is a outdated doc mirror website in china mainland. I will try to contact with owner and update content.

**Comment by RvanderLaan** [comment]
any luck @iChenLei ? I was scratching my head the last 2 hours because the documentation wasn't making sense 😩 
Lots of search engine results are pointing to the .com website
