### ISSUE TITLE
flow.bound doesn't work

### ISSUE THREAD

**Issue by blinkcat** [mobxjs/mobx#2941]
**Intended outcome:**
It should print 1 2 3 on the right screen

**Actual outcome:**
change `flow` to `flow.bound` on line 7 of store.ts
print nothing

**How to reproduce the issue:**
demo [https://stackblitz.com/edit/react-ts-kusqpj?file=store.ts](https://stackblitz.com/edit/react-ts-kusqpj?file=store.ts)

**Versions**
mobx 6.3.0
mobx-react-lite 3.2.0

**Comment by urugator** [comment]
Thanks for the report! Should be fixed in the next release (6.3.1)
