### ISSUE TITLE
autoBind option don't bind flows automatically

### ISSUE THREAD

**Issue by OldGraff** [mobxjs/mobx#2948]
**Intended outcome:**
_Similary to actions, flows can be bound by default using autoBind option._ — said in the documentation
`makeAutoObservable(this, { }, { autoBind: true });` — not working b/c lose context

**Actual outcome:**
`makeAutoObservable(this, { logout: flow.bound }, { autoBind: true });` —  working don't lose context 

**How to reproduce the issue:**

Try to `autoBind` generator and it lose context

**Versions**
`"mobx": "6.3.1"`

**Comment by urugator** [comment]
Thanks for the report. Should be fixed in next release (6.3.2)
