### ISSUE TITLE
Make prototype-based caching of properties via inferredAnnotationsSymbol optional

### ISSUE THREAD

**Issue by chris-ck** [mobxjs/mobx#2951]
I have a dynamic class whose properties are defined in a configuration map. Upon fetching objects from the network, the configuration is looked up and the getters and setters are created dynamically via defineProperty (fields prefixed with _ as observables and setters/getters as computeds) based on the object's type. After this initialization I call makeAutoObservable to have mobx do its initialization. This leads to the fact that the an instance of the same prototype can have (and actually has) different properties depending on the type. What happens now is that because of the property cache being stored in the prototype, initialization fails with mobx not finding fields because the first object's instance had a different type (and thus different fields/setters/getters) than the subsequent. I currently have two options (actually more but these are the feasible ones):

- create the options map manually and use makeObservable with the specific configuration or
- `delete obj.__proto__[Object.getOwnPropertySymbols(obj.__proto__)[0]];`

With the latter being a hack which I went for and which works now as long as inferredAnnotationsSymbol is the only Symbol on the prototype.

Is there a way to make this cleaner? Could we have a flag making the caching optional? From what I saw it saves mobx from calling ownKeys. What'd be interesting to know is how much performance do I lose with my "hack"? Is calling getOwnPropertyNames and getOwnPropertySymbols per instance a big deal? I was hoping this would be cached somewhere internally in the JS engine already.

**Comment by urugator** [comment]
> inferredAnnotationsSymbol

Does not exists since 6.2. It used to avoid an extra prototype traversal every constructor invocation to infer correct annotation (followed by another traversal applying the annotation).
Since 6.2 this happens in a single step, so no need for the cache.
However we still assume that `make(Auto)Observable` [is called unconditionally with the same annotations (point 9)](https://mobx.js.org/observable-state.html#limitations) ... so `makeObservable` with options that vary from instance to instance isn't ideal either.
It will probably work atm, but I can't guarantee it will stay like this.
It's a bit odd requirement since the "type" that dictates the object's shape is (usually) the prototype. Could you share more info on what's the prototype purpose, why the fields differ, provide an example how it looks like?
What you could do, I think, is to dynamically create a new subclass for each "type". You can't use `makeAutoObservable` then, but since you know the field names, you can pass options like `{ field1: true, field2: true }`. For the time being you could at least keep this as a backup solution.

**Comment by chris-ck** [comment]
Thanks a lot for your response. I realized I am using 6.1.8 that's why the caching is still around in my code. 

I am implementing a highly dynamic app based on electron. I originally used mobx-state-tree for the models but did have to abandon it and roll my own solution for a variety of reasons (for example the reference type not allowing other properties than the id itself and the cumbersome handling of lazily-loaded references). I therefore created a unified class that has the type definition stored in a config map (imagine `types.model` from MST in a simplified manner). Reasons for this level dynamicity are manifold, some of them include patching a type without an explicit app update (electron), and an overall smaller and easier-to-maintain code base. The model has a common set of attributes which is shared among all types and additional properties added depending on the object's type. I understand this approach is frowned upon by some developers, but for my purpose and my architecture it works quite well.

Regarding an example: there is really nothing complicated to it, imagine `types.model` of MST but less explicit/static via a configuration map. I iterate a map which calls defineProperty on the object. The getter additionally adds an `onBecomeObserved` for handling lazy loading of reference(d) objects into a cache. That's it.

Your suggestion aligns with my fallback idea. I appreciate your support in this matter and think I will implement it according to your suggestion. Should be a breeze since I know the fields/getters/setters already.

**Comment by mweststrate** [comment]
Note could still create new classes on the fly in that cause and benefit
from the optimisations that comes with it? E.g. 'return new class extends
BaseModel { }' Using a single class in a variety of shapes will cause a lot
of de-opts in JS

**Comment by chris-ck** [comment]
Yeah, @urugator's suggested solution includes dynamic class creation. I will definitely explore that option. Thanks.

**Comment by urugator** [comment]
If you're in control of model creation and you can impose some restrictons to model and it's definition, you could also consider creating observable objects on you own. It can be quite simple depending on your needs:
For each observable/computed field, you need an extra internal `ObservableValue`/`ComputedValue` and a getter/setter that delegates to their `.get()/.set()` method.
For `action/flow` you just wrap the original function with `action(fn)/flow(fn)` and assign it (or defineProperty) to instance/prototype.
Keys are not reactive, `observe`, `intercept`, `isObservableObject/Prop`  won't work etc, but perhpas you don't need these...

**Comment by chris-ck** [comment]
What would be the reason for doing it this way? You say it'd be faster...In what sense? Wouldn't I be replicating what `makeObservable` does for me? I mean sure, I would escape the potential issues you mentioned with differing objects of the same prototype, but if I followed your suggestion of dynamically creating classes (which itself is a no-brainer) I'd be set, or am I missing something here? Just trying to understand the benefits of rolling it completely on my own (good to know the approach though).

**Comment by urugator** [comment]
> What would be the reason for doing it this way?

Either perf or limitations imposed by `make(Auto)Observable`. 
`make(Auto)Observable` is designed for conviniency and has to take into consideration various use/edge cases.
I wouldn't consider it overly representative, but to provide some example, [this PR](https://github.com/mobxjs/mobx-state-tree/pull/1656) *"seems to have improved instance instantiation speed (MyModel.create()) by about 20%"*

**Comment by chris-ck** [comment]
This is good to know. For the time being I will stick to the simplest solution which seems to work now (and not roll everything on my own...you know, MVP, deadlines, impatient people waiting ;-)), but I'm glad I asked...now I now what to do, should I hit another roadblock. Thanks for the useful insights!
