### ISSUE TITLE
Upgrading from mobx-react@6.3.1 to 7.X.X causes tests that stub React.useState to throw error

### ISSUE THREAD

**Issue by ninefivetwo** [mobxjs/mobx#2952]
**Intended outcome:**

I have components tests that require stubbing around React.useState with sinon so that I can assert different states of my components. The stubbing had no issues up until I updated mobx and mobx-react to the latest version.

**Actual outcome:**

Since updating to mobx-react@7.X.X the tests that stub React.useState throw this error:

`
TypeError: FinalizationRegistry.prototype.register: target must be an object
    at FinalizationRegistry.register (<anonymous>)
    at addReactionToTrack (https://knyvk.csb.app/node_modules/mobx-react-lite/es/utils/createReactionCleanupTrackingUsingFinalizationRegister.js:21:16)
    at useObserver (https://knyvk.csb.app/node_modules/mobx-react-lite/es/useObserver.js:58:79)
    at ObservedClickCounter (https://knyvk.csb.app/node_modules/mobx-react-lite/es/observer.js:29:46)
    at ObservedClickCounter (https://knyvk.csb.app/node_modules/@wojtekmaj/enzyme-adapter-react-17/build/ReactSeventeenAdapter.js:669:38)
`

**How to reproduce the issue:**

I have tests reproducing the error in https://codesandbox.io/s/mobx-react-observer-with-stubbed-usestate-knyvk.

I have narrowed it down to the use of observer (see tests for components with/without the use of observer) and its not an issue exclusive to using sinon to stub React.useState (see tests where sinon/jest is used to stub).

**Versions**

I have encountered this issue after upgrading from:
- mobx@5.15.7->6.3.2
- mobx-react@6.3.1->7.2.0

**Comment by urugator** [comment]
Well `observer` uses `useState`, so if you replace it's implementation, it can't work properly...

**Comment by ninefivetwo** [comment]
I am trying to understand why it sudden started throwing this issue (or why it was working previously).
Based on the commit history the use of `React.useState` was added years ago. So what was changed recently that may have triggered this?

**Comment by urugator** [comment]
The mechanism for reaction disposal was changed to use `FinalizationRegistry` if available (instead of timer based solution). We use the `useState` to hold the registry's target. We use `useState` for others things (component invalidation), which you must have broken before, it just doesn't immediately throw.

**Comment by ninefivetwo** [comment]
Thanks for the insight.

For my case the easiest workaround is to conditional stub `useState`.
