### ISSUE TITLE
The example of Understanding reactivity in the  Documentation  seems not right

### ISSUE THREAD

**Issue by blinkcat** [mobxjs/mobx#2953]
code is here
```js
import { makeAutoObservable, autorun, trace } from 'mobx';

class Message {
  title;
  author;
  likes;
  constructor(title, author, likes) {
    makeAutoObservable(this);
    this.title = title;
    this.author = author;
    this.likes = likes;
  }

  updateTitle(title) {
    this.title = title;
  }
}

let message = new Message('Foo', { name: 'Michel' }, ['Joe', 'Sara']);

autorun(() => {
  console.log(message.title);
});
message.updateTitle('Bar');
```
**Intended outcome:**
it should log `Foo` then `Bar`

**Actual outcome:**
just log `Foo`

**How to reproduce the issue:**
[online demo](https://stackblitz.com/edit/js-tytoex)

**Versions**
mobx@6.3.2

**Comment by urugator** [comment]
Please change your `tsconfig.json` accroding to:
https://mobx.js.org/enabling-decorators.html#typescript
Without `"useDefineForClassFields": true` the field `title` does not exist yet when `makeAutoObservable` is called and therefore can't be made observable.

**Comment by blinkcat** [comment]
oh, I see, thank you for your quick reply.
