### ISSUE TITLE
Can't rerender Component when trigger an action

### ISSUE THREAD

**Issue by MrKou47** [mobxjs/mobx#2962]
**Intended outcome:**

re-render component as normal.

**Actual outcome:**

Can't re-rendered.And no error in the console.

**How to reproduce the issue:**
https://codesandbox.io/s/quiet-wave-lc2fv?file=/src/App.tsx

**Versions**

mobx: 6.3.2
mobx-react: 7.2.0

**Comment by urugator** [comment]
You have to call `makeObservable(this)` in `ListStore`'s constructor. See:
https://mobx.js.org/enabling-decorators.html
https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable

The reproduction uses mobx5, therefore it works fine.

**Comment by MrKou47** [comment]
@urugator Thanks, i use the classic syntax and i think i might miss somthing :)
