### ISSUE TITLE
Error: [MobX] 'set()' can only be used on observable objects

### ISSUE THREAD

**Issue by tanj** [mobxjs/mobx#2971]
I have a project running in development (ng serve), that works on a windows machine, but not on a linux machine.

**Intended outcome:**
I can run the project on either a windows or linux machine without errors.

**Actual outcome:**
Project runs in the windows environment, but not on linux. Linux version ends up with an error when trying to load data 
![image](https://user-images.githubusercontent.com/90219/121257384-7a59fc80-c862-11eb-8399-f293e3d0e9db.png)

**How to reproduce the issue:**
I'm not sure how to reproduce. As far as I can tell everything is the same. `npm ls` results in the same package list for both the linux and windows environments. The only difference I know of is that my windows environment is node 14, while the linux is node 12.

**Versions**
mobx 6.3.2
Linux node-js: v12.21.0
Windows node-js: v14.16.1

```
frontend@0.0.0 /home/tanj/pce-testsheets/pce_testsheets/frontend
├── __ngcc_entry_points__.json@ extraneous
├── @angular-devkit/build-angular@0.1102.14
├── @angular-eslint/builder@2.1.0
├── @angular-eslint/eslint-plugin-template@2.1.0
├── @angular-eslint/eslint-plugin@2.1.0
├── @angular-eslint/schematics@2.1.1
├── @angular-eslint/template-parser@2.1.0
├── @angular/animations@11.2.14
├── @angular/cdk@11.2.13
├── @angular/cli@11.2.14
├── @angular/common@11.2.14
├── @angular/compiler-cli@11.2.14
├── @angular/compiler@11.2.14
├── @angular/core@11.2.14
├── @angular/flex-layout@11.0.0-beta.33
├── @angular/forms@11.2.14
├── @angular/material-moment-adapter@11.2.13
├── @angular/material@11.2.13
├── @angular/platform-browser-dynamic@11.2.14
├── @angular/platform-browser@11.2.14
├── @angular/router@11.2.14
├── @datx/core@2.2.1
├── @datx/jsonapi-angular@2.2.0
├── @datx/jsonapi@2.2.0
├── @ng-select/ng-select@6.1.0
├── @ngrx/effects@11.1.1
├── @ngrx/store@11.1.1
├── @types/jasmine@3.7.7
├── @types/node@12.20.15
├── @typescript-eslint/eslint-plugin@4.16.1
├── @typescript-eslint/parser@4.16.1
├── bindings@1.5.0 extraneous
├── codelyzer@6.0.2
├── eslint-plugin-import@2.22.1
├── eslint-plugin-jsdoc@35.1.3
├── eslint-plugin-prefer-arrow@1.2.2
├── eslint@7.28.0
├── file-uri-to-path@1.0.0 extraneous
├── jasmine-core@3.7.1
├── jasmine-spec-reporter@7.0.0
├── karma-chrome-launcher@3.1.0
├── karma-coverage@2.0.3
├── karma-jasmine-html-reporter@1.6.0
├── karma-jasmine@4.0.1
├── karma@6.3.3
├── mobx@6.3.2
├── moment@2.29.1
├── nan@2.14.2 extraneous
├── prettier@2.2.1
├── protractor@7.0.0
├── rxjs-compat@6.6.7
├── rxjs@6.6.7
├── ts-node@8.3.0
├── tslib@2.2.0
├── tslint@6.1.3
├── typescript@4.1.5
└── zone.js@0.11.4
```

**Comment by tanj** [comment]
So I was confused by why this used to work and I noticed I had bumped mobx between deploys on the linux server.

I rolled it back to 6.2.0 and it is now working on the linux machine. Not sure where the issue would be.

**Comment by tanj** [comment]
I f'd up my package.json requirement and used `"mobx": "^6.2.0"` which means the install still has `6.3.2`. But it is working now.

I had `rm -rf node_modules` between my attempts to get this working. Not sure how changing the requirement from `"mobx": "^6.3.2"` to `"mobx": "^6.2.0"` changed anything

**Comment by mweststrate** [comment]
Closing as this seems more like a local issue than a bug report.
