### ISSUE TITLE
Mobx won't create an `observable.map` from `T extends Map`

### ISSUE THREAD

**Issue by Nokel81** [mobxjs/mobx#2979]
**Intended outcome:**
For some `class MyMap extends Map` and some value `const aMap: MyMap`, running `observable.map(aMap)` should not throw an error.

**Actual outcome:**
Throws the error: `Error: [MobX] Cannot initialize from classes that inherit from Map: MyMap`.

**How to reproduce the issue:**

```ts
class MyMap extends Map {}

const aMap = new MyMap([["a", 1]]);
const obMap = observable.map(aMap);
```

**Versions**
mobx: ^6.3.0

I see that this is caused by `mobx/src/types/observablemap.ts:322`. Also I see that this is not the case with `observable.set` and classes of the form `class MySet extends Set`.

**Comment by mweststrate** [comment]
As the fact that there is a specific error for this suggests, this is
working as intended :). For Set a similar limitation holds, but it might be
the case a check is missing there.
