### ISSUE TITLE
No log statements visible in terminal where expo is started in combination with annotations / babel decorators

### ISSUE THREAD

**Issue by rhoehener** [mobxjs/mobx#2981]
This has taken me weeks to reproduce and isolate, and now I don't dare to use annotations anymore :(

**Intended outcome:**

Log statements visible in terminal where `expo start` is executed.

**Actual outcome:**

Only one or two statements appear (if any at all), then nothing.

**How to reproduce the issue:**

[testproject.zip](https://github.com/mobxjs/mobx/files/6633389/testproject.zip)

In an empty test directory:

```
npm install -g expo-cli  (optional, to get latest expo-cli)
expo init . --template expo-template-blank-typescript --npm
expo install mobx-react
npm install --save-dev @babel/plugin-proposal-decorators
npm install --save-dev @babel/plugin-proposal-class-properties
```

App.tsx:

```
import React from 'react';
import {Button, View} from 'react-native';

export default class App extends React.Component {
  public render() {
    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Button title="Click me" onPress={e => console.log("click")}/>
      </View>
    );
  }
}
```

When running now and clicking the button, the log output appears in the terminal, as expected.

Then as documented at https://mobx.js.org/enabling-decorators.html

modify babel.config.js:
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    "plugins": [
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose": false }]
    ]
  };
};
```

modify tsconfig.json:

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": true
  }
}
```

Now run again with `expo start -c`. No logs appear.

**Versions**

```
  Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

+-- mobx-react@7.2.0
| +-- mobx-react-lite@3.2.0
| | +-- mobx@6.3.2 deduped
| | `-- react@16.13.1 deduped
| +-- mobx@6.3.2
| `-- react@16.13.1 deduped
```

**Comment by rhoehener** [comment]
Thanks for looking at this! I'm going circles between Expo, MobX and Babel. This just now: https://github.com/babel/babel/issues/13452
Another 2 days gone just fighting with configuration, but new problems just keep coming up. I'm giving up now and will rewrite with the non-decorator API :(

**Comment by mweststrate** [comment]
Yes, sorry for that. We hate this as much as you. This is not in control of
any of the directly involved parties (at least not Babel, don't know about
Expo). I'm participating in TC 39 to get decorators shipped, but in the
meantime the eco system is in flux since the class field proposal totally
changed how decorators could be used (I objected as hard as possible to the
change, but to no avail, so the language spec now differs in an decorator
incompatible way with how TypeScript is doing it now already for years). If
interested I can link you the technical discussions that culminated in the
change, but that will probably be of little solace.

It'd be great if Expo could bump, otherwise at least do check out
mobx-decorate, it should help with the conversion.

**Comment by rhoehener** [comment]
I did read something about it. A pity, I really liked the feel of MobX annotations.

**Comment by rhoehener** [comment]
Brent wrote that [Expo supports decorators out of the box](https://github.com/expo/expo-cli/issues/3570#issuecomment-859019217).

So I [gave it another shot](https://github.com/expo/expo-cli/issues/3570#issuecomment-859634381) without doing any of the plugin configuration described by the MobX docs, and without any of those described by the Babel docs, and so far it seems to work (including log output in the Expo terminal).

Thanks again for your support!

**Comment by rhoehener** [comment]
Btw I think that would be a nice quick start example to include in the MobX docs (named "Expo & MobX with annotations and component classes").

All the examples nowadays seem to use hooks and functional approaches. For someone like me who is coming from a traditional "one file one class"-Java background, that is just too many new concepts to grasp at once.

**Comment by urugator** [comment]
> Btw I think that would be a nice quick start example to include in the MobX docs

Feel free to PR

Added babel's assumptions to docs: https://github.com/mobxjs/mobx/pull/3001

Closing as resolved (?)
