### ISSUE TITLE
Changing state with actions fails using async

### ISSUE THREAD

**Issue by jorilallo** [mobxjs/mobx#299]
I started writing my `@action`s with async/await and this seems to fail when running MobX in strict mode:

```js
@action updateDocument = async () => {
   this.isSaving = true;
   ....
}
```

```
mobx.js:2077 Uncaught (in promise) Error: [mobx] Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode. Wrap the current method in `action` if this state change is intended
```

**Comment by mweststrate** [comment]
use async action (()=>...

I'll make sure to add it to the docs

Op vr 3 jun. 2016 06:17 schreef Jori Lallo <notifications@github.com>:

**Comment by jorilallo** [comment]
@mweststrate 👍

**Comment by mweststrate** [comment]
Updated the docs: http://mobxjs.github.io/mobx/refguide/action.html

**Comment by jorilallo** [comment]
@mweststrate After trying this out it seems that, at least with Babel6, `async` is unable to play ball with `action`:

```
ERROR in ./src/stores/UserStore.js
Module build failed: SyntaxError: /Users/jorilallo/projects/atlas/src/stores/UserStore.js: Unexpected token (47:65)
  45 |   }
  46 |
> 47 |   @action updateDocument = async action(() => {
     |                                                                  ^
  48 |      this.isLoading = true;
  49 |
  50 |   })
```

**Comment by mweststrate** [comment]
Thanks for noticing! Will investigate, in the mean time `() => action(() => { .. })()` probably works as workaround (or disable strict mode)

**Comment by jorilallo** [comment]
@mweststrate ended up just disabling strict mode but will be interested to hear the outcome of this :)

**Comment by aksonov** [comment]
+1, disabled strictMode as well because of the same reason

**Comment by mweststrate** [comment]
Did a quick test, simply putting parentheses around the expression seems to solve this issue (at least parsing). Can you guys verify this? If it doesn't fix it, could you share your `.babelrc` file? Then I'll take a further look later this week (conference tomorrow). Thanks!

```javascript
class Store {
  @action test = async (action(() => {

  }));
}
```

**Comment by alinz** [comment]
@mweststrate I don't think it's possible. they way that you wrote, the babel compiler compiles it into 
```

**Comment by mweststrate** [comment]
Would you mind creating a small github project in which I can quickly test? Then I'll try to dive into it somewhere tomorrow, otherwise it probably will be thursday.

**Comment by alinz** [comment]
@mweststrate I think it has nothing to do with mobx. This is how babel transpiles the code.

if you have the following ES6

```js
const fn = async () => {}
```

after babel transformation you get this

```js
"use strict";

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { return step("next", value); }, function (err) { return step("throw", err); }); } } return step("next"); }); }; }

var fn = function () {
  var ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, undefined);
  }));

  return function fn() {
    return ref.apply(this, arguments);
  };
}();
```

as if you have this which you are referring to

```js
const fn = async(() => {})
```

it transforms to

```js
"use strict";

var fn = async(function () {});
```

so symatically `async () => {}` is not the same as `async(() => {})`

**Comment by mweststrate** [comment]
Async will not generate useful code indeed for anonymous functions inside the async function. (Which makes lot of sense). To address this `2.3.0` will introduce a new feature, `runInAction`, which is basically sugar for `action(() => { stuff })()`, so that the above could be written as follows:

```javascript
updateDocument = async () => {
   await somethingAsync()
   await somethingElse()
   runInAction("updating document", () => {
     this.isLoading = true;
   })
}
```

**Comment by jorilallo** [comment]
Thanks Michel!

**Comment by codetony25** [comment]
I've have some other alternatives below:

      @action
      handleUpdate = () => ((async () => {
        const data = await fetch('my/cool/api/);
       this.isLoading = false;
      })());

      @action
      handleUpdate = (async () => {
        const data = await fetch('my/cool/api/);
        this.isLoading = false;
      }).bind(this);

Not sure if @action will work appropriately with these, but they seem to be working fine for me. What do you think @mweststrate ?

**Comment by TangMonk** [comment]
actually, runInAction not works in following code:

```
export default new class App {
  @observable logined = false
  @observable loginLoading = false
  @observable user = {}
  @action async login(payload){
    try {
      this.loginLoading = true  // this line is works, state changed
      await request('/admin/login', {
        method: 'post',
        data: payload
      })
      this.logined = true
      this.loginLoading = false
    } catch (error) {
      runInAction( () => { // this line not works, state not changed when exception cause.
        this.logined = false 
        this.loginLoading = false
      })
    }
  }
}
```
