### ISSUE TITLE
[mobx-react] State not made observable after upgrading to mobx 6

### ISSUE THREAD

**Issue by masylum** [mobxjs/mobx#2991]
**Intended outcome:**

We've recently migrated to `mobx` 6 (6.3.2) using the code mod and replaced all decorators with calls to `makeObservable`.
We've also upgraded `mobx-react` accordingly (7.2.0). 

**Actual outcome:**

After the migration we've seen some regressions in components that use state as part of a `computed`. For some reason it looks like state is no longer observable. I searched and couldn't find any change on that behaviour.

**How to reproduce the issue:**

I will try to showcase a very simplified case of the bug. the code will be a bit non-sense, but I tried to simplify it as much as possible:

```js
class Component extends React.Component<Props, State> {
  state: { num: 0 }

  constructor(props: Props) {
    super(props)

    makerObservable(this, {
      numPlusOne: computed
    })
  }

  get numPlusOne () {
    return this.state.num + 1
  }

  onClick (num: number) {
    this.setState({ num })
  }

  render () {
    return (
      <button onClick={() => this.onClick(Math.random() * 100)}>
        {this.numPlusOne}
      </button>
    )
  }
}

export default observer(Component)
```

You would expect `numPlusOne` to recalculate each time `this.state.num` changes, but it no longer does it.

**Versions**

- `mobx` 6.3.2
- `mobx-react` 7.2.0

**Comment by iChenLei** [comment]
Your usage is weird. Please read the mobx-react usage guide https://mobx.js.org/react-integration.html .

![2021-06-18 19 09 01](https://user-images.githubusercontent.com/14012511/122552254-a9454f00-d068-11eb-9ff2-b6379389c9f0.png)

And even remove `makeObserverable` code, you code snippet still work as expected, because you call `setState`, and `React` will rerender! So , what's your real problem ?

**Comment by urugator** [comment]
@iChenLei Does it work without commenting? Can you share a link to that repro? I would like to look at it.

**Comment by iChenLei** [comment]
@urugator https://jsfiddle.net/owtcvg2d

**Comment by masylum** [comment]
hmm... I don't manage to create a minimal case for reproducing the bug. Closing. Thanks for your time!
