### ISSUE TITLE
[MobX] minified error nr: 1 observable,ObservableObject.editableAccount

### ISSUE THREAD

**Issue by vor-obey** [mobxjs/mobx#3002]
After migrating mobx 5.15.4 to mobx 6.1.8 and migrating webpack 4.44.0 to webpack 5. 38.1, the error described below appeared.

Error: [MobX] minified error nr: 1 observable,ObservableObject.editableAccount. Find the full error at: https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/errors.ts
    at r (588.748df49efe06d0f85357.js:1)
    at Function.ue [as make_] (588.748df49efe06d0f85357.js:1)
    at e.t.make_ (588.748df49efe06d0f85357.js:1)
    at 588.748df49efe06d0f85357.js:1
    at Array.forEach (<anonymous>)
    at en (588.748df49efe06d0f85357.js:1)
    at new D (common.5315b6acae90cd58bfca.bundle.js:1)
    at new n.createContext.rootStore (common.5315b6acae90cd58bfca.bundle.js:1)
    at Object.4936 (common.5315b6acae90cd58bfca.bundle.js:1)
    at n (app.2203909650c7ca78a4ce.js:1)

package.json

{
  "dependencies": {
    "@babel/runtime": "7.0.0-beta.55",
    "@material-ui/core": "4.11.0",
    "@material-ui/icons": "4.9.1",
    "@material-ui/lab": "4.0.0-alpha.56",
    "@material-ui/pickers": "3.2.10",
    "axios": "0.19.2",
    "babel": "6.23.0",
    "clsx": "1.1.1",
    "crypto-browserify": "^3.12.0",
    "crypto-js": "^4.0.0",
    "fast-deep-equal": "3.1.3",
    "final-form": "4.20.1",
    "final-form-arrays": "3.0.2",
    "final-form-material-ui": "0.3.0",
    "lodash": "4.17.19",
    "mobx": "6.1.8",
    "mobx-react-lite": "3.2.0",
    "notistack": "0.9.17",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-final-form": "6.5.1",
    "react-final-form-arrays": "3.1.2",
    "react-router-dom": "5.2.0",
    "react-virtualized-auto-sizer": "1.0.2",
    "react-window": "1.8.5",
    "simple-crypto-js": "^3.0.0"
  },
  "devDependencies": {
    "@types/enzyme": "3.10.5",
    "@types/enzyme-adapter-react-16": "1.0.6",
    "@types/jest": "26.0.7",
    "@types/lodash": "4.14.158",
    "@types/react": "16.9.43",
    "@types/react-dom": "16.9.8",
    "@types/react-router-dom": "5.1.5",
    "@types/react-test-renderer": "16.9.2",
    "@types/react-virtualized-auto-sizer": "1.0.0",
    "@types/react-window": "1.8.2",
    "@types/redux-form": "8.2.7",
    "@types/webpack": "4.41.21",
    "@typescript-eslint/eslint-plugin": "3.7.0",
    "@typescript-eslint/parser": "4.27.0",
    "@welldone-software/why-did-you-render": "4.2.7",
    "autoprefixer": "9.8.5",
    "babel-jest": "26.1.0",
    "babel-plugin-require-context-hook": "1.0.0",
    "clean-webpack-plugin": "3.0.0",
    "css-loader": "4.0.0",
    "cssnano": "4.1.10",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.2",
    "enzyme-to-json": "3.5.0",
    "eslint": "7.5.0",
    "eslint-loader": "4.0.2",
    "eslint-plugin-react": "7.20.4",
    "file-loader": "6.0.0",
    "html-loader": "2.1.2",
    "html-webpack-plugin": "5.3.1",
    "husky": "4.2.5",
    "identity-obj-proxy": "3.0.0",
    "jest": "26.1.0",
    "mini-css-extract-plugin": "0.9.0",
    "node-sass": "4.14.1",
    "postcss-loader": "3.0.0",
    "react-svg-loader": "3.0.3",
    "react-test-renderer": "16.13.1",
    "resolve-url-loader": "3.1.1",
    "sass-loader": "9.0.2",
    "style-loader": "1.2.1",
    "terser-webpack-plugin": "3.0.7",
    "ts-jest": "26.1.3",
    "ts-loader": "8.0.1",
    "typelevel-ts": "0.4.0",
    "typescript": "4.3.2",
    "url-loader": "4.1.1",
    "webpack": "5.38.1",
    "webpack-bundle-analyzer": "4.4.2",
    "webpack-cli": "4.7.0",
    "webpack-dev-server": "3.11.2"
  },
  "browser": {
    "[module-name]": false
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint && npm test"
    }
  }
}

webpack.config.js

function getCommitHash(repositoryPath) {
  return execSync(cmd, {
    cwd: repositoryPath
  }).toString().split('\n')[0];
}

let plugins = [
  new webpack.DefinePlugin({
    process: {
      env: {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        API_URL: JSON.stringify(process.env.API_URL),
        VERSION: JSON.stringify(version),
        HASH: JSON.stringify(getCommitHash(__dirname)),
        DEBUG: JSON.stringify(process.env.DEBUG),
      }
    }
  }),
  new CleanWebpackPlugin(),
  new HtmlWebpackPlugin({
    template: './index.html',
    inject: true,
    favicon: './assets/images/favicon.png',
    minify: {
      removeComments: true,
      collapseWhitespace: true,
      removeRedundantAttributes: true,
      useShortDoctype: true,
      removeEmptyAttributes: true,
      removeStyleLinkTypeAttributes: true,
      keepClosingSlash: true,
      minifyJS: true,
      minifyCSS: true,
      minifyURLs: true,
    }
  }),
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoEmitOnErrorsPlugin(),
  new MiniCssExtractPlugin({
    filename: 'style.[hash].css',
    allChunks: true,
  }),
];

if (!isProd) {
  plugins.push(new BundleAnalyzerPlugin({
    openAnalyzer: false,
    analyzerPort: 9191
  }));
}

if(!isProd) {
  plugins.push(
    new webpack.ProgressPlugin(),
  );
}

module.exports = {
  mode: isProd ? 'production' : 'development',
  context: ROOT,
  entry: {
    app: './index.tsx'
  },
  output: {
    filename: 'js/[name].[contenthash].js',
    path: DESTINATION,
    chunkFilename: 'js/[name].[contenthash].bundle.js',
    publicPath: PUBLIC_URL
  },
  stats: {
    errorDetails: true
  },
  devtool: isProd ? false : 'source-map',
  devServer: {
    contentBase: path.join(__dirname, DESTINATION),
    allowedHosts: [
      ''
    ],
    historyApiFallback: true,
    disableHostCheck: true,
    compress: true,
    port: 9998
  },
  externals: {
    moment: 'moment'
},
  optimization: {
    minimize: isProd,
    minimizer: [
      new TerserPlugin({
        parallel: true,
        terserOptions: {
          output: {
            comments: false,
          }
        },
        extractComments: false,
      }),
    ],
    splitChunks: {
      cacheGroups: {
        default: false,
        vendors: false,
        common: {
          name: 'common',
          minChunks: 2,
          chunks: 'async',
          priority: 10,
          reuseExistingChunk: true,
          enforce: true
        },
        vendor: {
          chunks: 'all',
          maxSize: 200000,
          test: /node_modules/
        }
      }
    }
  },
  resolve: {
    extensions: ['.ts', '.tsx', 'jsx', '.js', '.svg', '.png', '.jpeg', 'jpg',
      '.json', '.css', '.scss', '.saas'
    ],
    modules: [
      ROOT,
      'node_modules'
    ],
    fallback: {
      crypto: false,
      fs: false,
      fsevents: false
    }
  },
  plugins: plugins,
  target: 'web',
  module: {
    rules: [{
        test: /\.ts$/,
        enforce: 'pre',
        exclude: /(node_modules)/,
        loader: 'eslint-loader',
      },
      {
        test: /\.tsx?$/,
        use: [{
          loader: 'ts-loader',
        }],
        exclude: /node_modules/,
      },
      {
        test: /\.(scss|sass|css)$/i,
        use: [{
            loader: MiniCssExtractPlugin.loader
          },
          'css-loader', 'resolve-url-loader', 'postcss-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        use: {
          loader: 'html-loader'
        }
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [{
          loader: 'file-loader',
          options: {
            limit: 512,
            quality: 85,
            name: '[path][name].[ext]',
          }
        }]
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: [
          'file-loader'
        ]
      }
    ]
  }
};

**Comment by mweststrate** [comment]
Please make sure that you follow the migration guide and update your babel / typescript config. If that didn't help, please follow the issue template when filing an issue.
