### ISSUE TITLE
This will not work if we use Hooks inside of our functions. Is there an workaround that I do not know of?

### ISSUE THREAD

**Issue by hidaytraj** [mobxjs/mobx#3006]
This will not work if we use Hooks inside of our functions. Is there an workaround that I do not know of?

_Originally posted by @radum in https://github.com/mobxjs/mobx/issues/853#issuecomment-497290356_

**Comment by mweststrate** [comment]
Please try again by following the issue template. A random sentence from 2019 isn't helpful to anyone.
