### ISSUE TITLE
Bug: `observable` field are editable when the object is frozen with `Object.freeze`

### ISSUE THREAD

**Issue by akphi** [mobxjs/mobx#3008]
I have frozen a non-plain object with `Object.freeze`, fields being decorated with `observable` are still modifiable.

I have looked around for similar issues, but I don't seem to find one that fits my description exactly, also most of those issues are rather old so this might be a problem that is introduced more recently.

**Intended outcome:**

I would expect the field to be non-modifiable, or an error is thrown when I attempt to change the value of the frozen field.

**Actual outcome:**

The observable field of the frozen object is modifiable.

**How to reproduce the issue:**

Please refer to this for code repro:
https://github.com/akphi/issue-repo/tree/mobx-observable-ref-freeze

I have the following code:

```ts
import { makeObservable, observable, action } from "mobx";

class Person {
  name = '';
  age = 1;

  constructor() {
    makeObservable(this, {
      name: observable,
      setName: action,
    });
  }

  setName(val: string) {
    this.name = val;
  }
}

export const App = (props: {}) => {
  const person = new Person();
  person.setName('initial');
  console.log("person", person, person.name); // this will print `initial` for the name
  Object.freeze(person);
  person.setName('something');
  // person.age = 3; // this will throw an error if uncommented
  console.log("person", person, person.name); // this will print `something` for the name
  return <div>{person.name}</div>;
};
```

As you can see, `person.name` is still modifiable after calling `Object.freeze(person)`. On the other hand, if we modify the non-observable field `person.age`, error will be thrown.

**Versions**

`mobx@6.3.2`

**Comment by mweststrate** [comment]
Observable properties are setter / getter pairs, not simple value fields,
so this is working as expected.

**Comment by akphi** [comment]
@mweststrate Gotcha, so do we have an idiomatic way to make an instance with observables atteibute immutable of some sort?

**Comment by mweststrate** [comment]
No, observables are per definition not immutable. Something immutable isnt
observable but constant.

**Comment by akphi** [comment]
@mweststrate Thanks for clarifying
