### ISSUE TITLE
Collection Util Functions / Map Functions does not work.

### ISSUE THREAD

**Issue by knuspertante** [mobxjs/mobx#3009]
**Intended outcome:**

Entries, values and keys should be printed. 

Currently I'm unable to get any value from map by id.

```ts
get(this.tasksMap, task.id) 
````
or 
```ts
this.tasksMap.get(task.id) 
````
always return undefined.

**Actual outcome:**

![Bildschirmfoto 2021-06-25 um 10 39 55](https://user-images.githubusercontent.com/32802753/123396884-1fced900-d5a2-11eb-8a63-99425acb13d1.png)

![Bildschirmfoto 2021-06-25 um 10 40 07](https://user-images.githubusercontent.com/32802753/123396956-2f4e2200-d5a2-11eb-9100-f0f5303bca82.png)

**How to reproduce the issue:**

```ts

class Store {
  tasksMap = new Map();

  constructor() {
    makeAutoObservable(this);
    this.setTasks(this.listTasks());
  }

setTasks(tasks: Task[]): void {
    tasks.forEach((task) => {
      this.setTask(task);
    });
  }

setTask(task: Task): void {
    set(this.tasksMap, task.id, task);
  }

  getTask(id: string): Task | undefined {
    // let taskReturn = this.tasks.find((task) => task.id === id);
    console.log(this.tasksMap);
    entries(this.tasksMap).map((entry) => console.log(entry));
    values(this.tasksMap).map((entry) => console.log(entry));
    keys(this.tasksMap).map((entry) => console.log(entry));
    let taskReturn = get(this.tasksMap, id);
    if (!taskReturn) {
      getTaskUtil(id).then((task) => {
        taskReturn = task;
        this.addTask(taskReturn);
      });
    }
    console.log(`taskReturn: ${taskReturn}`);
    return taskReturn;
  }
}
```

**Versions**

mobx@6.3.2
typescript@4.3.4

npm: '7.11.2',
node: '14.16.0',
v8: '8.4.371.19-node.18',

**Comment by urugator** [comment]
Can't reproduce https://codesandbox.io/s/mobx-3009-z6w3q?file=/index.js
Please setup something that we can actually run.

**Comment by knuspertante** [comment]
Sorry, i also can't reproduce it 🙈  The error is still exists but I can't reproduce it -.-
