### ISSUE TITLE
keeping 2 stores in sync

### ISSUE THREAD

**Issue by giladv** [mobxjs/mobx#301]
Hi everyone.
i need to keep 2 different stores with 2 different structures in sync
if i'll simply autorun it it will create an infinite loop.
how would you approach this? is it even possible?

thanks!

**Comment by mweststrate** [comment]
usually deriving one completely from the other works best. you can use
autorun as well, but make sure that you start with a germinating condition
to avoid looping

Op vr 3 jun. 2016 14:06 schreef giladv <notifications@github.com>:

**Comment by giladv** [comment]
not sure i can cleanly check for equality between those two.
can you elaborate more about deriving one from the other?

**Comment by mweststrate** [comment]
Suppose you have a store with messages, and a store with users, but you also want to know which messages belong to a user. You could store that in the user, but it is an anti-pattern in MobX to have redundant state (there are some rare good reasons to do it, but in 90% of the cases it can be avoided. So here is how I would write the stores:

```
class MessageStore {
   @observable messages = []; // store message objects here

   findMessagesByAuthor(author) {
      return this.messages.filter(message => message.author = author)
   }
}

class User {
   @observable name
   // don't put an @observable 'messages in here!'` (that might be kept up to date with autorun)

   @computed get messages() {
      return MessageStore.findMessagesByAuthor(this)
   }
}
```

As a rule of thumb: if you want to update an observable value in autorun, you are looking at a hidden computed value.

**Comment by giladv** [comment]
oh yeah, that's what i did in most cases.
my specific use case is that i have 2 UI's side by side allowing you to edit the same thing in different ways.
one is a form and other is some drag and drop UI.
the form works with an instance of a FormStore which by design use it's own copy of whatever it's editing. and the D&D side has it's own special store.

this is how i thought of doing this but obviously i need a way to check for deep equality or this will
create an infinite loop. 
```
autorun(() => {
    this.nodeForm.assign(node.raw)
})

autorun(() => {
    this.node.assign(nodeForm.data)
})

```

**Comment by mweststrate** [comment]
@giladv ah I encountered similar cases also a few times. Usually I solved it by introducing ViewModels (if that rings a bell). It had a lot of computed properties and some methods that just update the original model. So it acts a bit as a Facade. 

What you can do if the `FormStore` needs its own copy, is have a computed values for the props that, depending on the current state of the form, either returns the local copies or the original. So as long as the mutations are made by the DnD thing, these changes are immediately reflected in the Form, unless the form is in a state that it shows its 'own' copies. (I hope that doesn't sound to vague?)

**Comment by mweststrate** [comment]
closed for inactivity, feel free to reopen
