### ISSUE TITLE
react ui cannot update when change observable data

### ISSUE THREAD

**Issue by yyzclyang** [mobxjs/mobx#3021]
when i use 
```json
   "mobx": "6.3.2",
    "mobx-react": "7.2.0"
```
it cannot work, CodeSandbox link is https://codesandbox.io/s/crazy-almeida-stgkr
but when i use 
```json
    "mobx": "5.15.7",
    "mobx-react": "6.3.1"
```
it works well, CodeSandbox link is https://codesandbox.io/s/quizzical-khorana-zteht

They have the same code, and the code is referenced to this website https://mobx-react.js.org/recipes-context.

Thanks!

**Comment by iChenLei** [comment]
Missing `makeObservable`, use `makeAutoObservable` is also a solution.
```diff
export class GlobalStore {
+  constructor () {
+    makeObservable(this);
+ }
```
Look more detail for mobx6 changlog https://github.com/mobxjs/mobx/blob/main/packages/mobx/CHANGELOG.md#600

**Comment by yyzclyang** [comment]
> Missing `makeObservable`, use `makeAutoObservable` is also a solution.
> 
> ```diff
> export class GlobalStore {
> +  constructor () {
> +    makeObservable(this);
> + }
> ```
> 
> Look more detail via mobx6 changlog https://github.com/mobxjs/mobx/blob/main/packages/mobx/CHANGELOG.md#600

thank you!
