### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by hidaytrahman** [mobxjs/mobx#3023]
**Intended outcome:**
It should access the property

I have a property called `todos` of array type. I have created a function that will manipulate the `todos` like `push() pop() splice()`.
I am using splice() to delete an item from the `todos` array.

**Actual outcome:**
But it says
TypeError: Cannot read property 'todos' of undefined

**How to reproduce the issue:**
- create a class-based store, add a property of array format, or assign a blank array.
- create a method that will access the array and manipulate by array methods
- call `makeAutoObservable`  in the constructor and pass `this` as an argument
- create a context with the store and use it as a custom hook to be accessible in all components
- use it in react functional component by using hooks
- try to use `observer` from `mobx-react-lite`
- call the method at onClick event

**Versions**
```
     "mobx": "^6.3.2",
    "mobx-react": "^7.2.0",
    "node-sass": "4.14.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.8.1",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
```

**Store**
```
import { makeAutoObservable } from "mobx";

class todoStore {
    todos = [];

    constructor() {
        makeAutoObservable(this)
    }

   // this function working fine with another component with same code 
    addTodo(todoData) {
        this.todos.push(todoData)
    }

    deleteTodo(index) {
       console.log('  this.todos  ', this.todos );
    }
}

export default todoStore;
```

**Comment by iChenLei** [comment]
Missing `autoBind` options ?
> https://mobx.js.org/actions.html#actionbound

**Comment by hidaytrahman** [comment]
I don't know why this [project](https://github.com/hidaytraj/react-mobx-starter) is working fine without `autoBind`

**Comment by iChenLei** [comment]
```js
// access the note store action adding note to the notes array
  noteStore.addNote(note);
};
```
This usage is correct, `this` is direction to `noteStore`. 
Look for more `this` detail -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

**Comment by hidaytrahman** [comment]
what is the difference `noteStore.addNote(note);` and `noteStore.deleteTodo(index)` ?

**Comment by iChenLei** [comment]
Share a online reproduce link(codesandbox, stackblitz etc) is better for discussion, thanks.

**Comment by hidaytrahman** [comment]
@iChenLei somehow it's working fine now and I did nothing :(
Hope next time I wouldn't face the issue.
