### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [mobxjs/mobx#3024]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by mweststrate** [comment]
Feel free to ping me at my Twitter handle @mweststrate

**Comment by mweststrate** [comment]
Closing since nothing was reported.

**Comment by JamieSlome** [comment]
@mweststrate - it is because we wait for the SECURITY.md to be created, then we can send the report over.

**Comment by mweststrate** [comment]
> Feel free to ping me at my Twitter handle @mweststrate

..or feel free to grab my mail from the commits, or just open an issue / PR instead? I won't be putting a personal mail address in a public markdown file though, I get enough spam as it is :)

**Comment by mweststrate** [comment]
See https://github.com/mobxjs/mobx/blob/main/SECURITY.md
