### ISSUE TITLE
Array.replace doesn't run reaction?

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#303]
I don't know if this is classed as a bug or not, but it's best shown through example. See here:
http://codepen.io/jamiewinder/pen/RaqRNK?editors=1010

You should see numbers counting up. If you uncomment line 14 and comment line 15 (i.e. replace the array rather than reassign it), it won't work any more. Is this to be expected?

**Comment by gpfunk** [comment]
what browser are using? Seems to work fine for me on Chrome version 50.0.2661.102

**Comment by jamiewinder** [comment]
Same... and yes, it does appear to work at the moment! I did refactor the example after I'd confirm I'd replicated the real problem, so maybe I fixed it! I'm not really sure. I'll reopen if I manage to figure it out.... Sorry about that!
