### ISSUE TITLE
Array item access with optional chaining causes: "[mobx] Out of bounds read: 0"

### ISSUE THREAD

**Issue by Obiwarn** [mobxjs/mobx#3035]
Reproduce with:

```
  class Foo {
    arr = [];

    constructor() {
      makeAutoObservable(this);
    }
  }

  const myFoo = new Foo();
  console.log(myFoo.arr?.[0]);
```

**Comment by mweststrate** [comment]
Working as intended. The read _is_ out of bounds. Instead guard your access with a length check.

**Comment by urugator** [comment]
Don't you mean `myFoo.arr[0]?.something` ? In your example, you're conditioning the existence of the `arr` property, not the existence of the index.

**Comment by urugator** [comment]
it's simply `myFoo.arr != null ? myFoo.arr[0] : undefined`

**Comment by Obiwarn** [comment]
Sorry my fault. I am coming from other language where index out of bounds throws.

Thank you both for clearing this up.
