### ISSUE TITLE
[ComputedValue] It is not allowed to assign new values to computed properties [React Native, iOS 8]

### ISSUE THREAD

**Issue by aksonov** [mobxjs/mobx#306]
I'm not changing any computed property. No exception for iOS 9, but only iOS 8. Problem happens during intensive load of messages during React rendering with that computed value (i.e. computed property is constantly changed because observable data is changed)

![simulator screen shot 06 jun 2016 17 25 26](https://cloud.githubusercontent.com/assets/1321329/15827562/e7685c8e-2c0b-11e6-8bb7-cc5b8665086d.png)

**Comment by mweststrate** [comment]
Could you also include all console output?

**Comment by aksonov** [comment]
I don't see any logging within console. If you meant full error stack trace, it is very very long and i don't see how to get it as text, i can't cut & paste from that screen... Here is beginning
![simulator screen shot 07 jun 2016 17 32 54](https://cloud.githubusercontent.com/assets/1321329/15864090/e98d4482-2cd5-11e6-8e25-4432ee257d7b.png)

**Comment by mweststrate** [comment]
Could you check whether MobX 2.3 improves this?

**Comment by aksonov** [comment]
Just found that 2.3 brakes @autobind support (with autobind-decorator module)- my app cannot work at all (i.e. `this` is not visible within @action methods). Could you fix it?

**Comment by mweststrate** [comment]
Could you make a reproduction? cannot 100% agree that it is fixable, (I normalized subtle difference between typescript and babel, so I had to find a subset of patterns which is supported by both). 

Not however that autobind is not needed if field initializers are enabled in your babel rc, eg. the following is already bound to this:

`@action myAction = () =>  { }`

**Comment by mweststrate** [comment]
And babel also has a syntax for autobinding, something like `::field`, but I always forget the name :)

**Comment by aksonov** [comment]
With 2.3 i've got error `this.model` is undefined.

```javascript
@autobind
export default class XmppStore {

  @action onConnect(){
    this.model.connected = true;
    this.model.connecting = false;
  }
}
```

**Comment by mweststrate** [comment]
Would it be acceptable for you to write it as `@action onConnect = () => {...`? I think it might relate to the initialization order of the decorators.

**Comment by aksonov** [comment]
@mweststrate It works under iOS 8 now, thanks!!

**Comment by aksonov** [comment]
It is interesting what the reason was...

**Comment by mweststrate** [comment]
I've seen issues in the past that iOS had issues when the decorators where added in a different order then the keys (with the same name) had in the object. Which is like, really, really weird that that has an impact. But in MobX 2.3 the decorators are now on the prototype, which I think circumvents the problem.

**Comment by aksonov** [comment]
i see, thanks for explanation.
