### ISSUE TITLE
Mobx map and integer vs string keys

### ISSUE THREAD

**Issue by daimeng** [mobxjs/mobx#308]
Just noticed something funky with the deletion of numerical keys in map. I will do some more digging and provide some details in a bit, but just posting it here for now.

Basic issue is when you do something like
```
var m = mobx.map()
m.set(1, true) // => "[mobx.map { 1: true }]"
m.delete(1) // => "[mobx.map { }]"

m.set(1, true) // => "[mobx.map { 1: true }]"
m.delete('1') // => "[mobx.map { 1: undefined }]"

m.set(1, true) // => "[mobx.map { 1: true, 1: true }]"
m.delete('1') // => "[mobx.map { 1: undefined, 1: undefined }]"
```
I don't believe this is a huge issue since the map page mentions only Strings accepted as keys. But other values such as booleans seem to properly error.

**Comment by mweststrate** [comment]
All keys are coerced to strings now. Will be released in version 2.3
