### ISSUE TITLE
Passing computed values down as props

### ISSUE THREAD

**Issue by reauv** [mobxjs/mobx#310]
I like HoC, because they make components much easier to test & easier to reason about in my opinion. But I'm running into an issue with MobX and computed values. Right now I have a computed value in my store called `errors`. In my component I use `recompose` to pass the props down to my component from the store like this:
```
export default compose(
  mapProps(() => ({ ...Store, errors: Store.errors })),
  observer,
)(Component);
```
Now because computed values are not enumerable I can't use the spread operator for it so I have to pass them down explicitly. Now all the other observables are correctly being observed in the component, except the errors because it's just a plain object now. 

The workaround is to put `observer` above `mapProps` but that doesn't feel like the correct way because, if I understand MobX correctly, that will cause a re-render no matter what observables are used in my component, because the HoC uses them all.

Am I right about the anti-pattern to put the `observer` above `mapProps` and if so, is there are a better way to go about this?

**Comment by mweststrate** [comment]
I recommend to just past down the store as a whole. This doesn't have any further performance penalties

**Comment by reauv** [comment]
The reason I pass the props down individually instead of the store is not because of the performance but I wanted to be more explicit about which props I pass down so I can use the propTypes evaluation of React. Thanks for your response.
