### ISSUE TITLE
react native and mobx 6.x with TypeScript and Babel recommend options cause network request without any response

### ISSUE THREAD

**Issue by woowalker** [mobxjs/mobx#3100]
**How to reproduce the issue:**
`npx react-native init MyApp --template react-native-template-typescript`
`yarn add mobx mobx-react`
**babel.config.js**
`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      '@babel/plugin-proposal-class-properties',
      {
        loose: false,
      },
    ],
  ],
  assumptions: {
    setPublicClassFields: false,
  },
};`
**tsconfig.json**
`{"compilerOptions": { "useDefineForClassFields": true, ...others }}`
**App.tsx**
![image](https://user-images.githubusercontent.com/7894779/131488059-9de253bc-95f9-43f3-b23b-fdfd76a0a15e.png)
![image](https://user-images.githubusercontent.com/7894779/131488134-01e3f523-e192-4218-9deb-84c5a559c1f1.png)
**get rid off those options**
![image](https://user-images.githubusercontent.com/7894779/131488469-4b1b9efb-a98e-48d5-be2a-fc850f91e267.png)

**Versions**
```json
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "mobx": "^6.3.2",
    "mobx-react": "^7.2.0",
    "react": "17.0.2",
    "react-native": "0.65.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.64.5",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/7894779/131489439-77537a72-5ac3-4645-8707-ebb2062c6152.png)

**Comment by urugator** [comment]
I can't imagine how a compilation of your sources could affect behavior of `React/fetch`, which I assume comes already pre-compiled and therefore is not a subject of your compilation configuration (?).
My first guess would be it has something to do with HMR and the seeming relation with compiler configuration is just a coincidence.
What do you see in the console?

**Comment by woowalker** [comment]
@urugator error like that, but it still appears when i remove the recommend options. 
![image](https://user-images.githubusercontent.com/7894779/131593722-93e3db13-a94a-4f34-90a7-555a42f9a830.png)
and it is very weird that, when i connect to React-Native-Debugger tool and enable network inspect, it works
![image](https://user-images.githubusercontent.com/7894779/131594572-6bcd7fc2-5765-49a8-a5ec-d67f9c6eca69.png)
and my node version: v12.17.0, npm version: 6.14.4
by the way, i use vpn, but when i stop debugging mode, and turn off vpn, i still got nothing response.

**Comment by urugator** [comment]
Ok, so do I understand correctly, it's not related to mobx and therefore the issue can be closed here?

You may want to check:
Original issue: https://github.com/facebook/react-native/issues/26705
Proposed fix: https://github.com/facebook/react-native/pull/31153
Resolution: https://github.com/facebook/react-native/pull/31153#issuecomment-798804020

**Comment by woowalker** [comment]
emmmm, sorry about that, i have searched more before, but still cant find solution, may be its not mobx`s problem, but on new RN project without any packages and options, it work well as expect until add mobx and those recommend option.

and if its only matter of debugger, when i close debugger and even release to apk, it still not work. i am confused.

**Comment by enniel** [comment]
Hi @woowalker! I think finded solution. Add this to babel config:
```js
...
  overrides: [
    {
      test: fileName => !fileName.includes('node_modules'),
      plugins: [[require('@babel/plugin-proposal-class-properties'), { loose: false }]],
    },
  ],
...
```

**Comment by woowalker** [comment]
@enniel seems that the latest RN app without this problem
```json
{
  "name": "myappinit",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "mobx": "^6.3.7",
    "mobx-react": "^7.2.1",
    "react": "17.0.2",
    "react-native": "0.66.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.66.4",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

**Comment by woowalker** [comment]
sorry to reopen this issue, i try my hard, but it still happened. @enniel and sorry, it not work for me. but i found an solution, set babel config to
```
plugins: [
    ...
    ['@babel/plugin-transform-flow-strip-types'], // prevent compile
    ['@babel/plugin-proposal-decorators', { legacy: true }], // must in front of class-properties
    ["@babel/plugin-proposal-class-properties", { loose: true }],
    ...
]
```
it works, and #3102 fast refresh work again.

**Comment by urugator** [comment]
@woowalker could you also try to combine them like this:
```javascript
  overrides: [
    {
      test: fileName => !fileName.includes('node_modules'),
      plugins: [
        ['@babel/plugin-transform-flow-strip-types'],
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['@babel/plugin-proposal-class-properties', { loose: false }],
      ],
    },
  ],
```
and like this:
```javascript
plugins: [
   ['@babel/plugin-transform-flow-strip-types']
],
overrides: [
    {
      test: fileName => !fileName.includes('node_modules'),
      plugins: [
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['@babel/plugin-proposal-class-properties', { loose: false }],
      ],
    },
  ],
```
?

**Comment by RandomToni** [comment]
Hello,

I'm confused, I'm trying to add this configuration but the second I do, I get another issue about "undefined is not an object (evaluating 'props.getItem')". As explained [here](https://github.com/facebook/react-native/issues/24421), this happens by adding ['@babel/plugin-proposal-class-properties', { loose: false }] in plugins or overrides. Also, I'm not sure if I should do a yarn add @babel/plugin-proposal-class-properties or not.

How can I make this work? Thank you

**Comment by siddharth-kt** [comment]
@RandomToni did you got any solution ?

**Comment by RandomToni** [comment]
@siddharth-kt I was having a configuration issue but it really took me a long time to figure it out. I tried many many things, so I'm not able to tell you what really solved the issue. This is my last and working configuration for babel

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          "@components": "./components",
        }
      }
    ],
    ["module:react-native-dotenv", {
      "moduleName": "react-native-dotenv",
      "path": ".env",
      "blacklist": null,
      "whitelist": null,
      "safe": false,
      "allowUndefined": true
    }]
  ]
};

**Comment by siddharth-kt** [comment]
Thanks, as i see you remove "plugins": [["@babel/plugin-proposal-class-properties", { "loose": false }]],
but its mentioned to be implemented in mobx installation docs (https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties).
didn't it caused any issue ? 🤔

**Comment by RandomToni** [comment]
everything has been working without any issues for a while now. A a genereral rule, I always clear the cache between configs changes (react-native start --reset-cache), sometimes it didn't picked up the differences.

**Comment by RandomToni** [comment]
One more thing. That was my config for react-native, for a react project I ended up using
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins":[
    ["@babel/plugin-transform-typescript"],
    ["@babel/plugin-proposal-decorators", { "legacy": true } ],
    ["@babel/plugin-proposal-class-properties", { "loose": true } ],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": true }],
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ["@babel/plugin-transform-flow-strip-types"] // prevent compile
  ]
}

```

**Comment by siddharth-kt** [comment]
@RandomToni yeah its implemented here. 
Thanks for sharing it. 🙂

**Comment by Kawaljeet-AUI** [comment]
Dropping this here just in case you're using Nx, this is the babel config that worked for me:

  ```"presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["react-native-reanimated/plugin"],
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
  ]
}
```
babel version: 7.18.6
