### ISSUE TITLE
cannot read property 'getObservablePropValue' of undefined 

### ISSUE THREAD

**Issue by riminggit** [mobxjs/mobx#3108]
versions:  "mobx": "^6.3.2"
browsers：I don't know，because we have a layer of encapsulation based on  Chrome，but I guess his version is pretty low

This problem occurs in earlier versions of browsers。
I'm sure the current version of the browser can use proxy as well as Symbol。
As well as printing in the source code to make sure it exists。

![image](https://user-images.githubusercontent.com/35957389/133397757-fb187cc6-4997-4bb0-ad13-e54824aab6fe.png)

Minimum emersion ：

import { makeAutoObservable } from 'mobx';
class MyStore {
  constructor() {
    makeAutoObservable(this);
  }
}
const myStore = new MyStore();
export default myStore;

**Comment by mweststrate** [comment]
Closing for the lack of a repro, we can't do anything with reports like this.
