### ISSUE TITLE
FOUT on gh-pages

### ISSUE THREAD

**Issue by prashaantt** [mobxjs/mobx#312]
Each page of the GitBook doc loads with a flash of unstyled text. The CSS looks all right at the top, so I guess it's the GitBook-specific JS towards the end. Please consider fixing this for a smooth document-reading experience.

**Comment by mweststrate** [comment]
Just upgraded to the latest gitbook, hopefully it fixes things.

**Comment by prashaantt** [comment]
Yes it does, thanks!
