### ISSUE TITLE
A transaction of actions?

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#314]
Is there any benefits to using `@action`s if they're called within a `@transaction`? I find myself doing this sometimes:

```typescript
@action('Set A')
public setA(a) {
    ...
}

@action('Set B')
public setB(b) {
    ...
}

// (elsewhere)

setAandB(a, b) {
    transaction(() => {
        setA(a);
        setB(b);
    });
}
```
For example, if anything were to go wrong as a result of changes in `setA` or `setB`, then would these be traced back to those actions, or would the transaction make this impossible?

**Comment by mattruby** [comment]
It would be useful if you use run mobx in strict mode: mobx.useStrict(true)
If you never hit setA or B direct, then there's not much of a reason.  I
really like the logging in the mobx-react devtools with named actions.
I've been leaning on those in place of transaction whenever possible.

On Fri, Jun 10, 2016 at 2:31 PM, jamiewinder <notifications@github.com>
wrote:

> Is there any benefits to using @actions if they're called within a
> @transaction? I find myself doing this sometimes:
>
> @action('Set A')
> public setA(a) {
>     ...
> }
>
> @action('Set B')
> public setB(b) {
>     ...
> }
> // (elsewhere)
>
> setAandB(a, b) {
>     transaction(() => {
>         setA(a);
>         setB(b);
>     });
> }
>
> For example, if anything were to go wrong as a result of changes in setA
> or setB, then would these be traced back to those actions, or would the
> transaction make this impossible?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mobxjs/mobx/issues/314>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAIrcmN6R2U4NNUCaR2pPXh9AlApC99_ks5qKbt1gaJpZM4IzQY1>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by mweststrate** [comment]
Closing as the question seems answered. If not, feel free to reopen
