### ISSUE TITLE
`makeAutoObservable()` not work

### ISSUE THREAD

**Issue by kerryChen95** [mobxjs/mobx#3156]
**Intended outcome:**

Output in console:
```
Foo
Bar
```

**Actual outcome:**

Output in console:
```
Foo
```

**How to reproduce the issue:**

```javascript
/*
Code example from https://mobx.js.org/understanding-reactivity.html

Expect output:
Foo
Bar

In fact output:
Foo

[NOTICE]
Replace `makeAutoObservable()` with `makeObservable()`, all work as expected.
Refer: https://codesandbox.io/s/react-mobx-demo-zo59n?file=/mobx/reactions/what_to_react.js
*/
const { makeAutoObservable, autorun } = require('mobx')

class Message {
  // All own properties become observable.
  title
  author
  likes
  constructor(title, author, likes) {
    // https://mobx.js.org/observable-state.html#makeautoobservable
    makeAutoObservable(this)
    this.title = title
    this.author = author
    this.likes = likes
  }
  // All functions on prototype become autoAction.
  updateTitle(title) {
    this.title = title
  }
}

let message = new Message('Foo', { name: 'Michel' }, ['Joe', 'Sara'])

autorun(() => {
  // Track the access to `title` from `message` object
  console.log(message.title)
})
message.updateTitle('Bar')
```

**Versions**

mobx@6.3.0

**[runnable code](https://codesandbox.io/s/react-mobx-demo-zo59n?file=/mobx/observable_state/makeAutoObservable_not_work.js)**

To see output in console, must switch to current module view and then refresh the preview page.

![image](https://user-images.githubusercontent.com/1589388/138241405-cc658847-e859-4a6a-b4e1-a8233d8a0b5f.png)

**Comment by ch41** [comment]
It's typescript related.

**Comment by mweststrate** [comment]
Please read the docs. They include typescript instructions: https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties
