### ISSUE TITLE
Feature `whyRun`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#316]
So far I have the impression that the devtools and stacktraces in MobX help a great deal with answering the question: "Why does this computation run?".

However answering the question "Why doesn't it run?" is a lot harder and often consists of investigating whether all used values are actually observable.

So I propose a new feature, `mobx.whyRun(thing?, property?)`:
* without arguments you can use it inside a computed value, `render` method or autorun and give you info about why the thing is currently running, and what would trigger it to run the next time
* if `thing` (a Reaction / ComputedValue object) or `thing`, `property` (a computed property of an object) are provided, it will tell what observables would cause the designated thing to re-run.

So `whyRun()` can tell things like
* Running because the reaction is created, because a computed value is peeked into, because another derivation needs it, or because some of the observables used by it have changed
* Which observables it will react to (so far). If this list is empty for example, you know it won't re-run at all in the future.

**Comment by mattruby** [comment]
That sounds pretty helpful to me.  I could have used that while digging
into why autorun wasn't firing with my react render.
