### ISSUE TITLE
Provide an example with form validation

### ISSUE THREAD

**Issue by jgamedev** [mobxjs/mobx#318]
Forms and form validation are some of the most common elements in web apps.

It would be very useful to have an example with this use case.

**Comment by mweststrate** [comment]
Probably deserves an own doc page or package, but it should be pretty straightforward to roll your own, like done for example in this fiddle: https://jsfiddle.net/royriojas/qp5p33cn/

**Comment by jgamedev** [comment]
:gratitude:

**Comment by mweststrate** [comment]
Added the above link to #104. If somebody builds a ready to use abstraction, welcome :). Closing this issue for now

**Comment by foxhound87** [comment]
I updated the jsfiddle with json-schema validation with automatic messages:
https://github.com/foxhound87/mobx-ajv-form
