### ISSUE TITLE
Pull Request template is outdated

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx#3181]
Here is the current PR template:

![image](https://user-images.githubusercontent.com/22447849/141103074-cf8d633f-8a66-4aa9-b5be-84d5f7b4b610.png)

I seems like there is no `npm run perf` script anymore. Also I had to use `yarn` instead of `npm` in order to set up the project locally. Should the third step of this template be updated to `yarn mobx test:performance` ?

**Comment by mweststrate** [comment]
that sounds correct indeed!
