### ISSUE TITLE
Rebuild learn.knockoutjs.com with mobx

### ISSUE THREAD

**Issue by benjamingr** [mobxjs/mobx#319]
Hey, first of all kudos for the library.

One of the things that helped a lot of people learn how to use KnockoutJS was learn.knockoutjs.com - since Mobx is very similar to Knockout in many regards - I think it might be really useful.

Is this something you'd be interested in? If you don't want to develop it - would PRs be entertained?

**Comment by mweststrate** [comment]
Sounds like a cool idea! Feel free to create something similar and submit a PR against the `gh-pages` branch :)

**Comment by keuller** [comment]
@benjamingr Great initiative. I would like to help you with.

**Comment by mweststrate** [comment]
Closing issue. But PR is still welcome ;-)
