### ISSUE TITLE
mobxjs.com vs mobx.js.org documentation domains?

### ISSUE THREAD

**Issue by kevzettler** [mobxjs/mobx#3191]
I'm confused what the difference between the docs hosted at mobxjs.com vs mobx.js.org What is the source of truth? mobxjs.com seems to be outdated but seems preferred by search engines

**Comment by iChenLei** [comment]
https://mobx.js.org

**Comment by mweststrate** [comment]
Yes mobxjs is outdated, I tried to contact the owners but without success.
