### ISSUE TITLE
@observable asStructure

### ISSUE THREAD

**Issue by liron00** [mobxjs/mobx#320]
Inside an ES6 class definition, is it possible to do something like `@observable x = asStructure([2, 3])`?

**Comment by mweststrate** [comment]
@liron00 yes that is valid. the `asStructure` should be sticky (meaning that you shouldn't need to pass it on subsequent assignments, ( but there is a bug about that where this doesn't happen in all cases, see: #197 )

**Comment by liron00** [comment]
Ah ok that was basically my issue (plus I think this syntax isn't in the docs).

**Comment by mweststrate** [comment]
Updated!
