### ISSUE TITLE
Mobx-react observer() wrapped components break babel component transforms.

### ISSUE THREAD

**Issue by pnegahdar** [mobxjs/mobx#3206]
**Summary**: Using babel react transforms like [styled components babel](https://styled-components.com/docs/tooling#babel-plugin) and [fullstorydev/fullstory-babel-plugin-annotate-react ](https://github.com/fullstorydev/fullstory-babel-plugin-annotate-react) fail on components wrapped in `observer()`

**Intended outcome**: Displaynames and other attributes set by babel transforms to hold

**Actual outcome**: observer() wrapped components are usually not respected by those libraries. Not sure if it is a mobx-react issue or if I should dig into their respective libraries. 

**How to reproduce the issue**: Any typical webpack/babel/react project wont work with those plugins when observer() is enabled. 

Is this issue better raised with those plugins themselves or is there a common issue here with the way mobx-react wraps things?

**Comment by urugator** [comment]
Dunno how these transformers work, but I can tell you how the `observer` works:

`observer(fn)` returns a new function that calls the original `fn`. Properties defined on `fn` are copied to the returned function (hoisted).

Setting `displayName` on the returned function is not possible due to #2721
