### ISSUE TITLE
@observable doesn't add the prop to the object

### ISSUE THREAD

**Issue by dacz** [mobxjs/mobx#324]
Constructor
```javascript
export default class Store {
  transportLayer;
  @observable items = [];
  someProp = '';

  constructor({ transportLayer }) {
    this.transportLayer = transportLayer;
  }
}
```
When new Store is created, it has not the `items` prop initialized to observable array. It has someProp properly initialized as a empty string. Every `@observable` property has the same behaviour (not only array).

I'd like that prop `items` should be created on new object and observable.

Latest mobx.

I'm using AVA test runner with settings in package.json:
```
"ava": {
    "files": [
      "test/**/test-*.js"
    ],
    "require": "babel-register",
    "babel": {
      "babelrc": true
    }
  },
```

my .babelrc:
```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-object-rest-spread"
  ]
}
```
I am using examples from https://mobxjs.github.io/mobx/best/store.html

**Comment by mweststrate** [comment]
@dacz could you elaborate on this one? if you do `store.items` you should get back the observable array. It is correct that the property itself is not defined on the instances any more but on the prototype instead (this saves lot's of memory as it is no longer needed to duplicate all prop descriptors over all instances) but the values returned by the property are still per instance

**Comment by dacz** [comment]
@mweststrate I inspected the returned object and it was missing. I inspected because I got the error when using autorun within constructor:

```javascript
constructor({ transportLayer }) {
    this.transportLayer = transportLayer;

    this.fetchItemsHandler = autorun(() => {
      const recordsToFetch = this.items
        .filter(a => a.status === 'requestFetch')
        .map(r => r.data._id);
      if (this.autoSave) {
        this.store.transportLayer.fetchRecordsFromServer(recordsToFetch);
      }
    });
  }
```
Error was:
```
[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These methods should never throw exceptions as MobX will usually not be able to recover from them. Please enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'Autorun@1'
```
The thing is that as I tried different things back and forth it started to work (after your reply) and stopped to throw the error. I cannot reproduce it again. 

Thanks for your quick reply and explanation and I apologize myself.

**Comment by mweststrate** [comment]
No problem! I rather have a few bug reports too many than too few :)
