### ISSUE TITLE
Observer hoc not triggering re-render in a circumstances, where one observable references other observable through it's properties

### ISSUE THREAD

**Issue by danierlr** [mobxjs/mobx#3246]
The Mobx object is created in a way like this:

```
const turnIntoObservable = (node: Node) => {
  const children = node.children.map((child) => turnIntoObservable(child));

  let observableNode: Node = { ...node, children };

  // i'm trying to make observable not all, but only some specific properties
  observableNode = makeObservable(observableNode, {
    expanded: true,
    children: observable.shallow
  });

  return observableNode;
};

let rootNodes: Node[] = ...

rootNodes = rootNodes.map((node) => turnIntoObservable(node));
```

And later the rootNodes is used to render some folder structure, but updating a observable, that is not a root observable does not cause re-render.

There is also related SO quastion: https://stackoverflow.com/questions/70568283/why-mobx-observer-is-not-triggering-react-component-re-render

**Intended outcome:**

Component re-render is expected be triggered, when updating the the Mobx proxy object.

**Actual outcome:**

Component re-render is not triggered

**How to reproduce the issue:**

Here is full demo with steps to reproduce: https://codesandbox.io/s/react-mobx-not-triggering-rerender-3w0bq

**Versions**

"mobx": "6.3.10",
"mobx-react-lite": "3.2.3",
"react": "17.0.2",
"react-dom": "17.0.2",

**Comment by urugator** [comment]
You're in luck, I've actually answered exactly the same issue in the past:
Notice you're exporting `observer(NodeView)`, but the `NodeView` used in render isn't the exported one - it's not `observer`.
So you can eg just move the `observer` from export to definition: 
```javascript
const NodeView = observer(/**/);
export NodeView;
```

Btw don't use `memo` on `observer`, `observer` does that already for you.

**Comment by danierlr** [comment]
@urugator Thank you so much. It was a really dumb mistake.

**Comment by urugator** [comment]
Np, consider using [`configure({ observableRequiresReaction: true })`](https://mobx.js.org/configuration.html#observablerequiresreaction-boolean)
