### ISSUE TITLE
Naming ObservableMap

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#325]
I seem to be obsessed with naming things! 

At the moment, you can create an ObservableMap using `map()` and the name will default to 'ObservableMap@xxx'. When you examine things in the DevTools, it's impossible to know what is what when you model is very complex. I gather you can set the `name` property after creation, but it'd be nice to be able to do so on creation.

Is there anything to be said for allowing a name to be specified in the `map` function in a similar to how you can with `action`, `autorun`, etc.? Would there be other parts of the API where this could also be applied?

EDIT: Sorry if I seem borderline obsessive about this, but perhaps naming `computed` expressions too? It's nice that you used a named function, but we all love our lambdas these days. I've only just started using the DevTools and it's becoming apparent how useful being able to identify your data can be!

**Comment by mweststrate** [comment]
From MobX 3 onward you can do `observable.map(values, name)`, which should fix this issue.

Closing this issue as mobx@3.0.0-rc.1 is now available, which addresses this issue. Changelog: https://github.com/mobxjs/mobx/blob/mobx3/CHANGELOG.md#300. The changes in more details: https://github.com/mobxjs/mobx/pull/725/files. Feel free to re-open if questions arise!
