### ISSUE TITLE
mobx-react-lite `observer(Component, {forwardRef: true})` doesn't seem to work

### ISSUE THREAD

**Issue by bradleygore** [mobxjs/mobx#3267]
**Intended outcome:**

Expected to be able to render a component that is exported as `observer(Component, {forwardRef: true})`

**Actual outcome:**

Get error:
<img width="596" alt="Screen Shot 2022-01-18 at 1 49 24 PM" src="https://user-images.githubusercontent.com/5077928/150009748-f184e545-917d-4683-b54a-07f2310fd3bf.png">

**How to reproduce the issue:**

Make a component that uses `React.forwardRef`, then export that component as `export default observer(Component, {forwardRef: true});`.

There is an issue that seems to be related, and I went by this comment in that thread to try the `{forwardRef: true}` option:
https://github.com/mobxjs/mobx/issues/2527#issuecomment-704860034

However, that doesn't seem to work b/c the ref-forwarding component is an object and not a function:
<img width="1105" alt="Screen Shot 2022-01-18 at 1 56 39 PM" src="https://user-images.githubusercontent.com/5077928/150010073-ce53fba7-a853-4482-8a60-18bc0ba9589b.png">

Am I using this incorrectly, or should I just use `mobx-react`? I had been using `mobx-react` but we only use functional components so figured I'd switch to `mobx-react-lite` to get the smaller bundle.

**Versions**

- mobx-react-lite@3.2.3
- react@17.0.2

Thanks in advance 😄

**Comment by urugator** [comment]
> Make a component that uses React.forwardRef, then export that component as export default observer(Component, {forwardRef: true});.

You shouldn't wrap the component with `React.forwardRef` prior passing it to `lite`'s `observer`, the `forwardRef: true` wraps the component for you. This is different from `mobx-react`, that detects the component is already wrapped and rewraps the component. I will investigate if we can somehow improve this or at least throw a sensible error.

**Comment by bradleygore** [comment]
@urugator - oh, interesting. I did not realize this. Is this in the docs somewhere - my apologies if I overlooked that. Thank you for the explanation!
