### ISSUE TITLE
runInAction reading undefined when spy enabled

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx#327]
I'm using runInAction like:
```
runInAction('update due date', () => {
    this.dueDate = moment(new Date(year, month, day))
})
```

[here](https://github.com/mobxjs/mobx/blob/a682eb674bbfafc83eacb3b4840b193c867687b9/src/core/action.ts#L88) I'm getting `Cannot read property 'length' of undefined`

Which comes from [here](https://github.com/mobxjs/mobx/blob/a682eb674bbfafc83eacb3b4840b193c867687b9/src/core/action.ts#L65)

**Comment by mweststrate** [comment]
Just released 2.3.1 which fixes this issue. Thanks for reporting!

Op wo 15 jun. 2016 om 11:51 schreef Vojtech Novak <notifications@github.com
