### ISSUE TITLE
mobx throws errors whenever `[Symbol.iterator]` is non-writable

### ISSUE THREAD

**Issue by eligrey** [mobxjs/mobx#3272]
Some JavaScript environments lock all built-in iterators, making them non-writable. This causes mobx to throw errors at [this line of code](https://github.com/mobxjs/mobx/blob/72d06f8cd2519ce4dbfb807bc13556ca35866690/packages/mobx/src/utils/iterable.ts#L2).

There are multiple ways for you to fix this issue:

- Wrap the line with `if (!iterator[Symbol.iterator]) { … }` (i.e. don't overwrite `iterator[Symbol.iterator]` if it already exists)
- Wrap the line in a `try..catch` statement
- Check if the property is writable before attempting to write: `if (!iterator[Symbol.iterator] || Object.getOwnPropertyDescriptor(iterator, Symbol.iterator).writable) { … }`

**Comment by urugator** [comment]
May I ask which JS environment? It's only called on plain object, which [shouldn't be iterable](https://exploringjs.com/es6/ch_iteration.html#sec_plain-objects-not-iterable).

**Comment by eligrey** [comment]
I may have been mistaken as to where the error was originating from. It looks like the issue is actually here: https://github.com/mobxjs/mobx/blob/72d06f8cd2519ce4dbfb807bc13556ca35866690/packages/mobx/src/types/legacyobservablearray.ts#L83-L94

Honestly I'm not fully sure why this is happening. I can make a testcase page for you later to help with debugging.

> May I ask which JS environment?

It's a normal browser JS environment, except with most well known builtin iterators 'locked' with logic similar to this: https://gist.github.com/eligrey/c5a252f1f48cbdd8bf2b344b4ddaea65

**Comment by urugator** [comment]
What traspiler/configuration do you use? The assigment is suspicious, if prop is non-writable on proto, it can't be introduced on child by assigment, only by `defineProperty`.

**Comment by eligrey** [comment]
Sorry, this was happening in a third-party JS bundle on a site I have no control over or insight into. From my light review of your source I don't see anything wrong with this code so I'm going to close this issue.

Oddly enough, while this bug occurs in both Firefox and Chrome, it can't be reproduced in the devtools console in Chrome even with an exact breakpoint.
