### ISSUE TITLE
Containment checks on observable sets for non-observable values give unexpected results

### ISSUE THREAD

**Issue by guludo** [mobxjs/mobx#3277]
Hi there,

When we add a non-observable object `o` to an observable set `s` (i.e. `s.add(o)`), checking for containment with `s.has(o)` does not produce the desired outcome. I suspect that `s.add(o)` stores an observable version of `o` instead of the original object and that causes the issue.

I worked around that by wrapping each object of my list with `observable`, but I believe it would be nice/cleaner if observable sets allowed to check for containment with the original objects. I wonder if the same kind of issue is possible with observable maps as well.

**Intended outcome:**

I expected `s.has(o)` to be `true`.

**Actual outcome:**
`s.has(o)` returned `false`.

**How to reproduce the issue:**

The following code reproduces the issue. The call `a.hasValue(obj)` returns `false` instead of `true`.

```javascript
const mobx = require('mobx')

class A {
  constructor() {
    this.x = new Set()
    mobx.makeAutoObservable(this)
  }

  addValue(v) {
    this.x.add(v)
  }

  hasValue(v) {
    return this.x.has(v)
  }
}


const a = new A()
const obj = {}
a.addValue(obj)
console.log(a.hasValue(obj))
```

**Versions**
MobX version: 6.3.5

**Comment by iChenLei** [comment]
```diff
constructor() {
+ mobx.makeAutoObservable(this)
   this.x = new Set()
- mobx.makeAutoObservable(this)
}
```
<details>
<summary>Click to look screenshot from runkit !</summary>
<img src="https://user-images.githubusercontent.com/14012511/151359425-932a19e2-efa9-4410-8553-21076b9aee4c.png" width="700px" />
</details>

**Comment by urugator** [comment]
The `Set` becomes deeply observable, meaning if you add a new object/array as value, its converted to observable as well, copying the value in the process - so the obj inside the Set is an observable copy of the original.

**Comment by mweststrate** [comment]
See the observable.shallow options in the documentation, if you don't want
contents of a collection to be convertible automatically.

**Comment by urugator** [comment]
> I suspect that s.add(o) stores an observable version of o instead of the original object and that causes the issue.

Yes

>  but I believe it would be nice/cleaner if observable sets allowed to check for containment with the original objects.

You can create `shallow` Set:
```javascript
this.x = new Set()
mobx.makeAutoObservable(this, { x: observable.shallow })
// or
this.x = observable(new Set(), { deep: false });
```

**Comment by guludo** [comment]
> The Set becomes deeply observable, meaning if you add a new object/array as value, its converted to observable as well, copying the value in the process - so the obj inside a Set is an observable copy of the original.

I see. Thanks for the explanation. Does this behavior make sense though? I looks to me that adding the same non-observable object twice would end up with two copies being added. From the caller's perspective, it is expected that the object would be added only once.

**Comment by guludo** [comment]
@urugator @mweststrate

Cool! 🙂  Thanks for the tip about the `shallow` annotation. I'll use that in my code.

However, I still question if it does make sense sets copying added values.

**Comment by urugator** [comment]
You have to think about from where the object comes from. If it's already part of the state, then it's already observable, therefore no conversion, no cloning. If it's not, you usually want the object to become part of the state and therefore observable and then work with it.  The auto-conversion on assigment/set can be suprising, but convinient. The alternative means you would be constantly wondering, why your object isn't observable, because you forget to `observable(obj)` somewhere.

**Comment by guludo** [comment]
Okay. Thanks for the clarifications! I'll close this now.
