### ISSUE TITLE
Removing `any` types from `replace` and `merge` methods

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx#3286]
### Discussed in https://github.com/mobxjs/mobx/discussions/3285

<div type='discussions-op-text'>

<sup>Originally posted by **Nokel81** February  9, 2022</sup>
The current typings for `ObservableMap<K, V>` include the following method:

```
replace(values: ObservableMap<K, V> | IKeyValueMap<V> | any): ObservableMap<K, V>;
```

I would love to see that `| any` removed, what could I do to help with that? Including for `ObservableSet` and `ObservableArray`.

I know that, for instance, also `[K, V][]` is an acceptable type for `values` since I use it a lot.</div>

**Comment by kubk** [comment]
Hi @Nokel81
Thank you for spotting this. The last time this line has been changed was 4 years ago: https://github.com/mobxjs/mobx/blame/main/packages/mobx/src/types/observablemap.ts#L309

Related PR: https://github.com/mobxjs/mobx/pull/800/files

I think we should we fix it, despite it will be a BC break. @urugator Thoughts?

**Comment by urugator** [comment]
Agree. Probably should be just `IObservableMapInitialValues`.
