### ISSUE TITLE
Cannot redefine property: __mobxLazyInitializers with HMR

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx#329]
Hello,
I'm using latest mobx in a react native app and when the hot reloading feature is turned on, every now and then I get an error. It seems that it's happening with components that have something observable in them.

When running in debug mode (i.e. the app runs in chrome's V8), the error is caught [here in react-proxy](https://github.com/gaearon/react-proxy/blob/13f076b17b43a9d53c151931f3629ef1baae42e5/src/createPrototypeProxy.js#L71) with the following error messsage: `Cannot redefine property: __mobxLazyInitializers`.

When the app runs on device (i.e. using JavaScriptCore), I get `Attempting to change a value of a readonly property`. 

I'm using babel. 
Any thoughts?

Thanks!

**Comment by mweststrate** [comment]
yes, I can mark the property as being configurable. I'm not sure what the impact of HMR is on redecorating classes, but at least that should get you one step further.

**Comment by vonovak** [comment]
@mweststrate that would be great, thanks

**Comment by luisrudge** [comment]
I'm having this issue too, but I'm not using react-native. Just the browser

**Comment by vonovak** [comment]
@mweststrate I tried setting `configurable` and `writable` to true but no luck :/ I get another error in `react-proxy` [here](https://github.com/gaearon/react-proxy/blob/13f076b17b43a9d53c151931f3629ef1baae42e5/src/deleteUnknownAutoBindMethods.js#L31) cannot read length of undefined.. Any ideas on how to go further?

**Comment by mweststrate** [comment]
Are you guys using react-hot-loader? If I remember correctly decorators are only supported from 3.0.0 upward. "react-hot-loader": "^3.0.0-beta.2". See also http://mobxjs.github.io/mobx/best/stateless-HMR.html

**Comment by vonovak** [comment]
annotations - that was it

**Comment by MovingGifts** [comment]
@vonovak I get the same error. What do you mean annotations was the issue? Still trying to resolve it.

**Comment by vonovak** [comment]
annotations = decorators, so instead of `@observable count = 1` you use `var count = observable(1)`

**Comment by MovingGifts** [comment]
@vonovak Thank you, will check it out!
@mweststrate Hello, first of all, amazing work on mobX and thank you very much for making it! Regarding this error, I don't have react-hot-loader as a package, but I think it's just part of RN. I did a search through the entire RN app and didn't find react-hot-reloader, since you stated that "react-hot-loader": "^3.0.0-beta.2" should support the decorators without that error. I honestly prefer the decorator syntax, but any idea how to get the decorators to work and not get that error?

**Comment by vonovak** [comment]
@MovingGifts I dont think that Mobx can influence this, the issue about not supporting decorators is within react hot reloader implemented in the RN packager, which is probably based on webpack HMR [source](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html)

**Comment by MovingGifts** [comment]
@vonovak Got it, thanks :)

**Comment by MovingGifts** [comment]
I ended up cmd+d in the simulator, and hit Disable Hot Reload, while keeping Live Reload Enabled, which worked for me with the decorators intact, so unless you need Hot Reloading, give it a shot :)
