### ISSUE TITLE
Semver in mobx

### ISSUE THREAD

**Issue by billyjanitsch** [mobxjs/mobx#330]
Hi!

I just wanted to point out that the 2.3.0 release (specifically, the rewrite of `reaction` semantics) broke [semver](http://semver.org/). A minor version bump (i.e. 2.2.2 -> 2.3.0) shouldn't introduce backwards-incompatible changes. In this case, an app written with the old semantics may require changes to work with the new ones, so this change should have resulted in a major version bump (3.0.0).

Following semver is helpful because most devs specify dependencies using caret syntax (e.g. ^2.2.0, which matches >= 2.2.0 < 3.0.0). `npm install --save` does this by default. The idea of ^V is to match anything *compatible with V* (i.e. backwards-compatible bugfixes and new features), so if your tests pass with V, then they should pass with ^V.

Sorry if you already know this; I don't mean to come across as patronizing. Just a friendly reminder for next time! 🐹

**Comment by mweststrate** [comment]
No problem! This is my first large scale OSS project so I'm learning as well :)

I doubted about whether this change was breaking or not, as the docs already suggested this behavior (as pointed out in the related issue), so it was disputable whether this was actually a bug fix or breaking change (or both). I checked with some people whether it would give issues and that didn't seem to be the case. But maybe I should have stayed on the safer side here, warned by the fact that I took the effort to check this with others in the first place (and throw away a bunch of deprecated api's while at it :-P)

**Comment by billyjanitsch** [comment]
Good point -- I didn't realize that the docs pointed towards the new semantics. In this sort of case, I think the preferred approach might be to change the docs to align with the old semantics, and then change them back for the major version. (*Technically* only backwards-compatible bugfixes are allowed in patch versions according to semver, but many/most package maintainers are flexible on this rule.)

In any case, I really appreciate your work on this library! Thanks for putting in the time.
