### ISSUE TITLE
Missing "splice" change type

### ISSUE THREAD

**Issue by robak86** [mobxjs/mobx#3303]
**Intended outcome:**
I should be able to observe arrays for `splice` type change. 

**Actual outcome:**
`IObjectDidChange` type lacks the corresponding type for this kind of change. 

<img width="933" alt="image" src="https://user-images.githubusercontent.com/519239/154704514-c64cde0f-e7a4-40cd-ab20-db85ad9b3b8b.png">

**Versions**
6.4.0

**Related issue**
#3134

**Comment by urugator** [comment]
Thanks for the report.
