### ISSUE TITLE
Error: [mobx] @action fields are not reassignable while using multiple inheritance

### ISSUE THREAD

**Issue by jsgiant** [mobxjs/mobx#3318]
When I try to override the methods of base class in the superclass, I'm facing an error `Error: [mobx] @action fields are not reassignable`

Have a look at the code below

```
abstract class A{
   @observable value

   @action.bound
   method1(){
        doWorkInA()
    }
}
```

```
class B extends A{
   @observable valueInB

   @action.bound
   method2(){
        doWorkInB() 
    }
}
```

```
class C extends B{
   @observable valueInC

   @action.bound
   method1(){
        doWorkInC() 
    }
}
```

NOTE: It is working when I run it on my local dev server but getting the issue when I build the code with TypeScript(`yarn tsc`).

Ours is a giant codebase written with decorators using `v5` of `mobx`, so we're trying to solve this with the same version. Thank you!

**Versions:** 
- mobx - `v5.15.0`
- mobx-react - `v6.1.4`
- typescript: "v4.4.2"

**Comment by mweststrate** [comment]
> NOTE: It is working when I run it on my local dev server but getting the issue when I build the code with TypeScript(yarn tsc).

That sounds like you're not using the same babel or typescript configuration on both cases. Make sure they are the same first. 

After that, did you try using the `override` annotation? See also https://mobx.js.org/subclassing.html#limitations

**Comment by jeremy-coleman** [comment]
Mw, hes using v5, so that should work

jsgiant, are u loading from a cdn without a version?  It seems like youre transpiling your code and not bundling mobx, then the calling app is importing your code combined with mobx6

**Comment by urugator** [comment]
> importing your code combined with mobx6

There is no such error in v6 btw.

**Comment by jeremy-coleman** [comment]
@urugator 
I thought that was introduced in an early version of v6 before override was available? I remember some long issues about it, but maybe my brain is just making things up
