### ISSUE TITLE
[eslint-plugin-mobx] `no-anonymous-observer` rule false positive on arrow functions

### ISSUE THREAD

**Issue by aurora-stian** [mobxjs/mobx#3323]
Regarding https://github.com/mobxjs/mobx/tree/main/packages/eslint-plugin-mobx#mobxno-anonymous-observer rule.

As I have read and adopted from https://github.com/mobxjs/mobx-react-lite/issues/73#issuecomment-470883502, the following should have no problem with `displayName`, but the linter rule still reports a warning:

```js
const Component = (props) => { ... };
export default observer(Component);
```

The above is "option 1" from the link, while `mobx/no-anonymous-observer` rules seem to prefer "option 3".

**Intended outcome:**

Linter rule not flag any warnings for the above snippet ("option 1")

**Actual outcome:**

A warning of `observer component must have a name` flagged on the line of `observer(Component)`

**How to reproduce the issue:**

Use the above snippet, run `eslint`

**Versions**

`"eslint-plugin-mobx": "=0.0.8"`

**Comment by urugator** [comment]
Closing as the rule is now deprecated:
https://github.com/mobxjs/mobx/tree/main/packages/eslint-plugin-mobx#mobxno-anonymous-observer-deprecated
