### ISSUE TITLE
Can observable property depend on computed one?

### ISSUE THREAD

**Issue by SergeyAlexeev** [mobxjs/mobx#3328]
**Intended outcome:**

This is a simple example that demonstrates the issue - https://codesandbox.io/s/zen-stitch-3bp2nd?file=/src/index.js

Here I have three props:

 - **value**(observable)
 - **double**(computed that depends on **value**)
 - **some_observable**(observable that depends on computed **double**)

When I check these fields for the first time everything works as expected. But if I update **value** I will see that **double** is OK, but **some_observable** - isn't. **some_observable** still contains old value.

**Actual outcome:**

I can suggest two ways to make this behaviour consistent.

The first one - initialisation and update should work the same way. I mean **some_observable** should be updated if **double** is changed.

The second one - I should get an exception if observable can't depend on computed. BTW, I would prefer this way.

It makes sense if you have a huge view model that contains a lot of fields. By mistake you can mark some field as **observable** instead of **computed**. In this case debug can take a lot of time.

**How to reproduce the issue:**

Just refer this example https://codesandbox.io/s/zen-stitch-3bp2nd?file=/src/index.js, open console and check the result.

**Versions**

6.3.12

**Comment by mweststrate** [comment]
Yeah, sounds like you should have used a `computed` here indeed. Not much we can do about this, when using the wrong tool from the wrong job :). The computedRequiresReaction` flag (https://mobx.js.org/configuration.html#linting-options) would have warned you in this specific case though: https://codesandbox.io/s/inspiring-resonance-b8qklx?file=/src/index.js

**Comment by SergeyAlexeev** [comment]
Thank you for response! `computedRequiresReaction` looks good for my case)
