### ISSUE TITLE
App broken after upgrading mobx to 2.3.1

### ISSUE THREAD

**Issue by otbe** [mobxjs/mobx#333]
Hi,

after upgrading mobx to 2.3.1 from 2.2.2 my app is somehow broken. Simple ```autorun```s dont work  and components are not reactive anymore. It has been discussed at gitter and this issue should keep attention on this as long as is needed.

Project is at https://github.com/otbe/dwatch/tree/mobx-2.3.1
Just ```npm i``` and ```npm run test```. One test will fail, because it relies heavily on ```autorun()```.

Thanks!

**Comment by mweststrate** [comment]
Hi @otbe 

I am unfamiliar with Karma, can you elaborate how I can use a debugger in your test suite?

**Comment by otbe** [comment]
Change singleRun to false in karma.conf.js, visit http://localhost:<port> (port will be logged) and click "Debug" in the upper right corner. 
But I don't know if this performs very well because it is an electron/node project. Will try it later today. :)

**Comment by andykog** [comment]
Seems, that @otbe problem is not typescript, targeting ES3, but rather `reflect-metadata` that does not returns descritor, if 4th argument is present, but undefined. https://github.com/rbuckton/ReflectDecorators/blob/master/Reflect.js#L562
#343 can fix this, can't find better solution :-/

**Comment by otbe** [comment]
Hi @andykog,

Im not targeting ES3 with TS, but I think you are right. Its a mismatch between TS and ```reflect-metdata```.
```Reflect.decorate``` returns no descriptor if no descriptor was passed in. TS only defines a property if a descriptor was returned. Somehow wired :P
But who's right?

**Comment by andykog** [comment]
I have the same question, didn't find any specification on Reflect.decorate

**Comment by otbe** [comment]
Opened an issue for this https://github.com/Microsoft/TypeScript/issues/9265

**Comment by mweststrate** [comment]
Did somebody check whether #343 fixes the problem? It might be interesting to incorporate the patch in that cases, regardless whether it is TS or Reflect is wrong?

**Comment by andykog** [comment]
I did :-)

**Comment by mweststrate** [comment]
Ok, I think we can leave a big ugly comment pointing to this issue then and (if / as long as) nothing else breaks incorporate it.

**Comment by mweststrate** [comment]
@andykog I just tested the change, but it didn't fix the issue, did  you install it in `app/` in the project?

**Comment by andykog** [comment]
Sorry, I've tested isolated testcase `should persist changes to persistence`, but seems that another one fails now: `should recover settings from persistence if present`
It seems, that decorated properties are staying on the prototype. We used to have special magic that defines them on instance after prototype's getter/setter is called first time I'l find out, why it doesn't work this way tomorrow.

**Comment by andykog** [comment]
Ok, `should recover settings from persistence if present` was ok before #343 because `@observable` decorator didn't work at all.
Now it fails because of relying on properties to be copied with `Object.assign()` here https://github.com/otbe/dwatch/blob/mobx-2.3.1/app/src/stores/SettingsStore.ts#L30
More details: #359

**Comment by mweststrate** [comment]
@andykog @otbe just tested, the code now works as expected, but the test fails because of `deepEqual`. Apparently that compares only the *own* properties and not the inherited ones. In MobX 2.3 observable started to decorate the prototype of objects instead of each individual instance, which is a lot more efficient (and which was undone by #359, hence the difference)

Changing the test to the following works as expected

```javascript
for (var key in settingsMock.connectionSettings) {
      console.log(key, store.connectionSettings[key])
      expect(store.connectionSettings[key]).toBe(settingsMock.connectionSettings[key])
}
```

Not sure yet whether the property ownership should be 'fixed' or not, or optimized in some other way.

**Comment by otbe** [comment]
@mweststrate this fixes the test but app is still broken because you can't do something like [this](https://github.com/otbe/dwatch/blob/mobx-2.3.1/app/src/stores/SettingsStore.ts#L30):

```javascript
class Store {
   @observable cats = 5;
}
var store = new Store();
store.hasOwnProperty('cats'); // returns false
Object.assign({}, store); // returns {}
```

Thats a bit unexpected for me :(

**Comment by mweststrate** [comment]
Released fix as `mobx@2.3.3`, @otbe can you verify this? Thanks!

**Comment by otbe** [comment]
@mweststrate works fine :)

**Comment by asterius1** [comment]
It's still not always working correctly.

```ts
import { action } from "mobx";

function test() {
  class App {
    @action fun = () => {
      "undecorated";
    }
  }
  console.log(Object.getOwnPropertyDescriptor(App.prototype, "fun"))
  const a = new App()
  console.log(a["__mobxInitializedProps"])
  console.log(a.fun.toString());
}

test()
import "reflect-metadata"
test()
```

will return 

```
function () {
        return executeAction(actionName, fn, this, arguments);
    }
function () {
                "undecorated";
            }
```

first run is ok, second not

Looked into it and it looks like [argument length check](https://github.com/mobxjs/mobx/blob/master/src/utils/decorators.ts#L51) is not doing it's job, because `classPropertyDecorator` is [called with 4 arguments](https://github.com/mobxjs/mobx/blob/master/src/utils/decorators.ts#L101) regardless of decorator arguments.

**Comment by farwayer** [comment]
Look like problem is still exists if `--module commonjs` option provided.

```js
import {action} from 'mobx'

class User {
  loginCount = 0;

  @action
  login() {
    this.loginCount++;
  }
}

const user = new User();
user.login();
```

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
exports.__esModule = true;
var mobx_1 = require("mobx");
var User = (function () {
    function User() {
        this.loginCount = 0;
    }
    User.prototype.login = function () {
        this.loginCount++;
    };
    __decorate([
        mobx_1.action
    ], User.prototype, "login");
    return User;
}());
var user = new User();
user.login();
```

```js
/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:991
                Object.defineProperty(target, key, newDescriptor);
                       ^

TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at classPropertyDecorator (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:991:24)
    at /mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1029:64
    at actionName (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1096:43)
    at action (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1075:39)
    at /mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1054:25
    at typescriptInitializeProperty (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1038:5)
    at User.get (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:975:25)
    at Object.<anonymous> (/mnt/data/dev/react/mobx-decorators/test.js:23:5)
```
