### ISSUE TITLE
observable array is not expected 

### ISSUE THREAD

**Issue by hangaoke1** [mobxjs/mobx#3335]
in autorun I used list[1].name，when i change list[0] the autorun execue meaningless

**Intended outcome:**
autorun not execute when list[0] changed

**Actual outcome:**
autorun execute when list[0] changed

**How to reproduce the issue:**
https://codesandbox.io/s/gallant-thompson-87fjnw?file=/src/App.js

**Versions**
6.4.2

**Comment by mweststrate** [comment]
This is working as expected, the entire array counts as a single unit of change, this is to make sure operations like shift, splice, push are as efficient as possible and the underlying idea is that key 0 is not fundamentally then key 16, and items can move arbitrarily. If you want per-entry reactions, use an observable object or map instead, and use indices as keys.
