### ISSUE TITLE
`any` in `ObservableSet` harms type inference

### ISSUE THREAD

**Issue by Nokel81** [mobxjs/mobx#3337]
**Intended outcome:**

I initially reported this https://github.com/microsoft/TypeScript/issues/48293 but was told that because of the `any`'s in `has` and `delete` (and others) it was breaking the type inference.

**Versions**

mobx: 6.3.13

I would be willing to write a PR to remove these though that would technically be a breaking change.

**Comment by mweststrate** [comment]
Feel free to open a PR. Since it is a typing change, not a runtime one, it
is fine for a minor.

**Comment by urugator** [comment]
Released as 6.5.0. Thanks for the report and for PR (@kubk )
