### ISSUE TITLE
flowResult not inferring async generator type 

### ISSUE THREAD

**Issue by xaun** [mobxjs/mobx#3357]
`flowResult` returns `Promise<never>` when wrapping a generator with the signature `<AsyncGenerator<number, number, number>`. Is this a bug/missing feature? 

**Intended outcome:**

Use `flowResult` to wrap an `AsyncGenerator` and get type support.

**Actual outcome:**

The returned type is `Promise<never>` 

**How to reproduce the issue:**

See the `run` function here: https://codesandbox.io/s/minimal-observer-forked-ci11t1?file=/src/store.ts. It's inferred return type is `Promise<never>`, if you remove `async` from `*_run`, the type is correctly `Promise<number>`.

**Versions**

mobx 6

**Comment by kubk** [comment]
I doubt mixing async function with generator is a good idea. Either use flow without `async` keyword or use async / await without generators (with runInAction/action)

**Comment by kubk** [comment]
>  makeAutoObservable(this, { _run: flow });

There is no need to do it. If a class method is a generator function (marked with *), the `makeAutoObsevable` function automatically marks this method as `flow`

**Comment by kubk** [comment]
And since you're using flow with TS (as I do), I am interested in your input here: https://github.com/mobxjs/mobx/discussions/3195

**Comment by xaun** [comment]
> I doubt mixing async function with generator is a good idea. Either use flow without async keyword or use async / await without generators (with runInAction/action)

@kubk right, well yea I was using it to get the type async result lol, and also as wasn't sure if I would always want to `yield` the result of the promise. 

> And since you're using flow with TS (as I do), I am interested in your input here: https://github.com/mobxjs/mobx/discussions/3195

Awesome, love your result helper, yes would be great if this was exported/handled by Mobx. Typically after making an async query you want to continue to operate on the result with type safety.

**Comment by kubk** [comment]
Ok, I am closing the issue then. Regarding the helper - thank you for the answer. Let's wait for other maintainers response in that discussion.
