### ISSUE TITLE
Observed component names show as `Memo(ComponentName)` with mobx-react-lite 3.2.3

### ISSUE THREAD

**Issue by tahme** [mobxjs/mobx#3360]
We have some `enzyme` tests that look up components by name. Upgrading to `mobx-react-lite 3.2.3` breaks tests that use components wrapped with `observer` unless we explicitly give them a `displayName` afterwards.

**Intended outcome:**

Rendered `observer(ComponentName)` shows as `<ComponentName />` in tests.

**Actual outcome:**

Rendered `observer(ComponentName)` shows as `<Memo(ComponentName) />` in tests.

**How to reproduce the issue:**

You can see the behavior changing when you switch between `mobx-react-lite 3.2.3` and `mobx-react-lite 3.2.2` here: https://codesandbox.io/s/recursing-tdd-fke0ok

**Versions**

react 16.14.0
mobx-react 6.1.4
mobx-react-lite 3.2.3

**Comment by urugator** [comment]
It's caused by https://github.com/mobxjs/mobx/pull/3192
The newer behavior is more correct as it matches how react would normally display the component name and allows setting `displayName` for annonymous components.
I realize it's a minor version and it shouldn't break and I apologize for the complications, but I would prefer keeping the change. Would it be feasible to adapt the tests instead?

**Comment by tahme** [comment]
Previously applying `observer` was pretty transparent (except for anonymous functions where you needed to set `displayName` manually). For us this probably means always setting `displayName` manually after applying `observer` so we can't use the `export default observer(ComponentName)` pattern we had in our component files.

I understand that the current behavior matches the internals better but on the other hand I wish internal details were invisible.

Reading the linked PR this seems kinda unavoidable in React 17 for renaming anonymous components to work. We can live with this but were hoping we wouldn't have to.

**Comment by urugator** [comment]
>  so we can't use the export default observer(ComponentName) pattern we had in our component files.

You could use own observer:
```javascript
function observer(cmp) {
  const observerCmp = mobxObserver(cmp);
  if (cmp.name) {
    observerCmp.displayName = cmp.name
  }
  return observerCmp
}
```

> internal details were invisible

Memo on component has implications for it's consumers. From that perspetive it's not just an internal detail and therefore it's possibly interesting/important information for developer when debugging. From time to time an issue pops up where user is surprised/unaware that `observer` applies `memo`. I think it's actually more transparent and developer friendly now.
If all components are memoized and you're used to it, then I understand you could consider it just a visual noise.

**Comment by tahme** [comment]
Thanks, we'll consider your `observer` suggestion.

Btw, is it necessary for `observer` to use `memo` to work properly or is it just a performance optimization?

**Comment by urugator** [comment]
It's an optimization. But mobx as a whole is "just an optimization". By default all you need in react is to call `setState` on root component whenever state mutation occurs. Anything more involved is basically "just an optimization".

Removing memo shouldn't break your app if that's what you're asking.
