### ISSUE TITLE
Warning shown on out of bounds access to observed array with optional syntax.

### ISSUE THREAD

**Issue by stuckj** [mobxjs/mobx#3361]
I don't consider this a HUGE deal since the code still works, but thought I'd report it anyway. And it has a workaround.

**Intended Outcome:**
Use of optional access on an observed array doesn't generate an out of bounds warning from mobx if the index is out of bounds. E.g., `this.arr?.[1]` for an array with only 1 element shouldn't show a warning from mobx since `?` should prevent actual access to the value.

**Actual Outcome:**
We get a mobx warning on optional access.

**Workaround:**
Explicitly check if the index would be valid. E.g., `this.arr.length > 1 ? this.arr[1] : undefined` for the above example.

**How to Reproduce:**
Code sandbox example: https://codesandbox.io/s/mobx-warning-on-optional-nbw50f

Look in the console for the code sandbox and you'll see the mobx warning.

**Versions:**

I tested this on mobx@6.5.0 in the code sandbox (appears to be the latest). I'm guessing it applies to any 6.x version.

**Comment by urugator** [comment]
Please see https://github.com/mobxjs/mobx/issues/3035

**Comment by stuckj** [comment]
I claim temporary insanity. :-P I don't know why I was thinking `?.[0]` does a bounds check rather than just a null check. Closing this.
