### ISSUE TITLE
Mobx action not registering on Object.assign

### ISSUE THREAD

**Issue by Ryan-Zell** [mobxjs/mobx#3365]
**Intended outcome:**

I was looking for an action to fire and mutate an observed hash object.

**Actual outcome:**

When you use Object.assign the mutate does not register with Mobx actions.

**How to reproduce the issue:**

Inside of an observable action fire an action that uses Object.assign to mutate the object variable being observed. Attempt to view this variable inside of a compute after the object is mutated. You will not be able to register the change inside of the function.

**Versions**

Mobx 6

**Comment by FE-Sadhu** [comment]
The `increment` method in this [codesandbox](https://codesandbox.io/s/sad-heisenberg-5fbinn?file=/src/store.js) matches your description?
I try to use `Object.assign` to mutate the observable value then detects ui re-render as normal.
if I misunderstand your description, could u please provide a codesandbox ?
