### ISSUE TITLE
Suspend computed values that are not observed by anything.

### ISSUE THREAD

**Issue by steveruizok** [mobxjs/mobx#3367]
**Intended outcome:**  If computed values are not observed by anything, they should suspend entirely. Computed values without observers should cache and return their initial value until an observer is added.

**Actual outcome:** Computed values do not begin caching until observers are added.

**How to reproduce the issue:** Create a computed value and do not observe it. The computed value will be recomputed until it is first observed, at which point it will be cached until the dependent values change.

See this CodeSandbox: https://codesandbox.io/s/vibrant-brook-w5qlge?file=/index.js
Or this one: https://codesandbox.io/s/mobx-cached-values-z6ij20

**Versions**

mobx 6.5.0
mobx-react 7.3.0

---

Here's the relevant copy from the documentation:

> Computed values can be used to derive information from other observables. They evaluate lazily, caching their output and only recomputing if one of the underlying observables has changed. **If they are not observed by anything, they suspend entirely.**

I would interpret this as: if a computed property is not observed by anything, it returns its initial value and then never recomputes. This does not appear to be the case: instead, if computed values are not observed by anything, they instead behave like regular getters (recomputing on each request) until they _become_ observed. 

My guess is that the [default "untracked" derivation state](https://github.com/mobxjs/mobx/blob/e60b36c9c78ff9871be1bd324831343c279dd69f/packages/mobx/src/core/computedvalue.ts#L80) needs to be split into something like `UNTRACKED_NOT_COMPUTED`, which would cause the getter to run and cache the resulting value, and `UNTRACKED_COMPUTED`, which would return that value indefinitely (or at least, until an observer is added).

**Comment by urugator** [comment]
When computed becomes unobserved (suspended), the depedency graph is destroyed, meaning computed has no way of knowing whether any of it's dependencies changed in between invocations and therefore whether it can safely return cached value or if it must recompute.
Secondly computed can't hold onto any value (or rather reference) unless it knows it's being used somewhere (being observed), otherwise we could leak memory.

See https://mobx.js.org/computeds.html#computed-suspend

**Comment by steveruizok** [comment]
Makes sense, thanks for your reply! Is it enough that a computed property is being used in a different computed property?

ie. in the contrived example

```
@observable count = 0

@computed get double() {
  return this.count * 2
}

@computed get doublePlusOne() {
  return this.double + 1
}
```

if `doublePlusOne` was observed, but `double` was not, would `double` be considered tracked?

**Comment by urugator** [comment]
> would double be considered tracked?

Yes. You may want to take a look at https://mobx.js.org/analyzing-reactivity.html
