### ISSUE TITLE
observable.set triggers a refresh whenever any value in the set changes, even if that value was not accessed in the observer

### ISSUE THREAD

**Issue by TobiasWehrum** [mobxjs/mobx#3369]
**Intended outcome:**

I am using observable.set with many often-changing values. I also have many small observers observing the presence of single values in that set.

I would expect each observer to only refresh if the value it is observing is changing, e.g. if `observable.has("mainValue")` switches from false to true or vice versa.

**Actual outcome:**

The observer that uses `observable.has("mainValue")`  is called any time *any* value in the set is added or deleted, e.g. if I call `observable.add("otherValue")` or `observable.delete("otherValue")`.

**How to reproduce the issue:**

Minimal example showing the problem:
https://codesandbox.io/s/mobx-observable-set-rerk61?file=/index.js

Minimal example showing that this isn't happening for observable.maps (which is my current workaround):
https://codesandbox.io/s/mobx-observable-map-bhhgxi?file=/index.js

**Versions**

- mobx 6.5.0

**Comment by urugator** [comment]
Working as intended please see:
https://github.com/mobxjs/mobx/issues/2336#issuecomment-616128089

**Comment by urugator** [comment]
It's always a compromise. Array also doesn't track per index, comparators are not deep by default etc.
Personally I think it's something worth reconsidering for next majors.

> Maybe it could at least be mentioned in https://mobx.js.org/api.html#observableset?

Sure, PR welcome :)

**Comment by mweststrate** [comment]
PR welcome!

**Comment by urugator** [comment]
Doc updated.
