### ISSUE TITLE
Observing map additions does not trigger callback

### ISSUE THREAD

**Issue by lucsky** [mobxjs/mobx#337]
As demonstrated in the following snippet:
https://jsbin.com/cuqobitaho/edit?js,console

Not sure if a bug or if I'm doing something wrong... :)

**Comment by vvasilev-** [comment]
@lucsky Your code should be something like:

```js
mobx.observe(store.foo, () => {
  console.log('change observed');
});
```

See https://mobxjs.github.io/mobx/refguide/observe.html for more information. :)

**Comment by lucsky** [comment]
@vvasilev- aaaahh, I knew I was doing something wrong. Sorry for the noise @mweststrate.
