### ISSUE TITLE
ObservableMap not triggering reaction

### ISSUE THREAD

**Issue by fleksin** [mobxjs/mobx#3375]
**Intended outcome:** observableMap.set method can trigger reaction

**Actual outcome:** observableMap.set method only triggers autorun and computed

**How to reproduce the issue:**  demo here: https://codepen.io/fleksin/pen/MWrRWvZ  
Use Class + makeAutoObservable recipe, and make class property `c` a map, then create a reaction depend on it.   
Then mutate `c` using set , watch the console output
![image](https://user-images.githubusercontent.com/5846753/164599616-f021c168-fa4e-40ed-8e65-746177198cdc.png)

**Versions** 6.5.0  
https://cdnjs.cloudflare.com/ajax/libs/mobx/6.5.0/mobx.umd.development.js

Not sure if it's reported anywhere else before, can't find a similar open issue so far

**Comment by urugator** [comment]
Firstly reaction only reads property `c`, therefore it will only react to changes of the property (`this.c = foo`). It doesn't access the map itself, therefore it won't react to map changes.
Secondly reaction only triggers if returned value isn't strictly equal (unless changed via options), but `this.c` is always the same map instance.

**Comment by fleksin** [comment]
Got it. 
Right, so writing like this won't trigger reaction 
```
reaction(() => this.c, ...)
```
but, this somehow works
```
reaction(() => this.c.keys(), ...)
```

Anyway, probably should avoid using Map with Map.set
