### ISSUE TITLE
Customize observable with Proxy cannot work for collections datatype (Map, Set, etc)

### ISSUE THREAD

**Issue by Toubat** [mobxjs/mobx#3389]
> This is not a bug, but rather I would like to seek a workaround solution.

**Intended outcome:** I was trying to create a wrapper for Mobx used in my project. Since there is some extra logic I need to handle, I tried to create a Proxy wrapping around an existing observable data, like below 
```typescript
return new Proxy(target, {
  get(target, key) {
    if (key === ReactiveFlag.REACTIVE) {
      return !readonly;
    } else if (key === ReactiveFlag.READONLY) {
      return readonly;
    }

    let value = Reflect.get(target, key);

    // stop recurse if value is primitive data type
    if (!isObject(value) && !isFunction(value)) {
      return value;
    }

    // bind target to function's this (!important)
    if (isFunction(value)) {
      value = value.bind(target);
    }

    if (shallow) {
      return value;
    }

    return createReactiveProxy(value, shallow, readonly);
  },
  set(target, key, value) {
    if (readonly) {
      throw new Error(
        `Cannot set property ${String(key)} on readonly object`
      );
    }
    return Reflect.set(target, key, value);
  }
});

```
Please view this [Code Sandbox](https://codesandbox.io/s/hardcore-booth-w3zld7?file=/src/index.ts) for a more detailed code and test suite.

The extra logic is to return `true` whenever accessing the field `observed[ReactiveFlag.REACTIVE]`. (I know this can be achieved by using `isObservable`, this is just a small example. Of course, there can be more custom logic that is more complicated than this one.

**Actual outcome:** It works fine on objects and array datatype. However, when it comes to collections datatype (`Map`, `Set`, etc). The data accessed using `map.get(key)` will no longer be captured by the proxy I defined above. (**See test suite**). Since I define the proxy recursively, any data access should be captured by this proxy and handled based on the logic I provided, including collection types.

**How to reproduce the issue:** Please view this [Code Sandbox](https://codesandbox.io/s/hardcore-booth-w3zld7?file=/src/index.ts). Switch to Tests and see the error.

I somehow get an idea of why this failed. Since collections access is quite different to object and array access. So I wonder if there's a workaround such that data inside the `Map` can still be handled by Proxy.

**Versions** mobx 6.5.0

**Comment by mweststrate** [comment]
Map etc are normal objects, so you'll have to trap the "get"  etc property
and return your own function instead. Or subclass Map.

**Comment by Toubat** [comment]
Hi, I've figured out how to do this step. Thank you for your sugustion!
