### ISSUE TITLE
"set" action triggers effect within the same effect

### ISSUE THREAD

**Issue by Toubat** [mobxjs/mobx#3397]
**Intended outcome:** Here's the code
```typescript
  it("should untrack set action in effect", () => {
    const observed = observable({ foo: 1 });

    const spy = jest.fn(() => {
      observed.foo++;
    });
    autorun(spy);

    expect(spy).toHaveBeenCalledTimes(1);
    expect(observed.foo).toBe(2);
    runInAction(() => {
      observed.foo = 3;
    })
    expect(spy).toHaveBeenCalledTimes(2); // failed at this point
    expect(observed.foo).toBe(4);
  });
```
I want the spy only be called twice. i.e. set observed.foo should not trigger autorun. 

**Actual outcome:** 
```typescript
Expected number of calls: 2
Received number of calls: 100

  25 |     runInAction(() => {
  26 |       observed.foo = 3;
  27 |     });
> 28 |     expect(spy).toHaveBeenCalledTimes(2);
  29 |     expect(observed.foo).toBe(4);
  30 |   });
  31 | });
```
autorun is triggered 100 times, reaching the maximum recursion depth. Is there any way to allow observable data to change itself in an effect function when its dependencies include that same effect?

**How to reproduce the issue:** [Code Sandbox](https://codesandbox.io/s/hardcore-booth-w3zld7?file=/src/test.spec.ts)

**Versions** mobx 6.5.0

**Comment by mweststrate** [comment]
The recursion is the intended and correct outcome here. What is your real
life use case for anything else?

**Comment by Toubat** [comment]
Thank you for your feedback! Say I want to create an API wrapper based on autorun. A user who has no background knowledge of using this API (or even zero knowledge about reactivity) may simultaneously "get" and "set" inside the same effect function, but this would cause an infinite loop. So I just wonder if there's a way to "disable" effect triggering when I want to "set" some observable value inside autorun? A function like this:

```typescript
autorun(() => {
    let dummy = observed.foo;
    noTrigger(() => {
        observed.foo++;
    })
})

```

So whatever inside `noTrigger` will not trigger the autorun function. Is there a way to achieve behavior like this?

**Comment by mweststrate** [comment]
There are `untracked` reads, (see also `reaction`). There is no such thing as no-triggering writes, as it would lead to an inconsistent world where some parts of your app would have different ideas about what `observed.foo` is at this moment. Imagine rendering that variable, would it be `dummy` or `dummy + 1`?

**Comment by Toubat** [comment]
Yeah, that kind of makes sense. Last question: if I write nested runInAction:
```typescript
runInAction(() => {
    runInAction(() => {
        runInAction(() => {
            runInAction(() => {
                // some arbitrary code 
            });
        });
    });
});

```
Does the overall behavior the same as the following (unwrapped version)?
```typescript
runInAction(() => {
    // some arbitrary code
});
```

**Comment by mweststrate** [comment]
Did you check the docs on that 😊?

**Comment by Toubat** [comment]
Hi! Yes, I read the doc a couple of times, but I can't find where it explicitly says whether we can use nested `runInAction`. Intuitively, I think both examples above achieve the same result and I've also tested using some examples, but I'm not 100% sure.

**Comment by Toubat** [comment]
Great, thank you!
