### ISSUE TITLE
How to locate obfuscated errors?

### ISSUE THREAD

**Issue by licao404** [mobxjs/mobx#3407]
### Discussed in https://github.com/mobxjs/mobx/discussions/3406.

**Intended outcome:**
Throw the specific reason for the error if it went wrong in a production.

**Actual outcome:**
I noticed from Sentry that Mobx throws the following error in a production:

> [mobx] An invariant failed, however the error is obfuscated because this is a production 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/20166747/169432076-a940b4f8-2d21-4cd3-91c1-9f9ebcf8f99b.png">

It's hard for me to analyze from the obfuscated error what went wrong.
Is there any way to get more error messages?
Or is it possible not to report an error, If this invariant is not a critical problem?

**How to reproduce the issue:**
I cannot reproduce this error in a non-production.

**Versions**
5.15.7

**Comment by mweststrate** [comment]
Errors are generally numbered, as can be found here: https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/errors.ts. The error you're running into is probably this one: https://github.com/mobxjs/mobx/blob/5.15.7/src/v5/core/computedvalue.ts#L172
