### ISSUE TITLE
facing issue with mobx upgrade - please reopen this

### ISSUE THREAD

**Issue by vanilkumar** [mobxjs/mobx#3446]
### Discussed in https://github.com/mobxjs/mobx/discussions/3445

<div type='discussions-op-text'>

<sup>Originally posted by **vanilkumar** July  5, 2022</sup>
Hi Team, 
we are using below versions of mobx 
"mobx": "^5.15.7",
    "mobx-devtools-mst": "^0.9.21",
    "mobx-react": "^6.1.3",
    "mobx-state-tree": "^3.14.1",
same thing is working fine , but after did the npm install getting below error 
**TypeError: (0 , i.makeObservable) is not a function**
Then I added like this **import { makeAutoObservable } from "mobx"** but it is throwing like cant import makeAutoObservable from mobx.
can any one please help me.</div>

**Comment by mweststrate** [comment]
makeAutoObservable is only introduced in MobX 6, so you are combining incompatible versions of packages. NPM will have printed warnings about not meeting peerDependencies that indicate this.

**Comment by vanilkumar** [comment]
when I applied ^ symbol it will download the latest version only, when I ran this command  **npm view mobx version** it is showing the version as Mobx 6 only. so please do not close this issue give me the solution

**Comment by mweststrate** [comment]
`^` will only pick versions within the specified major, so if you have 6 locally your disk state is probably broken. But anyway, we can't do much without a minimal reproduction, so please follow the issue template as this is not an issue with MobX but with your local setup.
