### ISSUE TITLE
Observable array member's property becomes undefined (react-native)

### ISSUE THREAD

**Issue by siddharth-kt** [mobxjs/mobx#3482]
Mobx is really nice but i am facing some issues while using it with react-native.

Consider this example. 

> Taken from (https://github.com/mobxjs/mobx/issues/1596) somewhat same issue like mine.

const team = new Team({ name: "tt-name", _id: "tt-id" });
console.log("name:", team.name); // tt-name - ok
const teams = observable([team]);
console.log(teams); // [{name: "tt-name", _id: "tt-id" }] - ok
console.log(teams[0]); // undefined - messed up

**Intended outcome:**

console.log("name:", team.name)  should return **tt-name**.

**Actual outcome:**

But it returned undefined

**How to reproduce the issue:**

1.) Create an application with react native

2.) Wrap the component for testing in mobx-react observer function.

3.) User teams in that component.

**Versions**

"mobx": "^6.6.1",
"mobx-react": "^7.5.2",
"react": "17.0.2",
"react-native": "0.66.4",

**Comment by kubk** [comment]
Have you tried to check if your transpiler is configured correctly? https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties

There is a one line script to check.

**Comment by siddharth-kt** [comment]
Yeah, I have configured it like.

module.exports = function (api) {
  api.cache(true);

    return {
      presets: ['module:metro-react-native-babel-preset'],
      overrides: [
        {
          test: fileName => !fileName.includes('node_modules'),
          plugins: [
            ['@babel/plugin-proposal-class-properties', {loose: false}],
          ],
        },
      ],
      plugins: ['react-native-paper/babel', 'react-native-reanimated/plugin'],
    };
}

**Comment by kubk** [comment]
@siddharth-kt So what is the output of the one line script? No exception?

Unless we have a minimal reproduction it's very difficult to help. You may try to reproduce it here: https://snack.expo.dev/@trin4ik/mobx-theme-provider

**Comment by siddharth-kt** [comment]
@kubk Thankyou very much for taking time to help me.
I just found it was my mistake.
