### ISSUE TITLE
Autorun scheduler unable to achieve debounce behavior

### ISSUE THREAD

**Issue by bbabu01** [mobxjs/mobx#3485]
**Intended outcome:**
I was trying to implement debounce using autorun scheduler (My attempt to accompish the same using lodash didnt work earlier)

**Actual outcome:**
It seemed to act like throttle instead. Same behaviour as what we expect with `delay`

**How to reproduce the issue:**
```
    autorun(
      () => {
        console.log("autorun");
      },
      {
        scheduler: debounce => {
            clearTimeout(timerId);
            timerId = setTimeout(() => {
              debounce ();
            }, 3000);
          
        }
      }
    );
```
A complete example here. Thanks to @unel

**Versions**

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/issues/1956
