### ISSUE TITLE
[Typescript] observer() type does not correctly infer props when part of an object

### ISSUE THREAD

**Issue by smirea** [mobxjs/mobx#3510]
**Intended outcome:**

`observer()` correctly passes inferred props types along

**Actual outcome:**

wrapping a component in `observer()` causes the props to be `any`

**How to reproduce the issue:**

[Typescript playground example](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=2&pc=1#code/JYWwDg9gTgLgBAbzhARgZwKZQG5bgXzgDMoIQ4ByEVADwFooMBDAYxgoG4AoL4AOxhYirDHADKACyZgMAHgCCAPkRc4a4nwBccABRMoAczTb5ASjgBeZXwCuIFHgA+cWwBtX3fDyI2+bYBB8cMAAJhgCwDAAnrIAGoo6NNqxpsmIcIwwNlBBNBwEPCyBaPAACq5M-NqS0nJItiDaAIwATADMBMoWKuoa2vpGlsoDaAB0DQA0XF5cRXwlcADqkRIAkmER0dVSMrL1ds3tnZY96kRawRswkVF6hmhDcCPjdqZTM3MLyzASAPLoWFwUG2tT2LgOcFaHXwXVOanO2lQmBwWDugysT3uLxAb2mQA)

```ts
import { observer } from 'mobx-react';

interface Shape<A> {
    fn: (args: A) => number | null;
}

function identity<X>(x: X): X { return x; }

const Plain: Shape<{ num: 123 }> = {
    fn: args => args.num, // works
}

const WithIdentity: Shape<{ num: 123 }> = {
    fn: identity(args => args.num), // works
}

const WithObserver: Shape<{ num: 123 }> = {
    fn: observer(args => args.num), // FAILS, "args" is typed as "any"
}
```

**Versions**

```
"mobx-react": "^7.5.2",
"@types/react": "^18.0.17",
```

**Notes**

After looking into it a bit I noticed that if you remove the `React.ForwardRefExoticComponent<P>` from the `IReactComponent` definition the types are inferred correctly

**Comment by kubk** [comment]
Hi, thanks for the reproduction. I've removed React.ForwardRefExoticComponent but it didn't help. [Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSAlYBDAxjAYQgFtIA7YMmAHgAU4BeObMxAPkYCg4e4AfOFjwwAdAQA22AM5SAlriKkIFKhOlS6bbrwFD8YkuUqFJMzdp66c+gGIBXMvlnLFRquc6hIsOABNguJJQqABmDk7KcBAARlLAUABu8dQAKnCgMJS+Uuh6hIbKxmwAFLgFKjAAXHApAJTVKQDcnJyyVPEheKgAygAW2CjUAIIcAN4WcCFk1cXYUADmUtVDtYwcZHbE0fH8cBvi4s0Avi1hjjDOZHCy-lSySNQAGiUg1Y-1cI9wo3DBMHZQK4gRpwE6cMpkKTwWiSNrVPoDYDUH4bYjVACMACYAMygjhMca8SbTZgLHIMDhzRYiVEAGk4YIhULgAHV7r00LcLkh4f1BijNhicXjGN8JlNqjdjPdELMyWtSdTUbV6YzlMy2TBegB5WLxJJQXmI5F7QVwLG4o74sVEiVRPWJeJyxYKqlSGmbFUMoA)

The `arg` type is still any:

<img width="325" alt="Screen Shot 2022-09-01 at 08 22 26" src="https://user-images.githubusercontent.com/22447849/187837476-dd69d1bc-f769-423e-ac6e-6fdf6d9a9024.png">

Could you elaborate why do you need making `observer` part of an object here?

**Comment by smirea** [comment]
> Could you elaborate why do you need making observer part of an object here?

I was writing a library where I need to export a component together with metadata and found defining an interface for the export was the least amount of friction. Example:

```ts
interface Field<Value> {
	title?: string;
	Component?: React.FC<{ field: { value: Value } }>; // field is observed
}

const Numeric: Field<number> = {
	title: 'Number',
	Component: observer(({ field }) => <input type='number' value={field.value} />),
}
````

> I've removed React.ForwardRefExoticComponent but it didn't help. [Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSAlYBDAxjAYQgFtIA7YMmAHgAU4BeObMxAPkYCg4e4AfOFjwwAdAQA22AM5SAlriKkIFKhOlS6bbrwFD8YkuUqFJMzdp66c+gGIBXMvlnLFRquc6hIsOABNguJJQqABmDk7KcBAARlLAUABu8dQAKnCgMJS+Uuh6hIbKxmwAFLgFKjAAXHApAJTVKQDcnJyyVPEheKgAygAW2CjUAIIcAN4WcCFk1cXYUADmUtVDtYwcZHbE0fH8cBvi4s0Avi1hjjDOZHCy-lSySNQAGiUg1Y-1cI9wo3DBMHZQK4gRpwE6cMpkKTwWiSNrVPoDYDUH4bYjVACMACYAMygjhMca8SbTZgLHIMDhzRYiVEAGk4YIhULgAHV7r00LcLkh4f1BijNhicXjGN8JlNqjdjPdELMyWtSdTUbV6YzlMy2TBegB5WLxJJQXmI5F7QVwLG4o74sVEiVRPWJeJyxYKqlSGmbFUMoA)

You need to import react: [Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAD0ljhgE8wk4BJZdGAYV0gDsk-GAB4ACnAC8cFP0YA+KeTgq4AH0TEYAOm4AbFAGdDwNL3ARBw-UcPj5y1Rs4ZdfS0J4Hj9xyuda2gBiAK78GMCW5gKevlS00PAAJkhoBkRwmGERlnAQAEaGSFAAbsUiACpwNDBCSYbsLjzuVjDyABRoLZ4AXHAVAJR9FRTkwMLFmOisAMoAFigsIgCCigDefpn8fe0oUADmhn3LA1KK-CEg+cXqcBd6ehQAvpRZ4TCR-HDAKcLATCIABodah9QFDOCAuBrOBEGAhKBfaikOAvchdfiGeBiAzjPrzRZIEQwi4gPoARgATABmVGKaQbVRbPp7Q5nGQHQzaUkAGnIaIxWLgAHV-nM2L8Pkx8QsliTLhSaXSpNDNphtt9Jf9GLtOezWVzSQM+QLLELRTA5gB5QrFMpQGWE4l3BVwKm0p701VM9V9ApFUrFXVsySKA3cy7G-lAA)
