### ISSUE TITLE
Store initialization error occurs when the page switches and go back in chrome,Firefox is fine

### ISSUE THREAD

**Issue by wd4219** [mobxjs/mobx#3513]
When the page jumps to another page, refresh the new page, click go back, the store initialization does not take effect，But if not refresh,click go back, initialization was work good. who can help me resolve problem.thanks
<img width="637" alt="image" src="https://user-images.githubusercontent.com/17613480/187817615-a447f0dc-6073-427b-8355-f8c3df75d6d0.png">

**Comment by kubk** [comment]
Since you've created a discussion I'll close the issue to not discuss the same issue twice: https://codesandbox.io/s/minimal-mobx-react-project-ppgml?file=/index.js

Also for me it looks more like your setup issue rather than a Mobx issue.
