### ISSUE TITLE
autorun() behaviour

### ISSUE THREAD

**Issue by hellectronic** [mobxjs/mobx#353]
Hello,
I have the following code, that is similar to the Todo example in [Observable Arrays](https://mobxjs.github.io/mobx/refguide/array.html) section.

```javascript
class Store {
  @observable arr = [
    { selected: false },
    { selected: false },
  ];

  constructor() {
    autorun( () => {
      console.log( 'anobj = ', this._anotherObj );
    } );
  }

  @computed get _anotherObj() {
    return {
      arr: this.arr,
      other: true,
    };
  }
 
  changeArr() {
    this.arr[0].selected = !this.arr[0].selected;
    console.log( 'arr change' );
  }
}
```

The new assignment to `selected` does not trigger autorun. Is this supposed to be this way?

When instead of setting `select` I assign a new array, say `this.arr = this.arr.map( e => ( { selected: !e.selected } ) );`, then autorun will trigger.
When I only change `this.arr` to `toJS( this.arr )` (in `_anotherObj`), autorun will fire, too.
I suppose `toJS` does read the array elements which triggers the `autorun` ?

**Comment by hellectronic** [comment]
The same behaviour is true for observed objects as well.

**Comment by hellectronic** [comment]
I saw #333, but I don't know if this relates to it.

**Comment by mweststrate** [comment]
@hellectronic you autorun (nor computed property) depends on the `selected` property, so they won't react it to it. This is expected behavior. (the array itself is not modified by `changeArr`). Use `reaction` if you want to explicitly define on what you want to react (which might be more than is actually needed)

**Comment by andykog** [comment]
Nope, this is expected behaviour.
Your comuted `_anotherObj` doesn't assume something changed, because it doesn't use any values from array. And `arr` itself wasn't reassigned.

https://jsfiddle.net/Sl1v3r/6xrrgdw1/

**Comment by hellectronic** [comment]
Ah I understand.
Thanks for the fast reply.
