### ISSUE TITLE
@computed with Object and Array values

### ISSUE THREAD

**Issue by bringking** [mobxjs/mobx#354]
I was hoping for some clarification on the @computed values. I had the expectation that with the following code - 

```js 
  @observable postsBySlug = {};
  @computed({asStructure:true}) get postsByCat():Object {
    const {postsBySlug} = this;

    return Object.keys(postsBySlug).reduce((hash, slug) => {
      const post = postsBySlug[slug];
      const cat = post.fields.category[0].fields.title.toLowerCase();
      hash[cat].push(post);

      console.log('computing by cat'); // should only log when 'postsBySlug' changes
      return hash;
    }, {});
  }
```

the `postsBySlug` would only be iterated through whenever it is changed. However, in practice I am seeing this getter run every time it is accessed `store.postsByCat`. Is that intended? I tried it with both `asStructure` on and off.

**Comment by mattruby** [comment]
Have you observed that in an autorun or reaction?

**Comment by bringking** [comment]
@mattruby I haven't tried it, is a reaction the appropriate abstraction for what I am trying to achieve?

**Comment by mweststrate** [comment]
@bringking  see also: https://github.com/mobxjs/mobx/issues/356

**Comment by mweststrate** [comment]
Closed for inactivity, feel free to reopen when needed
