### ISSUE TITLE
The data has changed and the corresponding view has not been updated

### ISSUE THREAD

**Issue by Zian502** [mobxjs/mobx#3540]
**Intended outcome:**

**Actual outcome:**

Initialize Data：
![image](https://user-images.githubusercontent.com/26033663/195254433-b00495a9-3a73-4cc4-84cb-56cc304ad5bb.png)

Click the first row of data, and after re assignment, the view layer does not update the latest data：
![image](https://user-images.githubusercontent.com/26033663/195254526-cde6aa8f-2c44-48db-8f0a-603d84cd45a0.png)

**How to reproduce the issue:**

**Versions**

"mobx": "^6.3.3",
 "mobx-react-lite": "^3.4.0",
 "mobx-state-tree": "^5.1.6",
 "react": "^17.0.2",
 "react-dom": "^17.0.2"

**Comment by kubk** [comment]
Please provide a minimal runnable reproduction on [codesandbox](https://codesandbox.io/s/minimal-mobx-react-project-ppgml?file=/index.js).
Without the code it's not much we can do.

**Comment by mazhe-nerd** [comment]
盲猜是你的这个视图组件没有被observe，所以依赖没收集到

**Comment by Zian502** [comment]
> 盲猜是你的这个视图组件没有被observe，所以依赖没收集到

有的。
![image](https://user-images.githubusercontent.com/26033663/199658255-32a7c61c-c9ae-43d7-84c7-049dc5f1e64f.png)
我估计是不支持监听 antd 的表单组件。而且，有的数据没有放到 dom 上，数据变更了，视图不会更新。

**Comment by Zian502** [comment]
> Please provide a minimal runnable reproduction on [codesandbox](https://codesandbox.io/s/minimal-mobx-react-project-ppgml?file=/index.js). Without the code it's not much we can do.

The problem has been found. First, the ant d form is not supported. Second, the fields must be placed on the dom, otherwise the fields will be updated and the view will not be updated.

**Comment by iChenLei** [comment]
closed via https://github.com/mobxjs/mobx/issues/3540#issuecomment-1301693612
