### ISSUE TITLE
Is it safe to double wrap an object in `observable`?

### ISSUE THREAD

**Issue by mdebbar** [mobxjs/mobx#355]
Basically, can I do these things safely:
```javascript
var obj = observable(observable({ ... }));

extendObservable(obj, observable({ ... }));
```

**Comment by mweststrate** [comment]
@mdebbar yes that is save, but note that in the second the second argument being observable doesn't add anything, `extendObservable` copies values (like assign), but doesn't reuse the object itself

**Comment by mweststrate** [comment]
Closed for inactivity, I assume the question is answered :)
