### ISSUE TITLE
 Cannot find module 'react-dom' from 'node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js' & JEST simple test

### ISSUE THREAD

**Issue by i-vivdich** [mobxjs/mobx#3560]
Hi. I've **ReactNative** (0.70.2) app with "**mobx**": "^6.6.2", "**mobx-react-lite**": "^3.4.0" and JEST.

I have a simple functional Component wrapped in **observer**.
And I wrote simple test just to render that component!

**Intended outcome:**
I expect the test to pass or at least do not fail with build errors.

**Actual outcome:**
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/45571068/199516353-931dea22-619a-4555-82d5-59416ba08e3f.png">

**How to reproduce the issue:**
Nothing fancy. Just bare RN project, mobx and Jest libraries installed. Functional component wrapped in observer and then try to test that component - it will FAIL!

**Versions**
ReactNative (0.70.2) app with "mobx": "^6.6.2", "mobx-react-lite": "^3.4.0"

**Comment by kubk** [comment]
Hi, the provided information is not enough to help. Consider fill in the template and follow its recommendations, like this one: https://github.com/mobxjs/mobx/blob/main/.github/ISSUE_TEMPLATE/bug.md?plain=1#L32

**Comment by urugator** [comment]
I think your bundler should respect `package.json`: `"react-native": "es/index.js",` and use
`node_modules/mobx-react-lite/es/index.js`
instead of  
`node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js`
Why that's not the case I dunno.

**Comment by halenur** [comment]
Any updates?

**Comment by mweststrate** [comment]
Is the project configured to use CJS instead of ESM modules? Looks like the JEST config isn't respecting the react native configuration. Does this happen on a fresh react native project with only mobx-react-lite & mobx added, and further nothing else?

**Comment by patoinguai** [comment]
Hi! I am having the same issue, and since it's a React native project I wouldn't like to add React-DOM just for my tests. Could you please help us with this. 
Could be a possible solution to enable MobX to start using ESM instead of CJS just for Jest? I couldn't find the way. Maybe I'm wrong.

**Comment by vovkasm** [comment]
Just need to set this in jest.config.js:
```
const repoDir = __dirname;

module.exports = {
  ...
  moduleNameMapper: {
    "^mobx-react-lite$": `${repoDir}/node_modules/mobx-react-lite/es/index.js`,
  },
};
```
