### ISSUE TITLE
No error stack in reaction uncaught exception log

### ISSUE THREAD

**Issue by ArmorDarks** [mobxjs/mobx#3561]
**Intended outcome:**

When Mobx reaction reports an unhandled error, it should include a full error stack. Besides, ideally, it should include the stack from which reaction that error was thrown.

**Actual outcome:**

Having an error in reaction logs:

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1161]' Error: Example error
```

The handler [here](https://github.com/mobxjs/mobx/blob/2caf7e1a3504dde3d7c9bde3c6fb56ca85168018/packages/mobx/src/core/reaction.ts#L170) completely swallows the error, it's no longer thrown, so it's impossible to get any useful stack trace for it.

That makes it challenging to understand in a large project where the error originated. Having an original error stack would help with that.

So far it's workaroundable by adding `globalReactionErrorHandlers` but that's not very obvious

**How to reproduce the issue:**

Throw any error in the inside of the Autorun or Reaction.

**Versions**

Chrome v107.0.5304.87
Mobx v6.3.3

**Comment by urugator** [comment]
What browser/platform? The error is usually printed including the stack trace. We can't rethrow the error there and you wouldn't be able to catch it anyway, reactions act like async callbacks.

**Comment by ArmorDarks** [comment]
Chrome v107.0.5304.87

Now I understand that the problem is not with the browser, but with the 3rd party logger we use which stringifies error, and that loses the stack track because it's (of course) not part of the message.

Closing this since nothing can be done about it in MobX, I think
