### ISSUE TITLE
Return value of Atom.reportObserved is inconsistent with whether onBecomeObserved is called

### ISSUE THREAD

**Issue by upsuper** [mobxjs/mobx#3563]
**Intended outcome:**

`onBecomeObserved` should always be invoked when `reportObserved` returns `true`, or the other way around, `reportObserved` should only return `true` when `onBecomeObserved` has been run.

**Actual outcome:**

In some cases, `reportObserved` returns `true` but `onBecomeObserved` is never run, which breaks the way it is relied on, and makes atom a footgun to use.

This actually breaks the example shown for atom in [the document](https://mobx.js.org/custom-observables.html) that if it can be returning wrong time.

**How to reproduce the issue:**

See this example: https://codesandbox.io/s/magical-jang-zcplf2?file=/src/index.ts

```ts
import * as mobx from "mobx";

const atom = mobx.createAtom(
  "test",
  () => console.log("become observed"),
  () => console.log("become unobserved")
);

const computed1 = mobx.computed(() => {
  console.log("computed observed", atom.reportObserved());
  return 0;
});
computed1.get();
const computed2 = mobx.computed(() => computed1.get());
computed2.get();
```

The console log is:
```
computed observed false
computed observed true
```
and the `onBecomeObserved` is never called.

On MobX 5, however, the console log would be
```
computed observed false
become observed
computed observed true
become unobserved
```
which is not ideal, but fine.

**Versions**

It is a change in MobX 6, more specifically I believe it is a regression from 5536533ed26d6bd8c7989b49990994daa3831009.

**Comment by upsuper** [comment]
I guess a fix could be changing [this line](https://github.com/mobxjs/mobx/blob/8cf4784f53857cc977aed641bd778f2c14a080f5/packages/mobx/src/core/observable.ts#L154):
```diff
 export function reportObserved(observable: IObservable): boolean {
     checkIfStateReadsAreAllowed(observable)
 
     const derivation = globalState.trackingDerivation
     if (derivation !== null) {
         /**
          * Simple optimization, give each derivation run an unique id (runId)
          * Check if last time this observable was accessed the same runId is used
          * if this is the case, the relation is already known
          */
         if (derivation.runId_ !== observable.lastAccessedBy_) {
             observable.lastAccessedBy_ = derivation.runId_
             // Tried storing newObserving, or observing, or both as Set, but performance didn't come close...
             derivation.newObserving_![derivation.unboundDepsCount_++] = observable
             if (!observable.isBeingObserved_ && globalState.trackingContext) {
                 observable.isBeingObserved_ = true
                 observable.onBO()
             }
         }
-        return true
+        return observable.isBeingObserved_
     } else if (observable.observers_.size === 0 && globalState.inBatch > 0) {
         queueForUnobservation(observable)
     }
 
     return false
 }
```
```

**Comment by emereum** [comment]
Here's a similar repro comparing the behaviour in an `autorun` as compared to an `action`, noting the differences in `trackingContext` and `trackingDerivation` that lead to this edge case: https://codesandbox.io/s/boring-taussig-11y8c5?file=/src/index.ts

**Comment by mweststrate** [comment]
The original example doesn't create a tracking context, so the observable
never becomes "hot" to stay alive, hence it correctly never fires. Make
sure to use the computed from an autorun.

**Comment by upsuper** [comment]
I'm not arguing that `onBecomeObserved` should be fired, but that whether `onBecomeObserved` is fired should match whether `reportObserved` returns `true`, otherwise atoms are just a footgun.

**Comment by mweststrate** [comment]
Curious, what is your real life use case where this leads to problems? The
rationale behind the event is whether future updates should be propagated.
E.g. if it fires you need to set up a database subscription. In your
example, that should not happen, because even though you correctly called
reportObserved, no one is listening for the *future* updates to that atom.

**Comment by upsuper** [comment]
Your example code in the document for atom is a perfect case that this can cause a problem. If you happen to access the time through nested computeds before anything else starts observing it, you would unexpectedly get an undefined.

**Comment by urugator** [comment]
I want to point out it's not about nested computeds it's about batching. You can replace the second computed with `runInAction`, experiencing the same problem. It's just that `computed` function runs in batch implicitly:
```javascript
import * as mobx from "mobx";

const atom = mobx.createAtom(
  "test",
  () => console.log("become observed"),
  () => console.log("become unobserved")
);

const computed1 = mobx.computed(() => {
  console.log("computed observed", atom.reportObserved());
  return 0;
});

computed1.get();

mobx.runInAction(() => {
  computed1.get();  
})
```
The idea is to keep the computed's cache hot for the duration of the batch, event though there are no real observers, basically the computed itself becomes a temporal observer:
```javascript
mobx.runInAction(() => {
  computed1.get(); // recomputes, caches result
  computed1.get(); // returns cached result
  // ... leaving batch ...
  // computed tears down, purges cache
})
```
It has been established in #2309, that these temporal observations shouldn't trigger `onBecome(Un)Observed`.
In the same spirit I think that `this.atom.reportObserved()` should stay `false` in these cases (batch only).
However I am not sure if it's a simple change, since some internals might depend on this, dunno, investigation required.
But I agree the current behavior wrong. As already pointed out @upsuper, given the example in docs:
```javascript
getTime() {     
  if (this.atom.reportObserved()) { // is true in batch
    // assumes the clocs are ticking, but they're not, because onBecomeObserved was not called
    return this.currentDateTime
  } else {   
    return new Date()
  }
}
```

**Comment by mweststrate** [comment]
@upsuper and @urugator, thanks for pointing out the case, sorry I misunderstood the problems and I think your assessments are right indeed (shouldn't have tried to grok this from my phone 😅). 

> However I am not sure if it's a simple change, since some internals might depend on this, dunno, investigation required.

My gut feeling, might be wrong here, is that I don't think there is much internals further depending on this and changing it should be fairly safe. It might potential affect external libraries, but I'd assume this fixes a bug in them as well.

**Comment by urugator** [comment]
@upsuper The proposed fix looks good to me, wanna PR?

**Comment by upsuper** [comment]
Yeah, can do maybe next week
