### ISSUE TITLE
Property getters are lost when object is made observable

### ISSUE THREAD

**Issue by dusansmail** [mobxjs/mobx#3568]
**Intended outcome:**
Transformed/resulting object from makeAutoObservable(), makeObservable() or observable() should have property getters just like the original object had.

**Actual outcome:**
Transformed/resulting object no longer has getters that were defined in the original. On the other hand, functions are preserved just fine.

**How to reproduce the issue:**
```
const firstName = "John"
const lastName = "Smith"

const person = {
    get firstName() { return firstName },
    get lastName() { return lastName },
    sayHello: function () { return console.log(`Hello, I am ${firstName} ${lastName}`) }
}

console.log({ ...person })
// Object { firstName: "John", lastName: "Smith", sayHello: sayHello() }

makeAutoObservable(person)
console.log({ ...person })
// Object { sayHello: res() }
// Expected to be: Object { firstName: ..., lastName: ..., sayHello: ... }
```

**Versions**

**Comment by urugator** [comment]
Getters don't disappear, thery are turned into computeds and made non-enumerable. This is a design decision made long ago, it has some pros and cons and probably won't change any time soon.
Functions are enumerable , unless you explicitely mark them as `action`, in which case they also become non-enumerable and additionally non-writable. Otherwise they're treated as any other observable field, the only difference being that the value is as function.

**Comment by dusansmail** [comment]
@urugator Thanks, that clarifies a lot.

There are a lot of situations where we use de-structuring, enumerating properties and similar kinds of implementation.
For the 'action' annotation, docs states that those will become non-enumerable:

> action annotated members will be non-enumerable.

We could not find docs explicitly saying that computeds will become non-enumerable, except a clue in the toJs() docs:

> Computed` and other non-enumerable properties are completely ignored and won't be returned

I think docs should, at least, clearly and precisely state about this behavior in a single place.
Otherwise we end up are wondering what and why is something happening and chasing subtle bugs.

**Comment by urugator** [comment]
> There are a lot of situations where we use de-structuring

Just to elaborate a bit further, mobx encourages dereferencing props as late as possible, or in other words, it discourages creating copies, so arguably it shouldn't be needed as often. Non-enumerability comes in handy when sending observables over wire (`JSON.stringify(obs)`).

> I think docs should

Sure, PR welcome.

**Comment by urugator** [comment]
Added note to the docs
https://mobx.js.org/computeds.html#example
