### ISSUE TITLE
Map.entries, Map.keys and Map.values should return iterator instead of array

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#357]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values

for backward compatibility, return both an array and iterator in the 2.0 branch?

**Comment by benjamingr** [comment]
You can return an iterator and have a third party library for the old behavior or map? 

I think the library should make objects as indistinguishable from regular objects as possible.

**Comment by mweststrate** [comment]
released as 3.5.6 already.

**Comment by Jony-Y** [comment]
@mweststrate why change them into iterator and not an array? as arrays you can easily user filter, slice, find , etc... what is the benefit of returning a MapIterator?

**Comment by benjamingr** [comment]
@Jony-Y spec compliance with regular ES6 maps.
