### ISSUE TITLE
Why do I need to wrap my react components with observer when using React's useState or useMemo？

### ISSUE THREAD

**Issue by koloer-blus** [mobxjs/mobx#3571]
### Discussed in https://github.com/mobxjs/mobx/discussions/3570

<div type='discussions-op-text'>

<sup>Originally posted by **koloer-blus** November 11, 2022</sup>
```jsx
const TimerView = observer(() => {
    const [timer] = useState(() => new Timer()) // See the Timer definition above.
    return <span>Seconds passed: {timer.secondsPassed}</span>
})
```
In the above code, even without wrapping the component with observer, my TimerView is being updated in response, which is based on how react state updates.
Does the update method change if the observer package is used?
I don't understand why the observer package is needed here, since I'm not updating my component via props or an external model.</div>

**Comment by iChenLei** [comment]
duplicated https://github.com/mobxjs/mobx/discussions/3570
