### ISSUE TITLE
Functions with properties are clobbered when made observable in MobX 6

### ISSUE THREAD

**Issue by emereum** [mobxjs/mobx#3575]
**Intended outcome**

Properties of functions in observed objects should be accessible.

**Actual outcome**

Properties of functions in observed objects no longer exist.

**How to reproduce the issue:**

[CodeSandbox example](https://codesandbox.io/s/mystifying-kirch-nn2504?file=/src/index.ts)
```
const x = function() {}
x.y = function() {}
const o = mobx.observable({ x });

o.x.y(); // TypeError: o.x.y is not a function
```

The real-world scenario where this affects us is when mocking with Jest:

```
const o = mobx.observable({ x: jest.fn() });
o.x.mockReturnValue(...) // TypeError: o.x.mockReturnValue is not a function
```

We can work around this in some cases by explicitly making `x` `observable.ref`. In other cases such as when an object is observed in application code we need to redefine the property in conjunction with patches to `deepEnhance`:

```
const store = new BananaStore();
Object.defineProperty(store, 'eatBanana', { value: jest.fn() });
```

**Versions**

This behaviour occurs in MobX 6 onward.

**Comment by urugator** [comment]
Btw we could use proxies for `actions` (instead of wrapper function), but I am afraid of performance implications.

**Comment by urugator** [comment]
Similar issue
https://github.com/mobxjs/mobx/discussions/3481

**Comment by emereum** [comment]
> observable({ x }, {x: false}) should solve that issue.

That does solve the issue where we can control how the `observable` is created, but in more complex cases we still have issues. For example if we are testing a complicated aggregate root which creates an `observed` object somewhere inside its public API, we have limited options for mocking out such members. It is possible to work around most of these issues with minor changes to our codebase but it would be great to have the old behaviour back; it keeps the tests more concise.

**Comment by mweststrate** [comment]
Sorry that ship has sailed two years ago, to have better defaults in other
cases

**Comment by urugator** [comment]
Potential user land solutions:

Wrap with action an expose jest mock as special prop
```javascript
function jestFn(impl) {
  const jestFn = jest.fn(impl);
  const mobxAction = mobx.action(jestFn);
  mobxAction.jest = jestFn;
}

const o = mobx.observable({ x: jestFn() });
o.x.jest.mockReturnValue();
```

Wrap with action and hoist original functions props
```javascript
function actionWithHoistedProps(fn) {
  const mobxAction = mobx.action(fn);
  const names = Object.getOwnPropertyNames(fn);
  const symbols = Object.getOwnPropertySmybols(n);
  [...names, ...symbols].forEach(key => {
    // TODO may need some filtering
    const descriptor = Object.getOwnPropertyDescriptor(fn, key)
    Object.defineProperty(mobxAction, key, descriptor);
  });
  return mobxAction;
}

const o = mobx.observable({ x: actionWithHoistedProps(jest.fn()) });
o.x.mockReturnValue();
```

Wrap with action and set the original function as prototype
```javascript
function actionWithProto(fn) {
  const mobxAction = mobx.action(fn);
  Object.setPrototypeOf(mobxAction, fn);
  return mobxAction
}

const o = mobx.observable({ x: actionWithProto(jest.fn()) });
o.x.jest.mockReturnValue();
```
