### ISSUE TITLE
Support `@observable` on plain object attributes

### ISSUE THREAD

**Issue by jbe456** [mobxjs/mobx#358]
Consider the following examples:

```
const {observable, computed, autorun} = mobx;

class Global {
     @observable state = {
      @observable a: 0,
      @observable b: 1
    }

    @computed get computed_a() {
        this.state.a;
            console.log('computed of a!');
    }

    @computed get computed_b() {
        this.state.b;
            console.log('computed of b!');
    }

    @computed get computed_state() {
        this.state;
            console.log('computed of state!');
    }
}

const global = new Global();

console.log('autoruns');
autorun(() => global.computed_a);
autorun(() => global.computed_b);
autorun(() => global.computed_state);

console.log('Change b');
global.state.b = 'toto';
```

Here is the output:

```
autoruns
computed of a!
computed of b!
computed of state!
Change b
computed of a!
computed of b!
```

Here is what I would expect:

```
autoruns
computed of a!
computed of b!
computed of state!
Change b
computed of b!
computed of state!
```

How can I achieve that?

The reason behind is the following: imagine I have heavy computed values depending on each possible sub object that I can extract from `state`: the whole state object, the leaf a only, the leaf b only ... (and recursively if the object was much bigger).

If I create a computed value that only reads `a` from the `state`, since I read it using `this.state.a`, MobX considers it depends on the whole state. If I make only `a` and `b` observables it works, but then I can't listen to the whole state...

I'm aware I could create light computed values and have heavy computed values depending on the light one, but it is very verbose as I would have to create a computed value for each possible sub object that I can extract from `state`. What do you advise?

**Comment by mweststrate** [comment]
Your expectation is right. Note that observable object properties are not an officially supported case, as there is no real use for that in my experience. Doesn't just 
```javascript
 @observable state = {
      a: 0,
      b: 1
    }
``` 
already give the correct result? (observable recurses on plain objects automatically)

**Comment by mweststrate** [comment]
Since there are enough ways to construct observables already, I don't think this feature adds much value. Therefor a won't fix for now.
