### ISSUE TITLE
mobx 6.7.0 leaks @types/node global typings

### ISSUE THREAD

**Issue by kris7t** [mobxjs/mobx#3582]
**Intended outcome:** When using mobx in a TypeScript in a frontend-only project, it should be possible to use the DOM typings for globals such as `setTimeout` (which should return a `number`).

**Actual outcome:** The globals get their typings from `@types/node`, because `mobx/dist/api/when.d.ts` contains a spurious

```typescript
/// <reference types="node" />
```

since https://github.com/mobxjs/mobx/commit/223e3688631528a327c79d39e2f497c6e1506165. Unfortunately, global typings referenced by imported files are automatically propagated to importing packages: https://github.com/microsoft/TypeScript/issues/22331#issuecomment-613816908

In particular, `setTimeout` now return `NodeJS.Timeout` even if `"node"` is _omitted_ from `compilerOptions.types` in `tsconfig.json`. Globals not present in DOM, such as `process`, are also visible, which is particularly dangerous for type safety.

**How to reproduce the issue:**

Create a TypeScript project with a `tsconfig.json` containing

```json
{
    "compilerOptions": {
        "libs": []
    }
}
```

Observe that if mobx 6.6.2 is imported in the project, globals like `setTimeout` have their types as specified in DOM (e.g., `setTimeout` returns `number`): https://codesandbox.io/s/currying-worker-yj8gt6?file=/index.tsx

If mobx 6.7.0 is imported, the globals have their types as in `@types/node`, because mobx references the node global typings: https://codesandbox.io/s/sleepy-bird-dh354u?file=/index.tsx

**Versions**

* typescript 4.9.3
* mobx 6.7.0

**Comment by urugator** [comment]
Thank you for the report. 
PR https://github.com/mobxjs/mobx/pull/3583.
Let me know if there is a better solution.
