### ISSUE TITLE
Where is /best/pitfalls?

### ISSUE THREAD

**Issue by artalar** [mobxjs/mobx#3600]
Hi! I know there was https://mobx.js.org/best/pitfalls.html page with limitations and pitfalls descriptions. Where is it now? The docs search for "limitation" and "pitfall" now gets only couple results

**Comment by mweststrate** [comment]
I think it's now primarily under https://mobx.js.org/understanding-reactivity.html + the direct api's to which they applied

**Comment by artalar** [comment]
Got it, thank you!
