### ISSUE TITLE
Handling FlatList re-rendering when using Mobx to store nested data objects

### ISSUE THREAD

**Issue by pratikdhody** [mobxjs/mobx#3627]
Hi,

I have a FlatList component like so which renders ItemView based on partnerStore.filteredDataSource which is a store maintained via Mobx.

```
           <FlatList
                  data={partnerStore.filteredDataSource}
                  keyExtractor={(item, index) => item.id}
                  ItemSeparatorComponent={ItemSeparatorView}
                  //renderItem={ItemView}
                  renderItem={ItemView}
                  keyboardShouldPersistTaps="always"
                  refreshing={isLoading}
                  onRefresh={onRefresh}
                  initialNumToRender={20}
                  contentContainerStyle={{ paddingBottom: 190 }}
                />
```

The filteredDataSource is a Array object with nested objects and within those objects, nested arrays.

In addition to the above, I am updating data in filteredDataSource based on the fact that I'm allowing the user to search this filteredDataSource array and mutate it.

When removing items from filteredDataSource - the FlatList renders ItemView accurately but when adding new items to partnerStore.filteredDataSource - it does not.

I think this issue is related to the data prop in FlatList being a ReadOnly prop.

Has anyone been able to figure out how to resolve this?

Cheers

### Discussed in https://github.com/mobxjs/mobx/discussions/3626

<div type='discussions-op-text'>

<sup>Originally posted by **pratikdhody** February  5, 2023</sup>
Hi,

I have a flatlist showing items and the data for this is stored in a mobx store.
I've provided the functionality for users to be able to filter via searching with text on a few of the fields.
The search functionality works but I'm running into issues where the Flatlist is not re-rendering.
Console logging the store shows correct number of items based on the search filter.

I've tried to .slice() the store but this hasn't worked. I've tried to js() the store as the data prop is ReadOnly but that hasn't worked either. I've also added <Observer> component to the renderItem and I've also tried store.nestedstore.length on extraData and that hasn't worked either. I think the reason for this is because the store itself has nested arrays etc.

Does anyone else have any other ideas on how to re-render flatlists when using Mobx store and where the store itself is being mutated?</div>

**Comment by mweststrate** [comment]
Did you check https://mobx.js.org/react-integration.html#dont-pass-observables-into-components-that-arent-observer? If FlatList is not an observer, you might need to pass `partnerStore.filteredDataSource.slice()` as data

Similarly, `ItemView` should be marked as `observer` to reflect individual item changes. See also above link how to handle that.

**Comment by pratikdhody** [comment]
> Did you check https://mobx.js.org/react-integration.html#dont-pass-observables-into-components-that-arent-observer? If FlatList is not an observer, you might need to pass `partnerStore.filteredDataSource.slice()` as data
> 
> Similarly, `ItemView` should be marked as `observer` to reflect individual item changes. See also above link how to handle that.

Updating data to `partnerStore.filteredDataSource.slice()` and/or adding `<Observer>` like the following in ItemView did not work.
Items get reduced but when items get added back to partnerStore.filteredDataSource - the FlatList does not render the items.

```
const ItemView = ({ item }) => {

    const claimData = [...claimedRounds]
    const claimIndex = claimedRounds.findIndex(
      (claim) =>
        String(claim.relatedPartnerId) === String(item.id) &&
        String(claim.userId) === String(rootStore.authStore.id),
    )

    return (
      <Observer>
        {() => (
          // Flat List Item
          <TouchableOpacity
            style={styles.listItem}
            onPress={() => {
              partnerFilterStore.setSearch("")
              navigation.navigate("partner", { id: item.id })
            }}
          >
.......
```

**Comment by mweststrate** [comment]
Ok, then I don't see anything obviously wrong from what you shared so far. Best to build a minimal reproduction.

**Comment by urugator** [comment]
> When removing items from filteredDataSource - the FlatList renders ItemView accurately but when adding new items to partnerStore.filteredDataSource - it does not.

Are the item id's unique? Don't you use  `filteredDataSource.length` or something like that to generate ids of added items?

**Comment by pratikdhody** [comment]
> > When removing items from filteredDataSource - the FlatList renders ItemView accurately but when adding new items to partnerStore.filteredDataSource - it does not.
> 
> Are the item id's unique? Don't you use `filteredDataSource.length` or something like that to generate ids of added items?

the item ids are from our backend... so when the user first goes to screen, there are let's say 10 items in the object. The user then filters the data and items get removed. When adding them back in, they get added back with the same ids. Should this not happen @urugator?

**Comment by pratikdhody** [comment]
Just an update, so I have realised that my issue only occurs when partnerStore.filteredDataSource has no data and after an item gets added to this store.
