### ISSUE TITLE
action does not forward underlying function's toString

### ISSUE THREAD

**Issue by ahoisl** [mobxjs/mobx#3653]
**Intended outcome:**

It's kind of a special case, but we do have function/constructors in our project that implement `toString`. Wrapping such functions into an action should transparently return the same output for `toString` as if invoked on the original function.

**Actual outcome:** 

Currently, wrapping a function into an action hides the original `toString` and calling `toString` on the action will just show the source code for the `action` implementation.

**How to reproduce the issue:**

Using following unit test, see PR #3654
```
const fn = () => { /* not actually doing anything */ }
fn.a = 42;
fn.toString = function (this) { return `toString referencing this, a=${this.a}` }

const act = mobx.action(fn)

expect(fn.toString()).toBe("toString referencing this, a=42")
expect(act.toString()).toBe("toString referencing this, a=42")
```

**Versions**

mobx 6.7.0

**Comment by urugator** [comment]
Any chance you could handle this manually only where needed?

**Comment by ahoisl** [comment]
@urugator Unfortunately not. First, we are using decorators; second and more importantly, this happens for auto-observed items, e.g. when adding something to a ObservedArray or ObservedMap (and making those non-deep seems like a weird workaround).

Are you worried about backward compatibility? As I see it, the `toString` for the action wrapper was unused and would have only returned its own source code.

**Comment by urugator** [comment]
More about perf I guess. It makes sense, but it's one of those things that affects everyone, but actually helps, well, probably one user at this point.

You need it on production correct? it's not related to some debugging tool or something like that?

Would it help to just expose the original function on the action? So you could `myAction.original.toString()`. There were some issues regarding loosing custom props, so it could potentially help in this area as well.
The most robust solution I think would be to actually use proxy instead of wrapper, but I am afraid it would perform quite poorly - not just on creation, but also individual invocations. Did not try though.

**Comment by ahoisl** [comment]
Yeah, it's on production code. The problem is that everything else in mobx tries to work transparently, meaning, an observed value acts mostly similar to a non-observed value. In that case, the toString is just completely different.

The case where we need it does not even know about mobx, so I cannot call an `original` prop.

And yes, as I said first, it's a special case, but one that left us completely baffled first. Took us hours to understand that mobx auto-observe-feature causes the issue.

Regarding performance: if you're worried about the bind, a lambda would do, too, and should be quicker:
`res.toString = () => fn.toString()`

**Comment by mweststrate** [comment]
I think this is too much of an edge case to solve generically and pay the reflection needed on every action created (it's not just true for toString, but basically any other prop you put on the action as well). However, MobX doesn't double wrap actions, so at the place you customize the `toString`, you can also apply `action` right away, and from then on it should be preserved everywhere. E.g.

```
const _fn = () => { }
const fn = action(_fn)
fn.toString = () => { .... }
```

**Comment by ahoisl** [comment]
One more comment to performance: The performance impact (if noticeable) only applies to the creation of an action, not the execution. So IMHO the impact should be neglectable.

**Comment by ahoisl** [comment]
> However, MobX doesn't double wrap actions, so at the place you customize the `toString`, you can also apply `action` right away, and from then on it should be preserved everywhere. E.g.

@mweststrate Unfortunately, I don't have control of that. If it would be for a "distinct" action, it would be fine. The problem occurs with objects that are turned into observables automatically, e.g. when put into an ObservableArray, ObservableMap or ObservableSet

**Comment by mweststrate** [comment]
> I don't have control of that.

You're setting a custom `toString` somewhere, so at that same place you can already turn it into an action? ObservableSet etc. then won't and skip it.

**Comment by ahoisl** [comment]
> @mweststrate It's about native toString of the original function, not a custom one.

Right. And it's actually from different library that does not know about mobx at all. It's a base class/object that's being used and extended with mobx features in the frontend.

**Comment by mweststrate** [comment]
yeah in that case I recommend to go for a patch-package on the lib or mobx instead indeed

**Comment by urugator** [comment]
Btw in case someone is interested to investigate, I would really like to know perf difference of:
```javascript
function wrap(original) {
  return function() {
     return original.apply(arguments)		
  }
}

const proxyHandler = {
  apply: function(target, thisArg, argumentsList) {
     return target(target, thisArg, argumentsList)
  }
}

function proxy(original) {
  return new Proxy(original, proxyHandler);
}
```
If it would turn out to be comparable, I think we could make it available under flag or even default in next major.

**Comment by ahoisl** [comment]
I did some investigation on proxy performance for function/apply. I used the following code, see gist:
https://gist.github.com/ahoisl/8c4a2f38ae0b238fd3aa5c853016b238

Just paste the code in your browser dev console or run it with node. It will automatically start a run using the `rand` function, calling `Math.random` in a loop of 100 iterations. You can also use other functions as measurement scenario, I supplied a few (e.g. `calc`, `echo` or `fact` performing recursive factorial calculation), just use them as function to wrap/proxy by calling `start(func)`. You can also supply arguments, e.g. `start(echo, 123)`.

My findings or how I interpret them:
* The overhead for creating a proxy is in my opinion negligible compared to wrapping. Depending on the browser, proxy takes up to 2x time of wrapping, however, in absolute terms this means a difference of 10ns (nanoseconds) per call on my machine.
* Calling (apply) performance is heavily dependent on the code the function executes
  * If the function takes some time to execute, like the `rand` function does, the difference is again negligible, with no significant overhead from the proxy.
  * If the function does not do anything or is very simple, the proxy has again an overhead of approx. factor 2
  * There seems to be a big difference if the function calls itself as for the factorial (`fact`). While in FF the proxied variant is about 3x slower, in V8/Chromium the difference can be up to factor 30x. This seems heavy, but I'm not sure if this is a common case for actions, i.e. that they call themselves a lot.
* _off-topic_ Firefox seems slow when compared to Chromium based browsers or V8/Node (both for proxy and wrapping) and apparently does way less optimization on function evaluation

So again, the overhead from using proxy when compared to wrapping highly depends on the functionality of the action that's being proxied/wrapped. If the function really performs some (non-recursive on itself) action, the difference in creation and execution is IMHO negligible.
On the other hand, there are cases where the execution performance difference may be huge

All that said, this is a very limited example and one can probably not predict the optimization techniques and outcomes in real life...

**Comment by artemmatiushenko1** [comment]
For some reason when logging the name property of mobx store action it outputs the string `res` instead of the actual method name (`testName`).

```
class TestStore {
  @action.bound
  testAction() {
    console.log(this.testAction.name)
  }
}
```
