### ISSUE TITLE
Remove deprecated features for the next major version

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx#3655]
Since next Mobx update might be major due to native decorators support, it makes sense to revisit the API and remove deprecated features. Removing deprecated features gives less code to support for maintainers. For example here while mocking console.log I had to support both `observer` and `useObserver` usage: https://github.com/mobxjs/mobx/blob/01432751d235da15fc861619563a08f1c9dfa623/packages/mobx-react-lite/__tests__/observer.test.tsx#L17

Here is the list of deprecated API I've found:

- [useObserver](https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/README.md#useobservertfn---t-basecomponentname--observed-options-iuseobserveroptions-t-deprecated). The goal is to only remove it from public API since it's still being used internally: https://github.com/mobxjs/mobx/blob/01432751d235da15fc861619563a08f1c9dfa623/packages/mobx-react-lite/src/ObserverComponent.ts#L13
- [useLocalStore](https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/README.md#uselocalstoret-sinitializer---t-source-s-t-deprecated). It's deprecated in favor of useLocalObservable.
- [useAsObservableSource](https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/README.md#useasobservablesourcetsource-t-t-deprecated)
- Batching utilities like `batchingForReactDom.js`, `batchingForReactNative.js`, `batchingOptOut.js`:
https://github.com/mobxjs/mobx/blob/01432751d235da15fc861619563a08f1c9dfa623/packages/mobx-react-lite/batchingForReactDom.js#L2
- `isObserverBatched` since it's always returns true: 
https://github.com/mobxjs/mobx/blob/01432751d235da15fc861619563a08f1c9dfa623/packages/mobx-react-lite/src/utils/observerBatching.ts#L21
- `options` argument in `observer`:  https://github.com/mobxjs/mobx/blob/01432751d235da15fc861619563a08f1c9dfa623/packages/mobx-react-lite/src/observer.ts#L65
- Drop `flow` type checker support, types and tests since flow is no longer supported: https://github.com/mobxjs/mobx/issues/2792#issuecomment-775871814

Feel free to add missing API 👍 Once we agreed, I'll start working on PR.

**Comment by urugator** [comment]
- Export `_allowStateChangesStart/End`
- https://github.com/mobxjs/mobx/issues/2541

**Comment by mweststrate** [comment]
The new decorators seem to be able to fit in a minor. Still, once they're out and stable for a while, it might be nice to push for a new major to remove the legacy decorators (and the `makeObservable` based api's?) to have a single uniform mechanism and make everything a bit leaner

**Comment by kubk** [comment]
Closed in favor of https://github.com/mobxjs/mobx/issues/3796
