### ISSUE TITLE
Render function does not run on @observable change

### ISSUE THREAD

**Issue by windkomo** [mobxjs/mobx#366]
Hello, I'm having an issue with the following code:

```javascript
import React from 'react';
import { observable, action } from 'mobx';
import { observer } from 'mobx-react';

import Item from './Item';

@observer
export default class ItemList extends React.Component {
    @observable selectedItem = null;

    handleItemSelect (item) {
        this.selectedItem = item;
    }

    render () {
        const { items } = this.props;

        return (
            <div>
                <ul>
                    { items.map(item =>
                            <Item
                                item={ item }
                                key={ item.id }
                                onItemSelect={ this.handleItemSelect.bind(this, item) }
                                selected={ this.selectedItem && this.selectedItem.id === item.id }
                            />) }
                </ul>
            </div>
        )
    }
}
```

`Item` component just has a `onClick` prop that is set to the passed `onItemSelect`.

Here I am just defining a list component that stores a `selectedItem` object locally.

When running this in a browser, I get the following error: 

`makeAssimilatePrototype.js:21 Uncaught TypeError: Cannot assign to read only property '__mobxLazyInitializers' of object '#<ItemList>'`

That seems to be fixed when using the `observable` function instead of the decorator `(selectedItem = observable(null))`, but the `render`  function does not run when the `handleItemSelect` function is triggered (by a click on an `Item` component).

What am I doing wrong ?

**Comment by hellectronic** [comment]
The `handleItemSelect()` changes `this.selectedTrack`. And this is not an observable and is not used in the `render()`.

**Comment by windkomo** [comment]
Yes, sorry, that is a typo, I meant `selectedItem`

**Comment by hellectronic** [comment]
Ok maybe you should provide a reasonable default for `selectedItem` instead of assigning `null`. Cannot say if this is a problem for mobx.

**Comment by windkomo** [comment]
I just made a fiddle: https://jsfiddle.net/1agcnmvj/1/

But it works like it should on the fiddle... I don't understand why it works there and not in my local environnement...

I'm using 
```
"mobx": "^2.3.0",
"mobx-react": "^3.0.0",
"react": "^0.14.0",
```
if that helps...

**Comment by hellectronic** [comment]
Try to isolate it more in your codebase. Maybe the problem is not in the `ItemContainer`

**Comment by hellectronic** [comment]
Sorry I mean `ItemList`

**Comment by hellectronic** [comment]
Did you try assigning a reasonable default instead of `null`? If `selectedItem` is an object, just set it to `selectedItem = {}` and adapt the selected prop on `Item`.

**Comment by windkomo** [comment]
Yes wrapping in an object does not change anything unfortunately

**Comment by mweststrate** [comment]
@windkomo can you share your (dev) dependencies of your project, and the `.babelrc` file? It might have something to do with your project setup. Sounds like the decorator is not applied properly but something else is interfering.

As a workaround, `@observable x = y`, is just sugar for doing `extendObservable(this, { x: y })` in the constructor, or in your case of a React component, in `componentWillMount`.

**Comment by windkomo** [comment]
Here are my dev dependencies :

```
    "babel-core": "^6.3.26",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-1": "^6.3.13",
    "bootstrap-loader": "^1.0.10",
    "css-loader": "^0.23.1",
    "eslint": "^2.11.1",
    "eslint-plugin-react": "^5.1.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "flow-bin": "^0.27.0",
    "flow-interfaces": "^0.6.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "react-hot-loader": "^1.3.0",
    "resolve-url-loader": "^1.4.3",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.9.6",
    "webpack-dev-server": "^1.8.2"
```

And my `.babelrc` file:

```
{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": ["transform-decorators-legacy"]
}
```

I have written several stores where I'm using the @observable decorator and components where I'm using the @observer decorator though. But I'll try the workaround. Thanks !

**Comment by mweststrate** [comment]
ah i think it is react hot loader. can you try the same version as used in
the react boilerplate version?

Op di 28 jun. 2016 00:29 schreef windkomo <notifications@github.com>:

**Comment by mweststrate** [comment]
That is: `"react-hot-loader": "^3.0.0-beta.2"`

**Comment by windkomo** [comment]
Thanks a lot @mweststrate, that was it ! I hadn't noticed that my `react-hot-loader` was a bit outdated.
Thanks @hellectronic too :)
