### ISSUE TITLE
mobx-react depends on mobx-react-lite 4 which does not exists

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#3662]
mobx-react@8.0.0:
  version "8.0.0"
  resolved "https://registry.yarnpkg.com/mobx-react/-/mobx-react-8.0.0.tgz#ec3e13a19662f452f14d279c59168d94385c86f0"
  integrity sha512-WKfYrxIDmI/ysmugybfWBFnKC0li4VvLHhfZqn1y5hXkOJ0selFFZ4rO8KHWZljWrzseNGRRqatYX9X4PaDD8A==
  dependencies:
    mobx-react-lite "^4.0.0"

**Comment by urugator** [comment]
We are aware. We have issues with releasing `mobx-react-lite`:
https://github.com/mobxjs/mobx/actions/runs/4518698760/jobs/7958739332
```
info Publishing "mobx-react-lite" at "4.0.0"
🦋  error an error occurred while publishing mobx-react-lite: ELIFECYCLE mobx-react-lite@4.0.0 prepublish: `yarn build --target publish && yarn build:cjs && yarn build:es
```
Sadly it also prevents creation of release notes.

**Comment by mweststrate** [comment]
On it

**Comment by mweststrate** [comment]
@urugator #3664
