### ISSUE TITLE
Error: mobx-react-lite requires React with Hooks support

### ISSUE THREAD

**Issue by pyrokasper** [mobxjs/mobx#3697]
**Intended outcome:**

React component becomes an observer. I tried to make an `observer` component of the page in `next.js 13`, `react 18.2` with `app` directory.

**Actual outcome:**

I received an error in response: "Error: mobx-react-lite requires React with Hooks support". Which signals in my opinion that I use react < 16.8, but my project uses react 18+.
![изображение](https://github.com/mobxjs/mobx/assets/94339260/0ed9e627-595b-4374-a3d9-cc5b00f74cb7)

**How to reproduce the issue:**

https://codesandbox.io/p/sandbox/elastic-rumple-iihb2n?file=%2Fapp%2Fpage.tsx%3A5%2C30

**Comment by klaseca** [comment]
You are using new project structure next.js. By default, all components in `app` folder are server-side. Read their [docs](https://nextjs.org/docs/getting-started/react-essentials). As a quick fix, add `'use client';` directive to beginning of your file
