### ISSUE TITLE
Taro + Alipay miniprogram + Mobx v6 -> Error: [MobX] MobX requires global 'Symbol' to be available or polyfilled

### ISSUE THREAD

**Issue by Solyna** [mobxjs/mobx#3713]
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Versions**

**Comment by Solyna** [comment]
![image](https://github.com/mobxjs/mobx/assets/40814530/5aeea5a6-c770-460e-affc-5e5fc2ff0786)

![image](https://github.com/mobxjs/mobx/assets/40814530/88231736-3ec9-460f-9ed5-c9c0ec928ab7)

**Comment by mweststrate** [comment]
As per error message, MobX expects `Symbol` to be available in the browser, as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#browser_compatibility. It is available in all modern browsers, but if yours doesn't provide it, either use a polyfill (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#browser_compatibility), but typically it is an option in your build tooling, or downgrade to MobX 5.

**Comment by mweststrate** [comment]
Closing for now for a lack of relevant info, happy to reopen if more is provided.
