### ISSUE TITLE
`reaction` inside `action` is not fired

### ISSUE THREAD

**Issue by ivanabovin** [mobxjs/mobx#3716]
**Intended outcome:**

`reaction` should be fired on change.

**Actual outcome:**

`reaction` created inside an `action` is not fired after changes made in this `action`.

**How to reproduce the issue:**

See the code example in the following comment.
**Mobx 6**. I have tried `react@6.1.4`, `react@6.6.1` and `react@6.9.0`.
https://codesandbox.io/s/angry-pine-w7nc3h

```
// Expected console output
a: 2
a: 3
a: 4
b: 2
b: 3
b: 4
```

```
// Actual console output
a: 2
a: 3
a: 4
b: 4
```

**Comment by ivanabovin** [comment]
```js
import { action, makeAutoObservable, reaction } from 'mobx'

class Value {
  value = 1

  constructor() {
    makeAutoObservable(this)
  }

  increment() {
    ++this.value
  }
}

setTimeout(() => {
  const a = new Value()
  reaction(() => a.value, value => console.log('a:', value))
  a.increment()
  a.increment()
  setTimeout(() => a.increment())
})

setTimeout(action(() => {
  const b = new Value()
  reaction(() => b.value, value => console.log('b:', value))
  b.increment()
  b.increment()
  setTimeout(() => b.increment())
}))
```

**Comment by mweststrate** [comment]
The output is as expected, reactions only run at the end of any action to provide a consistent view to the outside world. It's basically like a database transaction. Without wrapping in action, any mutation becomes implicitly a tiny transaction by the lack of a bigger context that binds them together. See the first bullet here and the link in there: https://mobx.js.org/actions.html

**Comment by ivanabovin** [comment]
So is it ok, that I can't see final state of action in this example?
```
action(() => {
  const b = new Value()
  reaction(() => b.value, value => console.log('b:', value))
  b.increment()
  b.increment()
})
```
In this example, there will be no console output at all.

**Comment by mweststrate** [comment]
That is correct, `reaction` ignores the first effect run by default (unless the `{fireImmediately: true}`) is set. In other words, it will run only on the first change that happens after the reaction setup, and the reaction setup is only done at the end of the current transaction. In other words:

```
action(() => {
  const b = new Value()
  reaction(() => b.value, value => console.log('b:', value))
  b.increment()
  b.increment()
  // the tracking function "() => b.value" runs for the first time at the conclusion of the reaction (as it is a side effect)
  // so the first value it sees is `4`
})

b.increment() // this causes the first "change" to be observed by the tracking function of the reaction
```

**Comment by mweststrate** [comment]
Closing as answered
