### ISSUE TITLE
`isAction` is not working in MST

### ISSUE THREAD

**Issue by BanShan-Alec** [mobxjs/mobx#3726]
**Intended outcome:**

`isAction` can not work correctly in mobx-state-tree

**Actual outcome:**
When I use mobx-state-tree，I need judge a function is mobx action, but `isAction` always return false, I don't think my code is bad.
So I report this bug.

Now, I use a Private property `_isMSTAction` to resolve this bug, but using a Private property is not a choice for clean code.

![image](https://github.com/mobxjs/mobx/assets/44499686/d8acfe38-6beb-4121-93ff-90d31746d928)

**How to reproduce the issue:**
https://codesandbox.io/s/mobx-state-tree-playground-forked-yxhy6p?file=/src/index.js

**Versions**
"mobx": "^6.9.0", "mobx-react-lite": "^3.4.3","mobx-state-tree": "^5.1.8",

**Comment by urugator** [comment]
MST's action isn't mobx's action, it's some abstraction on the top of it. You should seek help in `mobx-state-tree` repo.
