### ISSUE TITLE
`isObservable(obj, property)` does not return true for unevaluated computed properties

### ISSUE THREAD

**Issue by jeffling** [mobxjs/mobx#373]
```
@computed get computedVal() { returns some stuff }
constructor() {
  console.log(isObservable(this, 'computedVal')) // false
  console.log(this.computedVal);  // some stuff
  console.log(isObservable(this, 'computedVal')) // true
}
```

Workaround would be to evaluate your computed property before the check.

**Comment by mweststrate** [comment]
Just double checking: you are transpiling using babel?

**Comment by jeffling** [comment]
@mweststrate we're using typescript

**Comment by mweststrate** [comment]
@jeffling I added a regression test, but the problem seems to be gone, I think it has been fixed with one of the late decorator fixes. Could you verify that?

**Comment by jeffling** [comment]
Sorry for huge delay in response. Yes, confirmed fixe :)
