### ISSUE TITLE
`isolateGlobalState: true` makes observer stop to react to store changes

### ISSUE THREAD

**Issue by antonabramovich** [mobxjs/mobx#3734]
**Intended outcome:**

`isolateGlobalState: true` should not affect whether `observer` works or not.

**Actual outcome:**

I'm not sure if this is an issue, or intended by design, but during update of mobx-react I've noticed, that `isolateGlobalState: true` breaks reactivness. It seems that `useObserver` stores its own copy of mobx global state and it does not get updated when `isolateGlobalState` is called.

**How to reproduce the issue:**

https://stackblitz.com/edit/stackblitz-starters-ba5qlf?file=src%2Findex.tsx

**Versions**

mobx: 6.10.0
mobx-react: 9.0.0

**Comment by urugator** [comment]
Fixed in mobx-react-lite@4.0.4
