### ISSUE TITLE
Proxied observable class prevents altering descriptors in getOwnPropertyDescriptor trap while proxied observable object allows.

### ISSUE THREAD

**Issue by n-lark** [mobxjs/mobx#3742]
**Intended outcome:**

Attempting to proxy an instance of a class, and within that proxy change the enumerability of specific keys through getOwnPropertyDescriptor trap.

**Actual outcome:**

See [codeSandbox](https://codesandbox.io/s/hopeful-merkle-fwtfn4?file=/src/index.ts), when proxying the instance of a class, any attempts to alter the enumerability of an observable property through  getOwnPropertyDescriptor trap throws the error:

```
TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property 'id' that is incompatible with the existing property in the proxy target
```

This works with basic objects, however something about classes prevents the altering of any enumerability through the proxy. I believe this may be intentional, due to the warning given for the linting option [safeDescriptors](https://mobx.js.org/configuration.html#linting-options):

_MobX makes some fields non-configurable or non-writable to prevent you from doing things that are not supported or would most likely break your code._

Is this a bug or is this intentional behavior? I would like to find a way to make this possible for my use case with classes, and it seems strange that objects would allow this but classes wouldn't. Any guidance is appreciated.

**How to reproduce the issue:**

See [codeSandbox](https://codesandbox.io/s/hopeful-merkle-fwtfn4?file=/src/index.ts).

Also, I apologize if this isn't really a bug and more of a question.

**Comment by urugator** [comment]
Don't have time to elaborate, but the motivation behind the behavior is mostly explained here https://github.com/mobxjs/mobx/pull/2641

**Comment by n-lark** [comment]
Thank you for the explanation @urugator, closing this.
