### ISSUE TITLE
[MobX 6] @action.bound decorator seems to not work as on v5

### ISSUE THREAD

**Issue by zibra** [mobxjs/mobx#3744]
I was trying to migrate my proejct from v5 to v6 of MobX but I've found that `@action.bound` decorator is not working as expected on v6. Is this expected?

Issue is fixed when I use `makeObservable` instead of `makeAutoObservable` + decorators. Below code works fine in v5 (with just removed store constructor.

Stack: 
* mobx: 6.10.0
* mobx-react: 9.0.0

Sample store:
```
class CounterStoreDecorated {
  @observable counter = 1

  constructor() {
    makeAutoObservable(this)
  }

  @action.bound increase() {
    this.counter += 1
  }
}

export const counterStoreDecorated = new CounterStoreDecorated()
```

Sample component:
```
export const Counter = observer(() => {
  const { counter, increase } = counterStoreDecorated

  return (
    <div>
      {counter}
      <button onClick={increase}>+1</button>
    </div>
  )
}
```

Error when button is clicked:
![obraz](https://github.com/mobxjs/mobx/assets/4493100/5a6fbb24-d621-4662-8173-3b21886c79f1)

**Comment by mweststrate** [comment]
Expected, when using decorators, don't use the "auto" version; you already
defined the observable types

**Comment by zibra** [comment]
Thanks. My mistake to use `makeAutoObservable`
