### ISSUE TITLE
Observable is getting overwritten

### ISSUE THREAD

**Issue by dnish** [mobxjs/mobx#3759]
Hey,
I've migrated from MobX v5 to v6 and having an issue with an older React component which looks like this:

```
@observer
class LoginBox extends Component {
   @observable profile = {...new UserProfile()}; // Contains fields for the user profile


   componentDidMount() {
       if(Meteor.user()) this.profile = {...Meteor.user().profile};
    }
}

```

What happens is that this.profile is never be a proxy object, it is a plain javascript object. After reading the docs I found out, that decorators are not supported anymore, so I've changed the line to this:

```
profile = observable({...new UserProfile()}); // Contains fields for the user profile
```

In this case, this.profile is a proxy object, but after calling

```
if(Meteor.user()) this.profile = {...Meteor.user().profile};
```

it gets "converted" to a plain javascript object. The observer component stops reacting on changes. I already tried to run this code within <code>runInAction</code> but there the same happens. The docs have an example where the code above should work (even with decorators), so I'm note sure if this is a normal behavior?

https://github.com/mobxjs/mobx/blob/main/packages/mobx-react/README.md#note-on-using-props-and-state-in-derivations  

// Edit:

Adding ```makeObservable(this);``` in the constructor of the Component fixes the issue, but it is not mentioned in the example above.

**Comment by mweststrate** [comment]
Turning `@observable` into `makeObservable` calls is documented in the migration guide: https://mobx.js.org/migrating-from-4-or-5.html#upgrading-classes-to-use-makeobservable
