### ISSUE TITLE
Update Canva logo on homepage

### ISSUE THREAD

**Issue by ewjmulder** [mobxjs/mobx#3772]
Hi, this is Erik from Canva, one of the gold sponsors of MobX. We noticed that the homepage still displays our old logo. We updated it 2 years ago, so could you please replace it with the new one?
Here is a good-quality image of the new logo: https://cdn-images-1.medium.com/max/1200/1*A6kkoOVJVpXPWewg8axc5w.png
Thanks!

**Comment by iChenLei** [comment]
Hi, @ewjmulder . You can submit a PR to change the logo ， the `canva` logo file is [here](https://github.com/mobxjs/mobx/blob/40f6b074ae4062ffd152604eaa3181d630a3faa0/docs/assets/canva.png)

**Comment by kubk** [comment]
Closed by https://github.com/mobxjs/mobx/pull/3780

**Comment by kubk** [comment]
It seems that the deployment didn’t work, so I’ll get back to you when it’s fixed
