### ISSUE TITLE
A warning in the console: changing (observed) observable values without using an action is not allowed

### ISSUE THREAD

**Issue by OlgaIvanovo** [mobxjs/mobx#3773]
**Intended outcome:**
I have a React functional component with div. I open it in a browser. I expect no warning in console. But I got a warning:  `Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: PageViewModel@19.ref.current 
`
```
import { observer, useLocalObservable } from "mobx-react";
import React, { ReactElement } from "react";
import { PageViewModel } from "src/demo/PageViewModel";

const PageElement = (): ReactElement => {
  const viewModel = useLocalObservable(() => new PageViewModel());
  return <div ref={viewModel.ref}>hello</div>;
};
export const Page = observer(PageElement);
```

```
import { makeObservable, observable, reaction } from "mobx";
import { createRef } from "react";

export class PageViewModel {
  public ref = createRef<HTMLDivElement>();

  public constructor() {
    makeObservable(this, {
      ref: observable,
    });
    reaction(
      () => this.ref.current,
      () => {
        console.log("ref current is not null");
      },
    );
  }
}
```

**Actual outcome:**

![Снимок экрана от 2023-10-17 11-27-12](https://github.com/mobxjs/mobx/assets/115163044/c9649f84-da17-4c12-bad6-5b809b72ef10)

**How to reproduce the issue:**

Just render this React functional component and you will see the warning in the console.

**Versions**

mobx: 6.8.0
mobx-react: 7.2.0
mobx-utils: 6.0.4
react: 8.19.4

**Comment by mweststrate** [comment]
Some concepts are being confused here, createRef is a React internal not to
be used outside components, don't combine it with observable. Instead just
store the thing directly in your model. CreateRef adds really nothing here.

**Comment by mweststrate** [comment]
I suggest to sync the React ref to the view model ref in useEffect instead
if you need the div object in your view model. I recommend to use
observable.ref as annotation when storing foreign objects like HTML
elements.

**Comment by OlgaIvanovo** [comment]
> I suggest to sync the React ref to the view model ref in useEffect instead if you need the div object in your view model. I recommend to use observable.ref as annotation when storing foreign objects like HTML elements.

sorry, I can't understand you :( 

What do you mean with "sync the React ref to the view model ref"?

I have only view model ref in my code:
`<div ref={viewModel.ref}>hello</div>;`

I don't have a React ref in my code.

Can you give a small code example to make your post clearer?

**Comment by jereklas** [comment]
You do have a react ref in your code. The first line of your PageViewModel is calling createRef from react.

However, the root of this warning is that you’re assigning an observable directly and not through an action. You could turn off strict mode (not recommended) by doing `configure({enforceActions:  “never”})`. 

Or you could make the property set go though an action.

**Comment by mweststrate** [comment]
Closing as answered / inactive. Feel free to reopen
