### ISSUE TITLE
Mobx is not working with Draft.js

### ISSUE THREAD

**Issue by khokm** [mobxjs/mobx#3779]
Hello! [Here is a sandbox](https://codesandbox.io/s/modest-sun-htpyr5?file=/src/App.js):
Select all text in rich text editor and cut it (ctrl+a, ctrl+x). Everything will work as expected.
Now, comment the `App` component definition at line 39, and de-comment the `observer-App` component definition at line 56.
Try it again. Now it shows a strange error.
Any ideas what can cause the problem here?
My current workaround is using `key={random()}` on `Editor` component, so react will replace the node completely.

**Comment by khokm** [comment]
@mweststrate 
> Both seem to be working fine for me?

Maybe there is a race condition or smth, and result may differ due to different execution order of queued tasks.
Anyway, this is how it looks on my machine in all browsers:
![Animation1](https://github.com/mobxjs/mobx/assets/25861783/8e2dc531-d2df-46b8-928c-989ebc6d0caa)

**Comment by mweststrate** [comment]
Could you share the stack trace?

**Comment by khokm** [comment]
Sadly, it's not informative enough:
```
The above error occurred in the <DraftEditorLeaf> component:
    at DraftEditorLeaf (https://htpyr5.csb.app/node_modules/draft-js/lib/DraftEditorLeaf.react.js:50:35)
    at div
    at DraftEditorBlock (https://htpyr5.csb.app/node_modules/draft-js/lib/DraftEditorBlock.react.js:77:35)
    at div
    at div
    at DraftEditorContents (https://htpyr5.csb.app/node_modules/draft-js/lib/DraftEditorContents-core.react.js:70:29)
    at div
    at div
    at div
    at DraftEditor (https://htpyr5.csb.app/node_modules/draft-js/lib/DraftEditor.react.js:176:31)
    at _c (https://htpyr5.csb.app/node_modules/mobx-react-lite/es/observer.js:41:47)
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. 
    in Unknown
```

**Comment by khokm** [comment]
It's too large and non informative. Most of the errors come from `react-dom.development`, but the exception raises here: 
```
...
(anonymous)	@	react-dom.development.js:25651
setTimeout (async)		
editOnCut	@	editOnCut.js:58
(anonymous)	@	DraftEditor.react.js:459
callCallback2	@	react-dom.development.js:4164
...
```
This is how `editorOnCut.js` looks like:
```javascript
function editOnCut(editor, e) {
  var editorState = editor._latestEditorState;
  var selection = editorState.getSelection();
  var element = e.target;
  var scrollPosition; // No selection, so there's nothing to cut.

  if (selection.isCollapsed()) {
    e.preventDefault();
    return;
  } // Track the current scroll position so that it can be forced back in place
  // after the editor regains control of the DOM.


  if (isNode(element)) {
    var node = element;
    scrollPosition = getScrollPosition(Style.getScrollParent(node));
  }

  var fragment = getFragmentFromSelection(editorState);
  editor.setClipboard(fragment); // Set `cut` mode to disable all event handling temporarily.

  editor.setMode('cut'); // Let native `cut` behavior occur, then recover control.

  setTimeout(function () { //LINE 58 THAT RAISES THE EXCEPTION
    editor.restoreEditorDOM(scrollPosition);
    editor.exitCurrentMode();
    editor.update(removeFragment(editorState));
  }, 0);
}
```

**Comment by khokm** [comment]
@mweststrate 
I found out that this problem is showing with `mobx-react-lite` 4
I did rollback to `mobx-react-lite` 3 and it works fine.

**Comment by urugator** [comment]
Seems like draftjs doesn't play well with `useSyncExternalStore`:
https://codesandbox.io/s/draftjs-useses-spg9ry

`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
seems to be a known problem with `draftjs`:
https://github.com/facebookarchive/draft-js/issues/1320

**Comment by romellem** [comment]
This is an old thread, but for other who are using DraftJS in 2024, this seems to work with React 17 and earlier, specifically when using the [`useSyncExternalStore` _shim_](https://www.npmjs.com/package/use-sync-external-store) that uses some [hacky](https://github.com/facebook/react/blob/ddcecbbebf6af3fa32a323c0591dad1f63587aeb/packages/use-sync-external-store/src/useSyncExternalStoreShimClient.js#L28) methods to get API parity.

- https://codesandbox.io/p/sandbox/draftjs-useses-forked-934q3k?file=%2Fsrc%2FApp.js
