### ISSUE TITLE
can't add property selected_book, object is not extensible

### ISSUE THREAD

**Issue by Dauth** [mobxjs/mobx#378]
I am using materials-ui SelectField as a dropdown. 

The store is being passed around using Provider component of mobx-react. 

this.props.store.updateBook is passed to the onChange of SelectField and i faced an error stated below whenever an item in the dropdown is clicked

The hackish way which works for me would be to place the updateBook method in my component itself and modify the observable selected_book from there.

Is there any ways to solve this issue?

Error
`can't add property book, object is not extensible`

Code
```
@observable selected_book = '';
@action updateBook(event, index, value){
        this.selected_book= value 
    }
```

**Comment by mweststrate** [comment]
Hi @Dauth

Can you share the rest of your file / class, or are these top level statements? `@action` and `@observable` can only be used on class members. If you want use these thing toplevel in your file you can either use:

```
const state = observable({ selected_book: ''; });
const updateBook = action((event, index, value) => {
  state.selected_book =  value
})
```

or create a boxed observable:
```
const selected_book = observable(''')
const updateBook = action((event, index, value) => {
  selected_book.set(value)
})
```

**Comment by Dauth** [comment]
This is the sample code for the store
```
import {observable, computed, action} from 'mobx';

export class Store{
    @observable selected_book;
    @action updateBook(event, index, value){
        this.selected_book = value 
    }
}


```

**Comment by mweststrate** [comment]
That looks pretty standard, is the object frozen after creation or something like that? Is it possible to produce a small reproduction?

**Comment by Dauth** [comment]
could you give me a sample code to test it out?

**Comment by Dauth** [comment]
weird i did a log for the below code inside the method updateBook and it shows false
`console.log(Object.isExtensible(this.selected_book)`
