### ISSUE TITLE
Storing a Lit template in a mobx store does not work

### ISSUE THREAD

**Issue by Artur-** [mobxjs/mobx#3837]
**Intended outcome:**

I want to store a Lit template in a mobx store, and then render it, like this
```
class TestStore {
  tpl: TemplateResult | undefined = undefined;

  constructor() {
    makeAutoObservable(this);
  }
}
const testStore = new TestStore();
testStore.tpl = html`Hello`;
render(testStore.tpl, document.body);
```

should add "Hello" to the document body.

**Actual outcome:**

Lit adds a `raw` property on the `strings` array inside the `tpl` value. This `raw` property is lost when mobx makes `tpl` observable and rendering then fails.

The main thing I want to accomplish is being able to store "rich text" in the store. I don't need it to be observable because it is not supposed to change. However, when using `makeAutoObservable`, it quickly becomes quite tedious to mark properties here and there as not observed, and I am not even sure if you can do that for nested properties.

Good outcomes would be any one that does not require any work per property but can be applied globally on the store, e.g.: 
1. MobX would preserve properties on arrays and it would just work, even when the template is observed
2. There is an easy way to plug in my own handler that in a generic way can copy the `raw` property when an array is set
3. There is an easy way to exclude all properties of type X when calling `makeAutoObservable`

**How to reproduce the issue:**

https://codesandbox.io/p/sandbox/elegant-benji-gs3zgs

**Versions**

mobx  6.12.0
lit 3.1.2

**Comment by mweststrate** [comment]
tpl should likely by an observable.ref:
https://mobx.js.org/observable-state.html#available-annotations

**Comment by urugator** [comment]
You can wrap the template in custom class:
```ts
class Ref<T> {
  constructor(readonly public value: T) // readonly because it's not observable
}
```
or in `observable.box(value, { deep: false })`
```ts
class TestStore {
  tplRef: Ref<TemplateResult> | undefined = undefined;
  tplBox = observable.box<TemplateResult | undefined>(undefined, { deep: false })`
  constructor() {
    makeAutoObservable(this);
  }
}
```
In both cases mobx will ignore the wrapped value.
```ts
const testStore = new TestStore();

testStore.tplRef = new Ref(html`Hello`);
render(testStore.tplRef.value, document.body);

testStore.tplBox.set(html`Hello`);
render(testStore.tplBox.get(), document.body);
```

**Comment by Artur-** [comment]
Thanks! Using `observable.box` or ref seem to be decent workarounds here even though you need to wrap all used templates individually
