### ISSUE TITLE
Initializing an observable class property in component constructor

### ISSUE THREAD

**Issue by hyperh** [mobxjs/mobx#384]
Following this article: https://medium.com/@mweststrate/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e#.hzcbmc5r8. Specifically [this gist](https://gist.github.com/mweststrate/67ab0a5ac4ee3df577d394273e71bc33#file-mobx-js)

I get the following errors
```
warning.js:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `AppContainer`
invariant.js:38 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AppContainer`.
```

Here's my code. I'm using Webpack if that matters.
I would like to initialize `this.matches` depending on the values of `this.props.items`.
```
import React, { PropTypes } from 'react';
import { observable } from 'mobx';
import { observer } from 'mobx-react';

/* eslint-disable */
@observer class Component extends React.Component {
  @observable matches = null;

  constructor(props) {
    super(props);
    this.matches = [1, 2];
  }

  render() {
    return (
      <div>
        <div>Vote</div>
        {this.props.items.map(item => <div>{item.name} {item.votes}</div>)}
      </div>
    );
  }
}

Component.propTypes = {
  items: PropTypes.object,
};

export default Component;
```

**Comment by mweststrate** [comment]
using babel? what does your import statement in app container look like?

Op ma 4 jul. 2016 17:07 schreef hyperh <notifications@github.com>:

**Comment by hyperh** [comment]
@mweststrate Yes, using babel. I can't tell what `AppContainer` is referring to, because webpack is building a bundle for me. 

But in terms of which component is importing this problematic component, here's the code

```
import React from 'react';
// import actions from '../actions/';
import store from '../stores/';

import Component from '../components/myThing/';

export default () => (
  <Component
    items={store.itemStore.items}
  />
);

```

**Comment by hyperh** [comment]
@mweststrate I figured it out. I had strict mode enabled. The following code works.

I just noticed that article is yours haha. Perhaps update it to point out possible issues following it if you are using strict mode. Great article by the way!

```
import React, { PropTypes } from 'react';
import { observable, action } from 'mobx';
import { observer } from 'mobx-react';

/* eslint-disable react/prefer-stateless-function */
/* eslint-disable */
@observer class Component extends React.Component {
  @observable matches = null;

  constructor(props) {
    super(props);
    
    const initMatches = action(() => this.matches = 'TEST MATCHES');
    initMatches();
  }

  render() {
    return (
      <div>
        <div>Vote</div>
        {this.props.items.map(item => <div>{item.name} {item.votes}</div>)}
        {this.matches}
      </div>
    );
  }
}

Component.propTypes = {
  items: PropTypes.object,
};

export default Component;
```

**Comment by mweststrate** [comment]
Looks fine. Usually this error refers to an import / export issue (using a
non default import for a non-default export or something like that). Have
you shareable project setup? Otherwise I suggest to set break on exceptions
in your debugger and check where it is trying to render undefined stuff

Op ma 4 jul. 2016 om 17:15 schreef hyperh <notifications@github.com>:

**Comment by mweststrate** [comment]
Ah yeas, there is an open issue for that, see #338
