### ISSUE TITLE
reaction wont be called if you watching an array

### ISSUE THREAD

**Issue by alinz** [mobxjs/mobx#385]
Hello, This might be duplicate for [this issue #214](https://github.com/mobxjs/mobx/issues/214) but I want to make sure of it.

so here's an example:

```js
const {observable, computed, reaction} = mobx;

class ChatState {
    @observable name
    @observable messages = []
}

let state = new ChatState()

reaction(() => {
  //uncomment the below code to see the trigger message
  //return state.messages.map((a) => a)
  return state.messages
}, (messages) => {
  document.write(`it's triggered<br/>`)
})

setInterval(() => {
	state.messages.push('Hello World')
}, 1000)
```

here's the [jsfiddle](https://jsfiddle.net/30ed2hff/1/) version of above code

so this code doesn't trigger the `document.write` code but if I replace `return state.messages` with `state.messages.map((a) => a)` then it starts working.

if I return `state.name` any changes to name will trigger the reaction.

**Comment by hellectronic** [comment]
Yes that is correct. The change in `messages` is only triggered when the changed elements are accessed. That's why it works with `map( a => a )`. Instead you can do a `messages.slice()`.

**Comment by hellectronic** [comment]
See this comment https://github.com/mobxjs/mobx/issues/248#issuecomment-218927070

**Comment by mweststrate** [comment]
I am currently writing a doc section that shows how this works in greater
details and with lot of examples. But rule of thumb: MobX will react to
anything you "dot into"

Op di 5 jul. 2016 om 14:47 schreef hellectronic <notifications@github.com>:

**Comment by mweststrate** [comment]
@alinz I just added docs to explain how this works better: https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/react.md

I added the above example as an explicit example: https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/react.md#incorrect-use-an-observable-but-without-accessing-any-of-its-properties

I hope that helps!

**Comment by hellectronic** [comment]
Thanks for writing this section! This should clarify a lot of beginner questions.

**Comment by alinz** [comment]
@mweststrate Awesome! 🍺

**Comment by markoshust** [comment]
Can a link to https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/react.md be added to the main readme, in a very apparent area? This one caught me up a bit today 😭

**Comment by mweststrate** [comment]
will add it!

**Comment by stevematdavies** [comment]
@mweststrate These links, appear to be broken, do you have up to date details?

**Comment by mweststrate** [comment]
https://mobx.js.org/best/react.html

**Comment by stevematdavies** [comment]
Thanks!
I still have issues, Im trying to run an async function to set sessionStorage (mobile) everytime an (favourites) array is updated. The session storage reolaces its current value with the updated array

basically

```

@observable favouriteParks = [];
// in constructor
reaction(() => {
                this.favouriteParks.length;
                return this.favouriteParks.slice() // as per your suggestion to force a reaction
            },
            parks =>
                async () => {
                    console.log(length);
                    if (parks.length > 0) {
                        console.log("setting parks item");
                        await AsyncStorage.setItem(
                            this.storageKeys.FAVOURITE_PARKS,
                            JSON.stringify(toJS(parks))
                        );
                    }
                }
);
//......
 @action addNewFavourite(id) {  this.favouriteParks.push(id) }
```

I'm still not 100% clear if this is correct, and / or why the console.log or the function is not firing.

**Comment by mweststrate** [comment]
@stevematdavies would you mind opening a new issues, rather than commenting on an old closed one? That enables you to provide the necessary context, and others to chime in as well (people not already in the convo won't see comments here).

The above should react any time you push an id. If it doesn't, please provide a small sandbox reproduction with the above (the new issue template has a link)

**Comment by stevematdavies** [comment]
OK, ill try opening another issue, I just hope someone doesn't refer back to this as a solution!
