### ISSUE TITLE
TypeScript definitions for boxed values are not correct

### ISSUE THREAD

**Issue by uweg** [mobxjs/mobx#387]
According to the documentation (https://mobxjs.github.io/mobx/refguide/boxed.html), observables created with ````observable(value)```` should have the methods get, set, intercept and observer. However, only get and set are defined in the definitions.

I think this problem affects only the type definitions because the actual object does have the members.

**Comment by mweststrate** [comment]
Thanks for reporting! Will look into it

**Comment by mweststrate** [comment]
Fixed in `2.3.5`

**Comment by uweg** [comment]
Thank you for the quick fix! Great library!
