### ISSUE TITLE
ReactNative app crashes when a component assigned to an observable object property

### ISSUE THREAD

**Issue by sunkibaek** [mobxjs/mobx#391]
Hi,

We are using mobx and stores for state management in a React Native app and it works great. But when we try to save a React Native component to an observable object property, it crashes the app. Strange enough, it only happens to a **released** app -- doesn't happen on simulator or debug mode app on device.

```
// ui-store
class UiStore {
  constructor() {

    ...

    this.modal = observable({
      isHidden: true,
      content: null, // this gets replaced with RN component
      y: new Animated.Value(this.deviceHeight),
      show: action((content) => {
        this.modal.isHidden = false;
        this.modal.content = content;

    ...
```

Any advice?
Thanks!

**Comment by mweststrate** [comment]
can you try to initialize content as asReference (null), does that help?

Op do 7 jul. 2016 06:24 schreef Sunki Baek <notifications@github.com>:

**Comment by sunkibaek** [comment]
Sure I can try that. But, then, it's not an observable any more is it?

**Comment by mweststrate** [comment]
Indeed, but a react component has all kind of internal react things in it, I don't think you should make that observable as a whole. Note that `observable` is not the same as being an `observer`. You can make individual fields (that you have defined) inside the component instance observable using `extendObservable`

**Comment by sunkibaek** [comment]
Makes sense. Thanks, that helped!
