### ISSUE TITLE
Typescript 5.6.x compatibility with ObservableSet and Observable Map

### ISSUE THREAD

**Issue by ymor** [mobxjs/mobx#3927]
**Intended outcome:**
`ObservableMap` should implement `Map` correctly and `ObservableSet` should implement `Set` correctly
 
**Actual outcome:**

```
Type 'ObservableMap<unknown, unknown>' is not assignable to type 'Map<unknown, unknown>'.
  The types returned by 'entries()' are incompatible between these types.
    Type 'IterableIterator<IMapEntry<unknown, unknown>>' is missing the following properties from type 'MapIterator<[unknown, unknown]>': map, filter, take, drop, and 9 more.
Type 'ObservableSet<unknown>' is not assignable to type 'Set<unknown>'.
  The types returned by 'entries()' are incompatible between these types.
    Type 'IterableIterator<[unknown, unknown]>' is missing the following properties from type 'SetIterator<[unknown, unknown]>': map, filter, take, drop, and 9 more.

```

**How to reproduce the issue:**
https://www.typescriptlang.org/play/?target=99&ts=5.6.2#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0wFk8wAaFDbfIzAZU3gF84AzKCEOAchAioAHrwDcAKHEBjCADt08AcLJgAXHBUAeAK6yA1rIgB3WVV0HjsgHxwAvHFmYj1LLgLEVACgCUE6XIU4JSEmGHVQnX1DExt7R2c0VzpiUJ8JIA

Seems this might be relevant https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#iterator-helper-methods

No errors in Typescript 5.5.x

**Versions**
mobx@6.13.2

**Comment by Weffe** [comment]
Just ran into this issue too. I think we need to update ObservableMap to match the new structure for `.entries()` with the new iterator helpers.

**Comment by tonyraoul** [comment]
Started working on a potential fix [here](https://github.com/mobxjs/mobx/pull/3935)
keen for your feedback.
