### ISSUE TITLE
Mocha : "[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer"

### ISSUE THREAD

**Issue by AshCoolman** [mobxjs/mobx#393]
I'm using mocha, enzyme and react-native.

I get this warning in my test output:

```
  <Main />
    empty
[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These methods should never throw exceptions as MobX will usually not be able to recover from them. Please enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'Main#.render()'
      ✓ throws error

```

**Question:**

The component works fine, the test passes, but I'm not sure how to find out exactly what the error is. When testing in the IOS sim, I can use the *react-native debugger* to  "_'Pause on (caught) exceptions' in your debugger to find the root cause_".

What options do I have to achieve the same within mocha tests?

Thanks!

**More details:**

The component:

```
/* eslint react/prefer-stateless-function: 0*/
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { observer } from 'mobx-react/native';
import { WasExpectingError } from '../libs/helpers/errors/WasExpectingError';

@observer
class Main extends Component {

  render() {
    if (!this.props.store) {
      throw new WasExpectingError('store to be an object', this.props['store']);
    }

    const calendars = this.props.store.calendars;
    return (
      <View >
        <Text>{'calendars:'+calendars.length} </Text>
      </View>
    );
  }
}

export default Main;

```

The test:

```
/* eslint no-unused-expressions: 0*/
import React from 'react';
import { shallow } from 'enzyme';
import { expect } from 'chai';
import { Main } from '../';
import WasExpectingError from '../../libs/helpers/errors/WasExpectingError';

describe('<Main />', ()=> {
  describe('empty', ()=> {
    it('throws error', ()=> {
      expect(()=> shallow(<Main />)).to.throw(WasExpectingError, /store to be an object/);
    });
  });
});

```

**Comment by mweststrate** [comment]
Actually nothing is wrong here. You throw an exception from your component's render. MobX will usually freeze the component after that, so hence it prints a warning. But the throw here was intentional so in principle nothing is wrong here, the warning is just superflous. Feel free to reopen #186 if you want an option to supress this error?

**Comment by AshCoolman** [comment]
Ok coming back to this 24hrs later I must of somehow got in my head MobX would "block" the error output. As MobX is just saying "*Gulp* now I die...",  that seems like great behaviour.
