### ISSUE TITLE
Gitbook Request

### ISSUE THREAD

**Issue by g2graman** [mobxjs/mobx#397]
Is it possible to publish the pdf for the gh-pages github overview/reference?
@mweststrate @tetsuo

**Comment by hustcer** [comment]
+1 for pdf / mobi / epub version ebooks.
Thanks !!!

**Comment by g2graman** [comment]
@mweststrate @tetsuo

**Comment by andykog** [comment]
[Generating eBooks and PDFs](http://toolchain.gitbook.com/ebook.html)

**Comment by andykog** [comment]
@g2graman, why did you close the issue? My link wasn't meant to say that you should generate it yourself.

**Comment by g2graman** [comment]
@andykog Apologies, I had assumed.

**Comment by hustcer** [comment]
@andykog Actually I have tried that before, it just didn't work. There were some errors, maybe need some special config ?

**Comment by g2graman** [comment]
It worked for me, I just went to the `gh-pages` branch, went into the `docs` folder and did `gitbook pdf ./ ./mobx.pdf` after `npm install -g gitbook-cli && gitbook install --gitbook=2.4.3`

**Comment by hustcer** [comment]
@g2graman I have done the same thing, they just got hang up, none of pdf / mobi / epub could be generated.

**Comment by hustcer** [comment]
```bash
hustcer@~/github/books/mobx/docs$ gitbook mobi ./ ./mobx.mobi
info: 10 plugins are installed
info: loading plugin "github"... OK
info: loading plugin "ga"... OK
info: loading plugin "disqus"... OK
info: loading plugin "edit-link"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 39 pages
info: found 16 asset files
```
Hanging here for years...

**Comment by hellectronic** [comment]
@hustcer had the same issue. Do a `npm install svgexport -g` and then try again.

**Comment by andykog** [comment]
Not sure we should provide those formats as this will require installing additional soft, thus can make updating docs harder.
One can generate mobi/ePub/mobi as described here https://toolchain.gitbook.com/ebook.html using `gh-pages` branch.
@mweststrate, please reopen this issue if you are ok with installing “ebook-convert from Calibre”, svgexport (npm)...

**Comment by apurvaojas** [comment]
Hi guys,

I am getting the following errors: 

error while generating page "README.md" 
Error: Error converting [file].svg into [file].png

Any Idea..?

**Comment by liu-xiao-cui** [comment]
@apurvaojas  remove the <img> tags in README.md file and try again.
