### ISSUE TITLE
React@19.0.0 mobx-react-lite@4.0.7 ﻿ Could not resolve dependency

### ISSUE THREAD

**Issue by guokaigdg** [mobxjs/mobx#3986]
Versions
React： 19.0.0
mobx-react-lite： 4.0.7

![jietu-1733823823960](https://github.com/user-attachments/assets/dd801b33-b176-4baa-8299-76ff1cf418c3)

**Comment by OriBenZaken** [comment]
The issue also occurs with mobx-react library.
<img width="689" alt="image" src="https://github.com/user-attachments/assets/ab728d95-3263-4046-9442-fdf6d0d13b13">

**Comment by mweststrate** [comment]
We're working on testing against React 19. As a quick work around, I'd recommend to either use suggested flags, and/or patch-package the mobx-react-lite/package.json and add the version.

**Comment by mweststrate** [comment]
See #3985  for progress
