### ISSUE TITLE
ObservableMap/ObservableArray broken 2.3.5 in desktop Safari 9.1.1

### ISSUE THREAD

**Issue by jlaxson** [mobxjs/mobx#406]
Similar to #401, ObservableMap creates an ObservableArray with null initialValue that hits the safari .  Seems like master would fix, although I'm not sure how to get npm to build/use it straight from github.  Can I second a request for cutting a minor version with that fix?

**Comment by andykog** [comment]
ObservableMap was really broken in `2.3.5`, sorry for inconvenience, published version `2.3.6`.
