### ISSUE TITLE
deprecate changelog and use github releases to enumerate changes in releases

### ISSUE THREAD

**Issue by capaj** [mobxjs/mobx#407]
I think it is a better practice, certainly one more accepted in OSS projects to use github release for change logs. Markdown file is other way to do it, which works, but I think there are couple of reasons for switching:

1. no changelog.md in the repo means there is less noise in the git commit timeline
2. no changelog.md means saving precious bytes on installing- currently 19433 bytes. If Mobx ever reaches popularity of React itself, amounts of traffic saved are big
3. nicer flow of creating new releases for the library authors

If you still aren't convinced and want to keep using markdown, then at least would be nice to add it into .npmignore. When I clone MobX 2.3.6 I don't need the full changelog burried somwhere in my node_modules folder.

Note that the release 2.3.6 already has a github release- this is because @andykog forgot to add a tag and when I noticed the missing tag I used github release to add a tag instead of adding regular git tag. Hope it's okay, since it cannot be deleted now(unless we would delete the tag).

**Comment by Keats** [comment]
Using github releases as changelog seem stricly inferior to having a changelog file afaik. Can I access it without internet if I cloned the repo?

Generating changelog from commits is (imo) a better plan, something like https://github.com/clog-tool/clog-cli but it requires forcing a commit message style.

Agree on the .npmignore though

**Comment by mweststrate** [comment]
@Keats Hmm `CHANGELOG.md` is added automatically, I didn't specifiy it in `package.json`'s `files` section.

**Comment by capaj** [comment]
> Can I access it without internet if I cloned the repo?

No, but do you really need to when you have the whole git history?
I certainly prefer to look for changes in git history.

@mweststrate npm picks up md files by default I think.

**Comment by mweststrate** [comment]
Decided to keep it as is. Mainly because it better benefits my workflow, updating the changelog immediately when I change something :) Otherwise I might forget subtle change details. Thanks for the suggestion nonetheless.
