### ISSUE TITLE
Suggestion needed: How do I do this with @computed/autorun

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx#409]
I have a form which needs to do a bunch of validations on a set of observable properties. I am tracking the validity of the form with a `@computed` **isValid** property. However I want to skip the validation the first time and only when an observable prop is changed after the first load of the form. 

Could you please how this scenario can be accomplished ?

**Comment by pavanpodila** [comment]
I was able to achieve this with the `autorun` and tracking the first run with a flag (`skipValidation`). Is the following the right approach ?

```js
@observable validation = null;
    skipValidation = true; // Skip first time validation
    setupValidation() {
        this.disposer = autorun('validation', ()=> {
            const {
                action,
                quantity,
                symbol,
            } = this;

            if (this.skipValidation) {
                this.skipValidation = false;
                return;
            }

            validate({
                action,
                quantity,
                symbol,
            }).then(
                success=> {
                    this.validation = null;
                },
                error=> {
                    this.validation = error;
                });

        });

    }
```

**Comment by mweststrate** [comment]
@pavanpodila just introduce a new observable `@observable isChangedByUser = false`, and use that in your rendering as well, something like `className={this.isValid && this.isChangedByUser ? "error" : "ok"`

**Comment by mattruby** [comment]
I'd take a look at reaction.  That would not run the first time by
default.  You way want a flag per field or something to mark that the field
has been manipulated before you bother validating it.

On Thu, Jul 14, 2016 at 2:54 PM, Pavan Podila <notifications@github.com>
wrote:

> I was able to achieve this with the autorun and tracking the first run
> with a flag (skipValidation). Is the following the right approach ?
>
> @observable validation = null;
>     skipValidation = true; // Skip first time validation
>     setupValidation() {
>         this.disposer = autorun('validation', ()=> {
>             const {
>                 action,
>                 quantity,
>                 symbol,
>             } = this;
>
>             if (this.skipValidation) {
>                 this.skipValidation = false;
>                 return;
>             }
>
>             validate({
>                 action,
>                 quantity,
>                 symbol,
>             }).then(
>                 success=> {
>                     this.validation = null;
>                 },
>                 error=> {
>                     this.validation = error;
>                 });
>
>         });
>
>     }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mobxjs/mobx/issues/409#issuecomment-232773566>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAIrcn5o968-Zft4i-stnj_kygO0KgDLks5qVpPZgaJpZM4JMq7K>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by pavanpodila** [comment]
Thanks @mweststrate, @mattruby. Surprisingly my earlier choice of `autorun` is holding up quite well. I will definitely take a look at `reaction` and also explore the MobX API a little more.

@mweststrate I have lots of fields and forms and doing the same for every field looks tedious. Also some of the validations are asynchronous and I am using a separate observable to track the result of validation. But overall the combination of a tracked `observable` and an `autorun` is worked well so far!

**Comment by mweststrate** [comment]
@pavanpodila Btw, for inspiration, under https://mobxjs.github.io/mobx/faq/related.html, section libraries, there are 3 examples of form libs build with MobX

**Comment by pavanpodila** [comment]
Great. Thanks for the tips!

Thanks,
Pavan
