### ISSUE TITLE
polymer 

### ISSUE THREAD

**Issue by joeblew99** [mobxjs/mobx#412]
mobx looks really good.

i was wondering if anyone has started an integration with polymer ?

**Comment by mweststrate** [comment]
Personally no experience with polymer, and it seems not too much other people either. There is no ready-to-use integration available, but note that MobX is in general applicable to any JS environment. The clue of integration MobX in a UI framework is general to put the code that is responsible for rendering in an `autorun` and hooking up the correct lifecycle methods for cleanup purposes. (this has been applied successfully already to quite a number of frameworks like deku, preact, inferno, meteor, jquery, angular). So if you want to give it a shot, feel free to ask any more detailed question about how to approach this. The gitter channel is probably more appropiate for this: https://gitter.im/mobxjs/mobx

**Comment by ivanrod** [comment]
I've started an integration with Polymer in [this repo](https://github.com/ivanrod/polobx). 
It's a state manager for Polymer, powered by MobX.

**Comment by mweststrate** [comment]
A gist I created a while back: https://gist.github.com/mweststrate/b4ebb27d7c4dcb7e3a37090b91490da7
