### ISSUE TITLE
Error with lazy intializers

### ISSUE THREAD

**Issue by bgnorlov** [mobxjs/mobx#414]
https://jsbin.com/pefutiyidu/2/edit?html,js,console,output
Basically when @observable decorator applied it resolves in a lazy manner so some fields which instantiating other stores does not execute immediately - they executes when first access to that field happens and it happens exactly in render method and it cause error ``` Invariant failed: It is not allowed to change the state when a computed value or transformer is being evaluated. ```

**Comment by mweststrate** [comment]
This is a known issue indeed with babel transpiled decorators, see https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/pitfalls.md#observable-properties-initialize-lazily-when-using-babel for some work arounds
