### ISSUE TITLE
Observable field initializer error with parallel access

### ISSUE THREAD

**Issue by bgnorlov** [mobxjs/mobx#415]
https://jsbin.com/micajoxefu/1/edit?html,js,console,output
I got this error ```"TypeError: Cannot read property 'get' of undefined``` when tried to access to some field at the moment when observable initializer applied this field.

**Comment by mweststrate** [comment]
This relates to the other issue. You can work around it by initializing in the constructor:
```javascript
class Node extends BaseStore {
  id = Math.random().toString(36);

  @mobx.observable order = 1;
  @mobx.observable attributes;
  @mobx.observable children = [];
  @mobx.observable parent;
  constructor(obj) {
    super(obj)
    this.attributes = [new Text({node: this})]
  }
}
```
