### ISSUE TITLE
Version 2.3.7 not working with TypeScript 2.0

### ISSUE THREAD

**Issue by danfma** [mobxjs/mobx#425]
After updating to the the last version, my app broke at loading, because of just a `@observable` decorator in one class.

After downgrading to 2.3.6, everything is working again.

**Comment by arahansen** [comment]
TypeScript is still in beta. Things are bound to break. Are you sure your issue isn't TypeScript related?

**Comment by danfma** [comment]
Hey @arahansen,

Yes, I use TS for a long type. I don't know with sure if something has changed with the decorator implementation at the TS 2.0, but checking the generated code, I don´t think so. 

Anyway, if was a problem with TS, then the problem should be there when I changed to the mobx version 2.3.6, but this version is working very well with the same TS compilation (I use JSPM, so I just changed the package version and restarted the browser without recompiling).

**Comment by mweststrate** [comment]
This might very well relate to #423

**Comment by mweststrate** [comment]
Released, @danfma could you confirm that this solves the issue?

**Comment by danfma** [comment]
Ok, I will confirm to you! I just can't confirm right now! ;)

**Comment by danfma** [comment]
Ok, it's working now! Thanks! :+1:
