### ISSUE TITLE
`Atom.reportObserve` does not synchronously call `Atom.onObserved`

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#427]
Consider the following code:

```javascript

class MyStore {
  const bar = rxToMobx(Observable.of(1))
  @computed get foo () {
    return this.bar * 2
  }
}

class ObservableRx extends Atom {

  value = undefined

  constructor (observable, name) {
    super(
      name,
      () => {
        this._subscription = observable
          .subscribe(x => {
            this.value = x
            this.reportChanged()
          })
      },
      () => {
        this._subscription.unsubscribe()
        this._subscription = null
      }
    )
    this._observable = observable
      .distinctUntilChanged()
      .cache(1)
  }

  get () {
    this.reportObserved()
    // HACK
    if (!this._subscription) {
      this._observable
        .subscribe(x => {
          this.value = x
        })
        .unsubscribe()
    }
    return this.value
  }

  toJSON () {
    return this.get()
  }

  toString () {
    return `${this.name}[${this.value}]`
  }
}

export function rxToMobX (observable, name = 'rxToMobX') {
  return new ObservableRx(observable, name)
}
```

Since `onObserved` is not called synchronously through `reportObserve` the following hack needs to be added into the `get` method: 

```javascript
  get () {
    this.reportObserved()
    // HACK
    if (!this._subscription) {
      this._observable
        .subscribe(x => {
          this.value = x
        })
        .unsubscribe()
    }
    return this.value
  }
```

**Comment by mweststrate** [comment]
`onObserved` won't be called at all if your atom is not in use by some reaction. If it is called, it will be called when the first computation that uses your atom has completed and all the dependencies are registered. That happens still synchronous, but after your `get` call completes. I might standardize this approach at some point, there are quite some similar abstraction, e.g. https://github.com/mobxjs/mobx/issues/238#issuecomment-217239351

**Comment by ronag** [comment]
@mweststrate: Assuming the `get` is called inside an action. Then we end up with either returning `undefined` even though the observable has a  `startWith` or we will unnecessarily create two subscriptions directly after each other.

My workaround for now is to use a `setTimeout`, see https://github.com/mobxjs/mobx/issues/419.

**Comment by mweststrate** [comment]
Yep that is correct, I'll check whether there is a better moment semantically to invoke this event. For now I'll recommend to do the subscribing just in the get. Note that in your subscription you should call `atom.reportChanged()` to be able to make assignments to value visible to the outside world

**Comment by ronag** [comment]
> For now I'll recommend to do the subscribing just in the get. 

Wouldn't that potentially result in a leaked subscription? i.e. if it is never observed/unobserved?

> Note that in your subscription you should call atom.reportChanged() to be able to make assignments to value visible to the outside world

Not needed in the get as far as I know. The subscription in the get is just for synchronous updates, e.g. `startWith` which would happen before the return.

**Comment by mweststrate** [comment]
yep that could leak if used outside a reaction. there is a function in
extras namespace to check that from the top of my head. anyway I plan to
change the moment the event is fired to avoid this confusion and also
return a boolean from reportobserved to indicate whether anybody is
listening / tracking

Op vr 22 jul. 2016 10:24 schreef Robert Nagy <notifications@github.com>:

**Comment by mweststrate** [comment]
Would you mind testing `mobx@2.4.0-fix427`? `reportObserved` will now automatically call `onBecomeObserved` if needed. Note that that will only happen if some reactive function is currently being tracked. In that case `reportObserved()` will return true, if the function is currently not being tracked, false is returned.

cc: @danieldunderfelt I recall you reported the same issue once?

**Comment by ronag** [comment]
@mweststrate: Where is mobx@2.4.0-fix427? Can't see anything related neither on GitHub nor NPM.

**Comment by andykog** [comment]
@ronag `npm install mobx@2.4.0-fix427`

**Comment by ronag** [comment]
@mweststrate: yep, that did the trick. Thanks!

**Comment by mweststrate** [comment]
Made an official release: 4.2.1
