### ISSUE TITLE
Creating custom object observables

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#428]
Is there any more information available on how to build custom observables?

e.g. I'm trying to interop with deepstream (https://www.deepstream.io/docs/) and technically I don't see any reason why a `RecordObservable` couldn't work exactly like a native mobx observable object. However, I am a bit lost as to how to achieve it. I've only got very rudimentary support:

```javascript
export class RecordAtom extends Atom {

  constructor (recordName) {
    super(
      recordName,
      () => {
        this._record = record.getRecord(this.recordName)
        this._record.subscribe(this._update, true)
      },
      () => {
        this._record.unsubscribe(this._update)
        this._record.discard()
      }
    )
    this.recordName = recordName
  }

  get = (...args) => {
    this.reportObserved()
    const rec = record.getRecord(this.recordName)
    setTimeout(() => rec.discard(), 1000)
    return rec.get(...args)
  }

  set = (...args) => {
    const rec = record.getRecord(this.recordName)
    setTimeout(() => rec.discard(), 1000)
    rec.set(...args)
  }

  _update = value => {
    this.value = value
    this.reportChanged()
  }
}
```

**Comment by mweststrate** [comment]
Could you elaborate what is not working? I'm not familiar with deepstreem, but I would expect the `get` / `set` method to use `this._record` instead of fetching and discarding fresh records each time? and probably the `set` needs to call `reportChanged()` as well?
