### ISSUE TITLE
RX Helper as Decorator

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#430]
Im not very familiar with decorators but basically I would like to be able to turn this:

```javascript
extendRxObservable(this, {
  items$: mobXToRx(() => this.search)
    .debounceTime(200)
    .switchMap(search => record.observe(`search/simple?${JSON.stringify(search)}`))
    .pluck('hits')
    .filter(hits => hits !== undefined)
    ::resolveMap(id => new GridItem(this, id))
    .startWith([])
})
```

into this:

```javascript
@rx get items() {
  return mobXToRx(() => this.search)
    .debounceTime(200)
    .switchMap(search => record.observe(`search/simple?${JSON.stringify(search)}`))
    .pluck('hits')
    .filter(hits => hits !== undefined)
    ::resolveMap(id => new GridItem(this, id))
    .startWith([])
}
```

Given https://gist.github.com/ronag/9b4b1442817fa12fa0aa34e6c9f82b5f.

Any advice?

**Comment by mweststrate** [comment]
There are subtle differences between decorators in TypeScript and babel, but the basic idea is that you write a function `function rx(prototype, propertyName, descriptor)` and you return a new or modified descriptor, (or declare a new property, depends much on where the decorator is used on

so roughly something along the lines:
```
function rx(prototype, propertyName, descriptor) {
  return {
    get: function() {
        // this decorator does nothing, just invokes the original getter
        return descriptor.get.call(this)
    }
  }
}
```

For further info see MDN on property descriptors and google for decorators, e.g.: https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841#.cc6x0ziez

**Comment by ronag** [comment]
@mweststrate: Thanks for trying. Been reading through things but I have no idea.
