### ISSUE TITLE
When is onObserved actually called for an Atom?

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#434]
I'm a bit confused as to when an Atom is actually observed? Given:

```javascript
class AudioChannel {
  @observable level = 0
}

export default class Audio {

  _atom = new Atom('audio', this._updateChannels, this._stopChannels)
  _channels = [new AudioChannel()]

  @computed get channels () {
    this._atom.reportObserved()
    return this._channels
  }

  @action _updateChannels = () => {
    this._channels[0].level += 1
    this._channelsUpdateInterval = window.requestAnimationFrame(this._updateChannels)
  }

  _stopChannels = () => {
    window.cancelAnimationFrame(this._channelsUpdateInterval)
    this._channelsUpdateInterval = null
  }
}
```

`_startChannels` is never invoked even though I have an `observer` react component calling `channels`. What am I missing?

**Comment by ronag** [comment]
While the non-lazy leaky version works fine:

```javascript
class AudioChannel {
  @observable level = 0
}

export default class Audio {

  @observable channels = [new AudioChannel()]

  constructor() {
    this._startChannels()
  }

  _startChannels = () => {
    if (this._channelsUpdateInterval) {
      return
    }
    this._updateChannels()
  }

  @action _updateChannels = (timestamp) => {
    this.channels[0].level += 1
    this._channelsUpdateInterval = window.requestAnimationFrame(this._updateChannels)
  }

  _stopChannels = () => {
    window.cancelAnimationFrame(this._channelsUpdateInterval)
    this._channelsUpdateInterval = null
  }
}
```

**Comment by mweststrate** [comment]
Can you set up a fiddle / jsbin?

**Comment by ronag** [comment]
@mweststrate: I tried. But @action doesn't seem to work: https://jsfiddle.net/wv3yopo0/367/

Tried updating to a newer mobx, https://npmcdn.com/mobx@2.2.0/lib/mobx.umd.js, but then it complains about mobxReact.

**Comment by mweststrate** [comment]
Fixed your fiddle: https://jsfiddle.net/wv3yopo0/374/. You forget to notify that your atom has changed using `reportChanged()` in update channels. Beside that there were just unrelated compile errors in your fiddle: mobx-react was loaded (twice) before react and your action wasn't bound to your instance (in contrast to the above snippet). Please do consult and fix errors in the logs next time first?
