### ISSUE TITLE
@observable properties in react component are shared by all components

### ISSUE THREAD

**Issue by jzlxiaohei** [mobxjs/mobx#439]
```javascript
@observer
export class Card extends Component {
    @observable haha={}
    hh={}
    constructor() {
        super();
    }
    render(){//...}
}
window.CardComp = Card;
```
then i write code in console 
```javascript
     new CardComp().hh == new CardComp().hh // output false
     new CardComp().haha == new CardComp().haha // output true !!!!
```

but if not in react componet,like

```javascript
export default class AA {
    @observable bb={};
}
window.AA = AA;
// ...
new AA().bb == new AA().bb // output false
```

now i use extendObservable in react component `constructor` to fixed this issue。but it is very confused

**Comment by dreambo8563** [comment]
same issue for me 

my packages
```
  "devDependencies": {
    "babel-core": "^6.0.20",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^6.0.1",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-react": "^6.0.15",
    "babel-preset-stage-0": "^6.0.15",
    "eslint": "^1.10.3",
    "eslint-plugin-react": "^3.6.2",
    "react-hot-loader": "^1.3.0",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-stage-1": "^6.5.0"
  },
  "dependencies": {
    "mobx": "^2.4.0",
    "mobx-react": "^3.5.1",
    "mobx-react-devtools": "^4.2.3",
    "react": "^0.14.6",
    "react-dom": "^0.14.6"
  }
```

**Comment by jtraub** [comment]
Could you please make a fiddle which demonstrates the issue?

I can not reproduce it with mobx 2.4.0 and mobx-react 3.5.0. See [this fiddle](https://jsfiddle.net/70wov0ae/1/)

[Class Fields](https://github.com/jeffmo/es-class-public-fields) proposal makes difference between non-derived and derived classes (ones with `extends` clause) but the difference is about mandatory `super` invocation in a derived constructor. So the issue is indeed very confusing.

**Comment by jzlxiaohei** [comment]
@jtraub tks for your response. i think it should be the issue of babel plugin, then we have different compiled code. i will debug step by step to figure it out. just keep this issue open for a while

thank you

**Comment by jzlxiaohei** [comment]
```
module: {
    loaders: [{
      test: /\.jsx$/,
      loaders: ['react-hot', 'babel'], // it is ok just after deleting react-hot 
      include: path.join(__dirname, 'src')
    }]
  }

```
it is `react-hot-loader`...  sorry for bothering
