### ISSUE TITLE
Singleton Stores communication

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx#440]
Hey all, I'm wrapping my head around the mobx workflow and have hit a snag: I've got singleton UI and Auth stores like so:

```
import ui from './stores/Ui';
import auth from './stores/Auth';

const stores = {
  ui,
  auth,
}
```
and am passing ```stores``` around via React Router. This works great, until my Auth store needs to tell the UI store to pop open the loading indicator because I'm logging in. 

I'd rather not pass the ```ui.isLoading``` observable into my ```auth.login()``` function, although that would work. In Redux land, I'd ```import``` the UI ```isLoading``` function into my Auth component and dispatch that, but now my stores are singleton instances and I can't import them.

What's a general workflow/best practise for this?

**Comment by mweststrate** [comment]
If there is a relationship between those two stores, I would just make that relationship explicit by giving one access to the other (either via a direct reference or more neatly, give the auth store a callback that can update the loading state) when you set up your stores.

**Comment by timothyallan** [comment]
As they're singletons, I ended up passing in a UI store instance into the constructor of the Auth stores (and other ones too). A lot less callbacks floating around, even if they are tightly coupled now, it's the lesser of two evils for me :)
