### ISSUE TITLE
MobX is obfuscating exceptions

### ISSUE THREAD

**Issue by tomaash** [mobxjs/mobx#445]
When my render function throws an exception (for example because I'm trying to access property of null object, which is quite common in render functions), I now get an unhelpful MobX message in console instead of the stack trace:

```
[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These functions should never throw exceptions as MobX will not always be able to recover from them. Please fix the error reported after this message or enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'JobFormComponent#.render()'
```

now, I'm able to find the root cause with debugger, but it's a nuisance. Is there a reason why MobX cannot just rethrow the exception? Those happen quite often during development, and are often a 10 second fix. Now, when I need to turn on debugger "just at the right moment" to catch the correct expection, it takes much more time and it's very frustrating. I'm whinning here because I love MobX, and I want it to be perfect :) I believe this could be a very simple fix on the MobX side, or I'm willing to help if it's not.

**Comment by tomaash** [comment]
I looked into the code.. I understand that some stuff is going on there with `derivations` that might prevent us from rethrowing the exception, but when we're already setting `hasException = true` somewhere, we could also set some exception data at least, to make the ^ warning message more helpful?

**Comment by andykog** [comment]
@tomaash mobx should rethrow exeptions. Are you using fresh mobx version? Is it possible that you didn't notice actual error in the console? Can you show minimal example if the error is really being swallowed in some cases

Duplicate: https://github.com/mobxjs/mobx-react/issues/83

**Comment by andykog** [comment]
See this example, error is being thowed https://jsfiddle.net/Sl1v3r/8xzbts9h/

**Comment by tomaash** [comment]
You are right, I cannot reproduce it. I forked it to add inject and
provider which I use, but it still works:
https://jsfiddle.net/hsyr8tzt/
Last think I did not consider is typescript.. (my project is in typescript)
I'll investigate further..

**Comment by andykog** [comment]
Closed in favour of https://github.com/mobxjs/mobx-react/issues/83
