### ISSUE TITLE
observer() type inference

### ISSUE THREAD

**Issue by testerez** [mobxjs/mobx#446]
I noticed that wrapping a stateless functional component with `observer()` returns a component typed as `React.ClassicComponentClass<any>`:
```
interface IProps { data: Data;}

const View = observer(({data}: IProps) => (
  <h2>{data.message}</h2>
));
```
So then I have no props type checking when using the component.

To fix it, I have to add an explicit generic type:
```
const View = observer<IProps>(({data}: IProps) => (
  <h2>{data.message}</h2>
));
```

It's not so bad but it's one more thing I need think about when writing the component and if I forget to do it, I have no warning and no type safety. I believe that this scenario could take advantage of the type inference with a better module definition. Am I missing something?

(I'm using ts@2 beta)

**Comment by mweststrate** [comment]
@testerez according to the types, this should be inferred indeed: https://github.com/mobxjs/mobx-react/blob/master/src/index.d.ts#L6, but somehow TS doesn't seem to well to infer this. On the other hand, I usually do get the correct autocomplete, so the precise behavior of the compiler here puzzles me a bit as well

**Comment by testerez** [comment]
Yes it seams like it should to me too. I'll try to find the time to isolate the issue and send it to the typescript team.

**Comment by mweststrate** [comment]
Closes the issue for now, feel free to reopen when there is more info
