### ISSUE TITLE
Simple observervables require @action?

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx#448]
I've got a State component which keeps track of which modules of my app are open/closed, it uses simple booleans like 

```
 @observable isEditing = false;
 @observable navOpen = false;
 @observable editorOpen = false;
```

In my code, I'm toggling them on and off by accessing the boolean directly (i.e. ```mystate.isEditing = false```), not using a @action setter... it works great, and I love the simplicity of it... but should I be using a @action for some reason?

**Comment by mattruby** [comment]
No, continue to enjoy yourself.  Actions are only required when you specify
strict mode. I would highly recommend using actions in place of
transactions.  As your application grows more complex, actions can aid in
debugging.

I can understand how you may feel concerned.  I was worried about shooting
myself in the foot when I started out with mobx.

**Comment by timothyallan** [comment]
Great! This is a pretty big app I'm refactoring, I'd hate to go back and have to do it all over again because I mucked up something simple :)

I'll look into actions/transactions more, thanks.
