### ISSUE TITLE
Improve error message when using method decorators on properties

### ISSUE THREAD

**Issue by bb** [mobxjs/mobx#449]
I just (stupidly) wrote a `@computed` decorator in front of a property like this:

    @computed urls: string[] = [];

The error message I saw in browser console was

    mobx.js:180 Uncaught TypeError: Cannot read property 'get' of undefined

**Comment by bb** [comment]
Sorry, I was intending to submit #450 directly instead of this issue which I wrote before actually fixing it.

**Comment by kyleferguson** [comment]
Not sure if the fix got changed later but I just came across this same issue, using a `@computed` decorator on a property accidentally and got the same `Cannot read property get of undefined` error.
