### ISSUE TITLE
Debugging @computed getters

### ISSUE THREAD

**Issue by robclouth** [mobxjs/mobx#451]
I'm having issues debugging @computed getters because you can't seem to set breakpoints inside getters in the Chrome debugger. Has anyone found any way around this?

**Comment by robclouth** [comment]
Ok sometimes you can and sometimes not. Is it something to do with the lazy evaluation? If i make the getter call out to another function I can set breakpoint inside the function.

**Comment by andykog** [comment]
@robclouth, `@computed` function may not reevaluate if the data it using didn't change and it is used in some reaction (not called directly)

**Comment by robclouth** [comment]
It's not that I'm setting breakpoints and they aren't getting hit, but that I can't set breakpoints at all. Chrome doesn't recognise it as a breakable section of code. Inserting console.logs shows that the code is being run.

**Comment by andykog** [comment]
@robclouth, have you tried unchecking this checkbox?
![screen shot 2016-08-01 at 14 43 25](https://cloud.githubusercontent.com/assets/6760207/17293029/66758c0c-57f6-11e6-8929-ef397834f681.png)

**Comment by andykog** [comment]
You can place `debugger;` statement in code, that's more reliable :-) Anyway, I don't think Mobx can have any influence on this behaviour

**Comment by robclouth** [comment]
I'm working with react native so sourcemaps are needed. Maybe the problem is with react native then, since it appears to fail to generate the maps properly.
