### ISSUE TITLE
Bug with toJS on ObservableArray ?

### ISSUE THREAD

**Issue by orrybaram** [mobxjs/mobx#453]
Im testing out some mobx stuff, and ran into an issue. Maybe its a bug maybe not?

#### setup
```js
export default class Store {
  @observable todos = [{id: 1, id: 2}];
  @observable searchInput = '';
  @observable showClearSearchResults = false;
  @observable test = {
    id: '1'
  }
```

#### issue
```js
 const obj = toJS(store.todos);
// =>  {
//  intercept:(handler)}
//  toJS: ()
}
const test = toJS(store.test);
// => {id: '1'}
```
The array, doesn't get converted to js. It just returns the above object. Observable objects seem to work fine. This might be on my end, but I was wondering if theres anything that sticks out?

#### screenshot
<img width="1245" alt="screen shot 2016-08-01 at 6 38 15 pm" src="https://cloud.githubusercontent.com/assets/723579/17311192/6b3511a6-5817-11e6-9a2f-12cf40750666.png">

**Comment by andykog** [comment]
@orrybaram, works fine for me: https://jsfiddle.net/Sl1v3r/6n0ohbse/

**Comment by orrybaram** [comment]
@andykog  Thanks for the reply. I think its gotta be something strange on my end. So I'm working on this https://github.com/micnews/mobx-deku/blob/master/index.js#L32. And in that line, im getting the issues i described before. The weird thing is, when I run the tests in that repo it works exactly as it should. The issues only occur when I import this module and use it in a different code base. ¯\_(ツ)_/¯ Im thinking the `Exception: TypeError: 'caller' and 'arguments' are restricted function properites and cannot...` might be a clue, but I couldnt figure it out.

**Comment by hellectronic** [comment]
Is `Array.slice()` an option?

**Comment by andykog** [comment]
@hellectronic, toJS is intendet to convert ObservableArray to Array without `.slice()` https://github.com/mobxjs/mobx/blob/master/src/api/tojs.ts#L30

**Comment by mweststrate** [comment]
Seems not to be an issue anymore? Otherwise feel free to reopen

**Comment by orrybaram** [comment]
Yeah close it!

**Comment by cellvia** [comment]
im getting this same issue... @orrybaram  how did you solve it?

**Comment by orrybaram** [comment]
@cellvia not a great answer but we were using deku and switched to react. Using the official React mobx bindings fixed our problems.

**Comment by cellvia** [comment]
ugh.  i am having all sorts of observable array issues lately like this, no idea why

**Comment by zacharyfmarion** [comment]
Yeah I am not getting the expected behavior with toJS...even when I try the fiddle it looks like it logs an object and not an array.
