### ISSUE TITLE
Can you make attributes of a class observable without using decorators?

### ISSUE THREAD

**Issue by mlesk** [mobxjs/mobx#459]
For example, without decorators a factory method to produce counter objects looks like this:

```javascript
const createCounter = () => observable({
  id: Math.random(),
  count: 0,
  increment: action('increment', function() {this.count++} ),
  decrement: action('decrement', function() {this.count--} )
})
```

I am wondering if there is a way to define Counter as a class and make it observable without using decorators:

```javascript
const Counter = observable(class Counter {
  id = Math.random();
  count = 0;
  increment = action('increment', function() {this.count++} );
  decrement = action('decrement', function() {this.count--} );
})
```

This raises the mobx error : use 'computed(expr) instead of 'observable(expr). 
Also, Counter in this context is no longer a constructor which causes a TypeError to be raised when call new Counter().

I thought that simply having a reference to an instance of a counter within an observable would cause the attributes of the counter to become observable, count in this case. But it does not, when the actions are invoked the count is changed but because it is not observable render does not get invoked. For example,

```javascript
const appState = observable({
      counter1: new Counter(),
      counter2: new Counter()
})
```

Why am I asking this question ... I was using create-react-app which does not come with support for decorators. Not that I am opposed to creating factory functions in place of classes, but I expect that doing so introduces overhead since the observable magic has to be injected into each instance rather than into the prototype. 

Appreciate any insight. And will take this opportunity to let you know that I think mobx is a really fantastic contribution. I expect to use it heavily. A big thanks to you and other contributors for making it available.

**Comment by mlesk** [comment]
Ah ... read the docs a bit more carefully ... and used extendObservable ... cannot not use Class but this works just fine. 

```Javascript
function Counter() {
  this.id = Math.random()
  extendObservable(this, {
    count: 0,
  })
  this.increment= action('increment', function() {this.count++} )
  this.decrement= action('decrement', function() {this.count--} )
}
```

**Comment by mweststrate** [comment]
@mlesk it works for classes as well, just do the `extendObservable` call in the `constructor`.

**Comment by mlesk** [comment]
Right, that makes sense, thanks.

```javascript
class Counter {
  this.id = Math.random();
  constructor() {
    extendObservable(this, {
      count: 0
    });
    this.increment= action('increment', () => this.count++);
    this.decrement= action('decrement', () => this.count--);
  }
}
```

**Comment by curran** [comment]
New syntax in version 4 https://medium.com/@mweststrate/mobx-4-better-simpler-faster-smaller-c1fbc08008da
