### ISSUE TITLE
Bug/unexpected behavior in ObservableArray.concat

### ISSUE THREAD

**Issue by mijay** [mobxjs/mobx#460]
If you decide to concatenate two observable arrays you get somewhat unexpected result:
```ts
import { observable } from "mobx";

var arr1 = observable([1, 2, 3]);
var arr2 = observable([1, 2, 3]);
var arr3 = arr1.concat(arr2);
console.log(arr3);

// hack around:
var arr3_fixed = arr1.concat(arr2.slice(0));
console.log(arr3_fixed);
```
![capture](https://cloud.githubusercontent.com/assets/697828/17400969/2741cef4-5a4b-11e6-8639-fc481b1708a5.PNG)

The issue is reproduced in 2.3.7, but judging from the code it seems that this is still an issue in 2.4.1

**Comment by mweststrate** [comment]
That is 'correct' in general, see the [docs](https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/pitfalls.md#arrayisarrayobservable123--false), `arr1.concat(arr2.slice())` is indeed the way to go

Although in this specific case MobX could actually detect it and deal with it. I'll look into that

**Comment by mijay** [comment]
Yep, I kind of understand why this is happening and why this can be correct behavior. But while using MobX this behavior caught me by surprise, so my vote would be on changing it to the more intuitive.

**Comment by mweststrate** [comment]
Released as `2.4.2`

**Comment by TuningGuide** [comment]
I just updated to 2.5.1 but the behaviour persisted. Has this been rolled back?

**Comment by danyalaytekin** [comment]
Under mobX 3.3.1, I'm having a similar problem, when `concat` is applied to an arbitrary number of arrays.  The following return a result similar to @mijay's:

```
const a = [ <ObservableArray>, <ObservableArray>, <ObservableArray>, <ObservableArray> ];
Array.prototype.concat.apply ([], a); // a problem
Array.prototype.concat.apply (...a);  // a different problem
```

**Comment by danyalaytekin** [comment]
Apologies - I've just seen the advice to use `.slice ()`.  Carry on...
