### ISSUE TITLE
Atom.reportStatic

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#461]
It would be cool if one could report to mobx that an Atom will no longer changed and no longer needs to be tracked, freeing up resources.

**Comment by mweststrate** [comment]
Mm not sure, if an atom is in use by a computed value for example, it might or might not have calculated already, so it might or might not still need the value of the atom in the future? On the other hand if the computed value is not in use, MobX will clean it up, notifying the atom that it is no longer in use through `onBecomeUnobserved`

**Comment by mweststrate** [comment]
I'm aware that this is a useful feature if you are talking about event streams, but MobX observable aren't intended to be used as event streams but as values over time (see https://github.com/mobxjs/mobx/wiki/Mobx-vs-Reactive-Stream-Libraries-(RxJS,-Bacon,-etc)) for some explanation. Values don't "stop", they just are. Or they aren't anymore when they are out of scope, but that is up to the GC. Conceptually having observables broadcast that they won't change anymore might be a feature, but I didn't see any practically usecase for this yet.

For example some object might stop being changed, so technically the component rendering it doesn't need to observe it anymore. But as long as that component is still present in the DOM, it doesn't really matter whether it is still observing the object or not.

**Comment by mweststrate** [comment]
Closing for now, feel free to re-open if anything needs to be added
