### ISSUE TITLE
More info about error: `[mobx] An uncaught exception occurred while...`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#462]

**Comment by ericclemmons** [comment]
Another helpful note, **be sure that you don't have both a `@computed` and `@observable` by the same name**.

This is common during refactoring code, and will cause this error.  Removing the duplicate definition should resolve it.

**Comment by mweststrate** [comment]
Heh nice one. Isn't the double declaration not picked up by lint / flow /
typescript btw? Or not using any of those?

Op vr 14 okt. 2016 om 04:07 schreef Eric Clemmons <notifications@github.com

**Comment by ericclemmons** [comment]
@mweststrate It seems our ESLint rules (based on those from AirBnB) don't see duplicate class properties as a problem.

Anyway, thought it was an interesting edge-case, but it's definitely user-error.

**Comment by jorilallo** [comment]
@mweststrate We just deployed a larger project using Mobx but given the complexity, also have higher amount of exceptions. We're using Bugsnag for exception tracking but unfortunately `mobx-react` completely obfuscating relevant stacktraces for errors in React components. Any recommendation for getting around this?

**Comment by mweststrate** [comment]
In principle that shouldn't happen, there is no error catching in MobX, only cleanup in `finally` blocks. So apparently something else is eating exceptions. But possible it relates to this issue: https://github.com/mobxjs/mobx-react/pull/134? That PR is in npm available as `mobx-react@3.5.8-fix134`. Could you check whether it makes a difference?

**Comment by jorilallo** [comment]
@mweststrate sure, I'll give it a try

**Comment by reisel** [comment]
working on it
