### ISSUE TITLE
Introduce isStrictModeEnabled

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#464]
deprecate `useStrict()` without arguments?

**Comment by vonovak** [comment]
imho `isStrictModeEnabled` sounds like something that could be assigned to a variable or checked in a condition like `if(isStrictModeEnabled)...`. If the intent is to enable the strict mode then I'd call it simply `enableStrictMode`

**Comment by mweststrate** [comment]
Related cause for this issue: https://github.com/zalmoxisus/mobx-remotedev/pull/3#issuecomment-236575386, `useStrict()` without arg was introduced recently, but not backward compatible so should be deprecated

**Comment by mweststrate** [comment]
Already released
