### ISSUE TITLE
requestIdleCallback

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#465]
It would be nice if mobx computed had an option to defer changes until `requestIdleCallback`. It helps when trying to keep an application responsive while a lot of things are going on.

**Comment by mweststrate** [comment]
Have you an example of this? In my experience either (trans)actions or autorunAsync suffices for these cases. Not deferring computations is one of the core principles, it guarantees that you cannot ever observe stale computed values, which avoids a lot of very subtly and hard to debug bugs.
