### ISSUE TITLE
isObservable returns false when using class constructor

### ISSUE THREAD

**Issue by matteoantoci** [mobxjs/mobx#472]
I'm using mobx with ES7 decorators to create stores.

`isObservable` returns false when using class constructor method because the `$mobx` property is delegated to the prototype and `isObservable` tests on own property only.

Is this expected?

**Comment by andykog** [comment]
@matteoantoci, yes, your class is not observable object itself. `toJS(myClassInstance)` should fail too.

**Comment by matteoantoci** [comment]
Of course the class is not the object itself, I mean, objects created with that class have the issue, while toJS works properly. I will post some code as soon as I'm at my laptop. Thanks!

**Comment by andykog** [comment]
I understand, I was meaning that you class' instances are not observable objects. They aren't inheriting from mobx internal `ObservableObject` class. So this behaviour is expected.

**Comment by matteoantoci** [comment]
Ok, got it, thanks! I'm closing this.
