### ISSUE TITLE
Doesn't observe constructed objects

### ISSUE THREAD

**Issue by gaui** [mobxjs/mobx#479]
When creating an observable array and pushing constructed objects (objects created with constructor functions) to it, `autorun` runs. However when I change values on props on those objects, `autorun` doesn't run. It's like the object is no longer observed.

Here's a JSbin with examples. Examples 1,2 and 3 all work (created with object literals). However, 4 and 5 don't (constructor function method). I'm wondering if there is an explanation why this doesn't work?

http://jsbin.com/dofunutone/edit?html,js,console

**Comment by mattruby** [comment]
http://jsbin.com/jukuku/edit?js,console

Make your Todo properties observable.

**Comment by gaui** [comment]
@mattruby Thank you. Does MobX automatically make props observable in object literals? Why not also for object constructs?

**Comment by mattruby** [comment]
For literals: try mobx.observable(whatever)
Check out my mobx examples for more help
https://github.com/mattruby/mobx-examples

**Comment by andykog** [comment]
@gaui, mobx checks if given object is plain object, so it can be safely converted to ObservableObject. It checks whether its prototype === Object.prototype or null. https://github.com/mobxjs/mobx/blob/master/src/utils/utils.ts#L57 In your case there is a class, so you should manually define observable values

**Comment by gaui** [comment]
@andykog Thank you for the explanation. However instances of classes can be data transfer objects, so I'm wondering if this should be changed?

**Comment by andykog** [comment]
I suppose, no. First problems that comes to my mind:
* We don't know what to do with the inherited properties. Copy everything from the whole prototype chain to each ObservableObject?
* It will loose it's prototype, so `observable(Object.create(Promise.prototype)) instanceof Promise` would return false
* Methods, that usually defined on prototype would be lost
* The only way I see to distinguish you custom class instance from standard one, like Set or Promise is to compare if `x.toString() === "[object Object]"` that may be not very reliable (don't know for sure).

**Comment by gaui** [comment]
@andykog Fair enough, thank you for your answer. :smiley:
