### ISSUE TITLE
Typescript: asMap() is not assignable to variable. defined as ObservableMap

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#480]
Look at examle:
```ts
const a: ObservableMap<string> = asMap();
```
This produces error: Type 'ObservableMap<{}>' is not assignable to type 'ObservableMap<string>'.
As a workaround, I should explicit type `asMap` call as this: `asMap<string>`.
This could work out of the box, if `asMap` has overload without generic like that:
```ts
declare function asMap(): ObservableMap<any>
```
Would you accept PR with that addition?

**Comment by mweststrate** [comment]
Sure go ahead. Note that the typings are compiled from the sources
