### ISSUE TITLE
SSR memory leak when using module-scoped object

### ISSUE THREAD

**Issue by jaysoo** [mobxjs/mobx#482]
Say I have a store as follows:

```js
// inside SelectionStore.js

const DEFAUL_OPTION = { id: 0, value: '' }

class SelectionStore {
  @observable options = []

  @action loadOptions(options) {
    this.options.replace([ DEFAULT_OPTION ].concat(options)) 
  }
}
```

I noticed that when the application is rendered on server-side, the SelectionStore instance cannot be garbage collected due to an event handler still reacting to `DEFAULT_OPTION`.

Is this expected? I'm trying to understand the mechanisms behind this better so I can avoid these types of memory leak in the future.

**Comment by mweststrate** [comment]
Note that this will turn `DEFAULT_OPTION` into an observable method, but beyond that this shouldn't leak. The usual suspects for memory leaks are undisposed reactions, intercepts, observes and autoruns. Beyond that everything should be cleaned up nicely.

**Comment by jaysoo** [comment]
Okay, we don't have any dangling subscriptions AFAIK, but will dig in deeper. You can close this issue for now.
