### ISSUE TITLE
Tell TypeScript API consumers when their objects are observable

### ISSUE THREAD

**Issue by spiffytech** [mobxjs/mobx#483]
Presently, calling `mobx.observable({})` returns a `T`, and there's no way for my downstream code to assert that it's passed an observable object. Knowing when an object is observable is desirable for e.g., guaranteeing my React components receive objects that will actually mutate my UI when I change them.

My PR uses TypeScript 1.4's union types to change the return type of `mobx.observable()` to `T & IObservable`. This should be fully backwards-compatible, since TypeScript will still treat the object as type `T`. But now consumers have the option of enforcing that various pieces of their apps receive observable objects by demanding a `mobx.IObservable`.

**Comment by mweststrate** [comment]
Merged PR, will be part of 2.5.2
