### ISSUE TITLE
@computed returning JSX/Components?

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx#485]
All the examples I've seen have ```computed ``` returning simple strings/values etc... I've got a map function that returns a React component which is always the same if the props don't change. Will ```computed``` handle/memoize this result, or is there a better/other way to do this in mobx?

``` 
@computed get myFancyComponentList() {
    return this.myStore.isLoading ? 'Loading'
      :
      this.myStore.items.map((item, index) => {
        return (
          <MyItemComponent
            key={item.id}
            otherParam={item.otherParam}
          />);
      });
  }
```

**Comment by mweststrate** [comment]
I experimented with this one time, by using a transformer (similar to computed) to cache the components that are rendered for each list item. That worked but didn't give big performance gains in my case (it was faster, but only 10%), as the expensive part for react turned out to be the reconciliation, and not the construction of the components. React seems to reconcile even if it gets the same instances. My code was like this:

```
const itemRendering = createTransformer(item => <MyItemComponent key={item.id} item={item} />)

render() {
  this.myStore.items.map(itemRendering)
}
```

**Comment by mweststrate** [comment]
Closed the issue as I think the question is answered? Otherwise feel free to re-open

**Comment by alisman** [comment]
Can anyone comment on the wisdom of using @computed on JSX?   It seems to me that this represents another paradigm analogous to tagging components with Observer or wrapping them with Observer tag.   The advantage of the latter is you get shouldComponentUpdate implementation.  My devs want to use @computed everywhere and I just want to make sure it's advisable.

**Comment by bsmith-cycorp** [comment]
React tends to obscure what really happens, with the goal of simplifying the user's mental model.

Intuitively it seems like avoiding re-computation of the JSX would avoid all work associated with it, but I _think_ (someone correct me if I'm wrong), React will still need to reconcile that virtual DOM tree with the real one, which according to @mweststrate is more expensive:

> as the expensive part for react turned out to be the reconciliation, and not the construction of the components

So it sounds like it's a gain, but not as big of a gain as breaking the JSX off into a separate observer component. Again, I welcome corrections if I've misspoken.

**Comment by mweststrate** [comment]
@alisman please open new issues for new questions
