### ISSUE TITLE
Support contract for classes, which can be self-converted into observable structures.

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#492]
It would be nice if mobx will check for existence of `toMobxObservable` method on a value and call it for observable variant of that value.
This would be useful for applications, which have a custom data structures, which could be used as non-observables too (in my applications, I have a custom `List`, `Map`, `Set` and other structures). Sometimes I need them as non-observable, but if they come into state, I need to control to-observable-convert. It would be easy to implement `toMobxObservable` on objects on that classes, which will return observable copy of that object.
What do you think about it?

**Comment by mattiamanzati** [comment]
I think that better solution would be to implement `Symbol.observable` on that custom data structure, and once #169 will be implemented, that would solve the problem and also provide ES7 interop!
We need to wait! :)

**Comment by mweststrate** [comment]
I think I close this issue for now? Not sure about the use case @Strate, and I can imagine it is nice, but not sure whether there is a lot of need for it? But it is quite trivial to implement, and maybe it solves certain problems very elegantly :). So with good example or PR could be reopened
