### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by andykog** [mobxjs/mobx#498]
There seems a lot of problems, with [react-hot-loader](https://github.com/gaearon/react-hot-loader) (#497, #439, #329 #366), especially for people, coming from redux
It would be nice to discover some working HMR mechanism and add a note to the docs.

**Comment by mweststrate** [comment]
Some things / fixes / workarounds are described here: http://mobxjs.github.io/mobx/best/stateless-HMR.html. But HMR definitely deserves a topic on its own. Also there is the difference between hot reloading components and hot reloading stores (the last one is hard / impossible to solve generically, but can be done like in here: https://github.com/mobxjs/mobx-reactive2015-demo/commit/ccc7e0e274653ce128484143e6f89954aae3111f

**Comment by AmazingTurtle** [comment]
@andykog has this been resolved? what is the outcome? I don't see any fair documentation on this, because I'm still having HMR issues
