### ISSUE TITLE
Typescript: make ObservableMap assignable to ES6 Map

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#503]
As for now, `ObservableMap<T>` is not assignable to ES6 `Map<string, T>`, due to incompatibles of some methods, at least because:
```
Type 'ObservableMap<T>' is not assignable to type 'Map<string, T>'.
      Types of property 'delete' are incompatible.
        Type '(key: string) => void' is not assignable to type '(key: string) => boolean'.
          Type 'void' is not assignable to type 'boolean'.
```
It sould be good to make `ObservableMap` interface be compatible to Map, for refactoring purposes.

**Comment by mweststrate** [comment]
Good point. I'll update it

**Comment by valorize** [comment]
Hi, my editor tells me that:
```
Error:(6, 2) TS2322: Type 'ObservableMap<{}>' is not assignable to type 'Map<string, ITick>'.
 Types of property 'forEach' are incompatible.
 Type '(callback: (value: {}, key: string, object: IKeyValueMap<{}>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: ITick, index: string, map: Map<string, ITick>) => void, thisArg?: any) => void'.
 Types of parameters 'callback' and 'callbackfn' are incompatible.
 Type '(value: ITick, index: string, map: Map<string, ITick>) => void' is not assignable to type '(value: {}, key: string, object: IKeyValueMap<{}>) => void'.
 Types of parameters 'map' and 'object' are incompatible.
 Type 'IKeyValueMap<{}>' is not assignable to type 'Map<string, ITick>'.
 Property 'clear' is missing in type 'IKeyValueMap<{}>'.
```

**Comment by mweststrate** [comment]
@valorize what is the code you get the error on, and the variable definition. Which version of typescript? (in your IDE, ide's sometimes pick a different version then you intended to compile with)

**Comment by arvind1234** [comment]
Hi, I am unable to assign ObservableMap object to Map. I see the following error when I try to assign:
Argument of type 'ObservableMap<Foo>' is not assignable to parameter of type 'Map<string, Foo>'.
  Property '[Symbol.toStringTag]' is missing in type 'ObservableMap<Foo>'.

I am basically trying to pass an ObservableMap<Foo> object to a function that is expecting a Map<string, Foo> - any pointers on how I can get this to work? 

I am running TS version 2.5.3

**Comment by eddiegroves** [comment]
I've come across the same thing @arvind1234 and I've raised #1204 to ask if this should still work.
