### ISSUE TITLE
[Feature Request] Bind Observables

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mobxjs/mobx#504]
Hello,

What do you think about binding/piping an observer to another ? Would it be hard.

I was trying to implement it myself but since the `observe` callback arguments are different for each type I fear I will miss some cases.

Example: 

```javascript

const a = observable({b: 1})
const b = observable({});

const unbind = a.pipe(b);

a.b = 7;
console.log(b.b); // 7
unbind();
a.b = 11;
console.log(b.b); // 7
```

**Comment by mweststrate** [comment]
Can you describe your use case for this? The idiomatic way to have one observable value synced with another  is using computed values.

**Comment by GuillaumeLeclerc** [comment]
Hello,
Our use case is quite simple. We have a global configuration state. We have a lot of components reading the global configuration. But the user may want to unbind the settings for some components, change them and eventually re sync with the global settings.
I implemented a simple bind function doing this that does not support set. But I will try with intercept. 
Thanks




-------- Message d'origine --------De : Michel Weststrate <notifications@github.com> Date : 23.08.16  01:46  (GMT-05:00) À : mobxjs/mobx <mobx@noreply.github.com> Cc : Guillaume Leclerc <guillaume.leclerc.work@gmail.com>, Author <author@noreply.github.com> Objet : Re: [mobxjs/mobx] [Feature Request] Bind Observables (#504) 
Can you describe your use case for this? The idiomatic way to have one observable value synced with another  is using computed values. 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mobxjs/mobx","title":"mobxjs/mobx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mobxjs/mobx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mweststrate in #504: Can you describe your use case for this? The idiomatic way to have one observable value synced with another  is using computed values. "}],"action":{"name":"View Issue","url":"https://github.com/mobxjs/mobx/issues/504#issuecomment-241632955"}}}

**Comment by mweststrate** [comment]
Did you check the `createViewModel` function from mobx-utils? It sounds like a quite similar problem: 

https://github.com/mobxjs/mobx-utils#createviewmodel

**Comment by GuillaumeLeclerc** [comment]
I will thanks.

I think we can close this. If it needs to be implement it's definitely not in the core library.
