### ISSUE TITLE
There 

### ISSUE THREAD

**Issue by DsMaccy** [mobxjs/mobx#506]
In documentation under the spy method:  "Spy listeners always receive one object, which has at least a type field."

This is not true.  Some of the objects will only have a property "spyReportEnd" and sometimes these objects will also have a "time" property.  Please either correct this behavior or document what it is/means.

![image](https://cloud.githubusercontent.com/assets/8063098/17874209/0056eefe-687f-11e6-9c8d-2a70c0b0cd25.png)

**Comment by mweststrate** [comment]
You are correct, I'll update the docs. A spyReportEnd is emitted to indicate the end of a nested group and always has a matching group with `spyReportStart`
