### ISSUE TITLE
Nesting observables

### ISSUE THREAD

**Issue by JakeCoxon** [mobxjs/mobx#507]
```javascript
function fakeLoadData() {
  const obs = observable(undefined);
  
  setTimeout(() => obs.set({ myData: true }, 100));
  
  return obs;
}

const state = observable({
  messages: fakeLoadData(),
  users: { me: 1 }
});

autorun(() =>
  console.log(state.messages.get()); // eventually { myData: true }
  console.log(state.users);  // { me: 1 }
)  
```

In this example both messages and users are internally an observable value, but users has been made a getter and setter. I have to write `state.messages.get()` but I'd rather have the symmetry to do `state.messages`.

I can fake it for now with a custom getter but I don't like doing this

```javascript
const state = observable({
  _messages: fakeLoadData(),
  messages() { return this._messages.get() },
  users: { me: 1 }
});

autorun(() =>
  console.log(state.messages); // eventually { myData: true }
  console.log(state.users);  // { me: 1 }
)  
```

Can I write a custom modifier like `messages: asSomething(fakeLoadData())`? I'm not sure of the implications but I suppose the setter would call set on the internal observable value rather than replacing it.

**Comment by mattiamanzati** [comment]
Uhm, I don't know much about asXXX() modifiers, but I have used getAtom() in the past to avoid this problem! :)

https://jsfiddle.net/8f8zmtu5/4/

**Comment by mweststrate** [comment]
Note that since you return the data before passing the outer object through `observable`, you can rely on the recursive nature of `observable`:

```javascript
function fakeLoadData() {
  const obs = { myData: false }
  setTimeout(() => { obs.myData = true }, 100));
  return obs;
}
```

Note that the fields have to be declared upfront (or use map) (and that this approach doesn't work for arrays). 

Personally I would set it up as:
```
const state = observable({ ... })
fakeLoadData(state)
```

**Comment by mweststrate** [comment]
@JakeCoxon did the above answers solve your issue? If so please close it :)
