### ISSUE TITLE
warning on ssr forceUpdate(...): Can only update a mounting component.

### ISSUE THREAD

**Issue by dreambo8563** [mobxjs/mobx#512]
## warning:
`
Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op. Please check the code for the Home component.
`
## reproduce steps
- install my repo which already integrate with mobx & react start kit (https://github.com/dreambo8563/RSK)
- find the route of home page

## code 
- this will works without warning
```js

export default {

  path: '/',

  async action() {
    const Home = await new Promise((resolve) => {
      require.ensure([], (require) => resolve(require('./Home').default));
    });
    // avoid the duplicated requrest from client
    if (userInfo.news.length === 0) {
      const resp = await fetch('http://jsonplaceholder.typicode.com/posts',
        {
          method: 'get',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
        });
      console.log('browser', process.env.BROWSER);
      const data = await resp.json();
      userInfo.news = data;

      if (!data) throw new Error('Failed to load the news feed.');
    }

    // to reproduce the warning
    // userInfo.fetchNews();

    return <Home />;
  },

};

```
- this will see the warning on your server output
```js
export default {

  path: '/',

  async action() {
    const Home = await new Promise((resolve) => {
      require.ensure([], (require) => resolve(require('./Home').default));
    });

    // to reproduce the warning
    userInfo.fetchNews();

    return <Home />;
  },

};

```

**Comment by mweststrate** [comment]
I could get your project to build locally, but that you get a warning makes sense, `userInfo` kicks of a fetching logic using promises, however, the results will always be in only after your `<Home />` rendering already has returned to the `renderToStaticMarkup`. So your `fetchNews()` calls seems to be a useless invocation. Maybe you intended an `await`? Although the warning could probably be avoided strictly speaking, it does seem to hint correctly that probably something is wrong.

**Comment by dreambo8563** [comment]
your analysis help a lot, thanks man
