### ISSUE TITLE
Several typos in "MobX Api Reference" documentation page

### ISSUE THREAD

**Issue by gamtiq** [mobxjs/mobx#514]
There are several typos in [MobX Api Reference](https://mobxjs.github.io/mobx/refguide/api.html):
> The condition expression will react automatically to any observables `is uses`.
> Low-level api that can `be used be used` to observe a single observable value.
> Usage: spyReport({ type: "your type", `&amp;laquo;details&amp;raquo;` data}).
> Usage: spyReportStart({ type: "your type", `&amp;laquo;details&amp;raquo;` data}).
> `expr(() => someExpression`

**Comment by mweststrate** [comment]
Note that there is an edit document button on top of each documentation page  ;-)
