### ISSUE TITLE
Wrong link on GitBook

### ISSUE THREAD

**Issue by evilj0e** [mobxjs/mobx#518]
I've got list item `8. Donate` on the sidebar with link `https://mobxjs.github.io/mobxjs.github.io/mobx/donate.html`, but it's 404 page.

Fix it, please.

**Comment by mweststrate** [comment]
On which page did you encounter this link? The link seems to be correct if I look here: http://mobxjs.github.io/mobx/

**Comment by andykog** [comment]
@mweststrate try with https :-) https://mobxjs.github.io/mobx/

**Comment by mweststrate** [comment]
hmm somehow gitbook turns `https://bla` into `https:/bla`
