### ISSUE TITLE
mobx and create-react-app

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx#521]
It would be great to see an example that works with `create-react-app` without having the need to `eject` immediately in order to support the babel `transform-decorators-legacy`.
Looks like `create-react-app` won't support legacy plugins (https://github.com/facebookincubator/create-react-app/issues/214) so it might be worth demonstrating using mobx with the OOTB `create-reach-app` configuration instead.

**Comment by mweststrate** [comment]
Tada: https://github.com/mobxjs/create-react-app-mobx/

**Comment by EQuimper** [comment]
You can the `transform-decorators-legacy` yourself in `node_modules/react-scripts/config/babel.dev.js`

![image](https://cloud.githubusercontent.com/assets/15819498/18135367/b2436808-6f6f-11e6-9263-e74cc3b6f66c.png))

**Comment by RainerAtSpirit** [comment]
Excellent, that will do the job!

**Comment by mweststrate** [comment]
@EQuimper would you mind adding that to the README of create-react-app-mobx as alternative?

**Comment by EQuimper** [comment]
@mweststrate Yes should be a good idea

**Comment by RainerAtSpirit** [comment]
@EQuimper Good workaround, but I'd rather have more examples that demonstrate using mobx with standard syntax. Projects like  e.g Aurelia have been suffered in the past by using experimental feature of jspm and babel, which later changed or where withdrawn. I'd rather have an option to not go down the same route.

**Comment by maczyt** [comment]
Now, you can push `require.resolve('babel-plugin-transform-decorators-legacy')` in node_modules/babel-preset-react-app/index.js plugins array

**Comment by pavelgarchenko** [comment]
This [article](https://www.robinwieruch.de/create-react-app-mobx-decorators/) clearly explains how to solve this issue. 

Basically it all boils down to two simple steps:

1.`npm install --save-dev babel-plugin-transform-decorators-legacy`
2. Add `babel` configuration to your `package.json`. 
```
    "plugins": [
      "transform-decorators-legacy"
    ],
```

<img width="348" alt="screen shot 2018-06-19 at 8 31 05 pm" src="https://user-images.githubusercontent.com/5801211/41614131-4f16b6d0-7400-11e8-897d-bafe76df0269.png">
