### ISSUE TITLE
Add MobX into Typings registry

### ISSUE THREAD

**Issue by gamtiq** [mobxjs/mobx#522]
It would be very helpful to add mobx into [Typings registry](https://github.com/typings/registry).
In my project I use TypeScript with JSPM. So TypeScript compiler cannot find `mobx` without typings.
I know that it is possible to install mobx typings via `typings install mobx=https://npmcdn.com/mobx/lib/mobx.d.ts` (thanks to [the comment](https://github.com/mobxjs/mobx/issues/203#issuecomment-212051015) in #203).
But having mobx in [Typings registry](https://github.com/typings/registry) would be more user-friendly (I experienced some difficulties until I found #203).

**Comment by mweststrate** [comment]
The package ships with typings out of the box which are picked up
automatically by TS 1.6+, you should not need to install typings, just
directly import from mobx

Op ma 29 aug. 2016 16:55 schreef Denis <notifications@github.com>:

**Comment by gamtiq** [comment]
Unfortunately in my case it doesn't work because of the following settings in `tsconfig.json`:
```js
  "exclude": [
    "node_modules",
    "jspm_packages"
  ],
```
MobX is installed inside `jspm_packages` by JSPM.

**Comment by mweststrate** [comment]
Argh! can typings handle non ambient typings in the first place?

Op ma 29 aug. 2016 17:17 schreef Denis <notifications@github.com>:

**Comment by mweststrate** [comment]
I doubt this is something that needs fixing on the MobX side of things (ambient declarations / decoupled declarations are really a downgrade of the current system, opening up a can of worms regarding maintenance, versioning etc). Would you mind checking whether these treads offers an acceptable solution / work around? https://github.com/Microsoft/TypeScript/issues/6012 https://github.com/jspm/jspm-cli/issues/1476

**Comment by gamtiq** [comment]
First of all I should say that I'm a newbie regarding JSPM and TypeScript.
Thank you for the links. I have scanned them quickly. It seems it is possible to work around `typings install` by using `baseUrl` and path mappings settings as described in Microsoft/TypeScript#5039 and in [Additional module resolution flags](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#additional-module-resolution-flags). I have missed this because I studied only official documentation from http://www.typescriptlang.org
I have not tried yet a possible workaround but I have the following concern in relation to it. If I understand correctly, it is necessary to specify package versions in directory names (see [this comment](https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-223092367), for example). At least it is inconvenient and can lead to problems when a package is updated. So I would stick with `typings install`.

**Comment by mweststrate** [comment]
Although I see your problem, I put a won't fix on this one. First, I suspect JSPM will address this issue. Secondly, maintaining such a typing is very tedious, especially since MobX provides good standardized typings by itself already. If someone from the community wants to submit typings though, he is welcome :)
