### ISSUE TITLE
Extends object with nested values

### ISSUE THREAD

**Issue by kevinya** [mobxjs/mobx#524]
Hello !

Is there a way to extend deeply an observable with mobx ?
When I try to use extendObservable() on a object with a nested array, that nested array is not deeply copied.

I try to keep data as I received it and compare it with the edited value so that I can ask the user leaving the page if he wants to save before leaving.

Here is an exemple:

``` javascript
import {observable, extendObservable} from "mobx";
import _ from "lodash";

class Store {
  @observable object = {};
  @observable editedObject = {};

  // $.ajax("url") returns {id:1, nested:[{id:1, value:4}, {id:2, value:8}]}
  fetchData() {
    return $.ajax("url")
      .then(data => {
        this.object = data;
        this.editedObject = extendObservable({}, data);
        console.log("object === editedObject", this.object === this.editedObject) // returns false;
        console.log("object.nested === editedObject.nested", this.object.nested === this.editedObject.nested) // returns true;
      });
  }

  isDataEdited() {
    return !_.isEqual(this.object, this.editedObject);
  }
}

new Store().fetchData();
```

Thank for your help.

**Comment by mweststrate** [comment]
I think lodash's deepCopy might help here, if you first mark the proper fields on `{}` as observable (can be initialized with `null`. observability is applied recursively, so from there on stuff should become observable as deepCopy assigns new values.
