### ISSUE TITLE
Question about observable references to other observable.

### ISSUE THREAD

**Issue by SukantGujar** [mobxjs/mobx#526]
Hi,

In my observable state tree, is it possible to have a variable refer to another observable? E.g. if my state tree looks like this -
```
"State" : {
	"Holders" : {
		"AH37502755643" : {
			"Name" : "Bruce Wayne",
			"Account" : "A146890036549"
		},
		...
	},
	"Accounts" : {
		"A146890036549" : {
			"Holder" : "AH37502755643"
		}
	}
}
```

I want to transform this state into a Mobservable and replace ID references between Account Holders and Accounts with actual references to the corresponding mobservables. E.g. in the above example data, Holders/AH37502755643/Account reference should point to the Mobservable Accounts/A146890036549 and similarly, Accounts/A146890036549/Holder should point to Holders/AH37502755643.
Quoting from [this article](https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254#.7ak1lfycr) -

> MobX can make most types of values (primitives, arrays, classes, objects, etc.) and **even (potentially cyclic) references observable** out of the box

it certainly appears to be possible, however I need to confirm it with you.

Thanks!

**Comment by mweststrate** [comment]
yep that is no problem, just make sure that you update objects instead of replacing them (as if you would do the latter the ref would still be to the old object and you are better of storing refs indeed)

**Comment by SukantGujar** [comment]
Thanks! Yes, the objects will be updated traditionally, or extended using extendObservable.

**Comment by SukantGujar** [comment]
This could be a common need for other apps too, could you please make this more explicit in the documentation :smiley: ? I am closing this issue.
