### ISSUE TITLE
Better doc and explicit dependency marking

### ISSUE THREAD

**Issue by donpark** [mobxjs/mobx#529]
I think the doc should put Array related issues front and center as it's a sore thumb of sort that sticks out after initial euphoria over mobx.

Also, I just spent an hour trying to figure out why splicing an array doesn't trigger update. Tracing the problem rabbit hole showed that there weren't any listeners. I was still scratching my head when I ran into this bit in one of the issues:

> But rule of thumb: MobX will react to anything you "dot into"

Sure enough, the array items weren't being access by the observing component but by some non-observing component down the React view hierarchy.

What would be nice is to have mobx export a _marking_ function to be used optionally like this:

```
render() {
    let list = observed(some.list) // or simply
   observed(some.other.object)
    ...
```

which would have three benefits:
1. mobx dependencies can be clearly marked
2. no unused variable warnings (this happens when render is not where mobx observables are used yet one has to access it from render with unnecessary code just to 'imply' dependency to mobx)
3. the function could "dot into" it internally to make sure updates happen.

**Comment by mweststrate** [comment]
Thanks for the feedback, i'll try to make some things more apparent in the docs. Did reading https://mobxjs.github.io/mobx/best/react.html help you to answer the above questions?

Do you have an example of point `2.`? I never needed to do that myself I think.

**Comment by donpark** [comment]
Hi, best practice section did help but not the full picture, like that 'dot into' rule. I also failed to find text making it clear whether changing array content will generate an update or not. All I found was a question by one of the users. Array really deserves a best practice section of its own.

Re point 2, non-render use of mobx typically happens with React component wrapping a non-React library like D3, Raphael or accessing DOM directly like drawing on canvas or fiddling with audio and video. Such components do most of the dynamic stuff in `componentWillUpdate` instead of `render` methods, both of which are called when `mobx-react` calls `forceUpdate`.

**Comment by SukantGujar** [comment]
Wouldn't `action` and `reaction` help in such cases?

**Comment by donpark** [comment]
They would except the same can be said about mobx-react which AFAIK is intended to reduce the need to make mobx-specific changes in React components. Likewise, seemingly cosmetic change I outlined above does the same for bridging React components. The dependency marking function from React developer perspective is just declaring what the component depends on. One could easily wrap it to avoid having to import mobx directly, making it easier to switch to another equivalent library or use as hook for other stuff.

**Comment by urugator** [comment]
I haven't put much thought to it, but may it be, that MobX should actually track not just `render` method, but "all" methods called during component update (lifecycle methods) (at least those, where it's not possible to change component state)?

**Comment by donpark** [comment]
That's a different problem which I think adding a section on how to write `react-mobx` like integration helper could be enough. Looking at the implementation, it wasn't exactly obvious.

As to the problem I was trying to communicate in this issue, what happened during TypeScript conversion I was doing over the weekend is a great example.

I had following code in my render code to make sure the React component gets updated when the `mediaList` contents change.

```javascript
render() {
    // eslint-disable-next-line
    let size = appModel.mediaList.length;
    ....
}
```

without that *dot-into* line, React component won't get updated. ESLint comment disables 'size not used' warning but I had forgotten all about it.

When I converted the component to TypeScript (just change .jsx to .tsx and see what breaks), `tsc` complained about the line because `size` wasn't used anywhere. Because I was distracted about other problems, I removed the line. An hour later, I was debugging to see why the component wasn't updating. doh.

**Comment by mweststrate** [comment]
@donpark curious: why should the component re-render if the length is not in use anywhere?

**Comment by donpark** [comment]
Right. Only key components are observers, to limit explicit mobx dependency. Subcomponents don't know anything about mobx so they're not observers.

Suggested best practice of converting mobx model to 'plain JS' conflicted with my need to allow subcomponents to change the model it received via props. So I chose the cheapest path, forcing a dot-into rule at the higher component.

**Comment by mweststrate** [comment]
hmm just using `@observer` sounds cleaner to me (you can even abstract it away in your own utility function). Because currently the mobx usage sounds 'unbalanced', you want the mobx benefits while writing (reaction to direct assignments instead of providing actions etc), but don't want to use provided the mechanisms while reading in the same component?

If you really want to keep this separation, I think it is cleaner to create your own `toView(model)` function, that works similarly to `toJS` but has setters that delegate to the original model object to force your key components etc to update
