### ISSUE TITLE
toJS returns empty object for observable arrays

### ISSUE THREAD

**Issue by cellvia** [mobxjs/mobx#530]
toJS seems to now return an empty object for observable arrays ... this wasnt the case before

console.log(obsArr.$mobx)
/* => ObservableArrayAdministration {
  mode: 0,
  array: ObservableArray {},
  owned: false,
  lastKnownLength: 2,
  interceptors: null,
  changeListeners: null,
  atom:
   BaseAtom {
     name: 'ObservableObject@6.obj.subObj.subSubArr',
     isPendingUnobservation: true,
     observers: [ [Object] ],
     observersIndexes: {},
     diffValue: 0,
     lastAccessedBy: 9,
     lowestObserverState: 0 },
  values: [ 1000, 10000 ] } */

console.log(toJS(obsArr))
// => {}

**Comment by mweststrate** [comment]
Just tried to reproduce it but couldn't: https://tonicdev.com/57c88d4e8d4e5c1600156f25/57c88d4e8d4e5c1600156f26. Could you try to setup a reproduction?

**Comment by mweststrate** [comment]
Cannot reproduce. This is such a basic case I suspect the error is somewhere else. (although, assumptions ;-))...

**Comment by jamesmccann** [comment]
@mweststrate I've been able to reproduce this when the observable array is nested within an object within an array, e.g.

```js
var m = require("mobx")

var obj = {
  nested: {
    prop: 'Test',
    arrayProp: [1, 2]
  }
}

var objs = [obj]

console.log(m.toJS(m.observable(obj)))
console.log(m.toJS(m.observable(objs)))
```

Will produce:

```js
{ nested: { prop: 'Test', arrayProp: [ 1, 2 ] } }
[ { nested: { prop: 'Test', arrayProp: [Object] } } ]
```

Is this expected behaviour?

**Comment by mweststrate** [comment]
@jamesmccann can you JSON.stringify first, or use console.dir? `console.log` doesnt print deeply nested structures

**Comment by jamesmccann** [comment]
@mweststrate can confirm works fine with JSON.stringify, must have been another issue and the console had led me to wrongly thinking it was this. Cheers :)
