### ISSUE TITLE
Preserving source type in toJS return value

### ISSUE THREAD

**Issue by jimkyndemeyer** [mobxjs/mobx#543]
The current toJS implementation has the following signature:

```
typescript
function toJS(source: any, detectCycles?: boolean, __alreadySeen?: [any, any][]): any;
```

I'd like to see it return the same type as it takes as source, so I don't have to cast the return value:

``` typescript
function toJS<T>(source: T, detectCycles?: boolean, __alreadySeen?: [any, any][]): T;
```

I tested with TypeScript 1.8, and the signature change seems compatible with existing code as TypeScript simply infers T.

**Comment by mweststrate** [comment]
Closed, as this will be added to 3.0
