### ISSUE TITLE
Bug in Ten minute introduction to MobX and React

### ISSUE THREAD

**Issue by hgeldenhuys** [mobxjs/mobx#544]
I think there might be something wrong with the first demo in the introduction, maybe I'm wrong but it looks like a copy-paste issue in the code?
<img width="631" alt="mobx__ten_minute_introduction_to_mobx_and_react" src="https://cloud.githubusercontent.com/assets/179999/18353380/c1426a52-75af-11e6-87f0-8404f86f23ba.png">

**Comment by andykog** [comment]
@hgeldenhuys, what exactly you think is wrong?

**Comment by hgeldenhuys** [comment]
Oh nevermind, I didn't see existing Todo's were being changed. A quick read through I expected 4 different Todos
