### ISSUE TITLE
Using @observable with modifiers

### ISSUE THREAD

**Issue by VolCh** [mobxjs/mobx#547]
There are not examples neither [here](https://mobxjs.github.io/mobx/refguide/observable-decorator.html)  , nor [there](https://mobxjs.github.io/mobx/best/decorators.html).

After severar attempts I found that works: 
`
class SomeClass {
  @observable property = asMap({}); 
}
`
Is there more declarative way like @observable(asMap()) (inspired by serializr)?

**Comment by urugator** [comment]
Afaik currently not. You might want to check #211

**Comment by mweststrate** [comment]
Closing this one in favor of #211, but thanks for the feedback! I agree, it would be cleaner :)
