### ISSUE TITLE
Cannot Use mobX with Rails using rails-assets.org

### ISSUE THREAD

**Issue by ankitrg** [mobxjs/mobx#555]
I am trying to require mobX using rails-assets.org into my rails project. I can use react, but I am facing error when doing the same for mobX.

The site [mobX on rails-asset](https://rails-assets.org/#/components/mobx) gives an error that
`This component's bower.json does not specify which assets to include`, can you please help me with this?

I don't know if this is the right place to post this, but can you guide me?

**Comment by andykog** [comment]
@ankitrg, I'm not familiar with rail-asset, but I think this won't work, as compiled files are not available in git, see https://github.com/mobxjs/mobx#bower-support and #85

**Comment by mweststrate** [comment]
Closed for inactivity
