### ISSUE TITLE
Support for sparse array index assignments

### ISSUE THREAD

**Issue by mbohgard** [mobxjs/mobx#557]
Are there any plans (or is it even possible?) to support index assignments higher than length of the array? Like `observableArray[new Date().getTime()] = { ... }` or is the official workaround to use a Map instead?

**Comment by andykog** [comment]
@mbohgard, Its not currently possible to implement this until proxies get wide browsers support. You're right, you should use Map for this.

**Comment by mbohgard** [comment]
@andykog I see, thank you for the clarification.
