### ISSUE TITLE
@action decorator can't be applied on setter method?

### ISSUE THREAD

**Issue by anatoo** [mobxjs/mobx#562]
I wrote the following code but not work on `mobx@2.5.1`. `@action` decorator can't be applied on setter method?

```
class Rect {
  @observable _width = 0;
  @observable _height = 0;
  @action set size({width, height}) {
    this._width = width;
    this._height = height;
  }
}

const rect = new Rect();
rect.size = {width: 10, height: 20}; // throw Error "[mobx] Invariant failed: It is not allowed to assign new values to @action fields"
```

Thanks.

**Comment by andykog** [comment]
@anatoo, from mobx docs:
> Usage:
* `action(fn)`
* `action(name, fn)`
* `@action classMethod`
* `@action(name) classMethod`
* `@action boundClassMethod = (args) => { body }`
* `@action(name) boundClassMethod = (args) => { body }`

**Comment by andykog** [comment]
> can't be applied on setter method?

What is setter _method_? Setter is a class property, not a method.

**Comment by anatoo** [comment]
@andykog Thanks to the quick response. 
Do you have any reason that does not support `@action` decorator on setter? 
I just want to know the reason.

**Comment by andykog** [comment]
@anatoo, the idea of actions is to explicitly define subset of methods, that are allowed to modify state. In my subjective opinion, making setters to be actions is a move in the opposite direction. 

Although it can be done like this: `set size({width, height}) { runInAction('set size', () => { this._width = width; this._height = height; }) }`. I don't like it either, see #331

**Comment by anatoo** [comment]
@andykog OK, I got it. Thanks!

**Comment by scriby** [comment]
I also tried to apply `@action` to a setter today.

I think it makes perfect sense when you're just exposing a simple field via a getter/setter combo, like so:

```
private _width: number;

get width() {
  return this._width;
}

@action
set width(value: number) {
  this._width = value;
}
```

If I can't mark the setter with `@action`, then it requires one of the following patterns, which are all undesirable:

```
private _width: number;

getWidth() {
  return this._width;
}

@action
setWidth(value: number) {
  this._width = value;
}
```

```
private _width: number;

get width() {
  return this._width;
}

@action
setWidth(value: number) {
  this._width = value;
}
```

```
private _width: number;

get width() {
  return this._width;
}

@action
private setWidth(value: number) {
  this._width = value;
}

set width(value: number) {
this.setWidth(value);
}
```

**Comment by cameronbraid** [comment]
Your introduction states "MobX is unopinionated about how user events should be handled"

Seems like making @action work with setter would be less opinionated :)

**Comment by mweststrate** [comment]
when using `@computed` on a getter, the setter will automatically be an action. beyond that you can use `runInAction` if you want a normal setter to act like as action.

And preferably, don't respond to issues that are closed for over a year to avoid sending notifications to people not dealing with the problem anymore.
