### ISSUE TITLE
add name metadata modifier

### ISSUE THREAD

**Issue by amir-arad** [mobxjs/mobx#572]
When I'm creating mobx instances, all instances are nameless. in the dev-tools I see objects named `"ObservableObject@505"` and such, although I may refer to them as `shoppingCart_5` (for instance) anywhere else in the code.
Injecting a custom instance name(incl. global id) will allow for better debugging experience as the object will be better linked to the application's logic. 

I.M.O a new `name` modifier (which accepts object and name arguments) that opts out of auto-generating the object's name can be a nice addition.

**Comment by mweststrate** [comment]
There are now explicit factory methods for each type of observable in mobx 3, which take a name as second argument, such as `observable.object(props, name)`

Closing this issue as mobx@3.0.0-rc.1 is now available, which addresses this issue. Changelog: https://github.com/mobxjs/mobx/blob/mobx3/CHANGELOG.md#300. The changes in more details: https://github.com/mobxjs/mobx/pull/725/files. Feel free to re-open if questions arise!
