### ISSUE TITLE
add "spy" functionality for mobx types

### ISSUE THREAD

**Issue by cellvia** [mobxjs/mobx#573]
Recently I have had the need to check not only if a property is a computed, but also if its a computed with a custom setter.

There are currently a few convenience methods for checking if a property of an object is an observable, but it would be nice if there was something more robust elaborating on the type and special properties , kind of like how "spy" is for events.

something maybe like...

```
spyProp(obj, "prop")
{
    type: "computed",
    hasSetter: true,
    hasObservers: false,
    ...
}

spyProp(computed)
{
    type: "boxedComputed",
    hasSetter: false,
    hasObservers: true,
    ...
}
```

etc

**Comment by mweststrate** [comment]
@cellvia `mobx@2.6.0` added `isComputed`, so you can now use `isComputed(obj, "prop")` and `isObservable(obj, "prop")`. That should suffice to address these issues I think. Whether an observable has observers can be determined by using the utilities from the `extras` namespace, e.g. https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#extrasgetdependencytree

**Comment by mweststrate** [comment]
Closing this issue for now, for the lack of further requests for this feature.
