### ISSUE TITLE
Strategies for more granular control over @computed

### ISSUE THREAD

**Issue by makeitrein** [mobxjs/mobx#574]
Hey all - struggling to figure out how to control when my @computed filteredTasks updates.

 ```
// My Filters...
@observable reporterFilter = "";
@observable assigneeFilter = "";
@observable propertyFilter = "";

// My tasks array...
@observable tasks = [{title: "Todo #1", assignee: "Jordan", property: "The Estate", status: "In Progress"}, ...]

// My @computed getter...
@computed get filteredTasks() {
        return this.tasks.filter(task => {
            let reporterFilter = this.reporterFilter ? this.filterOptions.reportee(task) : true;
            let assigneeFilter = this.assigneeFilter ? this.filterOptions.assignee(task) : true;
            let propertyFilter = this.propertyFilter ? this.filterOptions.property(task) : true;

            return searchFilter && reporterFilter && assigneeFilter && propertyFilter && statusFilter
        });
    };
```

So far, this is all well and good! I change any of my filters, and the @computed filteredTasks immediately updates. I change any of the tasks within my @observable this.tasks, and the @computed filteredTasks immediately updates.

However, now I am introducing a new filter, called "tabFilter", that should only update filteredTasks when it itself changes, but not when any of the tasks change. e.g. If I click on the "In Progress" tab, I would like to see all of my "In Progress" tasks. If I modify the status of a task to "Complete", I do not want to see the task disappear! I want to wait until I switch to another tab, before the "tabFilter" should filter my tasks again.

I am unsure about what is the recommended way to address this dilemma. Perhaps another @observable tasksForActiveTab? Is this a use case for a reaction? 

Many thx,
Jordan

**Comment by urugator** [comment]
I believe there are two options:

1)
As you suggested, introduce an observable field (`tabTasks`), which holds tasks filtered by tab filter.
Then your `filteredTasks` will use `this.tabTasks` instead of `this.tasks`.
Now there are two ways to update `this.tabTasks` field:
a) As a reaction to tab filter change
```javascript
mobx.reaction(() => this.tabFilter, data => { 
  this.tabTasks = this.filterByTabFilter();
});
```
b) Directly when you set the tab filter:
```javascript
// In setter (supported from 2.5.0)
@observable _tabFilter = "";
@computed get tabFilter() {
  return this._tabFilter;  
}
set tabFilter(filter) {
  if (this._tabFilter !== filter) {
    this._tabFilter = filter;  
    this.tabTasks = this.filterByTabFilter();
  }   
}
// In some action
setTabFilter(filter) {
  if (this.tabFilter !== filter) {
    this.tabFilter = filter;  
    this.tabTasks = this.filterByTabFilter();
  }  
}
```

2)
Make field `tabTasks` computed and wrap filtering logic into [untracked](http://mobxjs.github.io/mobx/refguide/untracked.html)
```javascript
@computed get tabTasks() {
  const tabFilter = this.tabFilter; // this line is needed to track this.tabFilter for changes
  return untracked(this.filterByTabFilter()); // tasks are accessed but not tracked  
}
```

**Comment by makeitrein** [comment]
@urugator - many thx for providing multiple options - gave my team and I an option to determine which pattern we wanted to use for this.  I think we'll end up going with the untracked (option #2) - seems cleaner to me IMO.
