### ISSUE TITLE
@observable property objects aren't recursively observable in computed properties or reactions.

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx#575]
Hello,
I've been trying to pinpoint what's happening to me for the last hour or so but I simply cannot find why it doesn't work as it should.

My problem is simple, I have a class like this:
```ts
export class ViewStore {
    @observable currentView = {page: undefined, id: undefined}

    @computed get currentPath() {
        return this.currentView.page + this.currentView.id;
    }
}

const store = new ViewStore();
```

The problem I have is that any reaction listening to `currentPath` will not react to a `id` or a `page` change, but will do on a `currentView` change. I looked with `whyRun()` which told me that it would indeed react only to `currentView`. I looked at the content of `currentView` when running the computed property and it showed that `page` and `id` weren't indeed observable properties, when they should have been.

I debugged through the entire creation of the `currentView` observable and the `ViewStore` creation and witnessed by the end that `page` and `id` were both made observable, so it looks like that by the time I got to the `currentPath` they somehow disappeared. Everything else is here in order though.

I'm at a loss here and I don't understand what's happening, it looks like a bug but at the same time this is pretty obvious so I shouldn't be the first to see that bug if it indeed existed.

I am running the latest MobX version (as of today) and the latest Typescript nightly (but i don't think that matters here).

Thank you.

**Comment by urugator** [comment]
I use 2.3.7 without decorators and works just fine:
```javascript
class ViewStore {
  constructor() {
      mobx.extendObservable(this, {
        currentView: { page: undefined, id: undefined },
        currentPath() {
          return this.currentView.page + this.currentView.id;
        }
      });
  }
}
const store = new ViewStore();
console.log(
  mobx.isObservable(store),
  mobx.isObservable(store, "currentView"),
  mobx.isObservable(store, "currentPath"),
  mobx.isObservable(store.currentView, "page"),
  mobx.isObservable(store.currentView, "id")
);
mobx.autorun(() => {
  console.log(store.currentPath); // observe currentPath
});
store.currentView.page = "page"; // change page
store.currentView.id = "id"; // change id

/*
OUTPUT:
true true true true true
NaN
pageundefined
pageid
*/
```

**Comment by JabX** [comment]
Okay, I found out it wasn't properly working. Turns out I was somewhere, unknowingly, doing `this.currentView = {}` which was destroying the observable properties. 

So no problems with MobX, just me being stupid for not seeing that. My bad. That's good to know though.
