### ISSUE TITLE
Inquiry into autorun behavior with observable array.replce

### ISSUE THREAD

**Issue by arackaf** [mobxjs/mobx#584]
Apologies if this has been asked - I did look, but saw nothing.

Assuming arr is a standard observable array, consider:

```
autorun(() => {
    let arr = this.arr;
    debugger;
})

this.arr.replace([new F(), new F()]);
```

This does NOT cause the autorun to fire after the call to `replace`, but forcing the observable array to unroll, by calling `slice` (or similar)

```
autorun(() => {
    let arr = this.arr.slice();
    debugger;
});
this.arr.replace([new F(), new F()]);
```

does.  

Is this intended behavior?

**Comment by mweststrate** [comment]
yes, the autorun does not use any values from the array, so re-running would (should) have no effect as far as MobX can tell. In the second version, it seems that the contents of the array is relevant, so MobX will react

**Comment by arackaf** [comment]
Thanks Michael.  I guess the confusing bit is the asymmetry between primitives and arrays.  Reading the observable reference itself is enough for an autorun to subscribe for a primitive, so I had assumed it would be for an array, too.

**Comment by mweststrate** [comment]
it is actually like an object indeed

Op wo 28 sep. 2016 16:03 schreef Adam Rackis <notifications@github.com>:
