### ISSUE TITLE
CDN files are broken 

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx#592]
Pasting content of `https://cdnjs.cloudflare.com/ajax/libs/mobx/2.5.2/mobx.min.js` in a browser console throws 

```
Uncaught ReferenceError: exports is not defined
```

**Comment by mweststrate** [comment]
that seems correct. I think you need the `umd` build?
https://cdnjs.cloudflare.com/ajax/libs/mobx/2.5.2/mobx.umd.min.js

Op ma 3 okt. 2016 om 18:45 schreef Mohsen Azimi <notifications@github.com>:

**Comment by mohsen1** [comment]
oh right! Thanks!

**Comment by Mirodil** [comment]
the same issue still exists `https://cdnjs.cloudflare.com/ajax/libs/mobx/3.2.2/mobx.min.js`
