### ISSUE TITLE
Allow wrapping getter and setter of `classPropertyDecorator`

### ISSUE THREAD

**Issue by antitoxic** [mobxjs/mobx#598]
As far as I can understand the code (*which to me looks really hard to get into*) mobx does some lazy initialization logic once a class instance is created. This lazy init logic is triggered when an observable property is accessed or set for the first time.

However this prevents me and other people to add extra prop descriptors ***after*** `observable` descriptor. This really is a problem. 

For [example](https://github.com/mobxjs/mobx/pull/597) I want to a check a value before and after it's converted to observable. That should be as easy as:

```
export function myObservable(target, key, descriptor) {
    var desc = observable(target, key, descriptor)
    var set = desc.set;
    desc.set = function(initialValue) {
        set.call(this, key, initialValue)
        if (initialValue instanceof CustomArray) {
            copyCustomProperties(this[key], initialValue)
        }
    }
    return desc;
```

But it doesn't work.

**Comment by mweststrate** [comment]
yes the reason for that nasty business is to have the same behavior in both typescript and babel compiled decorators, which both implement decorators in a semantically different way. 

There are several solution to work around this
1. use `intercept`, as is done for example here: https://github.com/mweststrate/mobx-state-tree/blob/master/src/core/node.ts#L31 + https://github.com/mweststrate/mobx-state-tree/blob/50b95f1fc0ec95c23e95b9cc64a97d58c4943520/src/types/array-node.ts#L24
1. have your own descriptor applying `@observable` by leveraging `extendobservable` and only put `@myObservable` on the field. Especially if you also use a class decorators this shouldn't be too hard to setup
2. create a seperate property with a different name, with your own getter / setter (or maybe rename the original property, not sure that is possible, or leads to other problems)

**Comment by antitoxic** [comment]
What worries me is that these are all work arounds and I have to write more and more mobx-specific code when it should be possible to do it with standard js as above.

This is bad for project because it decreases readability. I also need to document all of these workarounds.

2 questions:
1. Is it possible to make the build process output 2 distributions (babel and typescript) or is it too much hassle? 
1. Can environment variable be used to check the current environemnt and not run/include specific parts. This actually can improve also mobx production built size. `if (NODE_ENV!='production) { ...warnings, messages...})` or `if (!BABEL) { ...typescript stuff...})`

**Comment by mweststrate** [comment]
the problem is not in the builds, but in the semantics. It can only be made simpler if mobx would *behave* differently when using typescript and babel. But that would support wise be a disaster.

I think the short and sweet of having it clean and straight forward is: don't use decorators in the first place (or just not the mobx ones). it is a moving spec with poor implementations. Note that you don't even have to use the property descriptors of mobx for objects, you can also boxed observables in your own descriptors

**Comment by antitoxic** [comment]
To summarize gitter discussion here:

Decorators are still encouraged to use (_as the examples in the docs widely use them_). The limitation is the composability of descriptors.

Though I believe there is some kind of problem with mobx descriptors ignoring/discarding any changes done to them. The example above shows:

```js
 var set = desc.set;
desc.set = function(initialValue) {
  console.log('THIS NEVER GETS CALLED')
  set.call(this, key, initialValue)
}
```
This should mean the descriptors object (by reference) and if it's really reused the change it should work, even if it's reapplied on instance. It seems it's not reused and mobx re-generates the descriptor again before applying it to the instance.

**Comment by antitoxic** [comment]
Anyways, I'm writing one of the suggested workarounds - boxed value with custom decorator that uses it. I will post it afterwards.

**Comment by antitoxic** [comment]
Workaround using `extendObservable` with custom `observable` decorator:

```js
const OBSERVABLES_KEY = '__observables'
function getMeta(target, key, v) {
    if (!target[OBSERVABLES_KEY]) target[OBSERVABLES_KEY] = {}
    let meta = target[OBSERVABLES_KEY];
    if (key && v && !meta.hasOwnProperty(key)) extendObservable(meta, {key: v});
    return meta;
}
export function observable(target, key) {
    return {
        configurable:true,
        get() {
            return getMeta(this)[key];
        },
        set(v) {
            var toCopy;
            if (Array.isArray(v)) {
                toCopy = []
                Object.getOwnPropertyNames(v).forEach(p => {
                    if (isNaN(p) && p != 'length') toCopy.push(p);
                })
            }
            var meta = getMeta(this);
            meta[key] = v;
            if (toCopy) {
                toCopy.forEach(p => meta[key][p] = v[p])
            }
        }
    }
}
```
