### ISSUE TITLE
mobx + draft js slowness 

### ISSUE THREAD

**Issue by giladv** [mobxjs/mobx#599]
Hi,

My project implements a draft js editor with an observable state and while on desktop it works just fine, on mobile it gets extremely slow as the draft state grows.
i've noticed that using react state solves the issue so i"m confident i"m doing something wrong on the mobx side. 

i tried using an asReference/asStructure modifiers but it still works slow.
any suggestions?

best,
Gilad

**Comment by mweststrate** [comment]
Are you using actions / transactions already? Besides that it is hard to answer the question without code :)

**Comment by giladv** [comment]
tried as follows:
```js
class Test extends Component{
   @observable state = {
      editorState: asReference({})
   };
   render(){
      return <Editor editorState={this.state.editorState} onChange={editorState => this.state.editorState = editorState} />
   }
}
```

**Comment by mweststrate** [comment]
Ho not sure if it relates, but calling your observable `state` might be dangerous as it probably accidentally hides React's own state concept.

But please elaborate on your issue. Have you a running example somewhere? Did you profile it already. Where is it slow, in the renders, or in the event handlers ....  How often is the component rendered, how quickly is onChange triggered, etc etc. Please provide a reproducible setup if you want constructive feedback on your issues :)

**Comment by mweststrate** [comment]
Closed for inactivity. Feel free to reopen
