### ISSUE TITLE
How to terminate observability?

### ISSUE THREAD

**Issue by artursgirons** [mobxjs/mobx#601]
...or how to unsubscribe all observers from observing some observable property?
so that if this property changes observers don't get triggered.
for example in case of some exception happening and component not wanting any further updates to occur even if observed prop changes after this exception.

**Comment by urugator** [comment]
I am not familiar with mobx internals, but here is my logic:
In case of react components (or autorun in general), the "subscription" is done by accessing the observables during render method (or method passed to autorun).
So to "unsubscribe" you would need to run the render again without accessing the observables.
That may seem a bit impractical, but it kinda make sense - if you use "magic" to subscribe, you have to use the same "magic" to unsubscribe...
The question is how to run render again without accessing observables, if they are needed to do the rendering.
Maybe we can actually access them, render component with current state as usually, but not to subscribe for accessed observables again, by conditionally wrapping the logic in `untracked`: 
```javascript
class MyCmp extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      subscribed: true; // you could use another observable to controll this state             
    };
  }
  _render() {
    // actual rendering logic
  }
  render() {
    if (!this.state.subscribed) {
      return untracked(() => this._render()); // http://mobxjs.github.io/mobx/refguide/untracked.html            
    }  
    return _render();
  }
}
``` 
Now switching the `subscribed` state will cause re-rendering and unsubscribing from mobx.  

Another way would be to NOT make your component an observer and control subscription/unsubscription manually by using `observe` and then use returned disposer method. 
In that case, you would have to update your react component manually in listener passed to `observer` (via `component.forceUpdate()`).  

Probably there is a way to obtain (and remove) all observers for given observable object, but I don't know if there is a public API for that.

Maybe it might be useful to provide a way for switching the observability on and off for given observable object or even globally...

**Comment by artursgirons** [comment]
@urugator thanks! Particularly rewriting render will work, but IMO it will still cause this blank render to happen, witch on server will still cause "attempting to update unmounted component" error.
And yes, I'm looking for more "native" way of "switching the observability on and off for given observable"
My current solution:
```javascript
// old
class A {
  constructor() {
    extendObservable(this, {
      observable: asReference({})
    })
  }
}
// new
class A {
  constructor() {
    this.data = observable({
      observable: asReference({})
    })
  }

  dereference() {
    this.data = observable({
      observable: asReference({})
    })
  }
}
```
But on-and-off-ing without changing object structure would be nicer.

**Comment by mweststrate** [comment]
usually questions like this indicate there is more state in play them was stored, e.g. "there was an exception". putting that state in an observable and use it to short circuit the render function is a simple and elegant solution. let me know whether it applies to your use case!

**Comment by artursgirons** [comment]
@mweststrate If you mean approach similar to what @urugator suggested then yes, it will work for not rendering content or to render `null`, but this IMO does not solve **server side** rendering issue, or maybe we are missing each others points.
Let me describe a scenario:

1. There is some state management mechanics that use MobX under the hood
2. When request comes to **server** tree of pre-fetch actions is executed.
3. There is component that depends on two fetch actions to complete (two fetch actions are issued in parallel)
4. First resolved fetch throws exception, based on that component is rendered into "error-state"
----- next is just my thoughts on some maybe-potential issues on server (if second promise is not "canceled", render is not "short-circuited", "observable-dereferenced" etc.) -----
5. Altho server side rendering via `React.renderToString()` has completed, second issued fetch-promise resolves (as not being "canceled").
6. If component (altho-in-error-state) still observes state that gets populated by second resolved fetch, it will cause attempt to rerender unmounted component on **server** which will cause react to issue "...no-op error-warning" ("short-circuited" render will not help in that case).

**Comment by artursgirons** [comment]
Should `@observer` from `mobx-react` not be used on **server**?

**Comment by mweststrate** [comment]
what is your intended server flow here? Render the first state of the component tree and be done. Because if that is the case you don't have to kick off the promises at all. But if you want to wait until both promises has settled, the `renderToString` should not be invoked until both promises have settled? E.g. use promise.all? Note that if you want to renderd based on promises [`mobxUtils.fromPromise`](https://github.com/mobxjs/mobx-utils#frompromise) might come in handy.

Note that in principle the warning is quite harmless if this is the desired behavior. I noticed that this warning is often a result of wrongly using lifecycle hooks, e.g. kicking of changes or data fetches from the `constructor` instead of from `componentWillMount`. See https://github.com/mobxjs/mobx-react#faq

See also https://www.npmjs.com/package/mobx-server-wait and https://github.com/mobxjs/mobx-react/issues/12 / https://github.com/mobxjs/mobx-react/issues/73

**Comment by artursgirons** [comment]
K! thanks!

**Comment by steven-p-walsh** [comment]
Just a comment incase this subject comes up again, transaction is the perfect utility (and semantics) for an issue I just ran into.

**Comment by mweststrate** [comment]
Note that on the server, you should simply call userStaticRendering(true)
from mobx-react package, which effectively makes all observers do nothing

Op di 27 nov. 2018 om 17:39 schreef Steven Walsh <notifications@github.com>:

**Comment by artursgirons** [comment]
[use~~r~~StaticRendering(true)](https://github.com/mobxjs/mobx-react#server-side-rendering-with-usestaticrendering)
