### ISSUE TITLE
transaction function has no try/finally block

### ISSUE THREAD

**Issue by plinyar** [mobxjs/mobx#603]
I got an exception inside a code block wrapped in [transaction](https://github.com/mobxjs/mobx/blob/6e3df706de1f1fc2408ba919559297cd0d07573e/src/core/transaction.ts#L12) function, after that reactions stopped working.
Problem was found that the function increments globalState.inTransaction and then decrements it without try/finally block.

**Comment by mweststrate** [comment]
You are right. Should be addressed here: https://github.com/mobxjs/mobx/blob/99e70d5fb6371fbb453ae117a0744d71b4df3edc/src/core/transaction.ts#L14

**Comment by mweststrate** [comment]
Fixed in `mobx@2.6.3`
