### ISSUE TITLE
Observable array: seems it is possible to get it to be true array.

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#604]
Hey @mweststrate,
what do you think about this technique:
```ts
function observableArray<T>(value: Array<T>): T {
  // 1. Take true empty array
  const newArray: Array<T> = [];
  // 2..n define properties, create hidden props such as `$mobx`, and etc..
}
let observable = observableArray([]);
Array.isArray(observable) // true
```
Is there any caveats which I don't see?

**Comment by mweststrate** [comment]
yeah the problem is that native arrays don't allow the `.length` property to be reconfigured, which make it impossible for mobx to intercept / detect changes in length
