### ISSUE TITLE
autorunAsync stops observing observable array

### ISSUE THREAD

**Issue by ppatel890** [mobxjs/mobx#611]
Hi,

I have a couple instances of autorunAysnc that stop observing an Observable array randomly. Tried to search issues, but still couldn't exactly figure it out. Restarting server returns everything to a working mode, but as more and more users start using the app, eventually fails again silently.

``` javascript
class TaskRepo {
  @observable tasks = [];

  constructor() {
  }

  create(task) {
    console.log(`creating new task with ${task}`);
    return {
      id: uuid.v4(),
      name: task.name,
      model: task.model,
      options: task.options,
      tags: task.tags
    };
  }

  add(task) {
    const newTask = this.create(task);
    this.tasks.push(newTask);
    return newTask;
  }

  update(id) {
    const task = this.get(id);
    this.remove(id);
    this.tasks.push(task);
    return this.get(id);
  }

  remove(id) {
    this.tasks = this.tasks.filter((e) => e.id != id);
  }

  _taskRepoFile() {
    return '/opt/data/tasks.json';
  }

  async _createTaskRepoFile () {
    return fs.writeFileAsync(this._taskRepoFile(), JSON.stringify([]), ENCODING);
  }

  async _loadTasks() {
    try {
      const tasks = await fs.readFileAsync(this._taskRepoFile(), ENCODING);
      this.tasks = observable(JSON.parse(tasks));
      autorunAsync(() => {
        console.log(`auto saving ${JSON.stringify(this.tasks)}`);
        this._saveTasks(this.tasks);
      }, SAVE_DELAY);
      return this.tasks;
    } catch (err) {
      if (err.code !== 'ENOENT') throw err;
      await this._createTaskRepoFile();
      return this._loadTasks();
    }
  }

  async _saveTasks(tasks) {
    await fs.writeFileAsync(this._taskRepoFile(), JSON.stringify(tasks), ENCODING);
  }
}
```

Updates to the observable array don't trigger the autorun, and new tasks aren't written to the file. I might be missing something obvious, as I am new to using mobx.

Similar situation here: 

``` javascript
   const updateClientTaskRepo = (tasks) => {
        const action = {
          type: 'TASK_REPO_SYNC',
          payload: {
            taskRepo: {
              tasks: tasks 
            }
          }
        };
        console.log(`updating client ${JSON.stringify(action)}`);
        userStream.write(`data: ${JSON.stringify(action)}\n\n`);
      };

      const disposerTasks = autorunAsync(() => {
        updateClientTaskRepo(taskRepo.tasks);
      }, SAVE_DELAY);

      const cleanUp = () => {
        disposerTasks();
        console.log('closed stream for ', sessionCookie);
      };
```

`cleanup()` is called after a user session ends, but when in broken state, initial observing never starts and autorunAsync again doesn't run.

Any help would be appreciated, thank you in advance!

**Comment by mweststrate** [comment]
Sorry for the late response. 

Note that observable arrays are not plain javascript objects, so you probably want to serialize them as `JSON.stringify(mobx.toJS(tasks))`

**Comment by ppatel890** [comment]
Thank you for the response! Will that affect if they autorunAsync will continue to observe? Both the autorunAsync calls that should update the clients and save to file initially run as expected, but then fail after more users start using the app. 

Does using mobx on the server affect anything?. All observers work fine in the client applications, just seeing these issues in the node app.

Thanks again!

**Comment by ppatel890** [comment]
Follow up question, in both of my ```autorunAsync``` calls, I use an observable array. Should I be doing ```taskRepo.tasks.slice()``` instead of just ```taskRepo.tasks```?

Just read http://mobxjs.github.io/mobx/best/react.html, and realized I an not actually using the contents of the ```taskRepo.tasks``` in the autorun.

**Comment by mweststrate** [comment]
The clue is to use your array *somehow*. so slice will iterate on the array itself, so the array is considered "being used". `toJS` will iterate the array, and all the objects it contains, so the array and all the objects contained init will be considered "being used" etc .

`taskRepo.task` isn't considered a usage of your array itself; the contents of the array is apparantly not relevant as you don't use it. That is why the slice() makes the difference.

**Comment by ppatel890** [comment]
That seems to fix it. Thank you! Will close the issue. Do you have any thoughts on why it ran fine when I only tested a few users at a time?

**Comment by ppatel890** [comment]
Hi,

Using toJS didn't seem to do the trick. Same issue as before, initially the autorun works fine, and clients are updated anytime data changes on the server. But after the number of users increases, all the autoruns stop running. Any new data pushed to the server doesn't get saved, and nothing gets automatically pushed to the clients. 

```javascript
    const disposerTasks = autorunAsync(() => {
        console.log(toJS(taskRepo.tasks));
        updateClientTaskRepo(taskRepo.tasks);
      }, SAVE_DELAY);
```

Any insights or help would be appreciated. Thank you!

**Comment by mweststrate** [comment]
Are you sure there are no exceptions eaten somewhere? Do you have a reproduction, or testable environment somewhere? Otherwise it will be hard to assist

**Comment by ppatel890** [comment]
Looks like at some point, ```globalState.inTransaction``` becomes stuck at 1, and the pendingReactions never run. Assuming there is some point where ```transactionEnd()``` never gets called for a specific transaction.

Still trying to chase down where, but here is the two places transactions are used:

```javascript
transaction(() => {
  const user = userRepo.addByLogin(login);
  const userData = userDataRepo.getOrCreate(user);
  const userSession = userSessionRepo.add(login.phoneNumber);
  resAuth.send(userSession);
});
```

```javascript
transaction(() => {
  userData.id = payload.userData.id;
  userData.phoneNumber = payload.userData.phoneNumber;
  userData.tags = payload.userData.tags;
  userData.messages = payload.userData.messages;
});
```

Let me know if anything stands out, will update when I have more info.

Thanks!

**Comment by mweststrate** [comment]
@ppatel890 ah can you check with mobx 2.6.3 ? Might be related to #603

**Comment by ppatel890** [comment]
@mweststrate Thanks! Seems like this is fixing it. Gonna do some more testing, will update/close issue if all looks good.

**Comment by mweststrate** [comment]
Note that in that case you have an exception that is eaten somewhere

**Comment by ppatel890** [comment]
yep, the transaction is in a try/catch block, and the error is essentially ignored. Thanks for the help!
