### ISSUE TITLE
[Question] Is Mobx A Fractal Architecture?

### ISSUE THREAD

**Issue by thewillhuang** [mobxjs/mobx#616]
**Is MobX considered a fractal architecture?**

> A unidirectional architecture is said to be fractal if subcomponents are structured in the same way as the whole is.

In fractal architectures, the whole can be _naively_ packaged as a component to be used in some larger application.

In non-fractal architectures, the non-repeatable parts are said to be orchestrators over the parts that have hierarchical composition.

To put it simply, can you _naively_ make a generic filter picker work with a nested component like a table that is within another component using the generic filter picker without specifying a namespace, keys, or defining a new namespace automatically?

http://staltz.com/unidirectional-user-interface-architectures.html

**Comment by mweststrate** [comment]
MobX is not an architecture, it is a data flow library. Whether it is fractal or not depends on how you design it. If you make components / stores / whatever self contained, it is fractal, if you store state globally, it is globally. To give an impression, for example the [`mobx-state-tree`](https://github.com/mobxjs/mobx-state-tree) (very much WIP) is a fractal state tree, but some people prefer a global singleton as store, which is not fractal
