### ISSUE TITLE
Type definitions are missing JSDoc comments 

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx#617]
MobX has great JSDoc comments throughout of the app but they are missing from `mobx.d.ts`. 

Not sure if TypeScript allows you to keep the comments...

**Comment by nightwolfz** [comment]
Why would they need JSDoc comments? Typescript has types...

**Comment by mohsen1** [comment]
Not just for type definition. For actual comments that explains what every function does

**Comment by mweststrate** [comment]
I think it is actually a compiler option. I probably disabled it to avoid issues where the docs get out of sync with the official docs. (in newer projects I generated the docs from the JSDocs, which is much more maintainable)

**Comment by mweststrate** [comment]
Ah the missing docs are actually a result of the indirection found in in [`mobx.ts`](https://github.com/mobxjs/mobx/blob/master/src/mobx.ts) when exporting functions. So no easy fix for this :(.
