### ISSUE TITLE
Question/Issue: Invariant failed: @computed can only be used on getter functions

### ISSUE THREAD

**Issue by dmitriid** [mobxjs/mobx#620]
## Solution for those who come here through search/google

1. Make sure your `@computed` decorator is applied to a `getter`. See this comment https://github.com/mobxjs/mobx/issues/620#issuecomment-255328500 for a small example that produces this error. (In other words: pay attention to the error message :) )

2. If it's something you've run into when running jest, see #405 (and possibly https://github.com/mobxjs/mobx/issues/405#issuecomment-232679623)

## Original issue

I have a*:

1. [x] Question. Feel free to just state your question :) For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [x] Issue. Please make sure you have the following:
  * [x] Did you check this issue wasn't filed before?
  * [x] What is your issue? Why do you thing this is not the expected behavior?
  * [x] What MobX version(s) are you using? Which browser / node / ... version?
  * [x] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for most issues.

I'm not sure if it's an issue or a question, because I might be missing something really simple. I've looked at other issues, but haven't found a proper answer.

## What happens

The following error is triggered by:

- innocent-looking invocation of a function (event if the function body is empty)
- tests

The error:

```
Invariant failed: @computed can only be used on getter functions, like: 
'@computed get myProps() { return ...; }'. It looks like it was used on a property.
```

## Library versions

```
    "mobx": "^2.5.1",
    "mobx-react": "^3.5.6",
    "typescript": "2.0.3"
```
```
> npm -v
2.15.9
> node -v
v4.6.0
```

## Code and description

Three files

- `eventStore.ts` loads events
- `appState.ts` tracks current state, current event, current ticket etc.
- `ticketView.tsx` renders everything

`TicketView` breaks

``` ts
// eventStore.ts

import Api from './../utils/api'
import {observable, computed, asStructure, action} from 'mobx'

const emptyEvent = {
  /* several fields set to initial data */
}

export class EventStore {
  @observable _event = asStructure(emptyEvent) // or just emptyEvent
  @observable loading = false

  public load(eventId: number): void {
    this.loading = true
    // an HTTP request
    Api.Events.find(eventId).then(result => {
      this._event = result.data.data.events[0]
      this.loading = false
    }).catch((e) => {
      this.loading = false
    })
  }

  @computed
  public get event() {
    return this._event
  }
}

const singleton = new EventStore()
export default singleton
```

``` ts
// appState.ts

class AppState {
  @observable
  private _currentState  = 'INIT'
  @observable
  private _currentTicket = null

  constructor() {
  }

  @computed
  public get currentState() {
    return this._currentState
  }

  @computed
  public get currentTicket() {
    return this._currentTicket
  }

  @action  // doesn't matter if action is there or not
  public updateTicket(ticketid: number) {
    this._currentTicket = ticketid
    // this.next()
  }
}

export default new AppState()
```

``` ts
// ticketListView.ts

import eventStore from '../stores/eventStore'
import {observer} from 'mobx-react/native'
import * as React from 'react'
import {style} from 'typestyle'
import appState from '../states/app_state'

@observer
class TicketItem extends React.Component<{ticket: Ticket}, {}> {
  render() {
    const className = style({color: this.props.ticket.color})

    // just providing the onClick produces the error in the browser
    return <div className={className}
                onClick={() => appState.updateTicket(1)}>
      {this.props.ticket.title}
    </div>
  }
}

export default observer(() => {
  // any access to eventStore.event produces the error
  // during test runs
  return (
    <div>
      {eventStore.event.tickets.map(
        (ticket) => <TicketItem ticket={ticket}
                                key={ticket.id} />)}
    </div>
  )
})
```

The issues:

- Run `eventStore.load(1)`. It successfully runs and populates the store
- In browser environment (Chrome 53.0.2785.143) providing `onClick` with a method call to `appState` breaks (if you remove the handler, or replace the call with `console.log(ticket)` everything works)
- During tests (jest 16.0.1) any access to `@computed` properties on `eventStore` triggers the error. Access to properties directly (such as `eventStore.loading`) works

I hope this makes sense :)

**Comment by mweststrate** [comment]
There seem to be several issues in here.

1. For the Chrome issue, can you provide some additional details,  I guess you mean that `() => appState.updateTicket(1)` breaks`. How does it breaks? Is it only in Chrome or also in e.g. Firefox? Do you have a stacktrace?

2. This seems to related to https://github.com/mobxjs/mobx/issues/405#issuecomment-232679623. Could you verify whether this already breaks? It seems Jest does something with the property definitions. Are you sure your preprocessor uses the same decorator setup? (either from .babelrc or tsconfig.json)

Does this break in Jest? With which stacktrace?
```
class A {
  @computed get dummy() { return 1 }
}
const a = new A()
a.dummy()
```

**Comment by dmitriid** [comment]
Ah, yes. These may very well be two separate issues.

1. 

Yes, if I provide `onClick = {() => appState.updateTicket(/* any value, could be a fixed value like 1 */)}` it breaks. If I remove any references to `appState.updateTicket` (for example, replace it with `console.log(ticket)` everything works.

The issue is the same in Chrome and Firefox. 

The full issue, with stacktrace. See comments for code at those lines. It's a bit mangled by webpack though. `bootstrap` is webpack's bootstrap for `require`. Mobx.js lines correspond to `mobx.js` from `node_modules/mobx/lib/mobx.js`.

```
mobx.js:2577Uncaught Error: [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. 

invariant @ mobx.js:2577
observable @ mobx.js:232
(anonymous function) @ mobx.js:2476
(anonymous function) @ mobx.js:2515
runLazyInitializers @ mobx.js:2515
isObservableObject @ mobx.js:2307
asObservableObject @ mobx.js:2163
observable @ mobx.js:414
typescriptInitializeProperty @ mobx.js:2508
set @ mobx.js:2458
AppState @ app_state.js:16 // this._currentState = 'INIT';
(anonymous function) @ app_state.js:72 // exports.default = new AppState();
__webpack_require__ @ bootstrap 0ff9444…:19
(anonymous function) @ ticketListView.js:17 // var app_state_1 = require('../states/app_state');
__webpack_require__ @ bootstrap 0ff9444…:19
(anonymous function) @ eventView.js:5 // var ticketListView_1 = require('../views/ticketListView');
__webpack_require__ @ bootstrap 0ff9444…:19
(anonymous function) @ index.js:6  // var eventView_1 = require('./views/eventView');
```

2. I'll run/re-run/redo the tests tomorrow and try the dummy code

Thank you!

I will also try to provide a standalone example exhibiting this behaviour tomorrow.

**Comment by dmitriid** [comment]
Oh. Also.

Code is first compiled by `tsc` and then bundled by webpack. This may or may not be relevant. The configs are very barebone:

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": false,
    "experimentalDecorators": true,
    "noLib": false,
    "jsx": "react",
    "outDir": ".build_cache",
    "pretty": true,
    "noEmitOnError": true
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "**/__tests__",
    "**/__mocks__"
  ]
}
```

`webpack.config.js`
```
module.exports = {
  bail: false,
  devtool: 'source-map',
  entry:   [
    '.build_cache/index.js'
  ],
  output:  {
    path:       'build',
    filename:   'app.js',
    publicPath: '/static/'
  },
  resolve: {
    extensions: ['', '.js']
  },
  plugins: [],
  node: {
    fs: false,
    __filename: '',
    __dirname: ''
  }
};
```

**Comment by dmitriid** [comment]
Ok. I feel extremely stupid right now :) I should've really paid attention to the error:

> @ computed can only be used on **getter** functions, like: '@ computed **get** myProps()

And here's the minified example of the code which was producing the error. Not the `validate` function:

```ts
class A {
  @observable
  private _currentTicket = 1

  @computed
  public validate(): boolean {
    return true
  }

  @action
  public next(nextState?: PaymentFlowState): void {
    if (this.validate()) {
    }
  }

  @computed
  public get currentTicket() {
    return this._currentTicket
  }

  public set currentTicket(ticketid: number) {
    this._currentTicket = ticketid
  }
}

const a = new A()

export default observer(() => {
  return <div onClick={() => a.currentTicket++}>{a.currentTicket}</div>
})
```


I'll update the issue with the solution.
