### ISSUE TITLE
Bound action is not an action

### ISSUE THREAD

**Issue by urugator** [mobxjs/mobx#627]
Is this an expected behavior (user's error)?
```javascript
// mobx 3.6.0
let action = Mobx.action(function() {
  console.log(this);
});
console.log(Mobx.isAction(action)); // true
action = action.bind("hello");
console.log(Mobx.isAction(action)); // false
action(); // "hello" - Was it invoked as action or not?
```

**Comment by mweststrate** [comment]
This is expected, `bind` creates a new function so it is no longer recognizable as being an action (the original function cannot be inspected from the outside). Notetheless the behavior will remain the same, the function will be invoked with the original action semantics.
