### ISSUE TITLE
observableArray should have it's keys enumerable

### ISSUE THREAD

**Issue by capaj** [mobxjs/mobx#628]
currently `observableArray` keys are not enumerable. This has caused some bugs in our app code where we iterate through array with `for in` or using `Object.keys()` because I expected the array keys to be enumerable just like they are in regular javascript arrays.

here is an expected behaviour:

```javascript
const {observable} = require('mobx')

const a = observable([1,2,3])
Object.keys(a).forEach((key) => {
  console.log(key)
})
// should log 1,2,3 but now doesn't log anything
```

**Comment by mweststrate** [comment]
Originally this was the case, but the enumerability came at huge performance drops both CPU and memory wise.  Currently all index properties are only defined on the prototype, which just wraps the internal data array. To introduce enumerability (for the proper indexes) this requires to define properties on each ObservableArray instance. Fast arrays were introduced in 1.1.6, and became the default in 2.0.0

**Comment by capaj** [comment]
I see now: https://github.com/mobxjs/mobx/blob/master/test/array.js#L89

It was certainly a good decision-enumerability is not that important- one should rather use `forEach` or `map` to iterate state arrays anyway. It doesn't make much sense to iterate with manual loops. Tried quickly resolve it, but as you've said-it is almost twice as slow when creating arrays in the perf test. Enumerability is a tradeoff we'll fix when IE11 dies.

**Comment by capaj** [comment]
on the other hand-if it would solve the usecase for react-native:
https://github.com/mobxjs/mobx/issues/476
maybe it would be worth to add something like `enumerableArray` which would make an enumerable array instead of the default fast array.

**Comment by mweststrate** [comment]
depends, if they use Array.isArray internally it still won't work as these
are faux arrays. so i think it is always safer as rule of thumb to slice
before paying to an external lib, until proxies. slices are very cheap and
also makes it clear that the external lib is not supposed to mutate the
array

Op wo 26 okt. 2016 15:02 schreef Jiri Spac <notifications@github.com>:
