### ISSUE TITLE
Multiple re-renderes of observing component

### ISSUE THREAD

**Issue by ikido** [mobxjs/mobx#63]
Not sure why but I've noticed that my components that are recieving observable props are re-rendering at least twice on when observed data updates. Not that it's a performance problem, I just want to understand how your library works and control things. How do I debug this? What you might need?

Edit: I've noticed that this happens only when I'm updating name through 'parent' model, but it still calls name's __updateFromJson method. When updating name directly, e.g. changing 'value' property or 'is_default' property, component re-renders only once

Edit2: I was wrong, double render happens only when clicked on a link in 'ActionsDropdown' component, then 'onItemSelect' callback is executed calling appropriate 'name' method. But hen calling that same method directly, e.g. 'setAsDefault' component re-renders only once.

Edit3: Another component is showing same behavior and there is also domain object's method called as a callback. The question is why this happens and what is the possible workaround?

Here is my simplified model:

    @autobind
    class Name {
      
      id = null;
      store = null;
      nameable = null;

      @observable value;
      @observable is_default;

      constructor(store, nameable, json) {
        this.store = store;
        this.nameable = nameable;
        this.id = json.id;

        this.__updateFromJson(json)
      }

      __updateFromJson(json) {
        this.value = json.value
        this.created_at = json.created_at
        this.updated_at = json.updated_at
        this.is_default = json.is_default
      }

    }

And this is my simplified component:

    @observer
    @autobind
    class ShowName extends React.Component {

      getDefaultClass() {
        return this.props.name.is_default ? styles.defaultName : ''
      }

      onItemSelect(itemProps, parent) {
        var action;

        this.setState({ loading: true });

        if (itemProps.action === 'setAsDefault') {
          action = this.props.name.setAsDefault;
        } else if (itemProps.action === 'delete') {
          action = this.props.name.destroy;
        };

        action().then(() => {
          if (this.mounted) this.setState({ loading: false })      
        })
      }

      render() {
        var liClassName = `default-${this.props.name.is_default)} list-group-item entity`; 

        return (
          <li className={ liClassName }>
            <Row>
              <Col
                xs={9}
                className={ `default-${ this.props.name.is_default}` }
              >
                <EditablePopoverLink
                  editor={ <NameEditor name={ this.props.name } /> }
                  title='Edit name'
                  linkText={ this.props.name.value }
                />
              </Col>
		<Col xs={3}>
		  <div className="actions pull-right">
		    <ActionsDropdown
		      isLoading={ this.state.loading }
		      isDefault={ this.props.name.is_default }
		      onItemSelect={ this.onItemSelect }
		    />
		  </div>
		</Col>
            </Row>
          </li>
        );
      }

    }

**Comment by mweststrate** [comment]
Hi @ikido 

In principle components should render only once indeed. A few questions:
1. how did you determine this behavior? in tests or in the browser? Using console.log in render or in some other way?
2. do you change multiple values (or the same value multiple times)? If so, does this happen on the same process tick (synchronously) or not?
3. during the process that renders to often, do you also use setState?
3. If you install the `mobservable-react-devtools` you can double-check which values the component is currently observing
4. Just for verification, what are your versions of `react`, `mobservable` and `mobservable-react`?

**Comment by ikido** [comment]
@mweststrate thanks for such fast reply, here are my answers:

1) I use console.log in render in browser
2) I change multiple values in a 'Name' class instance or, for example, push new 'Name' instance to observable array of names on another class instance. I'm making a request to the backend first and changes happen asynchronously.
3) yes, I do — I change state before calling Name's action and then after promise is fullfilled (request finished and Name is updated)
3) I will try that, thanks!
4) 
"mobservable": "1.1.1"
"mobservable-react": "2.1.0"
"react": "0.14.2"

I've updated original issue, I've noticed that another component is showing same behavior and there is also domain object's method called as a callback, like onItemSelect in my example above. There is only one additional re-render happening when callback is executed, and if I call that method in render there is no additional re-render

**Comment by mweststrate** [comment]
@ikido So far the behavior is correct as far as I can tell, if you change a value before a promise and after it resolves the component is updated twice to keep the ui in sync with your state, which is as intended.

Note that components will only listen to values that were actively changed in the last render, so if you have a component like

```
var state = observable({
   loading: true,
   name: "nonsense"
});

@observer class view extends Component {
    render() {
        return <span>{ state.loading ? "" : state.name} </span>
    }
}

fetchData().then(data => {
  state.loading = false;
  state.name = data;
})
```
your component will only start listening to the `name` when `loading` yields false (and it will stop listening when `loading` becomes true again).

Can you elaborate on Edit 3? Didn't exactly get the picture of what happens (or goes wrong)

**Comment by ikido** [comment]
@mweststrate I agree, in case you've described everything works correctly. But take a look at these two examples:

In first case we pass a method of 'name' to 'OtherComponent' and it is called there, making a request to the API and updating observable name value

		@observer class View extends Component {
		    render() {
		    	return (
		    		<span>
		    		{ this.props.name.value }
		        	<OtherComponent updateAction={ this.props.name.update }/>
		    		</span>
		       )
		    }
		}

		class OtherComponent extends Component {
			handleClick() {
				this.setState({ loading: true })

				this.props.updateAction('nonsense').then(() =>
					this.setState({ loading: false })
				)
			}

			render() {
				return <Button onClick={ this.handleClick } />
			}
		}

In second example we pass a callback to OtherComponent, and we call a method on 'name' inside that callback:

		@observer class View extends Component {
			handleUpdate(value) {
				this.setState({ loading: true })

				this.props.name.update(value).then(() =>
					this.setState({ loading: false })
				)
			}

		    render() {
		        return (
		        	<span>
		        		{ this.props.name.value }
		        		<OtherComponent onUpdate={ this.handleUpdate }/>
		        	</span>
		        }
		    }
		}

		class View extends Component {
			handleClick() {
				this.props.onUpdate('nonsense')
			}

			render() {
				return <Button onClick={ this.handleClick } />
			}
		}


Where name is instance of this class:

    @autobind
    class Name {

      id = null;
      store = null;
      nameable = null;

      @observable value;
      @observable is_default;

      constructor(store, nameable, json) {
        this.store = store;
        this.nameable = nameable;
        this.id = json.id;

        this.__updateFromJson(json)
      }

      update(newValue) {
        return API.request({
          method: 'put',
          data: { value: newValue },
          endpoint: `/names/${this.id}`,
          onSuccess: (responseBody) => {
            this.__updateFromJson(responseBody)
          }
        })
      }

      __updateFromJson(json) {
        this.value = json.value
        this.created_at = json.created_at
        this.updated_at = json.updated_at
        this.is_default = json.is_default
      }

    }

So in second case our 'View' component is re-rendered multiple times, while in first example it does not

**Comment by ikido** [comment]
@mweststrate seems like the cause in second example is calling of setState({ loading: true }) in handleUpdate method — if I remove that then there are no additional re-renders

**Comment by mweststrate** [comment]
@ikido: correct, setState will always correct a rerender in react, so the first setState will render to reflect your 'loading:true'  state, and the promise fulfillment will trigger an additional render. 

Note that this might actually the desired behavior, if loading takes too long. However, since you have observable data already, personally I would probably move these kind of information to your data objects and not use `setState` at all. Introducing a property `@observable isLoading = true` in your component will also achieve the same effect :)

**Comment by ikido** [comment]
@mweststrate  but that should still be 3 renders, right?

1) setState({ loading: true })
2) promise fullfillment + update of observable data
3) setState({ loading: false })

And I'm getting 4 of them in case of callback example, and trying to understand why. Sorry for spamming you today)

**Comment by mweststrate** [comment]
Yup should be 3 max indeed. (double check: you are talking about the topmost component in both examples right?). Also, maybe the `name.update`  function does also update relevant parts of the name object before *and* after the request is fullfilled?

**Comment by ikido** [comment]
Nope, `name.update` is exactly as in example, it makes request to server and calls that `onSuccess` callback if request was successful. And yes, I'm talking about topmost component in both examples, the `View`

Any ideas how to debug this? Thanks

**Comment by mweststrate** [comment]
First I would remove the `@observer` decorator, so that you know how many renderings are coming from React & setState itself. 

After that reintroduce `@observer`. You can call `mobservable.extras.trackTransitions()` to a detailed log about when mobservable will update what. So if you invoke that at the beginning of your click handler you should be able to see how many times the rendering is invoked caused by what changes. Feel free to share the output as it might be a bit too verbose atm. Optionally you can pass `true` as first param for even more logging :-P.

**Comment by mweststrate** [comment]
Closed for inactivity.
