### ISSUE TITLE
Question: Is it possible to convert a computed value to plain JS in any way? 

### ISSUE THREAD

**Issue by jmaguirrei** [mobxjs/mobx#630]
I have a Store with observables, actions and computed values, like:

``` javascript
  @observable allPeople = false; // A reaction to a Meteor collection ready fill this up

  @computed get myUser() {
    if (this.allPeople) {
      return _.find(this.allPeople, { _id: Meteor.userId() });
    }
    return false;
  }
```

In a component I need to pass 2 fields of the computed myUser to an action:

``` javascript

import { CoreStore } from '/imports/client/store/stores/((Core)).js';

// later...
        onInputMessage: ({ text, myUser }) => {
          const { _id: myUser_id, base: { name: { orig: myUserName }}} = CoreStore.myUser;
          console.log('_id: myUser_id, base', myUser_id, myUserName);
          return ChatActions.onInputMessage({ text, myUser_id, myUserName });
        },
```

An the action receives that:

``` javascript
function onInputMessage({ text, myUser_id, myUserName }) {
    console.log('text, myUser_id, myUserName', text, myUser_id, myUserName);
    const
      conversation_id = State['Chat_conversation_id'],
      company_id = State['App_company_id'],
      newDoc = {
        _id: new Mongo.ObjectID().valueOf(),
        text,
        people: {
          _id: myUser_id,
          name: myUserName,
        },
        conversation_id,
        company_id,
      };

    console.log('newDoc', newDoc);
    Chat_addMessage.call(newDoc, (error, result) => {
        console.log('Chat_addMessage', error, result);
      });
...

```

However, the console shows the entire computed object inside the action, but the arguments of the function are just plain text...

![screenshot from 2016-10-26 17-35-20](https://cloud.githubusercontent.com/assets/11958637/19744166/aaa8d7c2-9ba2-11e6-9c31-6d58b46509d6.png)

I need the newDoc to be just a plain object, with exactly this fields, because I need to validate it against an Schema in Mongo.

I read the docs and I know computed values are not enumerable, and cant be converted to plain JS, but this behaviour surprises me, because I am passing some values inside the computed object to create another (non-computed) object, but cant get rid of the "observability"...

How is it possible?

Thanks

**Comment by mweststrate** [comment]
This looks really weird, there is no reason why the object should be observable here. Do you have a reproducible setup. Can you check also with `isObservable(Object)`? I'm wondering whether it is actually logging the right variable at the right time...

**Comment by jmaguirrei** [comment]
@mweststrate I found the issue, but I think its easy to get confused:

After logging the newDoc const I passed this object to a MessagesStore, like:

```javascript
function onInputMessage({ text, myUser_id, myUserName }) {

  console.log('text, myUser_id, myUserName', text, myUser_id, myUserName);
  console.log('text, myUser_id, myUserName', mobx.isObservable(text), mobx.isObservable(myUser_id), mobx.isObservable(myUserName));
  if (text !== '') {

    // Add the message
    const
      conversation_id = State['Chat_conversation_id'],
      company_id = State['App_company_id'],
      newDoc = {
        _id: new Mongo.ObjectID().valueOf(),
        text,
        date: getDate.new().JSON, // In the server will be rectified
        people: {
          _id: myUser_id,
          name: myUserName,
        },
        conversation_id,
        company_id,
      };
    console.log('newDoc', newDoc, mobx.isObservable(newDoc));
    // Write on Store
    MessagesStore.pushMessage(newDoc);

```

The 3 logs says that the object is not observable, but you see that newDoc inside is a mobx object.

The thing is that this action takes the input and write it to another observable, like:

```javascript

// In MessagesStore

  @action pushMessage(newMessage) {

    console.log('newMessage', newMessage);
    const newMessageEnriched = myMessages({
      Messages: [ newMessage ],
      people_ids: State['Chat_conversationPeople'],
      selectedMenu: State['Chat_selectedMenu'],
      myUser_id: Meteor.userId(),
      previousMessage: this.lastMessage,
    });

    this.setShowUnreaded(false);
    this.setLastMessage(newMessage);
    this.myMessages = _.union(newMessageEnriched, this.myMessages);
    this.removeTypings(newMessage.conversation_id);
  }
```

If I omit this step, the object is just a plain JS object, but because its passed to the store, its modified and became observable.

I solved just passing the object to the store like:

```javascript

// Creating a new empty object and passing it
MessagesStore.pushMessage({...newDoc});

```

Also noticed that this line: ` console.log('newDoc', newDoc, mobx.isObservable(newDoc));` logs an observable object and false. Maybe because the object became observable before the function to know it?

But I wonder if there is the generalization of this concept, a good practice to follow on the future ?...

**Comment by mweststrate** [comment]
@jmaguirrei note that modifiers like `asReference` or `asFlat` can be used to avoid child objects to become observable automatic. Personally I try to be a bit strict about observables; everything that is part of the state tree / graph should be observables. And those things I usually make observable as possible. This favors model classes which makes this very explicit

**Comment by jmaguirrei** [comment]
@mweststrate Thanks, I will keep that in mind. Closing this question.
