### ISSUE TITLE
[Documentation] https://mobxjs.github.io is inaccessible

### ISSUE THREAD

**Issue by dmitriid** [mobxjs/mobx#635]
This is an issue that has been bugging me for a while :)

MobX docs are available at https://mobxjs.github.io/mobx/ However, sometimes (actually, quite often) search or browser autocomplete will open https://mobxjs.github.io which is a 404

It would be nice to have a redirect there, or a page with a link to the proper doc page

**Comment by mweststrate** [comment]
fixed!

Op za 29 okt. 2016 12:56 schreef dmitriid <notifications@github.com>:

**Comment by dmitriid** [comment]
woohoo!
