### ISSUE TITLE
Provide flow typings

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#640]
MobX ships with typescript typings. However, flow people are regularly asking for these typings as well. It would be nice to add these typings as well. 

Some questions:
1. can the conversion be automated? see e.g. https://github.com/Kegsay/ProbablyFlowTyped
2. can the typings be maintained in this repo, or do they need to be stored in the flow typings registry?
3. what about mobx-react  / mobx-util?

PR's are welcome!

**Comment by A-gambit** [comment]
@mweststrate I need it in my project. I can do it the next time.

**Comment by mweststrate** [comment]
Awesome, looking forward!

**Comment by mweststrate** [comment]
@A-gambit check this: https://github.com/joarwilk/typedef-converter. Might be useful!

**Comment by A-gambit** [comment]
@mweststrate thank you. I start writing types locally, but I have a problem with function arguments. For example: https://github.com/mobxjs/mobx/blob/master/src/api/observe.ts#L12-L17. I think this library will be useful, thank you.

**Comment by A-gambit** [comment]
Already done in MobX3!
