### ISSUE TITLE
State vs Store vs Props @Mobx

### ISSUE THREAD

**Issue by Kamaraju333** [mobxjs/mobx#641]
I have started using Mobx and React , I have couple of question using Mobx with React .

1.Does Store in Mobx refer to State in React?
2.I read that mobx depends on ShouldComponentUpdate in React , is it true ?
3.I read in react that the props of a component shouldnt not be updated , only state has to be updated, when i followed the example egghead.io tutorial for mobx 

I see the "**count**" as observable in the example but when incrementing or decrementing it was mentioned as 

this.props.count++ and this.props.count--

what does this mean , does this mean i am updating my state or props ...

4.i have a small example below which made me to ask above questions 
@observer
class Example extends React.Component{
render(){
const{example}=this.props 
return(
<FormControl type="text" value={example.name} onChange={this.handleChange}/>

)

handleChange=(event)=>{
this.props.example.name=event.target.value
}

}

}

In the above example i am unable to edit the input field . I am not sure its issue with Mobx .

Appreciate necessary help

**Comment by hellectronic** [comment]
Did you read in the React documentation about [controlled and uncontrolled](https://facebook.github.io/react/docs/forms.html) form components?

**Comment by hellectronic** [comment]
In your example above, you are not updating the props of a component. You are updating the example-object properties.

**Comment by Kamaraju333** [comment]
@hellectronic  yes i have read about controlled and uncontrolled components , i am looking for a controller component . Can you answer the above questions

**Comment by hellectronic** [comment]
> 1.Does Store in Mobx refer to State in React?
You can store the state wherever it makes sense for your application. If state is only local to your component, then it makes sense to use React state.

> 2.I read that mobx depends on ShouldComponentUpdate in React , is it true ?
You can read about it https://github.com/mobxjs/mobx-react

**Comment by hellectronic** [comment]
@Kamaraju333 is the issue resolved?

**Comment by Kamaraju333** [comment]
Yes
