### ISSUE TITLE
Compatible with Zeit Next.js?

### ISSUE THREAD

**Issue by etinif** [mobxjs/mobx#643]
Any examples of Mobx with the Next-big-thing-in-react? https://github.com/zeit/next.js

**Comment by nightwolfz** [comment]
More like just-another-boilerplate :)

**Comment by nightwolfz** [comment]
Looks like just another boilerplate, it shouldn't be hard to integrate mobx.

**Comment by DigitalMarc** [comment]
examples shaps! 👯

**Comment by mweststrate** [comment]
Besides https://github.com/mobxjs/mobx-react/issues/140, which will soon be addressed, I don't see any reason why it shouldn't work indeed.
