### ISSUE TITLE
Way to get notified when the reaction to an action (computing + rendering) is finished.

### ISSUE THREAD

**Issue by ugros** [mobxjs/mobx#650]
Hello,

Let's say I have an action that modifies my state. The reaction to that action might take a very long time (more than is accetable for user to wait without getting notified that something is happening).

I want to find a way to start a spinner (indicating that something is happening - reaction to an action is being calculated/rendered) and then remove that spinner when reaction to that action is done.

Is there a way to do this? And if so, then how?
Thanks

**Comment by mweststrate** [comment]
@ugros make sure to run your computation in a promise, and then leverage `fromPromise` from mobx-utils to render the correct state. See the [docs](https://github.com/mobxjs/mobx-utils#frompromise) (third example)

```
const computation = mobxUtils.fromPromise(new Promise((reject, resolve) => {
  somethingExpensive()
  resolve()
))

const RenderComputation  = ({ computationPromise }) => 
   computationPromise.case({
      "pending": <div>Busy</div>
      "fulfilled": <div>Ready</div>
      "rejected": <div>Oops</div>
  )}
```

**Comment by mweststrate** [comment]
Assuming this question is answered, otherwise feel free to reopen
