### ISSUE TITLE
MobX as React component state replacement

### ISSUE THREAD

**Issue by AlgoTrader** [mobxjs/mobx#654]
That's not an issue, it's rather question. I have class like this

```
@observer
class View extends Component {
  @observable prop = {deep1: val1, deep2: val2};

  render() {
   return <div>{this.prop}</div>   
  }
}
```

I found it inconvenient to work with react's state with nested objects. I need code like this:
```
this.setState({prop: {...this.state.prop, deep: newValue}})
```

If I use mobx, all I have to do is `prop.deep = newVal`

Is it a good pattern to use @obserbvable and @observer with the samе React component? It's a kind of drop-in replacement for React state.

**Comment by ztolley** [comment]
https://medium.com/@mweststrate/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e#.na8z2q7gg

**Comment by AlgoTrader** [comment]
Great! I will consider saying goodbye for setState in projects using MobX.
The only reasonable exception is shared component can be used in non-MobX projects and when it is reasonable to remove external deps
