### ISSUE TITLE
Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by prashaantt** [mobxjs/mobx#655]
I have an:

2. [x] Issue. Please make sure you have the following:
  * [x] Did you check this issue wasn't filed before?
  * [x] What is your issue? Why do you thing this is not the expected behavior?
  * [x] What MobX version(s) are you using?
  * [x] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for most issues.

Coming back to MobX after a while, using `mobx 2.6.2` with `mobx-react 3.5.9`. This used to work in a previous version:

```tsx
import * as React from "react";
import { observer } from "mobx-react";
import { observable, action } from "mobx";

@observer
export class TestComponent extends React.Component<{}, {}> {
    @observable someProp: string;

    @action changeSomeProp = () => { // here seems to be the issue

        this.someProp = "value";
    }
}
```

Now I get this error every time my app re-renders `TestComponent` with hot-reloading:

```bash
mobx.js?6a62:2508
Uncaught (in promise) TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at classPropertyDecorator (eval at <anonymous> (http://localhost:3001/static/bundle.js:1613:1), <anonymous>:2508:24)
    at eval (eval at <anonymous> (http://localhost:3001/static/bundle.js:1613:1), <anonymous>:31:25)
    at typescriptInitializeProperty (eval at <anonymous> (http://localhost:3001/static/bundle.js:1613:1), <anonymous>:2550:5)
    at Object.get (eval at <anonymous> (http://localhost:3001/static/bundle.js:1613:1), <anonymous>:2495:25)
    at shouldDeleteModernInstanceMethod (eval at <anonymous> (http://localhost:3001/static/bundle.js:7927:1), <anonymous>:38:27)
    at eval (eval at <anonymous> (http://localhost:3001/static/bundle.js:7927:1), <anonymous>:79:9)
    at Array.forEach (native)
    at deleteUnknownAutoBindMethods (eval at <anonymous> (http://localhost:3001/static/bundle.js:7927:1), <anonymous>:78:9)
    at Array.forEach (native)
```

which corresponds to [this line](https://github.com/mobxjs/mobx/blob/c702239e91969f5c8f6228fe6999063dc8c20380/src/utils/decorators.ts#L55) in the source. The problem goes away when I use a proper method instead of a class property method:

```tsx
@observer
export class TestComponent extends React.Component<{}, {}> {
    @observable someProp: string;

    @action changeSomeProp() { // no more issues

        this.someProp = "value";
    }
}
```

**Comment by mweststrate** [comment]
I think this is a current limitation of Hot Module Reloading. I think it cannot easily be fixed until decorators have stabilized, but a simple workaround is doing `changeSomeProp = action(() => { .. })` (the down side of your approach is that the action is no longer bound)

**Comment by prashaantt** [comment]
Thanks, I guess I can live without decorators in a few places.

**Comment by WearyMonkey** [comment]
I had the same issue when my TypeScript target language was "ES5" (default). Changing the target to "ES6" resolved the issue.

**Comment by kevgathuku** [comment]
This also happens when you have an `observable` and `action` with the same name. 
Took me a while to notice that silly mistake 😄

**Comment by devuxer** [comment]
This appears to still be a problem with TypeScript and hot reloading (and I'm not able to target ES6 due to needing to support older browsers). As @mweststrate suggested, I'm finding that I have to remove all @action decorators on event handlers of the form `() => {...}` and replace it with `action(() => {...})` to get hot reloading to work. I hope a solution becomes available at some point...

**Comment by mweststrate** [comment]
Note that the `@next` version of HMR has some support for decorators afaik. (Still wouldn't trust it too much, personally I bailed out on HMR a long time ago)

Also note that computed values can have setters, and that they are actions automatically

**Comment by devuxer** [comment]
@mweststrate,

Thanks, I did eventually come across that in the docs. Since my comment, I've developed a preference for isolating the exact line of code that modifies state and wrapping just that in with `runInAction` (rather than wrapping the entire event handler method in `action`).

Example:

```
    private onToggleBookmarked = () => {
        const item = this.props.item;
        runInAction(() => item.isBookmarked = !item.isBookmarked);
    }
```

**Comment by juanmiret** [comment]
I'm having this issue in an app with React Native, out of nothing i'm getting Object.defineProperty called on non-object in the first render, but if I save any file and the app Hot reloads the problem goes away, none of the mobx code was modified, it was working OK, and bum out of nothing this error. I've tried disabling hot reloading, deleting all watchman caches, node_modules and reinstalling, etc...

The only thing that does actually stop the error is removing this line: 

class AuthStore {
   //........
  @observable authToken = null
  //..........
}

if I remove that line, code works (auth doesn't obviusly), if I replace null with an empty string '', code works, if I replace null with a random string, same error again. If I initialize it as an empty string, when I try to update it, same again "Object.defineProperty called on non-object"

The weird thing is, i didn't touch a thing in this file and suddenly this error appears

Any ideas?

**Comment by mweststrate** [comment]
Can you share your babel configuration?

Op di 22 aug. 2017 om 06:03 schreef Juan Miret <notifications@github.com>:

**Comment by juanmiret** [comment]
@mweststrate I'm sorry, it was a really silly mistake, one of my coworkers changed the name of an action in other store, and the new name was the same as the name of a property, and that was the root of the issue. The reason that removing the authToken line made it work is because without the token the other store would never be used. Took me a complete day to debug 😓

**Comment by WebCaiQingChong** [comment]
I have the same problem, what's the solution？ I use mobx@4.1.0 mobx-react@5.0.0

**Comment by WebCaiQingChong** [comment]
configure({enforceActions: true})

export default class Activity {
  @observable adList = []

  @action
  async receiveAdlist (params) {
    const data = await getBanner(params)
    if (data.success) {
      reaction(() => {
        this.adList = data.data
      })
    }
  }

  @action
  async addAdlist (params) {
    const data = await addBanner(params)
    if (data.success) {
      this.receiveAdlist()
    }
  }

  @action
  async editAdlist (params) {
    const data = await editBanner(params)
    if (data.success) {
      this.receiveAdlist()
    }
  }
}

**Comment by WebCaiQingChong** [comment]
`
configure({enforceActions: true})

export default class Activity {
  @observable adList = []

  @action
  async receiveAdlist (params) {
    const data = await getBanner(params)
    if (data.success) {
      reaction(() => {
        this.adList = data.data
      })
    }
  }

  @action
  async addAdlist (params) {
    const data = await addBanner(params)
    if (data.success) {
      this.receiveAdlist()
    }
  }

  @action
  async editAdlist (params) {
    const data = await editBanner(params)
    if (data.success) {
      this.receiveAdlist()
    }
  }
}
`

**Comment by mweststrate** [comment]
@WebCaiQingChong this issue is closed. Please open a new one, including reproduction in a sandbox

**Comment by bsmith-cycorp** [comment]
For those who find themselves in this ticket, I had the problem caused by the following:
```javascript
myReaction = reaction(() => this.foo, this.myAction)

@action
myAction = () => {
  ...
}
```

changing to this fixed it:
```javascript
myReaction = reaction(() => this.foo, () => {
  this.myAction();
})

@action
myAction = () => {
  ...
}
```
