### ISSUE TITLE
Any plans / low-hanging fruit to reduce the filesize?

### ISSUE THREAD

**Issue by matthewmueller** [mobxjs/mobx#656]
I'm wondering if there are any plans to reduce the filesize over time? 

Right now it's sitting at 16kb minified / gzipped, which is much better than some other libraries, but still adds up when you tack on the bindings, react / etc.

I love what @developit is doing with preact and making a small filesize a focus. Is mobx also pushing on this too or is it more about adding the right features?

**Comment by mweststrate** [comment]
One idea: #653. Besides that, I plan to bring out a new major in a few weeks, which kills quite some old already deprecated functions

**Comment by developit** [comment]
That looks like a pretty stellar idea!
