### ISSUE TITLE
Best practice for passing props

### ISSUE THREAD

**Issue by Raathigesh** [mobxjs/mobx#657]
I have a domain model as follows

``` typescript
class Item {
  @observable name: string;
  @observable quantity: number;

  @action
  public setName = (value: string) => {
    this.name = value;
  }

  @action
  public setQuantity = (value: number) => {
    this.quantity= value;
  }
}
```

And there is an `ItemComponent` which is going to display the data in the model.

```jsx
import ItemComponent from './ItemComponent';
const item  = new Item();
```
I can see two ways to pass the data from the model to the component as follows.

```jsx
<ItemComponent 
   name={item.name}
   quantity={item.quantity}
   onNameChange={item.setName }
   onQuantityChange={item.setQuantity }
/>
```
or

```jsx
<ItemComponent 
   item={item}
/>

```

What would you recommend and why?

**Comment by leader22** [comment]
https://mobxjs.github.io/mobx/best/react-performance.html

`dereference-values-lately` section will help you!

**Comment by mweststrate** [comment]
Indeed, always try to pass in objects. It makes the `ItemComponent` itself responsible for tracking, instead of the parent component, which is more expensive to re-render.
