### ISSUE TITLE
Question: Pass and Observable Collection through PropTypes needs toJS() conversion first?

### ISSUE THREAD

**Issue by jmaguirrei** [mobxjs/mobx#658]
I am passing Observable collections (arrays of objects) to a child component, but PropTypes fails because an observable collection is recognized as an Object  and no as an Array of objects.

For example:

```javascript

// PropTypes object definition
const Agreements_propTypes = {

 data: PropTypes.shape({
    meeting_id: PropTypes.string,
    editable: PropTypes.bool,
    agreements: PropTypes.arrayOf(PropTypes.object),
  }),

};

// data property passed from parent component

  const data = {
    meeting_id: MeetingStore.core._id,
    editable,
    agreements: toJS(MeetingStore.agreements),
  };

};

```

In this example:

`meeting_id` is a valid `PropTypes.string`
`agreements` is a only valid `PropTypes.arrayOf(PropTypes.object)` if `toJS` transformation is applied before passing the prop to child component.

Is this the pattern needed to use Observable Collections with PropTypes or do I have a simpler way available?

**Comment by urugator** [comment]
If you can change the component's PropTypes, `mobx-react` provides several useful alternatives like `arrayOrObservableArrayOf(React.PropTypes.number)` see https://github.com/mobxjs/mobx-react#proptypes

**Comment by jmaguirrei** [comment]
@urugator Thanks a lot, it works OK so far.
