### ISSUE TITLE
How to track object mutations?

### ISSUE THREAD

**Issue by tkrotoff** [mobxjs/mobx#662]
Example with Moment.js:

```JavaScript
var person = mobx.observable({
  birthday: moment()
});

mobx.autorun(function() {
  console.log('autorun: ' + person.birthday.toString());
});

person.birthday = moment(person.birthday).add(1, 'day'); // Ugly but works
person.birthday.add(1, 'day'); // Does not work

console.log('no autorun: ' + person.birthday.toString());
```

Output:
```Shell
autorun: Thu Nov 17 2016
autorun: Fri Nov 18 2016
no autorun: Sat Nov 19 2016
```

Online jsFiddle: https://jsfiddle.net/tkrotoff/ek64vvtf/

`autorun` is not being called when running `person.birthday.add(1, 'day')`.
[Moment.add](http://momentjs.com/docs/#/manipulating/add/) mutates `birthday` and Mobx does not know about it.

How can it be done elegantly?

PS: I've spent a long time in my code base before understanding why it did not work as I expected, I suggest to document this to avoid others the same mistake

**Comment by mattruby** [comment]
Check out my timer examples, https://github.com/mobxjs/mobx-examples . They
were using moment at one time. You'll want to use a computed to show the
date output. It should trigger as you'd like.

**Comment by hellectronic** [comment]
@tkrotoff, do you mean documenting [how moxb reacts](https://mobxjs.github.io/mobx/best/react.html)?

**Comment by tkrotoff** [comment]
@mattruby 
From the [timer example](https://jsfiddle.net/gh/get/library/pure/mattruby/mobx-examples/tree/master/react-examples/30-timer-tutorial), first initialisation: `startTime: null` then later `startTime = moment()`.
Since [MobX tracks property access, not values](https://mobxjs.github.io/mobx/best/react.html) it works.

In other words (tell if wrong), Mobx tracks the pointer value (pointer as in [C/C++ pointer](http://www.cplusplus.com/doc/tutorial/pointers/)).

That's why `person.birthday.add(1, 'day')` does not work: changing the value, not the pointer.
And `person.birthday = moment(person.birthday).add(1, 'day')` works: changing the pointer.

**Comment by nighca** [comment]
@tkrotoff Actually it's `Date` who basically causes this confusion. Moment.js uses Date instance to store the exact value, while mobx doesn't track change of Date instance - which is difficult.

You can try this example and you'll find that mobx tries to make object content observable recursively.

**Comment by nighca** [comment]
@mweststrate Maybe mobx can do some monkey patch stuff to make Date instance changes trackable? Just like what mobx did with Array instances.

**Comment by kpennell** [comment]
@tkrotoff What ended up being the elegant solution to this? Tearing my hair out a bit...

**Comment by francesco-carrella** [comment]
I'm curious about that too because I have the same problem. Is there some more elegant solution?
Thanks

**Comment by tkrotoff** [comment]
btw, will [ES6 Proxy](#776) be able to solve this problem?

**Comment by mweststrate** [comment]
@kpennell @francesco-carrella  I recommend to treat the date as immutable, and every time you want to modify it, produce a new data and store that in a `observable.ref`

**Comment by francesco-carrella** [comment]
Thanks for the support @mweststrate, I ended using this way out.

**Comment by tkrotoff** [comment]
Replying to my question "will ES6 Proxy solve this problem?", the answer is no. See https://codepen.io/tkrotoff/pen/WyWOZP
