### ISSUE TITLE
 Computed value 

### ISSUE THREAD

**Issue by Kamaraju333** [mobxjs/mobx#671]
Class Example {
id
@observable description 
@computed get name (){
//code to get the computed value 
}
}

I have two question here , 

Q1. When i retrive examples from db , i need to set the name , but i get an error that computed values cannot set a new value .

Q2.when i get the example object , i dont see name as a property . how will get name as a property of the object ?

**Comment by mweststrate** [comment]
@Kamaraju333

Q1: that sounds that the value is not really computed? Computed means that the value should be derived from other observables you already have. 

Q2: you can just access them the same as any normal field. They are just not marked as enumerable as they are often not interesting during serialization
