### ISSUE TITLE
Migrate to typescript 2

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#672]
The title says it all :)

Compile with strict null checks, for optimal typings

**Comment by benjamingr** [comment]
+1 for strict null checks and better typings.

**Comment by JabX** [comment]
In the mean time, simply updating the typings (if possible, since i suppose they're generated from the source) would be very much appreciated, especially around arrays (`find` returning `T` instead of `T | undefined` got me once for instance).

**Comment by mweststrate** [comment]
Currently working on it, see also #679. I think mobx 2 will stay TS 1, and
mobx 3 will ship with TS 2 typings. They are afaik not entirely backward
compatible.

Op vr 25 nov. 2016 om 00:27 schreef Damien Frikha <notifications@github.com

**Comment by mweststrate** [comment]
Closed, as this will be part of 3.0
