### ISSUE TITLE
`toJS` ignores custom properties added to an ObservableArray.

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx#680]
When `toJS` parses an ObservableArray, it simply transforms it to a regular array, just like every other array method I suppose.

My problem is that I sometimes carry around extra properties on ObservableArrays, and while I'm fine with losing them is most cases with array manipulation, it becomes a problem when using `toJS` because I am trying to serialize those too.

I can add them back easily when I'm calling `toJS` directly on an array, but most of the time I use `toJS` on an arbitrary object that may or may not contain one of my arrays with extra properties. I could probably do some kind of recursive function that would browse the `toJS`'d object but that seems like a waste.

What would be the preferred course of action for me here?
Thanks.

**Comment by mweststrate** [comment]
putting additional properties on array is tricky, I strongly recommend using two data structures. For example introducing additional observable properties on the observable array won't work .

Maybe the array should just be frozen to prevent this.

**Comment by JabX** [comment]
I am adding a metadata object (not observable) and an additional method (called `set`) which is meant to used instead of `replace()`, which applies a transformation based on the metadata object. This allows me to populate my array with `array.set(values)` instead of `set(values, metadata)`, which is easier to use and doesn't require me to get the method and the metadata from elsewhere. 

Maybe this isn't a very clean way of doing that but it works totally fine and I hope I will be able to keep doing that in the future.

The `toJS` function was simple and short enough for me to simple copy it and tailor it to my specific needs. Thank you for your input nonetheless.
