### ISSUE TITLE
The observable object whose attributes are not used shouldn't be observed

### ISSUE THREAD

**Issue by mickeyinfoshan** [mobxjs/mobx#684]
I'm new here and the code might be a little long.
An observable instance is being observed when the observer just invokes its methods.
Here's an example, which is a todo app, to explain the details:

The observable classes:
```es6
// hold todos
class AppState {
  @observable todos = [];

  @action addTodo(text) {
      var newTodo = new Todo(text)
      this.todos.push(newTodo)
  }

  @action removeTodo(todoID) {
      for(var i = 0; i < this.todos.length; i++) {
          if(this.todos[i].id == todoID) {
              this.todos.splice(i)
              break
          }
      }
  }
}

// todo
class Todo {
  id
  @observable text
  @observable completed
  createdAt
  constructor(text) {
      nextTodoID++
      this.id = nextTodoID
      this.text = text
      this.completed = false
      this.createdAt = new Date()
  }
}

```

components here:
```es6
// the app
@observer
class App extends Component {
  render() {
    const {
        appState
    } = this.props
    return (
        <div>
              {
                  appState.todos.map(todo=><TodoItem key={todo.id} todo={todo} onRemove={()=>appState.removeTodo(todo.id)} />)
              }
        </div>
    )
  }
}

// todo item
@observer
class TodoItem extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            editable : false
        }
    }

    render() {
        const {
            todo,
            onRemove
        } = this.props
        const {
            compeleted,
            text,
        } = todo
        return (
            <div>
                <span>{text}</span>
                <span onClick={()=>onRemove()} style={{float:"right"}}>X</span>
            </div>
        )
    }
}
```
render function:
```es6
let appState = new AppState()
appState.addTodo("todo1")
appState.addTodo("todo2")
appState.addTodo("todo3")
appState.addTodo("todo4")
render(
    <App appState={appState} />,
  document.getElementById('root')
)
```
Every time a todo item is removed, all `TodoItem` components will be re-rendered, which is not efficient.
`appState` shouldn't be observed by `TodoItem` components since `TodoItem` components just  invoke a method of `appState` and don't care any attributes of `appState`.

Appreciate for your anserwers

**Comment by mweststrate** [comment]
Your component is not rerendering because it is observing appstate I think, but because you pass a new `onRemove` handler into the component each time the parent re-renders. Two different functions are never equal so react will re-render your component since you changed it's props. 

This is typically solved by adding a `remove()` method to the todo item, or by prebinding the remove handler in the `App` component. But in that case you have to make sure the `TodoItem` component passes in the correct `id`

**Comment by mickeyinfoshan** [comment]
Oh I see! Thanks a lot! Closed
