### ISSUE TITLE
TypeScript: Typing problem with `asReference`

### ISSUE THREAD

**Issue by uweg** [mobxjs/mobx#690]
I think the typing definition for `asReference` is not correct.

This results in a typing error:
```typescript
export function getBoxedObservable<T>(value: T): IObservableValue<T> {
  return observable(asReference(value));
}
```

There is an easy workaround but i think it should be fixed in the library:
```typescript
export function getBoxedObservable<T>(value: T): IObservableValue<T> {
  return observable(asReference(value)) as any as IObservableValue<T>;
}
```

**Comment by mweststrate** [comment]
`asReference` has been killed in MobX 3. Use `observable.ref` or `observable.box` instead.

Closing this issue as mobx@3.0.0-rc.1 is now available, which addresses this issue. Changelog: https://github.com/mobxjs/mobx/blob/mobx3/CHANGELOG.md#300. The changes in more details: https://github.com/mobxjs/mobx/pull/725/files. Feel free to re-open if questions arise!
