### ISSUE TITLE
State Object Key going missing

### ISSUE THREAD

**Issue by mxmtsk** [mobxjs/mobx#691]
I'm using MobX with React Native:

In my state I have a cities object (cities.berlin, cities.hamburg, etc). When I log it in componentDidMount the object keys are missing if I call state.cities, but they are there when I'm logging state. I have no idea why this happens?

```Javascript
  componentDidMount() {
    console.log(this.context.state, this.context.state.cities);
  }
```

Result:

<img width="593" alt="bildschirmfoto 2016-12-01 um 10 07 08" src="https://cloud.githubusercontent.com/assets/4848184/20787784/fcee74a2-b7ad-11e6-9c68-5bddfd449d0a.png">

Edit: When I copy the line to the render() method, it works

**Comment by mxmtsk** [comment]
I have reworked the code a little bit to use asMap() on cities. I do get the correct object now but 
`state.cities.get("berlin")` for example does still return undefined in componentDidMount()

**Comment by mweststrate** [comment]
Can you create small fiddle reproducing this issue? Missing some context currently. This issue most probably doesn't relate to React Native so should be easily reproducible. Please specify which mobx / mobx-react version you are using as well

**Comment by mweststrate** [comment]
Closed for inactivity / lack of a reproduction. Feel free to reopen.
