### ISSUE TITLE
Want an automatic setter decorator

### ISSUE THREAD

**Issue by djyde** [mobxjs/mobx#695]
e.g:

```javascript
class Foo {
    @observable @setter name
}

// will automatically add an action `setName` to set the name

const fooStore = new Foo()
fooStore.setName("foo")
```

**Comment by caesarsol** [comment]
I don't think this would be in scope, your decorator should be simple to implement outside of MobX. 

It would save very few keystrokes anyway...

```
class Foo {
    @observable name

    @action setName(futureName) { this.name = futureName }
}
```

This is more explicit IMHO, and allows for very clear separation of actions from observables.

**Comment by mweststrate** [comment]
@caesarsol agreed, this sound something that can perfectly done in user land, and isn't really a MobX specific problem.

**Comment by farwayer** [comment]
@djyde I just released simple decorators set for mobx with `setter` https://github.com/farwayer/mobx-decorators

**Comment by mweststrate** [comment]
@farwayer cool!
