### ISSUE TITLE
createTransformer does not support transformer function that has an argument with a default value (ES6)

### ISSUE THREAD

**Issue by timmolendijk** [mobxjs/mobx#698]
`createTransformer` takes a `transformer` argument, which is expected to be a function that takes precisely one argument. MobX tries to test this requirement by [checking that `transformer.length === 1`](https://github.com/mobxjs/mobx/blob/6e3df706de1f1fc2408ba919559297cd0d07573e/src/api/createtransformer.ts#L8).

The problem though is that this will break in the case of functions that have an argument with a default value, because those will have `length === 0` (at least in Node 5 and in latest Google Chrome).

For example, this breaks (and unnecessarily so as far as I can see):
```es6
const slice = createTransformer((data = []) => data.slice(0, 5));
```

**Comment by mweststrate** [comment]
Closed as the fix will be part of the upcoming 3.0 release
