### ISSUE TITLE
Usage in a Chrome Extension?

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx#700]
I have a Question.

I am attempting to use MobX to develop a chrome extension and am wondering about the best approach. 

Im not sure if you have done any chrome extension development before but the basic idea is you have a "background" page for your extension that runs continually in the background, then for  each tab you have a "content-script" that runs on that page. 

To communicate between the background and content-scripts you must pass messages as serialized objects.

What I would like to do is to have a single "state" object in the background then each content-script have a "state" object that mirrors the background so that every script in my app has the same state at all times.

What would be the recommended method for keeping these state objects in sync?

Cheers,
Mike

**Comment by mattruby** [comment]
Check out mobx-state-tree.

**Comment by mikecann** [comment]
@mattruby thanks, I will do :)

**Comment by mikecann** [comment]
Hmm mobx-state-tree doesnt play very nicely with Typescript :(

**Comment by mattruby** [comment]
It's written in typescript. @mweststrate is the king of typescript. If
there's a problem that way, let him know.

**Comment by mweststrate** [comment]
@mikecann mobx-state tree is indeed perfect for these situations. But as it is severely WIP, typings are currently indeed incomplete. I hope to release something more complete late december

**Comment by mikecann** [comment]
@mweststrate awesome! thanks, I look forward to it. For now ill do a bunch of "any's" and typecasting and see where I get with it, thanks :smile:
