### ISSUE TITLE
How to initialize the state? Using with server side‘s rendering.

### ISSUE THREAD

**Issue by vifird** [mobxjs/mobx#703]
Hello, we have a question : How to initialize the state of project?
The using scence is that: We are facing the server rendering problem in our project, we need to initialize the state in server side, and transmit the state to client side.
We know in Redux, there is a property named '__INITIAL_STATE__', witch used to initialize the state of Redux.
Does `mobx` have it's way to resolve this problem?
Thanks a lot.

**Comment by urugator** [comment]
> Does mobx have it's way to resolve this problem?

No. I personally do it by inserting state as inline script (is there other option?). Roughly like this:

Server:
```javascript
// Make state accessible from template  
res.locals.state = { page: 1 };
// Inititalize client side App with state
const App = require("./App.js");
const app = new App(res.locals.state);
// Render app to string and make the string accessible from template 
res.locals.html = app.renderToString();
```

Client script:
```javascript
const App = require("./App.js");
// Initialize client side App with state passed through gobal var
const app = new App(window.state || {});
// Render app
app.render();
```

Template:
```pug
// Inclue rendered content 
div#app!= html 
// Serialize state and store it to global var
script(type="text/javascript") window.state = !{JSON.stringify(state).replace(/<\//g, "<\\/")};
// Include client script
script(type="text/javascript",src="/asset/js/app.js")
```

**Comment by mweststrate** [comment]
See also: https://www.sitepoint.com/universal-react-rendering-sitepoint/?utm_content=buffer7905c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer for some tips

**Comment by vifird** [comment]
@urugator Thank you so much. It's a little high-cost than `Redux`, but this may be the best way in `Mobx`.

**Comment by vifird** [comment]
@mweststrate Learned from it, Thanks
