### ISSUE TITLE
observable array's observe does not respect action

### ISSUE THREAD

**Issue by arackaf** [mobxjs/mobx#704]
I'm subscribing to changes in an observable array via

`tasks.observe(() => .....`

Elsewhere I have code which modifies that tasks array in an action method, however, the observe callback is invoked immediately, following the mutation, rather than at the conclusion of the action callback.

Is this expected? Aren't actions supposed to batch all updates until the very end?  Or is array.observe different somehow?

**Comment by mweststrate** [comment]
Yes, this is expected, observe is more lowlevel and does not respect transaction or doesn't do any tracking. It's just a callback that is invoked each time the array is _changed_, instead of whenever something needs to be _derived_ from the array (which is what computed / reactions do)

**Comment by arackaf** [comment]
Ah - roger that.  Thanks for the fast reply.
