### ISSUE TITLE
Computed property is recomputed each time when a setter function for the property exist

### ISSUE THREAD

**Issue by grimmen** [mobxjs/mobx#705]
Welcome to MobX. Please provide as much relevant information as possible!

I have a*:

2. [X] Issue. Please make sure you have the following:
  * [X] Did you check this issue wasn't filed before?
  * [X] What is your issue? Why do you think this is not the expected behavior?

My understanding of computed properties is that they should be cached as long as the values they depend on haven't changed.

If I define a set method with the same name as a computed get method, then the computed method will execute every time - not caching the computed result.  This  happens even if no dependencies of the computed get has changed and the set method is not being called.

If I comment out the set method, then the computed method is only called when values actually change, as I believe is the expected behaviour.

  * [X] What MobX version(s) are you using? Which browser / node / ... version?

"mobx": "^2.7.0",
node : 6.9.1

  * [X] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for most issues.

Below is a mini code snippet that demonstrates the problem.
Run the below sample with and without uncommenting the fullname property setter.
When the property setter is removed, the fullName is only recomputed once for each change.  With the property setter in place, it is recomputed each time:

import {observable, autorun, computed } from "mobx";
class Person {
  @observable name;
  @observable title;
  set fullName(val) {
    console.log("Set method, not implemented");
  }
  @computed get fullName() {
    console.log("Recomputing fullName");
    return this.title+" "+this.name;
  }
}
let p1 = new Person();
p1.name="Tom Tank";
p1.title="Mr.";
autorun( ()=> {
  console.log("Autorun 1:");
  console.log(p1.fullName);
})
autorun( ()=> {
  console.log("Autorun 2:");
  console.log(p1.fullName);
})
p1.title="Master";

3. [ ] Idea
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well?
  * [ ] Are you willing to (attempt) a PR yourself? (a javascript fork based on `npm run quick-build` is OK as well)
  * [ ] Are you willing to provide unit tests?
  * [ ] Are you willing to update the docs?

Please tick the appropriate boxes. Feel free to remove the other sections.

**Comment by urugator** [comment]
afaik computed setters are currently not supported with decorators (should be changed in next major). As a workaround use non-decorator syntax:
```javascript
constructor() {
  extendObservable(this, {
    get fullName() { /* ... */ },
    set fullName(fullName) { /* ... */ }
  })
}
```

**Comment by grimmen** [comment]
The workaround works, but I believe it will place a separate copy of the setter function on each Person instance, which is different from just having a single copy on the Person prototype with respect to memory use.

If I rather use a setFullName(value) method it also works and I believe the memory use would be solved, but then there is the asymmetry between reading the value using object.fullName and writing it with object.setFullName(..)  

Anyway, thanks for the tip.

**Comment by mweststrate** [comment]
computed setters are supported since `2.6.something` indeed. Quick check, does it make a difference if the setter and getter are swapped in order. It might be that the transpiler sees it as a redeclaration instead of extension of the same property. Are you using typescript or babel?

**Comment by mweststrate** [comment]
Just tried to reproduce in typescript / babel, but as far I can see everything behaves correctly, see the above commit

**Comment by grimmen** [comment]
I was using the typescript plugin in Atom (atom-typescript 10.1.13)
tsc --version says 1.8.10

It does indeed make a difference if I change the order of the getter and the setter.  With the setter trailing the getter, the program works as expected.  Having the setter first triggers the issue.

**Comment by mweststrate** [comment]
ah i tested on typescript 2.1, that might be a difference

Op wo 14 dec. 2016 21:11 schreef grimmen <notifications@github.com>:

**Comment by grimmen** [comment]
I wanted to try running your test, so I checked out the branch with the commit above : 
git clone -b feature-modifiers https://github.com/mobxjs/mobx.git
But the tsc --pretty command fails with :
tsc --pretty
225  	if (!firstTime && changed === true)
     	                  ~~~~~~~~~~~~~~~~
src/api/autorun.ts(225,21): error TS2365: Operator '===' cannot be applied to types 'false' and 'true'.
135  return result;
            ~~~~~~
 src/core/derivation.ts(135,9): error TS2454: Variable 'result' is used before being assigned.

Am I doing this wrong ?

**Comment by grimmen** [comment]
btw; as I updated in the comment, the atom-typescript was using the 2.1.4 version of typescript.  I have upgraded tsc to 2.1.4 and tested again from the command line, but still get the same issue as originally described.

**Comment by grimmen** [comment]
Update : I get different results using typescript 2.0.9 and typescript 2.1.4 on this.  I managed to run the test you added in the commit above and it fails for tsc version 2.1.4 but worked for 2.0.9

**Comment by mweststrate** [comment]
Thanks for sharing, I'll check that out! We had some other issues with TS
2.1 at Mendix as well ,so pinned it to 2.0.* already, but will investigate
further

Op ma 19 dec. 2016 om 14:56 schreef grimmen <notifications@github.com>:

**Comment by mweststrate** [comment]
Confirmed, with the latest typescript version this breaks again. I think the only way to handle this correctly for now is to make sure the setter is always defined _after_ the getter.
