### ISSUE TITLE
Computed value with manual garbage collection

### ISSUE THREAD

**Issue by jas99** [mobxjs/mobx#706]
Hi @mweststrate 
Based on snipt in issue #356 
```
function memoize(expr) {
  var c = computed(expr)
  var v;
  var d = c.observe( (newValue)=> {v = newValue})
  return {
    get: ()=> {return v},
    stop: ()=> d()
  }
}
```

I get the following error
`VizStore.js:14 Uncaught TypeError: c.observe is not a function`

Following is my .babelrc file
```
{
  "presets": ["es2015", "stage-3", "react"],
  "plugins": ["add-module-exports"],
  "env": {
    "production": {
      "presets": ["react-optimize"],
      "plugins": ["babel-plugin-dev-expression","transform-decorators-legacy","transform-class-properties"]
    },
    "development": {
      "presets": ["react-hmre"],
	  "plugins": ["transform-decorators-legacy","transform-class-properties"]
    },
    "test": {
      "plugins": [
        ["webpack-loaders", { "config": "webpack.config.test.js", "verbose": false }]
      ]
    }
  }
}
```

Thx

**Comment by vonovak** [comment]
There is no such thing as    .observe(). You want to use `reaction`

**Comment by jas99** [comment]
Hey Thx for reply @vonovak 
Chk out #356
Can you edit my snipt code to accomplish what I am looking for 

Thx

**Comment by vonovak** [comment]
take a look at the [docs](http://mobxjs.github.io/mobx/refguide/reaction.html) they will help you

**Comment by jas99** [comment]
hey @vonovak 
based on http://mobxjs.github.io/mobx/refguide/reaction.html

> computed(expression)  
>
> computed can also be invoked directly as function. Just like observable(primitive value) it will create a stand-alone observable. Use .get() on the returned object to get the current value of the computation, or .observe(callback) to observe it's changes. This form of computed is not used very often, but in some cases where you need to pass a "boxed" computed value around it might prove useful.
>
>Example: 
import {observable, computed} from "mobx";
var name = observable("John");
var upperCaseName = computed(() =>
    name.get().toUpperCase()
);
var disposer = upperCaseName.observe(name => console.log(name));
>
>name.set("Dave");
// prints: 'DAVE'

why observe is working in this example

**Comment by mweststrate** [comment]
@jas99 computed, if used as function, returns a boxed computed value that indeed exposes the `observe` method, so I can't explain that exception. Can you create a reproduction somewhere?

As @vonovak indicated, it is often better to use `autorun` / `reaction`, as those respect transactions etc. `observe` is quite a low level primitive, although it has its uses.

**Comment by vonovak** [comment]
ah, there we go. Since I didn't see `observe` in the docs I thought there wasn't such a thing.

**Comment by mweststrate** [comment]
oops, should be in there. computed is almost liked boxed value, except that
it cannot be intercepted

Op vr 16 dec. 2016 22:49 schreef Vojtech Novak <notifications@github.com>:

**Comment by mweststrate** [comment]
@jas99 did you have a reproducible setup where the `c.observe` in which the issue occurs or has the issue been solved?

**Comment by jas99** [comment]
@mweststrate I just referenced computed getters in autorun for now as a hack (since wanna cache then for whole app lifetime in my usecase). I am lil busy with my work; will give it another shot and discuss further on this thread in future.

**Comment by jas99** [comment]
Hey @mweststrate 

Please chk out this fiddle
https://jsfiddle.net/jas99/m1h0up7L/https://jsfiddle.net/jas99/m1h0up7L/

Thx

**Comment by mweststrate** [comment]
@jas99 you are using `computed` in a wrong way, your `memoize` function is invoked as decorator, see please check how decorators are written in general. 

Since it is used as decorator, first argument is not an expression, it is an object (the target object to which the decorator is applied). Since it is passed to `computed`, you are invoking the decorator overload of `computed` as well, instead of creating the boxed computed value you think you are creating. Also note that you should be returning a *descriptor* from your memoize function, in which you cannot put arbitrary things like `stop`. The expression you are looking for is probably the `get` method of the _third_ argument passed to `memoize`, namely the getter function of the original property descriptor.

**Comment by jas99** [comment]
Hey @mweststrate 
My bad; I figured out and wrote decorators; I implemented the following for memorized decorator

```
export function memorize(target, key, desc)
{
  mobx.computed(target,key)
  keepAlive(target,key)
}
```

**Comment by jas99** [comment]
Hey @mweststrate 
Can I setup decorator such a way when computed for first time; it stays alive.

The above way getter is computed even if not manually called once. My requirement is the getter to be cached if called atleast once.

Jas

**Comment by mweststrate** [comment]
@jas99 sorry for the late response. But yes that is possible, just compose a bit more, something like

```javascript
export function memorize(target, key, desc)
{
  const computedValue = mobx.computed(desc.value) // created a boxed computed
  let aliveDisposer;  
return {
     get: function() {
        if (!aliveDisposer)
            aliveDisposer =  keepAlive(computedValue)
        return computedValue.get()
     }
  }
}
```

Since this issue is quite old, you are probably not dealing with the problem anymore, otherwise feel free to reopen
