### ISSUE TITLE
behaviour breaks when trying to comply to deprecation warnings

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx#710]
I get this warning when updating from 2.6.5 to 2.7.0:

    In MobX 2.* passing a function without arguments to (extend)observable will automatically be inferred to be a computed value.
    This behavior is ambiguous and will change in MobX 3 to create just an observable reference to the value passed in.
    To disambiguate, please pass the function wrapped with a modifier: use 'computed(fn)' (for current behavior; automatic conversion), or 'asReference(fn)' (future behavior, just store reference) or 'action(fn)'.
    Note that the idiomatic way to write computed properties is 'observable({ get propertyName() { ... }})'.
    For more details, see https://github.com/mobxjs/mobx/issues/532)in: Store@2.history.goForward

The same warning appears referencing `history.goForward`, `history.goBack` and `history.block`.

To explain what I am doing: I use:

    import createHistory from 'history/createBrowserHistory'

then do

      @observable history = createHistory()

and a computed that makes the url a central part of my store:

    @computed get url() {
      const pathNamePassed = this.history.location.pathname
      const pathName = pathNamePassed.replace(`/`, ``)
      const pathElements = pathName.split(`/`)
      if (pathElements[0] === ``) {
        // get rid of empty element(s) at start
        pathElements.shift()
      }
      // convert numbers to numbers
      // http://stackoverflow.com/questions/175739/is-there-a-built-in-way-in-javascript-to-check-if-a-string-is-a-valid-number
      pathElements.forEach((e, index) => {
        if (!isNaN(e)) {
          pathElements[index] = +e
        }
      })
      return pathElements
    }

So basically I am making history observable to derive my state from it. In some other autoruns I observe search elements and also set pathname and search elements. This has worked very nice so far.

But it seems to break with the (upcoming) changes in 2.7.0 or rather 3.

I have tried following the recommendations, for instance using this:

    @computed get history() {
      return createHistory()
    }

But it seems that somehow url changes are _NOT_ observed same as before, as my ui does not update correctly any more.

Also, using asReference does not work as that does not make history observable.

I am quite sure that I have completely misunderstood and misused something here (this is my first MobX project), so maybe you can help me to get this working.

I am using:

- mobx 2.7.0
- chrome
- node 6.9.1

**Comment by spion** [comment]
`@observable` only works on primitives, arrays and plain objects. I think the best course of action would be to create a `class ObservableHistory` with an `@observable _location` that wraps the original history object by using `originalHistory.listen(location => this._location = location)`

**Comment by mweststrate** [comment]
@barbalex excellent question. The reason for the warning is probably that the history object probably looks a bit like:

```
{
  url: "http://locahost",
  back: function() {
     // code
  },
  forward: function() {
    // code
  }
}
```

The problem with this approach is that in mobx 2, `observable` would assume (incorrectly!) that `back` and `forward` are computed values, so it would turn those methods unexpectedly into computed values, which could lead to very strange results.

To prevent that, you should explicitly make it clear whether you want a computed value (e.g. trough `computed()` or `get value() { } `, or that the values should be kept as is (your case), by means of the `asReference` modifier.

As you can see, it is quite dangerous to convert an entire object you don't control into an observable; it could have some unwanted side effects. Ideally I would try to create a wrapper / delegate object around the history as @spion suggested, otherwise, at least only convert those properties into observable properties that you actually need. Use `extendObservable` for that, for example:

```
extendObservable(history, {
  location: history.location,
  otherInterestingProps: history.otherInterestingProp
})
```

**Comment by barbalex** [comment]
You guys are real heroes!

I now have ObservableHistory.js:

    /**
     * need to build a singleton from history
     * where the needed methods are returned
     * and location is made observable
     * reason: MobX starting at v2.7.0 does not accept making history itself observable any more
     * see: https://github.com/mobxjs/mobx/issues/710
     */

    import { observable } from 'mobx'
    import singleton from 'singleton'
    import createHistory from 'history/createBrowserHistory'

    class ObservableHistory extends singleton {
      constructor() {
        super()
        this.location = this.history.location
        this.history.listen((location) => {
          this.location = location
        })
      }

      history = createHistory()
      push = this.history.push
      @observable location = ``
    }

    export default new ObservableHistory()

and in store.js:

    history = ObservableHistory

Now all my computed's and autorun's work flawlessly again, example:

    @computed get url() {
      const pathNamePassed = this.history.location.pathname
      const pathName = pathNamePassed.replace(`/`, ``)
      const pathElements = pathName.split(`/`)
      ... (some more code)
      return pathElements
    }

Thanks _a lot_

**Comment by barbalex** [comment]
by the way: I choose MobX because it is so simple to use. So you end up getting these noob questions because you made such a great job... ;-)

**Comment by barbalex** [comment]
Unfortunately now going back and forward using the browser arrows does not work any more.

It does when using

    @observable history = createHistory()

instead of

    history = ObservableHistory

**Comment by barbalex** [comment]
o.k., got that to work using this ObservableHistory.js module:

    /**
     * need to build a singleton from history
     * where the needed methods are returned
     * and location is made observable
     * reason: MobX starting at v2.7.0 does not accept making history itself observable any more
     * see: https://github.com/mobxjs/mobx/issues/710
     *
     * get ui to follow url changes when user clicks browser back and forwards buttons:
     * http://stackoverflow.com/questions/25806608/how-to-detect-browser-back-button-event-cross-browser
     */

    import { observable } from 'mobx'
    import singleton from 'singleton'
    import createHistory from 'history/createBrowserHistory'

    class ObservableHistory extends singleton {
      constructor() {
        super()
        this.location = this.history.location
        this.history.listen((location) => {
          this.location = location
        })
        document.onmouseover = () => {
          this.mouseIsInDoc = true
        }
        document.onmouseleave = () => {
          this.mouseIsInDoc = false
        }
        window.onpopstate = () => {
          if (!this.mouseIsInDoc) {
            this.location.pathname = document.location.pathname
            this.location.search = document.location.search
          }
        }
      }

      mouseIsInDoc = true


      history = createHistory()
      action = this.history.action
      push = this.history.push
      replace = this.history.replace
      block = this.history.block
      go = this.history.go
      goBack = this.history.goBack
      goForward = this.history.goForward
      length = this.history.length
      createHref = this.history.createHref
      @observable location = ``
    }

    export default ObservableHistory.get()

**Comment by goldylucks** [comment]
I got it working like this:

```
import { createBrowserHistory } from 'history'
import { observable, decorate } from 'mobx'

const history = createBrowserHistory()

decorate(history, {
  location: observable,
})
export default history
```
