### ISSUE TITLE
Strange behaviour with JSX elements / React and node 'production' environment variable

### ISSUE THREAD

**Issue by MastroLindus** [mobxjs/mobx#716]
Having an issue using mobx in combination with react when using the production node_env variable.
Consider the following code.
```
class Container {
  @observable public testArray: Array<any> = [];
}

class RandomClass {private x = 1;}

const StatelessComp = () => <div>stateless</div>;

const StatelessCompWithParams = (props: {}) => <div>statelessWithParams</div>;

class StatefulComp extends React.Component<{},{}> {
  public render() {
    return <div>stateful</div>;
  }
}

const t = new Container();
  t.testArray.push(3);
  t.testArray.push("string");
  t.testArray.push(new Element());
  t.testArray.push(<div>html</div>);
  t.testArray.push(<StatelessCompWithParams/>);
  t.testArray.push(<StatelessComp/>);
  t.testArray.push(<StatefulComp/>);
  console.log(t.testArray);

  // change the 4 to a 5 or 6 to get the runtime error described below
  ReactDOM.render(t.testArray[4], document.getElementById("reactRoot"));

```
This is typescript code that I build&bundle using webpack.

If I look at the output of the log, I can see the observable array, and I can see the 7 elements I put in as they originally are, and they work just fine wherever I use them, or when I render them in case of JSX elements.

If I now switch to a production configuration by setting the NODE_ENV environment variable to "production" as described in the react documentation (here: https://facebook.github.io/react/docs/installation.html ) however, the behaviour changes. 
The string, number and random class are exactly as before, but the JSX.Elements get changed to an instance of a mobx observable object (in the console I can see they get augmented with mobx getters/setters).

What is worse is that trying to render the statelessCompononent without parameters and the stateful component will result in a react runtime error.
Try for example to render the 5th or 6th element in the above example instead of the 4th.

Error with stateless component without parameters: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

The error with stateful component comes from here: function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }. React calls thats _classCallCheck function before instantiating the component and the instanceof check fails.

The stateless component with parameters works.

Mobx version: 2.6.3
React version: 15.4.1
Typescript version: 2.1.1

Expected Behaviour:
Using the production flag should not alter the behaviour of the code above. Either It should always output the original object or the wrapped one. In my case either would be fine, since I can still use asReference. 
Also there shouldn't be any difference in behaviour between an observableArray of JSX elements and an observableArray of a random class or primitive value.

Actual Behaviour:
-Behaviour for JSX.Elements differs when having the production flag on and off
-Behaviour differs between JSX.Elements and other types (primitives and random classes).

**Comment by urugator** [comment]
MobX arrays are by default deeply/recursively observable... anything pushed to array is converted into observable ... so you're passing some observable object to render function instead of originally pushed element/string/component/function. Use `asFlat` modifier on array:
```javascript
class Container {
  @observable public testArray: Array<any> = asFlat([]);
}
```

**Comment by MastroLindus** [comment]
I am aware of the recursive behaviour of observable, if it is consistent. I even mentioned using asReference as a workaround (or even better asFlat as you suggest).
The main problem here is that I don't want having 2 different behaviours with the flag turned off or on, and I don't want JSX.elements to behave in a special/different way from other types.

**Comment by urugator** [comment]
May it be that JSX.Elements are converted to a different type on production env as a result of some optimization? Therefore MobX conversion logic is the same, but different type is being converted?

**Comment by MastroLindus** [comment]
It might well be the case, I am sure that react applies optimizations or at least strips some logging and warnings with the production flag set, while I am not aware of documented change in behaviour in mobx.

However given that observable members are supposed to be used transparently and in case of JSX.Elements it creates runtime errors, I think is still a mobx issue. I shorted the reproduction code to the following:

```
class Container {
  @observable public testElement = new Element();
  @observable public testJSXElement = <StatefulComp/>;
}

 const t = new Container();
  console.log(t.testJSXElement);
  console.log(t.testElement);

  ReactDOM.render(t.testJSXElement, document.getElementById("reactRoot"));
```

this code will work perfectly fine with the production flag off, and it will throw a runtime exception with the production flag on. The console logs will show the difference in the output of the observable wrapping in the 2 cases, while the testElement will obviously remain the same in both scenarios.

**Comment by urugator** [comment]
> I am not aware of documented change in behaviour in mobx for this flag

I am trying to suggest that there probably isn't any change in MobX behaviour with production flag.
The MobX behavior is still the same, `observable` doesn't autoconvert objects with prototype, but it autoconverts plain objects. So if <StatefulComp/> results in prototypeless object on production (unlike `new Element()` which is explicitely instantiated via new), then it's autoconverted to observable and the behavior stays consistent on MobX side ... otherwise the MobX would have to somehow detect (wonder how) that a passed plain objects is accidentaly also a "JSX.Element" and introduce a special treatment for such plain objects, and that would actually introduce inconsitency...

**Comment by mweststrate** [comment]
@urugator is right; MobX is working here as intended. use modifiers (`asFlat`, mobX 2), or shallow collections (`observable.shallowArray` or `@observable.shallow`, mobx 3).

**Comment by chebum** [comment]
Hi,

It seems that `@observable.shallow` decorator doesn't solve this problem. I prepared a small project illustrating this. 

```
let collection;

@observer
class Collection extends React.Component<{}, {}> {
	@observable.shallow items: JSX.Element[] = [];

	constructor(props) {
		super(props);

		collection = this;
	}

	@action.bound
	addItem() {
		this.items.push(<div>My item {this.items.length + 1}</div>);
	}

	render() {
		return <div>
			{this.items}
		</div>
	}
}

const root = document.body.querySelector("#app-mount");
ReactDOM.render(
	<div>
		<button onClick={() => collection.addItem()}>Add item</button>
		<Collection />
	</div>,
	root
);
```

This code breaks when being compiled by webpack with NODE_ENV being set to "production":
```
plugins: [
new webpack.DefinePlugin({
	"process.env.NODE_ENV": "\"production\""
})
]
```

I dug into the problem and it seems that in production mode mobx creates unnecessary ObservableValue containing correct ObservableArray. Here go two screenshots of the `addObserver` function's state

In development mode:
![development](https://user-images.githubusercontent.com/1398682/31722732-28f76286-b41d-11e7-9e7c-449c39380c16.JPG)

and in production mode:
![production](https://user-images.githubusercontent.com/1398682/31722750-3311c284-b41d-11e7-8448-e6a31561e300.JPG)

As you can see there is unnecessary observable in the production mode. Our Collection instance subscribes to that incorrect observable not to our observable array.

@mweststrate Do you have any ideas why this excessive observable may be created in the production mode?

I prepared a sample project illustrating the issue:
[test-project.zip](https://github.com/mobxjs/mobx/files/1394797/test-project.zip)

To build the app and open a hosting HTML page in your web browser.
```
npm install
npm run production
```

**Comment by chebum** [comment]
I was able to find root cause. It seems that in development mode react's `validateChildKeys` method iterates over the array and thus makes second subscription. This method isn't called in production.

So, the solution would be to change the render method to
```
render() {
	return <div>
		{this.items.peek()}
	</div>
}
```
