### ISSUE TITLE
get / set ES6 syntax

### ISSUE THREAD

**Issue by kmalakoff** [mobxjs/mobx#72]
I was doing something like this to ensure only one node has the isActive property on it at a time:

```
class Store {
  @observable activeNode = null;

    this.autorun(() => {
      if (this.previousActiveNode === this.activeNode) return;

      immediate(() => untracked(() => {
        if (this.previousActiveNode) this.previousActiveNode.isActive = false;
        this.previousActiveNode = this.activeNode;
        if (this.activeNode) this.activeNode.isActive = true;
      }));
    });
}
```

I'm new to ES6 get / set so I naively tried this:

```
class Store {
  @observable get activeNode() { return this._activeNode; }
  set activeNode(activeNode) {
    if (this._activeNode === activeNode) return;
    if (this._activeNode) this._activeNode.isActive = false;
    this._activeNode = activeNode;
    if (this._activeNode) this._activeNode.isActive = true;
  }
}
```

but am getting `Uncaught Error: [mobservable.view '.activeNode'] View functions do not accept new values`.

I guess I'm wonder what is the best way to write this? 

(1) for the previous value and value to return from get, can I get rid of the this._active node by getting access to the underlying storage used by mobservable? If so, what would the get and set look like?

(2) is (1) isn't possible, is there a good way other than autorun to achieve feature of one node only having isActive set on it?

**Comment by kmalakoff** [comment]
I probably should have said that I'm doing this for two reasons:

(1) optimization - rather than potentially redrawing every node when the active changes by watching the the store's active node directly, each component only watches the local isActive property so there will be maximum two nodes redrawn.  

(2) reducing access to the store - I don't use globals for the stores, but DI though the context so not all code should have or needs access to the store directly (but (1) is the main reason).

**Comment by mweststrate** [comment]
I think this is best solved by making `isActive` a stand alone computed value on the Node. This means that you won't trigger a re-render for all of your nodes. You will trigger a re-evaluation of all `isActive` expressions, but in my experience that is no performance issue. So you get:

```javascript
class Store {
  @observable activeNode = null;
}

class Node {
   // in render, use isActive, because as long as its result isn't changed it won't be propagated
   // to render
   @observable get isActive() {
        return this.store.activeNode === this;
    }

    makeActive() {
       this.store.ActiveNode = this;
    }
}
```

Note that `isActive` will only be evaluated for all visual nodes when the selection changes, in all other nodes there is no observer on the property so it won't be re-evaluated (see my upcoming blog post, lol)


Note btw that in you could even entirly solve it in the `render` method of your component using [expr](https://github.com/mweststrate/mobservable/blob/master/src/core.ts#L275) which creates a nested temporarily computed value, which, as long as it doesn't change, will prevent the outerly computed value (the render) from being re-evaluted
```javascript
render() {
  if (mobservable.expr(() => this.props.store.activeNode === this.props.node) {
    // active
  } else {
    // not active
  }

}

**Comment by kmalakoff** [comment]
I see this could be a good middle ground if the triggering of the reevaluations proves not to be too noticeable...I originally added isActive to help improve UI responsiveness at 1000s of nodes as a slightly deeper optimization so having this intermediate buffer for halting propagation would contribute to reducing the propagation of changes, but not the reevaluation (as you say).

Now that's I've played around with get / set more, what about:

class Store {
  @observable _activeNode = null;

  get activeNode() { return this._activeNode; }
  set activeNode(node) {
    if (this._activeNode === node) return;

   transaction(() => {
      if (this._activeNode) this._activeNode.isActive = false; 
      this._activeNode = node;
      if (this._activeNode) this._activeNode.isActive = true; 
   });
  }
} 

I think this would solve both the re-evaluation and change propagation problem. I'm just not sure about cycles / reactivity side effects...

**Comment by mweststrate** [comment]
I think your solution here is fine if determining the isActive state reactively is too expensive.

I was thinking about loosen the constraints on cycles and autorun's a bit, for example to allow it within the constraint that cycles converge to a value in, (magic number alert) for example 10 evaluations.

**Comment by kmalakoff** [comment]
Thank you for the feedback. 

I think the convergence check idea could be great...I find myself sprinkling in untracked or immediate calls to get around cycle detected. I think Angular 2 keeps running its dirty checking until it converges. 

If you add a magic number, it would be good to be configurable for troubleshooting.

**Comment by mweststrate** [comment]
Closing this issue as a result of releasing 2.0, to have a clean sleet for any future discussions on improving `MobX` :)
