### ISSUE TITLE
Why there's one central store?

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx#726]
I'm curious why there's usually one large global store in a MobX application as opposed to a hierarchical tree of smaller stores defined per component which would inherit data from the ancestor store.  This would better restrict access to the data.

**Comment by Keats** [comment]
You can have as many stores as you want to? We certainly do

**Comment by VolCh** [comment]
We use many global stores (one per Bounded Context, plus one to global app state like username, credentials, location) and many local component's stores (like form and filter  states)

**Comment by benjamingr** [comment]
I have a lot of stores rather than a global hierarchical one. MobX does not impose an architecture.

You're welcome to do what works for your use case :)
