### ISSUE TITLE
Documentation left hand table of contents menu is broken?

### ISSUE THREAD

**Issue by w-** [mobxjs/mobx#727]
Welcome to MobX. Please provide as much relevant information as possible!

I have a*:

2. [ x] Issue. Please make sure you have the following:
  * [ x] Did you check this issue wasn't filed before?
yes

  * [x ] What is your issue? Why do you thing this is not the expected behavior?
the documentation at http://mobxjs.github.io/mobx/index.html seems to have  a bug but only in chrome. at first all is good. then clicking on any page in the left hand nav seems to result in
![image](https://cloud.githubusercontent.com/assets/357317/21519575/d3be286a-cd20-11e6-94c6-03dc7263e04a.png)
The page navigated to is correct. In order to get back the correct table of contents, however, we need to reload the page

  * [x ] What MobX version(s) are you using? Which browser / node / ... version?
chrome 55.0.2883.87

It may just be me, but i thought i would raise it in case someone is able to repro.

**Comment by andykog** [comment]
@w-, may be some chrome extension breaks it? Have you tried this in private mode? (assuming you haven't allowed any extensions in private mode)

**Comment by w-** [comment]
ah ok. It totally works in private mode. Guess it is just on my end.
 =(

**Comment by andykog** [comment]
@w- would be still interesting if you find out what breaks it

**Comment by mweststrate** [comment]
Ah that is interesting, I am seeing this lately as well :) And not in
private mode indeed. Have to figure out which extension is responsible, as
private mode also fixed it for me :)



Op wo 28 dec. 2016 om 13:29 schreef Andy Kogut <notifications@github.com>:

**Comment by w-** [comment]
@mweststrate 
i just have ublock origin, ghostery and google drive extensions
first thought would be ublock origin or ghostery, but the only things those are blocking is google analytics and disqus

What have you got?

**Comment by andykog** [comment]
Would be nice if somebody tries clearing cache/localstorage/cookies. If it helps, the problem is not caused by extensions
