### ISSUE TITLE
Typed factories creates no instances

### ISSUE THREAD

**Issue by EmilTholin** [mobxjs/mobx#728]
I just read the changelog for 3.0.0 and got incredibly excited. Can't wait!

I might be misunderstanding the changelog, but I think I have an issue:
  * [x] Did you check this issue wasn't filed before?
  * [x] What is your issue? Why do you thing this is not the expected behavior?
I tried an `@observable.array` decorator and the instance of the class did not get an array. The classic`@observable` works great.
  * [x] What MobX version(s) are you using? Which browser / node / ... version?
MobX@3.0.0-rc.1, Chrome 55.0.2883.95 (64-bit)
  * [x] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for most issues.
I created this [**jsbin that isolates the problem**](http://jsbin.com/pomuwejedo/1/edit?js,console,output). Changing to `@observable arr = [1, 2, 3];` works great.

**Comment by mweststrate** [comment]
Thanks for testing!

`observable.array` is not a decorator, but a function that creates a new observable array. This might be confusing indeed and I'll make sure it will be abundantly clear in the docs. But a quick overview:

* `observable`: decorator *and* function
* `observable.(shallow)?(array|object|box|map)`: functions
* `observable.(shallow|deep|ref)`: modifiers; can be used as decorator *or* values can be wrapped in them before passing them to `extendObservable` / `observable.object`

**Comment by EmilTholin** [comment]
Ah, now I get it. Thanks Michel!
