### ISSUE TITLE
React Router 4 Match render not re-rendering on observable changes

### ISSUE THREAD

**Issue by adriantwarog** [mobxjs/mobx#741]
I am having a problem where the react routers `Match` used with `render={}` does not re-render when an observable variable from then component is updated.  The simplest explanation I can offer is below:

```
@observable observableArrayItem = []

construction(props){ 
   super(props);
   fetchFunction().then(res=>this.observableArrayItem = res) 
}

<Match pattern={this.props.pathname} render={() => <Component with={this.observableArrayItem} />} />
```

I have the following:
"react-router": "next",
"mobx": "^2.6.5",
"mobx-react": "^4.0.3",

If I call a `console.log(this.observableArrayItem.length)` before the return, it will re-render properly, 
or if I de-structure it using a `const { observableArrayItem } = this` and pass observableArrayItem directly
or if I remove it from the Match component.

However it does not re-render if I use `this.observableArrayItem` directly to the Component in the Match.

Any questions let me know.

Thanks

ps. I have also tried to follow the instructions here:
https://mobx.js.org/best/react.html#mobx-only-tracks-synchronously-accessed-data
by creating a seperate observer component that gets passed the {this.observableArrayItem } however this still did not work

**Comment by mweststrate** [comment]
@adriantwarog the problem is that your component does not use the `observableArrayItem`, so it won't react to it. The thing is only used in the (anonymous) component in the `render` property. So any of the following solutions should work:

```
const ObserverComponent = observer(({ array } => <Component with={array} />))
...
<Match pattern={this.props.pathname} render={() => <ObserverComponent array={this.observableArrayItem} />} />

/// OR:
<Match pattern={this.props.pathname} render={() => <Observer>{() => <Component with={this.observableArrayItem} />}</Observer>} />
```

**Comment by adriantwarog** [comment]
I have updated to mobx version 3 which seems to have resolved the issue without changing any code. Thank you for the suggested code patters which I can look at using in future projects.
