### ISSUE TITLE
Allow @observable to be applied to whole class

### ISSUE THREAD

**Issue by danielearwicker** [mobxjs/mobx#743]
For a simple all-observable class:

```ts
class Person {
    @observable name: string;
    @observable age: number;

    constructor(name: string, age: number) {
        this.name = name;
        this.age = age;
    }
}
```

it’s frustrating not to be able to use TypeScript’s public prefix on the constructor parameters:

```ts
class Person {
    constructor(
        @observable public name: string, 
	@observable public age: number) {}
}
```

Obviously once you have ten properties this would become genuinely helpful. [But this has been ruled out](https://github.com/Microsoft/TypeScript/issues/10777) because it clashes with decorators on the parameters themselves (rather than the properties they create in this case).

If we could apply `@observable` to the whole class and this be equivalent to marking every property as observable, we’d get the even neater:

```ts
@observable
class Person {
    constructor(
        public name: string, 
	public age: number) {}
}
```

**Comment by mavericken** [comment]
Hmm... in my project on typescript 2.1.4, I am kinda able to do this for some reason:
```
class Person {
    constructor(
        @observable public name: string, 
	@observable public age: number) {}
}
```
Only thing was I had to hack mobx so that it would allow additional parameters in createObservable.  For some reason, createObservable is called like createObservable(class,undefined,0).  I dont understand why it is being passed the undefined and the 0, but it isn't hurting anything once I strip the argument check.

**Comment by mweststrate** [comment]
Should `@observable` also auto decorate methods as `action` and getters as `computed`? This can get tricky if you have an utility methods that is used by a getter.

**Comment by danielearwicker** [comment]
That would surprise me a little given the name! :)

BTW I think the reason @mavericken saw extra parameters being passed is because those are interpreted as [decorators on the parameters](https://www.typescriptlang.org/docs/handbook/decorators.html), so the 0 indicated the first parameter, etc.

**Comment by urugator** [comment]
> That would surprise me a little given the name! :)

Hm, but maybe it should be aligned with `observable` function, which converts getters...?
Btw I wonder, can't we use `@observable` for decorating computed getters as well?

**Comment by mweststrate** [comment]
See also https://github.com/farwayer/mobx-decorators/issues/3 and #927 

Is this something that should be in MobX :) ? I never really needed it that hard. But it is an easy feature to implement and somehow MobX users tend to hate boilerplate... :-P. 

I doubt if it can be called `@observable` though, it will probably collide with one or another overload

**Comment by farwayer** [comment]
Yep it can be useful specially for data only observable classes. I will add @allObservable class decorator to [farwayer/mobx-decorators](https://github.com/farwayer/mobx-decorators) soon.

**Comment by mweststrate** [comment]
Closing as https://github.com/farwayer/mobx-decorators already provides @allObservable. Thanks @farwayer
