### ISSUE TITLE
lastObserved function (so we can do cool stuff)

### ISSUE THREAD

**Issue by mavericken** [mobxjs/mobx#748]
I have a*:

3. [x] Idea
  * [ ] What problem would it solve for you?
_It would allow simpler syntax for some use cases.  For example, if we wanted to establish 2 way binding on a textbox with mobx-react:_
```
function bind(observedValue){
    var observed = lastObserved();
    return {
        value: observedValue,
        onChange: function(e){
            observed.set(e.target.value)
        }
    }
}
export function Component(){
    return <input {...bind(state.username)} />
}
```
  * [x] Do you think others will benefit from this change as well?
  * [ ] Are you willing to (attempt) a PR yourself? (a javascript fork based on `npm run quick-build` is OK as well)
_I would have made one, but the whole build setup is profoundly incompatible with windows.  It would be nice if it used node.js scripts instead of bash.  However, I did hack some working code into the bundle:_

```
function lastObserved(thing, prop) {
    var derivation = globalState.trackingDerivation;
    if (!derivation)
       return log("lastObserved() can only be used if a derivation is active, or by passing an computed value / reaction explicitly. If you invoked lastObserved from inside a computation; the computation is currently suspended but re-evaluating because somebody requested it's value.");
    return derivation.newObserving[derivation.unboundDepsCount-1];
}
exports.lastObserved = lastObserved;
```

  * [ ] Are you willing to provide unit tests?
  * [ ] Are you willing to update the docs?

**Comment by mavericken** [comment]
Actually I just realized that the escape hatch I needed was inside all along:
```
import {extras} from 'mobx'

var mobxGlobalState = extras.getGlobalState()

function lastObserved() {
    var derivation = mobxGlobalState.trackingDerivation;
    return derivation.newObserving[derivation.unboundDepsCount-1];
}

function bind(observedValue){
    var observed = lastObserved();
    return {
        value: observedValue,
        onChange: function(e){
            observed.set(e.target.value)
        }
    }
}
```

**Comment by mavericken** [comment]
I started adding more to what I was doing and it stopped working right.  There is an optimization in the code which prevents newObserving from filling up with duplicate records, so you can't reliably get the last observed observable in real world scenarios.

A small patch in src/core/observable.ts would fix it:
```
export function reportObserved(observable: IObservable) {
	const derivation = globalState.trackingDerivation;
	if (derivation !== null) {
		/**
		 * Simple optimization, give each derivation run an unique id (runId)
		 * Check if last time this observable was accessed the same runId is used
		 * if this is the case, the relation is already known
		 */
		if (derivation.runId !== observable.lastAccessedBy) {
			observable.lastAccessedBy = derivation.runId;
			derivation.newObserving[derivation.unboundDepsCount++] = observable;
		}
               derivation.lastReportObserved = observable; //by adding just this line here, it becomes possible to get last observed
	} else if (observable.observers.length === 0) {
		queueForUnobservation(observable);
	}
}
```

It isn't the end of the world for me if we don't get it.  I can always patch my own copy of mobx.  I just figure that if we expose the lastReportObserved, it will be possible to make shared packages which take advantage of it using stock mobx.  I feel that the possibility of shorter string-free repetition-free syntax makes for a good selling point, worth a few extra processor cycles, transmission bytes, and memory bytes.

**Comment by mweststrate** [comment]
Exposing `lastObserved` sounds pretty dangerous to me, I think it is safer to explicitly ask for the related observable, see e.g. `extras.getAtom` of a certain property. N.B. see also: https://appendto.com/2017/01/introduction-to-data-binding-with-mobx/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+appendto+%28appendTo%29

**Comment by mavericken** [comment]
The dangers of using strings to find atoms cannot be managed conveniently or in one place.  `lastObserved` provides a type safe string free way to get the atom, which should be safer overall.

Also, the bind strategy in your link not only relies on error prone strings, but also unique IDs, which pose problems for large applications (or any sized React applications...).

Perhaps you are seeing some dangers that I am not seeing?  So far the only gotcha I have run into is that you only get the last _dereferenced_ observable property:
```
//BAD
var thingIWantedToBind = myObservable.theProperty;
var irrelevantInfo = myObservable.irrelevantProperty;
var atom = getLastObserved(thingIWantedToBind) // gives you the irrelevant property instead of the thing you wanted to bind
``` 

```
//GOOD
var thingIWantedToBind = myObservable.theProperty;
var irrelevantInfo = myObservable.irrelevantProperty;
var atom = getLastObserved(myObservable.theProperty) // gives you the thing you wanted to bind
``` 

Perhaps it should be called `lastDereferencedAtom` so that better describes what it is.

One other point, it is really just being tacked on to an internal structure that you already dangerously exposed.

**Comment by benjamingr** [comment]
I'm also -1 on this.

**Comment by mavericken** [comment]
So, I believe I have found a better way to do this, so I don't really need lastObserved tracking anymore.  

My new syntax looks like this:
```
var myObservable = mobx.observe({a:1}
var Component = ()=><div><BoundInput bind={ref(myObservable).a} /> Value is: {myObservable.a}</div>
```

[Typescript advanced types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) are very powerful.  If anyone is interested I'll make a TypeScript gist with the full details.
