### ISSUE TITLE
Example: Mobservable with GraphQL

### ISSUE THREAD

**Issue by ansarizafar** [mobxjs/mobx#75]
Thanks for amazing work. 
Please add an example of using GraphQL, Lokka (https://github.com/kadirahq/lokka#future-development) and Mobservale.

**Comment by mweststrate** [comment]
I didn't work personally with GraphQL / Relay yet, and I won't have time to do so on a short time, so any takers are welcome :)

**Comment by ansarizafar** [comment]
I can do the GraphQL part, Relay is too complex and confusing. Lokka (https://github.com/kadirahq/lokka#future-development) can be used as simple GraphQL client. I need help to create UI and Domain stores for optimistic updates and client side cache for GraphQL queries and mutations.

**Comment by mweststrate** [comment]
Closing this one for inactivity.

**Comment by antitoxic** [comment]
Related #297
