### ISSUE TITLE
observer stops working inside third party library

### ISSUE THREAD

**Issue by wildeyes** [mobxjs/mobx#753]
I have a bug in combination with onsen-react.

When using their `List` component, `mobx-react`s `observer` stops working.

Here's a reproduction: http://www.webpackbin.com/4kuYpLZ8z
Clicking 'configure' shows packages versions (all latest).

**Comment by leader22** [comment]
http://www.webpackbin.com/41xvPPbLz

```jsx
function Item({n}) {
  return (
    <div>
        <h1 style={{ display: data.state ? 'inherit' : 'none' }}>{n}</h1>
        <button onClick={_ => data.state = data.state ? false : true}>click me</button>
      </div>
  );
}
const OItem = observer(Item);

function HelloWorld () {
  return (
    <Ons.List
      dataSource={['1','2','3']}
      renderRow={n => {
        return <OItem n={n} />
      }}
    />
  );
}
```

You can make it works by wrapping each row component by `observer`.
Any other problems?

**Comment by wildeyes** [comment]
Interesting, could you explain why this happens?

**Comment by leader22** [comment]
First of all, in your first code http://www.webpackbin.com/4kuYpLZ8z
It seems that It just imports `observer`, but it does not apply to any component.

so, you have to pass **observed** component into `Ons.List.renderRow` func.

**Comment by mweststrate** [comment]
*observers* only react to *observables* in their own render function. However, your `renderRow` is not rendered by the `HelloWorld` component, by the `Ons.List` component, which isn't an observer so it won't react. If you however create an observer component for that row it will react. Note that `renderRow = n => <Observer><OItem n={n} />` should also work.
