### ISSUE TITLE
@observable m = new Map() // typescript thinks m is a Map

### ISSUE THREAD

**Issue by tcrognon** [mobxjs/mobx#756]
Mobx version 3.0.0
Typescript 2.1.4

```
class Foo {
    @observable m = new Map();
}
```

Typescript thinks m is a Map when it is really an ObservableMap

ObservableMap uses arrays where ES6 Map uses iterators. So doing

```
const f = new Foo();
f.m.values().map(someFunc);
```

produces a typescript error even though it is valid.

**Comment by mweststrate** [comment]
Correct, typescript will always infer the type from the initial value. For that reason there is also no `map`  decorator. If you want to get access to the full type of observable maps, the simple solution is:

`@observable m = observable.map()`

I hope that helps!

**Comment by tcrognon** [comment]
That definitely helps, thanks! Closing issue.

**Comment by abelkbil** [comment]
Hi @tcrognon , @mweststrate ,
How can i create map of type WidgetModel.Widget of empty
  @observable dashboardWidgetsRegistry = observable.map<WidgetModel.Widget>();

  getWidget(id: string): WidgetModel.Widget {
    return this.dashboardWidgetsRegistry.get(id);
  }

I get below error

```
Type 'Widget | undefined' is not assignable to type 'Widget'.
  Type 'undefined' is not assignable to type 'Widget'.
```

Thankyou for support

**Comment by mweststrate** [comment]
that error is correct, `.get` on a map can always be `undefined`. After all, typescript cannot guarantee that an arbitrary `id` will actually result in a `Widget`. 

so better is:

```typescript
 getWidget(id: string): WidgetModel.Widget {
   const widget = this.dashboardWidgetsRegistry.get(id);
   if (widget) {
      return widget // TS infers that widget cannot be undefined here
   }
   throw new Error("Widget not found " + id)
 }
```

Alternatively, you can force TS into thinking `.get` is always succesfull (for examle because you know that key will always be present:

```javascript
 getWidget(id: string): WidgetModel.Widget {
   return this.dashboardWidgetsRegistry.get(id)!;
 }
```

For the future, it is better to file a new issue then commenting on a closed one; as only few people will see your message now

**Comment by abelkbil** [comment]
@mweststrate Very thanks for quick support.
