### ISSUE TITLE
Merging ES6 Map with Observable Map fails in v3

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx#762]
Using MobX v3 I'm getting:

``` [mobx] Invariant failed: Cannot initialize map from [object Map]```
When trying to do ```myObservableMap.merge(myEs6Map)```.
 
![screen shot 2017-01-14 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/1995135/21957581/8fed394e-da56-11e6-8554-07b68365e8ae.png)

Observable map is defined initially as ```@observable myObservableMap = observable.map()```
and the one I'm merging is an ES6 map clone of it (for an undo scheme) ```const myEs6Map = new Map(myObservableMap);```

**Comment by mweststrate** [comment]
@timothyallan could you set up a reproduction for this? Are you using a `Map` polyfill? Code-wise I would expect no problems here: https://github.com/mobxjs/mobx/blob/fb5928dcad24fc35bd1da07527b75e0c83686bbc/src/types/observablemap.ts#L240, where `isES6Map` is defined as https://github.com/mobxjs/mobx/blob/fb5928dcad24fc35bd1da07527b75e0c83686bbc/src/utils/utils.ts#L201

**Comment by suubee** [comment]
I've got the Babel polyfill, but using the latest Chrome so it shouldn't be using it. I'm out of town for a bit, and will see if I can get a repro going when I get back.

**Comment by timothyallan** [comment]
I've got the Babel polyfill, but using the latest Chrome so it shouldn't be using it. I'm out of town for a bit, and will see if I can get a repro going when I get back.

**Comment by timothyallan** [comment]
Looks like you get a 2 for 1 with #779, as this one seems to be fixed with 3.0.2 :)
