### ISSUE TITLE
Strange @computed behaviour after update from 2.2 to 3.0.1

### ISSUE THREAD

**Issue by rasdaniil** [mobxjs/mobx#768]
Hello 

After update now this doesn't work when the second return argument changes. Despite the fact that both arguments are already true, the computed is still false.

  @computed get isReady() {
    return this.recipes.isReady && this.records.isReady;
  }

But this works perfectly!

  @computed get isReady() {
    console.log ( this.records.isReady);
    return this.recipes.isReady && this.records.isReady;
  }

Thanks

**Comment by mweststrate** [comment]
Could you provide a testable reproduction?

**Comment by rasdaniil** [comment]
Hi! Thanks for reply. I really to tried to reproduce it but on clean example everything works fine. I can't understand it, anyway will post it here:

```
  // doesn't trigger autorun in my case
  @computed get isReady() {
    return this.recipes.isReady && this.records.isReady;
  }

  // triggers
  @computed get isReady() {
    console.log(this.records.isReady); //added logging..
    return this.recipes.isReady && this.records.isReady;
  }

  // triggers
  @computed get isReady() {
    return this.records.isReady && this.recipes.isReady; //reverse order !!!!!
  }

 // triggers
  @computed get isReady() {
    return this.recipes.isReady & this.records.isReady; //bitwise
  }
```

%)

**Comment by mweststrate** [comment]
It is hard to do anything with this without reproduction. Is a less clean example an option?
