### ISSUE TITLE
build fails on windows

### ISSUE THREAD

**Issue by amir-arad** [mobxjs/mobx#770]
mobx 3.x on a windows machine:
after cloning the project and installing dependencies, building the minified file fails on a windows machine. this is also the reproduction method :)

The solution IMO is converting the build `.sh` script to javascript and running it with node.

  2. [X] Issue. Please make sure you have the following:
* [X] Did you check this issue wasn't filed before?
  * [X] What is your issue? Why do you thing this is not the expected behavior?
  * [X] What MobX version(s) are you using? Which browser / node / ... version?
  * [X] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for

**Comment by MadaraUchiha** [comment]
I'm working on it.
