### ISSUE TITLE
Observable Array Items with observe and dispose.

### ISSUE THREAD

**Issue by senguendk** [mobxjs/mobx#781]
Hi, I have a quick question regarding arrays containing observable objects, observe and dispose.
It's a little bit of a problem tracking the disposer functions for each item as items get added and remove to/from the array. Is it good practice to store the disposer functions as a member of the array items that are being observed?

So it would look like this:
```
let x = new Array<Object>()
() => {
  let newObject = observable<Object>(new Object());
  newObject.dispose = observe(newObject, (change)=>{console.log(change)});
  x.push(newObject);
}
.....
() => {
.....
  let o = x[indexOfObject];
  o.dispose()
  x.remove(o);
}
```

Even better, does the GC clean up the listener when newObject is simply deleted, so that I do not event have to dispose of it explicitly?

**Comment by urugator** [comment]
I woudn't say it's a good practise, it really depends on what you're trying to achieve.
Generally the piece of code calling `observe()` is responsible for allocating resources and therefore also for their disposal.     
Is `newObject` responsible for observing itself? Then it makes sense to store disposer with `newObject`.
It also makes sense to dispose observers from observable itself, when the observable somehow "ends"... like removing(disposing) listners(observers) of network connection when connection is terminated.
But in many cases it doesn't make sense ... usually observable doesn't even know it's being observed, so it can't dispose the observers, or even decide which one to dispose (like even emitter can't know when, what or why is listening to it's events).  

About GC, I wonder about that as well. I would be glad, if anyone could provide a detailed explanation about under which conditions it wouldn't be neccessary to call disposer manually (if such conditions exist).
And I am especially interested about `keepAlive` in case of computed getter props in classes.

**Comment by senguendk** [comment]
Thanks for the answer. The thing is, the piece of code that calls `observe()` also calls the `dispose` function and remove the item from the array. However, in order to track the `dispose` function for each array item, it _stores_ it with each array item, so there is no need to keep an array of dispose functions along side the array of objects.
In short: the item/object serves as a storage for its disposer, while the parent calls `observe` and `dispose`.

I am not sure about the GC aspect of this, but this could possible mean that it's not even necessary to call `dispose`, but rather just remove the object from the array that let GC handle the rest.

**Comment by urugator** [comment]
You could introduce some abstraction over the item, array itself or both, but it might simply not worth it.
You could also make the array observable and [intercept](https://mobx.js.org/refguide/observe.html) addition and removal of items.

**Comment by senguendk** [comment]
The second part sound reasonable, but I would still have to keep an array of dispose functions along side the array of observable objects. This not really an issue, but it also does not seems to be the cleanest of solutions.

**Comment by jamiewinder** [comment]
I'm not sure if it quite applies here, but I recently started a [utility library for MobX](https://github.com/jamiewinder/mobx-bind) for working with observable arrays (and maps) of data models which themselves should map to an observable entities which have a lifecycle (create, update, destroy) which are called as elements are added or removed from the collection. Might be worth a look.
