### ISSUE TITLE
mobx cann't tracked object when prototype in object changed?

### ISSUE THREAD

**Issue by cjd6568358** [mobxjs/mobx#784]
problem：
` 
test = observable({
        obj: {
            str: '111'
        }
    })

render(){
<Other {...test} />
}
`
when i changed test.obj.str='222',this render function doesn't run ,why?
i hope it can run render function 
Does anyone help me?
 or Is there any other solution?

**Comment by mweststrate** [comment]
Is Other an observer component?

Op vr 20 jan. 2017 om 11:24 schreef cjd6568358 <notifications@github.com>:

**Comment by cjd6568358** [comment]
NO,Other is a commn Component

**Comment by mweststrate** [comment]
?

**Comment by mweststrate** [comment]
But anyway, don't pass observables to non-observer components, as they cannot respond to them. So convert your data to non-observable in a observer component first

**Comment by cjd6568358** [comment]
@mweststrate look this code:
parent:
![image](https://cloud.githubusercontent.com/assets/3970494/22150513/4c4fbb96-df54-11e6-8758-e80f0a5cc154.png)
state:
![image](https://cloud.githubusercontent.com/assets/3970494/22150530/697ee39a-df54-11e6-9d32-ae421249e6af.png)

child:
![image](https://cloud.githubusercontent.com/assets/3970494/22150544/8110f8a4-df54-11e6-92b8-bec4d9cd8b18.png)
when i set tabBarConfig.container.hidden = true in parent component, parent component can't run render()
i want to know why?
thank you

**Comment by cjd6568358** [comment]
@mweststrate  i find  observer only can trigger  render() by observable object(a={b:11}) reference(a={c:0}) ,change object property(a.b=222) do not trigger.
for example: Index Component only can be trigger render() when tabBarConfig.container = {},if set  tabBarConfig.container.hidden = true/false can not  trigger   render()
and i want set  tabBarConfig.container.hidden = true/false also can  trigger   render(),
Is there any other way?
My English is not very good, I hope you can understand what I mean.
thanks a lot

**Comment by mweststrate** [comment]
Your example is a little bit confusing; in the first component you should use `this.props.indexState`, and throw away the willMount I think. Besides that the TabBar is the one that actually uses your data, so that one should be `observer` as well. Lastly, storing your children / container in state is very confusing, keep it in the props, otherwise your component will probably not react when receiving new props. 

For further questions, please provide a fiddle / bin / or a reproduction in any other form, which is more minimal. (there are some in the Readme which you can fork). It is now quite hard to see how it intended to work

**Comment by cjd6568358** [comment]
@mweststrate  can i provide my github project address ? 
https://github.com/cjd6568358/xgj-client
and I explain ,
TabBar component you can think of it as a black box,it is common components without mobx, it only receives the required parameters and don't need to know how it works.
What I want to know is how to modify the properties of the object can be achieved Index component  render()?

**Comment by cjd6568358** [comment]
@mweststrate  in the first component willMount  is used debug in console modify  the properties of the object

**Comment by mweststrate** [comment]
If don't want to put observer in the component, then don't send it
observables and expect it to react still. Instead send plain data, e.g.
mobx.toJS (container)

Op vr 20 jan. 2017 16:40 schreef cjd6568358 <notifications@github.com>:

**Comment by cjd6568358** [comment]
@mweststrate 
Yes, I understand. But now the focus is that I want to modify the properties of the object can automatically trigger the components of the render function, such as:
![image](https://cloud.githubusercontent.com/assets/3970494/22156462/4a16ee66-df6e-11e6-98fa-03ec6f92bc29.png)

i want modify indexState.tabBarConfig.container.hidden then trigger  Index Component render()
Is there any good way?

**Comment by cjd6568358** [comment]
@mweststrate 
It can now only trigger the render function by modifying the reference to the object

**Comment by cjd6568358** [comment]
@mweststrate 
It can now only trigger the render function by modifying the reference to the object.
such as :indexState.tabBarConfig.container = {}

**Comment by mattruby** [comment]
@cjd6568358 can you cut a simple jsFiddle test case showing your issue.  I'll try to help you out.

**Comment by cjd6568358** [comment]
@mattruby https://github.com/cjd6568358/xgj-client it's my github project address.
thank you

**Comment by mattruby** [comment]
Whoa, jsFiddle that is not.  Sorry, I don't have time to dig through that.  If you cut a simple fiddle showing your issue I'll help you out.  See https://github.com/mobxjs/mobx-examples for baseline fiddles to get you going.

**Comment by cjd6568358** [comment]
@mattruby  this is  jsFiddle address  https://jsfiddle.net/um2Lugpf/1/   ,i want modify store.config.todos.push("Get Coffee") and trigger TodoListView Component render()
Is there any good way?

**Comment by mattruby** [comment]
You're missing an `@observer`
https://jsfiddle.net/z04rgdfz/

**Comment by mattruby** [comment]
@cjd6568358 did my example there clear up your issue?

**Comment by mweststrate** [comment]
@cjd6568358 I suggest to carefully read: https://mobx.js.org/best/react.html

Realize that only data accessed in the `render` method of an `observer` component is tracked. So if you don't want to make your sidebar an observer, you have to convert the data to plain in the `Index` component, so that in that component `hidden` is tracked instead, and then passed to the TabBar. If you go for that solution, `Index` will react to the `hidden` change, and cause the TabBar to rerender.

**Comment by cjd6568358** [comment]
@mweststrate 
yes,i know that mobx can only be used to track the render function to the observer variable reference changes, and can not track changes in the variable attribute reference, right?
for example：
if observable a={
b:'123'
}
render(){
a//a={} will be trigger render(); a.b='456' will not be trigger render()
}
if i want a.b='456'  also trigger render() that render(){
a.b
}
is it?

**Comment by mweststrate** [comment]
MobX can react to any observable attribute reference, as long as the dereferencing happens in the observer component. 

```javascript
const data = observable({ a : { b: 3 }})

autorun(() => console.log(data.a.b))

data.a.b = 4
// Will print 4
```

**Comment by cjd6568358** [comment]
yes ,but i want 

const data = observable({ a : { b: 3 }})

autorun(() => console.log(data))

data.a.b = 4
// also will print { a : { b: 4 }}

**Comment by mweststrate** [comment]
As said, that is what happens if you use `toJS`. `autorun(() => console.log(mobx.toJS(data))`. 

`console.log` is, like rendering a react component, an asynchronous api. Since mobx cannot track async functions, you have to pass non-observable data to console.log to get the desired effect.

**Comment by cjd6568358** [comment]
@mweststrate yes,you are right. Is the solution I want
thanks a lot  !
