### ISSUE TITLE
Question about types flowing through "action"

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx#790]
I have a*:

1. [x] Question. Feel free to just state your question :) For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I am having an issue with type information flowing through `action` when using it with promises. TS is seeing the argument passed to the inner function as `{}` and is not able to enforce type correctness.

Here's a quick sample:

```
function getPromise() {
  return Promise.resolve('test');
}

//This one works just fine, typescript knows that x is a string
getPromise().then(x => {
  console.log(x.length);
});

//This one doesn't work, typescript thinks that x is a {}
getPromise().then(action(x => {
  console.log(x.length);
}));
```

Assume that the code above is running within a function decorated with `@action`.

I'm using the mobx.d.ts that ships with the npm module under lib (v3.0.1). For promises I'm using @types/es6-promise (v0.0.32).

I played around with the type defs a little, but I wasn't able to get anything working. I'd like to use strict mode, but not having the types flow through is a bit of a deal breaker. I'm wondering if you've encountered this and have any tips for me.

Thanks!

**Comment by scriby** [comment]
Maybe this is the best we can do?

getPromise().then(action(x => runInAction(() => {
  console.log(x.length);
})));

**Comment by mweststrate** [comment]
See also #803. Sadly typescript cannot infer this (from outside to inside through the `action` api). One work around is indeed `runInAction`, or just type `x` explicitly. Saddly there is no way to solve this though, afaik.
