### ISSUE TITLE
Idea: Allow provider to accept more than one child element

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx#791]
I have a*:

3. [x] Idea
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well?
  * [x] Are you willing to (attempt) a PR yourself? (a javascript fork based on `npm run quick-build` is OK as well)
  * [x] Are you willing to provide unit tests?
  * [x] Are you willing to update the docs?

Consider allowing Provider to accept more than one child element. This will make it easier to use and prevent the need to wrap the contents in an arbitrary div.

I'm assuming there aren't any drawbacks to supporting multiple child elements. Let me know if this isn't the case.

Thanks!

**Comment by urugator** [comment]
I personally don't use mobx's injection mechanism, so excuse me if I am wrong, but I think that Provider, as any other react component, must return exactly one react element.
If it could accept multiple children, it would still have to wrap them into a single element in it's [render method](https://github.com/mobxjs/mobx-react/blob/master/src/Provider.js#L15)

**Comment by mweststrate** [comment]
Correct, this is a known limitation until React 16 is available, which allows returning multiple elements from a single component.
