### ISSUE TITLE
Tips for optimising graph transformations with createTransformer

### ISSUE THREAD

**Issue by robclouth** [mobxjs/mobx#792]
I'm having trouble figuring out how to use createTransformer to optimise my code. 
Basically I'm creating a data-flow based visual programming language for creating GLSL shaders, so I have a graph of objects that each have arbitrary connections to other objects, except that feedback isn't allowed (i.e. no connecting to an ancestor). At the moment, if I add a connection the whole graph is re-scanned to find the new depth, ancestors and descendants of each object. However this is inefficient because if the connection is added right at the bottom of the graph, only the objects below it in the flow will be affected so it doesn't make sense to recalculate everything.

What's the best way to use createTransform to minimize the number of recomputations?

Also, each object generated code (for the GLSL shader) based on the connections that go into it. This ideally should be memoized too, but I'm struggling to figure out how fit it into the mobx paradigm.
Any tips would be great!

**Comment by mweststrate** [comment]
Could you demonstrate your case with some simple pseudo code?

**Comment by robclouth** [comment]
Sorry I was super vague. I'll explain the most difficult challenge, and if I can solve that I'll have nailed createTransformers.
I have a bunch of components that have a position and a size. Everything is locked to a grid so all sizes and positions are quantized. My task is to map a list of positions and sizes to a 2D grid, where 1 means there's something at that grid point, 0 means it's empty. Imagine like battleships.

I need this 2D grid representation to do pathfinding to automatically route the cables that connect all the objects.

What's an efficient way of constructing this? For example if only one object moves one space, the whole grid shouldn't be recomputed.

At the moment I'm using createTransformer like so:
```
// returns all objects that intersect the row at Y
objectsAtY = createTransformer(y => {
        return this.objects.values().filter(o => y >= o.bound.top && y <= o.bounds.bottom);
    })

//maps a row of objects into a 1D array of ones and zeros
    objectPositionsRow = createTransformer(y => {
        return this.objectsAtY(y).reduce((row, o) => {
            for (let x = o.bounds.left; x < o.bounds.right; x++)
                row[x] = 1;
            return row;
        }, new Array(this.size.width));
    })

// builds the final 2D grid
    @computed get objectPositionsGrid() {
        let grid = [];

        for (let y = 0; y < this.size.height; y++)
            grid.push(this.objectPositionsRow(y));    
        
        return grid;
    }
```
But, it seems that I can't use numbers as the inputs to createTransformer.

**Comment by mweststrate** [comment]
Closed for inactivity
