### ISSUE TITLE
How i set observable for array object from ajax ? 

### ISSUE THREAD

**Issue by kenshero** [mobxjs/mobx#794]
I use ajax get Item Array object and assign to @observable variable but become to "ObservableArray {$mobx: ObservableArrayAdministration}"

I want to assign [Object, Object, Object, Object, Object, Object] from ajax to @observable variable.
Can Help me please.

**Comment by urugator** [comment]
MobX 2.x `this.myObservableProp = Mobx.asReference(arrayFromAjax)`
MobX 3.x use `@observable.ref` on your prop instead
Note that changes of array won't notify observers (array itself won't be observable)

**Comment by kenshero** [comment]
Thank you. It work ! .
