### ISSUE TITLE
object not observed without decorator

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx#797]
Surely I am doing something wrong but I have not found out what so thanks for help.

I used to use es6 classes and decorators, so something like this:

    class Store extends singleton {    
        @observable datasetToDelete = {}
    }

Original Code: https://github.com/barbalex/apf/blob/aaec527bbf438e607725200f026781175cc8bf49/app/store/index.js

The app is now being refactored to use recompose and stateless functions. Not using decorators also enables using create-react-app.

So I have written this:

    const Store = {
      datasetToDelete: observable({}),
    }

The original code is here: https://github.com/barbalex/apf/blob/master/app/store/index.js

The problem is: datasetToDelete is not converted to an observable object any more. When inspecting in devtools, it remains a regular object.

What am I doing wrong?

**Comment by barbalex** [comment]
I am a bit confused by the documentation:

[Here](https://mobx.js.org/best/decorators.html) under the title

> Creating observable properties without decorators

is written:

> Without decorators extendObservable can be used to introduce observable properties on an object

On the other hand:

[Here](https://mobx.js.org/refguide/observable.html) it is stated, that usage is:

    observable(value)

**Comment by jamiewinder** [comment]
There is a difference between the two blocks of code. 

```typescript
@observable datasetToDelete = {}
```
This creates an observable property on the class, such that changes to the value of the property will be observable. It also contains the value to an observable object.
```typescript
{ datasetToDelete: observable({}) }
```
This defines a non-observable property whose value is an observable object. 

Basically if you do:
```typescript
object.datasetToDelete = { a: 1 };
```
Then observers accessing `object.datasetToDelete` *will* detect it in the first case, but not the second.

**Comment by andykog** [comment]
@barbalex, `@observable` decorator makes observable property (resulting in value being converted to observable as well)
`var a = { datasetToDelete: observable({}); }` results in only *value* being converted to observable.
what you want is: `var a = extendObservable({}, { datasetToDelete: {} })`
or `var a = {}; extendObservable(a, { datasetToDelete: {} })

**Comment by barbalex** [comment]
@jamiewinder thanks, that explains why my conversion did not work
@andykog thanks, that also explains how to do it right!

I feel that the documentation here: https://mobx.js.org/refguide/observable.html is a little misleading (at least for noobs) as the two listed methods seem to do the same thing but actually what the first does depends on how it is used as the given example is not complete.

To prevent noobs like me from getting it wrong it would be great if this part of documentation were clarified.

Thanks for this _great_ tool.
And for stellar help!
