### ISSUE TITLE
** bug ** [Mobx 3]: Reactions aren't firing: Invariant failed: reaction only accepts 2 or 3 arguments. 

### ISSUE THREAD

**Issue by grahamtallen** [mobxjs/mobx#799]
Version: Mobx 3.0.2
Environment: React-Native

I have an issue trying to implement reactions after :

This error keeps showing up, and the reactions aren't being run:
[Error: [mobx] Invariant failed: reaction only accepts 2 or 3 arguments. If migrating from MobX 2, please provide an options object] 

I have tried both this:
```
    bindReactions() {
        reaction(
            () => UserStore.finishedLoading,
            () => {
                this.loadTasks();
            },
            {context: this}
        );
        reaction(
            () => this.selectedTaskId,
            () => this.getTaskById(),
            {context: this}
        )
    }
```

and this, without an options object: 

```
    bindReactions() {
        reaction(
            () => UserStore.finishedLoading,
            () => {
                this.loadTasks();
            }
        );
        reaction(
            () => this.selectedTaskId,
            () => this.getTaskById()
        )
    }
```

Also, If "reactions only accept 2 **or** 3 arguments", then why is an options object necessary?

**Comment by mweststrate** [comment]
Could you reproduce this issue in a small fiddle or test project? Similar cases exists in the [test suite](https://github.com/mobxjs/mobx/blob/af45aa0ffc9194a119e6c76d708aaec386f83e92/test/reaction.js#L232), so it shouldn't fail. 

Could you try to reproduce the issue with this fiddle? https://jsfiddle.net/mweststrate/ocsfLfr9/2/
