### ISSUE TITLE
Mobx with Typescript action.bound type error

### ISSUE THREAD

**Issue by JohnLouderback** [mobxjs/mobx#803]
I have an issue:

  * [x] Did you check this issue wasn't filed before?
  * [x] What is your issue? Why do you think this is not the expected behavior? 
The vanilla JS API for Mobx has the method signature for `action.bound` as `bound(() => void)`. However, in Typescript the API appears to be different, causing a call like the following to not work:
```typescript
loadPeople: action.bound(function() {
  new ApiClient()['get']('api/people/load').then((data : Array<IPersonStore>) => {
    this.people.people = data;
  });
}) as () => void
```
The above show the error: `Argument of type '() => void' is not assignable to parameter of type '(a1: {}, a2: {}, a3: {}, a4: {}, a6: {}) => {}'` From what I can see this is a generic method then, but I can't understand what types I'm supposed to pass to the method then. I can't find any documentation on this either.
  * [x] What MobX version(s) are you using? Which browser / node / ... version?
**Typescript** 2.0.1, **MobX** 3.0.2
  * [x] Where can we find an isolated reproduction of your problem? A reproduction is mandatory for most issues.
See above example

**Comment by mweststrate** [comment]
Updated the typings, next mobx release will have updated typings for `action.bound` supporting this case
