### ISSUE TITLE
Missing isObservableValue()

### ISSUE THREAD

**Issue by hepiyellow** [mobxjs/mobx#804]
I think isObservableValue() is missing.

(using version 2.4.2)

**Comment by jhuiting** [comment]
There is a method `isObservableValue` in _src/types/observablevalue.ts_ but it's not exposed in utils like e.g. isObservableArray. Guess it would be more consistent to expose this one as well.

**Comment by hepiyellow** [comment]
I have tried to add `isObservableValue` to `mobs.ts`, in this line:
```typescript
export { IValueDidChange, IValueWillChange, IObservableValue, isObservableValue } from "./types/observablevalue";
```

But I am getting this ts errors:
```
Erezs-MacBook-Pro:mobx hepi$ /Users/hepi/Documents/dev/mobx/scripts/../node_modules/.bin/tsc -m commonjs -t es5 -d --removeComments --outDir lib .build/mobx.ts
.build/mobx.ts(36,63): error TS2448: Block-scoped variable 'isObservableValue' used before its declaration.
.build/mobx.ts(3728,7): error TS4025: Exported variable 'isObservableValue' has or is using private name 'ObservableValue'.
```

I guess it is needed to implement `isObservableValue` without using `ObservableValue`.
Currently I am using this hack in my own code:
```typescript
export function isObservableValue(thing: any): boolean {
    if (!thing) {
        return false;
    }
    const proto = Object.getPrototypeOf(thing);
    const name = proto.constructor?proto.constructor.name: "";
    return  name === 'ObservableValue';
}
```

**Comment by jhuiting** [comment]
@hepiyellow Misread your question somehow, too early this morning :-) Your example works fine on my machine, also seems like the right fix. Are you sure you're on the newest TS compiler? I've seen similar issues with old TS versions before

**Comment by mweststrate** [comment]
@hepiyellow probably this only happens when running `npm run small-build`, and not when run `npm run quick-build`? Feel free to submit a PR nonetheless.

The minification process currently bundles all source code in one big file, which means that sometimes variables are declared to late in the final sources to be able to use as `const`. Changing the declaration to `var` will probably fix this.

**Comment by hepiyellow** [comment]
Hi,

I tried the `quick-build` and it works, but I could manage to test it.
I used `npm-link` to include my `mobx` project (with the changes) from my other project.
And I encountered `babel` errors. 
```
ERROR in /Users/hepi/Documents/dev/mobx/lib/mobx.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "base" at 0, attempted to resolve relative to "/Users/hepi/Documents/dev/mobx/lib"
    at /Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/hepi/git/LM2_UI2/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/hepi/git/LM2_UI2/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/hepi/git/LM2_UI2/node_modules/babel-loader/index.js:88:12)
 @ ./src/app/services/LM2Store.ts 7:13-28 8:11-26
```

Would you mind making the fix yourself? (-: 
I guess if the `small-build` worked, I could have tested it more easily.
