### ISSUE TITLE
Trouble with getDependencyTree()

### ISSUE THREAD

**Issue by morganpierson** [mobxjs/mobx#807]
Having trouble using the mobx.extras.getDependencyTree() method. I simply just want a view (preferably JSON object) of my component structure, and getDependencyTree just keeps throwing errors

**Comment by mweststrate** [comment]
@morganpierson please provide both the error message and the relevant code. Preferably a small reproduction based on: https://jsfiddle.net/mweststrate/wv3yopo0/
