### ISSUE TITLE
Multiple Questions

### ISSUE THREAD

**Issue by zwhitchcox** [mobxjs/mobx#808]
I have a *:

1. [*] Question. Feel free to just state your question :) For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I'm probably going to have a lot of questions, so I'll just post them here, and whoever can respond whenever they feel like it, and I'll put a check when it's been answered. No need to create multiple issues.

- [x] What is a [trampoling](https://github.com/mobxjs/mobx/blob/master/src/core/reaction.ts#L209)?

- [x] Also,  what does [invariantLOS](https://github.com/mobxjs/mobx/blob/master/src/core/observable.ts#L150) stand for? A: Lowest Observer State

I tried to look it up, but couldn't find anything...is this a typo?

**Comment by andykog** [comment]
@zwhitchcox https://medium.com/@johnmcclean/trampolining-a-practical-guide-for-awesome-java-developers-4b657d9c3076#.oekavxxmh

**Comment by zwhitchcox** [comment]
Also, what does [invariantLOS](https://github.com/mobxjs/mobx/blob/master/src/core/observable.ts#L150) stand for?

Also, I'm probably going to have a lot of questions, so I'll just post them here, and whoever can respond whenever they feel like it
