### ISSUE TITLE
MobX 3 required native Map and is breaking iOS7

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx#810]
Not sure if MobX wants to support iOS7 or not

**Comment by andykog** [comment]
@mohsen1, are you sure this is about `Map`, not `Array#map`? Mobx doesn't use Map anywhere yet.

**Comment by mohsen1** [comment]
Getting this out of `https://cdnjs.cloudflare.com/ajax/libs/mobx/3.0.1/mobx.umd.min.js` in iOS 7:

`TypeError: 'undefined' is not a valid argument for 'instanceof' (evaluating 'e instanceof vt().Map')`

![screen shot 2017-01-31 at 11 19 58 am](https://cloud.githubusercontent.com/assets/543633/22480719/365ac064-e7a7-11e6-9f9a-8fcf96b2d172.png)

**Comment by mohsen1** [comment]
Ah I see, in non-minified code there is this:

```js
function isES6Map(thing) {
    if (thing instanceof getGlobal().Map)
        return true;
    return false;
}
```

**Comment by andykog** [comment]
@mohsen1, I see, I suppose, that is already fixed, will work fine with next release https://github.com/mobxjs/mobx/commit/d5f9f767e7939922d0fd625a14f4de489d0152cb

**Comment by mohsen1** [comment]
Yes. 3.0.2 Fixes this. Thanks for your help!
