### ISSUE TITLE
Introduce distinction between DEV and PROD builds

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#813]
Can we lift on what most people do with React as well, e.g. use `process.env.NODE_ENV` substitutions and conditions?

Things that could be stripped on PROD builds:

* Detailed error messages (see #653 )
* Many internal variant checks
* Don't show deprecation messages
* Give additional warnings & hings in dev builds, see e.g. #806

**Comment by tanzim** [comment]
@mweststrate I can take this on if no one has shown interest yet. Minor caveat is I haven't worked with TS, so bootstrapping time might be a little longer for me :)

**Comment by mweststrate** [comment]
Go for it! If you need process, you probably need put `declare var process:any` in somewhere, to signal that that is a globally available variable. Besides that typescript should hopefully not be too much in your way :)

**Comment by hccampos** [comment]
Cool stuff. Although MobX is not that big, it is always nice to get it a bit smaller. :)

**Comment by mweststrate** [comment]
This issue will be fixed in MobX 4
