### ISSUE TITLE
Reset store / store observables

### ISSUE THREAD

**Issue by exinferis** [mobxjs/mobx#814]
Welcome to MobX. Please provide as much relevant information as possible!

I have a*:

1. [ X] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

We have quite some stores with some observables (and computed values) each. Depending on the session status, these stores need to be reset at some point. What would be the most convenient and mobx compliant style to reset all the observables within a store? Just "nullify" all of them, or is there a "shortcut" for such action, I haven't noticed yet?

**Comment by jamiewinder** [comment]
There isn't really a 'store' concept in MobX itself, but presumably you mean the 'root' observable object / class? I've been happy just including a `reset` action which sets this back to the same state it was initialized with. I haven't met a situation where this wouldn't scale we'll, but if you think it mightn't in your case it'd be good to know the details.

**Comment by kamarajuPrathi** [comment]
I have the same question , is there a way for resetting a store

**Comment by sebastian-zarzycki-es** [comment]
There's no store. Just your properties and their values. "reset" is an ambiguous concept. Do what you want to them. If reset means changing them all to undefined or null, or 0, then by all means, do it. You will know best, what's the best "initial" state for them.

For what it's worth, the other question to ask here is how to do this effectively. If you have several "stores" (places with application state), then accessing them all just to call their reset() action would be a bit unwieldy. The cool way to do this is to dispatch an Event (i.e. using node's EventEmitter) and let all these "stores" subscribe to that event, resetting themselves upon receiving it. "logging out a user" is usually a common usecase for this.

**Comment by mattruby** [comment]
You could look at mobx-utils
https://github.com/mobxjs/mobx-utils/blob/master/README.md#createviewmodel

**Comment by mweststrate** [comment]
There is no generic reset concept in MobX. However, the upcoming [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree) package will feature such mechanism. So keep a close eye on that :)

**Comment by marialovesbeans** [comment]
I'm using this method to reset a store, do you think it's safe to use? @mweststrate @mattruby @jamiewinder 

```javascript
import _ from "lodash";
import { observable, computed, action, runInAction, toJS } from "mobx";

class SomeStore {
    @observable a = 1;
    @observable b = 2;
    @observable c = 3;
    @computed get d(){
        return a + 1;
    }

    // reset the store by creating a fresh new instance of the class
    // and extend the current one with it
    @action reset = () => {
        _.extend(this, toJS(new this.constructor()));
    }
}

```

**Comment by seanlarge** [comment]
late to the party here, might I suggest resting your observables when you leave a component? has anyone set something up like: 
`componentWillUnmount(){
 this.props.someThing.reset()
}
`
and your 'store'

```
@action
  reset() {
    this.questionList = null;
    this.questionResponse = new Map();
    this.responses = null;
    this.questionColor = new Map();
    this.questionComments = new Map();
    this.comments = null;
    this.grid = null;
}

```

**Comment by taylorgoolsby** [comment]
Here is a class you can extend to automatically store the initial state:

```
import {action, toJS} from "mobx";

export default class ResettableStore {
  _superInitialState: ?Object

  @action.bound
  setInitialState() {
    this._superInitialState = toJS(this)
  }

  @action.bound
  reset() {
    if (!this._superInitialState) {
      console.warn('reset() does not work unless you call this.setInitialState() at the end of the constructor.')
      return
    }

    const initialState = {...this._superInitialState}
    for (const key in initialState) {
      if (!initialState.hasOwnProperty(key)) continue
      if (key === '_superInitialState') continue
      this[key] = initialState[key]
    }
  }
}
```

All you need to do is extend it and then put `this.setInitialState()` at the end of your contructor:

```
export class MyStore extends ResettableStore {
  @observable myState: number = 0

  constructor() {
    super()
    this.setInitialState()
  }
}
const store = new MyStore()
store.reset()
```
