### ISSUE TITLE
Huge performance hit when accessing observable prototype properties

### ISSUE THREAD

**Issue by darsain** [mobxjs/mobx#815]
When you define an observable property on an objects' prototype (via `@observable`), accessing it is 20-30x slower than when it is defined on the object itself.

I would expect *some* slow down, but not something this severe, which leads me to believe this just has to be some mobx bug or a missing optimization.

Isolated benchmark of the slowdown in action: https://jsfiddle.net/sr7gvwhh/

Meat of the benchmark in question:

```js
class PropOnPrototype {
    foo = 'bar';
}

class PropOnObject {
    foo = 'bar';
    constructor() {
        this.foo = this.foo;
    }
}

class ObservablePropOnPrototype {
    @observable foo = 'bar';
}

class ObservablePropOnObject {
    @observable foo = 'bar';
    constructor() {
        this.foo = this.foo;
    }
}

const speedTest = action((Model, prop, size = 100000) => {
	// create items before the benchmark so only
	// the prop access time is measured
	const items = [];
	for (let i = 0; i < size; i++) {
		items.push(new Model());
	}

	const start = performance.now();
	for (const item of items) {
		if (item[prop] === 'bar') continue;
	}
	return performance.now() - start;
});

[PropOnPrototype, PropOnObject, ObservablePropOnPrototype, ObservablePropOnObject]
.forEach(Model => console.log(`${Model.name}: ${speedTest(Model, 'foo').toFixed(2)}ms`));
```

My results:

```
PropOnPrototype: 11.24ms
PropOnObject: 6.65ms
ObservablePropOnPrototype: 375.63ms
ObservablePropOnObject: 11.96ms
```

**Comment by urugator** [comment]
It's probably because Mobx initializes observables defined on prototype lazily during first get (so it doesn't happen on model creation as you have assumed).
Check this out: https://github.com/mobxjs/mobx/blob/master/src/utils/decorators.ts#L15

**Comment by darsain** [comment]
Oh, I see that in this modified jsfiddle, where the slowdown on `ObservablePropOnObject` just shifts to the creation time: https://jsfiddle.net/8gk011ny/

So this is the cost of creating observable properties, totally expected, and not much can be done about it?

**Comment by darsain** [comment]
Oh well. I'll have to keep this on mind.

**Comment by mweststrate** [comment]
@darsain yes this is currently as expected. Note that these numbers are even quite different when using Typescript instead of Babel (but not faster I think). Since current babel decorators is not up to date with the specs yet, (nor is Typescript's), MobX does currently same normalization to get at least consistent runtime behavior; hence the lazy first get.

This is quite inefficient indeed, hopefully this gets better when decorators are further standardized and using Proxies will definitely improve this. Thanks for the extensive test!
