### ISSUE TITLE
Flow definitions does not work in 3.0.2

### ISSUE THREAD

**Issue by schovi** [mobxjs/mobx#819]
After updating to new version 3.0.2 and running `flow-typed install` it wont generate definition file for mobx. With 3.0.1 it worked just fine. It looks like it has something to do with new building script file https://github.com/mobxjs/mobx/commit/192fd7f77f1c6fdf1b8bafc584c35778402d3233 (whole diff https://github.com/mobxjs/mobx/compare/3.0.1...3.0.2)

**Comment by mweststrate** [comment]
@A-gambit would you mind checking this one?

**Comment by mweststrate** [comment]
@schovi is this still an issue? are others running into this as well?

**Comment by schovi** [comment]
@mweststrate We ended with:

.flowconfig
```
[libs]
./flow-typed
./node_modules/mobx/lib/mobx.js.flow
```

This is stable solution for us currently :)

**Comment by hawkins** [comment]
I'm also unable to install the definition via `flow-typed install mobx@3.3.1`. However, doesn't that command only pull from https://github.com/flowtype/flow-typed/tree/master/definitions/npm? But, MobX is not listed anywhere in that repository.

However, `flow-typed install mobx@3.0.1` fails for me, unlike the author @schovi . 🤔

**Comment by Kriegslustig** [comment]
> However, doesn't that command only pull from [...]

Yes. So `flow-typed install` should never work. You can only link it as described in the docs and in @schovi 's comment.

**Comment by hawkins** [comment]
That’s what I thought, thanks for confirming. The original post indicated it worked for version 3.0.1 which threw me for a loop.

With that in mind, I think it’s safe to close this since we’ve covered that flow config step elsewhere and the original issue has been remedied.

**Comment by mweststrate** [comment]
Somebody interested in creating a PR that adds the proper flow setup to the
top of the readme (after `installation`)?

Op ma 6 nov. 2017 om 08:07 schreef Josh Hawkins <notifications@github.com>:
