### ISSUE TITLE
Autorun behavior when passed a function that has no dependencies

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx#821]
I was wondering what would happen if I passed a function to autorun that has no dependencies. In some sense, it seems like an error (at least a warning), because it will never get evaluated a second time. I tried it out and it looks like it just calls the function once and then does nothing.

The reason this came up is that I'm writing a utility function that takes an "observable" function as input, but I want it to throw an error if a function is passed that does not reference any observables, because it would indicate incorrect usage.

Is there a way I can detect if a function (after executed the first time by autorun) contains a dependency on an observable or not?

**Comment by mweststrate** [comment]
I experimented with adding that warning in the past, but it really made generic constructions hard, e.g. the `observer` decorator would start throwing warnings if you render a component that often receives a value, but sometimes not in which case it is just "static".

You can check if an autorun has observers by looking at its dependency tree:
```javascript
const disposer = autorun(() => console.log(someObservable.x))
console.dir(mobx.extras.getDependencyTree(disposer))
```

**Comment by scriby** [comment]
Perfect, thanks!
