### ISSUE TITLE
Delete function

### ISSUE THREAD

**Issue by zwhitchcox** [mobxjs/mobx#822]
I have a*:

3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?

My idea is to have a delete function on mobx object observables that performs the same operation as the `delete` operator in javascript. The only difference is this would trigger the observers of the object.

So, instead of 

```js
delete observableObj.myProp 
```

It would be
```js
observableObj.delete(myProp)
```

I think this would solve a lot of people's problems, especially people who don't want to use the ES7 maps. I guess dealing with objects is just more familiar to me and probably other people, and I would prefer that syntax.

Also, for me, this would solve the problem I'm having with 3-way data binding so the server's data isn't out of sync when I delete a property on an object. I want to be able to mirror an arbitrary data structure in my database, and I need to know when a property has been deleted to do that.

I'm pretty sure this would be a much appreciated feature in the community.

**Comment by urugator** [comment]
It would have to be an "utility" function `Mobx.deleteProp(observableObj, "propName")` or a symbol
`observableObj[Mobx.Symbol.deleteProp](propName)`, otherwise it could clash with user's `delete` method.

Would you like the delete operation to trigger autoruns/reactions like Map's `delete` or just delete the observable prop and notify listeners of `observe`? Notice there is no `set` operation for objects which would trigger autoruns/reactions, only `extendObservable`, which doesn't do that...

**Comment by zwhitchcox** [comment]
Yes, I would like to trigger autoruns and reactions, preferably to make sure the view is updated in react

**Comment by urugator** [comment]
Currently it's technically impossible. Autorun/Reaction can't subscribe for changes of object itself, only for changes of accessed properties (that's because the subscription is done in Mobx defined getters).
Consider you would be iterating the object keys inside render method - there is no way for mobx to know that it needs to re-run when some prop key is deleted.

**Comment by zwhitchcox** [comment]
Couldn't you just access it before you delete it? Or run the observers manually?

**Comment by zwhitchcox** [comment]
Oh wait...

**Comment by urugator** [comment]
> Or run the observers manually?

What would be the point of reaction/autorun then?

> access it before you delete it

If you would directly access the prop inside the `render`, then yes Mobx would be able to track that prop and re-run render on prop deletation. However thats quite inconvenient usage and very far away from what user would expect when working with maps (or key-value storage in general).

> Maybe you could have a transaction that accesses the property then deletes it

Not sure what you mean by that

**Comment by zwhitchcox** [comment]
Er...sorry, I mean, you `set` the property to a null value to trigger `autorun` and set the property to `null`, within a transaction, so the reactions don't run. Then you delete the property altogether. The reactions will run, and obviously the property will no longer be needed because you deleted it.

**Comment by urugator** [comment]
> And the autorun would be run.

... only if the deleted prop was previously accessed

**Comment by zwhitchcox** [comment]
Yeah, ok, maybe I'm wrong, but I thought autorun *always* only ran if it had been accessed during the previous autorun. So, if I don't access a property within the autorun callback, it's not going to be triggered anyway?

**Comment by urugator** [comment]
I was referring to this:
```javascript
const obj = observable({ toBeDeleted: "" });
// will re-run after obj.delete("toBeDeleted")
autorun() { 
  console.log(obj.toBeDeleted);
}
// won't re-run after obj.delete("toBeDeleted") (but it should because the output would be different)
autorun() {
  for (key in obj) {
    console.log(key);  
  }
}
òbj.delete("toBeDeleted")
```

**Comment by zwhitchcox** [comment]
Yes, that is consistent with the behavior of the rest of the events. For instance, when you run this

```js
const { observable, runInAction, autorun } = require('mobx')

const obj = observable({ toBeChanged: "" })

// will re-run after obj.toBeChanged = 'new value'
autorun(_ => console.log('first', obj.toBeChanged), false)

// won't re-run after obj.toBeChanged = 'new value'
autorun(_ => {
  for (key in obj) {
    console.log('second', key);  
  }
}, false)

obj.toBeChanged = 'new value'
```

Do you see what I mean? This is consistent with the code for deletion:

```js
const { observable, runInAction, autorun } = require('mobx')
const obj = observable({ toBeDeleted: "" })

Object.defineProperty(obj, 'delete', {
  configurable: false,
  enumerable: false,
  writable: false,
  value: function(key) {
    runInAction(() => {
      this[key] = null
      delete this[key]
    })
  }
})

// will re-run after obj.delete("toBeDeleted")
autorun(_ => console.log('first', obj.toBeDeleted), false)

// won't re-run after obj.delete("toBeDeleted") 
autorun(_ => {
  for (key in obj) {
    console.log('second', key);  
  }
}, false)

obj.delete("toBeDeleted")
```

Here is the output for the first code:
```
first 
second toBeChanged
first new value
```

And here is the output for the second code:
```
first 
second toBeDeleted
first undefined
```

In both cases the first autorun is run two times, but the second autorun is only run once. I think what triggers autorun should be consistent for both changing and deleting values.

And really, I feel like iteration should trigger an autorun, but what do you do?

**Comment by zwhitchcox** [comment]
Oh wait, I see what you mean now. You're saying the output of the second would be different because the key is different.

But another way to look at it is that mobx doesn't track key additions or deletions which is still consistent.

Consider this:

```js
const { observable, runInAction, autorun, extendObservable } = require('mobx')

const obj = observable({ toBeDeleted: "" })

Object.defineProperty(obj, 'delete', {
  configurable: false,
  enumerable: false,
  writable: false,
  value: function(key) {
    runInAction(() => {
      extendObservable(this, {[key]: null})
      delete this[key]
    })
  }
})

// will re-run after obj.delete("toBeDeleted")
autorun(_ => console.log('first', obj.hello, obj.toBeDeleted))

// won't re-run after obj.delete("toBeDeleted") (but it should because the output would be different)
autorun(_ => {
  for (key in obj) {
    console.log('second', key);  
  }
})

obj.hello = 'hi'
```

Neither autorun will be run a second time, because mobx doesn't track the keys. It doesn't have the ability to track the keys, only the values of the keys. So, if you're trying to track the actual keys of the observable, you're kind of out of luck either way.

**Comment by zwhitchcox** [comment]
Also, a hack people could use to get it to trigger is

```js
autorun(_ => {
  for (key in obj) {
    console.log(key)
    obj[key];
  }
})

**Comment by urugator** [comment]
> But another way to look at it is that mobx doesn't track key additions or deletions which is still consistent.

No it isn't.
Firstly key addition is done by `extendObservable` which doesn't invoke reactions/autoruns.
Secondly keys added by assigment, aren't observable at all, not just their addition isn't tracked, modification isn't tracked either, such keys don't relate to autoruns/reactions in any way... same can't be said about keys deleted by `delete`

**Comment by zwhitchcox** [comment]
Ok, I see. So, essentially, if I want to delete something, I should just set it to `null`.

**Comment by urugator** [comment]
Not sure if you can actually safely delete observable prop. (you can use null or some constant value as an indicator of deleted prop)
Observable additions and removals of observable fields are unfortunately not supported on objects because of mentioned technical difficulties.
Use of observable map is recommended in such situations.

**Comment by mweststrate** [comment]
For completeness sake: the potential problems with `delete` are even more subtle, as they leak in unforeseen ways:

If you delete the property from the object, the boxed observable that behind the scenes powers the property still exists; at least if it is observed. So your reactions will be observing properties that will never change in the future, but that is not something the GC can tell (until the reactions are disposed):

```javascript
var x = observable({
  y: 3 
})

// prints 3
const d = autorun(() => console.log(x.y))

// deletes the property from the object, but not the observable backing it!
delete x.y

// will still print 'x.y' in the observers list
mobx.extras.getDependencyTree(d)

// will create a "new" y property, old one still lives
// autorun will not fire 
extendObservable(x, { y: 4})

// but if autorun fires from some abitrary other reason, at that point it will start
// listening to the "new" y property and the old one will be GC-ed

```

So adding a delete could technically be done and be made to work 'consistently' with the rest of the system, but nonetheless lead to very confusing scenarios from DX perspective

**Comment by mweststrate** [comment]
> Adding/removing properties from objects seems like a core operation in
most apps

That is a questionable statement, as type systems cannot deal properly with
those operations. Which is the reason why properties need to be declared
upfront in most languages (C#, Java, etc), and cannot be added / removed at
runtime. JS is the exception here.

But anyway, as said, for varying collections, best use maps.

Op ma 13 nov. 2017 om 21:30 schreef Levi Thomason <notifications@github.com

**Comment by levithomason** [comment]
Perhaps I should have stressed "seems" and clarified "JS apps".  At any rate, I agree.  I also had somehow completely overlooked observable maps, which is exactly what I was hoping to find.

I appreciate the response.
