### ISSUE TITLE
Clean online examples using jspm

### ISSUE THREAD

**Issue by PAEz** [mobxjs/mobx#83]
I learnt about jspm today and it makes working with mobservable in plnkr a joy!!
http://plnkr.co/edit/lWPblu?p=preview

I like the fact that Im just using the normal stuff from the npm and no specific/weird/not to be supported stuff.
Now I can use my fav scratch pad to do my learning!

EDIT:
And heres your bigger example in plunker....
http://plnkr.co/edit/rVs5yE?p=preview

Had to tweak a couple of things to get it to work and all because it wasnt using the up to date stuff on npm!  This is why I like this jspm way of doing it, yeah it might be a little slow at loading all the stuff first time, but its all npm, so everything is up to date and the same as youd do locally.

**Comment by mweststrate** [comment]
Ah that is really cool! Thanks, gonna add those to the documentation.

**Comment by PAEz** [comment]
Just be aware that that second one really was just slapped together and there was some console warnings and whatever.  Also, jspm is awesome for these online tests and what not but seems to be a little sucky at packing for production.  Still, great for this.

Here's another little test I did today....
http://plnkr.co/edit/Udm85p?p=preview
http://plnkr.co/edit/69F2u8?p=preview
..its both those tests using react-lite, smaller and faster.  Unfortunately the perf stuff didnt work on the second test.  But if you do a high number of creating you can see its obviously faster.  Lite at 5000 entries was about 6-7 seconds and normal about 10.  And its alot smaller.
Also, the first test is using jsxtransformer and cdn's for all of it except mobservable because you dont have the dist directory in the npm so I couldnt use the npmcdn (only found out about that today, cool).
