### ISSUE TITLE
jest snapshot testing of mobx store 

### ISSUE THREAD

**Issue by satispunk** [mobxjs/mobx#834]
Hi,

I am using mobx 3.0.2 and jest 18.1.0

I've got store class
```
class Store {
    @observable someProp= {id: 1}
}
```

jest test
```
it('should have proper initial state', ()=> {
    const store = new Store()
    expect(store).toMatchSnapshot()
})
```

it produces snapshot like
```
Store {
}
```

So no someProp defined in Store until I call an action of store, or get/set observable value, or use extendObservable on store instance.

I use a workaround extendObservable(this, {}) in store constructor that makes test above works and to get proper snapshot
```
Store {
    "someProp": Object {
        "id": 2
    }
}
```

Any idea why it's like that?

**Comment by mweststrate** [comment]
Yes this is a limitation of the current decorator implementation, as long as the value is not read or written to; the property only exists on the prototype. That one is probably not picked up by snapshot serializer. 

There are several workarounds possible:
1. use extendObservable
2. assign the initial value in the constructor
3. Create a method that is responsible for serialization and use that in your snapshots

See this [test](https://github.com/mobxjs/mobx/blob/3ba2d240cd45351968f14d4b95c48ab7e47bf15f/test/babel/babel-tests.js#L539) for reference

**Comment by satispunk** [comment]
@mweststrate 

Yep, that's what I thought about, thank you.
Will implementation be changed in the future?

**Comment by mweststrate** [comment]
Depends on the babel updates of the decorators transformer :)
