### ISSUE TITLE
@observable on instance field not working

### ISSUE THREAD

**Issue by ldnguyen58** [mobxjs/mobx#836]
Hello.  I have this code:

```javascript
@observer
export default class Login extends Component {
  @observable canSubmit

  render() {
    ...
  }

  ...
}
```

Problem 1: when `canSubmit` is changed (i.e. `this.canSubmit = true`), `render()` is not called.

Problem 2: when I tried to set a default value to `canSubmit`, i.e.

```javascript
@observable canSubmit = false
```

I got this error: "Uncaught TypeError: decorator is not a function"

.babelrc
```
{
  "presets": ["es2015"],
  "plugins": [
    "transform-flow-strip-types",
    "transform-runtime",
    "add-module-exports",
    "syntax-async-functions",
    "transform-regenerator",
    "transform-function-bind",
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-export-extensions",
    "transform-object-rest-spread",
    "syntax-jsx",
    "transform-react-jsx",
    "transform-react-display-name",
    "transform-do-expressions",
    "react-hot-loader/babel"
  ]
}
```

package.json
```
"mobx": "^2.7.0",
"mobx-react": "^4.0.4",
...
"babel-core": "^6.21.0",
"babel-eslint": "^7.1.1",
"babel-loader": "^6.2.10",
"babel-plugin-add-module-exports": "^0.2.1",
"babel-plugin-syntax-async-functions": "^6.13.0",
"babel-plugin-syntax-jsx": "^6.18.0",
"babel-plugin-transform-class-properties": "^6.19.0",
"babel-plugin-transform-decorators-legacy": "^1.3.4",
"babel-plugin-transform-do-expressions": "^6.8.0",
"babel-plugin-transform-export-extensions": "^6.8.0",
"babel-plugin-transform-flow-strip-types": "^6.21.0",
"babel-plugin-transform-function-bind": "^6.8.0",
"babel-plugin-transform-object-rest-spread": "^6.20.2",
"babel-plugin-transform-react-display-name": "^6.8.0",
"babel-plugin-transform-react-jsx": "^6.8.0",
"babel-plugin-transform-regenerator": "^6.21.0",
"babel-plugin-transform-runtime": "^6.15.0",
"babel-preset-es2015": "^6.18.0",
"react-hot-loader": "3.0.0-beta.6",
```

Not sure what I did wrong.

**Comment by andykog** [comment]
Have you tried turning off react-hot-loader?

**Comment by andykog** [comment]
...and putting `babel-plugin-transform-decorators-legacy` before `transform-function-bind`

**Comment by ldnguyen58** [comment]
Hi, thanks for your response. I remove react-hot-loader/babel from .babelrc and move transform-decorators-legacy to before transform-function-bind, but the exact 2 problems persist.

**Comment by mweststrate** [comment]
> Problem 2: when I tried to set a default value to canSubmit, i.e.
> @observable canSubmit = false
> I got this error: "Uncaught TypeError: decorator is not a function"

That sounds like an issue with the ordering of your babel plugins. You have quite some of theme, isn't there a preset that matches your needs more closely? See for example: https://github.com/mobxjs/mobx-react-boilerplate/blob/master/.babelrc. `transform-class-properties` is responsible for the field initializers, you might also want to pull that forward

For problem 1: are you actually using `this.canSubmit` in your render function? But fixing 2 might solve one, this reeks like there is something off with the babel config.

**Comment by ldnguyen58** [comment]
I changed the code to use the exact same .babelrc from the mobx-react-boilerplate, changed the package versions of mobx, babel, plugins... to match that repo and also use the same webpack config, both problems still persist. And yes, I do use this `this.canSubmit` within `render()`.

**Comment by ldnguyen58** [comment]
After trying many options, it turned out I imported `@observable` from `mobx-react` instead of `mobx`. Very silly me 😔. Thanks everyone for your help.

**Comment by eranbaroz** [comment]
Thanks for sharing the solution.
It helped me a lot.

**Comment by mweststrate** [comment]
Tip: TypeScript :)
