### ISSUE TITLE
initialize empty observable map 

### ISSUE THREAD

**Issue by melihmucuk** [mobxjs/mobx#845]
I have a map that populated with dynamic keys. So I created observable.map() but map.set() doesnt add new keys to my map. 

Here is my code: 

```javascript
@observable tileMaps = observable.map(null, "tileMaps")

@action createTileMaps(){
	const {level} = levelStore;
	for(var i=0; i<level*level; i++){
		const tKey = 'tile#' + i
		this.tileMaps.set(tKey, {isEmpty: true, value: 0, position: {}, ref:{}});
	}

	console.log("this.tileMaps => ", this.tileMaps);
}
```

log looks like: 

![screen shot 2017-02-20 at 15 54 16](https://cloud.githubusercontent.com/assets/3147488/23125853/e429c7d4-f784-11e6-988d-535ee403fac7.png)

my deps:

```json
"dependencies": {
    "mobx": "^3.1.0",
    "mobx-react": "^4.1.0",
    "react": "~15.4.0",
    "react-native": "0.41.2"
  }
```

**Comment by jamiewinder** [comment]
Is level definitely > 0 ? Nothing else looks amiss at first glance...

**Comment by melihmucuk** [comment]
level is 5 in this case, Im sure.

**Comment by jamiewinder** [comment]
I'm not seeing the same: http://codepen.io/jamiewinder/pen/WRqmGE

It might be worth adding a `console.log` to your loop, just to be sure anything is being added... there isn't a lot that can go wrong in simple function as this.

**Comment by melihmucuk** [comment]
@jamiewinder ahhh, I forgot exporting levelStore 😅 now works. Thanks!
