### ISSUE TITLE
Can i use Mobx observe stateless component in react ?

### ISSUE THREAD

**Issue by kenshero** [mobxjs/mobx#853]
Can i use Mobx observe stateless component in react ?

**Comment by jamiewinder** [comment]
You can use a React stateless function component with MobX if that's what you mean? See the

**Comment by kenshero** [comment]
@jamiewinder  oh i will try.

thank you

**Comment by djyde** [comment]
Just try: 

```js
const App = observable(({ name }) => (<span>hello {name}</span>))
```

**Comment by jamiewinder** [comment]
* `observer`:

```typescript
const App = observable(({ name }) => (<span>hello {name}</span>)```

**Comment by shkrishms** [comment]
Hi, 
I would like to know if using a stateless component has any optimizations when used with observer? Mobx is managing state. So , if I use stateless component with observer, it still tracks state in some form right? 
So what is better

@observer
export class SomeComponent extends React.Component<{ value: string }, {}> {
    public render() {
        return (
            <p >this.props.value}</p>
        );
    }
}

OR

export const widgetSummaryLabel = observer(({ labelValue: string }) =>
    <p className="ms-fontSize-s ms-fontWeight-semibold">{}</p>
);

**Comment by kenshero** [comment]
Thank i got it.

**Comment by corysimmons** [comment]
```jsx
import React from 'react'
import { inject, observer } from 'mobx-react'

const Vegetable = () => (
  <h1>{this.props.FruitStore.favorite}</h1>
)

export default inject('FruitStore')(observer(Vegetable))
```

**Comment by radum** [comment]
This will not work if we use Hooks inside of our functions. Is there an workaround that I do not know of?

**Comment by mweststrate** [comment]
Please don't comment on old issues but open new ones instead

Op do 30 mei 2019 12:53 schreef Radu Micu <notifications@github.com>:

**Comment by janniks** [comment]
There's a new way to do this @corysimmons - posting here in case anybody finds this thread:
🔗 [`mobx-react` official migration to hooks guide](https://mobx-react.js.org/recipes-migration)
