### ISSUE TITLE
Firebase to MobX without pain

### ISSUE THREAD

**Issue by rasdaniil** [mobxjs/mobx#856]
Hi guys

I've just published an npm module **mobase**.

docs: https://rasdaniil.gitbooks.io/mobase/content/
npm: https://www.npmjs.com/package/mobase
github: https://github.com/rasdaniil/mobase

**Comment by mweststrate** [comment]
Tip: add links to the related projects settings in the docs! https://github.com/mobxjs/mobx/blob/gh-pages/docs/faq/related.md
