### ISSUE TITLE
[Mobx 3] How to clear map completely ? 

### ISSUE THREAD

**Issue by melihmucuk** [mobxjs/mobx#862]
I initialized map like below:

```javascript
@observable myMap = observable.map(null, "myMap");
```

If I want to clear myMap at runtime, simply I call `this.myMap.clear()` but it just deletes values, keys are still exist in myMap. How do I clear observable map completely ? 

```json
"dependencies": {
  "mobx": "^3.1.0",
  "mobx-react": "^4.1.0",
  "react": "~15.4.0",
  "react-native": "0.41.2",
}
```

**Comment by mweststrate** [comment]
@melihmucuk the keys should be gone as well after calling clear. How did you detect they are still there? Could you setup a small repro?

**Comment by melihmucuk** [comment]
@mweststrate my store like below

```javascript
class MyStore{
  @observable numbers = observable.map(null, "numbers");

  @action clear(){
    this.numbers.clear();
    console.log("numbers map cleared");

  }

  @action populateNumbers(){
    // some for loops to populate numbers
    // basically this.numbers.set(key, {num: number, excluded: false});
    console.log("this.numbers => ", this.numbers);
  }
}
```

If I call these functions like below:

```javascript
this.populateNumbers();
this.clear();
this.populateNumbers();
```
here is log:

![screen shot 2017-03-02 at 14 18 17](https://cloud.githubusercontent.com/assets/3147488/23505071/259e8454-ff53-11e6-92eb-d97aba073efc.png)

**Comment by mweststrate** [comment]
@melihmucuk this behavior is intended. `_data`  is just an internal data structure, and it is much cheaper to set object values to `undefined` then to actually delete keys. It shouldn't affect the behavior of your app though. In MobX 4 this internal data structure will be replaced by a real map (upping the requirement of the runtime environment) in which case this should be no longer an issue.

**Comment by melihmucuk** [comment]
thanks for info @mweststrate
