### ISSUE TITLE
Is there a better way to extend ObservableMap than this?

### ISSUE THREAD

**Issue by matthewrobb** [mobxjs/mobx#863]
Currently I am doing the below snippet to create a custom extended ObservableMap class. It seems to work exactly how I want but I am curious if there is a better way? Does `deepEnhancer` get exported anywhere?
```javascript
import { ObservableMap, intercept, observable } from 'mobx';
const { enhancer: deepEnhancer } = observable.map();

export class CustomMap extends ObservableMap {
  constructor(initialValues, name) {
    super(undefined, deepEnhancer, name);
    intercept(...);
    this.merge(initialValues);
  }
}
```
Thanks for any help!

**Comment by mweststrate** [comment]
If you pass in `null` or `undefined` as second argument, the map will default to the `deepEnhancer`. In general I recommend to abstain from extending library classes though. Wrapping, composing in a factory think is often more flexible / future proof (this would break if the internal constructor signature changes). 

For example:

```javascript
function createMyCustomMap(values) {
   const res = observable.map()
   res.intercept(...)
   res.merge(values)
   return res
}
```

**Comment by matthewrobb** [comment]
The problem is composition of class hierarchy in a large system. For example I can use the snippet I posted above to very easily model an observable collection type base class that I continue extending for various subclasses throughout.

```javascript
class PeoplCollection extends Collection {
  static ModelClass = Person;
  static idAttribute = 'userId';
}
```
I am able to set up some basic interfaces and extensions and I know there are ways to model this with other patterns but they would be very out of place in my codebase. Perhaps it could be something added as a decorator feature?
```javascript
@observableMap
class Collection {
  static ModelClass = BaseModel;
  static idAttribute = '_uuid';
  ...
}
```
From the little digging I have done it seems there is an internal contract with Map-like in particular that it be `instanceof Map`. I understand you wish to move to an all Proxy based system at a future point; will doing so completely ruin the possibility of supporting custom observable classes like this?

**Comment by mweststrate** [comment]
I don't think it will be easier then what you are already doing in the near future. concerning the proxies: that primarily affects observable objects. For observable maps they might not be used, or be used in such a way that they intercept native `Map`, in which case it would also work for anything that derives from that.
