### ISSUE TITLE
Strip action names in prodution

### ISSUE THREAD

**Issue by iotch** [mobxjs/mobx#865]
Hello. Will be great to have the ability to strip action names in production to reduce the bundle size, as names may be long/lots of. I'm not sure how to do that (Babel plugin?) but will be great feature to have. Thanks!

**Comment by mweststrate** [comment]
If you don't provide action names manually, but use the inferred ones; you might get small action names as a result of the minification of function names. For manually provided action names; mobx cannot do anything for this. You could either rely on process.env, which is cumbersome, e.g. `action(process.env === "production" ? "" : "myname", fn)`, but this is of course quite cumbersome. So creating a babel plugin would probably work the best. You might find some inspiration in this package: https://github.com/mobxjs/babel-plugin-mobx-deep-action

Closing this issue for now as this is something that lives in userland from mobx perspective.
