### ISSUE TITLE
computed doesn't cache?

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx#870]
I'm confused about the `computed` behavior I'm seeing in this basic repro:
https://jsfiddle.net/t9t7ycch/

It looks like the computed expression is reevaluated three times, but I thought `@computed` cached the value and didn't rerun it unless someone observable in the expression changed? Obviously nothing is observable here, but it doesn't seem to make a difference.

Actual output:
```bash
Computing...
5
Computing...
5
Computing...
5
```
Expected output:
```bash
Computing...
5
5
5
```

Edit: Expanded example using an `observable` - https://jsfiddle.net/zue4zgn0/

Actual output:
```bash
Computing...
Value is 1
Computing...
Value is 1
Computing...
Value is 1
Computing...
Value is 2
Computing...
Value is 2
Computing...
Value is 2
```
Expected output:
```bash
Computing...
Value is 1
Value is 1
Value is 1
Computing...
Value is 2
Value is 2
Value is 2
```

**Comment by mattruby** [comment]
Computeds are cached when they are observed.

**Comment by jamiewinder** [comment]
Ah, I think the problem here is that my observer (in my original code) is being disposed and recreated and presumably this brief period of being unobserved causes it to get re-evaluated.
