### ISSUE TITLE
Complete re-render when observable was null

### ISSUE THREAD

**Issue by bsitruk** [mobxjs/mobx#876]
Hi ! I have a quick question about Mobx rendering React component with observer.

I got an **observable array** in my store **initialized to null**. When I **start** my app, I **fetch** some data, and **push** those into my observable.
Then, the **whole app re-renders** (I see it with the Devtools) ? Is it **normal behavior** ?
If I push a new item into my observable after that, only the impacted component re-renders.

Thank you !

**Comment by mweststrate** [comment]
It depends on in which components the array is dereferenced and which components are observers. Hard question to answer without any more information. But ideally the same components that re-render on push should rerender on initializing.

**Comment by bsitruk** [comment]
Thank you. I finally understood how it works.
Here: https://mobx.js.org/best/react.html, the array at the bottom explain exactly the issue.

**Comment by Kielan** [comment]
this is a sign there needs more documentation

**Comment by mweststrate** [comment]
Documentation improvement PRs are always welcome

Op za 10 mrt. 2018 om 18:36 schreef Kielan <notifications@github.com>:
