### ISSUE TITLE
Exposing untrackedStart and untrackedEnd from index

### ISSUE THREAD

**Issue by AviVahl** [mobxjs/mobx#882]
Hi mobx team!

I wonder, would it be possible to export untracked primitives (untrackedStart and untrackedEnd) from mobx's public API?

It would save me and others having to create many function in use cases where each iteration has to be untracked.

Thanks in advance,
Avi

**Comment by mweststrate** [comment]
Note that `untracked(() => block)` is exposed, and actions are by default untracked as well. Could you elaborate why separately exposing untrackedStart / untrackedEnd would be beneficial?

**Comment by AviVahl** [comment]
Because running `untracked(()=> {})` creates a new function.

So if I have to iterate over **many** elements with this type of action:
```js
function action() {
  // code that should be tracked
  ...
  // code that shouldn't be tracked
  ...
  // code that should be tracked 
}
```
I wouldn't have to create an additional function (on every iteration) just to stop the tracking.

This came up from an actual use case I've encountered where I had to turn off tracking in some part (but not all) of the iteration.

**Comment by urugator** [comment]
Can't you create a helper action?
```javascript
@action helper() {
  // an actual MobX action, so it's automatically untracked
}
// Not sure why this function is called "action" ... bit misleading
function action() {
 // code that should be tracked
  ...
 this.helper()
  ...
  // code that should be tracked 
}
```
However, this doesn't feel right. Actions should be about state modifications. Using `action` as a replacement for `untracked` in subscription context (computed/autorun/reaction) is weird. Maybe we should have `untracked` and `runInUntracked`?

**Comment by mweststrate** [comment]
> Because running untracked(()=> {}) creates a new function.

Did you measure what difference that actually makes? I'm reluctant to expose these kind of internal api's / implementation details; as it makes future refactorings hard and increases the api surface

**Comment by AviVahl** [comment]
It's obviously not bad to create a single or several extra functions, and this is indeed the usual use case.

My use case happens in a loop that might do many iterations (hundreds/thousands), so using the usual `untracked` can be more demanding. In addition, my use case happens in the middle of React rendering, so I'd like to have it as optimized as possible (losing the overhead of creating all these functions and GC having to clean them up).

Exposing the start/end functions would cover such cases as well.

**Comment by mweststrate** [comment]
Closing issue. Can be reopened if there is ever a clear proof of the performance benefits of exposing these internal api's.
