### ISSUE TITLE
Computed values aren't cached outside of autorun

### ISSUE THREAD

**Issue by eugene-daragan-codex** [mobxjs/mobx#884]
https://jsfiddle.net/wmcswyum/

When getting computed values outside of autorun, computed functions are reevaluated without any need - evaluation counts (`count1`...`count3`) should be incremented at most once per observable change.
When `console.log` calls are wrapped in `autorun`, number of reevaluation becomes correct.

**Comment by mattruby** [comment]
This is known. Feel free to look over past issues to understand the reason
why.

**Comment by mweststrate** [comment]
...and intendended behavior to avoid manual garbage collection.
