### ISSUE TITLE
Why didn't list rerender when added new item to list?

### ISSUE THREAD

**Issue by blade254353074** [mobxjs/mobx#891]
I have a question:

![](https://raw.githubusercontent.com/blade254353074/mobx-array-example/master/assets/imgs/issue.png)

Here is the repo: [mobx-array-example](https://github.com/blade254353074/mobx-array-example) to reproduce the issue.

I'm wondering if I use mobx in the right way. I checked the gitbook again and again...

**Comment by diondirza** [comment]
Remove `peek()` function in your `State.js`

```
@computed get list () {
    return this.dataSource
  }
```

**Comment by blade254353074** [comment]
Thank you @diondirza !
