### ISSUE TITLE
forceUpdate(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by diondirza** [mobxjs/mobx#892]
I don't know if this related to mobx team scope or not, just want to have help about this. Since this error cause by mobx store so maybe you guys could solve it or give a workaround about this.

About this problem happened on [react-universally](https://github.com/ctrlplusb/react-universally) boilerplate, they have [mobx feature branch](https://github.com/ctrlplusb/react-universally/tree/feature/mobx%40next) that implement store using mobx. Everything seems working fine until you call mobx function in `componentDidMount` and the error will show up.

<img width="1440" alt="screen shot 2017-03-16 at 11 54 40 am" src="https://cloud.githubusercontent.com/assets/10954870/23982319/6835a4cc-0a3f-11e7-828a-5a19c1e5e079.png">

I have made a sample to reproduce this error in [my repo branch](https://github.com/diondirza/react-universally/tree/next-mobx-problem)
you could run it, go to **counter page** and do refresh.

Been couple of days struggling to fix this issue, will appreciate any help about this.

**Comment by vjeranc** [comment]
Yes, it seems to be linked to mobx.

When using `componentWillMount` there are no renders when observable object changes.

When using `componentDidMount` everything seems to work fine.
When using `componentWillUnmount` the `forceUpdate` warning is displayed.

`componentDidMount` and `componentWillUnmount` can have empty implementations.

I'm on react-native.

**Comment by femanso** [comment]
I was getting the same error, in my case I was showing some mobx properties on the Header, but the react-universally example didn't load the header async, I changed the Header code so it would load just like the other async components (like AsyncAbout), using react-async-component.
I also updated every package to the latest.
I don't this this is related to mobx package, or even that is a bug, more like something about how react-universally load components.

**Comment by mweststrate** [comment]
@diondirza is this still something that needs adressing?

**Comment by diondirza** [comment]
@mweststrate After some investigation from react-universally team I think this error occurred because we depends on `react-async-components` and `react-tree-walker` to rehydrate state on the server, please see this [issue](https://github.com/ctrlplusb/react-universally/issues/409) to get more detail about this. As for now it's been handled perfectly with latest patch of `react-tree-walker` so it can work nicely with MobX behaviour. I think this issue can be closed for now.
