### ISSUE TITLE
Chinese localization for mobx.js.org

### ISSUE THREAD

**Issue by SangKa** [mobxjs/mobx#897]
I have a idea:

MobX is so cool!  
So I want to help more developer which come from China to get started with MobX and I translate the MobX docs into Chinese. 
I hope it can be added into the README as a link.
The form can be like this:

### Translations:
  * Chinese or 中文

#### Appendix:
docs: [http://cn.mobx.js.org/](http://cn.mobx.js.org/)
repo: [https://github.com/SangKa/mobx-docs-cn](https://github.com/SangKa/mobx-docs-cn)

**Comment by SangKa** [comment]
Does any body here? @mweststrate

**Comment by mattruby** [comment]
Hello! That sounds like a great addition. Would you create a pull request
adding a link to your docs?

Thanks!

**Comment by SangKa** [comment]
My pleasure and one question:
Which position of the README will be fit for the **Translations** link?

**Comment by mweststrate** [comment]
Closed through #917
