### ISSUE TITLE
ie10 thorw error [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[<component>#0.render()] TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by w514986768** [mobxjs/mobx#900]
ie10 thorw error [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[<component>#0.render()] TypeError: Cannot call a class as a function

**Comment by mweststrate** [comment]
I tried dancing on my desk while glaring at IE 10 to reproduce the issue, but it didn't work out. Creating a new issue offers a template. Please fill it out.
