### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by zsl99a** [mobxjs/mobx#902]
https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/computed-decorator.md#setters-for-computed-values

class Foo {
    @observable length: 2,
    @computed get squared() {
        return this.length * this.length;
    }
    set squared(value) { //this is automatically an action, no annotation necessary
        this.length = Math.sqrt(value);
    }
}

===========================

class Foo {
    @observable length = 2
    @computed get squared() {
        return this.length * this.length;
    }
    set squared(value) { //this is automatically an action, no annotation necessary
        this.length = Math.sqrt(value);
    }
}

**Comment by jamiewinder** [comment]
I think this is just pointing out the typo in the code example? 
```typescript
class Foo {
    @observable length: 2 // <- should be = 2
```

**Comment by andykog** [comment]
Thanks, fixed
