### ISSUE TITLE
React.js do not react on MobX changes

### ISSUE THREAD

**Issue by expdevelop** [mobxjs/mobx#909]
Hi guys, I need your help.

ItemsStore
```js
class ItemsStore {
  @observable data = [];
  storeName = config.items;
}

export default new ItemsStore();
```

Store
```js
import TodoStore from 'stores/TodoStore'
import DeviceStore from 'stores/DeviceStore'
import DomStore from 'stores/DomStore'
import UserStore from 'stores/UserStore'
import ItemsStore from 'stores/ItemsStore'
import FilterStore from 'stores/FilterStore'


export const store = window.store = {
  todo: TodoStore,
  device: DeviceStore,
  dom: DomStore,
  user: UserStore,
  items: ItemsStore,
  filter: FilterStore
};
```

Entry point
```js
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'mobx-react'
import { AppContainer } from 'react-hot-loader'
import { App } from 'containers'
import { store } from 'store'

export const Application = (App) => (
  <AppContainer>
    <Provider {...store}>
      <App />
    </Provider>
  </AppContainer>
);

const AppElement = () => document.getElementById('app');

render(
  Application(App),
  AppElement()
);

if (module.hot) {
  module.hot.accept(() => {
    const App = require('./containers/App/App.js').default;

    render(
      Application(App),
      AppElement()
    );
  });
}
```

Component
```js
import React, { Component } from 'react'
import { observer, inject } from 'mobx-react'
import { ItemTilesBanner } from 'components'
import { devicesBreakpoints } from 'config'


const mapStateToProps = ({device: {width}, items}) => ({
  items, isMobile: width <= devicesBreakpoints.mobile
});

@inject(mapStateToProps) @observer
export default class ItemTilesBannerContainer extends Component {
  componentWillReceiveProps() {
    console.log('ItemTilesBannerContainer will receive props')
  }

  render() {
    const { isMobile, items: {data} } = this.props;
    return <ItemTilesBanner data={data} isMobile={isMobile}/>
  }
}
```

Trying to change the store
![mobx](https://cloud.githubusercontent.com/assets/11634956/24390154/c7c69f64-13a8-11e7-9f70-b755f21a9156.png)

So the data was updated, props of the component too (if I call forceUpdate data will be displayed), but there was no reaction on it (as you see my message from `componentWillReceiveProps` have not displayed).

**Comment by mweststrate** [comment]
Is `ItemTilesBanner` an `observer`?

**Comment by expdevelop** [comment]
@mweststrate yeah, I think so -

```js
@observer
export default class ItemTilesBanner extends Component {
...
}
```

**Comment by acopalipsis** [comment]
Too bad that wrap in the observer to the place where the actual data is used, but not where I want. It is abnormal and this will be the first reason for the unpopularity of mobx. The second reason is performance. Performance ten times worse than redux which is all the app re assemble.

**Comment by lavrton** [comment]
> Performance ten times worse than redux

Proof? I just can not image about this case. I made many performance tests with React. Using mobx was all times super-duper performant.

**Comment by acopalipsis** [comment]
@lavrton an example of a complex and there is no time to repeat it. If You have a fictional example, it is possible the test was not written correctly. I have an update on the drag and I clearly see how creepy mobx slow moving.for redux, which I'm not very fond of, and, to my surprise this was not.

**Comment by expdevelop** [comment]
@lavrton bullshit. We don't think so. In some projects redux lose his performance - in some - mobx. Everything should be used by your needs. In the project mobx works as well.

So, any solution for my problem? Should I remove the container and send the data directly to the component?

**Comment by andykog** [comment]
@expdevelop, could you create some jsfiddle that reproduces the problem. From what you posted seems that `ItemTilesBanner` should be updated correctly. (My be useful to start with: https://jsfiddle.net/Sl1v3r/8hngn2tn/)

**Comment by mweststrate** [comment]
@expdevelop I noticed you are using react-hot-loader. Does turning it of change anything? There are quite some known problems with decorators and RHL.

**Comment by benjamingr** [comment]
Hi @acopalipsis @expdevelop. Communication through the MobX GitHub must be constructive and never resort to personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct. In any other open source project I'm a collaborator of would not be nearly as nice as Michel here. In Node, the issue would definitely be locked at this point.


You have provided non-complete code which we can't test or run for a bug you have reported and then proceeded to thumbs-down the library's author @mweststrate. Then you proceeded to make unsubstantiated performance claims without a benchmark and complain about the response you've been getting. (I'm yet to see a single benchmark in which MobX doesn't win - but I'm ready to learn).

MobX data works with or without a container. I've tried to reproduce your example based on https://github.com/Mosho1/react-mobx-boilerplate and have been unsuccessful in getting it to not update.

If you have a bug - please create a [Minimal Correct and Verifiable Example](https://stackoverflow.com/help/mcve) which we can use to debug your issue.

**Comment by benjamingr** [comment]
In order to prevent these confusions in the future, I have added (with @mweststrate 's blessing) a CoC at https://github.com/mobxjs/mobx/blob/master/CODE_OF_CONDUCT.md

**Comment by expdevelop** [comment]
Thanks for everything guys. 

I've solved my problem by removing any containers from the project.
