### ISSUE TITLE
 Is the document incorrect?

### ISSUE THREAD

**Issue by dive2Pro** [mobxjs/mobx#915]
I have a Question: 
     I  am reading the document. and I found the @observable chapter . It say :
```javascript 
const line = new OrderLine();
console.log("price" in line); // true
console.log(line.hasOwnProperty("price")); // false, the price _property_ is defined on the class, although the value will be stored per instance.
```

so i run it in the jsbin and I got this . 
 ```javascript
console.log("price" in line); // true
console.log(line.hasOwnProperty("price")); // true
```
Did i miss something ?

**Comment by andykog** [comment]
@dive2Pro, you right, I think, there is mistake. All the properties are being initialized on the instance lazily as soon as you access any of them. Made a PR #924
