### ISSUE TITLE
create lazy observables

### ISSUE THREAD

**Issue by syvuilliot** [mobxjs/mobx#92]
I'm in love with mobservable and its approach to simple reactive programming with implicit subscription/unsubscription management.
I'm currently experimenting using it for auto subscribing/unsubscribing from remote data sources based on rendered components : newly rendered components create subscriptions for what matters (or reuse already created subscriptions) and when a subscription is no more in use, it is automatically disposed. 

So I need a way to create an observable on demand (that's ok) but also to know when it is not needed anymore in order to unsubcribe from remote source and forget about it.
I currently use the "onCleanup" of createTransformer and it works but it doesn't seem to be the way to go.
I think I would prefer something like the following:
```javascript
var observable = createObservable((pushValue, onCleanup) => {  
  dataSource.addEventListener('change', pushValue)
  onCleanup(dataSource.removeEventListener.bind(dataSource, 'change', pushValue)
})
```

What do you think about it ?

Thanks for your great great work at making a consitent, glitch free, transactionnal, transparent, reactive data graph implementation. (I tried on my own but was far from your result)

Regards 

Sylvain

**Comment by mweststrate** [comment]
Hi Sylvain,

That's a cool thing to work on! Thought of it but never was able to find the time :) There is a branch feature/2 in the repo which is the current development branch where I am rewriting the core algorithm to be more accessible etc. Anyway, it introduces atoms which would fit in perfectly for this I think. 

So a DataSourceAtom might look like this

```
import {reportObserved} from "./observable";
import {reportAtomChanged} from "./atom";
// ^ i just realize those aren't in the public api yet, feel free to clone the repo add them for now, or I'll try to add those later today using some convenience method

class DataSourceAtom {
    name = "some descriptive name for debugging";
    isDirty = false;
    observers = [];

    constructor(dataSource) {
         this.dataSource = dataSource;
         this.onBecomeObserved();
    }

    onBecomeUnobserved() {
        // dispose code here
        this.dataSource.removeEventListener.bind(dataSource, 'change', pushValue
    }

   onBecomeObserved() {
        // will be called if you recycle your atoms for later use
        dataSource.addEventListener('change', value => this.setValue(value))
   }

   setValue(newValue) {
        // store the new value so that getValue can return it
        reportAtomChanged(this);
        // as a result all observers of this atom will re-evaluate
   }

    getValue() {
        reportObserved(this); // for dependency detection
        // return the value
    }
}  

// This could now be used as
var myDataSource = new DataSourceAtom(someDataSource);

autorun(() => console.log(myDataSource.getValue());
``` 

I think it would be benificial if add an `createAtom(onBecomeObserved, onBecomeUnobserved)` call that returns an object that has the method `atom.reportObserved()`, `atom.reportChanged()`

Might sound a bit vague, but if you think this direction would help I'll work it out

**Comment by mweststrate** [comment]
Eh wait, I'm with my head to much into this atom thing. You can already do this in mobservable 1; although it is slightly more verbose, basically you need to use a computed observable because it has a `onceSleep` method.

So your createObservable could be like this:

```javascript

function createReactiveDatasource(datasource) {
   var observableValue = observable(undefined); // the value holder
   var computedObservable = observable(() => observableValue()); // just return the value
   var pushValue = value => observableValue(value); 
   computedObservable.onceSleep(() => {
      onCleanup(dataSource.removeEventListener.bind(dataSource, 'change', pushValue)
   }
   dataSource.addEventListener('change', pushValue)
   return computedObservable;
}
```
That should be it. I think btw you can skip `pushValue` and directly pass `observableValue` as callback, since that is a getter/setter function anyway.

**Comment by syvuilliot** [comment]
Thanks a lot for your answer.

Cool to see you are working for an even better core algo and this notion of atom for extending it easily.
For now I made an implementation for mobservable 1.
I tried to follow the upcomming API so it can help upgrading to the new version and hide the implementation details such as 'onceSleep' which is not directly on the computedObservable but on '$mobservable'.

So for those it can help, here it is:
````javascript
import { observable, asReference } from 'mobservable'

export default class Atom {
  constructor (initValue) {
    var obs = this._obs = observable(asReference(initValue))
    this._view = observable(() => obs())
  }
  onBecomeUnobserved (cb) {
    return this._view.$mobservable.onceSleep(cb)
  }
  getValue () {
    return this._view()
  }
  setValue (val) {
    this._obs(val)
  }
  patchValue (patch) { // only first level
    this._obs(Object.assign({}, this._obs(), patch))
  }
}
````

Note: I use 'asReference' since I need to store plain object as value and observe it as a whole (and not each prop individually)... that was the trickier thing but help me to better understand mobservable

Really appreciated your help
Thank you

**Comment by mweststrate** [comment]
`MobX` 2 has been released, see the docs for how to use atoms to create reactive data sources: http://mobxjs.github.io/mobx/refguide/extending.html
