### ISSUE TITLE
Idea: @observable.immutable

### ISSUE THREAD

**Issue by andykog** [mobxjs/mobx#925]
We often use `observable.ref` for data that is assumed to stay immutable, i.e. some config recieved via http that should change only when new config is recieved.
In that scenario it might be convenient to have something like `@observable.immutable` that works just the same as `@observable.ref` but applies `Object.freeze()` recursively to it's value, so nobody can mess around with the data stored inside.

**Comment by mweststrate** [comment]
Sounds like a cool idea! One concern, wouldn't the following, the reference itself still being mutable, look confusing for the unaware reader?

```javascript
class User {
  @observable.immutable address;
}

const me =  new User()
me.address = { stuff } // perfectly ok
```

**Comment by urugator** [comment]
Seems a bit out of Mobx scope maybe? Was thinking about `@observable.ref @immutable`, but I see it's not easily doable...? Maybe we should investigate if we can't somewhow allow an implementation of such decorator, which could intercept MobX getter/setter. Maybe exposing some internals or decorator factory?
 
For some reason I am a bit uncomfortable that freezing happens during set operation and not on object creation...guess it might be fine on private fields, but imagine an API documented like:
*Sets address and makes address immutable.*
If address is not copied, but passed by reference, it's address concern to be immutable, isn't it? Isn't such side effect confusing? Also notice that we went away from messing with setted value during autoconversion, which was confusing for some users (coincidentally an immutable user if I remember right).

**Comment by benjamingr** [comment]
I think this is out of scope, and can be written as a composition. 

Moreover, with TypeScript you can just use a `readonly` decorator which would not actually `Object.freeze` the object but enforce that properties are readonly (using keyof).

**Comment by andykog** [comment]
Thanks for feedback! Maybe this is really out of scope. Closing this issue, though, it still feels like since mobx provides a mechanism to mark data as mutable, opposite could also fit.

> Was thinking about @observable.ref @immutable, but I see it's not easily doable...?
@urugator thats seems to be quite easily done:
```js
function deepFreeze(obj) {
  Object.getOwnPropertyNames(obj).forEach((name) => {
    const prop = obj[name];
    if (typeof prop == 'object' && prop !== null)
      deepFreeze(prop);
  });
  return Object.freeze(obj);
}

function immutable(target, key, descriptor) {
  const { configurable, enumerable, initializer, get, set } = descriptor;
  if (initializer) {
    const value = deepFreeze(initializer.call(this));
    return { configurable, enumerable, value };
  }
  if (get) {
    deepFreeze(get.call(target));
    return descriptor;
  }
  console.warn(`Can\'t apply @immutable for '${key}'`);
  return descriptor;
}
``` 
... works like this `@observable.ref @immutable = {}` or `@immutable @observable.ref`. Or you were talking about some typescript hassles?

> guess it might be fine on private fields, but imagine an API documented like: Sets address and makes address immutable
Yeh, maybe it'd have to create deep copy like `@observable a = {}` does.

> with TypeScript you can just use a readonly decorator which would not actually Object.freeze the object but enforce that properties are readonly
@benjamingr, I haven't been used typescript 2.0 much, but doesn't `readonly` affect only reference? Can't find any info on how to apply it on the value (preferably deeply).

**Comment by benjamingr** [comment]
@andykog with 2.1 you have `keyof` and a `Readonly<T>` type that has the same keys as T only readonly (recursively). It's pretty neat.

**Comment by urugator** [comment]
> Or you were talking about some typescript hassles?

Nah, I just had a weak moment I quess :) However doesn't that freeze only the initial value? Or maybe that was the intention?
Nevertheless something like `descriptor.set = val => set(deepFreeze(val));` should do the trick as well I hope (when ordered like `@immutable @observable.ref`)...
