### ISSUE TITLE
Is @observable compatible with other functions/decorators that introduce getters?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [mobxjs/mobx#926]
I'm currently trying to integrate InverisfyJS into my MobX application. However, I've noticed some weird behavior that I cannot fully explain.

```
import React, {Component} from 'react';
import {observable} from 'mobx';
import {observer} from 'mobx-react';
import { container, lazyInject } from '~/container';
import {Seb} from '~/data/Seb';
import {Bas} from '~/data/Bas';

@observer
class Test extends Component {
    @observable
    seb;

    @observable
    bas = { bas : 'bas'};

    tablica = [1,2,3,4,5];

    constructor(props) {
        super(props);
        var self = this;
        setTimeout(function() {
            self.seb.seb = 'changeseb';
            self.bas.bas = 'changebas';
        }, 3000);
    }

  render() {
    return (
      <div>
          <div>{this.seb.seb}</div>
          <div>{this.bas.bas}</div>
      </div>
    )
  }
}

lazyInject(Seb.name)(Test.prototype, 'seb');

export default Test;

//

Seb.js

import {injectable} from 'inversify';
import {observable} from 'mobx';

@injectable()
export class Seb {

    @observable
    seb = "seb";

}

// container

import {Container, ContainerModule} from 'inversify';
import getDecorators from 'inversify-inject-decorators';
import {Seb} from '~/data/Seb';

function configureContainer() {
    var container = new Container();

    let models = new ContainerModule(function(bind, unbind, isBound, rebind) {
        bind(Seb.name).to(Seb).inSingletonScope();
    });
	
    container.load(models);

    return container;
}

let container = configureContainer();
let {lazyInject, lazyInjectNamed, lazyInjectTagged, lazyMultiInject} = getDecorators(container);
export { container, lazyInject, lazyInjectNamed, lazyInjectTagged, lazyMultiInject };
```

The timeout complains that self.seb is undefined at that moment, even though it initially renders its value. What's weird - if I remove the other @observable reference for another property (bas), it works fine. This makes me believe there are some conflicts on higher level?

**Comment by mweststrate** [comment]
I'm pretty sure that `lazyInject(Seb.name)(Test.prototype, 'seb');` will collide with `@observable indeed`, as both will probably overwrite the property on the prototype / instance. In general the `@observable` decorator cannot be combined with other decorators. 

There is too much code above to really understand what is happening, but introducing the observability after injection (using `extendObservable`) or using a react dedicated DI mechanism like `Provider` +`inject` might help.

**Comment by sebastian-zarzycki-es** [comment]
Yeah, that's what I thought, just needed a confirmation. That's a bit unfortunate, but I understand  the reasons and it's relatively easy to work around, so no big issue there. Thanks.
