### ISSUE TITLE
Accept 3rd arguments for findIndex() like find()?

### ISSUE THREAD

**Issue by leader22** [mobxjs/mobx#934]
I have a*: 3. [x] Idea:
  * [x] Are you willing to (attempt) a PR yourself?
- - - 

I've just found about `ObservableArray`.

- `#find()` accepts to call with additional arguments `fromIndex`
- but `#findIndex()` doesn't (passed argument is ignored)

Is there any reasons not implement this?
If you don't mind, I would send a PR ;)

**Comment by mweststrate** [comment]
PR is welcome!

**Comment by leader22** [comment]
Ok, thanks!
I'll send a 2 PRs later.

- 1. for source(to `master`)
- 2. for docs(to `gh-pages`)

**Comment by leader22** [comment]
@mweststrate 

Sorry to forget notifying here.
Please check 2 PRs above 🙏

**Comment by mweststrate** [comment]
Released as 3.1.10. Sorry for the delay!
