### ISSUE TITLE
when I use mobx.useStrict(true) and @computed return observable throw error

### ISSUE THREAD

**Issue by ckken** [mobxjs/mobx#937]
```
import mobx, {observable, computed, action} from 'utils/mobx'
export default class {
  @observable route = {}

  constructor() {
    mobx.autorun(() => {
      console.log(this.GetRouteString)
    })
  }

  @computed get GetRouteString() {
    return JSON.stringify(this.route)
  }

  @action InitRoute(options) {
    this.route = options
  }
}
```
Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: default_1@10.todos

**Comment by mweststrate** [comment]
I don't see todos in your code smo[[et. Please provide more complete code snippets or a reprodution in a fiddle like jsfiddle.net/mweststrate/wv3yopo0/

**Comment by ckken** [comment]
```
constructor() {
    mobx.autorun(() => {
      // console.log(this.GetRouteString) when I dont console, it work
    })
  }
```

**Comment by mweststrate** [comment]
Doesn't throw for me: http://jsfiddle.net/mweststrate/kwp9jqfm/.

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction
