### ISSUE TITLE
The properties decorator with @observable are defined on instance In Typescript

### ISSUE THREAD

**Issue by ElvisKang** [mobxjs/mobx#942]
Env:
 typescript => 2.2.2
 awesome-typescript-loader => 3.1.2
 webpack => 2.2.1
 mobx => 3.1.8

The Codes of [Doc(observable-decorator)](https://mobx.js.org/refguide/observable-decorator.html)

 `console.log(line.hasOwnProperty("price")); `

shows **`true`** instead of **`false`** 

Here is my [test codes](https://jsfiddle.net/elviskang/z8pp8tzr/)

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx/pull/924
