### ISSUE TITLE
Custom comparator for reactions

### ISSUE THREAD

**Issue by yixunx** [mobxjs/mobx#943]
I have a*:

1. [x] Question: 
I am using some objects generated by Scala.js as a field in the `data` object in a `reaction`. The Scala.js objects contain circular references, causing `deepequal` to fail. Is it possible to pass a custom comparator to replace `deepequal`, or is there any way to achieve something similar in effect?

**Comment by jamiewinder** [comment]
I asked something much the same in #802. It's not possible at the moment, but @mweststrate has indicated he'd be happy with a custom comparator being an option. If I manage to claw some free time from somewhere, I'll give it a go.

**Comment by mweststrate** [comment]
Version 3.2.1 added support for custom equality checks. Thanks @jamiewinder!
