### ISSUE TITLE
[Feature] Global suspend/resume function for scheduled reactions

### ISSUE THREAD

**Issue by jeremyong** [mobxjs/mobx#948]
3. [x] Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [x] Are you willing to (attempt) a PR yourself?
 
I'm curious if this facility already exists but it would be very nice to have an easily facility for globally suspending and resuming the execution of queued scheduled reactions stored on the global state.

An obvious use case is to prevent rendering during sensitive transitions or in other performance critical settings where the JS thread is under pressure. In other cases, a user may want to defer rendering while something is happening on the screen for example.

The 5 second implementation I came up with was to set a flag and queue things up on a secondary queue and do a swap+runReactions after things are resumed again, but I'm open to suggestions.

**Comment by jeremyong** [comment]
I have a working implementation but don't want to go through the motions of finalizing it with documentation and all unless there's interest or some display of intent to merge it someday. For now, I'll leave this open however so it's searchable for people perusing.

**Comment by mweststrate** [comment]
> An obvious use case is to prevent rendering during sensitive transitions or in other performance critical settings where the JS thread is under pressure. In other cases, a user may want to defer rendering while something is happening on the screen for example.

I don't see a real point in this, this is willingly introducing a stale; hanging UI. If you don't want to rerender, then don't modify the data that is used in the UI, but batch pending modifications until you actually want to  apply them?

If you properly use actions; reactions should not interfere with CPU intensive functions, unless a lot of async processes are used in this process. Which sounds actually like a fine approach to me, as there is often not much stuff more critical then actually updating the UI, as that prevents a lagging experience?

**Comment by jeremyong** [comment]
A feature that indicates why this is useful is the InteractionManager from react native which defers anything from happening in the passed closure until after existing onscreen animations are finished. Let's suppose you are in the middle of animating a screen into the foreground. At the same time, your client receives a network event which causes the screen being animated to change data. If the rerender takes anything approaching 10ms or more, you've started to drop frames in your animation, making things feel non-native. Internally, we've discussed things like adding a `priority` modifier to an observable (i.e. `observable.critical`) which would bypass a global suspend/resume by putting reactions spawned from it on a separate queue. Either way, I think having some sort of flow control is not a bad thing. In other words, your observation about this "willingly introducing a stale; [sic] hanging UI" is absolutely what we want in this case.

**Comment by urugator** [comment]
> InteractionManager from react native which defers anything from happening in the passed closure until after existing onscreen animations are finished.

Isn't InteractionManager actually closer to what @mweststrate suggested? That is defering the state updates instead of reactions:
```javascript
// instead of calling action directly like:
action()
// let's have an "InteractionManager" which represents our performance critical operation (animation, ...)
// and defer the action call, therefore the state changes and therefore the reactions
InteractionManager.defer(action);
// the action is queued and called when performant operations is finished (or not under pressure)
```
This also seems like a better solution, because you can actually controll which "reactions" to defer.

**Comment by jeremyong** [comment]
It's what I have tried and it simply not a good answer except in very simplistic situations. Stores get modified from all sorts of sources (network activity, reads from disk, etc). Wrapping literally every potentially expensive observable modification via the InteractionManager is untenable.

I'm really not sure I understand the resistance to providing some sort of flow control but like I said, the original PR has been closed and I am doing things in "closed" fashion since there isn't much external interest.

**Comment by urugator** [comment]
> I'm really not sure I understand the resistance

I am not a maintainer, but I wouldn't call it resistence. The issue is still open and therefore discussion is possible.... Any contribution effort is surely highly appreciated. I think there are just doubts whether suspending (all) reactions is the right way to handle this.  
 
As I see it, the first problem is suspending **all** reactions. Not sure if **disabling** flow altogether can be considered a flow **control**.
The reactions may not be used only for single task like updating UI, therefore some assumptions about the system would have to be made.
My first idea to solve this - reactions have a name, let me specify which reactions to suspend: `mobx.suspendReactions("*.render()")` would suspend all components wrapped in `observer`.
I think it would make a bit more sense than the `priority` modifier, because it's easier to anticipate that some reaction is slow/fast, rather than anticipating that some observable modification leads to a slow/fast reaction.
In both cases I think there is a problem with ensuring state consistency. If the reactions are used to keep multiple parts of the system in sync, and you delay some of the updates, than the updates are recieved in different order and you're potentially in trouble...or not?

**Comment by jeremyong** [comment]
My experience has been that there is no worry about consistency because reaction scheduling should be non-deterministic from the perspective of the user anyways, so if they are relying on some sort of ordering the code is likely already broken. Pausing and resuming is most certainly flow control. Suspending/resuming based on name filtering/regex is likely prone to perf problems in systems where a large number of reactions are in flight. As far as priority goes, the choice to attach it to an observable is because what you choose to gate is not based on what is fast or slow, but what is necessary or unnecessary.

**Comment by urugator** [comment]
> filtering/regex to perf problems

yea, I can imagine that may be a problem 

> reaction scheduling should be non-deterministic

I somewhere claimed that communication via reactions should be considered asynchronous, so I think you're probably right about this... Still have some weird feeling about it for some reason... What about suspending some reactions inside the same transaction, they were queued? Could it lead to a wierd UI update? Like updating an article text, but not updating the article headline at the same time?

> fast or slow, but what is necessary or unnecessary

But how do you know it's (un)neccessary? It's not the observable which must be updated immediately (you defer reactions not state updates) and you shouldn't need to know, which reactions are observing that observable.
It still seems a bit wierd that you don't mind suspending the performance critical operation by state mutations (which can potentially also take some time), but only their reactions (about which you shouldn't need to know about).     

Another idea:
Add ability to assign `priority` to `reaction` and make make an expensive operation itself a reaction. So the MobX is in control of scheduling reactions based on the assigned priority...

**Comment by mweststrate** [comment]
I agree with @urugator suggestions above, if you don't want your data mutations to interfere with your animations, just don't mutate the data yet. That seems to me a much more straightforward approach which is comprehensible under all circumstances then anything proposed above; even if reactions are scheduled, computed values won't be scheduled and always be evaluated on the first read. So like the state updates themselves, those will still interfere with your animation stuff.

Besides that I think react fiber solves this problem in a much more elegant way than MobX actually could do. MobX simply lacks the domain specific knowledge to support such a feature.

**Comment by mweststrate** [comment]
Btw, not that you can also do the scheduling on the reaction side of thing, so instead of using `@observer`, you could create a HoC that does something like this in it's cDM:

```
componentDidMount() {
   reaction(
       () => mapProps(this.props),
       (props) => {
           this.nextProps = props()
           requestAnimationFrame(() => this.forceUpdate())
       }
   )
}

render() {
    return <wrappedComponent {...this.nextProps}/>
}
```

```
const myComponent = myObserver(user => ({ user.name }))(({ userName }) => <h1>{userName}</h1>)
```

**Comment by adamabeshouse** [comment]
@mwestrate we're running into a use case for this in my work, with mobx-react: What if there is one source of data, with multiple views (React components) using it, but each view is in a different tab, and we don't want a view to rerender if it's not visible (i.e. in a different tab). So it's not an option to simply put off data modification, because we want the view which *is* visible to respond to it. And I don't think it's a good solution to have to duplicate the data for every view and only modify the one you want to change - the views are all drawing from the same source. How would you deal with this?

**Comment by urugator** [comment]
Perhaps `shouldComponentUpdate` with `!isVisibleView && !isShallowEqual`
or (un)subscribe conditionally:
```javascript
if (isVisibleView()) {
  return render();
} else {
  return untracked(() => render())
}
```
