### ISSUE TITLE
Cannot replace `observer` with `inject`

### ISSUE THREAD

**Issue by amorphius** [mobxjs/mobx#957]
I have this warning when using @observer decorator

Mobx observer: Using observer to inject stores is deprecated since 4.0. Use `@inject("store1", "store2") @observer ComponentClass` or `inject("store1", "store2")(observer(componentClass))` instead of `@observer(["store1", "store2"]) ComponentClass`

But when I replace it with `inject` my component does not get updates anymore. Isn't it enough just to replace `@observer(['storeName']` with `@inject('storeName')`?

**Comment by jamiewinder** [comment]
I need to specify both `@inject` and `@observer`, e.g.:
```
@inject("store1")
@observer class MyComponent 
```
