### ISSUE TITLE
Missing an error / warning when using computed value outside a reaction

### ISSUE THREAD

**Issue by adamkleingit** [mobxjs/mobx#961]
Hi,
is there a way to throw out an error / warning if using a computed value outside of a reaction / autorun?
Maybe as an option to useStrict to be backwards compatible?

Is there any reason to allow using computed values outside a reaction? Sounds like this should be a default behaviour

This is a silent issue at the moment that can cause performance issues.
If we use a computed value directly and forget to wrap it with an observer / autorun / reaction - it will work regularly, and we wouldn't know that it's being recalculated over and over again.

  * [X] Idea

**Comment by mweststrate** [comment]
Mobx 4 will introduce `mobx.configure({ warnOnUnsafeComputationReads: true })`
