### ISSUE TITLE
JSFiddle from README doesn't work

### ISSUE THREAD

**Issue by tylercollier** [mobxjs/mobx#963]
I have a*:

2. [x] Issue:

The (JSFiddle linked from the README](https://jsfiddle.net/mweststrate/wv3yopo0/) doesn't work.

  * [x] **Provide error messages including stacktrace**

Upon loading the page, the developer console says:

```
Uncaught SyntaxError: Inline Babel script: Unexpected token (12:4)
  10 | class Todo {
  11 |     id = Math.random();
> 12 |     @observable title;
     |     ^
  13 |     @observable finished = false;
  14 |     constructor(title) {
  15 |         this.title = title;
    at Parser.pp$5.raise (babel.js:17994)
    at Parser.pp.unexpected (babel.js:15337)
    at Parser.pp$1.parseDecorator (babel.js:15515)
    at Parser.pp$1.parseClassBody (babel.js:16017)
    at Parser.pp$1.parseClass (babel.js:15982)
    at Parser.pp$1.parseStatement (babel.js:15419)
    at Parser.parseStatement (babel.js:19333)
    at Parser.pp$1.parseBlockBody (babel.js:15844)
    at Parser.pp$1.parseTopLevel (babel.js:15354)
    at Parser.parse (babel.js:15249)
```

  * [x] Provide as much **relevant code**, or, preferrably **create a reproduction based on this [JSFiddle](https://jsfiddle.net/mweststrate/wv3yopo0/)**: 

This is ironic :-)

  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?

The JSFiddle should compile and run without errors.

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

The mobX versions should be available from the fiddle.
Browser is Chrome for Linux 57.0.2987.133 (64-bit).

**Comment by mweststrate** [comment]
Uh oh, this used to still work a few weeks back. Probably default babel settings of jsfiddle have changed. Will investigate

**Comment by mweststrate** [comment]
Filed issue: https://github.com/jsfiddle/jsfiddle-issues/issues/1015

**Comment by mweststrate** [comment]
JSFiddle just restored support for dcecorators, should be fixed now. Please reopen if it isn't.

**Comment by tylercollier** [comment]
I just checked it out and it works now, thanks!

**Comment by mattruby** [comment]
That's crazy fast!
