### ISSUE TITLE
[Feature] Add a way for MobX to work across different frames

### ISSUE THREAD

**Issue by sndurkin** [mobxjs/mobx#973]
I have an idea: Add a way for MobX to work across different frames.

  * [x] **What problem would it solve for you?**

    I'm working on a large single-page tabbed application that uses an iframe within each tab, and I'd like to use a MobX store within `window.top` that two or more screens within separate iframes share. In other words, modifying data from within one iframe would cause reactions to be fired within the other iframes.

    MobX doesn't appear to work out-of-the-box across iframes, but I was able to get it working by having the iframes all share the same `globalState` object.

  * [x] **Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?**

    I'm not sure how useful the change would be to others (I don't see iframes mentioned in any existing issues in this repo), but I think the change within MobX would be fairly simple. I would add a function similar to `shareGlobalState()` within `src/core/globalstate.ts` that does something like this:

    ```
    export function shareGlobalStateAs(win, globalStateVarName) {
        if(win[globalStateVarName])
            globalState = win[globalStateVarName];
        else
            win[globalStateVarName] = globalState;
    }
    ```

    Example usage:

    ```
    mobx.extras.shareGlobalStateAs(window.top, 'Store' + uniqueStoreId);
    ```

  * [x] **Are you willing to (attempt) a PR yourself?**

    Yes, I would submit a PR once I have everything working.

**Comment by sndurkin** [comment]
I did some additional testing, and IE/Edge throw an error if an iframe containing an observer is destroyed and the reaction fires. To clean those up, something like this inside Reaction's constructor seems to work:

var me = this;
window.addEventListener('unload', function() { me.isDisposed = true });

**Comment by mweststrate** [comment]
PR. is welcome. What we did btw instead in a similar situation, is just have react from the main window render into the iframe. That way you can keep react / mobx / all state within a single window and you circumvent this problem

**Comment by mweststrate** [comment]
Closing for the lack of a volunteer (& demand :wink:)

**Comment by lapidus** [comment]
> What we did btw instead in a similar situation, is just have react from the main window render into the iframe.
@mweststrate: Very appreciated if you could shine some more light on the above. I am trying to have a component within an iframe (on the same domain) share state with the parent to enable a sort of "responsive component playground" where I can tweak state both outside and inside the iframe.

**Comment by makarov-roman** [comment]
I'm trying to do the same. Can u guys provide some tips/example how to share internal state of mobx?
