### ISSUE TITLE
[Issue] Autorun not triggered when setting element transform style to observable or computed property

### ISSUE THREAD

**Issue by robstown** [mobxjs/mobx#978]
I have a*:

2. [x] Issue:
  * [ ] **Provide error messages including stacktrace** ---> NA
  * [x] Provide as much **relevant code**, or, preferrably **create a reproduction based on this [JSFiddle](https://jsfiddle.net/mweststrate/wv3yopo0/)**: 
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

I had code similar to the following, and I noticed the autorun was not triggered:
```
class store {
	domELement;	
	@observable scrollVal = 0;
	constructor(domELement) {
		this.domELement = domELement;
		this.scrollDispose = autorun(()=>{ 
			this.domELement.style.transform = 'translateX('+this.scrollVal+'px)';
			console.log('autorun');
		});
	}
}
```
I tried removing the string portion to see if it made a difference and it still didn't work.  If, however, I used an intermediate variable it worked:

```
this.scrollDispose = autorun(()=>{ 
	let translation ='translateX('+this.scrollVal+'px)'
	this.domELement.style.transform = translation;
	console.log('autorun');
});

```
It also worked if I used a different element property, like scrollLeft:
```
this.scrollDispose = autorun(()=>{ 
	this.domELement.scrollLeft = this.scrollVal;
	console.log('autorun');
});
```
It originally happened when setting value equal to a computed value, but I verified the same behavior when using an observable. I was using Mobx v3.1.9 with Chrome 57.0.2987.133 (64-bit).

There is an easy work-around, but curious why it wasn't triggered.

**Comment by urugator** [comment]
Can't reproduce:
https://jsfiddle.net/wv3yopo0/1161/

It shoudn't really matter what you do with obtained value, the subscription is performed when the getter is called - `this.scrollVal`.

**Comment by robstown** [comment]
Hmm, thanks.  I'll see if I can reproduce it on a simpler example than my app.  I thought it shouldn't matter, which is why it took me a while to debug and had me scratching my head.

**Comment by robstown** [comment]
It's not repeatable in any simple examples I made either.  I'll close and re-open a different issue if I figure out what happens and it's warranted.  Thanks.

**Comment by richdyang** [comment]
I also found a case when `@observable` dees not work, but `extendObservable(...)` works.
Because my autorun function is a deep nested code, i cannot isolate and let you reproduce
