### ISSUE TITLE
Custom observable types

### ISSUE THREAD

**Issue by jameslk** [mobxjs/mobx#98]
Sometimes it's a little tricky to define everything in a way that is consumable for Mobservable to observe. It would be great if I could specify custom types that expose an event-driven API that defines when the type's value has changed.

For example, take the ES6 Set type. It's an opaque data structure that isn't currently supported by Mobservable. If I could build a wrapper around Set objects that notifies Mobservable when its internal state has changed (by watching calls to the Set's functions that mutate its state), then I could use that type in my application with Mobservable. This goes for any opaque data structure where it's not really known how the internal state is represented but has an API that can be wrapped.

Hopefully this makes sense. If this is already possible, let me know since I couldn't find it in the documentation.

**Comment by mweststrate** [comment]
@jameslk That makes perfect sense. I'm currently in the middle of writing Mobservable 2.0 where these extensions can be made, as it will offer an api to define your own `atom`s (sources of truth) and `reaction`s. See also #92 for example or the `feature/2` branch. I hope to release it in 2 or 3 weeks.

For sets specifically, I recommend to use `mobservable.map()` for now.

**Comment by jameslk** [comment]
@mweststrate Awesome! Yes, the "atoms" are exactly what I was thinking. I was using `Set` as an example for simplicity. I'm trying to find a solution to use with my own [project](https://github.com/jameslk/relatedjs), which is a custom data structure for graph-like data. Hopefully with v2 I can utilize these new features of Mobservable to make the graph data structure observable.

I'm still learning about Mobservable's features, but its been very refreshing. Thanks for the amazing work!

**Comment by mweststrate** [comment]
The [Atom class](https://github.com/mweststrate/mobservable/blob/feature/2/src/core/atom.ts) concept is now available in the feature/2 branch, that should be enough for creating your own state sources. I'll try to add some docs & comments soon.

**Comment by mweststrate** [comment]
For preview the packages `mobservable-react@beta` and `mobservable@beta`  are now available

**Comment by mindreframer** [comment]
@mweststrate it would be great to update the demo to latest packages, maybe it will be fixed then? ;) 

https://github.com/mweststrate/mobservable-reactive2015-demo/issues/1

**Comment by mweststrate** [comment]
Released as part of `MobX@2.0.0`. See the documentation for how to extend `MobX`: http://mobxjs.github.io/mobx/refguide/extending.html

**Comment by mindreframer** [comment]
:+1: great, thx a lot!

**Comment by jameslk** [comment]
Sweet! I'll be testing out 2.0 and these new features. Thanks!
