### ISSUE TITLE
Mobx reaction effect not called

### ISSUE THREAD

**Issue by iandvt** [mobxjs/mobx#982]
I'm trying to introduce an observable singleton pattern in my code base using Mobx, TypeScript, Webpack, and Async. There seems to be an issue with Mobx reaction not calling the effect function while dynamically creating Mobx stores.

I've put together a [repo](https://github.com/iandvt/Mobx-Singleton) that reproduces this problem.

### Repo Setup
npm install
npm run build
node app.js

### Reproduction Steps
node app.js

Reaction Expression Index - false
Reaction Expression StateStoreCollection-undefined - false
Reaction Expression StateStoreCollection-singleton - true
Reaction Effect StateStoreCollection-singleton - true
Reaction Expression Index - true
Reaction Effect Index - true
ViewStore has hasInitialized
Reaction Expression StateStore-undefined - true
StateStoreCollection-singleton has hasInitialized
Index has hasInitialized

The StateStore Expression returns true but the StateStore Effect is not called.

**Comment by mweststrate** [comment]
Sorry, I tried to understand the code, in the sense of understanding what the code is supposed to do. Can you make your example a bit more minimal, pinpoint what code you expect to run, and pinpoint what code you expect to cause that run?

**Comment by iandvt** [comment]
I worked around this issue - thanks for taking a peak though 👍
