### ISSUE TITLE
Observable array should be concat-spreadable

### ISSUE THREAD

**Issue by Zzzen** [mobxjs/mobx#984]
I have a*:

2.  [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide as much **relevant code**, or, preferrably **create a reproduction based on this [JSFiddle](https://jsfiddle.net/mweststrate/wv3yopo0/)**: 
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
  * [x] Are you willing to (attempt) a PR yourself?

MobX version: 3.1.7
Code:
```javascript
    var a2 = mobx.observable([3, 4])
    var result = [1, 2].concat(a2)
```

I expect result to be `[1, 2, 3, 4]`. But it is `[1, 2, ObservableArray]`

**Comment by Zzzen** [comment]
Here is the solution I came up with, hope it helps.
https://github.com/Zzzen/mobx/commit/952f4f32d3decbe56a9e80a9bd0d4f8493e3cbd2

**Comment by spion** [comment]
Unfortunately this will cause unexpected behaviour in older browsers (see #806)

**Comment by mweststrate** [comment]
This is indeed a known limitation until proxies are fully supported. Use `a2.slice()` instead. Also see the docs.

**Comment by vantuan88291** [comment]
0

another way to concat array in mobx:

```
const arr = [...self.data, ...result.data.data.customers]
self.data.replace(arr)
```
