### ISSUE TITLE
how to sync stores

### ISSUE THREAD

**Issue by CodeXtinction** [mobxjs/mobx#991]
hello, i have two stores ui and auth. From auth im doing an promise request and i want to show a spinner while the request is completed then hide it, i do not want to put the ui in the same as auth so how could i call the hideLoading action from ui store in the auth store, thanks im pretty new with mobx.

my component

```
onSubmit(e){
        this.props.ui.showLoading();
        e.preventDefault();
        this.props.auth.Login(this.state);
       // here should hide the spinner but login response is in the auth store
    }
```
ui store
```
import { observable, action } from 'mobx';

class UiStore {

    @observable isLoading = false;

    @action showLoading() {
        this.isLoading = true;
    }

    @action hideLoading() {
        this.isLoading = false;
    }

}

export default new UiStore();
```
auth store
```
import { observable, action } from 'mobx';
import axios from 'axios';

class Auth {
    @observable token = '';
    @observable isLogged = false;

    @action Login(user){

        axios.post('http://localhost/Api/public/api/login', user)
            .then( res => {
               console.log(res);

               ///HERE SHOULD HIDE THE SPINNER
            })
            .catch( error => {  
                console.log(error);
            })
    }

}

export default new Auth();
```

**Comment by urugator** [comment]
Return the promise from `Login` method and simply chain another callback:
```javascript
onSubmit(e){
  this.props.ui.showLoading();
  e.preventDefault();
  this.props.auth.Login(this.state)
    .then(() => this.props.ui.hideLoading());
}
```
Another way would be to make promise status observable for example with `fromPromise` (alternatively set some `this.loggingFinished = true`)  and introduce reaction (`when`).

**Comment by CodeXtinction** [comment]
@urugator  i resolve the promise on Login method i assign token to token observable, how can return a promise after  that?, thanks i really apreciate it

**Comment by CodeXtinction** [comment]
@urugator  so from store i just return the post request right?

```
@action Login(user){
        return axios.post('http://localhost/Api/public/api/login', user)
}
```

**Comment by urugator** [comment]
Yea, but be careful about that `catch` callback, it swallows the error. Consider rethrowing it or returning some status object.

**Comment by CodeXtinction** [comment]
@urugator  yep im returning error from the api, and how if i want to resolve the promise in the store, and still execute a .then in the component ?

**Comment by urugator** [comment]
Oh, I misunderstood ... keep the `.then` in `Login` as before, just return it:

```javascript
  @action Login(user){
        return axios.post('http://localhost/Api/public/api/login', user)
            .then( res => {
               console.log(res);

               ///HERE SHOULD HIDE THE SPINNER
            })
            .catch( error => {  
                console.log(error);
            })
    }
```

**Comment by CodeXtinction** [comment]
@urugator  thats pretty much better, thanks :D

**Comment by mweststrate** [comment]
Question seems answered. Closing. In future: please close questions yourself if issues are resolved!
