### ISSUE TITLE
extendObservable is firing `observe` multiple times

### ISSUE THREAD

**Issue by refaelos** [mobxjs/mobx#993]
Hey,

I'm calling `extendObservable` inside an @action and `observe` the same extended observable on another function. It looks something like this:

```
extendObservable(installRange, {
      startDate: <some date>,
      endDate  : <some date>
    });
```

```
const o = observe(installRange, action(() => {
  console.log('installRange changed');
}));
```

The problem: the observe callback is called twice! Why?

**Comment by urugator** [comment]
Because two observable fields were added: `startDate` and `endDate`. You could see that if you would print the event passed to `observe` callback. From doc:

> Note that transaction does not affect the working of the observe method(s). This means that even inside a transaction observe will fire its listeners for each mutation. Hence autorun is usually a more powerful and declarative alternative to observe.

>observe reacts to mutations, when they are being made, while reactions like autorun or reaction react to new values when they become available. In many cases the latter is sufficient

**Comment by refaelos** [comment]
@urugator good stuff! thanks.
