### ISSUE TITLE
How to handle Ajax data with Mobx?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx#994]
I am playing around with mobx and wondering how do format data from the server to be match with the mobx classes? This of course would be done through an ajax request to grab the data.

```
      class Student {
                @observable firstName
                @observable lastName
                @observable classes = []
    
                constructor(firstName, lastName, classes) {
                    this.firstName = firstName;
                    this.lastName = lastName;
                    this.classes = classes;
                }
            }
    
         class Classes {
                @observable name
                @observable number
    
                constructor(name, number) {
                    this.name= name;
                    this.number= number;
                }
            }
    
    	class Container {
    		@observable students = [];
    	}

```
I am using SalesForce, so my backend is Java like, and I wondering do I have to make it into json? then on the client side build the classes with the data?

Or is there a more stream lined way I can do this?

**Comment by krnaveen14** [comment]
[serializr](https://github.com/mobxjs/serializr#serializr) can used to serialize from / deserialize to ES6 classes. 

We've been using it in our MobX + TypeScript project for quite some time.

**Comment by chobo2** [comment]
So you saying I need to return json back from my server and try to make it into an object?

**Comment by krnaveen14** [comment]
> So you saying I need to return json back from my server and try to make it into an object?

Yup..!

**Comment by jamiewinder** [comment]
This is how I do it:

```javascript
class Student {
    static fromData(data) {
        return new Student(data.firstName, data.lastName);
    }
    constructor(firstName, lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    @observable firstName;
    @observable lastName;
}

class Students {
    @computed get students() {
        return fromPromise(fetch('/students').then(
            (data) => data.map(Student.fromData)
        );
    }
}
```
But it isn't without its critics. 

Mapping a JSON-parsed object to a class is fairly straightforward for simple models and arrays of models.

Your `students` computed property will look like [this](https://github.com/mobxjs/mobx-utils#frompromise), so not an array of students, but what I think of as an 'asynchronous value' which will eventually update to have a value of the array of students. Your components would need to handle the possibility that this value hasn't resolved or errored during resolution.

**Comment by mweststrate** [comment]
Question seems answered. Closing. Feel free to reopen if it isn't

**Comment by naomipol** [comment]
A one line solution for creating a class object from a json-parsed object:

`Object.assign(new Student, jsonStudent)`

It helps for cases classes with a lot of properties...
