### ISSUE TITLE
`delete` does not delete keys of observable arrays

### ISSUE THREAD

**Issue by hearnden** [mobxjs/mobx#995]
An observable array doesn't allow keys to be deleted, which is inconsistent with observable objects, which do allow keys to be deleted.

1. [X] Issue:
  * [X] Provide as much **relevant code**
    ```js
    const arr = observable(['x']);
    delete arr[0];
    console.log(arr[0]);
    ```
    Example: https://jsfiddle.net/opjo6tyL/1/
  * [X] Did you check this issue wasn't filed before?
  * [X] Elaborate on your issue. What behavior did you expect?
    If `arr` is an observable array, then
    ```js
    delete arr[i];
    ```
    should delete the key `i`, and `i in arr`  should be false after the deletion.
  * [X] State the versions of MobX and relevant libraries. Which browser / node / ... version?
    MobX 3.1.9
    Node 7.10.0

**Comment by hearnden** [comment]
Related: https://github.com/mobxjs/mobx/issues/822

**Comment by mweststrate** [comment]
Deleting is not supported for neither observable objects or arrays. Even though the delete for an object appears to work, the backing observable still lives on and is tracked by whatever it was tracking it already, and assigning a new value later on might not be picked up. 

If the lack of support for `delete` is not clear from the docs feel free to add it!

**Comment by BrendanAnnable** [comment]
@mweststrate Now that observable arrays are backed by ES6 proxies, could we add a [`deleteProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/deleteProperty) trap here such that the `delete` operator is supported?

https://github.com/mobxjs/mobx/blob/805c02d685ba2993b55f0fa5d27573b0dfdfeba1/src/types/observablearray.ts#L81-L115

**Comment by mweststrate** [comment]
What is your use case for using delete on an array?

Op vr 12 apr. 2019 07:30 schreef Brendan Annable <notifications@github.com>:
