### ISSUE TITLE
What is the correct way to pass Store down to children?

### ISSUE THREAD

**Issue by cbll** [mobxjs/mobx#997]
Welcome to MobX. Please provide as much relevant information as possible!
I have a*:
1. [x ] Question: 

I got my Store working somewhat as intended, but I still have a few questions.

Using it with React, I have a `<Main />` component which is a container for some children. This Main component is what is rendered to to the dom with `ReactDOM`.

My question is: Should I initialize a new store in each of the children of  `<Main />`? Or should I pass it as a prop and access it with` this.props.store`?

My issue is that the latter somewhat ends up with the tree-architecture that you are forced to with plain React instead. At least, it seems so for me.

However, it could be solved by individually creating a store in new component and using it from, there, such as:

```
import Store from './store/stores.js';
const store = new Store();
```

Here's the question: Does this create its "own" store? I mean, it creates the class from new, meaning if the above store is created in another React component, they aren't "in sync"?

Is this correctly understood? If so, how do you solve wanting to pass data between children/grandchildren with React+MobX, without having these prop-chains going back and forth. It is even possible?

Thanks in advance for your appreciated patience with me :P

**Comment by mattruby** [comment]
See provider and inject in mobx-react

**Comment by cbll** [comment]
Will do! Thanks.

**Comment by cbll** [comment]
@mattruby 

So, I had a look at their example, but I don't really comprehend how it would work in "real life".

If I have a regular arrow function in my Store, and I want to use that function at a grandchild or great-grandchild, how exactly would that enable connecting the component to the store without passing as props?

I get that in 12 lines of Javascript it's easy to comprehend, but in this case with actual real React classes, I don't quite get which should be the Provider, and where to inject it.. When they are even in separate files :)

**Comment by urugator** [comment]
> If I have a regular arrow function in my Store, and I want to use that function at a grandchild or great-grandchild, how exactly would that enable connecting the component to the store without passing as props?

There will be a componet which instantiates the store `this.userStore = new UserStore()`. This component works as a provider of that store for all of it's descendants. As shown in example, wrap the output of this provider component into `<Provider userStore="{this.userStore}">`. Than you can decorate any of the descendants (no matter how deep) of this provider with `@inject("userStare")` making the store automatically present as prop `userStore` in this descendant.

**Comment by cbll** [comment]
Oh, ok. So how would I invoke a function from the store, if not with `this.props`?

**Comment by mattruby** [comment]
You'll still reference they injected store via this.props

**Comment by urugator** [comment]
>  if not with this.props?

I don't understand..? I wrote it will make the `userStore` present as prop, therefore accessible like: `this.props.userStore.function()`
Look ... the react passes `context` object all the way down the component tree.
`Provider` just puts something onto that context with given name, like `this.context.$mobxProvider.userStore = this.userStore`
And `Inject` just takes the things from `context` by name, like:
`this.props.userStore = this.context.$mobxProvider.userStore`;
...so inject will make `userStore` available on props without actually being passed by props, but being passed by `context`

**Comment by cbll** [comment]
I'm a bit confused, so let me elaborate.

Here's a very basic, dumbed-down example if what I want to achieve. How would you change it so I don't have to pass the props through the parent, to invoke the function?

Sorry if it's a stupid question, just trying to wrap my head around everything.




```
// Store
class Store {

    @action exampleFunc = () => {
		console.log("Invoked action!");
    };
}




// Container
import Store from './store';

@observer class Main extends React.Component {
	store = new Store(); // Initialize main store
	render () {

		const store = this.store;

		return (
			<div>
				<Provider store={this.store}
					<Child 1/>
					<Child 2/
					<Child 3/>
				</Provider>
			</div>

		)
	}
}

ReactDOM.render(
    <Main />
,
    document.getElementById('content')
);


// Child example
@observer class Child1 extends React.Component {

	render () {
		return (
			<div>
				<GrandChild 1/>
			</div>
			)
	}
}

// Grandchild example

@observer class Child1 extends React.Component {

	render () {
		return (
			<div>
				<button onClick={this.Examplefunc}> // I want to invoke the exampleFunc here, how would I do that without passing props?
			</div>
			)
	}
}
```

**Comment by urugator** [comment]
Just put the `@inject("store")` before the `@observer class Grandchild` and you can access the store:
`<button onClick={this.props.store.Examplefunc}>`

**Comment by cbll** [comment]
It worked. Thank you so much! Sorry for the trouble, it's a bit tricky to wrap my head around these concepts(relatively new to the ecosystem and such). Cheers :)
